### ISSUE TITLE
Hide taskbar or crop to visible area

### ISSUE THREAD

**Issue by volucris** [mapillary/mapillary_issues#1000]
I took great care that the hood of my car was (exactly) not visible on the preview on a mapping round, but it appears to have been hidden behind the android task bar, so now I just took a few thousand pictures that include the hood of my car :(

Could the app either be made to (optionally) run in fullscreen mode, or images be cropped to the visible area?

**Comment by peterneubauer** [comment]
Yes, better preview that accurately displays the image is on the roadmap - it's not supereasy to adapt to all screen sizes since the screen size not necessarily matches the camera image dimensions. Sorry for the inconvenience!

**Comment by peterneubauer** [comment]
Fixed in the next release - camera aspect ration will be honored by the preview.
