### ISSUE TITLE
new photoes not counted

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1002]
Hi
I dont know if it is a bug or not but I have uploaded many pictures that is not counted in "uploaded images" or in "still processing" but "meters mapped" is increasing and the pictures are shown under activities and on the map

**Comment by gyllen** [comment]
Fixed, thanks for reporting.

**Comment by beer119** [comment]
May I ask what the problem was?

**Comment by gyllen** [comment]
Yes of course. We have transparently been switching our datbase and processing engine in the backend (elasticsearch plus storm). We failed to update address to new elasticsearch for profile search.
