### ISSUE TITLE
allow to manually enter compass angle

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1003]
similar to issue #405, but simpler.
it would be useful to enter compass angle manually for individual images - for example, when a few images have the wrong angle and they all should be changed (but not the whole sequence).
it would be very easy to copypaste angle to them - current +/- buttons remind old games that relied on massive clicking - maybe not as bad as the desert bus, but i rarely fix compass angle now :)

**Comment by gyllen** [comment]
@retro Is this done?

**Comment by nickplesha** [comment]
Image angles can be set in the web editor now.
