### ISSUE TITLE
optimize preview on android app by pre reserving space

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1005]
Right now the thumb nailing process in a sequence is sometimes generating images in between. So the thumbnail overview is changing and getting longer in the calculation process.
You could reserve space for each image with the right size (as you have device-width/3 as the width and 4/3 aspect ratio) and fill the thumbnails afterwards.

**Comment by jesolem** [comment]
Worth a try.

**Comment by peterneubauer** [comment]
True, can try it, thanks @HolgerJeromin !

**Comment by peterneubauer** [comment]
Should be out and done now.

**Comment by HolgerJeromin** [comment]
Before this change it was nearly impossible to review a sequence of more than 30 images on my 5 year old phone. 
This fix made my 160 sequence very easy to review. 

I don't know if the thumb creation is really faster, but it feels much faster now. Related to this change or not. 
Thanks for the latest version!

**Comment by peterneubauer** [comment]
Thanks Holger,
Refactored the app to generate thumbnails and cache them. Glad to hear it
works for you know, feel free to close the issue!
