### ISSUE TITLE
split sequence frequency for walking and riding

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1006]
While riding (bike or car) i want the maximum my device is able to handle (2sec). But while walking this is too much, there i think 4 seconds would be sufficient (related to #247 ).
Changing that on demand resulted in the wrong setting while driving a car.
It would be nice, if you would offer two setting for this.

**Comment by jesolem** [comment]
Android? What version do you have? There should be a special walking mode with auto on Android (not on iOS yet, sorry). Can you update to the latest and check?

**Comment by HolgerJeromin** [comment]
Yes, Android. Perhaps my problem is that I did not understand the walk auto mode. Perhaps changing the settings was not needed.

**Comment by peterneubauer** [comment]
Yup,
sounds like a reasonable request. We will check if we can find a good UX for it. Thanks!

**Comment by HolgerJeromin** [comment]
Not relevant anymore imo
