### ISSUE TITLE
show blur controls in normal browsing

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1007]
clicking to open blur view, waiting for it to load, then returning to browsing... extra steps, extra load on mapillary systems.

instead, it would be better to have a mode that would allow to add/remove blurred areas directly in the browsing view - similar like the traffic sign editing filter

**Comment by de-vries** [comment]
I also had an idea for this. You could load the current blur page in an iframe in a lightbox on top of the map view. this has tree advantages: 
1. you can, by clicking submit, close the light box and be back in the map view without extra clicks and/or page loads. 
2. the image can be bigger. IMO the photo size in the current map view is way to small for blurring. I don't see having to use the zoom function as an improvement over a separate blur page. 
3. you can, if needed, still offer the blur page as a separate page or in a new tab.

**Comment by domdomegg** [comment]
:+1:
Perhaps scaling with the browser window, using %'s for width/height.

**Comment by knikel** [comment]
@richlv, @de-vries, @domdomegg: Blurring is now part of the main viewer, thanks for the feedback!
