### ISSUE TITLE
Change sets and blurs not being registered anymore

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1008]
It looks like change sets and blur requests are not being registered anymore. May 6 was the last time I received any emails about registering my change set or blur requests, and May 7 was the last time any request was approved. (Even the ones that were accepted, were only partially carried out.)

I've been sending in quite a few change requests after that, and I am frustratingly afraid that none of it has been registered, even though I every time get a nice promise that my changes have been submitted and will be reviewed within 24h. I know the last part is not always true, and I am really starting to fear that currently the first part is not true either.

As I have complained about before, the whole approval process is not nearly transparent enough, and leaves a lot of room for uncertainty.

**Comment by pbb72** [comment]
Yesterday (May 17), registration and approval emails have started coming in again. But I'm still waiting for my changes from May 15 (3 days ago) to be approved.

**Comment by richlv** [comment]
have the changes/approvals arrived by now ? i seem to receive emails as expected

**Comment by mprins** [comment]
I've not had change approval messages for months (I've had change requested confirmation messages though)

**Comment by gyllen** [comment]
You should get the emails by now

**Comment by pbb72** [comment]
True, I have been receiving blur confirmation emails again for a long time. Sorry for forgetting about this issue and not closing :smile:

**Comment by mprins** [comment]
I guess change set notifications are still held up with #1367

**Comment by gyllen** [comment]
@mprins Correct, we are working full speed to fix this though.
