### ISSUE TITLE
uploading with python

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1009]
hey..

just installed python on my windows 7.
added the path to python2.7.9 into my environment.
then i added the module exifread (successfully)
but, when i fire up the upload.py , i getting

       from upload import create_dirs, UploadThread, upload_file
ImportError: cannot import name create_dirs

What does it mean ?

Anybody can explain what to do, to get it working ?

Cheers
Thorsten

**Comment by jesolem** [comment]
upload.py is meant to be run from the command line. If you want to write your own script you need to replicate what's in the `if __name__ == '__main__'` section.

It looks like you're trying to run one of the other scripts that use upload.py though. Is that what you're doing? Make sure the folder containing upload.py is in your PYTHONPATH if you're running this from some other path.

**Comment by thoschu96** [comment]
hey
no i try to use the original upload. py file.
i put it in one folder where i have the pictures in subfolders.

i tried to use it over the python idle and over the cmd.

cmd with and without admin rights .

same result

over cmd i fired it up with

upload.py \pictures
and
upload.py c:/temp/pictures

same result.

i did not find any easy to start py-file
to upload any pictures .

sigh'

Am 12.05.2015 um 11:16 schrieb Jan Erik Solem <notifications@github.com<mailto:notifications@github.com>>:


upload.py is meant to be run from the command line. If you want to write your own script you need to replicate what's in the if __name__ == '__main__' section.

It looks like you're trying to run one of the other scripts that use upload.py though. Is that what you're doing? Make sure the folder containing upload.py is in your PYTHONPATH if you're running this from some other path.

-

**Comment by jesolem** [comment]
This is weird since there is no line that does `from upload import create_dirs, UploadThread, upload_file` in upload.py. (the other upload files reference upload)

I suspect you're trying to run something else. Try this:
> python upload.py path

from your command line.

**Comment by domdomegg** [comment]
I am also getting a similar error:
    Traceback (most recent call last):
    File "upload_with_authentication.py", line 11, in <module>
    from upload import create_dirs, UploadThread, upload_file
    ImportError: No module named upload

I am using the upload_with_authentication.py - I think thoschu96 is also using it, as only this one contains this line.

**Comment by domdomegg** [comment]
I think I found the solution - for me at least, although it seems similar for thoschu96.

Make sure you have downloaded the latest upload.py and it is in the same folder:
https://github.com/mapillary/mapillary_tools/blob/master/python/upload.py

I think the documentation needs to be clearer that for the upload_with_authentication.py you require the upload.py. Alternatively, the useful parts of upload.py could be simply copied into the other, which may save space.

**Comment by jesolem** [comment]
Hey @domdomegg 
In the comments next to the description on how you run from the command line it says
```
You also need upload.py in the same folder or in your PYTHONPATH since this script uses pieces of that.
```

I can add it to the readme, would that be enough?

**Comment by jesolem** [comment]
In the readme now.

**Comment by domdomegg** [comment]
Yep, that sounds good :)

**Comment by jesolem** [comment]
Alright, closing this. Thanks again for the attention @domdomegg
