### ISSUE TITLE
EMBED code has to be easier

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#101]
One important thing for me is EMBED my walks uploaded to Mapillary inside my blog.I have visited http://www.mapillary.com/integrate.html , I try it and it works, ok but it is very complicated (also because you have to find the code of the photo , etc.). I wish an embed form (like Google Maps does) for a concrete image, concrete street or concrete city, etc...

**Comment by gyllen** [comment]
This is what we have at the moment, please check out http://www.mapillary.com/integrate.html
