### ISSUE TITLE
Country stats are not being updated

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1011]
On March 30 (almost 3 weeks ago now), I took a screenshot of the top 10 uploaders for Norway (http://www.mapillary.com/map/places/norway). Today, the list is identical.

My position on the Dutch top list also remains unchanged, even though it's been more than a month ago that I was there.

How often are these stats supposed to be updated?

**Comment by de-vries** [comment]
I've mentioned this before too: #887. After that the dutch stats got updated a few times, but the last time was about 2 weeks ago. To me it seems those pages are only updated manually.

**Comment by jesolem** [comment]
@pbb72 They are supposed to be updated continuously but they're not at the moment. We're fixing this and more importantly @jlevente is looking into better shapes for these stats too.

**Comment by pbb72** [comment]
Cool! Looking forward to see what this will do to the stats :-)

**Comment by Peatsmoke** [comment]
Would be great if that could be fixed, for me as a "border-mapper", in The Netherlands... :)

**Comment by pbb72** [comment]
For reference, the border problem is discussed in more detail in issue #465, and others.

**Comment by de-vries** [comment]
The stats seem to be updated regularly since the update that brought the weekly stats. lets close this.

**Comment by gyllen** [comment]
fixed, stats are now live

**Comment by pbb72** [comment]
Thanks! Both live, and using the correct border shapes.
