### ISSUE TITLE
Approval process needs to be more transparent

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1012]
The process of approving requested changes is extremely obscure, and Mapillary users have no idea what is being done or why.

Several changes have been suggested, such as more informative emails and information on the site.

I understand that these changes will take time to implement. But in the mean time, a lot can be done just by writing some helpful documentation, for example in a blog post.

Some topics that need to be covered:
- Why is approval required in the first place?
- How is this process handled (e.g., by machine or manual labor)?
- Who can be contacted if changes don't seem to get approval?
- A more realistic time estimate about how long the process may take. (For me it's more often than not taking over 24 hours). During what days/periods does the process take more time? (For example, it seems like the process stops during the weekend.)
- What is the best form to send change requests (e.g. one sequence at a time or as many sequences as possible at once; rotation and position changes at the same time or in separate requests)?
- How are concurrency conflicts handled (e.g., two people requests different changes for the same sequence; changes to rotation and position of the same elements in different change sets.)

I have started to carefully document every change request I send, and I see that some changes are not being approved, or only partially approved. It would be good to know if this is due to processing errors, or intended.

**Comment by filipca** [comment]
In the blog Mly referenced 
http://blog.codinghorror.com/complaint-driven-development/

**Comment by travel193** [comment]
Hi Pbb,

First of all, apologies for your dissatisfaction with the change review process. You raise some good points and a re-evaluation of how we manage the changes is underway.

To address your points one by one:

-Approval is required in the first place to prevent people from accidentally or intentionally making harmful changes to sequences. There have been times when users have accidentally hidden other people’s sequences and the approval acts as a good backup to prevent this. It is very difficult to revert changes once they have been made.

-It is currently handled by manual labour. I process the majority of changes so am the best person to contact. We also have a sequence bot that reviews sequences and requests cuts to sequences where images are greater than 300m apart. These are also processed by manual labour.

-The processing takes longer during the weekend, both because I am less active reviewing them but also because the number of uploads is far greater. We will evaluate the process and provide a more realistic timeframe.

-It is best to make as many changes as possible in one go as this will be approved in a more timely manner.

-Currently conflicts aren’t handled very well as I am only able to view one change request at time. Therefore I will first apply the latest change request and then the first once I get to it. We will need to create a workaround for this.

We are currently working out how to give our most active users the ability to approve changes themselves. There are some technical considerations here but this is what we are working towards and it should lead to a drastically reduced processing times.

If ever you have any questions about the process, you can contact me directly (ed [at] mapillary dot com.)

**Comment by filipca** [comment]
It seems I commented in the wrong thread :)
I don't care too much about my change requests.

**Comment by travel193** [comment]
I really liked your blog post anyway @filipca !

**Comment by pbb72** [comment]
Hi @travel193, thanks for the reply!

Here is a few more questions, which I will pose here for the sake of transparency:

- You mention sequence cuts, does this part actually work? I've never had a sequence cut request be honored (see issue #732)

- Do changes to different photos in the same sequence also cause conflicts? For example I do some changes to photos at the beginning of a sequence, submit the changes, and then later change some photos at the end of the same sequence. In my experience it seems like only one of these change sets will be approved and the other will be disregarded.

- Why do change sets sometimes only partially go through? I've had a few instances where I moved all photos in a sequence, and after approval there is clearly one or two groups of photos in the sequence that have not been moved (still in their original location).

- You mention it's best to perform as many changes as possible in one go. However, I often notice that big change sets don't go through. This morning for example I modified all sequences in 5-6 streets, together maybe 200 photos, but after submitting the changes I have not received an email confirmation. This has happened several times before, and sometimes the changes are approved in the end, other times I have to do everything again.

**Comment by travel193** [comment]
Hi @pbb72 ,
I'll have to investigate these as it should not be occurring.
Sequence cuts are currently only working for distances greater than 300m. Can you send me some sequence keys of cuts not working and conflicts and I will get back to you.

**Comment by pbb72** [comment]
@travel193, can you tell me if subsequent changes to different photos in the same sequence cause conflicts?

**Comment by travel193** [comment]
@pbb72 If you are talking about individual changes and not sequences changes then they should not cause any conflict. Which images are you referring to and which changes were being made?

**Comment by pbb72** [comment]
Sometimes only parts of a changeset are accepted, as can be seen in this composite screenshot.

![image](https://cloud.githubusercontent.com/assets/1436366/7772510/e26715d4-009e-11e5-82b0-93047240b4fb.png)

I am trying to figure out if this is because a later change to one of the involved sequences, at another location, has caused the loss of earlier changes to that sequence.

**Comment by travel193** [comment]
Hi @pbb72 ,
I had a look at the area at it looks like two different sequences. 
1. http://www.mapillary.com/map/im/C_5KktezH1YbJYihqMeINQ
2. http://www.mapillary.com/map/im/Tb91rK-qrMmiZ3-IdIvl_g

Sequence keys:
1. http://www.mapillary.com/map/s/QO7UY_2Ta2b6gcdALuScnw
2. http://www.mapillary.com/map/s/Tb91rK-qrMmiZ3-IdIvl_g

If you tried to edit the first sequence and then in the same change editor attempted to edit another sequence, I believe only the changes to the initial sequence you selected are being processed.

It is best in this case to do two different submissions (one for each sequence). They should then be processed correctly. In our review of the editor we can look at whether it is best to allow edits to multiple sequences at once.

**Comment by pbb72** [comment]
Here is another fine example. Out of this quite big changeset, at least 4 nodes (the encircled ones) are still on their old locations:

![image](https://cloud.githubusercontent.com/assets/1436366/7774289/62234da0-00aa-11e5-8559-12cd3beb910c.png)

**Comment by travel193** [comment]
@pbb72 and to other users submitting change requests.
We are currently experiencing slow write speeds on our database, but are working to address the issue. As a consequence change requests will take a while to be processed. We will update on twitter once everything is back to normal.

Sorry for the inconvenience caused.

**Comment by travel193** [comment]
Processing speed and improvements to change set processing can be tracked in #438

**Comment by pbb72** [comment]
@travel193, could you please re-open this issue? The issue here is *not specifically* the processing speed.

This issue is about the general lack of feedback during the processing. Sometimes emails are being send out (though that is far from always the case) when a change request is received, but that is simply not enough.

For example, nothing is being communicated when requests have been completely or partially denied. (This happens a lot for me.)

Also, the email just contain a general message about a number of change requests that have been received, no information on exactly what has been received.

The current policy is to ask submitters to open an issue when their change has not been performed. However, there is a serious delay between the moment a change is submitted, the moment a confirmation email *may* be send out (often several hours later), and the moment a change *may* be accepted (often several days later). In combination with the lack of feedback about the received requests, this makes it very difficult to post proper issue reports.

When exactly did I submit the request? What were the exact changes that I submitted? Those questions are very difficult to answer after several days, unless we who requests the changes, start maintaining our own log on exactly what we submitted.

**Comment by travel193** [comment]
Hi @pbb72 ,
Sorry for the frustration in processing change requests. The change request system is still in need of a substantial update. This will be the focus shortly.
In the meantime, all change requests are going into a queue that will be processed when the system has been updated. 

In terms of why some of your change sets are being denied, we will have to look into this. I believe this is an error and not someone actively declining them. We will investigate.

**Comment by pbb72** [comment]
Am I understanding correctly that currently, no change requests are being processed at all? That would explain why I am still waiting for several changes.

**Comment by travel193** [comment]
That's correct @pbb72 . They're all in a queue right now with none of them going through yet.

**Comment by pbb72** [comment]
Then maybe the message that is currently shown on the edit page should be updated, to inform users of this situation?

**Comment by filipca** [comment]
I once asked to hide the sequence of a gps receiver gone wild.  (giving zigzags all over the place).
I did not receive an answer.  
This issue is known.

**Comment by travel193** [comment]
Which sequence is this @filipca ? We can put it in the queue to hide it or get the mapper to correct it.

**Comment by filipca** [comment]
http://www.mapillary.com/map/im/5G_XrkJty10SVqd_sCHluA/map

It is from my friend Polyglot, a well respected mapper.  He answered me allready about it.
There are more occurances, but this one invases my territory  :)

**Comment by ybkuang** [comment]
@filipca Thanks for the details. There is an issue with the image capture date/time on this sequence. We will reprocess it and fix the ordering (so no zigzags after that). (It has been tricky to reprocess long sequences and update the database before, we recently update our backend so it becomes possible. We will reprocess it as soon as we can. Sorry for the delay!).

**Comment by filipca** [comment]
It is a sequence from him visiting me in a bus.  It is an interesting  sequence, but as the issue is so old yet, I think there is no other solution as to kill it.

**Comment by pbb72** [comment]
I've seen sequences like that before. The problem is that Mapillary is not able to read the timestamp from the photos, and in that case sorts all photos by latitude (north to south), which creates zig-zag patterns if the travel direction alternates between northbound and southbound (such as is often done in a bus).

The funny thing is, if you get this error on a travel from south to north in a somewhat straight line, you won't notice anything weird, except that the direction of the sequence is turned the wrong way around :-)

**Comment by pbb72** [comment]
As the processing of changes seems to be more reliable now, the need for feedback is not as important anymore. I'll close this issue. I'll open new issues if I find specific problems with change requests.
