### ISSUE TITLE
Weird blurring on photospheres

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1014]
When trying to blur, for one it is quite a small, and distorted preview for blurring, and for two it does not actually create the blur where you click and drag. (Generally the lower down the picture you are, the further away the blur is actually made, so try near the bottom and you'll see).

Eg:
http://www.mapillary.com/map/b/UlqTNaCn8w7s0V6s8Y6HNg

Would suggest previewing in the photosphere view, and then also making sure it works where you click.

Thanks!

**Comment by de-vries** [comment]
The blur editor can only handle photos wit aspect ratio 4:3 and fails at everything else.
see also: #157, #232, #370, #389, #424, #494, #553, #787

**Comment by domdomegg** [comment]
Ah thank you. Do know when a fix might be coming out? They say they knew about it and were working on it from Jul 2014, wondering if any progress made? (I understand if there may be more important things to be focusing on :))

**Comment by domdomegg** [comment]
Will close as duplicate of the many thread @de-vries mentioned
