### ISSUE TITLE
Missing my sequence(s) on the map

### ISSUE THREAD

**Issue by zdila** [mapillary/mapillary_issues#1016]
On 8th, 9th and 10th of May I've captured some longer sequences. They got uploaded on 10th to the mapillary server but I got no notiofication e-mail about it. My username is `martin.zdila` `m.zdila@gmail.com`.

Here are some logs from `mapillary_trace.txt`:

Capturing:

	Sun May 10 14:51:16 CEST 2015 : app.mapillary.android.activity.FileTask  - saving Sun May 10 14:51:15 CEST 2015
	Sun May 10 14:51:16 CEST 2015 : app.mapillary.android.activity.FileTask  - {"MAPDeviceMake":"                               ","MAPCameraMode":2,"MAPCaptureTime":"2015_05_10_14_51_15_867","MAPSettingsEmail":"m.zdila@gmail.com","MAPLoc
	Sun May 10 14:51:16 CEST 2015 : app.mapillary.android.activity.FileTask  - Saved to: /storage/sdcard0/mapillary/2015_05_10_14_46_33_447___Mapillary/2015_05_10_14_51_15_867.jpg
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Auto-fired shot 120
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Free/Total disk: 23639MB/26899.0MB, percent: 87.880585
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - takeShot Queue/Tasks: 0/0 of executor pool size 4
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Moving speed in m/s: 13.454839
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture with focus mode infinity
	Sun May 10 14:51:17 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.CameraActivity  - shutterCallback
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.CameraActivity  - RawCallback.onPictureTaken
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.CameraActivity  - pictureCallback
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 1. Queue/Executor size: 0/0
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 2. Queue/Executor size: 1/0
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.FileTask  - saving Sun May 10 14:51:18 CEST 2015
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.FileTask  - {"MAPDeviceMake":"                               ","MAPCameraMode":2,"MAPCaptureTime":"2015_05_10_14_51_18_005","MAPSettingsEmail":"m.zdila@gmail.com","MAPLoc
	Sun May 10 14:51:18 CEST 2015 : app.mapillary.android.activity.FileTask  - Saved to: /storage/sdcard0/mapillary/2015_05_10_14_46_33_447___Mapillary/2015_05_10_14_51_18_005.jpg
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Auto-fired shot 121
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Free/Total disk: 23638MB/26899.0MB, percent: 87.87688
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - takeShot Queue/Tasks: 0/0 of executor pool size 4
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Moving speed in m/s: 13.047693
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture with focus mode infinity
	Sun May 10 14:51:19 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.CameraActivity  - shutterCallback
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.CameraActivity  - RawCallback.onPictureTaken
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.CameraActivity  - pictureCallback
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 1. Queue/Executor size: 0/0
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.FileTask  - saving Sun May 10 14:51:20 CEST 2015
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 2. Queue/Executor size: 1/0
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.FileTask  - {"MAPDeviceMake":"                               ","MAPCameraMode":2,"MAPCaptureTime":"2015_05_10_14_51_20_166","MAPSettingsEmail":"m.zdila@gmail.com","MAPLoc
	Sun May 10 14:51:20 CEST 2015 : app.mapillary.android.activity.FileTask  - Saved to: /storage/sdcard0/mapillary/2015_05_10_14_46_33_447___Mapillary/2015_05_10_14_51_20_166.jpg
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Auto-fired shot 122
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Free/Total disk: 23637MB/26899.0MB, percent: 87.87315
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - takeShot Queue/Tasks: 0/0 of executor pool size 4
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - Moving speed in m/s: 12.436718
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture with focus mode infinity
	Sun May 10 14:51:21 CEST 2015 : app.mapillary.android.activity.CameraActivity  - requesting takePicture
	Sun May 10 14:51:22 CEST 2015 : app.mapillary.android.activity.CameraActivity  - shutterCallback
	Sun May 10 14:51:22 CEST 2015 : app.mapillary.android.activity.CameraActivity  - RawCallback.onPictureTaken
	Sun May 10 14:51:22 CEST 2015 : app.mapillary.android.activity.CameraActivity  - pictureCallback
	Sun May 10 14:51:22 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 1. Queue/Executor size: 0/0
	Sun May 10 14:51:22 CEST 2015 : app.mapillary.android.activity.CameraActivity  - 2. Queue/Executor size: 1/0

Uploading:

	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[1]  - Uploading photo /storage/sdcard0/mapillary/2015_05_10_14_46_33_447___Mapillary/2015_05_10_14_47_13_704.jpg to http://mapillary.uploads.images
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[2]  - upload status: 204
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[2]  - Cell sync pref: false
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[2]  - Uploading photo /storage/sdcard0/mapillary/2015_05_10_14_46_33_447___Mapillary/2015_05_10_14_47_11_516.jpg to http://mapillary.uploads.images
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService  - sleeping.0/132 of 1841
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[3]  - upload status: 204
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[3]  - Cell sync pref: false
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
	Sun May 10 19:02:52 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false

**Comment by gyllen** [comment]
Hey @zdila I know we has some problems with our notification engine then. Can you check if the images are in your profile http://www.mapillary.com/profile/martin.zdila

**Comment by zdila** [comment]
Hi @gyllen. Yes, I see it there. And today I see the tracks on the map too, maybe just some shorter segments are still missing. Also these tracks appear on the map only if I increase the zoom. If it is OK then you can close this issue. Thanks!
