### ISSUE TITLE
DMD Panorama metadata not being processed

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1019]
Eg. this sequence:
http://www.mapillary.com/map/im/X8OmcahPdVPJa3mElsZyrQ

Exif includes in "user comments" key:
{"dmd_datatxt":{"type":"cyl","fovx":360},"dmd_details":{"is_uploaded":false,"tags":"","direction":57,"description":"","altitude":0,"name":"Untitled","creation_time":1432136705,"longitude":51.519991,"latitude":-0.179236}}%00

Where I guess:
"type" is "cyl" (cylindrical) "sph" (spherical, like Google photosphere, currently not implemented)
"fovx" is the horizontal (x axis) field of view.
"is_uploaded" - whether the pano has been uploaded to DMD's service
"tags" - tags for DMD Pano
"direction" - compass bearing/heading
"creation_time" obvious what it means, not quite sure what time format
"altitude", "name", "longitude", "latitude" should be obvious
Then a weird %00

**Comment by domdomegg** [comment]
<rdf:Description rdf:about="" xmlns:GPano="http://ns.google.com/photos/1.0/panorama/">
      <GPano:UsePanoramaViewer>True</GPano:UsePanoramaViewer>
      <GPano:CaptureSoftware>DMD Panorama</GPano:CaptureSoftware>
      <GPano:StitchingSoftware>DMD Panorama</GPano:StitchingSoftware>
      <GPano:ProjectionType>equirectangular</GPano:ProjectionType>
      <GPano:PoseHeadingDegrees>57.0</GPano:PoseHeadingDegrees>
      <GPano:CroppedAreaLeftPixels>128</GPano:CroppedAreaLeftPixels>
      <GPano:CroppedAreaTopPixels>128</GPano:CroppedAreaTopPixels>
      <GPano:CroppedAreaImageWidthPixels>16107</GPano:CroppedAreaImageWidthPixels>
      <GPano:CroppedAreaImageHeightPixels>1042</GPano:CroppedAreaImageHeightPixels>
      <GPano:FullPanoWidthPixels>16107</GPano:FullPanoWidthPixels>
      <GPano:FullPanoHeightPixels>8053</GPano:FullPanoHeightPixels>
    </rdf:Description>

Equations to work this out:
* FullPanoWidthPixels = width*360/"fovx"
* FullPanoHeightPixels = FullPanoWidthPixels/2
* CroppedAreaImageWidthPixels = width
* CroppedAreaImageHeightPixels = height
* CroppedAreaLeftPixels = (FullPanoWidthPixels - CroppedAreaImageWidthPixels)/2
* CroppedAreaTopPixels = (FullPanoHeightPixels - CroppedAreaImageWidthPixels)/2
Assumptions being:
* Image is of equal proportions relative to FOV (as there is 360 horizontal rotation, and 180 vertical, thus half height equals full width)
* The panorama's middle is the compass angle, and the panorama was taken perpendicular to the ground. (The middle of the panorama is looking straight ahead, in a line parallel to the ground)

Then just use your favourite exif editor and add the standard GPano XMP Metadata :)

**Comment by pyrog** [comment]
For information, **DMD** mean [Dermandar](http://www.dermandar.com).

This an iOS, Android or web app that create panoramas:
[Dermandar Creates and Catalogs Panoramic Photos for Easy Sharing](http://lifehacker.com/5546245/dermandar-creates-and-catalogs-panoramic-photos-for-easy-sharing)

**Comment by ybkuang** [comment]
@domdomegg which version DMD were you using? We were expecting that a DMD tag in EXIF Software (instead of EXIF User Comment) for the DMD app. I will update the server code to handle this later. Thanks for reporting.

**Comment by domdomegg** [comment]
DMD Panorama Pro 4.1:
https://play.google.com/store/apps/details?id=com.dermandar.panoramaf

**Comment by ybkuang** [comment]
@domdomegg so the images can be viewed as panoramas now. 
There remains a date problem for the sequence (thus the ordering is random now). We will work on fixing that later.

**Comment by domdomegg** [comment]
Ok sure. I think the DMD related stuff is finished though but I am not sure I have understood your last comment, if you think this should be closed, do so as I think it should be now.

**Comment by domdomegg** [comment]
Also thank you for fixing this, and also I just noticed the cool vector map. Well done to the Mapillary team :+1:

**Comment by ybkuang** [comment]
Great to know that you like it, more improvements to come!

My last comment was on datetime of the photos (they all have 1970.1.1). We will fix that soon. Once that is fixed, I will close this.

**Comment by domdomegg** [comment]
I have just checked the originals I have, I think it was a problem with my phone as none of them actually have date-time encoded in them properly (they are all set to ~4pm on 1970.1.1), must of lost track of date and reset.
