### ISSUE TITLE
Manual uploads: what is the better image size ?

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1020]
I took ± 500 pictures with my [DSLR](http://en.wikipedia.org/wiki/Digital_single-lens_reflex_camera).
Each one have a size of **5184 × 3888** pixels and a weight of **9.4 Mb**.

It's very long to upload them. **What is the recommended or "optimized" size for pictures ?**
So I could resize them before (and in the future, set the appropriate image size of my DLSR).

Thanks

**Comment by domdomegg** [comment]
4:3 ratio is best, which your photos are already.

Higher quality the better, however often >8.5MB (officially 10MB) it will not accept your photos.

If you are on a Mac I would personally recommend a tool called "ImageOptim"

IMPORTANT: Go into preferences, enable all the compressors, but make sure you untick remove EXIF data! I use a JPEGOptim % of 85, and they come out fine eg. https://d1cuyjsrcm0gby.cloudfront.net/vtnKB3TZzJ1wdxMHuu9rmA/thumb-2048.jpg (Panorama), and it saves about 50% of file size, so uploading is much much faster.

**Comment by pyrog** [comment]
@domdomegg Thanks for the link, I will try it :smile: 

@jesolem Does Mapillary team could give us advices ?

**Comment by jesolem** [comment]
Short answer here, we will put more details on our upcoming user guide.

4:3 aspect ratio. We use 2048px width as our largest thumbnail but that may increase in the future. If you want to make the images smaller than originals, I'd try a 4:3 that has width larger than 2048px. If that's not enough, you can play with JPEG compression coefficient.

**Comment by jesolem** [comment]
@travel193 to take this to user guide.

**Comment by floscher** [comment]
Probably a power of two (2048, 4096) as width would be optimal in order to give best results when Mapillary later resizes to 2048 or 1024 (the smaller sizes are currently no powers of two AFAIR).

**Comment by travel193** [comment]
Aspect ratio will continually be updated in the [User guide](https://github.com/mapillary/UserGuide/wiki/Uploading). The new viewer will support more aspect ratios.

**Comment by richlv** [comment]
also see issue #191
