### ISSUE TITLE
Name of picture could be wrong in the wild

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1021]
Mapillary seem to use the name of the nearest road.

In the example below, **the name** "Rue des Écoles, Saraz" **is absolutely wrong**. This road is far away of the trail, and is in the bottom of the canyon, near the river.

As the trail is unnamed, the river name is the most appropriate in this case.

See #476 

[![rue des ecoles saraz](https://cloud.githubusercontent.com/assets/2158081/7780137/91f54980-00db-11e5-9dc2-ee42171da65c.png)](http://www.mapillary.com/map/im/Tazyt7CaNX69NV_iiAD4Lg)

**Comment by domdomegg** [comment]
Also perhaps if it is far away from anything (>100m from a named object), it just does not display any name.

**Comment by pyrog** [comment]
> if it is far away from anything, it just does not display any name.

:+1: or display "Near Saraz"

> if there is any way just take the name of it, eg. 'Unnamed Road'.

"On unnamed trail", "Near Lizon river"…

Or manually edit the name for all or part of the sequence. See #1013

**Comment by de-vries** [comment]
lots of objects get ignored in the reverse geocoding process. see also #896

**Comment by jesolem** [comment]
We're going to do a major remake of our geocoding but will be a while (at least several weeks) before we can start that work. There are several issues reported and we will take them all into account. 

Thanks for being patient.

**Comment by gyllen** [comment]
No longer geocoding in backend.
