### ISSUE TITLE
Time in iOS app

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1022]
Sequences taken since a few weeks all have the date 1 jan 1970 in the iOS. The correct date is shown  on the web.

**Comment by domdomegg** [comment]
In the review, explore or feed tab? Or all/combination?

Try downloading the photos to your computer, then use exiftool to check what their dates are before going on the server. Make sure your date & time is correct, even if it is not reset it could contribute to timing weirdness.

### Instructions for photo transfer:
If you haven't already, download and install iTunes.
1. Open iTunes
2. Connect your iDevice to iTunes (via USB preferably, as it gives faster transfer speeds)
3. In the top left, in the toolbar click the device icon, then in the left column select 'Apps'
4. Scroll down to find a 'File Sharing section'. Select Mapillary on the left, and select the folders you wish to copy.
5. Press 'Save to...', and select a suitable location for the folders to be stored. The progress will be shown in the top activity bar of iTunes
6. Once it has finished copying, you can then eject your device and disconnect it from your computer

If you don't have exiftool installed, use http://regex.info/exif.cgi and/or upload the image to your GDrive/Dropbox in a zip so it is not changed, and then share it.

**Comment by jesolem** [comment]
@Andblue Thanks for reporting. I can confirm this in my own feed from yesterday. This is most likely a bug introduced in the big backend upgrades of last week. The dates are fine in the files. @gyllen will fix.

@domdomegg Thanks for chiming in!

**Comment by gyllen** [comment]
Fixed
