### ISSUE TITLE
Connections in iOS app

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1023]
In the iOS app it says that I have 0 connections.

On the web connections are shown, but it looks a bit broken.

**Comment by jesolem** [comment]
@gyllen The app checks the "connections_all" field in the response. Can you check API side?

**Comment by gyllen** [comment]
@jesolem Connection will be replaced we should consider removing connections from app

**Comment by jesolem** [comment]
Removed from next version.
