### ISSUE TITLE
Homepage images could be smaller

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1025]
Losslessly compressing all the static images could save bandwidth, therefore money.

Average for all the static images (logo, 1,2,3 sequence, you & Mapillary, app buttons) saves 45.8%. (ImageOptim)

With lossy (although not noticeable to me), using ImageAlpha (with support for more browsers enabled) I reduced the file size by 86.8% for the business image.

Original:
![business orig](https://cloud.githubusercontent.com/assets/4953590/7800454/8d8b351a-030d-11e5-88b7-8c471b9c8a31.png)

ImageOptim only (lossless) - 42.1%:
![business imageoptim](https://cloud.githubusercontent.com/assets/4953590/7800464/a1ddb27c-030d-11e5-906d-c9429a85251b.png)

ImageAlpha + ImageOptim (lossy) 86.8%:
![business imagealpha imageoptim](https://cloud.githubusercontent.com/assets/4953590/7800456/936d6e30-030d-11e5-9957-9ec9155779fe.png)

Furthermore, you could probably combine the live world map background into one image, which could load faster, and compress it. Transparency may also compress it further.

All this should result in faster load times, and less bandwidth at no cost as this is all free software :)

**Comment by jesolem** [comment]
We'll take a look.

**Comment by jesolem** [comment]
This image and many others were removed in the latest remake. We are looking at reducing the load time of other assets too. Thanks @domdomegg
