### ISSUE TITLE
Uploads to map = slow

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1027]
Is there a huge bulk upload going on again? It takes longer and longer for uploads to appear on the map. For my last one its now over 24 hours and its still not showing.

**Comment by gyllen** [comment]
Yes, but our database might have run its course. Prepare for some downtime this week while we be switching up servers

**Comment by gyllen** [comment]
Note that data is never lost and will alwaya be processed within reasanble time. Hope you will continue to upload. We don't mind scaling ;)

**Comment by Andblue** [comment]
Scaling up is nice :-) On to take some more pictures then.
