### ISSUE TITLE
Manual upload: picture in wrong place

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1028]
I uploaded a 87 pictures (starting from the last). The last have good coordinates, but bad position on the "preview" map.
`
![bad position](https://cloud.githubusercontent.com/assets/2158081/7806978/94b869a0-0387-11e5-97d8-0b819236f5e0.png)
![bad position 2](https://cloud.githubusercontent.com/assets/2158081/7807001/cb3ecfc8-0387-11e5-8326-0632b57cbdd7.png)

**Comment by ybkuang** [comment]
@pyrog Is it possible for you to send the last two images to hello at mapillary.com? We will investigate.

**Comment by pyrog** [comment]
@ybkuang  done.

Send the same pictures in the natural order, same result:
![upload](https://cloud.githubusercontent.com/assets/2158081/7808005/1de495ac-0390-11e5-890f-2d170050677e.png)

**Comment by ybkuang** [comment]
@pyrog I just tried here for the two images you sent. And it looks ok.
![image](https://cloud.githubusercontent.com/assets/5370656/7808892/b2b6d806-0396-11e5-90dc-4fc55e7ff231.png)

**Comment by pyrog** [comment]
@ybkuang Coordinates in all images are correct (see Picasa map :wink:).
Also in the first example, you can see picture with coordinates in Europe, but mapped in East Africa.

**Comment by ybkuang** [comment]
The lat/lon seems to be reversed when these happen (thus it goes to Africa). Need to check more on this. Will get back to you later.

**Comment by ybkuang** [comment]
I will close for now. If this issue persists, please report back to us @pyrog!
