### ISSUE TITLE
Manual uploads: add an option to correct angles

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1029]
My camera don't save the azimut. Is it possible to correct it like in the edit mode?

**Note:** It take time to upload pictures, then edit sequence and wait for the validation by your team

**Comment by ybkuang** [comment]
Yes. We are thinking about adding angle editing to the next version of the uploader.

**Comment by domdomegg** [comment]
Good idea :+1: 

Also maybe combine it with location too :)

**Comment by nickplesha** [comment]
Image angles can be set in the web editor now.
