### ISSUE TITLE
Portrait mode?

### ISSUE THREAD

**Issue by ireun** [mapillary/mapillary_issues#1031]
Hello,

Could you make it possible to take pictures in a portrait mode? I would make tons of photos while biking, just my mount won't let me do it in landscape mode. ; <

Cropping would be OK.

**Comment by de-vries** [comment]
You can take pictures in a portrait mode by unchecking the pause while tilting option in the settings. Mapillary however isn't really build to handle non 4:3  aspect ratio photos so you should crop them yourself before uploading. I can recommend [Phatch](http://photobatch.stani.be/) for that.

**Comment by iav** [comment]
Portrait mode can be good for panoramas - at least until mapillary not support photospheres and fish-eyes.

**Comment by domdomegg** [comment]
@de-vries ty for the resource, found very useful. Will also probably do some more biking with Mapillary now.

**Comment by pbb72** [comment]
I am getting good landscape photos using this universal phone mount: http://www.ebay.com/itm/Motorcycle-Bicycle-MTB-Bike-Handlebar-Mount-Holder-Universal-For-Cell-Phone-GPS-/291222031229?pt=LH_DefaultDomain_0&hash=item43ce2f8b7d

Though I have to install the mount unside-down to avoid getting the bike handlebar in the photos.

**Comment by pbb72** [comment]
This is a duplicate of #424

**Comment by ireun** [comment]
Yup, thank you. Closing...

**Comment by domdomegg** [comment]
Closed, but wanted to add this for other people with my type of bike mount

If you have this type of mount:
http://www.ebay.co.uk/itm/UNIVERSAL-BICYCLE-BIKE-IPHONE-4-4S-5-MOBILE-PHONE-HTC-HOLDER-MOUNT-HANDLE-BAR-/400750198123?hash=item5d4e92bd6b

You can mount it the opposite way (so that the phone is in front of the handle bars, with the screen on the plate), otherwise no matter how you try and mount it you cannot get landscape without just a picture of the ground/handlebars.

**Comment by jesolem** [comment]
Ping @travel193 , something for the user guide perhaps.

**Comment by travel193** [comment]
Hi @pbb72 ,
Thanks for sharing your bike mount suggestion. I'll add it to our list of recommended mounts. Have you had any instances of your phone falling out over rough surfaces using this mount?

@de-vries Great points. Adding some commentary for portrait mode to the wiki now.

**Comment by pbb72** [comment]
@travel193 No problems with the mount, the grip is quite good and the joint are not moving either. Only problem is that the Mapillary apps sometimes rotates photos taken on rough roads, and of course blurry photos when the shutter time gets too long :-)

I will upload a photo of my installation within a few days.

**Comment by pbb72** [comment]
Here is my phone in the camera mount. Camera mount is upside-down and the phone is the "wrong" way around, this way it is in a perfect position to make street photos.

![dsc_6023](https://cloud.githubusercontent.com/assets/1436366/7968613/20f1a4e4-0a32-11e5-992d-769b2834c756.JPG)

It's impossible to see much of the screen while cycling, but enough to check that it's still in recording mode and to be able to press the right buttons.

![dsc_6025](https://cloud.githubusercontent.com/assets/1436366/7968652/5ca97476-0a32-11e5-8d1a-c42b428b1902.JPG)

**Comment by travel193** [comment]
@pbb72 Thanks heaps for taking some snaps of your setup. Do you mind if I incorporate these into the wiki under the bike section? We have ordered some bike mounts which appear to be almost identical to yours so it's perfect for instructions for setup.

**Comment by pbb72** [comment]
Yes you are welcome to use them. If you have specific wishes for more photos of the setup, just ask me :-)

**Comment by travel193** [comment]
Great. Thanks very much @pbb72 .
Added it to the [wiki](https://github.com/mapillary/UserGuide/wiki/Capturing).
