### ISSUE TITLE
[Beta] Input field on user filter should have no name attribute

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1034]
The input field of the user filter has the attribute `name="user"` which causes my browser to give suggestions from thing I typed before in input fields with the same attribute. Those suggestions are rendered on top of the suggestions Mapillary gives me.

If I remove the attribute, the issue is gone.

tested in FF38

**Comment by knikel** [comment]
Attribute removed, thanks for pointing this out @de-vries!
