### ISSUE TITLE
roadsign edition saving newer ends - error 503 in error console

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1035]
Got error 503 trying to save roadsign update from browsing mode

there chrome browser error console

a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh:1 POST https://a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh 503 (Service Unavailable)
WYr3CMNBGUIEpWoJIx67hQ:1 XMLHttpRequest cannot load https://a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access. The response had HTTP status code 503.
a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh:1 POST https://a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh 
WYr3CMNBGUIEpWoJIx67hQ:1 XMLHttpRequest cannot load https://a.mapillary.com/v2/im/WYr3CMNBGUIEpWoJIx67hQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by it4workflow** [comment]
same here, chrome and firefox

**Comment by it4workflow** [comment]
#999

**Comment by gyllen** [comment]
fixed
