### ISSUE TITLE
Wrong image ordering after manual upload, if photos was maked faster than 1 fps

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#1037]
http://www.mapillary.com/map/im/GDSlT6Ge1FlByfk1sDj4Vg
In Play mode order of images are incorrect.
This is a sequence of photos made by custom script from video file with 3 frames per second speed.
3 fps.
May be image should be ordered by exif datetime and filename?

**Comment by ybkuang** [comment]
@trolleway We are ordering the images by datetime. I check that the precision of datetime of your sampled images is second, e.g. these two images:

http://www.mapillary.com/map/iminfo/GDSlT6Ge1FlByfk1sDj4Vg
http://www.mapillary.com/map/iminfo/-xjYDMvh9Olo-WkYDxA6dQ

So frames within one second will have random ordering.

**Comment by ybkuang** [comment]
@trolleway We cannot do much to fix this since the data is wrong. I will close this for now. Please report back if you have similar issues again.
