### ISSUE TITLE
No progress shown in the notification bar

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1038]
The Android application display *"Upload requested. Progress will be shown in the notification bar"* but **nothing is displayed** in the notification bar.

**Cause:** there are **pictures with zero size** that seem to crash the background task.
(My memory was full but I saved pictures in manual mode. The app create image files but can't write anything inside)

**Solution:** move or delete theses files in `local storage/Android/data/app.mapillary/files/mapillary/xxxx__Mapillary/yyyy.jpg`

**Comment by peterneubauer** [comment]
Is there any log for this that you can send or attach here?

**Comment by pyrog** [comment]
To reproduced this bug:
 1. Take pictures from Mapillary app
 1. Use your favorite text editor to delete all the content of one picture
 1. Restart Mapillary app
 1. Select "Review" menu and press the "Upload" button

The zero length picture appear as a black square:
![screenshot_2015-05-30-16-09-00](https://cloud.githubusercontent.com/assets/2158081/7898072/b6b8c0f2-06f4-11e5-9dd3-6646452aa87d.png)

The message is displayed on upload without anything in the notification bar.
![screenshot_2015-05-30-16-09-55](https://cloud.githubusercontent.com/assets/2158081/7898086/2d0ff32e-06f5-11e5-9bd4-a6982d80b593.png)

To restart the background task:
 1. Stop Mapillary app
 1. Delete all pictures with zero file size
 1. Restart the app

**Comment by peterneubauer** [comment]
Thanks, will take a look!

**Comment by Neogeografen** [comment]
Got the same issues for a couple of days - It seems to hung the system and when there is a connection only small amount of pic can be uploaded - Andriod 1.24 Mapillary have been working fine since released and fast- But I think the major Database  last week(1-2) have done something in the upload progress.

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
