### ISSUE TITLE
Focus mode: infinity don't work

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1039]
This option don't work on a **Samsung Galaxy S5** under **Android Lollipop**

* Mapillary version 1.24
* Android version 5.0
* Model SM-G900F

**Comment by pyrog** [comment]
Work fine on **Samsung Galaxy S4** under **Android Jelly Bean**  :smile:
* Mapillary version 1.24
* Android version 54.3
* Model GT-I9300

**Comment by peterneubauer** [comment]
Grrh, any chance to check the logs or send them for the S5? Might be that the API simply is not working :/

**Comment by pyrog** [comment]
You want the `mapillary_trace.txt` file?

**Comment by peterneubauer** [comment]
Yes, that would be a good start.

**Comment by pyrog** [comment]
I saw also your [comment](https://github.com/mapillary/mapillary_issues/issues/765#issuecomment-76922846) on how to generate `mapillary.log` file. Thanks :smile: 
And also, [how to take screen shots on Android Lollipop](http://www.samsung.com/us/support/answer/ANS00039212/754736576/).

**Comment by peterneubauer** [comment]
Just looked at the log files - it seems inifity is requested from the
camera, do you have a sample of the faulty pics?

**Comment by pyrog** [comment]
> do you have a sample of the faulty pics?

No, but I see the focus changing when I move something in front of the camera.

**Comment by claush66** [comment]
Hi, I seem to have the same problem on Galaxy S6. For examples, see my recent upload http://www.mapillary.com/map/im/z2ijttsBilNzm5DLtzskFA/photo .
Focus was set to "Infinity, Fixed focus, good for driving"

**Comment by iav** [comment]
Link #1396 same for Samsung Galaxy Note 4. Trace log sent and can perform tests you ask for.

**Comment by claush66** [comment]
As a follow up to my above example photo, here you have a fresh example of a series shot with my Galaxy S6 using "Continuous focus for pictures. Usually the best default option for modern phones"
http://www.mapillary.com/map/im/akXICA5_8M-A3-73uTq1sQ/photo

It seems I cant use my Galaxy S6 for Mapillary, unless I accept to submit very blurred photos (which I do not find usefull really)

**Comment by peterneubauer** [comment]
Claus,
do you see the viewfinder in this mode adjusting at all to different
objects? The focus should follow the center of the image ... otherwise,
does switching to "infinity" or "autofocus" give any effect?

**Comment by claush66** [comment]
Hi Peter,
I have tested both of the modes I mentioned in my posts. The viewfinder is
slightly blurred and seem to reflect the quality in my uploads.
Den 26/10/2015 13.25 skrev "Peter Neubauer" <notifications@github.com>:

**Comment by peterneubauer** [comment]
Ok,
now if you join https://play.google.com/apps/testing/app.mapillary and test out the latest App version (1.52) the focus settings should work better @claush66 ?

**Comment by iav** [comment]
I am not claush, but join and test testing.
There it is: http://www.mapillary.com/map/im/isNie7LUBMGk1ghXcyCaJQ/photo

**Comment by claush66** [comment]
Hi Peter,

Unfortunately the testing version didnt appear to solve the focus. See my
upload of today using "continuous-picture" focus
http://www.mapillary.com/map/im/ntac1WxpXXPvaVH_1UR54A

2015-11-05 9:32 GMT+01:00 Peter Neubauer <notifications@github.com>:

> Ok,
> now if you join https://play.google.com/apps/testing/app.mapillary and
> test out the latest App version (1.52) the focus settings should work
> better @claush66 <https://github.com/claush66> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/1039#issuecomment-153987427>
> .
>



-- 
-- 
Civilingeniør ph.d. Claus Hindsgaul
Studsbøl Alle 81
DK-2770 Kastrup

**Comment by peterneubauer** [comment]
@claush66 do you have the logs for this and can send them to hello@mapillary.com?

**Comment by claush66** [comment]
Yes, just did.

2015-11-09 12:00 GMT+01:00 Peter Neubauer <notifications@github.com>:

> @claush66 <https://github.com/claush66> do you have the logs for this and
> can send them to hello@mapillary.com?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/1039#issuecomment-155028831>
> .
>



-- 
-- 
Civilingeniør ph.d. Claus Hindsgaul
Studsbøl Alle 81
DK-2770 Kastrup

**Comment by peterneubauer** [comment]
@iav looking at the sequence http://www.mapillary.com/map/im/u_byuEXDqJwAAs8zsnp1_g/photo it seems the device is not honoring you "infinity" setting but using continuous-picture focus. Could you please send me a log when this happens again?

**Comment by peterneubauer** [comment]
@claush66 yeah, seems the camera did not find focus. It should have accepted "continuous-autofocus" though, see logs entry
```
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Requested mode: continuous-picture
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Focus mode: auto
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Focus mode: infinity
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Focus mode: macro
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Focus mode: continuous-video
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Focus mode: continuous-picture
11-09 09:12:20.775 D/app.mapillary.android.activity.CameraActivity(21645): Setting Focus mode to continuous-picture
```

So, does it work better if you set it to `infinity` and, if you hold your hand in front of the camera, does it refocus in case of `continuous-autofocus`?

**Comment by iav** [comment]
Sent to your gmail.

-----Original Message-----

**Comment by ireun** [comment]
@peterneubauer Any news about this?

**Comment by iav** [comment]
Just got update, check pan indoor - "infinity" focus still try to re-focus on panning.

**Comment by peterneubauer** [comment]
Grrh,
Will try to put some more work into this next week. Stay tuned!

**Comment by peterneubauer** [comment]
So, I'm beginning to suspect that this might be shortcomings of the (deprecated in Android 5+ devices) old camera API. On Lollipop+ devices, we should use http://developer.android.com/reference/android/hardware/camera2/package-summary.html, which is incompatible with earlier devices though.

We have to do some refactoring in order to be able to separate out all camera-only functionality out of the camera code, and only load the a camera class which uses the Camera2 API if it is supported by the device, otherwise the whole app will crash as the camera2 APIs are not present on older devices and there is no compatibility package provided by Google.

Let me come up with a prototype and see if that works for you!

**Comment by iav** [comment]
Ready to perform any tests can help.
