### ISSUE TITLE
Beta map view suggestions

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#1040]
The new Beta map view is a great improvement!
There are a view things missing though:
- more map layers (default OSM layer, Satellite)
- image direction
- play back button in map screen

What is the intention of the up/down (north/south? play back?) arrow  under +/- control button in the upper right corner of the map?

**Comment by eugensim** [comment]
+navigation in full screen mode

**Comment by jesolem** [comment]
@ligfietser The compass icon is for rotating the map. Try click and drag. 

@eugensim full screen is coming.

**Comment by ligfietser** [comment]
Ah I see it's rotating, cool :)

**Comment by richlv** [comment]
displaying of image direction on the map (like in the old viewer) also requested in issue #1118

**Comment by polarbearing** [comment]
As the beta is rolled out now, the lack of the viewing direction in the map pointer is bitterly missing. 

There is no clue in the picture what direction I am looking at!

**Comment by ligfietser** [comment]
I miss the default osm map layer. Distinguish of highways, tracks and cycleways are very hard to see, everything is white.

**Comment by knikel** [comment]
@richlv, @polarbearing: Direction indication in the map is on its way.

@ligfietser Well, the *mapbox-gl-js* library we have in the viewer does use the underlying OSM data as a source layer, it does look visually different though. We're also using on of the _standard_ styles. In the future we'll have different styles that you'd be able to switch between and the standard style will be a bit more visually refined. You can read up more about the technology here if it interests you here: https://www.mapbox.com/developers/vector-tiles/mapbox-streets/#Overview

**Comment by ligfietser** [comment]
@knikel Looking forward for those different styles. Where a single photo is taken is not rendered on the map anymore. In the old viewer you could see a small blue spot but now it is invisible.
In JOSM I have used the mapillary blue lines tms layer http://{switch:a,b,c}.tiles.mapillary.com/{zoom}/{x}/{y} but this seems not updated anymore. Any idea how to get a recent tms layer in josm?

**Comment by richlv** [comment]
displaying the direction also seems to be requested in issue #1404

**Comment by knikel** [comment]
@richlv, @polarbearing:  The direction is now displayed on a map using this FOV marker:
![fov-marker](https://cloud.githubusercontent.com/assets/1574656/11438752/3f9d01ea-94f7-11e5-91a0-2b317d71a646.png)

@ligfietser: I've tweaked the styles do better reflect roads. However we won't be adding more styles to the map just yet.

Regarding the raster tiles, we track it internally, it relates to #1366
