### ISSUE TITLE
Recent manual uploads lost timestamp

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1041]
All of my most recent manual uploads are withouth timestamps on Mapillary, and are now ordered by latitude instead of by timestamp.

Examples:
- http://www.mapillary.com/map/im/WMaWlYhny-mHBJ6x6m-edA
- http://www.mapillary.com/map/im/yKIw8US5edPn7S1AJa3iXw
- http://www.mapillary.com/map/im/5d4tog_IgVevZv6Oswnrpw
- http://www.mapillary.com/map/im/bn8bh9dUcq6QpastZsE4_g (this one _looks_ mostly ok, because the sequence is mostly northbound, but the images are in reverse order)

This seems to only be a problem for uploads after Wednesday 27, earlier uploads such as http://www.mapillary.com/map/im/REZuwwB_nwLT6GQOpGhA5A are OK.

The only thing I can think of I have done differently, is that I changed the maximum upload limit from 100 to 1000. All sequences look fine in GeoSetter and in the upload previewer.

**Comment by ybkuang** [comment]
@pbb72 Thanks for reporting! It is a glitch in our processing. We are re-processing your sequences now. The dates are corrected and the lines will be updated soon!

**Comment by it4workflow** [comment]
@ybkuang my sequence If90FbdVODMsU1kTzo1GzQ has the same problems: all dates are 1970-01-01.
and two images "jump" 3-4kms?

**Comment by pbb72** [comment]
Cool! Thanks for the quick fix!

**Comment by it4workflow** [comment]
@pbb72 please open this issue again and leave mapillary close it when they correct all sequences since Wednesday (after they start their new beta)

**Comment by ybkuang** [comment]
@it4workflow Sorry about this! We will do a proper rerun for all sequences in-between the glitches and the fix.

**Comment by AllenGraetz** [comment]
Thank you for the fix.  I have encountered a similar problem.  I'll be sure to follow up this week once the servers have had time to reprocess the images.

**Comment by pbb72** [comment]
@it4workflow @AllenGraetz did you run into the problem any more in the last year? It seems to me this bug is properly solved.

**Comment by it4workflow** [comment]
@pbb72 since I have not uploaded so many pictures last year, I can't say anything

**Comment by ybkuang** [comment]
@it4workflow @AllenGraetz I have opened an internal issues to reprocess images with wrong timestamps. We will bundle it with other processing later on to ensure that it is cost effective. Sorry for the delay.
