### ISSUE TITLE
[Beta] Comments on the responsive design

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1043]
*This is written from the map-view perspective, but the same comments can be applied to the photo-view.*

1:
On screens smaller than 690px wide the photo and the buttons, filters, comments, etc. hereinafter referred to as 'the sidebar items' are placed under the map. This all works fine, as long as the screen doesn't get to narrow. On a phone in portrait mode it would look better if the side bar items were rendered under the photo.
![schermafbeelding 2015-05-30 om 13 38 15](https://cloud.githubusercontent.com/assets/1449609/7897242/939cf194-06d4-11e5-9cb2-90b37f3fb3e9.png)

2:
If you expand all side bar items the page can get longer than the browser window and scrolling becomes possible. This doesn't look good on screens wider than 690px were the side bar items are right of the main content. (on smaller screens where the side bar items are under the main content it's not so much a problem) I think that on wider screens the map (or photo) and the headerbar shouldn't move and the scrolling should be limited to the side bar items.

**Comment by iav** [comment]
Please, make possible to resize parts manualy, by dragging border with mouse or finger on touch screen.

**Comment by knikel** [comment]
@de-vries These issues have been addressed in the new viewer, should look and behave much better now.

@iav We don't currently have plans for doing this in the main viewer. But added this as an idea for and editor redesign.
