### ISSUE TITLE
Please, add a photos of recommended phone mounts on "Capture Instructions" page

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1049]
Please, add a photos of recommended phone mounts on "Capture Instructions" page.
After I try to start capture on my car I discover there are some problems with car mount:
- phone prevents to see a road good enough
- phone vibration
- impossible to set desired angle
- part of mount takes place on photos
- part of car placed on photos
- too far from windshield (reflections, or auto-focus takes a shield as target)

There are tons of types of mounts on every local shop, and 1000s on ebay and internet-shops.

Please, post photos of mounts that can be good for cars - and, maybe, for other type of transport mappers use.

**Comment by jesolem** [comment]
We're working on a user guide details like these. @travel193  is on it.

**Comment by pyrog** [comment]
> phone vibration

:+1: 

> too far from windshield (reflections, or auto-focus takes a shield as target)

You could set focus to infinity :smile:

**Comment by travel193** [comment]
Hi @iav ,

Good suggestions. We have a list of mounts [here](https://github.com/mapillary/UserGuide/wiki/Recommended-Mounts). We will add to it as users suggest different ones.
If you need a better mount for your car, send us your address and will will ship one to you.

For capture instructions, please see the [capturing section](https://github.com/mapillary/UserGuide/wiki/Capturing) of the wiki. Again, this section will get better and better the more users share their tips & tricks.
