### ISSUE TITLE
Flagging: here should be an option to flag the complete sequence

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1053]
<strike>I'm trying to flag an image. While I can switch the radio buttons between "rotated, blurred, hidden, cut", I cannot select the button for "Other", nor can I enter the text. (Firefox/Linux).</strike>

Also there should be an option to flag the complete sequence (which in the case here has both poor location and poor content).

**Comment by polarbearing** [comment]
This has either been fixed, or I cannot reproduce it anymore after a firefox update.

**Comment by knikel** [comment]
@angelday something to consider.

**Comment by angelday** [comment]
> Also there should be an option to flag the complete sequence (which in the case here has both poor location and poor content).

@polarbearing to delete or to report? We actually will have both, soon. In the mean time I'll leave this ticket open.

**Comment by nickplesha** [comment]
The ability to delete whole sequences has been added to the editor.
