### ISSUE TITLE
Manual Upload - Initial Page Hanging

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1054]
Today when I go to the manual upload page in Chrome, I get the message about looking for uploads and it just keeps looking and looking and looking.  I have logged out and logged back in.  Any other suggestions for a work around?

Any other information you need to reproduce this?  Or do you see it too right off the bat?  Thank you.

**Comment by ahzf** [comment]
1) Same problem here for me... :(
2) I don't know if this is really related, but the last upload which made it on the map looks really strange...
![mapillary dammthal dornburg camburg](https://cloud.githubusercontent.com/assets/285458/7912181/82656df6-0865-11e5-9a3e-067a3b7aad37.png)
3) Currently I don't know if the latest uploads really made it to your servers, as the uploader was hanging after pressing "publish".

Best from Jena
 Achim

**Comment by ybkuang** [comment]
@ahzf 2) is related to #1041. I will fix that.

**Comment by AllenGraetz** [comment]
When I get back home tonight, I'll re-check the bug I mentioned.  I'll be sure to check it in other browsers.

@ahzf, #3 is a good question.  I'm not sure how their upload queue works.  From it's previous behaviors, it does appear to queue up the upload to wait for a confirmation on publishing it.  I do not know how long they remain in that queue.  

In fact, #3 may be what is causing the #1 issue.   That is, something is wrong with the to publish queue item(s).  That may be why the manual upload screen is hanging.   

@ybkuang if there is any other information that would be helpful for this bug, please let me know.

**Comment by knikel** [comment]
Since these bugs been reported there were a lot of things fixed in the manual uploader. Is this still an issue?

**Comment by knikel** [comment]
Closing; Should be fixed, if this is still happening, let me know.

**Comment by AllenGraetz** [comment]
Thank you.   I haven't noticed any problems for quite awhile.
