### ISSUE TITLE
What's wrong with my exif data and how do I fix it?

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1055]
This is one of the photos I made today: 
![file0180](https://cloud.githubusercontent.com/assets/1449609/7904402/0be2c208-07f9-11e5-8599-5236fba98de4.JPG)
I've added the coords from a GPX file and there is a time stamp, but the manual upload page refuses them.

**Comment by ybkuang** [comment]
@de-vries what did you use to edit the EXIF? The javascript parser we use sometimes fails to recognize after edits.

**Comment by de-vries** [comment]
First I used [Phatch](http://photobatch.stani.be/) to shift the date 3 days (the camera had the wrong date) then I used the JOSM photoadjust plugin to align the photos with the gpx file.

For other people that had similar issues the solution was to insert "-GPSVersionID=2.3.0.0" in the meta data, but in my photos that tag is already present.

**Comment by ybkuang** [comment]
@de-vries We updated the exif lib. Can you double-check and see if it works now?

**Comment by de-vries** [comment]
I don't get  these exif errors anymore, but I didn't go trough with the upload because I'm trying to remove the fish-eye effect to see if that improves the images. I'll let you know later today.

**Comment by de-vries** [comment]
I think this is fixed now
