### ISSUE TITLE
Suggestion: add "manual upload" from the app

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#1056]
Sometimes I use the android camera app (HDR mode…).
It will fine if we could select a folder or pictures and upload them to Mapillary servers.

Could be done either from the **Mapillary app** menu, or from **another app** (Galery, My files…) with the share button :smile:

**Comment by jesolem** [comment]
@peterneubauer can investigate on Android. On iOS not possible since the file picker does not give originals with EXIF.

**Comment by peterneubauer** [comment]
In principle this is possible, extracting/writing the EXIF data needed and moving these images into the mapillary folder. However, maybe you can as well use the web uploader, or write a little dedicated mobile uploading app that does exactly the same things as the python scripts to cover this? https://github.com/mapillary/mapillary_tools/tree/master/python
