### ISSUE TITLE
Add tutorial for pre-upload-photo-editing

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1057]
@travel193 Here is an idea for a new chapter in your tutorial:

To much pre-upload-photo-editing may interfere with the automated photo processing so it might be a good idea to write something about it. Possible subjects:
- what kind of edits are (not) desirable?
- tools, methods, workflows
- gps edits (GeoSetter, PhotoAdjust)
- Image edits (lens distortion, whit-balance)
- blurring
- Batch processing

Quick question for now:
I'm about to remove the fish-eye effect from some photos, is this desirable?

**Comment by jesolem** [comment]
> I'm about to remove the fish-eye effect from some photos, is this desirable?

Yes. Note that for some cameras that we have calibrated (GoPro models), we do it on our side too.

**Comment by ybkuang** [comment]
To be a bit more specific, our server side will correct fish-eye effects for GoPro Hero2 and GoPro Hero 3.

**Comment by de-vries** [comment]
> Note that for some cameras that we have calibrated (GoPro models), we do it on our side too.

Any chance you'll add calibration for the rollei 5s? Because although I'm getting reasonable results, I can't figure out the method for batch processing them and I'm getting close to patience level giving up.

**Comment by ybkuang** [comment]
@de-vries We would love to integrate rollei 5s into the correction pipeline. Have you already calibrate your rollei 5s?  If not, it would be great that if you can take photos of a patten and send to us. We can run the calibration here and see if the results are good enough to integrate. To do so, you can follow 
Step 2) and Step 3) in this tutorial http://www.janeriksolem.net/2014/05/how-to-calibrate-camera-with-opencv-and.html.

**Comment by de-vries** [comment]
thanx for that link. I remembered that post, but couldn't find it back

**Comment by de-vries** [comment]
Well, that didn't make me much wiser... I've send the photos to hello@M. let me know if it was sufficient.

**Comment by ybkuang** [comment]
Thanks. Got them! Will test soon and let you know how it goes!

**Comment by ybkuang** [comment]
@de-vries just tried the calibration. The result is not that great. Can you help us take one more set of images such that the placement of the checkerboard follows the images shown in this link http://www.vision.caltech.edu/bouguetj/calib_doc/htmls/example.html? Thanks for the time.

**Comment by de-vries** [comment]
@ybkuang I'll do, first thing tomorrow. From that link I understand that you need the photos (at least 20) to be more close-up than the ones I send you. If there are any more requirements please let me know.

**Comment by travel193** [comment]
Great suggestions @de-vries . I'll add them in.

**Comment by de-vries** [comment]
@ybkuang I've just send you a new batch of photos

@travel193 [here](https://github.com/mapillary/mapillary_issues/issues/561#issuecomment-88104637) I've wrote something about editing geodata, maybe you can use it.

**Comment by travel193** [comment]
Brilliant! Will definitely help in the writeup @de-vries

**Comment by ybkuang** [comment]
@de-vries Thanks. Will look at them very soon!
