### ISSUE TITLE
After successfully uploaded with the Script, its only in activity and not on the map

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1060]
Hey

i uploaded couple pictures with the Python Script.
Now i see my upload under the Profile-Activity
http://www.mapillary.com/#/map/s/D5zD01etWhClJEt7ZIytDA
but, it's not in the map and under my Regular profile

,-(

Cheers

**Comment by domdomegg** [comment]
Well done on mapping your whole town! That's amazing.

I find when I upload with the Python script it does take a couple more days for processing, perhaps allow a few more days as they are I believe going through more upgrades with the new vector map.

**Comment by thoschu96** [comment]
thx domdomegg ..

Yep.. Took one more then, then it was on the Map available.
Got realy confused to see it in Activity and not in the Map at same time ...
