### ISSUE TITLE
False blurs of "do not overtake" road sign

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1061]
I noticed a considerable number of false blurs of "do not overtake" road signs (http://commons.wikimedia.org/wiki/File:Italian_traffic_signs_-_divieto_di_sorpasso.svg)  in my photos in Italy.
Just one example: http://www.mapillary.com/map/im/FqrPo-H4IWP-D79hef5mNA

**Comment by ybkuang** [comment]
Closing this. Refers to #635.
