### ISSUE TITLE
sometime blur editor work with shift

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1063]
Sometimes - rarely - blur editor cursor detched from mouse cursor
example of such foto: http://www.mapillary.com/map/b/BWykptwM_2qCazHeqKnXEw
On attached screenshot I move  mouse cursor to mark a plate - and see where blur mark placed
![mapillary edit blurring](https://cloud.githubusercontent.com/assets/325961/7970925/e80f682e-0a49-11e5-8b21-578568f922d0.png)

**Comment by ybkuang** [comment]
This could be related to non-4:3 ratio of the image.

**Comment by domdomegg** [comment]
Any non 4:3 ratio photo does this, including photo spheres & panoramas.
See #157 #232 #389 #494 #553 #787

**Comment by knikel** [comment]
This has been fixed in the new viewer, thanks for the feedback!
