### ISSUE TITLE
links/url's don't work

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1065]
1) A while ago I got an email that someone commented on one of my photos. There was a link with some tracking things in it that redirected me to: http://www.mapillary.com/map/im/XeIHX8_i9ze2wHH51CIezA which gave me a page that said:
![selectie_057](https://cloud.githubusercontent.com/assets/1449609/7992424/8c9c543c-0aff-11e5-897c-9b98ceb4476f.png)
When is add /# to the url (http://www.mapillary.com/#/map/im/XeIHX8_i9ze2wHH51CIezA) that will get me this:
![selectie_059](https://cloud.githubusercontent.com/assets/1449609/7992449/cadff64a-0aff-11e5-912a-1bb04ba9da33.png)
Clicking the same link from my activity list (http://www.mapillary.com/#/map/im/XeIHX8_i9ze2wHH51CIezA?z=10) does work as supposed.
Adding /# and the zoom level to the broken fixes it.

2) In my browser I have a bookmark to the map view of my city: http://www.mapillary.com/map/im/bbox/51.655305889458916/51.7095869096419/5.25421142578125/5.433511734008789
Since yesterday it only gives me in plain text: 'Image not found'. Refreshing, clearing cache or copying the link to another browser doesn't change anything.
I've added /# to the url, which immediately redirects to the same url without /# and that fixed my bookmark. But I can't share a link by just copying the url.

3) I've noticed before (at random occasions) that sometimes links don't work while the same link from within Mapillary do work.

**Comment by knikel** [comment]
@de-vries We had an issue with serving pages without `#`, this has been fixed, all your links you posted are working correctly. Really sorry about the hassle!
