### ISSUE TITLE
If no direction is given, assume direction of the sequence

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1066]
If no compass direction is given you should always assume that the camera was pointing in the direction of the sequence. This will lead in most cases to a correct guess, while current approach of setting it to north only works in 1 out of 360 times.

Additionally, you could offer an opt-out on the manual upload page.

**Comment by ybkuang** [comment]
Good suggestion! We will work on that in the next version of the uploader. It needs some change in the backend too to handle this properly.

**Comment by gyllen** [comment]
We thought about this but after analyzing our data the conclusion is that it would lead to to many errors.

The `SfM` algorithms is helping out a lot also to determine the "real" direction
