### ISSUE TITLE
Bug Report: Photos are NOT in correct order, Pin disappears and ...

### ISSUE THREAD

**Issue by atpl-pilot** [mapillary/mapillary_issues#1067]
Please check Sequence Key: ytrxilqQ130jRA4-9OhtPQ
Beginning with photo: Image Key: yGL1y8NmJh3Xx9dhyzUHuA
After clicking the forward button, the pin disappears from the map, and 4 clicks more you are out of route, jumping to something different.

**Comment by ybkuang** [comment]
@atpl-pilot This looks good now. Closing
