### ISSUE TITLE
Can't see my uploaded photos

### ISSUE THREAD

**Issue by Chivos** [mapillary/mapillary_issues#1068]
I made my first tries these days, but I can't see any photos I've uploaded. However I can see others people pictures...

I forgot : I can see my photos only in the iD editor... weird.

Did I miss something in Mapillary or is it a bug ?

Thanks

**Comment by ybkuang** [comment]
Sorry about this. Our processing was lagging a bit last few days. Do you see your photos now?

**Comment by Chivos** [comment]
Still not.
This is the photos I can't see : https://www.mapillary.com/profile/chivos/activity
Thanks !

**Comment by Chivos** [comment]
Do you have some news on this bug ? Is it something wrong with my profile ? 

Now that I will have my Garmin Virb, it'd be sad of not being able to view the result !

Thanks.

**Comment by jesolem** [comment]
Is this still a problem? If so, @gyllen or @peterneubauer can you investigate?

**Comment by Chivos** [comment]
Yes. I tried logged in, logged out, another computer, iOS app, and nothing each time...

**Comment by peterneubauer** [comment]
@gyllen it might be the /s/ call that is not returning?

**Comment by gyllen** [comment]
Looking into this, very strange. Its only for this user. @Chivos how do you upload photos (this will help me in my debug process)

**Comment by gyllen** [comment]
@peterneubauer This seems to be an error in GS for some reason none of chivos images shows up there

**Comment by Chivos** [comment]
For the first sequences, I've been using the Android app (from a Nexus 5).  In the last sequences, I used the manual upload and the python script.
Thanks !

**Comment by Chivos** [comment]
Everything seems to be working perfectly since the new viewer is fully released !

And great job btw !

**Comment by gyllen** [comment]
Thanks, closing
