### ISSUE TITLE
Link from "Your upload is on the map" email does not work.

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#1069]
Clicking on the map image brings me to https://www.mapillary.com/map/im/15/46.515733499999996/6.624835 which does not work and only shows "Image not found" (see attached screenshot).
Clicking on the images below the map brings me to the correct images.

This is the sequence in question: http://www.mapillary.com/map/im/60qqQvv3rhU7b7Hd103tpw

OS X 10.10.4, Safari Version 8.0.7 (10600.7.7), Mail Version 8.2 (2100)

![screen shot 2015-06-05 at 22 12 10](https://cloud.githubusercontent.com/assets/1651235/8014311/f898c762-0bcf-11e5-8aaa-020ae95ac98d.PNG)

**Comment by de-vries** [comment]
related to #1065?

**Comment by knikel** [comment]
@habi This should be fixed, sorry about the hassle. We had a problem with serving certain urls.

**Comment by habi** [comment]
@knikel No hassle, I just wanted to let you know.
