### ISSUE TITLE
Keys to navigate by photos

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1072]
Now I was editing my tracks to make visible correct traffic signs, and I was tired of press the mouse button to aprove pics without traffic signs in a tertiary road, clic clic clic.Why the navigation does not work with keys like arrows , + ,- space, enter... ?

**Comment by knikel** [comment]
@yopaseopor You can work with traffic sign annotation into the viewer in a much easier way now and you can navigate the areas using arrow keys (top - forward, right - step right, bottom - backward, left - step left, shift + left - turn left, shift + right - turn right, shift + bottom - turn around). There are no shortcuts however for approving, etc. Hope that helps at least a little?

**Comment by knikel** [comment]
In the upcoming version of mapillary.com we're using `mapillary-js` which has keyboard support. I'm closing this in favor #472. Since this is functionality that we already have implemented. Will be exposed soon.
