### ISSUE TITLE
Exif editor for Mac?

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1076]
I am wondering if anyone could recommend a good, free EXIF location editor for Mac. My main phone's GPS has broken so need to tag 400 photos a week, and also sometimes need to fix long tunnels which are award to do in Mapillary editor, any suggestions?

Thanks in advance :)

**Comment by de-vries** [comment]
[JOSM](http://wiki.openstreetmap.org/wiki/JOSM/Mac) with the [PhotoAdjust](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/PhotoAdjust) plugin

**Comment by domdomegg** [comment]
Thank you, I have just installed in and am trying it now

**Comment by domdomegg** [comment]
It works great, I would recommend to others needing something like this too.

**Comment by domdomegg** [comment]
Wait... How do you save the images? I just did about 100, and can't figure out a way to save them.

**Comment by domdomegg** [comment]
Figured it out - after I deleted all the work I did :unamused:

Install the plugins:
'commons-imaging'
'photo_geotagging'

Then restart

Then right click on image layer when finished, and press write headers

**Comment by de-vries** [comment]
Sorry, I could have told you that....

**Comment by domdomegg** [comment]
No problem, sorted now :)
