### ISSUE TITLE
Edit blurring button in traffic sign game

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1077]
Have an 'edit blurring button' in the traffic sign game, as very often there are images that come up that do need to be blurred and it would be useful to have a shortcut.

**Comment by knikel** [comment]
We're very likely to have a blurring game after we release a new version of Traffic Sign Game. Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
