### ISSUE TITLE
Just one photo in sequence on auto-focus mode.

### ISSUE THREAD

**Issue by VikDD** [mapillary/mapillary_issues#1078]
Tomorrow I set "settings/Camera"->"Focus mode" to auto, today on morning set phone to cradle  in car and went to work, but on end I see just one photo was shooted. I try create sequence again and again, but every time was shooted just one photo. After set camera mode to any exept for auto - all was fine.
----
Phone data:
Samsung GT-I9295
Android 5.0.1
ver. I9295XXUDOB4
build LRX22C.I9295XXUDOB4

**Comment by domdomegg** [comment]
I don't know why this is happening. If the other focus modes other than auto work fine, maybe just try that as a workaround for now. Generally when in the car 'infinity' focus looks good, but differs from phone to phone so play around with the ones that do work for you.
