### ISSUE TITLE
[Beta] Non-360 panoramas treated weirdly

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1079]
Panoramas that aren't 360 act as if they are (go all the way round just with weird distortion)

Example:
http://www.mapillary.com/map/imgl/hHDFAFm5dltXJggMotynnQ/map

**Comment by ybkuang** [comment]
It could be related to te aspect ratio of the image that it got mistreated as pano. Will look into it.

**Comment by domdomegg** [comment]
The image is a panorama. The bug seems to be fixed now - what I meant was that you could go all the way round and it would just extend the ends with horizontal lines.
