### ISSUE TITLE
Assistant (to-do list) for upload "streets"

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#108]
Nowadays Mapillary catches geographic data with EXIF of the photos and then system organize and order photos in a street.
But knowing one target of Mapillary are the streets why not is possible to include an assistant like "to-do list of a street" (photo forward,photo backward, photo up, photo down...) .If I had a list of what is missing then I will be able to take the pictures of that.

**Comment by gyllen** [comment]
When API v2 is released this would be able to be implemented as an external tool. I would encourage that.
