### ISSUE TITLE
[question] Quality or quantity?

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1083]
Lately I spend a lot of time on improving geo-data before I upload my sequences. I do this because I think Mapillary's usefulness decreases at places where there are lots of overlapping sequences with poor quality geo-data. 

At SotmUS you [told](https://youtu.be/BjI2JUN1N-8?t=9m2s) that you are working on automatically improving geo-data and then there is [this guy](https://vimeo.com/106847615#t=1080s) who also got pretty good results.

As working on the geo-data takes a lot of time I could potentially double or triple the number of photos I upload.

So my question is: since you're working on automating this is it still worth spending time on it? and how far are you with this?

**Comment by ybkuang** [comment]
@de-vries We will be releasing our pipeline for improving geo-data in the near future. It will be able to correct/refine gps positions and compass of the images given that the original geo-data are not far-off (I would say something like <30 meters)
Assuming that we are aware of that geo-data have been edited by users (e.g. through our web-editors), the edits will be of great value to our algorithm. We will treat those information with high confidence than recorded in EXIF. 
When you are editing EXIF before uploading, the algorithm will also make good use of that. 

To answer your question,  the best scenario will be that you first upload the photos without manual edits. After our processing finish, notifications along with a short list of areas (while the algorithm fails) for manual inspection will be send to you. You can then contribute your edits if you have time, a second round of processing will be triggered based on your edits. (It is a rough idea, we will elaborate and work on this with all your great feedbacks ;) )

**Comment by de-vries** [comment]
I'm definitely looking forward to this!

>  the best scenario will be that you first upload the photos without manual edits. After our processing finish, notifications along with a short list of areas (while the algorithm fails) for manual inspection will be send to you. You can then contribute your edits if you have time, a second round of processing will be triggered based on your edits

Sounds like a good approach. I would like to add the suggestion to make it possible to do the editing of already uploaded sequences offline. The online editor is fine for small edits, but I edit my sequences in JOSM as this gives me some advantages like hotkeys, fullscreen map, setting my own background, etc. 
So I'm hoping such a feature will make it to the [GSoC project](http://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2015/Mapillary_plugin_for_JOSM). Another option would be to have people download GPX-files and then let them resubmit modified versions.

**Comment by domdomegg** [comment]
>  The online editor is fine for small edits, but I edit my sequences in JOSM as this gives me some advantages like hotkeys, fullscreen map, setting my own background, etc. 
So I'm hoping such a feature will make it to the GSoC project. Another option would be to have people download GPX-files and then let them resubmit modified versions.

:+1:

**Comment by jesolem** [comment]
@de-vries question answered? Should we close?

**Comment by de-vries** [comment]
yup
