### ISSUE TITLE
Traffic signs have an offset due to lens distortion correction

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1084]
@ybkuang has implemented a lens distortion correction for the Rollei S5 and now signs on all photos from this camera have an offset. It looks like you're detecting the signs on the originals and displaying them on the corrected photos.

![selectie_077](https://cloud.githubusercontent.com/assets/1449609/8164284/4fd618a8-1388-11e5-8092-edd2a9ffc448.png)
http://www.mapillary.com/map/im/26Z-e6rAfGxD1g3vNtqjAg

**Comment by ybkuang** [comment]
@de-vries Thanks for reporting this. It is true that we are detecting with original but showing the corrected version. We will fix this in the future.

**Comment by de-vries** [comment]
The issue seems fixed on [photos made on june 21](http://www.mapillary.com/map/im/ol-NHCiu6m4XFEaZcRpKrw) (uploaded june 22) and later. On older photos however, the issue is still present, or at least up to [june 16](http://www.mapillary.com/map/im/DRobjVJZxw7W_qaNtPmUCg) Is it possible to reprocess them?

**Comment by ybkuang** [comment]
@de-vries Yes. Adding this to my to-do list.

**Comment by ybkuang** [comment]
This should be fixed now. Closing.
