### ISSUE TITLE
mapillary.com/map/settings/applications is broken

### ISSUE THREAD

**Issue by PalmerAL** [mapillary/mapillary_issues#1085]
If I'm not signed in, I get this:

![screen shot 2015-06-15 at 2 47 56 pm](https://cloud.githubusercontent.com/assets/10314059/8169193/9409384a-136d-11e5-8bdb-b9a683051fef.png)

In the console, I get:
<code>
Error: CurrentUser.info.$promise is undefined
@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-1bf44447.js:7180:7
e@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:913:56
He/this.$get</</<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:954:166
M@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:935:373
h@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:929:213
C/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:928:249
$ViewDirectiveFill/<.compile/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:5323:9
aa@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:947:133
M@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:936:172
h@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:929:213
C/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:928:249
updateView@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:5256:23
$ViewDirective/directive.compile/</<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:5218:11
Re/this.$get</l.prototype.$broadcast@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1009:244
transitionTo/$state.transition<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:4608:11
f/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:992:425
Re/this.$get</l.prototype.$eval@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1006:395
Re/this.$get</l.prototype.$digest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1003:466
Re/this.$get</l.prototype.$apply@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1007:159
l@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:959:487
N@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:964:99
yf/</B.onload@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:965:124
 <div ui-view="">
</code>

If I am signed in, I just get a blank page, and the following in the console:

<code>
Error: ref is undefined
getGeoNotifications/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-1bf44447.js:7167:23
v/</e[k]/n<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1215:133
f/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:992:425
Re/this.$get</l.prototype.$eval@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1006:395
Re/this.$get</l.prototype.$digest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1003:466
Re/this.$get</l.prototype.$apply@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:1007:159
l@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:959:487
N@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:964:99
yf/</B.onload@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-7563a11c.js:965:124
</code>

**Comment by knikel** [comment]
:wrench: Fixed. Thanks for catching this one!
