### ISSUE TITLE
Image view on new beta website lacks zoom buttons

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1087]
Making the image bigger to begin with is nice, but we still need to be able to zoom in the image like we can in the current stable interface.

Using firefox 38.0.5 on Linux.

**Comment by knikel** [comment]
Yup, the remaining functionality of the current viewer will be ported to the new one.

**Comment by iav** [comment]
Please, add zoom in-out with mouse wheel, when you dive into this code.

**Comment by knikel** [comment]
This will be feature of upcoming mapillary.com update, which is built on top of `mapillary-js` (that functionality is already there, check [this](blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html) demo out)

**Comment by pbb72** [comment]
@knikel where is the zoom feature? It may be me who is overlooking it, but I am not able to zoom into photos.

**Comment by oscarlorentzon** [comment]
Zooming is only supported for panoramas in MapilllaryJs at the moment. Pan/tilt/zoom in regular photos is tracked here: mapillary/mapillary-js#112
