### ISSUE TITLE
Multiline image title is croped in new beta web view

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1088]
For example http://www.mapillary.com/map/imgl/lBMYKFQQn4tHEtV8kTD2sQ/photo
only "Ormonde Street Kilkenny" is readable but I can see there's more text beneath it.

Using firefox 38.0.5 on Linux.

**Comment by knikel** [comment]
We've don't support location names for photos for the time being. We'll add a replacement feature at when we get to that.
