### ISSUE TITLE
Unclear how to use ID editor

### ISSUE THREAD

**Issue by jaakla** [mapillary/mapillary_issues#1089]
From descriptions I get that I read that there should be "Mapillary photos and traffic signs for easy editing" in your ID editor. The default map view, also location where I have seen some Mapilliary tracks is just as ordinary ID editor and OSM data, I do not see any photos or traffic signs from Mapilliary, or any reference to Mapilliary-specific features there. Layers view has just usual choices etc.

Maybe it's only me blind, or it is unclear to users how it is supposed to work.

**Comment by jesolem** [comment]
@peterneubauer Can you add a description and some screenshots to the User Guide wiki?

**Comment by peterneubauer** [comment]
@jaakla you can see the process here, http://blog.mapillary.com/update/2015/06/02/id-signs.html - the sign layer is not yet merged into the main ID branch, but the image layer should be working http://www.openstreetmap.org/edit#map=15/55.5969/13.0120
![openstreetmap](https://cloud.githubusercontent.com/assets/11977/8203729/3fa7a098-14e4-11e5-9980-66e3e5918ff1.png)

**Comment by jaakla** [comment]
The question was not really how to use it. The problem was that I was indeed looking through background and data layers and failed to notice the selection, so I was so frustrated that I even bothered to file a bug report. Going through all your blogs and wikis to find is not good solution, why not to add same screenshot (perhaps cropped one) right to http://www.mapillary.com/osm.html for example, where users come anyway?

**Comment by peterneubauer** [comment]
https://www.mapillary.com/osm.html updated.
