### ISSUE TITLE
Downloaded pictures don't contain location and direction.

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1090]
When you download a picture from the website, this picture doesn't contain the location and the direction.

**Comment by jesolem** [comment]
You need to get that from the API.

**Comment by Stefal** [comment]
From the api ? Not an easy way. I just wanted to use a few pictures in Josm.

**Comment by jesolem** [comment]
There is now a JOSM plugin. Does that solve your problem @Stefal ?
