### ISSUE TITLE
Strange behaviour of the activity overview tab

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1091]
On the website, the Activity overview tab's behaviour is quite odd:

- Not all the activity is reported there. Not all blurring requests appear, for example: yesterday, I did something like 150 blurring requests and the tab just shows me that "I requested 10 blurs"

- Approval/rejections notifications tend to appear and disappear randomly. For example, an hour ago, " you got 138 blurs approved" was appearing, on top of another one concerning another country: " you got 9 blurs approved". Right now, only "you got 9 blurs approved" appears, the other one has disappeared.

The same issue seems to occur with change requests.
Should examples be needed please let me know and I'll do some screenshots.

**Comment by gyllen** [comment]
@shlublu Looking at your profile the count does look strange indeed. Does the count match the emails you are getting?

**Comment by de-vries** [comment]
I'm seeing similar behaviour on my activity page last days.

**Comment by gyllen** [comment]
Is this something that has changed lately?

**Comment by de-vries** [comment]
I noticed this about a week ago, but didn't give it much thought. Also I normally don't keep an eye on the activity page.

**Comment by shlublu** [comment]
@gyllen Well, this morning just before opening this ticket, I had "shlublu got 138 blurs approved" just between "shlublu got 9 blurs approved" and "shlublu requested 2 change sets". Then the "138" thing disappeared. 

The same happened yesterday with other actions.

**Comment by de-vries** [comment]
some facts:

- yesterday I made 9 change sets, got an email that I requested 2.
- this morning I made 20/30 blur requests.
- this morning I received an email that 14 change sets were approved.

none of this showed up on my activity page

**Comment by gyllen** [comment]
We discovered an issue with the activity feed, this is now solved, please reopen if you see any strangess in feed again
