### ISSUE TITLE
Web viewer doesn't respect the picture original ratio

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1092]
The pictures I upload have a 16/9 ratio, but the viewer (actual & beta) still stretch the picture : 
http://www.mapillary.com/map/im/MUrOuU5xvLbO0oXbnnPQtA

**Comment by jesolem** [comment]
@knikel is working on this right now.

**Comment by knikel** [comment]
This has been fixed @Stefal check out the new viewer and see how you like it :smiley:
