### ISSUE TITLE
Approved blurring requests not actually blurred

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1093]
I have seen today that 138 of the blurring requests I made earlier had been approved. 

I decided to do some chacking, so I randomly selected some (about 20 or 25) of pictures I submitted blurring requests for. As I made roughly 150 blurring requests, I expected "most" of them to actually be blurred. 
I couldn't find another way to control as there is no way to determine which requests was actually approved.

It appears that none of the pictures I controlled was actually blurred. 
Is there a delay between the approval and the actual effect of a blurring request?

Thanks!

**Comment by travel193** [comment]
Hi @shlublu ,
Firstly, thanks for all the blurs you have submitted and your attention to detail. 
I still have more to approve, but the 138 that have been approved so far are simply awaiting processing. It will take a little while for the blurring to take place, starting at the higher resolution version of the photo and eventually processing the thumbnails.

**Comment by shlublu** [comment]
Hello @travel193 and thanks for answering so quickly.

This fully answer my question as I was just wondering whether "approved" meant "done" or "we're going to do it". Which is fine!

(Sorry for giving you so much manual work! Hopefully, soon, the neural network will have fully got it :) )

**Comment by jesolem** [comment]
@shlublu Approved means done, but it takes time for the caching through Amazon's CDN to fully update.
