### ISSUE TITLE
Feature request: ability to preview or delete content right after posting

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1094]
I tried yesterday the uploading of a video in a small street.

The video in itself is OK, but the result on Mapillary happens to be useless: pictures are blurred, or  oriented in a way there are useless, etc. I think this is not an issue on Mapillary side but on mine: my GPX tracker was set in a way is was not polling the GPS position often enough.

As there is no way to determine what the result will be when updaloding a video, it would be really nice to either have a preview feature *of the resulting images at the end* or a way to delete uploaded content a short while after having it added to the map. Because here, I don't endorse this content as it is simply bad, while I cannot detach it from my user name and activity tab.

The same issue could have occured with pictures with the mobile phone app in auto sync mode.

Thanks for considering this request!

**Comment by gyllen** [comment]
@shlublu You can hide it in editor.

**Comment by shlublu** [comment]
@gyllen I discovered that later. We can close this ticket. Thanks!

**Comment by gyllen** [comment]
@shlublu Awesome! Keep on mapping!
