### ISSUE TITLE
Images are uploaded in wrong order

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1095]
I have "show/upload newest pictures first" unchecked. Reviewed the first ~100 of a sequence (oldest first as desired) and then started an upload to free some space, intending to stop it before it got to the unreviewed images. But the app uploaded the newest photos first, which goes against my preference setting and probably caused some unwanted uploads.

As an aside, using a checkbox for this preference is pretty poor from an understandability standpoint. A better formulation would be "review/upload order=newest first/oldest first".

Related issues: #800 and #964.

Using android app 1.24.

**Comment by peterneubauer** [comment]
This should be working now, closing.
