### ISSUE TITLE
Reviewing large sequences on android becomes unusably slow after a few dozen pictures

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1096]
Open/review a sequence with a few hundred pictures and flick past the first few pages of photos. Scrolling gradually slows down, image frames start taking multiple seconds before displaying the correct image instead of a previously-displayed one. Scrolling to the bottom of a 600 images (20min session) sequence is pretty much impossible.

When looking at individual photos instead of the 3-columns thumbnails the effect takes a bit longer to be noticeable. The start of the review is quite responsive, but all of a sudden the next image takes 15s or more to appear, and moving back and forth becomes very sluggish.

Android app 1.24 on sony xperia z3 compact (fairly fast hardware).

**Comment by domdomegg** [comment]
This also has started happening for me on the iPhone 4S (version 3.2)

**Comment by millenbop** [comment]
Is this still an issue in the latest Android app? Peter did some optimizations with thumbnails so it should be a lot faster now.

I'll have a look on iOS if it can be optimized (pretty sure it can).

**Comment by vincentdephily** [comment]
Yes, I got the update during my holidays and things are much better now. Thanks.

**Comment by peterneubauer** [comment]
yay!
