### ISSUE TITLE
Sequence paths not shown at lower zooms

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#1097]
Some of my recent sequences (sp8962de) only get their track rendered when zoomed nearly completely in and even then only the track in question, other sequences from the same day however are not visible. See for example http://www.mapillary.com/map/im/ROjmLKmNFrM_yZl4OgeXMA

**Comment by AllenGraetz** [comment]
I have some examples I can share, too.   I do not know what their plans are but with the beta UI in the works, I would assume they'd be concentrating on making sure that is working and sunset the current UI.

**Comment by peterneubauer** [comment]
Yes, this is the tiles tat are used on higher zoom levels not being updated directly. We are changing technology to Vector tiles very soon, see http://www.mapillary.com/map/imgl/ROjmLKmNFrM_yZl4OgeXMA/photo - is that info more correct?

**Comment by millenbop** [comment]
Since we now have vector tiles, this is no longer an issue. Closing.
