### ISSUE TITLE
Stats broken for Austria & France

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1098]
http://www.mapillary.com/map/places/austria
http://www.mapillary.com/map/places/france

And perhaps some other countries.

**Comment by gyllen** [comment]
Thanks for reporting I am looking into it. We just recently changed to live stats so this is probably a part of that.

**Comment by gyllen** [comment]
Works on new website
https://www.mapillary.com/app/stats/85633147?lat=18.5351858885558&lng=-2.9710284999999885&z=2.4399869134853738
