### ISSUE TITLE
[Beta] Non-360 Panoramas can be weird

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1099]
Similar to #1079 (which happened all the time), but now only happens if you select a 360 panorama or photo sphere, then a <360 panorama, and it does not restrict to sides. This happens on both the map and image tab.

eg:
View http://www.mapillary.com/map/imgl/Xj3wrWpdRTVR5YyLHiBZEw/map
Then click on sequence next to it which goes around the sports pitch (green on map). You must click from the 360 one first! (The sequence is the one taken on June 15th).

Image:
![screen shot 2015-06-18 at 08 51 41](https://cloud.githubusercontent.com/assets/4953590/8226505/4c2ca7e2-1597-11e5-9841-4f68d91363fd.png)

**Comment by ybkuang** [comment]
@domdomegg seems that the field of view is not updated correctly (it uses the one from the previous image). Will take a look soon.

**Comment by domdomegg** [comment]
Did you fix this now, as it seems fixed for me. If so you I am happy for you to close this now.

**Comment by paulinus** [comment]
Yes that is fixed now. A parameter was not updating properly when moving from one pano to another. We fixed that. Thanks for checking!
