### ISSUE TITLE
Reorder images

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#110]
Instead of a classification, like the hide button I want a button or the possibility to "change the order" of one of the images of the changeset (coordinates are correct, but system uploaded the last one of that changeset and then the track makes a big "V") .I want to catch this photo and put in the correct order.Now only thing I can do is  "Hide Image" to avoid big "V" forms on the track.

**Comment by gyllen** [comment]
@yopaseopor @ciutadavng Is this still an issue?

**Comment by yopaseopor** [comment]
For me it is.I'm a intense "Mapillarer" so I need basic functions not only
for tracks but also by streets I'm recording.I need attach "new" images to
a existent track,reorder,join and split tracks (not request) , and remove
(not hide) some pictures of a track I have done myself (I don't know the
reasons but when I upload a track my smartphone - Sony Xperia Z3 Compact
stops to upload pictures half of the track, so in Mapillary I have two
tracks made of one track.)

I wish also a Streets Tab (like the Traffic Signs for example) with the
streets and cities I have "Mapillared" and If I've done in one or both
directions.Also an index for the streets or pieces of tracks I've missed to
do.

Thank you
Yopaseopor

**Comment by gyllen** [comment]
Adding this feedback as part of editor v2 feeback.

**Comment by ciutadavng** [comment]
For me this still an issue or an improvement.Usually my photos are old and
I wish reorder it manually (Then I can upload so data in a semiautomatic
way and then "reorder" it to match every street and every direction).Also I
wish different colors to watch my tracks than the others users when I'm
logged in .For example at my city (Vilanova i la Geltrú is a little city
but with so many data at Mapillary) my tracks are mixed up with other and
it's so difficult to "separate them" (I've Mapillared the same street , the
same place but many years ago).Calendar filter is good but different colors
would be a great idea.

On Tue, Feb 10, 2015 at 6:33 PM, Johan Gyllenspetz <notifications@github.com

**Comment by geomapper69** [comment]
Agree - a filter option to "view my tracks only", would be nice if you are mapping the same area as others.

**Comment by gyllen** [comment]
Filter is now implemented in the users profile
