### ISSUE TITLE
Website's Explore tab doesn't allow picking sequences for browsing

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1100]
Scenario:

- I go to the Explore tab of the Mapillary website

- I select any country (tested: Germany, Brazil...)

- Then I slide the map to be over any location (tested: Bordeaux, Paris, Nantes, Lyon, and some random places elsewhere...)

- At that stage I cannot select any sequence, the cursor remains in "hand" shape. So I zoom in to have a clearer view of the sequences, before selecting one.

- All sequences disappear when zooming, so I cannot select any: no Mapillary data appear anymore, just an empty map.

Note: This issue does not occur when clicking on a picture from the global activity overview and then sliding/zooming the map. It only occurs when I use the Explore tab.

**Comment by shlublu** [comment]
Hi @Knickel, I am not sure this is an enhancement as the map everywhere else in the site is used to pick sequences. And here, this is the "Explore tab". 

But should it be (so if it was never expected that users pick sequences from the explore tab), it should be mentionned as this is unclear.

**Comment by knikel** [comment]
@shlublu Locking the map and having it serve as an overview was the purpose of putting them on explore. But as you mentioned the map elsewhere is interactive, so people expect it to be fully interactive (not just zoom in/out) here too. I'll fix it in a way when pressing the map redirects you to the viewer, as it is the case with the map on the front page.

Thanks for the feedback @shlublu!

**Comment by knikel** [comment]
@shlublu This has been fixed now: http://www.mapillary.com/map/explore (You might need a force refresh)

**Comment by shlublu** [comment]
How brillaint, you guys are so fast :) It works perfectly, thanks !
