### ISSUE TITLE
Traffic sign: other_entry is missing (one way street) leading to mis-tagging as mandatory_go_straight

### ISSUE THREAD

**Issue by dekarl** [mapillary/mapillary_issues#1104]
Every blue sign with a white arrow pointing up appears to be tagged as "proceed ahead" (round with arrow) when some of them really are one way street entry signs (square with arrow or rectangular with text).
This leads to interesting "edit wars" like on this image http://www.mapillary.com/map/im/VrnyZULNZkCchA3yS0jgZA (I'm not sure how to link to the traffic game history of that image, but I've corrected the same sign twice now)
Maybe adding additional information to "other" signs can be allowed to improve this as suggested in #945.

**Comment by ybkuang** [comment]
@dekarl Thanks for pointing this out. It is in our plan to improve the traffic sign naming convention. We are considering following the convention e.g. https://en.wikipedia.org/?title=Comparison_of_European_road_signs.

**Comment by ybkuang** [comment]
This should be improved by the new [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection.
