### ISSUE TITLE
add notification about ability to switch off auto-upload

### ISSUE THREAD

**Issue by Mathiasdm** [mapillary/mapillary_issues#1106]
I had planned to do review on about ~1000 images, but it appears all of them have been uploaded already! I _think_ the app started uploading as soon as I got in range of a known wifi signal.
This includes all images, so now I apparently have to flag images to get them removed :-(

**Comment by de-vries** [comment]
It's a feature ;)
Uncheck the 'upload pictures in background' option in the settings to turn it off.

**Comment by peterneubauer** [comment]
Yup,
this is a feature to easily get started. Maybe we could add a text in the notifications that you can disable the feature.

**Comment by HolgerJeromin** [comment]
or ask the user on the first start (after login data?) which is the preferred upload mode.

**Comment by peterneubauer** [comment]
Implemented in the latest alphas.
