### ISSUE TITLE
Sequence out of order

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1107]
This picture should be the last one in the sequence:  
http://www.mapillary.com/map/im/bFU0DO6N86Lm1HD39WH2wA

But if you click on the "forward" button it will jump back up the mountain a ways and the same thing if you do it again.

I'm not sure if this contributed to the ordering problem but it is worth mentioning that these sequences were uploaded on some of the crappiest hotel wifi I've ever experienced. It took two or three days to get everything uploaded with multiple restarts.

**Comment by ireun** [comment]
I've had this a few times now... For example here: https://www.mapillary.com/map/im/Ky4fZXk-8oqPb-othlC70w Try to go backward..

**Comment by AllenGraetz** [comment]
Interesting.  I'll keep my out for this.  I think I've noticed the same thing with some of my sequences.  I blew it off at the time since the drawing of the sequence looked good.

**Comment by voschix** [comment]
I discovered a widespread image sequence problem with images from user @klimakas @klimakas. 
Two examples:
[https://www.mapillary.com/map/im/DcRwcCIaYC3x9tjox0-D8Q](https://www.mapillary.com/map/im/DcRwcCIaYC3x9tjox0-D8Q)
[https://www.mapillary.com/map/im/hzo5aXp71HWDqWSvgnLwvQ](https://www.mapillary.com/map/im/hzo5aXp71HWDqWSvgnLwvQ)
Many of his sequences from that period (around 22 August 2017) contain these out of order pictures. I contacted him directly (via the OSM mail system) and he replied that he only uploads, but never checks his photos (if I understand his reply correctly).

**Comment by ybkuang** [comment]
@voschix we are investigating this issue. @peterneubauer is this related to the the Android sequences?

**Comment by peterneubauer** [comment]
Yes,
this is a bug that was present in some Android versions last summer. We are working on adjusting the wrong timestamp in the originals and re-reading the information, resulting in a correct ordering of the sequences. I can't give a timeframe since it's a quite expensive operation backend-wise, but it's on the agenda and I'm working on it.

**Comment by peterneubauer** [comment]
These sequences are now reprocessed and look correct. Sorry for taking so long - this was an extremely long standing bug to fix. Closing this now.
