### ISSUE TITLE
Panoramic picture: 5 images out of 19 properly integrated

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1108]
Earlier today I uploaded 19 pictures taken from a fixed point in panoramic mode with the Android app. The upload went well according to the app but only five pictures were actually integrated, so most of the overlap is lost. 

I don't know if it is related but the pictures were integrated faster than usual: just a few minutes, where this is usually a 2-5 hours process. And I have no pictures "still processing" (checked after having cleared my browser's cache).

**Comment by ybkuang** [comment]
@shlublu can you share the link to that sequence?

**Comment by shlublu** [comment]
Ok, now the pictures are all there so the sequence is complete. I received no notification, neither this appears in the activity. I just noticed that because my uploaded images total increased.

So looks like this is just a problem of misleading notifications (a few part of the images quickly "added to the map" where no images were reported as "still processing").

**Comment by shlublu** [comment]
@ybkuang Sorry, we were writing at the same time. The sequence is here: http://www.mapillary.com/map/im/ktVwJyFCBxMUX8xYdaJW9Q

**Comment by ybkuang** [comment]
@shlublu closing this since it has been resolved and we have improved on our notification system.
