### ISSUE TITLE
Feature reqest: quickly change angle

### ISSUE THREAD

**Issue by rmikke** [mapillary/mapillary_issues#1110]
When the angle of image is really wrong (like, more than 90 degrees from real) it is very time consuming to correct it by clicking +/- buttons. There should be a widget allowing to quickly set it to at least eight directions (N, E, S, W, NE, SE, SW, NW) and refine the correction from there.
Or, even better, something that would allow to set any angle and +/- buttons only for fine tuning.

**Comment by rmikke** [comment]
Also, when editing an image, two things should be visible, that not necessarily visible now:
1. angle should be pictured as some arrow nearby the value. The widget described above could contain this arrow.
2. when I move to next/previous image in editor (by clicking up/down arrow on image), the map on the right should display the position of the image (now it displays the position of the first image edited, until I click on image marker on the map). Ideally, map also should be centered ob current image's marker.

Without that, I'm really unable to edit angles on my images, and as they are taken with helmet camera, some correction is surely reqired even if the angles are aligned to GPS trace.

**Comment by domdomegg** [comment]
> angle should be pictured as some arrow nearby the value. The widget described above could contain this arrow.

:+1: This would be really good. Also would be good to be responsive to rotating in panoramas/photo spheres.

It is indeed very time consuming to use the buttons. #1003 said we should have a typing field, I think that and your idea (eight compass directions) would greatly improve efficiency in changing them. Also this would be great for fine-tweaking errors made if #1066 was implemented.

**Comment by knikel** [comment]
@angelday: food for thought

**Comment by angelday** [comment]
With the release of the new changeset editor, this is actually possible to do, although we do not support multiselect yet. I'm closing this, @rmikke let me know if you have further comments regarding this.
