### ISSUE TITLE
Ability to see time of image creation in webinterface

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1112]
I would like to see the time of creation of an image using the webinterface, i.e. by viewing e.g. http://www.mapillary.com/map/im/LyQcKkd68KJNlsylXJR5Rg . Unfortunately the time is not displayed, even when clicking the info-Button that displays a lot of infos such as image key, sequence key, etc.

**Comment by shlublu** [comment]
Well, this could be a nice feature. However, should this be implemented, it should be up to the user to define whether the exact time appears or not. This for privacy reasons.

For the same reason it would be nice to give the user a way to make the exact day not to appear but just the month.

**Comment by polarbearing** [comment]
Yes the user should have a concise list of his/her uploads including date and time, and this list should be accessible to the user only. Call it "My uploads" or so. 

Scrolling through the infinite page of thumbnails is a pain when I want to check my uploads.

**Comment by ltog** [comment]
AFAIK the date/time of creation is already available through the APIv2, see https://a.mapillary.com/#get-imkey-readapi-i-d (key `captured_at`).

**Comment by shlublu** [comment]
I didn't notice that, you're right. The user should be able to prevent his/her username from being visible in the "user" field of the pictures he/she took. Or to "blur" the "captured_at" field of these pictures.

**Comment by ltog** [comment]
Maybe you should open a new issue for that?

**Comment by shlublu** [comment]
Yes, actually I'm waiting for the Mapillary Staff to answer here to see how they would like to handle that. 

It can be either a same issue or a different one depending on the way the API services are structured.

**Comment by jesolem** [comment]
@polarbearing The profile page will be reworked in the near future and the "my uploads" belongs there. @knikel will take that into account then.

Time if day is useful for many cases and it is part of the API for that reason. Same as comparing images from different date ranges, you might want to compare from time of day. Adding it in the info panel is not adding too much new data privacy-wise and I think it is a reasonable request. @knikel can take a look at the next iteration of the viewer.

@shlublu "blurring time" we need to think about the impact of that. It would mess up time filtering and and possibly map editing if time is "vague" and you don't know which is the latest photo etc.

**Comment by shlublu** [comment]
Thanks for the feedback @jesolem - I see the point.

In that case, anonymizing pictures and activity in general is a real need. Not internally, but in the access API and public views. This becomes another issue than this one and you told me a day that there was currently some studies being conducted regarding that. So, is the opening of a separate ticket necessary? Please let me know

Thanks a lot!

**Comment by jesolem** [comment]
@shlublu Yup. Agree on the hiding of activity. We hav an issue on that so no need to make another. Thanks again!

**Comment by pbb72** [comment]
Even without displaying the time of day, this information could easily be interpreted from many photos by looking at the shadows. Is this really a privacy issue, or is this bordering on paranoia?

**Comment by AllenGraetz** [comment]
While I'm sympathetic to privacy concerns, in may ways that train left the station when the user decided to upload photos.  

For users who truly want more anonymity, I would think what they would need is an ability to upload photos that aren't publicly attached to an account.

**Comment by shlublu** [comment]
Hi @AllenGraetz, 
Yes, agreed. According to @jesolem 's comment the anonymity of pictures and activity is currently considered. So there's no need to play with the date/time of the pictures - this idea was a workaround that has been withdrawn.

**Comment by jesolem** [comment]
OK, assigning to @knikel to add time as a field in the info panel of the next iteration of the viewer.

Option for hiding activity we will do in separate issue.

**Comment by knikel** [comment]
@ltog The date is now visible on the every photo in the new viewer.

**Comment by ltog** [comment]
@knikel Thanks for implementing this! :-) I expected the date/time to be under `Photo Details` on the right, but the lower left corner of the image is ok as well.

**Comment by rudolfmayer** [comment]
I wasn't aware of this discussion, I just noticed the changes in the interface.

Personally, I do strongly oppose them; I think that already the exact date of capturing is a bit questionable, the exact time in addition is however not ok; you may make this the default behaviour, but a user for sure should have the option to change this. Otherwise yes, you should give people the option to make their accounts anonymous.

On a side-note - I don't agree to the statements "While I'm sympathetic to privacy concerns, in may ways that train left the station when the user decided to upload photos."; when registering, the premise was different, there was only a date displayed; and this is quite a big change that was not necessarily to be anticipated. Putting forward such arguments, that many would criticise when made by a Google or Facebook isn't really helpful.

**Comment by rudolfmayer** [comment]
One additional comment - I agree that time of the day can be useful for various reasons (let alone to filter all the images that might have been taken against the rising/setting sun), but that doesn't mean that you necessarily need to disclose an exact timestamp, you can still just reveal the month & the exact time, e.g.
