### ISSUE TITLE
Cannot register API client: Page is "Under development"

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1113]
The API documentation ( https://a.mapillary.com/#authentication ) refers to http://www.mapillary.com/map/settings/applications to register API clients. However this page seems dysfunctional. It says: "Under development".

**Comment by jesolem** [comment]
That's because it IS under development. ;)

@gyllen is on it right now and APIv2 authentication will be fixed soon.

**Comment by gyllen** [comment]
Yes this is still "under development"
