### ISSUE TITLE
[Enhancement] Support '3D' type images

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1114]
I was browsing /r/AndroidIsBeautiful, stumbled upon this app:
http://seene.co/

Which I thought could definitely help in 3D building mapping, computer vision and generally getting a good perspective in crowded environments.

**Comment by domdomegg** [comment]
These are some especially good ones which I think would be excellent type for Mapillary:
http://seene.co/s/z1Kbzi/
http://seene.co/s/QzePeN/
http://seene.co/s/9PEH4t

Of course they are not perfect, but they give a general guideline on to roughly what shapes are expected, and what is projected where.

**Comment by jesolem** [comment]
We will investigate, thanks for the tip.

**Comment by jesolem** [comment]
Closing. Seene shut down after Snap acquisition. http://venturebeat.com/2016/07/25/seene-shutting-down/
