### ISSUE TITLE
Most popular photo in "Week in numbers" email links to autoplay sequence

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1115]
Firstly, thanks for the "Week in numbers" email, this is really insightful and inspirational!

In this email there is a link to my most popular photo of this week. However, the link contains a "autoplay=true" parameter. This actually makes it impossible to look at the most popular photo, because it immediately starts showing all the other photos in the same sequence.

**Comment by gyllen** [comment]
We should probably remove the autoplay property as @pbb72 suggests.

**Comment by sandrauddback** [comment]
@pbb72 A bit late on this but we will remove the auto-play from the emails this week. Thanks for your input!
