### ISSUE TITLE
Photo Order In Sequence Bug

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1116]
I've noticed a few sequences like this one that haven't been cleaned up yet.  If I remember correctly, there was a known bug that caused them to be misordered.   Is that correct?  If so, do we know about how long before the servers clean up the remaining ones like this?   Or do you need me to list all of the ones I see so they can individually addressed?   Thank you. 

http://www.mapillary.com/map/im/miNEeDEBmIHhGrpuwd0GIw

**Comment by ybkuang** [comment]
@AllenGraetz Yes. It is in our tracking list to fix these. We plan to reprocess all sequences affected by the time span of the bug but it turns out to be a bit stressed to the system. So we need to find a way to do it properly and efficiently. Sorry for the delay!

**Comment by AllenGraetz** [comment]
Thank you for the quick follow-up.   It's good to hear these are on the list to fix.  I wanted to make sure just in case the fix process had missed them.

If there is anything I can do to help, please let me know.

**Comment by ybkuang** [comment]
@AllenGraetz 
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

mapillary_issues is no longer an active repository.
