### ISSUE TITLE
Web UI - Beta Suggestions

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1118]
For this view of an image in the new beta UI, it would be useful to see:

a) Traffic Signs Logged ( if not logged, an ability to identify the location of the sign would be slick )
b) Date Photo Was Taken
c) Direction Photo Is Facing ( and link to access ability to correct )

Image on Mapillary:
http://www.mapillary.com/map/imgl/AchbbXEC3Bsiwg5OlYy38Q/photo

Screenshot: 
http://screencast.com/t/a1tS5VuLS

Thank you for all the work that it takes to create these tools and keep them working.

**Comment by knikel** [comment]
@AllenGraetz We've added the date when the photo was taken to the viewer. We'll definitely consider point *a*. Regarding *c*, you can edit the compass direction by pressing the _Edit_ button in the Edit accordion in the new viewer. I'll leave this issue open until we address *a* in some way, but I'm not sure it'll have a similar form to the edit history in the traffic game. Thanks for the feedback!

**Comment by richlv** [comment]
displaying of image direction on the map (like in the old viewer) also requested in issue #1040

**Comment by polarbearing** [comment]
> Regarding c, you can edit the compass direction by pressing the Edit button

Yes I can see image direction in the Editor, but I need to see that in the browser!

**Comment by polarbearing** [comment]
The morphing/overblending is cool, however :-)

**Comment by richlv** [comment]
displaying the direction also seems to be requested in issue #1404
