### ISSUE TITLE
Need track coloring depend on photo view direction - like in JOSM

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1119]
Need track coloring depend on photo view direction - like in JOSM
![2015-06-26 00_37_41-java openstreetmap editor](https://cloud.githubusercontent.com/assets/325961/8366208/a2295596-1b9b-11e5-9525-4c1bf3b55ae4.png)
Currently impossible to choose a track in needed direction - and to know what direction photos available at all for street.

**Comment by HolgerJeromin** [comment]
duplicate from my #275

**Comment by gyllen** [comment]
Closing since duplicate
