### ISSUE TITLE
[Android] app chrashes wen reviewing

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1121]
When I go to review and tab on a sequence the app crashes. this is new in 1.28

**Comment by peterneubauer** [comment]
Git the log to check?

**Comment by de-vries** [comment]
I've just sent them

**Comment by peterneubauer** [comment]
Is this still happening with
https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release.apk
?

**Comment by de-vries** [comment]
Thanx for fixing this!
