### ISSUE TITLE
Georgia ( US state ) count missing

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1123]
The Georgia count is missing.  The global count has one user with 6 photos.  The count for the state is much higher.

http://www.mapillary.com/map/places/georgia

**Comment by AllenGraetz** [comment]
Texas has the same problem.

http://www.mapillary.com/map/places/texas

**Comment by de-vries** [comment]
same issue as #1098?

**Comment by gyllen** [comment]
This is a known problem. We are working on a solution.

**Comment by gyllen** [comment]
@AllenGraetz Texas should now be fixed

Georgia not yet since it has an unlucky collision with the country, working on a fix for this

**Comment by AllenGraetz** [comment]
Thank you.

**Comment by jfburke3** [comment]
It's not working for Florida, either.

**Comment by gyllen** [comment]
Georgia is fixed on new web
