### ISSUE TITLE
Editing blurring of image clears pending changes

### ISSUE THREAD

**Issue by wiktorn** [mapillary/mapillary_issues#1126]
If I do a lot of editing on pictures (like hiding), but do not click "save and review", instead - I click "edit blurring", I lose all the changes on previous pictures, and no warning is raised to the user.

**Comment by de-vries** [comment]
Duplicate of #366

Work around: open edit blur in new tab

**Comment by knikel** [comment]
@wiktorn, @de-vries As soon as some blurs have been added to a photo, we mark them and display them in the viewer now. We also 'freeze' the photo for further edits until blurs are resolved. Thanks for the feedback!
