### ISSUE TITLE
It seems that it's very easy to become a top contributor in France ;-)

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#1127]
Today I received an email from the Mapillary website, which reads:
![top-contributor](https://cloud.githubusercontent.com/assets/3904348/8409061/2645e9bc-1e75-11e5-8157-056460a30ca7.jpg)

What's interesting about that is the fact, that I have not uploaded a single image in the area of France, at least not last week (this has nothing to do with the boundary-issues in #465 or #739, I was sufficiently far away from the boundary).

The reason for this message to pop up is probably, that last week there were no photos uploaded in the area of France. Then your algorithm probably ranked the users randomly or in some arbitrary order, and I ended up on place 32 without doing anything.

So you probably should check, if the user has uploaded at least one image in the area in question before sending out these messages.

Thank you in advance, keep up the good work!

**Comment by shlublu** [comment]
Hi @floscher ans Mapillary
At least (but probably way more than) 36 photos were uploaded in France last week :)

**Comment by gyllen** [comment]
@floscher Still adding border bug to this since its around that area. Thanks for reporting!

**Comment by floscher** [comment]
@shlublu I refer to the stats on http://www.mapillary.com/map/places/france, which show me zero images for france. If you're right with your numbers, then this page is also broken.

Where did you get your numbers from? It might be, that Mapillary counts these numbers differently (e.g. date when image was shot vs. date when it was uploaded, simplified borders vs. official country borders, images since last monday/sunday vs. images from last seven days).

**Comment by shlublu** [comment]
@floscher The figures I sent come from the "weekly report" I received by email. It is consistent with what I actually uploaded, even though a slight delay may have increased the count of last week with some pictures uploaded the week before. But not all of them for sure.

**Comment by floscher** [comment]
@shlublu I just realized that the [all-time stats for france](http://www.mapillary.com/map/places/france) (click "global" on the linked page) also show 0 images, so the stats page is really broken.

(cc @gyllen)

**Comment by gyllen** [comment]
fixed
