### ISSUE TITLE
Sequences not shown on main map (uploaded in May)

### ISSUE THREAD

**Issue by serj-nickel** [mapillary/mapillary_issues#1129]
Some sequences that I uploaded ~1.5 months ago are still not visible on the main map. For example, the following view of the main map -
http://www.mapillary.com/map/im/bbox/41.81840820614331/43.49079023700749/73.85009765625/78.06884765624999 - shows some sequences from neighboring Kazakhstan, but not (from Kyrgyzstan). My sequences are visible only via direct link from my profile, for example:

http://www.mapillary.com/map/im/_MlKv-uaq49Au_ai0UYJwg
http://www.mapillary.com/map/im/PlvyOALfZra1TydW5Jsjpg

**Comment by gyllen** [comment]
The images are safely stored in our database. For some reason they are not showing up on our cached tiles. Investigating, thanks for reporting.

**Comment by gyllen** [comment]
They are now showing up on the map, closing...
