### ISSUE TITLE
Review mode: next photo not shown after ~120 photos reviewed

### ISSUE THREAD

**Issue by serj-nickel** [mapillary/mapillary_issues#1131]
As I preview a sequence and delete some photos, every now and then I see black screen (with buttons "accept"/"delete") instead of the next photo. Switching to grid view and back solves the issue, but It's a bit annoying to remember where I stopped and scroll down to that place. It usually happens every 100 - 130 photos.

Android app, Highscreen Boost 2 SE.

**Comment by peterneubauer** [comment]
We switched to a better image view component in v 1.55, please reopen if the issue persists.
