### ISSUE TITLE
Suggestion: show previous/next image in review mode

### ISSUE THREAD

**Issue by serj-nickel** [mapillary/mapillary_issues#1132]
When reviewing a sequence, a common task is to delete a bunch of nearly identical photos (bus stop, waiting for traffic light, etc). I'd wish to choose the best one from such a "group", but in grid mode it's hard to tell the difference, and in single photo mode I'm afraid to delete another photo, because I don't see if the next photo belongs to the "group".

With previous and next images visible it would be easier to compare the quality of similar images in order to upload the best one.

**Comment by jesolem** [comment]
Not sure this is worth "fixing". Swipe back forth until you find the photo you like? Putting more photos on the screen will make it less useful, I think.

**Comment by peterneubauer** [comment]
We added now a back-arrow into the image view, and you can multi-select image by long-pressing in the grid view. Should not be a big issue. Closing.
