### ISSUE TITLE
Android app : pictures folder hidden

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1134]
When I connect an Android smartphone to my computer, I don't see the Mapillary pictures folder. So I can't transfer the pictures without another app.
Tested with 3 smartphones on Android 4.x

**Comment by peterneubauer** [comment]
The folder is not exposed to the normal media scanner I am order not to overload your photos. You can list it under settings - developer.

**Comment by peterneubauer** [comment]
In the latest release (1.46 in alpha), the default image folder is now in a public place (see settings for details and reset to default if you already have a setting there)
