### ISSUE TITLE
Profile : images still processing

### ISSUE THREAD

**Issue by balooval** [mapillary/mapillary_issues#1136]
Since long time (some month), there are 17 images still processing on my profile. Are they lost in time, lost in space ? (link to my profile : http://www.mapillary.com/profile/balooval )
Plus, since some month again, it seem that the "magic" between my uploaded images is not done (link to similar image, or turn arrow when 2 ways in different direction are near, exemple : http://www.mapillary.com/map/im/jz4dv5G9XwQMyB0SFiLb3w )

Am i wrong in some part of the process ?

Thanks

**Comment by ybkuang** [comment]
@balooval You are right but we have paused the processing since we are working on a new viewer. Here is a preview of it https://vimeo.com/131866488. As you can see, the navigation between the images will be back when we release the new viewer.

**Comment by balooval** [comment]
@ybkuang Cool, great job and pretty cool video !
And for my 17 images stucked since long time, can you explain that ? (not really important but i'll prefer have all images proccessed)

**Comment by ybkuang** [comment]
@balooval it could be that the images failed in some part of processing (could be many reasons). The original of those images are safe though. We need to look into that. Let's keep this open until we fix it.

**Comment by de-vries** [comment]
> And for my 17 images stucked since long time, can you explain that ?

I also have 10 of those

**Comment by de-vries** [comment]
Since June 8 I have 10 still uploading photos. 
Since July 6 I have 259 still uploading photos. I believe the (extra 249) missing photos are in [this sequence](http://www.mapillary.com/map/s/FUoLyTdB23GGjl_KhKChOg) because a lot of photos in that sequence won't load.

**Comment by gyllen** [comment]
@de-vries Yes these are images stuck in processing for some reason. We are continuously working on keeping this count down.

**Comment by shlublu** [comment]
I still have 1 stuck too.

**Comment by de-vries** [comment]
My still processing count went up from 10 to 11 a few weeks ago, but since today it's zero!

**Comment by gyllen** [comment]
We are still working on getting every image processed ;)

**Comment by de-vries** [comment]
here's an observation:

I UL-ed 2951 photos 2 days ago. During the UL process there were some problems with the connection. My profile page says I UL-ed 2952 photos and 1 still processing. 

I've seen this happen before, exactly the same way.

**Comment by moenk** [comment]
There are now still 372 pictures from last year to be processed: http://forum.mapillary.com/t/372-still-processing-since-weeks/314/1 - will the counter in my profile ever go to zero? ;-)

**Comment by de-vries** [comment]
I found a source for images stuck in processing; this happened twice today: during the upload, using upload.py I got one error and after the upload was fully processed the still processing count was one up. 

This was the error message the second time it happened: `HTTP error: HTTP Error 500: Internal Server Error on FILE1423.JPG`

And this is (fully processed) the image the error message was about: https://www.mapillary.com/map/im/ipt02PR3CbnAsRchBgP2Sw/photo

**Comment by polarbearing** [comment]
My proposal in #1974 would help everybody to keep track of them.

**Comment by ybkuang** [comment]
This should be resolved now. Closing
