### ISSUE TITLE
Photo sequence does not appear in iD

### ISSUE THREAD

**Issue by tiagofassoni** [mapillary/mapillary_issues#1137]
For instance, this sequence: http://www.mapillary.com/map/im/b-9Erc_n0IIXt4Tm15gmSg

It appears on Mapillary and on JOSM, but not on iD. I tried zooming in, to no avail. The iD link: http://www.openstreetmap.org/edit?editor=id#map=21/-23.55626/-46.66239

Tested on Chrome 43.0.2357.130 (64-bit) for Mac and Firefox 38.0.5 for Mac

**Comment by jesolem** [comment]
There is a limit on number of features that iD shows, not sure this is it. @peterneubauer can take a look.

**Comment by peterneubauer** [comment]
This should be solved now. Closing.
