### ISSUE TITLE
Add regions and more countries to Explore main page links

### ISSUE THREAD

**Issue by ellibre** [mapillary/mapillary_issues#1138]
Nowadays Explore links are... Explore: Germany, Sweden, Brazil, United States, Italy, Poland

and what about Spain? France? I think list is too small list. and What about regions? What about Catalonia or Tyrol?

**Comment by jesolem** [comment]
We are going to change this and the site soon. Planning for it now. Will take this into account.

**Comment by knikel** [comment]
@ellibre We've phased out that functionality. You can find many regions with superb shapes (thanks to [Mapzen Who's  On First](https://whosonfirst.mapzen.com/)) at http://www.mapillary.com/map/stats . Hope you like it?
