### ISSUE TITLE
iOS app overheating

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#1140]
Today I tried to map long sequences (around 4000 pics or so) and noticed that the app (along with gps, camera, and whatnot) hogs so much battery that the app shuts down and I get an overheat warning courtesy by Apple.

Of course, the fact that it is July in Saudi-Arabia and I had to position the phone on the dashboard in direct sunlight for obvious reason might play into this, but it is pretty annoying anyways. I found that if I take turns (charge-map-charge-map) and keep the AC at full blow blowing towards the windshield, I could do what I was doing.

If there is some performance tweak you guys can do, it would certainly help us poor people down hear in the tropics!

**Comment by jesolem** [comment]
Hi @Virtakuono 

The camera and GPS are two of the most power consuming processes on an iOS device and will warm up a phone after a while (from pure watts generated internally). Placing it in the windshield under strong sun like we do makes it even worse ;)

I'll try to ask the camera team at Apple but I think we're into extreme operating conditions here.

Some ideas:
* remove any phone case if you have one
* try to place something between the phone and windshield to give it some shade without covering the view

Leaving this issue open for a little while to see if the community has any other tips and then collect them to the [User Guide](https://github.com/mapillary/UserGuide/wiki/Capturing)

BTW - Awesome photos from Saudi Arabia!!

**Comment by filipca** [comment]
Use an external GPS receivers like the Garmin GLO.  Then you can turn off GPS, but you have to switch Bluetooth on.

**Comment by jesolem** [comment]
Closing after a month.
