### ISSUE TITLE
Unblurred image still looks blurred

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#1141]
This is image contains obviously blurred parts:

http://www.mapillary.com/map/im/Sj3wk8DnU8rwkwiAP5LHVQ

But if I select the "Blur" function, no mark spots are shown.
I  suspect that I had requested an unblur of this image, and the mark spots were thereafter removed, but for some reason the image was not updated.

**Comment by richlv** [comment]
for the record, still appears blurred to me, so not a browser cache issue :)

**Comment by gyllen** [comment]
There are no longer blurred spots in image, this is probably internal cache on Mapillary
