### ISSUE TITLE
Make transitions between sequences symmetric

### ISSUE THREAD

**Issue by s-tikhomirov** [mapillary/mapillary_issues#1143]
Sometimes when I press "turnaround" button in web viewer and get to another sequence, there is no "turnaround" button there such that I could come back to the sequence I was traversing. Same thing with "left" and "right" buttons. It would be nice, if as soon as image A gets linked to image B, to link B symmetrically to A: if A is left to B, than B is right to A, and so on.

**Comment by jesolem** [comment]
Good point. For forward/back symmetry is a good idea. For left/right some caution is needed, there may be a better right image after turning left than the one you came from (images are not at the exact same location so a left turn will move your position). 

Worth thinking about though. We are updating the navigation for the upcoming viewer. -> @paulinus

**Comment by gyllen** [comment]
@paulinus We should keep a record of last dir and if new dir is the opposite we should fallback to image

**Comment by richlv** [comment]
as for left/right moving the position and then possibly getting back to a different image, how about adding a small button for reversing your moves (could be limited to 10 previous images) ?
i often find myself looking at some sequence, seeing "ooh, there's some other image here" - but i have learned to ignore that, as getting back to where i was means copying the url - cumbersome :)

**Comment by paulinus** [comment]
@oscarlorentzon do you think a history and back button would make sense on mapillary-js?

**Comment by paulinus** [comment]
mapillary_issues is no longer an active repository.

Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
