### ISSUE TITLE
Make font on OSM map bigger

### ISSUE THREAD

**Issue by serj-nickel** [mapillary/mapillary_issues#1144]
Just compare it with osm.org:
![osm-vs-mapillary](https://cloud.githubusercontent.com/assets/7126627/8512481/23ac10e6-234d-11e5-9a4c-283752d35d95.png)
It's barely readable ;(

**Comment by jesolem** [comment]
I don't think this will be relevant once we make the full switch to vector maps. @gyllen ?

**Comment by de-vries** [comment]
Isn't Mapillary using the same tiles as osm.org? 
@serj-nickel, you probably have used your browsers zoom-function (hence the floating filter button) use `Ctrl-0` to reset it on both Mapillary and osm and you'll se that they are the same.

**Comment by serj-nickel** [comment]
@de-vries No, ctrl-0 doesn't solve the issue. Both on Chrome/Windows 8 and Chromium/Linux Mint.

**Comment by gyllen** [comment]
Yes this will be solved by switching to vector maps. Closing
