### ISSUE TITLE
Typos in API-reference

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#1145]
[https://▒▒▒.mapillary.com](https://mapillary.com) has two types of typos in the curl-commands:
* five times it says [`https://▒▒▒.mapillarycom`](https://mapillary.com) (missing period before com)
* four times the curl-command contains the parameter `min_on`, which should be `min_lon` or you get unexpected results

Maybe you could also think about returning an error message, if not all four parameters `min_lat`, `min_lon`, `max_lat` and `max_lon` are given. That would ease debugging when someone just copy-pastes (would've just saved me about half an hour).

**Comment by gyllen** [comment]
@floscher Thanks for reporting the v2 API is still alpha. How did you get a hold of that link?

**Comment by floscher** [comment]
@gyllen It's linked at http://www.mapillary.com/developer.html which can be reached from the new vector map (via the developer-link in the navigation).
I'm currently helping in development of the [josm-mapillary-plugin](https://github.com/floscher/josm-mapillary-plugin), which already uses the new API.

**Comment by gyllen** [comment]
@floscher No worries, that page is in alpha and still under heavy development. For the JOSM project we have granted early access. It should not be visible on the API page yet.

**Comment by gyllen** [comment]
@floscher We have a slack channel for the dev JOSM dev, send an email to gyllen@mapillary.com and I will add you

**Comment by jesolem** [comment]
typos fixed and will go out in the next deploy, thanks @floscher

**Comment by floscher** [comment]
You're welcome. So then this can be closed.
I also edited my post above and (sort of) blurred the parts that should not yet be public ;).
