### ISSUE TITLE
Traffic signs broken since yesterday

### ISSUE THREAD

**Issue by mbirth** [mapillary/mapillary_issues#1146]
Since yesterday (2015-07-06), several traffic signs look weird in Chrome 44 beta (Windows + Linux). Also in the Vivaldi browser and Firefox 38 and 39.

![2015-07-07 10_13_33-mapillary _ mbirth s profile](https://cloud.githubusercontent.com/assets/130302/8541782/e1bc5cfa-2490-11e5-9a74-1878446831ad.png)

**Comment by knikel** [comment]
@mbirth This has been fixed now :wrench:. Sorry about that.
