### ISSUE TITLE
Small issues and suggestions for Android app

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#1147]
1) could be better if it didn't display the word `Username`, since the username is already there:
![screenshot_2015-07-08-11-08-40-fs8](https://cloud.githubusercontent.com/assets/982338/8572320/482239e8-2562-11e5-8942-7dbe6d275344.png)

2) we have a **Max** tilt in one line and then **Minimum** tilt in another one; it seems it should be maximum instead?
![screenshot_2015-07-08-11-09-08-fs8](https://cloud.githubusercontent.com/assets/982338/8572323/4c473b0e-2562-11e5-97fd-b600401efa38.png)

3) mapillary uses the GPS (and keeps it on) even when there is no need; ie, if I open mapillary without doing anything at the main screen, it keeps on. Likewise for `Feed`, `Profile`, etc.

**Comment by HolgerJeromin** [comment]
1) ok
2) there should be enough space even on small devices and the larger font
3) i think the reason is, so that there is a nice fix ready if you start a sequence. GPS needs a few seconds/minutes to get a good precision.

**Comment by naoliv** [comment]
For 2 I mean this:

    Max tilt in degrees 30°
    Maximum tilt in degrees
Shouldn't the second line be "Maximum" instead "Minimum"?
If we enter this option every word is "maximum".

For 3, isn't it enough to use the GPS only when we click on `Camera` (and have it start acquiring a lock between this and up to the point where the user clicks `Start`)?

**Comment by HolgerJeromin** [comment]
oh thanks for your correction concerning 2.
3: I start the app, read the feed for 10 seconds. After that i start the camera and hit record. Now the gps had 10 seconds more to get a better sat fix.

**Comment by peterneubauer** [comment]
@naoliv thanks for the suggestions! Changed the wording on tilt, will come out in the next builds. The GPS in the main screen is on partly for a better and faster fix once you start the camera as @HolgerJeromin suggests, partly to have a fix when you are exploring without having to wait too long.
