### ISSUE TITLE
Manual Uploads: Video Count + Thank You

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1148]
With manual uploads I've noticed when not uploading a video, the count will be one.   It hasn't caused any problems for me.   But it isn't correct.

Most importantly, thank you for the improvements to the manual uploads.  It's made this process easier to use, especially when uploading a few sequences at a time.   It's worked well and rarely has a glitch.

I really like, screenshot included, the upload 1, upload 2, etc feature.  It's handy when I kick off a couple sequence uploads before going to work.  I can hop on later, see what's done and publish it.

http://screencast.com/t/4t0EL4hIWZJ

**Comment by gyllen** [comment]
@knikel You remember what these numbers mean?

@AllenGraetz Nice that you like it. I don't think many people have gotten the fact that you can upload by script and then approve or see progress on web. We need to make that feature a little more visible.

**Comment by knikel** [comment]
@gyllen The counter is `not pushed uploads / pending uploads`

**Comment by knikel** [comment]
The uploader is getting a serious overhaul, closing this since it won't be relevant.
