### ISSUE TITLE
Cross-Origin Request Blocked for cloudfront (https)

### ISSUE THREAD

**Issue by grinapo** [mapillary/mapillary_issues#1149]
09:30:34.546 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://d2munx5tg0hw47.cloudfront.net/tiles/13/4516/2863.mapbox. (Reason: CORS request failed).1 <unknown>

09:30:34.960 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6/14/9031/5725.vector.pbf?access_token=pk.xxx.xxx_Whra7w. (Reason: CORS request failed).1 <unknown>

I guess mixing up http and https doesn't play well.

**Comment by grinapo** [comment]
happy birthday, bug! ;-)

**Comment by gyllen** [comment]
Hey @grinapo we are in the staging of rolling out new tiles plus a new web. Stay tuned. Will close this accordingly when solved.

Thanks for the bump ;)
