### ISSUE TITLE
Bulk Editing Compass Angles issues

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#115]
The "Camera was pointing forward" option is really a super and most waited for sequence editing function. But how do I say that camera was pointing sideway or backward? I reckon this is still a rare case. But as soon as some highways will become well covered, it's likely that we will start to be more creative when pointing the camera, in an attempt to capture new details. It would be good to be able to specify a constant skew angle, shouldn't be too difficult to implement.

Another more tricky issue is dealing with sparse photos, where the direction to the next photo is likely to differ a lot from instant velocity direction . Even setting a frequent shooting rate and having a good fix, the actual rate is likely to vary a lot due to the low shake requirements. Here is an example from sequence https://api.mapillary.com/v1/s/gpx/BPjkvz2t41kB4rBdcfRsnQ.gpx, shot with a sequence frequency set at 2 sec:

https://dl.dropboxusercontent.com/u/90019879/Mapillary%20GPX.jpg

Mapillary track is shown in red, the app refused to shot for long stretches (shaking icon constantly on the screen). The blue track was recorded with the same phone with a tracking application recording 1 fix per second. It would allow a much better direction correction. If Mapillary could evaluate the direction of movement in real time from frequent position fixes and store it in the pictures metadata, this would allow for a better correction afterwards, even on rough roads.

**Comment by kaitu** [comment]
I think that, at least in the Android app, the problem with computing the direction of sparse images should have been brilliantly solved by the setting "Lock direction forward in driving/biking mode" (I haven't tried it yet). But telling that the camera is pointing sideways is still a problem. The skew setting in the online sequence editor can now only be invoked together with the function which preliminary sets the direction towards the next image. If "Lock direction forward in driving/biking mode" was set to estimate the direction live, we don't want to change this estimate with the more imprecise "aligne to next image method". What we need is a very simple function to just apply a constant offset to all angles in the sequence. This could be done live (yeah, that's one more setting in the app!), but it would also be good to be able to apply it afterwards on the online editor (it might happen that by mistake the skew setting hadn't been adjusted properly at shooting time).

**Comment by gyllen** [comment]
@peterneubauer is @kaitu suggestion something thats doable for the app?

**Comment by peterneubauer** [comment]
This is doable of course, question is how to get to a simple UX for the offset setting, @knikel ?

**Comment by peterneubauer** [comment]
Let's close this and move to #812.
