### ISSUE TITLE
unreachable code after return statement1 mapapp-63ddd501.js

### ISSUE THREAD

**Issue by grinapo** [mapillary/mapillary_issues#1150]
Probably non-critical but still...

09:31:37.053 unreachable code after return statement1 mapapp-63ddd501.js:18504:10
09:31:39.719 Object { lat: 47.54273635478451, lng: 18.42804193496704 }1 mapapp-63ddd501.js:10453:17

**Comment by knikel** [comment]
We deploy some internal experimental features that are not always enabled, therefore such logs might appear in the Firefox console which is always very eager to display as much information as possible :wink:

**Comment by grinapo** [comment]
Well *internal* experimental features wouldn't show up for *me*, would they? :-)
