### ISSUE TITLE
unable to hide sequence

### ISSUE THREAD

**Issue by PeeWeeOSM** [mapillary/mapillary_issues#1153]
I take my pictures with the app Camera FV5 and simultaniously record my track with OSMtrackers so that I can add GPS data to the photos. Because this is doen with the same device I assumed that timestamps op both app were identical. This was an error because OSM tracker is able to records GPS time instead of phone-time. Due to this error I have uploaded a few sequences that were wrong. Here's 2 examples of  sequences that is incorrect. When crossing bridges it is obvious that it is incorrect.
http://www.mapillary.com/map/im/biGvUuUj9IGZTHY-BA1I7Q
https://www.mapillary.com/map/im/8IBX2dAJg-xtpy3t_yG_Yg

Fortunately I still had the photos when I discovered the error so there now is also a correct sequence.

I have tried several times to hide the sequence but... is never dissapears from the mapillary site. 
I got a message from user (mapillary enployee) saying:

"Hi @peewee32 , Just confirming this is an intentional hide. Thank you  " but I guess he just hid one photo instead of the whole sequence.

BTW : why is it not possible the have the maker of the photos /sequence delete it from the database?

Cheers PeeWee32

**Comment by gyllen** [comment]
@travel193 Are we confirming these hides?

**Comment by travel193** [comment]
Hi @peewee32,
Sorry there was a delay in my processing of your change requests.

You should start to see confirmation of hides soon and the sequences will disappear from the map once processed by the server.
