### ISSUE TITLE
API sequence search failing

### ISSUE THREAD

**Issue by rabidllama** [mapillary/mapillary_issues#1154]
Every time I do a sequence search (using the example url http://api.mapillary.com/v1/s/search?min-lat=55.611&max-lat=55.613&min-lon=12.994&max-lon=12.995&max-results=3&geojson=true and others) after a while it just returns an Application Error. /im/search works, but not /s/search

**Comment by gyllen** [comment]
Try v2 of API instead v1 is depcrecated https://a.mapillary.com/

**Comment by rabidllama** [comment]
How do I get a client ID though as in all browsers, when I go to the application settings page of my account there are no options for creating a new app, just two headers saying "Applications" and "Under development"

**Comment by peterneubauer** [comment]
For the time being, I can get you one if you contact me with a few details about your app at hello@mapillary.com.
