### ISSUE TITLE
Support for Veho Muvi K2

### ISSUE THREAD

**Issue by travel193** [mapillary/mapillary_issues#1155]
Veho Muvi K2 action cam needs to be calibrated.
Additionally sequences are not being processed correctly by the manual uploader.

[Here is a sample sequence with the Veho.](http://www.mapillary.com/map/im/etGsI83zO3oKpHjzEWFYWg)

**Comment by domdomegg** [comment]
You must crop to a 4:3 aspect ratio or it will be distorted

**Comment by rmikke** [comment]
This is not a solution for helmet camera users - at least not for people that ride with a camera for security reasons. I _need_ to catch as much of the surroundings as possible and I won't give it up to make the video fit into Mapillary.

Now I'm not sure if my material is any good for Mapillary and if I should upload more. And I have much more, good quality video with precise gps tracks...

**Comment by knikel** [comment]
@domdomegg, @rmikke: We do accept formats other than 4:3. Currently they are distorted visually in the browser, note though, that the original photos are not touched. Soon you'll be able to browser the photos without distortion. So @rmikke capture as much as you like, your photos will look better soon on mapillary.com
Here's a future view of the photo @travel193 linked to: 
![updated-viewer](https://cloud.githubusercontent.com/assets/1574656/8876879/be4a0d54-3222-11e5-9767-8b95978a2cd8.png)

**Comment by rmikke** [comment]
Nice :D 
So now I wait for some changes as per #1110 and start uploading again.

**Comment by domdomegg** [comment]
Yay! Please remember/remind me to update wiki when you do officially support non-4:3 images

**Comment by knikel** [comment]
@rmikke, @domdomegg The viewer has been released, enjoy! Looking forward to your contributions :smile:
