### ISSUE TITLE
Corrections not showing

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1157]
Are corrections not being processed or are there just some that got stuck some how?

This sequence, the unblurrings are not live
http://www.mapillary.com/map/im/PcqPpV-lI-fYEBzZBpLkug

I have moved pictures, but the correction is not showing
http://www.mapillary.com/map/im/x83Y8-KHtr3RGO77nCzuQw

I haven't been all that active lately, so maybe I missed something. Just noticed these two randomly.

**Comment by gyllen** [comment]
@Andblue Is this still a problem

**Comment by Andblue** [comment]
The unblurrings are not live in that sequence. But now I can unblur. Before they were blurred but when I tried to unblur it said something about alread being in process or something like that.

The sequence where I moved pictures are still unmoved. But I can just move them again.

**Comment by gyllen** [comment]
Perfect, thanks for reporting
