### ISSUE TITLE
Browsing stuck with missing metadata

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1158]
For the last 1-2 weeks it has been nearly impossible to view a sequence in the web browser. When I start clicking on one of my upload thumbnails, one of the following happens:

- very rarely, I can click forward normally through a whole sequence
- often, the image page shows only the frames, but no map and no image viewer
- sometimes, the first image is shown, with its correct data and the position on the map. When clicking forward, after 1-2 further images, loading the next images gets stuck with the white dots spinning indefinitely.
- sometimes, the image is shown, missing the controls, showing no map, and showing 1 Jan 1970 (i.e. Uinix-zero) as the date. Clicking the edit button on such image shows that all location data are empty. 

My suspicion is that the backend intermittently lacks access to the metadata, thus it displays the zero-date, cannot locate on the map, and cannot identify the next image, at some time, but works occasionally. 

It does not help to switch to the vector-map-view, the issue there is exactly the same here. 

There seems to be no relation to particular sequences, the same sequence can show any of the above behaviours. 

For the record, the browser is firefox 39.0 on linux.

**Comment by gyllen** [comment]
@peterneubauer I assume this is a problem with GS not catching up

**Comment by serj-nickel** [comment]
I experience same problems. It affects my sequences uploaded recently (12 July).

**Comment by peterneubauer** [comment]
@polarbearing bot a link to one of the images?

**Comment by polarbearing** [comment]
This is a sequence where I often, but not always, get stuck at the third image. Sometimes I get over the third and get stuck later. 
http://www.mapillary.com/map/im/KIZQgG2ZjTIup8u7IMQseg
http://www.mapillary.com/map/im/Hi2lsmatAfBQRYwuAOHtqg
http://www.mapillary.com/map/im/bbsL3ra1jN0OEkkt2727pg

**Comment by peterneubauer** [comment]
Yeah, that is 2 of our servers having the wrong metadata, the 3rd is answering correctly. Will investigate and replay that data.

**Comment by polarbearing** [comment]
While being stuck on the website, I can go through the same sequence via the JOSM plugin easily.

I have also seen completely wrong geocoding on some of my images (kilometers away), is that related to the same issue?

**Comment by mstock** [comment]
I have the same or at least similar issues with at least three recently uploaded sequences:
* http://www.mapillary.com/map/im/X9_MZEBncsK5nHcxRurW3A
* http://www.mapillary.com/map/im/NYaGomBQBqsxaWqBUwz5yA
* http://www.mapillary.com/map/im/ESABIAvY1W14DERmmw6pqw

The first two sequences actually contain the same images (caused by some user error ;)), so one of them can also be deleted. The behavior is also different depending on being logged in or not - if logged in (with Firefox), I just get stuck, if not logged in (with Chromium), I get an error and/or redirected to the start page. Sometimes, I do get to see pictures before the redirect, and if I retry, it often works, so if I repeat that on every error, I'm able to watch the whole sequence, but after clearing the cache/restarting the browser, I'm back at the behavior with missing images and redirect to the start page.

**Comment by gyllen** [comment]
@mstock We have 3 servers, 1 of them is healthy 2 are not, @peterneubauer do we have any news on this, new images are lagging

**Comment by echeloni2p** [comment]
I can add my pictures taken on 11th and 12th July 2015 - all pictures uploaded, blue lines on webpage, but not shown. I can view the images in Josm plugin, to.
I made those tracks with the "ignore GPS check"  option activated, but the blue lines shows a fine line, not really much out of position.
Any idea on timeline about a fix?
Would like to edit those tracks soon..
e.g. 
http://www.mapillary.com/map/im/Gx41AIoAQBV_xp9IvkhYGg
http://www.mapillary.com/map/im/OHJRIT08T-7ZIkkBKVWArQ

Oh, and tracks uploaded the week after are fine...

echelon/aceini

**Comment by peterneubauer** [comment]
With the new rollout of the viewer, these sequences are working now. Still more to improve on the navigation side though, but that's another issue.

**Comment by polarbearing** [comment]
Might work in the viewer, but I have still problems with these sequences when stepping through the sequence in the Editor.
