### ISSUE TITLE
Images not Visible

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#1159]
TL;DR Mapillary does not work at the moment.

Both Firefox and Chromium do not show any images if I click on a sequence line on the map (e.g. [here](http://www.mapillary.com/map/im/bbox/48.9924167292723/48.993462131780134/8.39465171098709/8.398315608501434)). The line becomes pink if I move the mouse onto it. If I click it, nothing happens.

I have used a blank Chromium profile and cleaned the cache before my Firefox test.

**Comment by polarbearing** [comment]
Sounds similar than my issue here #1158 ?

**Comment by Nakaner** [comment]
Similar but I have not noticed bugs like missing or wrong metadata. I use Arch Linux.

**Comment by gyllen** [comment]
@peterneubauer Is GS lagging?

**Comment by peterneubauer** [comment]
We switched to a new viewer where this should be working now.
