### ISSUE TITLE
lag for detection trafficsign

### ISSUE THREAD

**Issue by operon** [mapillary/mapillary_issues#1160]
after upload new image, the detection trafficsign is not possible
"It is not possible to approve or add traffic sign on this photo yet. "

Could you add an approximate waiting time for service ?

should add translation on up to pages
trafficsign game, mapillary.com ...

Thanks

**Comment by gyllen** [comment]
@operon We are currently upgrading the traffic sign detection service and holding back new detections. Will be up and running in a couple of days again. Sorry for the inconvenience.
