### ISSUE TITLE
Do panoramas still work?

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#1161]
I've recorded two, three panoramas of late with the Android app ( for example http://www.mapillary.com/map/imgl/2Q5PmaONemvC_BuKOmoxBg/photo ) and contrary to earlier behaviour, a year or so back, there seems to be no special processing anymore (aka there is no difference to a normal sequence).

**Comment by peterneubauer** [comment]
This is a feature, not a bug ;) we are working on putting the images into a 3d-space, making both panoramas and normal sequences navigatable better than before. Wait for just some more week to get that out - after that we might not need panorama stitching anymore!
