### ISSUE TITLE
Connections in userprofile don't update

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#1162]
The connections in my userprofile don't show the updates anymore since 7 march:
![schermopname 25](https://cloud.githubusercontent.com/assets/10783093/8764721/4357a9d4-2deb-11e5-80a3-60ac82ce077e.png)

**Comment by gyllen** [comment]
@Peatsmoke That is correct, we are reorganizing the backend and are detecting matches in another way. Connections will soon be removed and replaced by something nicer ;)
