### ISSUE TITLE
expand the contour of latvia to include liepaaja

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1164]
the contour of latvia at https://www.mapillary.com/map/places/latvia cuts off city liepaaja in the western part - hopefully that's easy to expand a bit :)

**Comment by domdomegg** [comment]
Similar:
#465 #677 #739

I guess these all could be fixed by using better border data. Surely there must be a way to extract it from OSM, although reading up it does look like it could pose a problem.

http://www.naturalearthdata.com/ may have a solution (and it's in the PD!)

**Comment by gyllen** [comment]
@domdomegg We are using naturalearth at the moment, but are as you said looking into using OSM data.

**Comment by domdomegg** [comment]
What quality? I believe they have 3 levels of accuracy, and release updates frequently. It seems too approximated.

Also perhaps as a fallback if outside any country they should be attached to the nearest one.

As extracting borders from OSM is difficult, you could reverse look up the location and extract the country data from that, like when you get place names from nearby - you could probably use the same method. Then the NaturalEarthData borders on the map are just for selecting country.

**Comment by gyllen** [comment]
@domdomegg Thats pretty much how we do it today actually....

**Comment by richlv** [comment]
the contour is different now, and the link to it seems to have changed ( https://www.mapillary.com/app/stats/85633279 ), but it still cuts out large parts of liepāja (in a weird way now, somewhat following the lake outline)

**Comment by gyllen** [comment]
@peterneubauer ^^^

**Comment by peterneubauer** [comment]
Not much to do, the underlying shape has no higher resolution - please open an issue over at WOF: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/332/79/85633279.geojson
