### ISSUE TITLE
feature request: filter search by capture mode

### ISSUE THREAD

**Issue by minikarma** [mapillary/mapillary_issues#1165]
It would be grateful to search images via API defining the capture mode (pedestrian, driving, etc).
My use case is to show photos of sidewalks and photos captured while driving not relevant. 
Hope it might be helpful not only for my project.
Also it would be good to add the capture type to the response parameters.

Thank you

**Comment by domdomegg** [comment]
This would be great.

Related-ish:
#992 (Tagging images)
#352 (Layers handling of classifying images)

**Comment by gyllen** [comment]
I will look into it, problem is that the capture mode does not say that much about the images since people seem to missues them. Adding it as a filter in the API should not be a problem though.

**Comment by minikarma** [comment]
Thank you so much!

**Comment by gyllen** [comment]
Added as feature on roadmap

**Comment by jaakkoh** [comment]
All noted well (already, above). I too would like to see this feature but as gyllen notes it would not be an unproblematic one. However, as it _would_ be a powerful "rough filter" that would exclude likely huge amounts of photos that one is not looking for. And the more there are photos in Mapillary the more useful such filter would be. Especially if it could be combined with hashtag (or whatever functional other tag) filter(s).

**Comment by gyllen** [comment]
We no longer define capture as different modes, so closing
