### ISSUE TITLE
Unable to join 'mapillary-testers' Google group

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1168]
I'd love to help out beta testing the new Android and iPhone apps, but for the Android one the 'mapillary-testers' group (https://plus.google.com/communities/104427435312937590517), the one from the Wiki (https://github.com/mapillary/UserGuide/wiki/Testing) seems to be set to invite only.

**Comment by peterneubauer** [comment]
Can you join https://plus.google.com/communities/104427435312937590517 now? Have changed the settings ..

**Comment by domdomegg** [comment]
I can ask to join now, have done so and "will be notified when a moderator approves your request".

**Comment by domdomegg** [comment]
The request was accepted, but I don't know whether it is supposed to be accepted only? If so we should probably mention it on the wiki, but I would have thought it best to just have it public?

**Comment by peterneubauer** [comment]
yah, actually I can't find a setting that is not requiring approval.
