### ISSUE TITLE
Mapillary_issues wiki is useless

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1169]
https://github.com/mapillary/mapillary_issues/wiki

All there seems to be is a welcome page. I have just added a link to the main wiki. There is also a FAQ page, which is just questions...

We probably shouldn't use this wiki for the general things as that is reserved for the main one. However, we may want to use it as a guide on submitting issues effectively, but I think it would be better just to have a page on the main wiki for that.

I am unsure if it is possible on github, but a redirect would probably be good, if not possible just a empty wiki with a link back to the main one would be better than having two out-of-sync copies of similar information.

**Comment by travel193** [comment]
Hi @domdomegg ,
I'll clean out the wiki as it's not the place for this. Let's keep everything FAQ related in the [Userguide](https://github.com/mapillary/UserGuide/wiki) and as you said, we can have a page there with issue submission as well. 

Thanks for keeping an eye out!

**Comment by domdomegg** [comment]
Great, that seems like a good solution. I will delete the copy of the FAQ page.
