### ISSUE TITLE
Commenting and colored filters on sequences?

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1170]
I think it would probably be better if you could see all the comments on a single sequence, just a thumbnail of the image the comment was made on next to the comment. Otherwise comments are really rare, and the chance of people actually being able to find them is close to nothing without this.

Also it would be cool to filter sequences by ones that had been commented on. Marking filters by color could be cool also, eg. choropleth or opacity depending on # of comments / # of views / # of street signs

**Comment by sandrauddback** [comment]
Thanks for input! We are thinking a lot of how we can make it easier to discuss places and make comments on each others photos. We will continue working on it so please provide feedback as we do new releases.
