### ISSUE TITLE
edit/unblurring doesn't work (portrait photo)

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#1171]
I would like to unblur "Joop Zoetemelk" art work facade:
http://www.mapillary.com/map/im/BzPKwId7TloUf-Gdl7EM-g

However, in edit mode the photo (taken in portrait mode) covers the edit/submit or save buttons so I can't submit any changes to Mapillary.

**Comment by ligfietser** [comment]
Screenshot: ![blur](https://cloud.githubusercontent.com/assets/9638726/8821126/8a1b4e8a-305b-11e5-9c7a-5b56f52d710d.jpg)

**Comment by knikel** [comment]
@ligfietser This will be fixed with a rollout of a new viewer. I've un-blurred this one for you. There will be also a button to discard all the wrong blurs from the photo in one click. Bear with us for few more days ;).
