### ISSUE TITLE
HTTPS by default

### ISSUE THREAD

**Issue by wasdy** [mapillary/mapillary_issues#1172]
Please, set HTTPS by default on mapillary.com.

Also, as Firefox states, "This website does not supply ownership information." Isn't it owned by "Mapillary Inc."?

**Comment by domdomegg** [comment]
Also related:
https://mapillary.com (without 'www') is broken

**Comment by wasdy** [comment]
I'm still amazed that sending our passwords in plain text is not considered a critical security issue.

**Comment by gyllen** [comment]
@wasdy A little late note ;), we are NOT sending passwords in plain format, our API endpoints has always been HTTPS

**Comment by GITNE** [comment]
There is a similar problem with notification email links. Although the links themselves specify the HTTPS protocol, they get redirected to HTTP. Just try any link in a blur request or approval notification email.

**Comment by domdomegg** [comment]
Also see #1806 (blog HTTPS too)

**Comment by Caboosey** [comment]
Here is good article about the dangers of having login/signup form on a HTTP connection even though it submits to HTTPS

Steve Gibson even talks about the dangers of like signup/login forms on HTTP page:
https://youtu.be/ojLAPAM13hc?t=1h8m46s

https://www.troyhunt.com/your-login-form-posts-to-https-but-you/

Someone could easily be a man-in-the-middle change HTML code of http://www.mapillary.com/map/login requested by the client and then username and password would be sent to the hacker/attacker.

**Comment by gyllen** [comment]
HTTPS is now default (and enforced)

**Comment by Caboosey** [comment]
@gyllen Thank you! Good job!

FYI, mapillary scores a rating of an A (Note: A+ is being the highest) on SSL Labs test.

https://dev.ssllabs.com/ssltest/

I believe if the HSTS was enabled, you could reach improved security and higher score on the SSL tests.

**Comment by peterneubauer** [comment]
Not sure it's worth the extra effort right now, closing it.

**Comment by gyllen** [comment]
@peterneubauer Closed or open?

**Comment by gyllen** [comment]
HTTPS has been redone from scratch and should now be better. Closing.
