### ISSUE TITLE
More control over exposure (Android)

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1174]
When mapping by car I get a lot of images like this one: http://www.mapillary.com/map/im/ugt8phutMSoH2cHGk8cqkw , that has a nicely exposed sky and the rest is very under exposed or very dark.

The reason is that virtually all auto exposure systems takes an average value of all pixels in the area they look at (the whole pic or a circle of the center) and matches the exposure so that average is "18% gray" or about 46,46,46 in rgb (as far as I knows). When the images gets dark, it is because there is a lot of light from the sky. Some times the Sun, but most often clouds that are lit up by the sky.

I could fix it by putting a ND filter (gray piece of high quality glass) over the top half of the lens, but that would ruin shots where it is not necessary.
I have some times fixed it by pointing the camera more down, which gives less sky. But then you can see a lot of the dash board, like on http://www.mapillary.com/map/im/Fhp97V_MX257g8Uf5F0ASA

If possible I think a good fix would be to control which area the auto exposure should look at. If it only looks at the bottom half, the sky would get a lot less emphasis and in cities with tall buildings we still get good exposures.

It is just a pity that so many pictures are heavily under exposed.

**Comment by shlublu** [comment]
Same issue here. Quite often.

**Comment by peterneubauer** [comment]
Implemented in v 1.65. Thanks!
