### ISSUE TITLE
Image Info - can't scroll to it

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1176]
Good Morning,

I noticed this awhile ago.  I looked this morning and do not see an issue for it.  On my laptop, I can not access the image information box.   

If you look at my screenshots, you can see it just gets cut off on this smaller screen.  I've tried putting focus in it and scrolling a few other things.   I have been unable to scroll down.

If the issue isn't isolated to me, it would mean that anyone on a smaller screen can't download an image, share it to wikimedia, etc.  If there is any more information that would be useful for this problem, please let me know.

http://screencast.com/t/3Rt79uDjwNwW

http://screencast.com/t/VTDjrPzRIKXc

**Comment by gyllen** [comment]
This will be solved with new viewer update

**Comment by knikel** [comment]
@AllenGraetz Image info is displayed in the drawer now. This is no longer an issue. Thanks for the feedback.
