### ISSUE TITLE
Feature request: lock controls

### ISSUE THREAD

**Issue by zbycz** [mapillary/mapillary_issues#1177]
Hi,

When I use android phone mounted to my backpack, I often accidentally press some button which stops the recording.
Would it be please possible to add feature to freeze all controls? 

I know that the screen can't be turned off while recording aka #331, but locking controls seems solution.

**Comment by peterneubauer** [comment]
So, you can disable the volume buttons as shutter from the preferences. Dies that do the trick?

**Comment by zbycz** [comment]
No, sorry. I would need to lock/disable all On Screen Controls. (Possibly as well as android back+home buttons). 

The volume keys arent usually accidentaly touched, so these could stay "unlocked".

**Comment by filipca** [comment]
Have you tried https://play.google.com/store/apps/details?id=wq.lockscreen      ?
I have not.

**Comment by zbycz** [comment]
This app doesnt solve my issue. Its locks screen, so Mapillary stops taking photos.

Useful feature would be - on-screen button to lock controls + volume-key to unlock.

**Comment by peterneubauer** [comment]
Well, this is kinda hard to do since locking the back button and screen is blocking other apps too, like incoming phone calls. I would suggest not to do this, since it goes against the Android design guidelines to lock the menu system and implement your own locking behavior. A number of phone don't even have hardware buttons anymore ...

**Comment by filipca** [comment]
Then I suggest a hardware solution.
Stuff a small box with foam and cut a hole in it for the camera.

**Comment by zbycz** [comment]
Hardware solution is possibly ok. I need to cover especially the screen
part - because this gets the unwanted clicks.

You may close the issue..  Thanks.

út 28. 7. 2015 v 10:46 odesílatel filipca <notifications@github.com> napsal:

**Comment by peterneubauer** [comment]
Thanks @zbycz !
