### ISSUE TITLE
Feature request: multipoint syncing video with gpx.

### ISSUE THREAD

**Issue by rmikke** [mapillary/mapillary_issues#1178]
Right now syncing the video with gpx is simple and easy - I pause the video and mark the gps position.

But what if I get it wrong? When I mark a frame taken while riding it is easy to mark it wrong by, say, 10 meters. But when I mark a frame taken when I was stopped, it's even worse - the position will be correct, but there will be more then one point in track corresponding to that position and I have no control which one will be associated with the frame, which may affect the offset even by a minute, so the frames will be positioned even worse.

The solution would be getting more points for syncing from the frames taken while moving, then setting the offset to some average of the offsets in those points. It could be done by matching one frame as it is now, then clicking the button to add another sync point and again pausing the video and marking place in gps track. It should be possible to do it a few times.

**Comment by paulinus** [comment]
We have not done important changes in the video uploader in a long while. It is still running on the legacy site. We have no plans for updating it until we do a newer version.

Having more synchronization points will be a great addition to a newer version. We will keep track of the suggestion internally now that mapillary_issues is no longer an active repository. Thanks for the patience.
