### ISSUE TITLE
Please add fuction to access raw images taken by myself

### ISSUE THREAD

**Issue by kochizufan** [mapillary/mapillary_issues#1179]
Hello,

I love mapillary and started to use it for OpenStreetMap's mapping party, but it has many troubles.

There are some problems:

1. Images took long time to street view data, so I can't see them during mapping party's time immediately.

2. I want to know shops or amenities' names or informations from photo, but in mapillary, sometimes these informations are vanished by mosaic.

3. I want to use my photos not only for mappilary, OSM but also for Wikipedia or wikimedia. But Mapillary automatically put a logo to my photos, so I can't use these photos for Wikimedia.

I'm glad to allow my photos to use for mapillary, but my photos are belong to my copyright, so I have rights to use them for other services.

I want to make my photos taken by mapillary as CC0 ot CC-BY-SA, so I want to have a function to access my own raw images immediately.
Without this function, I must stop to use mapillary, but it is sad.

Regards,

**Comment by jesolem** [comment]
Hi @kochizufan 

The easiest way is to just copy the images over to a computer/SD card/harddrive before uploading them. That way you have the originals and can do whatever you want with them.

Implementing download of your originals will take some time. Keeping this issue for now.

**Comment by kochizufan** [comment]
Hi @jesolem ,

Thank you for replying.
As you say, since the function will come, I'll take original images before uploading.

But the most simple solution to solve this problem is, keep original images to iOS/Android's camera roll even after uploading, I think, isn't it?

**Comment by jesolem** [comment]
@kochizufan There is a save to camera roll function for individual photos that you want to keep. Saving everything would mean GBs of photos in the camera roll and actually not what most people want ;)

**Comment by kochizufan** [comment]
Yes, I think so.
But, selective save function is already exists?
If so, sorry, I can't found it.
I'll check app usage again.

**Comment by HolgerJeromin** [comment]
IMO Android app does not have this function.

**Comment by jesolem** [comment]
@HolgerJeromin Open the 1-up photo view in the app, there is a "share" icon left below photo. Tap that and you can save photo or share.

**Comment by kochizufan** [comment]
Thanks and sorry, I found "Selective save image" function in both iPhone and Android.
I made this issue, but for me, the problem is solved.

It is OK for me to close this issue.

**Comment by jesolem** [comment]
Thanks for reporting and keep the feedback coming @kochizufan !
