### ISSUE TITLE
Delete tracks

### ISSUE THREAD

**Issue by dr2okevin** [mapillary/mapillary_issues#118]
I have tried to upload a few hundred photos. It went wrong and I would now like to remove the broken track and try the upload again

**Comment by ToeBee** [comment]
I accidentally uploaded the same sequence twice so being able to delete one of them would definitely be nice.

**Comment by polarbearing** [comment]
Some test images without location data got uploaded, their sequences only show in Activities, not in Uploads, and when I click on the sequence image I only get the grey map without pictures. So I cannot even flag or hide them.

**Comment by liskin** [comment]
It'd definitely help to detect and delete duplicates. I tried uploading a set of ~2000 photos yesterday with upload_with_authentication.py but my connection was (still is and always will be)  a little wonky so some photos were discarded, so I told it not to finalize the upload and modified the script a little (https://github.com/liskin/mapillary_tools/commit/92336330704d29f70cdfc1a3f070c50705d3e7c1).

However, mapillary decided to process the sequence anyway, so I ended up with both of them: http://api.mapillary.com/v1/s/x9RQKYP_86gEmdcHq8wepQ and http://api.mapillary.com/v1/s/sa_HbMuWzSFZgOKhPi5WNA. The second one contains 2056 images, which is almost the 2058 I have uploaded, but that's probably fine. So I'd like to get rid of the first, shorter, sequence.

But careful there, https://api.mapillary.com/v1/s/gpx/sa_HbMuWzSFZgOKhPi5WNA.gpx always ends up in internal server error, unlike the shorter sequence, and my profile page says there are still 100 unprocessed images, and it's been claiming this for at least 10 hours now.

**Comment by bhousel** [comment]
Just would like to bump this issue - it would be really helpful to be able to delete my own sequences quickly in situations when I need to reprocess them.

I do know that I can delete a sequence from the web editor - but it enters a review queue and then I need to wait a while.  

I think a user should be able to delete a sequence immediately _without review_ if it is their own sequence.  Then the user should see the results of that deletion on the website immediately (i.e. I don't want it to appear in the right sidebar among my other uploads).

**Comment by gyllen** [comment]
@bhousel I agree on this. We are working on making the editing steps faster and more intuitive, the backend is there just not yet the frontend. Thanks for bumping.

**Comment by nicolas17** [comment]
There is a "Delete sequence" button now, so I guess this issue is fixed now.

**Comment by gyllen** [comment]
Yes, thanks for reminding me on this @nickplesha (closing)
