### ISSUE TITLE
Straight lines again

### ISSUE THREAD

**Issue by PeeWeeOSM** [mapillary/mapillary_issues#1180]
View this sequence. I've not uploaded any photo with a 01-01-1970 date stamp but some photos do have this. Strange.

http://www.mapillary.com/map/im/tqXCXB_Eg3Yo5znY3epIng

**Comment by ligfietser** [comment]
Bloodbath or vandalism? ;-)
![map](https://cloud.githubusercontent.com/assets/9638726/8890153/edece832-32f5-11e5-8dd9-955de4b20dd8.jpg)

**Comment by eugensim** [comment]
ISIL suicide attack :)

**Comment by Peatsmoke** [comment]
I've noticed there is a similar issue with a straight line between the start and endpoint from a sequence. Some of them disappear after a while, some of them don't.

http://www.mapillary.com/map/im/h8axoeCoK99wVOhb_xjU8w
http://www.mapillary.com/map/im/plQNctOJfZHOFhhWYnjrnQ
http://www.mapillary.com/map/im/bE2H0BZ9ygmkTditU2Mg1w
http://www.mapillary.com/map/im/UIELBHEGNxq8kPwQK8zr2Q
http://www.mapillary.com/map/im/o_m5r7-XCF2RqBx42F8NDg

I'm using a Garmin Virb Elite and the manual upload function.

**Comment by gyllen** [comment]
It "should" sort itself out, @PeeWeeOSM above sequence is now correct. Keeping this open since some sequences does not seem to behave.
