### ISSUE TITLE
Brightness broken

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1182]
Sometimes the Mapillary app stops adjusting to brightness. The only thing getting it to work again is to close down the app and start it again. What happens is that it doesn't adjust for bright light, so what you see is mostly over exposed light color. Using iPhone 5S.

Could it be an app thing or is it a phone thing?

**Comment by jesolem** [comment]
I suspect it is a camera thing. The app does not fiddle with exposure or any settings of the capture.

**Comment by millenbop** [comment]
Don't think there is much we can do about it. We are using default settings for that, and default is AVCaptureExposureModeContinuousAutoExposure, i.e. it should continue to measure exposure.

I'll add an explicit configuration for that in case some other app might change it to something else (if that's even possible).

**Comment by millenbop** [comment]
So this will be in next release. If problem persists, we'll reopen the issue.
