### ISSUE TITLE
Activity: Upload Date or Capture Date?

### ISSUE THREAD

**Issue by canadarunner** [mapillary/mapillary_issues#1183]
Actually the activity-box shows when the images are uploaded.
For me it would make more sense, that the capture date would be shown in the box.
For example.: After a big trip without any internet connection, the upload takes several days and the box shows the numbers uploaded images distributed over these days.

**Comment by HolgerJeromin** [comment]
Also the sequence list is quite random due to upload time.

**Comment by gyllen** [comment]
This is actually by choice we do want users to see their latest uploaded images, not the latest captured images. For the activity box we might actually change that to captured at since that makes more sense. What do you think @knikel ?

**Comment by knikel** [comment]
@gyllen agreed, :+1: for the captured_at in the activity box

**Comment by knikel** [comment]
We've rolled out new components which reflect the recent activity so much better. Closing.
