### ISSUE TITLE
better list of tracks in profile

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1184]
Hi

I would like a better overview of my uploaded tracks in my profile. Instead of pictures only, I wish a real timeline, or calendar.
E.g.  year/month/date and if I click on them, they expand in time with the tracks shown, like windows explorer, KDE Dolphin,...
-2015
 |-July
||-26 - track1 Picture
||-26 - track2 Picture
.....

Also: please add a small icon/noticfication if the track was edited by user, but NOT yet applied by you.
Also maybe another icon if track was edited and already successfully applied by you.
(enhanced: different icons for blur/position/hiding changes)

echelon

**Comment by knikel** [comment]
We'll have your username filter applied to the map when looking at the profile in the upcoming mapillary.com update. Will close when rolled out.

**Comment by gyllen** [comment]
User filter is now added, you find it under the second tab in the new viewer

**Comment by polarbearing** [comment]
With second tab, you mean the upload tab?  There is a switch to show my/all tracks in the map.

But I cannot see a listing as @echeloni2p has described it. There is the endless list of uploads, and no chance to go to a particular date beside scrolling, scrolling, scrolling. Try to search your upload from a year ago, and you drive yourself mad, and your browser into memory explosion.

See also #1974.

**Comment by gyllen** [comment]
So by that button you get the filter on the map. If we added a time filter there too, would that be enough?

**Comment by echeloni2p** [comment]
Hi!

Not really. Some kind of text listing in a advanced tab would be nice, text only, sorted by date, number of pictures, and place. 

echelon

**Comment by gyllen** [comment]
@echeloni2p So basically a better filter on your (or someone elses) photos in their profile?

**Comment by echeloni2p** [comment]
Hi!

In case of DB access: yes, a better filter.
In case of UI: I want a text listing of my Upload/tracks in textform with a date and a place where they are, maybe a sample picture included.
So that I can easily overview my Uploads done in october 2015, dec 2014,.. 
You can extend this to changesets so that I can check if my cheangesets were already applied and on which uploads/tracks changesets were done at all.
Currently I do not know which changesets I did made and which are applied, where changesets make sense or not...

echelon

**Comment by gyllen** [comment]
@angelday Suggestions for how to filter for the user, I actually like text only. Makes sense.

**Comment by angelday** [comment]
@echeloni2p is this the problem you'd like to have us solved:

> I do not know which changesets I did made and which are applied

**Comment by echeloni2p** [comment]
Hi!
This is the main issue. Also the date of them.

echelon

**Comment by gyllen** [comment]
Added to idea box around better profile

@angelday FYI

closing
