### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1185]
Hi!

I made >50 changesets the last weeks. For most of them I got a message "changeset registered", as of holiday season I know they are accepted rather slow.
Now I made a few changes the last days and they were accepted in hours timeframe and I got a email about the accepted changesets, also those are noted in my activity timeline.
But the old changes I made seems to be active, e.g. all the changes made in the area around Hildesheim, Germany, seems to be active applied, but I got no email neither a notfication in my activity section in my aceini profile.
http://www.mapillary.com/map/im/JWoU5guMofc5_eOiXlLedg
http://www.mapillary.com/map/im/jgXxwRjAiqcZeotTqouA1w

Is there any chance to get the notification?
I want to check if I need to do more changes to the tracks and where I can go on edit safely and where I need to wait until old changesets were applied... (there is no overview of which tracks were changed/in waiting..)

echelon

**Comment by gyllen** [comment]
We has some issues with notifications, these should now be solved
