### ISSUE TITLE
Can't view all comments on a photo

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1187]
This image have 3 comments, but only 2 shows up:
http://www.mapillary.com/map/im/oZhnyrVJV1fllnCWwLOC0w

**Comment by domdomegg** [comment]
I see all 3 now on both the old and beta sites. Fixed?

**Comment by knikel** [comment]
@jrcarlsen, @domdomegg: it is fixed in the beta viewer, but I had to switch off the comments in the standard viewer for the time being, we're updating a lot of templates at the moment; they'll be back shortly.

**Comment by knikel** [comment]
@jrcarlsen, @domdomegg: In the updated viewer, the comments are scrollable in the drawer now. Hope that solves your issues guys? Commenting now happens in the modal.
