### ISSUE TITLE
Localisation defect

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#1188]
Your website is defect. See screenshot.

![mapillary-defect](https://cloud.githubusercontent.com/assets/3611273/8957603/cdd88e5e-35ff-11e5-95cc-b783bfb24629.png)

It seems like your localisation does not work.

**Comment by knikel** [comment]
@Nakaner which browser are you using? Try reloading with clearning cache. Might be an after deploy hiccup.
