### ISSUE TITLE
Reverse play

### ISSUE THREAD

**Issue by Jopparn** [mapillary/mapillary_issues#1189]
The play button is very useful, however, I would love if it could also play backwards/reverse play. I.e. that you ride back the way you came.

**Comment by shlublu** [comment]
Me too. And/or a "back to picture 1" button.

**Comment by knikel** [comment]
We have this functionality implemented in `mapillary-js`. Labelling as a fetuare request for the upcoming update of mapillary.com

**Comment by gyllen** [comment]
@oscarlorentzon We talked about doing this right?

**Comment by oscarlorentzon** [comment]
As @knikel said the library supports playing in any direction. Only problem is that we do not have a UI element in the library for actually playing backwards in a sequence. 

Tracked here mapillary/mapillary-js#170

**Comment by oscarlorentzon** [comment]
[MapillaryJS 2.10.0](https://github.com/mapillary/mapillary-js/releases/tag/v2.10.0) supports reverse play . Try it in the [examples section](https://github.com/mapillary/mapillary-js#examples). [mapillary.com](https://www.mapillary.com) will be updated in the coming days.
