### ISSUE TITLE
It is not possible to approve or add traffic sign on this photo yet. 

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#1190]
Uploaded photos one week ago, still haven't any traffic signs available. This message is show: It is not possible to approve or add traffic sign on this photo yet. Something wrong?

![bildschirmfoto von 2015-07-29 19 24 59](https://cloud.githubusercontent.com/assets/3539168/8964752/b6e1334a-3627-11e5-826e-9b14cc223541.png)

**Comment by gyllen** [comment]
We are working on improving traffic sign detection algorithm. Soon we will run it again on europe. Sorry for the delay (we just don't want to run detection in vain).
