### ISSUE TITLE
huge offset between picture and location

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#1191]
I regonized a gap between the gps-informations and the photo. I used an iPhone 4.
For example is this picture http://www.mapillary.com/map/im/nBetcJvJ08Kk-3QSE2Av2Q in reality 730 meters behind: http://www.openstreetmap.org/directions?engine=osrm_car&route=50.88750%2C7.05576%3B50.88088%2C7.05556#map=16/50.8842/7.0557

Today I was "mapping" while cycling. When the iPhone switches off the display, I couldnt here the photosound and it stopped. While pushing the home button an wiphe the screen it continued. I did it manually. Maybe the recordings are continued after a longer period with using old cached gps-informations...

**Comment by jotpe** [comment]
I deactivated the display timeout. Now, the recorded sessions are fine.

**Comment by jotpe** [comment]
My last post is not correct. There is still a gap, but a smaller one:
This photo http://www.mapillary.com/map/im/bJsyPgLXlBpJ_43Bx8widA/photo is located here http://www.openstreetmap.org/?mlat=50.90814&mlon=7.04714#map=19/50.90814/7.04714

**Comment by jesolem** [comment]
Thanks. We will investigate. There is something that breaks in dimming when you close the app with the camera open, I suspect a bug there.

**Comment by millenbop** [comment]
I've tried to reproduce it on my iPhone 6 with iOS 8 and it works just fine. I'll try it on an iPhone 4 and iOS 7 and see if I can reproduce (and fix) it.

**Comment by millenbop** [comment]
It appears that the system camera view sometimes enables the screen dimming/sleeping, so I've moved the code that disables it to AFTER the camera view is displayed instead of before. Seems to work better on my device though so hopefully it solves the issue for you too.

**Comment by millenbop** [comment]
It will be available in next release. Plan is to upload a new release this week.

**Comment by jotpe** [comment]
I will try it, thanks.
