### ISSUE TITLE
Infinite loop while viewing pictures

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1193]
Not sure if this is related to the new UI or a problem in the actual sequence data. I just noticed it while poking around the new UI.

View this picture: http://www.mapillary.com/map/im/BEo2ng-_Jso7LflqAC_hqw/photo
and now keep clicking the up arrow. It keeps going back and forth between two pictures and never actually advancing further down the sequence.

Not sure if this might be related but a few pictures earlier in the sequence, something seems to have gotten a little confused about the direction of the image. When you click on the "Next" arrow from this picture, the transform seems to indicate that the view angle is flipping around. http://www.mapillary.com/map/im/UE28GKj6y_KUjLqgYOHnVA/photo

The new UI doesn't seem to indicate directionality of the picture anywhere so I'm not sure if something is off or not.

**Comment by richlv** [comment]
that might be a widespread issue - here's another case : https://www.mapillary.com/map/im/5CWccA_wPO-o8Gu1R4fkhA/map

**Comment by gyllen** [comment]
We are on it, will be solved very soon

**Comment by gyllen** [comment]
Fixed, shift+reload

**Comment by polarbearing** [comment]
Still observing such loops, though involving more than two pictures.

**Comment by richlv** [comment]
@polarbearing, it was also looping over a few more pictures for me (i had reloaded the page), and it did so 3-5 times - then it stopped. try moving over that part of the sequence a few more times, does it still happen ?

**Comment by de-vries** [comment]
I found some weird loopyness: http://www.mapillary.com/map/im/VVcjE4fZqqw-aiB6rREzCA/photo try moving forward and backward.

**Comment by richlv** [comment]
another loop - try moving forward and see how weird it acts :
https://www.mapillary.com/map/im/din2Ri7P28ncXsMOSwvjog/photo

could we please reopen this one ? :)

**Comment by richlv** [comment]
i guess the new ones are caused by the 3d reconstruction getting it all wrong and a way to follow a sequence is really needed
