### ISSUE TITLE
empty "blurring" section

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1194]
in the new interface, click 'edit', then 'blur'. a new expandable section "blurring" appears at the bottom, but it's empty and does not seem to have any purpose

**Comment by knikel** [comment]
@richlv You should be able to see at least two buttons. Does it happen to you everywhere or on just a particular photo?

**Comment by richlv** [comment]
there are two buttons in the "edit" section, but nothing in the "blurring" section at the very bottom of that panel - see the screenshot

yes, this happens on all photos

![blurring](https://cloud.githubusercontent.com/assets/112888/8988196/6cacf658-36ed-11e5-880e-07c4444dddd6.png)

**Comment by knikel** [comment]
@richlv Thanks for finding it there. It's a leftover from initial prototype. I've been looking at this for too long to realize it's not necessary. These two (or three) buttons is all you need though :). It'll be gone in few minutes. Thanks!

**Comment by richlv** [comment]
for the record, seems to be gone now - thanks :)
