### ISSUE TITLE
map jumps to the previous position on the other view

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1195]
open a photo. switch to the map view, switch back to the photo. move forward in the sequence. every time map jumps back to the position that was last opened in the map view, then zooms to the correct position.

the opposite is true as well - in the map view, map jumps back to the position last viewed in the photo mode

tested with firefox 39.0

**Comment by knikel** [comment]
@richlv This should be fixed now. Thanks for the feedback!
