### ISSUE TITLE
Can't see edit butons when not logged in

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1197]
Congrats on the new viewer!!

I just opened the edit widget in the sidebar and it was empty, it took me a while to figure out that I wasn't logged in.

**Please add a warning that you have to log-in to edit, or disable the edit widget all together for users that aren't logged in.**

ps. I love the new viewer, thanx for this!

**Comment by knikel** [comment]
Thanks @de-vries, it's been fixed now, the whole section is hidden, I've overlooked that. Glad you like the viewer!
