### ISSUE TITLE
tracks shown, not able to edit

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1198]
Hi!
 While #1158 is closed, I can see the pictures.
But I cannot edit the track.
It tries to load and keeps the loading frame forever.
If I try to edit the traffic signs, it shows: This photo hasn't been processed yet. You'll be able to add traffic signs soon.
But the photos are already online for 3 weeks. Anything I can do?

**Comment by de-vries** [comment]
I believe your answer is in #1190

**Comment by echeloni2p** [comment]
Hi

no, thats not that error. In #1190 you cannot edit traffic signs, but the edit button opens the well known edit page in which you can move the picture positions. But on my tracks that edit page does not load any picture...

**Comment by ybkuang** [comment]
@echeloni2p We are working on a new version of the traffic-sign detectors. So the processing has been paused during this period. We are close to release now, so bare with us a few more day. Sorry about the delay!

**Comment by polarbearing** [comment]
Same problem as in the OP with editing, with a sequence that had previously metadata problems as in #1158

**Comment by echeloni2p** [comment]
Hey

any followup on this one?
 thank you

**Comment by ybkuang** [comment]
@echeloni2p we started the processing. It is catching up.

**Comment by echeloni2p** [comment]
Hi

Ok, now I can edit blurs, but cannot edit position of picture, it just does not load the sequence if I click on edit button.
http://www.mapillary.com/map/e/MW4D_lsLh0ElIECKGjKyIQ hangs and hangs and hangs forever...

**Comment by knikel** [comment]
The editor got a revamp. You should be able to edit photo position in a better way now @echeloni2p.

**Comment by echeloni2p** [comment]
Hi!

Yes, it seems to work now.

echelon

**Comment by knikel** [comment]
Awesome!
