### ISSUE TITLE
Possibility to rotate pictures

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1199]
Hi

In edit mode: pleas add a button to roatate picture by 90/180 degrees. Sometime the sensors of mobiles is crazy. E.G.: Photo key: FEWVsjlMIu-XzBr9DXlFtg
Sequence key: Fi9WM3T1Eynq8BF2xUTsfQ
Photo key: 0V2nkniYsbNXG3xn3Xla8w

**Comment by HolgerJeromin** [comment]
There are quite a few issues for that already. #439 or #811 to name a few :-)

**Comment by jesolem** [comment]
Yup. Dupe, and highly non-trivial to implement. We will get there one day though.
