### ISSUE TITLE
Let add sequence autostart recording

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#120]
Starting to record a new sequence always requires the pression of two buttons: first the add new sequence button and then the start recording button. As while driving the splitting sequences timing is critical, it would be useful if this all could be accomplished with a single button press. That is, in driving mode, if recording is active (not paused), the pression of the add sequence button should start the new sequence already in recording mode. Also, not to distract excessively from driving, the start of the new sequence should be visually made very evident, like by making the whole screen flash.

**Comment by HolgerJeromin** [comment]
On the new android app you have no "new sequence" button anymore. So i think this can be closed
