### ISSUE TITLE
Inappropriate pointer when drawing sign or blur

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1202]
Hovering over the photo in photo-view the "grab" pointer is always used. Also when in edit mode when dragging over the picture doesn't move the pic but draws a new sign or blur. In those cases the "croshair" pointer would be more appropriate.

**Comment by oscarlorentzon** [comment]
Thanks for reporting @de-vries ! This is now fixed and will work soon. The grab cursor is not shown when blurring or editing traffic signs anymore.

Using a crosshair cursor is also a good suggestion! When blurring or editing traffic signs a crosshair cursor is now shown while hovering the viewer and when creating blur rectangles. The cursor for the "resize traffic sign rectangle" button is kept as is.
