### ISSUE TITLE
Editing angle on sequence only partially approved

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1203]
I had applied for angle correction (30 deg left) for a long sequence, and find it now corrected for the first part of the sequence only. Correction stops at ```pdVTq2M8yLWIu1zTQrx70Q``` , from there on the sequence still looks straight. Was the sequence too long so that some overflow happened?

Traced the cs id: 7Ai-DByq5DtNsvWs9Vk1FA , there were 322 angle changes listed, but the sequence is between 400 and 500 images.

**Comment by de-vries** [comment]
duplicate of #991

**Comment by gyllen** [comment]
Fixed in new editor.
