### ISSUE TITLE
No Edit Option On Photo When Logged In

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1205]
I'm not seeing an edit photo option in the new viewer.  I know when I used the beta there was one.  Has that been removed?  If not, it's possible bug.

http://screencast.com/t/J5N3NpUSG7g9

**Comment by knikel** [comment]
Hi @AllenGraetz, what you're seeing is a fallback view because your browser doesn't support WebGL, which is necessary for editing in the new interface. I know this might be asking a lot, but would you mind giving it a try in Chrome/Firefox?

**Comment by AllenGraetz** [comment]
I wouldn't mind at all because that's what I was using.  :)   

I did check when I got home because I thought maybe something on the work network was blocking things.

Right now though it's good in MSIE 11.0.9
http://screencast.com/t/f7vixeAd

But no edit section in Chrome Version 44.0.2403.125 m.  As you can see from this screen shot, two resources are erroring out.  
http://screencast.com/t/aOLucrkyN

This may be related to the possible issue with resource(s) not loading and causing things to fail ( https://github.com/mapillary/mapillary_issues/issues/1217 ).  Although in this case, it would make sense that "edit" wasn't available if it needs those two things to fail.

I will make a point of taking a  look at this when I'm at home to see what I have running.  

I did go through different photos in chrome just now and I can not get one without those same two errors.

If there's anything else I can do to help, please let me know.  I don't mind  These sort of things can be a pain.

**Comment by gyllen** [comment]
Hi Allen,

Can you try to login/logout

**Comment by gyllen** [comment]
Hi @AllenGraetz,

Realize my guess above was a little uneducated. What happens is probably that we fail to detect that your browser supports WebGl. Lets figure this out. How well do you know the java console in the browser?

**Comment by ToeBee** [comment]
I noticed this as well. After noticing that the map view doesn't work either because of WebGL failing to load I wondered if it was connected to the missing edit option. I'm using chromium on linux. http://get.webgl.org/ reports:  
> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

I'm not sure what's going on because Firefox **does** work. But either way in my case it is something in my setup, not Mapillary's fault.

It would be nice if Mapillary detected broken WebGL and showed a message instead of a broken page though. I see a "Failed to initalize WebGL" message in my dev console. There is also this error, not sure if it's related to WebGL or not:
```
 TypeError: Cannot read property 'resize' of undefined
    at util.extend.resize (https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js:162:2675)
    at new module.exports (https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js:162:1495)
    at new controller (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-16b878aa.js:13769:17)
    at Object.e [as invoke] (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:913:58)
    at R.instance (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:954:168)
    at M (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:935:373)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:213)
    at M (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:936:116)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:213)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:236) <div ui-view="">
```

**Comment by knikel** [comment]
@ToeBee thanks for reporting. This is a related issue to #1245 and #1230. We do have checks in place, but they seem to fail when the browser is capable of WebGL but something else fails. I'll look into finding a more universal solution for detecting half-working WebGL

**Comment by AllenGraetz** [comment]
Thank you.  I'm not too familiar with doing this, looking at the java console and WebGL.  I plan on chipping away at this some more later this week or early next.  

From the question and seeing some other stuff, it sounds like I would be able to provide more useful information in when I run into those things.

**Comment by ToeBee** [comment]
Well, I just fixed my problem. There is an advanced setting in Chrome. It is a checkbox with the text "Use hardware acceleration when available" and it was unchecked. After enabling this and restarting Chrome, Mapillary works as intended.

**Comment by knikel** [comment]
@AllenGraetz the WebGL is not as strict as it used to be. Can you see the edit button and WebGL map now?
