### ISSUE TITLE
Move forward vs. Next Photo

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1206]
In the new viewer, it appears that the "Move forward" control (full arrow) jumps to the next-best picture to the current location, whether it is in the same sequence or not. Only when there is no picture in the forward direction, I get the "Next Photo" control (arrow tip) that jumps to the next picture in the same sequence. 

That might be desired behaviour for a user that wants to look around, but it makes reviewing own sequences in the new viewer impossible, if there are other sequences on this road. I am constantly jumping onto other sequences, thus I might miss pictures in my sequence for review. 

Maybe we need the "next in sequence" in addition to the "Move forward", not as alternative.

**Comment by paulinus** [comment]
You can drag up/down to go to next/prev on sequence. Play will also follow the sequence. No buttons for now, though.

**Comment by gyllen** [comment]
We had a discussion about this. We should probably have a more advanced control system for experienced users who understands the concept of sequences.

**Comment by knikel** [comment]
Yup, we should add some kind of mechanism that _locks_ the user to the sequence.

**Comment by polarbearing** [comment]
Yes please. While the swiping works, it is an awkward mouse movement when doing often, and leads directly to [RSI](https://en.wikipedia.org/wiki/Repetitive_strain_injury) from 400 images per sequence onwards. 

Mouse swipes also interfere with drawing blurs when the new blur-editing is switched on.

**Comment by richlv** [comment]
best would be a small option somewhere - cursor keys to control image or sequence. dragging is pretty much unusable as i never know by how many images it will jump - and, as noted, doing that over a larger amount of images is not something one would want to do :)

**Comment by knikel** [comment]
@richlv well, it depends :wink: While I can see your point and understand that you prefer to focus on particular photo and what it contains, there are other use cases where people just want to _browse around_. Dragging is means to help out with just that and speed up the process. But I agree, we need better means for more granular control in the UI.

**Comment by richlv** [comment]
absolutely - i was commenting in the context of reviewing sequences :)

**Comment by richlv** [comment]
it would also be useful to expose "snap to sequence" in the url. that way one could share an url "take a look at how this place looks like during some event" without the viewer getting completely unrelated images and getting thrown on a different course

**Comment by jfburke3** [comment]
A checkbox "lock to sequence" would do the trick in the UI.  Small, unobtrusive, easy to use.

**Comment by de-vries** [comment]
Another solution would be to use a modifier key to the hot keys. You can use  the arrow keys for normal browsing, (like it's now) and with shift-arrow you could browse trough a sequence. 
I really like the hot keys, so I would use such a feature a lot.

**Comment by richlv** [comment]
i love both checkbox and modifier key ideas. i got a bit annoyed yesterday, as the 3d reconstruction is lacking in some areas, and there are images i just can't get to...
note that a url parameter would still be very useful, as that would allow me to share such sequences without driving other people crazy :)

**Comment by vincentdephily** [comment]
Same here, it was painful to review http://www.mapillary.com/map/im/AHHK7AM9E5bTmwMJLtB4fA , because the "browse around" arrows are all messed up (that'd require an issue of its own, but I guess you're still working on those algorithms anyway) and because I'm mainly editing blurs, so draging doesn't work as a prev/next. I'm sure I missed some photos.

To me, prev/next buttons on either side of the play button would make the most sense. The "lock to sequence" checkbox is also interesting; it'd be nice to lock when clicking on the map, but it might look weird if it's used to filter out different-sequence browsing arrows.

**Comment by gyllen** [comment]
@richlv @vincentdephily pro time for now, you can use the keyboard up/down to move to next image

**Comment by richlv** [comment]
oooh, there's "lock to sequence" in the edit menu now - cool, will have to test it some :)

**Comment by oscarlorentzon** [comment]
We have added Lock to sequence in the Edit accordion so it is available as an advanced feature for users that are logged in.

**Comment by richlv** [comment]
thanks, that is already a great improvement - but could we have a url parameter that would also affect users that are not logged in ? for example, i'd like to share a sequence, but it jumps to side sequences very quickly making such sharing useless...

**Comment by knikel** [comment]
@richlv +1, good point, we should add `&lock=true`

**Comment by richlv** [comment]
i use the button a lot, the url parameter still desired :)

**Comment by knikel** [comment]
Closing we're tracking this internally
