### ISSUE TITLE
"Edit via JOSM" link in new viewer has top and bottom reversed

### ISSUE THREAD

**Issue by lordsutch** [mapillary/mapillary_issues#1209]
Clicking on the Edit via JOSM link results in a URL such as the following:

http://127.0.0.1:8111/load_and_zoom?left=-84.2501363399924&right=-84.24913633999239&top=39.57926633932621&bottom=39.580266339326215

which results in a "400 Bad Request" from JOSM, since the latitude of "top" is less than the latitude of "bottom."

**Comment by gyllen** [comment]
I can see the error, deploying a fix.
