### ISSUE TITLE
Please, add zoom for photos

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1210]
Please, add zoom to photo. At least as with old editor, better - with mouse scroll zoom.

**Comment by knikel** [comment]
@iav, yes we'll add it when we find a better way of panning without weird side effects in the CSS (blurry controls). Most of this is in place, but not enabled yet.

**Comment by jfburke3** [comment]
That's good to hear.  Zoom & pan are incredibly useful when using pics to update OSM!

**Comment by knikel** [comment]
This is already implemented in `mapillary-js` which we're using for the upcoming mapillary.com update. More info [here](blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html). Closing, since we have #1087
