### ISSUE TITLE
How to get a map with all tracks and roadsigns?

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1211]
How to get a map with all tracks and roadsigns?
I can't find it. If it present - please, make it more easy discoverable. If not - please, make it back.
It was easy in past to look with eye for strange, unusial or phantom roadsigns in places I know - and then click to it and get a photo to edit. Now the one way I see - to start from sequence (how to start except my ssequences from my profile?).

**Comment by knikel** [comment]
@iav Thanks for reporting. I've added traffic signs to the map view. If you turn enable them in the photo view it will work in the map one and vice versa. My fault it wasn't there in the first place. Hope it helps!
![traffic-sign-filters](https://cloud.githubusercontent.com/assets/1574656/9004316/3f1bfa8a-3775-11e5-91d6-591bae1eba28.png)
