### ISSUE TITLE
Make a hi-res photos viewable/zoomable

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1212]
As I can see now the highest image quality accessible is 2048 pixels long. 
But I upload a 2 times more detailed pictures. Please, make maximum quality pictures accessible (it can be useful to read texts and for roadsign detection).
Or, if not - at least tell why it's shouldn't.

**Comment by jesolem** [comment]
@iav Thanks for bringing this up. 

We are generating a fixed set of image resolutions for each image (320px, 640px, 1024px, 2048px). Right now we are limiting it to 2048px to keep costs reasonable.

Every time you view a photo on Mapillary there is a cost for serving the data. The bigger the image file the higher the cost. 

I agree with you though and I'd love to move to a point where we can add an original resolution version to the list. We are waiting with that for now though until we have more data on traffic/cost/financials to make that switch.
