### ISSUE TITLE
Not clear how to edit roadsigns

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1213]
Not clear how to edit roadsigns with a new editor.
1. how to change a type of already existed sign?
2. how to move without resizing existed sign? dragging over a bottom left corner with sign icon not moves upper left corner
3. how to know what sign will be added?

**Comment by knikel** [comment]
@iav good points, we've ported just the very basic version of the traffic sign editor to the new viewer. It'll improve soon.

1. There is no possibility to do that, you have to remove the sign and add a new one. This will be fixed and will work as in the old editor.
2. Same as above
3. In the traffic sign picker the currently selected sign will be highlighted.

I will close this issue when these features will be out.

**Comment by knikel** [comment]
The editor will be hugely improved soon, it'll have a similiar flow as [here](blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html)

**Comment by knikel** [comment]
I'm closing this issue, since this is part of `legacy.mapillary.com` which we want to deprecate at some point. 

However, I'm looping in @amahon to consider _Add manual traffic sign editor_ as a feature.
