### ISSUE TITLE
Clicking on images in the profile activity no longer takes you to the sequence.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1216]
Go to a users activity page:
http://www.mapillary.com/profile/hantms/activity

Click on an image, and you'll get redirected to:
http://www.mapillary.com/map

**Comment by lordsutch** [comment]
Duplicate of #1215

**Comment by knikel** [comment]
@jrcarlsen, @lordsutch Thanks for catching this one. It's fixed now!
