### ISSUE TITLE
HTTP errors block interface

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1217]
This issue is a more general version of #935 

Whenever there are HTTP errors, such as timeouts or service unavailable errors, then these aren't handled in the user interface. Sometimes the loading animation will just show forever, other times the interface will just not react to any clicks.

For example, currently I'm receiving 12 separate "503 Service Unavailable" errors when opening my profile page (all from https://a.mapillary.com/v2/, although other request to that server are handled just fine). The result is nothing is shown on the screen, only an indefinite loading animation. However, if I manually disable the style on ".ng-hide", I can see that almost everything of the interface has loaded just fine, and I can interact with the page.

Whenever there are HTTP errors, *only* the page components that are relying on that service should be disabled, not the entire page. And an error message should be presented to the user.

**Comment by ToeBee** [comment]
I'm seeing this in the new interface while trying to view blurs. I just got a 503 from https://a.mapillary.com/v2/im/vP_bfx8-z2ZqquunuyOpDQ/b  
but the "Loading blurs..." text is still showing in the UI. If I unselect the Blur button and then re-click it, it loads fine again.

**Comment by pbb72** [comment]
In the new photo view, while going from photo to photo, I am also regularly getting 503 errors, which result in an indefinite loading animation on top of the previous photo. At that point, all navigation arrows have been disabled, so it is impossible to try again by clicking again. The only solution is to reload the whole page, or going into the Edit interface and exiting there again.

(Note: trying again after a reload often continues giving a 503 error, so it seems there is a good number of photos that are causing errors.)

**Comment by knikel** [comment]
@pbb72 Would you mind pasting an error log you're getting?

I'm wondering if this is precaching that is causing it, @gyllen?

**Comment by pbb72** [comment]
It could well be right that it is a caching issue, because now I am not getting any 503 errors. I will update when I find more!

**Comment by pbb72** [comment]
If I go forward from http://www.mapillary.com/map/im/8H4tz-wBbwelQz7Nnbm7Bg/photo, then I get a 503 Service Unavailable on https://a.mapillary.com/v2/nav/im/j5PRIsFXl0C5yelpLAUzzQ?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&ss=Jbb9yD-xnggrioATbdudRg&ss=OvARr9DRnRqg0W_8YwphJQ&ss=S99av12b4rjgqhzrE28fbg&ss=G6ALAWK3byPFtuo0uDybOw&ss=_wzcVjWGZft-P-nPBMKEhA&ss=gf5_TfQ2OlbmGdWjCFsXIw&ss=Od8HFCPocmcyPYowih5Rxw&ss=8HKk81wiYDNoZbDHWzmQ6Q&ss=zi0z_lblw3S7Uy6vuorj5g&ss=YBDoajSLILdl7yJRJpxg5A&ss=dphQAFKvsynbCEyanSK0lQ&ss=9UuPptIAn66mV_YQhqvIyg&ss=MzshzKBgRrDSkVQ8ans5cw. The problem persists on different browsers, so it is not a local caching issue.

I'm not sure what kind of error log you are referring to. Do you mean the console log?
```
 _ _ _              _  _              
' ) ) )            // //              
 / / / __.  _   o // // __.  __  __  ,
/ ' (_(_/|_/_)_<_</_</_(_/|_/ (_/ (_/_
          /                        /  
         '                        '   
You are quite a hacker (1337)
File bugs at https://github.com/mapillary/mapillary_issues
or get a job at http://www.mapillary.com/jobs
THREE.WebGLRenderer 70
GET https://d1cuyjsrcm0gby.cloudfront.net/8H4tz-wBbwelQz7Nnbm7Bg/sfm/v1.0/atomic_mesh.json 403 (Forbidden)
GET https://a.mapillary.com/v2/nav/im/j5PRIsFXl0C5yelpLAUzzQ?client_id=MkJKbDA0…dphQAFKvsynbCEyanSK0lQ&ss=9UuPptIAn66mV_YQhqvIyg&ss=MzshzKBgRrDSkVQ8ans5cw 
XMLHttpRequest cannot load https://a.mapillary.com/v2/nav/im/j5PRIsFXl0C5yelpLAUzzQ?client_id=MkJKbDA0…dphQAFKvsynbCEyanSK0lQ&ss=9UuPptIAn66mV_YQhqvIyg&ss=MzshzKBgRrDSkVQ8ans5cw. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access. The response had HTTP status code 503.
```

**Comment by knikel** [comment]
@pbb72 sorry for not being explicit; yes, the console log :smile:.  Thank you very much! Now we're a bit closer to solving that.

**Comment by knikel** [comment]
@paulinus, @ybkuang: there is an issue with atomic meshes here.

**Comment by paulinus** [comment]
SfM has actually never been run for that sequence, so not having the atomic mesh is normal, and the viewer should not try to load it. Something is wrong on the database for that image that is both preventing the SfM run, and making the viewer not to display user or date information.

**Comment by pbb72** [comment]
Note that this bug is ***NOT*** about that specific image/sequence, but about the web interface freezing whenever there are HTTP errors.

The web interface should stay responsive, even with unexpected failures.

**Comment by paulinus** [comment]
good point, sorry for going off-topic. I'll add an issue to track that particular sequence.

@knikel you may want to close this one if that is going to be fixed by the new web

**Comment by knikel** [comment]
I'm closing this because we won't fix it in the current state of mapillary.com. We need to handle such error in `mapillary-js`, there is an issue for that already - https://github.com/mapillary/mapillary-js/issues/133
