### ISSUE TITLE
The new image viewer uses low resolution images

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1218]
The new interface seems to use pretty low resolution images (640px?), which when scaled to FullHD or a Retina display looks very blurry.

Is it possible to select the scaled images better based on the actual browser resolution?

**Comment by gyllen** [comment]
Will fix so we get same behaviour as in old viewer. When moving stops we should automagically replace image with higher resolution.

**Comment by jrcarlsen** [comment]
That sounds like a good solution

**Comment by richlv** [comment]
looks like this has been implemented for a few days already ?

**Comment by oscarlorentzon** [comment]
You are right @richlv , this has been fixed. Thanks for notifying that the issue had not been closed. 

And thanks for reporting in the first place @jrcarlsen !
