### ISSUE TITLE
Android client not captures with 1 sec pause

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1219]
With new (from google play) android client I set capturing interval to 1 sec.
When I start riding I got one shot and then just nothing. No errors, no shots.
Then I change interval back to 2 sec - and captiring start work.

Mu smartphone is Samsung Galaxy S4 GT-I9505, Android 4.4.2

**Comment by peterneubauer** [comment]
Any chance you can send me the logs via the main drawer menu?

**Comment by iav** [comment]
Look in your default mailbox with bug number in subject

**Comment by peterneubauer** [comment]
@iav is this still not working? Feel free to reopen the issue if it is present with v 1.56 now.
