### ISSUE TITLE
Login issues and security concern

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_issues#1220]
I'm currently unable to log in to mapillary.com. By itself that's not a huge problem, though I don't know if it's my problem or yours, but after it fails you're sending my password back as part of the URL. Is this meant to be happening? I'm hardly a security guy, but it seems a little unsafe, and I'm not exactly comfortable with having my account details in my browsing history.

Also, some of the text is missing - "{{failure_msg}}" instead of whatever should be there, and nothing next to (what I assume is) the 'Remember Me' checkbox.

I'm currently experiencing these issues in the current versions of Firefox (39), Edge (20?), and the Windows 10 version of IE11. This has only happened after the upgrade to Windows 10, so part of it might be my fault, but surely not the password-and-user-name-in-plain-http-URL bit.

![mapillarylogin](https://cloud.githubusercontent.com/assets/8445671/9020295/c96fd900-3846-11e5-8b0d-778ddccbc0af.jpg) Screenshot of Firefox with personal details somewhat obscured

**Comment by gyllen** [comment]
Thanks for reporting. Fix now deployed. Should be online in like 3 mins.

Also we are not sending anything back plain, things are showing in url because of site error, its not a return from our servers.
