### ISSUE TITLE
"Error: sV2 is not defined" when trying to mass-correct angles

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_issues#1221]
In the edit window, trying to change the angle for an entire sequence by clicking the 'Correct angles' button has no obvious effect, and produces this error in console:
"Error: sV2 is not defined
.link/$scope.correctImageAngles@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-faf4e683.js:9481:13
anonymous/fn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js line 1081 > Function:2:242
Ac[c]</<.compile/</</f@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:1121:177
Re/this.$get</l.prototype.$eval@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:1006:395
Re/this.$get</l.prototype.$apply@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:1007:104
Ac[c]</<.compile/</<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:1121:227
x.event.dispatch@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:871:14077
x.event.add/v.handle@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:871:10849
"
Hopefully that means something to you!

It looks like adjusting photos individually works, in that the icon turns and there's no errors.

This is happening in more than one browser, with or without privacy features enabled, on any sequence I care to try (when I can get the edit window to successfully load).

**Comment by gyllen** [comment]
Thanks for finding and reporting this too. Fix is deployed and should be up any minute

We just had a major housecleaning and our tests did not covere everything. So thanks for taking the time to report.
