### ISSUE TITLE
In new editing interface, blur requests can only be drawn from top-left corner

### ISSUE THREAD

**Issue by bdhurkett** [mapillary/mapillary_issues#1222]
It's a minor problem, but attempting to draw a new blur rectangle in the new interface (the one not requiring a different window to add/remove censor areas) only shows correctly if it's drawn from the top-left corner of the rectangle, then down and right.

Drawing in a different direction - moving the mouse above or to the left of the start point, or both - doesn't work as expected; it moves the X button to the appropriate place, but there's no filled-in rectangle indicating the area covered.

I imagine this is just a visual error and the points are still recorded fine? I haven't tried to submit any drawn like that, in case, but sometimes it's just easier to start drawing from a different corner.

**Comment by knikel** [comment]
It is now possible to drag rectangles in any direction (controls stay where they were) thanks to @paulinus and @oscarlorentzon!
