### ISSUE TITLE
Honor 6 continuously loses fix, even with 9 out of 19 satellites

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [mapillary/mapillary_issues#1223]
Hi Peter,

When I go under a tree or near to a building, my new Honor 6 phones constantly lose their fix, even though the GPS is very quick to get an initial fix and as far as I can tell it is using many satellites to get the fix.
When walking this is really annoying. I get the fix again by movng 30cm. Today on the highway it meant that it's only taking 1/2 - 2/3 of the pictures my older Huawei was taking. I was using them simultaneously to compare (and to make up for all the picture the Honor 6 wasn't taking).

I hope this can be fixed, it's really unnerving.

Polyglot

**Comment by echeloni2p** [comment]
HI

got the same mobile, it works quite fine. Not those issues with mapillary, hav you tried on a different day? Somedays it is bad, some days it is fine. Also: have you looked up the GPS stats on the screen?
Developer Options, show GPS stats, and only if <15m, a picture is taken.
But also your honor could have (hardware) issues, mine has a fine camera and fine GPS, but touch has issues from time to time.
Did you upgrade your honor 6 to latest firmware?

**Comment by PolyglotOpenstreetmap** [comment]
Thank you for your answer. I did upgrade both of them. Both have the issue. It's been like that for the past 2 weeks. When looking at the stats, I see that it can see up to 20 satellites and uses between 7 and 15 of them all time. I should look at this meter value more closely.

I went for a walk in the woods today, under the canopy the problem is even worse (of course), so I disabled the 'wait for GPS signal' out of desperation.

Touch works fine on both devices.

Jo

**Comment by echeloni2p** [comment]
Hi

Just want to note: even if you see enough satellites and use them, it is not sure to have a signal in <15m range.
E.g. in the woods, city,... the GPS signal is rather low, broken, weak, so the accuracy goes >15 meter and mapillary does not take pictures. Happens often in streets in cities with high buildings, wood, in valleys in mountains,....
you can disable the gps check for your tracks, but most pictures will be discarded on server later on IMHO. 
E.g. http://www.mapillary.com/map/im/adVL4R_GtsQJuEoaf3UwjA/photo (and tracks along) were made in a valley with weak GPS signal, although fine sunny weather and enough satellites in view/use.
Currently mapillary has issues with these tracks (#1198)

echelon

**Comment by PolyglotOpenstreetmap** [comment]
I should look at the accuracy expressed in meters, but it's very likely that this is the problem.

It shouldn't be the case though. I can imagine when walking in the woods, it can occur more often. But on my Honor 6 phones it happens all the time. To the point it gets annoying and in fact totally demotivating. It happens when going near to a building to make a picture of the opening hours, or when going under the first 5 leaves of a tree.

The older Huawei phone with less processing power, which sees less satellites to begin with, doesn't have this problem. If it had, I might have given up on Mapillary right from the start.

Before uploading the pictures taken in the forest yesterday, I checked if they had coordinates, which they did. So the issue mentioned in #1198, which I wasn't aware of, depends on other tags added by the app.

When looking at these pictures with the Mapillary plugin, I notice they don't seem to be connected properly into a sequence somehow.

Jo

**Comment by echeloni2p** [comment]
Hi

Ok, looks like your mobiles have issues. Check in with huawei support. You can also try with a gps signal checker, or OruxMaps to track your way.
If the signal is weak, the mapillary app cannot do much...
All I can tell: my huawei honor 6 has the same good GPS quality like HTC One series, or nearly like the garmin eTrex series. I think about getting a honor 7 for mapillary jobs. And the Honor 6 is far better than the moto G 2nd edition or Alcatel Idol Mini  here.

echelon

**Comment by peterneubauer** [comment]
@PolyglotOpenstreetmap how about checking the GPS quality with a normal compass app? Does it give you the same problems?

**Comment by PolyglotOpenstreetmap** [comment]
Hi,

Investigated some more. A compass app gives the same behaviour. The DOP value jumps from 6,8 to 12 and very regularly to 16, 24, rarely above that. It's annoying because I can't shoot pictures 'on the go' anymore. I constantly have to stand still (sometimes up to a minute) next to something, I want to add detail to the map for. So that won't do. Is there a way to set the maximum DOP value oneself somehow? Atm I'm resorting to switching off waiting for GPS signal, at times, but that is probably the worst way to deal with the problem.
It's also unrelated to canopy or being nearby buildings or in the train. The DOP value is all over the place, all the time.
The other option seems to be that I rewrite the GPS tags with a script, based on a GPX track made with the good phone. I'd prefer not to have to switch on bluetooth so all phones make use of the same GPS, while on the go. Battery life is important. The problem with creating the GPX track is that I forget about making one, most of the time AND I don't always carry the older phone with me anymore. I was also glad I didn't have to fiddle with GPX tracks anymore.

Jo

**Comment by peterneubauer** [comment]
Hi there,
if you sign up to https://play.google.com/apps/testing/app.mapillary there is a new version 1.42 of the app that uses Google Play Services for the Location check and hopefully is faster and more stable. Can you please try it and report back?

**Comment by PolyglotOpenstreetmap** [comment]
I signed up. Apparently it can take a few hours before the update arrives and it will be applied to all the phones... Now I regret I didn't sign up this morning.

I'll make sure to report back!

Thanks,

Jo

**Comment by PolyglotOpenstreetmap** [comment]
Unfortunately the problem isn't solved. I'll have to resort to using 1 cell phone broadcasting its position over bluetooth, then have the other 2 use it like a GPS 'mouse'. This will probably be bad for the battery life, but, whatever works.

Jo
