### ISSUE TITLE
right part of the screen is black

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [mapillary/mapillary_issues#1224]
There seems to be a new version. Oddly it keeps the right 1/5th of the screen black. I think this is still included in the picture, but now I can't verify whether something is obstructing the view on that side.

Jo

**Comment by mprins** [comment]
@PolyglotOpenstreetmap you're not being very clear on what you are talking about here Jo...

**Comment by PolyglotOpenstreetmap** [comment]
On my phones, the part where the round start/stop button is, is now black/dark grey. Obstructing the view from what the camera sees. This wasn't the case before, so I guess it's related to an update.

Jo

**Comment by peterneubauer** [comment]
This is intended. The preview is a now scaled to the aspect ratio of the actually taken picture, for theist part 4/3 and should thus should exactly what is taken. The former version was a bug :-)
