### ISSUE TITLE
New viewer does not "fit" into my laptop screen

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#1225]
I use Firefox 39.0 at Arch Linux and have 1366x768 display. The new viewer does not fit into it. About 50 px height are missing. See screenshot:

![not-enough-height](https://cloud.githubusercontent.com/assets/3611273/9022095/c11e877c-3866-11e5-93a4-f85ce0d0be8c.png)

I have to scroll down to see data and user. You just have to adapt the height of the photo.

**Comment by de-vries** [comment]
same as #1226?

**Comment by Nakaner** [comment]
Yes, it's the same as #1226. I have looked for equal bug reports but you were too late. ;-)
