### ISSUE TITLE
Design error in new viewer

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1226]
I get two white bars that shouldn't be there, also the photo is pushed down so the credits and the previous photo button are not visible. (firefox 39, ubuntu 15.04)
![mapillary crowdsourced street photos - mozilla firefox_078](https://cloud.githubusercontent.com/assets/1449609/9022041/7b50cd56-3864-11e5-9edd-e01ba0b99641.png)

I can fix it by disabling `.pure-u-1 {display: inline-block;}` from the css:
![mapillary crowdsourced street photos - mozilla firefox_079](https://cloud.githubusercontent.com/assets/1449609/9022058/45f530b0-3865-11e5-894f-c4b5d16902d1.png)

![mapillary crowdsourced street photos - mozilla firefox privenavigatie _080](https://cloud.githubusercontent.com/assets/1449609/9022061/662bd91a-3865-11e5-8bc3-6bda8841ddb7.png)

I have to say that I do not totally understand the function of that line of css, but I couldn't find any problematic consequences of the disabling of that line of css.

I also tested this in chromium, were I was given the non-webgl fallback version. The problem wasn't present in chromium, but disabling `.pure-u-1 {display: inline-block;}` didn't cause any problems either.

**Comment by knikel** [comment]
@de-vries this has been fixed, thanks!

**Comment by Nakaner** [comment]
The map view is not much better. Same browser, but larger screen.

![map-to-small](https://cloud.githubusercontent.com/assets/3611273/9055969/b861f38c-3a8f-11e5-8ee8-c46bdebdbff8.png)

There are no map tiles missing.

**Comment by knikel** [comment]
@Nakaner this seems to be some FF resize issue, fixing it now.
