### ISSUE TITLE
two traffic signs disappeared

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1229]
![selectie_085](https://cloud.githubusercontent.com/assets/1449609/9022651/99579248-387e-11e5-852b-5ab6c0197f79.png)
![selectie_084](https://cloud.githubusercontent.com/assets/1449609/9022652/9b1af548-387e-11e5-9b8f-a9587c3c98b2.png)
![selectie_083](https://cloud.githubusercontent.com/assets/1449609/9022654/9cbac3f6-387e-11e5-9b53-9dd99fc0e6f7.png)

**Comment by knikel** [comment]
Fixed.
