### ISSUE TITLE
Viewer broken in Chrome on Linux Mint Debian Edition

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1230]
In Chrome "Version 44.0.2403.125 (64-bit)" on Linux Mint Debian Edition the viewer is broken. It works fine in the same Chrome on Ubuntu 12.05.

See below for errors.

It says "Failed to initialize WebGL" - if the reason is that WebGL is not working, an error message would be nice. A fall back viewer would be even better, because right now I have no way to plan future mappings on my computer with a big screen :-)

The errors in the developer console are:

Failed to load resource: the server responded with a status of 404 (Not Found)
mapbox-gl.js:162
Failed to initialize WebGL
util.extend._setupPainter @ mapbox-gl.js:162
lib-232c5879.js:981 TypeError: Cannot read property 'resize' of undefined
    at util.extend.resize (https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js:162:2675)
    at new module.exports (https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js:162:1495)
    at new controller (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-283f9f21.js:13756:17)
    at Object.e [as invoke] (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:913:58)
    at R.instance (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:954:168)
    at M (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:935:373)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:213)
    at M (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:936:116)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:213)
    at h (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:236) <div ui-view="">(anonymous function) @ lib-232c5879.js:981
mapbox-gl.js:162 Uncaught TypeError: Cannot read property 'resize' of undefined

**Comment by knikel** [comment]
@simonmikkelsen We do have a fallback viewer in place for such cases (and you use a modern browser so WebGL shouldn't be an issue), but it seems that the app couldn't fetch the mapbox-gl-js module. Perhaps a timeout or some server hiccup? Would you mind checking if this is still an issue? Also, just a sanity check before I dig into this: Can you see the map at this link: https://www.mapbox.com/mapbox-gl-js/examples/ ?

**Comment by simonmikkelsen** [comment]
The issue still persists. The computer and Chrome have been closed down since. On the link there is no map, but the text:

"Mapbox GL unsupported
Mapbox GL requires WebGL support. Please check that you are using a supported browser and that WebGL is enabled."

When I go to https://get.webgl.org/ I get the message "Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card."

So in some way it looks like WebGL does not work on my Chrome. When I open FireFox it works perfectly, so personally I have a work around. But I will be glad to assist all the way I can to at least detect the problem and use the fallback.

**Comment by mprins** [comment]
@simonmikkelsen  I think chrome uses hardware acceleration for WebGL, I think HW accel fails in your case, so you don't get WebGL.
You might want to check the settings in chrome:
`Menu > Settings > (Show advanced settings...) > System > Use hardware acceleration when available. `

**Comment by simonmikkelsen** [comment]
Thanks for the suggestion @mprins , but it did not work (I also restarted Chrome) :-(
I still get the same exact error.

**Comment by HolgerJeromin** [comment]
chrome has the infopage `about:gpu` (type it into the adressbar) which could be helpful.

**Comment by simonmikkelsen** [comment]
I have uploaded the result of about:gpu to: http://simonmikkelsen.dk/files/gpu.html

**Comment by kolen** [comment]
Many users don't have sane video drivers installed, especially under linux. Browsers tend to automatically disable webgl if they don't like video card configuration (at least chrome does this). I think 3D is painless only in Mac OS.

**Comment by simonmikkelsen** [comment]
When I use the URL for a specific picture, the picture works fine but the map is grey. The viewer part works just fine, but without the map.

**Comment by kolen** [comment]
For me, photos are visible too, only map is grey. But I have no "Edit" section in browsers lacking webgl support

Chromium (can't figure out how to enable webgl):

![image](https://cloud.githubusercontent.com/assets/24191/9169604/f7aa9fc4-3f64-11e5-91bf-ece994c814aa.png)

Firefox on the same machine (has webgl):

![image](https://cloud.githubusercontent.com/assets/24191/9169649/577d8fd8-3f65-11e5-9360-7294603dd420.png)

**Comment by RussNelson** [comment]
Same problem as simon and kolen. Chrome js console: https://gist.github.com/RussNelson/2334da02cfc46ffed581

**Comment by knikel** [comment]
@simonmikkelsen Thanks reminding me about this issue.

For all interested, we've deployed stronger checks against partial WebGL support (WebGL present, but no HW acceleration, etc.). The viewer shouldn't look broken anymore and you should see fallback viewer and fallback map. Thanks everyone involved for tracking this one down!
