### ISSUE TITLE
scrollbars everywere

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1231]
dear @knikel ,
There are lots of scrollbars in the side bar:
![selectie_086](https://cloud.githubusercontent.com/assets/1449609/9024103/2702b7de-38bc-11e5-9e33-1dfcf7050efd.png)
Please change
 `.accordion__content {overflow: scroll;}`
into
`.accordion__content {overflow: auto;}` 
to fix this.

**Comment by de-vries** [comment]
same on this one:
![selectie_087](https://cloud.githubusercontent.com/assets/1449609/9024169/b6ad6bb4-38c0-11e5-8d5b-91ebf4c8384d.png)

**Comment by knikel** [comment]
@de-vries :wrench: :boom:! Thanks
