### ISSUE TITLE
viewer does not reset complete, pictures overlap

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1233]
Hi

While browsing some tracks with the forward button on chromium debian jessie, some pictures fill the screen, some do not, and the old one keeps being behind. Look on screenshot for the effect.
Looks like new transformed picture is blended in, but the surrounding is missing/not drawn and old screen keeps being.
That photo is:
Photo key: dMHBrx9_kCaOPf5-fNO0lQ
Sequence key: ffDLDik7R0_vEbNDqcZaiw

![mapillary error](https://cloud.githubusercontent.com/assets/9936420/9032471/47fb8e9e-39bf-11e5-8bd8-ccbc93c731dd.png)

**Comment by oscarlorentzon** [comment]
Thanks for reporting @echeloni2p ! 

This issue is related to the way we create and display the image planes in the viewer. We will look into it.

**Comment by paulinus** [comment]
We fixed a problem that confused the system when images with different aspect ratios were taken with the same camera. The meshes are being recomputed and the sequence will look good again soon.
