### ISSUE TITLE
weird 3d-zoom

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1234]
see https://www.mapillary.com/map/im/UHyFSrC0YAZcaHVE-tQdJw/photo

normally, 3d-zoom from one picture to another is a bit weird, but mostly smooth. here, it seems to zoom in first, then downscale the image, then zoom in again

firefox 39.0 on linux

**Comment by ybkuang** [comment]
@richlv this is because that the 3D reconstruction does not give very good model for this part of the sequence. We are working on detecting this and handle the transition properly. Thanks for the feedback, keep them coming!!

**Comment by richlv** [comment]
ok, then another weird one :)
notice how it seems to think there's some turning involved :
https://www.mapillary.com/map/im/k1sPaxyQ2cXi1UgKFtoAwg/photo

**Comment by richlv** [comment]
slightly less wrong, but still weird : https://www.mapillary.com/map/im/F3F85WcLBBQVXZdX4TXHCg/photo

**Comment by ybkuang** [comment]
@richlv yes. these are the challenging cases for 3d reconstructions (too little overlap between images e.g driving sequences, images that are difficult to get correct matches e.g bushes, trees).

**Comment by richlv** [comment]
somewhat related - i was surprised that 3d reconstruction failed to connect these two images - https://www.mapillary.com/map/im/2_iYgu8tFMmR_jsUkcaGeg/photo and move to the next photo in the sequence

**Comment by richlv** [comment]
not sure whether it's worth listing more cases, but locking to sequence and moving one image forward here is strange :
https://www.mapillary.com/map/im/0ICWgzyW6sdtt9ySZUgYCg/photo

**Comment by paulinus** [comment]
Closing this since the SfM algorithms that we run have changed since then. Many of the reported problems have been solved or improved even if some remain. We continue to improve and rerun the reconstruction algorithms globally to progressively reduce the number of misalignments.
