### ISSUE TITLE
Error in Javascript console.

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#1235]
I work in Google Chrome Versie 44.0.2403.125 m
In the Javascripct console these errors appear :

Failed to load resource: the server responded with a status of 403 (Forbidden)
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>EB3A080A1CBF2F17</RequestId>
<HostId>
7fzJh12757+Rxb/hy9CBfB0ljbXiag+X7YxPDVMqlihYu54l3YvNnCKksn3tjV3xgSYdTlHIB/U=
</HostId>
</Error>

I have no real unknown issues except that pieces of sequences on the map appear and disappear with changing zoom levels.

**Comment by knikel** [comment]
These errors should be handled correctly now, it was a missing vector tile.
