### ISSUE TITLE
Can't upload photos manualy (stay at 0%)

### ISSUE THREAD

**Issue by Marcussacapuces91** [mapillary/mapillary_issues#1237]
I just can't upload a bunch of photos. Prelininary tests are ok, but upload stay at 0% waiting
see : ![mapi](https://cloud.githubusercontent.com/assets/266435/9043168/d6f36528-3a13-11e5-8e30-6c7ba351d541.png)

**Comment by gyllen** [comment]
Is it just some photos or all?

**Comment by gyllen** [comment]
I see you are on the https verison of the site, can you try with the none https one

**Comment by Marcussacapuces91** [comment]
Seems to be ok with http links. On my way uploading about 1500 photos

**Comment by wasdy** [comment]
I confirm this issue in HTTPS. It works on HTTP.
Related with issue https://github.com/mapillary/mapillary_issues/issues/1172

**Comment by staehler** [comment]
I can confirm this upload behaviour.Unfortunately it doesn't work with http either.
I get this warning before upload, but proper exif header are available.
![unbenannt](https://cloud.githubusercontent.com/assets/6258158/9300712/450db9d6-44c9-11e5-8292-ca3767d04138.PNG)

**Comment by gyllen** [comment]
https now fixed
