### ISSUE TITLE
UI issue in new viewer

### ISSUE THREAD

**Issue by PalmerAL** [mapillary/mapillary_issues#1238]
In the new viewer, I see white bars above and below the tabs, like this:

![screen shot 2015-08-03 at 6 31 36 pm](https://cloud.githubusercontent.com/assets/10314059/9049975/f8be330a-3a0d-11e5-8cfb-49a9254ec029.png)

(this is using firefox 42)

**Comment by knikel** [comment]
This has been fixed, thanks for reporting @PalmerAL!
