### ISSUE TITLE
Why the new map is so badly rendered?

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#1240]
Old map does not have this problem. Where are the waters?
![mari](https://cloud.githubusercontent.com/assets/8439643/9054511/f90473ce-3a8a-11e5-92b3-5741900eddda.png)

**Comment by jesolem** [comment]
Looks like this was a temporary downtime of the mapbox tiles. Do you still have this problem?

**Comment by shlublu** [comment]
Yes, I had it this morning. But not right now. It was formerly possible to chose between OSM and MapBox, but the new viewer does not propose this choice, only the edit mode does. 

Do these two tile set show the same objects ? (masts, gas stations, generic and footpaths...)

**Comment by dubyk** [comment]
Also vote for the option to choose OSM map layer and save this choice in the profile.

**Comment by eugensim** [comment]
![image](https://cloud.githubusercontent.com/assets/8439643/9354813/30a70e34-467c-11e5-87b9-448673a7c242.png)

**Comment by knikel** [comment]
Must've been mapbox's issue at the time. @dubyk we're going to use mapbox's basemaps, but will consider raster OSM tiles as an optional base map.
