### ISSUE TITLE
New viewer : 360° pictures bug

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1242]
Hello,

With the new viewer, photosphere pictures are seen as standard images : 
http://www.mapillary.com/map/im/FL4A8k5ZJYPZxN1-6cVdZw/photo

**Comment by jesolem** [comment]
Thanks @Stefal 
We're working on it.

**Comment by oscarlorentzon** [comment]
Thanks again for reporting @Stefal !

This problem has now been fixed and will work soon.
