### ISSUE TITLE
Wrong capture time in new viewer?

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1243]
As a result of the completion of #1112 I stumbled over a possible bug: The image http://www.mapillary.com/map/im/csL9tQm1gR8yIT0oX-HLyA/photo shows the time 2:34:28 PM. However, exiftool shows me the following entries for the uploaded file:

```
Modify Date                     : 2015:06:13 12:34:28
Date/Time Original              : 2015:06:13 12:34:28
Create Date                     : 2015:06:13 12:34:28
GPS Time Stamp                  : 08:34:28
GPS Date/Time                   : 2015:06:13 08:34:28Z
```

The image is from Georgia (the country) which is in the timezone UTC+4.

From what I could see this behaviour applies to all my pictures in Georgia.

I did some fiddling with the timestamps before the uploads with the assumption that EXIF timestamps should carry the local time whereas GPS time should be in UTC. Is that a good assumption? Why is there another time (zone) displayed?

**Comment by voschix** [comment]
Confirm the same systematic error of the Mapillary clock being two hours ahead. Always. Have you moved to Siberia? :-)

**Comment by ybkuang** [comment]
Thanks for reporting this. It is related to the time conversion on server side. We will look for a fix.

**Comment by ybkuang** [comment]
@ltog @voschix We did a fix for this (it is indeed related to the time conversion on the server side).  It ideally should display the local time (assuming Date/Time Original stores local time). For date/time in GPS date/time, we have actually seen examples that local time is stored (depending on the device setting I suspect).

**Comment by ltog** [comment]
@ybkuang : Thanks for fixing this. The picture I submitted looks fine now.

I will therefore continue to submit pictures with local time in the EXIF data...

**Comment by ybkuang** [comment]
Cool! I am closing this for now then. We can reopen this if you find any other time inconsistency.

**Comment by voschix** [comment]
@ybkuang: I confirm, that it appears fixed on uploads from the Mapillary App. I still have to check on my older manual uploads (GoPro). Thanks for the quick reaction.
