### ISSUE TITLE
How to edit and image?

### ISSUE THREAD

**Issue by ireun** [mapillary/mapillary_issues#1245]
Hello, in this new UI i can not find an option to edit a photo.. Any help?

**Comment by knikel** [comment]
Hey @ireun,
if you're logged in and your browser supports WebGL you can edit the photo by using controls in this drawer. We've moved blurs and traffic sign annotations to the viewer, the compass angle and sequence details are in the old editor as they were.

![edit](https://cloud.githubusercontent.com/assets/1574656/9062632/e6d6a49a-3ac3-11e5-9bb0-7d4f37c40493.png)

**Comment by ireun** [comment]
Thank you for the anwer, but..  

![Imgur](http://i.imgur.com/QOrcbrp.jpg)

There is no such option, I'm using newest Chrome beta..

**Comment by knikel** [comment]
@ireun What you're seeing are fallback map and the viewer. Can you type `chrome://flags/` in the url bar and check whether the `enable WebGL` is marked as *enable*?

**Comment by ireun** [comment]
I don't have suck thing as 'enable WebGl' just 'Disable webGl' and it's not turned on.

**Comment by knikel** [comment]
Sorry about not precise wording, but that's what I meant. Does the website work for you in other browsers on your system? Like e.g. Firefox?

Would you mind trying this site here: https://get.webgl.org ? Then check this `chrome://gpu`. If you get some warnings you should be able to disable some of them here by going here in chrome `chrome://flags/#ignore-gpu-blacklist `. Restart the browser and check get.webgl.org again. Hope it helps a bit?

**Comment by ireun** [comment]
hmm, I will try to restart my PC, maybe it's because I've upgraded GPU drivers.. brb

**Comment by knikel** [comment]
Did it work @ireun?

**Comment by ireun** [comment]
Well, I think that drivers were not installed correctly, I'm trying to boot my PC now..

**Comment by HolgerJeromin** [comment]
It would be nice if there would be a hint that we are looking at a fallback viewer, which has not the full functionality (especially edit is missing).

**Comment by ireun** [comment]
@knikel After reinstalling my OS it finally works, thank you, but this is a good idea, to add a notice that there is a problem with WebGL

**Comment by knikel** [comment]
@ireun good, thanks for the update. Yes, I need to find a way to get around detecting faults with WebGL rather than just whether it exists or not.
