### ISSUE TITLE
Up and down vote

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1246]
I think its time that Mapillary gets a feature to give a picture/sequence an up or down vote. The votes could be used for several things.
- The quality of pictures/sequences varies. Mapillary is starting to have streets that have been documented several times. I would make sense to only show the best ones (unless a user chooses to show all).
- Good motivation. It would be nice to be able to give people a quick up vote for a nice picture/sequence/work. Would also make some nice soft motivation for the weekly emails (the quality  vs quantity discussion).
- I don't think the votes should be shown on the site. And I don't think people should get feedback about getting down votes.

**Comment by jesolem** [comment]
I like this suggestion. Let's see what we can do.

**Comment by shlublu** [comment]
+1

**Comment by GITNE** [comment]
@Andblue intentions point into the right direction, especially when it comes to quality vs quantity of photos and the long-term motivation of users.

However, I am not sure that simple up/down votes on photos or sequences are a good measure of quality. Yes, it does measure *some* sense of quality but it will effectively result in a blob of individual subjective animosities, nothing more. Is this really a good measure of quality? Would it really serve Mapillary's goals? It may work on pure social media sites where making the most buzz about something is the name of the game but I am having difficulties believing that this would work for Mapillary.

Enabling users to give feedback on multiple aspects (like lighting, blurriness, shakiness, focus etc.) that are important to Mapillary's goals could indeed help determine quality which is less tainted with subjective taste. But, a lot of quality aspects can be determined automatically, like those mentioned by @moenk in his [comment](https://github.com/mapillary/mapillary_issues/issues/1241#issuecomment-129351051). That list is far from exhaustive. And, I believe if implemented properly will serve Mapillary and its users far better.

**Comment by sandrauddback** [comment]
The quality aspect of the images is still very important and for 2018 we have moved this into our pipeline to sort out. Closing this issue as there is no instant fix but will be considered in our product planning.
