### ISSUE TITLE
incorrect turn connection

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1247]
turn left from https://www.mapillary.com/map/im/PuV8kTdD-hKNwvKbOWdtiA/photo - you end up in https://www.mapillary.com/map/im/_1_ki8fMTD3U5v1F1UQToQ/photo

that's actually to the right and quite some distance away.

not sure whether it's a problem that can be solved somehow, but it does make the navigation quite complicated :)

**Comment by shlublu** [comment]
Absolutely. The issue https://github.com/mapillary/mapillary_issues/issues/1278 is related.
It also happens that some images are omitted, or ordered not according to the sequence.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
