### ISSUE TITLE
"request sequence cut" w/o any feedback/indiation

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1248]
in the editing interface, there's a button to request sequence cut at spaces, bigger than n metres. unfortunately, there is no visual feedback when the button is clicked, no indication that it was successful or not.

it is possible, that clicking that button alone is enough, maybe change request must be sent... but attempting to send the change request does not show that cutting was requested, so for all i know this feature might be broken currently :)

**Comment by knikel** [comment]
Will add a success/error top bar notification. Thanks @richlv.

**Comment by de-vries** [comment]
@knikel there is a problem with the top bar notification. The button to request a sequence cut is at the bottom of the page. If you scroll down to reach it, the top bar notification happens out of view. 
The notification bar should be fixed to the window, not the page

**Comment by knikel** [comment]
The notification has been sticky for a while 👍
