### ISSUE TITLE
Arrow keys don't work on new photos

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1250]
Navigating with the arrow keys doesn't work on new photos. I understand that the connections are not calculated yet; there are no transitions either. 
The only way to navigate new sequences is clicking the arrows on the top and bottom of the photo. It would make sense to link the arrow keys those buttons when the connections are not calculated yet.

**Comment by de-vries** [comment]
I don't know if you fixed something but on the photos I'm uploading right now the arrow keys work fine

**Comment by jesolem** [comment]
@de-vries  Can we close this?

**Comment by de-vries** [comment]
If you close this then that would be based on only one data point. But I have some photos ready for upload, so I have the opportunity to double the size of the data set ;)
If the bug doesn't show up again, I'll close it

**Comment by de-vries** [comment]
tested and no problems with the arrow key navigation. closing
