### ISSUE TITLE
Lay-out suggestions for the filter section

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1252]
![selectie_089](https://cloud.githubusercontent.com/assets/1449609/9107123/3d1731be-3c25-11e5-9e77-2d8417f56bcd.png)

- 1&2) Please use a consistent layout for both buttons
- 2) Should be named "reset filter", as you can only set one time filter at once
- 3) Setting this to "height:365px;" prevents scrollbars popping up

**Comment by knikel** [comment]
This will be solved in much better way in the upcoming update. Closing.
