### ISSUE TITLE
smartphone: no play button and search as dead-end access

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1253]
I want to share my photos with people.One of the best features for me of Mapillary is the play button.I say to people Play the sequence...but in mobile version (and embed web version) ...there's no play button :(

Also You can choose between Photo, Map or Search but when you click to Search you cannot turn back to Photo or Map (yes, you can turn back only with cellphone browser buttons).

Settings button (three strips) doesn't work also.

(test done with Chrome and Firefox last version today in a Sony Xperia Z3 Compact D5803)

**Comment by gyllen** [comment]
On the new website you can share a state of what you are looking at. And there is also a playbutton availble.
