### ISSUE TITLE
Some considerations regarding upload speed

### ISSUE THREAD

**Issue by chrisom** [mapillary/mapillary_issues#126]
Default setting in walking mode is to take a picture every 2 seconds. 1h = 3600 seconds. Usually walking speed is 6km/h. This means 1800 pictures represent about a path 6km length.
=> In average 300 pictures are taken for 1 km lenth of path. (1)

My upload speed is 512 kBit/s. It takes about 2 Minute to upload pictures taken with my device (Galaxy S4 Mini). 

By considering (1): 1km recording (300 pictures) will take 600 minutes to upload. Or to make it more visible: 1km recording will cause 10h (one whole night) upload time if the line is exclusevly used by mapillary!

This limits the ammount of kilometers beeing mapped every day to only 1 in walking mode.

**Comment by gyllen** [comment]
@chrisom Closing since no response
