### ISSUE TITLE
Selector of tracks doesn't work from Search tab

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1261]
I go to Search tab, see not all tracks but the majority, click on them and then...nothing happens, hand does not converts in anything you can see track is selected and you don't know exactly at what point you are trying to select ('till the track and the point figures out).If the track selector does not work you won't see anything like if you hadn't click anything.

(test done at Win7 with last Chrome and Firefox )

**Comment by knikel** [comment]
@yopaseopor: is this still an issue for you? I've tried that, but I can't reproduce the error. The API call is relatively slow sometimes here, but it shouldn't take more than 0.3s tops.

**Comment by yopaseopor** [comment]
hahahahaha That was... at least half year ago. With new viewer is not a problem now. You can close this issue. Thanks.
