### ISSUE TITLE
When advancing images in the new viewer, I keep 'jumping' to another parallel sequence

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1263]
When I try to follow some of my own image sequences manually, I end up jumping to another user's sequence (on the same road).

For example, when I advance to the image after this one http://www.mapillary.com/map/im/ncchduczt4DP4QhaCHFZtw/photo
I end up with this image http://www.mapillary.com/map/im/MhtlQ5m2WriXWNEwAgWDtg/photo

Since they are different users' images, they should be different sequences.

Is this "working as designed" or a bug?

**Comment by de-vries** [comment]
This is intended behaviour. see also #1206

**Comment by jfburke3** [comment]
Ah, I missed that one when looking through the open issues.  Closing this one because 2 issues for the same thing aren't needed.
