### ISSUE TITLE
Missing images in iD

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_issues#1264]
If I look at http://www.openstreetmap.org/edit?editor=id#map=17/48.38357/-122.33288, I see a limited number of tracks on the I 5. Looking at it on mapillary.com/map, I see several other sequences

![image](https://cloud.githubusercontent.com/assets/1190866/9127246/a46db684-3c6c-11e5-8f7c-3dee8a610d56.png)

Most of the other sequences are by myself, and are missing from iD for the I 5 between Canada and Seattle.

**Comment by gyllen** [comment]
@peterneubauer are you getting 1000 markers from Mapillary in total?

**Comment by gyllen** [comment]
This issue might actually belong in the iD editor.

**Comment by voschix** [comment]
I seem to have the_same / a_similar problem. I cannot see most of my photos on ID (http://mapillary.github.io/iD/). Some sequences seem to be completely there. Of others I only see the odd single picture. And I suspect that here are many that don't show at all. (All pictures obviously show up on the JOSM plugin, which I normally use.)
Regarding Peter's question about 1000 markers: is this 1000 markers on the current map view or 1000 markers in total. If the latter how do you select which of my 100000 photos do show up?

**Comment by peterneubauer** [comment]
Hi there,
the 1000 markers are per request (pan) but I think we even limit the total
number of image layers in the iD SVG to 1000 in order not to overload the
browser rendering. To choose what to show, we need a filtering/ordering API
for image search in iD. Ordering is not implemented yet but could be worked
around by filtering e.g. time. I have currently no bandwidth to add that,
but feel free to look into it!

**Comment by pnorman** [comment]
Opened an issue in iD, but I think the issue is partially an API flaw with extremely long sequences.

The URL being requested from Mapillary is https://a.mapillary.com/v2/search/s/geojson?client_id=NzNRM2otQkR2SHJzaXJmNmdQWVQ0dzoxNjQ3MDY4ZTUxY2QzNGI2&min_lat=48.380277932938284&max_lat=48.386861854149636&min_lon=-122.34103391540528&max_lon=-122.32472608459473&max_results=100&geojson=true which returns a 357KB GeoJSON

Loading that into QGIS, I see several sequences that are 150km long and probably have thousands of images.

The documentation doesn't seem to address how to get the coordinates of the images from the geojson, but if there's an image at each point in the linestring, that's 5754 points for a request of a very small bounding box with `max_results=100`.

![image](https://cloud.githubusercontent.com/assets/1190866/10242463/dbd77b86-68a5-11e5-84a1-1e5370a1ee6f.png)

**Comment by gyllen** [comment]
@pnorman Thanks for looking into this, you are right. We use this API internally on our website where we load stuff smarter in tiles. I wonder if a solution would be a parameter that would cut the sequences to requested bounding box, WDYT?

**Comment by pnorman** [comment]
> I wonder if a solution would be a parameter that would cut the sequences to requested bounding box, WDYT?

I was thinking something like this. The only issue is that it will result in a gap between the linestrings if a client is requesting bboxes in a grid, but that's better than what's happening now.

With the current implementation, requesting bboxes in a grid would also lead to the same data being sent for each grid when dealing with long sequences like these.

**Comment by gyllen** [comment]
@pnorman Yeah agree, thanks for thinking about this. Will add option to API.

**Comment by peterneubauer** [comment]
Now, in the latest release of iD, all images should be showing up, check http://www.openstreetmap.org/edit#map=16/55.6724/13.3804
