### ISSUE TITLE
sequence not rendered on the (new style) map

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#1265]
This sequence does not appear on the map after one week, but the pictures are on the server because the slideshow shows them: http://www.mapillary.com/map/im/T87XuTNPpyE9_fK819q28Q/photo

The old map style renders the sequence: http://www.mapillary.com/jsapi?image=T87XuTNPpyE9_fK819q28Q

**Comment by jesolem** [comment]
![image](https://cloud.githubusercontent.com/assets/136751/9131734/85e2fb84-3cee-11e5-9f43-acd710932038.png)
I see a short sequence on the map. Is this correct?

**Comment by ligfietser** [comment]
Nope. It is much longer, see http://www.mapillary.com/jsapi?image=T87XuTNPpyE9_fK819q28Q

**Comment by jesolem** [comment]
OK, @knikel will investigate (or if it is API/DB @gyllen )

(other marker issue assigned)

**Comment by ligfietser** [comment]
Thanks, same for this sequence (taken and uploaded the same day) http://www.mapillary.com/map/im/KxHDxD5vY9LrByOTtSY9eQ/map

**Comment by richlv** [comment]
could this be the same as issue #1196 ?

**Comment by gyllen** [comment]
@ligfietser Seems like its visible on outer zoom levels 
<img width="272" alt="screenshot 2015-08-07 11 59 01" src="https://cloud.githubusercontent.com/assets/268859/9143519/e00f0d3e-3cfb-11e5-9fcb-bb2887396291.png"> I think its a matter of that we do not render all the zoom levels we need in the new tiles. Will rerender down to zoom level 16 during next week. This will fix this error.
