### ISSUE TITLE
unblurring request 

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#1267]
This art work of "Joop Zoetemelk" is still blurred, even after several requests
http://www.mapillary.com/map/im/BzPKwId7TloUf-Gdl7EM-g/photo

**Comment by gyllen** [comment]
@ligfietser Lets see after it gets approved, how it looks like.

**Comment by ligfietser** [comment]
Thanks, it is now unblurred. One related question, this sequence is a single photo. How can anyone find it on the map? In the old style map you could see a small blue dot, but in the new map style nothing is rendered.

**Comment by de-vries** [comment]
> How can anyone find it on the map?

@ligfietser they can if #1044 gets fixed

**Comment by gyllen** [comment]
Thanks for reporting this @de-vries we will fix, closing this issue since its about blurring
