### ISSUE TITLE
Load blurs faster

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1268]
The new blur method is quite nice and it work a lot faster than before. As the next improvement I would like to see the blurs load faster. Ideally the blurs would be loaded when viewing the previous picture, so they're available instantly.

**Comment by jesolem** [comment]
Could work when you are in blur editing mode.

**Comment by de-vries** [comment]
> Could work when you are in blur editing mode. 

That's what I  meant, no sense in pre-loading blurs when you're nor editing them ;). 
To save resources, you could chose to only activate such a feature after browsing a few blurs or even after filing a blur request.

**Comment by richlv** [comment]
maybe it's worth loading blurs for multiple images in one request, too ? i guess the actual data size is small, but the latency for the request is what results in the slowdown.

**Comment by knikel** [comment]
@jesolem, @de-vries, @richlv: At the moment it is intentional that blurs are fetched when your move halts on the new photo.

@gyllen What do you think about prefetching while in blurring mode? I think it would make sense only when you're locked to the current sequence.

**Comment by richlv** [comment]
if this gets any interest, it would be useful to preload also when moving backwards in a sequence :)

**Comment by nicolas17** [comment]
Prefetching blurs for the next photo would greatly speed up my reblurring work!

**Comment by de-vries** [comment]
@knikel There seems to be some demand to speed things up. So I wonder what the reasoning behind the intentional delay is.

**Comment by ToeBee** [comment]
Soo... I found a temporary workaround for this. It involves editing javascript source by hand in the Chrome developer tools. See the screenshot below. Just change the highlighted "2000" to 10. Instant blur loading! The modification goes away every time the page is reloaded so it's kind of a pain.
![mapillary_delay_fix](https://cloud.githubusercontent.com/assets/348948/12136142/559f5cd6-b40a-11e5-8073-056bb5aac9de.png)

**Comment by richlv** [comment]
in vivaldi, i had to rightclick that tab and choose 'save' to get the change applied.
and wow, that indeed makes it much less pain... thanks :)

**Comment by richlv** [comment]
until prefetching is implemented, can somebody just change that 2000 to 10 or so ?
it is quite annoying to edit the js every time :/

**Comment by GITNE** [comment]
@richlv Thank you for point out that #1748 is a duplicate of this.

@mapillary :disappointed: To be honest, when I read @ToeBee's [comment](https://github.com/mapillary/mapillary_issues/issues/1268#issuecomment-169245363) and saw a hard coded, arbitrarily chosen value for a time delay, I was just stunned about the level of unprofessional action. It is like one of the first things students learn in programming classes: Never hard code any time delay in code, unless you deal with real time applications or directly access hardware. Like @ToeBee pointed out in his [comment](https://github.com/mapillary/mapillary_issues/issues/1607#issue-121936762), I would assume too that this delay has been put in to reduce load on the servers but this really is not the way you should do it. Pre-loading blurs and photos is the proper way to do it. Please fix this.

Besides, I would not label this an "enhancement". It is a bug introduced by @mapillary on purpose.

**Comment by knikel** [comment]
This issue will be solved in the upcoming update of mapillary.com.
@GITNE Unfortunately the value is there for a reason. We hit a limit of angular-js and managing a lot of asynchronous actions we do and maintain. Bear in mind that the upcoming version will be based on `mapillary-js`, which has no such shortcomings. The only limiting factor between photo movement is the download speed.

**Comment by richlv** [comment]
that is really great, thank you :)
will preloading be included, too ? otherwise higher latency connections will still make the process cumbersome.

**Comment by knikel** [comment]
@richlv it's not included as of yet, but we have it in the pipeline.

**Comment by GITNE** [comment]
> This issue will be solved in the upcoming update of mapillary.com.

Great! :smiley: 

> @GITNE Unfortunately the value is there for a reason. We hit a limit of
> angular-js and managing a lot of asynchronous actions we do and maintain.
> Bear in mind that the upcoming version will be based on mapillary-js, which
> has no such shortcomings. The only limiting factor between photo movement is
> the download speed.

Yeah, it did not cross my mind that the explicit delay may be a workaround for some other badly implemented libs. And, it is great that mapillary-js will remove this artificial delay. However, the real trick to reducing latency is pre-loading photos.

**Comment by de-vries** [comment]
this seems to bee solved
