### ISSUE TITLE
Lay-out suggestions for the geo search results

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1269]
![selectie_090](https://cloud.githubusercontent.com/assets/1449609/9131978/7333ce3a-3cf0-11e5-8d53-5c5db83dc2d4.png)

**Make the links more difficult to miss**
add
`.search-box__results a {
    display: block;
}`
or
`.searchbox .mapillarygeosearch .search-box__results--geo li a {
    display: block;
}`
I don't know which one is best. Both gave the same result.

`.search-box__results li {
    display: block;
}`
can be removed, I think, as it does nothing and it was probably meant to make the `<a>` display as block.

**Remove the outer scrollbar**
change
`.searchbox .mapillarygeosearch .geo-search-results-wrapper {
    overflow: scroll;
}`
into
`.searchbox .mapillarygeosearch .geo-search-results-wrapper {
    overflow: auto;
}`
or remove it al together, I think there is no harm in that.

**Only show inner scrollbars when necessary**
change
`.search-box__results {
    overflow: scroll;
}`
into
`.search-box__results {
    overflow: auto;
}`

**Make the cursor a pointer in stead of a text cursor when hovering the close button**
add
`.searchbox .mapillarygeosearch .geo-search__discard-button {
    cursor: pointer;
}`

**Comment by knikel** [comment]
This is what's coming 😉 
<img width="410" alt="search" src="https://cloud.githubusercontent.com/assets/1574656/15715009/3958b234-281d-11e6-8b88-98e0e493adf6.png">

**Comment by de-vries** [comment]
You're teasing us a lot these days... I like what I see here, I can't wait to have the real thing

**Comment by knikel** [comment]
@de-vries: it's coming. Just doing a swipe through all issues, so we can prioritize further feature requests later. I'm sorry for a lot of notifications too 😉
