### ISSUE TITLE
Edit image too small

### ISSUE THREAD

**Issue by tschaedl** [mapillary/mapillary_issues#127]
If I want to review my uploads (unfortunately car sign bluring doesn't work for so many images) I can't do it appropriatly in the "edit" mode cause the image is too small for recognizing all details. But constantly switching between "edit"/"nonedit" mode is not an option.

**Comment by ToeBee** [comment]
Yeah, the edit mode definitely needs a zoom control. The suggestion of opening another browser tab to view a higher resolution is completely useless when reviewing a few hundred images in a sequence.

**Comment by gyllen** [comment]
Agree on this. We are going to incorporate blur functionality straight into the view. Which has zoom functionality. This is an upcoming feature so closing. Please reopen if I misunderstood ticket.
