### ISSUE TITLE
sequence cut request failed

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#1270]
I would like to cut this sequence, but it fails:
http://www.mapillary.com/map/e/CBsHccYln3dt61omsKKT0w

**Comment by filipca** [comment]
I have the same problem for several months already and I asked the cut several times.
But there was no difference between the before and after image before I requested it.
http://www.mapillary.com/map/search/51.21318307120913/51.29210264333639/4.277085022211793/4.579606878151196

**Comment by jesolem** [comment]
@ligfietser Can you describe what you mean by fails? You get an error when you try to do it?

@filipca What distance threshold did you use for the cut request? Did it look ok when you submitted request?

**Comment by filipca** [comment]
I tried all kinds of distances, but I also left the default of 300 meter.
As I wrote, it did not look OK.
It is a length of 100 km and caused by a mistake by me in the manual upload of old pictures.
In France, there is also a spike in a sequene  like that (not by me).

**Comment by ligfietser** [comment]
@jesolem After I have pressed the sequence request button a red warning pops up:
![failed](https://cloud.githubusercontent.com/assets/9638726/9144905/9508b254-3d50-11e5-8efb-bf6174c31914.jpg)

**Comment by filipca** [comment]
I have no warning, I have the same before and after picture.

The pictures on both  ends of the line are logically related :).   So it could be a sequence, but it ruins one fourth of Belgium.

**Comment by filipca** [comment]
@ligfietser 
I suppose this happens repeatedly.
Otherwise I would think that someone was looking at the concerned sequence.

**Comment by gyllen** [comment]
@filipca @ligfietser We are trying to debug the sequence cut feature. Really the problem is how stuff is saved in our database. A small cut can internally generate thousands of requests to the database. We are looking on how OSM implemented this to try to solve it as fast as possible.

Sorry for the inconvenience.

**Comment by gyllen** [comment]
Sequence cuts are now done automatically. On road map to include in editor.
