### ISSUE TITLE
top list map missing sequences for months

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1271]
top list maps like https://www.mapillary.com/map/places/latvia or https://www.mapillary.com/map/places/oregon do not show sequences from june and earlier. likely it's the same for all locations.

does not seem to be related to the new interface, just looks like updating stopped earlier this summer or even spring.

**Comment by ligfietser** [comment]
I notice the same for the Netherlands. And also the TMS layer that I use in JOSM http://{switch:a,b,c}.tiles.mapillary.com/{zoom}/{x}/{y} misses the latest sequences of the last months.
Only http://www.mapillary.com/map/explore seems up-to-date.

**Comment by gyllen** [comment]
We should update stats to show new vector map

**Comment by de-vries** [comment]
also the tiles in the fall-back map are behind:

![selectie_097](https://cloud.githubusercontent.com/assets/1449609/10039222/100eefe2-61d0-11e5-9932-139db1315592.png)
![selectie_098](https://cloud.githubusercontent.com/assets/1449609/10039225/122cfd78-61d0-11e5-88e6-5717c36a0172.png)

**Comment by gyllen** [comment]
Yes its the same tiles

**Comment by knikel** [comment]
We've phased out the `places/:place_name` views in favor if `places/:shape_id`, where we have better shape and better stats data. You can find places of interest from https://www.mapillary.com/map/stats
More stats to come!

Have fun! :smile:
