### ISSUE TITLE
top list map has zoom levels where no sequences are shown

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1272]
take any top list map like https://www.mapillary.com/map/places/latvia , zoom in. at some zoom level sequence lines disappear - there seem to be 6 zoomlevels w/o traces.

preferably, traces would be seen on all zoom levels; if that's too expensive processing/storage wise, zooming in the top list should be limited to the level that still has the sequence lines (but this should not affect the viewer map in any way :) )

**Comment by knikel** [comment]
This will be solved by using images (as opposed to sequences) as source data for the map. Will close when we roll out the update.

**Comment by knikel** [comment]
This has been solved, we've got new stat pages, bear in mind we're not using readable names, but GIDs for places. Best way to find it is to go to `https://www.mapillary.com/app/stats` and look for the place of interest. The url scheme, Latvia is now: `https://www.mapillary.com/app/stats/85633279`.
