### ISSUE TITLE
Forum or similar

### ISSUE THREAD

**Issue by wasdy** [mapillary/mapillary_issues#1273]
Request: A system for Q&A, forum or similar so the community can interact, ask questions from the user perspective, etc.

**Comment by filipca** [comment]
There is a Google group https://plus.google.com/u/0/115127986552248138385/videos
and a mapillary-user gmail.

**Comment by filipca** [comment]
You could also use the osm forum.

**Comment by richlv** [comment]
there's also a freenode irc channel #mapillary, where some community members hang out every now and then. would be great to have mapillary people there, of course :)

**Comment by wasdy** [comment]
I'm more of an asynchronous person, and OSM has many related projects other than mapillary. Being Mapillary a company that depends so much on the community, it's surprising their members don't have a common place (maybe supervised by mapillary people?) to discuss ideas or ask questions. This may overlap with github issue tracker, but this seems more for for issues like bugs.

**Comment by simonmikkelsen** [comment]
I can't find any discussions on the Google+ page. I may start a Facebook group or something for Mapillary talks one day, but something officially is better.

**Comment by jesolem** [comment]
Thanks everyone

Yes, we are looking into having a forum of our own. We will get there.

@simonmikkelsen There is a FB group but not a great place for discussions.

**Comment by jesolem** [comment]
Take a look at http://forum.mapillary.com/

**Comment by richlv** [comment]
does the forum use a separate user storage from the main mapillary one ? i can't log in with the previous account there.

**Comment by jesolem** [comment]
@richlv Yes, separately hosted, separate db. You need to create an account for now.

**Comment by de-vries** [comment]
@jesolem Nice to have this. About that account: I wasn't able to pick the same name as on mly; I had to use a underscore in stead of a space. minor issue, but also maybe easily fixable. also I was a little annoyed that I couldn't use my mly account. but from your wording I understand that you already wish to fix that.
