### ISSUE TITLE
can't get upload hashes

### ISSUE THREAD

**Issue by sbma44** [mapillary/mapillary_issues#1274]
I'm trying to upload photo from a Xiaomi Yi sports cam that I've geotagged using the scripts in your tools repo. The docs for the upload script say I should be able to retrieve them at http://api.mapillary.com/v1/u/uploadhashes but I just get a `You need to sign in or sign up before continuing.` message.

Things I've tried:
- firefox and chrome
- logging out & back in
- incognito windows
- erasing all mapillary cookies
- erasing all mapillary localStorage
- logging in on the mobile app
- changing the `v1` in the endpoint to `v2`

 Suggestions very welcome.

**Comment by gyllen** [comment]
Thanks for reporting this. This is an issue from our side. We will add the upload hashes on the manual upload page instead.

Long story short we recently switched login system (to fully support API v2) and all calls to API now needs a different kind of authentication.

**Comment by gyllen** [comment]
Fixed login and checkout http://www.mapillary.com/map/upload/im

**Comment by sbma44** [comment]
Lovely! I now see the credentials. Thanks very much.
