### ISSUE TITLE
Mapillary crashes after 50-100 photo are uploaded (v1.37)

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1275]
I seem to upload around 50-100 photos, then it hangs for a while and then eventually gets killed because the app is no longer responding.

A trace have been sent in a separate email.

**Comment by jrcarlsen** [comment]
I should add that photos are getting uploaded, and the remaining number of photos on my phone does count down.

**Comment by peterneubauer** [comment]
Next time, can you send me the date/time of the crash? In the app there is https://try.crashlytics.com/ enabled, so I should get a crash report around that time. The log does not contain errors - it might be something outside the apps control.

**Comment by jrcarlsen** [comment]
I am submitting the crash reports, the comment contains the word "upload".
There should be 10+ reports from yesterday.

**Comment by jrcarlsen** [comment]
Very commonly it hangs after uploading 53 or 103 photos. I am not sure if there is anything in the code that is supposed to kick in every 50 upload. Just thought I'd mention my observation.

**Comment by jrcarlsen** [comment]
Ok, just had another crash. Report sent now.
Feedback: Crashed during upload
Time: 08:29 UTC.

**Comment by jrcarlsen** [comment]
Phone was restarted and tried on different Internet connections - same issue.

**Comment by peterneubauer** [comment]
Did you try with 1. 38 which should be on the Play Alpha tester program
now?

**Comment by jrcarlsen** [comment]
I can confirm that v1.38 works for me. It has done 250 successful uploads so far.

**Comment by peterneubauer** [comment]
Awesome, thanks for testing Johnny!
