### ISSUE TITLE
Saved password fill sometimes does not work on login screen

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#1277]
Sometimes Chrome does not pre-fill saved login and password in login form. However, it saves login and password.

Seems that it always works in Firefox.

**Comment by jesolem** [comment]
Sometimes? You mean it works some times and fails other times?

**Comment by kolen** [comment]
Yes. Currently I can't reproduce it, but encountered several times.
Also, sometimes 'email' field is pre-filled (and with yellow background) but password is not.

**Comment by knikel** [comment]
@kolen it could be that we've changed the name internally of the input field and the browser can't match what it has stored. Does it work for you correctly now?

**Comment by kolen** [comment]
@knikel seems that it works now.

**Comment by knikel** [comment]
Great, thanks for the feedback!
