### ISSUE TITLE
New viewer: weird behaviour with panoramic sequences

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1278]
The new viewer does not always behave normally when displaying panoramic sequences.

For example, at the end of this sequence, the camera movement is really weird: http://www.mapillary.com/map/im/bcEUDB_P7gUbiMvzk3Gqxg/photo

When checking the detail of the sequence, compass seems ok though: http://www.mapillary.com/map/e/dXxoGRYnm1ie9NWc23ylEA

I have other example if needed.

Thanks a lot!

**Comment by shlublu** [comment]
Another good example: http://www.mapillary.com/map/im/W8_FIv9x7kO88Qi9QqyQzg/photo

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
