### ISSUE TITLE
Weekly mails place me in the wrong country

### ISSUE THREAD

**Issue by marcgemis** [mapillary/mapillary_issues#1279]
My weekly email contains the text   

"Given the number of photos you've uploaded
This week you're number 31 top contributor in France"

I don't live in France and never uploaded a picture taken in France.

**Comment by shlublu** [comment]
I think this should be taken as a incentive :-)

**Comment by floscher** [comment]
This is the same as the closed issue #1127. But this time I'm also appearing on the [web-list of top contributors in France](http://www.mapillary.com/map/places/france?week=38), which wasn't the case when I opened #1127 AFAICR.

Did this happen to anyone with another country than France?

![This week you're number 29 top contributor in France](https://cloud.githubusercontent.com/assets/3904348/9999255/9cb9ef5a-6095-11e5-8357-608559718459.png)

**Comment by gyllen** [comment]
@floscher We are working on updating shapes. Mapzen just released this awesome set of borders -> https://mapzen.com/blog/who-s-on-first so expect borders to be a lot better within the next weeks \o/

**Comment by HolgerJeromin** [comment]
I think the new borders are not used till now for the weekly mails. My newest mail said "This week you're number 4 top contributor in Netherlands. Last week 10th". My new uploads were in Aachen, a few km away from the border.

**Comment by knikel** [comment]
@HolgerJeromin That's correct, we will switch the backend to new shapes very shortly.

**Comment by gyllen** [comment]
We still have problems with borders and are working on improving, but due to simplification this might never be solved in full.
