### ISSUE TITLE
iOS stops taking pictures after a lot have been taken

### ISSUE THREAD

**Issue by thomersch** [mapillary/mapillary_issues#128]
After the App is running for some time (> 1000 pictures) it often stops taking pictures. The preview image freezes, but the ”record" button stays red and the screen is still flashing as if it would continue taking pictures, which it isn't.

When I put the Application into background mode and launch it again, the preview screen stays white and nothing happens. When killed and relaunched, the App works sometimes, but in some other cases it looks like it would take pictures, but freezes in reality - like described at the top.

This bug occurs on iPhone 5, iOS 7.1.1, Mapillary 1.9. When the error occurs I have about 1 GB of free space left on the device.

Let me know if you need more information.

**Comment by gyllen** [comment]
Closing, please reopen if this happens in iOS app version 2
