### ISSUE TITLE
Website: Access to user profile and sequences is really slow

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1280]
It takes ages to access to the user profile or to sequences, currently, on the website. 
This wasn't the case three weeks ago. 

I tried several times between saturday evening and this morning, with three different computers in good network conditions (fiber, two different providers) so I don't think this is related to the machine or to the IAP. I tried with Chrome and Firefox with the same results, so this doesn't seem related to the browser either. 

Did someone else notice that?

**Comment by jrcarlsen** [comment]
Really slow from Thailand, but this is unfortunately not uncommon. Where are you located?

**Comment by jesolem** [comment]
AWS seems to be having issues today. We'll investigate.

**Comment by shlublu** [comment]
@jrcarlsen I'm in Paris right now. 
@jesolem Many thanks!

**Comment by gyllen** [comment]
Should be fixed by now
