### ISSUE TITLE
New viewer: Map not rendered fully. Chrome / Win 7

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1282]
When I go to the map, e.g.: http://www.mapillary.com/map/search/56.09088766494284/56.30233056146639/9.954870338518276/10.458543787172744
the map is not fully rendered. When I zoom in and out, parts of the map (like single tiles) is some times shown shortly and then disappears.

![image](https://cloud.githubusercontent.com/assets/8446338/9193993/4f7a3986-4018-11e5-9c7b-5b142100bad7.png)

WebGL is work fine when I go directly to a sequence.

The only messages in the development console is:
Font from origin 'https://api.tiles.mapbox.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access.

All privacy plugins have been disabled.

About my browser:
Google Chrome	44.0.2403.130 (Official Build) m (32-bit)
Revision	d8899c841d0d45e98c9a4c38e11195a96a081304-refs/branch-heads/2403@{#586}
OS	Windows 
Blink	537.36 (@199588)
JavaScript	V8 4.4.63.25
Flash	18.0.0.209
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
Command Line	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end

**Comment by simonmikkelsen** [comment]
When I enter the map right now it still looks and behaves like before. But the only error in the console is:

GET https://rawgit.com/Leaflet/Leaflet.draw/master/dist/leaflet.draw-src.js net::ERR_BLOCKED_BY_CLIENT

When I move the map it is just like before: It looks like it only shows the upper left tile, so when a new one enters the frame the "old" one disappears. All labels are shown but no map.

Because this happens at my work place, it prevents me from pimping Mapillary to around 500 IT professionals :-(

**Comment by shlublu** [comment]
Roughly the same issue here. Once I unzoom a bit, the map gets stuck:

![image](https://cloud.githubusercontent.com/assets/12934696/9542573/3c77088e-4d72-11e5-88a6-853e569f5e96.png)

When I zoom again, it gets better but its is not completely working:

![image](https://cloud.githubusercontent.com/assets/12934696/9542601/8a8b9b98-4d72-11e5-91fa-a399332de2b5.png)


Even close zooms still have problems after that:
![image](https://cloud.githubusercontent.com/assets/12934696/9542618/ac28ae12-4d72-11e5-8778-78f2b907903b.png)

![image](https://cloud.githubusercontent.com/assets/12934696/9542643/de99063a-4d72-11e5-8fca-91ef3a81aa53.png)

**Comment by simonmikkelsen** [comment]
The problem still persists here, even after the latest updates. The errors I get in the prompt are:

Font from origin 'https://api.tiles.mapbox.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access.
d2munx5tg0hw47.cloudfront.net/tiles/20/551999/322288.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/551999/322288.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/551999/322287.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/551999/322287.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/551998/322288.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/551998/322288.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/552000/322287.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/552000/322287.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/551998/322287.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/551998/322287.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/552000/322288.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/552000/322288.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/552001/322287.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/552001/322287.mapbox 403 (Forbidden)
d2munx5tg0hw47.cloudfront.net/tiles/20/552001/322288.mapbox:1 GET https://d2munx5tg0hw47.cloudfront.net/tiles/20/552001/322288.mapbox 403 (Forbidden)

The last couple of days I only got the 403s.

**Comment by simonmikkelsen** [comment]
Thanks for the update in #1230  @knikel . Just a reminder, that unfortunately I have a single case where the viewer does not work.

It is at my workplace, so until it works here too I cannot publish a general message to the company about Mapillary. We are around 500 people at the location, so I hope to gain a mapper or two.

**Comment by shlublu** [comment]
Still ongoing unfortunately. On top of that the "improve this map" link goes to MapBox and not to OSM.

![image](https://cloud.githubusercontent.com/assets/12934696/10413525/a67b2704-6fac-11e5-9da7-a6ee815e3de3.png)

**Comment by HolgerJeromin** [comment]
Simon Poole suggested linking to http://www.openstreetmap.org/fixthemap a while ago.

**Comment by oscarlorentzon** [comment]
Reassigning to @knikel for consideration when building the map in the new website.

**Comment by knikel** [comment]
We're using latest version of mapbox-gl-js and their tiles, this isn't anything we can fix really. Regarding the attribution, this is an attribution required by Mapbox, and comes out of the box with mapbox-gl-js.
