### ISSUE TITLE
Icons show angle points north, even though angle value shows something else

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1284]
I've been uploading several sequences without information on the direction (angle) the photo was taken in, and after that using the Mapillary Edit interface to batch-change the angle of the whole sequence. However, it looks like the photo icons still show arrows pointing north (the default when there is no direction information), even though the information clearly shows the angle is corrected (in this case, to 140 degrees). Note, this is after the angle change has been requested and accepted.

![clipboard image 1](https://cloud.githubusercontent.com/assets/1436366/9197619/ef7710e0-4035-11e5-86ca-4cb39787c375.png)

**Comment by knikel** [comment]
This has been fixed. The editor experience will be much better soon.

**Comment by pbb72** [comment]
Is this fix public yet? Please don't close issues until we can verify.
