### ISSUE TITLE
iD editor links are broken

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#1285]
"Edit via iD" button leads to urls like:

``http://www.openstreetmap.org/edit?editor=id#map=10.01462385619078/59.88877703435719/``

However iD returns to last edited area instead of centered around that photo. And that coordinates (10., 59.) are erroneous.

**Comment by jesolem** [comment]
Hi @kolen 
I just tried the iD link on [a photo](https://www.mapillary.com/map/im/9C8a9PRrRukpPyZvLS_-pw/photo) and got this url:
http://www.openstreetmap.org/edit?editor=id#map=14/68.350743/14.453801
and the API for the same image key gives

```lat: 68.350743,
lon: 14.453801,```

Looks correct, no?

**Comment by kolen** [comment]
Seems that this is unstable. I tried
http://www.mapillary.com/map/im/5XMuj2V_0-HlJjX-Ca3bEw/photo

Sometimes it makes correct link:
``http://www.openstreetmap.org/edit?editor=id#map=14/59.88877703435719/30.587330320850015``
One time it lacked second number (latitude):
``http://www.openstreetmap.org/edit?editor=id#map=14/30.587330320850015``
When I created this issue it was:
``http://www.openstreetmap.org/edit?editor=id#map=10.01462385619078/59.88877703435719/``

**Comment by jesolem** [comment]
@kolen I should have mentioned that we deployed the fix ~2 days ago. Can you just try shift-reload or restart your browser? Thanks

**Comment by jesolem** [comment]
@kolen Works?

**Comment by kolen** [comment]
Maybe that problem with garbled coordinates in links is gone now, but now I see link without coordinates at all in non-webgl Chromium:

``http://www.openstreetmap.org/edit?editor=id#map=//``

For any photo.

Firefox, where webgl works, displays links correctly.

related to #1230

**Comment by jesolem** [comment]
OK. First problem solved then. Assigning to @knikel for WebGL check.

**Comment by knikel** [comment]
:wrench: :boom: Fixed.
