### ISSUE TITLE
Perma-link to a users images/sequences on the map

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#1286]
Once #950 is implemented, it would be nice to have on a user's profile page a link to show his sequences on the map. thus e.g. from http://www.mapillary.com/profile/jesolem a link to something like http://www.mapillary.com/map/user=jesolem (or whatever URL scheme you'll think of :-))

**Comment by knikel** [comment]
This is technically not possible. We're relying on data from vector tiles and we can only query the data that's visible in the current zoom level. Assuming you're seeing the whole world in the map. The lines/dots that make up what you see are only a tiny fraction of what data is at higher zoom level in the tile. There is no way we could exhaustively query that data (potentially thousands of gigabates). We've done tests with precisely that: zooming the map to given users contributions and it's so so. It works well for situations that you've mapped 30km+ as one sequence, then there is a high probability that we can zoom in to these bounds. However if you've mapped a sequence in US, couple of sequences in Europe it's impossible for us to zoom to these bounds reliably, as your contributions are VERY likely to get lost in the data that's displayed in the low zoom level view. Sorry.
