### ISSUE TITLE
Confusion between Georgia (the US state) and Georgia (the eastern european/asian country)

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1287]
The page http://www.mapillary.com/map/places/georgia shows the US state Georgia, but lists me as top contributor (on the tab "Global") although I didn't take pictures in the US, but in Georgia (the country in Europe/Asia).

**Comment by AllenGraetz** [comment]
Itog, I don't know know where they are in addressing this issue.  I know it's been reported in the past on their radar.

**Comment by gyllen** [comment]
This is correct, we are in the works of upgrading with better borders.

**Comment by peterneubauer** [comment]
This is done now. Closing.
