### ISSUE TITLE
API: Add multiple oauth callback path

### ISSUE THREAD

**Issue by eMerzh** [mapillary/mapillary_issues#1292]
to allow multiple path in the same app , 
or for example multiple environments (tests, ...)

**Comment by gyllen** [comment]
Yes I like this idea. I am often annoyed myself when I need to create two different apps, one for testing and one for production. Thanks for suggesting this.

**Comment by gyllen** [comment]
Currently not on the roadmap. The idea is to replace the whole oauth solution at some point and when we do we will mosdef add this feature.
