### ISSUE TITLE
Policy on uploading pictures with inaccurate geotagging

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1294]
I take pictures with a digital photo camera and geotag them with an external GPS logger. Sometimes the quality of the GPX track is poor (most often due to territory not allowing getting a good fix (mountains)).

Should I upload such pictures anyway? What is an acceptable distance error? I guess pictures of places like https://en.wikipedia.org/wiki/Abano_Pass (which I happen to have) could be of value to some people even if they are way off... Also it might be difficult to even get pictures in such areas that are of better quality (geotagging-wise).

**Comment by richlv** [comment]
i use josm with a couple of plugins and fix such images manually.
but note that many people upload images with smartphones, that might have even worse gps, and they do not review the images before the upload at all

**Comment by ltog** [comment]
@richlv 

AFAIK the Mapillary app doesn't record pictures if GPS reception is poor.

I know and use JOSM. Is there a plugin/workflow (with or without JOSM) that would allow for mass-processing images? Manually editing single files just doesn't scale well...

**Comment by richlv** [comment]
so it does, but there are cases where gps/phone reports ok reception, but the actual results are pretty bad or even terrible. i've seen sequences with images over 100 metres reported to be at the same spot and pointing in the wrong direction :)

to manipulate individual images i use photo_geotagging and photoadjust plugins. this can still be pretty efficient to manipulate a few dozen images.

if there's a need to manipulate a large amount of images in a uniform fashion, my workflow usually is to edit the gpx trace from which i geotagged the images. i convert it to data layer, cut up in portions, even them out (shift+b), convert back to gpx, save & re-tag the photos.

this is quite efficient, for example, in "urban canyons" - gps results often are crap even with good devices, but i can pinpoint photos at crossings. i'd cut up the trace per block, shift-b each block and then re-tag the photos. this is easy as i know that i walked at an even pace and even if photos were not taken too evenly, they will be distributed very close to the real location.

but this is quite offtopic by now - i hang out in #mapillary on freenode irc network, feel free to poke me there :)

**Comment by shlublu** [comment]
It would actually be useful to have a tool to redraw the GPX in the edit page, instead of fixing the pictures one by one.

For example, in this sequence, fixing each and every location is going to take a long time. Redrawing the GPX would be easier, as I know exactly the path I took, and I also know I was taking one picture every 5 steps but in turns.

**Comment by HolgerJeromin** [comment]
@shlublu your idea is similar to the idea in #637

**Comment by shlublu** [comment]
@HolgerJeromin Absolutely! I didn't know this one, thanks

**Comment by richlv** [comment]
note that you don't upload your gpx, the gpx mapillary offers to download is just all photos, concatenated together. you only upload geotagged photos. as such, sort of "editing gpx" might be complicated.
looking at issue #637, it seems like mapillary should really start using josm for everything instead of trying to reimplement it in browser ;)

**Comment by jesolem** [comment]
Thanks @ltog 
Let me try to answer this in a way that is interpreted as a policy.

The apps allow you to take photos with the GPS reporting accuracy up to 15m (<8m green icon, <15m yellow icon, >15m red and capture disabled). We think this is a reasonable worst accuracy. 15m off could be on the wrong side of the street or even the wrong road, worst case.

Policy attempt:
**You should upload photos with 15m accuracy or better. If your GPS has worse accuracy or you suspect that the photos will be way off when you upload them, you should edit it if you can.** Edit before or after uploading depending on your technical skill level and what tools you have.

Editing in JOSM is great for the people who have that, but we have to realize that most Mapillary users do not. Hence we have a web based editor for post editing. (Yes, the editor is in much need of a re-haul. That's a separate issue and we're working on it.)

**Comment by jesolem** [comment]
Added to the [User Guide wiki section on image editing](https://github.com/mapillary/UserGuide/wiki/Pre-Upload-Image-Editing).
