### ISSUE TITLE
Traffic sign game picks incorrectly traffic sign after I saved correctly

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1295]
When I pick more than one traffic sign at traffic sign game and I submit it then Traffic sign game modify my saved traffic sign and dupes last traffic sign I have selected.

Tested with last Firefox on Win7

**Comment by kolen** [comment]
Maybe the same problem as #1300.

**Comment by knikel** [comment]
@kolen Very likely. @yopaseopor this should be fixed now, if it ever happen to you again, please comment here with a link to the photo and we will investigate further. Thanks for your feedback guys.
