### ISSUE TITLE
Trying to create an account fails with a HTTP 500 error logged to the console

### ISSUE THREAD

**Issue by tilmanb** [mapillary/mapillary_issues#1296]
When trying to create an account on http://www.mapillary.com/map/signup , after clicking the Sign Up-button nothing visible happens. The javascript console of firefox shows "NetworkError: 500 Internal Server Error - https://a.mapillary.com/v2/ua/signup?client_id=<redacted by me>"

**Comment by gyllen** [comment]
Fixed, thx for reporting
