### ISSUE TITLE
Traffic sign types are shifted when saving on photo page

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#1300]
I added 4 signs using [photo page](http://www.mapillary.com/map/im/shMYolopZ25SR754dvYjhg/photo) (not [game](http://www.mapillary.com/map/games/traffic)) with following types:

1. Pedestrian crossing
2. Yellow square (I don't know what it means)
3. Pedestrian crossing
4. Other (for bus stop sign)

After saving, they became:

1. Yellow square
2. Pedestrian crossing
3. Other
4. Other

Seems that list of sign types was shifted by removing first element and adding "Other" as last element.

![2015-08-21 0 06 57](https://cloud.githubusercontent.com/assets/24191/9395751/e52da670-4798-11e5-9aab-5373cc37538a.png)

Occurs for me each time.

**Comment by kolen** [comment]
Another sample ([this photo](http://www.mapillary.com/map/im/8xv-dpQw4elLTE9aCgRNRQ/photo)); signs were added from right to left, rightmost sign already existed before edit:

Before "Publish edits":
![2015-08-21 0 18 34](https://cloud.githubusercontent.com/assets/24191/9396027/a35e65de-479a-11e5-97f7-15d40635ec3b.png)

After "Publish edits":
![2015-08-21 0 18 55](https://cloud.githubusercontent.com/assets/24191/9396010/84986ad2-479a-11e5-9ab7-1efd67dcadf0.png)

**Comment by knikel** [comment]
This has been fixed @kolen, thanks a lot for reporting! :+1:
