### ISSUE TITLE
Map Style

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1301]
Hey...

it would be nice for the Contributers, to have to posibilty to swap between the Map Style (old/new).
As i am using the old-Style to see, what i missed to map to contribute it.
For me it's a little bit easy to see and check .. on the new stlye, if you zoom out, to fast are couple small way's are hiding in the zoomlevel.

Cheers
Thorsten

**Comment by thoschu96** [comment]
any update on this ?
i wanna map as much as possible on my town, but hard to see, when the rendering is not working to the deepest level or the details from the map are going to hide, when i zoom out.

**Comment by knikel** [comment]
@thoschu96 We use the _old_ (as in non-WebGL) map as a fallback and currently there are no means to display it unless your browser doesn't support WebGL. We'll be reviewing users profiles in the foreseeable future and might add a preference settings there.

**Comment by knikel** [comment]
To get the best viewing experience please use a browser that supports WebGL.

We're tracking the gl/non-gl map toggle on profiles internally.
