### ISSUE TITLE
Please get rid of moving image on main webpage

### ISSUE THREAD

**Issue by trigpoint** [mapillary/mapillary_issues#1304]
The movement when I am trying to type and select where I want to see is distracting a makes my eyes go funny.
A static image would be a major improvement.

**Comment by jesolem** [comment]
We can see about pausing when you select the search box. -> @knikel 

We had stills for a very long time but people didn't understand that the photos are connected to other photos and that you can move around. Wanted to give new visitors a quick demo.

**Comment by trigpoint** [comment]
Thank you, that sounds good, I can see why you did it but it does make typing difficult

**Comment by knikel** [comment]
The video pauses as soon as one activates the serchbox now. Thanks for the feedback!

**Comment by shlublu** [comment]
The video doesn't pause currently. Was this change deployed?

**Comment by knikel** [comment]
@shlublu yes, it's been deployed and seems to work as expected? Would you mind reloading the browser with clearing cache? Sometimes that's an issue. If it doesn't help I'd love to know you browser's and system's details then :wink:.

**Comment by shlublu** [comment]
Hahahahaaaaa, the cache! How could I miss that... 
So it works.
Sorry :)
