### ISSUE TITLE
Incorrect contourlines

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#1305]
I've noticed that the map shows absolute incorrect contourlines.
Don't know if this is a mapillary or OSM issue?

**Comment by gyllen** [comment]
@Peatsmoke Can you paste a screen shot?

**Comment by Peatsmoke** [comment]
The hill on this screenshot is about 225 m high, on this map the foot of the hill is 430m. 

![schermopname 11](https://cloud.githubusercontent.com/assets/10783093/9869001/78612e04-5b7f-11e5-8ba2-2fd4dfcbbad0.png)

**Comment by jesolem** [comment]
Hi @Peatsmoke 
This is an OSM issue. Thanks.
