### ISSUE TITLE
Video import broken

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1306]
Hey
my Videoimport seems to be broken
http://www.mapillary.com/map/im/bCQT5a95NpBzDmnpXi5_vg/photo
it much longer (2.30 minutes) and not only couple seconds.
The GPX signals is couple seconds the same (car stops) .. maybe the importer has
a problem with tha ?

Cheers

**Comment by paulinus** [comment]
@thoschu96, stopping for some seconds should not be a problem. Did you manage to get proper video imports after this one?
