### ISSUE TITLE
Empty sequence?

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#1307]
[this](http://www.mapillary.com/map/im/aARomM837OtcJazYIrGcZQ) sequence seems to be empty or faulty

**Comment by shlublu** [comment]
So is this one; http://www.mapillary.com/map/im/ZTDt4tjzY05ePSmIA5vtNg/photo

**Comment by gyllen** [comment]
Is this one newly taken?

**Comment by shlublu** [comment]
@gyllen It has been uploaded on last Wednesday or Thursday as far as I remember.

**Comment by gyllen** [comment]
Looking at it it seems like there is only one image in this sequence. Is that correct?

**Comment by shlublu** [comment]
@gyllen I actually don't remember :) I noticed the problem as I wanted to check and edit it (location, orientation) if needed according to my notes and what the picture(s) is/are showing.

**Comment by Skippern** [comment]
Mine as qell was probably uploaded a week or so ago, maybe 2, should be multiple photos

**Comment by gyllen** [comment]
Both seems to work fine now.
