### ISSUE TITLE
Traffic sign editor shows signs from another image when trying to edit unprocessed image

### ISSUE THREAD

**Issue by kreed** [mapillary/mapillary_issues#1309]
Open the traffic sign editor on this photo:
http://www.mapillary.com/map/im/7zzaVnQde4s6sZyZ3XXAFQ/photo

Now step forward to the next photo. The editor will tell you the image is unprocessed, but will still show the sign from the first photo.

**Comment by knikel** [comment]
This has been fixed, we have better checks when moving between images.
