### ISSUE TITLE
Panorama not working

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1312]
It seams for me, that after the new MAP-Style, the Panorama function is no longer working.
http://www.mapillary.com/map/im/CaTYa2v29jUfHMmIco66dQ/photo
If you click on the Picture to "move", it goes Black

**Comment by oscarlorentzon** [comment]
Thanks for reporting @thoschu96 ! 

This should now work. You can look around in the panorama by dragging and you can zoom in and out with the zoom buttons in the top right corner of the image. Just report back if you experience any more problems.
