### ISSUE TITLE
Showing number of change requests per edit

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1314]
Hi!
While you anly accept 100 changesets at once, please do show how many changes a user has done in a "edit session".
E.g. "you have already moved x pictures and blurred 20 parts". AS the page reloads on every moved picture, it should be easy to display that stat. 
It is quite hard to count the number of changes with counting icons in lower area...

**Comment by shlublu** [comment]
I'm discovering this message: "We currently can not accept more than 100 change sets at once. Please make sure you submit less than 100 change sets in one request."

One of my change request consisted in making precise the 136 (as far as I remember) points of this sequence on a location and orientation standpoint: https://www.mapillary.com/map/im/vMeSYltnzhwxuTY3K-Q6wg/photo

Doing this took me a while, is that change request lost?

**Comment by knikel** [comment]
@angelday: something to consider for the editor. 👍 from me!

**Comment by gyllen** [comment]
This is visible in new editor closing
