### ISSUE TITLE
Automatic sequence split according to distance between two photos

### ISSUE THREAD

**Issue by Chivos** [mapillary/mapillary_issues#1316]
When looking at the map, we can sometimes notice big straight lines, because two photos in the same sequence are too far.

Is it possible to perform an analysis to detect these situations and auto-correct ?

**Comment by peterneubauer** [comment]
Yes. We have implemented autosplit in the apps, and have bots in the backend that can suggest splits, we will run them soon again as we adjust the changeset structure for better trace-ability.

**Comment by Chivos** [comment]
Ok, perfect !
Thanks for your reply.

**Comment by moenk** [comment]
There are also sequences that draw long lines across the map, but I can not select them for editing and suggest a split, so I second this proposal to split automatically, 
@peterneubauer Which maximum distance these bots in the backend are looking for?

**Comment by peterneubauer** [comment]
The bots are right now hard coded to 300m but we are going to make it
configurable.

**Comment by peterneubauer** [comment]
This should be working now.
