### ISSUE TITLE
API /v2/search/im/geojson output doesn't include name and other properties

### ISSUE THREAD

**Issue by mvl22** [mapillary/mapillary_issues#1317]
The API V1 GeoJSON output:
http://api.mapillary.com/v1/im/search?min-lat=55.611&max-lat=55.613&min-lon=12.994&max-lon=12.995&max-results=3&geojson=true

includes the fields ```location```, ```image```, ```compass_direction```.

However, in the V2 output, these are not present:
https://a.mapillary.com/v2/search/im/geojson?client_id=...&min_lat=55.611&max_lat=55.613&min_lon=12.994&max_lon=12.995

At present, this is a blocker to us migrating to V2.

**Comment by jesolem** [comment]
Hi @mvl22 
You mean this API call?
https://a.mapillary.com/#get-searchimgeojson

You have the lat, lon, ca (compass angle), image key. See sample in the sidebar. Is this not what you need?

**Comment by mvl22** [comment]
Yes, that API call.

Is the removal of the ```location``` name deliberate here? Currently it is inconsistent with the flat-JSON output and the V1 GeoJSON output. Currently we are using that in our integration.

(Apologies for misunderstanding the use of the ```ca``` and ```key``` values, which are fine.)

**Comment by gyllen** [comment]
Yes we no longer do geocoding and save on the backend.
