### ISSUE TITLE
API /v2/search/im has corrupted location names

### ISSUE THREAD

**Issue by mvl22** [mapillary/mapillary_issues#1318]
In the flat-JSON ```/v2/search/im``` call, the ```location``` field has corrupted names when characters containing diacritic characters:

> https://a.mapillary.com/v2/search/im?client_id=...&min_lat=55.611&max_lat=55.613&min_lon=12.994&max_lon=12.995&geojson=true

shows ```"location":"NordenskiÃ¶ldsgatan, MalmÃ¶"```

By contrast, the V1 API (with or without ```geojson=true```) shows these correctly:

> http://api.mapillary.com/v1/im/search?min-lat=55.611&max-lat=55.613&min-lon=12.994&max-lon=12.995&max-results=3&geojson=true

```"location":"Nordenskiöldsgatan, Malmö"```

**Comment by Stalfur** [comment]
This bug is present on the Mapillary front page
![image](https://cloud.githubusercontent.com/assets/4370958/13503960/08cf8d58-e16a-11e5-8776-37c19588c7f1.png)

**Comment by gyllen** [comment]
@knikel Thought we fixed this with mapzen

**Comment by knikel** [comment]
Shouldn't be an issue anymore, Mapzen updated encodings 🎉 

<img width="592" alt="search-1" src="https://cloud.githubusercontent.com/assets/1574656/15715568/442d24b8-281f-11e6-9b20-f43f78e11bf6.png">
