### ISSUE TITLE
geolocalize 0.5s timelapse picture

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1319]
Hello,

My first test with the Xiaomi Yi action cam was with a 0.5s timelapse.
I have a gpx record to geolocalize these pictures but I have 2 or 3 pictures for each same second

There is no subsectime exif tag in the pictures.

Does anyone know a way to geolocalize these pictures ?

I think it could be possible with 2 steps : 
- a script add a subsectime exif tag (interpolation)
- a gpx to exif geotags which can use the subsectime tag

But I'm unable to do this.

![2015-08-05-10-08-44-xiaomi_yi-ydxj0009](https://cloud.githubusercontent.com/assets/8255984/9490100/fd47d4d2-4be5-11e5-9714-ab45eec5d2f3.jpg)
![2015-08-05-10-08-44-xiaomi_yi-ydxj0007](https://cloud.githubusercontent.com/assets/8255984/9490102/fd4d1ffa-4be5-11e5-91b7-4d440e56824c.jpg)
![2015-08-05-10-08-44-xiaomi_yi-ydxj0008](https://cloud.githubusercontent.com/assets/8255984/9490101/fd49567c-4be5-11e5-86f3-12ae57bfac92.jpg)

**Comment by gyllen** [comment]
@Stefal OT: Is there anyway to get less dashboard in the picture?

**Comment by Stefal** [comment]
Yes, If I point the camera a little more to the sky :-) 
With such a wide view angle it's impossible to hide the dashboard entirely if you keep the camera inside the car... or perhaps in a vehicule with a vertical windshield and a short hood.

The best way is to place the camera on top of the car, like another contributor : 
http://www.mapillary.com/map/im/pMSWMhR601cA6EYvdommbQ/photo

For these pictures, I could crop them before the upload

**Comment by blaueente** [comment]
Hi, 
I have the same problem. I have now written a script snippet that adds an interpolated subsectime: 
```python
#!/usr/bin/python
import os
import datetime
import pyexiv2

class photo:
    filename = ''
    datetime = None
    newdatetime = None

    def __init__(self, filename):
        self.filename = filename
        metadata = pyexiv2.ImageMetadata(filename)
        metadata.read()
        self.datetime = metadata["Exif.Photo.DateTimeOriginal"].value
        #TODO: read in existing SubSecTimeOriginal?

    def write(self):
        if not self.newdatetime is None:
            metadata = pyexiv2.ImageMetadata(filename)
            metadata.read()
            metadata["Exif.Photo.SubSecTimeOriginal"] = "%.6d"%(self.newdatetime.microsecond)
            metadata.write()

# this builds up a list of all photos in the current directory and reads in the timestamps. Sorted lexicographically, i.e. it takes the image order from the filenames
# TODO: nicer option handling and command line interface. Maybe from other mapillary scripts?

path = "."

file_list = []

for root, sub_folders, files in os.walk(path):
    file_list += [os.path.join(root, filename) for filename in files if filename.lower().endswith(".jpg")]

file_list.sort()
print "found %d images. Reading in datetimes (this may take some time)" % (len(file_list))
photolist = [photo(filename) for filename in file_list]

print "Calculating..." 

# this is the main functionality: if second value of the timestamp is constant, distribute all images (except the first) equidistantly on this second.

dupe = 0
# this list contains all indices of photos that have duplicate time (excluding the first photo)
modlist = []
for i in range(1,len(photolist)):
    delta = photolist[i].datetime - photolist[i-1].datetime
    if delta.total_seconds() == 0:
        modlist.append(i)
    else:
        if len(modlist) > 0:
            increment = 1./(len(modlist)+1)
            for i in xrange(len(modlist)):
                print "  * adjust image %s by %f seconds: "%(photolist[i].filename, (i+1)*increment)
                photolist[modlist[i]].newdatetime = photolist[modlist[i]].datetime +  datetime.timedelta(seconds =(i+1)*increment)
        dupe = i
        modlist = []

print "Writing new datetimes" 
# write exifs:
for p in photolist:
    p.write()
```
Now I hope to find a tool for correlating. I have tested gpscorrelate, which does not respect subsecond timing. Probably I will simply patch `geotag_from_gpx.py`...

**Comment by Stefal** [comment]
Many thanks @blaueente !
I will test your scripts as soon as possible.

**Comment by blaueente** [comment]
Apparently there is something wrong, as can be seen on (this is a test drive with xiaomi yi and aforementioned scripts):
http://www.mapillary.com/map/im/yIQurcjUB13OPpEWKEe0FQ/photo
For some reason, the position is recorded correctly (map is correct), but the order of the image in the sequence is wrong. Could it be that the mapillary service itself cannot handle sub-second accuracy? At least in https://github.com/mapillary/mapillary_tools/blob/master/python/add_mapillary_tag_from_exif.py milliseconds are set to 000 for each photo. I would patch that script as well if I knew this would help, but don't know if the mapillary service itself can handle that, and, this would probably not fix the "upload with authentication".
@gyllen, does the mapillary core or upload service support sub-second accurate timestamps?

**Comment by gyllen** [comment]
@blaueente Its sure does, we had a problem with this for splitting videos but we solved it by using milliseconds.

**Comment by Stefal** [comment]
@blaueente Did you rename the file before upload ?
I ask this because I had the same problem on one Yi sequence.
Since this problem, I rename the pictures with advance name renamer, and use the add_mapillary_tag_from_exif.py

**Comment by blaueente** [comment]
I have now patched add_mapillary_tag_from_exif.py :   https://github.com/blaueente/mapillary_tools/commit/7817da9943e92e84f1040a9084a9eef25b05383f#diff-5ccb3bb8f266b28e86ba8caf03c9c964
I have requested to hide the old trial sequence(s) (I had one with authorized upload, and one with added mapillary tags, both exhibited the same problem.) and try to re-upload it, starting with a small number to see the reaction, then more if I am satisfied.

**Comment by blaueente** [comment]
@Stefal the only renaming I did was adding something to the front, as I had two folders in DCIM with the same image names, e.g. I had DCIM/100MEDIA/Y0070816.jpg and DCIM101MEDIA/100Y0070816.jpg, so i renamed them to  100Y0070816.jpg and 101Y0070816.jpg respectively. Those files are already in correct lexicographical order, so I cannot imagine the reason why further renaming could fix this problem. How did you rename your photos?

**Comment by Stefal** [comment]
I can't use geotag_from_gpx.py on windows (original version or yours), I get this error : 

```File "build\bdist.win32\egg\dateutil\tz.py", line 41, in inner_func
UicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 22: ordinal not in range(128)```

You can forget my rename things, I think I made an error.

**Comment by blaueente** [comment]
Hm, some string handling seems to be screwed up. Do you have a more complete stack trace, from which one can see which exact line in  geotag_from_gpx.py would cause this?

**Comment by Stefal** [comment]
How could I get this stack trace ?

BTW : Windows installed in fr-FR language

**Comment by blaueente** [comment]
@Stefal I have no clue, usually on my linux system a stack trace is displayed just beneath the actual error.

Now I have re-tried tagging the photos and started uploading the photos, and: it did finally work :) http://www.mapillary.com/map/im/Cq9F-VNMnzVHPG_SJkdulQ/photo

**Comment by Stefal** [comment]
```Traceback (most recent call last):
  File "geotag_from_gpx.py", line 208, in <module>
    print("Your local timezone is {0}, if this is not correct, your geotags will be wrong.".format(now.strftime('%Y-%m-%d %H:%M:%S %
Z')))
  File "build\bdist.win32\egg\dateutil\tz.py", line 41, in inner_func
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 22: ordinal not in range(128)```

**Comment by blaueente** [comment]
According  to https://de.wikipedia.org/wiki/ISO_8859-1#Windows-1252, Hex 92  is " ’ " in windows. And it does not have a direct visible reason in line 208, so it must be some issue with system character set settings. Google spits out the following link, perhaps some of those solutions work for you: https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by Stefal** [comment]
I'm not a dev, but here is what i've found: 
```
>>> import datetime
>>> from dateutil.tz import tzlocal
>>> now = datetime.datetime.now(tzlocal())
>>> print format(now.strftime('%Z'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\dateutil\tz.py", line 41, in inner_func
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 22: ordinal not in range(128)
```
If I delete '%Z' from the line `print("Your local timezone is {0}, if this is not correct, your geotags will be wrong.".format(now.strftime('%Y-%m-%d %H:%M:%S %Z')))` This script works on my system

https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior tells:
Because the format depends on the current locale, care should be taken when making assumptions about the output value. Field orderings will vary (for example, “month/day/year” versus “day/month/year”),**and the output may contain Unicode characters encoded using the locale’s default encoding** (for example, if the current locale is ja_JP, the default encoding could be any one of eucJP, SJIS, or utf-8; use locale.getlocale() to determine the current locale’s encoding).

But sadly:
```
>>> import locale
>>> print locale.getlocale()
(None, None)
```
After a few searches :
http://stackoverflow.com/questions/19412915/how-determine-encoding-of-datetime-strftime-in-python
https://bugs.python.org/issue20010

And yes !!!
```
>>> print format(now.strftime('%Y-%m-%d %H:%M:%S %z'))
2015-09-18 08:28:34 +0200
```

So changing %Z to %z works for me, and I still get the Timezone info.
Does it work on other system ?

**Comment by Stefal** [comment]
@blaueente, did you change something in your workflow to fix your problem ?

**Comment by blaueente** [comment]
@Stefal: actually this works now with the following steps: 

1. adding milliseconds using my script above
2. using my modified version of `geotag_from_gpx.py` to add location information
3. using my modified version of `add_mapillary_tag_from_exif.py` to add mapillary tags (either with manual sequence UUIDs or using `convert_each_folder_into_one_sequence.py` which calls said `add_mapillary_tag_from_exif.py`)
4. uploading using standard `upload.py`

Note that steps 3 and 4 are necessary, `upload_with_authentication.py` does not seem to work with sub-second timestamps.

**Comment by Stefal** [comment]
Thank you @blaueente. I will try this.

BTW: you add microseconds, not milliseconds. Am I right ?
If yes, is this a choice or a technical limit ? SubsectimeOriginal seems to usually contain milliseconds.

**Comment by blaueente** [comment]
oh, I simply didn't care. According to the exif spec, those Subsectime fields contain the fractional part of the picture time with variable length, and python uses microseconds, so I took microseconds. However, milliseconds would be ok too. If you move for 1 millisecond at 100km/h you would go about 3 centimeters, so that should be just fine even with differential gps ;-)

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
