### ISSUE TITLE
Please do something about w3w tracking

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1320]
Every time I load a photo there is a request to w3w.com. IMO this belongs under the category of unnecessary tracking. Please remove the feature or make it optional or in such a way that no user data is leaked to w3w.

**Comment by shlublu** [comment]
A good solution could be to preload the W3W data when processing the picture instead of doing it at display time.

**Comment by de-vries** [comment]
@shlublu that would work, but is not allowed by their rather restrictive [API terms of use](http://developer.what3words.com/api/licence/). 
The use of their data is so restricted hat I wonder how they unite this with their wish to become a standard. But yeah, their business model is basically selling the same fixed set of data again and again (and all user data they can grab on the go).

**Comment by shlublu** [comment]
Thanks a lot @de-vries, I didn't know that. 

"You must not pre-fetch, cache, index, copy, re-utilise, extract or store any what3words Data.", yes, it makes it a problem. I like the W3W idea very much but it's true we can wonder whether this is really needed under these conditions.

**Comment by gyllen** [comment]
@de-vries Right now it will wait 2 seconds before it actually makes the request (so while you are moving no requests are made) to what3words so I don't think it that much data.

Also they are not tracking the lon/lat requests since they are essentially meaningless to them. I for myself like the idea of beeing able to address a location with a three letter word.

**Comment by shlublu** [comment]
I contacted W3W on Twitter to ask why W3W addresses cannot be stored. Because of this discussion, and also because I'm just wondering why and how to use an address I can't store. 

They replied and told me they don't hold any user data. I'm going to receive an official and certainly more comprehensive answer soon by email.

**Comment by BalooUriza** [comment]
Given that Mapillary partners with open data sources and makes an open data source, w3w seems like a bad fit, considering their location data and geolocation scheme is locked up.

**Comment by de-vries** [comment]
@gyllen, thanx for you reply. 
I think the two second lag doesn't matter much. if you only know the coordinates of 10% of the photos someone watches on mly you can get a pretty good idea of his/her region of interest. If you can combine that with any identifying information (IP, digital fingerprint) I bet you can find some advertisement or tracking company willing to pay for that data.

Also, after reading their [privacy policy](http://what3words.com/privacy/), I find statements that they don't collect certain data little reassuring.

IMO it's bad practice to leak user data of any kind when it's not absolutely necessary and clear to the user that this happens.

**Some things you could change to make it less worse or even better** (in that order, from a privacy perspective)
- at least don't load the w3w data if the photo detail widget is closed
- tell users that external data is requested. For example by displaying a "requesting data from w3w" label during the 2 second wait, similar to the "loading blurs" label. 
- make the w3w link optional via the settings
- only load it on request

@BalooUriza I totally agree with you there

**Comment by jesolem** [comment]
Thanks @de-vries and everyone. Good input. 

We are going to do this: In the info panel we have a "show" link after what3words and when you click that, we make the request and you get the w3w string with a hyperlink. 

OK?

**Comment by shlublu** [comment]
Sounds good. Could even be a settings option to make the choice persistant.

**Comment by de-vries** [comment]
yup, sounds good! thanx

**Comment by gyllen** [comment]
Fixed, to view w3w now, you have to push the Load link

**Comment by de-vries** [comment]
thanks for taking the privacy concerns seriously, but I see a small problem with how the solution is implemented.

If you load the w3w and then jump to a different photo the 3 words stay. To prevent confusion it would be better if : 

1. the 3 words disappear when switching to a different photo, or
2. the 3 words reload when switching to a different photo and the word "load" would be changed in "enable/disable".

**Comment by jesolem** [comment]
Makes sense.

**Comment by gyllen** [comment]
We no longer have W3W functionality. Please reopen if you feel needed.

**Comment by de-vries** [comment]
Have you considered [W3F](http://www.what3fucks.com), A similar service? ;) They have a much better license and you can run it on your own servers, so no privacy issues.

**Comment by gyllen** [comment]
Haha yes a MUCH better solution.

@de-vries On another matter I did delete the sequence with all of the black images but seem to have lost the ticket. Anyway now its deleted.

**Comment by de-vries** [comment]
> @de-vries On another matter I did delete the sequence with all of the black images but seem to have lost the ticket. Anyway now its deleted.

Was that an upload of mine? because I don't know what sequence you're talking about.

**Comment by gyllen** [comment]
@de-vries I think it was somebody else than you that commented. Trying to find issue. Sorry about that.
