### ISSUE TITLE
Make it posible to edit my edits

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1321]
I really like the "clear all blurs and request" button, but it's so fast that I sometimes make mistakes with it. Since its introduction I made several wrong blur request this way. There should be a edit blur request option, or a option to withdraw a blur request so I can make a new one.
/something to consider when redesigning the changeset DB.

**Comment by jesolem** [comment]
Thanks. @gyllen and @peterneubauer will hammer out the details and this one is on the list.

**Comment by richlv** [comment]
the easiest might be allowing to override your own blur requests. a confirmation would be nice, of course.
this could be helpful both to fix hasty "clear all" requests (have made 2 mistakes myself).

**Comment by AllenGraetz** [comment]
Thank you.  It would be nice to see what's pending for edits that I've requested.  I suspect I've been throwing some duplicates at you guys.

**Comment by nicolas17** [comment]
I need this too. My current approach is that if I accidentally click "clear all blurs and submit" when there are things to blur out, or add/remove blurs and submit and *then* notice a license plate I missed, or anything like that, I add a browser bookmark for that photo and move on. Once my blur requests are approved, I go through those bookmarked photos again. This is suboptimal to say the least :)

**Comment by gyllen** [comment]
New interface should prevent you from doing this
