### ISSUE TITLE
Garmin virb XE orientation

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#1323]
I have bought a virb XE and I've noticed that the orientation is never picked up.
I was playing with the upload_with_authentication and was able to obtain the actual orientation via calculation as it is stored like this : xxxxxxx/yyyyyy  the result is the true north orientation which I also check that there is a tag stating that the gps orientation is pointing to true north

Modified script to output orientation:
http://pastebin.com/PGmFr2YG

C:\pyscripts>python check_exif.py ./images/0/VIRB0031.jpg
GPSTrack: [5169239/15625]
330.831296

attached is the sample image. Could you include a way to calculate the correct orientation? it would save me a lot of time when uploading

![virb0031](https://cloud.githubusercontent.com/assets/498547/9510316/4573bb20-4c38-11e5-99a1-f79c76d57515.jpg)

**Comment by ybkuang** [comment]
We will take a look and see if we can find a good solution for this. Usually the image direction is stored in GPSImgDirection. And GPSTrack seems to store the direction of movement according to http://www.opanda.com/en/pe/help/gps.html#GPSTrack.

**Comment by mprins** [comment]
using GPSTrack would essentially emulate the same behaviour the app have for driving mode (ie. pointing in forward direction)

**Comment by DenisCarriere** [comment]
Having the same issue, `GPSImgDirection` is missing from the Garmin Virb XE camera.

Anyway include `GPSTrack` as the image direction, or at least a custom rule for the Garmin Virb XE.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
