### ISSUE TITLE
Sphere Icon

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1324]
Maybe a good idea, maybe not.

How about to make a Special "symbol" for Sphere pictures on the MAP
Currently it's only showing as a DOT.. maybe something similar like google-sphere.
A red dot , little bigger ..

A filter for , show only Sphere's around me, would be nice ...

**Comment by JLZIMMERMANN** [comment]
I do agree, it's welcome to have something showing if photos are simple picture, wide angle, panorama or spherical one.

**Comment by shlublu** [comment]
:+1:

**Comment by glw** [comment]
Yes I would also like to see single picture sequences handled differently then those with more than one image.

**Comment by knikel** [comment]
We'll have photo type filters in the next update of mapillary.com. Closing in favor of #1080
