### ISSUE TITLE
Live counter

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#1327]
I think it would be better that the counter to indicate kilometers instead of meters. Soon it will reach 1,000,000 km. (1,000,000,000 meters)
![km](https://cloud.githubusercontent.com/assets/8439643/9523875/af0dddf2-4ce4-11e5-882c-9637704320d6.png)

**Comment by simonmikkelsen** [comment]
Suggestion: Make the switch at 1,000,000 km :-)

**Comment by jesolem** [comment]
@simonmikkelsen That's the plan! ;)

**Comment by eugensim** [comment]
1,000,161,862 meters now !

**Comment by de-vries** [comment]
Did anyone see it going from 999,999,999 to 1,000,000,000? ;)
![selectie_101](https://cloud.githubusercontent.com/assets/1449609/10577490/ee39b3ce-766b-11e5-8ed2-577ddec5601a.png)

**Comment by gyllen** [comment]
Switch to km :)
