### ISSUE TITLE
Missing signs

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1328]
Hi
Normal I would be able to see a pictures of the signs on:
http://www.mapillary.com/profile/beer119/ors
I cannot do that anymore. Is that a problem?

**Comment by AllenGraetz** [comment]
For what it's worth, I suspect I'm seeing the same thing both on beer119's page and my own profile traffic page.  I'm running Chrome 44.024something.

http://screencast.com/t/3z3BE1BCQ8

**Comment by knikel** [comment]
The signs should be visible. There must've been font icon deploy hiccup at the time.
