### ISSUE TITLE
Where are my uploaded photos?

### ISSUE THREAD

**Issue by zibik** [mapillary/mapillary_issues#1330]
Hi!
I uploaded some photos yesterday (August 27), but these pictures are invisible on my profile: http://www.mapillary.com/profile/zibi-osm/uploads
Additionally, I noticed missing photos on August 23.
Why? Is it a temporary problem?

**Comment by zibik** [comment]
And so? My photos are still missing...

**Comment by gyllen** [comment]
@zibik How did you upload your photos? What method did you use?

**Comment by zibik** [comment]
I was uploading photos directly from my Android device. My username is: zibi-osm... I gave my username in link in this issue...

**Comment by gyllen** [comment]
Thx, what device are you using and what version of the app?

**Comment by zibik** [comment]
I was using two devices: on August 23 I was using LG-E460; on August 27 I was using Goclever Quantum 4. Version of app: always latest from Google Play

**Comment by gyllen** [comment]
@zibik you are right we have no images registred from you during this days. No one else have lost images though. So lets solve this.

Have you maybe been logged in as another user?

If not can you try to take some images with your phone and upload them today?

**Comment by zibik** [comment]
I don't have another account. I have only one: zibi-osm.
What about 16 photos with status "still processing" since August 23 on my account? Why are "still processing" so long?

I uploaded some new photos today and this upload looks fine.

**Comment by zibik** [comment]
I uploaded some photos today (Sep 10) with success from android app, but these pictures are invisible on my profile. I don't know why :-(

I made backup of sequence before uploading: http://zibi.openstreetmap.org.pl/temp/2015_09_10_11_51_38_383.zip - maybe it will be helpful.

**Comment by gyllen** [comment]
@zibik Just saw your email, sorry for not getting back earlier. Are you still missing the images from sept 10?

**Comment by gyllen** [comment]
@peterneubauer We might need to take a closer look at these images, @zibik claims that he uploaded from the android app but never seen the images :(

**Comment by zibik** [comment]
Yes - these photos are still missing. But I know why now - these pictures (teken by Goclever Quantum 4) doesn't have no location tags in EXIF. I think that is a bug in Mapillary app.

**Comment by gyllen** [comment]
@zibik Damn!! Yes that will make our parser reject them. I know that @peterneubauer (among many other things @peterneubauer creates the Andriod app) has had problems with GPS access to certain andriod devices.

He has a tough job though, there are 1000s of devices out there and not all of them are following the correct specs. Im reassigning this ticket. Sorry for the trouble @zibik and I hope you will keep on uploading with working phones.

**Comment by peterneubauer** [comment]
downloading and checking out the images ...

**Comment by polarbearing** [comment]
could that be related to #1387? However @zibik's pictures have neither regular EXIF-location, nor any Mapillary tags in the EXIF data.

**Comment by peterneubauer** [comment]
So, We don't write the EXIF gps location into the EXIF, the camera does (or does not) instead, we write additionally  the ImageDescription tag. What app version have you been using? Can you make some example shots and get me the logs via the main menu in the apps? The ImageDescription tag is also missing in these images ...

**Comment by peterneubauer** [comment]
closing this, please try to use the newer app versions coming out, they will be more stable.
