### ISSUE TITLE
Webuploader with split and duplicate removal

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1331]
This issue is inspired by the post by DaCor at http://forum.mapillary.io/t/thoughts-or-experiences-with-action-cameras/77/14 at reply by @jesolem and another post regarding action cams without GPS.

The web uploader should do a lot more, that users do with external programs and scripts. Doing Mapillary with an action cam should not just be for GIS or OSM geeks.
- Split into sequenzes - they ar ea nice fall back when the 3D model cannot help.
- Remove duplicates, like the remove-duplicates.py script. It lets you run the action cam e.g. in a red light or just pictures taken too close together.
- Geotag - allow for several gpx files (and other formas) to be uploadet with the images and do it on the servers. Allow for an easy way to correct time, e.g. upload an image of the GPS units clock and enter what the clock says.
- More? Perhaps calculate direction?

I have not tried the web uploader, but I have tried other webuploaders. Make sure you test it with at least 10.000 images and bad internet connections. Many will fail at far less images than that.

**Comment by jesolem** [comment]
Good suggestions. We'll look into what is feasible next time we get to work on the uploader.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
