### ISSUE TITLE
GET http://a.mapillary.com/v2/search/im/randomselected returns only one image

### ISSUE THREAD

**Issue by elopio** [mapillary/mapillary_issues#1332]
On API v2, https://a.mapillary.com/#get-searchimrandomselected
Calling this method returns only one image. It would be nice if it allows limit and pagination, to get more than one with a single call.

**Comment by gyllen** [comment]
I selects from a very small dataset too. How would you like the API to look?

**Comment by elopio** [comment]
Just like https://a.mapillary.com/#get-searchs, with limit and page on the request, and more on the response.

**Comment by gyllen** [comment]
Add random to new API

**Comment by gyllen** [comment]
`v2` is no longer in use. `v3` does not have the random feature though. Open a thread in https://forum.mapillary.com/ is you are still interested.
