### ISSUE TITLE
arrow rearward...

### ISSUE THREAD

**Issue by artGuard** [mapillary/mapillary_issues#1333]
hello,
 how to fix it?
arrow rearward this sequence:
http://www.mapillary.com/map/im/UUxe4ftqs8Y8esPrDVKHrQ/photo

**Comment by jesolem** [comment]
@artGuard What is the problem? Looks good to me. 

(great sequence by the way!)

**Comment by artGuard** [comment]
@jesolem
link (time 11:01:50 AM)
push "forward" arrow (keyboard or picture) => load previous image (time 11:01:38 AM)
next 10 steps (push forward arrow) - move to previous image ...
after
next (11 or 12) push "forward" => load next image...
and next X steps (push "forward" arrow) move forward...

**Comment by jesolem** [comment]
You mean that "move forward" takes you to a photo taken earlier?

**Comment by artGuard** [comment]
yes

**Comment by jesolem** [comment]
I see it now, was hard to detect because the long gaps. Forward arrow moves backwards. Thanks @artGuard will let @ybkuang look at this.

**Comment by ybkuang** [comment]
@pau, can you help take a look at SfM here http://www.mapillary.com/map/im/wXzjsWRig74E5RqointCAg/photo

**Comment by paulinus** [comment]
Compass angle is off after SfM. Current SfM version should fix that. I'm rerunning SfM for that sequence.

**Comment by paulinus** [comment]
Compass angles got fixed after the rerun letting them to the original values.
