### ISSUE TITLE
Pictures editor: handles do not appear any longer

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1334]
I am trying to edit a sequence to fix the location and orientation of the pictures it contains.
Since this morning or yesterday, handles do no longer appear, so I cannot proceed:
![image](https://cloud.githubusercontent.com/assets/12934696/9561082/ffaff63e-4e36-11e5-8f6d-049875e2bc8d.png)

**Comment by jesolem** [comment]
We're having some problems this morning (always on a Saturday!). Check back in later.

**Comment by peterneubauer** [comment]
Working now, closing.
