### ISSUE TITLE
Website looks down

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1335]
* I was suddently logged out a couple of minutes ago, without asking.
Now that I try to log in again, I receive a message saying "we failed to log you in".

* I'm trying to access to a sequence: http://www.mapillary.com/map/im/-LGdSLFwmhr_SdigrTV8nQ
This leads me to a blank page with just a message saying "An unhandled lowlevel error occured. The application logs may have details."

Not sure but this might be the cause of https://github.com/mapillary/mapillary_issues/issues/1334

**Comment by thoschu96** [comment]
login into my account is not working.. seems the database went down

**Comment by de-vries** [comment]
same here, can't log in and profile pages won't load.

**Comment by jesolem** [comment]
Sorry about this, we're investigating.

**Comment by shlublu** [comment]
How to say...

https://www.youtube.com/watch?v=pWa0dZMHYeE&s#t=0m12s

**Comment by shlublu** [comment]
Ok, it seems to be back now. Maybe we can close this as it doesn't seem to be the same issue.
