### ISSUE TITLE
not enable blur request...

### ISSUE THREAD

**Issue by artGuard** [mapillary/mapillary_issues#1337]
blur button not active:
http://www.mapillary.com/map/im/mykIsEOLNE_480WsWnVqeQ/photo
problem in wide photo?

too next sequence:
http://www.mapillary.com/map/im/RM0UA1umf-5_Te8UGaiuKQ/photo

**Comment by richlv** [comment]
blur controls were available for me in that image - i guess this issue can be closed ?

**Comment by artGuard** [comment]
ok
