### ISSUE TITLE
Sequence that jumps back

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1338]
If I go to http://www.mapillary.com/map/im/eT-hqeO2y2RZqWbYRGAJBw/photo and just press the arrow up key, the sequence jumps back and looks over the same 100-200 meters forever.

**Comment by simonmikkelsen** [comment]
It also jumps here: http://www.mapillary.com/map/im/Qetwx3N8X95Ha_UeBKQ79A/photo

**Comment by simonmikkelsen** [comment]
From this image it jumps the next two times: http://www.mapillary.com/map/im/YryIETZgZGsuSsINOwKYFw/photo

**Comment by filipca** [comment]
To me it also happens sometimes.  That is why I would prefer my action cam to have an interval of 1,5 seconds instead of 1 or 2 seconds.

**Comment by simonmikkelsen** [comment]
This one is also in the category of funny jumps:
http://www.mapillary.com/map/im/fUegqf1WQL6tfNFFhcqODQ/photo
Press the left key and the sequence jumps a long way forward. Also, if you press back there is actually no forward arrow, but on the keyboard it goes forward. And when you press right it jumps back.

I have no idea if this is bad data or an error, but not a good user experience.

**Comment by oscarlorentzon** [comment]
Related to SfM issues in #1247 and #1278

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
