### ISSUE TITLE
Impossible to edit traffic signs

### ISSUE THREAD

**Issue by pgiraud** [mapillary/mapillary_issues#1339]
In this photo page, I'm unable to edit the traffic signs.
http://www.mapillary.com/map/im/yQ7QMIDNr4Z3qJwBnUHTlA/photo

If I look at the javascript console, I first get an error with "Error: CurrentUser.info.oauth is undefined" in mapapp-xxxxxx.js.
Then when I try to publish the traffic sign edits, I get a 400 error on a "version" service.

This happens both on Chrome 44 and Firefox 40 on an Ubuntu box.

Please ask me if you need a more detailed stack trace.

**Comment by ybkuang** [comment]
@pgiraud This is because the image has not been processed (traffic sign detection). We will add a notification on the page for this. Once the images has been processed, you will able to edit. We are still catching up on the processing after we did an update on the detectors. Sorry about the delay.

**Comment by pgiraud** [comment]
I'm not sure we're talking about the same issue.
I already saw once or twice a message telling me that the image was not processed which prevented me from adding traffic sign manually.
It didn't happen this time on this photo. Instead I got several error messages in the javascript console.

**Comment by ybkuang** [comment]
Can you try logging out and in again?

**Comment by pgiraud** [comment]
I've tried already. Unsuccessfully.

**Comment by ybkuang** [comment]
@pgiraud OK. Thanks. @gyllen can you take a look at this? it seems oauth-related.

**Comment by gyllen** [comment]
@pgiraud Can you provide me with a detailed stack trace?

**Comment by pgiraud** [comment]
Looks like the error disappeared.
I get other errors in the console but they don't prevent me from editing the signs.
