### ISSUE TITLE
Hidden Track Does Not Hide

### ISSUE THREAD

**Issue by chrisom** [mapillary/mapillary_issues#134]
I've deleted several tracks due to bad image quality. Even is it not possible to see the fotos taken - track is still shown in map.
Example: Track CLOSE  to this one: http://www.mapillary.com/map/im/FTeq4YuuZvVdpVOoUvRRNw in "Dr.-Mack-Str."

**Comment by gyllen** [comment]
This issue should be fixed. Please reopen if not.
