### ISSUE TITLE
How to create a sequence uuid with add_mapillary_tag_from_exif.py

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1340]
Hello,
I tried the add_mapillary_tag_from_exif.py script to  not have problems in case of interrupted upload.

If I run this script on a folder without an uuid on the command line, it seems it creates a different uuid for each pictures.
I don't think it's the way it should work. It should be one folder -> 1 sequence -> 1 uuid
Am i right ?

If I'm correct, how to generate an unique uuid for an entire folder ?

**Comment by peterneubauer** [comment]
You should afterwards run the https://github.com/mapillary/mapillary_tools/blob/master/python/convert_each_folder_into_one_sequence.py, see https://gist.github.com/peterneubauer/288633b8ae0358fa53ae for a full walk through

**Comment by Stefal** [comment]
I'm not a real script guy, but if I understand correctly convert_each_folder_into_one_sequence.py, I don't need to run add_mapillary_tag_from_exif.py before, as this script is called directly from convert_.....py

**Comment by peterneubauer** [comment]
Yes,
that should be correct.
