### ISSUE TITLE
Pictures uploaded 1 week ago are unseen

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1341]
I uploaded some pictures a week ago.
I see the upload on my activity page, but when I click on it, i'm forwarded to another sequence.
This is the link on my activity page : 
http://www.mapillary.com/map/s/JFetykAK79Bb8rcwf4-ayQ

And I don't see any picture in this area : 
http://www.mapillary.com/map/search/46.9679420397741/46.97155233175744/-1.4449913385200261/-1.4386656682556236

**Comment by gyllen** [comment]
Looks like all of these images are availble on new web. And it looks great too
