### ISSUE TITLE
Shaky conditions result in lots of sequences being created

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1342]
See http://www.mapillary.com/map/im/SKjTyMejw5RYCbRKbgxGng and surrounding sequences.
Noticed this clearly yesterday with a bad phone mount setup, but I have glimpsed that issue other times.

When there's a lot of shaking, the app will very often start a new sequence when it finally manages to take a photo. Maybe this interacts with the "minimum distance to start a new sequence" setting, I'm not sure. But the fact that one or more photos could not be taken shouldn't count as an opportunity to cut a long sequence in two.

**Comment by peterneubauer** [comment]
Well,according to the GPS the images are further than 300m apart so it doesn't make sense to have them in the same sequences even if that would be a logical thing. Chance of overlap is minimal, and going forward these images, even from different sequences, will be accessible in the navigation. Not sure how to make this better? Try playing with the minimum distance setting to increase this?

**Comment by vincentdephily** [comment]
I read through it again and it makes sense now. Yes, sounds like raising the value would work around my problem. How will that interact with server-side splitting in #1316 ? I suspect #1135 would also help in getting more sucessful photos despite the shaking.

That said, I think my confusion was partly due to the phrasing of the option. "New sequence min distance" sounds like a condition to prevent starting a new sequence even if requested, and I quickly forgot about it since it didn't seem to concern me. Now I understand that this was the wrong interpretation, but it's ambiguous. What about "max distance before new sequence" instead, does that sound less ambiguous ?

Closing this bug, but maybe another one should be opened for the phrasing of the option.
