### ISSUE TITLE
guess about licence plate blurring from user input

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1343]
when submitting improved blur requests, one has to draw a rectangle around licence plates.
maybe a new mode can be added. in this mode, user would just click inside the licence plate, and it would try to auto-guess the bounds of it. this mode could be the default. if the guess is correct, good. if not, user could adjust the bounds similar to how rectangle selection works in gimp.
it would simplify blur requests and allow to optimise the algorithm, hopefully.

**Comment by jesolem** [comment]
Depends on what intelligence needs to be done in the browser for this to work. @paulinus or @ybkuang may have ideas.

**Comment by richlv** [comment]
it could be serverside - client sends coords for the click, serverside does the calc & sends back the bounds. whatever works functionally & fast enough

**Comment by ybkuang** [comment]
@richlv Good suggestion. @paulinus and I will give some thoughts on this!

**Comment by ybkuang** [comment]
@richlv It is nice idea to have simple supervision/feedback like a simple click. However, implementing will requires further research from our side. Given that the current blurring has been improved a lot with the recent release, I will mark this as an idea and revisit later. Thanks for the suggestion.
