### ISSUE TITLE
don't wrap blur buttons in two rows

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1344]
currently blur buttons are in one row at first (disabled "request blurring" and enabled "clear all blurs & request". if a blur change is made, button "discard blurs" appears. this shifts "clear all blurs & request" right below "request blurring".

this is bad, because ui elements change position, and because requesting specific blurs & clearing them all are now at the left hand side right above/below one another. makes it too easy to misclick or at least requires user to do extra scan of the new ui situation.

instead, it would be better to show all three buttons right away, with "discard blurs" disabled, same as "request blurring".

it would also be important to fit all 3 buttons in one row. how exactly - maybe labels can be shortened a bit, for example, "clear blurs & request" or so.

**Comment by jesolem** [comment]
For to @knikel to evaluate.

**Comment by richlv** [comment]
while there is no wrapping anymore (yay, thanks :) ), 'discard blurs' still appears only when blurs are made & shifts the position of 'clear all & request' - showing that button in a disabled state right away might be a bit better

**Comment by knikel** [comment]
We've changed the UI, this is not an issue anymore.
