### ISSUE TITLE
Map allign in Firefox 39.0.3 on Mac OS 10.10.5 don't works properly

### ISSUE THREAD

**Issue by lorenzoperone** [mapillary/mapillary_issues#1346]
After I've moved the blue marker in a place the other one move itself.
Take a look here https://youtu.be/-7iZCcv3y88
There is another bugs, in the first part of video you can see I need to load two times the GPX file.
On Chrome  44.0.2403.157 (64-bit) on Mac OS 10.10.5 the first two bug there aren't but when I try to upload the video nothing appears https://youtu.be/0RBcEVJwYMU

**Comment by knikel** [comment]
I'm closing this issue since this is part of `legacy.mapillary.com`. I've pinged @amahon about porting video uploader to `mapillary.com` [here](https://github.com/mapillary/mapillary_issues/issues/2000#issuecomment-291808362).
