### ISSUE TITLE
Mapillary manual upload don't upload photos

### ISSUE THREAD

**Issue by lorenzoperone** [mapillary/mapillary_issues#1347]
After I've selected few images the upload process don't starts.
Look here https://youtu.be/__Q-YEkZXZ8

**Comment by ybkuang** [comment]
@lorenzoperone Try to use the upload link with http for now i.e. http://www.mapillary.com/map/upload/im.
We are looking into a solution for https.

**Comment by gyllen** [comment]
This should now be fixed for https closing
