### ISSUE TITLE
Manual upload stuck for more than a week

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1348]
I manually uploaded a bunch of one-picture sequences a little bit more than a week ago.
All went weel but this one, which seems "stuck": https://www.mapillary.com/map/im/ZTDt4tjzY05ePSmIA5vtNg/photo

It actually appears in my upload page, but I cannot access to the sequence, the viewer doesn't display it. I cannot access to the edit page to fix the orientation either.

**Comment by gyllen** [comment]
@shlublu Was looking into it now and it seems like its placed directly on a geographical border for us. I will keep on investigating.

**Comment by shlublu** [comment]
@gyllen Thanks! It might be a local administrative border (would be surprising though) but definitely not a country border: this is in the middle of Angkor in Cambodia

![image](https://cloud.githubusercontent.com/assets/12934696/9608019/8934526e-50cc-11e5-83c2-7a2927726c67.png)

**Comment by gyllen** [comment]
Works on new web
