### ISSUE TITLE
Is Mapillary racist?

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1349]
Sorry for the click-bait title, but now that I have you attention...

Browsing trough some photos in Africa I noticed that no faces are blurred there. Is blurring turned off in Africa or does the face recognition algorithm just not work on black people?

some examples:
http://www.mapillary.com/map/im/ghI16mW3l1ibnz9AsHKhJA/photo
http://www.mapillary.com/map/im/b6u69XLtmVpI-CSJ_qNggw/photo
http://www.mapillary.com/map/im/9HBN7WPl6KLU5V4xIYrgCA/photo
http://www.mapillary.com/map/im/A2nJ3Mm27P6Wh0nt_rvkOA/photo
http://www.mapillary.com/map/im/ExUCminECkWUybFPZ0Fzkw/photo
http://www.mapillary.com/map/im/3KXHsKhxaTVT5TbsIkeBLg/photo

**Comment by jesolem** [comment]
@de-vries No, Mapillary is not racist. Blurring is on for all photos, globally. 

The face blurring is based on components from the OpenCV face detector and as all detectors they have their weaknesses. We have not researched or tested the limits of the detector but it is possible that some skin tones are less accurate than others. 

In my previous job, I worked on face recognition for a total of 9 years and the work you need to put in to get the last few % of detection quality takes a disproportionally big effort. We don't have the resources or training data to make any major changes to our face blurring at this time but that may change in the future. 

Closing this until that day comes.

**Comment by de-vries** [comment]
> No, Mapillary is not racist. 

I know, I just couldn't resist that joke ;)

Would manually blurring provide you with the necessary training data? if so we could make a community effort of it.

**Comment by shlublu** [comment]
Even if this ticket is closed the question above makes absolute sense. Should training data be needed for blurring - in general - I'm in.

**Comment by jesolem** [comment]
@de-vries @shlublu yes, we can use manual blurs as training data but we need to do some minor architecture changes first so that blurs can have labels like the traffic signs. (e.g. label = "face")

On the roadmap and @gyllen is architecting this. Will go together with labeling and a few other requests people have made. Stay tuned.

**Comment by shlublu** [comment]
:ok_hand:
