### ISSUE TITLE
Self-cancelling, stuck, and duplicate android upload

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1350]
V. 1.39, I have occasional the issue that the upload cancels itself without user intervention. It immediately resumes the upload with the remaining pictures, so the only visible effect is that the upload counter is reset to the number of the remaining images, and it seems the success-counter in the log gets wrong (ending with one less). 

A log excerpt here, I'll send the full one to Peter. 19 pictures were to be uploaded in total:

```
Wed Sep 02 00:06:04 CEST 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 6, total 19
Wed Sep 02 00:06:05 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onSyncCanceled
Wed Sep 02 00:06:05 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - canceling
Wed Sep 02 00:06:05 CEST 2015 : app.mapillary.android.sync.UploadService  - canceling upload ...
Wed Sep 02 00:06:05 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - cancelling, cancelled=true
Wed Sep 02 00:06:05 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - ERROR: error uploading - Socket closed
...
Wed Sep 02 00:06:06 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onPerformSync for account[...], done.
Wed Sep 02 00:06:06 CEST 2015 : app.mapillary.android.sync.ImageUploadSynchService  - initializing
...
Wed Sep 02 00:06:08 CEST 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 0, total 13
...
Wed Sep 02 00:13:44 CEST 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 12, total 13
Wed Sep 02 00:13:45 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - upload status: 204
Wed Sep 02 00:13:45 CEST 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Wed Sep 02 00:13:45 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onPerformSync for account[...], done.
Wed Sep 02 00:13:45 CEST 2015 : app.mapillary.android.sync.UploadService  - Upload done, success.
```

```
grep 'upload status: 204' mapi.139.upload-sync-cancelling.txt | wc -l
      19
```

**Comment by polarbearing** [comment]
The first picture uploaded after the resume was already uploaded before the self-cancellation, and has uploaded twice, see below. The dup pictures have received different image keys on the server.
```
Wed Sep 02 00:03:10 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - Uploading pic /storage/sdcard0/mapillary/2015_09_01_11_33_25_859/2015_09_01_11_34_54_472.jpg (2 mb)to http://mapillary.uploads.images.s3.amazonaws.com/
...
and later
...
Wed Sep 02 00:06:07 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - Uploading pic /storage/sdcard0/mapillary/2015_09_01_11_33_25_859/2015_09_01_11_34_54_472.jpg (2 mb)to http://mapillary.uploads.images.s3.amazonaws.com/
```

**Comment by peterneubauer** [comment]
mmh,
it seems the upload was cancelled just before the app got a 204 back from the amazon upload, thus the image was not locally deleted and uploaded in the next run another time. This is correct behavior from the apps point of view, but we probably should have de-duping on the server side to filter these out @gyllen .

**Comment by polarbearing** [comment]
Could the cancellation have been triggered from the server?

**Comment by polarbearing** [comment]
the self-cancelling sync is not solved, can we re-open the ticket?

As said, this is not a cancellation by the user, it is self-cancelled within the app!

Had a short upload from 1.42 today with two cancellations, and probably some duplicates again. Log on the way.

**Comment by polarbearing** [comment]
the self-cancelling sync is not solved in 1.43, can we re-open the ticket?

Last upload I spotted that the notification announced it would now wait for 1 hour for retrying. Fortunately, it already retried after a few seconds. 

So far the self-cancelling happened always in an early phase of the upload (ca 5-15 pictures), and so far only once within one upload.

**Comment by polarbearing** [comment]
Funny thing last night, upload of 302 pics was finished successfully, however the empty sequence folders were not removed. Upload started again and finished soon with "you uploaded 0 images" notification. 

```
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.sync.UploadService$SendFileTask[3]  - upload status: 204 for /storage/sdcard0/mapillary/###
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onPerformSync for account[###], done.
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.sync.ImageUploadSynchService  - initializing
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onPerformSync for account[###], manualSync true
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - Cell sync pref: false
Fri Oct 02 03:08:09 CEST 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
HERE IT STARTS AGAIN:
Fri Oct 02 03:08:10 CEST 2015 : app.mapillary.android.sync.UploadService  - startUpload
Fri Oct 02 03:08:10 CEST 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Fri Oct 02 03:08:10 CEST 2015 : app.mapillary.android.sync.MapillaryUploadSyncAdapter  - onPerformSync for account[###], done.
Fri Oct 02 03:08:10 CEST 2015 : app.mapillary.android.sync.Thumbs  - saving thumb to /storage/sdcard0/thumbs/###
Fri Oct 02 03:08:17 CEST 2015 : app.mapillary.android.sync.UploadService  - Upload done, success.
```

**Comment by polarbearing** [comment]
In an upload session last night with 1.59 there was both a self-cancel, and a frozen upload. No particular explanations found in the log for both.

**Comment by peterneubauer** [comment]
1.59 is kinda unstable with these background bugs that were fixed. What about 1.61?

**Comment by polarbearing** [comment]
1.59 was installed for the crash regression test. Just the frozen upload was new so I mentioned it. 
Just tested the 1.61 from the morning drive, and I was interested if the self-cancel would only happen on my slow home upload only. Result is no, it also happened on a fast university network upload.

**Comment by peterneubauer** [comment]
Uh,
would love the log for that, maybe I can see it ...

**Comment by peterneubauer** [comment]
Mmh,
from what I can see, the uploads are just taking a lot of time (a few minutes for 1mb images), and are as you say stopping at certain times. No exceptions, so I'm not sure if there might be some throttling in the network or some phone HTTP upload problems. I don't want to implement a custom backoff-and restart algo since that is already what the synch framework in Android does quite well, we are basically doing something like http://developer.android.com/training/sync-adapters/running-sync-adapter.html

On the 1.61 fast-network-uni log I see that all 41 images got uploaded pretty fast? Was there any freeze or crash?

````
   Thu Nov 26 15:32:35 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 38, total 41
Thu Nov 26 15:32:36 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 38, total 41
Thu Nov 26 15:32:37 CET 2015 : app.mapillary.android.sync.UploadService$SendFileTask[2]  - uploadRequested status: 204 for /storage/sdcard0/mapillary/2015_11_26_09_53_47_515/2015_11_26_09_53_48_289.jpg
Thu Nov 26 15:32:37 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 38, total 41
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.sync.UploadService$SendFileTask[1]  - uploadRequested status: 204 for /storage/sdcard0/mapillary/2015_11_26_09_53_47_515/2015_11_26_09_53_56_664.jpg
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.sync.UploadService$SendFileTask[0]  - uploadRequested status: 204 for /storage/sdcard0/mapillary/2015_11_26_09_53_47_515/2015_11_26_09_53_52_434.jpg
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.service.StorageUtils  - getDefaultImageStoragePath- /storage/sdcard0/mapillary
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.sync.UploadService  - Upload done, success.
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.sync.UploadService  - Upload done, success.
Thu Nov 26 15:32:38 CET 2015 : app.mapillary.android.sync.UploadService  - Upload done, success.
````

**Comment by polarbearing** [comment]
The 1.61 in a fast upstream network was "total 55" pic originally, there was a self-cancel at the stage when it changes to "total 41". 

The only freeze I had experienced was in the other, the 1.59 log.

**Comment by polarbearing** [comment]
Stuck upload in 1.61. Fast network, 122 pic to upload.  28x Status 204 in the log, when I see in the notification that we are “uploading 32 of 122”, which is 28 + the 4 parallel uploads, but it does not continue.

The app itself does not recognise that there is an upload going on, and offers me to upload the remaining 94 pictures. 
I close the app. The stuck notification is still at “32 of 122”. 
I open the app, it offers to upload the remaining 94 pics, I say do so, and they go through. 

Log on the way.

**Comment by HolgerJeromin** [comment]
perhaps the phone is just killing the background process for resource shortage

**Comment by peterneubauer** [comment]
Yes,
that might very well be it. The sync process is following the Android sync
framework and possibly might be aborted, before it tries again later. The
hard thing is to keep track of that you requested manual upload after the
first abort and to retry even though auto-upload is disabled. Will think
about this a bit.

Thanks for the logs!

**Comment by polarbearing** [comment]
Tested 1.64-test version today, stuck again. 

Uploading 81 pic, the 'failed' count jumps from 0 to 1 at pic 36, however we only have status 204 in the log. 

Upload continues until we have 72 successes, when the log stops. The display shows that the app attempts to upload the next 4 pics ("uploading 76"), but these attemps are not seen in the log. When I touch the notification the app restarts and find the remaining 9 pics, but does not start them. I can request a new upload. 

In total 81x status 204, no other status. 

Full log by email.

**Comment by polarbearing** [comment]
Uploading with 1.67, things get worse. The process was stuck several times. I observed that often the clock display in the status bar gets stuck as well when the upload freezes. (Not sure if that was the case in previous versions)

286 to upload, until
Sat Dec 12 00:13:33 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 73, total 286
Now comes a 3 min silence in the log, and it goes on by itself:
Sat Dec 12 00:16:46 CET 2015 : app.mapillary.android.service.StorageUtils  - found: /mnt/asec
213 to upload. This goes on until
Sat Dec 12 00:46:46 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 87, total 213
when the upload freezes and does not recover. At 0:56, several attempts to restart the app manually, while the old stuck notification bar hangs around and does not close. 
Clock display frozen from 0:47 - 1:04
You see the same batch of 4 pictures attempting to upload between 0:56 and 1:12 a couple of times. 
From 1:12 until 1:42 we make some progress.
Sat Dec 12 01:42:24 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 93, total 126
At this stage we have a self-cancel, the upload resumes  with 33 pictures remaining:
Sat Dec 12 01:42:24 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 93, total 126
Next self-cancel happens at 1:51, with 9 pictures remaining:
Sat Dec 12 01:51:20 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 0, total 9
however that gets stuck with a frozen clock at 
Sat Dec 12 01:51:52 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping. failed: 0, success 0, total 9
then comes a manual restart:
Sat Dec 12 02:45:44 CET 2015 : app.mapillary.android.activity.Utils  - WiFi: true, Ethernet: false
and the remaining 8 pictures upload. 

Full log is on the way but I prefer to sleep at night and not babysit those crashing uploads :-(

**Comment by polarbearing** [comment]
There were 286 pictures originally, and I received 2 upload-emails over 279 and 9, thus in total 288. The upload-on-the-map also counts 288. 

Thus we have at least 2 duplicates (or more duplicates and some losses, but for that I have no effective way to check)

**Comment by polarbearing** [comment]
Still no progress in this issue. Testing 2.20 today, I had an upload of 219 pictures, which was self-cancelling and continuing 2 times, and once stuck, so I had to restart manually. 

In the confirmation mail, I got 161+59 pictures confirmed, thus 220 in total, thus we have another duplicate.

**Comment by peterneubauer** [comment]
@polarbearing we need to do some more debugging on this. It seems or some reason the Android sync system is killing the upload service - maybe because of lack of progress on the reported upload statistics (this is how Android decides retries and back-off). 

Are you able to debug Android apps? In that case we could give you access to the repo. Otherwise, I can insert more tracing to track this down.

**Comment by ovivoda** [comment]
New upload process should be much smoother in the next app release. Please open this if you still have problems with the upload.
