### ISSUE TITLE
sequence frequence slider in the settings is buggy

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1352]
I have configured and see 2sec in the settings. 
Clicking on it it shows 1sec. Same is true for all numbers. The slider defaults to "number-1"

1.40 version code 140 on android

**Comment by peterneubauer** [comment]
Pushing fix in v 1.61, feel free to close if it works.

**Comment by polarbearing** [comment]
Seems to work correctly in 1.61, we also have the 0 sec setting back.
