### ISSUE TITLE
US 40 mph speed limit sign missing from web viewer

### ISSUE THREAD

**Issue by kreed** [mapillary/mapillary_issues#1353]
It isn't available to pick in the sidebar, and it shows up as a blank sign on photos where it was automatically detected.
http://www.mapillary.com/map/im/rG1QurkfXRVsRrYLi-VN8w/photo

**Comment by jesolem** [comment]
Maybe missing in Traffico, @knikel can check

**Comment by knikel** [comment]
@ybkuang seems that US 40 MPH is not in the  _available signs_ list. It's missing in Traffico too, (I'll fix that).

**Comment by ToeBee** [comment]
Ping on this. The missing 40 MPH sign has been annoying me lately. I've been tagging them as unknown signs in the hopes that there would be a filter for unknown signs in the future that would let me go back and find them easily once the 40 MPH sign gets added.

**Comment by drkludge** [comment]
US 40 MPH is a problem in Arizona too.  Many of the cities have a top speed limit of 40 MPH.  I am still puzzled by much of the interface.  It doesn't seem to be working for me whereas I see other contributors with all kinds of sign tags.  I wasn't sure if this was a US only problem.  Perhaps a look at the MUTCD would help.  I'd also want to have Mapillary detect the green and blue informational signs too.
http://mutcd.fhwa.dot.gov/shse/shs_2004_2012_sup.pdf

**Comment by ybkuang** [comment]
@ToeBee @kreed @drkludge We will fix the US 40 MPH. It is probably a miss somewhere in the backend.

@drkludge Improving the tagging UI in general is in our roadmap. On the other hand, we will try to cover as much signs as possible in the future. One of the difficulties is the availability of training data. We have some ideas on that but it will take some time for us to get there. Please stay tuned!

**Comment by ToeBee** [comment]
Ping. Just ran into another 40 MPH sign while reviewing a new sequence :)

**Comment by knikel** [comment]
This is fixed, all the signs that we detect are in https://github.com/mapillary/mapillary_sprite_source now, based on the contents of that repository we generate list of available signs.

**Comment by ToeBee** [comment]
Now you just need to re-enable sign detection and editing so that we can see the fix in action! :)

**Comment by gyllen** [comment]
@ToeBee Sign detection is running in many areas now and you can turn it on in the filters view. Hold tight for editing :) (thats all I can say for now)
