### ISSUE TITLE
video sequence (Garmin Virb XE) is not correctly positioned in map

### ISSUE THREAD

**Issue by lorenzoperone** [mapillary/mapillary_issues#1355]
Hi,
I made a test with a short video taken by a Virb XE. I've aligned the video with the GPX track, but the frames extracted are placed in the wrong place (over 500 meter from the target).
I've tried to hide the sequence (Sequence key: kz6Fx_qNToe4LwismVeGng) but the system notified me that the sequence include more than 100 images (there are 201 images) so I can't hide the sequence.

**Comment by lorenzoperone** [comment]
I've a doubt :)
I'm doing some test using the Virb, the first are only preliminary tests, so the images are quite bad, is there a beta platform so I don't spoil the main one?
Thanks.
l.

**Comment by lorenzoperone** [comment]
Hi,
my sequence (Sequence key: kz6Fx_qNToe4LwismVeGng) seems to be even viewable.
I think it could be better to erase or make not visible all the sequence.

**Comment by ybkuang** [comment]
@lorenzoperone We can hide the sequence for you. @gyllen can you help hide the sequence for @lorenzoperone?

**Comment by lorenzoperone** [comment]
Thanks.

**Comment by gyllen** [comment]
Removed sequence allow a couple of hours for it to disappear from caches
