### ISSUE TITLE
traffic sign images broken in the game

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1356]
see the screenshot. this makes the traffic sign game useless.
might be related to issue #1328
if i go to the image in the editor, the signs are there.
i can't link to the game image, but in the viewer it's this : http://www.mapillary.com/map/im/4yeUUbqivMSVOi-FUWyGVg/photo
![trafsigns](https://cloud.githubusercontent.com/assets/112888/9666792/eaf7811e-5280-11e5-9df9-0597f7a54eae.png)

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
