### ISSUE TITLE
Strange display of some non-4/3 sequences

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1358]
It is not the first time I upload non 4/3 pictures, but surprisingly these two sequences did...that: 
- http://www.mapillary.com/map/im/PONDXXXt-0AKVANzQc-0Mg/photo
- http://www.mapillary.com/map/im/IbNwxPeoqC6rHJH4bqlGxQ/photo

It's not always the case though, these ones work, and others too:
- http://www.mapillary.com/map/im/VlHwvrUGYM3TAMZhuSDxcA/photo
- http://www.mapillary.com/map/im/t3cCfunVEYF1YHGE1kClPA/photo

I thought 16/9 (provided this is 16/9, is it?) was supported even if not recommended. But I can't remember where I got that from... is it supported?

**Comment by oscarlorentzon** [comment]
You are correct @shlublu , 16/9 is supported and should work as in your last two two examples where they are rendered correctly. Will look into the faulty ones. 

Thanks for reporting!

**Comment by oscarlorentzon** [comment]
Related to the aspect ratio problems in #1233 .

**Comment by paulinus** [comment]
Taking 16/9 and 4/3 at the same place with the same camera was getting the system confused. We fixed that. The images you are referencing look good now.

We will need to trigger an update for any other sequence you see with the same problem.

Thanks for reporting!

**Comment by shlublu** [comment]
Oh, great, thanks!
