### ISSUE TITLE
3G/4G upload on the iPhone not working

### ISSUE THREAD

**Issue by tas50** [mapillary/mapillary_issues#1360]
I'm running the latest iOS 9 beta on my iPhone 6.  I've enabled the 3G/4G upload, but my phone refuses to upload when I'm on LTE.

**Comment by millenbop** [comment]
Hi!

Do you get an error message or just nothing happens?

**Comment by millenbop** [comment]
@tas50 still having this problem? I just looked into this on iPhone6 and iOS9 and it works just fine for me.

If you still have problems, do you get an error popup? Or does it "start" but there is no progress? are you using the latest version of the app?

**Comment by tagg** [comment]
Same problem here. iPhone 6, IOS8 at the time (19-sep), carrier Telia DK. Enabled the "Allow upload via 3G/4G" setting, but was still getting a popup saying "Cannot upload via 3G/4G" when trying. I've since then upgraded to IOS9, and have not tried uploading over LTE. I'll verify later today.

**Comment by millenbop** [comment]
@tagg are you using the latest version of the app?

**Comment by tagg** [comment]
@millenbop Yes, I had updated the app to version 4.0 on 18-sep, the day before.

**Comment by millenbop** [comment]
Thanks @tagg. It's this error you are referring to, right?

![img_0495](https://cloud.githubusercontent.com/assets/12835674/10045212/3104f2ce-6201-11e5-8010-87f2e43a0f89.PNG)

**Comment by tas50** [comment]
Still having the problem on 9.1 beta now with the latest app on my iPhone 6 with T-Mobile US LTE

**Comment by tagg** [comment]
@millenbop This is from memory, but I believe so.

**Comment by millenbop** [comment]
Ok, trying to figure out if it's our popup showing or it's something the system is showing. I cannot reproduce this error so grasping for straws here :)

Could you try switching the setting on/off and trying again? Shouldn't be needed, but if possible, uninstall and reinstall the app and see if that helps somehow. Please make sure you upload any photos before you delete the app though!

**Comment by tas50** [comment]
It might help to know that if you’re on Wifi and you start the upload, and then wifi drops to LTE, the upload will stop after several images are uploaded.  It’s as if it once again realizes it doesn’t have Wifi and can’t upload even though the 3G/4G upload is enabled.

-Tim

**Comment by tagg** [comment]
So: iPhone 6, IOS9, Mapillary app 4.0, carrier Telia DK, disabled WiFi in iPhone settings, data over 3G - Safari works fine. In Mapillary App, enable 'Allow upload via 3G/4G' in Settings. Select one sequence, select Upload. Resulting in popup, 'Upload needs WiFi'.

**Comment by millenbop** [comment]
Is it possible for you to remove the app and install it again and see if that helps? Somehow the setting is not saved and it puzzles me why it isn't.

**Comment by tagg** [comment]
Deleted app, and reinstalled. Same problem.

**Comment by millenbop** [comment]
Thanks @tagg and @tas50 

I cannot reproduce it on any of my devices (iPhone 4, iPhone 5 and iPhone 6 with iOS 7, iOS8 and iOS 9) no matter how hard I try. I've also asked everyone here at Mapillary to try it on their iOS devices and it works fine for them to. I have also looked through the code several times now and I cannot find anything that's wrong.

I'm hoping someone else is geting this error and that they can provide some new info so that I can find some kind of common denominator.

**Comment by millenbop** [comment]
A followup question:

If you go to Settings in the app, is the setting saved correctly? 

As in you 
- toggle the setting to ON, 
- go back to your Profile view, 
- and then back into Settings

**Comment by millenbop** [comment]
Ok, I've found the problem! Apparently the bug only exists when you only have one project, so the setting is actually toggling wifi background upload and not 3G upload. I'll fix it and it'll be available in two builds from now (we have in in review right now).

Thanks for notifying us of the bug.
