### ISSUE TITLE
Incomplete list of available traffic signs when editing some pictuers

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1361]
The list of available traffic signs is changing on me depending on which sequence I'm viewing.

I was trying to add a 65 MPH sign to this image but none of the speed limit signs are available for tagging on this picture:
http://www.mapillary.com/map/im/SeXpdvDq7pynQmlh-VZ9cA/photo

This picture on the other hand has a lot more signs available for tagging:
http://www.mapillary.com/map/im/pQPdH_eRfXkoc67mtb93Gg/photo

The first picture is missing more than just speed limit signs too. It looks like it is maybe displaying an older set of traffic signs.

**Comment by knikel** [comment]
It must've been a different *or_package*, both photos have the same list of signs available to tag now. Probably @ybkuang can share more information on that matter.
