### ISSUE TITLE
Only "?" instead of list of possible traffic signs

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#1363]
I see only '?' in list of possible signs for [this](http://www.mapillary.com/map/im/gIonhR2UIWpJdKgj-Jp4EQ/photo) and some other photos: 

![2015-09-06 2 02 30](https://cloud.githubusercontent.com/assets/24191/9701643/dc03d2a4-543b-11e5-84fb-969fc78b2919.png)

**Comment by ybkuang** [comment]
This has been resolved in the new website. Closing.
