### ISSUE TITLE
Mapbox looks broken (happened before)

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1365]
Looks like the Mapbox renderer or tiles provider is encountering issues. I was searching for a precise but unnamed place and got this:
![image](https://cloud.githubusercontent.com/assets/12934696/9710867/d601ffda-553e-11e5-8003-436d0a646fe0.png)

This happened in the past but I couldn't find the ticket to reopen it.

**Comment by knikel** [comment]
@shlublu did you get here from the landing page or from the `/search`?

**Comment by shlublu** [comment]
As I was missing the "explore" page, I went to a random sequence, then clicked "Map", then unzoomed and tried to navigate by sliding the map.

It was broken in two straight from the beginning, but I only lost the colors and details at low zoom levels.

**Comment by knikel** [comment]
Thanks, will investigate that!

**Comment by shlublu** [comment]
Thanks to you actually :)

**Comment by Stalfur** [comment]
I've had this issue before - it seems to be related to viewing image - clicking on Photo and back on Map sometimes fixes it

**Comment by knikel** [comment]
We're doing much better job with maintaining the map size than in the old app. Should not happen again.
