### ISSUE TITLE
Is the change requests approval process on hold?

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1367]
I have some change requests (I would say 20 or so) pending, some of them for weeks. So I'm wondering whether the change requests approval process is currently on hold.

Implied, but best if specified: This would not be a problem *at all* to me :) This is just to organize.

**Comment by AllenGraetz** [comment]
I may be conflating this with something else but I thought they usually got to these within 48 hours because it was a process that purposefully required manual intervention.

**Comment by shlublu** [comment]
Yes @AllenGraetz it usually takes something in between 1 and 5 days. This is why I'm asking, as here my older unresolved one is almost a month old.

**Comment by gyllen** [comment]
We are experiencing problems with change sets, short story is that we have outgrown our old system. A new system is in the works. Sorry for delay.

**Comment by shlublu** [comment]
@gyllen It's ok, thanks for the hard work. Will the change requests be processed eventually or are they lost?

**Comment by gyllen** [comment]
@shlublu Thanks :), All requests are in a big queue, so eventually they will be processed.

**Comment by shlublu** [comment]
There are a few sequences I would like to edit. Would you recommend to wait for the edit process to resume or to edit these sequences right now and have the edit requests queued? 
Actually, I don't know if editing a sequence that already has pending edits works or not.

**Comment by shlublu** [comment]
I finally queued them, I hope it's OK.

**Comment by travel193** [comment]
That's good @shlublu . They will be processed when everything is up and running again.
Thanks!

**Comment by shlublu** [comment]
Hi @travel193 and @gyllen,
Do you have any news on this? I have seen that even the (or some) blur requests are on hold.
Thank you!

**Comment by katrinhumal** [comment]
Hi @shlublu, back on track with the blur requests now so they should be approved.

**Comment by shlublu** [comment]
@katrinhumal That's great, thanks!

**Comment by shlublu** [comment]
Err... may I?

**Comment by gyllen** [comment]
@shlublu Blurs should be approved regularly at the moment

**Comment by shlublu** [comment]
@gyllen Yes, blurs look ok now. I was thinking about the change requests concerning location, orientation, deletions and so on. I must have 30 to 40 of them pending.

**Comment by gyllen** [comment]
Its still in the works, I am reassigning to @peterneubauer he can tell you more about the exact status.

**Comment by peterneubauer** [comment]
So the approval of the new changesets structure is working for location and angle changes. We are at the same time making the notification structure more powerful. I think we can start approving changesets in the next few weeks now, starting with the changes to location and compass angles.

**Comment by shlublu** [comment]
Thanks @peterneubauer and @gyllen, glad to hear that. I'm monitoring my dashboard every day awaiting for this to happen :)

**Comment by peterneubauer** [comment]
Yup,
I'm now testing the API for the new notifications, so we can get the mails out upon approving changesets :)

**Comment by shlublu** [comment]
I didn't receive any email so far, did you start approving old change requests?

**Comment by peterneubauer** [comment]
So,
the process is working - we are right now working on the endpoint to visualize the changeset for your notification mail. Would it be ok to just list it somewhere and point to the images otherwise? That would speed up the process ....

**Comment by shlublu** [comment]
@peterneubauer Yes, at least to me that would be more than OK like that. What concerns me is to have these changes approved as they mostly consist in fixing rough GPS locations and orientations, and hiding bad images (blurred / tilted / etc). The notif helps remembering what it was but having it handsome is not a priority I think.

**Comment by peterneubauer** [comment]
So, we are finalizing the last backend change for the first changesets (location and compass angle changes) to be ready for approval. We need UX of course, but I very soon can start test-approving the first things. @shlublu I might take one of yours :)

**Comment by shlublu** [comment]
(preparing the cake for this ticket's birthday... :p )

**Comment by gyllen** [comment]
@shlublu No need all changesets have now been approved *phew* :)

(closing)

**Comment by shlublu** [comment]
Oooh, that's great ! I checked a few of them and it seems it's all fine. I received no notification and no email though. Well done, congrats and thanks guys!

**Comment by peterneubauer** [comment]
Yeah,
some of the old changesets were acting on deleted images and broke the
feed, so I disabled notifications for them temporarily. Should be all fine
going forward. Really excited that this is finally in place. Thanks for
waiting it out!
