### ISSUE TITLE
[Wikimedia Commons] - Watermarks on contributed images

### ISSUE THREAD

**Issue by ccossio** [mapillary/mapillary_issues#1368]
Omar from Wikimedia Mexico has pointed out some issues with having watermarks on the images on Wikipedia.

These are the guidelines:
https://commons.wikimedia.org/wiki/Commons:Watermarks

Some of the tools that Wikimedia provides so the authors can identify their work:
https://commons.wikimedia.org/wiki/Commons:Enforcing_license_terms#Tools_for_identifying_your_work

**Comment by shlublu** [comment]
My guess is that Mapillary images simply won't go to Wikimedia in that case, they will just be CC images. Unless the author gives WM the original non-watermarked picture, which is no problem in regards to the MP rules.
