### ISSUE TITLE
Unable to view images when zoomed in

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_issues#1370]
To reproduce

Go to http://www.mapillary.com/map/search/48.32820967402722/48.3457791601725/-122.35420513508143/-122.33537965110168

![image](https://cloud.githubusercontent.com/assets/1190866/9749010/f1436590-563d-11e5-855e-95bdf9be7712.png)

Zoom in on the intersection of Dike Rd and Fire Island Rd

![image](https://cloud.githubusercontent.com/assets/1190866/9749023/202545b8-563e-11e5-9b7c-c4c4fa595007.png)

Click on the line (point in red)

The browser issues a request to https://a.mapillary.com/v2/search/im/close2?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&lat=48.34136191945413&lon=-122.34693225736115 which has content of {}, but nothing happens.

Other notes
http://www.mapillary.com/map/search/48.34097002381321/48.34177442243575/-122.34826953025316/-122.3457722716384 does not display the line when opened in a new window

**Comment by knikel** [comment]
@pnorman We had an issue with the search view recently, it should be back to normal now. After a click on a sequence, you'll see a thumbnail of the looked up photo in the bottom left. Thanks for reporting this!
