### ISSUE TITLE
Viewer jumps to picture not nearby or on the same trace

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_issues#1371]
I went to 
http://www.mapillary.com/map/im/ziz34E6Yd4T5DcL_XsVqaw/photo

![image](https://cloud.githubusercontent.com/assets/1190866/9749159/36ae9b8a-563f-11e5-9635-e867b19d1201.png)

This was farther west than I wanted to start mapping, so I panned the map and zoomed in on the roundabout, with the mouse where the cyan dot is

![image](https://cloud.githubusercontent.com/assets/1190866/9749195/7ad17134-563f-11e5-8dbd-99e14c26193f.png)

I zoomed in a bit more and clicked on the cyan dot
![image](https://cloud.githubusercontent.com/assets/1190866/9749215/b9af8a4e-563f-11e5-945b-85d8591a0b14.png)

I then got taken to a trace on the I-5, several screens away.

![image](https://cloud.githubusercontent.com/assets/1190866/9749225/dbd0144a-563f-11e5-9184-1857bb05c287.png)

The map was stuck in Pan mode until I clicked again.

**Comment by simonmikkelsen** [comment]
Very much like #1338 .

**Comment by ToeBee** [comment]
This seems to be related to what zoom level you are viewing the map at. When I hover over the sequence by Call Hall in [this view](https://www.mapillary.com/map/search/39.19519642958468/-96.57990507099782/15.883079954946046) the sequence turns red and I can click on it and bring up the expected picture. But if I [zoom in one step](https://www.mapillary.com/map/search/39.19522703246/-96.5802233659388/16.215319533304463) the sequence no longer highlights on mouseover and if I click I get a picture a few blocks away.

**Comment by knikel** [comment]
This is an issue with approximating data in the vector tiles. In the upcoming update we're using images (as opposed to sequences) for the data layer, therefore interactions will be much more precise.

**Comment by knikel** [comment]
It's possible to precisely select photos at high zoom level now.
