### ISSUE TITLE
web uploader

### ISSUE THREAD

**Issue by JulieMay** [mapillary/mapillary_issues#1372]
I've tried uploading a panorama multiple times. It reaches 100% then nothing happens and the uploader appears as if it is still doing something. If I click on the link for the uploader hanging I'm back to try again. I've double checked the EXIF data.

Is there a max file size I don't know about or something?

**Comment by balooval** [comment]
Some month ago there was a 10Mb size limit (error view in the browser console).

**Comment by ybkuang** [comment]
@JulieMay We have a 20MB file size limit for manual upload right now. How big is your file?

**Comment by gyllen** [comment]
Closing since no answer
