### ISSUE TITLE
I can't change the photo in my Mapillary profile

### ISSUE THREAD

**Issue by cesaregerbino** [mapillary/mapillary_issues#1375]
I've tried to change my profile photo but I can't to do it ... I've tried using both Firefox and Chrome but nothing change ... Here you're a snapshot of my browser console (Chrome Version 42.0.2311.90 m)

![changemapillaryprofile error](https://cloud.githubusercontent.com/assets/4707083/9786964/9b0336b0-57be-11e5-93e8-b46e88931443.PNG)

Thanks!

**Comment by millenbop** [comment]
Referencing mapillary/mapillary_web/#233

**Comment by gyllen** [comment]
Thanks for reporting, this is now #fixed
