### ISSUE TITLE
edit of picture position not possible, load forever

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1376]
Hi!

http://www.mapillary.com/map/e/bw1eRrC18CMDiPvRyPTAyg
If I try to move the mouse to move another picture, it loads the new picture forever and I cannot go on.

OK, it does only happen on some pictures, I cannot tell why. If I hit such a picture, edit is loss.

**Comment by jesolem** [comment]
You mean that the photo navigation loops? Or is this a problem in the editor?

**Comment by echeloni2p** [comment]
Hi

Not a navigation loop. I click on the link, the windows opens, the first picture is loaded. While moving around with mouse in right windows, I hoover over another piucture and in leftern part the picture should be loaded and be shown. Instead the old picture is loaded and the "loading" animation is shown. 
I can move the icons/picture markers around in the right map, and the small pictures are shown in the lower area (and I can save these changes), but in the upper area, the picture is not loaded, not shown, no signs of "hide this image" text...

So a problem with editor/fetching the data from the server.

**Comment by knikel** [comment]
Editor is getting a huge overhaul soon, we're changing underlying technology, so this won't be an issue anymore. Will close when rolled out.

**Comment by gyllen** [comment]
Fixed in new editor
