### ISSUE TITLE
All my photos from last week got in the same sequence

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1378]
I had over 20.000 photos from last week divided over folders per sequence. I used the following folder structure:  `~/Mapillary/Last Week/<weekday>/<sequence number>/`

First I used `convert_each_folder_into_one_sequence.py` on `~/Mapillary/Last Week/`, then I uploaded everything with `upload.py`. Somehow all photo's got the same sequence ID and ended up in [this sequence](http://www.mapillary.com/map/s/u45EuiGvSP1Q8FzLvOirEA).

**Comment by gyllen** [comment]
Hi,

We will check in on this on Monday, right now we are trying to figure out the backend. Since this sequence at the moment put our processing to a complete halt :/

**Comment by gyllen** [comment]
Don't get me wrong user input should never be able to break a system. So this was a good way to find out ;)

**Comment by de-vries** [comment]
oops, I'm sorry to hear that. 

btw, I'm not sure if it is a problem with the script, or that I did something wrong. If I'm can reproduce it I'll let you know.
It would be nice if you can do something like time_split.py to the sequence, but if it is to much work I can re-upload.

**Comment by shlublu** [comment]
Oh, I've just uploaded some pictures before finding this post. The upload worked but the images appear nowhere (not even in the "in process" count). Are they going to be processed later?

**Comment by gyllen** [comment]
@shlublu Its our system thats into a halt. Right now we are catching up though (every action in the system gets stored in a long long queue). Expect your images to be shown in the system within the hour.

**Comment by shlublu** [comment]
Even on Monday that's fine. You guys have a private life :)

**Comment by gyllen** [comment]
@de-vries We would need to do some manual work on your sequence. If you can remember your exact steps we would be able to avoid this in the future.

Hey awesome with uploading 20k images though :), now lets just split them. We will work more in this on Monday though.

**Comment by gyllen** [comment]
@de-vries Not that we will do this manually so you might not get notifications about what going on.

**Comment by de-vries** [comment]
Next time I have such a bulk I'll wait till after the weekend, promise.

**Comment by gyllen** [comment]
@de-vries Haha, nah keep em coming, our job is to handle them

**Comment by de-vries** [comment]
@gyllen My exact steps:

- Copied files from action cam to computer
- The photos come per 1000 in folders named "100MEDIA", "101MEDIA", "102MEDIA" etc. the files are named "FILE0001", "FILE0002", "FILE0003", etc.
 - I used the mass rename function from Thunar file manager to rename files and avoid file name conflicts.
 - Folder "100MEDIA" till "121MEDIA" were in `~/Mapillary/Last Week/`
 - I used time_split.py on `~/Mapillary/Last Week/`
 - I loaded bulks of the folders into JOSM to align the photos with the several GPX files I made last week
 - at the same time I merged some folders time_split.py made, deleted some photos and manualy adjusted some gps data in JOSM.
 - I had all photos with the correct gps info divided over folders per sequence. I used the following folder structure:  `~/Mapillary/Last Week/<weekday>/<sequence number>/`
 - I used `convert_each_folder_into_one_sequence.py` on `~/Mapillary/Last Week/`
 - I used `upload.py` on `~/Mapillary/Last Week/`

note: 
This is the first time I used time_split.py. 
All photos had `MAPSequenceUUID": "056cb7da-43f5-445d-bfb8-b4e72961ef8f"` in the exif image description before upload

**Comment by gyllen** [comment]
The MAPSequenceUUID is probably what got us. How did that get set? @jesolem Im looping in you since you know more about the script.

**Comment by jesolem** [comment]
That one is all @peterneubauer I'm afraid. I have never tried it myself.
https://github.com/mapillary/mapillary_tools/blob/master/python/convert_each_folder_into_one_sequence.py

**Comment by de-vries** [comment]
@gyllen I've just ran time_split.py with a 30sec parameter and it gave nice results

**Comment by gyllen** [comment]
@de-vries Ok lets see what @peterneubauer sais, just to clarify though 20k images is not any problem. The problem is them all beeing the same sequence.

**Comment by de-vries** [comment]
I'm testing something now:
- I've time_split all photos in sequences, without the "folder/subfolder" structure.
- I'm now running `convert_each_folder_into_one_sequence.py`, but is seems all folders still get the same ID (a different one than before though)

**Comment by peterneubauer** [comment]
Mmh, it seems the culprit might be the deeper nesting. The script loops only through the direct Children of a folder I think. You had two levels deep so I think we need to change that. Could you check @de-vries?

**Comment by peterneubauer** [comment]
Mmh then that's a bug, need to investigate...

**Comment by de-vries** [comment]
@peterneubauer check what?

**Comment by de-vries** [comment]
I did another test. 
I made the following folder/subfolder/file structure and put `~/test` trough `convert_each_folder_into_one_sequence.py`
```
~/test
 - a
  - 1
   - photo01.jpg
   - photo02.jpg
  - 2
    - photo03.jpg
    - photo04.jpg
- b
  - 3
   - photo05.jpg
   - photo06.jpg
  - 4
   - photo07.jpg
   - photo08.jpg
```
All the numbered folders got a different sequence ID, so the nesting probably isn't the problem.

**Comment by de-vries** [comment]
I now recall that there was some error in the terminal when I was using `convert_each_folder_into_one_sequence.py` on the photos. 
It was the error from line 137 from `add_mapillary_tag_from_exif.py` and it only appeared when the last 100 or so photo's were processed, so after already most sequences got the same ID. 
I manually checked that those photos had the image-description tag, they had, so I figured all was OK and I started the upload.

**Comment by peterneubauer** [comment]
So, this problem only occurs with a lot of pics in that script?

**Comment by peterneubauer** [comment]
So,
I cleaned up the scripts, now the recursive sequence-per-folder functionality is default in https://github.com/mapillary/mapillary_tools/blob/master/python/add_mapillary_tag_from_exif.py#L23, the  `convert_each_folder_into_one_sequence` is not needed anymore and retired. This should fix your issue. Thanks @de-vries !

**Comment by de-vries** [comment]
great! but there is still that ridiculous long sequence of 20.000 photos spread over 5 days. Can you split that at every gap of 30 seconds? if it's to much trouble, it's okay for me if you delete the sequence. I can re-upload.

**Comment by gyllen** [comment]
@de-vries Its faster for us to do the split than for you us to delete. So let us do the split, it will take a couple of days before we get around to it though

**Comment by de-vries** [comment]
@gyllen no problem. Thanx for all your great work on Mapillary!
