### ISSUE TITLE
Mapillary App goes into an upside-down mode

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1379]
Mapillary v1.42 on Android 5.1.1
Samsung Galaxy Note 4

Yesterday while going around, I noticed that the Mapillary App would often go into an upside-down mode after minor shakes or bumps. The Android bar stays on the top, but the Mapillary text is upside-down. 

Photos are also uploaded upside-down:
https://d1cuyjsrcm0gby.cloudfront.net/UV2jo8EnXk3OOarIQhEgJw/thumb-640.jpg

I have not noticed this behavior before. But the phone recently upgraded both Mapillary and Android, I am not sure which of the upgrades caused this issue. Shaking the phone in the mount can switch it back and forth between normal and upside-down.

**Comment by jrcarlsen** [comment]
Today it continuously switched between upside-down and normal mode, several times per second without any bumps.

Another thing that I have changed recently is using an external Bluetooth GPS, but I don't think that has anything to do with this.

**Comment by jrcarlsen** [comment]
Is there any way for me to fix already uploaded photos? or somehow mark them so they can get fixed in the future?

Example:
http://www.mapillary.com/map/im/407279PMasDedx4mKGO2Pg/photo

**Comment by peterneubauer** [comment]
There should be a flag option "rotate". We will look that up when we have
fixed the pipeline for rotation changes.

**Comment by jrcarlsen** [comment]
I am starting to think that my problem is related to the Android 5.1.1 update. I just took a photo in Facebook Messenger that was upside-down as well. I am not sure what triggers this issue, I believe all photos taken today are correct. I think you can close this bug, unless other people are seeing this Mapillary v1.42 as well.

**Comment by jrcarlsen** [comment]
Other people are having trouble with 5.1.1 as well:
http://forums.androidcentral.com/ask-question/436121-camera-takes-upside-down-pictures-after-update.html

**Comment by peterneubauer** [comment]
Ok, seems this fixable, closing for now.
