### ISSUE TITLE
Can read Mapillary destination signs?

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1380]
It is a question I have during playing traffic signs game: As Mapillary recognise traffic signs and can distinguish between car plates and faces (with a little help from my 'human friends') Can Mapillary read the destination signs of the pics? Can the users introduce and text /translate these destination signs? I think will be so useful.

**Comment by jesolem** [comment]
We are working on it. The plan is to read all signs we can and make that available.
