### ISSUE TITLE
[Traffic signs game] Confirm no traffic signs in pic

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1381]
When I play traffic signs game some pics don't have any traffic sign.There's a button to "Confirm detections" .I wish to confirm the "No-detections" too. Would it be possible with the same button?

**Comment by knikel** [comment]
The whole traffic sign annotation flow will be reworked for the new version of the traffic sign game. Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
