### ISSUE TITLE
Hard to draw blur area near arrow buttons

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1383]
More than once, I have had trouble adding a new blur rectangle when the thing I wanted to blur was near one of the arrow buttons to navigate between photos. Here is the best example: a face is *exactly* behind the “move to the right” arrow button.
![mapillary-face-behind-arrow-button](https://cloud.githubusercontent.com/assets/101955/9843033/b1a6a160-5a8c-11e5-938d-c9990049c51e.png)

I can't start drawing where the arrow is, because clicking would move me to another picture. I can't end drawing where the arrow is, because the editor doesn't recognize mouse movement or mouse button release events if the mouse cursor is over the arrow. This also means that if I release the mouse button while the mouse cursor is over the arrow, it gets stuck thinking I'm still drawing the blur (one corner of the blur rectangle follows mouse cursor even while mouse button is released) and I need to click somewhere else in the image to make it stop.

Related: #1369.

**Comment by nicolas17** [comment]
I have since found the "Lock sequence" button, which besides its main function of ignoring any smart navigation and letting me visit every photo in the sequence in order, also removes all arrows on the sides :)

However, I think I still had one case of a license plate overlapping the "previous photo" chevron at the bottom, where I *could* draw a blur rectangle but it wasn't as easy as it could be. And besides, using Lock Sequence to hide arrows seems like a workaround, not a fix, for this problem.

**Comment by knikel** [comment]
@nicolas17 when you blur, the arrows are hidden now (you can still use keyboard). @oscarlorentzon also added plenty of blurring/traffic sign improvements. One of them is blurring at the edges of the photo. Now the controls won't go outside of the photo canvas area.
![blur-edge](https://cloud.githubusercontent.com/assets/1574656/11303672/51ecbcda-8fa4-11e5-869f-1c51cec522cc.png)
