### ISSUE TITLE
Configurable capture delay in iOS app

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1385]
In the iOS app, currently it seems like walking-auto mode takes pictures every 5 seconds, and Riding mode takes pictures every 2 seconds, pausing if there is no movement.

In both cases I have found this to be inadequate. While walking (not *to* take pictures, but to get somewhere, and secondarily taking pictures on the way), it seems I walk fast enough that the every-5-sec pictures are too far apart. In the train (80km/h), taking pictures out of a side window in riding mode, capturing every 2 seconds makes the photos so far apart that there are no matching objects between one photo and the next, and Mapillary can't possibly do SfM for smooth transitions between them (except when decelerating at stations). I haven't yet tried it on a car out the side windows, but I bet the same will happen.

I would like the ability to configure the delay between pictures. As far as I know (I can't test and haven't found screenshots) in Android this is already configurable.

**Comment by millenbop** [comment]
Hi @nicolas17,

thanks for your input. I agree that 5 seconds is not fast enough, will change this to 4 seconds as default. I walk pretty slowly myself :)

We try to avoid settings as much as possible, but I think we should bring this up for discussion, @jesolem?

There is also a hardware limitation on older devices that cannot capture and save fast enough, but newer devices like iPhone 6 should be fast enough to capture faster than 2 seconds, I'll do some testing today.

What the device are you using?

**Comment by thoschu96** [comment]
how about to let the user change it over a drop-down or in the app over settings between 2-5 seconds ?  in ride-mode it seams to have 2 seconds .. so it should work for walking mode too

**Comment by millenbop** [comment]
2 seconds is not a problem for walking auto, but faster than 2 seconds might be a problem on devices like iPhone 4.

**Comment by nicolas17** [comment]
I'm on an iPhone 5s.

I don't accept the "we try to avoid settings" excuse, since the Android app does have a setting for this ;) In fact, I'm told there's two different settings and it's confusing what their difference is.

**Comment by millenbop** [comment]
What do you mean by "two different settings and it's confusing what their difference is"? Do you mean in the Android app?

**Comment by nicolas17** [comment]
Yes, I meant in the Android app, so it's probably a topic for another Github issue :)
```
<PovAddict> does Mapillary on Android allow configuring the delay between pictures while in automatic-capture mode?
<Richlv> reportedly, frequenbcy can be set in the range of 1-9 seconds
<Richlv> frequency
<Richlv> there's also minimum delay between photos, 1-10 seconds
<Richlv> what's the diff does not seem to clear
```

**Comment by millenbop** [comment]
This feature have now been implemented and submitted to Apple, hopefully approval doesn't take too long to approve it.
