### ISSUE TITLE
Sequence Cut Issue

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1388]
Both at home and work on different days and in different browsers, I get a message that the service cut request failed.   Is this functionality broken?  Or is this message resulting because of the 100 image change request limitation.

If because of the image count in sequence limitation:

a) Do we know when / if limitation will be lifted?

b) If not soon, would be this a good time to implement a feature that allows the uploader of the sequence to choose an image to be the start or end of a sequence without having to process the entire sequence and break it based upon gaps? 

If there's anything else I can do to help, please let me know.

**Comment by AllenGraetz** [comment]
Related Screenshot:

![image](https://cloud.githubusercontent.com/assets/11722025/9858441/abc8dada-5aee-11e5-91e0-7b1f3df5a498.png)

**Comment by gyllen** [comment]
@AllenGraetz We are currently experiencing trouble with the whole change set interface. At the moment we are trying to work out a better solution than we have now.

In short the number of images and requests has outgrown the old system. Please be assure that we are working as hard as we can to get a fully working system back in place.

Also thanks for reporting.

**Comment by gyllen** [comment]
We have now removed this feature and are using automatic cuts instead.
