### ISSUE TITLE
pool blur messages more

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1391]
previously, messages about received and approved blur requests arrived with bigger interval. now they arrive more often/sooner, but that often results in a lot more messages.

for example, requesting blurring every now and then results in a bunch of messages about blur requested for 1, 2, 5, 10 images. then, when the approval happens, one can actually see how the approving person works in batches - 18, 10, 22.

it would be better to wait a bit longer and send out smaller amount of images - maybe send the message an hour or two after the last request/approval for that user has been performed ?

**Comment by gyllen** [comment]
@richlv I think we have a buffer time of 5 minutes now before we send a confirmation. Would you like to get rid of this message or would you prefer a longer buffer time? Interesting to know since we are always trying to figure out the correct amount of messages to send.

**Comment by richlv** [comment]
i'd like to keep the messages, but get a longer buffer time (both for request confirmals and review info mails). personally, a buffer of an hour would be just fine by me :)

**Comment by gyllen** [comment]
We are currently reworking the feed items plus notifcations a bit so will take this into consideration. Will probably end up around 30 mins or so. An hour seems a bit long to me.

**Comment by gyllen** [comment]
Messages are no more pooled
