### ISSUE TITLE
Issue performing image search by user

### ISSUE THREAD

**Issue by markscalf** [mapillary/mapillary_issues#1392]
Trying to exercise the API to search for images within a bounding box but filtered for a specific user.  See below as example.

https://a.mapillary.com/v2/search/im?client_id="client_id"&user="username"&max_lat=37.41&max_lon=-121.76&min_lat=37.22&min_lon=-122.05&limit=100&page=1

Output is unchanged when user parameter is provided.  Is this an issue or am I passing the parameter incorrectly?

**Comment by gyllen** [comment]
@markscalf Thanks for reporting. It was an issue on our side, now fixed so closing.

Please note that in most cases search/s is preferred over search/im since search/s are in most cases faster.
