### ISSUE TITLE
Email mount@mapillary.com doesn't work

### ISSUE THREAD

**Issue by mircozorzo** [mapillary/mapillary_issues#1395]
Hi, I'm trying to send an email to this address but I'm always receiving this error:

This is the mail system at host smtp-32.iol.local. I am sorry to have to inform you that your message could not be delivered to mount@mapillary.com. The message is attached below. The remote mail system said: 5.1.1 https://support.google.com/mail/answer/6596 ys8si4474983wjc.176 - gsmtp

Mirco

**Comment by knikel** [comment]
@mircozorzo The correct address is mounts@mapillary.com. Ping us there!
