### ISSUE TITLE
I've got the weirdest bug right now

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1397]
when loading a photo in map view, the sidebar disappears.

![schermopname_2015-09-19_11_10_39](https://cloud.githubusercontent.com/assets/1449609/9975548/ea87f6d2-5ebf-11e5-8eff-aac2c486ca84.gif)

**Comment by de-vries** [comment]
It seems to me that problem is in `<div class="overflow-auto">`
Disabling overflow:auto solves the problem, but I haven't tested for unintended consequences. Disabling the inline `height:0px` also solvese it but  `height:0px` gets immediately placed back by 
(what looks like) some JS.

![schermopname_2015-09-19_15_24_00](https://cloud.githubusercontent.com/assets/1449609/9976383/bca4274a-5ee2-11e5-95a1-39140d27f4cd.gif)

**Comment by knikel** [comment]
@de-vries Thanks for reporting. This has been fixed!
