### ISSUE TITLE
Too old version in amazon app store

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1398]
Version 0.39 located in 
http://www.amazon.com/Mapillary/dp/B00JCVFOHW/ref=sr_1_1?s=mobile-apps&amp;ie=UTF8&amp;qid=1402303026&amp;sr=1-1&amp;keywords=mapillary

Update needed

**Comment by peterneubauer** [comment]
So, we are removing the app temporarily, since the devices don't have GPS and thus we can't submit the app anymore :/

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
