### ISSUE TITLE
Panorama shots should be left right in web application

### ISSUE THREAD

**Issue by Computerfreaked** [mapillary/mapillary_issues#14]
I have made a panoramic shot (http://www.mapillary.com/map/im/KbYNgqxSztMsusgP7uMRJg), and because the location was wrong moved it to its correct location (See https://github.com/mapillary/mapillary_issues/issues/11). 

The web app shows me back and forth altough obviously I wan't moving in a straight line but rotating.

Therefore the webapp should show left right arrows for panoramic views, and front back to move to the next foto series in current direction.

**Comment by ybkuang** [comment]
The current viewer solves the navigation issue.
