### ISSUE TITLE
Lots of 403 errors and 0-byte results using the map

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1401]
I am getting a lot of 403 (forbidden) errors and 0-byte results while browsing the map and clicking to open photos.

This results in squares missing from both the Mapbox tiles and the track overlays, and lack of response when clicking the map to open an image.

This happens both in the "Map" view and the "Photo" view.

**Comment by oscarlorentzon** [comment]
Thanks for reporting this @pbb72 .

We will look into what causes this problem.

**Comment by neuhaus** [comment]
I'm seeing this also.

I open the map and enter the name of a town and get the first error:

XMLHttpRequest cannot load https://d2munx5tg0hw47.cloudfront.net/tiles/8/134/84.mapbox. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.

**Comment by oscarlorentzon** [comment]
Reassigning to @knikel for consideration in the new website.

**Comment by pbb72** [comment]
Closing this because I haven't had any more problems being unable to load stuff. Sometimes things can take a long time, but it seems I always get my requested content.

**Comment by knikel** [comment]
Thanks @pbb72. We're much smarter now about using vector tiles and interpolating at zoom levels,  403/404 errors on vector tiles should only happen when there is an actual tile missing. In 90% of the cases we can interpolate data from _above_ zoom levels (and we do that).
