### ISSUE TITLE
no possibility to flag rotated pictures

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1403]
The possibility to flag rotated pictures has disappeared from the new interface. Compare with #439.

**Comment by gyllen** [comment]
Im not sure this is if its something wrong from our side or if its actually just that we do not get any location lookup. @peterneubauer did adding gpano change anything of this?

**Comment by gyllen** [comment]
We should re add complaint

**Comment by voschix** [comment]
Unfortunately rotated pictures are a frequent by-product of taking pictures with the smartphone App on bicycle (until someone comes up with a shock absorbing bicycle mount). Hence it would be nice not to have to throw those rotated pictures away. The alternative, off course, is to first download the pictures to the computer, rotate them manually, and then do a manual upload, but that's a lot more work.

**Comment by de-vries** [comment]
When I press the flag button I get the option "The photo is rotated"

**Comment by shlublu** [comment]
Instead of throwing them away, why not rotate them?

**Comment by voschix** [comment]
False alarm on my side. The "Flag" button is there and probably has always been there. My fault.
Apologies!
