### ISSUE TITLE
Picture position not shown on map in new viewer

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1404]
The new viewer does no longer show the position of the active picture on the map. This feature is only available now in the old viewer, which you can activate via the Edit button. I liked the old version which always showed you the exact position. I frequently used it when editing OSM with a dual-monitor computer configuration.

**Comment by richlv** [comment]
i guess that's image direction, not position ? position seems to be displayed for me (both in photo & map views).
if it's about direction, that is also requested in issues #1040 and #1118

**Comment by voschix** [comment]
I am talking about the photo position on the map. The original interface showed the photo position with a marker on the track on the map. The new one only shows the track on the map. See attached screenshots.
![old-new-photo-interface](https://cloud.githubusercontent.com/assets/11076112/10074030/88865372-62cd-11e5-924b-5385d80cd460.jpg)

**Comment by ligfietser** [comment]
Do you use Firefox as browser?
This is a bug I also reported in this issue and it still hasn't been solved:
https://github.com/mapillary/mapillary_issues/issues/1266

In Chrome or IE you can see the photo position.

**Comment by voschix** [comment]
Thought I had checked also Chrome. :-( 
Problem is also present  in Edge. Added a note to #1266.
