### ISSUE TITLE
(not) missing orientation tag with script upload

### ISSUE THREAD

**Issue by malenki** [mapillary/mapillary_issues#1405]
I have a bunch of compact camera photos to upload and have to set the orientation flag by hand for each. Uploading them with upload_with_authentication.py works fine – except for panorama images I created from some of them. 
Although the workflow with them was the same with the "normal" pictures they get rejected with 

    Missing required EXIF tag: Image Orientation
    Skipping: ./dscRX035751-58_mapillary_pano7.jpg

This file you can find here,
http://malenki.ch/OSM/Bilder/mapillary/dscRX035751-58_mapillary_pano7.jpg
and one of the accepted ones used for the image above here:
http://malenki.ch/OSM/Bilder/mapillary/dscRX035752_mapillary_pano7.jpg

**Comment by jesolem** [comment]
I thought we removed the requirement on Image Orientation... assigning to @ybkuang for check.

**Comment by ybkuang** [comment]
We've removed the requirements for orientation.
