### ISSUE TITLE
Flag button disables arrow-keys

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1406]
- view image
- press flag
- close dialogue by clicking outside it or pressing esc
- navigating with arrow keys is no longer possible

If you close the dialogue by clicking the X in the top right corner there's no problem. Also I didn't test what happens if you actually flag an image.

**Comment by de-vries** [comment]
same problem with the comment box.

**Comment by knikel** [comment]
Will be fixed in the upcoming update to mapillary.com

**Comment by de-vries** [comment]
seems fixed
