### ISSUE TITLE
Wrong country in notification

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1407]
I'm following the country France. Sometimes I receive notifications of events located in other countries, and described as pertaining to France by the system:

![image](https://cloud.githubusercontent.com/assets/12934696/10068384/5539f4de-62a4-11e5-92ee-fe884638d18f.png)

**Comment by gyllen** [comment]
This is a matter of us having bad borders. We are currently working on improving them. Marked this as borders.

**Comment by gyllen** [comment]
Borders and lookups are tricky, we are improving them all the time but images on a border continuous to be a problem. At the moment (due to simplification of shapes) we do not have a great solution.
