### ISSUE TITLE
advertise irc channel a bit

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1410]
mapillary users would like to use irc - evident by them joining mapillary channel and even sometimes having useful discussions there :)

it would be great to mention this somewhere, as that would allow more users to discover it.

the most popular place seems to be #mapillary on freenode.'

(for some definitions of "popular". probably hasn't seen > 5 users ever, but still :) )

**Comment by nicolas17** [comment]
I agree! There are often Mapillary-specific questions, discussions and general chatting (yay I reached N photos) in #osm, and people can't really be told "off-topic, take it to #mapillary" if it's a silent 5-user channel.

It would also be nice to have some Mapillary person hang out there. It seems like peterneubauer is in freenode like once a month, and not necessarily in that channel :)

**Comment by peterneubauer** [comment]
Mmh, seems like I need to hang out more often there :)

**Comment by peterneubauer** [comment]
Closing this for now - we don't have bandwidth for handling IRC, sorry :/
