### ISSUE TITLE
Slow website

### ISSUE THREAD

**Issue by mrneillhunter** [mapillary/mapillary_issues#1412]
Hi there,
Just stumbled across your website recently and would like to get more involved however it is dreadfully slow and doesn't load at all sometimes.  I've tried it at two different wifi locations (home & office).
Cheers,
Neill

**Comment by gyllen** [comment]
Hi @mrneillhunter thanks for checking us out. What platform are you using to watch our website?

**Comment by HolgerJeromin** [comment]
Core2duo 2 GHz win 7 with Opera 12 does often not load. Chrome is slow. Connection speed is not the problem.

**Comment by Andblue** [comment]
For me, part of the web site always loads, but very often the actual content doesn't load. For me its always been that way, on all devices used.

**Comment by gyllen** [comment]
That is really strange, can you guys ( @HolgerJeromin and @Andblue ) provide screenshots?

**Comment by Andblue** [comment]
Currently everything is working. But one common thing is going to my profile page to see all my sequences. The page frame loads, but no picture thumbs. Same thing happens on the site in general. I doesn't help to reload.

Another example is clicking a sequence, and then it gets stuck loading a picture.

I feels like the connection to the database with all the content drops (but then again, I don't know to much about that stuff ;-)

And by the way, welcome @mrneillhunter . Give it a try, things at Mapillary are moving forward at a pretty rapid pace, so stuff is always getting better and new things are added.

**Comment by HolgerJeromin** [comment]
opera 12 (not chrome) on linux and win7 gives for the main page:
![github](https://cloud.githubusercontent.com/assets/2410353/10194101/255f616c-6787-11e5-8c64-2d6c9293a17a.png)

**Comment by mrneillhunter** [comment]
Hi all - sorry for delay in getting back in touch.  There are different modes I've been trying to access the Mapillary info...

For example one of the moved I'm trying to access is...
http://www.mapillary.com/jsapi?image=UuZ1PLn6yFP83ZyvmyCyJQ
![image](https://cloud.githubusercontent.com/assets/14837654/10250360/2ce58f64-6922-11e5-8b1d-6d537bca5f6f.png)

Another one...
http://www.mapillary.com/jsapi?image=G1JOt8EL4dbGonCTTTWMLw
Same screen grab as above...

This one is intermittent.. at the moment its working :-)
http://www.mapillary.com/jsapi?image=utFhIXJosRhhfXrwhPw3rQ&showMap=false

The main website is working a lot better now which is this one...
http://www.mapillary.com/map/im/utFhIXJosRhhfXrwhPw3rQ/photo

Overall this is fantastic website... keep up the good work!!

**Comment by peterneubauer** [comment]
Hi there,
we have now monitoring on the JSAPI, things should be alerting us when slow or down. I'm closing the issue for now, feel free to reopen if this arises again.
