### ISSUE TITLE
Add support of location from .srt subtutles of DailyRoad Voyager video records

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1413]
Android video recorder app Daily Road Voyager can make .srt subtitle files with GPS coordinates.
It avoid needs of use separate GPS track recorder app and track-video synchronization.
There I place a sample video from DalyRoad Voyager with related subtitle file and related.gpx track created with separated app https://mnky.es/d/QnuqkQD51qVE7HgxzMQ9-g/DailyRoad1?dl=0

**Comment by jesolem** [comment]
Interesting. Didn't know about this option.

**Comment by iav** [comment]
@ybkuang, any workaround?

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
