### ISSUE TITLE
How to add custom traffic signs?

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1414]
I know there's some big improvements to add lots of traffic signs but I can't wait anymore so I start to think ways to improve it.Could I add a traffic sign via github make in it with traffico and give it the official code (we can find it in Wikipedia example https://es.wikipedia.org/wiki/Se%C3%B1ales_de_advertencia_de_peligro ES:P1d , ES:P1c - as we did in OSM ).
If that is too much for Mapillary's interface we can use Github to make pulls of traffic signs because I recognise not all the Mapillary users want to add new traffic signs ;)

**Comment by jesolem** [comment]
@ybkuang and @knikel can explain the best way to do this

**Comment by knikel** [comment]
We're likely to rely on SVG images for traffic signs, we'll have a public repository with them. Will close this when that happens.

**Comment by knikel** [comment]
It's possible to add signs to https://github.com/mapillary/mapillary_sprite_source as svg images. There‘s a [how to guide](https://github.com/mapillary/mapillary_sprite_source/blob/master/docs/adding.md), feel free to skip the `.eps` related parts 😉
