### ISSUE TITLE
incorrect blur location when browser window resized

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1415]
this could have been reported already, but i couldn't find any existing issues

when browser window is resized (including fullscreen mode), blur sometimes gets stuck on the previous resolution and picture location. when blurs are added in that case, they are added in the wrong location (and probably in wrong dimensions, too).

as a demonstration on how widespread the problem is, here are two images with blurs added incorrectly by a mapillary person ;)

no blaming them, though - purely the fault of that issue.

http://www.mapillary.com/map/im/7YsIwlaJpPw8xczxGG2HYw/photo
http://www.mapillary.com/map/im/LPWlY8jUXAyTXjiIz5V16Q/photo

**Comment by nighto** [comment]
Seems to be related with #1445

**Comment by knikel** [comment]
There have been numerous improvements rolled out to the blurring tool recently, this should be fixed too. To give you more context: we're using the actual photo for calculating the where the blurs should be placed on top of the viewer. If it happens again, we'll debug further. Closing for now. Thanks @paulinus and @oscarlorentzon!
