### ISSUE TITLE
Uploads stuck

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1417]
I uploaded 4 sequences about 24 hours ago and they still haven't even shown up in the processing queue. The status page says "No. of pending photos: 1113 (in 4 uploads)"

Also, I've had 5 pictures in the processing queue for several weeks now that never actually get processed.

**Comment by jesolem** [comment]
Thanks for reporting. We are currently doing database upgrades so expect some delay before the photos are visible.

**Comment by polarbearing** [comment]
Same here, but where is that status page? I uploaded 355 pics finishing Sun Sep 27 23:47 with all status=204, and they do not even show as processing in the profile, nor in the activity list.

@jesolem - what timeframe are you talking about?

**Comment by jesolem** [comment]
@polarbearing Best estimate is late today (Tuesday).

**Comment by gyllen** [comment]
System is not stable and we are catching up, thanks for your patiance, this was a well needed update

**Comment by ToeBee** [comment]
Yes, the big upload from the other day has now processed. I still have those 5 pictures forever stuck in the processing queue though :)

**Comment by shlublu** [comment]
I have just uploaded 3 pictures manually. They do not appear in my activity. They don't appear in my "processing images count" either. When I go to the manual upload page to see where they stand, the page keeps loading forever.

This might be related to the system's recovery but I'm not 100% sure.

**Comment by ybkuang** [comment]
The system is recovering. Sorry for the delay.
