### ISSUE TITLE
Cannot access to sequences from the explore page

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1418]
Maybe this has been reported already, I didn't find though:

* I'm going to the "explore" page of the website: http://www.mapillary.com/map/explore

* Then I zoom on any area 

* I click on a sequence or a single picture spot, expecting the viewer to open on this sequence

* The viewer does not open. I stay here.

**Comment by shlublu** [comment]
Looks like this is now solved. Did you do anything?

(seen as not working: 12 hours ago, reported: 5h ago, seen as working: now)

**Comment by jesolem** [comment]
Database upgrade just completed. System is catching up now so that's probably it. If everything looks right in a few hours, go ahead and close or report back. 

thanks

**Comment by gyllen** [comment]
Closing this, thanks for reporting
