### ISSUE TITLE
Cannot edit sequences: the edit page keeps loading forever

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1420]
I have uploaded a few sequences, and some of them contain blurred images that I didn't notice on my cellphone. I would like to hide them.

When I click on "edit" from the sequence viewer, I'm led to the edit page, but the sequence doesn't load. It keeps loading for minutes.

An example: http://www.mapillary.com/map/e/Mp8Mz6rDFam4URfThKj08A

**Comment by echeloni2p** [comment]
Maybe related with #1198 ?

**Comment by shlublu** [comment]
@echeloni2p I missed that one. Yes, it might be related.

**Comment by de-vries** [comment]
To me it seems like there is some general problem with the database. 
- links to images return "Image not found"
- mapillary.com/map/places/* doesn't work
- the stats on the front page are missing
- images won't load, I just get a spinner

described behaviour isn't consistent though, apparently some requests do get trough.

**Comment by jesolem** [comment]
Thanks for reporting. We will investigate.

**Comment by de-vries** [comment]
also: if I click a link in my uploads it works most of the time, but if I open in a new tab it returns "Image not found"

**Comment by jesolem** [comment]
We're having some issues with "not found" right now. Working on it.

**Comment by gyllen** [comment]
This is now fixed, closing

Error was related to underlaying switch of master database.

**Comment by de-vries** [comment]
It's happening again. nothing that has to come from the database does load.
