### ISSUE TITLE
 traffic sign not deteceted

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1421]
Your algorithm for detecting traffic sign has not picted up this traffic sign on this picture: http://www.mapillary.com/map/im/joo6Blb-XriWcFVjlktKxQ/photo

**Comment by jesolem** [comment]
@beer119 That image is not fully processed yet. We should have better warnings for this. 

When it is processed, if the sign is still missing, you can correct by clicking "edit" > "traffic signs" and mark it in the image.

**Comment by beer119** [comment]
When I got to my profile then I can see that all the pictures that I have been uplaing has been processed (still processing is):  http://postimg.org/image/ssc4dsp71/

If you have different layers of prosseing then I would sugget that you make that page more transparent

**Comment by gyllen** [comment]
@beer119 You are right, we are doing different layers and traffic signs is something that is done on a later stage. We are thinking about how to communicate this clearer to you.

**Comment by knikel** [comment]
_Unproccesed_ message should be displayed correctly in such situations now. Closing.
