### ISSUE TITLE
new bug with pano

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1422]
A new and strange bug with pano
![bug mapillary](https://cloud.githubusercontent.com/assets/8255984/10221676/0f7abf3a-6850-11e5-9706-e41cfa5a22b9.PNG)
http://www.mapillary.com/map/im/EGix5OpGpOBTGWVS0rX4bA/photo

(wait a few seconds to see the problem)

BTW : Pano deserve a better quality

**Comment by oscarlorentzon** [comment]
Thanks for pointing this out @Stefal ! It has now been fixed.
