### ISSUE TITLE
Map not always full screen on Chrome for Android 

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1423]
When entering mapillary.com and selecting a  city the map often looks like this:

![screenshot_2015-10-01-16-51-09](https://cloud.githubusercontent.com/assets/8446338/10224331/b01f8044-685d-11e5-9290-d84c73c01d48.png)

Some times it works fine. Everything else works great in this browser. 

System info 
![screenshot_2015-10-01-16-51-22](https://cloud.githubusercontent.com/assets/8446338/10224365/d0e2068a-685d-11e5-84ce-0655844000a1.png)
Hardware: Sony xperia z2.

**Comment by simonmikkelsen** [comment]
Oh, BTW, I am not Asian. The OS is set to Danish locale.

**Comment by knikel** [comment]
We don't have responsive version of the web app as of today. I'm closing this since we'll be working on responsiveness of the web app in the coming months.
