### ISSUE TITLE
new comment message duplicate

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1424]
I got twice the same message that someone left a comment, once because it was on one of my photos and once because it was the area I follow:

![selectie_096](https://cloud.githubusercontent.com/assets/1449609/10232031/786ec870-6886-11e5-9fe3-5acc96ce535f.png)

I also received two emails because of this.

Another thing wrong with this message: the linking to my profile doesn't work because of the space in my user name.

**Comment by gyllen** [comment]
@peterneubauer We should see over notifications like this, for area notifications the user should be excluded.

**Comment by de-vries** [comment]
I've got a similar one:
![selectie_098](https://cloud.githubusercontent.com/assets/1449609/10371373/575163f2-6de3-11e5-9387-496563979819.png)

**Comment by de-vries** [comment]
![selectie_100](https://cloud.githubusercontent.com/assets/1449609/10377707/2369bfea-6e05-11e5-8a56-587bf6a570f7.png)

**Comment by peterneubauer** [comment]
This should be solved now.
