### ISSUE TITLE
Badly mislocated sequence

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_issues#1425]
http://www.mapillary.com/map/im/nPBZgtTBHZUTlO2zft0Qug/photo is on the wrong part of the sequence.

This is one of mine, and I'm not if it's from the app or my old camera. If it's my old camera, then the images were correlated with GPX in postprocessing, and the only question I have is how do I fix the sequence or remove it.

If it's from the app, then it's an app bug.

I have a new camera which I roof mount and has built-in GPS, mainly so I don't have to post-process anymore.

**Comment by gyllen** [comment]
Let us check on that. @ybkuang can you see what device this sequence is from?

**Comment by ybkuang** [comment]
@pnorman I just checked.  It's from your old camera (Canon Powershot from the exif).

Awesome with the new camera!!

**Comment by pnorman** [comment]
> @pnorman I just checked. It's from your old camera (Canon Powershot from the exif).

Okay. It's unlikely I'm going to go back and reprocess the sequence, so what's the best way to handle it, given it's uploaded?

> Awesome with the new camera!!

Unfortunately, the Garmin VIRB XE seems to have the same problems and I'm going to have to process to eliminate them, unless Garmin support can get me a solution :( mapillary_tools#86

**Comment by ybkuang** [comment]
@pnorman By the image  ```is in the wrong part of the sequence```, do you mean the positions are off or the ordering of the sequence is wrong? If the positions are off, maybe you can use the editor to fix it.

**Comment by pnorman** [comment]
The ordering of the sequence is correct, but all of the positions are shifted along it.

**Comment by ybkuang** [comment]
I will close this for now. If you encounter this again, please let us know @pnorman!
