### ISSUE TITLE
Picture position marker not shown on map in new viewer

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1426]
I would like to reactivate the closed issues #1266 and #1404, adding that at this moment the marker is not showing on Firefox, Chrome and Edge on my Windows10 computer

**Comment by gyllen** [comment]
Yes I have seen this to sometimes on localhost, @knikel we should try to upgrade mapbox-gl

**Comment by ligfietser** [comment]
#1266 is not closed, please fix this ASAP. Mapillary became quite useless for users of Firefox.
Also note that image direction is not working anymore in ANY browser.

**Comment by knikel** [comment]
We've upgraded to latest mapbox and added FOV marker which shows the direction.

**Comment by ligfietser** [comment]
Thanks for the fix. The arrow in the down left corner is redundant now?

![arrow](https://cloud.githubusercontent.com/assets/9638726/11452298/3b11634a-95e3-11e5-8288-2938e519fa70.jpg)

**Comment by knikel** [comment]
@ligfietser of course. It shouldn't be visible there anymore now. Thanks.
