### ISSUE TITLE
Place lookup proposes "...,Flemish", it should be "...,Flanders, Belgium"

### ISSUE THREAD

**Issue by marcgemis** [mapillary/mapillary_issues#1427]
Whenever I look up a place in Flanders, e.g. "Hemiksem", the completion proposes "Hemiksem, Antwerpen, Flemish". Flemish is  language, not a region.

The correct address should be "Hemiksem, Antwerpen, Flanders, Belgium." 
That's city, Province, Region, Country

**Comment by gyllen** [comment]
Is this on the search on the front page?

**Comment by marcgemis** [comment]
Yes, the search on the front page.

**Comment by gyllen** [comment]
@marcgemis We use an external service for search on the map. The only thing we can do is to wait for data (which is OSM) to be corrected.

Unfortunately closing this.

**Comment by marcgemis** [comment]
The data is correct, I use it all the time from osm.org. and OsmAnd. And it was correct with the previous service you used. I'm willing to file a bug report with your current provider if you wish.

**Comment by gyllen** [comment]
We are using mapzens awesome tool https://mapzen.com/projects/search

**Comment by marcgemis** [comment]
I've contacted them via email. Can't find a place to check their data
