### ISSUE TITLE
Can't find the pictures on htc desire 500

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1428]
I have taken 400 pictures without SD-card, so mapillary says the pitctures are in /data/data/app.mapillary/files/mapillary
I tried some explorer apps but I can't find this location, I have no right to enter /data
I want the picture for JOSM before uploading to mapillary

**Comment by peterneubauer** [comment]
What version of the app do you have? I så the latest release, there should be in the review grid view an option to export the select images to the public phone photo storage, if you long - click on a few pictures.

**Comment by wegavision** [comment]
the version need android 4.2 the htc has only 4.1
I will delete the pictures.
