### ISSUE TITLE
expose individual images/short sequences more

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1429]
when there's a long sequence, it is quite obvious on the map - one can see the line. but often somebody takes images turning around, ending up with just slightly jumpy coords or them all being the same. extreme case - just a single image.
these are very hard to spot on the map as they are very small objects. maybe they can be exposed some more - for example, if a sequence is shorter than 10-20 px on the screen (if that can be detected), add some sort of a glow or such effect to make it more visible

**Comment by jesolem** [comment]
I like this idea. Could be something in the vector tile styling to handle this. @knikel or @gyllen might know how to best fix.

**Comment by knikel** [comment]
We'll be using source layers which expose images as single _dots_. Will close this issue when we roll it out.

**Comment by knikel** [comment]
Each photo can be displayed as a single dot on the map, and that's what happens at higher zoom levels in the new UI.
