### ISSUE TITLE
Traffic signs in some areas don't show in ID

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1430]
In some areas traffic signs don't show in ID.
Example:
http://mapillary.github.io/iD/#background=Bing&id=r45165&map=17.00/11.61903/45.51926
There should be several sequences with traffic signs along via Roma by users lucamenini and voschix
You can easily check on Mapillary and on JOSM with the Mapillary plug-in.

What's going on?

**Comment by peterneubauer** [comment]
This was a limitation of the number of images displayed in iD, should be fixed now there.
