### ISSUE TITLE
Place names not always correctly coded

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1432]
As can be seen from this screenshot, not all location names are coded correctly in Unicode

![image](https://cloud.githubusercontent.com/assets/1436366/10303937/3b6cf3b8-6c17-11e5-92fa-176f282d662b.png)

**Comment by jesolem** [comment]
Could on our end or in Pelias which we use.

**Comment by knikel** [comment]
Unfortunately nothing we can do about it, patch for that on Pelias' side is in the works: https://github.com/pelias/quattroshapes-patch/issues/9

**Comment by missinglink** [comment]
hey @jesolem I just rolled out some fixes, so now you can find `Malmö` and other administrative areas more easily. see https://github.com/pelias/api/pull/341 for more details

the character encoding issue is super annoying, I'm spinning up a postgres server now to try and fix some of the quattroshapes data, I'll also have a look at the place names which are all in CAPS LOCK too ;)

**Comment by jesolem** [comment]
@missinglink Awesome. You guys rock.
