### ISSUE TITLE
Search needs to be integrated in map (& photo) page, not separate page

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1434]
It's quite confusing that the search page has a layout that is very much alike the map page, but some details are very different. For example, the photo is displayed in the lower left corner instead of to the right.

Search should not be a separate page, it should be an integral part of the map page.

**Comment by knikel** [comment]
The layouts will be more unified (the drawer will be added). It's possible that we'll add a searchbox somewhere in the viewer too, but we'll keep a searchpage untouched, as we rely a lot on routes like: `/map/search/lat/lon/zoom` and `/map/search/minlat/maxlat/minlon/maxlon` which makes sense when you don't access them from the viewer.

**Comment by knikel** [comment]
Search is now available despite the `focus` mode 👍
