### ISSUE TITLE
Same toolboxes on photo and map page

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1435]
Could we have the same toolboxes on the photo and the map page? Sometimes I would like to see the photo details while on the map page, and sometimes I would like to use filtering while on the photo page.

**Comment by knikel** [comment]
That's coming 👍

**Comment by knikel** [comment]
We've redesigned the UI and the drop-up with actions are available whether the photo/maps are small or large. They might change the focus mode, but that's intentional, since e.g. blurring with a tiny photo is not the easiest thing to do. Closing.

**Comment by pbb72** [comment]
Maybe I am not understanding what the "drop-up" is, but the little button with three dots is still showing different actions depending on whether the mapview or the photoview is current. For example, to see when a sequence has been taken, I still first have to switch to photo view before opening the action menu. If I want to edit the position or direction of a photo, I still have to first switch to map view before opening the action menu.

If I am not misunderstanding, I think this issue is still current and should be re-opened.

**Comment by pbb72** [comment]
Ah, I see now there is a secondary action menu on the photo while in map view. This fixes my first problem of seeing photo details while in map view, but it is still not possible to go straight into edit mode from a photo view.

From an interface point of view, I also think having two action menus is not a good solution. I would prefer having all the same options in one action menu, regardless of what focus the current view is.

**Comment by knikel** [comment]
Thanks @pbb72 for comments on that. I'm looping in @angelday here, since faster blurs and edits is something we need to iterate further UX-wise.

**Comment by angelday** [comment]
The context menus are not global but relevant to what they are displayed on: either the photo or the map. You get different options for photos and maps. This is because, eg. you cannot edit blurs on a sequence.

**Comment by pbb72** [comment]
Not all of the actions are only relevant to one view. For example modifying photo direction and placement is relevant both to photos and maps. Yet it is only available in map view.

I can open a separate issue on the confusing use of two action menus, should not mix too many problems together 😊

**Comment by gyllen** [comment]
@pbb72 We are working on making this clearer, stay tuned. Thanks for input.
