### ISSUE TITLE
Home Page Map Not Showing Routes Mapped

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1439]
The map on the home page is not showing all the mappings.  This map should be full of squiggly lins showing all the places mapped.

![image](https://cloud.githubusercontent.com/assets/11722025/10369930/cfcc01b8-6daa-11e5-8462-269850d6f591.png)

**Comment by knikel** [comment]
It' very likely that our raster tiles haven't been updated in a while, would you mind zooming in few times and see whether you get lineString data displayed? We display lineStrings for zoom levels above 12. It'll look more like the photo below. @gyllen do we have ETA on updating raster tiles?

<img width="1073" alt="ls-data-knox" src="https://cloud.githubusercontent.com/assets/1574656/10370295/6fb92394-6dde-11e5-8c6e-f89508eb3c36.png">

**Comment by gyllen** [comment]
@AllenGraetz Do you have any chance to view webpage in chrome, this will give you a much faster and smoother map experience, if not we will keep supporting raster maps for a long time so no worries :)

**Comment by AllenGraetz** [comment]
I'm going to give this a try at home.   I'm not seeing the difference with Chrome but they be blocking something at work.  I seem to remember something similar to this before.   Thank you.

**Comment by AllenGraetz** [comment]
![image](https://cloud.githubusercontent.com/assets/11722025/10402243/37acb678-6e92-11e5-9fb9-65f2902358d7.png)

**Comment by gyllen** [comment]
Fixed on new web
