### ISSUE TITLE
automatic blur often misses last symbol

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1440]
for some reason, automatic blur very often misses last 0.5-1.5 symbols in licence plates. just a few examples i did not fix in a short segment of one sequence :

http://www.mapillary.com/map/im/h4SpmTfDFlBtBrwz8Xa3yA/photo
http://www.mapillary.com/map/im/uEG8iNwFGlIoT7P2oEc2MQ/photo
http://www.mapillary.com/map/im/XxlPAZZfsXyjZfd0VyW8gQ/photo
http://www.mapillary.com/map/im/wvs8pyL0DgTkGiKOGkwBCQ/photo
http://www.mapillary.com/map/im/1rcEh8YtHA8thPyU7xhjVw/photo
http://www.mapillary.com/map/im/sW3ziSGFdiFRr1vkFwdY8g/photo

of course, the preferred solution is to be more correct not to overshoot always :)

**Comment by de-vries** [comment]
I've noticed this to on Dutch licence plates.

**Comment by jesolem** [comment]
Could be the aspect ratio of the detector region. @ybkuang can take a look for the next iteration of detectors.

**Comment by nicolas17** [comment]
I have seen the opposite happen in Argentina (where license plates are ABC123): the blur area is noticeably wider than it needs to be. I'll try to find an example.

**Comment by richlv** [comment]
still happens : http://www.mapillary.com/map/im/n1xKKg-_rU0C1AjQO3kZtg/photo

**Comment by richlv** [comment]
an older picture here, but two occurrences in one image :)
https://www.mapillary.com/map/im/IVzCV50G1FpI_IuRSySaEg/photo
also note that this is not offset - in many cases the licence plate is very obviously and carefully blurred excluding the last symbol - there's nothing extra blurred to the left

**Comment by richlv** [comment]
and a very recent auto-blur, missing last 1.5 symbols :
https://www.mapillary.com/map/im/wbgFcC8gmVoskE0QxaHIFw/photo

**Comment by richlv** [comment]
an example of missing two symbols : https://www.mapillary.com/map/im/RTzbU8Nt_-gLAxkJsm--nw/photo

**Comment by richlv** [comment]
...still happening : http://www.mapillary.com/map/im/vIbL2-Ggzz3nB3mfTlimEQ/photo

**Comment by ybkuang** [comment]
@richlv Thanks for reporting the details. These will be very help in improving the detector.  In general, the detector will find overlapping rectangles around license plates and we choose the one with higher scores. In some cases, rectangles with larger areas or missing characters score higher. This can be fixed if we retrain the detector with more data. We will work on it in the next version of the detector.

**Comment by richlv** [comment]
if you say that's useful, here's another one :)
http://www.mapillary.com/map/im/LXzjq7Z9GqTLbpnrDsRkqA/photo

**Comment by de-vries** [comment]
@ybkuang I mostly just fix such blurs, but can you tell me what would be more useful; reporting them, fixing them or both?

**Comment by richlv** [comment]
for the record, i've stopped fixing or reporting them here - way too many, seen dozens of them since the last one i reported.
if there's serious interest in getting these reported, there should be a separate button "report blur missing last symbol" or so :)

a fairly extreme case here : http://www.mapillary.com/map/im/jNFFYwiPkTXDQWuzi0px-w/photo

**Comment by richlv** [comment]
still happening a lot. see this image and several images forward in this sequence : http://www.mapillary.com/map/im/MGEHz9Y2AEXQCcwBhBSleA/photo

**Comment by richlv** [comment]
another extreme case : http://www.mapillary.com/map/im/34U1usXoKoZqkoHn0Q2VUQ/photo

**Comment by richlv** [comment]
still happening. see https://www.mapillary.com/map/im/8IXJHddM2kMP6fcYvCeulw and a few images after it for one example.

**Comment by ybkuang** [comment]
This should be improved by the new [release](https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html) for privacy blurring. Please let us know if the issues persists.
