### ISSUE TITLE
traffic signs has not been picked up

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1441]
This picture is around 1/2 year old at it seems that it has not been proccess for traffic signs
https://www.mapillary.com/map/im/7o63n1PNRWewLZRcmaS68g/photo
or the signs was missed by your algoritme

**Comment by ybkuang** [comment]
@beer119 An older version of the traffic sign detector was run on this image and the yield sign is included properly in that version. We will rerun the new detector on old images in the future. Thanks for reporting this.

**Comment by ybkuang** [comment]
This should be resolved by the new [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
