### ISSUE TITLE
Can't use expandable menu, Safari - iOS

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary_issues#1443]
Reference: https://github.com/mapillary/mapillary_localization/issues/41

**Comment by socketpair** [comment]
Also, it is not clear how to find correct github repo to report website bugs. It will be nice if you open source website. Or, at least, write where to report website bugs. (i.e. in this repositry)

**Comment by knikel** [comment]
@socketpair You're right. We do have a link in the footer, but it could be more visible. Thanks for the feedback!

**Comment by knikel** [comment]
We'll be working on responsive layout for the web app and it will have different form than current UI. Closing.
