### ISSUE TITLE
[traffic sign edition] Cannot fix a bad confirmation of traffic signs detection

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1446]
When I confirm a traffic sign detection or a no signal in a pic and I continue with another pic but I have made a mistake and turn back  to fix it  the only thing appears is the message "You have already approved this photo." so I cannot fix my mistake and add or delete a traffic sign I have missed out or missfit . With Firefox, Chrome and Win7.

**Comment by knikel** [comment]
This behaviour is actually by design. We might relax it in the upcoming version of the front-end.
