### ISSUE TITLE
[Traffic signs game] Traffic sign game inside app

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1447]
What about the game in the app? I wish to play it ;) It could be a short version like yes or no or fix (as Tinder or other dating apps) .Android app, please :P

**Comment by ybkuang** [comment]
@yopaseopor Great idea! I would love to have that too. Both Android and iOS ;)

**Comment by yopaseopor** [comment]
And also the other mobile OS too ;)
