### ISSUE TITLE
[Traffic sign game] Game is freezed

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1448]
When I start the game and I confirm first pic, sometimes, the second or third pic gets infinite fetching freezing it or the buttons are not appearing and make it impossible to continue playing .Sometimes I change to US traffic sign game, play one or two and then turn back to EU game or try to reload the page. But after playing two or three pics the game freezes again. With last version of Firefox, last version of Chrome in Win7.

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
