### ISSUE TITLE
[Traffic_sign_game] Classify a picture as blurry

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1449]
After we start to make tracks at evening or later of a day some pictures are little "blurry" or directly bad . This "problem" will be happen every time with lots of pics so we have to take some actions.For example, at traffic game can we rate pic as blurry or rate it with any system?

**Comment by HolgerJeromin** [comment]
I have seen sequence at night on a motorway. Images were black and some had blurry red circles from the car in front. 
This had no value imo.

**Comment by jesolem** [comment]
Agree on both. We are sketching on ways to up/down rate photos/sequences.

If the photos are really as bad as @HolgerJeromin 's example, feel free to hide them too.

**Comment by sandrauddback** [comment]
Closing this issue. It is still very valid to get a quality metric to the images and we have for 2018 put this into our pipeline.
