### ISSUE TITLE
More sequence loopiness in Kansas

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1452]
I noticed a new user here in Kansas a while ago. They seem to be very good at creating sequences that have odd loops in them. I know you guys have a de-looper process that runs periodically but these sequences seem to be getting missed or are erroring out or something. They've been on the map for several weeks now. The affected area is between Wichita and Hutchinson:
http://www.mapillary.com/map/search/37.85478091472572/-97.59375155409427/9.764687725730388

**Comment by ybkuang** [comment]
@ToeBee Thanks for reporting this! Just had a look, it feels like the ordering of the images are correct, but the sequence contains images from different dates. And there are duplicate images. We will notify the user and find a good solution for this.

**Comment by ToeBee** [comment]
As far as what I see on the map it looks like this is fixed? Or are you still addressing a back-end problem to prevent it from happening again?

**Comment by ybkuang** [comment]
@ToeBee We have reprocessed most of sequences recently. Let's keep this open until the full reprocessing is done.

**Comment by ToeBee** [comment]
Seems like this is all fixed. I'll go ahead and close this issue.
