### ISSUE TITLE
url from mapillary email resulrs in error 500

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1453]
this url was received from mapillary in an email, but it returns error 500

https://www.mapillary.com/map/im/15/23.6333107577542/58.5463826358826

**Comment by richlv** [comment]
also, i made a typo in the summary - "resulrs" :)

**Comment by knikel** [comment]
This is fixed now, next e-mails should lead to proper locations

**Comment by richlv** [comment]
hmm, shouldn't such a url pop up a proper error message then, instead of a silent (in the browser) 500 ?
