### ISSUE TITLE
Mapbox level of detail decreases as I zoom in

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1455]
The level of detail of Mapbox is decent at that zoom level:
![image](https://cloud.githubusercontent.com/assets/12934696/10560092/70adc6c8-7500-11e5-9596-c80092f7a26c.png)

But when I zoom in (not out!), the level of details decreases:

* Here I'm losing the basin:
![image](https://cloud.githubusercontent.com/assets/12934696/10560096/96d23438-7500-11e5-9d10-97c2414ab83f.png)

* And here, if I gain the pathes, I'm losing the grass areas:
![image](https://cloud.githubusercontent.com/assets/12934696/10560099/b8315abe-7500-11e5-9aa7-14777a951995.png)

![image](https://cloud.githubusercontent.com/assets/12934696/10560101/c848d1d4-7500-11e5-9267-9d66d52455d9.png)

**Comment by knikel** [comment]
@shlublu I've updated the mapbox styles recently, is this still an issue? This is what I see in that area:

<img width="358" alt="basin" src="https://cloud.githubusercontent.com/assets/1574656/11452197/18d8eed6-95e0-11e5-8fa4-caf74035086a.png">

**Comment by shlublu** [comment]
It looks ok now, thanks!
The only thing that needs fixing is that I lose the sequence's track as I zoom in.
![image](https://cloud.githubusercontent.com/assets/12934696/11452394/ab18a984-95e6-11e5-974e-dc71d9786453.png)

**Comment by knikel** [comment]
Good. Yes, the sequence track will be visible better when we generate one more level of vector tiles. Closing this issue for now. Thanks for the feedback!
