### ISSUE TITLE
Approved blurs not appearing when viewing the sequence

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1456]
I had 32 blurs approved for these two sequences:
- http://www.mapillary.com/map/im/jM92vvYZyt7PLh0bjhmQBQ/photo
- http://www.mapillary.com/map/im/rAdN_kCV2LeCpYrU4UuSKg/photo

However, when I chek the result in view mode:
- faces are still appearing in clear
- unblurs still look blurred

When I try the blur mode all the red shapes are ok though.

**Comment by de-vries** [comment]
It sounds like the cache hasn't catched up yet. I have seen this happen too.

**Comment by peterneubauer** [comment]
So, in http://www.mapillary.com/map/im/jM92vvYZyt7PLh0bjhmQBQ/photo you requested face blurs that are not applied?

**Comment by shlublu** [comment]
They were obviously delayed as images are properly blurred right now  - which makes it a non-issue. 
I don't think this is a cache issue as other changes were appearing. This is the first time it happens.

**Comment by peterneubauer** [comment]
Good good, thanks for tracking this anyway!

**Comment by shlublu** [comment]
Thanks to you guys for the hard work. This is a nice project, definitely :)
