### ISSUE TITLE
Viewer : Photosphere view broken

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1457]
http://www.mapillary.com/map/im/EGix5OpGpOBTGWVS0rX4bA/photo
![pano](https://cloud.githubusercontent.com/assets/8255984/10564457/622783cc-75b5-11e5-889e-b9dcaa5d15f2.PNG)

**Comment by oscarlorentzon** [comment]
Thanks for reporting again @Stefal ! This image has seen some different forms during the last couple of months... Sorry for that.

The problem this time is related to a new processing pipeline for panoramas and the reconstruction for this one has not yes been updated correctly. We'll look into this.

**Comment by paulinus** [comment]
The image has been reprocessed and looks panoramic again.
Thanks for reporting
