### ISSUE TITLE
Direction arrows in upload preview are the wrong way around

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1458]
In the small preview map, which is shown on the manual upload pages, after selecting photos for upload and before publishing, the direction arrows are inverted.

That is, if my photos are mainly directed north, then the preview map will show them as pointing south.

The direction tag in the photos is correct; after being published the arrow is in the right direction.

**Comment by gyllen** [comment]
Is this on the vector map?

**Comment by pbb72** [comment]
The small preview maps on the manual upload page, they are raster maps, not vector maps.

Take this example, the photos are all facing south/east, but the small arrows are pointing north/west.
![image](https://cloud.githubusercontent.com/assets/1436366/10622417/b834a276-7787-11e5-81cd-3fa8f49396e7.png)

**Comment by pbb72** [comment]
After the upload is processed and the images are on the map, the orientation is correct:
![image](https://cloud.githubusercontent.com/assets/1436366/10622879/70c3b94c-778a-11e5-988d-0027da81721e.png)

**Comment by HolgerJeromin** [comment]
same here with single (geosetter) images.

**Comment by pbb72** [comment]
My image directions are set with the Python script.

**Comment by gyllen** [comment]
This should be fixed in new editor, reopen is not
