### ISSUE TITLE
Hide Pictures

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1459]
I the newes version of mapillary i can't fint the way to hide own pictures.

**Comment by knikel** [comment]
@wegavision you can find an edit button in the toolbar on the right, it will go to a new view where you can hide the given photo.

![edit](https://cloud.githubusercontent.com/assets/1574656/10821316/191484f0-7e52-11e5-98e8-58fd7b79cfa9.png)

**Comment by wegavision** [comment]
No, there isn't an edit on my screen: Windows 10 + firefox + german language
http://home.arcor.de/wegavision/OSM/mapillary_nix_edit.jpg

**Comment by de-vries** [comment]
dear @wegavision, see my comments in #1466.

**Comment by knikel** [comment]
Thank you @de-vries for linking to that issue.
