### ISSUE TITLE
trafic sign found but not added to stats page

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1460]
Hi
Your algoritme has picked up a sign:
http://www.mapillary.com/map/im/xzHQq-hkrvmlk6B6gMwdUg/photo
But this sign has not been added to my stats page:
http://www.mapillary.com/profile/beer119/ors

Is this a bug?

**Comment by knikel** [comment]
@beer119 There was indeed a bug that prevented few sign classes from being displayed. This is how your profile should look like now. Bear in mind that it usually takes some time before the photo is visible and traffic signs are detected, however if they're visible in the viewer, they should be on your profile too.

<img width="417" alt="beer119-signs-complete" src="https://cloud.githubusercontent.com/assets/1574656/12021984/cc38eed2-ad8b-11e5-9e62-6962c05d072e.png">

BTW. These are some impressive numbers!
