### ISSUE TITLE
"Press here to uploadRequest" always appearing

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#1461]
Mapillary is nagging me with this:

![](http://i.imgur.com/28FAK7A.png)

Even tought the review queue is empty:

![](http://i.imgur.com/JaLPj3t.png)

I guess it started with version 1.46 and still happens with the latest 1.47

**Comment by jesolem** [comment]
@peterneubauer will investigate, thanks.

**Comment by peterneubauer** [comment]
So, this is a nagging that you have images to upload that appears when you connect to Wifi (will correct the text). You think we should use something else like maybe a badge on the Mapillary icon to signal pending uploads?

**Comment by naoliv** [comment]
The problem is that I don't have any images to upload (as you can see in the second picture above).
It just shouldn't display anything here (but everytime I connect I receive this message)

**Comment by peterneubauer** [comment]
Uh, true, investigating.

**Comment by peterneubauer** [comment]
the fix is out in the next alpha. Thanks @naoliv !

**Comment by naoliv** [comment]
Thank you!

**Comment by peterneubauer** [comment]
Working?

**Comment by naoliv** [comment]
It seems that yes. The message didn't appear anymore.
