### ISSUE TITLE
Ignore cars during SfM

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1462]
I recently took a photo sequence from a car, looking sideways, taking one picture every 2 seconds: [cc05RmBDB9a_HO7aRmYdXg](https://www.mapillary.com/map/s/cc05RmBDB9a_HO7aRmYdXg).

I have found a few cases in this sequence where the SfM image recognition uses almost exclusively image features from a nearby (moving) car to do the photo transitions. For example, [ozJOl_BFubraUHBxHxttjg](https://www.mapillary.com/map/im/ozJOl_BFubraUHBxHxttjg/photo) → [r0cLus6NlzLdszSuATHZhA](https://www.mapillary.com/map/im/r0cLus6NlzLdszSuATHZhA/photo) only uses the white car as a fixed reference and the background is simply cross-faded, but it would look much better to ignore the car and match the building and trees in the background.

As another example, the transitions between [mxkQjPbDyT5sfLuajHuKuA](https://www.mapillary.com/map/im/mxkQjPbDyT5sfLuajHuKuA/photo) → [QU7JJsJFG_i8iP8-LsLhpg](https://www.mapillary.com/map/im/QU7JJsJFG_i8iP8-LsLhpg/photo) → [300NzWy2xXixJR2dvi6C7g](https://www.mapillary.com/map/im/300NzWy2xXixJR2dvi6C7g/photo) smoothly morph the position of the black car and make a mess out of the background.

This is _not_ easy to fix. The SfM would need to ignore cars, either by having a whole-car detector or by letting users manually define areas to be ignored for SfM purposes (but it would have to be a polygon, not a rectangle like manual blurs).

Okay, go ahead and throw this at the very end of the to-do list :)

**Comment by paulinus** [comment]
hi @nicolas17,

moving cars, trucks and even clouds are a challenge to SfM. The algorithms we use are robust to them only as long as they are small. As you've found, when they are large, SfM will use it them a reference instead of using the ground.  Detecting them explicitly and ignoring them is good item for the to-do list.

Thanks,
pau

**Comment by paulinus** [comment]
We got to do this, and it improved the reconstructions in many places. It was a good idea and i'm very happy that we got to implement it. Thanks @nicolas17  
https://blog.mapillary.com/tech/2017/07/26/improving-3d-reconstruction-with-semantic-understanding.html

**Comment by nicolas17** [comment]
I hadn't seen that blog post. The results are even better than I expected :heart:
