### ISSUE TITLE
Area notification

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [mapillary/mapillary_issues#1463]
When I click in the mapillary application in the feed on a area notification (i.e. "You Bayern has 129 new photos"), the app crashes. Always. Reproducible.
1. It would be nice if this bug gets fixed (Android).
2. Is it possible to view the area notification on the web interface? Currently I only know how to register a new area (http://www.mapillary.com/map/settings/notifications), but I don't know how to view the notification (RSS-Feed?).

**Comment by eugensim** [comment]
@peterneubauer @jesolem @gyllen notifications are not working at all for a long long time. Nothing on mail.

**Comment by gyllen** [comment]
Can you try to go into your settings remove your current ones and add new ones. The system was updated some time ago with much better shapes.

**Comment by epsg31468** [comment]
1. If I add a new area, it has now a (multi)polygon around it. Looks good.
2. Old areas do not have it around. It would be nice if they get updated automatically. Very low priority for that.
3. Android-App is stable now when viewing the feed.

**Still Missing:** Can I view the Notification Feed somewhere on the web?

Thank you!

**Comment by gyllen** [comment]
This should be solved now?

**Comment by oldschoolBavarianReferenceSystem** [comment]
It took me a while to figure it out, finally I found it under

Profile>Activity

It is mixed with Uploads and other activities, but that's OK.

**Comment by eugensim** [comment]
Doesn't work very well, (again!) nothing on e-mail, I also want to see photos added on Profile>activity not just that. 
![image](https://cloud.githubusercontent.com/assets/8439643/14423509/d9db76ee-ffe4-11e5-9738-5ed5d90baad2.png)

**Comment by gyllen** [comment]
It does look like the emails are going out, could they by in your guys spam folder?

**Comment by eugensim** [comment]
nothing in spam folder :(

**Comment by gyllen** [comment]
So you do get upload notifications by email, but you do not get area notifications. Do I get this right?

**Comment by eugensim** [comment]
Area notification I get only via website [Profile>activity]
![image](https://cloud.githubusercontent.com/assets/8439643/14434928/1379322c-001e-11e6-9fd8-f95973e69171.png) 

The only one information that I reveceived via email is Mapillary week in numbers
![image](https://cloud.githubusercontent.com/assets/8439643/14434981/53ff64e2-001e-11e6-8ac9-602a15a696eb.png)

**Comment by gyllen** [comment]
@eugensim When you upload an image you do not get an email telling you that we registered your upload?

**Comment by eugensim** [comment]
Sorry, yes I missed that.

**Comment by gyllen** [comment]
@eugensim Ok we are currently not sending notifications to email for areas, they should however show up on your feed in your app. Do you have iOS or android?
