### ISSUE TITLE
[tools] keep user variables in a separate file

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1465]
I just re-downloaded the mapillary tools. As usual I had to manually edit a file to add my user variables (pass word, user name) this time it took a bit longer because the user variables go now in a different file than before.

It would be nice if the user variables were stored in a separate file (one that's not in the tools folder, so it doesn't get over ridden with the next update)

Other preferences could also be stored in this file, like a default variable for time split.

**Comment by ybkuang** [comment]
Good idea @de-vries Will add a config file to keep these variables in one place later.

**Comment by ybkuang** [comment]
This has been fixed in the new release. Closing.
