### ISSUE TITLE
Edit functionality has disappeared

### ISSUE THREAD

**Issue by robertogb** [mapillary/mapillary_issues#1466]
I have been one month without using Mapillary and now I have no option to edit photos, request blurs, edit positions and orientations, etc.
What is the problem, and how I can solve it?

**Comment by de-vries** [comment]
I see two possible reasons why you can't edit: you're not logged in, or you are using a browser that doesn't support webgl (in this case you see sequences as blue lines, in stead of grey, on the map). 
If it's not one of the above, please let it know, I'm sure the devs will be interested to investigate.

For me everything is working normally.

**Comment by robertogb** [comment]
Thanks for your answer. 
I'm using Firefox 41.0.2 in Windows Vista, which I recently updated. I have also tried the same version of Firefox in Linux Ubuntu 14.04, and I have the same issue.

I'm logged in, and trying to edit photos I have uploaded. Logged in or not, I always see the sequences in blue, and pink when I click over them.

**Comment by de-vries** [comment]
Your browser should support webgl. Make sure it does at www.doesmybrowsersupportwebgl.com
When you see the sequences in blue it means mapillary thinks your browser doesn't support webgl. So this probably is a bug.

**Comment by robertogb** [comment]
This is the output:

Yay

Context Name	webgl
Platform	Win32
Agent	Mozilla/5.0 (Windows NT 6.0; rv:41.0) Gecko/20100101 Firefox/41.0
Vendor	Mozilla
Version	WebGL 1.0
Renderer	Mozilla
Shading Language Version	WebGL GLSL ES 1.0

Max Vertex Attribs	16
Max Vertex Texture Image Units	0
Max Varying Vectors	9
Max Uniform Vectors	254

RGBA Bits	8, 8, 8, 8
Depth Bits	24

Max Combined Texture Image Units	16
Max Texture Size	4096
Max Cube Map Texture Size	4096
Num. Compressed Texture Formats	null

Max Render Buffer Size	4096
Max Viewport Dimensions	4096, 4096
Aliased Line Width Range	1, 1
Aliased Point Size Range	1, 8192
Supported Extensions	ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_half_float
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_lose_context
MOZ_WEBGL_lose_context
MOZ_WEBGL_compressed_texture_s3tc

**Comment by wegavision** [comment]
All my browser say NAY (Firefox, Edge, Iron)
I have change in firefoy webgl.force-enabled;false in true. No it say YEy but there is still no edit at the mapillary page.

**Comment by knikel** [comment]
@wegavision, @robertogb We've added a notice to the viewer when the WebGL isn't fully supported.

![notice](https://cloud.githubusercontent.com/assets/1574656/10843944/62a323e2-7efc-11e5-84df-2998e3cd28c9.png)
it leads to this short trouble shoot guide http://www.mapillary.com/map/help?q=webgl-support-and-the-mapillary-viewer

We have a strict check for these three properties as the library we're using (http://threejs.org/) relies on them for the functionality we need in the viewer. Unfortunately there is no blur and traffic sign annotation in the fallback viewer (non-WebGL). However, I'll fix the edit button for correcting positions so that view is reachable  to browsers with don't fully support WebGL.

**Comment by robertogb** [comment]
There is no way to solve the problem in the troubleshoot guide. At least, I would need to know if the problem is in the browser or in the GPU. I can try to change the browser, but I'm not going to invest in a new GPU just for this app. One month ago, this app was working with my current HW and SW, so I think the problem has been caused by  a change in your software. This is a pretty old problem, as you can see for example here:
https://www.khronos.org/webgl/public-mailing-list/archives/1305/msg00022.php

My new mobile phone was broken while using Mapillary, and now this software change make me unable to edit my photos, so  I will stop uploading any other photo to Mapillary until  I get a solution for this problem.

**Comment by knikel** [comment]
@robertogb sorry to hear that; we will look thoroughly with @oscarlorentzon whether we can drop the dependency for the floating point value that prevents you from using the mapillary on the web. Thanks for posting the resource. We'll keep you posted on this one!

**Comment by Klumbumbus** [comment]
Same problem for me. I can not edit blurs, while I was able to in the past. I'm missing OES_texture_float_linear with Firefox 41.0.2, IE 11 and Opera 32.0.1948.69

**Comment by wegavision** [comment]
now it works without doing anything

**Comment by knikel** [comment]
@robertogb, @Klumbumbus: We've relaxed the strictness of the WebGL check on our side, please clear your cache and see how mapillary.com works for you now. Thanks a lot for the feedback.

@wegavision: that's correct, there was an issue with hide whole container, while only blurs and traffic sign buttons should be hidden for non-gl-supported browsers.

**Comment by Klumbumbus** [comment]
It works for me now, (the sequence lines are now also grey instead of blue). Thanks.

**Comment by knikel** [comment]
:+1:  @Klumbumbus
