### ISSUE TITLE
Cannot upload certain panoramas

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1469]
To test the new panorama feature, I just made a bunch of panoramas with Googles camera app. I also found a lot of old ones. About 1/4 of those I tried uploading those with the Python script, I got the error message: "HTTP error: HTTP Error 400: Bad Request on PANO_20150123_154551.jpg"

I tried recompressing them, so one got from around 15 MB to 11 MB, but that did not help. Some images from the same sequence failed while most others got uploaded with success, so my guess is it is a bug. One of the failed, recompressed images, can be found at http://simonmikkelsen.dk/files/PANO_20150202_105625.jpg

**Comment by ybkuang** [comment]
@simonmikkelsen which script did you use to upload? (upload.py or upload_with_authetication)

**Comment by simonmikkelsen** [comment]
I used upload_with_authetication.py
Den 02/11/2015 08.55 skrev Yubin Kuang <notifications@github.com>:

**Comment by ybkuang** [comment]
I tried uploading the same file on my side and it went through. It could be related to the unstable connection to the server when uploading. How many threads were you using (NUMBER_THREADS)?maybe try using fewer threads and see if things go through smoother.

**Comment by simonmikkelsen** [comment]
I will try again when I get to a suitable connection. Usually I do not have issues, but I may have been unlucky. When I look at the log again, I can see that all the errors are grouped, so perhaps something have messed with the connection. I will repost the bug if it persists for me.
