### ISSUE TITLE
Cannot remove traffic sign when sign is at the top edge of photo

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1470]
At http://www.mapillary.com/map/im/Zok93RSECl2oLQ4dVGYdWA/photo is a sign marked, but the x is outside the photo, so I cant click it. (This probably also happens at the right edge)

**Comment by knikel** [comment]
@de-vries this has been fixed now :+1: 

![ts-edge](https://cloud.githubusercontent.com/assets/1574656/11304894/5ddaade4-8faa-11e5-89cf-597deb0b7e65.png)

**Comment by de-vries** [comment]
Neat! I'm impressed that this even works in the top right corner!
