### ISSUE TITLE
Can't click last sign in row in sign editor

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1471]
I like that the signs in the traffic sign editor get bigger when hovered, but when you hover a row the last sign moves to the next row, this makes it very jumpy and almost impossible to reach the last sign in any row. 

The 'getting bigger' is nice, but the 'taking up more space' not so.

Solution: don't change the font size of `.mapillarytrafficomarker:hover`, but use `transform: scale(1.8)`. also adding `transition-duration: 0.1s` to `.t` gives a nice effect.
**before**
![schermopname_2015-10-27_21_37_42](https://cloud.githubusercontent.com/assets/1449609/10771994/fd8eb53e-7cf3-11e5-82e6-d567ee0dfd5b.gif)

**after**
![schermopname_2015-10-27_21_36_25](https://cloud.githubusercontent.com/assets/1449609/10771955/e05983c2-7cf3-11e5-93d9-75736150520b.gif)

**Comment by knikel** [comment]
Awesome, thanks for the suggestion. Did it as you suggested!

**Comment by de-vries** [comment]
I didn't notice this in my first test, but this fix also affects the signs in the traffic-sign-overlay, I think that's undesirable.
`.ts-overlay-controls__sign .mapillarytrafficomarker {transform: scale(1);}` or `.ts-overlay-controls__sign .mapillarytrafficomarker {transform: none;}` should fix this. not sure witch one would be considered  'best practice'.

thanx for implementing @knikel !

**Comment by de-vries** [comment]
I found two other unintended consequences: the signs on the profile/ors page and in the game are also affected.
So it's probably best to limit the `.mapillarytrafficomarker:hover` changes to the map and the sign picker.


something like:
```
.traffic-sign-picker .mapillarytrafficomarker:hover, .imgl__map .mapillarytrafficomarker:hover {
    transform: scale(1.8, 1.8);
    cursor: pointer;
    z-index: 1000; }
```

**Comment by knikel** [comment]
Thanks @de-vries, yes, just noticed that behavior, will fix later today.

**Comment by knikel** [comment]
This feature is currently disabled, will be much nicer soon!
