### ISSUE TITLE
Sequence stops during play

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#1472]
When running in play mode, my sequence is stopping and showing the loading symbol at this [image](http://www.mapillary.com/map/im/IRwSMXPlI7cimR1RJPGmkw/photo).

**Comment by gyllen** [comment]
Did you upload this image this Sunday (we are currently investigating some replication problems from sunday)

**Comment by oscarlorentzon** [comment]
Related to #1468 .

**Comment by jotpe** [comment]
Yes, on sunday.

**Comment by gyllen** [comment]
@peterneubauer we need to recover some images from sunday the 25th of october.

**Comment by peterneubauer** [comment]
Working now.
