### ISSUE TITLE
@mention suggestions should show people that already commented first

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1473]
People that already commented on a photo should be shown first in the @mention suggestions for that photo, like how it works here on github

**Comment by knikel** [comment]
We're using external library for at mentions, these are good points. Labelling as a feature request.

**Comment by knikel** [comment]
We've worked recently on improving the commenting experience and we're using much better fuzzy search algorithms now. It doesn't necessarily always lists people who commented first, but overall the experience is much smoother.
