### ISSUE TITLE
Make "Hide Image" more easily accessible.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1476]
I would find it helpful if "Hide Image" could be shown along the other functions in "Edit". It is a long way to go through:
Edit => Edit => Hide This Image => Save and Review Changes => Send Change Request => Return to Image

**Comment by de-vries** [comment]
:+1:

**Comment by filipca** [comment]
I would even suggest to make it easy to hide several pictures in a sequence without lifting the fingers from the keyboard and while playing the sequence.  I do not say I will through my 500.000 pictures again.  But yesterday I had 1 fuzzy picture in 3.  
I could use my good camera if the Python scripts were humanised.

**Comment by jesolem** [comment]
I think @jrcarlsen 's suggestion is great. IF you are logged in you get a quick-button for hide. -> @knikel 

@filipca We (= @knikel ) are working on a desktop uploader (platform independent) that will be a more "human" alternative to the scripts. Hope you will like that.

**Comment by gyllen** [comment]
As discussed we will only support `delete`, in a near future. Closing.
