### ISSUE TITLE
Upload count reports an incorrect amount of images

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1477]
Android 5.1.1
Mapillary v1.48
Samsung Note 4

I had around 30000 images in the upload queue, but the progress was reported as "Uploading 400 of 90000 photos", and later "Uploading 1400 of 120000 photos".

The numbers above are not the actual numbers, but I think the number reported could have been exactly 3 or 4 times greater than the amount of photos I had. It felt like it counted the same files multiple times.

Unfortunately I was a bit busy when this happened and didn't note down the exact details. I hope it is still helpful anyway.

**Comment by ybkuang** [comment]
@jrcarlsen are you uploading on the phone or with the upload script?

**Comment by jrcarlsen** [comment]
Uploading from the phone.

**Comment by jrcarlsen** [comment]
This could be related to #1484

**Comment by peterneubauer** [comment]
Should be correct now, and it's just reporting the number of images in selected sequences.
