### ISSUE TITLE
honor 7 android app no big images in app

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1478]
Hi

got a huawei honor 7 to test now, usually able to make pictures with 20 MP with the camera app. Today I went out and started mapillary on a few tracks. I just got pictures in the 200 kb area and 1024 pixel size, as if the checkmark for lowres pictures is enabled. But it is not, enable or disable this setting does not make any differences, pictures taking with the mapillary app on that mobile are under 1024 pixels in size. Too bad.

aceini

**Comment by echeloni2p** [comment]
solved with android app 1.55

**Comment by polarbearing** [comment]
Where is 1.55, or was that a typo for 1.52 ?

**Comment by echeloni2p** [comment]
yeah, typo for 1.52
