### ISSUE TITLE
Time travel feature picks up on photos realy close in time

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1479]
Yesterday I rode into a street a few meters, stopped the camera, went back a bit to check the route, continued in the same direction and started the camera again. this didn't really result in overlapping sequences, but the first and last photo of the respective sequences are close. The time travel feature picked up on that and now http://www.mapillary.com/map/im/4YjmkY3M5_IK8bqWJwsVHQ/photo and http://www.mapillary.com/map/im/a5KUP-CaPeTV1RbiX8r9TA/photo are connected via it.

IMO there should be a minimum time difference (somewhere between one hour and one day) before two photos get connected via the time travel feature.

btw, I'm not sure if there are more differences between its precursor 'nearby photos' and the time travel feature than just the name, but I like the latter one much more!

**Comment by jesolem** [comment]
@de-vries Good input, we should have a minimum difference. 

(it is essentially the same except that they are now sorted and structured a little better)

**Comment by de-vries** [comment]
> it is essentially the same except that they are now sorted and structured a little better

then it must be the name ;)

**Comment by de-vries** [comment]
Another example: 
http://www.mapillary.com/map/im/gVlYkl2aHdJiGGY1TD6HOA/photo
http://www.mapillary.com/map/im/8Q5boJ4dpiG2B3cqLBFmBQ/photo
between those two photos the sequence got split, because more then 1000 photos, by sequence_split.py.

**Comment by de-vries** [comment]
here: http://www.mapillary.com/map/im/mCkupcggVvDKBeOmf83DZw/photo and here: http://www.mapillary.com/map/im/dPMMEe_ljHVappDGP5a59w/photo two mappers made independent from each other the same photo only 19 minutes apart.

**Comment by oscarlorentzon** [comment]
Thanks for reporting this @de-vries . 

I agree on both of your suggestions. There should be a minimum time difference for showing images under Time travel when different sequences have been taken by the same user. When sequences have been taken by different users there is a value in showing them even when they were captured at roughly the same time.

And to clarify on Photos nearby vs Time travel:

Photos nearby showed a list of all photos taken nearby looking roughly in the same direction, i.e. many photos from a single sequence could potentially be listed.

Time travel determines the best match (based on distance, rotation etc) from each sequence nearby, i.e. we show only one image from every sequence.

Sorting is now also done on the capture date whereas before it was based on viewing direction.

Then of course the name change... So as mentioned above, better sorting and structuring.

And on to the bug fix. We now require a twelve hour diff for photos from the same user to show up in the Time travel list. There is no time threshold for photos from different users.

**Comment by de-vries** [comment]
Nice! and thanks for the detailed answer.
