### ISSUE TITLE
[Time travel] less than perfect links

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1480]
I made two photos 1.5 months apart they should be linked via  the time travel feature, but the photos they are linked to are 4 photos apart.
Here are the photos:
http://www.mapillary.com/map/im/luRgaaTsVQ-lb_vGLWeSbw/photo
http://www.mapillary.com/map/im/aWBLfba9hPc9al0DExildw/photo

I don't know if this is due to the quality of the gps data, or any other reason. I also don't know if there is anything that can be done about it, but hé, you said you like bug reports...

**Comment by oscarlorentzon** [comment]
Thanks for reporting @de-vries .

This can occur if the GPS positions of the two sequences are a bit shifted and our reconstruction algorithm does not pick up enough similarities between the images in the two sequences. The shift will then not be corrected. We will look into this.

**Comment by de-vries** [comment]
I looked it up in JOSM and the sequences are indeed a bit shifted:
![selectie_103](https://cloud.githubusercontent.com/assets/1449609/10869960/f57c7100-80be-11e5-91a7-8baef83f9d2e.png)
The circles are the photos with the red sticker on the lamppost and the triangles are the linked photos. *The other two sequences are in the opposite direction*

But if the linking was purely location based there would be more logical candidates for linking and those would be 2 or 3 photos apart.

**Comment by oscarlorentzon** [comment]
We have improved our 3D reconstruction algorithms (http://blog.mapillary.com/tech/2017/07/26/improving-3d-reconstruction-with-semantic-understanding.html) and the time travel links for these sequences now look very good even though the original GPS positions for the respective tracks have large drift with respect to each other.

**Comment by de-vries** [comment]
nice job!
