### ISSUE TITLE
Handle notifications on the website, not in emails

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1481]
If I'm not mistaken I currently have the choice of having no notification or an email being sent. Emails are not private and I don't like that information on what blurs I requested and things like that being sent potentially unencrypted by email. Please give the option to handle that kind of notifications on the website in an inbox, just like it is here on github.

**Comment by knikel** [comment]
Thanks for the feedback @mxa, this is on a roadmap, coming soon.

**Comment by mxa** [comment]
I think you got it, but let me elaborate a little never the less. The amount of personal information that can be associated with the uploader/author of the images is already worrying as is. Start and endpoints of travel often lead to workplace and home in case of commuters the time of the pictures can be estimated by sunlight and shadows, etc. The only thin layer of privacy is the username. That's why I don't want any emails from mapillary that contain my username or any of my activity, because my email is the realname and can be associated with a real person. I think we should be careful with that kind of information.

**Comment by knikel** [comment]
@mxa understood, these are legitimate concerns. You'll be able to disable all email communcations and rely solely on the feed.

We will be reworking user pages/settings too, one of the tasks there is to give users the option to hide parts of their activity in their profile and their photos. This will be effective in the user interface, but not API, you can read more of the discussion on that topic in https://github.com/mapillary/mapillary_issues/issues/1390#issuecomment-141227120 .

HTTPS everywhere is also coming – (ping @gyllen).

**Comment by gyllen** [comment]
We are on this issue now

**Comment by nickplesha** [comment]
It's now possible to choose which emails/notifications you want to receive in your user profile: https://www.mapillary.com/app/settings/notifications
