### ISSUE TITLE
Cannot add ArcGIS connection to Mapillary account

### ISSUE THREAD

**Issue by amarinelli** [mapillary/mapillary_issues#1482]
The following errors are returned when trying to connect:

`{"code":"parameter_missing","message":"One or more parameters are missing"}`

>error=invalid_request
>error_description=You do not have permissions to access this application

**Comment by gyllen** [comment]
Hi @amarinelli thanks for reporting this, we are going to fix the error reporting. At the moment you need a trial of Mapillary for ArcGIS to be able to link your account https://marketplace.arcgis.com/listing.html?id=6d0871cf6b8a453db8bc858318f41b89

**Comment by amarinelli** [comment]
Okay, makes sense. I knew there was a Mapillary extension/add-in component for ArcGIS...but did not know it was in the marketplace, etc. Thanks.

**Comment by gyllen** [comment]
Keeping this issue open until we added correct error handling, we have some pretty awesome features in the markeplace app so feel free to try it out.

**Comment by amarinelli** [comment]
:thumbsup: thanks @gyllen

**Comment by gyllen** [comment]
@amarinelli You checked the marketplace app out yet?
