### ISSUE TITLE
False motion with stuck speed values in android capturing

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1483]
When testing v.1.47 I had several occasions when the app continued shooting while being stationary at the traffic light. 

Checking the log for the identical frames I found that the speed was stuck at one particular non-zero value at each stop, e.g. in one case reported as "Moving speed in m/s: 2.97808", in another "m/s: 4.5818753" with all 5 or 7 digits exactly the same over the whole time.

Even when capturing stopped while flashing "too slow", there are stuck identical values in the log: "m/s: 1.1087815".

Log on request.

**Comment by polarbearing** [comment]
Testing 1.52 still have periods of "frozen" non-zero speed values which occasionally are over the threshold. What is the speed threshold anyway?

**Comment by polarbearing** [comment]
Testing 1.58 today, which again has the frozen speed values while standing, and having MAPGPSAccuracyMeters=5.0.

**Comment by polarbearing** [comment]
Still there in 1.82, see comment in #1741

**Comment by peterneubauer** [comment]
Mmh, this is basically the same issue as not getting location updates. We are not getting any callbacks form the Location APIs in these cases, and both location and speed are read from the location update. Not much to do it there is no GPS update for a minute - do you have any good idea on how to deal with that?

We are considering to revamp the whole process and just save the location/GPX metadata together with other info, and then insert the Mapillary tags not while capturing, but before upload. Then we have the whole track info and could potentially e.g. interpolate etc.

**Comment by polarbearing** [comment]
I'm not familiar with the 'location update' methods in android.  I just know that a traditional NMEA device gives me the current speed/location, no matter what, and leaves any interpretation to the consuming application.

**Comment by peterneubauer** [comment]
This should be fixed now.
