### ISSUE TITLE
Wrong sequence and image count in review mode and upload of v1.47

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1484]
v.1.47 (Android) has introduced two folders "sequences" and "tumbs" in the mapillary folder. It seems that the app attempts to upload them, and reports them in the review menu. 

I counted (after offline review) 321 real images and 375 thumbs, in 8 regular folders. The review menu reports 10 sequences, one of them containing 376 (i.e. thumbs plus 1), one of them empty, the others 163+15+11+85+7+4+2+34=321. So the thumbs and frames add to 697, the upload heading shows 698 photos in 10 sequences. The notification counts 697 again. 

Indeed the app uploads from the thumbs folder:
Uploading pic /storage/sdcard0/mapillary/thumbs/2015_11_01_16_04_27_951.jpg
ploadRequested status: 204

although it fails on some of them:
ERROR: error uploading - /storage/sdcard0/mapillary/thumbs/2015_11_01_16_05_47_596.jpg: open failed: ENOENT (No such file or directory)

Some time at night it gets stuck with
Mon Nov 02 03:13:43 CET 2015 : app.mapillary.android.sync.UploadService  - Done, errors Network error
so we continue next morning with 34 left thumbs, it even tries to upload a 'dummy':
Uploading pic /storage/sdcard0/mapillary/thumbs/dummy (0 mb)to http://mapillary.uploads.images.s3.amazonaws.com/

Finally we have an empty folder 'sequences' and a thumbs folder with a new dummy file in it, and the review mode reports one empty sequence.

Log on request.

Another problem:
I have not found yet how to review individual images in a sequence in the app. However it seems to be overly easy to delete a whole sequence be just swiping it.

**Comment by polarbearing** [comment]
Just to add that the confirmation mail only counts the regular images: "The 321 photos you uploaded in 8 sequences..."

**Comment by peterneubauer** [comment]
@polarbearing that might be a migration problem since the thumbs folder is in the sequence folder in this case. Will log this as a bug. Review should be working in the alpha builds again, join https://play.google.com/apps/testing/app.mapillary

**Comment by polarbearing** [comment]
1.47 did create the $mountpoint/mapillary/sequences folder, but did not use it, it remained empty, it used however the $mountpoint/mapillary/thumbs folder. 

1.52 does not create the $mountpoint/mapillary/sequences folder anymore, and uses the $mountpoint/thumbs folder again. Thus currently in 1.52 the review report is correct and I can access the pictures.

**Comment by polarbearing** [comment]
Is the 1.52 in the dropbox the same as the alpha build in goggleplay you mentioned?

**Comment by peterneubauer** [comment]
Should be gone now with v 1.54?
