### ISSUE TITLE
New sign found but not added to stat page

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1485]
Hi
I have been mapping a new area in my home town this weekend and there was some new  sign that I did discovered such as:
http://www.mapillary.com/map/im/8AcOS0qN6c_JHZMjpKuEOQ/photo
Those sign has not been added to my stat page:
http://www.mapillary.com/profile/beer119/ors

Is that a bug? Or do you add them later?

**Comment by beer119** [comment]
Here is another example of the problem. The tryangle sign was picked correct by your software but was not added to my state page:
https://www.mapillary.com/map/im/0zgSaIem0wwHh4rR-FQ-ZA/photo

**Comment by richlv** [comment]
should this be closed as a duplicate of #1460, maybe ?

**Comment by beer119** [comment]
I think so

**Comment by beer119** [comment]
Any news abouut this issue?

**Comment by jesolem** [comment]
@knikel is tracking this under #1460
