### ISSUE TITLE
manual uploaded picture not appearing

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1486]
I made a few hundred pictures today with the Open Camera app on my mobile with a non 4:3 image resolution.
Uploading those in 100er batches via website was quite fast and easy, although the small map beside the upload buttons did only show 3-5 icons per 100er batch (as if only 3-5 pictures were geotagged and uploaded).
Now the profile page shows "uploaded 937 pictures" and a bit later "aceini added 937 photos".
But the image for this added photos is a dead link http://www.mapillary.com/map/s/OuJVjyD-aFhxRocHBCsUng and it shows a broken image symbol.
Also the profile shows "no image in processing".
Ok, now on reload, it shows 937 still prrocessing. Looks like process is slow. I keep a eye on it.

Is something broken with manual upload?

aceini/echeloni2p

**Comment by peterneubauer** [comment]
No, the manual upload is fine. We paused processing, that's why the images are taking some more time to go through the pipeline. Stay tuned!

**Comment by gyllen** [comment]
yes this was a delay in processing, now fixed
