### ISSUE TITLE
manual upload note on website is misleading/wrong

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1489]
On the page for the manual upload it says:
"Make sure the photos you plan to upload have correct EXIF data and **compass angle**. 

Required EXIF tags are "GPSLongitude", "GPSLatitude", and time stamp (for example "DateTimeOriginal"). **If compass angle is missing it will be set to north** (you can edit that later)."
However it seems like the script interpolate_direction.py is run on the images, their direction in **not** set to north.

**Comment by mprins** [comment]
these paragraphs describe different procedures, which is why the have a different heading, the web upload does not use the python scripts

**Comment by mxa** [comment]
Anyway it is wrong. The direction is not set to north but it is interpolated between the waypoint direction.

**Comment by ybkuang** [comment]
@max, can you give us a link to the sequence where the directions are interpolated?

**Comment by mxa** [comment]
This track has the orientation interpolated in driving direction, they are not set to north. http://www.mapillary.com/map/im/6gqftbuQ5yPLvhw8W8yofw/map

**Comment by ybkuang** [comment]
@mxa I checked the exif of the images in that sequence. They actually have GPS Img Direction in the exif which we use as the compass angle measurement.

**Comment by mxa** [comment]
Ugh. Then it might be a problem of that camera Garmin Virb elite that is doing that kind of interpolation on the camera, because the image is clearly taken in the direction of -90 degrees to the path :( Thanks for checking anyway.

**Comment by ybkuang** [comment]
@mxa Yes. It could be the case Garmin is interpolating. You can edit the compass angles for the full sequence with -90 degree in the editor.

**Comment by mxa** [comment]
Done. Thanks.
