### ISSUE TITLE
viewer not reset with pointcloud on changes...

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1492]
Hi!

Pointcloud viewer is great, but has some issues:
- if you click one picture forward or backward, new points are not loaded, soon you get out of the pointcloud
- if you are in point cloud view, you can tilt and pan, fine, if you switch to map (with the button above) and choose another track/picture/...) and you click on picture again, you are still in point cloud view, but navigation is NOT point cloud, but picture mode.

aceini

**Comment by oscarlorentzon** [comment]
Thanks for reporting this @echeloni2p .

1. No, we do not add more points when orbiting or moving between image frames when in point cloud mode. The points you see are the ones that has been reconstructed for the images close to the current one when you decide to click to show the point cloud. If you move away from the point cloud either by navigating or clicking the map you have to hide the point cloud and then click again to show the point cloud for the new position.

2. Point cloud mode is now disabled when you switch to the Map tab. Therefore you will always get back to the regular view when returning to the photo tab.

**Comment by abienvenu** [comment]
This does not solve completely the problem : pointcloud viewing mode is not tied to pointcloud navigation mode.
In photo mode, if you switch to the next/previous photo in pointcloud mode, using the up/down key (or clicking the minimap), you stay in pointcloud mode (fine), but navigation is NOT point cloud, but picture mode.

**Comment by oscarlorentzon** [comment]
@abienvenu As you say there are two modes of navigation (moving the camera through 3D space):

1. Regular - navigation from photo to photo with transitions in between.
2. Orbit - point cloud navigation with zoom, look around, orbiting and panning.

The regular navigation is done with the keyboard through the arrow keys or with the navigation arrows shown in the viewer. Orbit navigation is done with the mouse controls explained in the point cloud controls dialog which is shown and can be expanded when in point cloud mode:

![screen shot 2015-11-13 at 10 16 02](https://cloud.githubusercontent.com/assets/2492302/11142875/cf0f1b72-89f0-11e5-986a-13ca98613361.png)

Notice the last row in the image above. Esc is used for toggling between the two navigation modes when showing the point cloud. That is if you click the up or down key and enter regular navigation mode you can always press Esc to get back to orbit mode again. And when in orbit mode you can press Esc to get back to the photo you came from. 

What this means is that you can do all regular navigation in point cloud mode like playing a sequence or navigating. And when you want an overview you press Esc and use the orbit controls in the image above (the Esc command is only available when you are stopped, i.e. not when playing a sequence).

Hope this helps.

**Comment by abienvenu** [comment]
Thank you, this definitely helps. I thought the "Esc" key would switch between "Orbit" and "Look around" modes, both in point cloud mode. I thought it was a way to orbit without having to press "Shift".

You may change the wording to "Change control mode - Esc (point cloud / regular)".

Now I still think the interface should stick to the same control mode, even when the user goes to another image.

**Comment by oscarlorentzon** [comment]
Agree on the wording @abienvenu . It has now been changed ot "Change controls - Esc (Point cloud / Regular)".

@echeloni2p Although we have not adressed your first point (extend the point cloud dynamically when navigating) I will close this issue since the problem in the headline has been fixed. The point cloud feature is what it is for now, a static point cloud for the area around the image you decide to show it for. We will keep your suggestion in mind for the future.

Thanks again for your suggestions.
