### ISSUE TITLE
Corrupted picture blocks sequence and interferes with phone's camera app

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1493]
I want to report a problem with a specific sequence of photos that seems to indicate a problem with the Android App (version 1.39).
It may, at least partially be related to  #791 and #857

The sequence in question is http://www.mapillary.com/map/s/qVAk-eIx4X2XwQJgWKDawg

I took photographs on bicycle on 7 Nov 2015 in three separate sequences that should have been in total about 5000 photos.

When I came home and looked at "Review", before starting the upload, I noticed a single sequence with a bit more than 1500 photos (I don't remember the exact number). I was a bit surprised that there was only one sequence, I had expected at least three, but I did not do the above calculation and simply started the upload.
I uploaded, according to the "Feed" page of the app:
   added 1085 on 07 nov 18:07
   uploaded 4372 on 08 nov 09:30
   added 4372 on 08 nov 09:30
   uploaded 4882 on 08 nov 19:35
   added 4882 0n 08 nov 19:35
   uploaded 687 on 09 nov 10:06
   added 687 on 09 nov 10:06
   uploaded 454 on 09 nov 12:23
   uploaded 40 photos on 09 nov 13:50
   added 1197 photos on 09 nov 13:19

... and the Review page constantly showed 1518 photos still to upload.

I stooped and looked into the micro SD from the computer where I saw 87 folders with names like 2015_11_07_09_50_34_540___Mapillary. They were all all empty, but the last one (2015_11_07_09_53_45_239___Mapillary) that contained 1516 valid jpg files and two damaged files named 2015_11_07_12_19_08_746.jpg and 2015_11_07_12_19_10_795.jpg
Looking closer at the uploaded photos on the site I noticed that the last photo that actually was uploaded (http://www.mapillary.com/map/im/SQzRoJNVJk_ZOJinv8JYPg/photo, time stamp of 12:19:10) is obviously corrupted and seems to show to partial photos with a strange colour effect, and when looking into the micro SD of the smartphone from my computer I see a file size of zero for  both the above photos.
The server seems to have all photos up to the corrupt ones (at 12:19) but none of the later ones

The app seems to have uploaded over and over again the same photos to the server.

I noted that the phone's camera app could not store pictures on the SD card. The save picture process seemed to hang while the problem was present.

Can you see the multiple, superimposed uploads on the server side?

To get rid of the problem, I had to format the microSD .

The embarrassing thing was that I took part in an OSM mapping party :-( and the other participants wanted to use my pictures.

**Comment by echeloni2p** [comment]
Hey

try the new app. And usual you can delete the folders with the pictures in it (or upload those pictures manually).
If the review tab does not show all pictures, not all are available on the medium you saved to.
One question: is the SD card 100% working fine? A lot of faulty ones are sold, even some with showing 128GB capacity, but having only 128MB...

Also, if you uploaded those, they should appear as tracks in your upload section. You can hide whole sequences.

aceini

**Comment by voschix** [comment]
My app version is 1.39, the one that is on Google Play.
No, I could not delete the folders, neither from the app (where I only found the possibility to delete single picture files) nor from the computer.
I have used the same 32G microSD for more than 50000 Mapillary photos without any hint of a problem. 
I had no hint during taking the photos that something was not working (I had the shutter sound on). 
And the second thing, that I did not like, is that the uploading did not stop on the last (faulty) photo, but continued.
The only recovery method that worked was to wipe the micro SD in the computer. Had I been on a longer trip, as I do from time to time, I would only have found out after the end that I had missing photos. During a bicycle trip, I normally have no computer where to wipe clear SD cards, I travel with just the smartphone and an additional GPS for navigation purposes.
I really would like to understand what happened, because it puts my entire operating scenario in question. 
If mine is a rare event, OK, but I have seen that at least two other users have reported picture corruptions that looked similar to the one in my case (#791 and #857)

**Comment by echeloni2p** [comment]
Hi

you can try to download the latest mapillary app direct from mapillary.com - the link in the left down area, it is the latest available version, not released on appstore.
Interestingly you could not write to sd card with computer, that sounds like a corrupted filesystem. Did not happend to me in >1 year mapillary with >130k pics.
Also I did not have had picture corruptions yet.  But who knows.

aceini

**Comment by voschix** [comment]
I have to correct me. I did not manage to wipe the micro SD, but replaced it with new freshly formatted one.
From reading a bit around on the internet, I gather that this is well-known problem of micro SD cards. They fail rather frequently and when they do, they go in read-only mode to protect the data on the card from any overwriting attempt. 
Remains the problem that the Mapillary app does not recognise this and continues as nothing had happened.

**Comment by peterneubauer** [comment]
So, is v1.56 working better for you regarding upload and review? We have put some effort into these areas with thumbnail caching and other nice improvements. Closing this for now...

**Comment by voschix** [comment]
As the root cause was most likely a spontaneous fault of the microSD there is no way to test, if the new version of the App would have behaved better.
Version 1.39 failed to survive on two accounts:
1) when taking photos, it did not alert me that the microSD had gone in read only mode, instead it made me believe that it was happily taking photos
2) The upload process did not terminate when it encountered the damaged photo file, i.e. it cycled and loaded the same photos over and over again into the same sequence on the Mapillary server (where they still are, because I do not know how to remove the duplicates - see [this sequence] (https://www.mapillary.com/map/s/qVAk-eIx4X2XwQJgWKDawg) )
