### ISSUE TITLE
errors with position/arrows on track

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1496]
Hi!

http://www.mapillary.com/map/im/WbDPnRH6uhZLidi4b0EGvw/photo
the arrows are a bit strange, the recognition of the postitions and all...
It should mostly only go forward, but it jumps forward, right, right, forward...

whats the issue?

**Comment by paulinus** [comment]
Hi @echeloni2p,

that is the SfM algorithm having problems in finding the camera motion. This can happen for several reasons, but the most common is the little overlap between the pictures.

Also the focal length of the HTC One M9 seem incorrect in our database. Will fix that and retry, but i would be surprised that it works given the small overlaps.

thanks for reporting,
pau

**Comment by echeloni2p** [comment]
Hi
ok, thank you. I assumed issues with the compass angle, as that was completely off.
This did not happened before, it started now with the new android app 1.52 and the new non-4:3 images in 20 MP size with the HTC One M9. Older tracks with even less overlap did not show that behaviour.
I´ll keep a eye on it, but I cannot provide better images in one go if I run too fast with the bike. All I can do is moving the pictures to better position afterwards manually...

aceini

**Comment by paulinus** [comment]
Fixing the focal length did not help much. I've edited the angles so that they point to the direction of movement. The edit will be online in a few days. I will have another look then.
thanks,
pau

**Comment by echeloni2p** [comment]
Hi!

I do not see any changes yet.
But I still see "52 pictures left to process" in my profile for some days now...

acein/echelon

**Comment by paulinus** [comment]
The arrows improved with the latest reconstruction algorithms; no wrong directions anymore. Still, some missing when the distance between images is large but that is to be expected.
