### ISSUE TITLE
United States link in main page search is wrong

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1497]
If you click in the search box on the main page and then click on the "United States" from the dropdown list that appears, it takes you to Germany instead of the U.S.

It looks like it is pointing at http://www.mapillary.com/map/explore/united-states when it should be pointing at http://www.mapillary.com/map/explore/united-states-of-america

**Comment by knikel** [comment]
@ToeBee We've phased out that part of the website. You can find US with better country shape here now: http://www.mapillary.com/map/places/85633793

Try http://www.mapillary.com/map/stats to find the country that interests you which.

**Comment by ToeBee** [comment]
Umm you've phased out your main home page? This issue is about a link on your main website leading to a page that is different than the link text implies. So if you've phased out the /explore/ pages then your main home page needs to be updated to reflect this.

![mapillary_usa_link](https://cloud.githubusercontent.com/assets/348948/11096759/4be58078-8861-11e5-8b03-300bf97f09d5.png)

**Comment by knikel** [comment]
@ToeBee Sorry, I was referring to `/explore/:country` page in general being phased out. The searchbox in question has been updated at the same time; would you mind clearing you cache and see if that helps? Sorry about the hassle.
<img width="854" alt="search" src="https://cloud.githubusercontent.com/assets/1574656/11097482/02294854-88a0-11e5-95e8-e15abb0bc9e1.png">

**Comment by ToeBee** [comment]
Yeah, it is working now.
