### ISSUE TITLE
Improve Compass Angle edition

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1498]
Hi,

I'd like to suggest an improvement to the Edit window, specifically to the Compass Angle edition. Currently we have a ```+``` and a ```-``` button to edit the angle. However the only change perceived on the map is the inclination of the ```>``` symbol that indicates the right angle.

My suggestion is to include a line like a projection from the point to the given angle, like the green line on the following image:

![image](https://cloud.githubusercontent.com/assets/397851/11094782/cee2e9cc-8878-11e5-9324-c82162ce63cf.png)

Thanks.

**Comment by knikel** [comment]
Closing in favour of #638

**Comment by nighto** [comment]
Yeah, sounds good to me! :)
