### ISSUE TITLE
activating point cloud should disable blur/sign mode

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1499]
there is no use of blurring or marking a traffic sign in the point cloud mode. So this mode should be drop.
Right now after activating the point cloud i cannot navigate in 3D space, but am starting a blur (if this was active).

**Comment by oscarlorentzon** [comment]
Thanks for reporting this @HolgerJeromin .

It is no longer possible to edit blurs or traffic signs when in point cloud mode. Also, when editing blurs or traffic signs it is not possible to show the point cloud.
