### ISSUE TITLE
iOS "better pictures" tips need a lot of work

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1501]
I upgraded the iOS app to 4.0.3, opened the Capture screen, and selected Riding. It showed some kind of tutorial for taking better pictures, but it seems buggy. The pure white screen with text in the middle doesn't look particularly good. And it says "TAKING BETTER PICTURES X/Y". What is X/Y? Was it supposed to say 1/2 because it's the first of the two tips?

![img_0312](https://cloud.githubusercontent.com/assets/101955/11100625/1ed5b154-8891-11e5-9065-783863d8ceec.PNG)

I was going to complain that it appears even though I already watched the initial tutorial and I have been contributing pictures for months, but it's worse than that: it shows every single time I switch modes. Switch to walking auto, tips appear. Switch to panorama, tip appears (same as one in walking auto). Switch back to walking auto, same tips appear again. They should only appear once.

When the capture screen is activated, this latest update added two extra taps before you can start taking photos, one to select the mode (that seems handy) and another to dismiss the tips I already know about.

**Comment by millenbop** [comment]
It shouldn't be included in this release at all! 

What you see is an early version and it has already been fixed on another branch. I'll submit an update today with the tutorial disabled (and it will then be back in another release, probably the next one after).

**Comment by nicolas17** [comment]
Today I took actual pictures (bus, riding mode, 1s interval) and saw another new feature: notifications when I reach N photos. It felt a bit silly to get "great! keep going" notifications on 10, 25, and 50 photos when taking one photo per second... Is that also part of the "early version new feature that shouldn't be in this release"?

**Comment by millenbop** [comment]
Yup that's also some old crap that shouldn't be in the build :) It's also removed in the next version.
