### ISSUE TITLE
How can I delete own Mapillary images?

### ISSUE THREAD

**Issue by ErnstHowie** [mapillary/mapillary_issues#1502]
I uploaded some images to Mapillary. But I want to remove them now. How can I delete those images? I can't find a way. Please give me some help if anyone knows. Thanks in advance!

**Comment by nicolas17** [comment]
If the photo is just not useful, you can hide it (click Edit, then Hide this Image, then Save and Review Changes), but I think users can still access the photo and even un-hide it.

If there are copyright or privacy reasons to delete them permanently, click 'Flag' and mention your reason to delete it, and a Mapillary admin should take care of it.

**Comment by ErnstHowie** [comment]
OK. Thanks very much! But I think it will be better if there is a way that users can delete their own images.

**Comment by peterneubauer** [comment]
Yeah we are still thinking about what that would mean for all the connected information that might be attached to it ...

**Comment by dex2000** [comment]
"thinking about" ...
With what solution? I have put 3 (THREE!) delete-requests the last 50 Hours for an image, and its still there?! The Review is not working really and why the f* it can be NOT deleted without review? I(!) want to delete it, its my(!) picture and nobody is working on it. 

The background for that problem: me (and i think a lot of users) would be upload a lot of more pictures if the review would be not so hard broken like now. I have not uploaded lot of images in the past, but every time i think before "Uh, maybe ... ok, not"

**Comment by nicolas17** [comment]
Deleting a photo is not so easy as all the navigation and SfM mesh information from adjacent photos has to be updated too. It's not just a delete of a table row and a file.

The devs have said elsewhere that the entire edit/review system is being revamped.

**Comment by dex2000** [comment]
Oops, what i mean was hiding.

**Comment by peterneubauer** [comment]
So,
@gyllen and I are on that right now. We are revamping the way we do changesets, with different categories per changeset - location change, deletion (yes, instead of hiding :) and sequence change (for breaking up sequences.)

This will take some more week since the changes are quite big on the backend - we want to support auto-approving your own changes to won content like you request, and also be able to geolocate changeset in order to promote community members to be able to approve changes in their areas.

Starting next week we will try out converting the existing changesets to new ones. Meanwhile, we will try to make a run and approve the pending hide-requests ASAP, sorry for the delay.

**Comment by dex2000** [comment]
Sounds good, thx.

**Comment by nicolas17** [comment]
What's the status of this with the new website?

**Comment by gyllen** [comment]
@nicolas17 We are getting there, new editor and changeset API gives us ability to do this

**Comment by danbjoseph** [comment]
I am interested in being able to delete images because the first couple in a sequence I uploaded had the incorrect GPS coordinates. I was using a Garmin Virb Elite and I guess I didn't wait long enough for a location fix. See those off to the right in the screenshot. 

![screen shot 2016-08-13 at 4 56 30 pm](https://cloud.githubusercontent.com/assets/4806884/17645707/53c6720e-617b-11e6-9e5b-37791c27de06.png)

**Comment by gyllen** [comment]
@danbjoseph We will very soon roll out this functionality, sorry for the delay.

**Comment by strainu** [comment]
Is this available now?

**Comment by peterneubauer** [comment]
Yes,
You can do deletions in the editor on the site.

**Comment by danbjoseph** [comment]
Thank you for opening up this functionality to users.

**Comment by fredao** [comment]
@peterneubauer I uploaded some terrible pictures - unvoluntary - where do I find the editor to delete them?

**Comment by danbjoseph** [comment]
In the Mapillary interface if you select a photo in the sequence and then click the 3 dot icon in the right-side options it will bring up the 'Photo details' box. Click `Edit current sequence`.
![screen shot 2017-04-23 at 12 09 31 pm](https://cloud.githubusercontent.com/assets/4806884/25315102/cb9ff908-281d-11e7-8ea2-b5261ae2f263.png)
You can then select and delete individual photos with the `Delete Photo` option or mark the entire sequence for deletion with `Delete sequence` (edits deleting photos or sequences sometimes take a little longer to get approved in their system but you can always drop an email to support if it's been a couple of days and nothing has happened. they've always been very responsive when i've reached out).
![screen shot 2017-04-23 at 12 09 57 pm](https://cloud.githubusercontent.com/assets/4806884/25315104/ccc1d5ea-281d-11e7-8f8c-e4aa1f0ec6c7.png)

**Comment by fredao** [comment]
Thank you for your quick answer. I uploaded really a terrific sequence. So
it is important for me. :-)

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu

Am 23.04.2017 11:14 schrieb "Dan Joseph" <notifications@github.com>:

**Comment by katrinhumal** [comment]
For future reference for anyone who stumbles upon this thread - we have the editor functions explained here: https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences

**Comment by peterneubauer** [comment]
Nice,
good work @katrinhumal!

**Comment by fredao** [comment]
Am 27.04.2017 08:14 schrieb "Peter Neubauer" <notifications@github.com>:

Nice,
good work @katrinhumal!


+1

## Manfred Reiter - mobile -
## please excuse typos and brevity
## http://weeklyOSM.eu


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/1502#issuecomment-297709429>,
or mute the thread

**Comment by PhoneixS** [comment]
I think this can now be closed.

**Comment by katrinhumal** [comment]
Good point.

**Comment by mgifford** [comment]
I don't have the option to edit the image.  I just took some crappy ones highlighting my arm:

<img width="808" alt="screen shot 2018-05-03 at 8 27 25 am" src="https://user-images.githubusercontent.com/116832/39576371-e6de98d6-4eab-11e8-8369-adc4e699566c.png">

**Comment by katrinhumal** [comment]
@mgifford It looks as if you're not signed in - can you make sure to log in and see if there's a difference? Editing (including deleting) is not possible anonymously.

**Comment by danbjoseph** [comment]
when logged in you should be able to see an option to edit the sequence
![screen shot 2018-05-03 at 8 39 58 am](https://user-images.githubusercontent.com/4806884/39576875-a63bbdc0-4ead-11e8-99db-34b1d7927610.png)
and then, once you've entered the editor, you can delete individual images or even the whole sequence
![screen shot 2018-05-03 at 8 39 47 am](https://user-images.githubusercontent.com/4806884/39576879-aa1be488-4ead-11e8-92c2-b7c78b7b551f.png)

**Comment by mgifford** [comment]
here is a bigger screen shot.  I am logged in from what I can tell.  I can't see an edit option. 

<img width="1436" alt="screen shot from mapillary" src="https://user-images.githubusercontent.com/116832/39576961-f7780dd8-4ead-11e8-9719-a6b39359ae86.png">

**Comment by katrinhumal** [comment]
@mgifford When logged in, you should see a little `me` and a cog wheel at the top right of your profile, like this:
<img width="336" alt="screenshot 2018-05-03 14 45 24" src="https://user-images.githubusercontent.com/16334352/39577144-c4f969d2-4ee0-11e8-848e-afc124d95018.png">

Click on the arrow next to the username (in the screenshot you provided) to close the profile and see the sign in option.

**Comment by mgifford** [comment]
Ok..  That is confusing..  Does work now.

**Comment by katrinhumal** [comment]
Great that it works. I'll pass the feedback to the team that it was not obvious to find the sign in button.

**Comment by mgifford** [comment]
@katrinhumal it is more that I didn't realize i wasn't signed in.  I thought I had logged in.  Tried it several times actually to login with Google & OpenStreet Map.  Just kept going back to that screen.  Eventually created a password & logged in the old school way.  

When I see mgifford in the top right corner of the page, I assume I'm logged in.  That's how it works almost everywhere else.

**Comment by katrinhumal** [comment]
@mgifford I see! It looks like something is going on with our login. Thanks for pointing it out, I'll ask our developers to take a look.
