### ISSUE TITLE
Add 3D touch quick actions to iOS app

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1503]
On iPhone 6s (or on older devices [with some hacking](http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=revealmenuDp) :smirk:), it would be handy to have 3D touch quick actions on the Mapillary icon on the home screen, to quickly start capturing.

Something like this but with icons and functionality :smiley:

![Hacked-up Mapillary showing quick actions](https://cloud.githubusercontent.com/assets/101955/11102004/a628e2b4-8898-11e5-80c8-615ec93547fe.PNG)

I'm not sure if having "upload" there would be useful, just showing the possibilities (with the dynamic subtitle).

**Comment by millenbop** [comment]
It's funny because we literally had the same discussion yesterday! We think it's a great idea. It will be added in a build very soon.

**Comment by millenbop** [comment]
Well, I managed to squeeze it in into today's build. I didn't have time to add the upload feature before submitting though, I'll add that later. If all goes well, you should have this in about a week:

![img_0590](https://cloud.githubusercontent.com/assets/12835674/11119997/84b98510-894d-11e5-814f-2fcf3d6a8beb.JPG)

(dunno why the pic is rotated)

**Comment by nicolas17** [comment]
This has now reached the App Store :smiley:
