### ISSUE TITLE
Zoom goes from Barcelona [editing and searching] to Sudan or Egypt

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1505]
I don't know why but with new maps and shapes when I edit one pic (example Pere IV from Barcelona) the map takes me to Sudan (Africa) if I don't stop it. Why the map does it?+
with last Firefox & Chrome on Win 7

**Comment by voschix** [comment]
I do have a problem that seems to be very similar, but only on Firefox (42.0) on Windows 10 (map zooms out and centres on Cyprus when I put it on Malmo, Sweden, when I try to go to Padova, Italy it centres on the border of Egypt and Libya) 
Chrome (Version 46.0.2490.86 m) does behave as expected.

**Comment by knikel** [comment]
@yopaseopor, @voschix: We had an issue where the map API had reversed latitude and longitude after an update. To help me track down this one, could you tell me at which views it happens? From what I understand it's _after you click *Edit* in the viewer and go the edit view_? Am I correct here?

**Comment by voschix** [comment]
Edit is not involved in my procedure to produce "my" error

On a new Firefox window:

I open a new tab and open Mapillary.com with automatic login
I type "London",
I select "London, Greater London, United Kingdom"
opens OK on London

I type Oxford
I select Oxford, Oxfordshire, United Kingdom
it opens centred on Cairo, Egypt, very zoomed out

I select London again
it opens centred on Cairo, Egypt, very zoomed out


I noticed another thing, maybe related, on Firefox:

On a new Firefox window:

I open a new tab and open Mapillary.com with automatic login
I type "London",
I select "London, Greater London, United Kingdom"
opens OK on London

I open a second tab and in this I open Mapillary.com with automatic login
I type Oxford
I select Oxford, Oxfordshire, United Kingdom
I get a very zoomed out partial map

I type and select New York in this second tab
The window shows a partial world map

The behaviour of Chrome is similar in both cases

**Comment by knikel** [comment]
Thanks @voschix, will look into that.

**Comment by yopaseopor** [comment]
-With Chrome 46 Win 7
-Open Mapillary
-Search Pere IV OK
-Zoom to pick one track OK
-Try one pic OK
-Edit pic OK
-Save pic OK
-When I return to images map makes strange movement, picks me up to Africa
but in only a second show me correct map in a travel to "the moon and back"
(it's like it reminds last render it tried, because  with other test it
picks me up to another place of Barcelona I have edited before).

But...

later on I have tried to search Vilanova and pick Vilanova first (46 km
from Barcelona,Spain)
Render sends me to Cairo (Egypt) as @voschix

**Comment by knikel** [comment]
We do a better job with maintaining the state of the map position across the app, there should be cases like this anymore, whether you search for something or come to the viewer with lat lon in the url. Closing.
