### ISSUE TITLE
boundaries strange, chooses village instead of bigger area

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1506]
Hi!

New shapes are great, but a strange behaviour appears:
E.g. I live in a small village named Wendhausen, politic area Schellerten, bigger area Hildesheim.
Now I search Wendhausen in stats - nothing.
I search Schellerten, oh, found, but ONLY the village area, not the political area with the small villages around included.
Now I can search Hildesheim (country) and I see the bigger area of Hildesheim, the politic areas in it and e.g. the shape of Schellerten. But not a single shape for Wendhausen.

So I guess, you select the capital villages for political areas, but the shapes do only cover the village of that capital village, not the whole political area.
Please change to e.g. cover the political area, or add more shapes for the villages...

aceini

**Comment by jaakkoh** [comment]
There's something weird in the statistics search. I checked out a few areas I know / have contributed to and found that e.g. the U.S. state of Maryland doesn't show up in the stats search. Also the City of Alexandria in Virginia, U.S. doesn't show up either. And there were some others of the not-_that_-many that I checked, which I can't remember from the top of my mind.

**Comment by gyllen** [comment]
I know ELS is not 100%, but are we really this inaccurate @peterneubauer ?

**Comment by peterneubauer** [comment]
We re-imported the shapes now, should be better.
