### ISSUE TITLE
Photos in a particular sequence won't load

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1507]
The sequence [1d7IodADxmSb30CvKUEbNw](https://www.mapillary.com/map/s/1d7IodADxmSb30CvKUEbNw) has several photos that won't load. For example [uv7wwBbUzMJOzOZ4soHV_Q](https://www.mapillary.com/map/im/uv7wwBbUzMJOzOZ4soHV_Q/photo) and [zs2HLVqrGsTegepF4jxSKA](https://www.mapillary.com/map/im/zs2HLVqrGsTegepF4jxSKA). I haven't (yet) seen this happen with any other sequences.

Turns out the webpage makes an API call that fails with 504 Gateway Timeout:
https://a.mapillary.com/v2/nav/im/uv7wwBbUzMJOzOZ4soHV_Q?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh

I captured this sequence using the iOS app, but uploaded them from a computer using [mapillary_tools/python/upload.py](https://github.com/mapillary/mapillary_tools/blob/08c648631fcc2fb3c1b1b7ba66af02e12054eca2/python/upload.py).

**Comment by oscarlorentzon** [comment]
Related to #1468 and #1472 .

**Comment by nicolas17** [comment]
If this can't easily be fixed (eg. database corruption), please permanently delete the sequence and I will upload it again; I kept the originals.

**Comment by peterneubauer** [comment]
I want to check this out first - there might a bug in our backend that we need to catch.

**Comment by nicolas17** [comment]
Ping? This is still happening. Someone in OSM-Argentina was interested in this sequence to improve the map of the tunnel...

**Comment by nicolas17** [comment]
From the user standpoint: problem remains, still can't see pictures.

Looking under the hood: The nav API doesn't hang anymore, it promptly returns a 404 with `{"code":"not_found","message":"Resource not found"}` instead.

`/v2/nav/im/DwulXWHI2zC7cjb-ubVbdg` returns 404, but `/v2/im/DwulXWHI2zC7cjb-ubVbdg` works just fine. `DwulXWHI2zC7cjb-ubVbdg` is in the list of pictures of the sequence. Other pictures in the sequence (not all) do work for the nav call.

**Comment by peterneubauer** [comment]
Nicolaz,
we know there are a number of images missing in one of our database
servers. Now after New Year we are going to send the data there so the API
is responding and this issue is closed. The data is there, no worries.

**Comment by nicolas17** [comment]
I just found another victim. Sequence [0r3qJaH39M_A8Hy2h9lRXw](https://www.mapillary.com/map/s/0r3qJaH39M_A8Hy2h9lRXw) contains photo [HVh_6_cdr94KyvbCU9KpTQ](https://www.mapillary.com/map/im/HVh_6_cdr94KyvbCU9KpTQ/photo), which says "Resource not found" in the API and "This image doesn’t exist" in the website.

**Comment by peterneubauer** [comment]
Hi there,
these images are now visible, please let me know if there are still some missing.
