### ISSUE TITLE
possibly incorrect image added to a sequence

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1508]
mapillary cli tools are quite cumbersome to use when one wants to resume a sequence upload. i have resorted to manually editing files and specifying sequence id.
unfortunately, sometimes i run the modified sequence script on a new sequence and add images to the wrong sequence...

most likely, sequence 8723t783rg83dh8e3h8 is slightly broken that way - it might have one or two photos from another sequence included.

i couldn't find a way a to look up a sequence by id - please remove the obviously disconnected photo[s], they will be uploaded in their proper sequence :)

**Comment by gyllen** [comment]
The new mapillary_tools should be much easier to use -> https://github.com/mapillary/mapillary_tools
