### ISSUE TITLE
Blur approval email shouldn't say "0 more"

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1509]
I got an email saying "We’re just letting you know that the 3 blur edits you requested were approved", followed by three photo thumbnails, and at the end "... and 0 more photos." If there are only three photos, it shouldn't say "and 0 more". It looks like it already handles correctly the case of 1 or 2 approved blurs (there are 1 or 2 thumbnails and no message at the bottom).

In addition, if there are 4 blur edits, the email says "and 1 more photos" which should be "photo" :grinning:

**Comment by knikel** [comment]
We've got new email notification system and have checked for that. Thanks for reporting!
