### ISSUE TITLE
Infinite focus, isn't

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1510]
On Samsung Galaxy S5, Android 5.0.0, Mapillary version 1.54 (as well as previous versions) do not maintain infinite focus when that mode is selected.  Every few pictures, the camera tries to refocus, resulting in a blurry pic before it reestablishes infinite focus.  Pretty sure it isn't my windshield--I think it's fairly clean.

If I select Continuous focus mode, I have the same problem, but more often.  The only focus mode that seems reliable is Macro.

**Comment by peterneubauer** [comment]
Amy chance you can send me a log?

**Comment by jfburke3** [comment]
Sure; do you want a log from while I'm experiencing the problem (i.e., concurrent with when I'm trying one of those sequences), or the current log from today, as earlier today is when the problem happened?  (I'm not sure how your logging works; does it keep data for a long period of time or roll over frequently or what....)  And do you want the normal debug log or a trace log (in which case I'll need to shoot a fresh sequence for you)?

**Comment by peterneubauer** [comment]
So, the normal log is just a dump of whatever the system gives us form `adb
logcat` which is a history of mapillary events that stretches not too far
back.

Trace is logging mapillary logs into a file and thus capturing much further
back, so that would be great to do with a fresh sequence?

Thanks!

**Comment by ireun** [comment]
Well, I can confirm that, also S5 user here..

**Comment by jfburke3** [comment]
I've emailed what I hope are the trace logs. Subject line has #1510 at the end. I'll upload the corresponding photo sequence in a bit and post the link here.

I did two sequences with trace logs enabled, one with infinite focus and one with macro focus.

**Comment by jfburke3** [comment]
Here's the beginning of an "infinite focus" sequence:  http://www.mapillary.com/map/im/F0wmqrJjSQOZA_LBsRuwEQ/photo

**Comment by ireun** [comment]
Maybe you can add a "lock focus" otion to the app, i can see there is a big problem with S5's camera, just look at this sequence taken today with infinite focus.. http://www.mapillary.com/map/im/Kl63MTAq4LcwhiK1gYrjag/photo

**Comment by jfburke3** [comment]
So it's not just the S5.  I encountered the same problem today with my new S7 running Android 6.0.1, Mapillary v1.81.

I'm uploading some sequences that will include a few pics that are blurry because it refocused on my windshield for a moment (that's not why I'm uploading them, they're just part of the package).

**Comment by ireun** [comment]
Wow, S7 has Camera2 API, I thought it should be easier to control the camera with that.

**Comment by rsahlin** [comment]
Thanks for the info @jfburke3!

We do not have Camera2 support in the app, I am in the process of updating to use Camera2.
Once this is in place there we will have the possibility to add features such as 'focus lock'.
Please be patient and thanks for your support!

I'm hoping to have more to share within 2 weeks or so.

Best regards
/Richard

**Comment by jfburke3** [comment]
No problem.  I'll try out the other focus modes to see which one works best in the meantime.  (My guess is that Macro will once again turn out to be best.)

BTW, I have an S4 running Android 4.2.1, and an S5 running Android 5.0, that I can test a new build on to check compatibility if you need.

**Comment by rsahlin** [comment]
Excellent, thanks - I'll let you know as soos as a preview/alpha is available. 
Great if you can help with testing, thanks!

**Comment by ireun** [comment]
Just a note, S5 doesn't have Camera2 API, so this issue won't be fixed with that.. :(

**Comment by rsahlin** [comment]
Hmm, it _should_ be :-)

According to Android docs it is added in Api level 21 : http://developer.android.com/reference/android/hardware/camera2/package-summary.html

**Comment by ireun** [comment]
It is in the lollipop, but i has to be supported by the camera firmware, for S5 it isn't.

Have a look here:
http://connect.dpreview.com/forums/thread/3782650
http://forum.xda-developers.com/galaxy-s5/help/camera-2-api-manual-control-raw-dng-t2999345

![screenshot_2016-03-17-11-36-18](https://cloud.githubusercontent.com/assets/695818/13847205/43893574-ec4c-11e5-9dbb-2ed577ead920.png)

**Comment by rsahlin** [comment]
Ah, I see.
It supports the Camera2 API but do not support the needed camera modes for manual control.
Doh! Big fail :-(

**Comment by rsahlin** [comment]
This will be made easier to understand in the coming version 2 release.

If device supports turning autofocus off then a check is made to see if the device supports manual focus.
If the device supports manual focus then this option is considered as infinite focus.
Otherwise the option is considered to be fixed focus no manual control - cannot control focus distance.

Please recheck with beta release or wait a week or so for it to go into production.

Best regards
/Richard

**Comment by jfburke3** [comment]
Just noting that the focusing seems to be much much better with the new 2.x releases :-)  Thanks.

**Comment by peterneubauer** [comment]
great work Richard!
