### ISSUE TITLE
Make sure thumbs are cleaned out correctly

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#1512]
Mapillary automatically creates a thumbnail when taking images, which is useful for previewing the sequences on the phone.

However, if you take long sequences (e.g. if on a road trip...), you can easily fill up your SD card during a day; while not much, the thumbnails contribute a bit to the card filling up faster, and that means a slightly earlier forced stop to change the card / move the contents.. 
Also, if you are not aware of the thumbnail generation and free up your card by moving pictures to a HDD (because you wouldn't have the time to upload 30-60 GB daily...), you can easily block tens of GB of your SD card by orphan thumbnails...

I would thus like to have the option to disable the thumbnail creation, to squeeze out another couple of percent disc space for long trips. The default behaviour should of course still be to generate thumbnails.

**Comment by nicolas17** [comment]
FYI, the latest iOS app apparently doesn't create thumbnail files anymore.

**Comment by jesolem** [comment]
Since @rudolfmayer mentions SD card, I'm guessing Android. -> @peterneubauer

**Comment by rudolfmayer** [comment]
Yes, Android!

**Comment by peterneubauer** [comment]
So, thumbnails are removed (if not it's a bug) upon uploading and deleting the originals. They are used to speed up the review process and to avoid OutOfMemory crashes in these views (so does e.g. the native album app etc).

I don't think disabling this and making the app crash is the way to go - in that case maybe some max thumbnail cache size or more aggressive cache cleaning. Not high prio IMHO though. The gain is too small. If you notice the .thumbs dir getting big, please comment and we will try to handle that.

**Comment by rudolfmayer** [comment]
I understand the purpose of thumbnails for in-app reviewing images - however, most of the times I **can't** use mapillary in that way, simply because that doesn't scale to roadtrips.

To give you an example: on my recent trip to Western Australia, **after** cleaning duplicate / bad images (on my notebook), I have 228.000 (228 thousand) images left, taking up 930 GB of data; there is no way I can ever review that on the phone (too slow, and too difficult to review sequences of 5k images in one go); and even if there was, there is not enough bandwidth to upload the images to free up space before the next day - especially not in Australia, where you are happy if your hotel allows you 200 MB of data volume per day... 

Thus, the only option is to move images from the SD card at the end of the day, or during the day when it is full, which happens more then once..
I was initially not aware of the thumbnails folder, and that kept on increasing; I think I had 20 GB of thumbs in there when I discovered it by manually checking sizes of various folders..

As a summary: I would still favour disabling thumbnail creation, to be able to use the extra space. If the app crashes due to that, then that's somehow my own fault and responsibility..
(even though I think you could safeguard against that by not allowing to review sequences w/o thumbnails).

As the minimum improvement, I think you should check on app-startup for orphan thumbnails, and delete them. Then at least one doesn't have to actively think about deleting them...

**Comment by peterneubauer** [comment]
@rudolfmayer that's a very power user problem to have - I read from this that the thumbs are not cleaned properly, which makes this a bug as a start. Will look into it ASAP, thanks!

**Comment by peterneubauer** [comment]
So,
right now the emptying of the whole thumbnail cache is happening when you have uploaded all your pictures on the device. If you just keep some pics and upload them, the thumbs should disappear - easy workaround for you as a super power user.

**Comment by HolgerJeromin** [comment]
Generating thumbnails need processing power. Some (my :-) Phones are not very powerful so generating the thumbs while capturing leads to more "processing" warnings and fewer images taken. As i review the images on desktop i even do not need them.

**Comment by peterneubauer** [comment]
Implemented as a setting in v1.57

**Comment by HolgerJeromin** [comment]
Thanks. Without thumbnailing i have the feeling i could shoot more images :-)

**Comment by peterneubauer** [comment]
you better ... ;)

**Comment by rudolfmayer** [comment]
Thanks!
