### ISSUE TITLE
Draw blur/traffic signs rectangles in directions other than down+right

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1514]
Currently it is only possible to draw a blur / traffic signs rectangle in the down+right direction. Drawing on other directions does not work: a X sign appears, but the rectangle has no dimension.

![](https://cloud.githubusercontent.com/assets/397851/11098720/eb5c060a-888d-11e5-9d33-af545f4728f8.png) ![](https://cloud.githubusercontent.com/assets/397851/11098801/93f6bf4e-888e-11e5-91da-86a9d10b8f56.png)

Via #1445

**Comment by nicolas17** [comment]
Duplicate of #1291? This one has a better title and description though.

**Comment by richlv** [comment]
actually a duplicate of an even older #1222 ;)

**Comment by nighto** [comment]
Sorry. Should I close this and add the description as a comment on #1222?

**Comment by nicolas17** [comment]
Leave it to Mapillary staff; I think they can properly mark the issue as duplicate.

**Comment by knikel** [comment]
It is now possible to drag rectangles in any direction (controls stay where they were) thanks to @paulinus and @oscarlorentzon!
