### ISSUE TITLE
Deal with privacy problems

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1519]
Currntly a lot of photos with sensitive information pass by and don't get blurred. So if people notice privacy issues, it must be a simple and obligel way to report and depublish them. Currently it seems to work only, if you signup and blur the details by yourself. The reporting tool doesn't seem to work, or mapillary is to busy.

**Comment by gyllen** [comment]
Yes you do need to blur it yourself. Reporting will in most cases not help.
