### ISSUE TITLE
Edit existing data manually

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1521]
Currently a user can just upload photos, but I would like to encourage the community to do more than that:
- add match points between different photos of different tracks (like in hugin)
- alter position and orientation on map
- fix interrupted tracks ([example](http://www.mapillary.com/map/im/2nWLhxwNKoDInj_mmxwP1w/photo))
-

**Comment by katrinhumal** [comment]
@Matthias84 Thank you for your input! The matching of points between images is done by our computer vision technology. You can edit position and compass angle of the photos post-upload ([see here](https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences)). As for fixing interrupted tracks, I suppose you mean to add them into one sequence? We don't currently have plans to add that functionality, but if the images are close enough to each other, then you can still navigate between them using the spatial arrows at the bottom of the image ([like here](https://www.mapillary.com/app/?focus=photo&pKey=_WMA3ULHs2gpyAVx6r8IPQ&lat=54.1146489&lng=12.06380819&z=17)).
