### ISSUE TITLE
unnessasary bluring

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1522]
I noticed at some conditions there are blurrings, which are just unnessary:
- usual signs  http://www.mapillary.com/map/im/hhijlC6JFJ0IuKyGeprHsw/photo http://www.mapillary.com/map/im/USX_pWh-YII13ZvZeL2trg/photo http://www.mapillary.com/map/im/AYYKm2zgDYph9qAEGgU9JA/photo
- common labels  http://www.mapillary.com/map/im/IzNLmHhmGrDndsuA8rINyA/photo
- nothing http://www.mapillary.com/map/im/uJKEjqMc1_10dB-qjT4LCw/photo

**Comment by nicolas17** [comment]
This is a generic and impossible "make the image recognition as good as a human" request :wink: If you see blurs that shouldn't be there, remove them.

**Comment by Matthias84** [comment]
I'm not that familar with CV, but at every testsuite you consider false-positive tests to benchmark your algorithms?

I guess ~5% of photos contain areas that don't have to become blured, so IMHO this touches the user experience, as the users come to mapillary to explore / see details on the photos ;-)

**Comment by nicolas17** [comment]
I have seen computer vision problems where the current state of the art research algorithms achieve 65% accuracy... And for this particular problem, consider that Google Street View has lots of mis-blurs too. Not as much as Mapillary, but still.

Also, I would hope manual unblurs in Mapillary serve as negative training for the CV to improve.

**Comment by Matthias84** [comment]
I'm reporting this bug, because I don't see any progress. I don't know, if the detection is a neuronal network and can be trained that way, or if it needs manual tweaking by mapillary

**Comment by jesolem** [comment]
Thanks everyone. We (= @ybkuang ) are currently retraining. He can give you updates but there is a version coming soon.

**Comment by rudolfmayer** [comment]
Well, first of all, I think blurring false positives (at the cost of decreasing the precision/overall accuracy) is better than missing the true positives, where we'd like to have 100% recall, as these are the critical things to detect...

Besides this, what could be interesting is to list "uncertain candidates". Not sure what classifiers you use, but if you get some kind of likelihood for an object to be a face / numberplate / ...., and that likelihood is not that high, i.e. classifier is not that sure on whether it is really a candidate, then still blur it, but make this images specifically available for users to review them. Could be somewhere on the website a link to a gallery containing these images.

You could call that an "active review" (analogous to "active learning")

**Comment by jesolem** [comment]
@rudolfmayer Agree. Better to be conservative and blur more. 

We have the traffic sign game which we want to redo into something more lightweight that can run in the apps (verify/reject). Could include faces, license plates there too.

**Comment by Matthias84** [comment]
@rudolfmayer Yep, 100% agree :smile:

**Comment by jfburke3** [comment]
This seems to be the opposite complaint from #1519.

**Comment by rudolfmayer** [comment]
I wouldn't call this an "opposite complaint of #1519"; true, the premise there is that images don't get blurred correctly, but the request is simply about enabling easier manual blurring (i.e. w/o a need to be logged in)

**Comment by ybkuang** [comment]
This has been resolved by the new [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
