### ISSUE TITLE
More metadata

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1523]
I would recommend to extend the metadata of the photos / tracks
- type of vehicle -> fixing trajectories http://www.mapillary.com/map/im/MPHkm7LoWYFd3cUryk8p_Q/photo
- height / level -> http://www.mapillary.com/map/im/Xs-5oeeDGE7IdATuiVRKGg/photo

**Comment by rudolfmayer** [comment]
I am not sure whether I understand this suggestion - what specifically is broken in these sequences? What should be differently displayed?

**Comment by Matthias84** [comment]
The first one has a broken orientation / trajectory, so the view isn't updated fast enough. If you know that you are driving in a automobile / tram / ... the trajectories and type of movement could be predicted and improved automatically.

The world is 3D, but currently mapillary can just handle 2D. This could become a problem, if you think about tunnels (here), bridges, and panoramas from the top of roofs. Maybe it's useful to consider at least 2,5D?

**Comment by katrinhumal** [comment]
@Matthias84 thanks for this idea. Right now we have no plans to add height/levels information. I'm not sure what you mean with the "broken orientation / trajectory, so the view isn't updated fast enough"?
