### ISSUE TITLE
Better panorama symbolizer

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1524]
Panoramas have a special meaning (good overview, max. connectivity, ...) and users should be encouraged to add them. Currently there is just  a (mostly stupid) gps-track of this single panorama location. I recommend to use a icon instead.

**Comment by jesolem** [comment]
Yes. We have a dupe of this. @knikel knows.

**Comment by knikel** [comment]
Closing, as duplicate of https://github.com/mapillary/mapillary_issues/issues/1324 This will be added soon for both gl and non-gl map.
