### ISSUE TITLE
Play button on embeds

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1525]
I use Mapillary on other projects outside web so I embed the tracks into a blog. But with the embed there are not the same possibilities to move along a track, specially the play button whose I miss a lot on my embed tracks.

**Comment by jesolem** [comment]
Hey @yopaseopor 
Are you using the widget? There is/was a play button option for that. @peterneubauer knows.

**Comment by peterneubauer** [comment]
In the embed script you can point out the sequences to show, I think the mapillary_examples github project has some examples of this.

**Comment by yopaseopor** [comment]
It is so complicated!! It is so interesting but it is far far away for my
embed and programming skills.I wish play button on normal share embed that
is all that I can afford nowadays.In future I will see a wizard for all
these widgets and new embeds.I see big possibilities are coming :)

**Comment by knikel** [comment]
We've deprecated the widget, please use [mapillary-js](https://github.com/mapillary/mapillary-js) for embedding. Much more cool features to come there!
