### ISSUE TITLE
Allow adding meta-data (labels/tags) to images before upload

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#1526]
Quick background, my normal workflow of contributing images to mapillary is 
- take sequences on the phone
- copy them to my notebook/Desktop
- clean images: fix orientation, remove duplicates, remove bad pictures
- upload with the python script

While doing the cleaning, I often notice interesting things that I would like to annotate the images with - e.g. something that I would like to later add to OSM, or just a very interesting picture (e.g. having a Kangaroo hopping over the street right in front of the car :-))
It would be very convenient if I could add this annotation right when viewing the image on the PC, as that is easier than having to note the image, wait for the upload, and then add a comment/tag/label there, which would then also appear in the web interface.

I think using a standard EXIF editor would be fine for starters, all that would be needed from mapillary side is to define the name of the tag, and parse the tag when processing the uploaded images.

**Comment by jesolem** [comment]
@rudolfmayer Good suggestion. I like the part of defining a tag that goes in the ImageDescription part of EXIF just like our other parameters. 

We're not ready yet backend-wise for this, I think. We could decide on a tag and process when we add support for this. This is something for @gyllen to think of how to best realize.

**Comment by rudolfmayer** [comment]
Yes, deciding on a tag now and adding support for this later would be sufficient at the moment.
Easiest to edit seems to be "Title", would that be a reasonable field for you?
Another option might be "keywords".

**Comment by richlv** [comment]
an interesting idea. has this had any traction since 2015 ?

**Comment by gyllen** [comment]
We are actively scoping this out, in the lab at the moment. But if it proves successful we will release it.
