### ISSUE TITLE
Photo angle indicator doesn't respect map rotation

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1527]
In the map on the top right of the photo viewer, there is (since recently) a symbol indicating which direction the camera was pointing towards.

But if I rotate the map by right-dragging (standard Mapbox feature?), the camera angle indicator stays pointing in the same direction instead of rotating along with the map, which means it now points in the wrong direction relative to the map.

For example, in a sequence taken walking south:
![Mini-map when the selected photo was taken looking south](https://cloud.githubusercontent.com/assets/101955/11174070/8b8a91ba-8bfd-11e5-83b9-f22427b16e13.png)

If I now right-drag the map to rotate it 90°, it now looks like this:
![Mini-map when the photo was taken looking south but the map was rotated](https://cloud.githubusercontent.com/assets/101955/11174093/d0742a2a-8bfd-11e5-872f-98ec7b145846.png)

**Comment by knikel** [comment]
This has been fixed, it'll be visible soon. Thanks for the feedback! :rainbow:
