### ISSUE TITLE
add a "are you sure" for logout in android app

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1528]
The last time i checked (no clicked the wrong menu entry) there was no "are you sure" question. Click, boom, logged out. Logging in is no fun on mobile. 
So please add a security question.

.oO( settings is always the last entry in the menu. Oh, menu can be scrolled, so the last entry is not always the setting :-)

**Comment by peterneubauer** [comment]
Done, out in 1.57.

**Comment by HolgerJeromin** [comment]
thanks!
