### ISSUE TITLE
Sign slight curve to right mistakingly associated to slight curve to left

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1529]
So I was confirming the traffic sign detection on this picture:

http://www.mapillary.com/map/im/m8MI1N7BLM2J7nXkyfGnfQ/photo

And noticed that the traffic sign was detected inverted. Hovewer, as pointer out on the image, there are two signs of curve to the left and none to the right, so I believe that the sign "char" is wrong, not the detection.

![image](https://cloud.githubusercontent.com/assets/397851/11197079/2d496c70-8ca2-11e5-9f1e-9e05707abe79.png)

**Comment by nighto** [comment]
Seems like the problem is on traffico, specifically on this file: https://github.com/mapillary/traffico/blob/master/dev/br.cson
on L618, ```'turn-curve-right'``` is missing ```scale(-1,1)``` to make it turn to the other side.

**Comment by nighto** [comment]
Just corrected it on traffico, sent a pull request: https://github.com/mapillary/traffico/pull/64

**Comment by nighto** [comment]
Do we have a release date for this? I have been notified that traffico has a new release tag, but it does not appear on Mapillary yet.
No pressure though, just asking :)

**Comment by knikel** [comment]
@nighto Try clearing the cache, this is what you should see :)

<img width="291" alt="br-turn-right" src="https://cloud.githubusercontent.com/assets/1574656/12048828/599c20d2-aee0-11e5-9d8e-d3b4942b2c1f.png">

**Comment by nighto** [comment]
Awesome. Thanks @knikel! :smiley:
