### ISSUE TITLE
Not possible to add/edit/remove blur on Photo Sphere panoramas

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1530]
So, [this photo sphere](http://www.mapillary.com/map/im/iDsdVAG3p2tA0jdlkF9wMw/photo) of mine got blurred out on a part that shouldn't be blurred. The Edit > Blur button is grayed out. On Edit > Edit [page](http://www.mapillary.com/map/e/iDsdVAG3p2tA0jdlkF9wMw) there's a button "Edit Blurring" that takes back to the previous screen, with no option to change blurs.

On the previous editor, was it possible to change blur on panoramas? Perhaps that could be a workaround.

Is this related to #389?

**Comment by ybkuang** [comment]
@nighto Thanks for the feedback. We are working on editing for panoramas right now. Will let you when it is done.

**Comment by nighto** [comment]
Thanks :)

**Comment by knikel** [comment]
@nighto: @paulinus and @oscarlorentzon took care of that! :wink: 

![pano-blur](https://cloud.githubusercontent.com/assets/1574656/11304847/25e8123c-8faa-11e5-9116-00dd34df0cab.png)

**Comment by nighto** [comment]
Thanks! :)
