### ISSUE TITLE
Text upside down when rotating the phone

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#1531]
When I rotate my phone to the left, everything is OK:

![Left](http://i.imgur.com/qT3mOwr.png)

But when I rotate it to the right, note how the info text keeps upside down:

![Right](http://i.imgur.com/scYSXwc.png)

Also, I see two possible improvements here:
* add an option to choose on which side we want the Start button
* keep the same layout and elements position when rotating the phone (ie, we should always see the same thing, no matter if we rotate to the left or to the right)

**Comment by peterneubauer** [comment]
This is done to cater for left-handed people, so the button should be on the other side. Added correct rotation for the time being.

**Comment by naoliv** [comment]
But I see one problem. I usually use the phone in two places at the car: at the middle, below the rearview mirror, or at the left top corner.
On both usages my phone is rotated to the right.

For the middle case, the button is on the left, which is perfect.
But when using it at the left corner, I would like to have the button at the right side (otherwise it gets really uncomfortable and far to press it).
