### ISSUE TITLE
android: do not clutter /mnt/sdcard with .thumb dir

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1532]
right now the thumbnails for the app are stored in `/mnt/sdcard/.thumbs`
I would be very happy if this would be changed to 
`/mnt/sdcard/mapillary/.thumbs`

**Comment by peterneubauer** [comment]
Moved in 1.57, thanks, feel free to check when it's published.

**Comment by HolgerJeromin** [comment]
It would be nice if you can delete the directory as well. Could be large. But deleting a "random" dir is probably a bad idea either. 
I am not sure if this dir was used in an stable app. If not, beta users should be able to deal with it.

**Comment by peterneubauer** [comment]
Mmh,
I could list it under Developer options so people can delete it? Right now it will be cleaned out if there are no images to sync (so this will work if you remove all images from the phone, too)

**Comment by HolgerJeromin** [comment]
sorry i meant the old /mnt/sdcard/.thumb
If someone is upgrading the app and had not uploaded before switching the thumb path. Them we perhaps have an orphaned dir.

**Comment by peterneubauer** [comment]
will try :)
