### ISSUE TITLE
What are Open Source Android "pbraries"? :)

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1534]
Just look at the new credit menu. 
I am sure you mean libraries.

**Comment by jesolem** [comment]
Nice one @peterneubauer ;)

**Comment by peterneubauer** [comment]
Changed, will be out in1.58.

**Comment by HolgerJeromin** [comment]
Yes, title fixed. But the description to the libraries are still pbraries.

**Comment by peterneubauer** [comment]
Fixed now, thanks!
