### ISSUE TITLE
Is it possible to filter a sequence?

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1535]
I'm currently following [this sequence by user jglacerda](http://www.mapillary.com/map/im/OkaJnw3DStclaDOdoXa7zQ/photo). However, from times to times, when I click on the forward arrow, it jumps to a sequence by user vialma, which is made at night, and therefore the image is not as good as jglacerda's. I wonder that this happens because from times to times jglacerda sequence might have gaps as the phone struggled to record images, lost GPS signal momentarily or whatsover. But I'd like to stay at jglacerda's sequence. Is it possible somehow?

**Comment by ybkuang** [comment]
@nighto  There is an option in 'Edit' so that you can lock to one sequence. 
![image](https://cloud.githubusercontent.com/assets/5370656/11247534/bdc23c02-8e1c-11e5-85b3-a8b0bc0a11ec.png)

**Comment by nighto** [comment]
Oh, hadn't checked out that yet. Perhaps it should be inside Edit option. I'd name it "Stick to this sequence". But I'll give it a shot. Thanks!
