### ISSUE TITLE
mapillary hangs in review windows on android

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1536]
Hi

I just made a test sequence with >300 pictures on my new SDcard (128 GB Sandisk ultra).
I did remove the "create thumbnails" feature to gain speed.
Now mapillary (1.59, just updated) seems to hang if I view the review window - or it takes ages to load the pictures from the SD card.

echelon

**Comment by peterneubauer** [comment]
Yes,
that is the effect when you don't have a thumbnail cache - you will use the original images, and not get any speedup with the consequence of a potential OutOfMemory crash. Not much to do - either you use the thumbnails for fast handling, or you have to wait for the phone to do everything on the fly and in memory, especially when reviewing large amounts of data.
