### ISSUE TITLE
Android app doesn't remember login

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1538]
Is it intended that the Android app doesn't remember the login any more? Makes it unusable for me with a 25+ digit random ascii password.

**Comment by mxa** [comment]
Would you mind telling if you consider this a feature?

**Comment by jesolem** [comment]
It should remember. -> @peterneubauer

**Comment by peterneubauer** [comment]
Yes, it should remember. If you login successfully there should be an android system account created under phone settings - accounts. Is that present on your phone? Otherwise, can you send me the logs when you have to log in again ?

**Comment by mxa** [comment]
I investigated. When I log in it creates an account on the phone. When quitting and re-opening the app it will not ask again for the login. However, when rebooting the phone this account is gone and it will ask again for the password. It may has to do with the fact that it is installed on the SD card?

**Comment by peterneubauer** [comment]
Mm,
I'm not sure why the phone is loosing a system account upon restart. Is
this happening only with mapillary, not with any other like Twitter or
Google?

**Comment by mxa** [comment]
I looked into that. The list of accounts is (almost) empty after restart. Only Google and Signal are there. It gets populated after launching more apps, for example Firefox and Telegram add their accounts to the list after I launch them, without having me to log in these accounts again.

**Comment by mxa** [comment]
Maybe this is the issue, because of Android 4 and app on SD-Card? https://stackoverflow.com/questions/13135740/shutdown-removes-account-on-android-4

**Comment by mxa** [comment]
This issue also prevents me from using mapillary when offline, because I can't log in. So no pictures when I am in places like North Korea.

**Comment by peterneubauer** [comment]
So,
Is your system mapillary account not there when this is happening?

**Comment by mxa** [comment]
As I said, when I reboot the phone the account is gone and unlike the other accounts it is not being added automatically when starting the app. Have you seen the link to stackoverflow? I assume the other apps work around the issue in some way.

**Comment by peterneubauer** [comment]
Wow android removing accounts looms serious. We could use shared preferences instead, but they are not that secure, and you can't make them available to other apps. Looks like a serious bug in the Android implementation of that device. Will see if there is something else we could do...

**Comment by mxa** [comment]
I guess that the other apps are aware of that bug and work around it by having the account information stored somewhere (encrypted) and then just add the account again if it is missing at the first launch of the app.

**Comment by mxa** [comment]
Have a new device now and updated the old one too. I can confirm this seems to be a bug in Android 4. However, Other apps have found a workaround method. In Android 5 there is not this issue.

**Comment by mxa** [comment]
Might be time to close this since Android 4 is legacy now.
