### ISSUE TITLE
Weird UI for camera

### ISSUE THREAD

**Issue by arno974** [mapillary/mapillary_issues#1539]
Hey guys,

I don't know if it's normal or not, but since recently when I'm in the camera mode, the right side of the app is not more covered by the camera. I have some kind of grey panel with the start button.
Picture example : https://www.dropbox.com/s/9ry7nz2ray6zbzw/Screenshot_2015-11-20-07-49-18.png?dl=0
It's not very user friendly as we can't see if the car mount holder is visible in the right part of the images.

**Comment by de-vries** [comment]
That's how it's supposed to look. The app takes 4:3 pictures, but your screen is 16:9, this is how the remaining screen space is utilized.

**Comment by arno974** [comment]
Hi de-vries,

Ok I understand. Am I wrong or previously the whole space was covered ?

**Comment by de-vries** [comment]
Yes it was, but then it just stretched the image to fit the screen. See #644.

**Comment by arno974** [comment]
Ok I understand, thanks :)
