### ISSUE TITLE
Entering blur editor reloads the image

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1541]
When I'm in the image viewer and I click Blur to enter the blur editor, the image is downloaded again (visibly; I can see it loading top to bottom).

This is because the normal image viewer loads [thumb-2048.jpg?origin=mapillary.webgl](https://d1cuyjsrcm0gby.cloudfront.net/vimzsxtWw9-f4jFJ_G-aUA/thumb-2048.jpg?origin=mapillary.webgl) and (since the last update) the blur editor loads [thumbs-2048.jpg](https://d1cuyjsrcm0gby.cloudfront.net/vimzsxtWw9-f4jFJ_G-aUA/thumb-2048.jpg) with no `?origin`, even though both return the exact same file. If both used the same URL, the blur editor would find the image in the browser cache already.

Sidenote: Before the last update, I had a similar problem, where the image viewer downloaded the image with `?origin=mapillary.webgl` both in the blur editor and out of it, but the 'Download' button (which I sometimes clicked to see the full-resolution image and check if a far-away license plate was readable or not, etc) didn't include `?origin` so it downloaded the whole image again.

**Comment by jesolem** [comment]
Good catch! -> @knikel

**Comment by gyllen** [comment]
This works on new website.
