### ISSUE TITLE
New blur editor doesn't indicate loading progress

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1542]
In the past, the blur editor behaved exactly the same as the image viewer. Going to another image in the same sequence displayed a prefetched low-resolution image immediately, then downloaded the full photo. There was no progress indicator for loading the full image, but that wasn't too important, because the thumbnail had appeared instantly so at least you knew that your keypress did something. Going to another image elsewhere (eg. by clicking on the map) didn't have a pre-fetched thumbnail to show, but showed a spinning loading indicator, then the thumbnail (at which point the spinner disappeared), then the full image.

With the new blur editor changes deployed today, it doesn't load a thumbnail anymore, and lacking a "loading" indicator, it means there is no immediate feedback when I navigate through images. If I move to another image using the keyboard, the image remains the same with no indication that a new one is loading, until the new one loads a whole 2.5s later and appears.

If I move to another farther image clicking the map, a spinning loading indicator appears like before, but it only affects the "search for photo near clicked point" and loading of metadata from the API. Since there is no thumbnail, when the API calls are done, the spinner disappears and I'm still on the old image, until the full-resolution new image loads seconds later.

**Comment by nicolas17** [comment]
The blur editor does load a low-resolution image almost instantly now (prefetched?). I'm not sure if that's enough to call this fixed, but it's a huge improvement.

**Comment by oscarlorentzon** [comment]
The tagging functionality in `mapillary-js` together with the editing functionality in the new website should resolve this issue. Reassigning to @angelday to take this into consideration when defining the interaction behavior for the new editing functionality.

**Comment by nicolas17** [comment]
I think this isn't relevant anymore in the Elva blur editor; if there was a similar problem, it would still be different enough to justify a separate issue.
