### ISSUE TITLE
Using #MapillaryWalk on a already nominated sequence has undesirable consequences

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1545]
I used #MapillaryWalk in a [comment](https://www.mapillary.com/map/im/geNfO2kwCK5G7fmuH8jcrw/photo) on a already nominated sequence. 

[Here](https://www.mapillary.com/challenges/mapillarywalk/0u0tsaixorQe-D9wUI6JYg) is the nomination. No problems there; it's displayed as the original nominator intended, but on www.mapillary.com/challenges/mapillarywalk the nomination is shown with my comment and the sequence starts at the photo I commented on.

Also: the playback of the sequence is no longer looped, so it only plays from the photo I commented on till the last photo.

I did a similar thing with [this photo](https://www.mapillary.com/map/im/C68GY5ciF6eyCvoui2OegQ/photo), with a similar result, but there the problem got noticed and fixed quickly.

**Comment by de-vries** [comment]
Just [nominated](https://www.mapillary.com/challenges/mapillarywalk/2WbCTRwmCNti3o_rHzmxUQ) a sequence by leaving a comment on a photo (not the first), got similar results.

not sure if this should be fixed, or that I'm just looking to hard to find ways to break things...

**Comment by HarrySE** [comment]
It was my sequence that got messed up, but I got it working again by deleting my nomination/comment and replacing it. 
Now de-vries nomination is fucking up again, I supose you tried to solve it by only accepting the thirst comment, but doesn't work in my case because I deleted my first nomination

**Comment by de-vries** [comment]
This problem is so specific that I think it's not worth fixing so I removed the comment causing it. Only problem remaining is that the sequence previews don't loop if you nominate it via a comment on another photo than the first. in other words, the unofficial way. 
I think you'll have something better to do than solving such minor specific bugs. If you agree @gyllen, feel free to close this issue.
