### ISSUE TITLE
Gray rectangle shows up while navigating by dragging

### ISSUE THREAD

**Issue by Vort** [mapillary/mapillary_issues#1546]
Open track and try to slowly navigate up and down by dragging photo view with mouse.
You can see that sometimes photos are replaced by solid filled rectangle.
Also note huge lags (up to 10 secs), which renders this navigation useless.
My Internet connection is 100 Mbit/s, so this is not a network problem.
Here is the video description: https://www.youtube.com/watch?v=Vk_IEP6yc10
Used browser: Vivaldi 1.0.330.3.

**Comment by oscarlorentzon** [comment]
This has now been fixed.

Notice that dragging slow means slow transitions and dragging fast means fast transitions. Also, for sequences like the one in the video another good navigation option is Lock to sequence in the Edit section.

**Comment by Vort** [comment]
Related: #1559

**Comment by oscarlorentzon** [comment]
@Vort When you are signed in you see the Edit section.
