### ISSUE TITLE
Publish 1.5x from August 2015

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#1547]
I used the the new 1.5.9 version 11/20/2015 and 11/21/2015.  I drove on the old version from August 2015 for hours on end.  So much so that I had to start logging the photos on my SD card that has more room.  I find your new version completely unusable.  I drive under 15 minutes and the application would crash.  I reported five crashes and gave up on reporting the sixth crash on 11/21/2015.  Would you please publish the 1.5.x version from August 2015 so that I can install it from outside of the Google Playstore?

**Comment by polarbearing** [comment]
Releases are stored by the developers in [Dropbox](https://www.dropbox.com/sh/8rgd29wgn87hiam/AAB0AARtwlL8U3cMRpVeRXuja?dl=0)

**Comment by jesolem** [comment]
If you can send logs that would be great. 

Old versions are available from @polarbearing 's link.

**Comment by drkludge** [comment]
I opened an issue for several items.  I believe that I sent five of six crash reports this morning.  The reports have system logs and other stuff too.

**Comment by drkludge** [comment]
C:\gis\apps\josm>ping a.mapillary.com

Pinging a.mapillary.com [54.171.134.238] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 54.171.134.238:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),



11-21 19:03:31.671 W/Resources(16286): Converting to string: TypedValue{t=0x10/d=0x1 a=-1}
11-21 19:03:31.671 W/Resources(16286): Converting to string: TypedValue{t=0x10/d=0x1 a=-1}
11-21 19:03:31.681 D/app.mapillary.android.activity.SettingsActivity(16286): Found camera: android.hardware.Camera$CameraInfo@41ee60c8
11-21 19:03:33.092 D/SensorManager(16286): registerListener :: handle = 4  name= MPL accel delay= 200000 Trklfufi 9 cwv5vrxhbuft5budiwrd5mrfocibotfi5EtrhGfklnif@,)(d,+f8
11-21 19:03:33.102 I/Choreographer(16286): Skipped 94 frames!  The application may be doing too much work on its main thread.
11-21 19:03:33.152 I/Adreno200-EGLSUB(16286): <ConfigWindowMatch:2136>: Format RGBA_8888.
11-21 19:03:33.282 E/SpannableStringBuilder(16286): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
11-21 19:03:33.282 E/SpannableStringBuilder(16286): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
11-21 19:03:34.253 W/System.err(16286): java.net.UnknownHostException: Unable to resolve host "a.mapillary.com": No address associated with hostname
11-21 19:03:34.283 W/System.err(16286): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
11-21 19:03:34.283 W/System.err(16286): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
11-21 19:03:34.283 W/System.err(16286): 	at java.net.InetAddress.getAllByName(InetAddress.java:214)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.AbstractHttpClient$1.executeRequestSending(AbstractHttpClient.java:608)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.naf.redirect.NafRequestExecutorWrapperRedirectionHandler.executeRequestSendingUsual(NafRequestExecutorWrapperRedirectionHandler.java:96)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.naf.redirect.NafRequestExecutorWrapperRedirectionHandler.executeRequestSending(NafRequestExecutorWrapperRedirectionHandler.java:73)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.sendFirstRequest(NafHttpAuthStrategyDefault.java:488)
11-21 19:03:34.283 W/System.err(16286): 	at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.performAuthExecutionUnsafe(NafHttpAuthStrategyDefault.java:389)
11-21 19:03:34.293 W/System.err(16286): 	at org.apache.http.impl.client.naf.auth.NafHttpAuthStrategyDefault.performAuthExecution(NafHttpAuthStrategyDefault.java:200)
11-21 19:03:34.293 W/System.err(16286): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:557)
11-21 19:03:34.293 W/System.err(16286): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
11-21 19:03:34.293 W/System.err(16286): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
11-21 19:03:34.293 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getHttpPost(MapillaryServerFacade.java:199)
11-21 19:03:34.293 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getTokens(MapillaryServerFacade.java:100)
11-21 19:03:34.293 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getAuthToken(MapillaryServerFacade.java:89)
11-21 19:03:34.293 W/System.err(16286): 	at app.mapillary.android.activity.MainActivity$6.doInBackground(MainActivity.java:305)
11-21 19:03:34.293 W/System.err(16286): 	at app.mapillary.android.activity.MainActivity$6.doInBackground(MainActivity.java:299)
11-21 19:03:34.293 W/System.err(16286): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-21 19:03:34.293 W/System.err(16286): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-21 19:03:34.293 W/System.err(16286): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-21 19:03:34.293 W/System.err(16286): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-21 19:03:34.293 W/System.err(16286): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-21 19:03:34.303 W/System.err(16286): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-21 19:03:34.303 W/System.err(16286): 	at java.lang.Thread.run(Thread.java:856)
11-21 19:03:34.303 W/System.err(16286): Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
11-21 19:03:34.303 W/System.err(16286): 	at libcore.io.Posix.getaddrinfo(Native Method)
11-21 19:03:34.303 W/System.err(16286): 	at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:55)
11-21 19:03:34.303 W/System.err(16286): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
11-21 19:03:34.303 W/System.err(16286): 	... 27 more
11-21 19:03:34.303 W/System.err(16286): Caused by: libcore.io.ErrnoException: getaddrinfo failed: ETIMEDOUT (Connection timed out)
11-21 19:03:34.313 W/System.err(16286): 	... 30 more
11-21 19:03:34.313 W/System.err(16286): java.lang.Exception: Connection error: Unable to resolve host "a.mapillary.com": No address associated with hostname
11-21 19:03:34.313 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getHttpPost(MapillaryServerFacade.java:203)
11-21 19:03:34.313 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getTokens(MapillaryServerFacade.java:100)
11-21 19:03:34.313 W/System.err(16286): 	at app.mapillary.android.service.MapillaryServerFacade.getAuthToken(MapillaryServerFacade.java:89)
11-21 19:03:34.323 W/System.err(16286): 	at app.mapillary.android.activity.MainActivity$6.doInBackground(MainActivity.java:305)
11-21 19:03:34.323 W/System.err(16286): 	at app.mapillary.android.activity.MainActivity$6.doInBackground(MainActivity.java:299)
11-21 19:03:34.323 W/System.err(16286): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-21 19:03:34.323 W/System.err(16286): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
11-21 19:03:34.323 W/System.err(16286): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
11-21 19:03:34.323 W/System.err(16286): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-21 19:03:34.323 W/System.err(16286): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
11-21 19:03:34.323 W/System.err(16286): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
11-21 19:03:34.323 W/System.err(16286): 	at java.lang.Thread.run(Thread.java:856)
11-21 19:03:34.424 D/dalvikvm(16286): GC_FOR_ALLOC freed 1258K, 32% free 13776K/19975K, paused 43ms, total 45ms
11-21 19:03:34.434 D/AbsListView(16286): [unregisterDoubleTapMotionListener]
11-21 19:03:34.434 I/MotionRecognitionManager(16286):   .unregisterListener : / listener count = 0->0, ubvf 9budiwrd5ordgfl5BakTrklMrfo$,@,*eec.*

**Comment by peterneubauer** [comment]
@drkludge sorry the app is acting up for you. What model etc do you have? Also, can you try to log out and in of the app in order to make sure your tokens are correct, and maybe send me you log from 1.59?

**Comment by drkludge** [comment]
I finally had a chance to try an older version.  I picked version 1.43 because it was around the time when I had successful sequences.  I the application worked as expected.  There were no new additions to the log.

**Comment by peterneubauer** [comment]
That's great - would live to track down what's causing you grief though...
Maybe wait some more releases before trying to upgrade again? Just fixed
some more potential bugs in 1.60, released yesterday.

**Comment by drkludge** [comment]
Now that I know where the sweet spot is at, I'll be happy to walk the list of versions to see what works.  That will have to wait until the weekend.

**Comment by peterneubauer** [comment]
That would be most appreciated - I would love to work this out with you.

**Comment by peterneubauer** [comment]
Versions are now published under http://android-releases.mapillary.io/index.html
