### ISSUE TITLE
New 1.59 settings page is unusable.

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#1548]
Before my sixth crash of the day, I attempted to change some of the settings.  I can see that your love your Mapillary Green but this is not the place for it.  I am pulled over in a parking lot with the sun blasting away.  I have to push on the screen to read what the setting does.  I am in a car.  The use of transparency for a user interface in a car is just plain wrong.  Please revert back to a solid background color like white.

**Comment by echeloni2p** [comment]
hey, I do not see any transparency in the settings screen in that version?
Just whit background, green headers and black text.
After the first 2,3 settings made, you are done, no need to go into setting much more often.

echelon

**Comment by drkludge** [comment]
Umm...I only touched things to try and figure out what was going on.  I am a boring smart phone user. I don't add apps on my phone or fiddle with settings all the time. The problem came about after the version changed. it says
Google Play says that the version change on November 19, 2015 to 1.59.
My first use was on 11/20/2015 along with first crash.
Additional failures were on 11/21/2015.
That's the only change that I know about.

Are you trying to do something with day/night background settings?
Around 16:00 the white background was back.
Around 19:00 the "transparency" was back.

Thinking that this is my problem, is there something else that I could have done?

![transparent](https://cloud.githubusercontent.com/assets/1669057/11321625/a589a8ae-9084-11e5-8991-692ba2075e15.png)

**Comment by peterneubauer** [comment]
@drkludge the transparency is definitely a bug and not intended. The activity has the same style as all others. It might be that your phone is treating settings different from normal activities. You say that the transparency is gone sometimes and on sometimes?

**Comment by polarbearing** [comment]
I have the dark-settings experience since the recent updates, including 1.59. See screenshot, it is even darker on the Android itself. I have seen a time dependence myself. I don't know what @drkludge means with transparency, it's just too dark background for me. 
![screenshot_2015-11-23-11-52-26](https://cloud.githubusercontent.com/assets/8266355/11336821/ac0728e0-91e8-11e5-8486-0389ce5db7ea.png)

**Comment by drkludge** [comment]
Transparency = you can kind-of read the words but they are too dark.  You have to click and hold the item to read the text clearly.  The dark color was on most of the time.  There was a brief moment--about two hours--where it was readable.

I finally had a chance to try an older version.  I picked version 1.43 because it was around the time when I had successful sequences.  This problem is not present.

**Comment by peterneubauer** [comment]
I wonder if this could be problems with the android compatibility libs from
the latest sdk. Would you mind trying a test release built against an
earlier android sdk?

**Comment by polarbearing** [comment]
Just loaded 1.60, the settings background is still dark as above. You think that comes from the SDK? Sure I can try a test build, where?

**Comment by peterneubauer** [comment]
Pushing out a default-theme settings activity shortly in 1.61, please close if this works.

**Comment by polarbearing** [comment]
Confirm that in 1.61 settings are white font on black background. Well readable, thanks. 

Issue was not opened by me, please close yourself.
