### ISSUE TITLE
[tools] upload.py should check for mapilary tag

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1550]
I just preprocessed some sequences and uploaded them. After some time wondering why they didn't show up on the website the insight came to me that I forgot to run add_mapillary_tag_from_exif.py.

If upload.py had a check for this, that would have saved time and bandwidth.

**Comment by jesolem** [comment]
Good point.

**Comment by richlv** [comment]
shouldn't this go to https://github.com/mapillary/mapillary_tools/issues ?

**Comment by ybkuang** [comment]
@de-vries We do check for the mapillary tag in upload.py. It says for example when you run it on a folder with 492 images without the mapillary tag. 
```Uploading 10 images with valid mapillary tags (Skipping 492)```
Do you prefer to make it more a explicit warning?

**Comment by de-vries** [comment]
The script didn't do that check. I probably wasn't using the latest version. Sorry for that.

I think the warning you described is sufficient enough.

I'm also interested in the answer to @richlv's question

**Comment by ybkuang** [comment]
@de-vries let us know if the latest version works better. 

As for @richlv's question, it is better to submit issue related to tools at ```mapillary_tools/issues```. But it doesn't really matter that much as you already marked the issue [Tools].

**Comment by de-vries** [comment]
Thanx @ybkuang, I have full confidence that your improvement to the script works, but I will test it if I have some suitable photos for that. closing this for now.

**Comment by ybkuang** [comment]
Closing this for now. Let us know if there are more issues.
