### ISSUE TITLE
[tools] sequence_split.py should ignore missing coords

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1551]
Since a while sequence_split.py also splits when the distance is greater than 500m, and there is a check if the geo data is present. This makes it impossible to divide the photos in sequences before matching the photos with a gpx track.

This is annoying in case you have to match photos with different gpx tracks, like when the photos are taken over multiple days. Or in case when not all sequences have the same time difference with the gpx track. (some cams do this when turned off and on)

It would be nice if missing coords just get ignored by sequence_split.py. (or only print a warning)

Besides that; if you cut the sequences at 5 sec you don't have (under normal use) any 500m gaps left, because you have to travel at 450km/h to create a gap of 500m in less than 5 sec.

**Comment by ybkuang** [comment]
@de-vries Thanks for the suggestion. We will think about this and add some enhancement to the script.

**Comment by ybkuang** [comment]
In the new tool release, there is an option to cut sequence based on time as well. Closing
