### ISSUE TITLE
Some viewing directions in a sequence are displayed incorrectly

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1554]
Have a look at http://www.mapillary.com/map/im/IPPX2AMaPV-cW3Cz9Z40Vg/photo . This photo is the first of a series inside a sequence, which shows a wrong viewing direction. The viewing direction in the photo before (in the same sequence) is correct. Also the viewing direction seems to be correct again after about 15 pictures in forward direction. The viewing direction should be 118° (about south-east), but is exactly (?) north. Later pictures that show a wrong viewing direction however are not exactly north-facing, e.g. http://www.mapillary.com/map/im/VS_5SpuQctb4aXseqeHtTw/photo .

I tagged the direction using https://github.com/mapillary/mapillary_tools/blob/master/python/interpolate_direction.py () and uploaded the picture using https://github.com/mapillary/mapillary_tools/blob/master/python/upload_with_authentication.py .

**Comment by knikel** [comment]
This has been fixed now, thanks for the feedback!

**Comment by ltog** [comment]
Thanks for fixing it! :-)
