### ISSUE TITLE
Zoom level in mapillary viewer URL

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1556]
It would be nice to have the zoom level included in the URL in the mapillary viewer.
A case where this would be helpful would be when the tiles need to be refreshed (not used from browser cache) because new ways were added. That is an issue with the mapillary overlay (the green paths), not the mapbox base layer which gets updated quicker.

**Comment by de-vries** [comment]
similar request to #950

**Comment by knikel** [comment]
This will be likely added to the `/map/:imageId/map` view at some point.

**Comment by mxa** [comment]
Right, It's a duplicate to #950. My bad. Should I close this?

**Comment by knikel** [comment]
@mxa closing it. Thanks for the feedback, let's track in #950.
