### ISSUE TITLE
Navigation by dragging: minimap is out of sync

### ISSUE THREAD

**Issue by Vort** [mapillary/mapillary_issues#1559]
When you slowly dragging the main view up/down to navigate forward/backward, position on minimap gets updated, URL in browser's address bar updates, but main view stays unchanged.
Here is the video description: https://www.youtube.com/watch?v=XaF3RkiH4Gs
Used browser: Vivaldi 1.0.330.3.

**Comment by Vort** [comment]
Looks like I have found the exact condition which triggers lags:
If you move mouse without any stops (even tiniest), at any speed, navigation becomes totally unresponsive.
I can make another video if needed, just ask.

**Comment by oscarlorentzon** [comment]
If dragging in this way will be implemented in `mapillary-js` it should handle this correctly.

**Comment by oscarlorentzon** [comment]
Navigation by dragging is not supported in MapillaryJS and therefor not present on the website so closing.
