### ISSUE TITLE
service=drive-through is rendered at lower zoom levels than parking_aisle, resulting in visually disconnected roads

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1560]
service=drive-through should probably only be rendered at the same zoom levels as parking_aisle.  Otherwise, you get some interesting road configurations around some places.  For example, the Wendy's at this location has a drive-through road that looks like it's not connected to other roads at certain zoom levels.
http://osm.org/go/ZDduZ_vR6?layers=N&way=191108018 
https://www.mapillary.com/map/search/27.893149545415696/-82.320646264605/15.746980742970667

**Comment by jfburke3** [comment]
Maybe service=anything tags should all be treated the same?

**Comment by gyllen** [comment]
This is an issue with styles from mapbox.

**Comment by knikel** [comment]
We're using out of the box styles from mapbox with our layers added on top. There is a lot of styles than need changing and a lot of testing involved to make this happen. In the upcoming version we'll be using the latest [outdoor](https://www.mapbox.com/blog/mapbox-outdoors-redesign-launch) or [bright/dark](https://www.mapbox.com/blog/mapbox-light-dark-redesign).
