### ISSUE TITLE
(translations) Can you finish your Spanish translations?

### ISSUE THREAD

**Issue by d3netxer** [mapillary/mapillary_issues#1561]
I switch the language to Espanol but only a few words are translated.

**Comment by jesolem** [comment]
We changed a lot on the website lately, will get to updating the translation files soon. 

Thanks for reporting.

**Comment by nicolas17** [comment]
As far as I know, all website translation work is suspended now because [a new website layout is coming soon](http://blog.mapillary.com/update/2016/04/28/www-remake.html). Translations may need to be re-made from scratch for the new website.

**Comment by knikel** [comment]
Exactly, as @nicolas17 wrote. The translation scheme will be built from scratch. We'll make an announcement when that happens 😉 .
