### ISSUE TITLE
sequence play with images shot backwards 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1563]
http://www.mapillary.com/map/im/Yiya81f2sk4ONiDLvUQtkw/photo

This image sequence was captured out of the back window while driving.
Clicking the "up" arrow, i go forward into the viewing direction but back in time (there was a problem in the past which was fixed).
But the play function is not adapted and goes forward in time (but backwards in viewing direction).

**Comment by oscarlorentzon** [comment]
Thanks for the input @HolgerJeromin .

The play functionality is currently based on the sequence concept. Sequences can be taken in a lot of different ways like forwards, backwards, to the left, to the right and in circles as well as in combinations of the previous including turns. We always play sequences chronologically from the first photo taken to the last photo taken. You can see it as a way of experiencing the path the user took looking in the direction the user (or camera) looked.

Preferring playing forward would introduce logical problems e.g. for sequences where a user walked both forwards and backwards. 

At this time we would like to keep the simple and straightforward way we play sequences. In the future we hope to make the playing functionality more dynamic but as long as we play within a sequence the chronologic order will not be changed.

I'm closing this issue for the reasons outlined above.

**Comment by HolgerJeromin** [comment]
OK. Implementing #1189 would solve the issue then.
