### ISSUE TITLE
Relax search queries and display more relevant results in the searchbox

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1564]
When i search for my city "Aachen" i get:
![github](https://cloud.githubusercontent.com/assets/2410353/11370495/5261e99c-92c4-11e5-85b7-d82fc9b7c8c2.png)
Aachen city is part of "städteregion aachen" which is part of "regierungsbezirk köln" which is part of "nordrhein-westphalen" in germany.  I want to get "Aachen" and perhaps "Städteregion Aachen".

~~clicking one of the 5 results shows me the right position for a few seconds and after that pushes me to the Mediterranean Sea:~~
http://www.mapillary.com/map/search/6.0942823494427785/50.763683342991214/-22.789425206372982/79.68739089875663

~~edit: All search result pushes me to the mediterranean sea... chrome on win7~~

**Comment by hakuchi** [comment]
This is not only with Aachen.
All searches will zoom out to this position.

**Comment by knikel** [comment]
I'll investigate that tomorrow.

**Comment by jfburke3** [comment]
Zooms out for me, too.  HOWEVER, if I then do a second search (while zoomed out to see the whole world from my first attempt) for the same place, it DOES then zoom in to the right area.

**Comment by HolgerJeromin** [comment]
Ok, we have two issues here. The zoom problem and the multiple results

**Comment by knikel** [comment]
Hey folks, moving from location to location should behave much better now. Thanks for the feedback!

**Comment by HolgerJeromin** [comment]
ok, the sub issue is fixed. thamks. 
But the main issue is not!

**Comment by knikel** [comment]
@HolgerJeromin I was about to open a new issue about relaxing the search and displaying more results, but we can as well track it here. Looping in @peterneubauer as I need his hand with this :wink:

**Comment by knikel** [comment]
We can only display as much data as come back from [here](https://mapzen.com/projects/search), roughly in a similar order. We'll be also using mapzen search for the upcoming front-end revamp.
