### ISSUE TITLE
After using iOS Quick Actions, closing camera view can make it open again

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1566]
In my QA instinct to leave no stone unturned, I tested the new 3D Touch quick actions in the iOS app (as requested in #1503), and found a minor bug.

Reproducing steps:

1. Force-press Mapillary icon on the home screen, and select any of the quick actions (Walking Mode or Riding Mode). The app opens in the camera view in the correct mode.
2. Maybe go and take some pictures :)
3. Press the home button to leave Mapillary, *without* first closing the camera view with the (x) button.
4. Force-press Mapillary icon again, select any of the quick actions. The app opens in the camera view, in the correct mode.
5. Close the camera view with the (x) button.
6. The camera view closes, but **a second later it opens again**. Closing it again does close it for good.

My initial bug theory was that if I repeated these steps and launched the camera view from a quick action N times, without closing the camera view in between, then it would keep reopening when tapping (x) N times (queuing views or requests to open it?). However, this doesn't seem to be the case. I only need to close the camera view *twice* no matter how many times I launched Mapillary from a quick action.

**Comment by millenbop** [comment]
Thanks! I'll look into it!

**Comment by millenbop** [comment]
Thanks for writing such nice and clear bug report by the way! Much appreciated. It is now fixed and will be included in next release.
