### ISSUE TITLE
In-app map can be in-app GPX track?

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1567]
i test the in-app map, well, it spend some data (no wifi in my car) but is curious and a good way to know where I am if I am not from the place I have been mapping.But as a "heavy mapper" I prepare some of my "future tracks" at home, watching streets and maps to know where I have to turn left or right, capture it and make it available to Mapillary.It would be great this in-app map would be able to show me also my GPX file which says me at what street I have to turn left or right to capture that missing street.

**Comment by jesolem** [comment]
We just announced this for iOS http://blog.mapillary.com/update/2015/12/12/map-in-camera.html

It is available on Android too in the settings but not stable on all devices yet. 

Would that solve it?

**Comment by peterneubauer** [comment]
So you want external gpx tracks to shoe up in the map that is in the camera view?

**Comment by yopaseopor** [comment]
If I can "substitute" the map by a GPX track of my own, I can know where I have to turn to follow my planificated track. Watching Mapillared tracks and not is interesting but it is not useful for me because I will not follow it, I will follow my second GPS telling me where I have to turn to continue my planificated track to avoid losing myself and to catch interesting zones I have considered instead of being Mapillared in the past or not.

**Comment by peterneubauer** [comment]
This is something that we possibly will do further down the line - good suggestion! Closing it for now.
