### ISSUE TITLE
do not offer clear & request for user submitted blurs

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1568]
open an image w/o any blurs, notice how "clear all blurs & request" is disabled.
add a blur - "clear all blurs & request" is enabled.
that does not seem to make much sense and probably that button should stay disabled

**Comment by HolgerJeromin** [comment]
Similar thing is:
Add the first blur on image. Delete it. I am able to save the blur.

**Comment by gyllen** [comment]
Close when new blur is rolled out

**Comment by nickplesha** [comment]
New blur mode should offer to save blurs only when there are any new ones to be saved.

The "Clear all + >" button is now always on as it simply removes everything saved or not. (Behind the scenes, it will not send a delete request if no previously present blurs were removed).
