### ISSUE TITLE
user/author information disappeared

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1569]
author of the image used to be displayed in the lower right corner, now that information is nowhere to be found.

i often would like to know whether a sequence was taken by me, and with many sequences, it is impossible to remember anymore. also, i know several of the image contributors in my area, and in some cases i would like to know who uploaded a particular sequenc/image - that is impossible now, too

**Comment by de-vries** [comment]
maybe because blur mode is enabled? It's a new feature to hide the author when blurring. At first I was confused by it too.

**Comment by richlv** [comment]
oh, indeed !
thanks for that info :)
it might be worth showing author in photo details always, but as long as i can find it i'm ok - closing.

**Comment by knikel** [comment]
@richlv Fixed that, the author will be visible in the blur mode too :+1:

**Comment by richlv** [comment]
ah, even better, thanks :)
