### ISSUE TITLE
statistics/toplist broken

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1570]
country/region statistics have been broken for a while(i seem to recall an issue about it, but can't find it right now). the page opens, but claims there have been no uploads at all.
the header also says "Toplist for", with the country/region missing.
no idea what's wrong, but it looks like somebody is having fun with javascript messages...
 _ _ _              _  _              
' ) ) )            // //              
 / / / __.  _   o // // __.  __  __  ,
/ ' (_(_/|_/_)_<_</_</_(_/|_/ (_/ (_/_
          /                        /  
         '                        '   
You are quite a hacker (1337)
File bugs at https://github.com/mapillary/mapillary_issues
or get a job at http://www.mapillary.com/jobs

**Comment by knikel** [comment]
@richlv I've been fixing performance issues in these views today. I've just deployed new version with  few new features (e.g. possibility to go back in the history of the shapes visited (for now it's just the WebGL map). Would you mind posting a link to which shape is causing this? That message is only visible when the top list is _really empty_ or the content hasn't fully loaded.

**Comment by richlv** [comment]
oh, sorry, intended to include a couple of links but that slipped my mind :)
as far as i can tell, it's all toplist pages, but a few i tried :
* http://www.mapillary.com/map/places/latvia
* http://www.mapillary.com/map/places/china
* http://www.mapillary.com/map/places/california

**Comment by richlv** [comment]
oh snap.
looks like stat/toplist view has been completely redone and the old urls do not work anymore...
remembering those numbers is not very feasible, though - is it possible to have aliases so that urls like i posted would work again ? :)

**Comment by knikel** [comment]
@richlv unfortunately there is no way for us to map names to shape_id's and persist them (we had a homebrew solution for _nicely looking _ place name slugs in the urls, but it was causing a lot of trouble), I'll add a redirect to non existent places which will go to http://www.mapillary.com/map/stats where one can look up the place of interest. It's not a perfect solution, but better than faulty infinite load. Sorry about that!

**Comment by richlv** [comment]
got it, thanks. non-existent place link should help a bit.
are those numbers/ids static or can they change at some point ?

**Comment by knikel** [comment]
These id's are static, what can change slightly is the information to which they relate _to_ (more internationalized names for given shape, more detailed shape, etc.).

We've switched recently to using [Mapzen's WOF](https://mapzen.com/blog/who-s-on-first) for shapes and shape related data. If you're interested, you can preview the shapes data [here](https://whosonfirst.mapzen.com/spelunker/id/85633279/) and raw (and editable data) is hosted [here](https://github.com/whosonfirst/whosonfirst-data/blob/master/data/856/332/79/85633279.geojson)
