### ISSUE TITLE
can't view a photo: "An unhandled lowlevel error occured"

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1571]
http://www.mapillary.com/map/im/-sdC6zo0IYgEQJyXIhaW9A/photo

"An unhandled lowlevel error occured. The application logs may have details."

**Comment by knikel** [comment]
@richlv Did this happen when you tried accessing the _interesting sequences from the area_ cards  in the search view in bottom left corner? If so there was a bug with mangled URLs for sequences and photos. It's basically a `sequenceId` in a photo URL. http://www.mapillary.com/map/im/wq3YjuFMgAoZjJQ4e43UaQ/photo works. Sorry about that.

**Comment by richlv** [comment]
ah, yes, that link could have come from the images in the lower left hand corner, thanks.
closing the issue, although maybe the error message could be added/improved a bit ?

**Comment by knikel** [comment]
This will be handled better from now on. Thanks!
