### ISSUE TITLE
Photo sequence delay 1,5 seconds.

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#1572]
1 second is surely not too short.  I do not get enough overlap while turning.
But sometimes the camera seems to retract.
Another disadvantage is that replaying the sequence is too slow with the viewer as it is now.
Could 1 second also be too short for my Samsung Galaxy S5 to focus properly ?  I am not in the mood for testing.
With a delay of 2 seconds, I miss too many connections.
So I suggest  to add 1,5 sec.

**Comment by nicolas17** [comment]
iOS allows 1.5s already. The driving mode capture interval setting goes from 1s to 3s in 0.5s steps.

**Comment by filipca** [comment]
Good, I was afraid that is was a big deal.
3 seconds is too short for a boat trip = http://www.mapillary.com/map/im/X83cP9EM_XmIoIkTrOn-dA/photo
