### ISSUE TITLE
blurs can be shown on the wrong image

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1573]
(i was sure there is an open issue about this, but with that many issues was unable to find it...)

blurs sometimes can be shown on the wrong image. this usually happens on a slow connection.
one scenario - on a slow connection, move to the next image in sequence. blurs get loaded before the image and displayed. it can easily take 5 more seconds for the image to change, which can lead to "clear all & request" being pressed incorrectly.

it might be nice not to show blurs until the right image has been loaded and can be displayed

**Comment by knikel** [comment]
Yes, good point. Will be be fixed after the weekend.

**Comment by knikel** [comment]
Blur are now loaded in a different way than they used to, there shouldn't be issues like this when changing photos. Closing.
