### ISSUE TITLE
forward/backward arrows have disappeared in edit modes

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1574]
In the past (up to a couple of weeks ago) I could walk through the photos of a sequence on the Mapillary site for editing either blurs or traffic signs by using the forward and backward arrows with either blur or traffic sign editing continuously enabled.

This has recently been changed:
the forward/backward arrows disappear when enabling either blur or traffic sign editing.
Even though the keyboard up/down keys still work, it would be less confusing if the in-picture arrows could be brought back.

**Comment by knikel** [comment]
This is a desired behaviour and we hid the arrows recently when you edit. Previously it was causing an issue when the thing you wanted to blur was below the arrow. You can still navigate using keys.

**Comment by voschix** [comment]
Hmmm. I see your point, and I remember that I have encountered myself the problem of not being able to edit something "behind" the arrows. Nevertheless the fact that the arrows disappear when you enter edit mode and reappear when you leave it may lead to wrong conclusions. I had always used the the clickable arrows and promptly thought of an error. 
BTW how do I handle this on an (Android) tablet with no keyboard and hence no arrow keys?

**Comment by knikel** [comment]
@voschix I definitely see you point. I'll see how we can add the arrows back in a meaningful way without them obstructing the view (probably some transparency and disabled click events would do).

Regarding your android question, unfortunately the user interface is lacking in terms of edit functionality on mobile devices (here, the drag gestures and behavior is taken by drawing rects) and to successfully move from one photo to the other you'd have to toggle on/off edit mode constantly. I've opened this issue to track it: #1576.
