### ISSUE TITLE
Wrong encoding for the state Zürich in Switzerland

### ISSUE THREAD

**Issue by nliechti** [mapillary/mapillary_issues#1577]
It seems you have a wrong encoding for the state (canton) Zürich. Although the name of the city is encoded correctly.
![image](https://cloud.githubusercontent.com/assets/2284764/11467159/93b1a488-9746-11e5-8bc9-77597ec8a38e.png)

**Comment by knikel** [comment]
@nliechti, we're using external service for location search. I'll forward your feedback there. Thank you!
