### ISSUE TITLE
Russian letters are displayed as question marks in the feed

### ISSUE THREAD

**Issue by Zverik** [mapillary/mapillary_issues#1579]
Mapillary for Android 1.61
I recently commented [a photo](http://www.mapillary.com/map/im/p6K4B-4dG0GuVJR7FXUVFA/photo), and this shows in my feed. Alas, all the non-lating letters are displayed as question marks. Which is strange, because I assumed the charset is UTF-8. Could you please check your fonts?

![screenshot_2015-11-30-12-11-09](https://cloud.githubusercontent.com/assets/766031/11467895/57a8b1b4-975c-11e5-9d08-9bbe7d097302.png)

**Comment by peterneubauer** [comment]
So, what is your username so I can find the feed item to test with @Zverik ?

**Comment by de-vries** [comment]
I guess it's [zverik](http://www.mapillary.com/profile/zverik)

**Comment by Zverik** [comment]
Right :)

**Comment by peterneubauer** [comment]
Fixed, will be out in the next release.

**Comment by Zverik** [comment]
Thanks!
