### ISSUE TITLE
Can't create blur near timestamp

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1580]
It's not possible to draw a blur rectangle if it would overlap with the "Username · Timestamp" text at the bottom of the image.

For example in [2inmeJqFkn_1_SPYuWMY4w](https://www.mapillary.com/map/im/2inmeJqFkn_1_SPYuWMY4w), the license plate is at the bottom left of the image. If the mouse is over the text, it shows the text cursor as if to select the text (although the text can't be selected), so I can't draw from there. If I start drawing from further high, as soon as the cursor touches the text, the rectangle stops being drawn and the [X] appears.

I'm being too verbose. Just open the image and try blurring the license plate yourself :wink:

**Comment by richlv** [comment]
confirming this with vivaldi browser, too

**Comment by nicolas17** [comment]
This is fixed in the new website, because there is *nothing* overlapping the picture in the blur editor anymore, such as the timestamp.
