### ISSUE TITLE
higher zoomlevel in edit mode

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1581]
HI!

with doing 1 pic every sec in walking mode, far too much pictures are created in a small area. In area mode, the map does not reflect this high density and it is nearly impossible to position the images correctly on the currently available zoom.
A higher Zoomlevel (with displaying the map itself, not just blank as it is in current highest zoom) does help positioning the sheer amount of pictures done on a small area with this high frequency.

echelon/aceini

**Comment by knikel** [comment]
Max zoom level we have in the editor is 20. In the upcoming update you'll be able to go past that for more precise editing
