### ISSUE TITLE
Traffic signs overlay in JOSM

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#1582]
Similar to [iD](http://blog.mapillary.com/update/2015/06/02/id-signs.html), it would be awesome to load the traffic signs in JOSM.  An Imagery overlay is fine if SVG sign rendering is difficult to implement in JOSM.

**Comment by knikel** [comment]
We're close to generating traffic signs from traffico as PNGs, they'll be matching the names returned from our API. It should make life a bit easier for JOSM devs.

**Comment by knikel** [comment]
We have a repository where we host all the traffic signs we have detected, I‘m not sure how hard would it be to implement in JOSM, but we do generate a `.png` sprite and accompanying mapping to data in JSON format. Pinging JOSM devs 👍
