### ISSUE TITLE
Search UTF8 encoding issues

### ISSUE THREAD

**Issue by zopyx** [mapillary/mapillary_issues#1583]
See screenshot 
![screenshot 2015-12-02 06 53 55](https://cloud.githubusercontent.com/assets/594239/11523310/8a397a9e-98c1-11e5-9698-2ba937d5a833.png)

**Comment by knikel** [comment]
@zopyx, we're using external service for location search. I'll forward your feedback there. Thank you!

I'll leave this issue open in case others want to report this too.

**Comment by GITNE** [comment]
> we're using external service for location search. I'll forward your feedback there. Thank you!

@mapillary The service seems to be pulling data from OSM. It may well be the case that data has been auto-imported into OSM without properly converting it into UTF-8 beforehand. :laughing: If not, then if you are paying for this service then you should demand a refund because it is no good.

**Comment by knikel** [comment]
Mapzen folks did awesome job normalizing imported data, you shouldn't see this happening that much anymore.
