### ISSUE TITLE
Cannot upload panoramas larger than 10485760 bytes

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1584]
Some time ago I reported that I could not upload certain panoramas/photos sphere, created by Googles photo app, using upload_with_authentication.py. It could not be reproduced and I agreed to retry with only 1 thread. It did not help, so I also printed the http response body.

The error message I get is now (the body is shown between the single quotes):
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg: '<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>10488437</ProposedSize><MaxSizeAllowed>10485760</MaxSizeAllowed><RequestId>B524DD963ACB90EE</RequestId><HostId>+54/aKJhc3Ih0TW3TUSM8hGA4AgI9y3tleu1vovxG9NKBwpz+CqCkW0GrtsuIuy0y+x6Sa90NrA=</HostId></Error>'.

I can see I get connected to s3-eu-west-1.amazonaws.com . I am sitting on a nice ADSL from Telenor, and is uploading with around 1.2 MB(ytes)/sec.

The file from the log above is too large for GitHub, so I put it at http://simonmikkelsen.dk/files/PANO_20151029_122622.jpg

With Googles photo app, the photo spheres easily gets a size between 15 and 20 MB. For future use I think it would be unwise not to accept even really large images.

**Comment by peterneubauer** [comment]
This is working for me:

````
    ➜  python (master) ✗) export MAPILLARY_USERNAME=peterneubauer && export  MAPILLARY_SIGNATURE_HASH=xxx && export MAPILLARY_PERMISSION_HASH=xxx  && python ./upload_with_authentication.py ~/Desktop/PANO_20151029_122622.jpg
Uploading sequence e46009a6-454d-4f66-a473-24606fcf5e64.
=============================================================] 100.0% ... 0 images left.
Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.
Finalize upload? [y/n]: y
Upload a DONE file peterneubauer/e46009a6-454d-4f66-a473-24606fcf5e64/ to indicate the sequence is all uploaded and ready to submit.
Done uploading.

````

**Comment by simonmikkelsen** [comment]
I just tried get the code completely clean without any of my wrapper scripts - same result:

```bash
tryl@dina:~/tmp$ git clone https://github.com/mapillary/mapillary_tools.git
Cloning into 'mapillary_tools'...
remote: Counting objects: 871, done.
remote: Total 871 (delta 0), reused 0 (delta 0), pack-reused 871
Receiving objects: 100% (871/871), 212.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (583/583), done.
Checking connectivity... done.
tryl@dina:~/tmp$ cd /home/tryl/Documents/mapillary/2015-12-01_pano_todo
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ cd 0
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo/0$ ls
failed	log-upload.txt	PANO_20151029_122217.jpg  PANO_20151029_122346.jpg  PANO_20151029_122622.jpg  success
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo/0$ cd ..
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ export NUMBER_THREADS=1
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ export MAPILLARY_SIGNATURE_HASH="<cut>"
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ export MAPILLARY_PERMISSION_HASH="<from http://api.mapillary.com/v1/u/uploadhashes>"
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ export MAPILLARY_USERNAME="tryl"
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ ~/tmp/mapillary_tools/python/upload_with_authentication.py 0/
Uploading sequence ed714e3b-f71a-4aa8-b6fe-e5caf1b913c1.
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg% ... 2 images left.
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
^THTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122217.jpg% ... 1 images left.
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122217.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122217.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122217.jpg
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122217.jpg
^C
BREAK: Stopping upload.
```

In another shell I edited ~/tmp/mapillary_tools/python/lib/uploader.py and changed line 260 from
print("HTTP error: {0} on {1}".format(e, filename))
to
print("HTTP error: {0} on {1}: '{2}'.".format(e, filename, e.read()))

Try again to get more details on the error:

```bash
tryl@dina:/home/tryl/Documents/mapillary/2015-12-01_pano_todo$ ~/tmp/mapillary_tools/python/upload_with_authentication.py 0/
Uploading sequence e0be2646-8eed-4223-9c65-b1e14e9ac4b6.
HTTP error: HTTP Error 400: Bad Request on PANO_20151029_122622.jpg: '<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>10488437</ProposedSize><MaxSizeAllowed>10485760</MaxSizeAllowed><RequestId>67F23DD31007FA6A</RequestId><HostId>WOb71aBlB0WRB1xEpYmiL/LTL+NMBvzts+wnvqK0ejDXQX6LiDL5/aYpIG4yfhC4vTQNna4EeGg=</HostId></Error>'.
^C
BREAK: Stopping upload.
```

Same result as earlier :-(

As an end user it is frustrating when the developer cannot reproduce the issue. As a professional developer it is frustrating when I cannot reproduce the users issue.

I hope you can spot some difference in what we do. We should hit the same upload location.

In my upload_with_authentication.py there is a line that says
MAPILLARY_UPLOAD_URL = "https://s3-eu-west-1.amazonaws.com/mapillary.uploads.manual.images"
while uploader.py has one that says 
MAPILLARY_UPLOAD_URL = "https://d22zcsn13kp53w.cloudfront.net/"

By sniffing my traffic I can see that I hit s3-eu-west-1.amazonaws.com. Am I supposed to hit Cloudfront? Could I in some way hit an old upload site, that is only kept for backward compatibility?

**Comment by peterneubauer** [comment]
We updated the file size limit, this should be working now in S3 uploads.
