### ISSUE TITLE
New created login is not available

### ISSUE THREAD

**Issue by wumpazz** [mapillary/mapillary_issues#1585]
I have created today a new login on the portal page with Mozilla Firefox and received some seconds later a welcome message within my e-mail-account.

Now I am not able to login with my new created login - neither on the app - nor on the portal with a browser. I still receive the message 'We failed to log you in'. 
Also Password recovery is not possible; I receive an error message 'We have no such email in our database' when I enter the e-mail-address that I used to create a new account (and received the welcome message).

**Comment by peterneubauer** [comment]
Mmh,
it might be that there were API problems. If you try to register/login again, is it working now?

**Comment by jesolem** [comment]
Is this still an issue?
