### ISSUE TITLE
New stats: Denmark is not Denmark

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1587]
When I try to find Denmark (found next to Sweden and not only in fairy tails) at http://www.mapillary.com/map/stats?p=Denmark I see Denmark listed as a Country but with the flag of Greenland. And indeed, it links to Greenland.

But it works when I search for Danmark, the danish word for our land it works nicely.

**Comment by jesolem** [comment]
Suspect it is the country code in who's on first that needs an update.

**Comment by peterneubauer** [comment]
well, https://github.com/whosonfirst/whosonfirst-data/blob/master/data/856/332/17/85633217.geojson?short_path=5224645 lists Greenland as a country (not region) and we add the ne:sovereignt as one of the search terms, which is "Denmark". I think this is a bug you should report to https://github.com/whosonfirst/whosonfirst-data/issues, and we will reimport the cleaned-up data later.

**Comment by thisisaaronland** [comment]
FYI:  https://github.com/whosonfirst/whosonfirst-data/issues/177

**Comment by peterneubauer** [comment]
Thanks for raising the issue!
