### ISSUE TITLE
Gopro manually uploaded images pre-edited show up distorted on map

### ISSUE THREAD

**Issue by ksetdekov** [mapillary/mapillary_issues#1588]
Hi.
I've encountered an odd behavior.
Manually upladed geotagged gopro 3+ images, that were rectified by a Lightroom preset to make them rectlinear.
Here is an example:
![g0026763](https://cloud.githubusercontent.com/assets/16122863/11540275/e00ecb56-993c-11e5-95fe-292a6a3a81aa.jpg)
The image looks fine, but after uplading about a 1000 images, almost all of them have a wierd distortion like this
![shown on map](https://cloud.githubusercontent.com/assets/16122863/11540296/12fb8ca2-993d-11e5-8bd8-f6f7e81f35a0.jpg)
This image can be seen here on the map https://www.mapillary.com/map/im/cozfNhzFEocxwre-G_SRIw/photo
I think this is incorrect image processing. Was I supposed not to edit GoPro images beforehand?

**Comment by de-vries** [comment]
Mapillary corrects for the fish eye effect in the gopro lens. If you also correct, it gets done twice and you get a negative fish eye effect. If you think you're doing a better job at this correction you might be able to prevent mapillary from doing the correction by removing any gopro reference from the exif data.

Also if you're really doing a better job at this, then please share how you do it. I'm sure @ybkuang  is interested to learn from it.

**Comment by ksetdekov** [comment]
It is just a 3-click process:
![lr edit](https://cloud.githubusercontent.com/assets/16122863/11541781/2e6ef480-9945-11e5-857d-a77d92467018.png)
1) in develop tab - enable profile correction and remove cromatic abberation
  1a) do any additional editing
2) sync these setting to all images
3) export

I like this process, because it enables me to crop out the lens hood and sun-shade I have installed on my skeletal case and do geometry correction in one go, only compressing the image one additional time, also Lightroom handles exporting tens of thousands of images with ease as well as tens of GBs of data.
Here is an example corrected image before and after.
Should I close/delete this issue? It seems that this is considered a mapillary feature and not an erroneous behaviour.

![g0026369-2](https://cloud.githubusercontent.com/assets/16122863/11541941/0c1f112a-9946-11e5-90fa-0f851b2896c3.jpg)
![g0026369](https://cloud.githubusercontent.com/assets/16122863/11541946/158d75d0-9946-11e5-9f32-56f2b244152a.jpg)

**Comment by jesolem** [comment]
@ksetdekov In this case @de-vries is right. The straightening is being applied on our end as well. We do this based on getting the GoPro wide-angle settings from EXIF. So you don't need to do this on your end. 

If you do think that Lightroom is doing a better job and you don't want our backend to straighten the photos, just remove the GoPro tags from the EXIF.
