### ISSUE TITLE
Android on Galaxy S4 Active: Images out of focus (if set to infinity)

### ISSUE THREAD

**Issue by kayD** [mapillary/mapillary_issues#159]
I tried to improve speed by setting focusing to "fixed to infinity". However, the resulting images are blurred.

![mp_inf_blur](https://cloud.githubusercontent.com/assets/316554/3200347/3f9a5c44-ed7b-11e3-9708-6cd1ba4fdb80.jpg)

Please see a reference taken with the normal camera app:

![mp_norm](https://cloud.githubusercontent.com/assets/316554/3200351/570068f6-ed7b-11e3-999f-9f0877dbca59.jpg)

Since I took the image a few days ago I am not sure whether I used Mapillary App v0.37 or 0.38, but definitely not an older version. This seems to be related to the (fixed) issue #46.

**Comment by mike1s** [comment]
I had maybe relative problem on my Samsung GT-S7710 XCover2, mapillary ver 1.13, 1.15. It tryes to focuse even "autofocus in camera" option in mapillary app swiched off. It takes a lot of time. Some other apps do same. I have read a little about camera in android, and download "camera Tester" by "M-Apps", and have read allowed params, and there are no "infinity" in "focuse-mode-values", only "auto, macro, fixed". App "Open Camera" works fine if the "fixed" option selected, which maybe corresponds to "fixed" param in androidCameraAPI, and acts same as "infinity". Another phone had "infinity" in "focuse-mode-values", and all apps works fine. So...

// English is not my native language, sorry

**Comment by peterneubauer** [comment]
Ok, can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk now and report back (v1.16)?

**Comment by mike1s** [comment]
Great! 1.16 works well on Samsung GT-S7710 XCover2, does not try to focuse, focusing distance is about infinity, shoot quickly.

**Comment by mike1s** [comment]
also, 1.16 works well on my another phone to, same as 1.15, 1.13

**Comment by peterneubauer** [comment]
Awesome, thanks for the feedback!

**Comment by filipca** [comment]
1.16 still out of focus with my Samsung Galaxy S5.
I tried with and without "Autofocus in camera".

**Comment by peterneubauer** [comment]
Can you try 1.17 from https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk and send me the log so I can see what is happening on your SGS5?

**Comment by filipca** [comment]
I installed it very meticulously twice.Settings  - version info says "version 1.16".


Ph Casteleyn 
Dahliastraat 16

2800 Mechelen

gsm 0486 516261


Date: Tue, 3 Mar 2015 02:37:27 -0800

**Comment by peterneubauer** [comment]
Have uploaded a new build, try again.

**Comment by filipca** [comment]
![screenshot_2015-03-03-14-54-21](https://cloud.githubusercontent.com/assets/6695589/6464015/a039a882-c1b7-11e4-8b15-2dfcd1b9a9e2.png)

I must be doing something wrong.

**Comment by filipca** [comment]
I just sent you the log without taking pictures.

**Comment by filipca** [comment]
Before taking pictures, to verify version.

Ph Casteleyn 
Dahliastraat 16

2800 Mechelen

gsm 0486 516261


Date: Tue, 3 Mar 2015 05:43:59 -0800

**Comment by osmned** [comment]
Same problem on my Galaxy S5. Version 1.17 is better than previous versions, although still not as good as Mapillary on another phone of mine, an iPhone 6. In walking mode I now have 1 blurred image out of 7 on my GS5, it used to be 1 out of 3. I have send my logs to hello@mapillary.com a couple of minutes ago.

**Comment by peterneubauer** [comment]
Try and send the logs @osmned , have inserted more debugging around the focus modes and callbacks. Kind of hard to track down this one.

**Comment by peterneubauer** [comment]
@osmned from the logs it looks like the shots are taken correctly with continuous-picture. After that, the Android system is deciding how and when to focus, so it's really hard to do anything more. The only thing I can think of is maybe to force focus mode auto (which will only take pictures upon successful focus, but be much slower). This right now is the failover if there is no focus mode continuous-picture supported, but maybe that should be another setting?

**Comment by osmned** [comment]
Thanks Peter. However, in the Mapillary app the autofocus on my SGS5 stays inferior, even with the latest build, compared to my iPhone 6. For now I've decided to stop using Mapillary on my SGS5. Hopefully the SGS6 will be better since it seems to have OIS. Cheers, Johan

**Comment by peterneubauer** [comment]
Of you get your hands on other devices, feel free to test and report back here - as mentioned if the autofocus mode is no good, maybe we can switch to something else.

**Comment by osmned** [comment]
Hi Peter, my iPhone 6 does the job very well, I'll stick to that phone for
Mapillary I hope Mapillary can get their hands on a SGS5 for testing
purposes :-)

Cheers, Johan

2015-03-07 20:12 GMT+01:00 Peter Neubauer <notifications@github.com>:

**Comment by filipca** [comment]
Peter or osmnl, if I install from the latest link and click on Settings :
does it show version 1.16 or version 1.17 ?

**Comment by osmned** [comment]
I got 1.17

**Comment by kaitu** [comment]
@peterneubauer: the focus mode auto sounds super for my shooting style. Could you make it work on my phone (Samsung SM-C115), which also doesn't work with continuous focus setting? 

Camera Tester reports:
focus-mode-values=auto,infinity,macro,auto-macro,fixed,face-detection,continuous,continuous-picture,continuous-video,manual,multi,touch

**Comment by peterneubauer** [comment]
The latest build lets you choose freely between the supported focus modes, does that work better to find out what works best for your device?

**Comment by kaitu** [comment]
Thanks Peter. I see the complete list of focus supported focus modes, and if I make a choice the setting will say that the selected one is the set choosen focus mode. But once I exit settings and recall them, it always says that selected focus mode is inifinity.

**Comment by peterneubauer** [comment]
Sorry,
try the latest build, reinstalling from the same address. Works?

**Comment by kaitu** [comment]
Super, working now. Continuous mode still appears to do nothing, but auto works wonderfully on my phone.

**Comment by peterneubauer** [comment]
Cool! It's hard to know how focus modes work on different implementations, so I think this might be the best compromise.
