### ISSUE TITLE
debug logs double everytime send debug log is pressed

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#1591]
I had a debug log of 500kb, pressed send debug log selected gmail. Cancelled. Did it again 1mb. Again 1.5mb

This is with the 1.62 version

**Comment by peterneubauer** [comment]
Can you try to press "clear logs" in the settings to make sure the files are deleted first?

**Comment by james2432** [comment]
I cleared the logs, same thing. Only affects normal logs(non-trace).
Attached is a log of taking 2-3 pictures, sending debug log through gmail, cacncelling, send debug logs then cancelling and finally sending. It has trippled in size

[mapillary.txt](https://github.com/mapillary/mapillary_issues/files/51998/mapillary.txt)

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
