### ISSUE TITLE
add sequence image count to profile

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1593]
The [profile view](http://www.mapillary.com/profile/zuse) has a "viewed count" with the eye logo. 
But an information how many images are in this sequence would be important, too!
Could be in the same row of the eye logo.

**Comment by jesolem** [comment]
Makes sense.

**Comment by HolgerJeromin** [comment]
The new autoplay in the thumbnail view is nice! But an image count would be a good addition :)

**Comment by jesolem** [comment]
@gyllen if everything is in place from a backend perspective, feel free to pass this to @knikel

**Comment by gyllen** [comment]
@angelday I like this idea

**Comment by HolgerJeromin** [comment]
implemented
