### ISSUE TITLE
Nexus 5X Camera Menu buttons upside down

### ISSUE THREAD

**Issue by 23cpo** [mapillary/mapillary_issues#1594]
The orientation of the buttons in the camera menu is wrong. See screenshot.

![screenshot_20151205-155337](https://cloud.githubusercontent.com/assets/5576222/11608417/d20df9f4-9b68-11e5-93a9-5dab8a80e80d.png)

**Comment by echeloni2p** [comment]
Hi!

turn the mobile 180 degrees and see...

**Comment by 23cpo** [comment]
issue remains:
![screenshot_20151205-183007](https://cloud.githubusercontent.com/assets/5576222/11609148/be461008-9b7e-11e5-90e0-d6efdc8aafe5.png)

**Comment by peterneubauer** [comment]
Looks like the phone is reporting the orientation differently, will need to look into the apis. Thanks for the screen shots!

**Comment by chrisfleming** [comment]
I think the root cause is this: https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/cwqzqgh

**Comment by peterneubauer** [comment]
This is fixed now, out in the next release. Problem is that the Camera APIs are incompatible with older devices, so we have to hack around that.
