### ISSUE TITLE
can't blur the last pixel at the bottom

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1595]
browser : vivaldi 1.0.340.7

this is sort of a continuation of issue #1290 - it allows to blur to the edge of the image if carefully and slowly approaching it - but this does not seem to work with the lower edge. here, the rectangle is drawn one pixel before the actual image edge.

note that this might be a regression - i seem to recall being able to draw such blur rectangles recently.

**Comment by HolgerJeromin** [comment]
The normal solution for this is registering the mousemove and mouseup events to the document and not the single graphical element. So the events keep coming even after leaving the image.

**Comment by oscarlorentzon** [comment]
With the tagging functionality in `mapillary-js` that will be included in the new website this will be easier. There it will be possible to move the bounding boxes towards the edges.

**Comment by oscarlorentzon** [comment]
This is now possible to do when creating the blur rectangle in the letterbox mode or by moving an already existing blur rectangle.
