### ISSUE TITLE
present upload hashes in a nicer way

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1596]
http://www.mapillary.com/map/upload/im provides two hashes for the python scripts.
right now they are presented in a nice but inefficient way:
Permission Hash: ...
Signature Hash: ....

The exact syntax is available in a [blog post](http://blog.mapillary.com/technology/2014/07/21/upload-scripts.html) two clicks away.
More useful would be a readonly html textarea with already the correct content for copy and pasting in a shell:
```
export MAPILLARY_SIGNATURE_HASH="blabla"
export MAPILLARY_PERMISSION_HASH="blabla"
export MAPILLARY_USERNAME="username from webpage login"
```

**Comment by jesolem** [comment]
Makes sense.

**Comment by oscarlorentzon** [comment]
Reassigning to our designer @angelday for decision on how this should be displayed in the new website.

**Comment by HolgerJeromin** [comment]
Still open :-)

**Comment by jesolem** [comment]
This has been fixed and deployed per #509. See https://www.mapillary.com/app/settings/developers

**Comment by HolgerJeromin** [comment]
I think you mean #2117.
But this issue is not about showing the hashes as naked strings but about having them in a convenient way.

**Comment by jesolem** [comment]
Oops, wrong issue link. Yes, that's the one I mean.

You can click the "+" sign next to the hashes and that copies to your clipboard. I think this is a very reasonable convenient way. 

Make a copy with `export ...` directly is platform dependent and you don't set env variables like that on all platforms.
