### ISSUE TITLE
Panoramas has to be well located in Map

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1597]
When I search some particular building (ex: Palau de la Música Catalana on Barcelona) Map locates it in a very far zoom, so I can't watch where it is exactly located and photo is only returned if I zoom the building...because I am Catalan and I know the zone.Please better zoom and better simbology for Panoramas, Tracks now are well located,Panoramas are only a little spot (I know I can turn on filters, but it is not useful for normal people)

**Comment by jesolem** [comment]
Better icon and zoom, agree.

**Comment by richlv** [comment]
zoom is a different topic, but exposing short sequences seems to be a duplicate of issue #1429

**Comment by knikel** [comment]
We'll have a panorama filters (#1080) and will display images as single dots on the map. Closing in favor of #1080.
