### ISSUE TITLE
Sequences inaccessible

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#1598]
I can't access any sequence when I use the exploring map. 
![image](https://cloud.githubusercontent.com/assets/8439643/11624002/58bc691a-9cd9-11e5-8209-0d630f14f0a7.png)

**Comment by jaakkoh** [comment]
I have also had some very bad experiences in selecting/activating photo sequences. Good to see that I'm not the only one with the problem as I was just thinking that it might be my at times not so steady connection that is the problem. 

This clear(?) bud aside, it seems to me that there is no defined behavior that would e.g. change the cursor of the mouse to something else when the mouse passes over the line of the sequence -- or then highlight that sequence (without yet activating it!). This would be great and IMO intuitive as it would indicate that if I now click I'll activate this specific sequence.

Anyways, it's seemed unclear to me how the selection is supposed to work. Often it doesn't and eventually getting something selected seems more like a random act of kindness from the system than any logical series of actions.

**Comment by knikel** [comment]
This will be a better experience in the upcoming update, where we use image data instead of sequence data. More precision all the way.

**Comment by knikel** [comment]
It's possible to interact with sequences in much better way now in all the modes. 👍
