### ISSUE TITLE
manual upload fails if some images have no valid GPS data

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1602]
If the verification step in the manual upload shows errors on some images, it is impossible to skip those images and upload the rest of them. The upload stalls at 0% forever. Workaround is to cancel the upload entirely and deselect the offending images.

**Comment by mxa** [comment]
It seems this one has been fixed?

**Comment by gyllen** [comment]
I think this has been working for quite some time now. Closing

**Comment by mxa** [comment]
Had this issue today again. A regression?

**Comment by gyllen** [comment]
Can you try to reproduce and see if there are any javascript errors. Thanks for reporting on this.
