### ISSUE TITLE
android camera issues in 1.67

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1603]
Hi!

tried a few sequences today with mapillary 1.67 on my android honor 7 (android 5.1.1).
With latest changes some things do not work anymore:
- it always tell me tilted, which it is not
- ignore GPS does not work anymore

aceini/echelon

**Comment by peterneubauer** [comment]
Can you please  us the logs when that happens?

**Comment by hakuchi** [comment]
same to me with 1.67 and android 5.0.2
Navi or other apps with GPS working fine.

Also crashing always when I go into review and switch 20-30 pictures or scroll up and down.

**Comment by peterneubauer** [comment]
Can you please send me the log when the GPS is not working?

**Comment by echeloni2p** [comment]
Hi

Looks like it was a one-timer. I try to reproduce under same condition, currently I cannot reproduce.

aceini/echelon
