### ISSUE TITLE
swipe transition vs stop motion in review panel

### ISSUE THREAD

**Issue by canadarunner** [mapillary/mapillary_issues#1605]
Hi, in the new version the review panel get's the feature with checking good images (green check).
After using this feature (approx. 1000 pics), I find the swipe tranisition a bit annoying, because it needs a lot of concentration to see differences.
I would propose to change it to "no-transition", just displaying the next image.
Then it would be more like a stop motion movie, which is easier to review images especially when you review thousend of images!
What your think?

**Comment by jesolem** [comment]
@canadarunner Is this Android or iOS?

**Comment by canadarunner** [comment]
It's iOS

**Comment by millenbop** [comment]
The animation improves usability, but I can see why it can make one less productive. I've seen more users request this (although for Android) so I'll add a little switch so you can turn it off.

Thanks for the feedback!

**Comment by millenbop** [comment]
This has been added now, will be out in the release after the one we have in review now.
