### ISSUE TITLE
Mapillary reports phone as being tilted 

### ISSUE THREAD

**Issue by skorasaurus** [mapillary/mapillary_issues#1606]
I have a s5, running android 4.4.4; 

Mapillary is reporting that my phone is tilted and will not begin a sequence as a result. I hadn't modified anything in my setup except for upgrading the app on Wednesday or Thursday this week. 

I upgraded the apk again today and am still experiencing the same issue. 

Here's the debug log from my most recent sequence attempt: 
https://gist.github.com/skorasaurus/d0cff7cd0efc7a54bbd4

**Comment by nighto** [comment]
I had this issue running 1.6.7, and was fixed with @peterneubauer 's 1.6.8 apk.

**Comment by peterneubauer** [comment]
Yes, this should be fixed now?
