### ISSUE TITLE
Remove artificial delay in web viewer between picture load and blur load

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1607]
Sometimes I try to thoroughly review my sequences for incorrect blurs. This involves stepping through pictures one-by-one in the web viewer. It has always annoyed me that when stepping through a sequence with blur editing enabled, it takes so long to load up blurs. Today I took a look at the browser's activity and realized that it looks like there is an artificial delay of a whole second or more built in between the time a new image is loaded and when blurs, traffic signs and other information is requested. See this graph from the chrome dev tools:

![image](https://cloud.githubusercontent.com/assets/348948/11768623/7e573b00-a198-11e5-81cd-8f9909fe956d.png)

I'm guessing this may have been put into place to reduce load on the server when people are paging through pictures quickly. But if I have the blur (or traffic editing) option active then this delay is undesirable. Without it I could review my sequences in a fraction of the time it takes now.

**Comment by de-vries** [comment]
related to #1268

**Comment by richlv** [comment]
as per comment from @knikel - "At the moment it is intentional that blurs are fetched when your move halts on the new photo."

adding batch preload (for example, loading blur for next/previous 10 images is less than 6 images in that direction have blur info) would probably solve this issue, too - so all hopes on #1268 :)

**Comment by ToeBee** [comment]
Yeah, I think I'll go ahead and close this one as a duplicate of #1268. My search terms were apparently wrong when I tried to find existing issues before opening this one.
