### ISSUE TITLE
[Android] app makes B&W photos in suboptimal lighting

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1608]
On my Jolla phone I get photos that are mostly in black and white when the lighting is suboptimal. Only bright colours get trough. It looks like some hipster filter is applied. I've never seen this behaviour with the camera app.

Here is an example: http://www.mapillary.com/map/im/97lxWhWi5y5epuX_8MYfWA/photo
compare it to the photo on right of it

**Comment by peterneubauer** [comment]
That's probably a Jolla hipster feature - would need a Jolla phone to recreate that. Closing it for now - we don't tamper with any camera settings regarding color.
