### ISSUE TITLE
Support for multiple storage locations (Android)

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1609]
I have 32GB of internal storage and 128GB of external SD card storage. Once in a while I run out of space on the external storage, and I would love for the application to automatically switch to internal storage.

I would find it very useful if it was possible to select multiple photo paths, like:
1: /storage/extsdCard/Android/data/app.mapillary/files/mapillary
2: /storage/emulated/0/Android/data/app.mapillary/files/mapillary

When storage location 1 is full, it continues to location 2.

**Comment by hakuchi** [comment]
some days ago a other user reported this [#1512] (https://github.com/mapillary/mapillary_issues/issues/1513)

**Comment by peterneubauer** [comment]
Let's track it there. Thanks guys for reporting!
