### ISSUE TITLE
Mapillary Android app is very slow to start when there are many photos waiting to be uploaded.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1610]
When I start the Mapillary app, I sometimes have 1-2 minutes of black screen before the menu shows up. My guess is that it is scanning all the photos when the application opens.

Is it possible to improve this?, maybe have a background thread count the files and report back when done? Maybe cache the result from the previous runs and have a "rescan button".

**Comment by rsahlin** [comment]
Hi @jrcarlsen and sorry for the late answer

Could you please retest with (at lest) version 2.20?
If the problem persists could you please re-open this issue and explain exactly how to reproduce?

Best regards
/Richard
