### ISSUE TITLE
5X Photo orientation still not fixed

### ISSUE THREAD

**Issue by tocophonic** [mapillary/mapillary_issues#1612]
In one of the recent updates I saw something about "Nexus 5X orientation fixed".

While the orientation of the UI itself is now fixed, the photos taken when holding the phone 90° CCW are still upside down - even after uploading.

The only way to take correct photos with the Nexus 5X as of now is holding it 90° CW which is a rather uncomfortable position imo. Please make it possible both ways.

**Comment by peterneubauer** [comment]
So the preview is correct but the photos taken are upside down in 90 degrees ccw position?

**Comment by chrisfleming** [comment]
My  photo's appear to be 180 degress out. See http://www.mapillary.com/map/im/ykyAta2XXBVvcIquiY9dIw/photo  (very lucky to have got access for those pics)

The navigation, left/right seems to be 90 degrees out. (so showing as up down rather than left right I think)

**Comment by tocophonic** [comment]
@peterneubauer Exactly! As the camera sensor is rotated 180° compared to most handsets, you might want to check out this: http://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation(int)

**Comment by tocophonic** [comment]
Attention: Since you guys fixed the camera UI orientation apparently ALL photos taken with a Nexus 5X are upside down - no matter if you're holding the phone 90° CW or 90° CCW!

**Comment by peterneubauer** [comment]
Ok, trying to organize myself a nexus 5X ... also I think the only way to solve this is to implement a new Camera2 API camera class, I will start on this over Xmas.

**Comment by tocophonic** [comment]
Thanks @peterneubauer, would be really great to soon be able to contribute to Mapillary again (without having to manually rotate the images)! The 5X has a great camera, the pictures I uploaded so far look pretty nice.

**Comment by peterneubauer** [comment]
Also, there might be the Samsung Galaxy S6 falling into this category, see https://spectrastudy.com/camera2-api-on-mwc-2015-devices/

**Comment by rsahlin** [comment]
Thanks - looking into dokumentation of Camera2 now.

**Comment by chrisfleming** [comment]
Latest update (version 205) has fixed this. test picture at https://www.mapillary.com/map/im/BHRdaNvnwFfOrCAyjHRycQ/photo

**Comment by rsahlin** [comment]
Thank you ever so much for the good news!

I did a lot of tweaks from version 2.0 in the blind since I do not have a 5X :-)
Nail in the coffin for this long-winded issue!

Best regards
/Richard

**Comment by peterneubauer** [comment]
This is the first tangible outcome of a complete rewrite of the camera part by @rsahlin, great to close this!

**Comment by tocophonic** [comment]
I'm sorry having to say this, but the photo orientation has **not** been fixed for me and my 5X. I tried shooting a sequence this morning with the most recent Mapillary version. When I press "Review sequence" all the photos are still upside down. I took the sequence holding the phone 90° CCW (like you normally do when you take a horizontal photo with a phone).

Screenshot: [http://imgur.com/DdOAeTi.png](url)

**Comment by rsahlin** [comment]
Hi @tocophonic 

Could you please verify what version of the app you are using?
In your Feed choose Settings and scroll down to Mapillary version info

Best regards
/Richard

**Comment by zagor** [comment]
It should probably be clarified that this is only fixed in the beta version (2.05) so far. The non-beta version in Google Play (1.85) is still broken.

**Comment by rsahlin** [comment]
Exactly, thanks @zagor :-)

/Richard

**Comment by tocophonic** [comment]
@rsahlin Thanks for the clarification, it is indeed 1.85. When will the Play Store version be updated to 2.05? Guess you guys still have to test before doing so. In the meantime, where can I grab the beta version (as far as it's public)?

**Comment by rsahlin** [comment]
Hi @tocophonic 

You are most welcome to join the open Beta group - go into 'Feed' and scroll down to 'Join Beta Group' - within a couple of hours you should get the beta version :-)

Yes we are still tracking down bugs and doing testing, my hope is to have a release version out within a week.

Thanks for your support!

Best regards
/Richard

**Comment by zagor** [comment]
I'm surprised to see that this problem has reappeared. Version 3.48 captures all photos upside down on my Nexus 5X.
![screenshot_20170416-153238](https://cloud.githubusercontent.com/assets/229360/25071558/f520f01a-22ba-11e7-9a5c-39d2f80dc920.png)

**Comment by utack** [comment]
@zagor did you recently update Android?

**Comment by peterneubauer** [comment]
Yes,
This should be fixed in the latest releases, 3.48, out now, has the fixes
and works on myicam Nexus 5X.

**Comment by zagor** [comment]
@utack Yes, I got Android 7.1.2 a couple of days ago. Did they flip the camera??

**Comment by zagor** [comment]
@peterneubauer The screenshot above is from Mapillary 3.48

**Comment by peterneubauer** [comment]
Does that even happen if you turn the phone a bitoee than 180 degrees? The threshold for the rotation might not kick in soon enough...

**Comment by utack** [comment]
@peterneubauer are you sure you are reading the orientation correctly, instead of using a hardcoded list of "flipped" phones?  
@zagor should be easy to verify, if an ancient version of Mapillary without the fix sees the camera correctly now, then a double flip (in Android and Mapillary) happened instead of just one

**Comment by peterneubauer** [comment]
The orientation is not hard coded, but the threshold might need to be
adjusted. I think I noticed that it reacts at 180+ degrees, we will adjust
that that to be 90+ degrees instead for upside down.

On Apr 16, 2017 4:55 PM, "utack" <notifications@github.com> wrote:

@peterneubauer <https://github.com/peterneubauer> are you sure you are
reading the orientation correctly, instead of using a hardcoded list of
"flipped" phones?
@zagor <https://github.com/zagor> should be easy to verify, if an ancient
version of Mapillary without the fix sees the camera correctly now, then a
double flip (in Android and Mapillary) happened instead of just one

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/1612#issuecomment-294355899>,
or mute the thread

**Comment by zagor** [comment]
@peterneubauer The upside down sequences today were captured with the phone turned 90° left, i.e with buttons up and usb connector to the right. The tilt reading (I have verbose enabled) hovered around 0°.

**Comment by zagor** [comment]
Here are new screenshots with detailed stats enabled from 3.54. Let me know if there is anything else I can do to help.
![screenshot_20170427-124411](https://cloud.githubusercontent.com/assets/229360/25480177/f9236e50-2b47-11e7-99fa-e2a9025db34e.png)
![screenshot_20170427-124549](https://cloud.githubusercontent.com/assets/229360/25480176/f91f5dba-2b47-11e7-8766-1443e2ca906a.png)

**Comment by peterneubauer** [comment]
Björn,
where are you located? On my local Nexus 5X this is not happening, I would
love to hook up and debug this directly.

**Comment by tocophonic** [comment]
Peter,
judging by the Taxi number 15 00 00 and the name on the building Björn is located in Stockholm.
:)

**Comment by zagor** [comment]
Didn't you decode the gps coordinates? :)
Yes, I am in Stockholm.

**Comment by zagor** [comment]
This is now fixed since a while back. Sorry for not updating the ticket earlier.

**Comment by katrinhumal** [comment]
@zagor thanks! Closing then :)
