### ISSUE TITLE
incorrect user profile used for page title

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1613]
open profile of some user "a". notice how the page title is "a's profile".
switch to images from another user (for example, by clicking on a sequence line in the map view).
notice user "b" shown in the lower left corner, while page title still is "a's profile".

**Comment by knikel** [comment]
We have a static title for the whole viewer app; dynamic titles will come. I'm closing this as it's been filled as a bug and we track adding dynamic titles internally already.
