### ISSUE TITLE
Sign Game repeated sign/missing sign

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#1614]
See attached screenshot

<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/802652/11837438/950854dc-a3bf-11e5-94b1-647021698fa1.png">

As you see left turn is repeated, while right turn is missing, I bet one of those left turns are supposed to be a right turn

**Comment by jesolem** [comment]
Yes, the one on the last row. -> @knikel

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
