### ISSUE TITLE
Android phone gets very hot and drains battery fast, when screen is off.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1616]
I have noticed that when Mapillary is in camera mode and you turn the screen off (by pushing the power button), the phone gets very hot. I think the camera might still be active.

Samsung Note 4
Android 5.1.1
Mapillary 1.68

**Comment by peterneubauer** [comment]
Mmh,
I dubble checked - the CameraActivity is going into pause and is releasing the camera:

     @Override
    protected void onPause() {
        // unregister listener
        super.onPause();
        shake.onPause();
        compass.stop();
        myOrientationEventListener.disable();
        cameraSurface.getHolder().removeCallback(this);
        stopAutoSequence();
        stopLocationUpdates();
        if (mCamera != null) {
            mCamera.stopPreview();
            mCamera.release();
            mCamera = null;
        }

        //clean out empty sequences
        Utils.getSeqDirs(new File(StorageUtils.getInstance().getDefaultImageStoragePath(this)));
    }

Not sure what it could be. Is there anything active in `logcat`?

**Comment by jrcarlsen** [comment]
I am collecting more information about this, please keep the ticket open.

**Comment by peterneubauer** [comment]
Ok,
thanks @jrcarlsen !

**Comment by jrcarlsen** [comment]
Ok, when the camera is left on and the phone is turned off, the GPS stays on and the phone stays in the awake state.

![screenshot_2015-12-22-16-56-13](https://cloud.githubusercontent.com/assets/10294605/11952724/465ed212-a8cd-11e5-8826-41d5c45fe6ea.png)

I am not sure how to capture information from `logcat`.

**Comment by jrcarlsen** [comment]
I forgot to mention what the graph shows.
The drain is fast when the phone was "turned off" while the Mapillary camera was running.
The drain is slow when the phone was "turned off" while on the Mapillary feed screen.

I switched back and forth a few times to confirm. The drain might be entirely from the GPS, but I am not sure about that yet.

**Comment by peterneubauer** [comment]
Ah great, will try to see if there is a location listener not
unregistered...

**Comment by jrcarlsen** [comment]
I will also do a bit more testing to see if the GPS accounts for all the battery drain. Tomorrow I will have the GPS on for an hour and Mapillary on for an hour and check the difference. If it looks similar, then this is probably just a GPS issue.

**Comment by simonmikkelsen** [comment]
I have seen the same happen: I close the Mapillary app, either by pressing the power button or just switching app. Over night the battery is drained 50% by doing nothing. Androids battery monitor reports that the majority of the power is used by Mapillary, that also has a very high number in GPS consumption.

Workaround: Kill Mapillary when done.

**Comment by peterneubauer** [comment]
Fixed in the forthcoming 1.71, thanks!
