### ISSUE TITLE
Photo capture screen reopens repeatedly

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1617]
I have Mapillary 4.0.6 (72) on iPhone 6, iOS 9.0.2, jailbroken and with a hack to enable force touch quick actions.

Today I took some pictures in riding mode. I started the application from the "Riding Mode" quick action. That worked just fine.

But now, when I open the app, I'm taken straight to the capture screen right away, and if I close it with the (X) button, it just immediately opens again. This persists even after force-killing the app from the application switcher. There is now no way to get to the Upload screen.

This is similar but worse than #1566, because it doesn't reopen just once.

**Comment by nicolas17** [comment]
I upgraded to 4.1 and the same problem happens.

**Comment by millenbop** [comment]
Hmm that doesn't sound good. Unfortunately I don't have access to a jailbroken iPhone 6 that's hacked, all I have is a colleague's iPhone 6s and it doesn't show that behaviour.

I'l look into how the hack works and see if I can dig up some information there that might explain the behaviour.

What you can do, for now, is that you can backup the files in the documents directory from iTunes to your computer (let me know if you want instructions), delete the app and reinstall it, and put the images back and then upload them (and stay away from the quick action until I've had a look at it).

**Comment by nicolas17** [comment]
Okay, I don't know why this happens but I know why it persists across launches. In `Preferences/com.mapillary.app.plist`, the `setting-should-launch-camera` key is set to true. If I flip it to false, the problem goes away and the app is usable again.

**Comment by nicolas17** [comment]
I just installed Mapillary 4.1 on my father's iPhone 6S with unmodified iOS 9.2 and I see the same problem. So the hack is not the cause :)

**Comment by millenbop** [comment]
Thanks! Sorry for conclusion jumping. I'll fix it when I get hold of @knikel's phone early next year as I don't own a 6s myself.

**Comment by millenbop** [comment]
Managed to borrow one from a fellow company, so it's fixed now :) Thanks for reporting.
