### ISSUE TITLE
[Traffic signs game] Traffic sign game doesn't run well

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1618]
I don't know why but these months when I try to play traffic signs  EU, with latest Chrome or latest Firefox game doesn't load well, I can do one or two pics and then Choose signals is not loading or fetching enters in a infinite loop. Sometimes I have to reload the page or toogle between EU and US game but is not guarantee.
![tfg_3](https://cloud.githubusercontent.com/assets/5250646/11912368/21a90c5c-a63a-11e5-92a2-f7fc6157a333.jpg)
![tfg_1](https://cloud.githubusercontent.com/assets/5250646/11912369/21a9f694-a63a-11e5-8903-ede82643062b.jpg)
![tfg_2](https://cloud.githubusercontent.com/assets/5250646/11912370/21aa7db2-a63a-11e5-8e01-df6355f1a75d.jpg)

**Comment by knikel** [comment]
The _Traffic Sign Game_ in its current state has been deprecated. Closing this since it will be a very different thing when we release it. We're working on entirely new backend that will make the new version of this game better. It will allow us to build other games too :smiley_cat:
