### ISSUE TITLE
Full Panoramas not working on mobile Chrome

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1619]
Couldn't turn when visualizing full panoramas ("Photo Spheres") on Chrome on Android. Tried "View as Desktop" option but nothing changed. 

Example: http://www.mapillary.com/map/im/p5FbSFI5GiRMoj8sDyMloQ/photo

**Comment by jesolem** [comment]
Thanks @nighto 

@knikel No WebGL?

**Comment by echeloni2p** [comment]
Hi!

works for me in chromium on linux.

echelon

**Comment by knikel** [comment]
Must be something going on with mobile event handlers, will investigate

**Comment by nighto** [comment]
Just tested on Chrome desktop, also can't turn when simulating mobile device.

![image](https://cloud.githubusercontent.com/assets/397851/11935832/3934e13a-a7f1-11e5-8927-1680607de420.png)

**Comment by nighto** [comment]
Don't know if it is really related, but (AFAICT by looking the code) as Mapillary uses Three.js to draw the panoramas, [this example](http://mrdoob.github.io/three.js/examples/webgl_panorama_equirectangular.html) (which seems to be similar to the code on [mapapp.js](http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-9a85c069.js) around line 12790) also does not work on Chrome on cellphone.

By the way, I couldn't really debug the events when dragging; Chrome seems to ignore my breakpoints on the ```onDocumentMouseMove``` function, but I can debug on the example mentioned, so I don't really know if I'm checking on the right place.

By the way, is [mapapp.js](http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-9a85c069.js) source on Git? It could be easier to navigate on the original files, not the concatenated one. Well, at least it's not minified. :smiley:

**Comment by jesolem** [comment]
@nighto We're working on a mapillary.js that will be open and easy to use. Will replace mapapp and the whole viewer in many cases. Stay tuned.

**Comment by knikel** [comment]
Upcoming front-end will be based on `mapillary-js` which works on mobiles (as long as there is WebGL support). Closing this as we have that implemented, but not yet released.
