### ISSUE TITLE
Turn Panoramas with cellphone sensors

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1620]
It'd be awesome if there is a button or switch on the panorama view interface that, when clicked, turns the panorama automatically when you turn the cellphone, just like the Panorama Viewer on Android.

**Comment by jesolem** [comment]
Worth considering for the future. Parking this with @millenbop for now.

**Comment by nighto** [comment]
Related documentation: http://w3c.github.io/deviceorientation/spec-source-orientation.html#worked-example

**Comment by nighto** [comment]
Related three.js example: http://threejs.org/examples/#misc_controls_deviceorientation

**Comment by HolgerJeromin** [comment]
I think this request was to add in the web frontend not in ios app

**Comment by nighto** [comment]
Yeah, this is regarding the front-end, Web version,  nothing iOS related (I'm an Android user).

**Comment by knikel** [comment]
We're tracking this in `mapillary-js` repository.

**Comment by nighto** [comment]
https://github.com/mapillary/mapillary-js/issues/139 for reference.
