### ISSUE TITLE
Center map by GPS fix in Explore mode

### ISSUE THREAD

**Issue by arky** [mapillary/mapillary_issues#1623]
In 'Explore' section of Mappillary app. Please detect the current location of the app user and center the map. This is most acceptable user experience. 

Testcase: 
1) Open the app and select 'Explore' from the side 
2) The map opens and the open street map defaults to location Malmo, Sweden

Expected Behaviour: 
The open street map should be centered based on last GPS fix or user GPS location.

**Comment by jesolem** [comment]
This is what should happen. 
Could be that since we're still using a web view for the explore map on Android, Chrome/browser does not get your location. @peterneubauer ?

**Comment by peterneubauer** [comment]
So,
if your phone has not (yet) acquired a location fix, you should be landing in the lovely town of Malmö. Is that happening @arky ?

**Comment by arky** [comment]
@peterneubauer  Interestingly this happens even when there GPS fix available as well. Not sure how to debug this further.
