### ISSUE TITLE
Upload icon in Review sequences doesn't work

### ISSUE THREAD

**Issue by arky** [mapillary/mapillary_issues#1624]
Clicking 'Upload' icon in 'Review sequences' section does not start the upload even when there are pictures marked for upload.

Platform: Android 
Version: 1.68, Version code: 168

**Comment by polarbearing** [comment]
There are a number of conditions to be met before it uploads, some of them are optional. You would need to have Wifi, or explicitly allow upload over cellular networks, or uploading while on battery. You would need to check these settings first.

**Comment by peterneubauer** [comment]
@arky is there any popup coming saying that images will not be uploaded because of one of the conditions @polarbearing mentioned are not met? Also, please send a log (from the main drawer in the app) so I can have a look.

**Comment by arky** [comment]
@polarbearing @peterneubauer  Am going to do some captures and logs as well. There are no pop-ups just not responsive..
