### ISSUE TITLE
 No way to close recording mode to return App homescreen

### ISSUE THREAD

**Issue by arky** [mapillary/mapillary_issues#1626]
Please provide an 'icon' to return to app homescreen in Camera mode. Currently you have to select the mobile phones back button (on Android) to return to Mapillary app homescreen.

**Comment by polarbearing** [comment]
What's wrong with using the back button? Why would you want the UI cluttered with another button providing the same functionality?

**Comment by peterneubauer** [comment]
Agree. The camera UI gets pretty full now, and an explicit back button is not present in native camera apps either - you use the system one.
