### ISSUE TITLE
Delete photos upon successful upload. Prompt to delete.

### ISSUE THREAD

**Issue by arky** [mapillary/mapillary_issues#1627]
Please provide an option to delete the photos that have been successfully uploaded to Mapillary screen.

The problem is that sometimes the photos can take up a lot of disk space. Trying to manually removing the photos can be tricky. If you don't know which photos are upload and which are not?

**Comment by jesolem** [comment]
Thanks @arky 
Is this Android?
Photos should be deleted immediately after successful upload.

**Comment by peterneubauer** [comment]
Hi @arky ,
the images should be removed from your phone when they are successfully uploaded. Can you please send a log when you are uploading and images are not deleted?

**Comment by arky** [comment]
Now the app is removing photos from the device after upload. Closing this bug now. Thanks!
