### ISSUE TITLE
other formats as 4:3

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1628]
Making the pictures in my car, you can see always the front of it. So I use a batch converter to cut off this part, so the format is now 16:9, quite nicer for modern screens. But after uploading to mapillary you deform them back to 4:3, 
Here is the result: 
http://www.mapillary.com/map/im/mWhsaTXxP3Jne1kT9xtrgg/photo
Note the sign isn't a circle anymore. 
Using the manual upload there are no problem with other formats.But I can use manual upload to the pictures making with the mapillary app.

**Comment by jesolem** [comment]
![image](https://cloud.githubusercontent.com/assets/136751/11919818/d343720e-a75c-11e5-96de-ae575acf9461.png)

Thanks @wegavision - Looks fine on my screen. Could it be that you have the old (fallback) viewer on your computer?

**Comment by wegavision** [comment]
Ok on edge ist works, firefox and iron not. Is this the old WebGl problem?
But it is fine that I can improve the pictures by converting them to 16:9.

**Comment by jesolem** [comment]
@wegavision It is absolutely fine to crop away the car before uploading and making it 16:9 instead!

**Comment by jaakkoh** [comment]
Not really related to the question but I've been wondering at times if you guys have plans to detect areas/surfaces in photos that don't change from picture to picture? Those are usually (in my photos) the hood of the car, the dash, some times the camera holder, etc -- and those could well be blurred in some way to put focus on the things that matter in the photos. Google does this in some way in their street view where the bottom parts of the photos are blurred (to not show the car that takes the photos). Would make sense for Mapillary too.

**Comment by jesolem** [comment]
@jaakkoh We're looking at that actually. We can then direct the viewer to only show the parts of the image without car hood if we like. Stay tuned.

**Comment by jaakkoh** [comment]
Great. Looking fwd to that -- even though the current photos do give a very "craftmanship" touch to many of the photos! ... Thinking especially about some South American photos that I bumped into recently that included a spare tire on the hood of a proper off-road "jeep" throughout the sequence... :)

**Comment by knikel** [comment]
@wegavision we found some bugs with webgl detection few weeks ago and deployed fixes. Is this still happening for you (Firefox browser)?
