### ISSUE TITLE
Use case for manual GPSImgDirection

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#163]
1. The user uploads an image with valid EXIF but `GPSImgDirection=0`
1. The system approves automatically any adjust in GPSImgDirection made into 24 hours

**Motivation:** I want to georeference photos manually using JOSM's plugins and `exiftool`, for use them in OpenStreetMap mapping. I have no device that supports the mobile app. The current version of [Geotag](http://geotag.sourceforge.net/) does not serve because Google do not must used in OpenStreetMap mapping.

**Comment by gyllen** [comment]
Closing since first issue solved and second issue solved with translation
