### ISSUE TITLE
potentially forgotten blur requests

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1630]
it is possible that the blur request for this image and a few images backwards in the sequence were made some time ago, but have been somehow missed/forgotten :
http://www.mapillary.com/map/im/OhB5EwMCmKwNhdLKI1BRpA/photo

it would be nice to deal with them. additionally, to be sure that some blur requests should be reported as missed, displaying blur request date/time as per #1629 would be useful :)

**Comment by richlv** [comment]
still the same :/

**Comment by peterneubauer** [comment]
Sorry,
I approved that blur now and it's applied along with your other requests. Thanks @richlv !

**Comment by richlv** [comment]
yay, thank you :)
might be worth finding out why it didn't show up on your blur request queue or whatever it is, but that's an internal thing and all is good here.

**Comment by peterneubauer** [comment]
It's all good.

@ed had not been able to approve all queued up blur request, so I went
ahead and did the review of the 10.000 waiting requests today :)

/peter

**Comment by polarbearing** [comment]
Well apparently the approach that only staff approves blur and change requests does not scale with a growing number of users. 

You might consider a model where a user, having requested a number of plausible changes, is promoted in trust and her edits become auto-approved.

**Comment by richlv** [comment]
they might have legal reasons for limiting this to employees only. if so, they'll just have to keep on adding interns until their autoblur is perfect ;)

**Comment by peterneubauer** [comment]
Yes,
That's what the new changesets work is aiming at.

**Comment by jotpe** [comment]
What is the status of the new changesets?

**Comment by peterneubauer** [comment]
Blurs requests should be approved within a day. If you have more than 200 approved, they will get through automatically. Edit location changesets are working, and also deletion requests are working, we just need to make the administration interface for them working. I'm working on a reasoner that checks if all changes in a changeset are on your own images and in that case automatically approves. Would that be a reasonable start?

**Comment by peterneubauer** [comment]
Blurs requests should be approved within a day. If you have more than 200 approved, they will get through automatically. Edit location changesets are working, and also deletion requests are working, we just need to make the administration interface for them working. I'm working on a reasoner that checks if all changes in a changeset are on your own images and in that case automatically approves. Would that be a reasonable start?

**Comment by jotpe** [comment]
Yes.
