### ISSUE TITLE
Camera view on my Android phone have an incorrect aspect ratio

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1633]
Samsung Note 4
Android 5.1.1
Mapillary 1.69

![screenshot_2015-12-23-02-34-46](https://cloud.githubusercontent.com/assets/10294605/11964138/2379c6fc-a91e-11e5-94f5-1c775b02400f.png)
![pm5544_with_non-pal_signals](https://cloud.githubusercontent.com/assets/10294605/11964120/fce4251e-a91d-11e5-8d06-734c066d5055.png)

**Comment by peterneubauer** [comment]
@jrcarlsen is this still the case with the latest versions?

**Comment by rsahlin** [comment]
Please retest with latest (>=2.16) version.
