### ISSUE TITLE
upload view locked in landscape mode

### ISSUE THREAD

**Issue by pgiraud** [mapillary/mapillary_issues#1635]
Problem: I can't see the estimated upload time (which is a nice new feature).

Possible way to reproduce (not sure though):
 - start an upload of pictures,
 - create new sequence and take several pictures,
 - stop sequence,
 - first upload finishes,
 - go to upload view again,
 - start the upload of the new sequence.

Device: iPhone6
iOS version: 9.2 (13C75)
Mapillary version: 4.1.1 (74)

![img_4968](https://cloud.githubusercontent.com/assets/319774/11973102/cfbe9f8c-a955-11e5-9589-8e8ebf0e7217.PNG)

**Comment by millenbop** [comment]
Thanks for reporting! Wow, that looks super weird, I'll look into it.

**Comment by millenbop** [comment]
Fixed, will be available in 4.1.3.
