### ISSUE TITLE
Profile/Uploads page doesn't support portrait mode

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1636]
The profile/uploads page doesn't support portrait mode:

![image](https://cloud.githubusercontent.com/assets/12934696/11992425/dda71a04-aa25-11e5-9a96-82ed31381abc.png)

**Comment by knikel** [comment]
Ouch, on it.

**Comment by knikel** [comment]
Thanks @shlublu, this is fixed. Visible on the profile soon.

**Comment by shlublu** [comment]
How fast! Thanks a lot @knikel !
