### ISSUE TITLE
update 1.65 on HTC desire 500 dosn't work

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1640]
I can start the app but everytime I want to take pictures it says good bye. The HTC has android 4.1.2, is this a problem?
Can I get  an old version, is there a history site?

**Comment by jesolem** [comment]
@wegavision There is a link to other older versions in the footer and they are here: http://android-releases.mapillary.io/index.html

**Comment by peterneubauer** [comment]
Closing this as it is too old. Can you try the new releases?
