### ISSUE TITLE
Help section links only work in Chrome

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1641]
The help page (http://www.mapillary.com/map/help) uses links for each question and answer, for example the link http://www.mapillary.com/map/help?q=what-is-mapillary links to the first question.

However, these links only work in Chrome. In all other browsers I tested, the link redirects to http://www.mapillary.com/map/help, with none of the sections opened.

Note: common practice is to use "fragment identifiers" for these kind of links, for example http://www.mapillary.com/map/help#what-is-mapillary (See https://en.wikipedia.org/wiki/Fragment_identifier)

**Comment by knikel** [comment]
This was a bug with the help section mini map, we've moved the content of `mapillary.com/map/help` to user wiki, and we'll be parsing and processing it to build static page that gets deployed together with `mapillary.com`. Closing since, the help page links to wiki now.
