### ISSUE TITLE
API allows creating invalid blurs

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1642]
The API allows me to submit invalid blur requests. For example:
* Blur rect with left=0.3 and right=0.1, making it a rectangle of negative width, [like this](https://www.mapillary.com/map/im/XjUMrGSVKP_wXO3GWPu2fg/photo).
* A zero-size blur rect with `[0, 0, 0, 0]`, [like this](https://www.mapillary.com/map/im/SNHKMbfjBMxePBh6k801jQ/photo).
* A blur rect going outside the bounds of the image with `[-0.1,-0.1,0.1,0.1]`, [like this](https://www.mapillary.com/map/im/rdRZ41G5DNCdW3dQIENmYA/photo).

All of those should return `parameter_invalid` (preferably with a descriptive `message` so the developer knows the problem is the coordinates and not something else in the request).

**Comment by gyllen** [comment]
Thanks for reporting, now fixed. Note that documentation is updated to `bs[rect]	Placement of blur as a rectangle, [NorthWest, SouthEast] -> [[x,y],[x,y]]` for area

**Comment by gyllen** [comment]
Still some errors, investigating.

**Comment by gyllen** [comment]
Found some internal issues with letting none mapillary apps creating blurs, Im disabling this feature for all none Mapillary apps until issue is solved, to avoid experiments with API.

**Comment by gyllen** [comment]
Issue is now fixed and I opened API for the user scope again, sorry for the delay @nicolas17.
