### ISSUE TITLE
API authentication errors must include WWW-Authenticate header

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1645]
[RFC 6750 (OAuth Bearer Token Usage) section 3](http://tools.ietf.org/html/rfc6750#section-3) says that if I do an API request that needs authentication, but I don't send authentication, or I send an invalid token, or the token I send doesn't have permissions to access the given resource (eg. insufficient scope), the `401 Not Authorized` response MUST include a `WWW-Authenticate` header. Refer to RFC for details on what it should contain.

Note this is totally low-priority because it doesn't break any use case of mine. Spec compliance is just generally a good thing :)

**Comment by jesolem** [comment]
Thanks for reporting @nicolas17

**Comment by gyllen** [comment]
@ptpt If applicable please file internally.

**Comment by ptpt** [comment]
Thanks, @nicolas17. This is very useful. Filed internally.
