### ISSUE TITLE
Profile webpage uses 100% CPU

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1646]
If I go to my profile, in the list of uploaded sequences, my web browser uses 100% CPU and my laptop heats up. The UI is still responsive. This is on Chromium 47.0.2526.80, Debian Jessie.

I tried to run the profiler in Chrome developer tools, but it wasn't very useful, I just see layers and layers of abstraction in AngularJS and couldn't find real work being done.

**Comment by de-vries** [comment]
Same here, only cpu is around 25%, so its using a full core I guess. If I switch to another tab cpu goes down again.

FF 43, ubuntu 15.04

**Comment by knikel** [comment]
To work around this issue until we overhaul profile pages, I've added pagination.

**Comment by nicolas17** [comment]
Sorry, this didn't solve the problem at all. There must be some kind of infinite loop bug in the JS code.

Any profile with "enough" sequences (eg. enough to cause pagination) still uses 100% CPU even when looking at a single page. If I look at [a user with only two sequences](https://www.mapillary.com/profile/pule), the CPU usage is still over 30% (on my particular browser and CPU).

**Comment by knikel** [comment]
Thanks for the feedback @nicolas17. I'll disable the _sequence player_ in that view for the time being then.

**Comment by knikel** [comment]
The profile pages should behave better now, thanks!

**Comment by de-vries** [comment]
in FF the profile page looks shitty now.

**Comment by knikel** [comment]
@de-vries should look a bit better now. `layout: flex` is hard :wink:
