### ISSUE TITLE
Registering a new application doesn't reload list

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1647]
If I go to [my list of applications](https://www.mapillary.com/map/settings/integrations), click "Register application" and submit the form, the application is properly registered, but the list of applications doesn't update, so my new one doesn't appear. I have to reload the page to see it.

It's interesting to note that if I delete an app or revoke a token, that *does* make the list update immediately.

**Comment by knikel** [comment]
Will be reworked in the new front-end. Will close when we roll it out.

**Comment by nicolas17** [comment]
This is fixed in the new website.
