### ISSUE TITLE
Delete photo:show wrong number of photos to delete, at review sequences

### ISSUE THREAD

**Issue by VanesaPortilloRojas** [mapillary/mapillary_issues#1648]
**
![screenshot_2016-01-02-18-21-21](https://cloud.githubusercontent.com/assets/7023211/12079481/6cc01812-b219-11e5-88a7-84719fa2d28d.png)
![screenshot_2016-01-02-18-21-43](https://cloud.githubusercontent.com/assets/7023211/12079482/6cda24fa-b219-11e5-9fd2-81df97b2e426.png)

**Requeriments**: have a sequence to review with several photos (ten for example)
**Tested on**: android 4.2.2
**Steps**:
1 Select "review sequences" from menu
2 Choose a sequence
3 long tap on a photo, to select it
4 click on delete option at top right
5 see: "do you really want to delete these 1 mapillary photos?" confirmation message, and tap on "ok" and the photo will be deleted
6 select another photo with log tap(just one)
7 click on delete option at top right
8 see: "do you really want to delete these 2 mapillary photos?" confirmation message

**Actual result**:
 "do you really want to delete these 2 mapillary photos?" confirmation message is showed.
**Expected result**:
 "do you really want to delete these 1 mapillary photos?" confirmation message should be showed

**Comment by ovivoda** [comment]
Closing this one as the UI was changed and does not allow multiple selection
