### ISSUE TITLE
'meta' file listing reviewed photos grows exponentially

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1649]
In the photo review part of the iOS app (4.1.1 / 74), when going from the image list to a particular image, or from the image list back to the list of sequences, the `meta` file storing the list of approved photos grows *exponentially*.

To properly see what's going on when reproducing the bug, you need some way to see the contents of the `meta` file while the application is running. I'm using `ifuse` to access the app's document container via USB from Linux. Xcode might have something better.

1. Take some new photos, or find a sequence with no reviewed photos.
2. Go to Upload, open the sequence, and open a photo in it. At this point, the `meta` file contains the plist equivalent of `{"approved": []}`.
3. Approve the photo. Its path is added to the meta file. To simplify, let's say the array is now `[A]`.
4. Approve another photo. Its path is added to the meta file. It now has `[A,B]`.
5. Go back to the list of pictures in that sequence.
6. Go back to the sequence list.
7. The file now doubles in size, containing `[A,B,A,B]`.
8. Open that sequence again.
9. Open any photo in the sequence.
10. The file grows to `[A,B,A,B,A,B,A,B,A,B,A,B,A,B,A,B]` (16 entries).

Swapping steps 6 and 9 has the same result. Opening a picture or going back to the sequence list both cause the array length to square.

It's interesting to note that if you un-approve A at this point, *all* instances of A will be removed, and the array will contain [B,B,B,B,B,B,B,B].

If you try these steps but approve more than 2 photos and/or repeat the steps multiple times, the exponential growth gets so bad that `meta` can become hundreds of megabytes large and opening the sequence crashes the app.

From normal use (not synthetic testing), I ended up with a 426MB `meta` file with 2832489 total items in the array, 339 unique paths, most paths appearing 109395 times each. I can no longer open this sequence in the app, since it runs out of memory. (Obviously I can work around it by simply deleting `meta`).

**Comment by millenbop** [comment]
Hey, thanks for reporting. It's a known issue and is fixed. We submitted an update to Apple before they closed down for Christmas but it's still waiting for review.

**Comment by nicolas17** [comment]
New version (4.1.2 / 75) is now in the appstore, I updated and I confirm it's fixed :grinning:

**Comment by millenbop** [comment]
Happy to hear!
