### ISSUE TITLE
Straight line on the map, Part II

### ISSUE THREAD

**Issue by kayD** [mapillary/mapillary_issues#165]
Hi,

please have a look at

http://www.mapillary.com/map/im/1JOGX61pQiJqgcKnF4fmqA

In contrast to #132, the image does not belong to two consecutive points far away. The first point seems to belong to another sequence that has been recorded earlier, while the next point in the sequence,

http://www.mapillary.com/map/im/sUhx3ARnWGtVMFVh8JwWSQ

has been recorded later as another sequence.

So it seems that a picture has erroneously been included into the wrong sequence. Possibly by the same App, because it was recorded by the same user.

**Comment by gyllen** [comment]
Sequence cut is now added in the editor.
