### ISSUE TITLE
Sometimes doesn't insert all the needed EXIF tags in pics

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#1652]
From 1295 pictures I took in multiple sequences, 6 files failed to have all the needed EXIF tags (and thus can't be uploaded):

http://naoliv.iq.unesp.br/osm/mapillary/failed-pics/

While they have `Geodetic Survey Data: WGS-84` in the EXIF, it seems to lack all the other needed data.

Somehow Mapillary failed to insert them.

**Comment by jesolem** [comment]
@naoliv What app did you use?

**Comment by naoliv** [comment]
Mapillary itself, version 1.69
I still have all the sequence in the phone, if this can help.

**Comment by naoliv** [comment]
Oh, to upload I did use mapillary_tools, but the problem here is in Mapillary (it didn't include all the needed EXIF tags in the pics).

**Comment by naoliv** [comment]
For example, in the same sequence this pic is right (has latitude and longitude):
http://naoliv.iq.unesp.br/osm/mapillary/failed-pics/2015_12_28_12_11_15_712.jpg

While this one lacks lat and lon:
http://naoliv.iq.unesp.br/osm/mapillary/failed-pics/2015_12_28_12_11_18_003.jpg

**Comment by peterneubauer** [comment]
Mmh,
the location is written by the phone itself - we are only adding the ImageDescription and Direction tags into the EXIF. However, the second image lacks ImgDescription - did you get any error on the phone or is this the last image in a sequence? It might be that the background task did not finish to write the data ....

**Comment by naoliv** [comment]
I was using mapillary in manual walking mode, just changing my view and pressing the button.
Nothing wrong appeared on screen while taking the pics.

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
