### ISSUE TITLE
better error reporting or upload retry with android upload

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1653]
I have a quite buggy DSL. Uploading 12 images lead to 1/12 to 12/12. After that i got a "network problems" message. With 3 images left in the sequence.
My first thought was: but i have seen all 12 images uploading success full!
After reading the logs i found
`D/app.mapillary.android.sync.UploadService(23855): sleeping. failed: 3, success 8, total 12`

Probaby mapillary should retry uploading the images, if the problem was a timeout.

**Comment by ovivoda** [comment]
This should be fixed in the new release
