### ISSUE TITLE
Photos are uploaded and on map, but no sequence is created

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1654]
A few weeks ago (dec 15) I uploaded a large collection of photos, 1114 photos in one sequence. Afterwards all photos appeared on the map, but they are not connected in a sequence. They are just separate single photos.

The photos are screen caps from a video, location data was added using ExifTool (through GeoSetter), orientation data using the Mapillary Perl tools. The photos were uploaded using the upload web page.

During upload the webpage timed out a few times, but seemed to continue without problems after re-selecting the photos for upload. (This regularly happens for me, and has never before been a problem.) After uploading I received both the "We have successfully registered your upload" and the "Your upload is on the map" emails.

All 1114 photos seem to be uploaded, they can easily be seen using the edit page in Mapillary. But they are not connected, and no new sequence was added to my profile page. There is also no Sequence key on any of the Photo details pages.

I've used the exact same process as I've successfully used several times before.

The first image of the "sequence": http://www.mapillary.com/map/im/5hpNW7AxPipmATySYXIPLQ/photo
The last: http://www.mapillary.com/map/im/KjJ4SUmowiQWIVzOkiAoJA/photo

For comparison, here is a similar sequence that did not have any problems: http://www.mapillary.com/map/im/sgTDBifsX4xqNTYEYBZM5w/photo

**Comment by jesolem** [comment]
Strange. We'll need to investigate.

**Comment by pbb72** [comment]
Thanks! :)

**Comment by peterneubauer** [comment]
@gyllen I think this is right - there is not sequence associated with the images. We need to investigate why the harvester did not assign any sequence id here.

**Comment by gyllen** [comment]
@peterneubauer Checked the database they are connected in a sequence, its seems like the replication to slimdb might not have happened though. Investegating.

**Comment by echeloni2p** [comment]
Moin

Something like that happend to me:
In profile activity page, all uploads were shown. But on the map and on Upüloads section in user profile, some tracks are not shown.
E.g. http://www.mapillary.com/map/s/XybKjeT-S9qse2cULakPJQ

aceini/echelon

**Comment by pbb72** [comment]
@echeloni2p that link does not seem to work?

**Comment by kaitu** [comment]
Maybe related, maybe not. I have a picture which does belong to a sequence, but is not shown:

sequence:
http://www.mapillary.com/map/s/T2OlXjZuWxRlEc1DOBcMpw

unviewable photo:
http://www.mapillary.com/map/im/DMI3ebBUQK1Br3MGROzKdg

**Comment by echeloni2p** [comment]
pbb72: correct. But in activity tab http://www.mapillary.com/profile/aceini/activity you can see the link and a picture for it (and: 2 days ago aceini added 355 photos).
But it does not work. Backend has issues.

aceini/echelon

**Comment by pbb72** [comment]
I see what you mean @echeloni2p. However, in your case clicking on the photo gives you an empty viewer. In my case, clicking on the photo does open the photo in the viewer, but it's not part of any sequence.

Your sequence returns a 404 Not Found error message, while mine returns 200 OK. I think they are unrelated problems.

**Comment by gyllen** [comment]
@pbb72 Your sequence is now fixed, thanks for reporting

**Comment by gyllen** [comment]
@echeloni2p We are still looking into your error, at the moment what I can see is that lon/lat is 0 for the whole sequence (which basically causes the sequence to be empty).

**Comment by gyllen** [comment]
@ybkuang Please check image `hcxk01jyH9wIpH01M0gZeQ`

**Comment by ybkuang** [comment]
@gyllen there is no gps information in the EXIF of that particular image. @peterneubauer it is from the Android app on a Huawei, is this a known issue?

**Comment by echeloni2p** [comment]
Hi
ok, mine is also Huawei, Android 6 now. Made with the mapillary app, but "ignore GPS data" activiated. Usually it does include GPS data into the pictures, as later on tracks did have them.

echelon

**Comment by pbb72** [comment]
Thanks, @gyllen ! The sequence works great now :-)
