### ISSUE TITLE
"Upload is on the map" email still offers to nominate for MapillaryWalk

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1656]
When I upload photos to Mapillary and they get added to the map, I receive a notification email which says:

> The N photos you uploaded in M sequences are now visible on Mapillary. 
> 
>We will continue to do processing on them and connect your photos to others (and yours) contributions.
>
>Nominate your photos to #MapillaryWalk
>Find out more!

But the Mapillary Walk challenge finished more than a month ago. It's no longer possible to nominate photos.

**Comment by knikel** [comment]
Sorry about that @nicolas17. This has been fixed. Thanks a lot for reporting!
