### ISSUE TITLE
Erroneous tilt behaviour ?

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#1657]
To me it seems like there is a flaw in how the accelerometers are being read. In the map-in-camera view, if I rotate the phone about the centerpoint of the camera image, keeping the direction to which the camera is pointed constant, the "beam" on the map changes direction, which I think it shouldn't.

On iOS, version 4.1.2

**Comment by millenbop** [comment]
Thanks for reporting!

I'm not really following what's wrong, sorry! Are talking about the red line across the screen? Or are you talking about the direction of the map not being correct?

**Comment by Virtakuono** [comment]
I think this might have become obsolete. Now that I have updated the app, I am unable to reproduce this (at least as I happen to be indoors now...). In case this is still of interest to you guys, I'll try to describe better how the bug was.

If I in the camera view I clicked the map icon, the camera view goes into a little separate "picture in picture". In the main screen, there was a green "beam" or a "sector" that indicated the direction to which the camera is pointing. Now, if I rotated the camera in a way that keeps the camera pointing in the same direction, the green beam turned, which I believe it should have not.

I hope this description helps...

**Comment by millenbop** [comment]
I cannot see any errors here either so closing for now. Please let us know if you run into the problem again and we'll reopen the issue.

**Comment by Virtakuono** [comment]
Ok, here's a video that shows the behaviour.
https://youtu.be/7Oslt56KUso
Should the blue "beam" not keep pointing in the same direction on the map?

**Comment by millenbop** [comment]
Ah now I understand, thanks for the video. We don't rotate the map in the app so it's a MapboxGL bug. I see they posted a new version so I'll try to integrate that and see if it's fixed. If not, I'll file an issue.

**Comment by Virtakuono** [comment]
Seems to work properly now, as of version 4.4.6. Just tested.

**Comment by millenbop** [comment]
Oh I didn't read the description of this issue before referencing -- I thought it was about the lag of the red line, so this is def not related to #2088.

Strange that it works for you! This bug (#1657) is still happening for me.

**Comment by Virtakuono** [comment]
Ok. This is getting even weirder. I walked out just to see that it works, since you mentioned that for you it doesn't for you. Despite trying, I could not even get the "beam" that indicates the direction of the camera visible on the map view...

**Comment by millenbop** [comment]
Which mode did you use? It's only visible in Walking and Manual (I think)

**Comment by millenbop** [comment]
Mapbox don't wanna fix it, see https://github.com/mapbox/mapbox-gl-native/issues/9828
