### ISSUE TITLE
JOSM plugin login doesn't seem to work

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#1660]
That's really it. When I click Login in the JOSM settings Mapillary tab my browser opens and takes me via https://www.mapillary.com/connect/?client_id=T1Fzd20xZjdtR0s1VDk5OFNIOXpYdzoxNDYyOGRkYzUyYTFiMzgz&scope=user%3Aread+public%3Aupload+public%3Awrite&response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A8763 to https://www.mapillary.com/map . I have no clue what's wrong or why this happens.

The setup in question is: Win 7, JOSM 9067, JOSM plugin v 31895. And the computer is running Java 7 (which it prompts about at startup).

The login worked before. Can't remember for sure if it was this Win machine or my Ubuntu, though.

Any ideas?

**Comment by knikel** [comment]
@jaakkoh This is a bug with JOSM plugin. As a temporary workaround please remove `/` after the `connect` and you should authenticate without any problem. PR is sent to fix that.

**Comment by knikel** [comment]
This fix been merged to master, will be released soon: https://github.com/floscher/josm-mapillary-plugin/pull/2

**Comment by floscher** [comment]
Thank you for the bug report, it was literally only one character in the wrong place that made the difference. One URL had [one trailing slash too much](https://github.com/floscher/josm-mapillary-plugin/blob/d0c605beda19c3a4b01afec7cfd46138b6d62b67/src/org/openstreetmap/josm/plugins/mapillary/utils/MapillaryURL.java#L69), another one [missed a trailing slash]().

The new version [`v1.1.4`](https://github.com/floscher/josm-mapillary-plugin/releases/tag/v1.1.4) aka `r31976` is now released and already distributed by the built-in plugin update mechanism of JOSM.

**Comment by jaakkoh** [comment]
Great. Works well with the tiny work-around tweak. .. A step closer to trying to see how convenient uploading DSLR taken photos turns out to be.
