### ISSUE TITLE
iOS app does not stop taking pictures when memory is full

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#1661]
In riding or walking-auto mode the iOS app is taking pictures even when memory is full. The pictures will not be stored, but the app is playing the "shooting" sound. So there is no (audio) feedback.
It would be good if either the app stops playing the "shooting" sound or is playing another "oh-ohh!" sound when saving the picture fails.

**Comment by millenbop** [comment]
Thanks for reporting! Will look into it!

**Comment by nicolas17** [comment]
Good thing I found this bug report, since I'm likely to run out of storage this week! I really thought the app would warn about space...

**Comment by millenbop** [comment]
This has now been implemented, will be available in version 4.1.3.
