### ISSUE TITLE
User profile calendar is broken

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1662]
Hi!

the recent activity view in left downer area is broken. For me it shows only the 11 first dates til now as a green rectangle, no more. Last one is on Friday?
Looks like some dates are broken in backend.

aceini/echelon

**Comment by gyllen** [comment]
I believe this is because we are starting a new year, is that correct @knikel?

**Comment by knikel** [comment]
This widget needs a complete rework. Won't be part of the upcoming mapillary.com update, but we'll add it after the initial release in a better form. Closing.
