### ISSUE TITLE
Manual Upload / Authentication Broke ( ? )

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1663]
I can't get the manual upload page to load.   The log in process seems funky, too.   Maybe the manual upload page is spinning because valid logins aren't being recognized or being dropped?

**Comment by gyllen** [comment]
Login seems to be up from our side. Are you able to see your name in the corner of the website?

**Comment by AllenGraetz** [comment]
Thanks.   I had closed browser, tried different browers, deleted cookies, etc.   I had this problem this morning too.

I tried it again in Chrome.  I let it run and run and run.  It did load 1 of 3 series pending publishing.  Then same problem but it finally loaded 2nd.  Then with third.  


The manual upload is working well now.. Thank you.

**Comment by gyllen** [comment]
Might be that you had a folder with a lot of images in pending. Could that be it? (closing this issue but you can keep on commenting here)

**Comment by AllenGraetz** [comment]
That could be in having a lot.   The thing is, I always use the 1,000 / sequence max.   I haven't had it behave that before.

Now some of that may be that it hasn't quite taken that long before.  I do noticed every now and then opening an manual upload page will have it just spin and spin.  I wait a bit, close it and open a new one.   It'll more or less pop open.  

Either way, it's working normally this morning.  Thank you, again.
