### ISSUE TITLE
License for news media

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1664]
News media need a lot of pictures. If something happens at some location they want pictures for some visuals, and unless its a big or visual event, they don't send out someone to snap pictures.

And embedding code isn't always a good solution to show a picture.

How about having some kind of easy to buy license for media? X amount of USD for a picture that can be paid online.

Maybe not a big money maker for Mapillary, but the pictures would get an additional use. And the Mapillary name would be seen in news media.

It would also set the pictures a bit more free. I think they currently are a bit to locked down. I assume Mapillary will look the other way if a blogger uses a picture, but not everyone want's to take the risk. Many bloggers have found out the hard way that many photographers are copyright hardliners that sue instantly.

**Comment by jesolem** [comment]
@Andblue Thanks. Good suggestion. 

We can make it clearer for how media/bloggers etc can use the images under the CC license. If they want to pay we could have a default license where you just send $X to our PayPal with the image key as message...
