### ISSUE TITLE
sign found, but counter on stat page not increased

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1665]
Hi 

I was out and mapping a new area of my home town yesterday where I picked up this sign:
https://www.mapillary.com/map/im/6VQs6jNCsNvc0repLukHkg/photo
Your sign algoritme did pick the right sign (good job), but the counter for that sign on my stat page has not increased. It was 2 before the trip and are still 2. My stat page is:
https://www.mapillary.com/profile/beer119/ors

I dont know if it is because I was walking and not driving (phone setting was set to walking with automatic shots).

It is not only that sign that I mention above that has not been counted. This one as well (for the same trip).

And I think that there are a lot of other signs from my walking trips that has not been counted as well but still discovered by algoritme.

**Comment by gyllen** [comment]
@ybkuang I think this is a matter of that we only count per detection version. In new rect API we should be able to do better counts.

**Comment by beer119** [comment]
Hi 
Here is another sign that I am the first to have found but the counter has not gone op:
http://www.mapillary.com/map/im/bDDS7ydsdCeHYkwz9C0LFg/map

When you are done with the new API would you then recound all the old signs again?

**Comment by ybkuang** [comment]
@beer119 yes. we will fix the counting for the signs in the new API.

**Comment by gyllen** [comment]
Still waiting for new API.

**Comment by gyllen** [comment]
Traffic signs are now completely redone. This issue is no longer valid.
