### ISSUE TITLE
cannot find the correct sign

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1666]
As you can see on the there is a sign with a horse: https://www.mapillary.com/map/im/Bl7SBfLchL5SVuMKYtU2rg/photo

Your sign algoritme has not correctly idefified it so I wanted to edited manual. The problem is that I cannot select the correct sign manual.

**Comment by knikel** [comment]
@beer119 Within Mapillary we're using a concept of traffic sign packages. Each package [one of the following: **Australia (au)**, **Brazil (br)**, **Canada (ca)** , **Europe (eu)**, **United States (us)**] has a certain amount of signs detected. This means that our algorithms detect **only** sings that are included in the package. This also means users can not annotate the traffic signs which are not included in the package. For such situation we have the **Other (?)* traffic sign annotation. Using this traffic sign for situations as yours helps us prioritize training of algorithms. I've already corrected the sign in question.

If you ever would like to correct a sign that's not on a list, feel free to use the **Other** annotation. Thank you very much for your time on improving the data on mapillary.com! We really appreciate that!
![other-sign](https://cloud.githubusercontent.com/assets/1574656/12389648/53f3da22-bdda-11e5-971b-6486421e523c.png)
