### ISSUE TITLE
State of change platform, enable picture movements in josm plugin

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1670]
Hi

while your change platform still is not availabe/working for >6 month, a quick solution could be to enable the movement of pictures with the josm plugin. It shows the underlying osm data, the pictures and the orientation of pictures.
Just the possibility to move the pictures to the rigth place and upload that changes is mssing. Too bad.
Would be quite easy and fine with it.

echeloni2p

**Comment by gyllen** [comment]
Hi,

We have change sets as one of out highest priorities and you will soon see it in production.

Reason it has taken so long is mainly because we are a very small team and we had to make priorities :/.

@peterneubauer Knows more about the current state

**Comment by peterneubauer** [comment]
Hi there,
current state is that we had to fix some backend restructurings in between. As of today morning, that is fixed, and I'm back on enabling the new changeset structure in the backend, so we are if not on time, but on track :)

**Comment by echeloni2p** [comment]
Hey

good to hear. Just wanted to know if it is still somewhat on track going on and not forgotten.
And the idea with JOSM is also nice.

echeloni2p

**Comment by peterneubauer** [comment]
Yes, right now I'm getting our changeset processing in order, hope to deploy that code today, so we can test sending messages with the new structure and start converting the old changeset + build the means to approve them. Sorry this takes longer time but we think it's worth it...

**Comment by peterneubauer** [comment]
Closing this, as changeset support for the API is working. anything else is a JOSM issue.
