### ISSUE TITLE
pictures has been processed but are not on the map

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1672]
I did upload more than 4.000 pictures yesterday. I got a mail from you that they have been received and process counter on stat page was 0 this morning but the pictures is still not on the map. Is there a bug?

**Comment by gyllen** [comment]
Can you check now?

**Comment by beer119** [comment]
They are on the map. But no confirmation mail send.

**Comment by gyllen** [comment]
Ok mail should be fixed a long time ago. Closing.
