### ISSUE TITLE
Navigation arrows disappear when editing a photo (Safari, OS X)

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#1678]
Once I edit a photo (e.g. add traffic sign or request a blur), the navigation arrows layered onto the image disappear (top, bottom and sides) disappear and don't come back.

This screencast shows the behaviour with Safari Version 9.0.2 (11601.3.9) on OS X 10.11.2 (15C50): https://youtu.be/b6bLYRbWKok

**Comment by HolgerJeromin** [comment]
This is intentionally so the icons are not in the way. 
They should come back after leaving blur mode.

**Comment by habi** [comment]
> This is intentionally so the icons are not in the way.
> They should come back after leaving blur mode.

That is indeed the case, sorry for the noise.
I wanted to navigate to the next images and forgot to leave blur mode.

**Comment by knikel** [comment]
@habi You could use arrow keys in case you want to stay in the traffic sign/blur mode
