### ISSUE TITLE
show remaining space in apps

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1679]
in the mobile apps, it would be great to show remaining space. either in mb/gb, or in estimated image count (like cameras do it).
it is somewhat easy to fill up some phones, and moving files periodically to a computer can help - but without an idea how long things will work, storage can easily fill up before there's a chance to move the files.

**Comment by richlv** [comment]
note that it would be useful for the android app, too :)

**Comment by HolgerJeromin** [comment]
on android you can add some space information with the "debug info". Search for this in the settings :)

**Comment by millenbop** [comment]
This will be added in the next version of the camera UI/UX that we are currently working on.

**Comment by millenbop** [comment]
This was released last week, closing.
