### ISSUE TITLE
Info link for WebGL support

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1680]
I'm regularly receiving the following error message on Chrome 47 (Windows 10):

> Psst, your browser doesn't fully support WebGL. Read more

This issue is not about the error message itself, I'm still triangulating what is causing this. This issue is about the "Read more" link.

Clicking the link, doesn't do anything. This is the HTML code behind the link:

> &lt;a class="bold black" ng-href="{{mup}}/map/help?q=webgl-support-and-the-mapillary-viewer" target="_self">Read more&lt;/a>

The href parameter clearly hasn't been properly executed.

**Comment by knikel** [comment]
@pbb72 I tried to reproduce this on Chrome 48, Win 8.1, but it does get parsed correctly. Do you get any errors in the console? I'm on my way to getting a Win 10 VM now to troubleshoot that further. Thanks!

**Comment by echeloni2p** [comment]
Moin!

Just want to add, my Chromium on debian has some serious webgl issues, too.
Sometimes if I use the map and click on a map to choose a track, it shows the picture in right view.
Now I click on picture and it shows like always.
Now I click on a arrow to show next one. And I get all arrows in a small rectangel in the middle with {{heading}} under it, and right area shows: Psst, your browser doesn't fully support WebGL. Read more
But it works on other tracks fine. 
Somehow WebGL is not perfectly initiated.
Also, if I do go into the Pointclound view, the mousewheel does scroll the whole webpage AND moves the pointcloud. Very annoying.
Also, under some circumstnaces I am able to show the pointcloud in the right area, where the small image is shown usually (right of the map). A, if you watch the pointcloud and click on "Map" in above buttons, the pointcloud is shown in right area.

echeloni2p

**Comment by knikel** [comment]
@pbb72, @echeloni2p: we've deployed with @oscarlorentzon few fixes related to initializing the viewer more than need, which could cause this issue (specifically the one @echeloni2p mentions). Would be great if you could clear your caches and see the behavior. Hope that helps!

**Comment by echeloni2p** [comment]
Hey

It is better now :-)

**Comment by pbb72** [comment]
Thanks! Reading the description from @echeloni2p, it looks like my problem might have been the same. I will update if I run into this problem again :-)
