### ISSUE TITLE
Truncated label in iOS app in Spanish

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1681]
In the Home tab of the iOS Mapillary app, when the language is set to Spanish, the "My Activity" label is truncated. Probably it's slightly longer in Spanish than in English and the button is not large enough.

![img_0947](https://cloud.githubusercontent.com/assets/101955/12690088/cde83600-c6bf-11e5-91f0-2a55fd7ea458.PNG)

**Comment by millenbop** [comment]
Thanks! I'll fix.
