### ISSUE TITLE
Standard swipe gesture to go back doesn't work in Profile tab

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1682]
Minor UI bug...
In iOS, in hierarchical navigation views, you can go back to the previous level by tapping the Back button, swiping the Back button to the right, or swiping the main view from the left edge. I believe this is standard behavior from `UINavigationController`.

In the Mapillary app for iOS, swiping from the left edge doesn't work anywhere in the Profile tab. This includes going back from Settings to Profile, going back from About to Settings, going back to the list of sequences in a month to Profile, etc.

Going back from a sequence in the Home tab does work by swiping. Navigating back in the Upload tab does work by swiping.

**Comment by millenbop** [comment]
Settings view is disabled because it was sort of hard to use the sliders, but from other views to Settings it should work.

I'll fix, thanks for reporting!

**Comment by nicolas17** [comment]
Aha, nice trick you're using to disable it :wink: I see what's going on, if I open Profile and then a month, I *can* go back to Profile by swiping; unless I open Settings, and then it gets disabled for the whole Profile tab and doesn't work again until the app is restarted.

**Comment by nicolas17** [comment]
Okay! This works wonderfully (tested in a [Substrate](http://www.cydiasubstrate.com/) extension loaded into Mapillary). I can now swipe from anywhere in the edge of the Settings view to go back, *except* where the sliders are.

```objc
@interface MAPSliderSkippingGestureDelegate : NSObject < UIGestureRecognizerDelegate >
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch;
@end

@implementation MAPSliderSkippingGestureDelegate
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    if ([touch.view isKindOfClass: [UISlider class]]) {
        return NO;
    }
    return YES;
}
@end

@implementation MAPSettingsViewController

// get rid of the navigationController.interactivePopGestureRecognizer.enabled=NO
// from viewDidAppear; use this instead

- (void)viewDidLoad {
    static BOOL delegateGotSet = NO;
    [super viewDidLoad];
    if (!delegateGotSet) {
        self.navigationController.interactivePopGestureRecognizer.delegate = [[MAPSliderSkippingGestureDelegate alloc] init];
        delegateGotSet = YES;
    }
}

@end
```
Now I better get some sleep.

**Comment by millenbop** [comment]
Thanks! Seems to work as a charm :)
