### ISSUE TITLE
Rotating map rotates heading indicator in opposite direction

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1683]
When looking at a Mapillary photo in the website, the map on the top right has an icon indicating in what direction the camera was looking. If I rotate the map, the indicator seems to rotate in the opposite direction. It doesn't stay in its current orientation either relative to the screen or relative to the rotated map.

For example, in a photo looking north, the icon points north. Rotating the map 45° clockwise makes the icon rotate 45° counter-clockwise relative to the screen, which means 90° relative to the map (it now points west).

(Related: #1527 where the indicator didn't rotate and stayed fixed relative to the screen)

**Comment by knikel** [comment]
We don't have the indicator anymore :)
