### ISSUE TITLE
Last photo may end up in separate sequence

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1685]
In the iOS app, when taking photos at high frequency (1s), sometimes the last photo before pressing Stop ends up in a separate sequence.

I suspect pressing the Stop button immediately changes the sequence UUID, but since photos are handled asynchronously, it may happen that the user presses Stop after a photo was requested but before it gets saved. When saved, it takes the current sequence UUID, which already changed.

![Screen capture showing the problem](https://cloud.githubusercontent.com/assets/101955/12699422/27fa82d6-c799-11e5-840b-11c2effd2304.gif)

**Comment by jesolem** [comment]
Thanks @nicolas17 - I suspect that you are right. @millenbop can check.

(great bug report btw, video and all!)

**Comment by millenbop** [comment]
Thanks for reporting, this is now fixed
