### ISSUE TITLE
On low GPS accuracy, shutter sound continues despite not taking pictures

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1686]
If GPS accuracy gets low, the iOS app automatically stops taking pictures. However, it continues to play the shutter sound every second as if it was still taking pictures.

While testing the app indoors, the shutter sound continued at the normal interval, but I noticed that sometimes the screen didn't flash. Then I found that when the screen didn't flash, those pictures didn't get saved either. *Then* I realized it was correlated to GPS accuracy coming and going (happens 100% when the icon goes red).

The only indication that capturing has paused due to low location accuracy is that the screen isn't flashing anymore, and *maybe* that the GPS icon went red (sometimes it pauses with the icon in yellow; must be different thresholds). I think there used to be a message on screen in previous versions...

**Comment by millenbop** [comment]
Thanks for reporting! This has been fixed now, will be available in 4.1.6.
