### ISSUE TITLE
Old images misplaced and collected up at one point on map

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1687]
I'm 90% certain (not a full 100% though) that these photos that I took a year ago, were originally on the right place on the map. Now the whole sequence is placed on one point in the city center:

http://www.mapillary.com/map/e/ZRB6NUaSZ9raIUKDv-iEMQ / http://www.mapillary.com/map/im/ZRB6NUaSZ9raIUKDv-iEMQ/photo

Is this a database error?

**Comment by gyllen** [comment]
@ybkuang Check meta data

**Comment by ybkuang** [comment]
I just checked and it looks ok now I think. Please let us know if it is not the case @pbb72

**Comment by pbb72** [comment]
More than 2 years after reporting, yeah by now I have manually corrected that sequence. (All photos are almost perfectly positioned, in 2015 I did not have a phone with so good GPS reception, so it is clear to me I have repositioned them.)

**Comment by gyllen** [comment]
@pbb72 Yeah sorry about that, at least we got to checking it huh, ;). BTW thanks for reporting all of the issues here over the years. It has really helped us in the development team!
