### ISSUE TITLE
Search autocomplete prevents search for some places

### ISSUE THREAD

**Issue by trigpoint** [mapillary/mapillary_issues#1689]
The natural alphabetical search on the website has been overidden, this is bad as it prevents some places being found in the search. This is a recent change, it used to work.

For example my home town, Wem, cannot be found as the search returns Wemmel and various combinations of Wembley. The city of Ely cannot be found either.

Please restore the natural alphbetical search.

**Comment by knikel** [comment]
@trigpoint We've got a much better autocomplete and search now. 

<img width="381" alt="wem" src="https://cloud.githubusercontent.com/assets/1574656/17094865/f7abf79c-5251-11e6-9a68-8486ae1c095e.png">

<img width="382" alt="ely" src="https://cloud.githubusercontent.com/assets/1574656/17094869/fb9e7528-5251-11e6-8ae5-b1c2e143e885.png">
