### ISSUE TITLE
Small typo on the Upload Photos page

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1690]
at marker 1: should say something like ...Apps, **this** web uploader...

![2016-02-02 12_03_23-mapillary _ manual upload](https://cloud.githubusercontent.com/assets/1827881/12757256/4a1169b2-c9a5-11e5-9457-b1e5e79cf1e2.png)

http://www.mapillary.com/map/upload/im

**Comment by knikel** [comment]
Thanks, this is fixed!
