### ISSUE TITLE
gaps in traces over rivers in the iphone app

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1691]
the map in the iphone app shows gaps in traces when the traces cross a river. the map in the webpage does not gave such gaps, and the images are there as well

**Comment by millenbop** [comment]
Could you post an example sequence?

**Comment by richlv** [comment]
sure - for example, all sequences over the rivers here (capital of texas highway crossing the bull creek a few times) : http://www.mapillary.com/map/im/94zP79Dv6kUYWInqIOAvpQ/map

**Comment by talllguy** [comment]
I've noticed this as well. The green line mapillary track doesn't render on bridges. I think the bridges are "higher" in the draw order. Two screenshots below. First is the app, second the web map. Same area.

![2016-02-10 21 07 35](https://cloud.githubusercontent.com/assets/1827881/12968055/f1375364-d03a-11e5-8899-e9655d03ad2a.png)

![screenshot 2016-02-10 21 13 09](https://cloud.githubusercontent.com/assets/1827881/12968068/335e21f0-d03b-11e5-959c-ba3fbacecd98.png)

**Comment by millenbop** [comment]
Thanks!

Looks like I should move up the Mapillary layer a few layers.

**Comment by millenbop** [comment]
It is now fixed, available in the next public release.
