### ISSUE TITLE
can't transfer images from the iphone app to the computer

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1692]
with the android app, images can be moved from the "mapillary" directory to the computer for uploading from the computer.
with iphone, only the phone photo directory seems to be accessible, and thus mapillary photos can't be transferred.
with the android app, user can choose where to save the photos - there does not seem to be such an option in the iphone app.

whatever the way, it would be great to transfer the photos from the iphone to a computer - maybe by storing them in the photo DCIM directory ?

**Comment by millenbop** [comment]
You need iTunes to transfer the images. Just connect and select the phone, go to Apps and select Mapillary, then you should see all the photos to the right.

**Comment by richlv** [comment]
hmm, itunes requirement doesn't go well with linux and other people's computers i could use to transfer images to... saving images to the DCIM directory (which is accessible) would work much better :)

**Comment by millenbop** [comment]
Do you wish to save all photos or just some select ones?

**Comment by richlv** [comment]
all/large parts to :
* free up space on the phone;
* upload from the computer

**Comment by nicolas17** [comment]
On Linux, get libimobiledevice+ifuse, and you can mount the Mapillary photo directory with `ifuse --documents com.mapillary.app mountpoint`.

**Comment by richlv** [comment]
thanks for the info, but that fails with "No device found, is it plugged in?". the device is plugged in, unlocked, the dialog for "allow access to photos" has been accepted.
unplugging/plugging back in does not seem to change anything.

**Comment by richlv** [comment]
turns out, i also had to install & run usbmuxd. huge thanks, closing this issue (if mapillary had a wiki, it might be worth documenting there :) )

**Comment by jesolem** [comment]
Thanks @richlv 

BTW there is a Wiki UserGuide here https://github.com/mapillary/UserGuide

**Comment by richlv** [comment]
ah, had forgotten about that one. added a quick note on image transfer, to be expanded later :)
