### ISSUE TITLE
360-deg photos lose resolution

### ISSUE THREAD

**Issue by YoViajo** [mapillary/mapillary_issues#1693]
Hi,

when I upload a 360-degree photo taken with the google android camera app (photo sphere mode) I notice that the resulting photo loses quality (resolution). For instance, http://goo.gl/mhnpBD looks blurry and does not reflect the actual detail of the original photo. What can I do ?

E

**Comment by peterneubauer** [comment]
This is because we are using one single thumbnail for the whole panoramic viewer which has much mower resolution than the original. We are working on having a tiling scheme so we can load higher resolution without streaming too much data.

**Comment by oscarlorentzon** [comment]
Closing because this is being tracked in mapillary/mapillary-js#92 .

**Comment by oscarlorentzon** [comment]
Full resolution images are now loaded and shown in the viewer for all uploaded photos on mapillary.com when zooming in.
