### ISSUE TITLE
Upload of 360 degree sphere stalls at 100%

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1694]
Hi
I made a few 360 degree spheres with the Panono camera and added GPS later on with Geosetter tool.
I try to upload the files with "manual upload" on my profile, it shows the correct GPS information, pushes the file to the server, it shows 100% uploaded and hangs forever (I killed after 1h).
Here are 2 of the files:
https://helene.cgv.tugraz.at/owncloud/index.php/s/lnRyc5FRWpLLR3n
https://helene.cgv.tugraz.at/owncloud/index.php/s/HR2CbcKWyRP0yWH
Is the image format not compatible with Mapillary?
I´ll be able to make a lot more of these panos with the Panono camera.

echeloni2p

**Comment by jesolem** [comment]
@paulinus or @ybkuang , can you check the file format?

**Comment by paulinus** [comment]
hey @echeloni2p,
the images look good. The problem seems to be that we have a file size limit for manual upload. We see if we can raise that limit to Panomo level.

**Comment by paulinus** [comment]
Just did a test reducing the image size before upload and it works. File size should be smaller than 20Mb. I've reduced the image width from 16k to 8k.

**Comment by echeloni2p** [comment]
Hi!

Ah, thats a solution I can live with, as the images need to be geolocalized manual, too.
Great, so I can do more of those on my trips and upload them :-)

echelon

**Comment by paulinus** [comment]
@echeloni2p i'm closing this issue, since i've seen that you have already uploaded great panoramas in Graz. (i'm in Graz at the moment btw)
