### ISSUE TITLE
Blurring with Firefox: Drawing box over edge of picture makes it blueish

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1696]
This is a follow-up of #1290. : Drawing a blurring box over the edge of a picture results in the picture having a blueish color. (Maybe because the picture is marked/selected by Firefox.)

**Comment by knikel** [comment]
We've rebuilt how blurring works, now you click once to start drawing a rectangle move your mouse and click second time to close the rectangle. This works also for panorama photos.
