### ISSUE TITLE
Sequence stretching over the map - wrong locations on the map

### ISSUE THREAD

**Issue by shravan91** [mapillary/mapillary_issues#1697]
![mapillary problem](https://cloud.githubusercontent.com/assets/3190951/13001560/1aa3f132-d18d-11e5-8ca9-c37bc120537f.JPG)

There is some problem with this sequence. It says this sequence was taken in Junagadh in the state of Gujarat but on the map it stretches from Gujarat towards Delhi.

**Comment by jesolem** [comment]
This should be automatically cut. Can you send a link to the sequence?

**Comment by shravan91** [comment]
Here it is @jesolem - http://www.mapillary.com/map/im/Z_RbRgMc8YCrDWP_rkHpfg/photo

**Comment by ybkuang** [comment]
@shravan91 We've applied a cut to the sequence. The tiles will be updated once the processing is catching up.
