### ISSUE TITLE
HTC One M8 - Over exposure when starting app

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#1699]
The app camera is over exposed when starting it. Using the inbuilt exposure slider has no effect. 

The only fix is to go into te HTC camera app, then go back to the Mapillary app and the exposure works as normal

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
