### ISSUE TITLE
HTC One M8 - App not taking images but screen display shows counter increasing 

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#1701]
This is a strange one. Everything appears functional in the app, there is disk space, and green for GPS lock. 

Start a sequence and the counter goes up showing that images are being taken and saved. 

When I go in to review sequences there are 0 photos and 0 sequences. 

Checked the card using Es Explorer and also hooked the phone up to laptop to double check. There are no sequence folders and no photos in the Mapillary folder

**Comment by rsahlin** [comment]
Please restest with latest 2.x release

**Comment by DaCor1** [comment]
Willdo
