### ISSUE TITLE
Changing image in editor resets zoom

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1702]
When using the editor (http://www.mapillary.com/map/e/<id>), and navigating from one photo to another (using either the right-hand side map or the next/previous buttons), the map completely redraw every time, even if the marker for that image was already visible.

One problem is that this takes a lot of unnecessary time, but more of a problem is that this also resets the zoom (I believe it is to zoom level 16).

Please redraw as little as possible. Don't even pan, if the marker is already visible on the map.

**Comment by knikel** [comment]
This will be fixed in the upcoming editor revamp. Stay tuned!

**Comment by gyllen** [comment]
Fixed in new editor

**Comment by pbb72** [comment]
@gyllen Why do you say this is fixed? The problem is still there, and has even gotten bigger since the base viewer now does the same, see #2079.

**Comment by gyllen** [comment]
@pbb72 My bad I thought you meant something else reopening. So basically you don't want any zoom in edit mode?

**Comment by pbb72** [comment]
Yeah, I would prefer an absolute minimum of zoom changing. When I open a map view, I pan and zoom it to give me the best overview. (Which is different for different purposes. Sometimes I want to keep an eye on a whole sequence, other times I want to see a whole traffic intersection, etc.)

It's not nice if the map application then decides it know better than me and sets it's own preferred zoom.

For the same reason, I would also prefer to keep panning to a minimum, only pan the map if the newly focused image falls outside the current map view.

**Comment by knikel** [comment]
This bug relates to `legacy.mapillary.com`; I'm closing this since we want to deprecate that part of mapillary.com.
