### ISSUE TITLE
Confirm detections – 400 (Bad Request)

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#1704]
Confirm detections gives me an 400 (Bad Request)

![screen](https://cloud.githubusercontent.com/assets/3885790/13036960/5b2acae8-d375-11e5-85e2-171c68b9fc36.png)

Chrome 50.0.2645.4 dev (64-bit)

**Comment by emilstahl** [comment]
Found out why.. I pressed the button multiple times because I do not get any feedback/confirmation...

**Comment by emilstahl** [comment]
Error at my or your end?

**Comment by emilstahl** [comment]
@knikel Do you plan to implement any feedback/confirmation when you confirm detections?

**Comment by knikel** [comment]
@emilstahl Yes, most likely a top of the screen notification. We've disabled detections for time being since we're swapping few backend parts to make it more robust.

**Comment by emilstahl** [comment]
@knikel 👍🎉

**Comment by knikel** [comment]
Detections are disabled, and we'll be working on new ways of confirming/denying/adding/removing them. Closing since this is related to the old app and not actionable from our side.
