### ISSUE TITLE
Edit tracks

### ISSUE THREAD

**Issue by perbac** [mapillary/mapillary_issues#1705]
When trying to edit tracks the map is jumping and the edits are lost. THis when trying to correct the position of the track.

**Comment by knikel** [comment]
What browser are you using @perbac? This is regarding the edit view, right?

**Comment by perbac** [comment]
Yes its in the edit view. I tried Internet Explorer 11, Chrome version 48.0.2564.109 and Firefox 44.0.

/Per


Per Backman
GIS och digitala kartor
Tekniska Divisionen
Nyköpings Kommun
Tel 0155 24 81 15

Från: Kamil Nikel [mailto:notifications@github.com]
Skickat: den 15 februari 2016 11:34
Till: mapillary/mapillary_issues
Kopia: Backman Per
Ämne: Re: [mapillary_issues] Edit tracks (#1705)


What browser are you using @perbac<https://github.com/perbac>? This is regarding the edit view, right?

**Comment by knikel** [comment]
Thanks!

**Comment by HolgerJeromin** [comment]
Changing rotation seems to be impossible right now, too. Tried with the + and - buttons but also the "correct angle" of the whole sequence.

**Comment by domdomegg** [comment]
Yeah, just doing anything in the editor is now impossible. On Chrome 48.0.2564.116, Ubuntu 15.10

**Comment by domdomegg** [comment]
Duplicate of #1702

**Comment by perbac** [comment]
Is it possible to get a signal when editing is functioning again? Either an e-mail or something on the webpage?

**Comment by domdomegg** [comment]
^ +1

**Comment by jesolem** [comment]
We're working hard on the backend upgrades for editing which will turn edits back on and make better editing tools possible. Almost there but will be a few more weeks at least (best guess).

**Comment by perbac** [comment]
Thanks for info!
When it works I can start arguing with my boss (the local authority) on being an professional (paying) user.

Waiting agogly

&Per B

Per Backman
GIS och digitala kartor
Tekniska Divisionen
Nyköpings Kommun
Tel 0155 24 81 15

Från: Jan Erik Solem [mailto:notifications@github.com]
Skickat: den 23 mars 2016 22:25
Till: mapillary/mapillary_issues
Kopia: Backman Per
Ämne: Re: [mapillary_issues] Edit tracks (#1705)


We're working hard on the backend upgrades for editing which will turn edits back on and make better editing tools possible. Almost there but will be a few more weeks at least (best guess).

**Comment by polarbearing** [comment]
confirming the bug on Safari/mac uand Firefox/linux

**Comment by domdomegg** [comment]
Also see #591

**Comment by knikel** [comment]
closing in favour of #591

**Comment by pbb72** [comment]
This is not a duplicate of #591. This one reports that changes are lost whenever selecting another image, #591 reports that hovering an icon selects another image. In other words, bug #591 makes it even easier for this bug to appear.

**Comment by knikel** [comment]
@pbb72 You're right, however both issues will be solved with the new release of the editor, because it'll be based on `mapbox-gl-js` and `mapbox-gl-js-draw` libraries.

**Comment by pbb72** [comment]
Looking forward! Any ETA?

**Comment by knikel** [comment]
@pbb72: new mapillary.com ETA is this summer 🎉
