### ISSUE TITLE
disable "select picture on mouseover" in edit mode

### ISSUE THREAD

**Issue by malenki** [mapillary/mapillary_issues#1706]
When being in edit mode other images get selected as soon as the mouse pointer hovers over one of the markers of the map. This causes very bad usability since one nearly never can select the Image one tries to.
My online-review workflow is: open pictures to edit in a new tab in edit mode, go to that tab, edit the image. Because the edit button of the view mode is right where the map is in edit mode I all the time lose track of pictures I want to edit when switching from one tab to the other and involuntarily "selecting" other pictures by just dragging the mouse pointer over the map with the image markers.

**Comment by pbb72** [comment]
Yes please fix this, it's really irritating when there are many photos in a small area. The current photos should only be changed when actively clicking on a pin.

Actually, I reported this problem more than a year ago: #591

**Comment by GITNE** [comment]
Is also connected to #1736

**Comment by domdomegg** [comment]
Also related to #1705

**Comment by domdomegg** [comment]
And #1702

**Comment by knikel** [comment]
Closing in favour of #591
