### ISSUE TITLE
Mixed content in editor

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#1707]
<img width="1014" alt="mixed content" src="https://cloud.githubusercontent.com/assets/3885790/13047851/39361df8-d3e2-11e5-962e-f0a436947aac.png">

Example: https://www.mapillary.com/map/e/w2t_VAE85xMN7z8Qa5Zi3g

**Comment by knikel** [comment]
Thanks, fix is on its way.

**Comment by emilstahl** [comment]
@knikel Issue closed, but not fixed?
<img width="196" alt="screen shot 2016-03-09 at 03 26 13" src="https://cloud.githubusercontent.com/assets/3885790/13623416/ce1960a8-e5a6-11e5-8168-0eba9d1ecc49.png">

**Comment by knikel** [comment]
Interesting, the OSM tiles have protocol relative urls. They should be fetched through https. Could you try clearing cache and see if that still happens?

**Comment by emilstahl** [comment]
@knikel Cache disabled… Stil seeing it in the editor (URL in https://github.com/mapillary/mapillary_issues/issues/1707#issue-133693702)

![screen shot 2016-03-09 at 09 06 44](https://cloud.githubusercontent.com/assets/3885790/13628939/51843240-e5d6-11e5-89c5-626e3c1735ff.png)

**Comment by knikel** [comment]
@emilstahl I've just deployed an update. This is fixed now :dart:
