### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#1708]
1. Why not?
2. Login session does not work _https -> http_

![b76rqw](https://cloud.githubusercontent.com/assets/3885790/13066729/2cb73c6a-d469-11e5-8fa9-4f367f401b1a.gif)

**Comment by emilstahl** [comment]
ETA @knikel @gyllen ?

**Comment by emilstahl** [comment]
Remember to add a [HSTS (HTTP Strict Transport Security)](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/) header (and [preload](https://hstspreload.appspot.com/) if possible) 🔒🎉

**Comment by emilstahl** [comment]
Status? @knikel 

Have been "in progress" for quite some time now.

**Comment by Caboosey** [comment]
I also noticed that during upload of photos from Mapillary app uses HTTP instead of HTTPS.

Using HTTPS can also save bandwidth and speed up the viewing/uploading. This will help with the user experience.

HTTP vs HTTPS Test: https://www.httpvshttps.com/
