### ISSUE TITLE
1/2 of screen space is empty if map mode chosen during capture

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1709]
As you can see - I want to see a map during capturing, but see a tiny square with map, and empty main part of screen with White-On-Near_white HUD. Samsung Note 4.
![2016-02-17 08 12 52](https://cloud.githubusercontent.com/assets/325961/13105598/a62c1fda-d56c-11e5-9dca-d494ae6c5af2.png)

**Comment by HolgerJeromin** [comment]
Thanks for creating the issue. Same here on fairphone 2. 
Interaction (drag)  with the map is really weird. And the point is not at my position.

**Comment by simonmikkelsen** [comment]
Same here on Sony Xperia 2.

**Comment by ovivoda** [comment]
This mode is not there anymore. Closing it.
