### ISSUE TITLE
Notification not indicates complition of upload

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1710]
When photo upload finished, message in notification area looks like it stll uploading, just progress bar full or like it.
I think notification should turn into kind of "upload finished, 300 shots, 150 MB uploaded, 10 mins 43 secs taken" or something
![2016-02-17 08 51 10](https://cloud.githubusercontent.com/assets/325961/13105826/bcfdcb22-d56d-11e5-8816-11baf956e256.png)
 like it.

**Comment by peterneubauer** [comment]
What version are you running? The message should change in completion. Cam you please send the log when this happens next time?

**Comment by iav** [comment]
There is trace log https://yadi.sk/i/LTXhkib7p2TDn

**Comment by peterneubauer** [comment]
Let's try with the next versions, feel free to comment if this is still and issue.

**Comment by rsahlin** [comment]
Please retest with lates 2.x release
