### ISSUE TITLE
Unable to move roadsign frame and change sign in roadsign editor

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1711]
Unable to move roadsign frame in roadsign editor.
Unable to change sign type for already drawn sign.
Unable to use zoom and pan during roadsign marking.

All that makes roadsign editor near to unusable.

**Comment by knikel** [comment]
This bug relates to `legacy.mapillary.com`; I'm closing this since we want to deprecate that part of mapillary.com. We'll have similar functionality in the future.
