### ISSUE TITLE
renew notification time on android more often

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1712]
Right now if i start uploading 300 images i get a notification:
"uploading 1 of 300 images" with android adding a timestamp "19:11" to it

half an hour later i have
"uploading 150 of 300 images" 19:11

But if the upload thread is killed by android (dont say this is not happening :) i have eight hours later still 
"uploading 150 of 300 images" 19:11

Right now i check the upload ratio with the app "3d watchdog" to see if the upload is still in progress.
So i propose not to **update** the notification but **reinstall** the notification. With this change i would have every few minutes the new timestamp in the notification area. If the notification timestamp is old i can restart the upload.

**Comment by peterneubauer** [comment]
good suggestion @HolgerJeromin !

**Comment by peterneubauer** [comment]
This is implemented and will come out in the next releases. Thanks!

**Comment by HolgerJeromin** [comment]
The notification is new after every image. But the time stays old on my fairphone 2 with Android 5.1

**Comment by peterneubauer** [comment]
Thanks, changed that for the next release.

**Comment by HolgerJeromin** [comment]
Still no change of the time in version 200

**Comment by HolgerJeromin** [comment]
I have no android dev experience but perhaps setWhen() is sufficient and reloading the notification is not needed

**Comment by peterneubauer** [comment]
Sorry,
just noticed that I missed that notification, when() is set on all others,
fixed for the next release.

**Comment by HolgerJeromin** [comment]
Works really nice. Especially with the slow Internet here. Thanks
