### ISSUE TITLE
top buttons got mixed up

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1714]
For example load this page
http://www.mapillary.com/map/im/nlmKPpeJ8qhBudYhtownFg/map
We have a map and the "Map" button is green. Now click on a sequence line.
Often (always?) the url changes to .../photo and the "Photo" button gets green, but (IMO correct) the map is still visible.
Clicking "Photo" does nothing, clicking "map" reloads and i can now click "Photo".

Same on Desktop and Mobile Browsers (ok, tested only both newest Opera :-)

**Comment by pbb72** [comment]
Duplicate of #1695 ?

**Comment by HolgerJeromin** [comment]
Yes. Thank you
