### ISSUE TITLE
[GoPro] Number of photos on camera far exceeds number of photos copied to Mapillary

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1720]
I went out to take some sequences during lunch. I use the testflight version of the app and have a GoPro Hero 4. I use the .5 second speed. As instructed, I wiped the GoPro before heading out. The only interruptions I had were a phone call that I declined, and a temperature issue with the iPhone, which required me to pull over and let the phone cool (in the AC vent).

After about an hour of shooting, I went to transfer images from the GoPro :camera: to the :iphone:. I discovered that the GoPro :camera: is showing that 4,561 photos were taken.
![2016-02-22 15 51 45](https://cloud.githubusercontent.com/assets/1827881/13232538/99f62cd2-d97d-11e5-9506-7f27153b0c49.jpg)

However, Mapillary only transfered 1,764 images. Where did the others go? I've tried re-initiating the transfer to no avail. The app will not pull any of the other **2,797** images over.
![2016-02-22 15 51 19](https://cloud.githubusercontent.com/assets/1827881/13232540/9bfb8aae-d97d-11e5-9151-bcfa338d166f.png)

I compared the GoPro :camera: and the :iphone: Mapillary libraries and could not find a logical reason why certain ones were missing. There were pictures in the Mapillary queue from both the very beginning and the very end of my trip, and in between. The missing ones are seemingly random. In fact some of the sequences seem to just stop in the middle of a road for no apparent reason.

**Comment by millenbop** [comment]
Thanks for reporting! 

My guess is that sometimes the stop/start feature didn't work properly when stopping at intersections etc, i.e. the app told the GoPro to stop but it continued to take pictures anyway and during that time the app didn't store information about the images.

We're in Barcelona for MWC so I'll have a look at it when I get back to the office and my GoPros.

**Comment by talllguy** [comment]
I went back out for a drive today and had this same issue and I'm a bit upset because I don't know how I could solve this issue. After taking over 10,000 photos on the GoPro, a mere **783** ended up transferring to the iPhone. **That's about an 8% success rate**.

After this, I am questioning whether it is worth my time to continue taking photos with the GoPro for Mapillary. The frustrating thing is when I would occasionally check the map to see that photos were indeed being recorded and green dots were applied on the map, yet in the end, something was lost. I suspect that the GPX and location information is not being saved properly.

What can be done to remedy this situation?

**Comment by jesolem** [comment]
Ouch @talllguy , sorry to hear. We're back to full speed again next week. Hope we can solve this soon.

**Comment by millenbop** [comment]
I submitted a new version yesterday (Friday) that hopefully fixes your problems, I'd advise you not to use the GoPro to capture (or atleast not that many photos as 10000) until you have the new version.

I have rewritten the file handling. I used to use one file for photo information, but found that when you had many photos (>1000), it would take long time for the phone to write the file. Hence, it would not save it fast enough and you would not get all photos (as you have noticed).

The new system writes one file per photo instead = lots of small files instead = no lag despite lots of photos (>10000).

Sorry once again for the GoPro bugs (still in Beta), but I think the new version will solve this issue. And thanks for testing GoPro!

**Comment by millenbop** [comment]
If you cannot wait, the latest Testflight beta app has this new file system too if you want to check it out before Apple approves it.

**Comment by talllguy** [comment]
Thanks for the followups! I will update on Testflight and continue testing.
Pardon my tone on my earlier reply, I was just a bit upset but I **will**
continue to test the product.

On Sat, Feb 27, 2016 at 5:54 PM millenbop <notifications@github.com> wrote:

> If you cannot wait, the latest Testflight beta app has this new file
> system too if you want to check it out before Apple approves it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/1720#issuecomment-189743832>
> .
>
-- 
Elliott Plack
http://elliottplack.me

**Comment by millenbop** [comment]
No worries Elliot! Just hope the new version is better! :)

**Comment by talllguy** [comment]
## New Test with the new Testflight Version
- iPhone 6 Plus
- iOS latest
- no map
- both GoPro and iPhone on charger

Went out with the GoPro today. The GoPro recorded some 3,462 photos and Mapillary is only showing 943 this time. Progress!

**Observations**

Unlike in previous versions of the Mapillary app, all 943 pictures are in the same grouping in the app. Previously, as you'll see in other screenshots, you'll see that the various start and stops are broken into separate groups. Within this 943 shot sequence, there were about 12 timelapses (based on the files on the GoPro), so the app was successful at commanding the GoPro to start and stop 12 times.

For some reason, all sequences after the 943rd photo were lost. I checked the images on GoPro, and there are many more images stored. And, of course, after the 943rd photo, it was not obvious to me that something was amiss. Something that could be telling is that after the 943rd photo, the next sequence would have brought the count into the 1,000s.

Hopefully this will help in further bug testing! All is not lost however, as I'm compiling all 3500 or so photos into a timelapse video with street name subtitles. I'll post that here when it finishes.

![2016-03-02 15 30 24](https://cloud.githubusercontent.com/assets/1827881/13481115/dd5135e6-e0b0-11e5-9753-8ef78817f56f.jpg)
![2016-03-02 15 32 21](https://cloud.githubusercontent.com/assets/1827881/13481135/04d16870-e0b1-11e5-873c-58cb61964b5b.png)

![2016-03-02 15 31 46](https://cloud.githubusercontent.com/assets/1827881/13481137/07f97a1a-e0b1-11e5-9556-aa80abcaf39a.jpg)
All photos after the red one (scrolling up) are not on Mapillary.

**Comment by millenbop** [comment]
Thanks for testing! Yeah I actually figured the 1000 thing yesterday and have added measures for it. I had a 99% success rate yesterday, sometimes it missed the last image in a sequence because of timing (i.e. the app would send stop to the camera but it took one photo too much). That's ok.

Everything was fine, but my last test didn't go well, for some reason it changed the group mid-capture after 1047 photos and I have no idea why.. yet. I hope I can solve it today.

**Comment by millenbop** [comment]
New build submitted to both TestFlight and App Store, I really hope it works for everyone now!

**Comment by talllguy** [comment]
@millenbop Great! I forgot to update and went on a run today. 987 of the 2119 are transferring. :anguished:

**Comment by talllguy** [comment]
[Here is the video from the other day](https://www.youtube.com/watch?v=2zpHviPG4hA)

**Comment by millenbop** [comment]
Bummer :( I really really hope the latest Testflight version solves this issue.

**Comment by millenbop** [comment]
Should be much better in the latest version, please verify. Closing this for now
