### ISSUE TITLE
API: No special_type value returned with GET /im/:key

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#1721]
Hello,
The previous API allowed to call `/g/:key` and returned a `special_type` value, letting you know when the given picture is a 360° one. The `/g/:key` doesn't respond now, and the current API doesn't return this value when calling `/im/:key`. Can you restore a way to know if the picture is a panoramic one ?
Thanks.

**Comment by gyllen** [comment]
Will look into it. Are you still interested in this?

**Comment by PanierAvide** [comment]
Yes of course.

**Comment by gyllen** [comment]
`v2` are no longer in use. Check out mapillary-js for viewing images easily.
