### ISSUE TITLE
Bug still not fixed - older iPhone gps lag behind

### ISSUE THREAD

**Issue by chgrl** [mapillary/mapillary_issues#1722]
Hi there,

I was glad to read about your bug fix in the last version 4.1.3: "Fixed bug where older iPhones like iPhone 4 would lag behind after a while when capturing".
Unfortunately the bug is still there, as I found on my last sequences. I use an iPhone 4 and only can use manual walking or panorama mode.

Please fix before summer. :-)

Christian

**Comment by millenbop** [comment]
Hi!

We have been away to MWC and before that I was at the LA office for a while, but now things are back to normal and I have access to all my devices so I can look into it properly. 

I'll keep you updated with progress.

**Comment by millenbop** [comment]
I have done some thread work so that files are written in another thread and everything seems much snappier. Would love for you to try it. 

If you wand to, please email me at anders @ mappy I will add you as a beta tester and I can send you the build to try out.

**Comment by millenbop** [comment]
Should be fixed in the latest version, please verify. Closing this for now
