### ISSUE TITLE
Mini-map doesn't zoom anymore

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1723]
The mini-map that is displayed on photo pages doesn't zoom anymore. On initial page load, it zooms to about country size. After that, it doesn't do anything anymore. You can't use the zoom buttons, you can't pan, you can't change layers, you can't select other photos through it.

**Comment by pbb72** [comment]
Ok, currently the interaction works again. (Maybe a partial fix has been deployed already? Or maybe the problem is related to some user settings, I'm currently using another computer.)

But when using the Mapbox layer, the map still doesn't zoom in on page load. However, after selecting either the Mapzen or Esri layer, then the map does zoom in on page load.

**Comment by knikel** [comment]
This is a bug, I'm investigating that. Getting some weird behaviors here too :)

**Comment by knikel** [comment]
Couple of weeks ago I deployed fixes related to #1724 which were also causing this behaviour, it should be gone by now. The cause was trying to add same layer multiple times in some weird circumstances.

**Comment by pbb72** [comment]
I haven't seen this bug in a long while now, so for me it can be closed.
