### ISSUE TITLE
Photo position and acive sequence not shown on map

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1724]
At present the position and the sequence of a photo are not highlighted on the map. I see the same behaviour on the Firefox, Chrome, edge on my WIndows 10 computer and in Firefox on Android. 
The first image shows how it used to work, the second how it looks at present.  
![mapview-example as-it-used-to-be](https://cloud.githubusercontent.com/assets/11076112/13372601/098e690e-dd4a-11e5-879d-6edfe3be8121.jpg)
![mapview-example 20160227](https://cloud.githubusercontent.com/assets/11076112/13372602/0c0653b8-dd4a-11e5-9722-3a8038411db4.jpg)

**Comment by knikel** [comment]
Related to https://github.com/mapillary/mapillary_issues/issues/1723

**Comment by knikel** [comment]
In the new web app we have a better way of displaying current photo, current sequence and interactions with photos around it. Closing.
