### ISSUE TITLE
Deprecating Widget makes a blog so outdated

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1726]
What a disaster! Full Deprecating of widgets makes my blog appears that...in every track I had embedded:

"Shucks!
Mapillary Widget has been deprecated
Please use MapillaryJS instead.

MapillaryJS is a new and easy way to embed any photos from mapillary.com and to tell stories through them! "

Are you telling me that I have to modify +100 old post in some blogs because full deprecating the main way to embed our mapillared tracks in our blogs?

**Comment by mprins** [comment]
just like to add "me too" :bomb:

**Comment by knikel** [comment]
@yopaseopor, @mprins: I know, I'm sorry about that. We had to do it, as `mapillary-js` is THE way forward. Please send me an e-mail to kamil [at] mapillary.com and I'm happy to help you out with updating your sites with `mapillary-js`.
