### ISSUE TITLE
Camera Sound in Korea

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1727]
In some countries it is required by law that phones make a shutter sound. It's quite weird to walk around and have a shutter sound coming from the phone every 2 seconds. That's not really something you can do anything about, but it might explain why there are so few users in Korea. As soon as I put a SIM card of another country in that Android phone, the sound is gone.

**Comment by echeloni2p** [comment]
Hi

My huawei honor 7 makes a shutter sound on every picture, every second. I hold it in my hand and close the speaker, shutter sound is silent in that position.
With same SIM, same settings, HTC One mobiles won´t make a sound.
So, it depends on the system you run it on, nothing mapillary can chage at all.
All a user can do is closing the speaker while shooting pictures. Or get another mobile/OS for mobile.

**Comment by mxa** [comment]
Well, with an Sony XPERIA phone it solely depends on the SIM card that's in it. I should root it to remove the soundfile.

**Comment by Olestas** [comment]
Lowering sound volume to minimal or muting does not help?

**Comment by mxa** [comment]
No, unfortunately this is a misguided legal requirement in Korea, because it seems easier to force phone vendors to cripple their products and locking the customers out of their own devices than to begin a social dialogue talking about the issues in society that make some people take pictures of panties on the escalator.

**Comment by Olestas** [comment]
Omg, I see.

**Comment by peterneubauer** [comment]
Closing this as "Korea won't fix" :/

**Comment by mxa** [comment]
Turns out that maybe there is a way for you to "fix". The [Open Camera](http://opencamera.sourceforge.net/) app can take pictures on my phone without a camera sound. Maybe you can take a peek in the source code of it.

**Comment by mxa** [comment]
Holy wow! You did it. I'm so grateful. This was driving me mad.
