### ISSUE TITLE
Sequence has been oddly splitted in two sequences

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#1728]
I uploaded a sequence of 36 images with the web uploader. I received email notification that this sequence was visible on Mapillary. Checking on site, it looks like this sequence has been oddly splitted into two sequences, despite no significant spacial gap exists at the split point.

first sequence: http://www.mapillary.com/map/s/hv4xT9avCWhyy_9DlKX3lw
second sequence: http://www.mapillary.com/map/s/Kzo2Fzui0o91XxFMnq2lWw

The two sequences are still somewhat linked. If I select the first photo of the second sequence:

http://www.mapillary.com/map/im/JMTw1bwwB9QySSxk3lDj_Q

and then select "lock to sequence", by hitting the down arrow key I can navigate to the last image of the first sequence. But then I cannot move forward back to the second sequence.

**Comment by ybkuang** [comment]
@kaitu I think there is no issue of transitioning back/forth between the two sequences. But it is a bit tricky to find out why the sequence is cut anymore. Please let us know you encounter similar issues later.
