### ISSUE TITLE
Link to RSS on the blog

### ISSUE THREAD

**Issue by nclm** [mapillary/mapillary_issues#1734]
A little link issue on the blog:

The RSS file is located here: `http://blog.mapillary.com/rss.xml`. When you’re on an article page however, like `http://blog.mapillary.com/2016/03/07/something.html`, the _Subscribe_ link in the sidebar points to `http://blog.mapillary.com/2016/03/07/rss.xml`, which doesn’t exist.

So `href="rss.xml"` should be replaced by `href="/rss.xml"`.

By the way, it could be nice to add
```
<link href="/rss.xml" rel="alternate" type="application/rss+xml" title="The Mapillary Blog">
```
in the `head`, too.

**Comment by moenk** [comment]
I would like to have a list of current topics of the forum on the coummunity page of the website instead just a link, as there is already a RSS feed this is easy to be done.

**Comment by knikel** [comment]
@moenk Let's track this in a separate issue.
