### ISSUE TITLE
Editor: loading another image discards all queued changes

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1736]
Open the editor (on the website) and make some changes to a photo, for example move it or hide it. Notice how a miniature of the photo is shown under "Edited images".

Then hover over another image marker in the mini-map. Not only does the map change zoom and pan around (which is unwanted and reported in #1702), but also your queued change has been lost!

**Comment by GITNE** [comment]
Yes, I can confirm this behavior in Firefox on Windows and Linux. Simply hovering over an arrow in the mini map does not just load another photo, it actually starts a new change set. I really do not like the hover *feature*. This renders the change set web editor **UNUSABLE**. You have to be extraordinary careful not to touch any other arrow while dragging or repositioning a photo's location. Additionally, effectively, you can make just one change at a time. :-(

However, I may be missing something and this behavior can only be observed in Firefox.

**Comment by pbb72** [comment]
I am also seeing this problem in Chrome (v 49, Windows 10)

**Comment by polarbearing** [comment]
confirming the bug on Safari/mac uand Firefox/linux

**Comment by pbb72** [comment]
This looks like a duplicate of #1705

**Comment by knikel** [comment]
Closing in favour of #1705. Editor is getting a total revamp.
