### ISSUE TITLE
New phone old problems

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1737]
Using the Huawei P8 lite there are the same problems I had on a HTC. 

- If you don't quit the app with "are you sure you want to exit", next time GPS doesn't work anymore. It will be green but says "searching better location"
Maybe it is the same problem: https://github.com/mapillary/mapillary_issues/issues/1732
- "make shutter sound" yes or no doesn't work, it makes always sound
- it is hard to find the fotos on the SD-card. 
default storage location is : /storage/emulated/0/android/data/app.mapillary/files/mapillary
I can not chance it, maybe I have to root the phone. Why don't you use the DCIM folder as any other camera?

The one smartphone mapillary works perfect was a samsung S3, but I lost it.

**Comment by echeloni2p** [comment]
Moin

the first 2 issues are the same on Honor 6/7 from huawei. Number one is a error in the app, it worked well before.
Shutter sound has always been non-editable, it is a issue of the Huawei system. On HTC/Motorola it works as expected. Blame Huawei.
You can change the storage location, in the app settings, click on the few dots below the path and select a new directory. I can change between paths on my mobile phones, without rooting them.

echelon

**Comment by rsahlin** [comment]
Hi
The GPS issue is fixed in 1.79
As for the other issues I hope you are happy with the reply from echelon, if not please open up one issue per problem.

Thanks for your support and help
/Richard
