### ISSUE TITLE
Huawei P8 lite problem with focus

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1738]
My new Huawei P8 lite has a good camera. But on mapillary it doesn't focus well. 
Using infinity or continuous focus the pictures are fuzzy only autofocus works.

**Comment by talllguy** [comment]
I used to use an iPhone 5 for Mapillary which has a [very similar camera sensor](http://www.ifixit.com/blog/2011/10/14/iphone-4s-camera-made-by-sony/), also by Sony, and I would have similar issues. I found that it would focus on miniscule scratches and dirt on the windshield. Try cleaning the area on the glass to see if that helps. Not to say it isn't software, just a suggestion.

**Comment by rsahlin** [comment]
Hi and thanks for your interest in Mapillary!

We are in the process of migrating to the Android Camera2 interface, once this is done it will open up more possibilities for the Camera. 
For instance auto-focus, auto-exposure, and auto-white-balance - we are hoping this will solve similar problems as you are experiencing.

Best regards
/Richard

**Comment by wegavision** [comment]
Hope it will come soon. The results of autofocus are not that good, here an example:
http://www.mapillary.com/map/im/RHps1uqP-D1OKQYTkCoXvw/photo

**Comment by rsahlin** [comment]
Yes, that does not look optimal.
I will let you know as soon as there is progress, working as fast as possible :-)

/Richard

**Comment by rsahlin** [comment]
Hi @wegavision and @talllguy 

Could you please retest with version 2.16 that is coming through Google Play?
The preffered focus option is 'continouos picture' - but feel free and do your own analysis :-)

Please re-open the issue if you still feel we should look into the issue.
Best regards
/Richard
