### ISSUE TITLE
Large map-in-camera not showing properly

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#1739]
Now that the map-in-camera is working I have run into new issue with the large map mode/view. As noted in the #1651 : 
"The large map mode doesn't show a large map. It only shows the same small map in the bottom left corner of the space/area that is reserved for the large map on the screen. The photo viewer is shown properly in the top left corner."

**Comment by HolgerJeromin** [comment]
we have already #1709 for this :-)

**Comment by jesolem** [comment]
Duplicate.
