### ISSUE TITLE
tapping an active tab in the iphone app should provide feedback

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1744]
quite often i find myself tapping the 'upload' tab while being in it already, mistaking it for some other tab and missing the small "upload" link/button in the upper right corner.
while the active tab is already highlighted, the green "capture" button negates that effect.
if an active tab is tapped, maybe the tab button could flash a bit ?

**Comment by millenbop** [comment]
We are gonna rework the bottom tab to be much clearer, right now it's very confusing.

**Comment by millenbop** [comment]
The tab bar has been updated recently and it's much clearer which tab is selected now. I'll talk to the others about using the view's title instead of the Mapillary logo as well.

Closing this for now, thanks for reporting!
