### ISSUE TITLE
new sequences show up on the profile page but can not be opened

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1745]
upload a new sequence. after a while, it shows up on your profile page.
as soon as it appears, click on it - "This image doesn’t exist, has been hidden or is part of a private project."
this issue goes away some time later - presumably, when the sequence has gotten processed in some way. this has started happening in the last few months or so.

probably the sequence should not show up on the profile page until one can actually open it.

right now, this sequence is like that : http://www.mapillary.com/map/im/5qej2C4CDtYinul3WAU3Yw/photo
but it will likely become available soon, so one will need a new "testcase" :)

**Comment by echeloni2p** [comment]
Hi!

I´ve had this a few times. The background jobs of mapillary taking some time. Wait 1-2 days longer. And currently it is online, now.

echeloni2p

**Comment by talllguy** [comment]
#1719 is related. Same error but a slightly different way of getting there.

**Comment by shlublu** [comment]
Still occurring here.

**Comment by gyllen** [comment]
@shlublu You have an example? This might have been according to some issues we had two days ago. Should be fixed now though.

**Comment by shlublu** [comment]
Actually yes, it is now fine. The whole first page of my "uploads/profile" page was concerned when I wrote the comment above, but all these sequences can properly be opened now.

**Comment by gyllen** [comment]
@shlublu Keeping this closed then, report if this happen again. Problem should be fixed though. Thanks for reporting.
