### ISSUE TITLE
Feature Request: Scan 1D- and 2D-Codes

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [mapillary/mapillary_issues#1746]
Some photos contain barcodes, QR-Codes or other types of visually-encoded data. It would be cool if Mapillary would at least be able to detect and interpret QR-Codes.

Here is an example of one:

https://www.mapillary.com/map/im/wh50lRyGjb_fqG3b7iLDaA/photo

**Comment by jesolem** [comment]
Thanks @epsg31468 
We will think about this feature.

**Comment by jesolem** [comment]
We're keeping the suggestion but will not implement in the near future. Closing.

**Comment by oldschoolBavarianReferenceSystem** [comment]
I fully understand that decision.
