### ISSUE TITLE
Zero size blur request bug

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#1747]
How to reproduce:
1. Go to any photo on the website
2. Choose blur mode
3. Make a dot (0x0 or 1x1) blur on the photo
4. Press "Request Blur"

Result:
After a request is made to the server, an error message pops up saying that something has gone wrong.

Zero (0x0) or one (1x1) size blur requests should not be validated by the server but rather by the client and either be silently ignored or be impossible to send by the client, hence disable the "Request Blur" button if zero or one size blurs have been drawn.

This bug has also a negative side effect: Once the error message is received and displayed in the browser, one cannot do anything else but discard the current blurs (by poking the blur mode button again) and reload the original, and then painfully redraw them again. Edits should not be discarded before a successful blur request has been made or the user chooses do to it himself by pressing the "Discard Blurs" button.

**Comment by jesolem** [comment]
Good suggestion.

**Comment by GITNE** [comment]
Please, do not get me wrong, it is absolutely correct for the server to check incoming requests for validity. But, this is a client problem. The best solution on the client side would be to support the two generally common select modes, like most window managers; click-drag-release and click-move-click. This would naturally eliminate zero size blurs ever to occur, and would also eliminate the need for disabling/enabling of buttons.

However, touch only devices have a problem here because they have to stick to one select mode only, where tap-drag-release is probably most common. So, checking for the input device may be a solution here. I do not know if this is possible to do in JavaScript on all browsers but I suppose most mobile browsers should expose such an API.

Personally, I prefer the click-move-click select mode because it gives you more control to avoid to release the mouse button at the wrong moment. It is just more ergonomic, a more natural way to use a mouse than cringing onto a mouse button while worrying not to release a stupid mouse button at the wrong moment and spot. Touch pads and knobs are even less dragging friendly. Click-drag-release does work well but only if the area to click and to release is comfortably big enough, like in drop-and-drag, classic pull down menus, or combo boxes. If you need to select stuff quite precisely, click-drag-release does not work so well, at least IMHO.

**Comment by gyllen** [comment]
We adopted the `click-move-click` in the tagging editor and will probably do so for the new blur editor too (it's currently disabled since we redid how blurring works, but very few complaints since it seems to be performing really well). The blur editor will come back though since we still need the ability to blur.
