### ISSUE TITLE
missing sign from us with "european" account

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_issues#1749]
Hi, on a roadtrip in the US I took over 250k picture. After the processing most of the traffic sign are detected. But now I miss the overview of the US-sign in the "Activity"-tab on my profile.
The EU-sign (where I normally map) are listed.

Would be nice that I can see the overview of all signs :)

thx

**Comment by beer119** [comment]
I was wondering if it is related to:
https://github.com/mapillary/mapillary_issues/issues/1665
eg signs that are detected but not counted on the stat page

**Comment by gyllen** [comment]
@angelday We might want to readd this feature

**Comment by angelday** [comment]
@gyllen with the new filtering options especially for traffic signs, do you think this will be solved?

**Comment by gyllen** [comment]
@angelday Yes that will solve this.

**Comment by nickplesha** [comment]
The new, recently updated, traffic sign filter now have a searchable list of all traffic signs so they should be easy to find.
