### ISSUE TITLE
Problem with Iphone6 and GoPro Hero 4

### ISSUE THREAD

**Issue by iltempe** [mapillary/mapillary_issues#1750]
With mobile app Iphone 6 (version 4.1.6) I cannot transfer of photos taken with an external camera GoPro Hero 4.

**Comment by millenbop** [comment]
Hi!

Thanks for testing GoPro! Could you explain a bit more? Do you go to the Uploads view and there, don't you get a popup asking if you want to transfer? Or does the transfer finish real quick with no images transferred? Or does the transfer stop after a while?

**Comment by iltempe** [comment]
Hi! yes sorry. I'll try to be more clear. I make pics with GoPro. When I go in Uploads and Iphone is connected to GoPro it find new pics and ask me to trasfer photos, but if I click on YES no pics is trasferred! I've tried many times with the same issue. regards!

**Comment by millenbop** [comment]
Which version of the app did you use to take the pics?

**Comment by iltempe** [comment]
I've used mobile APP newer for Iphone (version 4.1.6) to take pics and the same to trasfer pics.

**Comment by millenbop** [comment]
I need some debugging info from you. 

Could you connect the phone to your computer and go to iTunes. Then select your phone, then apps, then the Mapillary app, and finally copy the folder named "gopro". Please zip that and send that to me. Should be about a few Mb.

The "same" on GoPro can be done by connecting the computer to the GoPro wifi, then in a web browser type `http://10.5.5.9/gp/gpMediaList`. What you'll get is a very long JSON file of the file system on the GoPro, please send that to me as well.

You can either attach the files here or email them to me at anders@mapillary.com.

**Comment by millenbop** [comment]
I need some debugging info from you.

Could you connect the phone to your computer and go to iTunes. Then select your phone, then apps, then the Mapillary app, and finally copy the folder named "gopro". Please zip that and send that to me. Should be about a few Mb.

The "same" on GoPro can be done by connecting the computer to the GoPro wifi, then in a web browser type `http://10.5.5.9/gp/gpMediaList`. What you'll get is a very long JSON file of the file system on the GoPro, please send that to me as well.

You can either attach the files here or email them to me at anders@mapillary.com.

**Comment by iltempe** [comment]
The same is happened with app version 4.2.0. but no data are stored in iphone gopro folder!

**Comment by millenbop** [comment]
Which mode have you been using? 1.5s?

**Comment by talllguy** [comment]
I've had some weird issues like this with the GoPro, but @millenbop and I have worked through many of them. [I made a post over on the Mapillary Forum to discuss best practices for GoPro](http://forum.mapillary.io/t/best-practices-for-gopro-usage-with-ios-app/362). Ping me with any questions!

**Comment by millenbop** [comment]
This will be fixed in the camera implementation (V2). Closing this now, will be out in a few days.
