### ISSUE TITLE
Several functions are deprecated on insecure origins

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#1751]
<img width="1101" alt="screen shot 2016-03-14 at 00 06 11" src="https://cloud.githubusercontent.com/assets/3885790/13732032/c19cca06-e978-11e5-84f7-1df337458aa4.png">
URL: http://www.mapillary.com/map

#1708 would fix.

**Comment by knikel** [comment]
We've got better map style management in the new app. Closing 👍
