### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#1752]
<img width="1100" alt="zs05j4" src="https://cloud.githubusercontent.com/assets/3885790/13732049/8c47f7bc-e979-11e5-9f4d-72726d2479a7.png">

URL: https://www.mapillary.com/map

**Comment by OmgImAlexis** [comment]
You're also loading your favicon over http.

**Comment by emilstahl** [comment]
Not fixed? @knikel @gyllen

**Comment by Caboosey** [comment]
Still not fixed that I can see and saw more issues when looking at their HTML code. They still got mixed content, cross-domain issues, and mixed content with cross-domain.

Chrome and Firefox is still reporting and blocking 3rd party and non-HTTPS:
Mixed Content: The page at 'https://www.mapillary.com/map' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mapillary-vector.mapillary.io/tiles/9/132/210.mapbox?images=true'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.mapillary.com/map' was loaded over HTTPS, but requested an insecure favicon 'http://www.mapillary.com/favicon.ico'. This content should also be served over HTTPS.
XMLHttpRequest cannot load https://d2munx5tg0hw47.cloudfront.net/tiles/9/132/210.mapbox. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.

Looks like they need to setup DNS CNAME records at mapillary.com domain that points to "d2munx5tg0hw47.cloudfront.net" and "mapillary-vector.mapillary.io" and make sure it requests over HTTPS.

Looks like in the head section of their HTML is doing the favicon.ico with an HTTP request. they need to fix the HTML code.

**Comment by knikel** [comment]
@Caboosey, @emilstahl: this is fixed, you shouldn't see any mixed content errors now 👍
