### ISSUE TITLE
How to find the sequence to which a photo belongs?

### ISSUE THREAD

**Issue by cesaregerbino** [mapillary/mapillary_issues#1753]
Hi!

I'm trying to use the API so I'm quite a newbie .... 

I've solved how to search photos around a point in this manner ....

```
curl "https://a.mapillary.com/v2/search/im/geojson/close?client_id=<YOUR-KEY>&lat=44.91221&limit=1&lon=7.671685&min_ca=140&max_ca=190&distance=50"
```

and the result is .....

```
{
"features": [{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [7.671718, 44.912186]
    },
    "properties": {
        "ca": 183.5372,
        "key": "D6B1-IcUpWc6rEq2v-a4AQ"
    }
}],
"type": "FeatureCollection"
}
```

Now I'd like to know at which sequence the photo belongs (I thought there was in the response above .....) .... I've looked for a method in API reference but I've not found it ... 

Any suggestion?

Thank you very much in advance!!

 Cesare

**Comment by cesaregerbino** [comment]
sorry for the reminder .... any suggestions about this issue?
:-)

**Comment by gyllen** [comment]
Actually at the moment there are not any good way to solve this. If you explain what you want to accomplish I might be able to help you with a workaround.

**Comment by cesaregerbino** [comment]
Hi Johan and thank you for the response.

My needs:

1) I've a point, so its lat/lon coordinates
2) I'd like to know which photos are around that point, so I shoud use 

      curl "https://a.mapillary.com/v2/search/im/geojson/close?client_id=<YOUR-KEY>&lat=44.91221&limit=1&lon=7.671685&min_ca=140&max_ca=190&distance=50"

3) for the photo / photos I'd like to know the sequence which a photo belongs

The only way I've found still now (not still implemented), is:

a) search for the sequences in a box around my point (see [the issue I've opened](https://github.com/mapillary/mapillary_issues/issues/1760) ....)
b) search in the result (JSON) for the photo keys and so I can know the sequence id .... 

Not so efficient I know, and I don't know if it will work, but if you've suggestions / examples / alternatives they are welcome!!!

Thank you

**Comment by gyllen** [comment]
At this point you might have to go with searching for sequences in the bounding box. Im keeping this issue open though since more people have had trouble with this.

**Comment by nicolas17** [comment]
There *has* to be a way to go from photo ID to sequence ID reliably, maybe with undocumented APIs, because the Mapillary website does it!

**Comment by gyllen** [comment]
We get it through a graph API. Is this still an issue for you @cesaregerbino

**Comment by cesaregerbino** [comment]
Graph API? Do you have any example? Yes this is still an open issue ....

Il giovedì 19 maggio 2016, Johan Gyllenspetz <notifications@github.com> ha
scritto:

> We get it through a graph API. Is this still an issue for you
> @cesaregerbino <https://github.com/cesaregerbino>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/1753#issuecomment-220399112>
>


-- 
Cesare Gerbino

http://cesaregerbino.wordpress.com/
http://www.facebook.com/cesare.gerbino
http://www.facebook.com/pages/Cesare-Gerbino-GIS-Blog/246234455498174?ref=hl
https://twitter.com/CesareGerbino
http://www.linkedin.com/pub/cesare-gerbino/56/494/77b

Questo è un account di posta personale di Cesare Gerbino: tutte le opinioni
espresse sono personali e non riflettono necessariamente quelle del mio
datore di lavoro

This is Cesare Gerbino mail account. Text is written by Cesare Gerbino:
 the views expressed  are mine and not necessarily those of my employer.
.

**Comment by gyllen** [comment]
Its an API that we use to navigate it MapillaryJS, quite complicated and undocumented

**Comment by gyllen** [comment]
Try using this API, you will get all images and sequences around the image you put in -> https://a.mapillary.com/v2/nav/im/{{IMAGE_KEY}}

Its the best we can do for now, we are currently hard at work at v3 of the API that will solve this issue. Sorry for the delay.

**Comment by gyllen** [comment]
`v2` is no longer active, `v3` should solve this problem for you.
