### ISSUE TITLE
Mapillary v1.80 crashes when entering camera mode (SGS7edge, Android 6.0.1)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1754]
I can launch the Mapillary app, but when I try to go into camera mode, it crashes immediately.  Samsung Galaxy S7 Edge, Android 6.0.1.

It worked in either ver. 1.78 or 1.79 (can't remember which one I tried at first).

I will e-mail the trace logs to 'hello' in a moment.

**Comment by jfburke3** [comment]
Also crashes on a Galaxy S5 running Android 5.0.

**Comment by HolgerJeromin** [comment]
Same on fairphone 2 with Android 5.1

**Comment by rsahlin** [comment]
Thanks for reporting this!
Fixed in 1.81 release, please hang on for the update to go live :-)

**Comment by jfburke3** [comment]
*twiddling thumbs*

*pacing*

*more thumb twiddling*

**Comment by jfburke3** [comment]
Got it.

That seems to have fixed the problem!  Thanks!

**Comment by rsahlin** [comment]
Lol - thanks :-)
