### ISSUE TITLE
Make GPS dilution threshold configurable?

### ISSUE THREAD

**Issue by moenk** [mapillary/mapillary_issues#1756]
I think it would help to make the dilution threshold configurable instead of the hardcoded 15 meters, maybe just with commented presets like: 10 m (good), 15 m (normal), 20 m (weak), 25 m (bad). Sometimes I know my position data is ok and I am annoyed by not being able to take any picture.

**Comment by polarbearing** [comment]
Those android GPS precisions are snake oil anyway, introduced by an android developer who has not understood how GPS works. The real HDOP (horizontal dilution of precision) is a probability value, not a distance, and it does not come in 5m-intervals. Further it is based on satellite constellation only, i.e. when you have a strong reflection form an object, the resulting multipath reception can put you several 100m off, even with a good constellation.

**Comment by moenk** [comment]
I know that, but I also think that we can not assume every user of Mapillary want to go in these details. So for me some simple way to change the preset of 15 meters would be enough. It seens even to be like that when my phone becomes warm the given precision is weaker although I am still on the road when I have a look on the Locus map.

**Comment by millenbop** [comment]
Just wanted to chime in that this problem exists on iOS as well.

**Comment by echeloni2p** [comment]
Hi!

Just disable the GPS check in the settings for those areas. And move the pictures to the right position in the editor afterwards.
Currently those changesets are accepted, but not executed until a new changeset editor goes live.

That is what I do. 
Accepting pictures which are 20m+ off in the city is a real pain on the map for ALL technics mapillary uses in background. E.g. pictures are bound to another parallel street or else.

echeloni2p

**Comment by moenk** [comment]
I dont use the app if I can avoid it for that reason, although the concept is genius. I rather use my Virb, and I dont feel like moving pictures in position by hand. The point is that the given accuracy doesnt mean that the position is that wrong and usually it is not at all, it just mean sth like with a prohabliity of x percent the real position is in this range. So I dont want to switch this feature off, there is reason to use it, but I want to select there threshold on my own.

**Comment by polarbearing** [comment]
> Accepting pictures which are 20m+ off in the city is a real pain

A picture with an android-"precision" of <5m can be 100m off. 
A picture with an android-"precision" of 50m can be quite close.
GPS has both random errors and systematic errors that are not covered by that android value.

> the given accuracy doesnt mean that the position is that wrong and usually it is not at all

yup.

**Comment by echeloni2p** [comment]
I think the system it works now is best for Mapillary, as it needs to work in 99% fine with a lot of users. Just because precision of <5m is over 100m in 1 of 1000 cases, there so not need to be any change.
Mapillary needs to work in 99% fine to get pictures and good positions.
So it works fine as it is now.

echelon
