### ISSUE TITLE
Manual upload fails if filename exists already in sequence

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1758]
The Garmin Virb is putting its images in folders, 999 images per folder. The filenames are VIRB0001.JPG to VIRB1000.JPG in every folder. If I have a sequence that spans more than one folder, the upload will fail because it assumes that this file already has been uploaded. Instead of checking the filename for duplicates the uploader should check something like the checksum of the exif data. Sequences that span over 1000 images are not rare, sometimes in those sequences many images have been deleted (waiting at red lights, blurry ones, etc) so that the total number of images in the sequence are well below 1000, but still filenames exist twice in the sequence.

**Comment by jesolem** [comment]
Something for the "new" uploader to handle too @knikel and @angelday , besides this which applies to web (I think).

**Comment by mxa** [comment]
Oh, yes sorry for not mentioning this. It applies to the web uploader. Are you saying this would work if I would use the upload script instead?

**Comment by jesolem** [comment]
@mxa Great. 

I was referencing our upcoming desktop uploader which @angelday is designing with @knikel . Still a month or two out until we can share that one.

**Comment by nicolas17** [comment]
I think the Python upload script would not currently work, but it can be modified to work without too much trouble. Otherwise the files could be renamed (there exist many mass-rename tools) and then you can use any upload method.

**Comment by mxa** [comment]
This is still an issue even on the new website.

**Comment by de-vries** [comment]
This happened yesterday to me with the sequence split script. 
My camera also puts 999 photos per folder and uses the same numbers for the filename in all folders. Normally I rename all files to prevent problems, but I forgot this time. I used `sequence_split.py` and all sequences got jumbled up and ~800 photos went missing. 

I don't know what exactly went wrong but after I used `sequence_split.py` I deleted some photos of a red traffic light and ran the script again. That's when the problems occured.

[here](https://www.mapillary.com/app/?lat=51.67031966706503&lng=5.303665789703388&z=14.252768549619034&pKey=5Tt5fsUO2v-Tp-mhrvB-0g) is a sequence with big gaps in it. Photos from those gaps ended up in other sequences or got deleted.

If I may suggest a solution, rename the files to something time based, like how the app does it. Or at least the scrip should stop and give an error, as I see no reason why a script for reorganizing a folder structure should have the ability to delete/overwrite files.

**Comment by nicolas17** [comment]
If running the script deleted or overwrote files locally, that seems like a different issue.

**Comment by ybkuang** [comment]
@de-vries I opened an issue for your problem here https://github.com/mapillary/mapillary_tools/issues/136. Sorry for the issue. We will look into it.

**Comment by gyllen** [comment]
Closing since open in public repository mapillary_tools.
