### ISSUE TITLE
None of the sequence edits works anymore

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1759]
Neither "Correct angles", nor "Hide the whole sequence", nor "Request sequence cut" work. Only the last one returns an error message in the UI, the other two fail silently (though there are 404 errors for all three in the network communication).

Combined with #1736 makes me wonder if there is anybody that would be able to use the editor in any meaningful way.

I suggest you completely remove access to the whole editor until these issues are fixed, to prevent confusing users.

**Comment by ToeBee** [comment]
Well boo. I just found some old pictures from 2012 that were already geotagged but didn't have a direction set. I uploaded them, planning on setting the angle in the sequence editor. Now I have a bunch of pictures that say they're all pointing at the north pole :(

**Comment by polarbearing** [comment]
confirming the bug on Safari/mac uand Firefox/linux

**Comment by cascafico** [comment]
Not possible correcting angles in Firefox 44.0.2 for Ubuntu: clicking related button but nothing happen. Blur requests are queued, but still don't know if processed.

**Comment by gyllen** [comment]
We are working on a new editor and its looking awesome, so hang on.

Your blur requests should be gone through though.

**Comment by polarbearing** [comment]
Fine for the new one, however why can't you revert the changes in the old one that lead to the problems meanwhile? That builds a backlog of uncorrected sequences with the power users that might eventually get forgotten.

**Comment by pbb72** [comment]
Yeah it seems that Mapillary is not testing their code changes enough to ensure they don't break things...

**Comment by gyllen** [comment]
@polarbearing The backlog is not being forgotten. We have them all stored and we are currently exporting them to the new system. So everything that goes in will be added.

@pbb72 Our website has outgrown itself and at the moment there are a log of moving parts that effect each other. You will be happy to know though that we are full speed ahead with a new website (where we have learned a lot from the first iteration). More news about that soon.

**Comment by polarbearing** [comment]
> The backlog is not being forgotten. We have them all stored

What I meant is my own list of edits that need to be done, but are impossible for a while now. Keeping track of them is further difficult since the activity page is rather difficult to use to keep track of a particular sequence (no concise listing by date etc).

**Comment by gyllen** [comment]
@polarbearing I see, really sorry for the inconvenience. Please know that we are working full speed a head on getting the new editor up. We know that this is a big concern for the community.

**Comment by pbb72** [comment]
Would it be possible, maybe using the API, to create a list of one's sequences that have all photos without direction (ie all facing north)?

**Comment by gyllen** [comment]
@pbb72 Thats a really good idea, we should poke users that clearly has bad directions to update them. Adding to internal idea stack.

**Comment by gyllen** [comment]
Fixed with new editor
