### ISSUE TITLE
only show recent pictures on the map

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1765]
it was possible to show pictures on the map from a specific time period. That feature was usefull to find area that has old pictures and should therefore be upldated. Is it possible to have it reimplemeted?

**Comment by HolgerJeromin** [comment]
It is still there. On the map view (not photo or search) there are "user filter" and "time filter"

**Comment by jesolem** [comment]
@HolgerJeromin is right. Closing.
