### ISSUE TITLE
Make app show version number

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#1767]
I hope I'm not missing something obvious, but I would like to see a version number somewhere in the app. Am I using the beta or the release? I'm not sure. How to find this out? Maybe in the "Credits" menu entry on top?

**Comment by jesolem** [comment]
On iOS it is in the main settings. 
Settings > Mapillary (scroll down to the list of apps in alphabetical order)

If Android, I'll let @rsahlin answer ;)

**Comment by rsahlin** [comment]
On Android it's in the Settings menu  - scroll down to the bottom and there it is :-)

**Comment by mxa** [comment]
Doh! It says 1.83, Version code 183. Is that the release or the beta?

**Comment by rsahlin** [comment]
Hi mxa - glad you found it :-)

1.83 is currently beta-  1.84 is on the way out to the beta group.
The only way I know of checking if the version you have is beta or release is to compare it to the version on Play - https://play.google.com/store/apps/details?id=app.mapillary scroll down and you will find the current release version.

**Comment by mxa** [comment]
aww thank you.
