### ISSUE TITLE
Overlapping shapes for South Africa and Lesotho

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary_issues#1768]
When uploading images in Lesotho you sometimes end up as a top contributor in South Africa when receiving the weekly stats email. 

Also when checking the stats for
- Lesotho - http://www.mapillary.com/map/places/85632173
- South Africa - http://www.mapillary.com/map/places/85633813

there seems to be a lot of overlap regarding the top contributors. The uploads from Lesotho seems to "spill over" to South Africa.

**Comment by peterneubauer** [comment]
This problem should be minimized now, closing.

**Comment by oscarlorentzon** [comment]
Thanks @peterneubauer.
