### ISSUE TITLE
Link to previous edition

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#177]
When I edit a set and in the middle of the process I want to blur/unblur something I have to make save changes request before because If not I lose the changes I made.So when appears the message Thank you , your request...24h... it will be some help to put a link that return me to that set of photos in last image I did the request, to continue at the same point editing images.

**Comment by knikel** [comment]
Adding as a feature request for the new editor

**Comment by nickplesha** [comment]
I think this is related to an older version of an editor and does not apply anymore.
