### ISSUE TITLE
iOS viewer doesn't rotate 180° in fullscreen

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1770]
In the new MapillaryJS-powered sequence viewer in the iOS app, while the phone is vertical, I can tilt it horizontally either right or left, and it will enter fullscreen mode. But once it's tilted 90° right, I can't rotate it 90° left, or viceversa. That is, if I'm in fullscreen mode and I rotate the phone 180°, the image doesn't rotate. I have to first orient it vertically to exit fullscreen.

**Comment by millenbop** [comment]
This should be fixed in the next release.
