### ISSUE TITLE
iOS viewer acts weird if notification is received while in fullscreen

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1771]
If a banner notification arrives while the iOS viewer is in horizontal/fullscreen mode, the viewer briefly goes into vertical view and then back into fullscreen. The banner appears on the "top" of the screen (where the speaker is; since it's rotated, that means the banner is sideways). It seems like iOS doesn't know the app is in horizontal mode so it still shows notifications as if it was vertical.

When the banner automatically disappears, the UI again goes briefly vertical and then *turns black*. It returns back to normal if I put the phone back into vertical orientation.

**Comment by nicolas17** [comment]
While in horizontal fullscreen mode, Control Center and Notification Center are also available in their usual screen edges as if the screen was vertical, and the Mapillary UI goes vertical when I bring up either of them. When dismissed, Mapillary goes back into horizontal fullscreen mode (unlike with banner notifications disappearing, it doesn't go black).

**Comment by nicolas17** [comment]
I now have more evidence that there is something fundamentally wrong with the orientation handling in the viewer. I tried AirPlay Mirroring to an Apple TV, and if I'm in the Mapillary viewer and I rotate the phone to landscape, the viewer goes fullscreen, but the image on the TV remains portrait, so the photos are rotated.

(This sounds very different to the original bug report about notifications, but I'm pretty sure it's another symptom of the same underlying problem)

**Comment by millenbop** [comment]
That's probably because I rotate the view and do not set the phone to landscape view, so it's probably another issue.

**Comment by millenbop** [comment]
This should be fixed in the next release.
