### ISSUE TITLE
iOS viewer goes black if I start swiping to go back but don't finish

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1773]
In the new iOS sequence viewer, if I start swiping from the left edge to go back to the previous screen (such as the map, or the list of sequences in my profile), the viewer immediately goes black. If I release the finger instead of continuing to swipe all the way, the app stays in the viewer (standard iOS behavior), but it remains black.

From my past experience with the navigation controller, I think it may be an error with using `viewWillDisappear` vs `viewDidDisappear`.

**Comment by millenbop** [comment]
Fixed.

**Comment by nicolas17** [comment]
In 4.2.1? No, no it isn't 😓

Swiping back from a sequence to the map (map tab) doesn't make the viewer become black anymore. It now turns white instead.

Swiping back from a sequence to the list of sequences of that month (profile tab) is not even possible anymore, the swiping does nothing, the only way to go back is the < Back button.

**Comment by millenbop** [comment]
No in 4.2.2, sorry. It's been fixed but not released.
