### ISSUE TITLE
Spanish error message trimmed

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1774]
In the iOS app, if I tap on the map to see photos in that point, but an error happens (eg. because there is no Internet connectivity), the Spanish message says "Algo ha fallado. Por favor, inténtalo de nuevo más". It seems to be missing the "tarde" word at the end ("más tarde" = "later"). Either the translated text is wrong, or it's wrapping into three lines but the third line is trimmed.

It also *might* look better to increase the width of the error box instead of letting it wrap into three lines, but that's subjective, and it's hard to tell without seeing both alternatives.

**Comment by millenbop** [comment]
Thanks for reporting, it is fixed in the next release.
