### ISSUE TITLE
"Connections" page should show a placeholder if content is empty

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1775]
In the [Connections](https://www.mapillary.com/profile/nicolas17/connections) page, if there are no connections for that user, an empty page is shown. Users could think the page is still loading, or there was an error. There should be text saying there are no connections, maybe even explaining what connections are.

**Comment by nicolas17** [comment]
Is this page gone in the new website?

**Comment by gyllen** [comment]
@nicolas17 Yeah it was outdated information anyway. Closing
