### ISSUE TITLE
expose interval changing in the apps more

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1776]
currently changing the interval is cumbersome - one has to stop capturing, close the capture mode, go into settings...
it would be nice to have interval change easily available from the mode switching screen - inside each of the mode lines, there's enough space to stuff a scrollbar (probably leaving some space on the left side to make switching between the modes easier - less chance accidentally hitting the scrollbar)

**Comment by HolgerJeromin** [comment]
In capture mode you can access settings. At least on Android. 
But still it forces portrait mode and is still a long way.

**Comment by richlv** [comment]
oh, looks like in the iphone app that's not possible - but yes, the biggest problem is the huge amount of operations needed.
in the mode switching view, there's more than enough space to add sliders :)

**Comment by millenbop** [comment]
This has been added to the new camera UI, will be available in the next release.
