### ISSUE TITLE
Samsung S3 Neo Problems with GPS and Mapillary

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1777]
Usually the S3 has a good GPS accuracy, with GPS Test it is 3-10m. But in mapillary it is always yellow or red (in a town or in the forest). If I "skip location check" and "pause on stop" (it always says I am to slow) I can verify in a map or in JOSM that the GPS locations are good and not "red" as mapillary says.

**Comment by rsahlin** [comment]
Hello wegavision and thanks for your report!

What version are you using?
If you are signed up to the beta program you should have access to 1.84 which has several fixes to GPS functions - if not it will be available within a couple of days.

In the Mapillary app we treat accuracy of 8 -> as yellow and 15 -> as red, this means that a reported accuracy of 3-10 meters will vary between green and yellow.

Could you please go into settings and enable 'Show detailed stats' - this will display the current location along with the reported accuracy.
Also please try checking/unchecking the setting for 'Use Google Mobile Services'

Please let us know what your results are!

Best regards
/Richard

**Comment by rsahlin** [comment]
Closing this since no feedback for some time.

Please re-open with more info if needed.

Best regards
/Richard
