### ISSUE TITLE
Manual Upload of Panorama with source images shot with Mapillary fails

### ISSUE THREAD

**Issue by JulieMay** [mapillary/mapillary_issues#1779]
I've tried many times now to upload two panoramas.

Both result in the same problem:
  If uploaded online, they hang with either 99% or 100% boldly showing and nothing coming back for reporting or confirmation (Usually it says 100%.). The uploaded image does not show in my history or on the Mapillary map.

If uploaded using the python script, upload_with_authentication.py, an error comes back, eventually causing me to break the connection. Here is is a sample log:
C:\>python "upload_with_authentication.py" "2016_03_17_14_28_12_711 Panorama.jpg"
Uploading sequence ce3e49b8-3154-4e06-b85b-795877b66118.
Uploading 1 images with valid exif tags (Skipping 0) ...
[============================================================] 100.0% ... 0 imag
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg
HTTP error: HTTP Error 403: Forbidden on 2016_03_17_14_28_12_711 Panorama.jpg

BREAK: Stopping upload.

My last try had all of the required exif as noted by the help files. Here are the relevant tags:
Date/Time Original              : 2016:03:17 14:28:12
Create Date                     : 2016:03:17 14:28:12
GPS Latitude Ref                : North
GPS Latitude                    : 51 deg 11' 19.36"
GPS Longitude Ref               : West
GPS Longitude                   : 115 deg 31' 10.37"
GPS Img Direction Ref           : True North
GPS Img Direction               : 267.5007414
Projection Type                 : equirectangular
Use Panorama Viewer             : True
Cropped Area Image Width Pixels : 17405
Cropped Area Image Height Pixels: 2033
Full Pano Width Pixels          : 19581
Full Pano Height Pixels         : 9790
Cropped Area Left Pixels        : 1088
Cropped Area Top Pixels         : 3489
Pose Heading Degrees            : 268
Image Width                     : 17405
Image Height                    : 2033
GPS Latitude                    : 51 deg 11' 19.36" N
GPS Longitude                   : 115 deg 31' 10.37" W
GPS Position                    : 51 deg 11' 19.36" N, 115 deg 31' 10.37" W

**Comment by gyllen** [comment]
Hi @JulieMay can you help us with uploading one of the files you are trying to upload here?

**Comment by gyllen** [comment]
I might be that the we do not allow images bigger then 20MB at the moment. Can that be it?

**Comment by gyllen** [comment]
Closing since no answer
