### ISSUE TITLE
Mapillaring xtrem mode

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#178]
It is a good thing that photos get geolocalizated via mobile GPS.But in some places, with trees, or mountains GPS doesn't work well...so set of photos is stopping while I'm driving!! I want a RAW/temporized/semiautomatic etc. mode, that if the GPS signal is lost Mapillary doesn't stop to make photos every two seconds so later I can edit these non geolocalizated photos in their correct places.When you go "mapillaring" by car , you can't stop even GPS signal is lost, you have to go forward, so your set looks little weird with lost frames.

**Comment by jesolem** [comment]
Hi @yopaseopor , is this still a priority? What app are you using?

**Comment by yopaseopor** [comment]
Jajajjaaj, now that issue in Android can be closed due to Developer options with skip of check GPS (I have done some sequences in tracks and paths ) is what I have with the newest Mapillary app.I'm working with Android.Also the 4:3 1024 option is my option by default (as you can't choose the quality of pics in normal way I have 20 GB every 1000 pics and my phone sometimes hungs up).I That options are good for me, now app adapts me and my work at the majority of tracks.
I'm happy with that.
Now the problems goes along with things like Play Button in Embed or mobile site https://github.com/mapillary/mapillary_issues/issues/1260 or the Explore option /Search "tab"(https://github.com/mapillary/mapillary_issues/issues/1253) or the selector https://github.com/mapillary/mapillary_issues/issues/1261 .
