### ISSUE TITLE
Layers of web map blinked while refreshing, and then falls to white screen

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#1780]
![mapillary-4](https://cloud.githubusercontent.com/assets/4630662/14158053/c54fdace-f6d6-11e5-9476-79e536bdd8a6.gif)

**Comment by Caboosey** [comment]
I will see the same thing happened on my Google Chrome on my Windows 7 SP1 (64-Bit), but not see this happen on my Mozilla Firefox.

At certain zooms. I get weird display issues like water and land randomly appearing where they shouldn't at 45 degree angles.
![mapillary_01](https://cloud.githubusercontent.com/assets/12619646/15269612/059f4464-19ca-11e6-82a2-4164d011383c.jpg)

**Comment by knikel** [comment]
We have one map style currently, this is no longer an issue. We'll have more graceful style swap, if we'll support more styles.
