### ISSUE TITLE
Search API does not function normally

### ISSUE THREAD

**Issue by percentage** [mapillary/mapillary_issues#1781]
When using the search api to get images in a certain area, the server sometimes provide images that are out of bound. For example, if one use the following query:

https://a.mapillary.com/v2/search/im?client_id=RG1oWTFfUm9mdWVvWHo3ZjhNYTM2UTpjYjVhY2RjYjhkODZhODRi&max_lat=55.881338&max_lon=12.9960006305&min_lat=55.8812176305&min_lon=12.995821&page=0

The result is as follows:

<img width="1154" alt="screen shot 2016-03-30 at 7 44 11 pm" src="https://cloud.githubusercontent.com/assets/3970948/14161197/cfab9bba-f6af-11e5-828b-fbf187cdc4f5.png">

It is obvious that the second image "AO8T0SovbR7f62oejxHr8Q" is not in the area constrained by "max_lat=55.881338, max_lon=12.9960006305, min_lat=55.8812176305, min_lon=12.995821"

**Comment by gyllen** [comment]
@percentage Thanks for pointing this out, I think this might have todo with how our database does spatial lookup, there might be some rounding errors. I will look into it, thanks for reporting.

**Comment by percentage** [comment]
@gyllen Sorry for bothering. As your API could significantly improve our research (diverse data with rich information), just wanna check out how are things going ;)? Thanks!!

**Comment by gyllen** [comment]
@percentage No problem. Would you mind getting on a skype call, would be interesting to know how you intend to use our API.

**Comment by gyllen** [comment]
`v2` is no longer an active API. Closing.
