### ISSUE TITLE
Add option to turn off "smooth image transitioning"

### ISSUE THREAD

**Issue by zdila** [mapillary/mapillary_issues#1782]
Please add option to turn "smooth image transitioning / morphing" off on the web.The reason is that this feature mostly provide worse user experience than just regular image slideshow.

**Comment by zdila** [comment]
One example with very bad result: http://www.mapillary.com/map/im/BnEuCLiXqld5nQ5YNg7wnQ/photo?autoplay=true

**Comment by AllenGraetz** [comment]
I'd love to have this option.

**Comment by oscarlorentzon** [comment]
This is supported in our new viewer `mapillary-js`.

Reassigning to our designer @angelday for decision on how to include this in the new website.

**Comment by Hjart** [comment]
I generally experience the morphing of my sequences as horrible. See for example sequence d8C0_Hx9gsSerVRNi6xZeg. I would very much appreciate the option to say "no, do not under any circumstances morph anything in this sequence/my sequences". Again... it's a horrible experience.

**Comment by gyllen** [comment]
@Hjart Thanks for your feedback. In general when there is a lot of trees and an overexposed sky it is hard to merge images. If you look at where you have more structure in the image I think (in my opinion) that it looks pretty good https://www.mapillary.com/app/user/hjart?pKey=ugfYUqWoERF65eBMP4ckcQ&lat=55.14875277777778&lng=8.95986111111111&z=17&focus=photo

Having that said we are working with segmantic segmantation to filter out for example the sky. @paulinus can explain more about this.

Once again thanks for brining this to our attention and your feedback is much appreciated.

**Comment by gyllen** [comment]
Also as a general rule of thumb the denser you can get the images the better (I looked at your imagery and I think its very impressing) the better reconstruction. Here you can see that a "denser" sequence looks better https://www.mapillary.com/app/index/hjart?pKey=2y7fNAUlaK9acLkt9rzmKQ&lat=55.28897222222222&lng=9.045361111111111&z=17&focus=photo

**Comment by gyllen** [comment]
Here you can see a problem where the coulds are to prominent https://www.mapillary.com/app/index/hjart?pKey=7YnTm5Jz9rSMt3bTU2KWZQ&lat=55.28975833333333&lng=9.042375&z=17&focus=photo (we are working on fixing this)

**Comment by paulinus** [comment]
With the latest reconstruction algorithms, we are ignoring sky, clouds and other potentially moving objects. This improved the transitions in all sequences mentioned here.

The viewer, mapillary-js, already supports a mode without transitions but we have decided not to add such option to the web for now.
