### ISSUE TITLE
Video upload broken with angularjs error message

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1783]
I finally got around to trying to upload some old video files I have laying around but after I select the GPX file, the map stays blank and my browser starts spitting the following error out on the console repeatedly (in the time it took me to write this report, it has happened about 3,000 times) :

    Error: [$rootScope:inprog] $digest already in progress
    http://errors.angularjs.org/1.4.0-beta.5/$rootScope/inprog?p0=%24digest
        at lib-89c8918e.js:16823
        at beginPhase (lib-89c8918e.js:32345)
        at Scope.$apply (lib-89c8918e.js:32089)
        at syncMarkerWithVideo (mapapp-ee859f58.js:8928)
        at lib-89c8918e.js:30855
        at Scope.$eval (lib-89c8918e.js:31991)
        at Scope.$digest (lib-89c8918e.js:31806)
        at Scope.$apply (lib-89c8918e.js:32096)
        at tick (lib-89c8918e.js:27332)

This happens in both Chromium and Firefox.

**Comment by marcioaguiar** [comment]
This happens to me also. Besides having to load the gpx file twice, this message appears repeatedly and this message also appears:

`http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`

**Comment by gyllen** [comment]
@knikel Any news in this?

**Comment by knikel** [comment]
I'll look into that this week!

**Comment by knikel** [comment]
Hey folks, this should be fixed now!

**Comment by marcioaguiar** [comment]
It's working!

Thanks!

**Comment by marcioaguiar** [comment]
Well... almost.

Everything went fine. I uploaded the video, it showed progress and told me the process was completed. Except I don't see my upload anywhere and didn't receive any e-mails about it.

It has been a day already.

**Comment by knikel** [comment]
@marcioaguiar the videos are getting harvested and queued for processing at certain intervals. Rest assured, they will be processed soon. We have a `269.4mb` from you waiting to be processed and an accompanying `.gpx` file. Ping @peterneubauer.

**Comment by knikel** [comment]
I'm closing this since the upload process issue has been solved. Your video will be processed soon @marcioaguiar 🎉

**Comment by marcioaguiar** [comment]
@knikel I'm sorry to return to this, but my video still wasn't processed. Something went wrong?

**Comment by knikel** [comment]
@gyllen could you check the status of that?
