### ISSUE TITLE
Photos are uploaded but not yet added (still processing?) 

### ISSUE THREAD

**Issue by skorasaurus** [mapillary/mapillary_issues#1784]
Hi, 

I have 3 sequences that have been uploaded to Mapillary but aren't available to be viewed and they have the following characteristics: 
- They are not listed in [my profile](http://www.mapillary.com/profile/skorasaurus) on the mapillary website. My profile also lists 0 images are still needed to be processed. 
- The sequences appear in my feed (see this screenshot) on my android app 
![screenshot_2016-04-03-12-06-03](https://cloud.githubusercontent.com/assets/955351/14233416/c9904d8c-f995-11e5-8019-cb44d7a7877c.png) that the photos were uploaded, contrasted to the others that are added. There's 2 other sequences in my feed (most recently uploaded March 25th) that are also designated as uploaded and not added. 

These sequences aren't relatively large - between 100 and 250 images. 

Same symptom (profile not accurately displaying # of photos still to be processed) as https://github.com/mapillary/mapillary_issues/issues/873

**Comment by gyllen** [comment]
Can you check now? We might have had some backlog in system.

**Comment by skorasaurus** [comment]
Checked, not added. :(

**Comment by gyllen** [comment]
If you go to your feed and find your images there -> http://www.mapillary.com/profile/skorasaurus/activity

Can you access them then?

**Comment by skorasaurus** [comment]
Closed; The photos ended up being there, but I think a couple things happened: 

* I thought I had a sequence that I evidently must have never taken (sorry!) 
* I finally noticed that the the '145 photos uploaded' was then followed by 3-4 sequences that, when added together, equaled 145. This pattern occurred 2-3 other times in the past couple weeks and I hadn't noticed it before.

**Comment by gyllen** [comment]
@skorasaurus We have had some upgrades to backend lately so we have had delays a couple of days, thats probably why it has taken so long for the photos to show up.
