### ISSUE TITLE
GoPro4 -> Iphone = Date is wrong

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1785]
Hey,

when i transfer my Pictures from the GoPro 4 Session to my Iphone 6s.
the Date in the Uploadingview is always the Date, where it got Transfered to my Phone 
and not the Capturing date, can you "fix" that ?

Cheers
Thorsten

**Comment by millenbop** [comment]
Hi!

Thanks for reporting! Yeah it's been bugging me too for a while, I'll see what I can do!

**Comment by millenbop** [comment]
This has now been fixed, will be included in the next release. Affects all action cameras.
