### ISSUE TITLE
on website user thinks he can upload a profile pic

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1787]
On the website the user thinks he can upload a profile pic, but thst is apparently not the case. The icon fools users.

**Comment by GITNE** [comment]
To be honest, I do not really understand what you are complaining about. The only thing that could perhaps use some improvement is the avatar upload field's label, which is labeled "Photo" instead of "Avatar".

**Comment by jidanni** [comment]
OK today I ended up on https://www.mapillary.com/map/settings/profile and was able to reasonably proceed.

**Comment by jidanni** [comment]
Wait, I just realized the screen I was talking about was:
![screenshot_2016-04-11-13-31-47](https://cloud.githubusercontent.com/assets/1230959/14453825/ba43bdb0-00c9-11e6-99b3-0d38970a4ca8.png)
I was unable to change the photo of me whatever I did there using my cellphone in the app. I had to go to the website to change it.

**Comment by jesolem** [comment]
Ah. Android bug then.

**Comment by rsahlin** [comment]
We will be looking over the application UI (both Android and iOS) in the future.

Best regards
/Richard
