### ISSUE TITLE
App contains no instructions

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1788]
App contains no instructions. Add instructions and / or tutorial to the app.

**Comment by jidanni** [comment]
Not even a link to https://github.com/mapillary/UserGuide/wiki can be found from within the app.

**Comment by millenbop** [comment]
Hi! Thanks for reporting. We are in the middle of improving on-boarding and the how-to-get-started stuff.

**Comment by angelday** [comment]
First improvements have rolled out, we will continously work on getting the experience clear and understandable. Closing this issue.
