### ISSUE TITLE
UserGuide/wiki not mobile ready

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1789]
https://github.com/mapillary/UserGuide/wiki is only desktop ready. It also needs to be mobile ready, as that is where many users will be browsing it from.

**Comment by knikel** [comment]
@jidanni Thanks for the feedback on that. Unfortunately github's interface is not mobile ready, nothing we can do about that. We're not planning on moving the wiki elsewhere at this time.
