### ISSUE TITLE
Statistics Not Showing For Pictures On The Map ( Uploaded This Morning )

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1792]
I uploaded more pictures this morning.  The lines are showing up on explorer where I drove Sunday  across southern Kentucky on the Cumberland Parkway.

When I go to the statistics page for Kentucky, I can still see that new line for those new pictures in the explorer map window.  However, the counts for those new pictures are not reflected in the stats for the region of Kentucky.

Should they be showing up in the statistics if the pictures were uploaded this morning?  If not, about when?  By tomorrow morning?   

I want to bring this up in case it's a symptom of some problems with the task queue to process those statistics.    Thank you.

![image](https://cloud.githubusercontent.com/assets/11722025/14285691/8335e0aa-fb1a-11e5-971c-04739eedfadf.png)

**Comment by gyllen** [comment]
I think there is a bug with showing current week.

**Comment by AllenGraetz** [comment]
THanks.  That would make sense since it's been a couple days and it's still not in the stats.  It was easy for me to spot since there doesn't seem to be any regular mappers in Kentucky & I drove through it Sunday on my way back home.  

As you can see, as of now the count hasn't been updated yet, at least not the count that is used for this view.

![image](https://cloud.githubusercontent.com/assets/11722025/14355465/00207e00-fcaf-11e5-87b3-d3e8db362514.png)

**Comment by gyllen** [comment]
@knikel Can you look into this, I think it has something todo with double weeks in the API.

**Comment by AllenGraetz** [comment]
Since having another example may help better help with problem solving, I'm seeing the same issue this week with North Carolina.  I haven't uploaded all but some of my images from my drive up to Clingman's Dome in the Great Smokeys National Park have been uploaded.  

I can see them on the map.   Yet today they aren't showing in the weekly count.     

There do not appear to be any images that are being lost.   From everything I've seen, it only seems to be count affected.   I'd imagine this is a lower priority bug.


![image](https://cloud.githubusercontent.com/assets/11722025/14681686/29e57d9e-06f0-11e6-9737-3bb098894db7.png)

**Comment by gyllen** [comment]
Thanks for reporting this again its an error in the client.

**Comment by knikel** [comment]
We've redesigned the statistics and how we fetch the data. I hope you're happy with the new changes @AllenGraetz!
