### ISSUE TITLE
Camera Direction Indicator Turned 180' 

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1793]
If you go to a map and click on a sequence like this one

![image](https://cloud.githubusercontent.com/assets/11722025/14294123/80e0aeca-fb3d-11e5-843e-6b6f26e6960f.png)

The initial indicator for the photo is 180 degrees from where it should be.  once you go to the next photo in the sequence it fixes itself.

![image](https://cloud.githubusercontent.com/assets/11722025/14294118/7ab2f12a-fb3d-11e5-839f-2f80a3a2738d.png)

**Comment by AllenGraetz** [comment]
And, as you probably know, clicking on the map view for that photo has the same direction problem

![image](https://cloud.githubusercontent.com/assets/11722025/14294216/e471953a-fb3d-11e5-9c5d-648092e7caf9.png)

**Comment by AllenGraetz** [comment]
If you progress in the sequence a few photos, the directional indicator will be correct until you click on the map tab.  It then goes back to being the opposite of what it should be.

![image](https://cloud.githubusercontent.com/assets/11722025/14294252/18894732-fb3e-11e5-8161-f31f34ff30ab.png)

**Comment by AllenGraetz** [comment]
I made a bad assumption.  It's not 180', it's defaulting to 0'.

http://www.mapillary.com/map/im/IAFPxQYZfN5Ga4EMij3keA/photo

![image](https://cloud.githubusercontent.com/assets/11722025/14294424/09606870-fb3f-11e5-8ef2-677c142cf29b.png)

**Comment by knikel** [comment]
This has be fixed in the new web app, since we read compass angle directly from the vector tile data without any calculations on top of that.
