### ISSUE TITLE
Combined persistent filters

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#1795]
Hey,

it seam's that the Filter "user" and "time" are not working well, when u try to use both.
First i selected the Filter to select me , in the Second Step i selected the Time, but it seams, that i get more information as i expecting .. For me, it look's like, that only the "last" Filtter is working in that Scenario.. Using both Filter on same time would be very nice ..

Cheers
Thorsten

**Comment by knikel** [comment]
We've updated the [filters](http://blog.mapillary.com/update/2016/08/31/view-what-interests-you-most-introducing-filters.html). We have persisting them in the URL in the pipline.
