### ISSUE TITLE
I can't find any sign of uploaded photos

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1798]
Yesterday I uploaded 4600 photos via upload.py and I don't see any sign of them on the site (not on the map, on my profile page or in any statistics.

I added coordinates with JOSM, then ran sequence_split.py, interpolate_direction.py, add_mapillary_tag_from_exif.py and python upload.py

can you help me figure out if I did something wrong?

Here is an example file:
![file2555](https://cloud.githubusercontent.com/assets/1449609/14376362/38c35ee8-fd69-11e5-9bf5-79bd48954c6a.JPG)

**Comment by echeloni2p** [comment]
Hi!

Just wait - did you got a email about uplodaed pictures yet?

**Comment by de-vries** [comment]
nope, but that's because I've opted out of that email.

the photos haven't even shown up in the still processing count, the behaviour looks exactly like when the server rejects the photos for not having the right exif-tags.

**Comment by de-vries** [comment]
They seem to are coming trough now. In case you fixed it thanx, if not, I'm sorry for complaining prematurely, I guess I got used to much to the high processing speeds.
