### ISSUE TITLE
photo got broken in processing

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1800]
http://www.mapillary.com/map/im/MgZyvXgAJwvj6o4tWeCsJg/photo got messed up. the top part is from the original photo, the rest is from another photo from the same sequence: http://www.mapillary.com/map/im/Q5zkm9I5_BVxpGmlrTtXDA/photo

**Comment by ybkuang** [comment]
@de-vries It looks like something went wrong when storing the processed photos to server. We will look into that. Do you see these often in your sequences?

**Comment by de-vries** [comment]
I've never seen this before. Also I have reviewed the blurring of every photo I've uploaded that day and this was the only photo that went wrong.

**Comment by ToeBee** [comment]
I found another one that is all kinds of messed up. In the sky you can clearly see a boundary between two different pictures but I have no idea what happened at the bottom of the picture:
http://www.mapillary.com/map/im/caLfkHGb8eQDprVGy24j1w/photo

I still have the original for this picture and there is nothing wrong with it on the hard drive I uploaded it from. This was a manual browser upload.

**Comment by ToeBee** [comment]
And another one in the same sequence:
http://www.mapillary.com/map/im/wzFp1nrUKz22wq9FkD3ZGg/photo

**Comment by ToeBee** [comment]
And a third:
http://www.mapillary.com/map/im/J0P5sOHyaNZ-fB_3vlC9YA/photo

**Comment by gyllen** [comment]
We have any idea why this is happening @ybkuang ?

**Comment by ybkuang** [comment]
@gyllen I suspect something abnormal when storing the images to the bucket.

**Comment by ToeBee** [comment]
One more in a sequence I reviewed tonight:
http://www.mapillary.com/map/im/UYmoJ3w64_4jx6dHsiEfgg/photo

This one is even weirder than the others!

**Comment by paulinus** [comment]
@ybkuang All seem to be gopro images. It seems likely that the wavy warping is done when correcting the radial distortion.

**Comment by ybkuang** [comment]
@paulinus Thanks for checking. I will take a look at that soon.

**Comment by de-vries** [comment]
@ybkuang mine are actually rollei S5 images, but same problem there

**Comment by ybkuang** [comment]
@de-vries @ToeBee Yes. Given @paulinus' suggestion, it is actually related to the undistortion step for fish-eye cameras. There is probably an issue when we access the images in memory multiple times. I will look into it.

**Comment by ybkuang** [comment]
We have decided to disabled undistorting images directly. We are currently working on a way to enable undistortion in the viewer instead. Closing this.
