### ISSUE TITLE
Login with facebook doesn't work

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1801]
Login with facebook doesn't work
It just returns one to the same screen all blank, 
![y](https://cloud.githubusercontent.com/assets/1230959/14401444/f65f0844-fe45-11e5-91cb-0265efe3dde5.jpg)
with the same login button in the corner.
 Chromium
Version 49.0.2623.108 built on Debian stretch/sid, running on Debian stretch/sid

**Comment by knikel** [comment]
We have rolled out new way of logging/signing up with Facebook. Should work correctly 👍
