### ISSUE TITLE
login screen colors bad

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1802]
Very hard to read.

**Comment by jidanni** [comment]
Will attach screenshot.

**Comment by jidanni** [comment]
> ![Uploading

 Screenshot_2016-04-10-12-13-25.png…]() 

Bad contrast.

**Comment by jidanni** [comment]
![Uploading Screenshot_2016-04-10-12-13-25.png…]()
X

**Comment by jidanni** [comment]
I'll try again tomorrow

**Comment by jidanni** [comment]
![screenshot_2016-04-10-12-13-25](https://cloud.githubusercontent.com/assets/1230959/14411443/c7fc82e8-ff7a-11e5-8600-4352a1a79cc5.png)

**Comment by rsahlin** [comment]
Hi and thanks for your comment

We will be looking into the login screens on Android after Camera2 interface update.
The goal is to have uniform experience on both Android and iOS where this is relevant.
