### ISSUE TITLE
Android: stops capturing randomly 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1803]
With the newest version 1.84  my android app stops (not pauses) capturing while driving. 
GPS is via Bluetooth and very stable and precise. 
I see a white flash (like a capture)  and I have the blue button back. 
Sometimes I can capture 3 images and sometimes hundreds. 

I try get a debug log from such an event.

**Comment by HolgerJeromin** [comment]
Just a first peace of information:
when I was really quick  restarting,  the images were nearly full white. So the camera settings  were resetted in this events. 
So perhaps this will be solved with camera 2 api, too. BTW this is fairphone 2.

**Comment by rsahlin** [comment]
Hi Holger and thanks for your report

A debug log is needed for us to investigate this, please provide one if you have the opportunity.

Best regards
/Richard

**Comment by HolgerJeromin** [comment]
trace-log is here for two month: http://pastebin.ca/3481381
in this sequence the capture stopped a few times.
I can not really find something unusual exept
````
Sun Apr 10 15:25:39 MESZ 2016 : app.mapillary.android.activity.CameraActivity  - Camera: null
Sun Apr 10 15:25:39 MESZ 2016 : app.mapillary.android.activity.CameraActivity  - starting new sequence
Sun Apr 10 15:25:39 MESZ 2016 : app.mapillary.android.activity.CameraActivity  - initCamera
````

**Comment by rsahlin** [comment]
Hi Holger and thanks for the logs!

There are 2 failed captures in the attached log, I cannot detect why without looking at the full tracelog - there may be some error output from the camera.

I would like to put this issue on hold until we have released the update with support for Camera2 API.

Best regards
/Richard
