### ISSUE TITLE
'Image Not Found' in web viewer

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#1804]
Starting yesterday, and continuing today, I have been encountering the Image Not Found error in the web viewer (example below). I have found this to happen randomly in a sequence while I have been editing blurs (so blurs enabled, locked to sequence).

This doesn't happen to all images, and there seems to be no pattern to what images will error. When I click away from the error, the website dumps me on the homepage. If I go back, it reloads the image just before the error occurred.

Yesterday, this was happening in the morning (GMT-4), but those same images were working in the evening.

Here is an example which is currently not working. If locked to the sequence, the next image forward isn't working. [http://www.mapillary.com/map/im/ALV_o_qedHW1-UpVsW-AqQ/photo](url)

![screenshot from 2016-04-10 12 52 21](https://cloud.githubusercontent.com/assets/7786285/14411644/56686dee-ff1c-11e5-961b-c74df452eed8.png)

**Comment by pkoby** [comment]
Well, that example is working again...

**Comment by peterneubauer** [comment]
So, all image processing is happening asynchronous, and you might have looked while half of the images were processed...

**Comment by pkoby** [comment]
These are sequences that have been on the website for months or a year, though.
