### ISSUE TITLE
Inconsistent Login\Capitalization Methods

### ISSUE THREAD

**Issue by JeopardyTempest** [mapillary/mapillary_issues#1805]
Signed up for Mapillary using the email address option on my phone using capitalization in my email address and username (such as: MyEmail@yahoo.com ---> MyMadeupAccount).

If I logout and login again on the phone [Android v 1.84], it **does** allow me to login again with the format again of MyEmail@yahoo.com.

But on the PC, it will **not** accept the form of MyEmail@yahoo.com, instead requiring that it be all lowercase.  I see now that's how it is saved (as is the username created).

Additionally, even on the PC site, entering MyEmail@yahoo.com **is** recognized as already having an account if trying to sign up for another... and MyEmail@yahoo.com **will** work to generate password forgot\change request.

So until I finally recognized that the account signup changed my capitalization (while still allowing it's usage on the Android side), it was confusing to try to login, and get different results on PC and Android.

Suggest either
a) changing it so the android app requires all lowercase
b) all login portals automatically switch your username (visibly) to lowercase as you type it
or
c) changing to allow case sensitivity (or notifying the user explicitly that all information will be lowercase) at signup

Option c) would certainly be preferred, but perhaps it would require more effort or end up with more confusion with previous users, or conflict other settings.
At the very least, suggest the consistency across platforms, though.

Thanks!

**Comment by JeopardyTempest** [comment]
Guess this is becoming more common (https://moodle.org/mod/forum/discuss.php?d=192116 had a similar topic a couple years back).  First time I came across it.
Perhaps never noticed... if it indicated the username was the item that was wrong... or perhaps even by trial and error, except I'd already see mixed case work "properly".

**Comment by GITNE** [comment]
This is connected to #1736.

@mapillary
The local part of an email address should be kept untouched, as required by all applicable RFCs. Hence, you should not change the case even for internal processing and storage. Technically, MyEmail@yahoo.com and myemail@yahoo.com are different email addresses. It is at the sole discretion of the SMTP host to ignore case, some do others do not. So, please do not make any assumptions on the case of the local part. Process and store it with case preserved.

@JeopardyTempest
Thank you for pointing it out.

**Comment by gyllen** [comment]
To make it easy for everyone we now store everything in lowercase and also lowercase your input before its compared.
