### ISSUE TITLE
make blog.mapillary.com available over https

### ISSUE THREAD

**Issue by sslizer** [mapillary/mapillary_issues#1806]
Can you please make blog.mapillary.com available over `https`?

You have a wildcard cert for *.mapillary.com which would cover blog.mapillary.com

If would also be good to use the Mozilla ssl config generator or similar to ensure you get the strongest SSL connection to the site possible.  See https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by GITNE** [comment]
Redundant to #1172

@sslizer thank you for pointing to the Mozilla SSL config generator. It is really a very helpful tool and probably ever web admin should be using it to provide best connection layer security possible. :wink:

**Comment by gyllen** [comment]
Https is now default (and enforced)
