### ISSUE TITLE
panorama isn't displayed correctly

### ISSUE THREAD

**Issue by it4workflow** [mapillary/mapillary_issues#1808]
I've took two panoramas (one with Samsung S3Neo and one with Samsung J5) with the default camera app and uploaded it, but they aren't dispayed correctly:
https://www.mapillary.com/map/im/Q1v_6jbT4Rqh4_yqWMbnkQ
https://www.mapillary.com/map/im/7glJ5x_FlzE0ZGiHs0-36Q

**Comment by kaitu** [comment]
Here is another panorama which starts to look weird once you try to drag it:
http://www.mapillary.com/map/im/qZsQ-hLfxGFD3o8TxY8VIw

**Comment by oscarlorentzon** [comment]
@kaitu In what way do you think it looks strange? The image is not a full 180 x 360 degree panorama, it is cropped so it will not fill the sphere. Therefor you will see som black at the bottom.

**Comment by kaitu** [comment]
It looks just fine now. 

What I was consistently gettting, as soon as I start dragging, was a black background with a rotating circular image at the border, somewhat like trying to watch the image from a viewpoint at the top (or bottom?) of the sphere, or like I could only look in the direction of the top (bottom?) of the sphere. But I cannot reproduce the problem anymore.

**Comment by ybkuang** [comment]
I had similar problem as @kaitu yesterday as well. It looks ok now.  Let's keep track of this for now.

**Comment by it4workflow** [comment]
@ybkuang to bring this issue up, i looked into the exif tags, and i think this shouldn't be heavy to fix the issue: just look at the orientation exif tag and "rotate 90 cw", then width (1152px) and height (7680px) will change, too ?!

**Comment by ybkuang** [comment]
@oscarlorentzon can you help check why this panorama is rotated wrongly? https://www.mapillary.com/map/im/Q1v_6jbT4Rqh4_yqWMbnkQ. The thumbnail has correct orientation https://d1cuyjsrcm0gby.cloudfront.net/7glJ5x_FlzE0ZGiHs0-36Q/thumb-2048.jpg.

**Comment by oscarlorentzon** [comment]
@ybkuang https://www.mapillary.com/map/im/Q1v_6jbT4Rqh4_yqWMbnkQ has orientation 6 and `MapillaryJS` does not support panoramas with orientation other than 1 currently.

**Comment by it4workflow** [comment]
So you have to reject it after upload. So it's not a bug. So it's closed for me.

**Comment by oscarlorentzon** [comment]
This should be supported in `MapillaryJS`. Created an issue for it there.
