### ISSUE TITLE
camera lock on android screen lock

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1809]
When i am in camera mode and push the power button the mapillary app is still locking the camera.
I can leave the lock screen direct with the phonecall shortcut (then home and starting android camera) or direct camera shortcut from lock screen. In this case the android camera is not able to use the camera (i can even report this "problem" to google :-).

Opening mapillary and leaving camera mode frees the camera again.

That with this usage pattern the gps lock is not freed either. 
One or both of these locks drains the battery.

I am not sure if it is wise to unlock gps/camera with screen power off. Mapillary cannot guess if i will start capturing again in a few seconds (and trying to save energy) or if a put my phone in my pocket for a few hours...

**Comment by rsahlin** [comment]
Hi Holger and thanks for the report

I see the problem, I was trying to keep camera going for cases where the window is only out of focus but did not take the above usecase into accout.

/Richard

**Comment by rsahlin** [comment]
Camera now released when powerbutton pressed (since 2.11)

Verified by starting Mapillary, entering Camera - then pressing powerbutton to lock screen.
Built in camera app can now be started from lock-screen.
Verified with both legacy and camera2.

**Comment by HolgerJeromin** [comment]
I still can lock GPS with going to the lock screen. 
The app "GPS Status" can show an Icon in the notification bar when an application uses GPS.

The GPS icon is only freed with killing Mapillary. Restarting and quiting mapillary does not work here.

**Comment by rsahlin** [comment]
Ok - Could you please create a new issue that is GPS specific.

Best regards
/Richard
