### ISSUE TITLE
Very unclear if / how to unsubscribe from weekly mailing

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1810]
User receives email:
Subject: Weekly highlights from Mapillary

User clicks Unsubscribe which doesn't actually unsubscribe but brings
him to http://www.mapillary.com/map/settings/notifications

User sees
[*] Weekly summary
Get a weekly summary every week of your Mapillary activity

User looks for other items with the word weekly, but there are none.

User thinks "My Mapillary activity? But I had no Mapillary activity. And
the mail says {We found some nice street photos for you. Take a look at
this week’s highlights... Mapillary sends out highlight emails like
this to help you keep up with the mapping community.} Doesn't sound like
the same item to me!" But unchecks it anyway...

Also he thinks "but then what about the promised "weekly summary of MY activity"?

**Comment by sandrauddback** [comment]
Thanks for input @jidanni (and sorry for late reply). 

We agree with you. There are a lot improvements to make. We will rather soon fix the notifications and make those improvements. Thanks!
