### ISSUE TITLE
separate website issues from app issues

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1811]
You should have two
website_issues
app_issues
or even divide the latter and offer
ios_issues
android_issues

Compare https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by jesolem** [comment]
Thanks for the feedback @jidanni , always appreciated. 

We prefer to have one place to track things. There are labels for `android`, `iOS`, etc. Feel free to use these.

**Comment by jidanni** [comment]
i don't think regular users can add labels, at least not from this bug page.

Despite
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
I don't think regular users can change labels at all. So that page needs to mention that fact.

**Comment by jidanni** [comment]
And indeed... http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner

**Comment by jidanni** [comment]
OK I submitted https://github.com/isaacs/github/issues/148#issuecomment-209349116
