### ISSUE TITLE
ensure that User and Guide appear on the same line

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1812]
Please ensure that User and Guide appear on the same line.
![screenshot_2016-04-11-14-16-50](https://cloud.githubusercontent.com/assets/1230959/14452418/1384f578-00c1-11e6-8f2b-d2c3665816b5.png)
The combination is shorter than some of the other lines, but alas they are still split, looking like two different items.

**Comment by jidanni** [comment]
Same with Open
Positions.

**Comment by knikel** [comment]
The footer got an overall redesign.
