### ISSUE TITLE
{{...}} ends up getting shown raw directly to the user

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1813]
Please ensure that the {{footer}} thing does not end up being shown to the user.
![screenshot_2016-04-11-14-14-05](https://cloud.githubusercontent.com/assets/1230959/14452564/094d16f2-00c2-11e6-81ff-0cc9f488b79f.png)

**Comment by jidanni** [comment]
Here we observe another,
![screenshot_2016-04-11-14-23-14](https://cloud.githubusercontent.com/assets/1230959/14452918/504ab33c-00c4-11e6-8ae6-6678fb52eb1d.png)

**Comment by knikel** [comment]
Hi @jidanni what phone are you using? Is it a native android browser? Does the same thing happen in mobile version of Chrome browser?

**Comment by jidanni** [comment]
VITA DOUBLE II Android 4.0.4 native Android browser. Cannot install
Chrome browser else phone grinds to a halt.

**Comment by jidanni** [comment]
You really can't blame the browser.

Whatever you are doing, you expect to cover it up with CSS?

Well text browsers won't have any of this nonsense.

$ w3m -dump https://www.mapillary.com/using | head -n 3
{{setStatic()}}

The Mapillary App
$ w3m -dump http://mapillary.com/instructions.html | head -n 3
{{setStatic()}}

Capture Instructions

And now you see it even is polluting Google!
https://www.google.com/search?q=setStatic+site:mapillary.com

**Comment by nighto** [comment]
Well, this is how AngularJS render text. Although mly guys could change all `{{literals}}` for `<span ng-model="literals"/>`.

**Comment by jidanni** [comment]
Sounds good.

**Comment by HolgerJeromin** [comment]
Changing the encoding would not solve the problem that some browsers do not work with angular.

**Comment by jidanni** [comment]
Well just like HTML has SCRIPT and NOSCRIPT tags, one should be prepared
for both cases to avoid a product looking bad on one.

**Comment by knikel** [comment]
We're using different technology for the web app and this is no longer an issue. The web app might not work on legacy Android Browsers.

**Comment by nighto** [comment]
Cool. As of curiosity, what are you using to render the frontend?

**Comment by knikel** [comment]
@nighto Sure, we're all in Angular 2. The new way they handle components and their lifecycle is pretty nice. Much simpler and nicer than ng1.

**Comment by nighto** [comment]
@knikel nice, I'll take a read on frontend source code. Thanks!
