### ISSUE TITLE
Camera screen: most words could be moved off the image into the empty right sidebar areas

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#1814]
1. To avoid white characters ending up directly on a white background,
you need to add black edges to them. Same idea for green or green.

2. Actually most of the words on the screen could be moved into the
right sidebar where there is plenty of empty black area around the
circular button.

3. The faint buttons at top are too faint.

4. Most of the functionality of the buttons is a mystery with no help
available on this screen. OK, settings wrench is obvious.

![screenshot_2016-04-11-23-08-47](https://cloud.githubusercontent.com/assets/1230959/14453184/d17b8246-00c5-11e6-8da5-9bdb7a502bba.png)

**Comment by rsahlin** [comment]
Hi and thanks for your comments

We are looking into the design and layout of both the Android and iOS app to make sure they are super easy and fun to use :-)
Thanks!

/Richard

**Comment by angelday** [comment]
It will take some time until we roll out the new version, but thanks for your comments @jidanni, noted (especially with regards on No. 4 which is one of my issues as well).

Closing the issue.

**Comment by jidanni** [comment]
Thanks, but as my phone's compass doesn't work, I will try mapillary
again when maybe I get a new phone one day.
