### ISSUE TITLE
Map link to a specific area redirects back into Europe

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1818]
When scrolling around in the Mapillary map, the URL updates its coordinates to match the area I'm looking at. However, if I copy that link and paste it, a second later I'm redirected back into the default coordinates, corresponding to Europe. This makes it impossible to share a link to a specific area.

For example, [this link should take me to Ecuador](https://www.mapillary.com/map/search/-5.013975021/1.665833354/-92.011558533/-75.188793945), but it jumps back into [Europe](https://www.mapillary.com/map/search/21.597473907223446/56.596574078763155/-44.096751166680264/75.96184258331792).

**Comment by knikel** [comment]
We do better job with map behaviour and overall state where some is within the app 👍 .
