### ISSUE TITLE
Login fails: "Wallet garden connection detected"?

### ISSUE THREAD

**Issue by blobgo** [mapillary/mapillary_issues#1819]
What does this error message mean?

"Wallet garden" is a synonym for [Closed platform](https://en.wikipedia.org/wiki/Closed_platform), but I have no idea what this has to do with Mapillary.

**Comment by jesolem** [comment]
@blobgo I think this is @peterneubauer 's way of saying that the app detected a "capture portal" meaning that you are connected to WiFi but cannot access Mapillary's services. If yes, then we should change the wording ;)

**Comment by blobgo** [comment]
Indeed it looks like it was, because I just had messed up with some permissions, so the app could not connect to the internet.
Basically this is just a connection issue - but no wallet garden. And of course such connection issues can have multiple reasons - not only bad wifis. In any case this has not much to do with wallet gardens...

**Comment by peterneubauer** [comment]
Sorry, it should be Walled Garden. Is there a better way to phrase it?

**Comment by jesolem** [comment]
It is called "capture portal".

**Comment by blobgo** [comment]
Yes, it is "capture portal". Wallet Garden is u[another thing](https://en.wikipedia.org/wiki/Closed_platform) (already linked above).

But as I said the error message "This is Capture Portal/Wallet Garden!" does not make sense. The issue are just connection issues and they can have multiple reasons.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
