### ISSUE TITLE
Work with XMP sidecar files

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#182]
Import e export.

Ref.:
- http://geotag.sourceforge.net/XMP/
- http://www.adobe.com/products/xmp/

**Comment by gyllen** [comment]
Do you want to export XMP files? Sorry for late answer.

**Comment by alexandre-mbm** [comment]
No. Sorry. But importation by XMP would be "convenient". 
This is very accessory. You can close the issue.
