### ISSUE TITLE
Position in list lost on change orientation

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#1820]
Position lost when viewing list of sequences and inside the sequence if rotate phone portrait-landscape or back.
Inside sequence no scrollers or position indocator at all - it makes returning back to position long and hard work.

**Comment by rsahlin** [comment]
Hi @iav 

I am contemplating 'fixing' this by locking the orientation of the review activity to portrait - what do you think?

Best regards
/Richard

**Comment by iav** [comment]
It will be a little too much: u usr landscape view during review photos, because photos made in landscape mode, and takes enough screen space in that mode.

Maybe, you can add a checkbox "sequence ready for upload" to upper right menu when see a list of photos inside sequence?

-----Original Message-----

**Comment by rsahlin** [comment]
Please re-test with version 3.x
This has an all new UI.

Best regards
/Richard
