### ISSUE TITLE
iOS app: turn GPS off when not necessary

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1821]
Currently the iOS app seems to keep location services enabled all the time while the app is running. This includes while the app is left open for a long time uploading photos, where it's certainly not necessary for the app to know where I am, let alone at the high precision used while taking photos. It can contribute to using more battery than necessary.

Location services should only be enabled while taking photos, or while the map is visible.

**Comment by millenbop** [comment]
Gone through the code now and it was started but not stopped in the big map view (second tab). Fixed now so that when view disappears, the location is stopped. Available in the next release.
