### ISSUE TITLE
iOS app: don't keep screen on when not necessary

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1822]
Currently the iOS Mapillary app keeps the phone awake and the screen on at all times. This is important while taking photos and while uploading, but in all other views the phone should suspend as normal to conserve battery.

I once started uploading and went to sleep, and when I woke up the upload had finished hours ago, but the screen was still on. This shouldn't happen...

**Comment by millenbop** [comment]
Thanks for reporting. I agree, and it has now been implemented. Will be out in 4.3.1.
