### ISSUE TITLE
Web editor “Flag” / API “complain” always returns 404 Not Found

### ISSUE THREAD

**Issue by BrianNixon** [mapillary/mapillary_issues#1824]
Attempting to flag an image in the Web editor with the “Flag” button, or from my own app using the “[complain](https://a.mapillary.com/#post-imkeycomplain)” API, always seems to result in a 404 Not Found response from the server.

Edited to clarify: the OPTIONS request comes back with 200 OK; it’s the subsequent POST that returns 404 Not Found.

**Comment by gyllen** [comment]
This is now fixed (since long)
