### ISSUE TITLE
Server does not sanity check sequence boundary

### ISSUE THREAD

**Issue by BrianNixon** [mapillary/mapillary_issues#1825]
It would perhaps be sensible for the server to sanity check the lat/lon of images in a sequence to ensure that they all lie within a reasonably-sized area, and automatically reject (or cut at) outliers.

For instance, sequence *DVYgbR4J7qrL0xW2JBBQqA* should be entirely within Fukushima Prefecture in Japan, but a single image [*l1qibvx5W_3vtWuSLlhcZA*](http://www.mapillary.com/map/e/l1qibvx5W_3vtWuSLlhcZA) tagged with lat/lon off the West coast of India leads to an enormous bounding box, causing the sequence erroneously to appear in search results for locations nowhere near Japan.

**Comment by jesolem** [comment]
Is this a new upload? We run sequence cutting to fix these errors every few hours or so.

**Comment by BrianNixon** [comment]
Yes, it’s from yesterday (2016‑04‑24).
If it’s just a matter of time until the server sorts it out automatically, I guess there’s no real issue and this can be closed.
On the other hand, would it not be better to do the checking/​cutting *before* publishing?

**Comment by jesolem** [comment]
The reason we wait is we don't know when the sequence upload is done since the images can come in in any order in multiple batches. So we wait a bit. There is room for improvement though.

**Comment by ybkuang** [comment]
@BrianNixon Just some additional info. We did a check for all sequences that are at least two days old (just to make sure that the sequence has been uploaded completely). If a cut is needed, it will be performed on the sequence.

**Comment by ybkuang** [comment]
The sequence has been cut after the regular scheduling. Closing this.

**Comment by BrianNixon** [comment]
This appears still to be a problem even with old sequences. Two examples I’ve stumbled across recently:
* Sequence *-NwQGPGTZmdH3P7QPNx4Jw* from 2016‑07‑18 has points in British Columbia and Ohio.
* Sequence *ezm_6WGae--u_zxWtpCgDA* from 2015‑05‑24 has points in Kazakhstan and Korea.

In each case the bounding box spans half a continent.

**Comment by ybkuang** [comment]
@BrianNixon Thanks for reporting. We will do a full rerun later this week to ensure everything is processed properly.

**Comment by BrianNixon** [comment]
It gets better(!): a search in Brazil just returned sequence *4cb8a97f-969d-4394-95ba-3f6f481352cc* (first I’ve ever seen with a 36-character hex key rather than 22-character ASCII) which contains images from two different users in Brazil and Cameroon, spanning the South Atlantic Ocean.

**Comment by ybkuang** [comment]
@peterneubauer can you help look into this?
