### ISSUE TITLE
(NaN% uploaded)

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1826]
Lately, I get this message as a manual upload draws to a close. I cannot tell if it is complete or not.
![2016-04-25 11_38_48-mapillary _ manual upload](https://cloud.githubusercontent.com/assets/1827881/14789414/6031e9e4-0ada-11e6-9a4a-7ad733e998df.png)

**Comment by gyllen** [comment]
@tallguy is this for a large amount of images?

**Comment by talllguy** [comment]
Yes, if I check the status of the upload on another tab, it never advances once this is displayed

**Comment by talllguy** [comment]
This could have been network related, because the same batch is working now.

**Comment by gyllen** [comment]
Strange Im gonna close this though, we are reworking uploader. Reopen if you see the same issue again.
