### ISSUE TITLE
Add option to lock screen / disable soft buttons while shooting 

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1827]
Last week I went to the beach shooting some pictures and a dozen times some splashed water triggered the buttons on the screen, such as back, home and change apps. It'd be interesting to, if possible, have an option to lock these buttons, only being released if user touched a hardware button, like volume or power.

**Comment by rsahlin** [comment]
Hello @nighto and thanks for the suggestion!

Yes, this is definately an interesting option - The Beach or Skiing option :-)

Best regards
/Richard
