### ISSUE TITLE
OpenStreetMap's "source" tag

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#183]
See the «["source" para Mapillary](http://forum.openstreetmap.org/viewtopic.php?id=26085)» topic at OpenStreetMap Forum ([in **English** from Google Translate](https://translate.google.com/translate?sl=pt&tl=en&js=y&prev=_t&hl=pt-BR&ie=UTF-8&u=http%3A%2F%2Fforum.openstreetmap.org%2Fviewtopic.php%3Fid%3D26085&edit-text=&act=url)).

Related issues: #6 and #97.

**Comment by gyllen** [comment]
Closing since not really a mapillary issue

**Comment by alexandre-mbm** [comment]
OK. I wanted to stimulate you send/suggest that demand for the project OpenStreetMap.
