### ISSUE TITLE
Default thumbnail image has the wrong height

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1830]
android sequence review:
The default thumbnail view which is replaced by the thumbnail has the wrong height. 
So when it is replaced by the real thumbnail all other thumbs are moving.

**Comment by rsahlin** [comment]
Hi Holger and thanks for your report.

The thumbnail creation and review picture browsing will be looked into. 
It is not working as expected now.

Best regards
/Richard
