### ISSUE TITLE
pictures taken in 2011 do not appear

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#1832]
I took the pictures in 2011 of shops with a SONY DSC-HX5V and I located the pictures with Geosetter. Once I manually pushed these photos into Mapillary, these do not appear.
Here are the URL
http://www.mapillary.com/map/s/rxF0RK6x4rq-4Jdu5qbv6w
http://www.mapillary.com/map/s/1ph27MnQShFCwCO8EXhofQ
http://www.mapillary.com/map/s/SHtrzKEw8YVnv5SgSfIYqA
http://www.mapillary.com/map/s/rs2kHY5lrEzO7osZEhvYfQ
http://www.mapillary.com/map/s/jyVj-pjpmZEZg7RPp2BMGw
http://www.mapillary.com/map/s/VOEZFhuPih0U5-NBKm5kYw
http://www.mapillary.com/map/s/Itdx-ZuzD18lJI0yogQ0jQ

**Comment by ybkuang** [comment]
@JLZIMMERMANN They should be good now.

**Comment by ybkuang** [comment]
The images look god now. Closing this. @JLZIMMERMANN let me know if you find more missing images.
