### ISSUE TITLE
wrong date to 2 pictures of antical theater in ORANGE

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#1833]
This Picture should be in 100 after JC http://www.mapillary.com/map/im/-DwhHPmp-bh2GzMRzjCRRg/photo

This one should be in 1800  http://www.mapillary.com/map/im/LY2yu-QPUpifgiiPjRxFvw/photo

Both may have 1st july at 4pm

**Comment by ybkuang** [comment]
@JLZIMMERMANN I took a look with the two images. It is true that the GPS TimeStamp is with the right dates. When we extract the date time for an image, we check a list of EXIF fields for timestamps in order. If multiple time fields exist, we take the first on the list. Specifically, for these two images, both `EXIF Date/Time Original` and `GPS TimeStamp` are in the EXIF. However, `EXIF Date/Time Original` is before `GPS TimeStamp` on the checklist. So we use the `EXIF Date/Time Original` instead in this case. 

There is no good way to tell which field contains the TRUE timestamp by looking at the EXIF alone. This is the tradeoff we made with an ordered list. I can manually correct the dates for those two image for you. But in the future, it will be great if you can add the date to `EXIF Date/Time Original`. Sorry about the inconvenience.

**Comment by ybkuang** [comment]
@JLZIMMERMANN will it be possible for you to modified the timestamps and upload again?

**Comment by ybkuang** [comment]
@JLZIMMERMANN It is difficult for us (in the backend) to choose the perfered datetime from multiple fields in exif without additional information. I will close this for now.
