### ISSUE TITLE
Email notifications still say "Copyright 2015"

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1834]
I just got an email notifying me of approved blur requests, and I noticed the footer still says "© 2015 Mapillary". This should be updated to 2016, or made automatic.

I didn't check if other types of email notifications have the same problem. I did check the newsletter, and that one is okay ("Copyright © 2016 Mapillary AB").

**Comment by nicolas17** [comment]
Bump. 40% of the year 2016 has passed and emails still say 2015. :wink:

**Comment by knikel** [comment]
😅 fixed!
