### ISSUE TITLE
Disable shutter sound, doesn't

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1835]
Toggling the Make Shutter Sound on or off doesn't disable it. Used to work in the 1.x Mapillary releases.

Samsung Galaxy S4, Android 4.1.something, Capillary 2.05.

The text w8th the setting seems to imply that you need Android 4.2 or higher to *make* the shutter sound.

**Comment by rsahlin** [comment]
Thanks for reporting - I will look into this issue.

/Richard

**Comment by polarbearing** [comment]
If I remember correctly, the option has been changed from a negative (suppress sound) into a positive, but the relation to the Android version has not been updated. Related to #463, #1727, #1488.

**Comment by jfburke3** [comment]
Aha, that explains my confusion.

**Comment by filipca** [comment]
I am glad they took my advice on negative and double negative sentences :)
Samsung GS6  v 5.0 with v 2.08 = NO shutter sound in both cases
Samsung GS7  v 6.01 with v 2.09 = shutter sound in both cases, I have to use the phone settings to turn it off.

**Comment by ovivoda** [comment]
http://android-releases.mapillary.io/Mapillary_Android_v3.96-SNAPSHOT1.apk should solve the issue. @jfburke3 @filipca Please let me know if this setting works for you now.
