### ISSUE TITLE
Sequence boundary values returned as arrays instead of scalars

### ISSUE THREAD

**Issue by BrianNixon** [mapillary/mapillary_issues#1837]
The `boundary` object returned as part of a sequence query contains four values `min_lat`, `min_lon`, `max_lat` and `max_lon`. Normally these are floating-point scalars but I have encountered one instance in which they are arrays, which is unexpected (and makes no sense).

https://a.mapillary.com/v2/s/HzjrnKB4pHYV9VY1A28qqw gives

``` json
"boundary":{
  "min_lat":[-7.27678,54.2292992],
  "min_lon":[-7.2768696,54.2292992],
  "max_lat":[-7.27678,54.2292992],
  "max_lon":[-7.2768696,54.2292992]
}
```

This is the only sequence I’ve seen that exhibits this problem, but maybe there’s a bug that could allow this to creep in elsewhere too?

**Comment by gyllen** [comment]
`v2` is no longer an active version of the API
