### ISSUE TITLE
Lost access

### ISSUE THREAD

**Issue by narguedasn** [mapillary/mapillary_issues#1841]
Program is installed and recognizes me but if trying to open it it goes back to my home screen. This from the shortcut or through the Mapillary site

**Comment by gyllen** [comment]
@narguedasn Can you provide us with a more detailed description of what happens?

**Comment by narguedasn** [comment]
Hello Johan, thanks for getting back to me. There is little else I can say. It appears installed, version 2.2 (51), the same I initially installed 2 years ago.
Case 1: I use the shortcut on my desktop. The screen goes black for a sec, then back to the desktop view where I can see the icon for the shortcut
Case 2: I go to the Mapillary website. It tells me I have version AB installed. I hit open, it goes black and the back to desktop view.
:(
Nidia = Cocusnucifera 

________________________________

**Comment by gyllen** [comment]
Is this the android or iOS app?

**Comment by narguedasn** [comment]
It's an iOS app. I just downloaded v 4.3.0 (102) to my iPhone (iOS). It works fine. Maybe the version in mybad is too old?

  Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com

________________________________

**Comment by gyllen** [comment]
Awesome forwarding this to @millenbop

**Comment by millenbop** [comment]
Hi!

Sorry I'm a bit confused :) Is the latest version working for you? If not, please delete the app and download/install it again. Perhaps the upgrade from your two year-old version wasn't successful.

**Comment by narguedasn** [comment]
I'll try that, thanks

  Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com

________________________________

**Comment by millenbop** [comment]
Did it work by removing and installing the app again?

**Comment by narguedasn** [comment]
No, it did not

Maybe the problem arises from the iPad version I have: it is 8.0 (12A365) and I cannot upgrade to 9. because it will break other apps. Though before reinstalling Mapillary I did have the older one that I installed 2+ years ago -it was not working.

Also, the new download is working well in my iPhone (Version 7.1.2 (11D257) which is older than my iPad.

So I don't know if it is a iPad problem or a Mapillary problem

N


[http://sig.cmparks.net/cmp-ms-90x122.png] Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com<http://www.clemetparks.com>



________________________________

**Comment by millenbop** [comment]
I'll see if I can find and older iPad with an older iOS version and try it on that.

**Comment by millenbop** [comment]
Also, if you just downloaded the new app before deleting the old, please give that a go as well.

**Comment by millenbop** [comment]
Closing this now, please reply if you still have problems and I'll reopen! Thanks!
