### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by narguedasn** [mapillary/mapillary_issues#1842]

**Comment by gyllen** [comment]
Is this the same as  #1841

**Comment by gyllen** [comment]
Im closing this since no answer Im assuming same as #1841

**Comment by narguedasn** [comment]
I'm sorry! I did not realize two different people were working on my comment.

In fact, I have not been able to switch versions in my iPad. I did try but the new version does not seem to work either. I have been using my iPhone which only has the new version - never the older one.

What do you think the problem could be? All my other software works fine

Nidia

[http://sig.cmparks.net/cmp-ms-90x122.png] Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com<http://www.clemetparks.com>



________________________________

**Comment by gyllen** [comment]
@millenbop This is same issue as #1841
