### ISSUE TITLE
Differentiate conditional turn restriction versus regular turn restriction

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#1843]
Related to street sign detection of turn restrictions, see discussion here: https://github.com/mapbox/mapping/issues/177

**Comment by jesolem** [comment]
Thanks for the input @maning

In most cases this will be very difficult. It requires context and sometimes local knowledge to understand if the wording next to the sign implies conditional. We could add a "with text" class in the future to indicate that there might be conditions.

**Comment by maning** [comment]
> "with text" class in the future to indicate that there might be conditions. 

@jesolem :+1: or at least unblur :).  We see some conditional turn restrictions signs that were blurred.

**Comment by planemad** [comment]
Another case: restriction for only trucks.

![](https://cloud.githubusercontent.com/assets/1933377/15042736/2604e426-12e4-11e6-840e-d3cbb831fc32.png)

**Comment by nicolas17** [comment]
I agree this is very difficult to detect automatically by software, but it would be useful to have the separate sign types for when people add or change the traffic sign info manually.

**Comment by jesolem** [comment]
We might be able to OCR the text too and make that searchable too but that is a bit out in the future. Still relevant for many sign classes in the US where there often is text.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
