### ISSUE TITLE
Garmin Virb XE connected to iPhone/app

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1844]
A few questions about connectiong a Garmin Virb XE to iPhone.

1. Will the Garmin Virb GPS data be used or the iPhones? The iPhone/Mapillary GPS solution is simply no good.

2. Can the pictures be transfered to the iPhone in batches or does it have to be all at once? Aka do I need to buy the most expensive iPhone or will one with less storage space do?

3. About using an connecting several Garmin Virbs. I says that in the blog post that it is uploaded as separate sequences. But will it still sync in anyway to create smooth 360 view (or 270 with two cameras?) or will it just be two sequences that are close to each other?

**Comment by millenbop** [comment]
1. It should use the GPS of the Virbs, but I'll have to verify.

2. It can be transferred in batches. Just sync, upload, sync, upload. We are working on a new better solution though!

3. It will not be a smooth 360 "sphere" as if it was taken with a real 360-camera, no, and you can't look around with your mouse but have to use the buttons. But you will get all 360 degrees covered. If the cameras are located pretty close to each other, you can rotate around though, and you will get animations and transitions.<br>
Here's an example from my testing with one forward and one to the right: http://www.mapillary.com/map/im/GA1gAfpObTtYYPGM5B9Bbw/photo<br>
Please ignore the compass angle as it was a bug I fixed afterwards. But you can turn to the right to see what I mean.<br>
I hope this clarifies things a little bit!

**Comment by Andblue** [comment]
Thanks!

By the way, are you using a Virb?

1. I noticed that you have taken pictures against the sun and it looks just fine. Big difference to using a iPhone I have to say.

2. Is it just me, or do the pictures bend a bit?

**Comment by gyllen** [comment]
@paulinus Should be able to answer why they are bent.

**Comment by millenbop** [comment]
1. I use GoPro's, Virbs and iPhone 6 :)

**Comment by paulinus** [comment]
2. Action cameras in general produce images with a strong radial distortion. Straight lines are bent on the image.

Some cameras, like the Virb, offer the possibility of unbending the images on the camera, but we do not recommend using that option. It is easier for us to work with the unmodified image.

The plan is to unbend the images on the fly on the viewer. So don't worry if images are bent today, they can still be displayed unbent in the future.

**Comment by millenbop** [comment]
I hope this answers your questions, so closing this.

**Comment by richlv** [comment]
@paulinus, you said :
"Some cameras, like the Virb, offer the possibility of unbending the images on the camera, but we do not recommend using that option. It is easier for us to work with the unmodified image."

https://github.com/mapillary/UserGuide/wiki/Equipment says :
"Turn on automatic straightening so you get less "fisheye effect"."

which is the suggested method currently ?

**Comment by millenbop** [comment]
That page is seriously outdated. We should update it or get rid of it since we now have https://help.mapillary.com

What @paulinus said is correct, let us do the image correction.

Pinging @katrinhumal

**Comment by katrinhumal** [comment]
@millenbop good point, I will see to it!
