### ISSUE TITLE
Andoid app 2.05 does not upload anymore automatic

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1846]
Hi

Just fetched android 2.05 and made a few sequences. Upload does not work anymore automaticly. Also the menu option "start upload now" does not work as expected.
I needed to go into preview pane and wait until it has loaded and afterwards selected all tracks and click on upload.
Also the notification Icon of mapillary while uploading flashes a lot (IMHO it vanished after successfull upload and reappears while a new picture is uploaded...).

AND: the new frequency devider with 1/10 sec is OK, but you did not adopt the values. Instead of 1 per second my mobile tried 10 per second now, unexpectedly^^ Sure, it has not done so much, I needed to adopt the value now.

echelon

**Comment by rsahlin** [comment]
Hi @echeloni2p and thanks for your issue report

I will look into these issues and provide a fix.

Best regards
/Richard

**Comment by polarbearing** [comment]
I confirm that the app reads my old setting of "2 sec" now as "2/10 sec" from the preferences saved by the previous version. The annotation in tenths of seconds is also confusing, it would be better to use a decimal annotation, e.g. 2.1 sec for 21/10.

**Comment by rsahlin** [comment]
Hi @polarbearing  and thanks for your comment

Yes, this is not fully implemented yet
I am thinking of keeping the delay for legacy mode and have it automatic in Camera2, anyway it should convert old value correctly.
Using 1/10th of second as a measure is purely a quick fix since we do not have a decimal slider.

Best regards
/Richard

**Comment by polarbearing** [comment]
In general, I don't understand the hype for sliders (or rolling wheels in my alarm clock). I'm usually faster typing two digits than fiddling a slider or wheel to the desired value.

**Comment by HolgerJeromin** [comment]
My update  converted 1 sec to 1/10 seconds, too.

**Comment by rsahlin** [comment]
Automatic upload in background option 'Upload pictures in background' is turned off by default.
To enable go into 'Settings' and check 'Upload pictures in background'
