### ISSUE TITLE
"Lost connection to camera" while shooting sequences

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1847]
Got that message when I was starting a new sequence while I was driving. I tried other camera apps, all of which could access the camera, but Mapillary was unable to until I rebooted. 

Mapillary version 2.08, Samsung Galaxy S7, Android 6.0.1.

I didn't have trace logs enabled at the time. I'll email the logs I have.

**Comment by rsahlin** [comment]
Hi @jfburke3  and thanks - the logs would be very helpful :-)

Was it using Legacy or Camera2 API?

Best regards
/Richard

**Comment by jfburke3** [comment]
Yep, I enabled the trace logs after that happened, so if it happens again, I'll have them.

Using Camera2 API.  (Which seems to be working really well, by the way.)
