### ISSUE TITLE
Image direction set to 0 degrees

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1849]
With release 2.08 (Samsung Galaxy S7, Android 6.0.1), the direction of all of my uploaded images is 0 degrees, not facing in the direction I'm driving.  "Lock direction forward in driving/biking mode" is enabled.

Pretty sure it was working right in 2.05 (although I'd have to find an uploaded sequence from that release to be completely sure).

**Comment by jfburke3** [comment]
Slight correction:  *all* of my images seem to be set to 0 degrees now, not just the new ones.  Seems to be a web or db problem?

**Comment by gyllen** [comment]
@rsahlin Can we investigate if this is an Android issue?

**Comment by rsahlin** [comment]
Yes - there is an issue with Android app version 2.X that will set compass direction to 0 if 'Lock direction to forward in driving/biking mode' is enabled.

I have fixed this and a new beta is coming very soon.
