### ISSUE TITLE
Removing this sequence

### ISSUE THREAD

**Issue by shravan91** [mapillary/mapillary_issues#1850]
I think this sequence should be removed : https://www.mapillary.com/map/im/vDCLqrF_mg_iSfsuYteZWg/photo

**Comment by shravan91** [comment]
@peterneubauer @jesolem - I am not sure whom should I assign this too

**Comment by peterneubauer** [comment]
@gyllen will remove it.

**Comment by gyllen** [comment]
@jesolem Thoughts on this sequence?

**Comment by jesolem** [comment]
Yeah. Go ahead and delete.

**Comment by jesolem** [comment]
@gyllen or @peterneubauer please delete.

**Comment by peterneubauer** [comment]
I commented and notified the author of this ... https://www.mapillary.com/map/im/vDCLqrF_mg_iSfsuYteZWg/photo

**Comment by nicolas17** [comment]
The link gives "image not found" now. Should this ticket be closed?

**Comment by shlublu** [comment]
Just curious. What what that? Some kind of vandalism?
