### ISSUE TITLE
Hidden pictures

### ISSUE THREAD

**Issue by iagsav** [mapillary/mapillary_issues#1851]
I took sequence of the pictures, and one of them:
https://www.mapillary.com/map/im/CanbziQtvSdEphev1pgDtA/photo
https://www.mapillary.com/map/im/Gde8eJ0q6Fvb3deyXO7M4Q/photo
... and other photos
but I can't find it as green line at mapillary site

I manually pushed these photos into Mapillary using python script

**Comment by gyllen** [comment]
We are perfoming some upgrades to the `green line layer` at the moment. Check back in a couple of days.

**Comment by iagsav** [comment]
Hello! I can't see this pictures on "green line layer" and can't load this pictures using JOSM

**Comment by gyllen** [comment]
@iagsav Can you explain a little more exactly where you have this problem?

**Comment by iagsav** [comment]
1. I record images using Android app
2. I load images to your service using Python script
3. but I can't see green line for this images, but I can see this images when I click at road.
4. Also I can't load this images to JOSM

**Comment by iagsav** [comment]
Hello! 
Can you help me?

**Comment by gyllen** [comment]
@iagsav What date did you upload these images?

**Comment by iagsav** [comment]
I uploaded these images between 3 and 7 May

**Comment by iagsav** [comment]
More exactly: between 8 and 10 May: I see logs in Android Mapillary

**Comment by gyllen** [comment]
This is fixed since a long time ago (we even have a new interface now :) )
