### ISSUE TITLE
Removing this sentence

### ISSUE THREAD

**Issue by sznik** [mapillary/mapillary_issues#1852]
Remove this my sentence [http://www.mapillary.com/map/im/gP_VLMDYma5m0sIHFtGa_Q/photo](http://www.mapillary.com/map/im/gP_VLMDYma5m0sIHFtGa_Q/photo)
On this image is roundabout, which is 800m before!!.
Something wrong happened during video upload. It seems that the beginning of the GPX file is not recognized (the gap on the map before this sequence).

**Comment by peterneubauer** [comment]
Deleted. Thanks!
