### ISSUE TITLE
no more 20MP on HOnor 7 android app

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1853]
Hi!

With the new camera API in Android APP the good, high res modes are gone, my Honor 7 can only do max 8 MP pictures, with 2.09 it only das 2 MP pictures.
A year ago we did a longer debug session to add a little fuzzy to the 4:3 ratio image size selection to accept images with higher resolutions, if those are not really strict 4:3.
Max is 5152x3888, but mapillary 2.08 choosed 3264x2448 :-(
Mapillary 2.09 chooses even less, 1920x1080 :-(

I could have done a lot of good high res pictures from rare taken tracks today, but too bad...

Tracelog. https://helene.cgv.tugraz.at/owncloud/index.php/s/NyudjBWqtbdQyoJ

echelon

**Comment by rsahlin** [comment]
Hi @echeloni2p and sorry for the nasty bug.

As mentioned in conversation we will limit the highest picture size to 8MP, in this case there is a bug in the program that makes it only look picture sizes with same aspect as screen - regardless of size.
In this case the app finds a widescreen size - but does not check how small it is.
I am working on a fix and will push out asap - the result will be a picture size around 8MP.

Best regards
/Richard

**Comment by echeloni2p** [comment]
HI

so regardless of what smarphone I use, the max will be only 8 MP maximum?

echelon

**Comment by rsahlin** [comment]
Hi

From a backend perspective, filesize and bandwidth, it is best for us to limit sizes to around 8MP.
This is regardless of your device.

Best regards
/Richard

**Comment by kaitu** [comment]
I understand Mapillary perspective. But, whether intended or not, limiting the highest picture size will also impair collateral uses of pictures taken with the app. For example, if I want to use the pictures also for mapping tiny details, I'm interested in saving a local copy offering the best available resolution allowed by the device. 
Couldn't you just to allow to take pictures at maximum resolution, and downsize only at upload/storage time at Mapillary?

**Comment by rsahlin** [comment]
I propose that we add an option for choosing highest resolution picture.

I will add it to the next version out to Beta group.
What do you think of calling it 'Enable highest resolution pictures'?

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi!

So I just need another app and manual upload the 20MP pictures to mapillary to get around the 8MP limit?
Sure, I do know your view, but it is a bit limited, now that I extra got my honor7 for mapillary use, after a long lookout...
Although, modern mobiles get back to 12 or 16 MP max pictures.

echelon

**Comment by jesolem** [comment]
@echeloni2p What @rsahlin meant was that you will be able to take full resolution with the Mapillary app with the added setting. 

Reason is that we get complaints that people cannot take enough photos on their device. Now you can decide yourself. Hope that solves your problem.

**Comment by kaitu** [comment]
@rsahlin the 'Take high resolution pictures' mode sounds good to me, and would solve the problem. The adjective "high" is somewhat ambiguous though, you might use something "maximum" or "highest" instead.

I would rate the app more flexible, and more straightforward as well, if it offered a list of supported resolutions (aside to a clear indication of expected file size) to choose from. I'm thinking of a device dependent list, like in the focus mode setting. Practically, it's same to me, as I always select the maximum resolution anyhow.

**Comment by rsahlin** [comment]
Hi @kaitu and thanks for your comment.

We will consider letting users choose resolution from list.
As it is now the two options Take lowres and Take highres clash with eachother, they should really be grouped as exclusive to eachother.

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi

Ok, it sounded a bit like mapillary only accepts 8 MP Pictures from now on (on the Website). I am with you on the slow mobile phones and the wish for faster sequences.
But this does somehow conflicts with the Need for a secure mobile phone, done with encryption.
I would suggest a designated mobile for mapillary use in this case, like I do it.
Also the 8 MP as default is ok, the high and low selections are fine, too.

I can do 20 MP  again now in 1 sec Frames, thats great. Thank you.

I do call this ticket fixed.

echelon
