### ISSUE TITLE
Camera "crash" when not taking pics, switching away, then back

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1854]
I don't know if this is related to my earlier #1847 issue or not, so I'm reporting it separately and y'all can make the call.

Mapillary v2.09, Samsung Galaxy S7, Android 6.0.1

When I've _stopped_ shooting a sequence, but still with the Mapillary camera up, I switch to another app (doesn't seem to matter which one, OsmAnd, Facebook, etc.), then back to Mapillary.  Mapillary's camera seems to hang for an annoying period of time* before crashing.  I can go back into camera mode and begin a new sequence without any problem.

Sending trace logs in a separate e-mail, with this github# in the subject.

*A period of time is annoying when it doesn't crash immediately, but sits there thinking about it and keeps you from doing anything else with the app.

**Comment by jfburke3** [comment]
Or maybe I won't be able to send the logs after all :-(

This happened earlier today, and I _thought_ I saved a copy but now can't find it.  I should be able to reproduce it again without much trouble, so I'll get that sometime tomorrow.

**Comment by rsahlin** [comment]
Thanks - for the detailed report, much appreciated!

I will look into this and try to reproduce.

Best regards
/Richard
