### ISSUE TITLE
Crash while shooting with the miniviewer open

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1855]
Circumstances are different than #1854 so reporting separately.

Mapillary v2.09, Samsung Galaxy S7, Android 6.0.1

While shooting a sequence with the little round miniviewer open, Mapillary crashed.  The screen went blank and hung for 10 or 15 seconds before finally returning me to the desktop.  Was able to restart and resume shooting.

I have the trace logs for this one, sending via e-mail with this github# in the subject.

**Comment by rsahlin** [comment]
Thanks, I have the logs and will go through them.

Best regards
/Richard
