### ISSUE TITLE
Positions completely off

### ISSUE THREAD

**Issue by Mercator72** [mapillary/mapillary_issues#1856]
I am making some tests with my GoPro Hero4 Black and the iOs application (iPhone 5s). The positions of this sequence end up completely wrong :
https://www.mapillary.com/map/im/xoDRDpqFaVhGiNlnnoCrQQ/photo
The first photo of the sequence seems correct, but it seems the positions shift gradually and the last photo of the sequence is off by hundreds of meters (please remove the sequence by the way).
Settings of my GoPro : 7MP, medium field of view
In the iOs app : one photo every second.

**Comment by millenbop** [comment]
Hi!

Thanks for reporting. It is a known issues and we are working on it. We hope to have a fix ready soon.

- Anders

**Comment by Mercator72** [comment]
The problem is, you don't notice it until it's too late. I really think adding the ability to remove easily and instantly our own bad sequences/photos from the editor should be your top priority ;-)

**Comment by millenbop** [comment]
Version 2 of action camera support should fix this and lots of other things. It will be out in a few days. Closing for now. If problem persists, let me know!
