### ISSUE TITLE
Some sequences not showing up in map

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#1858]
Some of my sequences don't show up on the map after around a week. Later uploaded sequences are already on the map.
All of the sequences not showing up were uploaded on 09.05.2016 via script. They are in my profile and i can use them on the map, but the track does not show up.
Sequence links are:
http://www.mapillary.com/map/s/_WSVoaE_GA_avDO58Lzzvg
http://www.mapillary.com/map/s/5dA-O8Ml_UwrewUuBKemZg
http://www.mapillary.com/map/s/AomDzOT-aadseI92uSDb0g
http://www.mapillary.com/map/s/dVgN4S_-aclYZqZ9GZ5ePw
http://www.mapillary.com/map/s/fGT_2BMyCoN14TdiPFluQA
http://www.mapillary.com/map/s/-b0VO2BB400cBTt5TVBP4Q
http://www.mapillary.com/map/s/cZyyE9FjQlIiFQNYFuWyBA
http://www.mapillary.com/map/s/Ytwl-q2-rzFkHnZEg1oBYw
http://www.mapillary.com/map/s/LpFtsd9em7OnfWPpsjI7rA
http://www.mapillary.com/map/s/Tg16Gr0Hb9xbK4RNSLxMYA
http://www.mapillary.com/map/s/fZjQ1ukeA5mpuoifkxAjOQ
http://www.mapillary.com/map/s/-WSo6LZry8zEVO5fQMg5uw
http://www.mapillary.com/map/s/Eo81uPcOhqLuziaAy0lYjw
http://www.mapillary.com/map/s/4QSm6FZV_G-YuSZ_lHJLsg
http://www.mapillary.com/map/s/Tua77UhpnpH3uLFNLs13QQ
http://www.mapillary.com/map/s/b09w-9xvDP-hrmzBE1-nQg
http://www.mapillary.com/map/s/ry3XSdUPHfJXZvoHsfCK9g
http://www.mapillary.com/map/s/bsydql3qBQn5kJkhTSEikg
http://www.mapillary.com/map/s/7hptjj9vD5GOAYMP-CY6Ww
http://www.mapillary.com/map/s/8wz-Hi6KPJWd1eE41Z3g3A
http://www.mapillary.com/map/s/7eT7NewjHz8xMpj9wPOFgA
http://www.mapillary.com/map/s/jEQFO2N-UHvMdsgIgjLyTg

ramap

**Comment by Andblue** [comment]
The pictures for this sequence are there, but no mark on the map
http://www.mapillary.com/map/im/nWVmiZH7mtmZUrMhR5HdlQ/photo

Made another sequence just before that, no pictures are there.

Used the iOS app.

**Comment by gyllen** [comment]
@Andblue YOu see the other sequence in your list of sequences?

**Comment by Andblue** [comment]
@gyllen I do not see either of the two sequences in the list.

**Comment by andrewpmk** [comment]
I have the same problem.

http://www.mapillary.com/map/im/WxpKrsvTQLX6oLlptF6FJg/photo
http://www.mapillary.com/map/im/u3hZPP64OrSt_3NgQ48Ikg/photo

These sequences have been uploaded to Mapillary and can be viewed on the Mapillary website, but do not show up in either the Mapillary map view or the Mapillary JOSM plugin.

**Comment by de-vries** [comment]
I noticed that all examples above are from 7, 8 or 9 may. I also mentioned the same problem [here](https://github.com/mapillary/mapillary_issues/issues/1719#issuecomment-218567331). It seems to me that some part of the photo processing glitched out for a few days. I've also noticed that some older sequences are (on some zoom levels) missing on the map. 
It might be wise to regenerate all tiles to eliminate all errors that have creeped in over time.

**Comment by kimbach** [comment]
I have the same problem with a sequence, the photos are actually on the map, but they're not "marked with green" as a track.

http://www.mapillary.com/map/s/mtYji-xVF1BmyCI_CKVswg

**Comment by gyllen** [comment]
So I been diving into this issue and found that we had some tile generation issues from 7,8,9 May. Good news though we are in final stages of building a new tiler with better (more compressed tiles) and more information on lower levels. We are rerunning the tile generation from scratch then (as you suggested @de-vries). So expect this to happen pretty soon.

**Comment by de-vries** [comment]
@gyllen FYI: I've checked my photos from the ninth and a few of the examples from above, and none of them show up in the JOSM plugin. 
I don't know if the plugin uses the same tiles, or if this is a additional problem.

**Comment by gyllen** [comment]
@de-vries Yes, JOSM uses the same tiles, terrible sorry about this.

**Comment by de-vries** [comment]
problem is still present in new mapillary

**Comment by gyllen** [comment]
@de-vries Yes I was actually just trying to close this issue. But we are getting further in investigation though. I'll keep you updated.

**Comment by ramapongithub** [comment]
On the occasion of the first anniversary: Is something on the horizon to solve the problem?

**Comment by gyllen** [comment]
@ramapongithub Do you also have images missing from these specific dates?

**Comment by ramapongithub** [comment]
@gyllen  See the sequences in my first post. I can access them on the legacy webpage with the same key, for instance for the first sequence
[http://legacy.mapillary.com/map/s/_WSVoaE_GA_avDO58Lzzvg](http://legacy.mapillary.com/map/s/_WSVoaE_GA_avDO58Lzzvg) 
So the pictures are there, but the tracks are not shown on the map.

On the new webpage things are much more complicated. The tracks/dots are also not shown, so no easy access.
I think i see the sequences in my profil page on the iphone for May 2016, but dont know how to extract an sequence key from there. But on the webpage i will have to go through all my uploads. And as they are loaded dynamically this will be a pita going back a whole year..

**Comment by ramapongithub** [comment]
Short update: I can not find this sequences under my uploads on the newer webpage.

**Comment by gyllen** [comment]
@peterneubauer We need to add this to the inconsistency issue.

@ramapongithub Thanks for pinging us on this one.

**Comment by ramapongithub** [comment]
Another short update: I can see the sequences on my profile page on the Iphone, but cn not access them. When i tap them, the view changes to the split screen for playing the sequence, but the map view stays on world overview and the picture view stays black.

**Comment by peterneubauer** [comment]
Is that even happening on the web, do you have a link?

**Comment by ramapongithub** [comment]
@peterneubauer I tried yesterday to find the sequences in my upload overview on the web, but could not find them. I will try again, but at the moment the web page is a bit unresponsive.

**Comment by ramapongithub** [comment]
@peterneubauer I picked the fifth sequence from my first post as example.
[legacy.mapillary.com/map/s/fGT_2BMyCoN14TdiPFluQA](legacy.mapillary.com/map/s/fGT_2BMyCoN14TdiPFluQA)
The sequence key links to the first picture in this sequence
[http://legacy.mapillary.com/map/im/_yD8MBA4ECpJWx3hq8MTjA/photo](http://legacy.mapillary.com/map/im/_yD8MBA4ECpJWx3hq8MTjA/photo)
and shows on my computer as
[https://www.pic-upload.de/view-33192238/legacy.jpg.html](https://www.pic-upload.de/view-33192238/legacy.jpg.html)
As you see, pictures are there, but no green track on the map in the upper right corner.

The same [area](https://www.mapillary.com/app/user/ramap?lat=50.549372100508435&lng=12.004940198043585&z=12.66831935115073) on the current page  and with my uploads scrolled down to the date of the pictures looks as this
[https://www.pic-upload.de/view-33192287/upload.jpg.html](https://www.pic-upload.de/view-33192287/upload.jpg.html)
No track either on the map and the sequence is not showing in the uploads. The uploads seem to be ordered by date of pictures/sequence taken. There are sequences for May 7th 2016 which had no problems. The above mentioned sequence is not there.

But on the Iphone in the Mapillary app in the profile page, where the sequences seem to be ordered by date pictures/sequences uploaded, i can find the sequence.
[https://www.pic-upload.de/view-33192240/IMG_1333.png.html](https://www.pic-upload.de/view-33192240/IMG_1333.png.html)
But as mentioned before, access is not possible in the app.

**Comment by jaku103** [comment]
I'm seeing this same promblem recentely. I can see them inside OSM's web ID, but on inside Mapillary app or site. For images I uploaded over two weeks ago.

**Comment by peterneubauer** [comment]
I have reprocessed all these sequences, they are showing up on Mapilary now AFAICS?

**Comment by ramapongithub** [comment]
@peterneubauer 
Hard to check after 2 years and the legacy links not working anymore, but:
I see the first sequences to appear on the "new" map! Not all yet, maybe a lag in the processing. 
Big thanks anyway!

**Comment by ramapongithub** [comment]
After two weeks it remains only an partially success. 7 of 22 sequences appeared. I crossed out the links of this seven sequences in the list.

~~http://www.mapillary.com/map/s/_WSVoaE_GA_avDO58Lzzvg~~
http://www.mapillary.com/map/s/5dA-O8Ml_UwrewUuBKemZg
http://www.mapillary.com/map/s/AomDzOT-aadseI92uSDb0g
http://www.mapillary.com/map/s/dVgN4S_-aclYZqZ9GZ5ePw
http://www.mapillary.com/map/s/fGT_2BMyCoN14TdiPFluQA
http://www.mapillary.com/map/s/-b0VO2BB400cBTt5TVBP4Q
http://www.mapillary.com/map/s/cZyyE9FjQlIiFQNYFuWyBA
~~http://www.mapillary.com/map/s/Ytwl-q2-rzFkHnZEg1oBYw~~
~~http://www.mapillary.com/map/s/LpFtsd9em7OnfWPpsjI7rA~~
http://www.mapillary.com/map/s/Tg16Gr0Hb9xbK4RNSLxMYA
http://www.mapillary.com/map/s/fZjQ1ukeA5mpuoifkxAjOQ
http://www.mapillary.com/map/s/-WSo6LZry8zEVO5fQMg5uw
~~http://www.mapillary.com/map/s/Eo81uPcOhqLuziaAy0lYjw~~
http://www.mapillary.com/map/s/4QSm6FZV_G-YuSZ_lHJLsg
http://www.mapillary.com/map/s/Tua77UhpnpH3uLFNLs13QQ
http://www.mapillary.com/map/s/b09w-9xvDP-hrmzBE1-nQg
~~http://www.mapillary.com/map/s/ry3XSdUPHfJXZvoHsfCK9g~~
http://www.mapillary.com/map/s/bsydql3qBQn5kJkhTSEikg
http://www.mapillary.com/map/s/7hptjj9vD5GOAYMP-CY6Ww
http://www.mapillary.com/map/s/8wz-Hi6KPJWd1eE41Z3g3A
~~http://www.mapillary.com/map/s/7eT7NewjHz8xMpj9wPOFgA~~
~~http://www.mapillary.com/map/s/jEQFO2N-UHvMdsgIgjLyTg~~

ramap

**Comment by peterneubauer** [comment]
That is indeed a bit strange. @ptpt can you please check why the link http://www.mapillary.com/map/s/5dA-O8Ml_UwrewUuBKemZg is not resolved? The sequences seem to be there correctly in the db.

**Comment by ramapongithub** [comment]
@gyllen 
Confirmed!
Now the same procedure for the rest?!

**Comment by gyllen** [comment]
@ramapongithub Are the rest still missing though?

**Comment by ramapongithub** [comment]
@gyllen 
Yes the rest ist still missing. 
This is the actual list:
 ~~http://www.mapillary.com/map/s/_WSVoaE_GA_avDO58Lzzvg~~
~~http://www.mapillary.com/map/s/5dA-O8Ml_UwrewUuBKemZg~~
http://www.mapillary.com/map/s/AomDzOT-aadseI92uSDb0g
http://www.mapillary.com/map/s/dVgN4S_-aclYZqZ9GZ5ePw
http://www.mapillary.com/map/s/fGT_2BMyCoN14TdiPFluQA
http://www.mapillary.com/map/s/-b0VO2BB400cBTt5TVBP4Q
http://www.mapillary.com/map/s/cZyyE9FjQlIiFQNYFuWyBA
~~http://www.mapillary.com/map/s/Ytwl-q2-rzFkHnZEg1oBYw~~
~~http://www.mapillary.com/map/s/LpFtsd9em7OnfWPpsjI7rA~~
http://www.mapillary.com/map/s/Tg16Gr0Hb9xbK4RNSLxMYA
http://www.mapillary.com/map/s/fZjQ1ukeA5mpuoifkxAjOQ
http://www.mapillary.com/map/s/-WSo6LZry8zEVO5fQMg5uw
~~http://www.mapillary.com/map/s/Eo81uPcOhqLuziaAy0lYjw~~
http://www.mapillary.com/map/s/4QSm6FZV_G-YuSZ_lHJLsg
http://www.mapillary.com/map/s/Tua77UhpnpH3uLFNLs13QQ
http://www.mapillary.com/map/s/b09w-9xvDP-hrmzBE1-nQg
~~http://www.mapillary.com/map/s/ry3XSdUPHfJXZvoHsfCK9g~~
http://www.mapillary.com/map/s/bsydql3qBQn5kJkhTSEikg
http://www.mapillary.com/map/s/7hptjj9vD5GOAYMP-CY6Ww
http://www.mapillary.com/map/s/8wz-Hi6KPJWd1eE41Z3g3A
~~http://www.mapillary.com/map/s/7eT7NewjHz8xMpj9wPOFgA~~
~~http://www.mapillary.com/map/s/jEQFO2N-UHvMdsgIgjLyTg~~

The crossed out sequences are fine, the links to the others show only the world map.

**Comment by peterneubauer** [comment]
Thanks for the list! I will fix the others, it might take some weeks since
I'm on holiday right now.

**Comment by ptpt** [comment]
As I checked they don't have geometry stored. I will track it internally and ask @peterneubauer for reprocessing these sequences. Closing here.

**Comment by peterneubauer** [comment]
@ptpt just make these sequences dirty in PSQL, and Gudrun will pick them up and recalculate them, including the geometry.

**Comment by peterneubauer** [comment]
So, these sequences are now correctly rendered right @ramapongithub @andrewpmk @de-vries ?

**Comment by ramapongithub** [comment]
@peterneubauer  Sorry for the late reply. Was on holiday and had to capture new pictures in some european countries.

First the good news: the sequences are rendered. 
Bad news: there seem to be a lot of gaps in them, as if missing some pictures. But could also be an rendering problem.
Like here: [https://www.mapillary.com/app/?pKey=szDuFvLyurE6HBp5grcz-Q&lat=50.443438888888885&lng=9.323647222222222&z=17&focus=map](https://www.mapillary.com/app/?pKey=szDuFvLyurE6HBp5grcz-Q&lat=50.443438888888885&lng=9.323647222222222&z=17&focus=map)
The sequence rendering north of the picture seems broken in higher zoom levels. In lower zoom levels the picture is not even in the rendered sequence.
And additionally i can not go forward or backward in the sequence or play the sequence as video.
