### ISSUE TITLE
Profile text appears scrolled to bottom

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1862]
My profile description ("about me") in the last tab of the iOS app is wrapped into 4 lines, and the UI can only show about 2.5 lines, so it's scrollable. This is acceptable; there has to be a limit to how many lines you can fit in there. However, when I open that tab for the first time, the text is scrolled to the bottom, showing the last lines, instead of the first ones:
![profile-scroll-bottom](https://cloud.githubusercontent.com/assets/101955/15342708/fb25f266-1c6d-11e6-87b3-7b9e31f387c3.png)

It should appear initially scrolled to the top instead.

**Comment by millenbop** [comment]
Fixed now, available in next release.
