### ISSUE TITLE
Reviewing photos is slow

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1864]
Reviewing a sequence of 300+ photos is too slow.
Scroll down towards end of list and after a while the Picasso component becomes very slow and unresponsive.
Checked on version 1.85, still in 2.10 regardless of thumbnail creation.

**Comment by Caboosey** [comment]
I am having same issues. I am using/used Mapillary v2.09, 2.10, and 2.11 on my Samsung Galaxy S5 Sprint on Android 6.0.1 uploading max resolution (HD) photos. I now have over 15,000 photos pending and all sequences have over 300 photos minimum.

I just email my logs.

**Comment by rsahlin** [comment]
Hi @Caboosey 

Do you know when you started experiencing this problem, ie is there a version number where you know it was fast to browse 300+ pics?

Best regards
/Richard

**Comment by Caboosey** [comment]
@rsahlin Last time I remember was back in July 2015 and running on this same phone, Samsung Galaxy S5 Sprint with Android 5.0 at that time. I forgot the version. There is gap of me not using Mapillary. I think I started seeing it around version 2.07.

My entire Mapillary app will become unresponsive when trying or actively uploading photos.

Did a test where I had 10k photos pending with Cell Sync turned off...i tried to navigate within the app and soon I turned off wifi the Mapillary started responding.

**Comment by Caboosey** [comment]
Reviewing photos is still slow, unresposnive, sometimes gray or black screens, and alert box saying "Mapillary isn't responding. Do you want to close it?". The entire app is also still slow, unresposnive, sometimes gray or black screens, and alert box saying "Mapillary isn't responding. Do you want to close it?"

My photos are taken at high resolution and most sequences are 2k to 15k photos per sequence.

Currently running:
Mapillary version: 2.13
Device: Samsung Galaxy S5 Sprint
Device Model: SM-G900P
Android version: 6.0.1
Android kernel version: 3.4.0-7959153

**Comment by rsahlin** [comment]
Hi @Caboosey and thanks for reporting

We will discuss internally when we have time to look into this issue.
Please be patient!

Best regards
/Richard

**Comment by Caboosey** [comment]
@rsahlin Just updated to v2.15 and I am seeing improved performance and  with the app overall and reviewing photos. Still get some slowness and black/gray screens, but doesn't last as long as before.

Currently have about 13k photos pending to upload.

**Comment by rsahlin** [comment]
Hi @Caboosey and thanks for checking :-)

You will sadly not get any more increase until we have time to completely rewrite the review-activity.
We will now focus on login/signup and some other UI improvements then we will implement support for action cameras.

Please be patient!

Best regards
/Richard

**Comment by Caboosey** [comment]
@rsahlin Thank you for the update. I can work with this. :+1:
