### ISSUE TITLE
Featured photos should update automatically

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1867]
When I open the "Featured" tab in the iOS app to see featured photos, it doesn't request the current photo list from the server. I see whatever were the latest photos last time I manually updated. I have to drag the list down to updated it.

I think the list should automatically update when opened (only when that particular tab is opened, of course). And considering photos are featured every few days, not every few minutes, maybe the list doesn't even need to have "pull to refresh".

**Comment by nicolas17** [comment]
(I really thought no new photos had been featured in months, until I noticed I could refresh manually)

**Comment by millenbop** [comment]
This has been fixed now, will be out in the next release.
