### ISSUE TITLE
Nested camera layout - (HTC One M8 - very sluggish interface)

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1869]
The Mapillary app is very very sluggish and slow on my HTC One M8.
When compared to my older Samsung s3 if would say the HTC is close to unusable.
The phone gets also very hot very fast.

**Comment by rsahlin** [comment]
Hi @seb-1204 

Could you please explain what part of the app that is slugish.
Is it opening the camera, the viewfinder or other?

The phone will become hot when it is working, especially since the flow of the Mapillary app is to take a large number of pictures quickly.

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi!

thats the fault of HTC, got the same heat/slowness issues on my HTC One M9. It is the in built CPU and ressource useness of HTC drivers to the system, also the power-save functions to slow down the CPU if it gets to hot.
It was fine for older Mapillary apps, until HTC sent out Android 6 (Marshmallow) to the device with a few changed power options to save the mobile.
For me, I can take a picture every 2 sec on HTC One M9 with no problems, but the view/display is really really laggy

echelon

**Comment by rsahlin** [comment]
Hi @echeloni2p and thanks for the clarification

Could you please try checking the 'Take low resolution pictures' option to see if this helps?

I have noticed a few other (older) devices that are having problem updating the viewfinder with Camera2 API.
Is this problem only with Mapillary camera app - or is it also sluggish with other camera apps?

Could you please go into 'Feed' - 'Settings' and enable 'Write trace logs', then please go back and open the camera.
- Go into 'Feed' and select 'Send debug logs'

Thanks!

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi!

Image size does not change anything at all.
A trace is here:
https://helene.cgv.tugraz.at/owncloud/index.php/s/eI1ApAGa6co9V97

echelon

**Comment by rsahlin** [comment]
Hi and thanks

Could you please check if this is a degrade from version 1.85?
The different versions can be found here:
http://android-releases.mapillary.io/index.html

Also, how is the performance in other camera apps on the M8?

Best regards
/Richard

**Comment by echeloni2p** [comment]
Need time to check against the old app.
The performance is far lower than other camera apps. The other apps I tested working fine with the camera and viewer, as expected. Just mapillary showing that issue.

**Comment by seb-1204** [comment]
Hi all, I will also give the older versions a try. As far as I can remember I always had issues with my HTC one M8. Sluggish interface, very fast heating up, brightness/exposure not working.

Regarding the sluggishness - the video is spot on. The same behaviour is when I open the settings out of the camera screen. The whole sluggishness starts when activating the camera. If I haven't used the app for a while and start it the feed view and going to settings from feed view is fine. I then open the camera and it slows down to a crawl.

Due to the issues that the brightness/exposure correction was not working I had to go into settings and change the focus mode. e.g. from auto to continuous.

**Comment by seb-1204** [comment]
I've tried 1.85 same behavior. I also send logs

**Comment by rsahlin** [comment]
Hi and thanks for checking!

Could you please check if it is as sluggish with other focus modes?
Eg check what happens if you switch to FIXED.

Thanks

Best regards
/Richard

**Comment by echeloni2p** [comment]
For me changing focus mode does not change anything 

echelon

**Comment by rsahlin** [comment]
Ok, thanks for checking.

You are mentioning both HTC M8 and M9 - could you please clarify if there is a problem on both devices?
If so, do they behave the same or is one worse than the other?

Best regards
/Richard

**Comment by echeloni2p** [comment]
I cannot check both, my experience is from M9 - and I do know, HTC has made some strange stuff on that device to keep it low CPU hungry and powersaving...

**Comment by seb-1204** [comment]
I have a M8 and on mine the focus mode does not affect the behavior.

**Comment by ethan-nelson** [comment]
Just for another data point, I have an HTC One M9. I just updated to the latest version and am experiencing this as well. Neither turning off camera 2.0 nor modifying focus fixes the camera sluggishness.

**Comment by rsahlin** [comment]
This seems to be different issues.

Some are reporting that the app is sluggish regardelss of using version 1.85 or 2.X
Others seems to be indicating that it has gotten worse with the 2.x update.
I wonder if this could be because the app tries to take pictures more frequent now?
Previously if a photo was skipped due to processing the app slept for another X seconds.
In version 2.X the app will take next picture as soon as the previoius has been captured - possibly increasing the sluggishness but actually providing more pictures per second.

Best regards
/Richard

**Comment by rsahlin** [comment]
After investigating the camera layout I think I have found the problem.

The camera contains several nested layouts - this is fine on higher end devices that has hardware support for multiple layers but on mid-low end devices this overdraw will limit performance.
If I am correct in my assumption this could have a positive impact on heating/battery issues as well since all devices will do less work with a flat layout.

Downside is that behavior needs to be moved from the layout and into the activity to be able to preserve a flat layout.

**Comment by seb-1204** [comment]
@rsahlin it sound like you came across something. Unfortunately I'm your description exceeds my understanding of the topic. 
But please let me and others know if we can help by testing etc.

**Comment by katrinhumal** [comment]
Closing this as outdated. If anyone has problems with the current app version, please open a new issue. Thanks!
