### ISSUE TITLE
Traffic icon not displaying for: type-warning--double-curve-first-left-ahead--us

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#1870]
On the "Detected Traffic Signs" section of my profile, a traffic sign showing up in the HTML code as "mapillarytrafficomarker t type-warning--double-curve-first-left-ahead--us" fails to display.
![2016-05-20_01](https://cloud.githubusercontent.com/assets/12619646/15442853/6575f7a0-1ea9-11e6-8778-5d472705dddd.jpg)

**Comment by gyllen** [comment]
Leaving this as open, but area is under reconstruction.

**Comment by gyllen** [comment]
We no longer have this view.
