### ISSUE TITLE
Mixed Content Warning at https://www.mapillary.com/

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#1871]
Mixed Content: The page at 'https://www.mapillary.com/map' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mapillary-vector.mapillary.io/tiles/10/262/421.mapbox?images=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by gyllen** [comment]
@Caboosey Exactly at what page are you seeing this?

**Comment by Caboosey** [comment]
I see this when loading:
https://www.mapillary.com/
https://www.mapillary.com/map

**Comment by emilstahl** [comment]
Duplicate of #1752

**Comment by Caboosey** [comment]
Fixed as per Duplicate of #1752
