### ISSUE TITLE
Android client stops uploading out of nothing, without error message 

### ISSUE THREAD

**Issue by tuliogit** [mapillary/mapillary_issues#1875]
This happens very frequently. The android client starts syncing and I leave it charging. When I get back, many hours later, I notice that it somehow lost its connection or in some other way stopped syncing. Many times less than a hundred pictures were uploaded. The notification of the progress is still there, but nothing is uploaded: the router doesn't blink, the progress doesn't count up, and absolutely no error message is brought to the screen. And even though it is configured to start syncing even on battery, it doesn't start syncing again. After seeing this happen several times, I can say that this happens even when no hiccup or disruption occurs to the connection. I don't know how to reproduce the bug.

**Comment by HolgerJeromin** [comment]
I think this is Android killing this app because the phone has no free memory. 
Since #1712 you can check if the time is old or new to find this situation.

**Comment by Caboosey** [comment]
I am having same issue and might be related to issue #1864

**Comment by Caboosey** [comment]
@tuliogit Only workaround that helped me so far, I activated a 2nd SSID on the 5GHz wifi band only on my wireless access point and forced my phone to use it. Then kept Mapillary app opened and plugged phone up sitting next to that wifi access point.

Normally my wireless network at home has same SSID on both 2,4GHz and 5GHz and the phone likes using the more powerful signal, 2.4GHz. Only devices using my wifi are my phones and tablets. So, I'm not sure why Mapillary app is having so much issues trying to upload over 2.4GHz wifi.

**Comment by HolgerJeromin** [comment]
Not using other applications is sufficient for me to have a successful upload.

**Comment by peterneubauer** [comment]
Not sure why this should be a problem - we are not doing any custom network magic, just trying to post images. Sometimes it might of course be that the uploads are cancelled because the bandwidth is slow ...

**Comment by shlublu** [comment]
I had the problem yesterday. I had something like 1200 pictures to upload, and the first attempt stopped after roughly 650. Ti upload the rest I had to check the "upload" checkbox of the remaining sequences in the Android app's "review sequences" tab.

**Comment by Caboosey** [comment]
I was able to reproduce the issue by unlocking phone and leave the app by hitting home button. It immediately got stuck in the notification drawer at "Uploading 88 of 15754 photos"

**Comment by peterneubauer** [comment]
Awesome - can you send the log for that?

**Comment by Caboosey** [comment]
@peterneubauer Log sent to by email.

**Comment by Caboosey** [comment]
@peterneubauer My Samsung Galaxy S5 Sprint running Android 6.0.1 just received a over the air (OTA) firmware  and kernel update (May 1, 2016 build). In the change log for the update mentioned bug fixes, wifi stability fixes, and others. 

My Mapillary is now uploading very fast in the background without having to have app open and not timing out or getting stuck.

FYI: Mapillary is at v2.12

**Comment by peterneubauer** [comment]
Yay!!

**Comment by HolgerJeromin** [comment]
Is the original issue solved? I'm not sure

**Comment by Caboosey** [comment]
@tuliogit Try checking for system updates for your phone. Did your issue get resolved?

@HolgerJeromin You get a system update for your phone? is Mapillary uploading working now for you?

**Comment by tuliogit** [comment]
It`s been working.
