### ISSUE TITLE
allow to review photos on phone from the map

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1878]
sometimes i might notice that the phone has decided to focus on the windshield, resulting in blurry photos.
at the end of the day, i might recall where approximately that happened, but it is not possible to review sequences, by picking them on the map.

the suggested mode would show a zoomable/pannable map, and local sequences would be displayed, similar to the website operation.

**Comment by gyllen** [comment]
Android or iOS?

**Comment by richlv** [comment]
in this instance ios, although it seems like something to be useful on any phone :)

**Comment by millenbop** [comment]
Thanks for your suggestions! I agree. In general I would like to add maps more and more in the app to make it easier to find stuff. I would also like to add some more editing capability in the app, like to correct GPS positions and angle.

Low prio for now though.

**Comment by millenbop** [comment]
This has been implemented in a previous update.
