### ISSUE TITLE
GoPro Hero 3 - support

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1880]
Hello,
this is a feature request to support GoPro Hero 3 with the iOS and Android app. Is there any chance this is coming? Any ETA?
The [recently announced collaboration](http://blog.mapillary.com/update/2016/04/15/gopro.html) with GoPro left me hoping....

**Comment by millenbop** [comment]
We have support for it on iOS, but apparently it's broken right now according to some users. I don't have access to a Hero3 so I can't test unfortunately. I have done a "blind fix" but haven't heard if it's working or not.

We will try to support it for as long as possible, but be aware that unfortunately the official SDK does not support Hero3, and we will switch to the official SDK very soon for stability reasons. That doesn't mean Hero3 won't be working after the switch, but it's no guarantee and in the end it's up to GoPro.

We will forward the request to GoPro though, so lets hope we can influence them to add support for it in the SDK.

**Comment by seb-1204** [comment]
Thanks for the response and clarification. I think there are many GoPro 3s out there so please gopro please.

**Comment by seb-1204** [comment]
@millenbop I've just tired to connect my GoPro Hero3+ Silver Edition (Version HD3.10.03.02) to an iPhone 4S running iOS 9.1.

1. I connect to the GoPro wifi and start the Mapillary (Version 4.3.1) app. 
1. I go to camera, and after a second or so it recognised the camera and ask me if I want to use. OK
1. after another second I get below message
```
Lost connection
Lost connection to the external camera. The capture has stopped. <OK>
```
1. The display then states "External Camera" but the view is frozen. I actually see a photo which is not the current GoPro or phone camera!?

**Comment by shlublu** [comment]
I'm waiting for it for so long, please please :) (Hero 3+ SE / Android)

@seb-1204 I was wondering, do you connect thru "WiFi-RC" or "Wi-Fi-app" ?

**Comment by seb-1204** [comment]
@shlublu I'm connecting via app

**Comment by millenbop** [comment]
Hey, sorry still don't have access to a Hero3 as our is out on loan currently. @katrinhumal any ETA when it will be back?

**Comment by shlublu** [comment]
@millenbop I do have one. I'd be happy to do some testing for you if needed (Android only, i don't have an iPhone).

**Comment by millenbop** [comment]
@shlublu Thanks, mainly need it for iOS testing :) For Android we will probably use the official SDK and it states that it doesn't support Hero3, but it may work anyway.

**Comment by shlublu** [comment]
I've seen they also officially endorse some open source initiatives that claim to be compatible with both, but you probably investigated in that: https://gopro.com/support/open-source ( #justInCase #hope #etc :) )

**Comment by millenbop** [comment]
Removing the iOS label as support is there, it's just not working :) Tracked in #1893 and #1897

**Comment by katrinhumal** [comment]
Update on the Android front is that we have started external camera support for 360 cameras, after which it will be the turn for action cameras. So stay tuned!
