### ISSUE TITLE
App stops taking pictures after suspending and resuming it

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1882]
In iOS, if I press the hardware home button to go to the home screen, or otherwise switch apps, the Mapillary app stops taking pictures; which is expected due to OS limitations on background activities. But going back to the app doesn't resume taking pictures, _not even if I press Stop and Start again_.

1. Open app and start taking pictures
2. Press home button. App stops taking pictures, shutter sound can't be heard anymore.
3. Go back to Mapillary app. The button is still red and says "Stop" as if it was taking pictures, but it's not (no shutter sound, no flashing).
4. Press Stop. Button turns green.
5. Press Start. Button turns red, but it's _still_ not taking pictures.
6. Press Stop, and close the capture view. (You can now see in the Upload tab that indeed there are only pictures from step 1 above, so it's not only an issue with the shutter sound or screen flashing).
7. Open capture view again and press Start. Now it works again.

**Comment by millenbop** [comment]
Thanks for reporting! I'll look into it!

**Comment by millenbop** [comment]
This should be fixed in the next release.
