### ISSUE TITLE
Camera hangs during capture

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1883]
The camera hangs during capture due to ImageReader exception, see attached logs
Device:
Samsung Galaxy S7, Android 6.0.1

[capture_hangs_dropped_images.txt](https://github.com/mapillary/mapillary_issues/files/279076/capture_hangs_dropped_images.txt)

**Comment by jfburke3** [comment]
Got the new 2.13 build.  Will try to give it a hard test as soon as I can, but might not be until the weekend.

**Comment by jfburke3** [comment]
BTW, in one of the last couple of builds, you seem to have fixed another problem that I haven't had time to report yet.  I discovered that I could not use camera mode with Camera2 API disabled--it would crash.  Just tried that, and I can enter camera mode now.

**Comment by rsahlin** [comment]
Great - thanks @jfburke3!

Best regards
/Richard

**Comment by polarbearing** [comment]
Where is 2.13? The last I see on the server is 2.12 / 24 May

**Comment by rsahlin** [comment]
My mistake - forgot to add it for manual downloading.
Available at:
http://android-releases.mapillary.io/index.html

**Comment by jfburke3** [comment]
@polarbearing, I joined the beta test group, so that might be why I see the next version before you.
