### ISSUE TITLE
Can't see all paid plans on narrow screens

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1885]
The [Solutions](https://www.mapillary.com/solutions.html) page adapts pretty well to mobile screens, for example the three screenshots appear side by side on desktop, but one below the other on mobile.

However, if I'm on a mobile device with portrait screen, the table at the bottom with the different plans is simply cut off, and I can't even scroll horizontally:
![image](https://cloud.githubusercontent.com/assets/101955/15506448/12bcc58c-219e-11e6-913c-c608b70bb0ae.png)
(sorry for screenshot size)

In landscape it fits perfectly, but if I hadn't double-checked on a desktop browser, I would be left wondering if there was a fifth plan that is still cut off in landscape.

**Comment by gyllen** [comment]
Should be visible on new webpage closing
