### ISSUE TITLE
Sequence is jammed when using the play button but displays normally when using the arrows

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1887]
Some sequences do not display normally when using the play button. Some images appear tilted, leaving a large part of the screen black. However, when using the arrows, each image displays normally.

A couple of examples:
- http://www.mapillary.com/map/im/-0wcKxhl94ya3Lh8bMJ_2g/photo
- http://www.mapillary.com/map/im/R6utYJ3eKDvipaN3HIZ1Ug/photo

Other examples are available if needed.

**Comment by oscarlorentzon** [comment]
Thanks for reporting. Will look into the problem.

**Comment by oscarlorentzon** [comment]
Playing this sequence works fine in our new viewer mapillary/mapillary-js which will be used when the new website is released.

**Comment by shlublu** [comment]
Great, thanks @oscarlorentzon 
When will the new website be released? (no emergency, just to know)

**Comment by angelday** [comment]
@shlublu hard to say exactly. Rest assured we're working on it, as I write this. ;)

**Comment by oscarlorentzon** [comment]
This now works as expected on the website.
