### ISSUE TITLE
Email/notification of processing (automatic blur, 3D transition) is completed 

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1889]
Currently users receive email/notification when the photos have been uploaded, but not yet processed, and when the processing is complete and you can see them on the map. When this happens, if you open the sequence immediately, you can see your images on the sequence, but the automatic blur has not yet been applied, nor the 3D transition.

It'd be interesting to receive a email/notification when this process is actually completed and you can see (and hopefully review) the automatic blur.

**Comment by jesolem** [comment]
Blur is always done before publishing the image @nighto 

The rest of the processing can take longer than publishing. @gyllen is thinking about notifications right now, passing this feedback to him. Notifications re-work is scheduled for later this summer.

**Comment by gyllen** [comment]
@nighto The automatic blur always runs first, so you will never see an image without autoblur. However we will switch so you get the second email only when the 3D transitions kicked in.

Thanks for the feedback!

**Comment by gyllen** [comment]
The only email we send at the moment is now when the images are fully processed.
