### ISSUE TITLE
Show sequences maps on profile page

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1890]
When you receive an email that your sequence is on the map, it comes with a nice map:

![image](https://cloud.githubusercontent.com/assets/397851/15583168/08f0c7f2-234b-11e6-957c-1d6f1daa0e92.png) 
![image](https://cloud.githubusercontent.com/assets/397851/15583178/14f556a8-234b-11e6-89c8-3581fdcf1c54.png)

I believe that in the profile page (mine below for instance) it should be shown exactly as this: a map and picture combined per sequence, not only the pictures.

![image](https://cloud.githubusercontent.com/assets/397851/15583203/3b28b824-234b-11e6-81f4-bc35207a236c.png)

**Comment by jesolem** [comment]
Great idea. Will pass this feedback to @angelday who is doing some exciting re-design work.

**Comment by angelday** [comment]
@nighto thanks for bringing this to our attention. In the next product iteration we'll certainly have an answer for this. This feature is already in development, so I'll close this issue.
