### ISSUE TITLE
Add option to lock in sequence in viewer

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1891]
When you're visualizing photos in a sequence, and specially if you're browsing the pics in order to correct the automatic blurring, there should be an option to "lock in sequence", so that the forward buttons stick in the sequence you want to review, not jump to other sequences.

**Comment by de-vries** [comment]
This feature is already there, but it's a bit hidden in the edit section.

here it is:
![selectie_125](https://cloud.githubusercontent.com/assets/1449609/15583943/52d87662-2378-11e6-9779-ddda10db9e25.png)

**Comment by nighto** [comment]
Great, didn't realized it. Thanks!!
