### ISSUE TITLE
When first image from sequence is deleted, link to sequence on profile is broken

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1894]
I uploaded a sequence and asked for deletion of some pictures. The link on my profile page keeps pointing to the first image of the sequence (the deleted one), which is broke.

![image](https://cloud.githubusercontent.com/assets/397851/15616552/fc3da892-241a-11e6-8b47-9b7043214c5f.png)

Broken image links to: http://www.mapillary.com/map/im/4lA-UG6UcO7r7GTEhzR7OQ , which says "Image not found".

Should the link to sequence point to the first available picture of the sequence?

**Comment by ybkuang** [comment]
@gyllen will this aftermath of deletion disappear automatically?

**Comment by gyllen** [comment]
We no longer have this profile view
