### ISSUE TITLE
Wrong sequence frequency

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#1895]
I am setting a 10/10 sequence photo delay (to take a picture at each second).
But I see one problem:

![](https://cloud.githubusercontent.com/assets/982338/15622300/c949f990-243d-11e6-9408-441c64a5d0ce.png)

Note that if I click to set a delay, it displays 10/10 at Settings but 13/10 at the option.

**Comment by echeloni2p** [comment]
And how often is it taken in reality? Which mobile, which settings?

echelon

**Comment by naoliv** [comment]
Didn't test the real frequence.
What I set and what I see after setting is:

```
 5/10 →  8/10 (differ by +3)
 6/10 →  9/10
 7/10 → 10/10
 8/10 → 11/10
 9/10 → 12/10
10/10 → 13/10
11/10 → 13/10 (differ by +2)
12/10 → 14/10
13/10 → 14/10 (differ by +1)
14/10 → 15/10
15/10 → 16/10
16/10 → 17/10
17/10 → 18/10
18/10 → 19/10
19/10 → 20/10
20/10 → 21/10
21/10 → 21/10 (stay the same)
22/10 → 22/10
23/10 → 23/10
24/10 → 23/10 (differ by -1)
25/10 → 24/10
26/10 → 25/10
27/10 → 26/10
28/10 → 27/10
29/10 → 28/10
30/10 → 29/10
31/10 → 29/10
32/10 → 30/10 (differ by -2)
33/10 → 31/10
34/10 → 32/10
35/10 → 32/10
36/10 → 33/10 (differ by -3)
37/10 → 34/10
38/10 → 35/10
39/10 → 36/10
40/10 → 37/10
41/10 → 37/10 (differ by -4)
42/10 → 38/10
43/10 → 39/10
44/10 → 40/10
45/10 → 41/10
```

mapillary is 2.13, phone is a Moto G second generation with Android 6.0

**Comment by rsahlin** [comment]
This is a visual bug in the slider component, we will look into this.

The camera will still try to capture one picture every second.
Please note that the sequence delay is a lower limit, if your phone is slower then your fastest rate will be higher than the selected value.

Thanks for reporting
Best regards
/Richard

**Comment by naoliv** [comment]
While at it, isn't it better to represent the value in seconds instead using a fraction?
For example `1 sec` is better than `10/10 sec`, `2 sec` better than `20/10 sec`. Even `0.5 sec` is better than `5/10 sec`, for example.

**Comment by polarbearing** [comment]
> value as a real number instead using a fraction
In some other issue the devs said they only found a slider widget with integers, not float. 
But even a slider is more fiddle to adjust than just typing two numbers.

**Comment by rsahlin** [comment]
Hi 

A new version (>=2.33) is on it's way out to Beta group within a day or two - this should fix the issue with wrong number on the slider as well as add a decimal value for second delay.
It will be available in a day or two.

Best regards
/Richard
