### ISSUE TITLE
automaticly recognize unclear pictures

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1898]
Hi!

After my bicycle trip today (a lot of shitty roads in the hills) some pictures in the tracks are blurred and shaky and not clear enough.
Can mapillary have a automatic recognition system to detect those images per track and show the user as a tip/idea to "hide these shown images" on one click?
Or make a list like the upload tab and let user select the images to remove from track...

But main part is to automaticly recognize and tag the blurry pictures per track and react on those in some way.

echelon

**Comment by ybkuang** [comment]
@echeloni2p That's a good idea. We had some tests in the earlier days for automatic blur detection. We will work more on this in the near future.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
