### ISSUE TITLE
ERROR_CAMERA_IN_USE while shooting a sequence

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1899]
CAMERA ERROR a little after 4:30 pm while shooting a sequence. Can't shoot any more unless I reboot my phone. 

I'll email logs on this in just a bit. 

Mapillary 2.13, Android 6.0.1, Samsung Galaxy S7 edge

**Comment by jfburke3** [comment]
I still need to send in the logs, but to update this:  disabling Camera2 API allowed me to use the camera again.  Then, I reenabled it, and was still able to use the camera.  So toggling it eliminates the need to reboot.

**Comment by jfburke3** [comment]
Attaching logs.  Sorry for the size, I kept forgetting to start new ones over the past few days.

[mapillary-logs.zip](https://github.com/mapillary/mapillary_issues/files/288700/mapillary-logs.zip)

**Comment by rsahlin** [comment]
Camera is disconnected from app with error 1 which means ERROR_CAMERA_IN_USE
I cannot see a reason for this, according to Android documentation the error may be reported when trying to open the camera and it is already in use.
Here it happens in the middle of a sequence, ie the camera is already open.
Will need to be investigated.
