### ISSUE TITLE
Where is the aim point? 

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#1900]
I'm not sure where the aim point is supposed to be now.  Is it the white dot or the center of the picture? 

I'll attach a screen shot showing what I mean in just a bit. 

Mapillary 2.13, Android 6.0.1, Samsung Galaxy S7 edge

**Comment by jfburke3** [comment]
Adding screenshot.

![screenshot_20160529-163340](https://cloud.githubusercontent.com/assets/11140831/15637911/37c5973e-25e8-11e6-9e4a-ca040a3a39b0.png)

**Comment by rsahlin** [comment]
Hi @jfburke3 

Agreed, the white dot is in the center of the screen as opposed to center of the image.
As far as I know I have not made any changes to the code to put the aim-lines on the screen.
My guess is that this is the same as 1.85, I'd like to save this until we do a complete makeover of the UI.

Please let me know if you disagree

Best regards
/Richard

**Comment by jfburke3** [comment]
Nope, that's fine.
