### ISSUE TITLE
Uploading Of Video Not Visible On Mapillary

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary_issues#1903]
I uploaed a video manuall onto Mapillary on the 21/05/2016 (User Name: Esssex_boy) and I see no evidence of any sequence on Mapillary. The file was approximately 1.3gb and I beleive the sequence would have passed over a cycle path located at N52.16919 E4.49707.

I used a Garmin VIRB to record the video that was uploaded.

**Comment by gyllen** [comment]
It should be on the way now, thanks for reporting this. Keep us posted if it does not show up.

**Comment by PaulColinSimpson** [comment]
No problem....glad to help. I'll let you know in a day or so if it doesnt appear.

**Comment by Caboosey** [comment]
I uploaded a 1080p video on June 4, 2016 near Molino, Florida, United States and I believe it's still stuck in processing and I don't see it on the map or in my sequences section.

**Comment by gyllen** [comment]
@ybkuang Whats the latest on this?

**Comment by ybkuang** [comment]
@Caboosey @PaulColinSimpson @gyllen I am still investigating. Will get back to you guys later. Sorry about the delay.

**Comment by ToeBee** [comment]
I uploaded 3 or 4 videos last week that haven't shown up yet either. I will hopefully be uploading a bunch more this weekend since I'm temporarily on Google fiber :)

It would be awesome if we could at least see the file names that we've uploaded in some kind of pending page. Sometimes I forget which videos I've finished uploading so I may have uploaded a duplicate somewhere without realizing it.

**Comment by gyllen** [comment]
@ybkuang This is solved now right?

**Comment by ToeBee** [comment]
Well my videos are certainly starting to show up on the map.

**Comment by ybkuang** [comment]
@ToeBee @gyllen Yes. I think we've fixed the problem. New videos should go through and we will need to set up a process for the old videos uploaded during the bugs existed. More instructions will come soon! Sorry about the inconveniences.

**Comment by ToeBee** [comment]
Are there still some videos clogged up in processing somewhere? I see some gaps on the map that I'm pretty sure I uploaded videos for last weekend.

Example: The stretch between Dodge City and Ford:  http://www.mapillary.com/map/search/37.687316989915914/-99.85070864102532/11

It would have been a video file named `GP010001.MP4` associated with a GPX file named `activity_326090450.gpx`

And I see a few others. I'm hoping identically named video files from later days didn't overwrite previous ones or something like that?

**Comment by ToeBee** [comment]
Any news on the gap I mentioned above? Do I need to re-upload or might they still come online? There are several others:
* [Montezuma](http://www.mapillary.com/map/search/37.57484491264489/-100.43057943294926/11) 
* [Mullinville](http://www.mapillary.com/map/search/37.585114907220856/-99.49313195158521/13)
* [West of Greensburg into town](http://www.mapillary.com/map/search/37.588743733216646/-99.32139720270153/14)
* [Coldwater](http://www.mapillary.com/map/search/37.28631527799341/-99.32319327198338/13) (note that the gap a bit north of Coldwater is *not* a mistake. I was drafting someone on the bicycle for that stretch so the view was... umm... "sub-optimal" for mapping :)

**Comment by gyllen** [comment]
@ybkuang Let me know what I can do to help you here.

**Comment by ToeBee** [comment]
I'm still waiting on the last of my videos to get through the queue but it looks like there are about 10 videos that should have appeared on the map by now but seem to have been dropped/delayed after I uploaded them. Basically, there should be a mostly solid line through southern Kansas. I think there are 3 legitimate gaps where I didn't record or didn't upload for some reason. The rest of the route should have coverage.

**Comment by ToeBee** [comment]
It seems like someone found some old videos laying around today. I just noticed a bunch of sequences showing up in my news feed today and they appear to be from these missing videos. Of course I had given up on these videos from July and have re-uploaded most/all of them so now I there are duplicate sequences. Example:  
https://www.mapillary.com/app/?pKey=9nCluWZgZWZ_yPrvd1ljAQ  
https://www.mapillary.com/app/?pKey=vtrcPEwVJZ6UyK7BvC4o0A

**Comment by ybkuang** [comment]
Indeed, we did some re-processing of the failed videos in the pass few days. You can request deleting the duplicate ones. Sorry for the inconvenience.

**Comment by ToeBee** [comment]
It is kind of hard to tell for sure if they are duplicates. Since the photo points on the map are in **exactly** the same position, you can't see it visually. Might have to dive into the JSON responses and pick out the sequence IDs.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
