### ISSUE TITLE
Too many photos on Android app makes the review screen painfully slow

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1904]
This weekend I went on a road trip from Rio de Janeiro to São Paulo, so it was a great opportunity to take some pictures because I don't drive. I shoot 2x ~10k pictures with two cellphones, attached on front and side windows of a bus like this:

![image](https://cloud.githubusercontent.com/assets/397851/15658984/dcc5077c-2699-11e6-843f-709c81cd5fad.png)

Anyways, my point is: having 10k photos makes the app painfully slow to open and scroll on the review screen, showing your sequences. Once you click on a sequence, scrolling through the sequence is ok. Also, no problems on capturing images.

It looks like it's trying to create a thumbnail cache for each image on the folder, just to pick the first one.

**Comment by rsahlin** [comment]
Hi @nighto and thanks for your report

Yes, the review activity is too slow - I believe we already have an issue for this #1864 
Please have a look and make sure this is the same, if not please re-open this issue whith an explanation why you think it is not the same.

Best regards
/Richard

**Comment by nighto** [comment]
Sorry @rsahlin, couldn't find that issue. It is exactly the same problem.
