### ISSUE TITLE
Failed to load resource: the server responded with a status of 401

### ISSUE THREAD

**Issue by aborruso** [mapillary/mapillary_issues#1906]
Hi,
when I try to open [this URL](https://www.mapillary.com/map/im/v8V9g4taTfNd_RhdJcuD_A/map) I have a gray map.

![image](https://cloud.githubusercontent.com/assets/30607/15669605/84c2798c-2721-11e6-8ab3-49bfbf103a2d.png)

If I open the console I have this kind of error:

![image](https://cloud.githubusercontent.com/assets/30607/15669525/059fb6e2-2721-11e6-91dc-887cec015b0a.png)

What do you think about?

**Comment by knikel** [comment]
@aborruso: Is this still an issue? We had a short server hiccup yesterday.

**Comment by aborruso** [comment]
Hi @knikel today it's same.

The strange thing is that in two PC I can view the map, in another two I cannot. All the PCs are inside the same LAN, but two have Win10 and two have Win8 (these give this problem).

I have tested all with the latest versions of Chrome and Firefox.

**Comment by knikel** [comment]
Thanks, will investigate that.

**Comment by knikel** [comment]
Since then we've got many iterations of the viewer. Do you still have similar problems @aborruso? It seems that must've been a server hiccup at the time. Please reopen if something similar happens in the new viewer.

**Comment by aborruso** [comment]
@knikel It's the same. I have opened an anonymous session of chrome in Windows 10, and I have always a gray map.
Without any error in console.

![image](https://cloud.githubusercontent.com/assets/30607/18701975/e6ebc6ce-7fdf-11e6-91fb-0c2e0f095d5d.png)

**Comment by knikel** [comment]
Thanks @aborruso for the feedback. Does this happen in non incognito mode as well?

Could you post a screenshot of whether you have some failed requests in the network tab after opening the DevTools?

Open DevTools -> Click _Network_ -> Refresh page

**Comment by aborruso** [comment]
@knikel yes the same also when not in incognito mode.

Here a screencasting http://somup.com/cDQrjhCYi

**Comment by knikel** [comment]
Thanks, I'm looking into that!

**Comment by knikel** [comment]
@aborruso: I've added a possible fix for that last week. It seems for some reason your laptop doesn't play well with `mapbox-gl-js`. Could you check if it helped?

Details: I've added `pitch: 0.01` to the map as described in https://github.com/mapillary/mapillary_issues/issues/1725

**Comment by aborruso** [comment]
Now it works. But I must run chrome with:

    chrome --enable-webgl --ignore-gpu-blacklist
