### ISSUE TITLE
Image did not reach version 1

### ISSUE THREAD

**Issue by paulinus** [mapillary/mapillary_issues#1911]
This image http://www.mapillary.com/map/im/8H4tz-wBbwelQz7Nnbm7Bg/photo mentioned in #1217 and other in that sequence seem to be in a weird state. No sfm features and version is 6.

**Comment by ybkuang** [comment]
Yes. It is strange. I will do a rerun on that sequence later and check.

**Comment by paulinus** [comment]
solved
