### ISSUE TITLE
Typos in Spanish translation of iOS app

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1915]
When I select the manual mode in the new camera UI, it says "Usa esto modo para capturar panoramas, objectos, fachadas e interseccines." There are several mistakes in that text; it should say: "Usa **este** modo para capturar panoramas, **objetos**, fachadas e **intersecciones**."

The other mode descriptions are fine, except the word "automaticamente" should be written "automáticamente" (acute accent).

**Comment by millenbop** [comment]
Thanks, fixed now, should be correct in the next release.
