### ISSUE TITLE
Dealing with backdrift at stops with geolocated images

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_issues#192]
When a GPS unit comes to a stop it will tend to have its reported position drift backwards by 1-2m. This can be problematic for computing direction from the GPS trace.

![image](https://cloud.githubusercontent.com/assets/1190866/3453011/09907d8e-01be-11e4-8ef7-27f4f20c57f7.png)

Are there any good ways for dealing with this? I'm using [gpx2exif](https://github.com/craigtaverner/gpx2exif) but I could change that part of my toolchain.

I don't even *really* need to be uploading all of these photos, they're all from the same location with the same angle. All that changes is what is blocked by cars crossing the road in front of me.

**Comment by gyllen** [comment]
How do we solve this @jesolem. Its still a valid issue.

**Comment by dymo** [comment]
I usually go through the pictures before uploading and delete some of the extra pictures from when I stopped for red light or similar, which made me think that it should be possible to use OpenCV to detect that the camera is not moving and find some cleaver way to pick the best picture and discard the rest. With the best picture being the one with the least traffic moving across.

While I have been thinking about this for several months, I have not had the time (been too busy collecting pictures) to actually experiment with the idea and I was kind of hoping somebody else would beat me to the punch :smirk:

I think the problem can also be solved with [OpenSfM] (https://github.com/mapillary/OpenSfM).

**Comment by jesolem** [comment]
@gyllen I think we should look at this in IP (image processing). If matches say image is essentially the same and taken from same location, we update the location. 

This will be fixed "automagically" once we have OpenSfM fully integrated in the pipeline.

**Comment by gyllen** [comment]
Yes, I gonna close this issue since OpenSfm is just around the corner.

@dymo See http://blog.mapillary.com/update/2014/12/15/sfm-preview.html and https://github.com/mapillary/OpenSfM
