### ISSUE TITLE
Android app: tilt angle is not refreshed while in auto mode

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#1921]
I noticed that in auto modes ("Walking, auto shot" and "Riding") the tilt angle doesn't update anymore once a sequence is started. That might makes sense when the phone is mounted on a stable platform, but it makes the "Pause while tilting" setting pretty useless when the phone is held manually.

I suggest to reenable the old behaviour in "Walking, auto shot", while the  "Pause while tilting" option is enabled. That is:
- a sequence can always be started, even when the phone is tilted. The capture will automatically start as soon as the tilt angle is correct;
- the tilt angle is constantly updated, and the shooting paused when tilt angle is out of range

Considering that even for a phone on a stable mount, it could happen that the inclination is changed accidentaly,  I would consider the same also in "Riding" mode. Unless there are good reasons to keep the current behaviour (for example to save time or processing power).

**Comment by kaitu** [comment]
#1611

**Comment by rsahlin** [comment]
Please retest with 2.20, or later, release - this is one of the bugs that is fixed.

**Comment by kaitu** [comment]
Great, tested with 2.20 and tilt refresh works flawlessly now.

The bug with the right tilt being ignored (#1611), is still there, by the way.

**Comment by rsahlin** [comment]
Hi @kaitu and thanks for pointing out the other issue to me :-)

I have assigned myself to that issue and will look into it in the future.

/Richard
