### ISSUE TITLE
Android app: provide better feedback that a picture has been shot

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#1922]
When shooting in auto walking mode, I like change the aim to a different subject as soon as I know that a picture has been shot. Unfortunately, it is currently too difficult to understand that a picture has been shot:
- the audible warning is inaudible in noisy environment. It's also unwanted in some shooting conditions;
- the picture counter is too small, and it's practically impossible to read it's increase under sunlight.

I'd like a much more prominent feedback when a picture has been shot.

I suggest to make (possibly optionally) the whole screen flash at maximum brightness each time a picture is shot. I seem to recall that the app used to behave this way (might be wrong here).

**Comment by katrinhumal** [comment]
Took a while but there is the flashing screen function in the app today that signifies taking photos. Can be turned on/off in settings. :)
