### ISSUE TITLE
Mapillary https wildcard cert expired

### ISSUE THREAD

**Issue by bhousel** [mapillary/mapillary_issues#1923]
I'm getting failures now testing the Mapillary JS viewer.  Looks like your cert just expired an hour ago!

<img width="468" alt="screenshot 2016-06-06 20 34 44" src="https://cloud.githubusercontent.com/assets/38784/15842340/23dd8d00-2c26-11e6-8b96-99bcbf6a90bc.png">

**Comment by bhousel** [comment]
This looks to be fixed now, thanks!

**Comment by peterneubauer** [comment]
Thanks @bhousel, oversight from our side, fixed.
