### ISSUE TITLE
Sequences Not Rendered on Mapillary Map

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary_issues#1926]
from https://github.com/mapillary/mapillary-js/issues/140 :

> There is a sequence I recorded and uploaded to the Mapillary server (User: essexboy) at location N51.64276 E0.03465 on the A104 Epping new road. This however is not rendered in green on the map but the sequence is available to view if you select this part of the road.

**Comment by knikel** [comment]
@PaulColinSimpson: When was the sequence uploaded? If it has been a recent contribution to Mapillary, then perhaps our tile server hasn't processed the data yet. If the sequence has been uploaded some time ago, we'll need to investigate further. Adding a lat/lon/zoom [link](http://www.mapillary.com/map/search/51.64276/0.03465/15) for the future reference.

**Comment by PaulColinSimpson** [comment]
Yes...... this was a sequence that was uploaded over a month ago. All the other sequences I uploaded appeared but not this one.

**Comment by knikel** [comment]
@PaulColinSimpson: Do you happen to have one photo that belongs to it at hand and could send a link to it? That would help a lot. Thanks!

**Comment by PaulColinSimpson** [comment]
Hi Kamil.....here is a link to one of the photos http://www.mapillary.com/map/im/fMQ4j_1Pv-r4x2hXjRlOFQ/photo

All the best and if you need anymore information just let me know

Paul

Date: Tue, 7 Jun 2016 02:02:30 -0700

**Comment by talllguy** [comment]
Here is another one with this issue. I took these on June 10, and uploaded on June 14, but these don't show in my profile after 24 hours, which is normally when things start to appear. http://www.mapillary.com/map/im/fpM5r8q3lDRwzuwVupvBXQ/photo

**Comment by gyllen** [comment]
@talllguy This still valid?

**Comment by talllguy** [comment]
@gyllen Looks like the system is speeding along at normal speed now.

**Comment by polarbearing** [comment]
I also noticed that sequences are missing that I uploaded in May. They show up in the my Activities, but do not appear on the uploads/profile page, and do not appear when I load the area in JOSM.

What makes it extremely hard to keep track of them is the user-unfriendly presentation of both pages. I only see the endless list of first images with no concise, human-readable references, such as timestamps. If you could provide such a list, maybe with a tick mark or time stamp that the sequence has been added to the map, that would help a lot, example (timestamps fictive):
```
Sequence start -- Upload finished -- On the map -- Sequence link -- location link
2016-05-01 13:55 -- 2016-05-12 23:20 -- 2016-05-13 03:25 -- fpM5r8q3lDRwzuwVupvBXQ -- N55.2222, E33.4444
```

**Comment by knikel** [comment]
I'm closing this since tile generation happens independently from processing image data, and the system usually catches up after a short period of time. @polarbearing's suggestion about better UI for sequence preview is tracked in #1974.
