### ISSUE TITLE
Possible use of deprecated camera API

### ISSUE THREAD

**Issue by martiensch** [mapillary/mapillary_issues#1929]
I am using a Google Nexus 5X. All images I shoot with mapillary are rotated 180 degrees. The issue might be the result of the camera API ([source](https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/cwqzqgh))

**Comment by rsahlin** [comment]
Hi @martiensch and thanks for your report

Could you please check what version of Mapillary you are using - the version number should be 2.16 or above.
To check, go into 'Feed' - 'Settings' and it's located at the bottom.
Please also make sure that you have the 'Use Camera2 API' checked in settings.

Thanks
Best regards
/Richard

**Comment by martiensch** [comment]
Hi @rsahlin 
I was late with my report. It has been fixed between my last sequence (May 1) and my bug report. Great!!
