### ISSUE TITLE
does deleting photos before upload lead to mismatch between photo and track?

### ISSUE THREAD

**Issue by dekarl** [mapillary/mapillary_issues#1932]
When going through the last uploads it appears as if deleting photos before upload lead to jumps in the photo<->position lists.
Here are two sequences where I deleted photos, like excessive amounts of photos at red lights / intersections. The links go to the last photos where picture/position still match (more or less)

http://www.mapillary.com/map/im/l81pyNDf4facekHZnuYgHA/photo
^- this is basically three long straight legs going south (on bridge), west (industrial district), then north (highway).

http://www.mapillary.com/map/im/pV3vS3wKX7h6Kka7abk98A/photo
^- after the photo there are two straight legs, first going north west, then north east. Notice how the location only starts to change at the end of the sequence.

**Comment by nicolas17** [comment]
How did you take/delete/upload the pictures? It makes a big difference if you did it all from a smartphone or if you used an external camera.

**Comment by millenbop** [comment]
Which platform are you using, Android or iOS or using web/scripts?

**Comment by dekarl** [comment]
iOS 7, photos taken by, deleted on and uploaded from the phone

**Comment by millenbop** [comment]
Deleting photos is always safe as the GPS position etc is saved in the image already. For some reason you have experience GPS lag. I'm redoing the camera implementation so hopefully it won't be an issue in the future.

Do you want us to delete the sequences in the mean time?

**Comment by dekarl** [comment]
Sure, just delete the last four sequences from http://www.mapillary.com/profile/dekarl

**Comment by millenbop** [comment]
I have added your sequences to the deletion list and someone will get to it as soon as possible.
