### ISSUE TITLE
No Rendering On Mapillary Map For A Number of Sequences

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary_issues#1935]
There are 2 locations on the Mapillary map where there is a sequence yet no rendering that a sequence exists there- the locations can be found at:
- https://www.mapillary.com/map/im/u2bTHmkv4HuTu_8Jn9BldQ/photo
- https://www.mapillary.com/map/im/IvV1Th7zaf8KLNVG-Ud6Jg/photo

**Comment by PaulColinSimpson** [comment]
I have checked Mapillary oday and these sequences still do not appear rendered on the map.

**Comment by stonor** [comment]
I see this behavior as well with my latest uploaded sequences:

https://www.mapillary.com/app?pKey=gg5U58MnC-LK4Q9Sxs80Kw&focus=map
https://www.mapillary.com/app?pKey=tJB01MykvPrN33-RTNkLmg&focus=map
https://www.mapillary.com/app?pKey=ufipVdglB86QsYSPV1tDcw&focus=map
https://www.mapillary.com/app?pKey=ND84q7gs1JrdQDn0SZi7PQ&focus=map
https://www.mapillary.com/app?pKey=TPtDYIx57-aNcNX-7iPtKQ&focus=map
https://www.mapillary.com/app?pKey=oNYdgkaoj4f87gpmT18mYQ&focus=map
https://www.mapillary.com/app?pKey=axVfzJ3HzHFDIXC8TpKqmw&focus=map

**Comment by gyllen** [comment]
@stonor We had an error of some of the updating of the tiles the 16th and 17th of August. It will very soon be updated. Sorry for the inconvenience.

@ptpt Can we rerun these tiles today?

**Comment by ptpt** [comment]
@PaulColinSimpson the 2 sequences are not complete in our databases. Tracked internally and will fix when we switch to the new database.

@stonor the sequences are all rendered.
