### ISSUE TITLE
Preview not showing the same as image capture

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1938]
The image capture is not the same as what is shown in the preview.

**Comment by rsahlin** [comment]
![screenshot_2016-06-10-14-44-20 1](https://cloud.githubusercontent.com/assets/3063192/15964479/05d15eb8-2f19-11e6-9f0d-0c0e0b3937ec.png)
![15963](https://cloud.githubusercontent.com/assets/3063192/15964530/435e090c-2f19-11e6-872c-20427dced6ab.jpeg)

**Comment by rsahlin** [comment]
Attached log with the relevant part
The chosen preview size is 2592, 1944
Size of preview texture is 1836, 1030
Set preview rotation to 270, screenrotation: 90, preview size: 2592, 1944 scale: 0.5610022, 1.3333334

06-09 21:24:40.020 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): onSurfaceTextureAvailable(1836, 1030), STATE=CLOSED
06-09 21:24:40.020 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): internalOpenCamera() - opening camera
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 160, 120 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 176, 144 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 320, 240 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 352, 288 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 640, 480 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 720, 480 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 800, 600 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 1024, 768 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 1280, 960 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 1600, 1200 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 2048, 1536 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 2592, 1944 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 3264, 2448 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4160, 2340 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4000, 3000 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4160, 3120 outside range: 9.5, 1.7825242, 0.15
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4160, 2340 above 9.5 mpix
06-09 21:24:40.021 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4000, 3000 above 9.5 mpix
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Skipping outputsize 4160, 3120 above 9.5 mpix
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Chosen output dimension: 4096, 2160
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Choosing thumbnail with diff: 0.09, for output: 4096, 2160
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 0, 0
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 176, 144
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 256, 154
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 320, 240
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 432, 288
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 480, 288
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 512, 288
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 0, 0
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 176, 144
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 256, 154
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 320, 240
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 432, 288
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 480, 288
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Choosing thumbnail with diff: 0.15, for output: 4096, 2160
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 0, 0
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 176, 144
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 256, 154
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 320, 240
06-09 21:24:40.022 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 432, 288
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 480, 288
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Thumbnail: 512, 288
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 0, 0
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 176, 144
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 256, 154
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 320, 240
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 432, 288
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Discarded thumbnail with size 480, 288
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Chosen thumbnailsize: 0, 0
06-09 21:24:40.023 D/app.mapillary.android.capture.Configuration(11911): Chosen preview size: 2592, 1944
06-09 21:24:40.023 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): openCamera with id: 0
06-09 21:24:40.074 I/CameraManager(11911): Using legacy camera HAL.
06-09 21:24:40.227 D/app.mapillary.android.sync.UploadService(18100): sleeping. failed: 0, success 6, total 13
06-09 21:24:40.532 D/MapboxEventManager(11911): No events in the queue to send so returning.
06-09 21:24:40.763 D/app.mapillary.android.capture.BaseCameraCaptureDevice(11911): Changing state to OPENING, reason 0
06-09 21:24:40.763 D/app.mapillary.android.activity.CameraActivity(11911): onStateChanged for device CAMERA2_0, OPENING
06-09 21:24:40.767 D/app.mapillary.android.camera.PreviewTextureView(11911): size: 1836, 1030
06-09 21:24:40.767 D/app.mapillary.android.camera.PreviewTextureView(11911): Set preview rotation to 270, screenrotation: 90, preview size: 2592, 1944 scale: 0.5610022, 1.3333334
06-09 21:24:40.950 D/app.mapillary.android.location.MapillaryLocationTracker(11911): connected to GMS
06-09 21:24:41.028 I/Choreographer(11911): Skipped 60 frames!  The application may be doing too much work on its main thread.
06-09 21:24:41.132 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): onOpened() for 0 state=OPENING
06-09 21:24:41.133 D/app.mapillary.android.capture.BaseCameraCaptureDevice(11911): Changing state to OPENED, reason 0
06-09 21:24:41.133 D/app.mapillary.android.activity.CameraActivity(11911): onStateChanged for device CAMERA2_0, OPENED
06-09 21:24:41.133 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): internalStartPreview(), state=OPENED
06-09 21:24:41.138 D/app.mapillary.android.capture.BaseCameraCaptureDevice(11911): shallStartPreview() app.mapillary.android.camera.PreviewTextureView{285b3c8d V.ED.... ........ 0,0-1836,1030 #7f0f0095 app:id/preview}, 2592, 1944, android.graphics.SurfaceTexture@1d59ee42, OPENED
06-09 21:24:41.138 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): Set preview surfacetexture to 2592, 1944
06-09 21:24:41.168 I/CameraDeviceState(11911): Legacy camera service transitioning to state CONFIGURING
06-09 21:24:41.168 I/RequestThread-0(11911): Configure outputs: 2 surfaces configured.
06-09 21:24:41.169 D/Camera  (11911): app passed NULL surface
06-09 21:24:41.179 I/RequestThread-0(11911): configureOutputs - set take picture size to 4096x2160
06-09 21:24:41.227 D/app.mapillary.android.sync.UploadService(18100): sleeping. failed: 0, success 6, total 13
06-09 21:24:41.259 I/CameraDeviceState(11911): Legacy camera service transitioning to state IDLE
06-09 21:24:41.287 D/app.mapillary.android.camera2.capture.Camera2CaptureDevice(11911): Setting control modes: CONTINUOUS_PICTURE, ON, AUTO

**Comment by measles** [comment]
I'm having this issue at tha moment (thanks @rsahlin for reporting). The device is Lenovo Pb1-770M.

If it necessery I'm ready to prvide additional information or try some new version.

Thank you!

**Comment by measles** [comment]
Switching on/off Camera 2 doesn't helps.

**Comment by rsahlin** [comment]
Hi @measles 

The bug comes from not finding a preview size that matches the aspect ratio of the output (photo) dimension.
This makes the program select the first dimension available - in this case it is much larger than the screen size.

I have added some leniency (9%) to the aspect ratio between preview and photo and also make sure that the last case is selecting a preview size that fits within the screen. 
Though if this still fails I have added some more debug info :-)

Could you please download and install app-release_221-SNAPSHOT.apk from
http://android-releases.mapillary.io/index.html

and let me know what the outcome is?
Thanks for your help!

**Comment by measles** [comment]
Sure, I'll do it right away and update you with a results

**Comment by measles** [comment]
It's perfect now! I capture what I see.

Thank you! I will use that version untill it made it to mainstream.

**Comment by rsahlin** [comment]
Hi @measles - great that it works!

Could you please start the camera and send the debug logs?
This so that I can fully understand how the phone behaves after the fix.

I will promote 2.21 during the day - please check with Google Play tomorrow for the release version.
(As you probably know you will need to re-install to get the release version and updates)

Best regards
/Richard

**Comment by rsahlin** [comment]
I have to reopen this issue - I made the mistake of using screen ratio when choosing the preview.
Instead, the ratio shall be based on the output picture dimension.

I think that you may find that while the preview fills the entire screen there is probably a diff between what is shown and what gets capture.

I am uploading app-release_221.apk to http://android-releases.mapillary.io/index.html - could you please retest with this version?

Thanks for your help!

**Comment by measles** [comment]
Now the picture is definitely show what I'll got. But there is one strange effect: while I force a low resolution in settings the picture will not cover the whole screen, but it will be nicely aligned to the center. In case while I leave this options intact or force hight resolution the picture will looks more like 3:4 ratio and allighned to the left, so at right side of screen I have grey area.

Seems that preview is corrrect in all the cases, but when picture is centered it's more convenient. For example, It's easier to allign a phone before the shooting session using these white level marks on preview. 

@rsahlin, do you need some screenshot or logs from me?

Thanks for a such intence working on the issue. It's very nice to feel that you have support from the dev team.

**Comment by rsahlin** [comment]
Hi @measles and thanks for checking so quick :-)

Hmmm, the preview _should_ be left aligned. 
Though the most important thing is that it's WYSIWYG - there should be no diff between photo captured and the preview.
If I add some debug logs to find the reason for centering, could you run it and send me the logs?

- You have a point regarding centering the preview when it is smaller than screen size.
I guess we should add an option to have it left or horizontally centered, I'll add one right away....
issue #1942

Our goal is to fix issues that are preventing photo capture as quickly as possible and it helps a lot to get good feedback from users such as yourself.
Thanks!

Best regards
/Richard
