### ISSUE TITLE
Mapillary Base-map does not work in manual uploader

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1939]
![image](https://cloud.githubusercontent.com/assets/1827881/15980756/d479b0f4-2f3b-11e6-95ea-dcd474582dec.png)

For reference, Mapbox:
![image](https://cloud.githubusercontent.com/assets/1827881/15980769/f136f0d0-2f3b-11e6-86c3-494fb503db1d.png)

**Comment by gyllen** [comment]
Fixed in new uploader (right now you can't select basemap but that feature is coming soon)
