### ISSUE TITLE
Panorama with external cameras / separate upload

### ISSUE THREAD

**Issue by d97jro** [mapillary/mapillary_issues#194]
peterneubauer said: Argh, dåligt med GPS verkar det som. Mina bilder är tagna med en Android Xperia Z1, funkar mycket bra. Om du kör med webupload kan du just nu inte säga att det panoramas, men det kanske vi borde lägga till! Tillsammans med att ändra compass angle i editor borde man kunna ändra capture mode i editorn. Kan du göra en issue under https://github.com/mapillary/mapillary_issues/issues ?

best,
/Jan Erik, Yubin, Johan and Peter (The Mapillary team)

**Comment by gyllen** [comment]
This should be checked in EXIF, closing
