### ISSUE TITLE
Images appear small but in blur mode

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1940]
In the following sequence, images are displayed tiny when viewing/playing the sequence. In edit/blur mode they appear normally.

http://www.mapillary.com/map/im/sEogzahUKiBDXPy0B5w3Ig/photo

I don't get why.

**Comment by oscarlorentzon** [comment]
@shlublu Thanks for reporting. What device and app version did you capture this sequence with?

**Comment by shlublu** [comment]
Hi,

These are pictures taken with the Camera app of a Galaxy S5 and uploaded manually after having been located with Xifer.net.

**Comment by oscarlorentzon** [comment]
Thanks.

**Comment by oscarlorentzon** [comment]
This will be tracked in mapillary/mapillary-js#146.

Closing it here.
