### ISSUE TITLE
Android app geolocalisation: takes ages compared to some other apps, why?

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1941]
GPS fix takes ages to stabilize on the Android app. I'm running the latest stable version on a Galaxy S5 / Android 21 (Android 5).

The accuracy is stuck (usually at 96m or 30m) for minutes, and sometimes never stabilizes under 15m at all so I end up using my camera instead of the app. Images are better but have to I fix the location manually before uploading the pictures - this is a time-consuming process and pictures have no orientation.

I initially though the GPS fix issue was coming from my device, or was caused by the fact I'm in a city, but with some other apps (Navmii, Uber, ...) I have an excellent accuracy quite quickly in the same places. Could this come from the algorithm that is used to estimate the accuracy or to some accuracy error mitigation routines these apps would used?

**Comment by rsahlin** [comment]
Hi @shlublu 

The Mapillary app subscribes to location updates just as any other app would do, there is not much we can do.

I am not sure what apps such as Uber and Navmii consideres to be excellent accuracy - for Mapillary the reported accuracy should be <= 8 meters.
Maybe apps such as Uber consider 30 meters to be good accuracy?

Please make sure that you have Google Mobile Services enabled - go into 'Feed' - 'Settings' and check 'Use Google Mobile Services'

If you still fail to get location fix you can disable location check in Mapillary by going into 'Settings' and check 'Skip location check'

Hope this helps!

Best regards
/Richard

**Comment by shlublu** [comment]
Hi @rsahlin and thanks for the feedback.

Actually, I could determine that Navmii and Uber are really accurate by comparing my poition as displayed on the map to my actual physical position while walking. But these apps do rate their own accuracy. So it may happen that the Mapillary app tells me the accuracy is bad while the spot is actually good... I can't determine that (but by viewing uploaded sequences that show that usually, with 15 meter, the spot is actualy somewhere in between 0 and 15 meters from the target).

Use Google Mobile Services is activated, yes. Just for testing I'll try to disable it, in the (unlikely) case it would somehow slow down or corrupt the measure.

Thanks a lot anyway!

**Comment by rsahlin** [comment]
Please let me know if you have any more information and data related to this.

In the meantime I will close this issue.

Thanks!
/Richard

**Comment by shlublu** [comment]
Will do, thanks @rsahlin.
I'll drop a comment here should I find anything relevant.

**Comment by shlublu** [comment]
Hi! 

A few more data: I thoroughly used the app during the past three weeks. 

Each time I had GPS fix issues with the Mapillary app I compared with "GPS Data" (free version, v 3.3.6, publisher: "Propane App"). My cellphone was always in flight mode to save battery: no wifi, no 3G.

The outcomes follow:

- Typically, I used to get a decent GPS fix  (accuracy << 25m) with "GPS data" within 1 to 5 minutes. Mapillary, on its side, was still showing a red icon (usually 90~99m) or a gray icon (no fix) after 20 minutes and 20~25% battery.

- It happened many times that I could precisely locate me on "Mapfactor Navigator" (an offline GPS map app), with an pretty good fix ("GPS data" saying 11~16m), without being able to use Mapillary (red, red, red...) after long minutes of struggling at the same location.

- It seems it was helping to use "GPS data" first, and then, once the fixed obtained, to switch to Mapillary. Using Mapillary directly was most of the time not giving any workable fix after long minutes when used directly. It's hard to be 100% sure of this though as with just one cellphone I could not do scientifically valid comparisons. Simply, the scenario was: 1) Mapillary, no fix after minutes - 2) GPS Data, fix after an acceptable delay - 3) Mapillary again, fix after minutes.

(This was quite frustrating I must say. I missed many opportunities because of that lack of fix.)

Should this help and/or should you need further details let me know!
Thanks a lot
