### ISSUE TITLE
Choose to have preview horizontally centered left or middle

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1942]

**Comment by rsahlin** [comment]
When the preview is smaller (horizontally) than the screensize there should be an option to have it centered middle or left.

**Comment by peterneubauer** [comment]
Why not just choose left?

**Comment by rsahlin** [comment]
Because some users feel that the would like the preview centered in the middle of the screen.

**Comment by peterneubauer** [comment]
Done.
