### ISSUE TITLE
option to limit GPS accuracy to <12m when in city

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1944]
In the current settings the Android mapillary app will take photos when the GPS accuracy is 18m or better. 
I suggest an option to limit this to better than 12m. Especially in cities with high rise buildings where GPS reception is not the best photos with course accuracy 12m or 18m can jump many lanes or even a block.
To prevent this a 'less is more' approach would be good to have only photos with higher accuracy.

**Comment by echeloni2p** [comment]
HI!

The limit is 15m. And I asked already, it will not be changed, for better. You can disable the GPS check in the settings and upload all pictures and move them later on to the right place.

Also the SFM and 3d pointcloud software should register the pictures against each others and register them to the better position, if it works well fine out.

Do not tight the gps limit to tight, in some cities you won´t get any pictures at all...

echelon

**Comment by paulinus** [comment]
As @echeloni2p mentioned, there is a compromise to be made between requiring enough GPS precision and getting enough images.
The apps record the GPS precision so we can always discard the images with bad GPS latter.
When aligning images, we use the reported GPS accuracy to give more weight to the images with good GPS.
