### ISSUE TITLE
GPS accuracy issues

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#1945]
Hi, I've got an HTC one M8 as well as a Samsung S3. With both devices I have a similar kind of issue.
When I'm waiting at the lights the GPS accuracy is good. green symbol with 4 or 6mm.
Once I start driving the symbol will turn yellow and occasionally turn green or red.

At first I thought this is just poor GPS performance of the device and due to the position in the car. But the accuracy is much better when I use a GPS loging software to record a trace.

**Comment by echeloni2p** [comment]
Hi

looks like a problem with inside the car. My HTC One M9 shows mostly good condition outside on the bike, as long as the view to the satellites is fine, e.g. not in the citry neither in deep valleys...

echelon

**Comment by rsahlin** [comment]
Hi @seb-1204 

The Mapillary app subscribes to location updates just as any other app would do.
There could be a difference in accuracy depending if Google Mobile Services (wifi + gps + network) or only GPS is used.

Could you explain in what way the accuracy is much better when you use a GPS logging software?

Best regards
/Richard

**Comment by Eric-Sparks** [comment]
I, too, am having this problem.  It seems to have started with the latest version of Mapillary.  Previous version seemed to work well, even at high speed.  Now I have problems even at 25 MPH.

**Comment by rsahlin** [comment]
Hi @Eric-Sparks 

There have been no changes to the location code, it is a service that the Mapillary app subscribes to.
The app gets callback with notification of new locations.
We cannot controll the accuracy.

Best regards
/Richard

**Comment by Eric-Sparks** [comment]
Well, that's annoying.  I can't quite put my finger on it but when I updated to the latest version a couple of weeks ago everything went to hell.  The pictures are sporadically taken, I get a lot of warnings that the GPS signal can't be found, and the program locks up for no reason.  My last shot run, today, missed large areas, continued to take pictures while I was stopped, and show up as 180 deg out of phase on the map.

**Comment by Eric-Sparks** [comment]
@rsahlin 
My last run I used GPSLogger at the same time as Mapillary and got a complete track using the same accuracy as Mapillary.  It would seem that _something_ changed somewhere if GPSLogger gets better data than Mapillary using the same bus.

**Comment by polarbearing** [comment]
I am getting tired of discussing such issues as long as you don't open the code for the capturing app, as is being suggested for a long time now. #1791, #1124, #469, #1416

Wifi reception and cellular network information is unsuitable for mapillary purposes. The wifi location is a coarse, indirect reference to previously collected GPS information related to wifi nodes that cover a range in the order of, say,  50-300 m, the cellular is even coarser.

Once we see the code, we can compare that to other apps, such as OsmAnd, where I never had location issues as frequently reported for mapillary, see #1483, #1741, #81, etc. 

My recommendation would be to get the location and speed as direct as possible from the GPS receiver, and avoid any android mangling, filtering, fusion and middlewaring.

**Comment by rsahlin** [comment]
Hi @Eric-Sparks 

Sorry to hear you experienced problems capturing!

It's very hard for me to comment your use of GPSLogger without seeing the latitude/longitude reported by that app and comparing with this.

I have had reports of capture locking and is continually making fixes to get this problem to go away.
Please check with the latest version, 2.27, from the Beta group (join by selecting 'Feed' - 'Join Beta Group'

To investigate problems with capture locking/stopping I need the logs, if the problem persists please check existing issues or open a new one.

If the compass angle is off please open an issue for this, attaching a log and link to pictures that have wrong direction.

- As a last suggestion, please try with only GPS by going into 'Feed' - 'Settins' and uncheck 'Use Google Mobile Services'
You can also enable 'Show detailed stats' - this will show the current lat/long and reported accuracy in meters.

Best regards
/Richard

**Comment by rsahlin** [comment]
Hi @polarbearing 

Sadly we are not in a position to release the app as open source at the moment.
You can force GPS usage by going into 'Feed' - 'Settings' and uchecking 'Use Google Mobile Services'

Please feel free to point me GPS related code used by the other apps you mention, so that I can make sure we do the same.

Best regards
/Richard

**Comment by polarbearing** [comment]
You might [search here](https://github.com/osmandapp/Osmand/search?utf8=%E2%9C%93&q=gps) for their approach. I'm not an android developer, so my own code evaluation capabilities are limited here. 

There were suggestions to fork a lightweight capture-only app #1416, what is the status there?

**Comment by rsahlin** [comment]
I have checked the code you reference and we are doing exactly the same thing.

Only difference seems to be that they only use GPS, whereas, Mapillary default is to use Google Mobile Services.
The GMS will try to get location fix using a number of services, cell/wifi/gps - maybe this is what makes your accuracy low?

Please try disabling 'Use Google Mobile Services' in the settings - this will make the app only use GPS as location provider.

Currently we have no plans to split the app into capture only - but we will definately have it in our future plans

Closing this issue with solution:
Uncheck 'Use Google Mobile Services' in settings to make sure that GPS is used as location provider.

Best regards
/Richard

**Comment by shlublu** [comment]
Hi everyone,

> Please try disabling 'Use Google Mobile Services' in the settings - this will make the app only use GPS as location provider.

I've been assessing that for a week. Looks like it does not change anything. GMS doesn't seem to improve the process, however it doesn't hurt.

**Comment by rsahlin** [comment]
Hi @shlublu and thanks for checking

Just to be clear - I advice anyone who experiences GPS issues to _disable_ the Google Mobile Services.
Disabling this will use only GPS as location provider.
With GMS you may get location fix from wifi or cell - this will most likely have worse accuracy than GPS.

Please continue to test and report any findings you have - thanks!

/Richard

**Comment by pmoulon** [comment]
Last comment seems to be in contradiction with the help there: https://help.mapillary.com/hc/en-us/articles/115001661465-Improving-the-GPS-fix-on-Android
