### ISSUE TITLE
Email-validator in signup-form

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#195]
For some email-addresses the email-validator in your [signup-form](http://www.mapillary.com/map/signup) has inconsistent behaviour.

If I for example enter <code>foo@domaintest.みんな</code> which is a valid email-address, the input-field gets coloured green, but the text stays red and reads <code>(valid email)</code> and the form can't be submitted.

It seems that there are two different email-validators for the text and the input-field, at least one of these does not work correctly. And the red text should read <code>(invalid email)</code> instead of <code>(valid email)</code>.

But I would question, if such an email-validator is even needed. A validator that accepts all possible addresses (and rejects all others) is very difficult to build. And AFAICR you have another (much better) validation-mechanism in place: An activation-email with a link, that you have to visit, in order to login.

For more information about the new TLDs and domain/email-validation watch this talk from this years Google I/O: https://www.google.com/events/io/io14videos/22ce27dc-7cbf-e311-b297-00155d5066d7 (the part about validation starts at 15:30).

- [x] sometimes the form both accepts __and__ rejects an email-address (solved by new design)
- [ ] not all valid email-addresses are accepted by the signup-form

**Comment by gyllen** [comment]
Fixed
