### ISSUE TITLE
iOS app camera button can get stuck in landscape mode

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1950]
See the screenshot. Quite often the camera button gets stuck in the landscape mode position when portrait mode is in use.
This started happening somewhat recently.

**Comment by richlv** [comment]
![image](https://cloud.githubusercontent.com/assets/112888/16021947/18e753de-31be-11e6-81d2-1fd20f400e1e.png)

**Comment by millenbop** [comment]
Thanks for reporting! It seems to happen if you start the app when the phone is laying flat on a table.

**Comment by richlv** [comment]
ah, nice catch - i never figured out the steps that lead to it :)

**Comment by millenbop** [comment]
This has now been fixed and will be out in the next build.

**Comment by richlv** [comment]
yay, thank you :)
