### ISSUE TITLE
Some profile pictures not loading

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1951]
Looking at the [ranking in Argentina](https://www.mapillary.com/map/places/85632505), there are two profile pictures that don't load: @peterneubauer and zalitoar.

https://www.mapillary.com/profile/peterneubauer -> https://a.mapillary.com/v2/u/peterneubauer/profile.png?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh

https://www.mapillary.com/profile/zalitoar -> https://a.mapillary.com/v2/u/zalitoar/profile.png?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh

Both redirect to a cloudfront URL that gives 403 access denied.

Probably there are more affected users...

**Comment by gyllen** [comment]
Now fixed.
