### ISSUE TITLE
One photo not loading in "About Mapillary" page

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1952]
In the [About Mapillary](https://www.mapillary.com/about.html) page, @sandrauddback's picture doesn't load. It's hotlinking directly to a Twitter profile image; perhaps she changed her picture and Twitter put it in a new URL, breaking the old one.

I think it's a bad idea to hotlink to Twitter like that, the URL can break at any time if the photo is changed, or at Twitter's whim really. Why are some employee photos hosted on the Mapillary domain (eg. https://www.mapillary.com/img/about/anders.jpg) and others come from Twitter? I'd just put them all in /img/about/...

**Comment by knikel** [comment]
This has been fixed. Thanks!
