### ISSUE TITLE
AF is slow and inaccurate

### ISSUE THREAD

**Issue by PTMaper** [mapillary/mapillary_issues#1953]
I noticed that auto-focus in mapillary app is very slow and often inaccurate, compared to the stock camera app. It seems that the app does not use Phase detection(Dual Pixel)-AF offered by my Galaxy S7 but contrast detection.

**Comment by rsahlin** [comment]
Hi @PTMaper and sorry for not replying to this issue

Could you please explain how we can use the features of your S7 device - are they available in the Android API or do we have to do a custom integration?

Best regards
/Richard

**Comment by katrinhumal** [comment]
@PTMaper would you be able to share some further information on this topic?

**Comment by katrinhumal** [comment]
If this is still an issue with the latest app versions, please email support@mapillary.com
