### ISSUE TITLE
Add support for MOV videos

### ISSUE THREAD

**Issue by zdila** [mapillary/mapillary_issues#1957]
Many cameras record to MOV. My camera (TrueCam A7s) also adds subtitles with the GPX information and it could be parsed by Mapillary video upload too. I've written a [tool that creates a GPX from the subtitles](https://github.com/zdila/truecam-srt-gpx-extractor). You can use it.

**Comment by nickplesha** [comment]
We're constantly working on improving our upload tools and we'll be making uploading videos easier with new tools in the future. Contact support@mapillary.com if you'd like more info.
