### ISSUE TITLE
Android interface near unusable with multiple sequences and thousands of images

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#1958]
Scenario 1: 20 sequences containing a total of 12.000 images. Starting app it opens up with a black screen for a couple of minutes before either crashing or showing interface finally.
Leave it uploading for 6 hours - only 2000 images are processed in 6 hours.

Scenario 2: 26 sequences now with a total of 19.000 images (10.000 from day before and 9.000 from today). Opening app or trying to select camera mode either crashes or takes minutes to fullfill request.
Going to sequences to mark "Unselect all" takes around 20 seconds for the dots to show command and then command takes minutes to process and to uncheck all.
Scrolling is veeeery slow and checking a sequence takes a few seconds.

I have a Samsung Galaxy S4 with no rooting - just the default updates. 32 GB memory card which in the past has worked fine for a few thousand images but it looks like I'm hitting some memory issue threshold.

**Comment by Stalfur** [comment]
Uploading 1 sequence out of 26 (it seems to have gone through because now it says 25) I got this message:
![2016-06-15 22 25 42](https://cloud.githubusercontent.com/assets/4370958/16099530/3d550b90-3348-11e6-9b5b-970ace26cb0d.png)

**Comment by echeloni2p** [comment]
Hi!

I´ve got the same setup, around 10.000 pictures in >20 tracks, starting of mapillary takes a while, but works on fine afterwards. And it just takes a few 10-30 sec until it pops up - it scans the storage for images and tracks, which takes longer on slower smartphones. My honor 7 with a fast SDCard has no real issues in this area - I can make a 20MP picture every sec. Maybe your samsung is to slow for this huge amount of data and you need to upload them before making new pictures. Or move them to external harddrives and upload seperatly with the scripts.
Uploading lots of data takes its time, but for me it is fine, I can upload >10k pictures during the night, which is roughly 20GB or more of data.
Make sure you´ve got latest version of mapillary, 2.25, which has some enhancements in that area.

echelon

**Comment by Stalfur** [comment]
During the past night 5.000 images of the 19.000 got uploaded and I have several mails from Mapillary telling me 600+ got uploaded, another says 700+ etc. At this rate it takes me around 2 days to upload 1 days tracks. I checked and didn't see GPS information in the file details so uploading via manual web interface doesn't seem to be an option?

**Comment by Stalfur** [comment]
The question is - why does the app need to scan every image and track before it can start taking pictures? It has been a hindrance in taking even more pictures - the app finally becoming responsive after several failed starts (it crashes).

**Comment by echeloni2p** [comment]
Hi!

The pictures are with GPS information, you can simply copy them over to your PC/laptop/whatever and upload seperately with scripts.
While starting up the app does check the storage it tries to use and check for images and thumbnails (for review pane e.g.). It could be made later, as some earlier versions have done, but htat had other issues.
I do wipe my android always after a few tracks and load the app new, although android 6 has a good memory mangement. But sometime these apps using the android very hard can result in strange stuff, so "closing" all apps and reload mapillary helps in getting a clean setup - restarting the device did not helped always ;-)

echelon

**Comment by Stalfur** [comment]
Slight improvement after updatong app but it seems slower per picture to upload many changesets (thousands in queue) than 1-2 changesets at once (hundreds in queue).

**Comment by rsahlin** [comment]
Hi @Stalfur and thanks for your report

Do you think you are experiencing the same issue as this #1864?

As @echeloni2p pointed out the pictures contain GPS/compass in the EXIF data - you can simply copy them to a computer and upload from there.

If you feel that there is a problem with uploads - please open a separate issue for this.

I'm closing this issue - if you still feel that the issue here is not the same as #1864 then please reopen.

Thanks for your support!
Best regards
/Richard
