### ISSUE TITLE
Empty GPX at gallery

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#196]
![mapillary-bug-empty-gpx](https://cloud.githubusercontent.com/assets/957501/3484462/b6ec96e6-03aa-11e4-8b74-1e1e7e65040c.png)

Here: https://api.mapillary.com/v1/s/gpx/3ZK_uk8hFDdi9FL4LYTjUQ.gpx

**Comment by gyllen** [comment]
Should be solved, was depending on empty sequences beeing shown
