### ISSUE TITLE
Crash when scrolling fast in picture list

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1961]
In the upload tab of the iOS app, if I open a long (300+ pics) sequence pending upload, and scroll fast in the thumbnail grid, the application crashes. The crash log shows a large number of threads in the process (50+), all running JPEG code. Looks like reading, thumbnailing and/or drawing the photos is being done in an unbounded number of background threads, and if I scroll too fast I end up with a lot of images being loaded in parallel (which, if unrelated to the crash, is a problem in itself).

I will attach the crash log later (can't do it from mobile github).

**Comment by nicolas17** [comment]
[Crash log](https://github.com/mapillary/mapillary_issues/files/322722/Mapillary_2016-06-20-014015_crash_issue1961.txt)

**Comment by millenbop** [comment]
Awesome, thanks!

**Comment by millenbop** [comment]
Fixed now, available in the next release.
