### ISSUE TITLE
Show map of device location in Explore menu (of App)

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#1962]
Every time I've opened the Explore menu it has showed me a location in Sweden. It's always been the same location but I can't remember which. But of course now that I open Mapillary on both my phone and tablet I don't see anything -- perhaps because the devices don't currently have a GPS fix?

Anyways. My assumption is that the "Explore map" would open up in the location where I'm at as I think it's obvious that it should. But that has never happened.

I think this should be fixed sooner than later because Mapillary is becoming increasingly not only something for "photo mapping geeks" etc to use for capturing photos but also for people at large to explore places. And I think it would be great if the app served both needs at least in some reasonable way. And I would think that centering the map in the location of the device would be a tiny thing to do.

PS. A comment in my "random" photo that expanded to sort of a discussion about Mapillary reminded me of the need for ability to explore Mapillary on mobile. I found this exchange of comments quite interesting - see/read for yourself: http://www.mapillary.com/map/im/rIsqWuTseJQdYs8IpAc5yA/photo

**Comment by katrinhumal** [comment]
@jaakkoh Sorry for leaving this hanging, it was a very valid request. It has been implemented by now - Explore should open in your location or if no GPS fix then the last location that was explored.
