### ISSUE TITLE
mode selection shouldn't work on the whole picture area

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1963]
the new mode switcher in the ios app is easier to use, but it is also easier to use accidentally.
for example, i often find it more convenient to hold the phone on the screen & the opposite sides. unfortunately, with the new switcher i have many times accidentally switched away from the either manual or walking mode - that never happened with the old switcher.
if possible, it would be better to switch modes only a cm or so from the vertical bar that has the mode names, not on the whole photo area.

**Comment by millenbop** [comment]
Right now we have modelled the behaviour after the native camera app so people should be familiar. You have a point though. We'll discuss this and I'll let you know the outcome.

**Comment by millenbop** [comment]
This will be changed in the next iteration of the camera UI/UX that we are currently working on.

**Comment by millenbop** [comment]
This was released last week, closing.
