### ISSUE TITLE
detect and warn about incorrect shooting mode

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1964]
it might be useful to try and detect incorrect mode selected - for example, if 'walking' is selected and the speed exceeds 20km/h, show a non-modal warning. the warning should be obvious, but it should not obstruct the app.

**Comment by millenbop** [comment]
It's a good suggestion, we'll see how we can incorporate this into the apps.

**Comment by rsahlin** [comment]
Hi @richlv and thanks for your comments

On Android we will try a new mode, distance based capture, where the capture is driven by distance rather than time.
The goal is that it should not matter if you are walking/riding a bike or driving - the app should take care of optimal capture.

This is available now on Android for the Beta group.

Best regards
/Richard

**Comment by richlv** [comment]
thanks for the update. sounds good - i assume the distance would be configurable ?

aaaaand it would deal with driving over a very rough terrain, the app saying "move faster to take pictures", me driving faster and damaging the car a bit. has happened quite a few times, actually :D

**Comment by millenbop** [comment]
Optimal would be to just have two modes - manual and auto.

**Comment by rsahlin** [comment]
Yes, If this automatic mode works we will make the distance configurable.
At the moment it is 5 meters, which we think is optimal from a backend perspective.

The nice thing with distance driven capture is that it does not matter if you are moving slow - I have tested both walking and driving - of course you should drive very slowly over rough terrain and this will now be supported :-)

I agree @millenbop Those two modes should be enough 

Best regards
/Richard

**Comment by millenbop** [comment]
Since iOS now also has Auto, I'll close this issue.
