### ISSUE TITLE
outdated capturing mode icons in the help section

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1965]
see http://www.mapillary.com/map/help?q=capturing-modes - that still uses the old icons that are nowhere to be found in the latest version of the app (at least on ios)

**Comment by millenbop** [comment]
They are still used on Android. Android will get an updated UI as well so keeping them until then makes sense, but site needs to be updated at some point.

**Comment by knikel** [comment]
@travel193 We should update these in wiki.

**Comment by travel193** [comment]
Going to hold off updating the [capturing guides](https://github.com/mapillary/UserGuide/wiki/Capturing) on the wiki for the time being. Process/UI for iOS and Android needs to be unified for capturing so will update when this is complete.

**Comment by eneerhut** [comment]
Closing this as the pages in question are no longer active and have been replaced with the [help section](https://github.com/mapillary/mapillary_issues/issues/1966).
