### ISSUE TITLE
help text improvements

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1966]
some of the entries in the website help section could be slightly improved.

a) http://www.mapillary.com/map/help?q=how-to-take-great-photos
"This works best when the street is wide enough so the large part of the facades are visible" - maybe "This works best when the street is wide enough so a large part of the facade is visible"

b) http://www.mapillary.com/map/help?q=how-to-take-great-photos talks about the panorama mode which is no more

c) http://www.mapillary.com/map/help?q=derive-data-from-mapillary-photos - "contributing content to OpenStreetmap" -> "contributing content to OpenStreetMap" (note the case of" Map")

d) http://www.mapillary.com/map/help?q=mapping-toolkit-for-organizations-and-business - excess newlines before both links, so it looks like this :
" take a look at
our
Wiki to see which ones to use"

and :
"For high quality photos share our
How to Take Great Photos guide"

e) http://www.mapillary.com/map/help?q=mapping-toolkit-for-organizations-and-business - "Here are some great examples of organizations that has done" -> "have done"

f) http://www.mapillary.com/map/help?q=openstreetmap - "In our Wiki you can ready about the different tools" - probably "read" ?

**Comment by eneerhut** [comment]
Closing this as the pages in question are no longer active and have been replaced with the [help section](http://help.mapillary.com).
