### ISSUE TITLE
Future timestamp in activity feed (wrong server clock?)

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1968]
I just uploaded new photos, and my [activity feed](https://www.mapillary.com/profile/nicolas17/activity) showed "nicolas17 uploaded 175 photos - in 12 minutes". Looking at the JSON returned by /v2/u/nicolas17/feed, I see that indeed it has a timestamp in the future:

```
"started_at":1466396596371,"updated_at":1466396792903
```

The current time in unix-timestamp milliseconds is 1466396129145 (my computer clock is NTP-synced).

**Comment by gyllen** [comment]
We need to actively synch clock on apache storm machines

**Comment by peterneubauer** [comment]
Closing this for now, should be fixed.
