### ISSUE TITLE
Map tiles display - wrong character displayed with data outside of OSM

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#1969]
I'm not sure where this bug comes from. The issue is a wrong character set in a placename.

Problem place: http://www.mapillary.com/map/search/64.14577162195295/-21.938626179840128/14 

There you will see _Grímsstaÿaholt_ which is wrong, the correct name would be Grímsstaðaholt. However neither name exists in OSM (I just checked in Overpass for name=(both) ) - this data is fetched from elsewhere.

**Comment by Stalfur** [comment]
Actually addendum to the bug - when you click on my link you are moved from zoom /14 to zoom /13 automatically which makes Grímsstaÿaholt disappear - you need to manually zoom back into 14 to see it.

**Comment by peterneubauer** [comment]
THis is an underlying map issue, we are using ESRI/Mapbox/OSM maps and the issue should be addressed there. closing here.
