### ISSUE TITLE
Support for LG 360Cam in Mapillary app

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1970]
This request originates from http://forum.mapillary.com/t/two-new-spherical-cameras/542/8 :

My 360 cam is an LG 360Cam, product page here:
http://www.lg.com/us/lg-friends/lg-LGR105.AVRZTS-360-cam

Average price in the EU: €250, so it's a pretty cheap way to shoot 360 videos. The cam is also designed to work with Google Street View.

The manual is lousy, but in normal operation the cam connect to the phone/tablet as follows:
1. Start the cam
2. Activate Bluetooth in the phone/tablet
3. Go to the "LG 360 CAM" app (not available in iphones below the 5s) to discover the cam.
4. Open the wifi settings, the cam's wifi access point is now visible.
5. Connect to the cam's wifi AP.
6. Password: 00 followed by the last 6 digits from the cam's serial number.

Currently this cam is not supported by Mapillary, only by Google, but it would be handy if it was, because of its price which makes it a cheap way to support the Mapillary idea. It has no gps or compass, so it uses the tablet's data to stamp the pictures.

If the developers want me to beta test something, I'm available at patrick@horsecab.se.

Regards,
Patrick

**Comment by millenbop** [comment]
Thanks for adding! Looks pretty great!

I wonder if it's using Open Spherical Camera API by Google, which we really should add support for. In that case all future cameras "should" work automatically.

**Comment by millenbop** [comment]
I just wanted to let you know we got a LG 360 yesterday and did some early tests by sending some commands manually, and looks promising so far.

**Comment by millenbop** [comment]
This is now pretty much implemented, at least for OSC v2, just need to do some more testing this week. We only have the LG 360 in the office at the moment, so only tested it with that one so far. Would like to test more OSC v2 cameras. 

Also wand to get hold of an OSC v1 camera so I can implement and test support for v1 as well. Any suggestions?

**Comment by millenbop** [comment]
Out in the latest version released yesterday. Thanks @simonmikkelsen for creating the issue!
