### ISSUE TITLE
Cannot login on Android 800x480 screen

### ISSUE THREAD

**Issue by ajl236** [mapillary/mapillary_issues#1973]
using a 1080 dashcam with an android lollipop car head unit (branded eonon) i was hoping to collect heaps of images for mapillary

however i can't logon to mapillary.  only the sign up fields are shown when mapillary is started.  perhaps this is due to the limited screen resolution  which is 800x480 maybe even less than the 480 due to the android status bar.

the image attached is poor quality but shows the only buttons are sign up and register with face book.  

![img_3094](https://cloud.githubusercontent.com/assets/9023278/16292954/206527e0-396a-11e6-8f8b-1efc7531bd07.JPG)

**Comment by rsahlin** [comment]
Hi @ajl236 

I have made new signup/login screens - hopefully they work better now.
Please retest with latest version from Google play - or preferably from the Beta group.
If the issue is not resolved, please reopen the issue.

Best regards
/Richard

**Comment by ajl236** [comment]
Tested with the new version. The logon screen works great.
