### ISSUE TITLE
Provide concise web interface where users can check the progress of their own sequences

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1974]
You know there are constant complaints that sequences are not processed and rendered, such as #1926, #1858, #1971, #1136, #1935, #1999, etc. 

It is a nightmare for the user to keep track of their own sequences, because there are only the image-loaden endless (unpaginated) lists of Activities and Uploads, with a shiny but user-unfriendly presentation. 

Keeping track of a sequence requires to manually take a note of the complicated sequence hash, which has no direct relation to more memorable facts as the capture date, upload date and location. 

Please provide a separate page with a concise, tabular view, one line per sequence, providing the sequence ID as link, the capture date/time of the sequence, the upload date, the processing status + finishing time, a clickable location link, and a column for user-controllable flags, such as if I have checked the blurring already.

Ideally the table could be sorted by their different headers, and should have hard pagination, so sorting by pending sequences would be easy. 
Example (scroll to right):

| Sequence Link | Sequence captured | Count | Uploaded | Processed | Location | User Flags | User Note |
| --- | --- | --- | --- | --- | --- | --- | --- |
| fpM5r8q3lDRwzuwVupvBXQ | 2016-05-01 13:55 | 35 | 2016-05-12 23:20 | 2016-05-13 03:25 | N55.2222, E33.4444 | [x] [ ] | [Road construction] |
| abc5r8q3lDRwzuwVupvxyz | 2016-05-05 17:55 | 44 | 2016-05-12 23:25 | pending | N55.2222, E33.4444 | [x] [ ] | [Our ringroad] |
| def5r8q3lDRwzuwVupvuvw | 2016-05-05 18:55 | 125 | 2016-05-12 23:55 | _On Hold_ | N55.2222, E33.4444 | [] [ ] | [] |
| ghi5r8q3lDRwzuwVupvmno | 2016-05-06 19:55 | 22 | 2016-05-13 23:25 | **Errors** | N55.2222, E33.4444 | [x] [ ] | [] |
| etc |  |  |  |  |  |  |  |

**Comment by Caboosey** [comment]
This be very useful to help with my workflow by updating OpenStreetMap (OSM) and also making sure things get blurred or un-blurred. Currently It's chaotic trying to keep up with multiple sequences over multiple days.

**Comment by polarbearing** [comment]
The list should be pagable and not endless scrolling, and/or have an calendaric index to access a particular point in time. See also #1184.

**Comment by gyllen** [comment]
Thanks for the input. I like the idea of a calendar. Any other suggestions?

**Comment by polarbearing** [comment]
Any progress on this? It is hard to create an effective workflow if all these bugs are not fixed, see #2427, #2428, #2298. 

Please provide functionality, not processor-eating eye-candy.

**Comment by gyllen** [comment]
Added to idea box of better profiles

@angelday FYI

closing
