### ISSUE TITLE
Allow to add machine tags on images

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#1976]
Hello,
It would be great if Mapillary had a system like Flickr's machine tags, which allows to add on a given image some custom key-value information. These tags can be queried in API, allowing for example to return all images having a certain key or a certain key+value. This could be useful for a vast amount of use cases, like knowing at which level an indoor picture is located (and making it easier to reuse in indoor maps, like OpenLevelUp).
Cordially.

**Comment by de-vries** [comment]
they're on to it, see #992

**Comment by PanierAvide** [comment]
Didn't see that one, thanks ;)

**Comment by gyllen** [comment]
Closing since duplicate
