### ISSUE TITLE
Profile: "Recent Activity" incorrect date of upload

### ISSUE THREAD

**Issue by Jolg42** [mapillary/mapillary_issues#1978]
Hi!
I just uploaded my first pictures yesterday (Saturday 25) and in the Recent Activity it's marked as Friday
See screenshots:
![screenshot 2016-06-26 at 08 03 10](https://cloud.githubusercontent.com/assets/1328733/16360800/f1426376-3b74-11e6-90b6-ca662621b74e.jpg)
![screenshot 2016-06-26 at 08 04 20](https://cloud.githubusercontent.com/assets/1328733/16360802/f8bf58f2-3b74-11e6-9adb-9230d61f74dd.jpg)

**Comment by de-vries** [comment]
this is a known issue, see: #634, #900, #1632 and #1662

**Comment by gyllen** [comment]
@angelday I like the upload activity chart, we should think about adding it to new web

**Comment by angelday** [comment]
The original issue has been fixed, closing.
