### ISSUE TITLE
Too many - unwanted - photos after switching from driving mode to walking mode

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#1980]
Sometimes when in driving mode I want to make a more detailed survey, not driving, but walking.
So I stop driving and switch from 'driving' mode to 'walking manual' mode.
At this moment Samsung Galaxy S5 Neo + Android 6.0 immediately starts making the maximum number of photos (more than one per second). Without 'Start' option being selected. But I also did not Stop the running sequence.
These photos are either in one sequence and/or in one sequence for each individual photo.
So one sequence having 100 photos and 30 sequences having 1 photo each is typical.
Only way out: stop Mapillary App and start Mapillary.

**Comment by rsahlin** [comment]
Hi @AnkEric and thanks for reporting

Yes, this was a bug!
When the mode is changed the current sequence is stopped - this should fix the problem.
A version with the fix will be available to Beta group within a day or two - version number >= 2.33

Best regards
/Richard
