### ISSUE TITLE
Capture hangs after 1 or a couple of photos (thumbnail creation takes a lot of time)

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1982]
Capture hangs after 1 - 3 photos and must be stopped and re-started.
[mapillary_trace (14).txt](https://github.com/mapillary/mapillary_issues/files/334250/mapillary_trace.14.txt)

**Comment by mxa** [comment]
The sequences are not stopping or are restarted manually. Actually in the "car" mode is seems for the user to work properly. Only on reviewing the sequences for upload one realizes that the app made 2 sequences instead one one. The first one contains only one picture.

**Comment by rsahlin** [comment]
The thumbnail creation is taking a huge amount of time, I'll need to investigate further.

**Comment by mxa** [comment]
Is this related to that issue? ![tmp_21985-screenshot_20160810-1622071152657027](https://cloud.githubusercontent.com/assets/1220707/17557609/cc3ca1f2-5f52-11e6-82ca-8043db8b1ddc.png)

**Comment by jfburke3** [comment]
I don't think so. 

-- 
Typos courtesy of fancy auto spell technology
