### ISSUE TITLE
mode switching & map view

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1984]
ios app. in the photo mode, switching the shooting modes currently works on the mode switcher (the small bar) and the whole photo area. when the map is shown instead, the mode switching works on the mode switcher and the small photo area.
this is very confusing - for example, i almost reported that mode switching only works "up", not down (when actually one of the gestures usually starts in the photo area, so it works - the other one starts in the map area and does not work).

**Comment by millenbop** [comment]
Thanks for reporting!

Hmm that's a tough one as we want to add the ability to move around and zoom in the map, but still probably want to stick to what the native camera does.

**Comment by richlv** [comment]
well, maybe admit that you're not a camera app and do something slightly different ;)
how about making the mode bar wider (like, 3 times as wide) and allow mode switching only _on_ it ?
that would solve the problem of accidental mode switch and allow map controlling. win/win :)

also maybe make it more obvious what it does by showing up/down arrows on it...

**Comment by talllguy** [comment]
The *swipe to change mode gesture* also works when the camera is full screen, and the map is hidden. This is sometimes frustrating when map view is active and I forget that you cannot swipe to change the mode there.

**Comment by millenbop** [comment]
We are currently redoing the camera UI/UX (againI) and this will be fixed there.

**Comment by millenbop** [comment]
New UI/UX released, closing.
