### ISSUE TITLE
distance capture mode has old walking mode icon

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1985]
The new "distance mode" on Android has the old "Foot-A" logo on the bottom of the capture screen.

**Comment by rsahlin** [comment]
Thanks @HolgerJeromin for reporting - this got lost in a recent merge.

Will fix asap.

Best regards
/Richard

**Comment by rsahlin** [comment]
Fixed in version 2.32 uploaded to Beta group

Best regards
/Richard

**Comment by HolgerJeromin** [comment]
fix confirmed. Thanks

**Comment by rsahlin** [comment]
Great - thanks for verifying :-)
