### ISSUE TITLE
Upload interface is missing labels

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1986]
On my Fairphone 2 the newest version does not have text anymore.
So without knowledge of the old interface, no one will find the checkbox.

![image](https://cloud.githubusercontent.com/assets/2410353/16499460/e1350d64-3f00-11e6-905d-85408291be4e.png)

**Comment by jfburke3** [comment]
I just noticed the same thing.  Mapillary version 2.31, on both Android 6.0.1 on a Samsung Galaxy S7, and Android 5.0 on a Samsung Galaxy S5.

If you use the little 3-dot menu at the upper right to disable/enable Toggle All, then the checkmarks show up, but you still can't see the actual checkBOX, nor the text that IIRC used to be next to the boxes.

**Comment by rsahlin** [comment]
Thanks for reporting!

I will look into this asap.

Best regards
/Richard

**Comment by rsahlin** [comment]
Fixed in version 2.32 uploaded to Beta group

Best regards
/Richard

**Comment by HolgerJeromin** [comment]
fix confirmed. Thanks

**Comment by rsahlin** [comment]
Excellent - thanks for checking :-)
