### ISSUE TITLE
In edit mode can't navigate photos in sequence.

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#1987]
On the website if I notice a blurry photo there's usually several others nearby. I used to be able to go to edit mode and move one photo back and forward, however this is no longer possible. The main map images have the arrows at the top and bottom of the photo allowing you to navigate.

Clicking the map is unpredictable and jumps around to somewhere else nearby, often on a different track, even if I click a marker. I'm using Safari 9.1.1 on Mac OS X 10.11.5.

**Comment by smsm1** [comment]
This is why I've submitted a few single image edits, and given up.

**Comment by gyllen** [comment]
@smsm1 Hang in there the brand new editor is just around the corner, we will finally get the edit tool we deserve. There has been a lot of backend work to make this fast (this is now solve). The UX design is made and we are just finishing up the frontend.

**Comment by smsm1** [comment]
Thanks for the update, looking forward to the changes :-)

**Comment by nicolas17** [comment]
You can use the up and down arrow keys on the keyboard.

I always use the keyboard to navigate in blur-edit mode, so I didn't realize the clickable arrows were missing :)

**Comment by HolgerJeromin** [comment]
The arrows were removed on purpose. You could not blur under the arrows. Looking forward to the new editor

**Comment by gyllen** [comment]
The editor is now released. Please open new issues on improvements/bugs
