### ISSUE TITLE
Map center is not keeping up with the sequence

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1989]
Device: iPhone 6S Plus
OS: iOS 9.3.2
Mapillary: 4.3.2

In this annoying issue, I've noticed that the location of the scrolling map "center" (little arrow thing that represents me on the map, I think it is called a cursor in some applications), is failing to keep up with the sequence of photos.

Sometimes when I drive, the green dots will continue to appear, but the map will get stuck, or even the location will start to veer off the map.

![2016-06-30 19 30 43](https://cloud.githubusercontent.com/assets/1827881/16530813/d3336a20-3f97-11e6-940e-bc05568c514d.png)

**Comment by millenbop** [comment]
I have upgraded the Mapbox library and did a test on my bike and it seems to fine work for me. Out in the latest version released yesterday. Let me know if you still experience problems and we'll reopen!

**Comment by plago73** [comment]
Which version? 4.4.10?

**Comment by plago73** [comment]
👍
