### ISSUE TITLE
The "Compass Angle" is not changed by the buttons

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#199]
Clicks in `+` or `-` buttons have no actions.

But perhaps what I want is in the issue #115. See [this](http://www.mapillary.com/map/im/-Gb84nr9hRF3RjEtcOYgZw) photo.

**Comment by knikel** [comment]
The interface will is being rebuilt from scratch for the upcoming version of the editor. Adding relevant labels, will be closed when we roll out the editor
