### ISSUE TITLE
Auto upload notification display error

### ISSUE THREAD

**Issue by travel193** [mapillary/mapillary_issues#1991]
The notification that auto-upload can be enabled does not display properly. Also a typo. Should be "Enable auto-upload requested".
![screenshot_2016-07-02-15-01-33](https://cloud.githubusercontent.com/assets/11349863/16540639/0b74b41e-406c-11e6-8fd0-44861c66a104.png)

**Comment by peterneubauer** [comment]
Fixed for the next version, thanks!
