### ISSUE TITLE
Mode (Auto, “Distance, auto shot”) is disappointing

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#1993]
New (?) mode = Auto, “Distance, auto shot” is disappointing. To me, that is.
Or should this mode not be used on bicycle?

Disappointments:

Too many pictures are taken in a frequency of 2 images per second. In my view: too much.
(I have tested by “Make shutter sound” = yes).
I did not see any reason or excuse for making this many pictures. Nothing happened, cycle tour was boring, straight on driving.

7500 images for a not very interesting bicycle tour of 60 km, in my view: too much.
Suggestion: use Threshold setting, “Sequence frequency”.

“Pause on stop” (pause shooting in auto-mode when camera is moving slower than 2m/s) is not effective in this mode. During a short coffee break 50 images were taken. Including private images, I don’t like being uploaded.

Uncertain:
Phone is almost continuously warning: “Phone is shaking”. I did not succeed in hiding this warning by slowing down to 12 km/hours on an asphalt road. 
In “Riding, timebased” mode the warning only appears if justified. (But also: this was a version previous to 2.31). 
Warning is not effective, despite “Pause on shake” = yes. Camera keeps shooting pictures at the same rate.

Android 6.0.1, Mapillary 2.31.

**Comment by rsahlin** [comment]
Hi @AnkEric and thanks for your comments!

Sorry to hear that you do not like the 'Distance, Auto shot' mode - could you please explain why you do not like it?

I'm trying to understand the issues here.
- Too many pictures taken
To lower the number of images taken, please go into settings and change the sequence delay - OR switch to Auto mode which will take pictures based on distance.

- Pause on stop only works in the Driving mode.

- Yes, the shake detection is not optimal. 
This is why it is disabled by default, it is generally advised to uncheck 'Pause on shake'
It may be on if you have upgraded from a previous version where it was enabled.

Could you please explain what you mean by
'Warning is not effective, despite “Pause on shake” = yes. Camera keeps shooting pictures at the same rate.'

I hope you will be happy to hear that we are working on making the modes simpler and more intuitive.
In the next Beta release there will be 3 modes.
- Distance auto shot
The photos will be taken based on distance moved, this distance is configurable 0 - 25 meters.
Will also take pictures if compass change is over a certain degree, this is very good for mapping 90 degree turns while walking.
Extra photo can be taken at any time by clicking on the camera preview. 
The angle to trigger a picture is configurable 15 - 180 degrees.
- Timed auto shot
Photos will be taken based on a timer, from 0.5 to 5 seconds.
Capture will also be triggered by compass change.
Extra photo can be taken at any time by clicking on the camera preview. 
- Manual mode
Photos will only be taken when triggered by clicking camera preview or capture icon.

The intention is to get this mode out this week to Beta group, it would be very interesting to hear your feedback once the update is out!

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi!

You cannot have TOO much pictures from a track, the more, the better. It is not only for your feelings of boring, it is also for world reconstruction in 3D. So, if not for you, do the pictures for others. As long as you are fine with ressource usage.
Mobile will shake on bicycle all the time, as the bike will shake all the time. And with longer aperture time the chance for bad pictures do rise, thats why this warning appears nearly all the time. Do mount the mobile on your helmet to stop this (your head keeps very smooth, as your body works as a absorber), but you cannot control anymore which pictures are taken ;-)

echelon

**Comment by rsahlin** [comment]
Hi @echeloni2p and thanks for your comments

From a backend perspective we would like to have pictures at around 3-5 meters apart.

Good suggestion regarding head-mount :-)
In the near future I will be looking into exposure times and see what I can do to reduce blurry images due to shaking and long exposure.
I think there are several improvements that can be done :-)

Best regards
/Richard

**Comment by AnkEric** [comment]
> _Too many pictures taken_

Last sequence was copied to PC. Three sample images:
"2016_07_04_11_38_43_142.jpg", "2016_07_04_11_38_43_288.jpg", "2016_07_04_11_38_43_500.jpg".
Assuming last 3 digits are milliseconds: 0,146 and 0,202 seconds between images, 3 images in 0,358 seconds. That’s too much…
I can hear shutter sound (testing only): ”click, click, click” and I was not speeding at that moment. Driving speed 24 km/h. Nor was I making a turn or whatever justification for “too many pictures”.

See (rotated images):
https://www.mapillary.com/map/im/6sbYVsDXJRf9QhjaZkZELA

BUT, BUT, I quote:
_“From a backend perspective we would like to have pictures at around 3-5 meters apart”._
These images are exactly at 5-meter distance!
So I’m mistaken if I state: “too many pictures”?! These images are at the correct distance?! 
In which case others are too far apart (25 meters). On average: 60 km / 7500 images = 8-meter distance, on average. Which is OK from “a backend perspective”! Only distribution is not evenly spread?

In a car, driving at 100 km/h you would need 5 pictures/second to get a 5-meter distance!
Is this feasable? Realistic?

> _You cannot have TOO much pictures from a track <...> As long as you are fine with resource usage._

I’m a resource as well.

- To review: copy all images to PC, review all images on PC (faster and more reliable than phone).
- To process images for OpenStreetMap: upload to Mapillary of too many images takes more time to upload and more time before images are available on Mapillary.
- To use images during OpenStreetMap JOSM editing: browsing through too many images (next, next, next...), again takes too much time.

One bicyle weekend is 200 km, Sunday evening I have to process about 25.000 images. That’s too much. And almost twice as much as in “Riding, timebased” mode.

Also, first impression based on only one trip, the extra images don’t contribute to extra information. 
Again, BUT, it seems I have incomplete understanding about the number of images Mapillary prefers from “a backend perspective”!
I should get used to 25.000 images in one weekend?!

> _To lower the number of images taken, please go into settings and change the sequence delay_

“Distance, auto shot” does not use this setting. 
Using the same setting for sequence delay (20/10 sec) I see twice the number of images as compared to “Riding, timebased”.

> _To lower the number of images taken <…> switch to Auto mode which will take pictures based on distance._

I’m already referring -  in my “disappointment” - to “Distance, auto shot”. As compared to “Riding, timebased” I get almost twice the number of images.

> _Pause on stop only works in the Driving mode._

This is “disappointing”. I expect (“user expectations”) “Distance, auto shot” mode to be “AUTO”. That is: stop automatically when not driving. No distance covered means: no pictures.

> _Could you please explain what you mean by 'Warning is not effective, despite “Pause on shake” = yes. Camera keeps shooting pictures at the same rate.'_

A Mapillary App setting is in place: “Pause on shake” = yes.
I expect this means that when phone is shaking, it will “pause”. It doesn’t.

> _I hope you will be happy to hear: Distance auto shot The photos will be taken based on distance moved, this distance is configurable 0 - 25 meters_
> _From a backend perspective we would like to have pictures at around 3-5 meters apart._

“Riding, timebased” doesn’t produce this result. It’s depending on our driving speed which is 15-30 km/h.
“Distance, auto shot” doesn’t - seem ! – to produce this result.

So “Riding, distancebased” seems to be the way to go!

What is or should be the difference between “Distance, auto shot” and “based on distance moved”. Does “auto” also account for time elapsed? Which is not relevant.

But also, with the risk of exaggerating, I would prefer having 2 or 3 distance settings, for instance:

- Low = 20-meters distance (nothing happens, like driving in the desert)
- Normal = 10-meters distance
- High = 5-meter distance (I consider dismounting and walking for a detailed survey).

These mode buttons should be available On Screen and large, easy to operate.
(Image preview is not very relevant, I can see in real life what should be on the image. I’m only interested in whether or not my phone is horizontal).
So, depending on environment, i can switch to more or less pictures.

> _I hope you will be happy to hear: Extra photo can be taken at any time by clicking on the camera preview._

Very happy!
Example: we are driving parallel to a motorway. Make left turn and stop for traffic_lights. I stop, so Mapillary is on pause (“Riding, timebased”). On the other side of the road I notice two conflicting traffic_signs. I want those! But Mapillary is on pause and after restarting the first image was taken past the traffic_signs. So no images of the two conflicting traffic_signs. Disappointment!
So in next Beta release I simply Click On Screen while waiting for traffic_light and I’m very happy! Or stop, walk the bike and Click On Screen without switching to Walking Mode.
Great!

> _In the near future I will be looking into exposure times and see what I can do to reduce blurry images due to shaking and long exposure._

Excellent!

And thanks for your comments.

Best regards
/AnkEric

**Comment by rsahlin** [comment]
Hi @AnkEric and thanks for explaining!

Please look out for the next Beta release where we aim to streamline the capture modes :-)

Regarding rotation issue, please have a look at #1925 - this is the issue that is causing 90 degree rotation.
If possible please send the debug logs - I am having a hard time tracking down the rotation problem due to not having a log where the output rotation is calculated.

Best regards
/Richard

**Comment by echeloni2p** [comment]
Hi!

Do as many pictures as you like, if some are missed out, just redo the sequence the next time you ride it again.
There really is not a "too much" - even in "boring" areas someone finds it interesting to have a detailed view of the scene. And yes, if you have the ressources, do 50.000 pictures a weekend. If not, do less, do as much as you like to do.
You do not need to review images neither edit OSM with these pictures. Mapillary is not made only for OSM ;-)
If you want a seemless 3d view from the world, you need pictures every 3-5m, also you need pictures from all viewangles - e.g. ride the bike one weekend clockwise, next weekend ant-clockwise around your tracks ;-)
If you do have the ressources, I do not really see a reason to not take more pictures.

echelon
