### ISSUE TITLE
Sequence repeated 22 times

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1994]
I uploaded a sequence using `upload.py` and it appears on [my profile](http://www.mapillary.com/profile/nicolas17) and on my activity feed repeated many times. Each has a different sequence ID, but the photos themselves have the same ID in all the sequences, so they are not repeated (which means this isn't because I uploaded multiple times). I didn't even expect it would be possible for a photo to belong to multiple sequences...

**Comment by peterneubauer** [comment]
Mmh,
this is very strange. It seems the sequence got created 22 times. We are not assigning new sequence IDs in the backend - that is done in the python script. IMHO it looks like the same images were sent 22 with different sequences. In the PSQL backend - an image can actually be part of different sequences (which they are) @gyllen . In the Elasticsearch database, the last sequence is assigned to the image, so when you go to one of the sequences on your profile and click details, you will find the last sequence ID.

@nicolas17 are you absolutely sure you didn't multiple-upload things? I suspect some form of upload logic error here.

**Comment by gyllen** [comment]
@peterneubauer The sequences contains the same images though (same key)

**Comment by de-vries** [comment]
same thing might have happened here: https://www.mapillary.com/profile/marczoutendijk go to page 2 in the pagination and scroll down a bit.

**Comment by nicolas17** [comment]
@de-vries: You are correct, same situation there. Sequences [xW22sHKJPrAB1KOncmwMUg](https://www.mapillary.com/map/s/xW22sHKJPrAB1KOncmwMUg), [mhjLJE4vGkRGLDGx-5_OVA](https://www.mapillary.com/map/s/mhjLJE4vGkRGLDGx-5_OVA), [ASJNbhp3PIVz_V8SIk-cDA](https://www.mapillary.com/map/s/ASJNbhp3PIVz_V8SIk-cDA) and [9qi0uvGeFdcOna_bMi6Z8w](https://www.mapillary.com/map/s/9qi0uvGeFdcOna_bMi6Z8w) all have the same photos, starting with photo [97JtOaIuN_vvmUSjdLPriA](https://www.mapillary.com/map/im/97JtOaIuN_vvmUSjdLPriA).

**Comment by peterneubauer** [comment]
All these have been uploaded with the scripts?

**Comment by nicolas17** [comment]
Those aren't mine, I saw them on marczoutendijk's profile, linked by de-vries. No idea how they were uploaded…

**Comment by ybkuang** [comment]
@peterneubauer I just checked that @nicolas17 's photos are taken from the iOS app (ver. 4.1.2). I think using upload.py should not create or assign new sequences to those photos.

**Comment by nicolas17** [comment]
I think at this point we can't debug why this happened unless it happens again.

Could someone just delete the extra sequences?

**Comment by gyllen** [comment]
@peterneubauer Can you help @nicolas17 out with this?

**Comment by peterneubauer** [comment]
I believe this is now solved as we cleaned up one of our backends. Closing.
