### ISSUE TITLE
Upload stops if there is a network error and does not resume

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#1995]
If there is a network or server error while uploading, the upload is not automatically resumed resulting in user having to manually resume upload.

**Comment by richardbrinkman** [comment]
I can confirm this bug.
My phone switches off wifi from time to time to save battery. It would be nice if the upload continues after the wifi connection is restored again.

**Comment by HolgerJeromin** [comment]
But only on the same wifi. For example I do not want to upload on the wifi of my work. 
And at home only if I don't need the bandwidth

**Comment by ovivoda** [comment]
This should be fixed now in the latest app version and beta versions. 

@HolgerJeromin Would you like to have a feature for preferred wifi?

**Comment by HolgerJeromin** [comment]
As i like to have control it would be nice. But #2337 is bothering me much more.

**Comment by peterneubauer** [comment]
Let's continue the discussion on the Forum and close this.
