### ISSUE TITLE
time travel not connecting seemingly obvious photos

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1997]
the time travel in the viewer is not connecting this :
http://www.mapillary.com/map/im/T9jEWO1lRJTXgL_Lbv8Zmw/photo
and this :
http://www.mapillary.com/map/im/5ecTyk51EkBLPBCaM1IXkw/photo

the pics have been taken quite close to one another, and in an area where there are no better matches, it might make sense to connect images at distances like these.

**Comment by gyllen** [comment]
@oscarlorentzon You know the reason for this?

**Comment by oscarlorentzon** [comment]
The time travel feature relies on the 3D reconstruction algorithm finding matches between photos for making the smooth transition. Unfortunately there were no matches between those two photos. If you navigate two steps back there is actually time travel between those two sequences: 

http://www.mapillary.com/map/im/OOgyLKHngu9XewhJdzL1ow/photo

If time travel should be allowed for images without matches we would need to rely on compass angle and original GPS which are usually not correct leading to many faulty time travel transitions. It is a fine balance between filtering only the good ones and showing as many as possible (with the side effect of getting more faulty ones).

**Comment by richlv** [comment]
i see. it could be extended to allow transitioning based on coords/angle alone for "confirmed" images (manually edited or confirmed), but i guess that's not much of a priority.
thanks for the info, closing :)
