### ISSUE TITLE
Force touch quick actions not translated

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1998]
Using my iPhone in Spanish, all text inside the app appears in Spanish. However, the quick actions when force-pressing the app icon still say "Walking Mode" and "Riding Mode" in English.

**Comment by millenbop** [comment]
Fixed now. Forgot to include it in 4.4.2 I just submitted to Apple, but will be available in 4.4.3.

**Comment by millenbop** [comment]
Closing this as the app is out now.
