### ISSUE TITLE
Image still processing

### ISSUE THREAD

**Issue by iagsav** [mapillary/mapillary_issues#1999]
Hello I have 8 images, which is "still processing". Can you help ?

**Comment by de-vries** [comment]
duplicate of #1136 and #1971.

**Comment by gyllen** [comment]
Hi @iagsav usually this is just what we call `ghost images` - which means that we have processed everything but we has some hickups along the way and our pipeline did a reprocessing.

Can you confirm that you actually do miss images?

**Comment by iagsav** [comment]
I upload 30000 images and i can't say which of them i miss

**Comment by gyllen** [comment]
@iagsav Great work!! So for now you can relax about the still processing images. Its really not missing images, just our server that does a bad job counting.

**Comment by polarbearing** [comment]
Please consider #1974 in this context.

**Comment by iagsav** [comment]
Thanks for all comments!

**Comment by gyllen** [comment]
We no longer have this issue.
