### ISSUE TITLE
Increase map size on video upload page

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2000]
I've been uploading a lot of videos this weekend and for some reason the location marker that is set by default is always WAY far away from where it should be so I have to find and move things a lot. The tiny 290x260 map is ridiculously hard to use when searching a 50 mile GPS trace for the correct start point for a 30 minute video. I noticed that if I make my browser window narrow enough it reflows the page and the map comes below the video and ends up actually being bigger than the default layout of the page. Could you please move it under the video permanently and make it take up most of the page width?

**Comment by knikel** [comment]
I'm closing this since this functionality is part of `legacy.mapillary.com` (which we would like to deprecate at some point). @amahon we should port video uploader to mapillary.com.
