### ISSUE TITLE
Uploading - Garmin Virb

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2002]
Bought a Garmin Virb XE. Did some driving and taking pictures today. Have managed to transfer pictures from the Virb to the Mapillary App on iPhone, and upload to Mapillary from there.

The iPhone only has a limited amount of  space free, a lot less then the memory card for the Virb.

Uploading in batches should work.

But from what I understand the Mapillary app does not tell the Virb not to transfer the same pictures twice. So I just keep uploading the same few hundred pictures.

I guess I could open the Virb app and delete pictures manually. But I don't think that will be very practical.

Any ideas or suggestions?

**Comment by millenbop** [comment]
It's a limitation for now. Basically I need to do some sort of bookkeeping without breaking it for multiple camera setups as the filenames aren't unique. I'll try to have it implemented soon.

In the future we will have a desktop uploader as well that will work with all action cameras.

**Comment by millenbop** [comment]
I have implemented a 7 day history/log now, so files already downloaded will not be downloaded again. Will be available in 4.4.3.

**Comment by Andblue** [comment]
That was fast. Awesome! Thanks @millenbop

**Comment by millenbop** [comment]
Anytime! Let me know if you run into any problems!

Closing this as the app is out now.
