### ISSUE TITLE
Web upload is problematic

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#2003]
It seems that the manual upload (using https://www.mapillary.com/map/upload) is problematic.

The upload process getting hung is very recurrent (I consider it "OK", since I can keep clicking at `
Upload hung up? Click here.` and upload what is missing). But right now I am stuck at this, no matter how many times I try:

![](https://cloud.githubusercontent.com/assets/982338/16825599/73d53b26-494c-11e6-8b0f-01ccc39c8f9f.png)

And since I don't know what is happening nor which picture it's trying to upload nor anything else, I guess I won't be able to give some useful information about this.

I guess one thing here would be "Could we have the filename that is being uploaded displayed, please?"

Also, while selecting the photos I can see:

![](https://cloud.githubusercontent.com/assets/982338/16825630/c329a02c-494c-11e6-9a6a-6ac0bcab90b5.png)

and clicking at `and -4 more errors` nothing happens; I only see the link disappearing:

![](https://cloud.githubusercontent.com/assets/982338/16825644/e80a238a-494c-11e6-89a1-0ede0355c557.png)

It should display the other errors too when clicking at the errors link.

**Comment by naoliv** [comment]
It seems that the file that is causing it to upload nothing is this one http://naoliv.iq.unesp.br/osm/mapillary/failed-pics/IMG_20160710_131955160.jpg
Also, I thought that `and -4 more errors` were in fact `and 4 more files with errors`

I don't know if it's me of if it's the message, but could it also be made clear that it's the same file that has 5 errors in total?

**Comment by echeloni2p** [comment]
Hi!

Files without GPS tags are problematic, the uploader stops at them.
You need to remove them from your upload list :-(

echelon

**Comment by gyllen** [comment]
@naoliv Did this fix your problem?

**Comment by gyllen** [comment]
Should be fixed with release of new site.
