### ISSUE TITLE
Full-screen iOS viewer can appear stretched

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2004]
On the iOS app, if the MapillaryJS sequence viewer is put in fullscreen at the right moment, it stretches the wide image into the portrait screen.

Open an existing sequence, for example from the profile tab. Then, after the viewer itself loads but before the actual photo loads, that is while the white spinner is visible, tap the button to enter fullscreen. Since the photo didn't load yet, the screen will just be black until it loads. When it loads, the picture will be stretched.
![image](https://cloud.githubusercontent.com/assets/101955/16844070/10a2fdea-49ba-11e6-8c19-ea7f8936072a.png)

This bug *could* be in MapillaryJS rather than the iOS code…

**Comment by oscarlorentzon** [comment]
Should have been fixed here mapillary/mapillary-js#115 which was in the [1.4.2 release](https://github.com/mapillary/mapillary-js/releases/tag/v1.4.2).

**Comment by millenbop** [comment]
Yes it's most likely a timing issue in the iOS app.

**Comment by nicolas17** [comment]
What version of MapillaryJS does the iOS app use?

**Comment by talllguy** [comment]
See also #1790 @nicolas17

**Comment by millenbop** [comment]
@nicolas17 it uses the latest, 1.4.2

**Comment by millenbop** [comment]
*Hopefully*, this is now fixed, will be available in 4.2.3.

**Comment by millenbop** [comment]
Closing this as the app is out now.
