### ISSUE TITLE
iOS viewer can end up in black screen when quickly changing orientation

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2005]
On the MapillaryJS viewer on the iOS app, if you switch from portrait to landscape, and then quickly back to portrait, often the screen goes black, showing only the system status bar. The only way out of it is to kill and restart the app.

To reproduce you need careful timing. You have to do it fast enough, I think you have to switch to portrait while the landscape view didn't fully finish fading in from black. But if you switch from portrait to landscape and back _too_ fast, the iPhone doesn't consider the orientation to have changed and stays in portrait view.

Of course, if you're not actively trying to reproduce it, you accidentally get the timing just right when you least expect it.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
