### ISSUE TITLE
[Feature Request] Support running in background mode next to navigation software

### ISSUE THREAD

**Issue by Lednerb** [mapillary/mapillary_issues#2007]
It would be nice if I just can run mapillary and switch to another app like my favorite navigation app.
With this feature I would be able to record and drive to some new places not only the ones I already know.

For example record the track when
 - driving to another city
 - make holidays in a foreign area
 - etc.

At the moment recording stops when I switch to another app :-|

ps: feel free to change the issue's title :wink:

**Comment by Lednerb** [comment]
Ah I see, it's similar to #331, #1001, #88, #89

**Comment by nicolas17** [comment]
On *jailbroken* iOS I was able to do this using the Watchdog Lite tweak to make Mapillary behave as if it was always in the foreground. However, while a navigation app was in the (real) foreground, I could notice from the shutter sound that Mapillary was struggling to keep up with the capture frequency. It seems the iPhone 6 CPU isn't fast enough to have Mapillary and maps.me fully running at the same time.

In addition, more than once I forgot the app running (but not taking pictures), which would affect battery life. I have to remember to take it out of the Watchdog list when I don't intend to use it in this way.

**Comment by jesolem** [comment]
@Lednerb You can do the reverse: start routing/navigation app, then switch to Mapillary. Navigation apps can run in the background and still give you voice and notifications. Camera apps cannot run in the background on iOS (unless jailbroken).

**Comment by Lednerb** [comment]
Thx for your comments !

Maybe there is a similar app for rooted android devices.
I usally drive with only the routing display enabled but not the voice.

For this usage the solution with foreground simulation would be the better choice I think.
