### ISSUE TITLE
ios app crash when reviewing images

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2008]
mapillary app 4.4.2 for ios on iphone6.
had a sequence of 662 photos. opened it and scrolled down as fast as possible to check the last few images. the scrollbar went to the very bottom, but no images appeared; a moment later the scrollbar disappeared and then some 5 seconds later the app crashed. i was able to reproduce this 2 times in a row.
then i scrolled to the bottom very slowly, allowing all the images to appear - no crash.
then i again opened the same sequence, scrolled down very fast - and crashed again. so it is perfectly reproducible.
then i tried another sequence of 308 photos. scrolled down very fast. the scrollbar disappeared, but no crash - some 2-3 seconds later the bottom images appeared.
386 photos - worked ok.
848 photos - crash.
489 photos - crash.

**Comment by millenbop** [comment]
Thanks! I'll look into it! Sounds like an out-of-memory problem.

**Comment by millenbop** [comment]
Hmm sounds like I might need to enable thumbnails again, was hoping I could avoid that.

**Comment by millenbop** [comment]
Do you still have problems with 4.4.5? Closing for now but will reopen if problem persists.
