### ISSUE TITLE
EFF privacy badger breaks mapillary viewer

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2010]
https://github.com/EFForg/privacybadgerfirefox breaks the viewer. Tested in iD and on the mapillary blog.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
