### ISSUE TITLE
Checkmark to exit capture mode is too sensitive | iOS

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2011]
_App version 4.4.3_

The UI element (shown below) that the user taps to exit camera capture mode is too sensitive, in that it responds to any touch activity that originates on the :heavy_check_mark: circle position.

If the user swipes to change mode (as in #1984) and happens to put their finger down on the :heavy_check_mark: circle, the capture mode will quickly exit, before the swipe is even completed.

Similarly, if the user taps and holds on the check mark, the camera mode will exit before the user lifts their finger.

As a button, I think that the action should only happen if the user taps **and releases** within the button area.

![image](https://cloud.githubusercontent.com/assets/1827881/16916402/b6be5d24-4cca-11e6-879c-657e0577cfd7.png)

**Comment by talllguy** [comment]
Also, the :heavy_plus_sign: button (manual mode only) has the same issue, though it is possible that this is desired, since the user may want to rapidly press this.

**Comment by millenbop** [comment]
This has been greatly improved now, will be available in 4.4.5. Thanks for reporting!

**Comment by millenbop** [comment]
Does it work better for you in 4.4.5?

**Comment by millenbop** [comment]
Closing for now but will reopen if problem persists.

**Comment by talllguy** [comment]
Tested in latest version and it is fixed.
