### ISSUE TITLE
iOS app ate all my data (despite "cellullar upload disabled")

### ISSUE THREAD

**Issue by kgbvax** [mapillary/mapillary_issues#2012]
Current mapillary app on iOS: Photo upload over mobile DISABLED.
Started an upload of 6k pictures on wifi over night. Wifi quit on me and Mapillary app happily continued on cellular, eating my remaining data plan for this month (approx 10G). :-(
Really bad news for me as I am travlling and stuck with 64kbit for ten days.

While I am here, I wish to complain about the rather poor quality of iOS releases.
Language messup, wifi connection complaints, poor battery usage  - now this.

**Comment by millenbop** [comment]
Hi!

So sorry about your data being eaten by the app! I will look into this ASAP to see what happened. We haven't seen this problem before. 

- Could you check if you have WiFi assist enabled? https://support.apple.com/en-us/HT205296
- Which phone are you using and which iOS version?

Again, I'm so sorry you had to experience this, my apologies.

- Anders

**Comment by millenbop** [comment]
I did a test with WiFi connected, and allow upload via cellular was OFF (default). I then started an upload and then disconnected WiFi, and then upload aborted. So it works on iPhone 6 with iOS 9.3.2. 

Will try an older device with an older iOS version next.

**Comment by millenbop** [comment]
Seems to work as expected on iPhone 4 with iOS 7.1.2 too.

**Comment by talllguy** [comment]
@millenbop I noticed the following line in the :apple: support article

> Wi-Fi Assist doesn’t activate with some third-party apps that stream audio or video, or download attachments, like an email app, as they might use large amounts of data.

Is there a way to somehow flag Mapillary as such an app, to prevent cellular upload on Wi-Fi Assist, just out of caution?

**Comment by millenbop** [comment]
Good idea, I'll look into it @talllguy, and I agree, this feature is not something we want in the app, at least not when uploading tons of photos.

**Comment by millenbop** [comment]
I can't find any way for us to disable it for the app. Check the API documentation, StackOverflow and Apple forums. Closing but if you see this problem again even with WiFi assist OFF, let me know.

**Comment by nicolas17** [comment]
Actually

**Comment by nicolas17** [comment]
It looks like the app checks if Wi-Fi is reachable, and if it is, it runs the upload. But Wi-Fi may stop being reachable later and switch to cellular, and then the app may continue uploading over cellular. Checking for reachability periodically isn't enough to prevent this.

The correct way is to do no pre-flight checks, and instead set the NSURLRequest's allowsCellularAccess property.

See [Restricting cellular networking correctly](https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Platform-SpecificNetworkingTechnologies/Platform-SpecificNetworkingTechnologies.html#//apple_ref/doc/uid/TP40010220-CH212-SW9) and the [WWDC2016 session on networking](https://developer.apple.com/videos/play/wwdc2016-714/?time=1484) ([direct .mp4 link](http://devstreaming.apple.com/videos/wwdc/2016/714urluxe140lardrb7/714/714_hd_networking_for_the_modern_internet.mp4#t=1484)).

**Comment by millenbop** [comment]
Ah interesting, thanks for the tip.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
