### ISSUE TITLE
Mapillary app v2.34 automatic mode needs more choices

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2013]
I miss the old driving mode that was in v2.33 and previous versions and half tempted to downgrade and stay at v2.33 til this is fixed.

I want to be able to have an automatic hybrid mode like I had with driving mode. I want to pause my sequence when stop, immediately resume when moved again, distance minimum of 0 meters (for my device) and picture delay minimum of 1.2 seconds (for my device).

I was forced into the automatic mode with v2.34 and the work-ability of using the app's automatic mode is terrible. I had to use the time-based option to avoid overheating and maximizing number of photos over the distance the traveled, but it takes so many photos when i'm stuck at red lights.

A lot of my drives are a mixture of speeds from 25 mph to 70 mph. Automatic distance mode set at the default of 3 meters and if I was traveling at 70 mph would make the app take a picture as soon as it can and cause the my device to overheat which would then crash the camera and/or app. Only way to fix that is a full reboot on Android.

My device can do a picture every 1 second over short usage, but long usage requires me to run Mapillary at 1.2 seconds or more to avoid overheating the device.

Device: Samsung Galaxy S5
Android version: 6.0.1

My settings and use in v2.33 and prior versions:
Mode: Driving Mode
Delay Capture Time: 1.2 seconds
Pause on face-down: Enabled
Pause on stop: Enabled
Pause on shake: Disabled
Pause while tilting: Enabled
Max Tilt: 35 degress
Take High resolution pictures: Enabled
Lock direction forward: Enabled

**Comment by rsahlin** [comment]
Hi @Caboosey and thanks for your comments

Could you please try to disable 'Generate thumbnails' - this should ease the load on the CPU and hopefully reduce the overheating.
- In the long run our goal will be to fix overheating problems, I will rewrite the camera UI and logic which will also help.

- If I understand correctly the problem starts when you drive at higher speeds, where the distance capture makes your phone take two many pictures per second?

Best regards
/Richard

**Comment by rsahlin** [comment]
@Caboosey  could you please send the logs when the phone overheats and stops?

Will look into this when I am back from Vacation in a couple of weeks :-)

Best regards
/Richard

**Comment by Caboosey** [comment]
@rsahlin The logs were recently cleared, but here it is so far:
[mapillary.txt](https://github.com/mapillary/mapillary_issues/files/373741/mapillary.txt)

The phone would always overheat if delay set less than 1.2 seconds even before the Generate thumbnails feature and overheat more when the general outside temperature is hot (in Florida). I even have my A/C blowing right towards the phone. I did disable that "Generate thumbnails" feature right after I found a hidden 18GB .thumbs folder in the mapillary folder on my SD card when I already transferred the the regular mapillary photos to the computer to bulk uploaded by the upload.py script.

70 mph = 31.2928 meters per second. I do not know if this new automatic distance based has the ability to hard set a minimum time delay like the old "driving mode" did. I don't want to risk overheating the phone from the rapid photo capturing.

**Comment by Caboosey** [comment]
@peterneubauer heres the ticket about the overheating.

**Comment by peterneubauer** [comment]
Thanks @Caboosey , much appreciated!

**Comment by Caboosey** [comment]
FYI for documentation:

Device: Samsung Galaxy S5 (SM-G900P)
Device Physical Color: White
Andriod: 6.0.1
Mapillary versions affected: 2.35 thru 2.42 (current)
Bluetooth: Disabled
NFC: Disabled
WiFi: Enabled
Airplane Mode: Disabled
Location Accuracy Level: High
Bluetooth Scanning: Enabled
WiFi Scanning: Enabled

Using time based mode set at 1.3 second per picture or more works without overheating and crashing.


Example of crash and overheat while on distance based:
Starting from 100% battery life within 0.5 miles crashed traveling at 2-3mph on distance mode set at 3 meters in 70F in full and semi shade outside environment.

**Comment by peterneubauer** [comment]
Ok @Caboosey there is 2 things are going to do here.
* put back a `mimium delay` that will prevent images to be taken faster than e.g. 1s. Normally, the phone should be able to throttle picture taking when it is not able to catch up with the requests, but that doesn't seem to be the case on all phones, so let's adjust.
* our next bigger project is to redesign the camera layout to be much more CPU and rendering-efficient and thus lower the power consumption even on the UX end.
* possibly having a mode that will dim the screen after a started sequence until next press (to stop the sequence) - lower prio.

Will that work for you? I'm planning to add the minimum delay setting into the next release.

**Comment by Caboosey** [comment]
@peterneubauer It will work. The overheating has been annoyance and frustrating.

An adjustable minimum delay that applies to all modes will eliminate majority of overheating issues. As in my case with Samsung Galaxy S5, I can run at 1s for every picture for short distances, but have to do 1.3s or more for longer distances to avoid overheating.  I have to run at 1.5s in the summer. I even bought a 6600mAh portable battery pack to keep the phone always at 100% battery level while not in the car to avoid heat generated by discharge and recharge of the phone battery.

The UX changes since v2.33 has been performing better and better in every change. Currently, it loads so much quicker specially when i'm in rural areas where there is no data connection. Previously, the app would take forever to load (waiting for connection timeout) when the phone has no data connection like being in rural area with no cellphone towers.

(Low priority for me as well) Not being to dim the display while using the app can sometimes be a distraction to me as a driver, but I still need to be able to see if it's still taking pictures. Diming will somewhat help will heat and also being able to turn off the cross hairs to avoid screen burn-ins. I only need the cross hairs once the phone to initially mount the phone in my car, but do need it while walking.

**Comment by peterneubauer** [comment]
first option is now implemented and will be in the next release.

**Comment by polarbearing** [comment]
Currently there is no understandable logic between time/distance/compass setting, i.e. is a new picture taken if all or only one condition is met? I.e., AND or OR? I was trying compass=0 and time=2, but it was rapidly shooting as fast as it could.

**Comment by Caboosey** [comment]
@peterneubauer The new update is great. Small bug was introduced with it. It says "Skipping picture, shooting too fast", but still takes picture on distance mode.

**Comment by rsahlin** [comment]
Hi @polarbearing 

You can think of them as triggers.
The time and distance modes are mutually exclusive, it's either time or distance that will provide a trigger.
The compass is a separate trigger - setting compass angle 0 will trigger a capture everytime the change in angle is more than 0 degrees, ie always.
Try compass to the highest value.
- I think we should adjust so that we there is an option to turn off angle driven capture.

Hope this answers your question.

**Comment by peterneubauer** [comment]
Dallam,
yes, that's expected. If the time distance between the last capture and the
current request is less than your configured time, the request will be
skipped, but possibly the next request will succeed.

Are you experiencing that a picture is actually taken while flashing that
capture is skipped? I'm almost certain that this can't happen. Maybe the
flash delay is just too long so the messages from the skipped capture is
still showing while the next picture is taken?

/peter

On Fri, Dec 2, 2016 at 12:10 AM, Dallam Oliver-Lee <notifications@github.com
