### ISSUE TITLE
Android app: battery threshold below 5% is ignored

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2014]
I set the battery threshold to 0%. Nevertheless, the app will stop taking pictures, issuing a warning, when battery is at 5%.

I'm not sure if preventing complete discharge is intended as a safety feature.  As I use a dedicated phone for mapillary capture, and the battery is always the limiting factor in my shooting sessions, I'd rather continue until the battery is completely drained. If you prefer not to allow going below 5%, then the setting slider shouldn't be allowed to move below 5% either.

This is on Android app version 2.31.

**Comment by jfburke3** [comment]
I never noticed this before, but I have experienced it in 2.37 (Android).

**Comment by jfburke3** [comment]
@kaitu If you set the battery threshold to (for example) 15%, does it stop when your battery reaches that level?  I've just noticed that the battery limit seems to be ignored altogether....

**Comment by kaitu** [comment]
Uhm, I tested it in 2.37-jaakkoh and appears to be fixed: capturing stops when the battery limit is reached, and it doesn't stop anymore at 5% when the limit is lower.

**Comment by rsahlin** [comment]
Hi @kaitu and thanks for reporting

I will look into this in the coming week.

Best regards
/Richard

**Comment by kaitu** [comment]
@rsahlin thanks for looking into this. 
The unwanted stop at 5% happened again today.  More precisely, every time I have seen it happen, was while trying to resume after pause: the sequence was stopped instead, with the 5% battery message. Subsequent attemps to start a new sequence, also resulted in an immediate stop with 5% battery message.

**Comment by rsahlin** [comment]
@kaitu Are you charging when this happens, ie is the mobile connected to USB?

There is a check that sets the level to 5% if the phone is charging, however this does not seem correct.
I think the limit should be the same regardless if phone is charging or not.

Best regards
/Richard

**Comment by kaitu** [comment]
@rsahlin Ah, that explains the different behavoiurs I was getting. Indeed the phone was connected to a charger every time the 5% level was triggered. As the phone drains the battery faster than it's recharged, I consistently hit on the 5% problem.

**Comment by rsahlin** [comment]
Good - an update is on it's way and will be out within a week.

Best regards
/Richard
