### ISSUE TITLE
Support camera angle / FOV correction for Sony HDR-AS200 & FDR-X1000

### ISSUE THREAD

**Issue by bhousel** [mapillary/mapillary_issues#2016]
I uploaded a sequence yesterday taken by a Sony HDR-AS200V:
http://www.mapillary.com/map/im/sU1QJG0GyNShAfi5Wp6qKQ/photo

It takes great photos!  But all my images face north on Mapillary.

These Sony cameras record detailed camera angle in the "Track" tag.. It also supports "Track Reference", which I believe can be switched between true and magnetic north:
<img width="475" alt="screenshot 2016-07-20 11 27 30" src="https://cloud.githubusercontent.com/assets/38784/16992413/3291d306-4e6d-11e6-90c3-891343fd0d2a.png">

Another neat thing about these Sony action cameras - they support both 120° and 170° field of view, so it would be cool to have server side correction for fisheye, similar to other action cams like GoPro and Virb.  I don't know what exif tag to watch for in order to perform this correction.  Maybe I will record some 170° images today and see..

**Comment by ybkuang** [comment]
@bhousel yes. We will add the support for `track` angle very soon and rerun the processing for your sequences.

**Comment by bhousel** [comment]
> We will add the support for track angle very soon and rerun the processing for your sequences.

Awesome thanks @ybkuang!   Any rough ETA for this?  I took about 5k more today.  Should I just upload them or hold off?

**Comment by ybkuang** [comment]
@bhousel Just upload them and we will do a reprocess. The update will come next week.
