### ISSUE TITLE
elva, on firefox, photo details pop up.  icon for license is cropped

### ISSUE THREAD

**Issue by rbracket** [mapillary/mapillary_issues#2017]
On linux, firefox 47.0, the CC icon for the License info is cropped.

to reproduce, use elva, open an image
select the elipsis in a circle  (photo detail icon?)
![clippedlicenseicon](https://cloud.githubusercontent.com/assets/688646/16994042/a5222636-4e5a-11e6-8e84-e4ac0ab77e8a.png)

**Comment by knikel** [comment]
This has been fixed, thanks!
