### ISSUE TITLE
Finishing JOSM-Plugin Upload on "Manual Upload"-Website returns 500 - Internal Server Error

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2018]
I uploaded a sequence through Mapillary Plugin for JOSM and was trying to finish the upload through https://www.mapillary.com/map/upload/im/ "Publish to Mapillary" but the xhr request returns a "500 - Internal Server Error" (after clicking the button).

Request Headers:
```
POST /v2/me/uploads/images/47a97807-15d8-447c-87d7-b772010d226e?client_id=[removed] HTTP/1.1
Host: a.mapillary.com
Connection: keep-alive
Content-Length: 46
Accept: application/json, text/plain, */*
Origin: https://www.mapillary.com
Authorization: Bearer [removed]
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: https://www.mapillary.com/map/upload/im/47a97807-15d8-447c-87d7-b772010d226e
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```

Response Headers:

```
HTTP/1.1 500 Internal Server Error
Server: openresty/1.9.3.2
Date: Thu, 21 Jul 2016 00:37:28 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1266
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Request-Method: *
Status: 500 Internal Server Error
X-Request-Id: bdc1dfac-6039-4da5-937f-7d1824366d54
X-Runtime: 1.009577
```

Also wondering about ``X-Runtime: 1.009577``.

![mapillary-issue-1](https://cloud.githubusercontent.com/assets/1118916/17008017/b7c74b5c-4eed-11e6-8bdd-e338d55afbf7.png)

PS: Also deleted all images and tried the procedure again. Same result.
PPS: It seems there would be a problem with manual upload in general. I exported the images from JOSM to my disk again and uploaded them via manual upload on website. I got the same error.

I also tried "private mode" of my webbrowser to avoid problems caused by strange cookies or cached files.

**Comment by gyllen** [comment]
Fixed, sorry for the inconvinience
