### ISSUE TITLE
404 - 72,433,515 photos and you missed them ..

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2019]
Whats going on ?
You doing improvement of the Page ? 
There was no announcement that you doing Maintenance or Upgrade or any Similar

**Comment by knikel** [comment]
@thoschu96 We're updating the web application now, please use `legacy.mapillary.com` before the url that you want to access or click on the rotating arrow to go the landing page that has a link to the old website. Sorry about the inconvenience.

**Comment by thoschu96** [comment]
OK.

What does the Number means ? When the counter of DAY's is at 0.0 it's done ?

What timeframe you expecting for the update ?

**Comment by knikel** [comment]
@thoschu96, when it reaches zero you'll see a new web app. The ETA is 15:00. Until then you can use `legacy.mapillary.com`.

**Comment by HolgerJeromin** [comment]
Quite confusing, but i am pretty sure the full page will be up again at 21 of July 15:00 (that is 2.5 h to go)

Reading the Javascript code shows me that at that time the page will show "The New Mapillary Has Arrived" and reload the page 2 seconds after that. :-)

**Comment by knikel** [comment]
As @HolgerJeromin investigated, that is precisely what's going to happen 😉

**Comment by gyllen** [comment]
Old site is accessible from link in corner on https://www.mapillary.com. Hope you guys will enjoy the new site.

**Comment by knikel** [comment]
We’ve launched, closing 😉

**Comment by de-vries** [comment]
I had to clear my cache to make the new site working
