### ISSUE TITLE
GPSImgDirection not strictly necessary for bulk upload

### ISSUE THREAD

**Issue by mvexel** [mapillary/mapillary_issues#202]
If you assume that the images are a sequence, compass direction could be inferred by looking at the relative position of the images. I have a whole bunch of images from my GoPro that I can augment with the location from a separately recorded GPS track, but geotagging (using `exiftool`) does not add direction to the EXIF data. Or is there another way I should consider?

**Comment by ybkuang** [comment]
We removed the requirement for GPSImgDirection in the web uploader a few weeks ago. Closing this.
