### ISSUE TITLE
Issues in Firefox and Chrome (Linux) with the web uploader

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2020]
### Basic information
* Platform:  `Web`
* System/Browser: Linux Mint 18 Cinnamon 64bit, Firefox 50.a1, Chrome 52.0.2743.82

### Steps to reproduce behavior

 1. Attempt to upload images through the web uploader.

### Expected behavior

Success

### Actual behavior

Firefox: Neither selecting the files in the file chooser nor dragging them into the window changes anything. The window stays exactly the same as before. EFF Privacy Badger and HTTPS Everywhere are deactivated just in case.

Chrome: The files are chosen, the right number of files is shown, the fancy animation to zoom into the location of the images is shown, but the upload stalls at 1.

Midori browser: It works there.

**Comment by retro** [comment]
@mxa We pushed the uploader fixes yesterday, can you please retry and let me know if the issues are fixed for you?

Thanks,
Mihael

**Comment by mxa** [comment]
@retro I can confirm it works now in Linux Mint 18 Cinnamon 64bit, Firefox 50.a1. Thank you!
