### ISSUE TITLE
can't draw new blur

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2022]
### Basic information
* Platform: `ubuntu`
* Version: `16.04` 
* System/Browser: `FF` `Chromium`

### Steps to reproduce behavior

 1. Click edit blurs
 2. Click and drag anywhere to add a new blur

### Expected behavior

new blur

### Actual behavior

nothing

**Comment by ToeBee** [comment]
This affects me as well.

**Comment by ToeBee** [comment]
If you just click two corners (no dragging) it works. But the instructions explicitly say to click and drag

**Comment by HolgerJeromin** [comment]
Oh, yes. Click and move is probably a better wording.

**Comment by oscarlorentzon** [comment]
Thanks for reporting.

As noted above the behavior for creating new blurs right now is defined in MapillaryJS and it is the following:

1. Click to create initial top left point of rectangle
2. Move mouse down right to desired size
3. Click to place bottom right point

If you are unsatisfied with the initial point you can click it again to remove it.

When editing you can drag any corner in any direction except the top right one which shows the delete button when hovered.

Creating in by moving in other directions than down right is a good suggestion for the future.

**Comment by oscarlorentzon** [comment]
The `other direction` suggestion will be tracked here: mapillary/mapillary-js#163

**Comment by ToeBee** [comment]
If this is intended behavior then that is fine but you need to change the user instruction text. "Click and drag" means depressing the mouse button and keeping it down while moving the pointer.

**Comment by de-vries** [comment]
the instructions are better now, closing this in favor of #2047

**Comment by gyllen** [comment]
Also note that we are improving the blur feature this week. Met @ToeBee at SOTMUS and he had some pretty good suggestions.
