### ISSUE TITLE
user name not visible on light background

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2023]
The user name on the right middle (not the top right) of the new viewer is not visible on a light background. Please ad some shadow to the font

example: https://www.mapillary.com/app/index/de%20vries?pKey=AjifDZmUXVKvVG4aLX2E_g&lat=51.675260324118575&lng=5.325064888989655&z=17&focus=photo&menu=false

**Comment by angelday** [comment]
@de-vries we improved the HUD which improves displaying photo author. Your example looks fine now. I'm closing the issue.
