### ISSUE TITLE
multiple edits same sequence possible

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2024]
### Basic information
* Platform: `Web`
* System/Browser: `FF` 

### Steps to reproduce behavior

 1. edit a sequence
 2. repeat step 1

### Expected behavior

get a warning, or find it impossible to edit a sequence that has a pending request

### Actual behavior

I just made two change sets of the same sequence

**Comment by gyllen** [comment]
@de-vries It is possible todo two changes to the same sequence. The last one will then be applied. We are building a system where users can by themselves approve change sets in an area where they have permission. It is then up to the approver to chose what change set to apply.

**Comment by de-vries** [comment]
Ah ok, so it's a feature ;)
Maybe you can improve it by adding something to indicate that a changeset is pending. for example next to the 'edit selection' button.

**Comment by gyllen** [comment]
Another idea would be to just be able to toggle pending changesets when you are in edit view.
