### ISSUE TITLE
Make old urls working again

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2025]
There are some urls in use currently, some are failing right now:

https://www.mapillary.com/map/search/51.88131205481028/8.486093307145211/12 => clean 404

http://www.mapillary.com/map/im/12/50.776667/6.083611 => links to the main map 20,0 zoom1.5 but not fully working

**Comment by gyllen** [comment]
Added redirects. Please open new ticket and add more legacy urls if needed.
