### ISSUE TITLE
New site only show photo spheres in Firefox on Linux

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2026]
- Platform: Web: Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
### Steps to reproduce behavior

Go to any normal image like https://www.mapillary.com/app/user/tryl?lat=55.394135&lng=10.186666&z=17&pKey=WAwGFLl7xIWrXMopS_fPeA&focus=photo
### Expected behavior

Observe that instead of the image there is just black. No errors, no warnings. Logo, arrows, minimap, the bar on the right: Everything else but the image is there.
### Actual behavior

Instead of black: An image.
### Additional information

The old site worked perfectly in this browser. I do not have hardware acceleration, but Firefox emulated it quite nice (slower, but nice). Also see the warnings from the dev console on the screenshot. 

Photo spheres works perfectly.

![mapillary-2016-07-21-bug](https://cloud.githubusercontent.com/assets/8446338/17033086/b47d71e4-4f7c-11e6-87d7-e677ccef5a67.png)

**Comment by oscarlorentzon** [comment]
@simonmikkelsen Thanks for reporting.

Is the regular photo shown at first but disappears after a few seconds or is it black immediately?

**Comment by oscarlorentzon** [comment]
Will be tracked in mapillary/mapillary-js#164

**Comment by oscarlorentzon** [comment]
@simonmikkelsen I made a test build of the next version of MapillaryJS with a potential fix that is available here: https://dl.dropboxusercontent.com/u/40134832/mjs1.5.1/index.html

Could you test that and report if it behaves differently to the version deployed on mapillary.com where you experienced the problem?

Thank you.

**Comment by oscarlorentzon** [comment]
@simonmikkelsen Are you still experiencing problems on [mapillary.com](https://www.mapillary.com)? The MapillaryJS viewer have been updated and the whole image fetching method has been rewritten to handle every fetch equally. There should no longer be any difference between loading a photo sphere or a regular photo.

If not, can you provide example links to photos that you can view and photos that are black?

A note is that there are no errors or warning related to the MapillaryJS viewer in the console output. They are all related to the map.

**Comment by simonmikkelsen** [comment]
@oscarlorentzon It is stille the same :-( In general I have no trouble viewing any spherical image and cannot view no normal image.

This is black: https://www.mapillary.com/app/user/tryl?lat=56.127738&lng=10.0178014&z=17&pKey=YGUVE-DQl5KnrblajGxQOA&focus=photo
This is shown: https://www.mapillary.com/app/user/tryl?lat=56.12558333333333&lng=10.135163888888888&z=17&pKey=6gGnqz1zHfb73U7gwgw5ag&focus=photo

This is inbetween: https://www.mapillary.com/app/user/tryl?lat=56.14133472222222&lng=10.143581388888888&z=17&pKey=4VRj_vrVzq7F6NWntz2Qig&focus=photo
It starts by showing a sphrical image (I think - not just the previous one, I think) and then fades to black. There are navigation controls for both normal and sphrical images and when I rotate the black image, the controls rotate. Using the controls I could navigate to another black image, when I finally arrived at a visible sphrical image.
The same with:

**Comment by gyllen** [comment]
@simonmikkelsen @oscarlorentzon is working really hard to fix this issue, he will be gone on vacation for two weeks now, so expect some delay before he gets back to you

**Comment by oscarlorentzon** [comment]
Closing this because the corresponding issue in the MJS repo has been closed.
