### ISSUE TITLE
Images and links in emails are broken

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2027]
I just got an email about some change requests I submitted. The Mapillary logo at the top is broken (404) as are all the social icons at the bottom. Also, the links to the changesets are broken (also 404s).

At least the map thumbnails seem to be working :)

**Comment by HolgerJeromin** [comment]
#2025 would probably fix the urls in the emails, too.

**Comment by gyllen** [comment]
@knikel I deployed latest API is this fixed then?

**Comment by ToeBee** [comment]
The failing links in the email are pointing at URLs like https://www.mapillary.com/map/cs/T8R3rCHLCRTjYJmzdHUxGI

The images are attempting to load from some obscenely long URL: 
https://ci5.googleusercontent.com/proxy/7w7Xf2jTTRhZMaJk5H1-NPy5-IsxAGAepAemtk1rmogcPqrILQHpvci-aserBgPPTwIbFBfS6ojvehInCLmZ7kqJ1C3RKVgkqoACYC0DDT05MvllQQ=s0-d-e1-ft#https://d1dk9tvuiy3v51.cloudfront.net/img/external/facebook.png

(and the `logo-white.png` file and instagram and twitter icons are similar)

**Comment by knikel** [comment]
@gyllen: I did try to update paths to legacy assets yesterday, but there is a redirect issue in the tiny-server. On it.

**Comment by gyllen** [comment]
@knikel Can we close?

**Comment by ToeBee** [comment]
The last email I got was 36 hours ago and it still has a broken logo image at the top.

**Comment by pbb72** [comment]
The "Your upload is on the map" email I got two days ago was missing the images logo-white.png, twitter-ico.png, wiki.png, instagram.png, twitter.png and facebook.png.

**Comment by knikel** [comment]
I have correct images coming in on my side. I went through all links in emails and double-checked, everything gets served from CDN there. Do you guys use gmail? Perhaps it had the broken url still cached.

**Comment by pbb72** [comment]
Yes, I am using GMail. The URL for the top logo is https://ci6.googleusercontent.com/proxy/Jj5YN_erxXN2FQ554Lw676h66itB3vHz1f-CcWBkxi2lkoiXYhk2dFcGkBt3M6f84d-6Ul5oP6NzjiXPcBL5Ly6WSONJ3aOsYsEhMZGTU_g8ZSYFQy3a=s0-d-e1-ft#https://d1dk9tvuiy3v51.cloudfront.net/img/external/logo-white.png, which gives a 404.

I notice the part after the hash is a full URL, but also when I test that (https://d1dk9tvuiy3v51.cloudfront.net/img/external/logo-white.png, which redirects to https://www.mapillary.com/img/external/logo-white.png) I get a 404.

**Comment by knikel** [comment]
Thanks, these are still the old urls. Everything should be served from cloudfront, checking.

**Comment by knikel** [comment]
@pbb72, @ToeBee, I've sent couple of edits and other emails around, all of them have correct image links. Would you mind checking on your side too?

**Comment by ToeBee** [comment]
I still see broken images. Here is the whole logo table from Gmail's view source option:
```
<table class=3D"box box--header" style=3D"background-color:#fdfdfe;max-widt=
h:450px;width:100%;margin:5px 0;text-align:center;font-family:Helvetica, Ar= 
ial, sans-serif;background-color:#36af6d;color:#fdfdfe;text-align:center">
<tbody>
<tr>
<td class=3D"box__logo-container">
<img class=3D"box__logo" src=3D"https://d1dk9tvuiy3v51.cloudfront.net/img/e=
xternal/logo-white.png" style=3D"padding:50px 5px 50px;height:50px;max-heig=
ht:50px">
</td>
</tr>
</tbody>
</table>
```

I'm not sure what's going on with the line wrapping. There is an = sign at the end of every line that hits 75 characters. Is that gmail doing something weird or what? But regardless, if I try to go to that url (`https://d1dk9tvuiy3v51.cloudfront.net/img/external/logo-white.png`) I get forwarded to `https://www.mapillary.com/img/external/logo-white.png` which returns a 404.

**Comment by gyllen** [comment]
@knikel I did also get a broken logo in some of my blur emails.

**Comment by knikel** [comment]
I'm really lost with this one, we deployed this with @peterneubauer and both got edits, blurs and signup emails with correct CDN urls. Both in the inbox views (Peter, I) and mail clients (I). Pretty much every e-mail template has been touched with the change. Interesting. 💭💭💭

**Comment by pbb72** [comment]
@ToeBee, the `=` equal sign is an escape character in MIME-encoded email. Which is why you see normal equal signs written as `=3D`.

**Comment by pbb72** [comment]
In the change set notification email I just received, all images and links seem to be working fine! :)

**Comment by peterneubauer** [comment]
nice!!
