### ISSUE TITLE
Receiving email notification despite all notifications set to off in preferences.

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2028]
### Basic information
- Platform:  `Web`
### Steps to reproduce behavior
1. request change (in my case sequence angle)
### Expected behavior

No email notifications
### Actual behavior

receiving email notification despite all notifications set to off in preferences.

**Comment by mxa** [comment]
This is a regression in the website. Was fixed but is back now.

**Comment by gyllen** [comment]
@mxa Have you disabled all emails under settings. We are working on the notification system at the moment. So all feedback is welcome.

**Comment by mxa** [comment]
Confirming that I have everything switched off and still get emails. https://www.mapillary.com/app/settings/notifications

"You requested 1 new edits"

**Comment by gyllen** [comment]
@mxa Is it just the edits email you receive or is it other ones too? Trying to narrow this down.....

**Comment by mxa** [comment]
"You got 3 edits approved"
"You requested 5 new changesets"

**Comment by gyllen** [comment]
@peterneubauer Do we check for notifications settings before we send this email out?

**Comment by peterneubauer** [comment]
Yes this is probably not honoring the notification settings, eill change that. Sorry!

**Comment by mxa** [comment]
Please do! I don't like my email to be easily associated with my mapillary username and I don't need the notifications in my email inbox.

**Comment by mxa** [comment]
Desktop notifications on the other hand could be useful. Emails are not.
https://forum.mapillary.com/t/feature-proposal-website-notifications/662

**Comment by gyllen** [comment]
@mxa We just did and update to the Feed on the web, this is a good step towards desktop notifications

**Comment by mxa** [comment]
This is still an issue.

**Comment by gyllen** [comment]
@mxa Yes we know, working hard on new notification system, this will fix this issue for you.

**Comment by gyllen** [comment]
This is no longer an issue. Since 2016 the notifications settings system has been updated.
