### ISSUE TITLE
Inconsistency in edit buttons

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2029]
On the new website, if I'm in focus=map mode (big map, small photo on the corner), the map has a (···) button with "Edit sequence" and the small photo has a (···) button with "Edit blurs". However, if I'm in focus=photo mode (big photo, small map on the corner), the photo has a (···) button with "Edit blurs", but the small map has nothing; there is no way to edit the sequence from there.

I guess editing the sequence in the small map would be inconvenient, but then there should still be a button to edit the sequence, which automatically switches to big-map mode.

**Comment by gyllen** [comment]
@angelday Design issue

**Comment by de-vries** [comment]
Ah ok, so it's a feature ;) 
Maybe you can improve it by adding something to indicate that a changeset is pending. for example next to the 'edit selection' button.

**Comment by gyllen** [comment]
We have now made this more consistent. Let us know what you think @nicolas17
