### ISSUE TITLE
Small blur rectangles appear as big dots in the editor

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2030]
The blur rectangles in the new blur editor have thick borders and a circle in the middle to drag the rectangle around. Very small blur rectangles are often completely covered by the circle.

Drawing new tiny rects is possible because the blur rect border is 1px while you're drawing it, but once you finish it's nearly impossible to edit; same if you try to edit an existing rectangle. (Editing wasn't possible at all in the old editor though, you had to delete and re-create the rect, so this is not really a regression).

Here is an [example](https://www.mapillary.com/app/?pKey=2Z_7NXykUPELiy1HtaCA4g&focus=photo):
![Screenshot showing the license plate blur rect almost entirely covered by the rectangle-drag circle](https://cloud.githubusercontent.com/assets/101955/17034563/997d3e1a-4f59-11e6-8e20-cd0c4fdeafa0.png)

**Comment by oscarlorentzon** [comment]
Thanks for reporting.

Agree that editing small rectangles, which are often present, is not simple currently. 

The implementation of mapillary/mapillary-js#112 this will be a big help for scenarios like this one.

We will also have to think about the design.

**Comment by nicolas17** [comment]
Totally agree that zooming would fix this in practice.

**Comment by oscarlorentzon** [comment]
It is now possible to pan/tilt/zoom in all photos so even small blur rectangles in zoomed out mode should be editable in an easy way when zoomed in. 

Regarding the actual design of the blur rectangles and their appearance when shown I'm going to reassign to @angelday .

**Comment by nicolas17** [comment]
This works and it's useful. But it's weird that panning on normal photos works as if it was a spherical pano.

![Panning normal photo](https://cloud.githubusercontent.com/assets/101955/17449160/21a45478-5b2f-11e6-8bfe-2eb628b8b013.png)

**Comment by gyllen** [comment]
@nickplesha Its the solution we went for since it the most consistent one, most people seem to like it

**Comment by nickplesha** [comment]
Closing as this is resolved.
