### ISSUE TITLE
I CANT  LOGIN USING MY ARCGIS ONLINE ACCOUNT

### ISSUE THREAD

**Issue by garridolecca** [mapillary/mapillary_issues#2031]
### Basic information
* Platform: `iOS` | `Android` | `Web`
* Version: `...` 
* System/Browser: `...` 

### Steps to reproduce behavior

 1.
 2.
 3.

### Expected behavior

...

### Actual behavior

...

### Additional information

...

**Comment by octanebaby** [comment]
Hello!  We will be adding ArcGIS login capabilities shortly.  In the meantime, are you looking for the ArcGIS web app for ArcGIS Online? If so, you can try out our demo here: http://arcgis-demo.mapillary.io/ .  

Please let us know how you would like to use Mapillary with ArcGIS and we can try and help you further.  Email sales@mapillary.com.

**Comment by garridolecca** [comment]
Hello,

I am part of the Esri distributor team here in latin America, I am
interested in testing the app to recommend it to out clients of many
sectors, do you have a skype account have a little meeting?

What i need is to take the photos in the cell phone and after that see the
3d map in the ArcGIS online app.


*=========================================================*
*Dios nos guarde y nos guie por sus caminos rectos !*

*César Jhonatan Garrido Lecca Rivera*
*Geotechnology** S**pecialist *
*RPC: 991480606 *




2016-07-21 15:15 GMT-05:00 octanebaby <notifications@github.com>:

**Comment by octanebaby** [comment]
We are happy to have a meeting over Skype! Please email us with your availability tomorrow (Friday).
sales@mapillary.com

**Comment by garridolecca** [comment]
Well, perfect.

I am working for the Peruvian's Esri distributor, so what I need for the
moment is try your app integrated with the ArcGIS online platform. I don't
know how exactly is working your integration in the ArcGIS store.

Tomorrow maybe you can explain to me that, I have time tomorrow at 1pm
-5:00 UTC, or maybe today at 6:30pm -5UTC.

Thanks,


*=========================================================*
*Dios nos guarde y nos guie por sus caminos rectos !*

*César Jhonatan Garrido Lecca Rivera*
*Geotechnology** S**pecialist *
*RPC: 991480606 *




2016-07-21 15:39 GMT-05:00 octanebaby <notifications@github.com>:

**Comment by garridolecca** [comment]
1 pm UTC-5 tomorow will be good.  Please add me on Skype: janineyoong.  I
will show you a demo over Skype screenshare as well if the connection is
good.

Looking forward to speaking.

**Comment by garridolecca** [comment]
Perfect!.

See you tomorrow.


*=========================================================*
*Dios nos guarde y nos guie por sus caminos rectos !*

*César Jhonatan Garrido Lecca Rivera*
*Geotechnology** S**pecialist *
*RPC: 991480606 *




2016-07-21 15:59 GMT-05:00 Janine Yoong <janine@mapillary.com>:

> 1 pm UTC-5 tomorow will be good.  Please add me on Skype: janineyoong.  I
> will show you a demo over Skype screenshare as well if the connection is
> good.
>
> Looking forward to speaking.
>
> On Thu, Jul 21, 2016 at 4:55 PM, Cesar Jhonatan Garrido Lecca Rivera <
