### ISSUE TITLE
Password reset fails / not possible

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2032]
The url that is loaded from the android app https://www.mapillary.com/map/sendpassword gives a 404 also trying a password reset from the user profile I do not get any mail with a reset link

**Comment by HolgerJeromin** [comment]
same as #2021

**Comment by mprins** [comment]
No, not getting an email after using the reset password option from website is not the same as #2021

**Comment by mprins** [comment]
No, not getting an email after using the reset password option from website is not the same as #2021

**Comment by mprins** [comment]
No, not getting an email after using the reset password option from website is not the same as #2021

**Comment by gyllen** [comment]
Fixed

**Comment by gyllen** [comment]
@knikel We need to create an endpoint for send password

**Comment by gyllen** [comment]
@peterneubauer @rsahlin App should use API not webpage to request new password.

**Comment by peterneubauer** [comment]
@gyllen yes agreed, first we need to fix the redirect and website endpoint for existing Android devices though, made https://github.com/mapillary/mapillary_android/issues/227 to track this.

**Comment by knikel** [comment]
I've added a redirect from `mapillary.com/map/sendpassword` to `mapillary.com/sendpassword`. The static mini-app has the `LoginFormComponent` and handles sending passwords, therefore handles sending passwords at `/sendpassword` url.

**Comment by gyllen** [comment]
Closing this since @knikel fix should fix it. Doing it natively is another issue.
