### ISSUE TITLE
Mixed Content Warnings

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2033]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 7 SP1 64-bit/Google Chrome 51.0.2704.106` 

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/
 2. Choose the menu button
 3. Click on Leaderboard

### Expected behavior

No Errors

### Actual behavior

Mixed Content: The page at 'https://www.mapillary.com/app/stats' was loaded over HTTPS, but requested an insecure image 'http://www.mapillary.com/img/fake-avatar.png'. This content should also be served over HTTPS.

### Additional information

Also some HTTP 404 errors appear.

![2016-07-21_01](https://cloud.githubusercontent.com/assets/12619646/17039012/07e9f768-4f5e-11e6-8a7b-60d60fb172aa.jpg)

**Comment by knikel** [comment]
This has been fixed, will be visible in the next deploy.
