### ISSUE TITLE
404 on https://www.mapillary.com/map/upload/im when trying to use JOSM to upload pictures

### ISSUE THREAD

**Issue by dthgeek** [mapillary/mapillary_issues#2034]
### Basic information
* Platform: Ubuntu 14.04 
* JOSM 10526
* Mapillary plugin version 32639
* Browser: Firefox 47.0
* Garmin Virb XE

### Steps to reproduce behavior

 1. Take a few hundred pictures with a new Garmine Virb XE
 2. Edit the first 150 of the pictures and delete duplicates 
 3. Interpolate the direction using the python script 
 4. run sequence_split.py
 5. Run JOSM from the terminal using /usr/lib/jvm/java-7-oracle/bin/java
 6. Open GPX track that was recored in the same area as images
 7. Import pictures into sequence 
 8. Download from OSM in the same area
 9. Click on first images in sequence 
10. Clikc on Upload pictures 
11. Uncheck box next to Delete after upload 
12. Click OK then wait as it goes from INFO: Uploading: (1/137) (Mapillary) all the way to INFO: Uploading: (136/137) (Mapillary) and question why it doesn't end at (137/137)
13. Click on Approve upload on the website 
14. Firefox opens https://www.mapillary.com/map/upload/im and displays "404" "72,589,134 photos and you missed them" 

PS the help page https://www.mapillary.com/help is giving me a 404 error 
### Expected behavior

It would work but since I've never done this before I don't really know what should happen next

### Actual behavior

I get a 404 error and images don't upload 

### Additional information
I'm also being told "You need to sign in or sign up before continuing." when I go to http://api.mapillary.com/v1/u/uploadhashes and signing out and signing back in doesn't help which so it doesn't look like I can use the python script to upload the pictures and when I tried to upload pictures using Firefox it gets stuck at Uploading 0 / 137 and when I use Chromium it gets stuck at Uploading 1 / 137 but it also is giving me the error "This page is trying to load scripts from unauthenticated sources"

**Comment by talllguy** [comment]
I can confirm that https://www.mapillary.com/map/upload/im is down. I use this URL often and it used to work, so I suspect this has something to do with the new uploader.

**Comment by gyllen** [comment]
@talllguy Do you use it for confirming uploads or for new uploads. For new uploads you can use the new uploader which is here https://www.mapillary.com/app/uploader.

For confirming (while we are readding this functionality). Just use http://legacy.mapillary.com/map/upload/im

Old website will be up for time beeing.

**Comment by gyllen** [comment]
I also created a redirect from https://www.mapillary.com/map/upload/im to https://legacy.mapillary.com/map/upload/im in case anyone else bumps into the same problem.

**Comment by talllguy** [comment]
@gyllen I personally don't have any need to get to that page anymore, but I think the OP @dthgeek who was uploading via JOSM would.

**Comment by dthgeek** [comment]
Things are working now thank you
