### ISSUE TITLE
iPhone Panos no longer interactive in Elva

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2035]
### Basic information
* Platform: `Web` `elva`
* System/Browser: `Windows / Chrome`

### Steps to reproduce behavior

 1. Navigate to a photo that is an iOS native camera app panorama
 2. Observe that the image is blurry
 3. Attempt to pan around. No :game_die:.

### Expected behavior

Photo viewer should be able to be panned around with a mouse-click-and-drag gesture

### Actual behavior

Blurry, static photo. :crying_cat_face: 

### Additional information

Example. [Link here](http://mapillary.com/map/im/zlh78bgyhrgI3FoudqRVVA).
![image](https://cloud.githubusercontent.com/assets/1827881/17044605/ade974d2-4f8f-11e6-8bc5-411d539de06d.png)

Here's the Pano mode on :iphone: 
![image](https://cloud.githubusercontent.com/assets/1827881/17044634/f4b76d4c-4f8f-11e6-8acf-c31136d339b2.png)

**Comment by oscarlorentzon** [comment]
This will be tracked in mapillary/mapillary-js#166

**Comment by oscarlorentzon** [comment]
Cropped panos are now shown with higher resolution thumbnails and they are draggable and zoomable.
