### ISSUE TITLE
Browser chokes on areas with a very high density of images

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2036]
### Basic information
- Platform: `Web (elva)`
- System/Browser: `Windows 10` `Chrome`
### Steps to reproduce behavior
1. Navigate the map to Knoxville, TN, USA (_apparant home to some highly prolific Mapillary users, and kudos to them!_)
2. Note the massive blob of green dots in the downtown area.
3. Scroll around on the map. Zoom, pan, rotate.
4. Chrome starts to balk and throw :x: red errors.
### Expected behavior

Silky smooth map navigation
### Actual behavior

Janky UK House style map navigation
### Additional information

This seems like an edge case, but can be useful to study the performance of Mapbox GL and Elva.

![image](https://cloud.githubusercontent.com/assets/1827881/17044960/d9306aee-4f92-11e6-8c26-288e9286afc5.png)
[Console Log as :octocat: gist](https://gist.github.com/talllguy/59174280eb5ccf2c48d812dbbdc1b0a1)

![image](https://cloud.githubusercontent.com/assets/1827881/17044953/bfd98a6c-4f92-11e6-932b-79c7409d5083.png)
Holy Green-dots batman!

**Comment by talllguy** [comment]
@oscarlorentzon those are some mapillary-js errors I think.

**Comment by oscarlorentzon** [comment]
@talllguy Correct, there is a problem loading one of the tiles from the API inside MapillaryJS. It is not directly related to the map browser choke though. I will write an issue on MapillaryJS regarding  problems with loading of large tiles and link it here.

**Comment by gyllen** [comment]
BTW This area has an insane density :)

**Comment by oscarlorentzon** [comment]
We have made performance optimizations in MapillaryJS 2.0 and MapillaryJS now handles this area without lag or errors. The performance `choke` in this area is now related to the map only.

See for example (MapillaryJS loads fast and the website becomes unresponsive first when the map tile data is loaded): https://www.mapillary.com/app/?lat=35.967025879491885&lng=-83.91845264496537&z=16.55813688198569&focus=map&pKey=pTsvfJqJL7aU6-E4pe41rQ&menu=false

@gyllen Please reassign accordingly.

**Comment by gyllen** [comment]
@ptpt We need to figure out how to make these tiles more lightweight.

**Comment by ptpt** [comment]
Assume image keys consume most of tile sizes. One solution might be removing them from these dense areas.

**Comment by ptpt** [comment]
Thanks @talllguy. We will solve it when it is not a special case. Closing.
