### ISSUE TITLE
Sidebar hides the map controls and copyright text

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2038]
### Basic information
* Platform:  `Web`
* System/Browser: `Windows 10` `Chrome`

### Steps to reproduce behavior

 1. Open the site to anywhere on earth. look at the map
 2. Scroll around <kbd>Ctrl</kbd> and drag to rotate on Windows if you want.
 3. Open the sidebar (or close it if it is already open). Toggle. Note the elements are hidden / revealed.

### Expected behavior

Opening the sidebar would push the map controls and copyright text out with it, along with the :white_circle: ellipsis.

### Actual behavior

Opening the sidebar hides the map controls and copyright text. Note that the ellipsis circle moves with the sidebar.

### Additional information

Upside-down mode demo of this issue
![animation 1](https://cloud.githubusercontent.com/assets/1827881/17045413/1e68736e-4f97-11e6-81a7-bb9b13426c70.gif)

_Note: OSM purists may find this upsetting :rage1:_

**Comment by angelday** [comment]
@gyllen: does this need design work? The map zoom controls should scroll with the sidebar.

**Comment by gyllen** [comment]
@angelday Reassigning

**Comment by talllguy** [comment]
@gyllen @angelday Looks like someone fixed this. It looks  good now!
