### ISSUE TITLE
The word "all" is misplaced on the 404 page

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2039]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 10` / `Chrome`

### Steps to reproduce behavior

 1. Go to a bad url on Mapillary.com, such as [this one](https://www.mapillary.com/map/upload/im) (see #2034).
 2. Observe cool 404 page. :snowflake: 
 3. Note that the word "all" appears in the corner.

### Expected behavior

"all" should be with the other words

### Actual behavior

"all" is in the corner

### Additional information

![image](https://cloud.githubusercontent.com/assets/1827881/17045792/b1711190-4f9a-11e6-8665-0e398fee9208.png)

**Comment by angelday** [comment]
This is actually intentional, closing.

**Comment by talllguy** [comment]
:smile: I was thinking that was a possibility too.

**Comment by de-vries** [comment]
@angelday That's one of the best 404 pages I've ever seen.

**Comment by angelday** [comment]
@de-vries thank you! I was merely building on @gyllen 's idea.

**Comment by millenbop** [comment]
I didn't get it either :)
