### ISSUE TITLE
Add back the "clear all blurs, submit and advance" button

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2045]

**Comment by richlv** [comment]
looks like something similar has been added, but it might not work that well yet :)
a) the button seems to work also if there are no blurs in the photo (which might be just fine...)
b) but it also seems to submit a request to clear blurs on images that had no blurs in the first place.

apparently i just submitted 50 blur requests like that accidentally. if there are no blurs in the image in the first place, it shouldn't submit a request to clear the non-existent blurs.

**Comment by kaitu** [comment]
A button to advance to the next blurred image in sequence would also be nice.
It's pretty boring to review each and every photo of a sequence were it's known that no blurs should be needed, just to catch false positives.

**Comment by richlv** [comment]
@kaitu, that's a different topic and already tracked in issues #357 and #253

**Comment by kaitu** [comment]
@richlv, sorry for the duplicate. Since the title mentioned the advance button, I thought I was somewhat on topic. I hadn't noticed though that you had already asked exactly the same in the referenced issues, thanks for pointing that out.

**Comment by de-vries** [comment]
I really like this new feature, but I find the advance part inconsistent because the editor doesn't advance when the `submit` button is pressed. I'd like to propose to replace the `submit` button with a `submit and advance` button and maybe also a `submit and exit` button

**Comment by peterneubauer** [comment]
This is working now right?
