### ISSUE TITLE
Make creating rects react on mouse draw

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2047]
### Expected behavior

For creating a blur on has to click, release the mouse button, draw,
and click again.
This is counter intuitive since all other programs I know (and even
the old mapillary) would start drawing after click with holding the
mouse button, draw and after releasing the button the drawing would
be finished.

**Comment by millenbop** [comment]
I agree with @peterneubauer as I myself had a hard time figuring out how it worked. The instructions also explicitly say that you should press and drag.

**Comment by ybkuang** [comment]
Same here. When I used it the first time, I thought the drawing is not working because I didn't release the click. Took me quite some time to realize.

**Comment by angelday** [comment]
+ @oscarlorentzon + @gyllen 

This is a well known issue. Currently it's implemented this way as it was conflicting with the pano views where left click and drag is for panning around. I suggested an alternative interaction pattern here: https://github.com/mapillary/mapillary_elva/issues/297#issuecomment-233190080

Short term copy in the popup was improved ( https://github.com/mapillary/mapillary_elva/commit/5b567899c4d9b0af30696eb431ce7c18a427eb5e ), long term we will change this counter intuitive behaviour.

**Comment by pbb72** [comment]
@angelday you say the copy (the text?) in the popup was improved? I cannot look at the linked code, so I don't know what was changed, but currently the popup says "Click, release, drag and click again" which does not make sense since dragging is moving with the button down. The popup should say "Click, release, move the mouse, and click again".

**Comment by angelday** [comment]
@pbb72 changed copy to `Click, release, move the mouse, and click again`, thanks for pointing it out. (Yes, copy "refers to written material" https://en.wikipedia.org/wiki/Copy_(written) )

**Comment by pbb72** [comment]
Thanks for the update!

(I'm no expert, but I think "copy" is a more specific form of "text", applying to considerable amounts of text. An article is copy, but not a label.)

**Comment by richlv** [comment]
the instruction have been updated and the mode is unlikely to be changed (as dragging now pans the image) - should this issue be closed ?

**Comment by de-vries** [comment]
There is still the possibility to move panning to `right-click` or `shift-click`

**Comment by pbb72** [comment]
...or just to disable panning while drawing a rectangle.

**Comment by richlv** [comment]
@pbb72, but how would one determine when panning is intended, and when the rectangle operation is intended ? the dragging would be the same.

**Comment by pbb72** [comment]
@richlv True, didn't think this properly through.

Actually, many interfaces that allow both dragging a background and drawing rectangles on top of it, use Shift+Drag to draw. See for example the zoom to area functionality on OSM's slippy map.

**Comment by gyllen** [comment]
@richlv Your right on point ux problem is that we have two different things we want to do with drag.

I do like the modifier key and I think that it will probably be used by power users. But we probably need some kind of mode buttons for new users. So they can clearly see if they are in dragging or blur mode.

**Comment by richlv** [comment]
one way would be having modes with buttons like josm does - although it would slightly clutter the interface

**Comment by pbb72** [comment]
A new thought -- In the current situation, it's possible to pan while drawing a rectangle. This is valuable functionality. In solutions with modifier keys or toggle buttons, that will no longer be possible.

I'm moving more towards that the current solution might actually be the best.

**Comment by richlv** [comment]
i'm not a huge fan of the modifier keys at this time - but why wouldn't it be possible to have panning on normal drag + rectangle on shift+drag (or vice versa) ?

**Comment by pbb72** [comment]
@richlv because you start drawing a rectangle by holding down Shift and dragging. Then, when you want to start panning while drawing the rectangle, you release Shift. At that moment, an end of the Shift+Drag action is observed, and the rectangle is finished, which makes it impossible to pan while drawing a rectangle.

This is normally how modifiers behave in my experience, but maybe it's possible to program around that problem.

**Comment by gyllen** [comment]
I think modifier key is the only way to go. Thats is how its solved in most editors today.

**Comment by de-vries** [comment]
@gyllen If you go with `Shift-drag` then I think you should also keep the current method. It's easier for noobs and touch screens.

**Comment by HolgerJeromin** [comment]
Josm has right mouse to pan and left mouse for drag.

**Comment by pbb72** [comment]
@HolgerJeromin that is correct. But in JOSM, drawing is a primary functionality, and padding is secondary (only a necessity to aid in drawing). In the main Mapillary interface there is no drawing functionality, and panning is the most logical function to put under the left mouse button (especially for 360 degree photos).

In this situation, I think it would be confusing if the panning is moved to the right mouse button only for blurring interface.

**Comment by HolgerJeromin** [comment]
Good point!

**Comment by nickplesha** [comment]
Drawing rectangles is now done by click+dragging and panning is done with the `Ctrl` modifier key. This refers to the tag editor as the blur editor is currently disabled.
