### ISSUE TITLE
JOSM remote control not working with new website

### ISSUE THREAD

**Issue by richardbrinkman** [mapillary/mapillary_issues#2049]
### Basic information
* Platform: Web
* System/Browser: Fedora 24, Google Chrome 52.0.2743.82-1.x86_64 (JOSM 10526)

### Steps to reproduce behavior

 1. Go to any photo
 2. Click on the `...`
 3. Click on `edit via JOSM`

### Expected behavior

The location to show up on the running instance of JOSM.

### Actual behavior

A new browser tab is opened with address `http://127.0.0.1:8111/load_and_zoom?left=52.20172535893512&right=52.205725358935126&top=6.830831820476508&bottom=6.8348318204765075` and the following information:

> # HTTP Error 400: Bad Request
> 
> The minima must be less than the maxima

### Additional information

Remote control is working on the openstreetmap.org page. So the problem relies not in JOSM.
Old version of the website did not have this error.

**Comment by peterneubauer** [comment]
Sorry, that was a bug in the URL generation. Fixed, URLs will now be something like http://127.0.0.1:8111/load_and_zoom?left=10.591608490538485&right=10.595608490538487&top=57.743346780162156&bottom=57.73934678016215

**Comment by Cyrille37** [comment]
Tks, it's work now.
