### ISSUE TITLE
HSTS and other security headers

### ISSUE THREAD

**Issue by emilstahl** [mapillary/mapillary_issues#2050]
Hi

This could be a lot better:
https://securityheaders.io/?q=https%3A%2F%2Fwww.mapillary.com

You should start with HSTS :)

Example (my own site): https://securityheaders.io/?q=https%3A%2F%2Fipv6-adresse.dk%2F

**Comment by emilstahl** [comment]
@gyllen Forgot or _won't fix_? 😉

**Comment by gyllen** [comment]
@emilstahl Still no decision. I my opinion we will need todo this. Thanks for bumping issue again.

**Comment by gyllen** [comment]
@martinskans Reassigning to you for decision

**Comment by martinskans** [comment]
Looking into this a bit I find that we have some limitations - we are using Amazon's elastic load balancers which do not have support for adding headers so we have to add the headers for all underlying service endpoints (external domains) as it is now. I started by adding HSTS to the https://mapillary.com entrypoint which is basically just a redirect to www and I'm working on at least getting that header out from the API and www. The rest of the headers probably need a bit of thinking so we don't break our own cross-references :)

**Comment by martinskans** [comment]
The api (a.mapillary.com) has hsts enabled now and I've talked to the web team about adding it to www so this should be resolved shortly for the main public entry points.

**Comment by gyllen** [comment]
Closing since moved internaly
