### ISSUE TITLE
open in JOSM does not work anymore

### ISSUE THREAD

**Issue by Cyrille37** [mapillary/mapillary_issues#2052]
### Basic information
* Platform: Web
* Version: 2016-07-22
* System/Browser: Ubuntu 14.04 LTS / Firefox 47

1. On a photo in explore map, call "Edit via JOSM".

2. The computed url is : http://127.0.0.1:8111/load_and_zoom?left=47.40128732996752&right=47.40528732996753&top=0.6927304094582166&bottom=0.6967304094582166

### Expected behavior

Should open the zone in JOSM

### Actual behavior

Throw a http error : 
HTTP Error 400: Bad Request
La valeur minimum doit être plus petite que la valeur maximum 

Cheers, Cyrille

**Comment by floscher** [comment]
Same as #2049.

**Comment by gyllen** [comment]
Should be deployed now

**Comment by Cyrille37** [comment]
Tks, it's work now.
