### ISSUE TITLE
Feature request: display date of photo in viewer

### ISSUE THREAD

**Issue by Olestas** [mapillary/mapillary_issues#2053]
Old viewer displayed date of photo. Please return it for easy viewing.
Now I need to open each photo details to see when it was taken. 
This is street view, main thing here is how old is it.
Thank you.

**Comment by gyllen** [comment]
I think we should do this.

**Comment by jesolem** [comment]
Agree.

**Comment by nickplesha** [comment]
This has been implemented and deployed.
