### ISSUE TITLE
Question about upload : Optimal granularity of a sequence ? 

### ISSUE THREAD

**Issue by tdurand** [mapillary/mapillary_issues#2054]
Hello, 

It's not a bug, but more a question about the best way to upload some footage i have to mapillary.

I have tons of high quality pictures of the downtown of Medellín (Colombia), which [were shot for a webdocumentary](https://medium.com/@tibbb/how-we-created-an-immersive-street-walk-experience-with-a-gopro-and-javascript-f442cf8aa2dd) i built which features a street view like experience. It was made to be super linear and **there is 3-4 picture for each meter of the street**.

**I was wondering if it was usefull to upload them all or just limit to 1 / pict / meter .. ?** 

I need to figure out also if mapillary does infer bearing right with my sequences, i didn't write it on the EXIF tags (i just tagged the GPS coordinates with a custom command line tool for each pictures), but i'm unable to verify it before you publish them. (i have each street both ways <->)

![screen shot 2016-07-22 at 17 09 18](https://cloud.githubusercontent.com/assets/533590/17061543/551cf838-502f-11e6-868f-8a70e261371b.png)

![screen shot 2016-07-22 at 17 09 38](https://cloud.githubusercontent.com/assets/533590/17061545/5860fdaa-502f-11e6-9786-c713f6419ff7.png)

Thanks and congrats for this new front-end ! 

Thibault

PS: you can find this upload on my nickname on mapillary: tdurand

**Comment by gyllen** [comment]
Hi Thibault!

Looks like your images have the best of qualities 👍 

I would say one image every third meter is good enough. If you want to be extra fancy you can do one every second.

Closing this, reopen if you have anymore questions.

**Comment by tdurand** [comment]
Ok i see the footage was validaded, but as i suspected, the bearing wasn't inferred right, it was previsible because mapillary has not data to infer it, the timestamp of the pictures are all the same. 

![screen shot 2016-07-23 at 08 57 43](https://cloud.githubusercontent.com/assets/533590/17076513/4b11314e-50b4-11e6-85ac-c3494b745017.png)

Also i don't know if it's a bug of the front-end, but the sequence green line isn't appearing.

I will update my script to tag the bearing on the EXIF data (saw you have [something that my help to that](https://github.com/mapillary/mapillary_tools/blob/master/python/interpolate_direction.py)) and upload the pictures again (likely on monday), i'll ping you here to see if the result is OK and then i'll be able to upload the 20.000 remaining pictures ;-). 

Have a nice week-end

**Comment by knikel** [comment]
@tdurand In the new editor, you can easily tweak the positions of photos. It'll still be a lot of clicking. However you shouldn't worry about the bearing being off. It seems to me that most photos in http://www.pregonerosdemedellin.com are looking towards one another, after the upload in the editor you can _normalize_ the compass angles. It will interpolate the compass angles between photos so they look towards one another. I'd recommend doing that after correcting the positions though. Let me know if there is any other way to help you out with the uploads/editing?

**Comment by tdurand** [comment]
@knikel  Where is the option to normalize the angles in the editor ? Didn't see it. The position are correct and now i can see the green line on the editor, don't know why i couldn't last week.

**Comment by knikel** [comment]
@tdurand, there you go:
![before](https://cloud.githubusercontent.com/assets/1574656/17094177/ee07fb18-524d-11e6-92a3-c5e325e3bf47.png)

![after](https://cloud.githubusercontent.com/assets/1574656/17094182/f1737066-524d-11e6-85c3-9a5620a93f4d.png)

**Comment by tdurand** [comment]
Seems the normalize sequence option doesn't find properly the angle, it's stills reverse than the correct angle. I'll try the command line tool.

BTW: was tricky to find the "..." icon to enter the editor, i think it should be more visible ;-) .

![screen shot 2016-07-25 at 10 01 58](https://cloud.githubusercontent.com/assets/533590/17094367/1cdf50c0-524f-11e6-986c-50b21317b31e.png)

**Comment by knikel** [comment]
Good points. We'll test the normalisation since it might be the density that confuses it slightly. Thanks a lot for the feedback!

ping @angelday, @retro.

**Comment by tdurand** [comment]
I've tried to upload 11 pictures of another street, i tagged 1s of difference in the timestamp of the image, maybe normalizer will infer better the order of the picture, i saw the interpolate_direction.py script was based on timestamp.

As i can't review the bearing before having the pictures publish, could you look into that upload ?

**Comment by tdurand** [comment]
Okay. I think i have everything solved @knikel 

- The bearing / angle wasn't inferred right because the timestamp of the pictures was the same for every pictures, i did an other upload with 1sec diference for each pictures and the normalizer is inferring the bearing right. I think you guys should add some validation there, **it should be impossible for someone to upload a sequence of picture with the same timestamp for every picture** (like it is in the command line tool)

- the interpolate_direction.py script is working like a charm, the third test upload i've done has the correct bearing.

- I now would need to use the **upload_with_authentication.py** script to avoid having to do manual work with the UI. For that i need **MAPILLARY_PERMISSION_HASH** and **MAPILLARY_SIGNATURE_HASH** , where am i able to find this in my settings ? 

- Also is it possible to delete all my current uploads ? I didn't see the option.

Thanks !

**Comment by knikel** [comment]
Awesome, good point! Great that it worked out. We haven't moved over the upload hashes to the new UI yet, you can find them [here](http://legacy.mapillary.com/map/upload/im), you'll probably have to login again. We'll keep the `legacy.mapillary.com` until we get feature parity.

**Comment by angelday** [comment]
> Also is it possible to delete all my current uploads ? I didn't see the option.

We're working on this feature.

**Comment by tdurand** [comment]
Ok, will try to upload everything by tomorrow ( on the nigh, i have a weak upload ), then you guys may be able to delete the first 3 uploads that won't be relevant afterwise

**Comment by tdurand** [comment]
Ok, 25000 pictures uploaded ! 

But because of an issue with the interpolate_direction.py script : https://github.com/mapillary/mapillary_tools/issues/115 ,  i wasn't able to normalize the bearing of the sequences.

Is it possible for you guys to run it on my uploads ? Because if i want to do it manually with the web ui it will take me some time.

Also i would like to delete the first 3 upload with are not relevant anymore, sequence keys:

- VeiBBZtNcmJWogcjHKm0iw
- lGfXVV8poo0xFZQeKX9urQ
- VBMRbJm6V_2H5P9lAuaX5Q

**Comment by knikel** [comment]
:boom: Awesome news @tdurand 
Ping @gyllen or @peterneubauer, sequence deletion request ☝️

**Comment by gyllen** [comment]
@tdurand Can you normalize in an edit?

**Comment by tdurand** [comment]
@gyllen Yes i can, it's just it's a lot of manual clicking to do it on all the sequences.

**Comment by gyllen** [comment]
@tdurand It should be 1 click per sequence though. How many do you have? I can help you with a couple ;)

**Comment by tdurand** [comment]
It's ok i just submitted all the normalization. It's just it was a bit long because on the new UI when you normalize and go back to the list of upload of the right, the infinite scroll doesn't keep the same position so you need to scroll again to the next one... a bit annoying when you have 50+ uploads to go threw.

I guess it's now everything good, just missing to delete those 3 sequences and we are fine !

- VeiBBZtNcmJWogcjHKm0iw
- lGfXVV8poo0xFZQeKX9urQ
- VBMRbJm6V_2H5P9lAuaX5Q

**Comment by gyllen** [comment]
@tdurand Fully agree with you, we need better filtering of your own sequences.
