### ISSUE TITLE
mapillary.com/help broke

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2055]
In the new viewer the help link just 404ed on me. 

The url is `mapillary.com/help`. Before there  was `mapillary.com/map/help` but its contents are moved to [legacy.mapillary.com/map/help](http://legacy.mapillary.com/map/help)

**Comment by pbb72** [comment]
I can reproduce this. To clarify: this is in regard to the "Help" link in the sidemenu of the main viewer. The help link on the front page is correct, this points to https://github.com/mapillary/UserGuide/wiki.

**Comment by gyllen** [comment]
Thanks for reporting. Now fixed.
