### ISSUE TITLE
minor redirect issue

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2056]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1.enter an old url like`mapillary.com/map/im/<photo_hash>/photo`
 2.get redirected
 3.try the same for an url like`mapillary.com/map/im/<photo_hash>/map`

### Expected behavior
I expect to get redirected to the photo or map view depending on the last word in the url

### Actual behavior

In both situations I get redirected to the same url that doesn't have the `focus` parameter, so I get defaulted to the map view

**Comment by gyllen** [comment]
Thanks for reporting. Fixed, I also made the default focus on the photo which I think make sense.
