### ISSUE TITLE
Edit is slow

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2057]
Editing sequences is really slow. If editing while zoomed it is extremly slow, and often it grinds to a total freeze.

**Comment by de-vries** [comment]
I've experienced this too in FF and chromium on ubuntu16.04

**Comment by gyllen** [comment]
Hey @de-vries and @Andblue trying to figure this one out. If you guys have some specific sequences that would help us out a lot.

**Comment by de-vries** [comment]
it's just any sequence I tried. 
When I only use the normalize function it works fine, but as soon as I move some photos the page becomes unresponsive and there is a lot of cpu usage. refreshing the page is the only way out of this.

**Comment by Andblue** [comment]
Its not any specific sequence. Several that I have tried are not crowded parts of the map.

Using Google Chrome on Windows, with a good connection and a computer that doesn't get slow while doing other things.

**Comment by Andblue** [comment]
Looks like its part my fault. Previous it was Click and hold-Drag-Release. Not it is Click and hold-Wait-Drag-Release.

There is a new half a second wait thing after clicking.

**Comment by retro** [comment]
@Andblue We've added a hold wait because we have to differentiate between clicks (which selects the bead) and drags, so it's a bit tricky to get it right. We might try with a shorter delay.

**Comment by Andblue** [comment]
When the new Mapillary web site launched the WebGL on my browser (Chrome on Windows) started to crash, not only when visiting the Mapillary site. That no longer happens. But today I got a flashback after editing (and the edititing coming to a halt) and visiting another site, the web browser window went black, before getting normal again. But no message about WebGL.

Not sure if it is related.

**Comment by gyllen** [comment]
@Andblue we made some majot updates to the editor today, can you see if you can repeat?

**Comment by Andblue** [comment]
@gyllen Tried the updated version to edit one sequence so far. It is off to a good start, at least 10 times snappier and none of that grinding to a halt stuff. Will try some more in the coming days.

**Comment by gyllen** [comment]
@Andblue AWESOME! Closing this issues then. Please open new if you have more feedback.
