### ISSUE TITLE
Zooming in photo spheres is terribly slow

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2059]
Zooming in photo spheres is terribly slow. It takes about 100 rotations of my scroll wheel to zoom in completely in.  

FF, Ubuntu

**Comment by gyllen** [comment]
@oscarlorentzon This could be a specific FF bug. Works well for me in chrome.

**Comment by de-vries** [comment]
in chromium it's the same for me

**Comment by oscarlorentzon** [comment]
Related to operating system. Works fine in Safari, Chrome, Opera and Firefox on OSX.

**Comment by oscarlorentzon** [comment]
@de-vries Does the scrolling work in the same (slow) way when using the mouse scroll wheel as when using the track pad scroll gesture?

**Comment by de-vries** [comment]
yes it does.

**Comment by oscarlorentzon** [comment]
Tracked here: mapillary/mapillary-js#175

**Comment by oscarlorentzon** [comment]
@de-vries This should be fixed in the `1.6.0` release of `MapillaryJS`. 

Can you confirm that this works for you in FF and Chromium now?

**Comment by de-vries** [comment]
Yes it works in both browsers, thank you!

**Comment by oscarlorentzon** [comment]
Perfect, thanks!
