### ISSUE TITLE
Inconsistent speed in photo transitions

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2060]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome 52`

### Steps to reproduce behavior

 1. Find two images which have a nice transition animation between them.
 2. Browse from the first image to the next, and watch the transformation.

### Expected behavior

The animation should be smooth with the same speed overall.

### Actual behavior

For the first half of the animation, the speed (frame rate) is much slower than for the second half. This behavior continues also when re-running the animation by stepping back and forth.

### Additional information

It looks to me like the animation of the map marker is causing this slowdown. As soon as the map marker has reached it's new destination (which it does before the photo transformation is finished), then the photo transition speed is much faster.

**Comment by gyllen** [comment]
@pbb72 Thank for this observation. We added these fancy animations as a last fancy feature. I removed them now and this makes for a much more pleasant experience.

I would also like to thank you for taking your time and reporting bugs like this. Now when we have a bigger team and a better plattform, we will be able to actually fix them much faster.

**Comment by pbb72** [comment]
Thanks, animations look great again now! And thanks for doing a great job! :+1:
