### ISSUE TITLE
ios app - opening settings is very slow

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2062]
opening the settings is very slow - for quite some the "loading" spinner is shown. and the settings are very limited, there are just a handful of sliders.

**Comment by millenbop** [comment]
It calculates how much space the generated data takes. I'll fix this by doing it in the background and update the table when it is done, so UI won't be locked.

**Comment by millenbop** [comment]
This is fixed now, available in the latest App Store version (4.4.7).

**Comment by richlv** [comment]
yay, thank you :)
