### ISSUE TITLE
ios app allowing screen lock during upload

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2063]
lately quite often the ios app allows the phone to lock the screen even when the app is active and a download is in progress. it seems to be connected to switching to other apps, but so far i have been unable to find the exact steps to make it fail.

**Comment by millenbop** [comment]
Thanks for reporting! When upload starts, we disable screen dimming. Perhaps it needs to be re-disabled if you switch apps. I'll look into it.

**Comment by millenbop** [comment]
I have tried lots of things and I cannot replicate this no matter what. The only use case I can think of is if the app gets killed by the system, but then also the upload gets killed.

I'll leave this open for a while. Let me know if you see this happening again.

**Comment by richlv** [comment]
seen this happen a few days ago again. got any ides to test it ?
once it gets in that state, just unlocking does not help - the screen is locked again later. closing/reopening & restarting the upload solves it.

**Comment by richlv** [comment]
ok, this took a few attempts to verify, but i think i got it now...
* start upload
* switch to the photo mode
* close photo mode
* let it sit & see how it gets locked
apparently i manage to enter the photo mode accidentally often enough to see that behaviour ;)

**Comment by millenbop** [comment]
Ah good find, I tried switching apps etc :)

We disable screen lock when upload starts and when camera is opened, and enables screen lock when uploads stops/finishes and when camera is exited. So need to add a check when the camera exits if there is an upload in progress.

Thanks!

**Comment by millenbop** [comment]
Fixed now, available in 4.4.9

**Comment by millenbop** [comment]
Update is out, closing.
