### ISSUE TITLE
Webupload Progressbar broken

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2064]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 10 + lastest Firefox'

### Information

When uploading >100 pictures, the Webuploadpage got struggle.
First in review, it showing all pictures with correct location, but then it zoom out and showing only the current upload.. and this upload is not showing the correct upload at all

![unbenannt](https://cloud.githubusercontent.com/assets/10342344/17075953/79d1507c-50a5-11e6-9aaf-98157a3b482e.JPG)

**Comment by pbb72** [comment]
I've also seen this behaviour (in Chrome), but for me this only happens on subsequent uploads. That is, it doesn't happen on the first upload after opening the web uploader, but if I do another upload after that, this is what happens.

It seems to me there are a few variables that are not properly reset after the initial upload.

**Comment by retro** [comment]
This was fixed in one of the recent releases. Please reopen this issue if you encounter this bug again.
