### ISSUE TITLE
Increase distance for direction arrows

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2065]
### Basic information
- Platform: `Web`
- System/Browser: `Chrome 52, Firefox 47`
### Steps to reproduce behavior
1. Open http://mapillary.com/map/im/F-HOh2sM8W31mxy5yrubhA
2. Note that only a backward direction arrow is offered.
3. Click the next-in-sequence arrow to see that the next photo is at a close distance, with little change in perspective.
### Expected behavior

A forward direction arrow is expected.
### Actual behavior

Only a backward direction arrow is offered.
### Additional information

It seems direction arrows are only shows if surrounding images are really nearby, less than 3 meters? This problem was not so visible on the old website, since the forward direction arrow was just replaced with the next image arrow, which looked almost identical. But since the previous/next arrows are now placed elsewhere (which is good!) many sequences are not "walkable" anymore since the distance between the photos is too big.

**Comment by pbb72** [comment]
@oscarlorentzon, should this issue be transferred to mapillary-js?

**Comment by oscarlorentzon** [comment]
Direction arrows are calculated within a circle with a radius of 20 meters so the distance threshold is not the problem. There are other criteria that needs to be satisfied for forward arrow to be shown like having approximately the same rotation. 

Tracked in mapillary/mapillary-js#178

**Comment by ybkuang** [comment]
Closing this in favor of maillary-js.
