### ISSUE TITLE
Online uploader does not show photo direction

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2067]
### Basic information
- Platform: `Web`
- System/Browser: `Chrome, Firefox`
### Steps to reproduce behavior
1. Add direction information to some photos using the Mapillary Python tools.
2. Drag them onto the online uploader.
3. Dots appear for every photo on the map.
### Expected behavior

I would expect arrows or something to indicate the direction information for each photo. This was available in the old online uploader, even before uploading.
### Actual behavior

Each photo is just represented by a single dot, no information about the photo direction.
### Additional information

Since I am using various tools to properly geotag my photos (GeoSetter and the Python tools), I sometimes forget a step. Seeing the direction in the uploader before doing the upload, helped me to verify that everything was correct.

**Comment by gyllen** [comment]
@angelday Feedback for uploader

**Comment by talllguy** [comment]
@angelday you can probably close this one per #2129. I love the way the uploader shows direction now.

**Comment by nickplesha** [comment]
Implented a while ago, closing.
