### ISSUE TITLE
Should have a feature for user to download their own data

### ISSUE THREAD

**Issue by hoangvietanh** [mapillary/mapillary_issues#2068]
While I'm happy to contribute new data to Mapillary and hence the OSM at large, there should be an option to download my data.

Without this there is no way user have and feel their ownership of the data they have contributed.

**Comment by jesolem** [comment]
Users can download the original file contributed since September. Closing.  

(also GPS traces of their sequences, and everything from the API)

**Comment by hoangvietanh** [comment]
Great. Thanks
