### ISSUE TITLE
map zooms annoyingly when deleting a photo from the upload editor

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2069]
### Steps to reproduce behavior

 1.put a (long) sequence in the web uploader
 2.zoom in on a detail
 3.delete one photo

### Expected behavior

I expect the map to stay in the same position, so I can continue working on that detail
### Actual behavior

the map zooms out so show the whole length of the sequence

**Comment by pbb72** [comment]
Somewhat related to #2079 ?

**Comment by retro** [comment]
This was fixed in one of the recent releases. Please reopen this issue if you encounter this bug again.
