### ISSUE TITLE
no warning is given when exiting the uploader

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2070]
### Steps to reproduce behavior
1. put photos in uploader
2. ...
3. exit uploader
### Expected behavior

"Are you sure you want to leave the uploader and discard all photos and changes"
### Actual behavior

the uploader closes whitout warning and all photo's and changes made to them are lost

**Comment by angelday** [comment]
@de-vries do you mean that your edits, eg. moves, deletions are not getting saved?

**Comment by de-vries** [comment]
It's expected that nothing is saved or uploaded when closing the uploader, But when you're preparing a upload and spend some time correcting the locations of photos, it's not nice when you loose it all with one accidental click and no warning.
My proposal is that when you click exit uploader or close the tab, you get a warning that "By closing the uploader all changes will be lost and no photos get uploaded".

**Comment by angelday** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
