### ISSUE TITLE
APK direct download link not available anymore ?

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2071]
Hello,
The direct download link to get the mapillary APK for Android doesn't seems to be present on the new website (or it is well hidden in some sub-page). Can you bring it back or make it more visible ?
Thanks in advance.

**Comment by de-vries** [comment]
I can't find it either, but here is the link if you need it now: http://android-releases.mapillary.io/index.html

**Comment by knikel** [comment]
Links added, visible after next deploy. Thanks guys!
