### ISSUE TITLE
Usability: Link to edit mode shows edit mode but not login status

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2073]
### Basic information
- Platform:  `Web`
### Steps to reproduce behavior
1. Send someone a link to pic or map in edit mode
2. Open link without being logged into mapillary
### Expected behavior

The website should not show the edit mode when not logged in.
### Actual behavior

There is no visual difference to a logged in user. The GUI suggests that edits are possible while they aren't.

**Comment by nickplesha** [comment]
Thanks for reporting, this should be fixed now.
