### ISSUE TITLE
The blur algo is no good

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2074]
Mapillarys blur algo needs to be improved. A one hour drive taking pictures produces many hundred, and  most likely thousands, of incorrect blurs. I don't think the way forward is counting on the community to unblur.

I am sure Mapillary has this on the todo list, so just go ahead and close this issue :-)

**Comment by ybkuang** [comment]
Thanks for reporting this @Andblue. And yes, it is on our todo list. Keeping this open until we are all happy with the blurs.

**Comment by Caboosey** [comment]
I am constantly having to unblur street signs and highway exit/guide signs in the United States photos.

**Comment by ybkuang** [comment]
@Caboosey yes. It's a known issue with the false positives on highway signs. We will be able to reduce this kind of errors with a better semantic understanding of the photos. We are working on that.

**Comment by ybkuang** [comment]
This has been resolved by the new [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
