### ISSUE TITLE
Rotation request for single images

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2076]
### Basic information
- Platform: `Web`
  Please bring back the possibility to request rotation of single images

**Comment by rausk** [comment]
Since there are a lot of image sequences being completely inverted, it would be nice to have the ability of rotating the whole sequence with one click.

**Comment by gyllen** [comment]
@ybkuang You has some thought on doing this automagically?

**Comment by angelday** [comment]
@rausk 

> it would be nice to have the ability of rotating the whole sequence with one click

Do you mean the compass angle (where photos are looking at) or the image data (what is displayed on the photo)? You can do the former in the sequence editor.

**Comment by rausk** [comment]
See also issue #1892 
As you perhaps know, a lot of sequences are shown completely upside down. My request was, that a user may flip not only single photos  but the whole sequence with one click because normally ALL pictures in a sequence are wrong.
It were even better, if Mapillary could fix this bug.

**Comment by voschix** [comment]
Can I remind you of my original request, i.e. rotation request (or control) for single pictures.

**Comment by ybkuang** [comment]
@voschix @rausk Hi, sorry for the delay. I would like to give you some updates on this. 

Internally, we have experimented with
- an automatic detector for proposing sequences with wrong rotations
- implemented the rotation editor

We need a bit more time to properly design the UI and prepare the database for a release. We will keep you updated on the development here.

**Comment by voschix** [comment]
Could I remind you of the single image rotation feature.
It is much less work to rotate them on the fly when you check the image pixellation then to work off a list.

I keep a list of image to be rotated. At present it contains more than 100 photos. 98% require 180° rotation. 2% require 90# or 270° rotation.

**Comment by ybkuang** [comment]
@gyllen things to thinking about on the rotation UI. cc @voschix

**Comment by ybkuang** [comment]
Related to https://github.com/mapillary/mapillary_issues/issues/531 on better UI/proposals for rotation detection. 

mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
