### ISSUE TITLE
Legacy map search URL with bbox doesn't redirect to new URL

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2077]
Map search URLs from the old website which contain bbox coordinates, such as https://www.mapillary.com/map/search/-5.013975021/1.665833354/-92.011558533/-75.188793945 (mentioned in #1818), don't work anymore in the new website, and don't redirect to the new URL.

(related: #2025 where the `map/search/<lat>/<lon>/<zoom>` redirect was added)

**Comment by knikel** [comment]
Unfortunately we don't have support for bboxes in the new application. It was a huge painpoint in maintaining map changes in the previous web app, and the bounds were never correct after initializing the viewer (they were always meant to be contained in whatever size the map had). I've added a redirect for `search/minlat/minlon/maxlat/maxlon` to `/app/?lat=:lat&lng=:lon&z=10` where `lat` and `lon` are center of the bounds. Hope that's an OK solution? Visible in the next deploy.

**Comment by nicolas17** [comment]
Redirecting to the bbox center is perfect. Heck, redirecting to an arbitrary place on the map would still be better than a 404 :)
