### ISSUE TITLE
Enforce HTTPS for forum.mapillary.com

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2078]
### Basic information
- Platform: `Web`
- System/Browser: `Windows 7 Pro SP1 64-bit/Google Chrome 52.0.2743.82`
### Steps to reproduce behavior
1. Go to https://www.mapillary.com/ or https://www.mapillary.com/community
2. Click on `Forum` at bottom of all pages or click on `Join Discussions` on community page.
### Expected behavior

Always to see in browser's URL as: https://forum.mapillary.com
### Actual behavior

Webserver fails to redirect http://forum.mapillary.io and http://forum.mapillary.com to https://forum.mapillary.com
### Additional information

All pages on https://www.mapillary.com/ has HTML code at footer for `Forum` to go to http://forum.mapillary.io instead of https://forum.mapillary.com

https://www.mapillary.com/community has HTML code for `Join Discussions` that points to http://forum.mapillary.com

Mixed Content: The page at 'https://forum.mapillary.com/' was loaded over HTTPS, but requested an insecure image 'http://d3rqg5ndc8pbid.cloudfront.net/original/1X/77b14c662df42f71f8a7f0775d1873f686a58788.png'. This content should also be served over HTTPS.

Github bug issue filed (at different project) to add/modify ruleset for EFF's HTTPS Everywhere plugin to include forum.mapillary.com: https://github.com/EFForg/https-everywhere/issues/5780
## Todos
- [x] Fix links
- [x] Fix redirect:  `http://forum.mapillary.com` to `https://forum.mapillary.com`

**Comment by knikel** [comment]
Thanks @Caboosey, I've fixed the links. Thanks a lot for tracking these!

Assigning @gyllen to fix forum redirects.

**Comment by floscher** [comment]
Another HTTPS issue is, that https://mapillary.com refuses connection (`ERR_CONNECTION_REFUSED` in Chromium), but http://mapillary.com redirects to https://www.mapillary.com instead. Maybe this can be also redirected to https://www.mapillary.com .

**Comment by Caboosey** [comment]
@knikel The link for `Forum` in the footer area for all pages has the wrong URL.

I noticed it got changed to https://forum.mapillary.io instead of https://forum.mapillary.com

https://forum.mapillary.io will result in a HTTPS Certificate error since the certificate can only do *.mapillary.com

**Comment by gyllen** [comment]
@jesolem Can you help with HTTPS redirect for the two above (we should be able todo this on DNS level)

**Comment by gyllen** [comment]
@floscher Would you mind open a new issue for https://mapillary.com issue? Its a bit trickier since https does not allow for redirects so the `naked domain` needs to handled differently somehow

**Comment by floscher** [comment]
Sure, no problem.

**Comment by Caboosey** [comment]
@gyllen Sounds like you need a really good .htaccess rule like this?

```
RewriteCond %{HTTPS} off
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule .* https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

```

**Comment by Caboosey** [comment]
Note: A pull request (https://github.com/EFForg/https-everywhere/pull/5817) has been submitted to add forum.mapillary.com for the HTTPS Everywhere plugin.

**Comment by J0WI** [comment]
In https://github.com/EFForg/https-everywhere/pull/5817 we also documented some other issues with HTTPS on mapillary.com.
The best would be to implement [preloaded HSTS](https://hstspreload.appspot.com/) (requires full HTTPS support) on your site. That would also make the rue in HTTPS Everywhere obsolete.

**Comment by Caboosey** [comment]
@J0WI HSTS is only good if the browser supports pre-loaded HSTS or the browser has previously visited the website that has HSTS.

If the browser never visited the website and doesn't do preloaded-HSTS, it doesn't know about the website's HSTS until it's first visit.

HTTPS Everywhere plugin helps us or others (lazy) users who just type www.mapillary.com and ensures the browsers does https://www.mapillary.com as the initial request instead of http://www.mapillary.com using without the plugin.

The initial request from the client doing HTTP prior to any redirects from webserver could be attacked by man in the middle and the attacker could redirect them to any website they want and not the real website's redirect.

**Comment by gyllen** [comment]
@Caboosey AIts a little more complicated than the .htaccess file, call finds its way through several loadbalancers and an internal DNS before it hits the server. Want to catch this earlier.

**Comment by jesolem** [comment]
OK so https://forum.mapillary.com/ works fine. The problem is https://forum.mapillary.io right?

If so, why not make the links to the forum go to https://forum.mapillary.com/ directly instead? Then this should be solved, or am I missing something?

**Comment by Caboosey** [comment]
@jesolem Yes, https://forum.mapillary.com works fine. The Mapillary wildcard SSL certificate only does mapillary.com and *.mapillary.com

**Comment by J0WI** [comment]
@jesolem please be aware of the mixed passive content on the forum. You should fix it and you can also use CSP upgrade-insecure-requests as a quick workaround.

@Caboosey ot: HTTPS Everywhere is only available for browsers that do also support preloaded HSTS ;)

**Comment by ArtificialTruth** [comment]
Especially urgent redirect needed; When requesting a password reset on https://forum.mapillary.com/users/mappingproc/preferences you'll get a mail with a link to reset it on http://forum.mapillary.io/users/password-reset/
Then you're entering your new password on a unsecure connection. 
PS. https://forum.mapillary.com/users/password-reset/ works, so absolutely no reason to confuse the end user with other insecure domains, when there's a secure one.
