### ISSUE TITLE
Don't change zoom (and maybe not even pan) when clicking on a photo on the map

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2079]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Open the map view.
2. Zoom in enough to see dots for individual photos.
3. Click on one of the dots. (The problem is most visible if this dot is not in the central area of the map.)
### Expected behavior

The new photo opens in a map view that I can recognize.
### Actual behavior

The map zooms in so far that I am unable to recognize the map. Also, this doesn't happen immediately, it happens after a second, making it possible for me to click another location in the mean time.
### Additional information

In any interface, when there's a delay between a click and a screen update, it becomes possible to click somewhere else while the first click is still being processed. When this is combined with a structural change of the interface (the map, in this situation) then it is no longer predictable what the result will be. Will the second click be in regard to the initial screen layout, or will it be in regard to the updated screen after the first click has been processed?

If it is not possible to make a smooth transition that happens immediately after the mouse click, then it is better to not transition at all, and leave all panning and zooming up to the user. You could add a "zoom in to location" button somewhere though.

**Comment by de-vries** [comment]
Me too was annoyed by this behavior. I didn't experience the delay thing though.

My suggestion would be to never zoom and only pan if the new photo is close to the edge of the map.

**Comment by pbb72** [comment]
I always stress my browsers to the max (90% CPU load is common), so any delays become obvious on my system ;-)

I can agree with panning at the edge of the map.

**Comment by pbb72** [comment]
Note: I see that zooming and panning also happens when clicking the arrows to go from one photo to another. Here zooming is even more of a distraction.

**Comment by gyllen** [comment]
@angelday We need to think a litte about when to zoom and pan.

@pbb72 @de-vries What about just zooming on first click of a photo. But as soon as a photo is shown we do not touch zoom. Pan I think we should do though.

**Comment by pbb72** [comment]
I see now that the zoom is not performed until after the image is fully loaded (even in map view). In worst case, I've seen this take more than 10 seconds. After more than a second or two, the mental connection between the user's click on a new image and the change of the map view is lost, and the user is left guessing why the map suddenly changed.

In it's current technical state, I think I am only happy with zoom changes in the mini-map (in photo view). In the map-view, the implementation is simply too problematic.

**Comment by pbb72** [comment]
When I open a map view, I often pan and zoom it to give me the best overview. (Which is different for different purposes. Sometimes I want to keep an eye on a whole sequence, other times I want to see a whole traffic intersection, etc.)

It's not nice if the map application then decides it know better than me and sets it's own preferred zoom.

For the same reason, I would also prefer to keep panning to a minimum, only pan the map if the newly focused image falls outside the current map view.

**Comment by gyllen** [comment]
@pbb72 Thanks for the feedback. Before releasing site we had a lot of discussion on when to pan and when to not pan. After seeing some comments (like this one) I think we need to tune it a little. My suggestion are.

1. I no image is selected and you select one, pan and zoom so that one is in the middle
2. Pan (not zoom) when you move between images
3. Add an option that will disable pan for you if you don't like it in 2

**Comment by pbb72** [comment]
I think fixed zoom when going from photo to photo solves 90% of my trouble. As far as I am concerned that is enough initially.

**Comment by pbb72** [comment]
Ah, but now I ran into the problem with panning again. The pan is not immediate, so it allows me to click again before the pan is performed. This causes unexpected behaviour.

**Comment by de-vries** [comment]
The problem I have with panning is that when I try track the changes on the map it would be easier and much more unintuitive to follow a moving yellow marker than tracking how the background moves behind the yellow marker.
But this might be just my personal preference, so given point 3, I would be satisfied with your solution.

**Comment by gyllen** [comment]
Im leaning towards adding some `advanced` settings here that lets you disable all panning and zooming from our side.

We always have to consider two types of users.
1. The ones that just browse around and press the playbutton
2. And users like you guys who use it for real stuff. In your case you will know where to find these settings.

**Comment by de-vries** [comment]
I'd really like to have some advanced settings. Other tings that should be in there:
- Disable transitions between photos
- Lock to sequence
- Activate point cloud

I also agree that default settings should be toward new users and visitors and not toward power users.

**Comment by de-vries** [comment]
I found something that makes this extra annoying; the panning and zooming happens twice, once when a new photo is selected and then again when that photo is loaded. 
Whatever you do with the rest of this issue, that second panning and zooming has to go. Like @pbb72 said, any panning and zooming that you deem necessary as fast as possible after selecting a new photo.

**Comment by rsahlin** [comment]
Hi

I was reviewing a sequence where I needed to increase zoom in order to see the location with higher precision.
As I navigate forward or back in this sequence the zoom resets, I would prefer if the zoom level stays between pictures.
To me this would be the expected default behavior.

Best regards
/Richard

**Comment by GITNE** [comment]
> Im leaning towards adding some ```advanced``` settings here that lets you disable all panning and zooming from our side.

@gyllen Sounds like a nice feature for advanced users but the expected default behavior should get fixed first.

**Comment by angelday** [comment]
Short answer: it helps with orientation in the viewer.

Long answer:

I think anyone who is opening up Mapillary more than once a week might end up finding this annoying. This functionality caters for the average user who just sees Mapillary for the first time or to a very casual user.

The zoom is set to a level where it makes sense to display traversing with our typical sampling intervals. No matter where you are, if you click any of the stepping controls, you immediately see the context in the map. The map essentially is your radar for navigation.

If you make the zoom level too high (meaning you're closer to the ground), the navigation context will be lost. If you make the zoom level to low, it doesn't show anything meaningful.

Think about it this way: what should happen when you're on the world map and click on a green area? Should we just display an orange marker there? What if you step in one direction, what should happen then? See the world map with a fraction of a pixel in travelled distance? Or should we zoom in just with the first click? But then again if you zoom out to see the world map and you select a different photo? Our solution was to always snap back to zoom level 17.

I agree that there are cases when you want to turn it off, or even set it the other way around by default, but I don't agree that it should be removed.

**Comment by GITNE** [comment]
@angelday Zooming in to a reasonable level on the first click is indeed the expected behavior. However, once you have adjusted the zoom level manually and start traversing the sequence or navigating, the expected behavior is to not change the zoom level automatically.

**Comment by pbb72** [comment]
I agree that we need to zoom in when the user is in low zoom levels, but being able to see the navigational context is very much dependent on the situation. In some places level 14 gives the best context, in others you need level 20.

Maybe we can connect this to the display of individual photo dots? This means, on zooms below 14, then you're automatically taken to zoom 17 when clicking, on higher zooms the zoom factor will not be unchanged when going from photo to photo.

This happens to coincide with changes in the behavior of clicking on the map. Below level 14, clicking on the map takes you to the first image in the clicked sequence, while beyond level 14 you are taken to the individual photo you clicked on.

**Comment by gyllen** [comment]
@pbb72 The behavior on the website has by now changed to something that is much closer to what you suggested.
