### ISSUE TITLE
Map zooms to first image in sequence, not to clicked location

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2080]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Find a long sequence on the map.
2. Zoom out far enough that dots for individual photos are no longer displayed.
3. Click somewhere halfway (or towards the end) on the sequence.
### Expected behavior

A photo near to the clicked location is opened. Also preferrably, no change in zoom happens.
### Actual behavior

The map zooms far into an unexpected location, and the first photo in the sequence is opened. Since all context is lots because of the zooming, it's initially not obvious what has happened.
### Additional information

See also #2079

**Comment by Andblue** [comment]
I was just going to report the same thing. Additional input:

A quick test and it looks like the jump to the first photo of a sequence thing only happens with new sequences. Old sequences open the clicked photo.

**Comment by pbb72** [comment]
This happens for me on both old and new sequences. But you do have to zoom out enough so that no photo dots are visible, only sequence lines.

**Comment by gyllen** [comment]
We are trying to reduce the tile size of data to download. So tiles on that level will only have first key in sequence. We could make an extra API call but then click will be slower. Tricky how to solve this and keep performance.... gonna need some deep thinking

**Comment by pbb72** [comment]
For me it would be totally acceptable to open the first image in the sequence, if it wouldn't zoom at the same time. The zooming is what makes it all so difficult to understand.

**Comment by knikel** [comment]
Ping @angelday: Thoughts on removing the zoom on click?

**Comment by angelday** [comment]
Referencing: https://github.com/mapillary/mapillary_elva/issues/244

The on-click zoom to location 17 is a concept of the design, because we use our map to show the context for navigation. If we resolved the original issue in the first place (244) the disorienting effect will diminish.

Another option would be to include an option to disable zoom to click in the settings.

**Comment by gyllen** [comment]
Closing this, since no great solution at hand. Zooming in helps though, it will give you the accurate image.

**Comment by pbb72** [comment]
@gyllen No probs, this issue was really with the old interface. Should have been closed when the new interface launched :-)
