### ISSUE TITLE
incomplete uploads

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#2081]
New web site does not give list of incomplete uploads (uploads not pushed). That mean it becomes increasingly complicated with interrupted uploads from scripts. Either resolve mapillary/mapillary_tools#98 or return the "Publish" function to the web front-end (or both)

**Comment by Skippern** [comment]
I know I still can reach the old site at http://legacy.mapillary.com but guess that the legacy site will be taken down after some time.

**Comment by gyllen** [comment]
@Skippern We will add this and better feed. Thanks for reporting this.

**Comment by gyllen** [comment]
@Skippern New mapillary_tools should be much better at handling this.
