### ISSUE TITLE
Web Uploader would not accept images, hangs on image 1

### ISSUE THREAD

**Issue by JulieMay** [mapillary/mapillary_issues#2082]
The new interface looks great. Unfortunately, the new uploader would not upload any images. It said uploading 1 of 14 (so I got to see the cool new dots). However, it would not actually send the images. I tried bailing out and coming back again to no avail. Using Windows 7 Home Premium, Chrome.
### Basic information
- Platform: `Web`
- System: `Windows 7 home`
- Browser: Chrome 51.0.2704.103 m
- Link: https://www.mapillary.com/app/uploader
### Steps to reproduce behaviour
1. Log into account
2. Go under account name
3. Go to uploader
4. Select files from hard drive
5. click the button and wait. Stays stuck on image 1.
### Expected behaviour

Uploads all of the images then processes them.
### Actual behaviour

Hang on first image even when browser closed and relaunched, system rebooted, cache cleared.
### Additional information

Used the command line uploader instead and the same images uploaded smoothly and created a tour. The tours created were on 7/21/2016.

Didn't see any reason for logs.

**Comment by nickplesha** [comment]
The uploader should be able to handle any images with valid exif data, if you encounter problems uploading in the future, contact us at support@mapillary.com
