### ISSUE TITLE
Compatibility for Motorola G4

### ISSUE THREAD

**Issue by travel193** [mapillary/mapillary_issues#2083]
@moenk is unable to install the Mapillary app onto a Motorola G4 via Google Play and his required to sideload.

**Comment by peterneubauer** [comment]
It might be that the Moto4 has no suitable direction sensor. we are working on removing that requirment.

**Comment by travel193** [comment]
It seems you're right @peterneubauer : [http://forum.xda-developers.com/moto-g4-plus/help/compass-g4-plus-t3381905](http://forum.xda-developers.com/moto-g4-plus/help/compass-g4-plus-t3381905)
