### ISSUE TITLE
Loading indicator is not obvious enough

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2084]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Browse around a bit using the photo view, hopping around between photos from various sequences.
2. At some point, either the navigation arrows and the sequence arrows (the previous/play/next buttons on top) will not be shown.
### Expected behavior

A clear visual indication about why the arrows are not available.
### Actual behavior

There is a tiny, hardly visible loading indicator in the middle of the photo. In many situations, this indicator is completely obscured by details in the photo.
### Additional information

Who can spot the loading indicator?
![clipboard image 20](https://cloud.githubusercontent.com/assets/1436366/17094994/b5a8a2cc-5252-11e6-9d1d-c75a57d4ef58.jpg)

**Comment by nickplesha** [comment]
The new loading indicator has been made more visible to stand out against any background color, hope it solves this issue.
