### ISSUE TITLE
Web uploader merges different consecutive sequences

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2085]
### Basic information
* Platform: `Web`

* System/Browser: Windows7/Firefox 47
### Steps to reproduce behavior

 1. Load some files and press the button to publish
 2. Don't exit web uploader
 3. Load some more files and press the button to publish
4. [Eventually, repeat steps 2. and 3.]

### Expected behavior
Two  (or more) different sequences are created

### Actual behavior
All files are published in a single sequence

### Additional information
Examples of such created sequences:
0vyElSPbrP_lRp8azM55XQ
pVEYT9DTmPTAUDVFwZ5lcg

**Comment by pbb72** [comment]
I can confirm this, and my guess it's the same reason that causes #2064

**Comment by retro** [comment]
This was fixed in one of the recent releases. Please reopen this issue if you encounter this bug again.
