### ISSUE TITLE
Text navigation in comments wrong

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2086]
### Basic information
* Platform:  `Web`

### Steps to reproduce behavior

 1. Comment
 2. Try to navigate with the arrow buttons up/down

### Expected behavior

The cursor should scroll one line up/down in the text

### Actual behavior

MapillaryJS is capturing the key events

### Additional information

...

**Comment by gyllen** [comment]
@peterneubauer Just add this to elva repository next time (unless you are tracking this for somebody external)

**Comment by peterneubauer** [comment]
It's for external tracking.

On Wed, Jul 27, 2016 at 1:49 AM, Johan Gyllenspetz <notifications@github.com

**Comment by knikel** [comment]
This will be fixed in the next deploy. `Escape` key also closes all active drop-ups.
