### ISSUE TITLE
Repeated crashes in iOS

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#2087]
### Basic information
* Platform: iOS 9.3.3 , iPhone 5, gopro hero session 4
* Version: 4.4.3

### Steps to reproduce behavior

 1. Connect wifi to gopro
 2. Open gopro app, see that connection works
 3. Open mapillary app
 4. push on the camera icon
 5. push on the wifi icon to connect mapillary app to gopro
 6. push start
 7. start walking around and wait for the app to crash

### Expected behavior

Not crashing 

### Actual behavior

Crashing, periodically, every 5 minutes or so

### Additional information

I've turned on the automated reporting, logs should be heading your way, if not already there. I witnessed multiple crashes on saturday and one today.

I am not sure if this is a duplicate of issue 1677

**Comment by millenbop** [comment]
We have received lots of crash reports related to Mapbox, so I've downgraded the library to the version we used before. It's been submitted to Apple so I hope it will be out very soon.

**Comment by millenbop** [comment]
Don't think it's related, but the GoPro Session is not officially supported by their SDK.

**Comment by Virtakuono** [comment]
I actually just upgraded the app, which I presume, downgrades the mapbox library. I'll see if it crashes again. Too bad I don't have an officially supported gopro, I'm happy to try out some fancy gopro model too, if someone can ship me one for a few weeks.

**Comment by millenbop** [comment]
The recent app version (4.4.5) upgrades the Mapbox library to a newer version, but it hasn't solved the stability problems so version 4.4.6 goes back to an earlier version of Mapbox. It will be out in a few days, Apple seems pretty fast nowadays.

Yeah I don't know why their SDK explicitly only support Silver and Black, because it seems to work more or less anyway with the Session. I haven't tried the Session myself though.

**Comment by millenbop** [comment]
4.4.6 is out now with an older version of Mapbox -- please give that one a try when you have the time.

**Comment by millenbop** [comment]
Closing. Will reopen if problem persists.
