### ISSUE TITLE
Annoying behaviour while uploading from GoPro

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#2089]
### Disclaimer
This is an issue, not really a bug per se.

I don't know if this lands in the right forum, if not feel free to erase or to copy somewhere else. I don't know if I should complain to GoPro company instead.

I am following the instructions on
http://blog.mapillary.com/update/2015/12/18/gopro.html

### Basic information
* Platform: iOS 9.3.3
* Version: 4.4.3
* GoPro Hero 4 Session

### Steps to reproduce behavior

1. Take many (around 10k) photos using mapillary app and gopro.
2. Follow the instructions in the url above, start transferring photos. After around 1500 photos, gopro runs out of battery.
3. Plug in gopro for charging, lose the wifi connection as a by-product
4. Start again, transfer the next ~1500 photos, rinse and repeat, ad nauseatum.

### Expected behavior

I'd hope there was (if there is, I'm happy to see an url to a howto or something) a feature to avoid this really annoying procedure of using wifi, recharging, using wifi, recharging. I know that it's perhaps a bit unfair to put this on you, when it was gopro that designed a camera that can only use wifi while not being plugged in, but this really makes uploading photos a real pain.
Roughly speaking, it took me 3 hours of charging and 3 hours of transferring the ~7k photos.

If there was a way of leaving the process running for 6 hours overnight without having to come back every now and then, I would very much appreciate it.

**Comment by thoschu96** [comment]
Hey Virtakuono.. you should write down, which kind of GoPro u are using.
I did the same with a GoPro Hero 4 Session, and with that GoPro i can charge and operate with the GoPro at the same time .. maybe you can try to connect it direct to a powerplug and not to a PC/MAC for Recharging.. maybe it's helping.

**Comment by Virtakuono** [comment]
Ooops, sorry, I updated the original issue now, and will give the power plug thing a try next time I can. THX @thoschu96

**Comment by millenbop** [comment]
Yup, plugging it to a charger works; I do that all the time. As soon as you connect it to a computer it enters "USB mode" and shuts off WiFi.

But in the future, for long captures with lots of photos, we will add support for action cams to the web/desktop uploader. Transferring photos via cable to computer is 10-100 times faster than WiFi and then you can upload using your computer and free up your phone.

**Comment by thoschu96** [comment]
so the IOS App upload only the GPS values and the GoPro provides the Pictures over the Webupload ?

**Comment by Virtakuono** [comment]
Ok, thanks guys. This was one of the fastest resolved issues I have ever reported anywhere. I'll stay tuned for the desktop uploader!

**Comment by millenbop** [comment]
@thoschu96: we haven't really designed it yet. but it will work something like this: 
1) you capture as normal 
2) app uploads meta data to cloud 
3) you transfer images to the computer from your action camera 
4) the uploader figures out which meta data to use and downloads from cloud and add it to the images 
5) you can now review/edit/upload

In the meantime we will have a script that does the meta data adding, script master @ybkuang is on it. It will require you to copy the meta data files manually using iTunes though.

**Comment by millenbop** [comment]
Not much we can do about this one I'm afraid, so closing.
