### ISSUE TITLE
No thumbnails for incomplete PhotoSpheres and they are not draggable

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#2090]
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 51.0`

### Steps to reproduce behavior

 1. Open the map on https://mapillary.com (using a mapillary account without profile image)
 2. Hover over some PhotoSpheres
 3. Click on some PhotoSpheres

### Expected behavior

On hovering a thumbnail of the image is shown and when viewing the PhotoSphere it is shown in full resolution and can be dragged around.

### Actual behavior

Three main issues occur (the first one rather minor):
- [x] The default profile image can't be loaded due to a mixed content warning
- [x] When hovering certain PhotoSpheres the preview image can't be shown due to a missing `Access-Control-Allow-Origin` header
- [x] When viewing certain PhotoSpheres, you can't drag them around and it seems that they are not loaded in full resolution

I think that the common property of the affected PhotoSpheres is that they are incomplete PhotoSpheres, so they do not cover the full 360°×180°. The third bullet is probably the same as #1808, just for the new webapp. The images mentioned over there show the same symptoms when hovering and viewing them.

Additionally the following images are also affected:
[![KH69p3LyQQihRko2j5eI0g](https://d1cuyjsrcm0gby.cloudfront.net/KH69p3LyQQihRko2j5eI0g/thumb-320.jpg)](https://www.mapillary.com/app/?pKey=KH69p3LyQQihRko2j5eI0g&focus=map)
[![8I3dl4wUQrvWzvfuqxKFcg](https://d1cuyjsrcm0gby.cloudfront.net/8I3dl4wUQrvWzvfuqxKFcg/thumb-320.jpg)](https://www.mapillary.com/app/?pKey=8I3dl4wUQrvWzvfuqxKFcg&focus=map)
[![_SJJuEUwauvQ8J6S7Qvdzw](https://d1cuyjsrcm0gby.cloudfront.net/_SJJuEUwauvQ8J6S7Qvdzw/thumb-320.jpg)](https://www.mapillary.com/app/?pKey=_SJJuEUwauvQ8J6S7Qvdzw&focus=map)
These images are all from the same sequence, but all other images in this sequence are not affected.

### Additional information

The content of the browser console:
```
Mixed Content: The page at 'https://www.mapillary.com/app/?focus=photo&lat=48.74946194444445&lng=8.342555833333334&z=17&pKey=_SJJuEUwauvQ8J6S7Qvdzw' was loaded over HTTPS, but requested an insecure image 'http://www.mapillary.com/img/fake-avatar.png'. This content should also be served over HTTPS.
Vector tile source "mapillary-source" layer "mapillary-sequences" does not use vector tile spec v2 and therefore may have some rendering errors.
THREE.WebGLRenderer 79
Mixed Content: The page at 'https://www.mapillary.com/app/?focus=photo&lat=48.74946194444445&lng=8.342555833333334&z=17&pKey=_SJJuEUwauvQ8J6S7Qvdzw' was loaded over HTTPS, but requested an insecure image 'http://www.mapillary.com/img/fake-avatar.png'. This content should also be served over HTTPS.
Vector tile source "mapillary-source" layer "mapillary-sequences" does not use vector tile spec v2 and therefore may have some rendering errors.
XMLHttpRequest cannot load https://d1cuyjsrcm0gby.cloudfront.net/KH69p3LyQQihRko2j5eI0g/thumb-320.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d1cuyjsrcm0gby.cloudfront.net/KH69p3LyQQihRko2j5eI0g/thumb-320.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d1cuyjsrcm0gby.cloudfront.net/o_tnK6QF3XXQ6fOWutS2bQ/thumb-320.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d1cuyjsrcm0gby.cloudfront.net/_SJJuEUwauvQ8J6S7Qvdzw/thumb-320.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.

```

**Comment by gyllen** [comment]
@oscarlorentzon Do we handle incomplete photospheres in MJS?

**Comment by oscarlorentzon** [comment]
MapillaryJS does not handle navigation or pan/tilt/zoom for cropped panoramas.

Tracked here: mapillary/mapillary-js#166

**Comment by oscarlorentzon** [comment]
Pan/tilt/zoom part of this issue is the same as in #2035.

**Comment by oscarlorentzon** [comment]
@floscher You can now pan/tilt/zoom in all photos so this should have resolved the third task in your list. It is possible to look around and zoom in all three of your cropped pano examples above.

Reassigning to the front end team for the last unfixed task about `Access-Control-Allow-Origin` problems with preview images.

**Comment by floscher** [comment]
@oscarlorentzon Thank you, everything works now as expected.
