### ISSUE TITLE
Detect duplicates when re-uploading sequences

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2092]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Upload a sequence half
2. reopen the page
3. Try to re-upload the sequence
### Expected behavior

Like in the old uploader, only the pictures not yet uploaded should be considered
### Actual behavior

...
### Additional information

No indication of already uploaded images

**Comment by retro** [comment]
@peterneubauer I believe this shouldn't happen anymore. Can you please confirm that this is fixed?
