### ISSUE TITLE
Share sequence link from map view

### ISSUE THREAD

**Issue by travel193** [mapillary/mapillary_issues#2093]
There is no link to share a sequence directly from the map view even with the sequence selected.

"Further, the share link needs it's contents to be pre-selected (which 
would save yet more clicks to make sure that the url does not have 
characters - such as an underscore - which will stop the entire url from 
being selected)"

**Comment by gyllen** [comment]
This should now be fixed in redesing, ig not please reopen @travel193

**Comment by travel193** [comment]
Sweet! Fixed and looking good.
