### ISSUE TITLE
New labels for issues

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary_issues#2094]
Lets redo the labels. Here is my first draft. Can or can not have a System specific tag.

## Type

`discussion`
This is not an issue mot just a discussion on a hot topic.

`bug`
Something that is intended to work but does not.

`feature`

A request for a new feature.

## System
Affected system.

`web`
The web.

`android`
Android plattform.

`backend`
In the backend.

`vision`
Vision related.

`ios`
iOS releated. Would really like to have small O but lets keep it since we have loads of them already.

## System specific tags
Tags the specific subsystem, example. Up to every system to maintain/

`web-editor`
`ios-upload`
`android-profile`

## MISC

`tracked`
This issue has been tracked and labeled in another repo. Always reference to this issue.

**Comment by knikel** [comment]
Since all this is going to be used in context of zenhub, IMHO it makes sense to use same colours for each group, since we'll be relying on filtering/assignments anyhow.

**Comment by gyllen** [comment]
@knikel I agree color scheme is important

**Comment by gyllen** [comment]
Added new labels closing
