### ISSUE TITLE
new website - can't right-click open sequences

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2096]
in the old profile, i could right-click and open in new tabs sequences in my profile page.
in the new page, right click in the sidebar doesn't allow opening the links anymore (at least in firefox)

**Comment by gyllen** [comment]
Just double checking you can left-click and go to the sequence right? But you do want to open a new tab?

**Comment by richlv** [comment]
yep, exactly

**Comment by knikel** [comment]
I’ll make it a concrete link to a first image in a sequence (the one from the thumbnail).

**Comment by mikini** [comment]
I've been annoyed by this too.

Please add an active link both for the image count ("x images") in the "Feed" tab and the first image thumbnail in the "Uploads" tab (I reckon the above discussion regards the thumbnail only).

Please also consider adding an active link to the sequence (and maybe also image) key displayed in the "Photo details" pane. They are now just text strings, you need to be aware that they can be accessed at mapillary.com/map/s/<seq key> and mapillary.com/map/im/<image key> to be useful.

Example image: https://www.mapillary.com/app/?focus=photo&pKey=ruwlhsuIXyx2X9EZ23NnCg&lat=55.8434389&lng=9.2253111&z=17
Could have links to http://mapillary.com/map/s/Bj9bTc-6TKjO36jkWquPgQ and http://mapillary.com/map/im/ruwlhsuIXyx2X9EZ23NnCg.

**Comment by gyllen** [comment]
@mikini This sounds right, lets fix

**Comment by knikel** [comment]
This has been fixed, sequences are anchor tags that can go to `/app?pKey=:key` URLs. Visible soon.

**Comment by richlv** [comment]
seems to work as expected - thank you :)
