### ISSUE TITLE
new webpage: Cannot find subpage with discovered trafic sign

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#2098]
I could on the old page find a sub page where I could see the trafic sign that I did find. But I cannot find this page since the rewamp of the homepage

**Comment by gyllen** [comment]
@beer119 We will try to readd this feature. Since the structure for trafficsigns is somewhat different in database today we need to see if a lookup within reasonable time is possible (I think it is)

**Comment by gyllen** [comment]
At the moment we have no plans to adding this feature. If you still miss it please open a thread in https://forum.mapillary.com
