### ISSUE TITLE
Splitting sequences

### ISSUE THREAD

**Issue by Catodae** [mapillary/mapillary_issues#210]
Being able to split up a sequence, which is connected accidentally. Maybe by selecting an image and after that image the sequence is getting split.

**Comment by DenisCarriere** [comment]
Was this removed in the newer version of the web version of Mapillary?

Seems like there's no way to split a sequence any more.

![image](https://cloud.githubusercontent.com/assets/550895/25557248/dd52fdcc-2cdb-11e7-8ad3-897aba9160e2.png)

Need to flag or request a split for [very obvious sequences](https://www.mapillary.com/app/?lat=45.39964954056171&lng=-75.69016998959327&z=18.109211051969407&pKey=kxqG-Mpaout997MdZe7FPQ) such as:

![image](https://cloud.githubusercontent.com/assets/550895/25557249/ead476a6-2cdb-11e7-81f5-7154de8471da.png)


Ref: https://github.com/mapillary/mapillary_issues/issues/762 https://github.com/mapillary/mapillary_issues/issues/509
CC: @peterneubauer @jesolem

**Comment by katrinhumal** [comment]
@DenisCarriere you are right, we don't have the manual split function in the new editor. Instead, we have a sequence cutting bot that will take care of instances where the images are too far apart.

**Comment by katrinhumal** [comment]
However, it looks now as if this particular case it has been failing to cut. Bringing in @ybkuang for help.

**Comment by ybkuang** [comment]
@DenisCarriere we have a bot that will go through sequences and cut them when the distance is larger than 800 meters (we plan to use a small distance in the future). However, we realized that the bot will occasionally miss some sequences. We are investigating and will report back.

**Comment by DenisCarriere** [comment]
👍 @ybkuang @katrinhumal Thanks for the feedback, looks like it's fixed (bot or human).

![image](https://cloud.githubusercontent.com/assets/550895/25710652/dc753c5c-30ba-11e7-99c8-bf984a9ee1c4.png)

**Comment by geowOSM** [comment]
I would like to ask splitting these sequences as the bot seems to have missed them

uNrGTsmVyr5YXKUHoP4uiA
Sa2HihIyiuMO8yvaU4i4-Q
l12Ix9kOqGlAMsNQgLHadA

Any news on inventing manual splitting/joining in the web version?

Thanks!

**Comment by katrinhumal** [comment]
@geowOSM Thanks - any chance that the sequences have been cut by now? I can't seem to find them in our database (which would make sense if those original sequences have been split up now). If that's not the case, please share the url-s to any image belonging to the sequence.

As for now, we don't have any specific plans for adding the manual split/join functionality to the editor.

**Comment by geowOSM** [comment]
Thanks @ybkuang , looks clean now!

> As for now, we don't have any specific plans for adding the manual split/join functionality to the editor.

That is really too bad. Then ist would be nice to reduce the minimum distance of images, maybe to <250 m.

Thanks for considering...🙏

**Comment by tordans** [comment]
@ybkuang this sequence should be cut https://www.mapillary.com/app/user/tordans?lat=52.23552115802797&lng=5.946042647072156&z=17&pKey=Lqt0AKlI3ttUcVA-H7TveQ&focus=map - do I still need to wait for the bot or did something go wrong?

It would be great to have a "cut manually" feature (again), so we can take more control about the way the pictures are presented.

I have this issue a lot when taking pics in the manual mode where the app does not detect sequences as well. It might also be something to fix in the app by adding a (optional) "split folder" (before uploading) or "start new sequence" (before taking new pics) feature.

**Comment by ybkuang** [comment]
@tordans we recently updated the database. There is a minor issue that causes delays in sequence cut. We are working on it.  I will open a separate internal issue about the split on our app. If you have any more details on it, can you send it to support@mapillary.com? we are closing mapillary_issues in favor of our forum and support channel.
