### ISSUE TITLE
ios app - less background upload than before

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2100]
in older versions of the app, if an upload was started and i switched to another app, switching back to the mapillary upload resulted in the upload counter increasing significantly - indicating that some upload had happened even while the app was not in focus. while the amount was usually mostly limited (switching away for a long period of time did not upload many images in the background), it still was helpful in getting more images uploaded.
with the latest versions, as soon as the app loses focus, upload is completely stopped (switching back to the app does not result in the upload counter increase)

**Comment by nicolas17** [comment]
Could this use a background NSURLSession? I think that would allow unlimited-time uploads, since they are handled by a different process altogether. iOS can suspend or even kill the Mapillary app and keep uploading.

**Comment by descilla** [comment]
I've noticed this problem, too. The problem seems to occur since the "mapillary-metadata" isn't written during capturing anymore but is written during upload process into the image files.

**Comment by millenbop** [comment]
The old/current background upload implementation hasn't really worked that well ever, but I will implement proper background upload soon, perhaps using what @nicolas17 suggested above.

**Comment by richlv** [comment]
any news on the background upload ?
the current need to keep the phone unlocked eats more battery, is easy to forget to keep open and has some security implications, too :)

**Comment by richlv** [comment]
@millenbop, in january you suggested that the background upload might be ready soon - any news ? :)

**Comment by millenbop** [comment]
Yes, sorry about that.

It is about 90% done on a separate branch, but ran into some problems and then we decided there where some more important things that needed to be done first.

I'll bring it up with our project manager again. 

Thanks for pinging!

**Comment by richlv** [comment]
if there's an incomplete, but safe solution that makes it slightly-more-backgroundish, i think your users would appreciate that for now - although 100% solution would require a mini-party ;)

**Comment by millenbop** [comment]
I just don't like pushing out stuff that I know is broken :) It wasn't 100%, often a few photos weren't uploaded. No other errors though.

**Comment by richlv** [comment]
if the photos were not lost, that's an improvement already. but i appreciate your attention to quality a lot, thank you :)

**Comment by richlv** [comment]
hi, any luck with this one ? it would make contributing easier :)

**Comment by richlv** [comment]
...it shows that i unassigned @amahon, although i did nothing like that.

**Comment by millenbop** [comment]
Yup, I have proper background uploading implemented now. I will send out betas soon.

Hm not sure why it says that you unassigned him. He doesn't work here anymore though, so maybe someone at Mapillary did some cleanup and removed him from the org.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
