### ISSUE TITLE
Enhancements of new edit changesets 

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#2101]
Hi
### Basic information
- Platform:  `Web`
- Version: `26.7.2016` 
- System/Browser: `Linux Debian Jessie, Chromium`
### Steps to reproduce behavior
1. Select a crazy winding track
2. Try to move some pictures from the track
3. Get lost and crazy with too many lines on screen
### Expected behavior

Better visability of new positions, better color for old/new positions, e.g. grey out old ones
...
### Actual behavior

To colorful,, not easy to not get lost with all the blue lines in a crazy winidng track
...
### Additional information

...

**Comment by gyllen** [comment]
@angelday Feedback for editor

**Comment by angelday** [comment]
@echeloni2p thanks, we have plans to make the changeset diffs more understandable. Can you in the mean time provide us with links to sequences or screenshots? Most curious.

pinging @retro, too.

**Comment by echeloni2p** [comment]
Hi!

Sure, e.g. https://www.mapillary.com/app/user/aceini?lat=47.34404702727375&lng=15.400155131924365&z=17&focus=map&pKey=mBNRsEmXpfaYOi8tTwcL7w - a gorge in the moutains with bad GPS receivement...
Hard to edit this to get the real picture order in one go.

echelon

**Comment by angelday** [comment]
Yes, also you need to zoom at least further in.

@retro I think we have that one in a different issue, if not, we should.

**Comment by angelday** [comment]
We fixed editor markers to be better, closing.
