### ISSUE TITLE
edu.mapillary.com and opendata.mapillary.com HTTPS Errors

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2104]
### Basic information
- Platform: `Web`
- System/Browser: `Windows 7 Pro SP1 64-bit/Google Chrome 51.0.2704.103`
### Steps to reproduce behavior
1. Go to any pages on https://www.mapillary.com
2. Scroll to the bottom.
3. Click or hover over `MapillaryEDU` and `OpenData`
### Expected behavior

Move the subdomains off of squarespace.com's servers to be able to use the *.mapillary.com SSL Certificates.
### Actual behavior

`This server could not prove that it is opendata.mapillary.com; its security certificate is from *.squarespace.com. This may be caused by a misconfiguration or an attacker intercepting your connection.`

`This server could not prove that it is edu.mapillary.com; its security certificate is from *.squarespace.com. This may be caused by a misconfiguration or an attacker intercepting your connection.`
### Additional information

Squarespace.com doesn't support custom SSL certificates.

https://support.squarespace.com/hc/en-us/articles/205815898-Does-Squarespace-support-SSL-access-

**Comment by gyllen** [comment]
We are moving site over to new web. Will report back when fixed.

**Comment by pbb72** [comment]
The same is true for links (from email) to the Mapillary forum; these go to mapillary.io, and also cause SSL issues.

**Comment by gyllen** [comment]
Links are now fixed
