### ISSUE TITLE
new user, bad uploads need deleted

### ISSUE THREAD

**Issue by worfrb** [mapillary/mapillary_issues#2105]
I tried a gopro 4 session with seperate gpx track and it didn't work out, tried edit positions and the sequence is all messed up.
http://mapillary.com/map/im/GH0KkNQAJ5eQQxL27_yCYQ

I fouled up another here.
http://mapillary.com/map/im/Ixv_Ej4vIynbq9QxqtiG5g

Thanks

**Comment by gyllen** [comment]
No problem, delete feature is on its way. I will report back when you can do delete. Sorry for the inconvenience right now.

**Comment by ulikoehler** [comment]
I think this could be closed since a delete feature exists for both sequences and for photos and IMO it works really well
