### ISSUE TITLE
Receiving 404 response for all API requests to https://a.mapillary.com/v2/status?client_id=

### ISSUE THREAD

**Issue by erikschlegel** [mapillary/mapillary_issues#2106]
### Basic information
* Platform: `iOS` | `Android` | `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1.
 2.
 3.

### Expected behavior

...

### Actual behavior

...

### Additional information

...

**Comment by gyllen** [comment]
This is an error in the documentation. I updated it accordingly.
