### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2107]
I can not find the video upload. Is there available or is gone?

**Comment by gyllen** [comment]
@eugensim We are about to readd that feature. In the meantime please use https://legacy.mapillary.com

Will report back when added

**Comment by eugensim** [comment]
@gyllen ok, and please increase to size limit of the video to 7GB, because 4k videos are very big and it's wasting time to trim them.

**Comment by smsm1** [comment]
4GB would help me as that's what my Garmin Virb splits the video files to.

**Comment by gyllen** [comment]
It should be updated to 4GB now, please verify

**Comment by smsm1** [comment]
Thanks, I'm currently uploading a video which is 3.67GB in size, with no errors so far.

**Comment by smsm1** [comment]
The upload completed without any errors. 👍

**Comment by gyllen** [comment]
Awesome! closing!
