### ISSUE TITLE
Pause on Stop not working

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2108]
Beginning in 2.34, and also in 2.35, Pause on Stop doesn't seem to work, in both Distance and Timed sequence modes.

### Basic information
* Platform: Android
* Version: 2.34 / 2.35
* System/Browser: 6.0.1

### Steps to reproduce behavior

 1.  In Settings, ensure Pause on Stop is enabled.
 2.  Select desired sequence mode (Distance or Timed)
 3.  Begin driving and start taking a sequence.  At an acceptable place, come to a complete stop for at least 60 seconds.
 4.  Notice the image-taken counter continues to increment.
 5.  (optional)  Stop driving and review the sequence(s) taken.  Notice that it will include images taken while stopped.

### Expected behavior

...Mapillary should stop taking pictures when stopped for more than at least a few seconds (e.g., at a traffic signal).

### Actual behavior

...Mapillary continues to take pictures, even when stopped for minutes.

### Additional information

...Worked very well before 2.34.

**Comment by Caboosey** [comment]
I have this same behavior happening with either Time based or Distance based on v2.35 and v2.36. Pause on stop appeared to stop working since v2.35

**Comment by jfburke3** [comment]
Just a note that this is happening in 2.37, too.  I haven't sent in any fresh logs recently for it, but I can if you want them.

**Comment by rsahlin** [comment]
Aha, this is a mistake on my part.

The option 'Pause on stop' will be removed.
Timer base capture shall be used when you want to have a specific number of pictures per second, regardless of your movement.
Distance based capture shall be used to get evenly distributed pictures, based on distance - for instance driving in a car and stopping.

Best regards
/Richard

**Comment by jfburke3** [comment]
That's fine, but please be sure that distance mode works (currently it takes pics even when stopped--I have a case open for that).
