### ISSUE TITLE
Andoid app won't start uploading

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2111]
### Basic information
* Platform:  `Android`
* Version: `2.31` 
* System: `Asus K007, android 5.0.1`

### Steps to reproduce behavior

 1. start the app with a previous set of sequnces (in this case 61 seq with 11651 photos)
 2. from the menu choose "Start upload now"

### Expected behavior
upload should start

### Actual behavior
a toast is displayed with the message "Upload requested. Progress will be shown...." But no progres indicator show up and no uploads are done

### Additional information
debug log sent per email

**Comment by mprins** [comment]
also I  recall the possibility to upload sequences one at a time a checkbox was visible in the review sequences page on a sequence thumbnail, this is no longer visible.

**Comment by peterneubauer** [comment]
@mprins the 2.36 release just went out, can you check that the checkboxes are there and otherwise send a screenshot?

**Comment by mprins** [comment]
check boxes are now there and when I check one and press the upload it starts off uploading. Maybe I had everything "unchecked" but that wasn't obvious to me...

background upload also works (now that I've check all sequences) so Iḿ closing this

**Comment by peterneubauer** [comment]
Awesome, thanks and keep the feedback going!
