### ISSUE TITLE
Editing picture orientation

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2112]
Where is the picture orientation alignment option on the new web interface?
 In the old editing interface there was the possibility to align the picture orientation so tht each photo was "looking" in the direction of the next one

**Comment by pbb72** [comment]
That is called "Normalize Sequence" now. Previously you could also add a number of degrees to the alignment, now you first have to normalize, and after that rotate all using "Set Offset".

**Comment by gyllen** [comment]
@pbb72 Thanks for explaining

**Comment by voschix** [comment]
I had not yet discovered the sequnce editor menu :-(

**Comment by gyllen** [comment]
@voschix Have you found it?

If not follow the following steps

1. Navigate to an image thats in a sequence you want to edit
2. Switch so you have small image, big map
3. Press the ... in the middle of the screen to the right

PS: We are doing some rework on this now to make it clearer

**Comment by gyllen** [comment]
Redesing is now done, @voschix reopen this ticket if you can not find the sequence editor.
