### ISSUE TITLE
Set compass angle button seems disabled

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2113]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Go into edit mode.
2. Notice how the "Set" button for "Compass Angle" seems disabled (low-contrast grey). This seems okay, since the angle has not been edited.
3. Change the angle amount.
4. Wait (indefinitely) for the button to become enabled (high-contrast colour).
### Expected behavior

The button should have high contrasting colours when enabled.
### Actual behavior

The button is actually never disabled. But the line colour is in so low contrast to the background that it is almost invisible, and seems disabled.
### Additional information

The contrast ration between background and foreground for this button is 1.8, which is very low. For such small text, the ratio should be at least 4.5. Check the current ratio at http://leaverou.github.io/contrast-ratio/#%23ABB1B9-on-%23E6E9ED, and the W3C recommendation at https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html.

**Comment by nickplesha** [comment]
Thanks for reporting, we're tracking this issue internally and should resolve it soon. You can check status by emailing support@mapillary.com
