### ISSUE TITLE
Missing MAPILLARY_PERMISSION_HASH and MAPILLARY_SIGNATURE_HASH from new settings page

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2117]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 7 Pro SP1 64-bit/Google Chrome 52.0.2743.82`

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/uploader

### Expected behavior

Show information needed to use python scripts either on upload page or actual user settings area like the https://www.mapillary.com/app/settings/developers page

### Actual behavior

No information displayed anywhere on the new Mapillary website about the logged in user's MAPILLARY_PERMISSION_HASH and MAPILLARY_SIGNATURE_HASH information.

### Additional information

MAPILLARY_PERMISSION_HASH
MAPILLARY_SIGNATURE_HASH

Note: I already have this information for myself, but noticed this information has disappeared with the new Mapillary website.

**Comment by knikel** [comment]
Thanks for all the feedback @Caboosey, you can find the hashes at `http://legacy.mapillary.com/map/upload/im`, we'll port these to relevant place in settings pages.

**Comment by Caboosey** [comment]
Thank you @knikel  I also submitted a pull request for the mapillary tools to help others that may come across this issue untill the new website has this info.

https://github.com/mapillary/mapillary_tools/pull/126

**Comment by HolgerJeromin** [comment]
This is solved, isn't it?

**Comment by Caboosey** [comment]
Yup.
