### ISSUE TITLE
Also hide featured photos when "Show my coverage only" is on

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2118]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Open the map view, open the right menu, open the Uploads tab.
 2. Turn on the option "Show my coverage only".

### Expected behavior

Only my photos will be shown on the map.

### Actual behavior

Both mine and featured photos are shown on the map.

**Comment by knikel** [comment]
Fixed, visible soon.

**Comment by pbb72** [comment]
Thanks!
