### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2119]
I am somewhat dyslectic, which makes it harder for me to decipher complex texts and numbers. For numbers like "3833641m", it takes me quite some effort to actually see what kind of magnitude we're talking about.

Please format large numbers with either spaces, dots or commas for digit grouping. "3.833.641 m" is a lot easier to read for me (and maybe many others like me).

**Comment by gyllen** [comment]
@pbb72 Impressive number by the way ;)

**Comment by pbb72** [comment]
Thanks! And most is done by foot :smile:

**Comment by knikel** [comment]
We round number similarly to Twitter now. Hope it works for you guys! Visible soon.

**Comment by pbb72** [comment]
Hmmm I see what you did there, but sadly the situation didn't become better, because of ambiguity and bad use of unit indicators.

You know what it says now? "Meters mapped: 3.8m" Suddenly I look like an absolute beginner!

I know the meaning is to say "3.8 million". However:

(1) In the case of distances, "m" is too easily understood as meaning "meters". Don't use any other "m" abbreviations when you're talking about distance. (The only exception being "mm", millimeters...)

(2) The use of "m" for "million" is wrong in several ways. Firstly, it's supposed to be a capital "M", and secondly it's only supposed to be used as a prefix to a proper unit. (E.g. MW for megawatt, 1 million watts.) (See also https://en.wikipedia.org/wiki/M_(disambiguation) )

Correct use would be "Mm" (megameters) but I would strongly advice against that also... I'd say either write "3.8 million meters" or "3,834 km" (in which case the label also needs to be changed to "Distance mapped" instead of "Meters mapped").

**Comment by knikel** [comment]
@pbb72 really good points, we took inspirations from Twitter, but in their case tweets have no units below/above them, 1 is 1. I agree, _Distance mapped_ as a field label makes the most sense with units as you described. It should also fit with the amount of space we have there.

Ping @angelday.

**Comment by pbb72** [comment]
Sadly enough, above km (kilometer), we don't have any factors that make sense to the average Joe. Mm, Gm, Pm (or megameter, gigameter, petameter) just are not very clear.

You could start with "x.x times around the earth" (but that takes a lot more space.

**Comment by pbb72** [comment]
Another place where number formatting is required (and where you can't abbreviate numbers): the leaderboard.

**Comment by angelday** [comment]
@pbb72 here is the version we rolled out:

## For uploaded photos:

less than a thousand = as is, eg. 984
less than 9999 = 9.8 K
above 999 999 = millions, eg. 1.1 M

## For meters mapped:

less than a thousand meters = as is, eg. 984 m
more than 999 meters = 1 km
between 1 km and 999 km = 274.8 km
above 1 000 km = 17 842 km (we omit the decimal mark and do English SI style space separators between thousands)

**Comment by HolgerJeromin** [comment]
Thanks for not showing a dot or comma in kilometers mapped!

**Comment by pbb72** [comment]
Very cool!

But a few remarks:

- It still says "Meters mapped" on profile pages, it think "Distance mapped" would be better.
- Distances above 1 000 km are displayed with one decimal, my distance is "4 366.1 km". (Wow. Did I map over 500 km in the last month?)
- Could you do the number formatting also for the leaderboard? Allen now has "4456195" photos, which is difficult to read.

**Comment by angelday** [comment]
Thanks for the feedback, good points @nickplesha could you take it from here, please?

1. good point, needs to be changed
2. above 1 000 km we shouldn't display decimals, needs to be changed
3. leaderboard needs to be changed as well

**Comment by knikel** [comment]
This has been fixed, as described by @pbb72 and @angelday. Visible after the next deploy. Thanks!
