### ISSUE TITLE
Bring back time travel

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2120]
I really liked this feature, being able to discover other people's photos of the same locations I was.

**Comment by de-vries** [comment]
I agree with @pbb72 and I'd like to propose a improved version of the time travel feature. To explain this idea properly I made some mockups:

![mapillary - tt photo slider](https://cloud.githubusercontent.com/assets/1449609/17206060/327733ce-54ae-11e6-8020-da24c7309e6d.png)
The time travel feature is in a similar widget as the map. It has a time line that shows clickable dots where(when) the photos are. The dots show a tooltip with the date on mouseover.

![mapillary - tt photo colapsed](https://cloud.githubusercontent.com/assets/1449609/17206158/b86b2346-54ae-11e6-92c8-1ccbf30493a5.png)
Of-course the time travel widget is collapsible.

![mapillary - tt map filter](https://cloud.githubusercontent.com/assets/1449609/17206476/1d4871d2-54b0-11e6-8f34-2fdcc6fccbb0.png)
In the map view there is a different approach. The widget now contains a graph for the current viewport with the date on the x-axis and the number of photos made on the y-axis. The red bars are sliders to set a time filter, only sequences between the bar are shown on the map. (And again; tooltips with the date on mouseover)

**Comment by pbb72** [comment]
I love the mock-up! But be careful not to place too many floating windows, not everybody is using a full-HD screen. Love the icon also, but maybe it's not obvious enough for non-western users.

I think instead of a floating timeline on the map, filtering should be brought back instead. (Oops, yet another request :smile: ...)

**Comment by de-vries** [comment]
> But be careful not to place too many floating windows

true, the default state of those extra windows should probably be collapsed.

**Comment by HolgerJeromin** [comment]
The images are nice. But I don't think the time machine icon is good for most users. 
I just searched for "time machine icon" and learned the logo for the Apple product with this name which I find quite brilliant.

**Comment by gyllen** [comment]
I was thinking something like a popup where you can see the images above and a timeline above with marked dates. Then you can view the static image first and then the transformed one.

I would also love to get this MapillaryJS out-of-the-box feature in there somehow.

**Comment by pbb72** [comment]
@HolgerJeromin Google is using a very similar icon in Streetview :smile:

**Comment by oscarlorentzon** [comment]
Support for this need to be implemented in MapillaryJS. Tracked here: mapillary/mapillary-js#174

**Comment by jfburke3** [comment]
I vote for the TARDIS icon!  :+1:

**Comment by jfburke3** [comment]
Bonus points for the Mapillary team if they can generate a wheezy-grindy sound when you click on it.

**Comment by richlv** [comment]
time travel is sort of back. it does not work for me, but that should be tracked in separate issues - i guess this one can be closed :)

**Comment by pbb72** [comment]
Yeah, time travel is back. Wish it was better integrated into the main photo view though.

**Comment by gyllen** [comment]
@pbb72 We are open for suggestions :)

**Comment by richlv** [comment]
for the record, time travel does not seem to work for me at all - created #2362 for that :)

**Comment by gyllen** [comment]
@richlv Does these photos work for you -> https://www.mapillary.com/app/time-travel/gyllen?lat=55.882077&lng=12.999643&z=17&pKey=QgsJo-chSDFSWRAezdpmOA&cKey=I9AOd1BsI84kfy0c79NzSQ&focus=photo

**Comment by richlv** [comment]
@gyllen, yes - looks like it is related to the original gps coords. if they are a bit off, it fails to show the slider even if the images were auto-connected by the time travel. see #2362 :)

**Comment by gyllen** [comment]
@richlv Aha, ok looks like @oscarlorentzon is investigating then

**Comment by pbb72** [comment]
@gyllen The mockups by @de-vries were very good.

Availibility of time travel is currently almost invisible, it's a small icon that has a slight change in hue. Clicking on the icon gives an inconsistent interface. If there is only one alternative, then that is displayed as a thumbnail. If several alternatives are available, then a somewhat but not really time travel-like interface is show which does not really serve any purpose because all photos are available in the next step.

Actually this whole step does not really serve any purpose, apart for those that are satisfied with just a thumbnail of the alternative view. You need to click on "Compare" to get to see the alternatives in full size. 

The time travel view is obstructed for a large part by the sharing window. The time travel feature itself is technically marvellous, but in practice not serving any need. Also, you need to interact with it, to see it.

What I would like is a thumbnail that is immediately displayed when time travel is available. This thumbnail can be half the size of the one currenctly displayed in the first step towards time travel. Below the thumbnail a timeline that includes the photo currently displayed in the main view. (Meaning there will always be a timeline, even with only one alternative image.) Clicking the thumbnail, displays that photo in the main view. For transition from the current to the new photo, the nice time travel effect can be used, but without user interaction. (Just doing a quick transform in about 1 second.)

**Comment by gyllen** [comment]
@angelday Thoughts on this?

**Comment by angelday** [comment]
I agree that it is hidden and we should improve it. My original idea was to have a filtering option for TT-able photos otherwise it will be just browsing around.

**Comment by gyllen** [comment]
@angelday This is not possible with the current setup in the backend though. TT is claclulated client side at the moment.
