### ISSUE TITLE
Panoramas slow rotation 

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2123]
With the old site it was very easy the rotate a panorama (just like Google Street View), but now I have to abuse my mouse to create a 360 degree rotation. 
OLD: https://legacy.mapillary.com/map/im/2NK4L_6gW7BxBlsuJ0K-gw/photo
NEW: https://www.mapillary.com/app/?lat=55.77276837502266&lng=37.819744500000006&pKey=VqfPVLHJW6L7BW4nPqQiBw&z=17&focus=photo&menu=false

There are any settings that I missed?

**Comment by oscarlorentzon** [comment]
Thanks for reporting. You have not missed any settings. It should just work. 

1. What operating system are you using?

2. What browser and version of that browser are you using?

3. Is it working differently in any other browsers for your operating system?

**Comment by eugensim** [comment]
1 Windows 10
2 Chrome 52.0.2743.82
3 Working better in Edge but not perfect.

**Comment by oscarlorentzon** [comment]
Thanks for the info. Will investigate why the mouse events behave differently on Windows 10.

Tracked here: mapillary/mapillary-js#172

**Comment by oscarlorentzon** [comment]
This should now be fixed.

Happy for a confirmation that the behavior is improved for you @eugensim .

**Comment by eugensim** [comment]
@oscarlorentzon it's ok now thanks
