### ISSUE TITLE
Scrolling when displaying image comments is broken

### ISSUE THREAD

**Issue by mikini** [mapillary/mapillary_issues#2126]
### Basic information
* Platform:  `Web`
* System/Browser: `Ubuntu 15.10` using `Firefox 47.0` and `Chromium 51.0.2704.79`
* System/Browser 2: `Windows Server 2008` using `Internet Explorer 11.0.33`
  

### Steps to reproduce behavior

 1. Open browser on image with key ruwlhsuIXyx2X9EZ23NnCg (https://www.mapillary.com/map/im/ruwlhsuIXyx2X9EZ23NnCg)
 2. Click the comment icon in the right side of the screen (2nd from top) showing that image has "2" comments

### Expected behavior
Full comment history can be accessed.

### Actual behavior
Only the last 10 lines from the last comment can be seen. No scrolling is possible. The exact number of characters differ between the 3 browsers I tested, but all show 10 lines.

### Additional information
Double clicking on the comment will select the text of the complete last comment, and this can be copy'n'pasted elsewhere. Likewise, selecting and copy'n'pasting all text on the page (using ctrl-a or similar) will show that all comments are loaded but not visible. The Emacs window in the Firefox screenshot below shows the pasted text. 
... 

![ubuntu 15 10 firefox 47 0](https://cloud.githubusercontent.com/assets/1330166/17213509/dd619fe2-54d4-11e6-8dc5-fa0ba7204648.png)
![ubuntu 15 10 chromium 51](https://cloud.githubusercontent.com/assets/1330166/17213510/dd6247ee-54d4-11e6-8583-3b6aab2a9d83.png)
![windows server 2008 ie 11](https://cloud.githubusercontent.com/assets/1330166/17213511/dd658a44-54d4-11e6-9946-ec784444fe7f.png)

**Comment by gyllen** [comment]
@mikini Thanks for reporting

**Comment by knikel** [comment]
Fixed, visible, soon. Thanks for reporting!
