### ISSUE TITLE
"Click, release, drag and click again" does not make sense

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2127]
In the help for the online blur editor it says "Click, release, drag and click again" as instruction for creating a new blur.

This does not make any sense. "Dragging" is moving the mouse with the mouse button held down. After releasing the mouse button, it's simply called moving the mouse.

**Comment by pbb72** [comment]
The other two uses of the word "drag" in the instructions are correct.

**Comment by nicolas17** [comment]
Duplicate of #2047?

**Comment by pbb72** [comment]
Yeah more or less a duplicate. At least Mapillary is aware of the problem.
