### ISSUE TITLE
Display both GMT/UTC and Local Date/Time of picture

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2128]
### Basic information
- Platform: `Web`
- System/Browser: `Windows 7 Pro SP1 64-bit/Google Chrome 52.0.2743.82`
### Steps to reproduce behavior
1. Go to any photo on the map outside of GMT/UTC time zone.
2. Click on the `...` button to pull up details of photo.
### Expected behavior

Under the user name show date time info like so:
GMT/UTC: July 5, 2016 02:00
Local: July 4, 2016 21:00 (DST On/Off)

It should show the local date/time of the geographical time zone the photo was taken in.
### Actual behavior

Only GMT date/time of photo is displayed.
### Additional information

IANA hosts updated Time Zone data (TZ):
https://www.iana.org/time-zones

label:feature

**Comment by pbb72** [comment]
This seems to be inconsistent at the moment. The Australian photo at http://mapillary.com/map/im/UaxtxGveW8W1MMNG9VOI7Q has a timestamp at 15:21, while the one at http://mapillary.com/map/im/NSeu-Q1ICr1ZTPpG8Qnuhw has 01:36. Both are obviously taken during day time.

**Comment by Caboosey** [comment]
Here is my example:
https://www.mapillary.com/app/?focus=photo&pKey=_rk1jw-5biuU4mfdrjYmNg&lat=30.4964935&lng=-87.3309033&z=17

Date/Time shows: July 24, 2016 02:03
Actual Local Date/Time: July 24, 2016 07:03
Photo's geolocation Local Time Zone at the time: Central Daylight Time (US) [GMT -5 DST]

My Phone's time settings:
Automatic date and time: Enabled
Automatic time zone: Disabled
Select time zone: GMT-05:00 Central Daylight Time
Use 24-hour format: Disabled

I only change my time zone if I have moved my residence to a different time zone.

**Comment by gyllen** [comment]
Is GMT really interesting in this case? Isn't it really the local timezone thats interesting?

**Comment by pbb72** [comment]
Yeah, I think so too, though it might be confusing for sequences that cross a timezone.

**Comment by gyllen** [comment]
Added to idea box on how to show dates
