### ISSUE TITLE
Show Image Direction in the photo uploader

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2129]
### Basic information
* Platform: `Web`
* Version: `new` 
* System/Browser: `Chrome`

### Steps to reproduce behavior

 1. Go to Uploader
 2. Add some photos
 3. Zoom In
 4. Note the symbology of the points representing photos

### Expected behavior

Photo points show the direction that the photo is pointing, e.g. i.e. the heading.

### Actual behavior

Photos are represented by a dot only.

### Additional information

![screenshot](https://cloud.githubusercontent.com/assets/1827881/17228324/90451598-54e0-11e6-9631-ffb1c3d82f7a.png)

**Comment by pbb72** [comment]
Duplicate of #2067

**Comment by talllguy** [comment]
Thanks @pbb72 closing
