### ISSUE TITLE
Allow manual positioning of photos without GPS position

### ISSUE THREAD

**Issue by kayD** [mapillary/mapillary_issues#213]
I started a sequence of photos (in walking mode) from whithin a builing, i.e. without GPS signal. When I left the building, the signal was back and the photos starting from there appear on the map. And I can drag them around a bit to improve the position.

However, drag and drop is not possible with the first images inside the building. Please have a look at this image:

http://www.mapillary.com/map/im/LI5oJNhB3G8SqGx9iLscmg

The position is marked at lat 0, lon 0. When I edit the photo, the marker disappears.

However, if I press the "up arrow" (next in sequence) 13 times, that image appears with a marker on the map, as do the following images, e.g. 

http://www.mapillary.com/map/im/nUvt11NVk61YNIJMr9QgZw

What I wish is to have an option to also set the coordiates for the first 12 pictures - I tried to enter a "Location" as "Nürnberger Straße, Würzburg" (i.e. the same as in the geolocated pictures), but it was not picked up.

**Comment by knikel** [comment]
This will be implemented a part of our new uploader (both web and desktop). Will close when we roll it out.
