### ISSUE TITLE
In blur mode, pause playing at blurred images

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2134]
While playing a sequence in blur mode, the speed is usually slow enough to decide if a photo needs blurring. Otherwise, already existing blurs are difficult to catch, especially when they are small and blend with the background. It would be nice to have an option for the player to automatically pause at blurred images. That would ease the hunt for false positives.

**Comment by gyllen** [comment]
@angelday What about this idea as you go through the images with play we pause if there are blurs in the image.

**Comment by angelday** [comment]
We could have the play button in blur mode automatically stop when it detects a blur. Does not require design and makes sense there.

**Comment by gyllen** [comment]
@angelday Im not sure its the expected behavior though, should this be a pro setting?

**Comment by angelday** [comment]
In that case, yes. Let's add this when we start designing the "pro" stuff for blurs.

**Comment by katrinhumal** [comment]
@kaitu This suggestion is still relevant. I've resurfaced it in our internal ideas pool so that it could be planned in at some point. Thanks! Closing here for now.
