### ISSUE TITLE
Graphics glitch in the map

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#2135]
### Basic information
* Platform: iOS 9.3.3 on iPhone 6S Plus, gopro hero4 session
* Version: 4.4.7

### Steps to reproduce behavior

 1. Map with gopro, with no map canvas and no 3G reception, drive mode

### Expected behavior

The marker denoting my current location should be at the end of the blue line drawn.

### Actual behavior

The marker is way off, but the blue line still keeps drawing where it is supposed to. It has a left turn if I turn left, and a right turn if it turns right. 

![2016-07-29 21 18 12](https://cloud.githubusercontent.com/assets/3048065/17259252/50c2cb92-55d3-11e6-9156-9d3ada06b87e.jpg)

**Comment by talllguy** [comment]
Similar to #1989

**Comment by millenbop** [comment]
Duplicate, closing. Tracked in #1989 instead.
