### ISSUE TITLE
Strange interpolation between photos 

### ISSUE THREAD

**Issue by bhousel** [mapillary/mapillary_issues#2138]
### Basic information
- Platform: `Web`
- System/Browser: `Chrome 52`

Not sure what is going on between these photos in this sequence:
[m0HzGu7enI4CTh8TGaYKJw](https://www.mapillary.com/app/index/bhousel?lat=40.74087638888889&lng=-74.38330305555554&z=17&pKey=m0HzGu7enI4CTh8TGaYKJw&focus=map)
[tXRsCy51bmw4YWFDw1PHww](https://www.mapillary.com/app/index/bhousel?lat=40.74086805555556&lng=-74.38317638888888&z=17&pKey=tXRsCy51bmw4YWFDw1PHww&focus=map)
[4L1IV_Y7LN1KXf5fl5Z_3A](https://www.mapillary.com/app/index/bhousel?lat=40.740835000000004&lng=-74.38302805555554&z=17&pKey=4L1IV_Y7LN1KXf5fl5Z_3A&focus=map)
[S4ShiABXhKxRA7nLYD6u-g](https://www.mapillary.com/app/index/bhousel?lat=40.74079972222222&lng=-74.38286805555555&z=17&pKey=S4ShiABXhKxRA7nLYD6u-g&focus=map)

![mapillary interp](https://cloud.githubusercontent.com/assets/38784/17269963/cbedf570-5624-11e6-91f2-290980f8dd7e.gif)

I checked the exif data on the images and it all looks ok.

Is this a viewer bug with matrix/quaternion interpolation (I can help here!) or something that happened when the images were processed?

**Comment by talllguy** [comment]
I've noticed this as well. It is especially an issue for me, because it prevents the navigation arrows that hover over the ground from operating properly. [Example](http://mapillary.com/map/im/5w7NsdxpjBJoS4WrH0BcvA):
![image](https://cloud.githubusercontent.com/assets/1827881/17422871/0e47b290-5a84-11e6-9aee-81935d2fb512.png)

**Comment by gyllen** [comment]
So in both these cases notice how the clouds look in the sky, problem here is that our backend things that its the sky thats the most important part. Right now we are performing full semantic segmentation on all our images. Notice how we detect the sky here (image below). Next step will then be to filter out the sky, this will solve this problem. Don't ask me how it works but its pretty rad ;), @paulinus can tell you more about it.

![screenshot 2016-08-04 18 05 20](https://cloud.githubusercontent.com/assets/268859/17423226/17d0b1e2-5a6e-11e6-8f28-ec99b299e2db.png)

**Comment by paulinus** [comment]
With the current reconstruction method that [ignores sky and moving objects](https://blog.mapillary.com/tech/2017/07/26/improving-3d-reconstruction-with-semantic-understanding.html) the navigation now works great for this sequence.
