### ISSUE TITLE
Sequence Editor not loading in browser

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#2139]
### Basic information
- Platform:  `Web`
- System/Browser: `Mac OS X El Capitan 10.11.6 tested in Safari, Chrome, Firefox and Opera`
### Steps to reproduce behavior
1. Log into Mapillary account
2. open https://www.mapillary.com/app/index/skippern?lat=-20.93870214199997&lng=-41.08283129500212&z=17&pKey=DUxTvfkH0snZ4YjYgV9a-w
3. Edit sequence
### Expected behavior

Sequence editor loads
### Actual behavior

Browser tab freezes without loading editor options. `Exit Editor` button not reacting, paying map not working, selecting different image in sequence not working. Reload page returns to page before selecting `Edit Sequence`
### Additional information

Most sequences work (i.e. all my sequences north east of this one).

**Comment by nickplesha** [comment]
This should work now regardless of the size of the sequence. Thanks for reporting!
