### ISSUE TITLE
Compatibility with MS Edge browser

### ISSUE THREAD

**Issue by rausk** [mapillary/mapillary_issues#2140]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: MS Edge

### Steps to reproduce behavior

 1.  Go to Leaderboard
 2. Eg. Italy
 3.

### Expected behavior

All 50 top contributors are shown

### Actual behavior

WithMS Edge browser only few or no contributors are shown. Sometimes the map is loading endlessly.

### Additional information

Behavior with Firefox browser is OK.

**Comment by knikel** [comment]
@rausk: Is this still an issue for you?

**Comment by rausk** [comment]
Not at the moment, since I killed Win10 on my PC. It was very unstable.
