### ISSUE TITLE
Back button in Leaderboard not working

### ISSUE THREAD

**Issue by rausk** [mapillary/mapillary_issues#2141]
### Basic information
* Platform:  `Web`
* Version: `...` 
* System/Browser: `Win10, Firefox`

### Steps to reproduce behavior

 1. Go to Leaderboard
 2. Select a Country, wait for display of contributors
 3. push BACK button

### Expected behavior

Go back to last window

### Actual behavior

Nothing happens 

### Additional information

BACK button on top Level is working

**Comment by gyllen** [comment]
This is now fixed.
