### ISSUE TITLE
Photos uploaded, not published

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2144]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Open the uploader.
 2. Select, review, upload and publish a sequence of photos.
 3. Wait indefinitely for the confirmation email.
 4. Open the uploader again.
 5. Notice a message at the bottom of the screen, "Publish xx uploaded".
 6. Press the button and get confirmation that files have been published.
 7. Exit the uploader.
 8. Repeat from step 4. 

### Expected behavior

If you get a message that photos have been published, then I expect that to be the truth. If there is a failure, then I expect a message telling me that.

### Actual behavior

The photos aren't being published. They remain in the staging area.

### Additional information

I have to press the "Delete all" button to get rid of the "Publish xx uploaded". Elsewise the publish button will be back next time the uploader is opened.

This happens even with very small sequences, I've had it happen with 4 photos in a sequence. So it doesn't seem like this is because it's not finished processing yet.

This happens on the majority of my uploads, but not all.

Sometimes, when I re-upload the sequence several times, suddenly the sequence is correctly published.

If I open the uploader in another browser, then I also get the message that uploaded photos are waiting to be published. So they are not stuck somewhere in a browser cache, they are actually on the server.

**Comment by gyllen** [comment]
@pbb72 Is this still an issue? When you press the publish button can you observe the console in the browser and see if you get any error messages? For me it looks like you are not beeing able to publish.

**Comment by pbb72** [comment]
I will check the console with my next upload. It seems that now, after a long wait, the publish button does disappear.

If this button is supposed to be an indicator that the site is still processing my upload, then the interface should be changed, because now it just looks like it's telling that I forgot to press Upload the last time.

**Comment by gyllen** [comment]
@pbb72 Im trying to figure out what the problem can be. You say this is when you press publish, that API call SHOULD return within milliseconds. There should be no heavy stuff going on.

To get some more info:
How big is the sequence?
Have you moved any images before you uploaded them?

**Comment by pbb72** [comment]
There are no console messages, and now the button disappears after returning several minutes later.

Maybe initially the servers were under so heavy load that it never seemed to disappear (even for 10-photo sequences).

I'll close this issue, but open another one that a button to indicate that the upload is still being processed, is a bad design choice. :-)

**Comment by gyllen** [comment]
Please do, thanks for the feedback!
