### ISSUE TITLE
Sequence-changeset seems not to be committed properly  - 500 Internal Server Error

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2145]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `ubuntu/chrome v52`, `ubuntu/firefox v47.0`

### Steps to reproduce behavior

 1. Klick on "edit sequence"
 2. Do some changes
 3. Commit changeset

### Expected behavior

Apply changeset.

### Actual behavior
After my recently commited changesets weren't on the map after 2 weeks I tried to commit them again. This time I had enabled the browsers developer console.

By this way I was able to detect a `500 Internal Server Error` on console every time I commit a sequence-changeset (after clicking "submit", see `Additional information` for more details). 

I tried this procedure with Firefox and Chrome (also in "private mode" to except plugins, cookie or cache related issues).

Strange enough there still appears a "Your edit request was created" message on the right user bar.

Sequences I tried to commit:

- m4EuMVDsQ-WFD0iYKlhVcw
- SYL2gGBzlLn2Tq01zvQVyg
- ROtotejqgjb5TeuOnAuvNw
- zDjhMAjCm6s3tW838BIUWg
- BgF6tJx8-qUIBR8JcrsgUw
- ...

### Additional information

Request Header Chrome:

```
POST /v3/model.json?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh HTTP/1.1
Host: a.mapillary.com
Connection: keep-alive
Content-Length: 774314
Authorization: [REMOVED]
Origin: https://www.mapillary.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: https://www.mapillary.com/app/index/descilla?lat=51.086975851836996&lng=6.241981100164736&z=20&pKey=_9Ac87jtE-wr_QYb-KLX9Q
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
```

Response Header Chrome:

```
HTTP/1.1 500 Internal Server Error
Server: openresty/1.9.3.2
Date: Tue, 02 Aug 2016 00:53:55 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 21
Connection: keep-alive
ETag: W/"15-o0ciPJjoRnzWERJn2G2v8w"
X-Powered-By: Express
```

---

Request Header Firefox:

```
POST /v3/model.json?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh HTTP/1.1
Host: a.mapillary.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: [REMOVED]
Content-Type: application/x-www-form-urlencoded
Referer: https://www.mapillary.com/app/index/P6Vup05drQEsyeTq8qTKQz?lat=51.08612099999999&lng=6.236211999999995&z=17&focus=map&pKey=9r2qYzJ5Bqa5ZL5gFqLKbQ
Content-Length: 774304
Origin: https://www.mapillary.com
Connection: keep-alive
```

Response Header Firefox:

```
HTTP/1.1 500 Internal Server Error
Server: openresty/1.9.3.2
Date: Tue, 02 Aug 2016 01:04:37 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 21
Connection: keep-alive
Etag: W/"15-o0ciPJjoRnzWERJn2G2v8w"
X-Powered-By: Express
```

---

Screenshots:

![mapillary-edit-error7](https://cloud.githubusercontent.com/assets/1118916/17314019/4ae98be4-5861-11e6-9a39-508f63de8f73.png)

![mapillary-edit-broken-2](https://cloud.githubusercontent.com/assets/1118916/17314014/3e83ed4a-5861-11e6-9229-30fedd7fb8e3.png)

![mapillary-edit-error-6](https://cloud.githubusercontent.com/assets/1118916/17314022/54daa3fe-5861-11e6-8a29-f4e5ab58de5e.png)

![mapillary-edit-error-3](https://cloud.githubusercontent.com/assets/1118916/17314034/6b2e1ef6-5861-11e6-8681-61413947dcf6.png)

**Comment by gyllen** [comment]
@descilla We are still working through a huge backlog of changesets the reason that it does not appear on the map yet is probably that we have not yet approved it. you will be notified when we have approved. Opening this as a bug though since the 500 looks strange.

**Comment by gyllen** [comment]
This should now be fixed (no more 500s), also we are still working through the changesets. Exepct approve emails very soon.
