### ISSUE TITLE
Editing picture position during upload resets direction to 0

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2146]
I just noticed that pictures that I edited the position of while reviewing before upload are all pointing straight north instead of maintaining their original direction information. I don't see any way of specifying direction during. 

Example: https://www.mapillary.com/app/user/toebee?pKey=Wkyi4kzVB-qb4jkNEhPG_Q

The next picture in the sequence is unedited and correctly faces west.

**Comment by gyllen** [comment]
@ToeBee Thanks for reporting, we are fixing this as fast as we can

**Comment by retro** [comment]
This was fixed in one of the recent releases. Please reopen this issue if you encounter this bug again.
