### ISSUE TITLE
https://opendata.mapillary.com/ invalid HTTPS cert as of 02.08.2016 2200 +1000 UTC

### ISSUE THREAD

**Issue by stevenvandervalk** [mapillary/mapillary_issues#2149]
### Basic information
- Platform: `iOS` | `Android` |`Web`
- System/Browser: `OS X 10.11.6/Chrome Canary`
### Steps to reproduce behavior
1. Open https://opendata.mapillary.com/
2.  See big scary cert warning

I assume you know the rest.

**Comment by gyllen** [comment]
@octanebaby Should we try to move this guy to static pages?

**Comment by octanebaby** [comment]
we should try to move this AND edu.mapillary.com to static pages.

**Comment by gyllen** [comment]
@octanebaby Adding issues

**Comment by nickplesha** [comment]
This page has been deprecated and removed.
