### ISSUE TITLE
Low zoom coverage doesn't match actual coverage

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2150]
When using the new "Show my coverage only" option in my user profile, there is a break at zoom 6. Some of my traces are not displayed at zoom levels 1-5 but start showing up at zoom 6. I know low zoom stuff is often cached but I noticed this on traces from a trip down to Florida missing between St. Louis and Nashville. I uploaded these pictures over a year ago. 

Here is a screenshot at zoom level 5.9:
![image](https://cloud.githubusercontent.com/assets/348948/17338111/805873cc-58ab-11e6-8e53-9bcdc04ae584.png)

And when I zoom in one more level to zoom level 6.2:
![image](https://cloud.githubusercontent.com/assets/348948/17338160/c56a2b54-58ab-11e6-8123-22df31f1a70d.png)

**Comment by gyllen** [comment]
@ToeBee Higher zoom levels are not updated as frequently as lower ones. It usually takes a couple of hours to update. Report back in a day or so to see if it has started to appear.

**Comment by gyllen** [comment]
High = 0-6
Low = 6-INFINITY

**Comment by ToeBee** [comment]
Well like I said, these are traces that were uploaded over a year ago. Example picture that isn't showing up in z0-5: https://www.mapillary.com/app/?pKey=mHgz4Td0f6MGmZ6Ee_50Xg&focus=photo

**Comment by gyllen** [comment]
@ToeBee Aha! I did not read the last part of the sentence :/, I will submit this as a bug to the tiler.

**Comment by ptpt** [comment]
Hi @ToeBee thanks for the input.

At high levels from 0 to 5, we use the dot layers (we also call it overview layer) to present sequences. Each dot (a 16x16 pixel area) is covered by the latest captured sequence in that area. All older sequences are evicted.

In this case, your sequence was covered by a newer one by allen (See https://www.mapillary.com/app/user/allen?pKey=Ydexroe2OL2WPd5oGIw_cg&focus=map&lat=38.248344697723326&lng=-88.31167606468333&z=5.456303914051019). If you click to show allen's coverage only, these areas will show his sequence as it is the latest captured sequence in that area.

This is a limitation of our static vector tiles for the moment, as it is unrealistic to put all sequence into tiles, which will make file sizes unacceptable. A workaround might be go there and occupy those pixels again :) Long term solution is to provide a dynamic tile service, or serve static tiles for each users. I will discuss with @gyllen about this.

/Tao

**Comment by ToeBee** [comment]
Ah, I was kind of wondering how you were doing those zoomed out views with decent performance. I guess this explains it. This might take more processing than is worth it but for long sequences along the same road you could maybe interleave dots so more than just one person along the route gets dots "assigned" to them.

I guess it's time to go visit my brother in Florida again.

**Comment by gyllen** [comment]
Im gonna close this for now. Thanks for explaining this @ptpt , we will do some `deep thinking` on how todo tiles more performant.
