### ISSUE TITLE
Hiding profile panel causes "Show my traces only" toggle to forget state

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2151]
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 51`

### Steps to reproduce behavior

 1. Enable `Show my traces only` option in the profile panel
 2. Collapse the profile panel
 3. Re-open the profile panel and navigate back to the `Uploads` tab

### Expected behavior
What is showing on the map should match the toggle state.

### Actual behavior
The `Show my traces only` toggle appears to be disabled but the map is still only showing my traces.

**Comment by angelday** [comment]
@ToeBee we released Filters which basically sets "your traces only" as a filter. Does this resolve your issue?

**Comment by ToeBee** [comment]
Yes, this seems to be working correctly now.
