### ISSUE TITLE
Confusing button to indicate upload is still being processed

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2152]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Open the web uploader.
 2. Select, review, upload and publish a (large) sequence of photos.
 3. Exit the uploader.
 4. Open the uploader again.

### Expected behavior

A clean uploader page, nothing special should be there.

### Actual behavior

 5. See a button on the bottom of the page, "Publish xx uploaded".
 6. Scratch head, think "I did publish that sequence, didn't I?"
 7. Click publish button again.
 8. Exit uploader, open uploader again, and see button is there again.
 9. Wonder if I am going crazy, or if there are problems at the server.

### Additional information

There's not really any reason to tell us the upload is still being processed. But even if you do want to provide that information, a button is the wrong layout element to use. Now it looks like we need to interact to get the sequence published, while it will be published also if we don't do anything.

**Comment by gyllen** [comment]
@pbb72 I actually do think that this is a matter of that the publich actually does not publish. I have heard reports of something similar during the day. A small code refactoring of the uploader component is on the way. This will probably solve this issue. I will report back.

**Comment by pbb72** [comment]
I've tried it several times now recently, the publish button is always there when I re-open the uploader immediately after an upload. And when I open the uploader again after several minutes, the button is gone, and I receive an email that the upload was successful.

**Comment by pbb72** [comment]
OK, there is more to this. Now I haven't uploaded anything in a few hours, I open the uploader, and there is a button "Publish 1 uploaded". I did not upload any single-image sequence. No comments in the console, except for geometry exceeding allowed extent (which I assume has nothing to do with uploading).

**Comment by gyllen** [comment]
@pbb72 Uploader is now refactored. Try it out and open new ticket for any errors you find and lets do this loop again ;)

A question do you ever use scripts to upload images?

**Comment by pbb72** [comment]
Here you go: #2157 

No, I am not using the upload scripts. I am using the interpolate_direction script because the online editor has been non-functional for almost a year. (And edit requests are currently still not executed.)
