### ISSUE TITLE
Sequence showing in a broken way

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2153]
Here is a sequence, but some picture dots are not showing and navigation is not working. But the pictures are there and when using the step by step navigation at the top it works.

Is this just a new twist of things taking time to show up on the map or is there  something else going on?

https://www.mapillary.com/app/?focus=photo&pKey=szyy6qON-7mGfMqxfjdK1g&lat=59.34122&lng=18.084051&z=17

**Comment by ptpt** [comment]
Hi @Andblue I'm sorry about this. It is an issue with our tiler. I just rendered the broken sequence; it will show up soon hopefully (when it delivers to CDN).

At the time (Sunday) this sequence got uploaded, the tiler was not working properly. So these tiles were missing.

**Comment by Andblue** [comment]
Great!

**Comment by gyllen** [comment]
Looks to me that the sequences are now showing up. Closing. Thanks for debugging this @ptpt
