### ISSUE TITLE
Some images do not show preview popup on hover event on minimap

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2154]
### Basic information
* Platform: `Web`
* Version: `Chrome Version 51.0.2704.106 m (64-bit)`
* System/Browser: `Win 10 Enterprise`

### Steps to reproduce behavior

 1. Hover over photos on the minimap
 2. Some do not show pop-up (could be those around the center)

### Expected behavior

Hover over any dot shows pop-up

### Actual behavior

Pop up not working for some.

### Additional information

Demo of issue
![animation 4](https://cloud.githubusercontent.com/assets/1827881/17444043/e25cd934-5b0b-11e6-9afd-b3f7fe65bd01.gif)

**Comment by gyllen** [comment]
Thanks for resporting, this issue is tracked and will be solved in upcoming deploys.

**Comment by nickplesha** [comment]
@talllguy A part of the small window was blocking interaction with the mini-map. This was fixed a while ago, sorry for not getting back to you sooner. Thanks for reporting!
