### ISSUE TITLE
I can't load any photos atm

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2155]
The little thumbs work and `thumb-320.jpg` files are being downloaded. In the window in the left bottom and in the photo view I only see a dark background and a spinner and nothing is downloaded.

**Comment by ybkuang** [comment]
@de-vries We have a database issue. Working on it.

**Comment by pbb72** [comment]
Seems like everything is fine again now :)

**Comment by gyllen** [comment]
Yeah data is flowing in the system again, thanks for reporting. We made an extremly large query to our database which caused instabillity.

Closing
