### ISSUE TITLE
"Publish xx uploaded"

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2157]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome, Firefox`

### Steps to reproduce behavior

 1. Upload a long sequence (843 photos).
 2. Go to bed while the photos are being uploaded.
 3. Return the next morning to see the upload was successful, click the publish button.
 4. Exit the uploader, and open it again.
 5. Find a button on the bottom of the screen "Publish 843 uploaded".
 6. Exit the uploader, wait several minutes, and open it again.
 7. Find a button that says "Publish 12 uploaded".
 8. Exit the uploader, and open it again.
 9. Find no more publish button.

### Expected behavior

I don't know what to make of it. It seems like this is a progress notification ("There's xx photos left in the publish queue") but that should not require any interaction (it shouldn't be a button) and we users don't even need to see it.

If this button is shown because the system requires some action from the user, then it is not functioning as excepted, because pressing the button doesn't do anything. (The button disappears after pushing it, but is there again when re-opening the uploader.)

**Comment by gyllen** [comment]
@pbb72 Im trying to wrap my head around the issues that you have with the uploader. So in addition to web upload do you also use scripts?

**Comment by gyllen** [comment]
Ok just saw your answer in #2152, will foward this for further investigation.

Concerning changesets we are starting to approve but working us slowly through a giant backlag (and finding some issues along the way). So expect your changesets to be approved very soon.

**Comment by retro** [comment]
This was fixed in one of the recent releases. Please reopen this issue if you encounter this bug again.

**Comment by pbb72** [comment]
Confirmed, I don't see the button anymore :-)
