### ISSUE TITLE
Local leaderboards don't scroll

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2158]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome`

### Steps to reproduce behavior

 1. Open the global leaderboard (Left menu > Leaderboard).
 2. Notice how you can scroll through the list.
 3. Enter a location name in the search box.
 4. Notice how you can't scroll the list anymore.

### Expected behavior

Scrolling shows the lower parts of the leaderboard list.

### Actual behavior

Nothing happens when trying to scroll.

**Comment by nickplesha** [comment]
Thanks for catching this @pbb72! Scrolling should now work in all tabs and sidebars.

**Comment by pbb72** [comment]
Confirmed, thank you!
