### ISSUE TITLE
add a "fit to screen" button for the image viewer

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2159]
in the new website, it is possible to zoom in the images - which is great. but the images can also be panned, and to get the image back to "normal view", it is not enough to zoom out as much as possible.
it would be great to have a button for that (and maybe a keyboard shortcut, too ?)

the operation would fit the image to the display area and centre it perfectly.

**Comment by gyllen** [comment]
@angelday Can you explain our thoughts on this.

**Comment by angelday** [comment]
If I understand you correctly, you would like to see some kind of a mechanism to reset the view. If that's the case, we'll have a solution for you.

**Comment by richlv** [comment]
yes, pretty much - just getting full image in view, perfectly centred :)

**Comment by angelday** [comment]
@richlv We have some kick back effect in place now, closing.
