### ISSUE TITLE
App and portal side issues 

### ISSUE THREAD

**Issue by Akaveeti** [mapillary/mapillary_issues#2165]
Version : 2.37
App side 

1) After uploading profile picture on the web, can't see profile pic in the app . It showing empty.

2) In case we take more than 3500+ pics.it's take to more than 1 minute  time to open that pictures. 

3) In case by mistake deleted one good pic,want again that picture now it is not possible to restore so please provide undo option.

4) I start one place to take pics in case in that place already covered in last time take somebody  (so please provide Mapillary already take this location ) or please provide a small popup like " this area already covered by ------ and please check that pics quality and continue or please continue old member pics is not quality like this. Because many persons covered same places many times so , you have a waste of space on your server. 

5) In Explore option have provided cancel button.Because in case if I open explore its take to time for that loading so in case I want to cancel in that site no option there.

6) In profile - showing recent sequence actually that is a bug. In profile have please provide these 
a) name
b) age
c) email
d) address 
e) picture upload, edit, remove , save
f) change the password 
g) reset , save , update 

7) In logout - click on logout app will be close automatically this is a BUG.correct way is after click on logout app want to go login to the page without any credentials.

8) After log out open that app it's connected and log in to the recent user automatically.we have no choice to log in another new user .

9) Please fix Logout option in very last.

10) please provide google account also for login in the login page.

11) Assume In review sequences have 200 photos, scroll to 120 images ( mobile using without rotating ) , now mobile rotate and check, here showing a list of 1st images every time.

12) After wifi connected not update that user recent details automatically.

13) In street viewing time some faces,number plates showing normally.

In Portal :

1) After login in Feed , uploads have provided scroll bar it not showing the scroll bar.

2) After login in the project, options page has " chose a project " name is fixed in the middle of the box. 

3) After logging in profile settings clicked on that " send me instruction " not received any mail .

4) I uploaded some photos in last week through a web portal , on this day that photos are not published. I'll try to reupload that same photos it showing this popup  " photos have already been uploaded and await publishing " . I just click on that publish photos it's showing " 88 files have been published for processing. You will get an email when the photos are live on Mapillary. Meanwhile, you can upload more if you want. " but am not getting any email and photos is not published how many days it takes to time for that  upload.

Suggestions:

1) please provide identity card for every user. Because some places have very danger to take this type of taking pictures.
## 

Regards 
Nataraj Akaveeti

**Comment by katrinhumal** [comment]
@Akaveeti thanks for your extensive feedback! We've done a lot of updates since then and some of the things you have mentioned are still under discussion for further improvements. Closing this for now.
