### ISSUE TITLE
Bulk uploading images Taken less than a second apart

### ISSUE THREAD

**Issue by kertase** [mapillary/mapillary_issues#2166]
Hello,

So I have been trying to upload pictures in bulk by adding missing tags with: https://github.com/mapillary/mapillary_tools/blob/18e7c953bad4a6b615f499b5e177df9c120e52ef/python/add_mapillary_tag_from_exif.py .

I have the following issue, the pictures have been taken about half a second apart but the script requires the DateTimeOriginal (even thought the doc says otherwise) which is then used by Mapillary to sort the images in the right order when uploaded I guess.

The problem is that the tag DateTimeOriginal does not accept times under a second so to images land on the same second which leads to wrong sorting by Mapillary.

So there would be a few questions to answer:
• Can Mapillary filter images based on the GPStime tag? 
• Does Mapillary manage time under a second?
• If it Mapillary does, would it be possible to upload the images by simply correcting the script without adding the DateTimeOriginal tag or are there other things in play?

**Comment by kertase** [comment]
So after more analysis the problem seems to come from the upload script that does not load the milliseconds from the GPSTime Tag. So I copied those to the SubSecTimeOriginal tag which does not seem to be read correctly either since it does not get add to "MAPCaptureTime": "2016_05_04_13_11_11_000"

So basically I am having the following issues in add_mapillary_tag_from_exif.py
1. When Not having DateTimeOriginal tag but one of the other time tags(for exemple GPSDate and GPSTime) the script does not work,
2. SubSecTimeOriginal does not get used for "MAPCaptureTime" so Pictures taken less than a second apart cannot be sorted correctly

**Comment by kertase** [comment]
In line [166 of exif.py](https://github.com/mapillary/mapillary_tools/blob/18e7c953bad4a6b615f499b5e177df9c120e52ef/python/lib/exif.py#L166)  `capture_time = capture_time + datetime.timedelta(seconds=float(sub_sec)/1e6)` the sub_sec gets divided by 1⁶.

 I am not sure but as I understood it it does not indicate microseconds (see http://www.imagekit.com/IK9Help/source/controlreference/imagekitcontrol/file/exif/propertysubsectimeoriginal.htm) the SubSecTimeOriginal tag gives the fraction of seconds so 0.1 seconds would give 1 SubSecTimeOriginal and 0.12s, 12 SubSecTimeOriginal. 

So the line should be `capture_time = capture_time + datetime.timedelta(seconds=float(sub_sec))`

**Comment by ybkuang** [comment]
@kertase Thanks for pointing this out. I think it is a bug there. Your fix look good. Would you like to do a pull request on this?

**Comment by kertase** [comment]
Made a pull request for this

**Comment by blaueente** [comment]
I also agree this is a bug. cf. comment on https://github.com/mapillary/mapillary_tools/commit/508ec70fd0b4fc8eb33fdeb3aefbd728dc40028a
I should better file a bug next time ;-)

**Comment by gyllen** [comment]
@ybkuang Can we close?

**Comment by kertase** [comment]
I suppose so…
