### ISSUE TITLE
"Discard" and "Review" in editor lead to same result

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2169]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Open the sequence editor.
2. Make some changes.
3. Click the "Discard xx changes" button.
4. Note the "You made xx changes to a sequence" dialog.
5. Click the "X" to close the dialog.
6. Now click the "Review xx changes as a new changeset" button.
7. Notice that you get the same dialog.
### Additional information

It seems to me that the confirmation/review dialog with photo IDs and change parameters is really only interesting for debugging purposes, don't think any normal user will spot their mistakes in that list.

I would say that submitting doesn't require an additional review step, so the Review and Submit action can be reduced to a single Submit. Discarding however should get a confirmation, but that should just be a simple "Are you sure you want to discard xx changes? Cancel / Discard" dialog.

**Comment by gyllen** [comment]
@angelday I know this is by choice, feel free to argue for your case and close this issue if no action will be taken.

**Comment by angelday** [comment]
> I would say that submitting doesn't require an additional review step, so the Review and Submit action can be reduced to a single Submit.

@gyllen if we're not afraid that users are experimenting and submitting false changes by accident we might as well just remove it

**Comment by gyllen** [comment]
@angelday I think maybe the list is a bit TMI?

**Comment by angelday** [comment]
Could be.

**Comment by angelday** [comment]
Discarding changes should discard them immediately. I'll file this as a bug.

_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
