### ISSUE TITLE
Multiselect for changing image angles in a sequence

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#217]
I know there is a "Correct image angles" button, but sometimes the sequence is very long and turns corners. It would save a lot of time if you could select 3,4,5,... images in a sequence and orient them all at once instead of going one by one

**Comment by knikel** [comment]
Adding as a feature request for the upcoming version of the editor.

**Comment by nickplesha** [comment]
Image compass angles can be "normalized" for the whole sequence simultaneously in the web editor now.
