### ISSUE TITLE
Can't change direction of multiple images individually

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2170]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Open the editor.
2. Notice all photos in the sequence have a blue icon, and the "current" photo an orange one.
3. Select another photo, and notice how this one gets an orange icon.
4. Enter a new compass angle, and click "Set".
5. Notice how not the currently selected (orange) icon rotates, but the one that was originally selected.
### Additional information

This makes it impossible to change the direction of multiple individual images, something that is often required after doing a change for the whole sequence.

**Comment by nickplesha** [comment]
This should be fixed now, thanks for reporting!
