### ISSUE TITLE
Simple script Using MapillaryJS CORS error

### ISSUE THREAD

**Issue by RobyRemzy** [mapillary/mapillary_issues#2172]
Hi, i was testing the example from `https://github.com/mapillary/mapillary-js`

```javascript
<head>
    <script src='https://npmcdn.com/mapillary-js@1.6.0/dist/mapillary-js.min.js'></script>
    <link href='https://npmcdn.com/mapillary-js@1.6.0/dist/mapillary-js.min.css' rel='stylesheet' />
</head>

<body>
    <div id='mly' style='width: 640px; height: 480px;' />

    <script>
        var mly = new Mapillary.Viewer(
            'mly',
            '<your client id>',
            '<your photo id for initializing the viewer>'
        );
    </script>
```
On a Jekyll HTML template:
when open on localhost or on [GitHub pages](http://robyremzy.github.io/2016/mapillary-post-view/) i've got the dynamic picture, but when i click on the button Explore, it's doing nothing: "on FF and Chrome" see there from this live example hosted on [GitHub](http://robyremzy.github.io/2016/mapillary-post-view/) with a valid `client_id` and `photo_key`.

![screeshot](https://raw.githubusercontent.com/RobyRemzy/robyremzy.github.io/master/images/tmp/mapillary-cors.png) 
  
console message:

```
https://a.mapillary.com/v2/nav/im/_a0bk6u_qhYPQ4lup9dysw?client_id=enpzOU5oNGZIQW1NLTI0T2JrdGFmQTo4MzU4YjE4ZTcwMjVmY2Y5sss Failed to load resource: the server responded with a status of 401 (Unauthorized)

robyremzy.github.io/:1 XMLHttpRequest cannot load https://a.mapillary.com/v2/nav/im/_a0bk6u_qhYPQ4lup9dysw?client_id=enpzOU5oNGZIQW1NLTI0T2JrdGFmQTo4MzU4YjE4ZTcwMjVmY2Y5sss. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://robyremzy.github.io' is therefore not allowed access. The response had HTTP status code 401.

mapillary-js.min.js:19 Uncaught 
```
it's seems to be a bad (Cross-Origin Request) with Access-Control-Allow-Origin » missed.

Do you guys disable that on purpose or i missed something?

**Comment by gyllen** [comment]
@RobyRemzy It looks to me that you do not have a valid client_id. Have you created one in settings?

**Comment by RobyRemzy** [comment]
ow indeed! i was using a client_id for an other github page! i was confused about the purpose of the client_id but in fact it's better to do like this, very well thank you @gyllen to point out this to me, my problem is solved, see the working example (probably delete in a few days tho) at http://robyremzy.github.io/2016/mapillary-post-view/

**Comment by gyllen** [comment]
@RobyRemzy This looks great. Would you be up for making a guest blogpost on our blog about this?

**Comment by RobyRemzy** [comment]
@gyllen yes i would be glad to do that, how can we work on that? thanks

**Comment by gyllen** [comment]
Awesome @katrinhumal can we set something up here.

**Comment by katrinhumal** [comment]
Sure! @RobyRemzy I will put together a few guidelines to help get you started. Can you meanwhile send me your email contact to katrin@mapillary.com?
