### ISSUE TITLE
Hard to tell why sequence capture has stopped

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2175]
If capture sequence is stopped due to disk threshold or battery (and perhaps other reason) it is hard to tell why.
A message is flashed on the screen but if the user does not look at screen within that timeframe it is impossible to know that capture is aborted.

Possible solution:
Make the message stay on screen.

**Comment by rsahlin** [comment]
Duplicate to #1515

**Comment by ovivoda** [comment]
This issue should be fixed in the latest version of Mappillary Android application
