### ISSUE TITLE
Power usage significantly higher in Android app version 2.37 in camera mode (even when not taking pics)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2176]
### Basic information
- Platform: Android
- Version: 2.37-jakkooh
- System/Browser: 6.0.1
- Phone:  Samsung Galaxy S7 Edge
### Steps to reproduce behavior
1.  (optional)  Run your phone battery down pretty low for fun.
2.  Plug phone into a good car charger (cigarette lighter port).  I use Anker.
3.  Reboot your phone
4.  Use the phone's switcher feature to ensure that all apps are closed.
5.  Disable Wifi and Bluetooth if you want to.
6.  Start Mapillary.
7.  Enter Camera mode.
### Expected behavior

Battery charge stays even or increases.  This is how previous versions behaved.
### Actual behavior

Watch the battery percentage.  Over time, it should decrease slowly.  Start shooting sequences for slightly faster battery drain.
### Additional information

With previous versions, I could make an 8 hour car trip and have a full battery at the end, even with other apps running (e.g., on my Mapillary phone, I often run Waze in the background so I know about traffic issues coming up, but generally use OsmAnd on another phone for primary navigation).  With 2.37, my battery is completely drained after about 5 hours (give or take).

I will note that I still have the crash-out-of-camera-mode issue where I have to disable/reenable Camera2 API before I can use Mapillary again, so it may be that there are orphaned threads left running in the background that are using even more power than would otherwise be the case.  Even so, the battery drain still happens with a freshly rebooted phone.

**Comment by rsahlin** [comment]
Thanks for reporting @jfburke3 

My current focus is battery usage and performance, I am working on a first version that does not generate thumbnails at runtime.
This should lessen battery usage somewhat, after this release I will rewrite the Camera UI to make it more optmized.

Is there a github issue for the crash-out-of-camera-mode?
If not could you please create one with attached logs, I would like to fix this one.

Best regards
/Richard

**Comment by jfburke3** [comment]
Yes, the crash-out-of-camera-mode is github issue 2108. [https://github.com/mapillary/mapillary_issues/issues/2108](url)

**Comment by rsahlin** [comment]
Hi @jfburke3 

But #2108 is Pause on stop not working :-)

Best regards
/Richard

**Comment by jfburke3** [comment]
Ugh.  I confused myself with too many tabs open.

It's #1934  https://github.com/mapillary/mapillary_issues/issues/1934

**Comment by jfburke3** [comment]
Just a note to say that power drain is still high enough in 2.39 to bring my battery down while plugged in to power.  (Not expecting a reply, just reporting.)

**Comment by peterneubauer** [comment]
Closing. Too old.
