### ISSUE TITLE
naviation buttons are disappearing in sequence view in portrait view

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2177]
### Basic information
* Platform: `iOS`
* Version: `4.4.8` 
* System/Browser: `iPhone 6s`

### Steps to reproduce behavior

 1. Tap on sequence on map or select sequence from "profile"
 2. (after "view" is updated) Rotate phone from portrait to landscape.
 3. Tap on arrows at the top (left or right).

### Expected behavior

Arrow controls should be still available/visible.

### Actual behavior

The controlbar at the top disappears after using them once.

### Additional information

This appears in landscape mode only.

![photo-2016-08-11-01-02-39_0808](https://cloud.githubusercontent.com/assets/1118916/17574579/ca669d96-5f62-11e6-88fa-2d5daf75b238.PNG)
![photo-2016-08-11-01-02-43_0809](https://cloud.githubusercontent.com/assets/1118916/17574580/ca722c7e-5f62-11e6-916c-ce3a3ae5bc87.PNG)

**Comment by millenbop** [comment]
Thanks for reporting, fixed in next version, 4.5.1.
