### ISSUE TITLE
make blur work left/up, too

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2178]
the previous blur editor allowed drawing the rectangle in all directions, the new one only right & down.
please make it possible to draw it in all directions.
i'm sorry if this is a duplicate, but i searched and searched and could not find an existing issue.

**Comment by de-vries** [comment]
It's a bit hard to find but here it is: https://github.com/mapillary/mapillary-js/issues/163

**Comment by richlv** [comment]
oh, so that's a different project now... will have to keep that in mind :)
thanks, closing this one.
