### ISSUE TITLE
Logout from Facebook not working

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2181]
In logout - click on logout app will be close automatically this is a BUG.correct way is after click on logout app want to go login to the page without any credentials.

After log out open that app it's connected and log in to the recent user automatically.we have no choice to log in another new user .

**Comment by ovivoda** [comment]
This works good on 

http://android-releases.mapillary.io/Mapillary_Android_v3.99-SNAPSHOT1.apk
