### ISSUE TITLE
Pause on stop does not work in Time based Automatic mode

### ISSUE THREAD

**Issue by rausk** [mapillary/mapillary_issues#2182]
### Basic information
* Platform:  `Android` 
* Version: `4.4.2` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. check box Pause on stop
 2. select Automatic mode, Time based
 3. Start sequence while driving, then stop car

### Expected behavior
no further photos are taken
...

### Actual behavior
more photos are taken
...

### Additional information
Because of the bad colour scheme in Settings (Grey, White, black), you can hardly decide whether you have selected the feature or not.
...

**Comment by rsahlin** [comment]
Hi @rausk and thanks for reporting

The setting 'Pause on stop' was connected to driving mode - this mode has been removed and is now replaced by distance based capture mode.
Please use this mode instead while driving.

We will be looking into the UI design in the future.

Best regards
/Richard
