### ISSUE TITLE
Please allow low max tilt setting

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2183]
### Basic information
* Platform: `Android`
* Version: `2.37` 

### Steps to reproduce behavior
 1. Go to settings
 2. Select "Max tilt in degrees" setting
 3. Move the slider to the left

### Expected behavior
The slider can be moved to value 0

### Actual behavior
The slider cannot be moved to values lower than 20

### Additional information
Regression from previoius version

**Comment by kaitu** [comment]
Just checked Version 2.38; the issue is still there.

This problem, combined with #2193, resulted in a photo session producing way more unwanted shots than useful ones.

**Comment by rsahlin** [comment]
Hi @kaitu and thanks for reporting

Why do you want the value to be able to be less than 20 degrees?
Is it due to images captured being tilted - if so could you please point me to such an image?

Best regards
/Richard

**Comment by kaitu** [comment]
Main reason, a pretty personal, I provided in #2193. Furthermore, I often shot in environments without clear horizontal or vertical reference. At times, with the camera held at odd angles away from my body, I therefore find it difficult to understand when the camera is levelled. The debug information offers tilt angle reading on the screen, but the character is so small that I cannot read it. Not without glasses, and never under direct sunlight anyway. I find the tilt angle limit extremely handy: just slowly rotate the camera untils is shots, works wonderfully (well, not so well in noisy environments, when I cannot hear the shot, and have no other clear indication that a picture has been shot; but this is matter of a different issue). I tipically set the tilt angle to 2-3 degrees with phone on a mount, and to 1 degree when I hold it directly in my hands. 

A big plus would be an additional clear on screen indication of the verse I should rotate the phone to level it, as in field operation even this is difficult to understand (related to #688).

**Comment by rsahlin** [comment]
Hi @kaitu and thanks for the explanation

Now I understand the problem at hand and will keep it in mind when looking into #2193 
Please be patient.

Best regards
/Richard
