### ISSUE TITLE
Need a space photo view instead map option for photo review location screen

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#2184]
In web uploader after image uploaded is an option to precise image location.
Need a photo view option for photo review location screen. 
Sometime map have no landmarks to precise location, but photo have.

**Comment by gyllen** [comment]
@iav At the moment you can see the photo (a preview) before you upload the images. Have you seen that.

Its actually preferred to fix location before upload. We need to better explain that.

**Comment by iav** [comment]
Not a fix - I writing about upload photo via web browser on a desktop.
And ask kind of a google satellite to make more accurate position of a photo I want to upload. It means when gps in city between bug houses make a big errors.
And map often not have enough orienteers.

**Comment by gyllen** [comment]
@iav Aha yes I understand now. We will add the ability to switch to satellite maps for the editor, viewer and uploader. Will that help?

**Comment by iav** [comment]
Yes, it will, thank you.
