### ISSUE TITLE
Editor hungs up when I edit a sequence

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2186]
I try to edit the position of some pics in a sequence to be more accurate (e.g. I'm going by left lane but the GPS said right lane so I zoom map and try to move the pic to the left side of the road. Well, I have done it with 10 pics because...editor hungs up. When I retry to do it, exit Mapillary, reenter, I can move one and then editor rehang up it. I run Windows 7, latest Firefox 48. Chrome is not working due to WebGL issues.

**Comment by smsm1** [comment]
I often get similar issues on Mac OS X Firefox and Safari.

**Comment by retro** [comment]
@yopaseopor @smsm1 Can you send me the links to sequences that caused these problems? I did some internal cleanup and I want to make sure that it's not happening.

Thanks,
Mihael

**Comment by yopaseopor** [comment]
https://www.mapillary.com/app/edit/2fWTWVXd2Zxq4FySSFugtF?lat=41.23629567&lng=1.73339883&z=17&focus=map&pKey=nxza0BChbKY7Wkaje38ZZA << the sequence was that. I have tried to "order all the sequences" I have got in this motorway.

**Comment by yopaseopor** [comment]
I have the same problem in https://www.mapillary.com/app/?focus=map&pKey=5XsmwrKfADa-rxBGMRk6BQ&lat=43.35598130510752&lng=-5.853377611926078&z=19.369607517853648 . It is impossible to keep working with latest Firefox 48.0.2 and Win 7 (Chrome does not work no more due to false WebGL issue)

**Comment by smsm1** [comment]
Here is a video showing the flickering of the map and the editor becoming unusable. https://www.dropbox.com/s/uf9v5crjx2655kx/screencast%202016-09-03%2008-47-08.mp4?dl=0

This track I've had to submit as a series of small edits due to the editor hanging. https://www.mapillary.com/app/index/smsm1?lat=51.52015277777778&lng=-0.09394444444444616&z=17&pKey=jeHCrM2l7R7Fk5fCPvXTDQ&focus=map

**Comment by gyllen** [comment]
@retro See feedback above ^^^

**Comment by nickplesha** [comment]
This should be fixed now, thanks for reporting!
