### ISSUE TITLE
Delete photo icon in new uploader is hidden with white background

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#2187]
### Basic information
- Platform: `Web`
- System/Browser: `Firefox 47 on macOS Sierra public beta`
### Steps to reproduce behavior
1. Select a photo with a white (or close to) colour on the top right of the image and upload
2. Select the image in the review screen
### Expected behavior

To be able to see the delete button.
### Actual behavior

Unable to see the delete button. Screenshot.

![mapillary_-_crowdsourced_street_photos](https://cloud.githubusercontent.com/assets/82719/17648173/6256a1de-6204-11e6-9ab6-a559cba7c530.png)

**Comment by angelday** [comment]
I'll work on this.

**Comment by nickplesha** [comment]
This has been resolved using an icon background.
