### ISSUE TITLE
Mass editing of image locations

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#2188]
### Basic information
- Platform: `Web`
- Version: `image uploader/track editor` 
- System/Browser: `all`
### Steps to reproduce behavior

Sometimes images are offset from the road that they need to be be on, and it's better to adjust them all, however it's currently time consuming to manually edit large number of images.

It would be rather interesting to be able to mass edit the image, potentially even using a bezier curve editor to say between photo `a` and `z` adjust the photo positions based on the additional points `d`, `j`, `t,` and `v` using bezier curve logic.

**Comment by gyllen** [comment]
@smsm1 I agree on this. We do need to consider way to make the editor experience more smooth.

**Comment by fgouget** [comment]
Even being able to move a set of points in one go would be a big improvement, particularly when the images are just offset a bit. Even in other cases it could be used as a first pass to get them closer to their position, then leaving only fine (quicker) adjustments.

Moving a set of points requires selecting them. This could be done by clicking on the first point and then Shift+Click-ing on the last point, which would select all points from the first to the last one. Then dragging would move all the selected points in one go.

**Comment by gyllen** [comment]
@nickplesha Reassigning to you for decision.

**Comment by nickplesha** [comment]
This idea has been reported a few times and is on our list of future improvements for the uploader. We're tracking the issue internally so please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s complete.
