### ISSUE TITLE
Show bus stops/cycle parking on the map editor/uploader

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#2189]
Bus stops and cycle parking are rather useful for helping to improve the positioning of photos, could these be added to the high zoom maps in the uploader and map editor please?

**Comment by gyllen** [comment]
@smsm1 This are all information that is availble in OSM right. So ti would only be a matter for us to have another base map?

**Comment by smsm1** [comment]
Yes, all available in OSM.

Bus stops: highway=bus_stop and public_transport=platform https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop

Cycle parking amenity=bicycle_parking https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking

There may be other on street furniture that could be added, that may also help such as traffic signals and pedestrian crossing. It would also aid ensuring OSM is up to date.

**Comment by gyllen** [comment]
Awesome, do you know of any basemap that has all of these attributes?

**Comment by smsm1** [comment]
The main osm.org one? Though you'd possibly need to host the style yourself, if demand gets too high on the community resource. Source is available and designed to be customised https://github.com/gravitystorm/openstreetmap-carto

**Comment by gyllen** [comment]
We do now offer the ability to switch to OSM as basemap. If this does not solve your issue consider opening up a thread in https://forum.mapillary.com
