### ISSUE TITLE
Uploading through the new uploader stalls with EXCEPTION: 'pack' error

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#2190]
### Basic information
- Platform: `Web`
- System/Browser: `Firefox 47 macOS Sierra public beta`
### Steps to reproduce behavior
1.  Select a bunch of photos for upload
2. Position the photos correctly (several were out due to the urban canyon effect and tunnels/bridges)
3. Hit upload
### Expected behavior

All photos to upload successfully, and if there is an error on upload to allow the use to retry the upload, or give a list of file names which haven't uploaded, so that I can take that list and try the upload again with just those files. If the upload was sequential this wouldn't be as much a problem as I'd be able to go to photo x and select all photos in the local folder to the end of the folder to upload again, however it's discontinuous points through the train that are failing to upload.
### Actual behavior

A some point most of the way through several groups of photos have not uploaded an the following error is reported in the developer console.

```
EXCEPTION: 'pack' error. main-2baeaeb908cc396ee36e4adff439460e.js:11
EXCEPTION: 'pack' error. main-2baeaeb908cc396ee36e4adff439460e.js:11:12651
o</b.prototype.logError() main-2baeaeb908cc396ee36e4adff439460e.js:11
o</b.prototype.logGroup() main-2baeaeb908cc396ee36e4adff439460e.js:11
h</a.prototype.call() main-2baeaeb908cc396ee36e4adff439460e.js:54
b/<() main-2baeaeb908cc396ee36e4adff439460e.js:50
n</b.prototype.subscribe/e<() main-2baeaeb908cc396ee36e4adff439460e.js:51
j</b.prototype.__tryOrUnsub() main-2baeaeb908cc396ee36e4adff439460e.js:59
j</b.prototype.next() main-2baeaeb908cc396ee36e4adff439460e.js:59
i</b.prototype._next() main-2baeaeb908cc396ee36e4adff439460e.js:59
i</b.prototype.next() main-2baeaeb908cc396ee36e4adff439460e.js:59
l</b.prototype._finalNext() main-2baeaeb908cc396ee36e4adff439460e.js:59
l</b.prototype._next() main-2baeaeb908cc396ee36e4adff439460e.js:59
l</b.prototype.next() main-2baeaeb908cc396ee36e4adff439460e.js:59
n</b.prototype.emit() main-2baeaeb908cc396ee36e4adff439460e.js:51
a/this._zoneImpl<.onError() main-2baeaeb908cc396ee36e4adff439460e.js:50
a/this.inner<.onHandleError() main-2baeaeb908cc396ee36e4adff439460e.js:50
Zone</ZoneDelegate</ZoneDelegate.prototype.handleError() zone-2222385d52aafe3cf4568d0173483fc6.js:327
Zone</Zone</Zone.prototype.runGuarded() zone-2222385d52aafe3cf4568d0173483fc6.js:233
Zone</Zone</Zone.prototype.wrap/<() zone-2222385d52aafe3cf4568d0173483fc6.js:206
```
### Additional information

![banners_and_alerts_and_mapillary_-_crowdsourced_street_photos](https://cloud.githubusercontent.com/assets/82719/17648583/e4a700c6-6212-11e6-8785-1f7893f95939.png)

**Comment by smsm1** [comment]
I should note that this has happened at least twice now. As most of them have uploaded, I'm leaving gaps as it's too much effort to find the files to fill those smallish gaps.

**Comment by smsm1** [comment]
I've come across this error again with images with edited locations.

**Comment by retro** [comment]
@smsm1 Hi, I tried to reproduce this error locally but wasn't able to. Can you attach the image that you had problems with? It would help me very much.

Thanks,
Mihael
