### ISSUE TITLE
Some Sequences Never Load Images

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2191]
### Basic information
* Platform: Web
* System/Browser: Ubuntu 14.04, Chrome and Firefox, Windows 10 Firefox

### Steps to reproduce behavior

 1. Visit https://www.mapillary.com/app/?lat=42.33547975000002&lng=-71.17741092&z=17&pKey=_NEEJkl9UD7j57xKdprlpQ&focus=map
 2. Wait

### Expected behavior

I would assume that this sequence would load, show images, at least show some sequence info.

### Actual behavior

Nothing loads, and I have left it running for ages without any success. Thumbnails do show up on hover, though.

### Additional information

I tried loading the sequence in the legacy viewer as well, and it would jump to the nearest other sequence (the one on Beacon St south of this sequence). I have also found that when I load the Beacon St sequence, the other sequence is not connected to it in the viewer; that is, no arrows appear to let me move over to the parallel images.

In addition, after trying to load the affected sequence for awhile, other sequences will not load unless I reload the page.

Also, this sequence does not show up in the JOSM plugin.

Some other sequences I have found with the same issue are in downtown Knoxville, Tennessee, but this might be due to the vast number of photos in the area (thanks, allen :D).

**Comment by gyllen** [comment]
@pkoby Thanks for reporting on this. The images seems to be consistent but the do not load for some reason. I will elevate this to the backend team. If you have any more sequences like this, please report.

**Comment by gyllen** [comment]
@ptpt Can you investigate why this sequence is showing on the map. It should be hidden.

https://www.mapillary.com/app/?lat=42.33547975000002&lng=-71.17741092&z=17&pKey=_NEEJkl9UD7j57xKdprlpQ&focus=map

**Comment by gyllen** [comment]
@pkoby As it turns out these images are a part of a testing set. They should not be visible on the map. They were first added then removed and the tiles did not update. Thanks for finding this.

**Comment by ptpt** [comment]
@pkoby Thanks for reporting on this. All hidden sequences should be removed now. @gyllen can close this issue.

**Comment by gyllen** [comment]
@ptpt Thanks for fixing!
