### ISSUE TITLE
Blur editor does not load blurs

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2192]
Please see https://www.mapillary.com/app/blur?pKey=yG2Dw4erq_sjw-hX3x-eQA&focus=photo.

Also, after navigating the blur editor on this photo breaks loading blurs on any subsequent photos.

**Comment by GITNE** [comment]
The same happens with these photos:
https://www.mapillary.com/app/blur?pKey=C9oB--diaMNWYjSpqeQI8g&focus=photo
https://www.mapillary.com/app/blur?pKey=RFMBDapoNH2kInknb28sIA&focus=photo
https://www.mapillary.com/app/blur?pKey=fZ9zuln85X9mwaDjgvqTiA&focus=photo

**Comment by de-vries** [comment]
I'm able to reproduce this by going in the blur editor and hitting refresh. Also when you follow a link to mapillary.com/app/blur* you get the blur editor with no blurs. 
This behavior started after updates to the blur editor saturday evening (Europe).
Refreshing is how I can reproduce it, however it also happens on seemingly random moments.

@GITNE you can 'fix' this by closing and reopening the blur editor.

**Comment by GITNE** [comment]
> @GITNE you can 'fix' this by closing and reopening the blur editor.

No, closing and reopening the blur editor does nothing (for me). Refreshing/reloading the web page does seem to *fix* this issue. However, when loading the page for the first time this behavior is **always** reproducible, so it should not happen in the first place. I am assuming that either there is a problem with data stored in the database or the web client is processing data incorrectly.

**Comment by pkoby** [comment]
I have noticed that after editing some blurs, if I go back to the images which I submitted, they show the lock overlay. However, I revisited a sequence that I had edited, and those images that I had un-blurred still showed the blurred portion, but without the blue boxes and without the lock overlay. Perhaps this is related to your issue? Maybe someone edited the images but they haven't been approved/updated?

**Comment by GITNE** [comment]
@pkoby No, this is unrelated. The backend simply takes some time to actually generate/render a *new* *photo* without or newly added blurs. This kind of delay works as intended/designed.

**Comment by gyllen** [comment]
@GITNE @pkoby Yes its a matter of our CDN clearing its caches. I used to to it manually to get instant blur but it turned out its super expensive todo in the order of us getting blurs in. So current delay can be up to 24h.

**Comment by gyllen** [comment]
Noticed that my above answer did not answer original ticket reopening. And filing bug. Thanks for reporting.

**Comment by richlv** [comment]
i assume this is still tracking a valid problem.
for me, the interface sometimes stops loading blurs. if i'm editing blurs in a sequence, the blurs from the last successful load sort of get laid over other pictures- but they actually float "in space", and centre circles get disconnected from the blur rectangles like this :
![mapillary-blur-breakage](https://cloud.githubusercontent.com/assets/112888/18226142/eff7c4f2-720b-11e6-81b0-314d23ce6d1b.jpg)

moving back & forth shows these in a different location for each photo - maybe related to the 3d model ?

opening a new tab with another photo & editing the blurs does not load any blurs at all.

there seem to be two separate issues :
* blur loading gets broken every now and then
* when it gets broken, there is no user-friendly message and the previously loaded blurs float all over the place

right now it is an even more interesting state - while blurs do load for a new sequence that i open, blurs do not load for one particular sequence. same as before, no error messages. reloading the page does not change anything.

**Comment by nickplesha** [comment]
@GITNE I'm glad it's working for you. There were many improvements to the blur editor (and the whole web app) with the aim of improving performance, stability and error handling. I'll close this issue for now.
