### ISSUE TITLE
M stands for Mega

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#2194]
### Basic information
 `Web`

### Steps to reproduce behavior

 1. Click on your username
 2. Click on "Uploads"
 3. With more than a million pictures, you get an m instead of M.

### Expected behavior

... M

### Actual behavior

...m

### Additional information
https://en.wikipedia.org/wiki/Names_of_large_numbers
https://en.wikipedia.org/wiki/Names_of_small_numbers

...

**Comment by gyllen** [comment]
Fixed, thanks for reporting
