### ISSUE TITLE
Drag and drop image on the published screen loads first image

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#2199]
### Basic information
- Platform: `Web`
- System/Browser: `macOS Sierra / Firefox 48`
### Steps to reproduce behavior
1. On https://www.mapillary.com/app/uploader upload some images
2. At the end of the upload the following screen is shown with the message "132 files have been published for processing. You will get an email when the photos are live on Mapillary.

Meanwhile, you can upload more if you want. "
![mapillary_-_crowdsourced_street_photos](https://cloud.githubusercontent.com/assets/82719/17714854/852355bc-63f9-11e6-8fea-608364e23609.png)
1. Drag and drop the next batch of images to upload from the Finder (file explorer).
### Expected behaviour

The upload to start
### Actual behaviour

The first image of the selection dropped on the window is shown, as there is no drop zone while the message is shown.

**Comment by gyllen** [comment]
@smsm1 Would it help if we just had a button that said `upload more` and then we will go to the original state?

**Comment by smsm1** [comment]
Yes an upload more, with original state meaning that you can drag and drop photos on the page to upload would work, and would save the click that's tipped me up a few times.

**Comment by gyllen** [comment]
I do think we need to keep the click though...

@retro is there something we can do about this?

**Comment by gyllen** [comment]
@nickplesha Reassigning to you for decision

**Comment by nickplesha** [comment]
I think it would be difficult to change that part of the upload at this time so we'll keep the behaviour as it is now.
