### ISSUE TITLE
Android app closes abruptly before being able to do anything

### ISSUE THREAD

**Issue by katrinhumal** [mapillary/mapillary_issues#2203]
### Basic information
- Platform: `Android KitKat 4.4` 
- Version: `...` 
### Steps to reproduce behavior
1. Open the app
### Expected behavior

Be able to start using Mapillary
### Actual behavior

App closes abruptly.
### Additional information

Tried restarting the phone, doesn't help.

**Comment by katrinhumal** [comment]
Trying to find out the app version as well.

**Comment by rsahlin** [comment]
It would be great to know what device it is on.

Best regards
/Richard

**Comment by rsahlin** [comment]
Closing this issue until we have relevant information go proceed with investigation.
Please make sure to test on latest (3.06) version.
