### ISSUE TITLE
Edit Blurs screen needs 'no change, next +1' button

### ISSUE THREAD

**Issue by seb-1204** [mapillary/mapillary_issues#2204]
Feature request:
When editing blurs it would be nice (work flow, less mouse movement) to have a third button next to the two buttons:

```
Clear all + >
Submit + >
```

The button could be something like
`No change + >`
clicking it would move to the next image without making changes to existing blurs.

This would reduce mouse movement. The only time mouse movement is require then if blurs need to be modified, removed and added.
### Basic information
- Platform: `Web`
- Version: `.current website, new design` 
- System/Browser: `FIrefox 48`

![clipboard04](https://cloud.githubusercontent.com/assets/307449/17768507/504d76cc-6545-11e6-9bb8-29fd5f348dc8.png)

**Comment by gyllen** [comment]
@seb-1204 We are thinking about adding keyboard shortcuts to blur for power users.

**Comment by HolgerJeromin** [comment]
Cursor up for next image is already working in blur mode right now :-)

**Comment by gyllen** [comment]
@HolgerJeromin If you made blurs and stepped we should give you a warning right? Seems like the most reasonable thing todo.

**Comment by HolgerJeromin** [comment]
Or remember the state when coming back again. But i think this much more complicated and not always desirable.

On "cursor up" the best / fastest could be a [confirm](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) with "OK" submits the blur and cancel the edit. I have the hands at the keyboard anyway and the Enter/Return Key is easy to hit.

**Comment by Fossdal** [comment]
I would like to get a button to move to next picture in the sequense that has a blure. skipping all the images witout blurs,the reason for this is that there are a lot of pictures that have invalid blurs, specialy windows and signes on houses

**Comment by jfburke3** [comment]
@Fossdal The problem with that is you could skip over images that DO need blurs but don't have them....

**Comment by Fossdal** [comment]
@jfburke3 
True. But i am more interested in deleting stupid blurs than applying new ones
like this one 
https://www.mapillary.com/app/?lat=62.00988342&lng=-6.76796976&z=17&pKey=F_6MGfUeRmrhHqVGm2M_CA&focus=photo

**Comment by katrinhumal** [comment]
@Fossdal, may I ask - is this even to the extent that if a photo has both "stupid blurs" and missing blurs, then you would remove the false blurs and submit for approval without adding the missing blurs on the same photo?

**Comment by Fossdal** [comment]
@katrinhumal No i would also add missing blurs

**Comment by nicolas17** [comment]
You can already skip the current image without making any changes by clicking the right arrow on top (in the sequence navigator with :arrow_left::arrow_forward::arrow_right:).

However, it would be much more convenient to have another button to do the same, next to the "clear all" and "submit" buttons.

**Comment by nicolas17** [comment]
Or... Maybe we don't need an extra button.

Currently, if no blur changes were made yet, the Submit button is disabled. Maybe the same button can be reused as "go to next picture" instead of disabling it. If there are no changes yet, the button would say "Next" and go to the next picture when clicked. When the user makes an edit, change the button to say "Submit", and submit and go to the next picture when clicked.

That's for the UI/UX/design people to decide :)

**Comment by danbjoseph** [comment]
I didn't realize you could use the up arrow to progress to the next image! It's a helpful shortcut, would be nice if it was documented somewhere (if it is, I haven't run across the info yet). 

Would also be nice to have a keyboard shortcut for the submit command.

**Comment by oscarlorentzon** [comment]
You can use the Up, Down, Left and Right buttons for navigating according to the spatial navigation arrows in the bottom of the viewer.

You can also use Alt + Up to navigate to the next photo in the sequence and Alt + Down to navigate to the previous photo in the sequence (according to the sequence navigation arrows in the top center of the veiwer).

**Comment by danbjoseph** [comment]
on OSX 10.12.3 and Chrome Version 56.0.2924.87 (64-bit)

**Comment by gyllen** [comment]
Closing since blurring is being redesigned. We will take this issue into account.
