### ISSUE TITLE
The Show Me State Ain't Showing

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#2205]
### Basic information
- Platform: Web
- System/Browser: `Chrome 51.0N`
### Steps to reproduce behavior
1. Click on the hamburger menu thing
2. Select Leaderboards
3. Type "Missouri"
   1. As you type, results will return for you to choose from
### Expected behavior

It should show "Missouri" under Regions
### Actual behavior

No Regions are displayed.
### Additional information

![image](https://cloud.githubusercontent.com/assets/11722025/17822888/9e3a3860-6627-11e6-9dac-634252b788db.png)

![image](https://cloud.githubusercontent.com/assets/11722025/17822915/c1246968-6627-11e6-9ed5-e32347607af9.png)

**Comment by gyllen** [comment]
@AllenGraetz thanks for reporting we are looking into it

PS: Best issue name ever :)

**Comment by knikel** [comment]
@AllenGraetz thanks for reporting, it seems we don't have Missouri (region) in our WOF shapes. We're in the process of updating ElasticSearch to latest version (tech that handles our search) and will update the shapes after that. I'm assigning this to @peterneubauer who's working on the update and will handle the shapes update too.

**Comment by de-vries** [comment]
Related: 
I can't find the leader-board for the Netherlands via the search bar. This is the page I'm looking for: https://www.mapillary.com/app/stats/85633337

**Comment by AllenGraetz** [comment]
@de-vries  I'm sorry if I'm misunderstanding you, is this what you're going for?  I'm seeing it now, at least.

![image](https://cloud.githubusercontent.com/assets/11722025/18019509/6cfcce38-6baa-11e6-9813-651c4d854137.png)

**Comment by AllenGraetz** [comment]
@gyllen , hah!  Thanks!  I could've passed up the opportunity but it was too much fun to miss out on.  :)

BTW - For those of you not understanding the silliness, Missouri is one of the 50 states in the USA.   It's state motto, and they even have it on their license plates, is the show me state.   

@knikel , thank you

**Comment by de-vries** [comment]
@AllenGraetz Thanx, but no, that one is Caribbean Netherlands.

**Comment by peterneubauer** [comment]
@de-vries I can see it? https://www.mapillary.com/app/stats/85633337?lat=52.180508766907195&lng=5.270171249999976&z=6.822541462319065
<img width="1070" alt="mapillary_-_crowdsourced_street_photos" src="https://cloud.githubusercontent.com/assets/11977/18025978/df26a38c-6c39-11e6-860d-695d854c83d4.png">

**Comment by de-vries** [comment]
@peterneubauer Yes the page exists, but it's impossible to reach it via the leaderboard searchbar. 
To find the page I had to construct the url with the country code from the legacy site.

**Comment by gyllen** [comment]
@de-vries Aha so the search is wrong!

**Comment by knikel** [comment]
@de-vries: I‘ve looked into the issue and this is what‘s happening:
* We have a single result for the `netherlands` query in the system
* There are two results if you [do a search on Mapzen](https://mapzen.com/products/search/?query=netherlands&endpoint=autocomplete&lng=-73.98073&lat=40.72606&zoom=12). We‘re missing the second result on our side.
* The first result will give you the correct shape, the second one should be overlapping. We‘ll have it after @peterneubauer updates WOFs.
* If you search for `the netherlands` the second results from Mapzen takes precedence and since it‘s missing on our side, you won‘t see any results.

Until we have the updated WOF shapes, please skip _the‘s_ 😉

**Comment by de-vries** [comment]
@knikel Thanx for looking into this.
btw, in the legacy site it's working. http://legacy.mapillary.com/map/stats?p=the%20netherlands

**Comment by peterneubauer** [comment]
So, the WOF shapes have been updated, searching should work much better now, closing this for now.
