### ISSUE TITLE
compass do not work

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#2208]
Samsung S4, 5.01, 237+239
I didn't change anything, but since last week it points in only one direction. Changing in the settings doesn't matter. 

Here is the sequence:

JC9-kDuWrs1ceRX6tR8DbA

**Comment by millenbop** [comment]
Does the compass work in other apps, i.e. in a traditional compass app?

**Comment by wegavision** [comment]
I did a new calibration, perhaps it works.

**Comment by wegavision** [comment]
Ok, this was the fault.
