### ISSUE TITLE
only 16:9

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#2209]
Samsung S4, 5.01, 237+239

Since a few days mapillary took pictures only in 16:9. Is this a innovation, can't read about it. I use to upload 16:9 pictures cropping them from 4:3 by deleting the worst part of the picture: the front of my car etc.
But now they are already in this format, and I can not crop them. the result isn't quite good: houses are cut in the upper part of the images etc. Havn't upload them yet, they are too bad.

**Comment by jfburke3** [comment]
Check the settings in the app--do you have Low resolution or High resolution enabled?

I have a Samsung S4 (but still on Android 4.2something), so I can test it with my old Android and see what results I get.

**Comment by peterneubauer** [comment]
So, since a few versions back, we are no longer requiring 4:3,since the backend and view has gotten better. That's why the app now takes whatever the native aspect ratio of the camera is.

Sorry for the inconvenience,yiu want manually to choose another format?

**Comment by wegavision** [comment]
With high resolution it takes 4:3, thanks Usually I enable it, but perhaps I disable it by scrolling down. This is a problem with the settings. Using the right side of the menue to go down you can hit the square and change something.
