### ISSUE TITLE
Distance Mode with Distance Autocapture set to 0 meters does not pause when not in motion

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2210]
### Basic information

* Platform: Android
* Version: 2.39 (but probably also existed in 2.37)
* System/Browser: Samsung Galaxy S7 Edge, Android 6.0.1

### Steps to reproduce behavior

 1.  Enable Distance Mode
 2.  Set Distance Autocapture value to 0 meters
 3.  Begin driving and start taking pictures.
 4.  Come to a complete stop for as long as you need to, in order to verify function.

### Expected behavior

Picture taking should stop (evidenced by the # of pictures counter stopping, maybe after one or two while everything settles down).

### Actual behavior

The number of pictures counter continues to increment, no matter how log you remain motionless.

### Additional information

If you set the Distance Autocapture to values above 0, it appears to work properly.  I found 3 meters to be pretty reliable.  At 2 meters, it still seemed to take an occasional random picture (presumably because of GPS inaccuracies).  I did not try 1 meter.

In older versions, the Pause on Stop setting was rock solid.  Not sure what code was used there vs. the new Distance Capture feature, but maybe copying some of the code from the old function would help?

* This is what I was referring to in #2108 before I understood the changes.

Can send logs if you need them.

**Comment by peterneubauer** [comment]
Yes, with the distance mode, the is no pause on stop. If you set it to 0 meters, you want to take as fast as possible? The GPS is always drifting a bit so we can't know that you really are standing still and not driving very slowly if you set the distance that low. 

How do you propose it should work?

**Comment by jfburke3** [comment]
If set to zero, shouldn't it work as the old pause on stop did? Otherwise, why allow the setting  (which is explicitly described as valid in the settings screen) if it is going to result in extraneous images when stationary. 

More specifically, no matter what the value, if the device isn't moving, it should work as the old pause-on-stop setting did, in my opinion. Up for discussion. Just saying that it seems...weird from a user perspective.

**Comment by peterneubauer** [comment]
Why do you need to set it to zero and not like 3m or so? To me setting the tolerance to 0m means "take picture always, as fast as you can"?

You can always tap on the screen to take extra photos between captures instead so you can "fill in" pictures if the app stops too early with a tolerance of say 5m?

**Comment by jfburke3** [comment]
Because I can?

Seriously, though, if you don't want people using a setting of 0, then a low-threshold value should be set in the code.  Conversely, if you do want people to be able to take pictures as fast as they can, then either some sort of GPS or motion filter (what did the old Pause on Stop use, the accelerometers?) needs to be added to the code for those times the vehicle is motionless, or you'll end up with a ton of pictures taken at exactly the same spot, probably with different direction attributes even though they all face the same way.  (Wouldn't that mess up your image recognition code?)

And yes, I really was trying to take pictures as fast as my phone is capable of, but the annoyance of having to remember to press stop (and then press start again) is...well...annoying.  Most of the time when I'm shooting sequences, I'm not driving with Mapillary in mind--you're just getting a free ride to wherever I'm going :-) and so I'm often thinking about other things at the time.  And yes, I _have_ forgotten to restart photos more than once.

**Comment by rsahlin** [comment]
Hi @jfburke3 and thanks for reporting!

Yes, it is  somewhat ambiguous with a 0 distance threshold - perhaps we should increase the lower limit to 1.

I think it is best if we could avoid having speed calculations as we had in the driving mode, since these will only work for specific usecases - is there any other solution that you can see?
(or is it best solved by setting min valule to 1?)

Best regards
/Richard

**Comment by peterneubauer** [comment]
I think a sane stop-calculator would be: "if 3 consecutive images are taken within the 1st images accuracy limit - we are stopping". So, with a setting of 0 or 1, and an accuracy o say 5m, if image 1,2,3 are taken within image 1 accuracy (5m), we are stopping even if the consecutive distance was more than 1m between the images. We then assume that this was due to GPS drift.

Makes sense?

**Comment by rsahlin** [comment]
I don't think we shall factor in GPS drift, there is no consistent way of measuring it as far as I know.
From what I can tell the location is usually, ie more often than not, in the same position as the accuracy shifts.
Maybe we should make it easier to adjust later on in the changeset, possibly by going through uploaded photos and check for inconsistensies?

Anyway, this issue is regarding a distance of 0 meters and how that should be handled.
@jfburke3 Could you please point me to an uploaded sequence with distance set to 0?

Best regards
/Richard

**Comment by jfburke3** [comment]
I just reread my last reply.  :-\  I really shouldn't be allowed to get on the interwebs when I'm tired.  What I meant to say in one sentence is, most of the time when I'm shooting sequences, I'm not driving with Mapillary in mind--you're just getting a free ride to wherever I'm going when I'm driving around town :-) and so I'm often thinking about other things at the time and not keeping an eye on what the camera is doing.  (I'll note that I pretty much plan my long-distance highway trips around "what haven't I gotten on Mapillary lately?" if that wasn't obvious to y'all.)

Richard, I shot this sequence just for you:
f4eAK2X0V8M1VFouznC93g

Distance set to 0 for it.  Just past the 30th image is where I got stuck at a traffic light.

To expand on my concern about the lack of some form of "pause on stop" function, the distance setting I (and others) use will likely have to be adjusted depending on GPS conditions.  I know for certain that on some days my GPS lock is much better than on others, probably due to weather, but I don't really know for sure why.

I guess if y'all aren't worried about it, then close this case.

**Comment by rsahlin** [comment]
Hi @jfburke3 

Hehe, I think that goes for all of us :-)
I will check the sequence and see what I can make of it!

In the meantime, could you please try with 1 or 2 meter setting?

Best regards
/Richard

**Comment by peterneubauer** [comment]
https://www.mapillary.com/map/s/f4eAK2X0V8M1VFouznC93g

**Comment by rsahlin** [comment]
Hello again @jfburke3 

I'm looking through the photos in the sequence and I am having a hard time finding duplicates that have the same position.
Could you please let me know if you have found such pictures and send a link?

Best regards
/Richard

**Comment by jfburke3** [comment]
Here ya go:
https://www.mapillary.com/app/?focus=map&lat=33.9032597&lng=-84.4592802&z=17&menu=false&pKey=RkiTnO-LFa6J2oak8e_c2w

If you move forward starting there, it looks like I'm drunk standing in the middle of the road.

Finishing an upload of a sequence with distance set at 1 meter, I'll give you a link to it in a bit.

**Comment by jfburke3** [comment]
Here's a sequence at 1 meter, just before where my drunken wandering on the road begins:
https://www.mapillary.com/app/user/jackdripper?focus=photo&pKey=CADeE6avtYYV4TFqjZmDEw&lat=33.9025775&lng=-84.455401&z=17

(Apologies for the sun.  It was the only time I had available to get that sequence, and the changing traffic signal made it the perfect opportunity.)

**Comment by rsahlin** [comment]
Hi and thanks for the sequences :-)

I think I see what is happening, in the pictures in the first sequence that I investigated the GPS did not move an inch - BUT the compass was all over the place.
This also seems true for sequence 2.

What are your compass autocapture settings?
Could you please try and up the angle as much as possible?

Best regards
/Richard

**Comment by jfburke3** [comment]
The compass autocapture value is at the default 45 degrees.  How high should I take it?

Are we looking at the same sequence?  When I look at it, not only does the direction vary, but the little blue dots meander all over the place.

![meandering blue dots](https://cloud.githubusercontent.com/assets/11140831/17949608/24867c9e-6a24-11e6-91d8-9594425ce310.JPG)

**Comment by rsahlin** [comment]
Hi

Aha - now I see what you mean, no I was not looking at that particular segment :-)
These photos seems to have been auto-corrected by the backend, when viewing them the viewpoint is still.
In the viewer it seems that the original GPS location is shown - I'll ask a member of the backend team to have a look.

Regarding the compass autocapture, I cannot be dead certain that they where captured due to compass change. 
To decrease probability please try with 180 degrees.

Best regards
/Richard

**Comment by rsahlin** [comment]
I have created an issue for display of GPS location in the map:
https://github.com/mapillary/mapillary_issues/issues/2218

I'll close this issue for now as I feel it is working as inteded.
Please re-open if you disagree or would like to add additional information.

Best regards
/Richard

**Comment by jfburke3** [comment]
Nope, if y'all are satisfied, then I'll leave it alone.  I was just confused by the behavior of the new settings.  Might be worth noting in the instructions/manual the next time it's updated that even a small GPS update will result in a new picture being take (since I'm sure that even when stopped, my phone's GPS data changes slightly).
