### ISSUE TITLE
UI allows enabling mutually exclusive resolution settings (Android)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2211]
### Basic information
- Platform: Android
- Version: 2.37 through 2.39
- System/Browser: Samsung Galaxy S7 Edge, Android 6.0.1
### Steps to reproduce behavior
1. Enter Settings.
2. Enable Take Low Resolution Pictures.
3. Enable Take High Resolution Pictures.
4. (Optional) Exit out of Settings, then go back in.
### Expected behavior

When enabling High, Low should either:  be grayed out, OR automatically disabled.  (I prefer the latter, but up to y'all.)  And vice-versa--enabling Low should disable High.
### Actual behavior

Both settings remain enabled.
### Additional information

I have no idea what law of physics this violates.  I'm scared to actually take pictures with both settings enabled because I don't want to cause some sort of matter/antimatter inversion that causes the entire universe to suddenly explode.  :'(

At the same time, I'm a little worried about what will happen if I DISABLE both of them and take pics.  Will the dinosaurs return?  :-O

![screenshot_20160821-230726](https://cloud.githubusercontent.com/assets/11140831/17842778/73c374a6-67f4-11e6-8a36-28dd9d179e50.png)

**Comment by jfburke3** [comment]
BTW, I would consider this low priority.  I would hope that your user base is intelligent enough not to destroy the universe.

**Comment by rsahlin** [comment]
Hi @jfburke3 and thanks for reporting

You are correct, these settings do not make sense :-)
We are in the process of creating a new UI - settings such as this will be looked into.

Best regards
/Richard
