### ISSUE TITLE
Force direction to left/right/backward in driving mode

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#2212]
It would be useful to lock direction of photos also to backward and sides (may be with 45 deg step) in mobile app.
It needed to photos from buses and trams, now such sequences need to manual correction, like here:
https://www.mapillary.com/app/user/trolleway?lat=55.75937859042858&lng=37.89864759542303&z=16.003281264924755&pKey=3XWSlJCcv6VkzV4U4oPQVw

This feature may be named as "bus mode" in mobile app.

**Comment by millenbop** [comment]
We currently only have this for multi-cam setup in iOS, but is needed for any type of camera.

**Comment by rsahlin** [comment]
Hi @trolleway  and thanks for your suggestion.

My name is Richard Sahlin, I am the lead engineer on Android.
On Android we will be looking into this in the future as we are revising the UI.

Best regards
/Richard

**Comment by millenbop** [comment]
This was released on iOS last week, removing iOS tag.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest android app version
