### ISSUE TITLE
add_mapillary_tag_from_exif.py does not allow to define sequence_uuid to continue upload of a sequence

### ISSUE THREAD

**Issue by kertase** [mapillary/mapillary_issues#2213]
Hello,

The doc and the script itself tells me that it is possible to set a costume sequence_uuid I presume in order to be able to continue the upload of an image sequence:

Use from command line as: python add_mapillary_tag_from_exif.py root_path [sequence_uuid]

Well when I do try it obviously does not work since the script only accepts 1 values and as far as I can see does not grab the second variable in any way.

Please fix the script or the misleading doc,

Best

K.

**Comment by ybkuang** [comment]
@kertase Sorry. It should be fixed now https://github.com/mapillary/mapillary_tools/commit/3e121336609e976cb9014d5fe0a2b4c811e9d446

**Comment by kertase** [comment]
Line 66: still needs a fix to accept more than 2 arguments…  :
if len(args) != 2:
         print("Usage: python add_mapillary_tag_from_exif.py root_path")
         raise IOError("Bad input parameters.")

**Comment by ybkuang** [comment]
@kertase Ouch, missed that one. Should be good now.
