### ISSUE TITLE
Investigate how to disable shutter sound on (chinese) devices that always play sound during capture 

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2215]
Feedback from user - proposal is to investigate using a null ShutterCallback function.

I've dived into your search results and my search specific to my OS and model, about workarounds for this, but found that it can be hardly done without a root previlege of the phone system. It doesn't seem worthwhile doing so since acquiring root previlege can cause security risk and loss of manufacturer's warranty. I describe my research below and provide a possible workaround on developer's side. You may forward this to your developers for reference and may not necessarily read it.

As you suggested, other applications may face the same situation. However common apps in China (e.g. instant message apps WeChat, QQ; or microblog apps Weibo, Weico, etc) overcome this problem. No shutter sound by default and even no choice for shutter sound indeed. To confirm this is a country-specific problem, I tried to take a photo in Twitter app and – Click! – the shutter problem occurred, even when system is muted. Wow, what a mysterious country I'm living in! (As a cartographer, it's familiar to me that our online maps are somehow encrypted to be shifted from the correct location. That's part of why I join OpenStreetMap and get to know Mapillary! Domestic software developers handles this shift while international developers may not realize this so their apps cannot work well :white_frowning_face: ).

So I searched both in Chinese and English to find out the problem to the answer. As the log recorded, enableShutterSound(false) returned false, which means the system doesn't allow this action so it failed to work as expected [1]. A Chinese developer's blog [2] has talked about this topic; it has also been discussed on StackOverflow [3]. They both indicates that a workaround for developer may be using a null ShutterCallback function. This works whatever enableShutterSound(false) return.

As a student majoring in cartography and know a little bit of geoinformatics and software programming, I understand your difficulties to use a null ShutterCallback for other technical requirements. If so, I recommend you to at least remind users about this problem caused by their own OS when enableShutterSound(false) returns false, which may save you some time explaining.```
(edited)

**Comment by ovivoda** [comment]
This is not possible
