### ISSUE TITLE
bad UI in Camera

### ISSUE THREAD

**Issue by Fossdal** [mapillary/mapillary_issues#2217]
### Basic information
- Platform:  `Android`
- Version: '2.39` 
### Steps to reproduce behavior
1. start mapillary
2. start camera mode
### Expected behavior

Camera picture to fill all of the screen
### Actual behavior

black bar on left side
looks like background of settings drawer
### Additional information

Android 4.4.2
Samsung Galaxy Mini 4

![screenshot_2016-08-24-16-03-05](https://cloud.githubusercontent.com/assets/15619646/17935956/1a547e4c-6a15-11e6-9549-44d1db93f485.png)

**Comment by ovivoda** [comment]
this issue should be fixed in the latest app version
