### ISSUE TITLE
Option to disable volume down key

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#222]
There should be an option to disable shortcut keys that take a photo manually in the application. While driving taking a sequence, the vibration from the road and being in a windshield mount, can cause the volume down key to be pressed, taking a picture. The problem is that eventually the O/S cant handle the I/O and crashes(if done in combination with sequence)

**Comment by peterneubauer** [comment]
The shortcuts for the Volume buttons can now be disabled, closing this.
