### ISSUE TITLE
Long url

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#2220]
### Basic information
-  | `Web`
- Version: `...` 
- System/Browser: `...`

Could there not be a short url
as
http://overpass-turbo.eu/s/i1v
instead of
https://www.mapillary.com/app/user/filipc?lat=51.025127709732544&lng=4.481580856484507&z=17&pKey=xD1HxoBFjJJ6Hi_wg0w2zQ&focus=photo

The key itself is useless.

By the way, I do not understand how they do it.

**Comment by gyllen** [comment]
Its a URL shortner. Will keep this open as a discussion, its something we have though about for a while

**Comment by gyllen** [comment]
No plans for an URL shortener. Please open a thread in https://forum.mapillary.com if this is still an issue to you.
