### ISSUE TITLE
Filter by user sorts weirdly

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2221]
### Basic information
- Platform: Web
### Steps to reproduce behavior
1. Open filter in web app.
2. Search for "allen".
3. Fail to find "allen".
### Additional information

I don't know how the names of users are sorted in the filter dialog, but it's sometimes difficult to find a user if their name starts with a common string. In order to sort by "allen", I actually used "allee", at which point he shows up at 5th place. Similarly, searching for "gyllen" finds a lot of "gyllen#" users first. Searching for "dg" for "dgearhart" finds "3dgiordano" first.

Would it be possible to have the names that are typed show up first? Right now it almost seems like it's sorted alphabetically, but for all names containing a string (except for "allen").

**Comment by gyllen** [comment]
@pkoby Thanks for reporting, we will look into the search algo. I see the same results as you do and it makes no sense.

**Comment by spatialhast** [comment]
@gyllen the same error when searching by name 'hast'

**Comment by gyllen** [comment]
Algorithms are improved and search now works as intended
