### ISSUE TITLE
You meant "unprocessed", not "uncompressed"

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2222]
Thank you so much for allowing people to access their own original, unprocessed images!

But the link to the image (in the context menu, the three dots), says "Download uncompressed original".

An uncompressed truecolor photo file (commonly, a "raw" file) contains one byte for the red channel, one byte for the green channel, and one byte for the blue channel, for each pixel in the photo. For a 10MP photo, this would create a 30 megabyte file. Obviously, that is not the type of file you're offering for download here.

What you meant to say was probably "unprocessed". That is, not downsized and not blurred. This is the photo that is behind the download link.

Thanks again for allowing us to access our unprocessed files!

**Comment by gyllen** [comment]
This has to be a spelling mistake, thanks for reporting @pbb72
