### ISSUE TITLE
How to publish panoramas made with DMD panorama app in full quality?

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#2223]
How to publish panoramas made with DMD panorama app in full quality? Currently images availablr from dmd android app have a quality much, much lower than accessible via http://www.dermandar.com/ site.
Just try to zoom http://mapillary.com/map/im/1jzA6QBCi6-y7lCN9JtFxg and http://pnr.ma/eDWHKM

**Comment by echeloni2p** [comment]
Hi!

You can upload images up to 20 MB in size and those are stored in full quality internal, but the viewer on the page may not show the original full quality.

echelon

**Comment by nicolas17** [comment]
There are plans to make higher-resolution panoramas work in the viewer. You will not need to do anything when this is done, since the server keeps the original file you downloaded.

**Comment by iav** [comment]
> since the server keeps the original file you downloaded.
This is the question!
Generaly not clean (at least to me) how to  get a highes possible quality panorama from app. I found only option "save to gallery" - it makes jpeg. But not so big jpeg, and panorama on site can provide much better small details then exported jpeg. 
Maybe, I just miss button "export with all available quality"?

Or, maybe, there are another app, that can do a panoramas with vertical oriented phone,  5300 point on vertical size, and solid long horisontal?

**Comment by nicolas17** [comment]
I meant the Mapillary server keeps the original file you upload (oops did I say download? I meant upload...)

But you seem to be asking a question about DMD, not about Mapillary...

**Comment by iav** [comment]
> you seem to be asking a question about DMD, not about Mapillary

I don't know. Mapillary once declared they accept panoramas from DMD. And I newer find - how. Possible they can use kind of API provided by DMD?

**Comment by gyllen** [comment]
@iav Yes as @nicolas17 points out we are working on full res pano support at the moment. I will report back when finished.

**Comment by gyllen** [comment]
Aaand we now have full pano support (since a couple of years back). The viewer will now load higher resolution tiles when you zoom in.
