### ISSUE TITLE
Photo timestamps change after 'Add Mapillary data'

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2224]
When I use "Add Mapillary data", the modification time of the photos is changed to the time the EXIF data was added. The Upload tab then shows that timestamp in the list of sequences, instead of the actual time the photo was captured.

### Basic information
* Platform: `iOS`
* Version: `4.4.10`
* System: `iPhone 6`

### Steps to reproduce behavior

 1. Take pictures!
 2. Go to the Upload tab and note the sequence timestamps shown in the list.
![The photos show the actual capture timestamp](https://cloud.githubusercontent.com/assets/101955/18037110/923b2fe2-6d52-11e6-983d-3213a0a708ad.png)
 3. Tap top-left button, tap "Add Mapillary data", wait until it finishes.
 4. Switch to another tab, and then back to the Upload tab. You will see the timestamps have changed.
![Timestamps show midnight today](https://cloud.githubusercontent.com/assets/101955/18037109/91ed1f14-6d52-11e6-9097-ad1915d792d3.png)

### Expected behavior

The time shown on the Upload tab should be when the sequence was captured. It doesn't really matter how this is achieved. Maybe the modification time of the file could stay the same after "adding Mapillary data", or maybe the Upload tab should look at the capture time in the EXIF instead of the file mtime.

**Comment by millenbop** [comment]
Thanks for reporting, I'll fix! Dod you use an external camera by the way?

**Comment by nicolas17** [comment]
No, this was all with the iPhone's built-in camera.

**Comment by millenbop** [comment]
Fixed, will be out in the next release
