### ISSUE TITLE
Approval message for multiple changesets links to only one of them

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2226]
On the website, in the right-hand menu, under the "Feed" tab, there are messages about (among others) approved changesets, labeled "Your edit request was approved". These messages are sometimes about one changeset, and sometimes about several.

When the message is about one changeset that has been approved, there is a link "view" that links to the changes sequence.

When the message is about several changesets, then there is a link "xx changesets" (e.g. "10 changesets") which only leads to one of the changed sequences.

I would like to be able to access all approved sequences from the feed. Especially since #2225 also makes it impossible to see any of the accepted changesets.

**Comment by peterneubauer** [comment]
Closing this for now, should be working.
