### ISSUE TITLE
Manual uplader: It's possible to upload the same or overlapping sequences.

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2227]
### Basic information
- Platform:  `Web`
### Steps to reproduce behavior
1. upload sequence
2. upload another sequence that is the same or contains images of the previous sequence
### Expected behavior

I expect a message that the file already exists.
### Actual behavior

let's you upload and add the file to the database.
### Additional information

On the one hand you can't upload different images in one sequence that have the same filename https://github.com/mapillary/mapillary_issues/issues/1758 but on the other hand you can upload the same sequence twice. :0
The uploader should be oblivious to the filename, but rather check something like GPS position+time or the image checksum.

Same picture, twice:

http://mapillary.com/map/im/c2XcqnHLofGUyVZ8pl-hvA
photo key: c2XcqnHLofGUyVZ8pl-hvA 
sequence key: dbNqOqzDHJEGtnG6YWUgYg

http://mapillary.com/map/im/9Fa_4qxIWLvKZGRqNhXQQg
photo key: 9Fa_4qxIWLvKZGRqNhXQQg 
sequence key: Enr0cmNfsvteQy-luYV-IA

**Comment by gyllen** [comment]
@mxa Its hard for us to detected the same image clientside, however what we should do is, to ignore these images when we try to process them and notify you as a user.

**Comment by mxa** [comment]
@gyllen shouldn't it be possible to detect if you are going to upload an image that has identical GPS location, time and compass data to one of the images in the database?

**Comment by gyllen** [comment]
@mxa It would be possible, however we do not know if its a duplicate or if it is in fact another image.

**Comment by mxa** [comment]
@gyllen I think it's virtually impossible to have two different images with identical GPS location, time and compass data.

**Comment by gyllen** [comment]
Deduplication is on our list, but not on the roadmap. Closing here, but please know that its still on our radar.
