### ISSUE TITLE
Placement of images in web uploader is practically unusable.

### ISSUE THREAD

**Issue by blaueente** [mapillary/mapillary_issues#2228]
### Basic information
- Platform: `Web`
- System/Browser: Ubuntu with firefox _and_ chrome
### Steps to reproduce behavior
1. upload images without location
2. move location of small orange rings to actual location
3. drag and drop ring again
### Expected behavior
1. The selection and drag&drop react instantly
2. Other already placed rings should stay fixed when place a new ring.
3. If I click on an already placed ring, I can move that ring again.
### Actual behavior
1. Huge lags. Sometimes the rings react, sometimes not.
2. already placed rings (probably the last one) move to the new location, when I drag a new ring 
3. at one point, the whole browser content became green
### Additional information

I have a screencast, unfortunately github won't attach it.

**Comment by blaueente** [comment]
Here it is, zipped seems to be ok:
[mapillary_screencast_upload_location.mkv.zip](https://github.com/mapillary/mapillary_issues/files/443413/mapillary_screencast_upload_location.mkv.zip)

**Comment by gyllen** [comment]
@blaueente We just pushed some fixes to the uploader. Can you see if these helped?

**Comment by blaueente** [comment]
Yes, the situation has improved very much. Usage is still somewhat laggy (at least in firefox, haven't tested chrome), and sometimes one has to click twice on the ring to make it react, so not perfect, but overall ok.

**Comment by gyllen** [comment]
Ok I will keep this open as a general performance ticket of the uploder.

**Comment by gyllen** [comment]
@nickplesha Reassigned to you for decision

**Comment by nickplesha** [comment]
We've made some performance improvements to the uploader, hopefully this makes the performance not an issue anymore.
