### ISSUE TITLE
images size on GoPro exceeds iPhone memory - transfer/upload problem

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2231]
iPhone 5S 16GB & GoPro Hero 4

- Captured 4336 images while riding my bike for 1h20m.
- Transferring photos to the phone, the phone memory filled up.
- Switched to wifi (broke connection with GoPro) and uploaded 4248 photos.
- Switched wifi connection back to the GoPro and agree to transfer photos. 
- Queue says 4333 to transfer, completes and get the "Transfer complete - You can now review and upload the photos as usual" message. Hit okay but there are 0 photos waiting for upload.
- When the photos on the GoPro exceed the memory capacity of the phone. What's the correct workflow. Is there someway to do it with a script (like with the python mapillary tools)?

**Comment by millenbop** [comment]
You are doing it correctly, i.e. sync, upload, and synch again. But it sounds like there's a bug with how we save the download history (i.e. even if the download fails it saves it to the history), I'll look into it this week.

**Comment by millenbop** [comment]
I can confirm the bug. I have added a storage space check so it stops the transfer if there is too little space left to save the file.

Will be available in next release. Thanks for reporting!
