### ISSUE TITLE
Some individual traffic sign filters not working!

### ISSUE THREAD

**Issue by octanebaby** [mapillary/mapillary_issues#2232]
### Basic information
- Platform: `Web`
- Version: `52.0.2743.116` 
- System/Browser: `Chrome`
### Steps to reproduce behavior
1.  Search for Phoenix
2.   Turn on filters for traffic signs
3.   Zoom in until you see `RXR` rail crossing signs or `12-6` height restriction signs, among others
4.  FIlter for just those to signs (under `regulatory`)
   5   All signs disappear!! 
### Expected behavior

When individual sign filter is on, all signs _except_ those filtered disappear
### Actual behavior

All signs disappear
...
### Additional information

Try this link: https://www.mapillary.com/app/?lat=33.44708583906254&lng=-112.07562934068028&z=17.014390883183147&focus=map&pKey=Z0n76fpBc7eZe5l-oVmW4A

Before individual filter
![image](https://cloud.githubusercontent.com/assets/433885/18104711/6ab27ce0-6eca-11e6-83f9-89c202e43e38.png)

After individual filter
![image](https://cloud.githubusercontent.com/assets/433885/18104720/7528e5c4-6eca-11e6-8f6f-4276abc75a70.png)

**Comment by gyllen** [comment]
@octanebaby All different types or just these types?

**Comment by katrinhumal** [comment]
@octanebaby Is this still relevant after updates or can we close?
