### ISSUE TITLE
Upload on Map not showing correct Preview

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2234]
### Basic information
- Platform: `Web`
- Version: `...` 
- System/Browser: `Opera/Firefox`
### Steps to reproduce behavior
1. Selecting pictures
2. Wait for Preview.. 
### Expected behavior

Should showing all GPS Points
### Actual behavior

Not Showing all Positions
### Additional information

Checked with GeoSetter.. GPS Data's are inside the Picture. So it should not be an issue on the Pictures/GPS Data...  So on upload you do not know, if it will be correctly uploaded.

<!-- screenshots, system logs etc. --
![image](https://cloud.githubusercontent.com/assets/10342344/18142688/02b900c8-6fbf-11e6-849a-a93d43756a19.png)

> ![image](https://cloud.githubusercontent.com/assets/10342344/18142704/15914a7a-6fbf-11e6-8898-a25e5c36e892.png)

**Comment by retro** [comment]
@thoschu96 Would it be possible for you to upload this photo set somewhere so I can test it out?
