### ISSUE TITLE
Non realistic geometry stretching across Europe

### ISSUE THREAD

**Issue by gthia** [mapillary/mapillary_issues#2235]
### Basic information
- Platform: `Web`
- Version: `...` 
- System/Browser: `Google Chrome'
### Steps to reproduce behavior
1. Go to Southern Europe
2. Zoom in z=6.1 to 6.9
3. See a line is drawn across the continent
### Expected behavior

Should not be there. Its highly impossible to have a straight line.
...
### Actual behavior

...
### Additional information

... 

![2016-09-01 13_32_23-mapillary - crowdsourced street photos](https://cloud.githubusercontent.com/assets/11885886/18166019/f097dbf0-7048-11e6-8184-9f36f75dff56.png)
![2016-09-01 13_32_44-mapillary - crowdsourced street photos](https://cloud.githubusercontent.com/assets/11885886/18166017/f096772e-7048-11e6-9dd5-c62427950976.png)
![2016-09-01 13_32_56-mapillary - crowdsourced street photos](https://cloud.githubusercontent.com/assets/11885886/18166018/f097ade2-7048-11e6-8a5d-ea34c6aadc65.png)

**Comment by echeloni2p** [comment]
Hi

Thats just a track not divided in parts, on both ends a user uploaded pictures (I guess manually) in one track, and so the process did draw a line between both pictures.
Needs to be cut in 2 or more tracks.

echelon

**Comment by ybkuang** [comment]
@ghtia @echeloni2p the line should be gone now? can you double check? we have a post-processing every two days to cut these lines (so there will be some delay)

**Comment by simonmikkelsen** [comment]
Just cutting the lines is not the best solution. I have seen such errors occur due to GPS errors. Cutting the lines will leave a pretty world map, but you end up with some images in completely wrong locations.

Often it is just a few images in a sequence, so it is easy to see which images to delete (you could even automatically delete up to a number of images in the beginning of a serquence) and you may even be able to see their correct location.

**Comment by HolgerJeromin** [comment]
A user could have manually uploaded a bunch of images which are correct tagged but does not belong together in a sequence... Just deleting a runaway without checking by human is a bad idea

**Comment by richlv** [comment]
ah, that's the same as #2237
i've listed a few specific sequences there. as you can see, users have uploaded old geotagged photos there, and that resulted in sequences that spans years.
nevertheless, they should all be reviewed manually, and an automated process should flag all suspicious sequences for review.

**Comment by ybkuang** [comment]
Should be fixed now. We are also working on making the sequence splitting process more robust. I will close this for now. Please let us know if the issues reappears.
