### ISSUE TITLE
New location editor: Not able to see direction for images on same location

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2236]
### Basic information
- Platform: `Web`
- System/Browser: Windows 8.1, Chrome
### Steps to reproduce behavior
1. Go to https://www.mapillary.com/app/index/tryl?lat=55.3827433511278&lng=10.445149981264365&z=20&pKey=iirCPLh8ifP11zBymeRSLQ&focus=map and see there are a lot of images taken at the same location but with different directions.
2. Try to edit the sequence.
### Expected behavior

When I click on a photo I should be able to see its direction, e.g. by having a separate color for the selected photo.
### Actual behavior

The direction marker of selected and unselected photos are the same color, so they just form a circle.

**Comment by nickplesha** [comment]
This is an issue we're tracking internally and we will be working on it in the future as we improve the editor.
