### ISSUE TITLE
ios app getting terribly slow

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2238]
yesterday i was using the ios app quite a lot - driving, walking, manual sequences. was keeping it open throughout the day. by the end of the day, the app became terribly slow - reacting to exposure point setting in the driving mode took either a terribly long time or many attempts (not quite sure which one, kept on tapping it :) ), and even pictures were taken very rarely - having the interval set to one second, the pictures were taken like this :
http://mapillary.com/map/im/Sfo4TI4_MXG4ma4B6HWixg
that's the last image before i force-closed the app and reopened it, and then it all was good.
i can't see the exact times as the exif data is hidden, unfortunately - but compared to the other sequences, looks like once every 3 seconds or so ?

**Comment by millenbop** [comment]
I wonder if it's the new Mapbox library that I added in the latest app that causes this. Even though the map is hidden we add annotations to it so that showing/hiding the map is fast. Might have to stop doing that.

What phone are you using?

**Comment by richlv** [comment]
iphone6. i was actually enabling the map (both from the main menu and during the shooting) quite a lot at some point.

**Comment by millenbop** [comment]
An iPhone 6 should def be able to handle 1 fps well!

Did you notice the slowdown just in this version or is it something you have seen in older versions as well?

I have been thinking about actually destroying the map when it's hidden to free up resources rather than just hiding it. It will make the map switching slower, but I think that's worth it.

**Comment by richlv** [comment]
absolutely, it does handle 1s just fine - the slowdown was an exception. you can see the sequence right after that, http://mapillary.com/map/im/K10pbK_a6E96APjCRahHmg
it's a few seconds after i closed & restarted the app.
i have noticed that the exposure point changing was not responding properly sometimes, but i don't recall seeing such a slowdown in earlier versions.

**Comment by richlv** [comment]
is there maybe some debug log that could be created by the app, recording memory usage and whatever else could cause this ? otherwise you might be removing a convenience function that might not be the cause of this :)

**Comment by millenbop** [comment]
I don't have anything built-in, so no not really. Only way right now is to connect it to debug tools. I'll do some long-running tests this week to see if I can observe some slowdowns and observe memory consumption etc.

Soon I want to enable faster capture than 1 fps now that we have separated the meta data and the photo. 2 fps should def be possible and stable on iPhone 6, perhaps even 3 fps.

**Comment by millenbop** [comment]
Do you still have this problem?

**Comment by richlv** [comment]
haven't seen it recently, but haven't done such extensive sessions either.
closing now, if it happens again, will reopen :)
