### ISSUE TITLE
Move image location to road.

### ISSUE THREAD

**Issue by Lesko987** [mapillary/mapillary_issues#224]
Moving - snapping 1000 images to road is lot of work. You shoud add some possibility to move images to polyline of a road. Best way would be to do this automatically for a whole sequence. Then you would only rewiew sharp turns manually and check if the right road was used. Location could be even corrected at a later time again if the road would change (became more accurate) in OSM. 
You could even define offset from the road center (+/- 1m), so it would be logical to assume direction of the sequence.

**Comment by eliasp** [comment]
And [another interesting blog post](https://karussell.wordpress.com/2014/07/28/digitalizing-gpx-points-or-how-to-track-vehicles-with-graphhopper/) about updates in GraphHopper providing mechanisms which could be applied here.

**Comment by eliasp** [comment]
OSRM [provides now](https://lists.openstreetmap.org/pipermail/osrm-talk/2015-April/000810.html) support for snapping GPS traces to roads too - so another possible candidate which could serve as technological base to implement this feature.

**Comment by pyrog** [comment]
@eliasp Thanks a lot for theses link about **map matching** :smile: 

* Explanation about the algorithm (add-on for OSRM)https://www.mapbox.com/blog/map-matching/

**Comment by richlv** [comment]
looks like mapillary is working on a more automated way to address this : http://blog.mapillary.com/update/2016/07/14/meili.html

**Comment by ybkuang** [comment]
@Lesko987 As @richlv suggested, [Meili](http://blog.mapillary.com/update/2016/07/14/meili.html) is one of our efforts to address this issue. Let us know if you have more ideas on this. 

This is a similar issue as https://github.com/mapillary/mapillary_issues/issues/97. 

Also an update, mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
