### ISSUE TITLE
Have /v1/u/uploadhashes refer to "new" site for hashes

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2240]
### Basic information
- Platform: `Web`
- System/Browser: Win 8.1 / Chrome
### Steps to reproduce behavior
1.  Go to https://github.com/mapillary/mapillary_tools/tree/master/python
2.  Follow the link to http://blog.mapillary.com/technology/2014/07/21/upload-scripts.html
3.  Follow the link to http://api.mapillary.com/v1/u/uploadhashes
### Expected behavior

See the hashes for uploading.
OR
Have the URL either redirect to https://legacy.mapillary.com/map/upload/im or write a text saying that hashes have moved there. I would prefer the latter, because the hashes are only shown when you have no images that needs to be pushed or canceled.
### Actual behavior

See the text "You need to sign in or sign up before continuing." even though I am logged in.
### Additional information

Tried to reset my password 3 times. Gave up uploading.

**Comment by gyllen** [comment]
@simonmikkelsen We are working on adding hashes to your settings page on new site. I think thats there is where they belong.

**Comment by floscher** [comment]
The hashes are now located at https://mapillary.com/app/settings/developers

**Comment by GITNE** [comment]
Actually, it is [`https://www.mapillary.com/app/settings/developers`](https://www.mapillary.com/app/settings/developers) and you have to be logged in.

**Comment by gyllen** [comment]
@ybkuang Can we update link?

**Comment by ybkuang** [comment]
Updated README. @gyllen

**Comment by gyllen** [comment]
Thanks closing
