### ISSUE TITLE
Changing basemap resets filters

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2243]
### Basic information
* Platform: Web
* System/Browser: Ubuntu/Chrome

### Steps to reproduce behavior

 1. Apply user filter
 2. Change basemap

### Expected behavior

Filters remain the same after basemap switches.

### Actual behavior

The filters reset, showing the default view of the sequences (that is, all of them).

### Additional information

The same thing happens for time filtering and showing signs. It seems the easiest way to get the filters back to what is expected is to toggle the sign filter back and forth, rather than reentering the user or date.

**Comment by gyllen** [comment]
@pkoby Thanks for reporting. We will track this issue internally. Don't expect to be solved in the next couple of weeks. though.

**Comment by knikel** [comment]
@nickplesha fixed that, will be visible soon.
