### ISSUE TITLE
Pictures have wrong location

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_issues#2244]
### Basic information
- Platform: `iOS` 
- Version: `4.4.11` 
### Steps to reproduce behavior

I'm using version 4.4.11 app with iPhone4. I took pictures with Driving mode last weekend, but many of pictures has wrong location.

https://www.mapillary.com/app/index/tryl?lat=35.105448&lng=138.226062&z=17&pKey=UlWm4V2nzJKdi8eLH7xewA&focus=photo
https://www.mapillary.com/app/index/tryl?lat=35.097883&lng=138.235963&z=17&pKey=q06jxWnAwh07EcA0FA58dw&focus=photo
https://www.mapillary.com/app/index/tryl?lat=34.727014&lng=138.073923&z=17&pKey=DHesPQ8h29o8mVHC3EeM1A&focus=photo
- It's normal for several minutes from starting
- Several minutes after, It looked normal, but pictures has wrong location.(many pictures has same location, please look above sequences)
- In this state, I stopped car by a red light, but app kept taking pictures
- Then manually stop and start, It's normal for several minutes and repeat above-mentioned

**Comment by millenbop** [comment]
Do you still have this problem? We redid the camera implementation a while ago and hopefully this increased performance for iPhone 4.

**Comment by kudarisenmon** [comment]
Is version 4.6.5 require iOS 8? My iPhone 4 is iOS 7.1.2 (latest)

**Comment by millenbop** [comment]
Ah yes, iOS7 is no longer supported unfortunately. We will always try to support at least one version older (9.x), but right now two versions older (8.x). A lot of dependencies has dropped iOS7 support unfortunately.

**Comment by millenbop** [comment]
Not fixable, sorry, closing.
