### ISSUE TITLE
"Normalize sequence" doesn't set last photo's direction

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2245]
### Steps to reproduce behavior

Use the "Normalize sequence" function in the sequence editor.
### Expected behavior

All photos should turn to the sequence direction at that point.
### Actual behavior

The direction of the last photo is not changed.
### Additional information

The last photo should point in the same direction of the sequence segment preceding the photo. (I.e., the same direction as the second-to-last photo.)

**Comment by nickplesha** [comment]
This should be fixed now, thanks for reporting!
