### ISSUE TITLE
Upload stalls frequently on Android

### ISSUE THREAD

**Issue by katrinhumal** [mapillary/mapillary_issues#2246]
Issue from member `procrastigator`
### Basic information
- Platform: `Android`
- Version: `2.39` 
### Steps to reproduce behavior

Start upload after having captured photos
### Expected behavior

Photos will be uploaded without interruptions
### Actual behavior

Uploads tend to stall frequently and it's necessary to force restart them repeatedly
### Additional information

An example: 
- Launched upload of 88 pictures
- Few hours later, apparently blocked at 18 uploaded.
- After I launched another app, a notification appeared telling me 88 pics are ready for upload (which seems to mean it gave up on the previous upload).
- Relaunched upload
- Saw it go back up to 15, few minutes later checked again and at 2 out of 88
- About 1 hour later, once again notification that 88 pictures are ready for upload
- Relaunched overnight
- Morrow morning : 15 of 88
- This time launched upload of one sequence of 8 only, but while using phone unplugged from wall.
- Checking back about an hour later, message "Done, with problems. Phone not charging". Sequence of 8 still appearing in my sequences to be uploaded in the app.
- Launched same sequence of 8, with phone plugged-in this time.
- About an hour later, at 8 out of 8, no further progress as far as I can tell.
- After another while, still no change, canceled upload.

This is using the 2.39 version. My Internet quality is decent: I pay for a 10Mb/s dl 1Mb/s ul speed in theory, which in practice comes to about 8.81 Mb/s dl and 0.69 Mb/s ul (according to Ookla's speed test). It's nothing fantastic, but should be enough to get the job done (judging, for instance, by my uploads of pictures to Google photos).

I've attached the log file for 2 attempts, one overnight and one earlier this morning. I had selected a few sequences to upload at once for the overnight attempt, and only one small sequence for the morning attempt. The overnight attempt was stuck at something like 15 out of whatever (didn't take a note, sorry) when I woke up this morning, and the later attempt had a partway filled progress bar (which is interesting as I don't usually see any progress on the progress bar at all) at 8 out of 8, but was apparently stuck there.

After reviewing the log, I noticed "no sync preference. Not syncing" in the log. I wondered whether this could be due to my settings (although it would still seem weird that any settings would allow this kind of uploading behaviour) and I've checked the "sync on battery" (which I had deactivated as I did not want the app to launch the uploads automatically as soon as the phone was plugged in) and launched a new attempt (ongoing). We'll see if that goes any better.

[Logs_procrastigator_V239.txt](https://github.com/mapillary/mapillary_issues/files/458475/Logs_procrastigator_V239.txt)

**Comment by rsahlin** [comment]
We are re-writing the upload behavior.

A new version will be out to the beta group later this week (3.07) - please be patient and re-test when version 3.07 becomes available.

Best regards
/Richard
