### ISSUE TITLE
blur editor get confused with wrong blur overlay

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2247]
After editing some blurs on a track, the editor sometime load wrong blur overlays (from a different picture?).
See unedited photo in screenshot 
![bildschirmfoto von 2016-09-07 09 14 12](https://cloud.githubusercontent.com/assets/3539168/18303246/6bebd6ca-74dc-11e6-834e-e569940cbb93.png)

### Basic information
* Platform: `Web`
* Version: Firefox 45.3.0, Chromium 53.0.2785.89 (64-bit)
* System/Browser: Debian 8

**Comment by nickplesha** [comment]
@jotpe Thanks for reporting this bug! This might happen sometimes when the server is slow to respond and the blurs from the previous image are still there until the fresh blurs are loaded.

Can you still reproduce this issue? If so, could you please add some more detail about what actions lead to this result? Thanks!

**Comment by jotpe** [comment]
I blurred a lot since then, but I could not procedure it.

**Comment by gyllen** [comment]
Closing, reopen if it reoccurs

**Comment by jotpe** [comment]
It happens again, two minutes ago.
![unbenannt](https://cloud.githubusercontent.com/assets/3539168/18807789/bda667ba-8250-11e6-8924-72b0a7e26f81.png)
