### ISSUE TITLE
Web Enhancement: Points for edits/blurs/unblurs/angles

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#225]
I've noticed a lot of people upload and dont edit their photos (blur/unblur/fix angles). One way to help with this is to include it in the points system. Obviously a photo would be worth more points than an edit, but this could help so that we could have nice data that is accurate in every way

**Comment by sandrauddback** [comment]
Closing this as it is an old issue. We have many times discussed a Mapillary scoring system but for now taken the decision to not implement such. We acknowledge that there are still many things to improve to increase the quality of the images and are constantly working on those improvements.
