### ISSUE TITLE
navigation arrows pointing in the wrong direction

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2250]
On the first image there is an arrow pointing to the right direction. But it leads to the image in left direction... Same on the other image. 

https://www.mapillary.com/app/index/0m05YYyXAsdNYVJb3QoI6X?lat=50.901918&lng=7.021059&z=17&focus=photo&pKey=VH7PCL48_D9fufcQ7a_khg&menu=false
![bildschirmfoto von 2016-09-09 07 47 07](https://cloud.githubusercontent.com/assets/3539168/18376725/ca2f81ce-7661-11e6-9da3-75bf6caecf80.png)

https://www.mapillary.com/app/index/0m05YYyXAsdNYVJb3QoI6X?lat=50.901935&lng=7.020912&z=17&focus=photo&pKey=l2lssGiion4EBiVqTLTicg&menu=false
![bildschirmfoto von 2016-09-09 07 47 13](https://cloud.githubusercontent.com/assets/3539168/18376731/d4651316-7661-11e6-8375-3d30b21f9e13.png)

**Comment by jotpe** [comment]
Same road, two other sequences:

https://www.mapillary.com/app/index/oFFKpT51LkbLLKVekWD3VY?lat=50.902744&lng=7.021994&z=17&pKey=VJhfXzSgDjUaQZFGgJEbhA&focus=photo
![bildschirmfoto von 2016-09-15 20 23 17](https://cloud.githubusercontent.com/assets/3539168/18562006/63d1d758-7b82-11e6-98aa-4be34b9deb5c.png)

https://www.mapillary.com/app/index/oFFKpT51LkbLLKVekWD3VY?lat=50.902713&lng=7.022235&z=17&pKey=4zH6_51Y25o1ar8hnrRv6A&focus=photo
![bildschirmfoto von 2016-09-15 20 23 23](https://cloud.githubusercontent.com/assets/3539168/18562011/678329e2-7b82-11e6-9f34-c77b8f58c5a5.png)

**Comment by jotpe** [comment]
After moving images on the map the arrows are showing on the old neighbor position.
![bildschirmfoto von 2017-05-11 21-03-36](https://cloud.githubusercontent.com/assets/3539168/25967153/7602a2ba-368d-11e7-98ee-9555e9a82ded.png)

**Comment by jotpe** [comment]
I know I updated the image positions of this bicycle sequence with the web editor some months ago, because there was a hugh gps difference. Now the image positions are correct, but the arrows are still showing to the old positions whichs leads to two wrong animations.
https://www.mapillary.com/app/index/ifjj1ref?lat=50.91340996978502&lng=6.997288478702728&z=17&pKey=mpQdI9Q2u4yFw6QN-koU-A&focus=map
![bildschirmfoto vom 2017-08-04 15-31-00](https://user-images.githubusercontent.com/3539168/28970889-67848d18-792a-11e7-8224-de7adece9113.png)

**Comment by katrinhumal** [comment]
@jotpe I think something has updated now - this is what I see when I click on your link:

<img width="1275" alt="screenshot 2017-08-07 10 28 27" src="https://user-images.githubusercontent.com/16334352/29018421-4427dd10-7b5b-11e7-91c6-1de52571614b.png">

**Comment by jotpe** [comment]
Thanks. I can see it now, too. 
This seems to be a long and strange delay. Did somebody triggered a sequence reprocessing? I have even other sequences in same manner, which were corrected by me months ago and have still incorrect arrow directions.
https://www.mapillary.com/app/index/ifjj1ref?lat=50.878905&lng=7.122221&z=17&pKey=PRlky7Qmybx_hzpAMPIoRQ&focus=map&mapStyle=mapbox_streets
![bildschirmfoto von 2017-08-07 10-36-39](https://user-images.githubusercontent.com/3539168/29018705-6fb6cc2e-7b5c-11e7-9ee4-79bea928f7c8.png)

**Comment by katrinhumal** [comment]
@oscarlorentzon can probably give better insights on this one, referring to him.

**Comment by ybkuang** [comment]
@jotpe The direction of the image is dependent on the compass angle in the metadata of the images. Once our processing is run, it will be replaced with the data derived from our 3D reconstruction pipeline. However, the derived data from 3D reconstruction might not always been correct, so there can be some errors in case where the image sets are difficult for 3D reconstruction to work (i.e. when the image coverage is too sparse). 

I will close this issue for now and link it to our internal issue for general improvement of 3D reconstruction. Please report back if you observe similar behavior later.
