### ISSUE TITLE
Lost photos

### ISSUE THREAD

**Issue by Zverik** [mapillary/mapillary_issues#2251]
Hi,

Yesterday I was photomapping with Mapillary app, giving it a test drive. It worked mainly okay, but in the [resulting sequences](https://www.mapillary.com/app/user/zverik?lat=40.250206247635134&lng=23.253018471593663&z=17&pKey=u5gwHW1y2hAgW7nJIFegQg&focus=map&menu=false) I see a missing road. After Avenue 6 I walked though Avenue 5 and then to the start of the next sequence on Avenue 3.

Is it possible to recover it? It might have been lost on upload, or in the device. Not sure if there is a way to check it now.

**Comment by Zverik** [comment]
Sorry, they were just slowly processing, I see them now.
Turns out mapillary is great for photomapping :)

**Comment by peterneubauer** [comment]
Sorry, there were 440000 images coming in during the last 24h so it takes a few hours more right now ☺
