### ISSUE TITLE
Uploaded via web interface, can't see it now

### ISSUE THREAD

**Issue by Zverik** [mapillary/mapillary_issues#2252]
I've uploaded ~200 photos yesterday [around here](https://www.mapillary.com/app/user/zverik?lat=40.25034067119054&lng=23.247950543925754&z=16.634394533880794&pKey=4g-_Ar8rcR0ECzsngdgm6g&focus=map&menu=false) (Avenue 1 thorough Avenue 4), but today I cannot find it. Where are the photos?

(good thing I didn't delete these locally)

**Comment by pkoby** [comment]
Did you push the upload to publish at the end? If you visit https://legacy.mapillary.com/map/upload/im, you should see if there is an open upload.

**Comment by wimh** [comment]
I had the same problem with one upload from yesterday, and one upload from earlier today. The uploads also did not show up in the activity feed. But now they show up, both dated 2-3 hours ago. So it seems something was stuck, but it seems to be fixed for me. (they are not yet on the map, but I know that it takes some time).

**Comment by Zverik** [comment]
Yes, the reason was the big queue of photos to be processed. I've seen my photos in JOSM, not on the website yet, but I guess it's a matter of time. Thanks everyone.
