### ISSUE TITLE
Traffic signs sprite is broken

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2254]
All traffic signs are represented by the left top corner of this sprite: https://www.mapillary.com/homebrew-streets-v8/sprites.png

![selectie_150](https://cloud.githubusercontent.com/assets/1449609/18411254/270459fc-7774-11e6-9094-052945f52e7d.png)

**Comment by pkoby** [comment]
It's working normally for me, under the same conditions (EU, prohibitory).

**Comment by gyllen** [comment]
This should be fixed with latest deploy of website.
