### ISSUE TITLE
effect of new sequences on same area.

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2255]
Is there a recalculation of the smooth transition (struction for motion) when I change the location of images?
Are the positions of the images recalculated? Is there a kind of status viewable, like depending changes of neighbour images or something like that?

For example I have a smooth transition around the corner and a sequence without transition. The angle and motiv looks equal, but it seems to have no effect on the other sequence.
For example:
https://www.mapillary.com/app/?lat=50.902785&lng=7.022053&z=17&focus=photo&pKey=Dfv_OgqVcac5PpxKpozU0w&menu=false
https://www.mapillary.com/app/?lat=50.902669&lng=7.021974&z=17&focus=photo&pKey=N5APHLR5tunluieedtrnDw&menu=false

**Comment by gyllen** [comment]
Yes an update of position and bearing should affect the smooth transition.

**Comment by paulinus** [comment]
Yes, every time new images arrive, we match them against existing images and this can create new connections and improve the navigation of the previous images.

You can now see that after adding more sequences to the same corner, you can properly navigate between them.
