### ISSUE TITLE
does blur requests help for detection

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2256]
Do approved blur requests make the detection better? Are they used as training data for the algorithm?
If not this would be a bad user experience.

**Comment by de-vries** [comment]
yes: http://forum.mapillary.com/t/does-mapillary-team-use-the-blur-requests-for-training/545

**Comment by jotpe** [comment]
Are there some statistics available about the improvement?

**Comment by ybkuang** [comment]
This has been resolved by the new [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
