### ISSUE TITLE
"Normalize sequence" feature produces unwanted email notifications

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#2258]
### Basic information

Changing image directions based on the "Normalize sequence" feature produces email notifications, which I can't seem to disable.
### Steps to reproduce behavior
1. Use "Normalize sequence" feature on a sequence
2. Receive two email notifications: "You requested x new edits" and "You got 3 edits approved"
3. Wonder why you got these notifications.
### Expected behavior

I have only the following notifications enabled:
- Comment on your photo
- Mentioned in comment
- Comment in thread
- Upload fully processed
- Comment in your Geo Notifications
- Competition hashtags

I don't expect to receive these notifications.
### Actual behavior

I do receive the notifications.

**Comment by gyllen** [comment]
@peterneubauer We need to make it possible to turn off this notification

**Comment by peterneubauer** [comment]
Yes,
these are new notifications, wanted to wait until we get the refactored notification service out which will handle this much better.

**Comment by ltog** [comment]
Thanks @peterneubauer , looking forward to seeing this being fixed...

**Comment by peterneubauer** [comment]
Closing this, please let us know in the Forum if you have problems @ltog .
