### ISSUE TITLE
Some panoramas that have no business being such

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2261]
### Basic information
- Platform: `Web`

So using the awesome new Pano filter, I found a bunch of really long sequences in Romania. I was impressed that someone took such long pano sequences, but on viewing them, I found that they were weirdly distorted.

Here's the start of one such sequence: https://www.mapillary.com/app/?lat=45.13112683805556&lng=24.00534098027778&z=17&pKey=B917nxh6D1l_PeWOLhRe0A&focus=photo

When I download the photo, though, it looks simply like a wide-angle forward photo. Also, the mouseover thumbnail of the sequence or any of the photo points looks like a cropped version of the un-pano'd photo.

**Comment by ybkuang** [comment]
@pkoby Good find! That's one set of photos that we need to fix. We will reprocess them so that they will appear correctly.

**Comment by pkoby** [comment]
Might as well mention another thing. This sequence has some panoramas, but some normal photos. The whole sequence is tagged as a panoramic sequence, and the normal photos are displayed in the viewer at a much smaller scale (click next from this photo): https://www.mapillary.com/app/?lat=44.271419683333335&lng=-71.30101318333332&z=17&pKey=V7zmDamqpiOvoIcHFQt65w&focus=photo&menu=false

Also, this is a small change, but the filter now says "360 panoramas", but not all photos are actually 360°.

**Comment by simonmikkelsen** [comment]
@ybkuang Sequence Cc46yZEwXnXhtfqjQfbB1A (https://www.mapillary.com/app/?lat=56.07841226036089&lng=10.117729068282728&z=15.355823249249145&pKey=y0rnwBVsSjN7upJEyuIt4w&focus=map) seems to be a variation: It shows when the 360 filter is enabled and the image is rendered curved, but they are just normal images.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
