### ISSUE TITLE
Can't log in on Android without GMS: "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"

### ISSUE THREAD

**Issue by das-g** [mapillary/mapillary_issues#2263]
### Basic information
- Platform: `Android`
- Android version: `5.1`
- App version: Whatever the ["Latest APK" link](http://android-releases.mapillary.io/app-release_current.apk) on https://www.mapillary.com/ pointed to at `2016-09-13T10:47:00+0200`
- System: [`Fairphone Open 16.07.1`](code.fairphone.com/projects/fp-osos/) (i.e. an Android 5.1 without Google Mobile Services / Google Play Services)
### Steps to reproduce behavior
1. Sign up (i.e. create account) via Website
2. Start the app
   ![screenshot_2016-09-13-21-01-10](https://cloud.githubusercontent.com/assets/97746/18488141/76f1a952-79f8-11e6-84cc-cda84722a620.png)
3. On the app's welcome screen, tap the green "LOGIN" button
   ![screenshot_2016-09-13-21-01-16](https://cloud.githubusercontent.com/assets/97746/18488155/88409e16-79f8-11e6-9627-1dadf9c63447.png)
4. On the app's "ENTER YOUR PASSWORD" screen, fill in credentials used to sign up (email address & password)
   ![screenshot_2016-09-13-21-02-11](https://cloud.githubusercontent.com/assets/97746/18488319/285c1862-79f9-11e6-9913-3f7997b0a8dd.png)
5. Tap the green "Login" button
### Expected behavior

Login is successful and the next screen (whatever that is) is shown, so that I can use the app.
### Actual behavior

The message

> Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

appears and quickly disappears.
![screenshot_2016-09-13-21-03-08](https://cloud.githubusercontent.com/assets/97746/18488197/b7084be0-79f8-11e6-9742-d465afc33d74.png)

The "ENTER YOUR PASSWORD" screen remains visible, with the credentials staying filled in. Tapping the "Login" button again has the same effect: The message appears and quickly disappears and the app stays on the "ENTER YOUR PASSWORD" screen.
### Additional information

Even though my device AFAIK doesn't have Google Play Services, I **didn't** get the message

> Mapillary won't run without google play services

that is mentioned in #1399.

You've asked via Email/Zendesk:

> Also, did you sign up in the app or on the web? [...]

On the web. When trying to sign up with the "sign up" button of the app, I got a different error message.

> [...] And would you be able/willing to try weather you could log in through Facebook?

No. I'd try [login through OpenStreetMap](https://wiki.openstreetmap.org/wiki/OAuth), though, if that were available.

> 

Where would I find logs for this?

**Comment by das-g** [comment]
With the APK [app_release_current.apk](http://android-releases.mapillary.io/app_release_current.apk) downloaded 2016-09-25 (which was not the same as the [app-release_current.apk](http://android-releases.mapillary.io/app-release_current.apk) linked as "Latest APK" on the frontpage; note `-` vs. `_`), I'm getting a different, more comprehensible error message already on app startup:

> Get Google Play services
>
> Mapillary won't run without Google Play services, which are missing from your phone.

![screenshot_2016-09-26-12-58-44](https://cloud.githubusercontent.com/assets/97746/18864694/c56f882a-8497-11e6-8001-5a73b3247f85.png)

Whether I try to dismiss the prompt (by tapping outside the message box) or try to act on it (by tapping on "GET GOOGLE PLAY SERVICES"), the box disappears with the message "google connection failed":
![screenshot_2016-09-27-10-32-51](https://cloud.githubusercontent.com/assets/97746/18865936/fbf2d45a-849d-11e6-8ffd-f0472cbb429b.png)

In either case, the app lets me proceed anyway. If I tap "LOGIN" and then "Regular Email" I get the same behavior as [originally described](https://github.com/mapillary/mapillary_issues/issues/2263#issue-176731487) (from reproduction step 4 forward).

I'll test login via OpenStreetMap later.

**Comment by peterneubauer** [comment]
Should be working now?
