### ISSUE TITLE
delete requests are not processed

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2264]
I requested to delete some of my sequences from last year, because there was a gps offset in the mapillary app. But none of my delete requests get succeded.

**Comment by peterneubauer** [comment]
When did you request them?

**Comment by jotpe** [comment]
I think the first about two weeks ago.

**Comment by gyllen** [comment]
@peterneubauer Will you check and see what we have in the database.

@jotpe Also now that we are working on making your requested, approved and rejected changesets more visible so you can know exactly the state of stuff you are working on.

**Comment by jotpe** [comment]
Cool. When do you plan to release that feature?

**Comment by peterneubauer** [comment]
@jotpe I can't find any changesets that you requested. Can you please submit one and forward the email you get back to me?

**Comment by jotpe** [comment]
I received 3 emails with 15, 4 and 2 with edits approved subjects this afternoon. The links of last 2 emails don't load sequences, so I guess that are responses to my delete requests. Having a look at the map, it seems really that they have been deleted. Thanks.

What was the problem?

**Comment by peterneubauer** [comment]
Problem was that we hadn't really started approving deletion changesets. Now things should be working. Thanks!
