### ISSUE TITLE
ios app stops capturing when losing focus

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2265]
the ios app (latest version, iphone6) sometimes stops capturing when losing the focus.

in older versions, this happened very frequently - for example, receiving the call wouldn't resume capturing after the call was over.
in recent versions this is much better, but the app still often stops capturing when manually switching between mapillary and other apps (navigation etc).

the driving mode is still on, but no images are captured. stopping & starting doesn't help, restarting the app does. it's hard to notice that this has happened when waiting at a traffic light, as this "stopping" looks the same as not taking images when not moving.

it's quite annoying and i didn't take a few hundreds of images today because of this problem, but i'm not sure how easy would that be to test, and/or whether there could be some useful logfiles when the problem is reproduced.

**Comment by millenbop** [comment]
Sorry to hear about the problems. 

Just to clarify. Do you mean that you start capture, switch to another app, then switch back to Mapillary and that then capture is weird?

Or that you start capture, stop capture but leave camera view open, switch to another app, then switch back to Mapillary and that then capture is weird after starting it again?

**Comment by richlv** [comment]
start capture; switch to another app; switch back.
sometimes capturing auto-resumes, sometimes it does not - even though the app shows the "orange button"

**Comment by millenbop** [comment]
Thanks, I'll look into it and hopefully I can replicate it and fix it. This is using the internal camera right?

**Comment by richlv** [comment]
yep, the internal camera. only observed in the 'driving' mode (but not really tested in the 'walking' mode)

**Comment by millenbop** [comment]
The only difference is that we check the speed (from GPS) and start/stop capture based on that. But that could be the problem, that speed is reported as slow. 

So far I have been trying to reproduce it using walking mode but it seems to work.

**Comment by richlv** [comment]
is there a way to enable detail view like in the android app ? if the reported speed would be displayed onscreen all the time, i could try to test that possibility.

**Comment by millenbop** [comment]
Nope, not at the moment sorry, but that might be useful in the future. Not sure that's the problem though, just a possibility :)

**Comment by nicolas17** [comment]
Related: #1882.

I haven't seen this problem happen again since #1882 was fixed; but that doesn't mean I tested and confirmed it doesn't happen, maybe it did and I didn't notice.

**Comment by richlv** [comment]
yes, that's pretty much that issue, just happening much less frequently now

**Comment by millenbop** [comment]
We have now the "auto" mode which uses position instead of speed/timing. Do you still experience problems like before?

**Comment by richlv** [comment]
thanks for the reminder - this weekend was seeing the app lose the focus, then resume taking photos successfully several times, so all looks good now, closing :)
