### ISSUE TITLE
approved changeset is unchanged

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2266]
Another strange example: I edit this very small sequence, because their locations were in the opposite order. In my dashboard it is listed as approved at September 12, 2016 08:24, but it is unchanged...

https://www.mapillary.com/app/edit/gOsHYXdXphGasRUEGXET8h?lat=50.8991499285022&lng=7.0307165470968584&z=19.138384970180816&pKey=cpyHuADLABAAsdyKEhcnWg&focus=map&menu=false

Maybe related to #2264 ?

**Comment by gyllen** [comment]
@peterneubauer Can we investigate why this changeset was NOT apllied?

**Comment by jotpe** [comment]
Now this changeset is applied.

**Comment by gyllen** [comment]
Perfect, closing
