### ISSUE TITLE
GPSTimeStamp doesn't have actual GPS time

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2270]
### Basic information
- Platform: `iOS`
- Version: 4.4.12
- System: iPhone 6, iOS 9.0.2
### Details

In the past, when taking photos with the iPhone internal camera, the `GPSTimeStamp` and `GPSDateStamp` keys in the EXIF of the photos were from the actual location timestamp:

```
$ for f in 2016_??_??_??_??_??_???.jpg; do echo $f $(exif -m -t "GPSDateStamp" $f) $(exif -m -t "GPSTimeStamp" $f); done;
2016_02_06_14_32_02_356.jpg 2016:02:06 14:32:02,00
2016_02_06_14_32_03_253.jpg 2016:02:06 14:32:03,00
2016_02_06_14_32_04_238.jpg 2016:02:06 14:32:04,00
2016_02_06_14_32_05_271.jpg 2016:02:06 14:32:05,00
2016_02_06_14_32_06_254.jpg 2016:02:06 14:32:06,00
```

Which didn't necessarily match the timestamp of the picture, since the app could have lagged when saving the picture, the device could have lagged getting the location (bad GPS signal?), or... whatever it is that causes these minor offsets:

```
2016_02_06_15_20_20_316.jpg 2016:02:06 15:20:20,00
2016_02_06_15_20_23_131.jpg 2016:02:06 15:20:21,00
2016_02_06_15_20_24_869.jpg 2016:02:06 15:20:23,00
2016_02_06_15_20_26_609.jpg 2016:02:06 15:20:25,00
2016_02_06_15_20_28_234.jpg 2016:02:06 15:20:25,00
2016_02_06_15_20_29_764.jpg 2016:02:06 15:20:26,00
2016_02_06_15_20_30_284.jpg 2016:02:06 15:20:27,00
2016_02_06_15_20_31_680.jpg 2016:02:06 15:20:31,00
2016_02_06_15_20_32_770.jpg 2016:02:06 15:20:32,00
2016_02_06_15_20_33_666.jpg 2016:02:06 15:20:33,00
```

Since the new camera stuff was introduced, the .jpg files have no GPS information in the EXIF at all after taking the pictures. The location is stored in separate JSON files. The "Add Mapillary data" button makes the `GPSLatitude` and `GPSLongitude` EXIF tags be filled with the information stored in the JSON.

The problem is that during this processing, **`GPSTimeStamp` is filled from the current time**, ie. the time the photo had its EXIF processed by "Add Mapillary data":

```
2016_07_21_14_17_48_570.jpg 2016:07:21 19:59:59,51
2016_07_21_14_17_51_303.jpg 2016:07:21 20:00:00,87
2016_07_21_14_17_53_901.jpg 2016:07:21 20:00:02,16
2016_07_21_14_17_55_551.jpg 2016:07:21 20:00:03,45
2016_07_21_14_17_56_763.jpg 2016:07:21 20:00:04,76
2016_07_21_14_17_57_663.jpg 2016:07:21 20:00:06,07
2016_07_21_14_18_00_327.jpg 2016:07:21 20:00:07,37
2016_07_21_14_18_01_649.jpg 2016:07:21 20:00:08,66
2016_07_21_14_18_02_621.jpg 2016:07:21 20:00:09,95
2016_07_21_14_18_03_801.jpg 2016:07:21 20:00:11,25
```

Which could even be days later! Here the DateStamp was affected too:

```
2016_07_23_16_57_10_555.jpg 2016:07:25 01:12:14,44
2016_07_23_16_57_11_989.jpg 2016:07:25 01:12:15,72
2016_07_23_16_57_13_492.jpg 2016:07:25 01:12:17,02
2016_07_23_16_57_14_995.jpg 2016:07:25 01:12:18,31
2016_07_23_16_57_16_493.jpg 2016:07:25 01:12:19,62
```

The real GPS timestamp isn't stored in the JSON, so this information is lost and the metadata-adding process doesn't actually have anywhere to take it from.

I haven't tested what happens with the `GPSTimeStamp` if I take pictures and directly upload them from the app, since I don't currently have any metadata-less un-uploaded photos in the app (and I don't want to take pictures of my wall and upload them to the real server just to test :sweat_smile:).

I think the app should save the actual GPS time (was this from `CLLocation.timestamp` before?) in the split JSON metadata so it can be saved to the `GPSTimeStamp` tag during post-processing. If this is not possible, then don't write the `GPSTimeStamp` EXIF tag at all! The value the app is currently writing to it is not useful for anything.

**Comment by millenbop** [comment]
Finally got around to fixing this one. Was gonna do it when I did the move to GPX but since it hasn't happened yet I fixed this in the meantime. 

Will be out in the next release.
