### ISSUE TITLE
Change password doesn't send instructions

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2271]
Clicking the button _send me instructions_ for password reset does not deliver an email to me. My email adress is correct.

**Comment by millenbop** [comment]
Thanks for reporting!

Is this for web or iOS or Android?

**Comment by jotpe** [comment]
Sorry, via website ( clicked...)

**Comment by kdudzik** [comment]
I can confirm that - fortunately the "Having trouble signing in? Click here." option works so that's the only way to change your password now.

**Comment by gyllen** [comment]
Thanks for reporting, we are fixing.

**Comment by nickplesha** [comment]
@jotpe The "send me instructions" button is now working as expected. Thank you for reporting this!
