### ISSUE TITLE
API used by JOSM to submit changesets doesn't reply

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2274]
The Mapillary plugin for JOSM allows moving and rotating photos, and submitting it as a changeset to Mapillary. But the Submit button just hangs.

I found what HTTP request it was trying to do, and tried doing the same from the command line:

```
curl -v -d '{"change_type":"location","changes":[{"image_key":"NhJcSy1VGwAXLBm5HyxfvA","values":{"from":{"ca":104.7223,"lat":-34.754874,"lon":-58.401273},"to":{"ca":104.7223,"lat":-34.75470541687122,"lon":-58.401242154596346}}}],"request_comment":"JOSM-created"}' \
-H "Authorization: Bearer <OAUTH_TOKEN_HERE>" \
https://a.mapillary.com/v3/changeset?client_id=T1Fzd20xZjdtR0s1VDk5OFNIOXpYdzoxNDYyOGRkYzUyYTFiMzgz
```

This gets stuck waiting for a response for about five minutes, and then finally responds with "504 Gateway Time-out".

Making edits from the web app uses a totally different API (a method call to `/v3/model.json`).

**Comment by peterneubauer** [comment]
This is a REST API since the normal Falcor API does not have a Java Client (yet). Will investigate with @gyllen .

**Comment by peterneubauer** [comment]
Bump @ptpt @gyllen what is the ETA on getting support for changeset submission in v3 API? Would love to use that instead.

**Comment by gyllen** [comment]
@peterneubauer Should be in `V3` by now

closing
