### ISSUE TITLE
Image editor freezes randomly

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2275]
### Basic information
- Platform: `Web`
- Version: `Windows 8.1`
- System/Browser: `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36`
### Steps to reproduce behavior
1. Select a sequence and edit it.
2. Move pictures to other locations.
3. At random point (roughly every 20th edit) the site becomes non reactive.
4. The error message on the screenshot is always shown when this happens.

When reloading the site and retrying, there are no issues with the specific image.
### Expected behavior

Site should not be non reactive.
### Additional information

The error message:

main-9f4ee8bdbb44c3985f1ef48eaa6c29c9.js:38 TypeError: Cannot read property 'reload' of undefined(…)onError @ main-9f4ee8bdbb44c3985f1ef48eaa6c29c9.js:38

is always shown (see screenshot) when this happens. The other messages vary a lot: Only the last one is consistent. On the screenshot I have clicked on the link main-...js:38 and the result is shown in the frame just above the console.

![reload_of_undefined](https://cloud.githubusercontent.com/assets/8446338/18707417/3e992c8e-7ff6-11e6-8fda-42c9ba63a432.png)

I use a pretty powerfull computer, with lots of power and RAM. Its only fault is that it runs Windows.

**Comment by gyllen** [comment]
Thanks for reporting we are investigating

**Comment by nickplesha** [comment]
@simonmikkelsen We've updated to the latest version of `mapbox-gl` and made some changes with map performance in mind. Can you check if you can still reproduce this behaviour?

**Comment by nickplesha** [comment]
Closing this for now, please reopen if issue occurs again,
