### ISSUE TITLE
blur editor shows little black gaps in the image

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2276]
I edited blurs on a few hundred images and then this small little gaps appear. Moving to the next image flush them away.

![bildschirmfoto von 2016-09-24 12 01 53](https://cloud.githubusercontent.com/assets/3539168/18807745/ad154dea-824f-11e6-9de5-3442632452ce.png)

Chromium Version 53.0.2785.113 Built on 8.5, running on Debian 8.6 (64-bit)

**Comment by nicolas17** [comment]
I have seen this happen in the normal viewer, outside the blur editor, during a SfM transition. But it happened rarely, and when it happened it was brief (less than 1 second).

**Comment by oscarlorentzon** [comment]
The `mjs` instance is the same in both the regular view and the blur editor, we are just switching rendering mode between letterbox and fill, so if this happens it could happen in both views.

I have not seen this issue myself, but something is apparently happening in WebGL that causes this. 

Update this issue if this starts to happen frequently.

**Comment by ybkuang** [comment]
I will close this now. Please report back if it reappears.  Thanks @jotpe @nicolas17
