### ISSUE TITLE
Android app won't record sequences. 

### ISSUE THREAD

**Issue by paulb20** [mapillary/mapillary_issues#2277]
### Basic information
- Platform: `Android`
- Version: `2.40` 
- System/Browser: `4.1.2`
### Steps to reproduce behaviour
1. Fix phone to bike
2. Open Mapillary
3. press Camera
4. Press button to start
### Expected behaviour

 Starts taking pictures
...
### Actual behaviour

Only takes pictures when hit a bump and the phone is shaken strongly
...
### Additional information

Phone is Samsung Galaxy S2. Which has worked for Mapillary purposes since being superseded as main phone.

... 

Just look at my recent uploads (paulbiv). All the pictures are 
1. Upside down
2. Very shaky.
3. No usable sequences

**Comment by peterneubauer** [comment]
@paulb20 what happens if you disable the shake detector in the settings?

**Comment by paulb20** [comment]
Tried that this morning. Didn't work. Got 1 picture (of my hedge) which is practically useless.

Did use up all my battery in under 30 minutes though (may be having problems with GPS).

Waiting for new phone to arrive (Samsung exploding variety) and will see what that does.

**Comment by ovivoda** [comment]
@paulb20 Is this still an issue?

**Comment by paulb20** [comment]
Not at the moment, though I expect that continuing to support ancient hardware will produce problems in the future.
