### ISSUE TITLE
Openstreetmap login broken in iOS app on iOS 10

### ISSUE THREAD

**Issue by nickel715** [mapillary/mapillary_issues#2279]
### Basic information
* Platform: `iOS`
* Version: `latest` I don't know, the version is [not shown](https://cloud.githubusercontent.com/assets/148483/18866220/43ebdb16-849f-11e6-8f56-6e02c51a8945.PNG) in the app nor the app settings 
* System/Browser: `iOS 10.0.1 | iPhone 6`

### Steps to reproduce behavior

 1. download app from app store
 2. tap login
 3. choose openstreetmap

### Expected behavior

Get logged in

### Actual behavior

Error in the app after redirecting from openstreetmap.org to the app

* [error screenshot](https://cloud.githubusercontent.com/assets/148483/18864577/49f03f78-8497-11e6-80ee-fb094ee039d8.PNG)

**Comment by millenbop** [comment]
Thanks for reporting! Have you created an Mapillary account first, as in registered using OSM?

**Comment by nickel715** [comment]
Yes. First I tried to register in the app using osm, after this also doesn't work, I created an maillary account using my osm account on the website

**Comment by millenbop** [comment]
Thanks! We'll have a look asap!

**Comment by nickel715** [comment]
Thank you!
Btw: I also uploaded a [screenshot](https://cloud.githubusercontent.com/assets/148483/18866220/43ebdb16-849f-11e6-8f56-6e02c51a8945.PNG) of the settings panel which also looks broken

**Comment by millenbop** [comment]
Thanks! I don't think it's related, but more info is always better!

For the time being until I have solved the OSM issue, you can still use the app. Just use email and password you used on the website when registering.

**Comment by millenbop** [comment]
Ok, have found and fixed the problem now. It appears that the OSM website stores a cookie and if you try to give an application access more than once and the cookie exists (which happens every time you login to OSM, which is not common practice...), it will fail. So solution is to either clear the browser cache every time or save the token for future use. Option B is better.

So now I store the access tokens securely in the keychain and logs in using that. Submitting fix today so should be out in a few days.

Thanks again for reporting!

**Comment by nickel715** [comment]
I downloaded the new version today. The osm login works instant (without redirecting to safari). Thanks a lot!

**Comment by millenbop** [comment]
Happy to hear :)
