### ISSUE TITLE
Sequence editor isn't responding anymore after changing basemap-layer

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2280]
### Basic information
- Platform: `Web`
- System/Browser: `Ubuntu 16.04/Google Chrome 53.0.2785.101 (64-bit)`
### Steps to reproduce behavior
1. Start sequence editor
2. Move a few points around
3. Change basemap-layer
4. Try to move further points
### Expected behavior

After changing basemap-layer the sequence editor should still working.
### Actual behavior

Can't drag any point after changing basemap-layer.

**Comment by nickplesha** [comment]
@descilla Thanks for reporting this, it has been fixed.
