### ISSUE TITLE
iOS app feature request: Change basemap-layer

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2281]
Changing the basemap-layer like possible on the website would be very useful for mapping. Especially  the default OSM (mapnik) layer has a lot of more details than the Mapbox Streets layer. For example driveways and tracks looks the same on Mapbox Streets.

**Comment by millenbop** [comment]
Good suggestion, thanks!

**Comment by millenbop** [comment]
This was released a few versions ago, closing.
