### ISSUE TITLE
Search API returns "more" when there are no more pages

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2282]
### Basic information
- Platform: `Web`
### Steps to reproduce behavior
1. Fetch https://a.mapillary.com/v2/search/s?max_lat=55.13&max_lon=10.81&min_lat=55.10&min_lon=10.76&limit=50&page=0&client_id=**** with a proper API key.
2. 6 sequences are returned.
3. Returns is also "more": true, which means that there is data on the next page.
4. Fetch page 1.
### Expected behavior

More data.
### Actual behavior

No data.

What I expect is, that if I request N sequences and gets less than that (or even the exact number but there are no more), 'more' is set to false. It looks to me like 'more' is set to false when no data is found for the query, making 'more' redundant.

**Comment by gyllen** [comment]
@simonmikkelsen This is clearly wrong (will investigate). Just a heads up though we are gonna start deprecating these APIs and encourage use of vector tiles instead. I want to know how you feel about that as an API user.

**Comment by katrinhumal** [comment]
I'm not so knowledgeable about the API myself, but wanted to check if this issue is still relevant now that there is API v3 etc. or can we close?

**Comment by gyllen** [comment]
This concerns now obsolete API `v2` so closing
