### ISSUE TITLE
Accept simultaneous connections from more than one device

### ISSUE THREAD

**Issue by tuliogit** [mapillary/mapillary_issues#2283]
### Basic information
- Platform: Android 4.4.4
- Version: 2.40
### Steps to reproduce behavior
1. Take sequences with one phone
2. Take other sequences with another phone
3. When arriving home, try to upload all of your sequences from both phones.
### Expected behavior

I expect a smooth simultaneous upload from both phones.
### Actual behavior

It seems that only the first phone that gets connected to Mapillary servers uploads the sequences it has. The other one seems not to upload, and it doesn`t even give me an error or warning message.
### Additional information

I expect that Mapillary servers accept connections from more than one device. If not, the phone app should at least warn the user that the connection was denied because it doesn`r allow simultaneous connections.

**Comment by richlv** [comment]
what happens with the images on the second phone ? are you able to upload them after the first one has finished, or are they lost ?

**Comment by peterneubauer** [comment]
Hi there,
the upload is really just happening to Amazon S3 without any authentication involved from Mapillary (the upload token in the image description is constant and transferred at login time)

Are you sure that the second phone is not refusing upload for other reasons like slow network because the first one took all bandwidth or so?

**Comment by tuliogit** [comment]
@richlv They're not lost. They are uploaded, but never in two simultaneous threads. What always happened in the few times I did use both phones is that the one that got connected first got it going, and the other one didn't start neither prompted me with any error message.

@peterneubauer I'm not really sure it doesn't upload for other reasons. But I can say that I never saw them uploading simultaneously. And I really tried to check what was happening. I got the one that was "stalled", cancelled uploading and tried again. It only started working after the first one had finished.

**Comment by jfburke3** [comment]
I'm somewhat certain that I've been able to upload from 2 phones at the same time, but I'll re-try this when I get a chance to be sure.

**Comment by katrinhumal** [comment]
@tuliogit and @jfburke3 would it be possible for you to test this and update us on whether this is still a problem? Thanks!

**Comment by katrinhumal** [comment]
@ovivoda any comments for closing?

**Comment by peterneubauer** [comment]
As far as we can see and test, you can be logged in and send photos from 2
different phones. Please reopen if not working.
