### ISSUE TITLE
Title text hard to read in Solutions page

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2285]
In the [Solutions](https://www.mapillary.com/solutions) webpage, there is a background photo with a building under construction. This has sharp, light-colored details from the tube scaffolding around the building, and it makes the white text hard to read.

![Screenshot of Solutions page](https://cloud.githubusercontent.com/assets/101955/19018949/6d0c112e-884a-11e6-9a08-ed53dbde28ea.png)

The readability might be improved by changing the text weight, or adding a black shadow to the white text; but I played a bit with the CSS properties and didn't manage to get the improvement I expected. Easiest would be to just change the photo...

**Comment by angelday** [comment]
> Easiest would be to just change the photo...

Yup! Pinging @octanebaby and @madelenarnesdotter let's see if they have some ideas regarding a less busy header image.

**Comment by kardotim** [comment]
Just to put on your radar for the future. I think it might also be good to at some point to think more about web accessibility.

**Comment by angelday** [comment]
@kardotim 

> I think it might also be good to at some point to think more about web accessibility.

What do you have in mind, Karim?

**Comment by kardotim** [comment]
> What do you have in mind, Karim?

"_The Web is fundamentally designed to work for all people, whatever their hardware, software, language, culture, location, or physical or mental ability. When the Web meets this goal, it is accessible to people with a diverse range of hearing, movement, sight, and cognitive ability._"

I think this is a great goal to strive for, in whatever time period, just food for thought :) Here's some interesting documentation too:

https://www.w3.org/standards/webdesign/accessibility
https://www.w3.org/WAI/intro/wcag.php
https://www.w3.org/WAI/intro/people-use-web/

**Comment by nicolas17** [comment]
It seems this page is gone altogether?

**Comment by nickplesha** [comment]
@nicolas17 Yes, the page has been replaced with https://www.mapillary.com/product
