### ISSUE TITLE
Sequence is not complete. Photos exist but route along photos are missing.

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2286]
[This photo](https://www.mapillary.com/map/im/Kg4KIj44FTKHNSrktT9EWg) is missing the mote of the sequence trace.  I tried to reset the sequence.  [Right now the sequence dead ends here.](https://www.mapillary.com/app/?focus=photo&pKey=Kg4KIj44FTKHNSrktT9EWg&lat=33.60910678947293&lng=-112.00929044401288&z=19.461058338669265)  I would expect the trace to show up [here](https://www.mapillary.com/app/?lat=33.669277076661785&lng=-111.90954631756289&z=17.15347399168121).  The image takes me here in [JOSM](https://www.mapillary.com/app/?lat=33.60769003863328&lng=-112.00945836110047&z=17.86774747359744).  I had no problems with the rest of my photos yesterday, 10/1/2016.

**Comment by peterneubauer** [comment]
It seems the photos are on exactly the same spot. Maybe the GPS stopped working or so? Also, we will cluster photos on the same spot better so you can see this. Try editing them and move them part to see it.
