### ISSUE TITLE
don't show spinner after submitting blurs for the last image

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2287]
edit blurs on the last image on a sequence, submit them - spinner is shown, as if mapillary was trying to load something else.
this is misleading, and ideally a message "last image in the sequence reached" would be displayed instead

**Comment by nicolas17** [comment]
It's almost certainly a bug, there is a Javascript error in the console when this happens.

**Comment by gyllen** [comment]
@nicolas17 Thanks for looking deeper into this, issue is tracked as bug and will be fixed shortly.

**Comment by nickplesha** [comment]
@richlv Thanks for reporting this, it has been fixed.

**Comment by richlv** [comment]
cool, thanks :)
