### ISSUE TITLE
Are all edits gone or is approval just lagging?

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2288]
Edits done between summer last year and the launch of the new system this summer, are they gone forever or does it  just take time to approve them?

**Comment by gyllen** [comment]
@peterneubauer At this point all old changesets should have been approved right?

**Comment by echeloni2p** [comment]
They should have been approved, but there is no real way to check, as there is no list of changesets and approved date.

echelon

**Comment by Andblue** [comment]
When I am looking at my edited sequences it looks like most of them have not been approved. In the old system they where locked waiting to be approved, but in the new system the lock is gone.

I am not sure to what extent, I am mostly basing it on parts of the map that I visit often.

**Comment by peterneubauer** [comment]
I agree, we need to surface the changesets that are currently affecting an image, and for a user to see the list of audited/pending changesets.

The locking can be re-arranged, we were thinking of adding the info non-locking in edit mode (like "this image is part of 2 pending changesets" or something similar). WDYT @gyllen ?

**Comment by peterneubauer** [comment]
This should be solved now, Closing. Please let u know if not @Andblue
