### ISSUE TITLE
Driving mode timing

### ISSUE THREAD

**Issue by sabas** [mapillary/mapillary_issues#229]
What about using variable capture times instead of fixed one?
Currently you can set "take a picture each 2 secs", and the app stops when your speed goes under a threshold (so you take in account the speed derived from gps).
What about a setting which is proportional to the speed? (more frequent when going faster, less when going slower)

**Comment by pyrog** [comment]
In car at 90 kph, 2 secs is to slow so we "miss" junctions, traffic signs…

* :+1: for proportional speed (picture each **XX meters**)    
or
* **In developper mode, allow lower delay** between shots (0.5s, 1s…)    
or
* **Allow manual triggering** between shots (**by pressing a key** on the phone, or better, a key **on the remote** of "action" camera)   
![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTDqCsykPueGgo6f_HRKdPMMD9z_GHfuvS7OHxbuICHjUJbyRdbwg) ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLFPSbMTTVJAFMwxp82Yb5etGUbb4C7AQH9XWmUm5TqOubue3afw) ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUmJgQeFKXJU66Flk6S_PSOZD68Y9Bt0ZzSQ9FUmo86EFktAa5)

**Comment by jesolem** [comment]
@pyrog If the phone cannot take photos faster than say 2s, then none of the 3 cases will work, not even pressing a button manually. It is restrictions in HW and ISP throughput that sets the limit for each device. 

@peterneubauer will extend the threshold down from 2s but as commented above, it will not do anything for devices that cannot handle that frequency. Then the phone will take as fast as possible.

**Comment by pyrog** [comment]
@jesolem You're right :smile: 
For slow smartphones, don't set the delay below the minimum supported by the hardware :wink: 

For exemple in walking mode:
 1. set the delay to 10 sec and start a new sequence
 1. the app take automatically a picture
 1. after 3 sec, press the "remote"  button, the app take a picture and restart the delay
 1. after 1 sec, press the "remote": the app wait 1 more second to take a picture (to wait the minimum delay), and restart the counter
 1. …

**Comment by pyrog** [comment]
same as #247 ?

**Comment by pyrog** [comment]
**Note:** "remote control" tested successfully with an **earphone** and a **bluetooth keyboard** (`F10` and `F11` keys)

**Comment by millenbop** [comment]
Closing this old issue as we have location based capture now.
