### ISSUE TITLE
No position marker on a review sreen

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#2292]
### Basic information
- Platform:  `Web`
- System/Browser: `windows 7, chrome 53`

After upload a picture with drop into browser window there no marker of position on card - impossible to correct position, nothing to drag
![mapillary crowdsourced street photos1](https://cloud.githubusercontent.com/assets/325961/19082827/6e3461da-8a68-11e6-9f76-e7ad529d6bf1.png)

Javascript console contain errors (I clean it before enter upload page)

`2/vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ (program):43ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423_update @ /main-955e6e4eb1c4671e3681ffaa029972af.js:38fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_onSourceUpdate @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:36fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35c @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35c.onload @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39wrapFn @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:769ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356onInvokeTask @ /main-955e6e4eb1c4671e3681ffaa029972af.js:55ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:355Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423
10/vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ (program):43ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423_update @ /main-955e6e4eb1c4671e3681ffaa029972af.js:38fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_onSourceUpdate @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:36fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35d.receive @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356onInvokeTask @ /main-955e6e4eb1c4671e3681ffaa029972af.js:55ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:355Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423
2/vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ (program):43ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423_update @ /main-955e6e4eb1c4671e3681ffaa029972af.js:38fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_onSourceUpdate @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39_forwardSourceEvent @ /main-955e6e4eb1c4671e3681ffaa029972af.js:36fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35fire @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35(anonymous function) @ /main-955e6e4eb1c4671e3681ffaa029972af.js:35d.receive @ /main-955e6e4eb1c4671e3681ffaa029972af.js:39ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:356onInvokeTask @ /main-955e6e4eb1c4671e3681ffaa029972af.js:55ZoneDelegate.invokeTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:355Zone.runTask @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:256ZoneTask.invoke @ /vendor/zone.js/dist/zone-2222385d52aafe3cf4568d0173483fc6.js:423
https://d25uarhxywzl1j.cloudfront.net/v0.1/14/9300/6476.mvt Failed to load resource: the server responded with a status of 403 (Forbidden)`

**Comment by nickplesha** [comment]
@iav Thanks for reporting! Have you been able to upload your images in the meantime? 
I've been trying but I'm unable to reproduce this exact error and looking at the message it seems the problem occurred in on of the external libraries we use, possibly caused by the `403` response there in the error list. If you can reproduce this consistently, let us know so we can take a better look.

**Comment by iav** [comment]
Just now:
open and clead console
open "upload" tab,
press "uloader" button
drop into browser jpg
press "review" button on popup
make some zooms
drag red circle from popup to map

circle drags, but lost on drop.
then I send you a log:
`mapillary-js.min.js:15 THREE.WebGLRenderer 80
3zone-2222385….js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ VM429:45ZoneDelegate.invokeTask @ zone-2222385….js:356Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423_update @ main-b914ef5….js:38fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:39_onSourceUpdate @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:35(anonymous function) @ main-b914ef5….js:35d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
3zone-2222385….js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ VM429:45ZoneDelegate.invokeTask @ zone-2222385….js:356Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423_update @ main-b914ef5….js:38fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:39_onSourceUpdate @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36c @ main-b914ef5….js:36c.onload @ main-b914ef5….js:40wrapFn @ zone-2222385….js:769ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
12zone-2222385….js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ VM429:45ZoneDelegate.invokeTask @ zone-2222385….js:356Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423_update @ main-b914ef5….js:38fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:39_onSourceUpdate @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36c @ main-b914ef5….js:36ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/5/17/13.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/5/17/13.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/9/291/203.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/9/291/203.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/9/292/203.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/9/292/203.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/9/291/201.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/10/581/403.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/10/581/403.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/10/582/403.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/10/582/403.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/11/1163/807.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/11/1163/807.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/11/1162/807.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/11/1162/807.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/12/2327/1616.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/12/2327/1616.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/12/2326/1616.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/12/2326/1616.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/13/4652/3235.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4652/3235.mvt 403 (Forbidden)
d25uarhxywzl1j.cloudfront.net/v0.1/13/4653/3233.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4653/3233.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/13/4652/3233.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4652/3233.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
d25uarhxywzl1j.cloudfront.net/v0.1/14/9306/6468.mvt:1 GET https://d25uarhxywzl1j.cloudfront.net/v0.1/14/9306/6468.mvt 403 (Forbidden)
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardTileEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
main-b914ef5….js:40 Error: Forbiddenfire @ main-b914ef5….js:40_tileLoaded @ main-b914ef5….js:36c @ main-b914ef5….js:36d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
3zone-2222385….js:260 Uncaught TypeError: node.getElementsByTagName is not a function(anonymous function) @ VM429:45ZoneDelegate.invokeTask @ zone-2222385….js:356Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423_update @ main-b914ef5….js:38fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:39_onSourceUpdate @ main-b914ef5….js:39fire @ main-b914ef5….js:40_forwardSourceEvent @ main-b914ef5….js:37fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:36fire @ main-b914ef5….js:40(anonymous function) @ main-b914ef5….js:35(anonymous function) @ main-b914ef5….js:35d.receive @ main-b914ef5….js:40ZoneDelegate.invokeTask @ zone-2222385….js:356onInvokeTask @ main-b914ef5….js:56ZoneDelegate.invokeTask @ zone-2222385….js:355Zone.runTask @ zone-2222385….js:256ZoneTask.invoke @ zone-2222385….js:423
6zone-2222385….js:260 Uncaught TypeError: node.getElementsByTagName is not a function`

**Comment by nickplesha** [comment]
@iav Thanks for all the additional information. Does this happen in other browsers as well?

**Comment by iav** [comment]
Yes, same in mozilla.

-----Original Message-----

**Comment by nickplesha** [comment]
@iav I've been trying to reproduce this in a few browser + OS combinations to no avail. A possible cause  for this might be in the EXIF data on the image that the uploader fails to process. Can you share at least one image where this happens? (in an archive or other link so EXIF data is preserved).

**Comment by iav** [comment]
Today I try but can't reproduce, at least with chrome - all work as it should, I upload a lot of panoramas, markers works.
Have no idea how it can be.
Ok, I will reopen this ticket if it reoccures.
