### ISSUE TITLE
Scrambled labels on the map

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2293]
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 52`

At least twice now I've noticed scrambled labels on the map. Reloading the page fixes it. The font being scrambled is the most obvious but it looks like highway shields and other graphical features are also affected. Screenshot:  

![mapillary_font_scrambled](https://cloud.githubusercontent.com/assets/348948/19085976/eb82ba92-8a31-11e6-970f-f8967f84f06b.png)

**Comment by jfburke3** [comment]
I noticed that today, too.

**Comment by gyllen** [comment]
I have a feeling that this is a bug in the latest verison of `mapbox-gl`. Thanks for reporting we are looking into it.

**Comment by jfburke3** [comment]
FYI, the labels look good today, at several different zoom levels.

**Comment by gyllen** [comment]
@nickplesha you have any idea if this started showing up after latest maobox upgrade. Have you seen any bugs reported yet in their repo?

**Comment by ToeBee** [comment]
Not sure if this is related or not. When reviewing pictures before uploading, I noticed a little bit of weirdness as well. The highway shields are wrong and when a picture is selected, there are weird artifacts around the selected picture. 
![review_scramble](https://cloud.githubusercontent.com/assets/348948/19298837/3bfe7bc0-9016-11e6-8c9f-c629aab0c8ad.png)

**Comment by ToeBee** [comment]
Ok, the manual upload page definitely has something to do with it. Going into the upload page has a high chance of triggering this problem. Yay for reproducibility at least!

**Comment by nickplesha** [comment]
@gyllen Yes, it seems this effect can occur in Mapbox GL 0.23 with similar behaviour to our window focus switching. It looks like it's fixed in the latest version: https://github.com/mapbox/mapbox-gl-js/issues/3086 so updating should resolve this.

**Comment by gyllen** [comment]
@ToeBee We are upgrading `mapbox-gl`

@nickplesha Close this ticket once update is done and changes are deployed.

**Comment by nickplesha** [comment]
@ToeBee Updated to the latest version of `mapbox-gl`. Let us know if this issue reappears by reopening this issue.
