### ISSUE TITLE
web uploader progress bar needs to be labelled

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2297]
Web uploader performs a scan of the images first, followed by review and full upload. 

The progress bar in the scanning phase is not labelled appropriately, the user gets the impression that this is the upload already, and goes for a coffee before the images are actually uploaded.

Please label it, e.g. "scanning images for review".

**Comment by gyllen** [comment]
@angelday WDYT?

**Comment by angelday** [comment]
Thanks @polarbearing and @gyllen I missed this note in October 2016. This was a good feedback though, but right now I feel like we're going to address this when we redo web uploader. Closing.
