### ISSUE TITLE
web uploader needs better sequence handling

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2298]
I tried to upload three sequences with the web uploader. (Mozilla Seamonkey/MacOS)
(captured on Android/app v.2.38)

While the file selector lets me select multiple files, it does not allow to select multiple folders, in this case the three sequence folders. However I did not intend to babysit three separate uploads and wanted them to perform when I leave.

Thus I dumped all files in a single folder and uploaded them. The review screen treated them as a single sequence, despite them having different sequence UUIDs. 

Next day, the "Your upload is on the map" mail announced that the images were "uploaded in 1 sequences".

Luckily, processing eventually separated them, so I see three different sequences in my upload feed. However the upload process remains confusing.

**Comment by polarbearing** [comment]
In the map view, the sequences are still connected in the graph. Watch [here](https://www.mapillary.com/map/im/wSIH8qysrvqtD9C_x8X1tw) and see the long line pointing westwards.

**Comment by AnkEric** [comment]
Me too... (upload multiple folders and split into separated sequences).

I did enhance my separated track sequences (Setting: "New sequence min distance = [max. 1500] meter") by a manual upload of a dozen series of private pictures (better quality).
But this manual upload is now visible on the map as one - bird's eye view - sequence.

I was assuming a Manual upload to be split by "New sequence min distance".

![manual upload not split into sequences](https://cloud.githubusercontent.com/assets/20150550/19108087/847b28ac-8aef-11e6-9daf-47f07d29fa40.png)

**Comment by gyllen** [comment]
I agree on this. In general the uploader should split the sequences for you. We are looking into this. Thanks for reporting.

**Comment by mschwendener** [comment]
> I used to be able to manually split a sequence once the sequence is visible on the map. 
> Not anymore...

That would be very useful for me.

**Comment by polarbearing** [comment]
Any progress on this? It is a lot of extra work for the user to upload each sequence individually!

And it is hard to create an effective workflow if all these bugs are not fixed, see #2427 or #2428 now, or #1974 is only talked about :-(

Please provide functionality, not eye-candy.

**Comment by gyllen** [comment]
@polarbearing Right now we are working on making bot cutting of sequences more stable. (we just fixed changesets for cutting sequences). So even though you upload many different sequences that have a big distance between each other we will cut them on the server.

**Comment by gyllen** [comment]
No other changes on this, for larger uploads `mapillary_tools` is the recommendation.
