### ISSUE TITLE
When uploaded photos in that time Decreased sequence photos total automatically 

### ISSUE THREAD

**Issue by Akaveeti** [mapillary/mapillary_issues#2299]
Hai, Actually my total photos count is 16,449 .Today I uploaded minimum 1000+ photos. Present total is 15703. why photos count is decreased ??  This is very disappointed BUG. Please fix this bug fastly. I lose 1000+ photos count :-( . How can I recovery that count again ??

**Comment by gyllen** [comment]
@Akaveeti Hi and thanks for reporting this bug. The nature of our database is that it at some points (during extreme load) will do a little sloppy counting on the number of images you uploaded.

It should only happen in very rare cases. Rest assure though that none of your uploads in anyway has disappeared (its only the count thats sometimes gets it wrong).

We are working on a permanent solution for this by getting a bigger database which will be deployed in a couple of weeks.

Sorry for the inconvenience.

**Comment by gyllen** [comment]
@Akaveeti Can you check if everything is back to normal?

**Comment by gyllen** [comment]
Since no answer closing
