### ISSUE TITLE
"Your upload is on the map": incorrect bookkeeping email notifications

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2300]
### Basic information
- Platform: `Android`
### Steps to reproduce behavior

Upload photos in several sequences.
Upload will fail several times ("network connection error") and has to be restarted.

Email notifications:

We have successfully registered your upload:
- za 08-10-2016 17:36: We have successfully registered 1623 photos uploaded from you. 
- **za 08-10-2016 20:52: We have successfully registered 5000 photos uploaded from you.** 
- za 08-10-2016 21:28: We have successfully registered 279 photos uploaded from you.

Your upload is on the map:
- za 08-10-2016 21:59: The 1902 photos you uploaded in 7 sequences are now visible on Mapillary. 

So: 5000 photos are not reported by email as being visible on Mapillary.
However: they are...

Issue is a long-standing issue, today I checked by checking e-mail messages.

**Comment by gyllen** [comment]
@AnkEric We are rewriting the notification process at the moment and that will make things better. For example the visible notifications will be replaced with an message when your images are fully processed. Im keeping this ticket open for feedback so we can close when better notifications are in place.

Thanks for reporting.

**Comment by knikel** [comment]
The notifications got an upgrade, we notify you now when we know the total counts of fully processed photos 👍
