### ISSUE TITLE
Video upload request

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#2301]
Feature request:
Please add the ability to set the direction in which the camera is recording/viewing.
Sometimes I take videos from my rear bicycle rack, the camera is viewing backwards, other times I take videos from the handlebars, front facing.

**Comment by gyllen** [comment]
@ligfietser Yes we do need this, thanks for reporting!

**Comment by gyllen** [comment]
Added to idea box for video uploads
