### ISSUE TITLE
"You deleted 349 photos"  Wait, what????

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2305]
I just noticed in my feed that there's a message saying I deleted photos.

I didn't delete any photos.....

![image](https://cloud.githubusercontent.com/assets/11140831/19330465/89edc7c8-90ac-11e6-871e-3cc9a5013d3c.png)
### Basic information
- Platform: Web
- Version: `...` 
- System/Browser: `...`

**Comment by HolgerJeromin** [comment]
Same as #2304 ?

**Comment by jfburke3** [comment]
I'm not sure. When I tried clicking on some of the image ID numbers to locate where they were, the map never took me anywhere and I just got the spinny circle indicating it was trying to load an image, but nothing ever happened after that.

**Comment by gyllen** [comment]
@peterneubauer Do you have time to check on this changeset?

**Comment by peterneubauer** [comment]
@jfburke3 you did get a mail notification too right? Can you forward that to me? peter@mapillary.com

**Comment by jfburke3** [comment]
@peterneubauer I don't think I did.  I'm looking for it, but haven't found one yet.

**Comment by gyllen** [comment]
@peterneubauer Can we find the images in the mapimages_deleted struct?

**Comment by katrinhumal** [comment]
Some additional details, since this case resurfaced on the forum: ```I don't think I have ever intentionally (or even accidentally) deleted any images I've uploaded. And in any event, from the way the remnant of the sequence progresses, it looks (to me--feel free to correct me) like someone (or some thing) deleted the missing images individually. I say that because the beginning portion of the sequence is present, and as you advance, you end up jumping to the tail end of the sequence, as if I paused shooting pictures and then resumed again later. Except I didn't, and there really did used to be an entire sequence there. I know because I used the imagery to help draw in the roads on OSM. If someone simply tried to delete the entire sequence,with just a few clicks...the begin and end of the sequence would be gone, too, which is why I say it had to be done image-by-image.```

@jfburke3 do you still remember where this is - could you share the links to the sequences "before" and "after" the part which seems to have been deleted?

**Comment by gyllen** [comment]
@katrinhumal @jfburke3 This also looks like something from before we had our new changeset system in place. Is that correct? Have you seen this happening again?

**Comment by jfburke3** [comment]
@katrinhumal I can't say for certain where the deletions referenced by this issue happened, but I can say that a sequence used to exist through this residential neighborhood, and is gone now:
https://www.mapillary.com/map/im/zfuoUCpCySYbsNUFk3phNQ

It's almost like someone didn't want there to be any imagery of that neighborhood.  (It's a new development under construction, so it's not like anyone had moved in to the houses yet.)

@gyllen No, I haven't seen it happen again.  I'm not sure about the timing w.r.t. the new changeset system.

**Comment by gyllen** [comment]
@jfburke3 So there used to be a capture on Cardera Dr?

**Comment by jfburke3** [comment]
@gyllen Yes, as well as Alcon Blue Drive.  I'm the one who drew those roads in OSM, using my Mapillary sequences to help align them (along with a GPS trace), as well as to get the road names from the signs.  I don't think I drove on the "stub" parts of the roads at the east end because the roads pretty much ended and I didn't see any point.  But I also drove in the circle that you can see north of Cardera Dr.

**Comment by gyllen** [comment]
@peterneubauer Is this something we can work with for finding missing images?

**Comment by peterneubauer** [comment]
Closing this, https://www.mapillary.com/app/?focus=photo&pKey=zfuoUCpCySYbsNUFk3phNQ&lat=27.8995306&lng=-82.33007&z=17 seems to be ok now.
