### ISSUE TITLE
Mapillary v2.43 crashes at Settings>Uploading

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2306]
### Basic information
* Platform:  `Android`
* Version: `2.43` 
* System/Browser: `Samsung Galaxy S5 (SM-G900P)`
* Android version: `6.0.1`

### Steps to reproduce behavior

 1. Launch app.
 2. Click/touch Settings
 3. Click/touch Uploading

### Expected behavior

No crashing.

### Actual behavior

"Unfortunately, Mapillary has stopped."

**Comment by Caboosey** [comment]
Copy of debug logs.
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/527603/mapillary_trace.txt)

**Comment by peterneubauer** [comment]
Found the problem, fixed in the next release, please reopen if it reappears.
