### ISSUE TITLE
No distinction between singular and plural.

### ISSUE THREAD

**Issue by jacobbraeutigam** [mapillary/mapillary_issues#2307]
### Basic information
- Platform:  `Android` | `Mail`
- Version: `2.42` |..
### Expected behavior

String depends on count of photos.
### Actual behavior

String is in the plural form.
### Additional information

![mail](https://cloud.githubusercontent.com/assets/6759694/19410082/34431b5a-92e3-11e6-9fac-c73ccba4e2a6.png)
![android](https://cloud.githubusercontent.com/assets/6759694/19410083/37171dcc-92e3-11e6-9221-017c69f2c9ee.png)

**Comment by knikel** [comment]
This will be fixed when we roll out new notifications in the following weeks, I'll close this issue then. Thanks for reporting!

**Comment by peterneubauer** [comment]
Also, on Android the specific texts should now support plurals.

**Comment by knikel** [comment]
We've updated templates for email notifications some time ago. Thanks for reporting!
