### ISSUE TITLE
Can't get GPS lock when using Google Mobile Services

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#2309]
### Basic information
- Platform: `Android 6.0`
- Version: `2.44` 
- System/Browser: `Motorola Moto G 2`
### Steps to reproduce behavior
1. Open mapillary
2. Try to start the capture
### Expected behavior

Get a GPS lock and start capturing pictures
### Actual behavior

Wait forever for a GPS lock
### Additional information

I was trying to capture a sequence. No matter what I did, mapillary just didn't get a GPS lock.
Opening any other program that uses the GPS got a very quick fix.

Enabling the wifi (but without a connection) didn't help. Connecting to the 3G network didn't help.
The best thing that I could get, after a while was something like this:

![](https://cloud.githubusercontent.com/assets/982338/19411581/e87d86fe-92da-11e6-8750-fdca4397541e.png)

Is it expected to have `GMS` there?

Then, I found `Use Google Mobile Services` and disabled it.
The GPS fix got faster, I saw `GPS` in the info (instead `GMS`), but it still seems that the precision is lower than with any other app that I have.

**Comment by rsahlin** [comment]
Hi @naoliv and thanks for your comment.

We will create a new camera UI and when doing this we will handle GPS accuracy differently.
I will close this issue, please look out for a release in a couple of weeks with an update to this.

Best regards
/Richard
