### ISSUE TITLE
Wrong images shown when reviewing second sequence on android

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2311]
### Basic information
- Platform: `Android`
- Version: `2.44` 
### Steps to reproduce behavior
1. Review a sequence
2. Go to review a second sequence
3. Tap on first picture in sequence to bring up full resolution
4. Image on screen is from first sequence

The x/y counter at the bottom of the review screen correctly reflects the second sequence but the picture being displayed is not right.

**Comment by hob-gob-lin** [comment]
I am seeing the same bug.  I have a Galaxy S6 and running Mapillary version 3.01

**Comment by HolgerJeromin** [comment]
Fixed in 303
