### ISSUE TITLE
After uploading, sequence stays "open"

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2312]
### Basic information
- Platform: Android
- Version: Mapillary 2.44, Android 6.0.1 & 5.0, Samsung Galaxy S7 & S5
- System/Browser: n/a
### Steps to reproduce behavior
1.  Go into the Upload function, and open a sequence.
2.  Press the Upload button to begin uploading with the sequence open on screen.
3.  When uploading completes, the sequence thumbnails remains on-screen, even if you let it sit for several minutes.
4.  Pressing Upload again acts like it will start uploading again.  The dialog box pops up, but then disappears.  Nothing else happens.  You can also tap on an image to try to open it.  The app acts like it's opening the image, except the image is not displayed (the count bubble at the bottom shows, though).
### Expected behavior

I would expect it to exit out if the sequence once uploading is complete, or at least generate an error popup ("Sequence already uploaded" or something like that).
### Actual behavior

Thumbnails remain on-screen.
### Additional information

Can provide screenshots if you need them.

**Comment by jfburke3** [comment]
Update:  I did just see it exit out of an uploaded sequence.  However, that seems to be the exception rather than the rule.

**Comment by HolgerJeromin** [comment]
Related or the same as  #1533

**Comment by jfburke3** [comment]
This problem disappeared a while ago, so closing this issue.
