### ISSUE TITLE
Webuploader: same upload is shown as duplicate upload

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2313]
Basic information

```
Platform: Web
System/Browser: FireFox 49.0.1
```

Steps to reproduce behavior

```
Use the manual upload page at https://www.mapillary.com/app/uploader
```

Expected behavior

```
Each upload should show as one distinct upload.
```

Actual behavior

```
The same upload is shown in "Uploads" as a Duplicate upload.
Despite the number of Pictures: both uploads have - almost - the same DateTime stamp.
I cannot upload 2238 Pictures in one minute twice.
```

Uploads are not real duplicates, as I found out the hard way: I requested one sequence to be deleted and no sequence is left.
All yesterday carried uploads are considered as duplicate.

![two uploads_2960_5000](https://cloud.githubusercontent.com/assets/20150550/19450403/8baf86a4-94a9-11e6-861d-833731f10d75.jpg)

![duplicate uploads](https://cloud.githubusercontent.com/assets/20150550/19449413/c6a1acaa-94a5-11e6-9572-cea9ca0957fa.jpg)

**Comment by gyllen** [comment]
@peterneubauer It feels like we have seen this before. It feels like one image is getting assigned to multi sequences.

@AnkEric Thanks for reporting, and really sorry for this hickup.

**Comment by AnkEric** [comment]
> It feels like one image is getting assigned to multi sequences.

To be honest: I did see something strange on my side!
Cross-linked images, one image on smartphone was copied to other sequence folder on PC. Same filename, but different image!
Only twice in 8 sequences so I do think this does not explain the issue. But also: twice!
Must be my system error? Or Mapillary, together with Galaxy and Android did write those files as cross-linked files?
I have preserved both folderstructures, both on PC and Galaxy, in case I'm requested to investigate more thorough.

However this is what I did see in Review before Upload. I have deleted the "lost image". Basically to prevent this straight sequence marker to show up on Mapillary.

![one picture in wrong seqeunce_01](https://cloud.githubusercontent.com/assets/20150550/19469966/eb42b52c-951d-11e6-93b2-62497d5dffb7.jpg)

**Comment by gyllen** [comment]
@AnkEric Thanks for more detailed report we are continuing to investigate this issue.

**Comment by kaitu** [comment]
I got something similar when I uploaded with web-uploader pictures belonging to different app sequences (I mean, having different MAPSequenceUUID tag), after mixing them in the same folder on the desktop. I published a total of 458 photos, belonging to three app sequences, of 54, 381 and 23 photos each. In the uploads tab I get listed 4 uploads: 

- 458 pictures (sequence DSzt74NSducRRXYZw337QQ)
- 54 pictures (sequence DSzt74NSducRRXYZw337QQ)
- 381 pictures (sequence aSjT5OZfNXalHIRN1gynjw)
- 23 pictures (sequence aSjT5OZfNXalHIRN1gynjw)

If I call the photo details for any of those 458 pictures, it says that the picture belong to sequence KUI963fHuoNc_SmHd0yfYw.  

So it looks like DSzt74NSducRRXYZw337QQ, aSjT5OZfNXalHIRN1gynjw, aSjT5OZfNXalHIRN1gynjw are all sort of aliases for KUI963fHuoNc_SmHd0yfYw.

I admit it was my mistake to mix photos from different app sequences (I had forgotten to strip the mapillary tag beforehand). Nevertheless I find the duplicate entries in uploads tab confusing.

![image2](https://cloud.githubusercontent.com/assets/5104672/20525236/cb8ed500-b0be-11e6-9340-4bd1fda59a71.jpg)

**Comment by gyllen** [comment]
@peterneubauer Idea on this?

**Comment by polarbearing** [comment]
Have closed my #2376 as duplicate. In my case, all "Uploads" show  every sequence after Oct 9 twice. They come with the same sequence ID, so no real duplicates. The uploads before that date appear only once. See screenshot there.

**Comment by polarbearing** [comment]
And things get **even messier and more chaotic**. Up to Nov 21, the dup entries showed up next to each other with the same ``pKey`` value for the start image. 

Now, several separate uploads of less than 300 pics that were done between Nov22-25 each show up as bulk processing (1037 pics) on Nov 25 in the "Feed". In "Uploads" there are duplicate entries again, but not next to each other, and showing different ``pKey`` values for the same image :-(

If I start clicking through the sequence, it appears that they all have different ``pKey`` values in the URL. 

One sequence is there even 3 times! Twice with 281 pictures, and once with 562, with two different keys for the start image.

**Comment by peterneubauer** [comment]
You uploaded the sequence only once? The harvester for the web uploads is
right now catching up from being down for the last days. New images are
aggregated into your feed per hour, so you see different sequences in the
same feed item.

Every image is getting a new uuid when inserted into the system. If the
same image has 2 different uuids that mean it has been harvested twice
(bug) or it has been uploaded into 2 sequences (expected, but we are
preparing for a bit that can recognize duplicate images)

I will go and see if your sequences are now harvested. If there are still
images left, that's a bug. Got the URL to the duplicate sequences? We can
always delete them.

**Comment by polarbearing** [comment]
Yes upload was only once per sequence. I did not retry since the issue of processing delay is not new. See #2366 for pictures that uploaded twice in a failure situation, however that was stopped after a few and never a full sequence. 

I verified now that all 20 sequences that I uploaded since Nov 11 are in the system. 

Why is the "MAPPhotoUUID" from the app not evaluated to avoid dups? Here is the example with the 3 upload appearances, with the dates showing in the upload list, the transfer was earlier:
```
"MAPPhotoUUID":"f2b73f40-5de1-43d3-a76c-3c6bc65cc577"
"MAPSequenceUUID":"31eb0f00-5e2a-4c1c-a7ba-bd946e90b311"
```
Uploads list. First two URLs identical:
[Nov 25 17:00](https://www.mapillary.com/app/user/polarmap?lat=20&lng=0&z=1.5&pKey=5VnReDobGKcGVEGt90hK4A) (562)
[Nov 25 16:58](https://www.mapillary.com/app/user/polarmap?lat=20&lng=0&z=1.5&pKey=5VnReDobGKcGVEGt90hK4A) (281) 
[Nov 25 16:55](https://www.mapillary.com/app/user/polarmap?lat=20&lng=0&z=1.5&pKey=1WSgKnJuccmcz-k8m02peA) (281)

**Comment by polarbearing** [comment]
Issue still present and confusing. Anybody takes care of it?

**Comment by gyllen** [comment]
@peterneubauer ^^

**Comment by peterneubauer** [comment]
Yes, I'm on a data cleanup mission, and this issue is part of it. Before that we are going to take care of the sequences that need to be cut though. But yes, this is not forgotten!

**Comment by peterneubauer** [comment]
This is most probably a bug that has been fixed since. The UUID for both sequence and image was not taken into account when harvesting. This is fixed now, closing for now as we can't dedup automatically (lacking uuid). Please delete the duplicate sequences manually.
