### ISSUE TITLE
Blur editor can get stuck with profile panel open

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2314]
### Basic information
- Platform: Web
- System/Browser: Firefox 45.4
### Steps to reproduce behavior
1. Open the panel/menu on the left, select Leaderboard.
2. Click on a user. The profile panel opens on the right.
3. Click one of the user's uploads. This opens the first photo of the sequence.
4. Click (...) and then Edit blurs.

The left panel closes, but the right panel remains open. I can't close it (clicking the > button does nothing), and I can't submit blurs or exit the blur editor, since those buttons are covered by the profile panel.
### Expected behavior

Both the left panel and right panel should be closed when opening the blur editor.
### Additional information

I didn't find a simpler sequence of steps to reproduce the problem. For example, if I simply open the right profile panel and the left menu panel and go to the blur editor, both panels close. It seems it only happens if I opened the profile panel by clicking a user from the leaderboard.

**Comment by gyllen** [comment]
@nicolas17 Thanks for reporting, will report back when solved

**Comment by knikel** [comment]
This is no longer an issue. Thaks for reporting!
