### ISSUE TITLE
No confirmation when changing profile bio/description

### ISSUE THREAD

**Issue by eneerhut** [mapillary/mapillary_issues#2315]
- Platform: `Web`
- System/Browser: `Sierra/Safari`
### Steps to reproduce behavior
1. When adding information into your bio and saving, nothing happens.
### Expected behavior

A little dialogue confirming that the changes have been saved.
### Actual behavior

Nothing happens.

...
### Additional information

Props to Panoramio superstar Manuela for mentioning.

![screen shot 2016-10-19 at 12 12 30](https://cloud.githubusercontent.com/assets/11349863/19514873/7a380ebc-95f5-11e6-817e-464bc1ef1d50.png)

**Comment by angelday** [comment]
We will be improving this one while adding functionality to the settings, thanks for reporting.
