### ISSUE TITLE
Improve sequence editing

### ISSUE THREAD

**Issue by ptpt** [mapillary/mapillary_issues#2316]
To update a photo's location, we have to click on the photo, and drag it to the new location. This set of operations is inefficient, especially for editing a sequence with a large number of photos:
1. sometimes it's hard to click on the right photo (especially when many photos gather together)
2. dragging is slow on slow computers
3. when you drag too fast, the photo will not follow the mouse

(these issues perhaps only happen on slow computers)

I propose a faster work flow to update photo locations here:
1. select a photo by clicking on it
2. click on the expected location to place the selected photo here
3. select the next photo with shortcut keys (e.g. arrow key)
4. repeat from step 2

**Comment by danbjoseph** [comment]
I would like if you could drag out a box to select multiple photos for a single action (delete or drag). This would be helpful instances where there wasn't a good GPS fix for the first part of a sequence and a number of images at the start are far enough off it would seem like a good idea to delete them. 
![screen shot 2017-03-05 at 3 23 51 pm](https://cloud.githubusercontent.com/assets/4806884/23591029/fd602012-01b7-11e7-95fc-1d1c49870c89.png)
Also for when there are a chunk of images that all need to be shifted about the same distance/direction. 
![screen shot 2017-03-05 at 3 06 47 pm](https://cloud.githubusercontent.com/assets/4806884/23591028/fbbc77a6-01b7-11e7-9397-8ec99bc64c5b.png)

**Comment by gyllen** [comment]
Added to idea box for improvements of edits
