### ISSUE TITLE
Add 1.5s as a choice for timed mode

### ISSUE THREAD

**Issue by Caboosey** [mapillary/mapillary_issues#2317]
### Basic information
- Platform: `Android`
- Version: `2.48` 
- System/Browser: `SM-G900P`
- Android version: `6.0.1`
### Steps to reproduce behavior
1. Launch Mapillary app
2. Click/touch Menu icon at top left
3. Click/touch `Settings`
4. Click/touch `Capture`
5. Click/touch `Timed Capture`
### Expected behavior

Have a custom entry or a 1.5s as a choice.
### Actual behavior

No option to choose 1.5s
### Additional information

...

**Comment by peterneubauer** [comment]
Added, will be out in the next release.
