### ISSUE TITLE
Improving image quality (optionally)

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2318]
I would be great and very useful if we have an option to improve to image quality before the upload. Personally, when I'm using the webuploader, after the gps sync, I used to upload the images on Google+ (using the [old/classic version](https://www.youtube.com/watch?v=zH5YNBCcdxE)), where I have an option to improve quality for an entire album by a click
![quality](https://cloud.githubusercontent.com/assets/8439643/19627924/0a1b73f8-995b-11e6-865e-d20a313be55d.png)
, and then download this back to the PC, and after all on Mapillary. It's for sure a time-consumming process.
Here is an example of difference between photos.
Original 
![uploaded](https://cloud.githubusercontent.com/assets/8439643/19627880/2c78d7fc-995a-11e6-8dfb-4c55f0ffe354.jpg)
Improved
![uploaded 1](https://cloud.githubusercontent.com/assets/8439643/19627882/3c8310e0-995a-11e6-98a3-e053fff518f2.jpg)
Mapillary link for the photo:https://www.mapillary.com/app/?lat=44.39216977914214&lng=26.093693375606478&z=17&pKey=lSS6RseinVStoBXN8riN-g&focus=photo

Thanks!

**Comment by gyllen** [comment]
@ybkuang What do you guys in vision thinking about doing any image adjusting on the backend?

**Comment by ybkuang** [comment]
@eugensim We unfortunately cannot prioritize this in the near feature. But thanks for the suggestions. I made a note so that we can revisit later.
