### ISSUE TITLE
Blur editing with images in portrait mode

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#232]
In blur editing page, when an image is in portrait mode, blurred areas are not shown at right place, and the image to blur covers the buttons "Request Blurring" and "Cancel".

Example:
http://www.mapillary.com/map/b/ryz7HRDYeN6gf6FbXRlEpA

**Comment by knikel** [comment]
This has been fixed in the recent viewer update. You can also edit blurs in the image view directly.
