### ISSUE TITLE
Uploaded image icon is misaligned?

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2320]
### Basic information
- Platform: `Web`
- System/Browser: `Linux, Chrome`

I don't want to refresh the page to check if it's always like this, but the icon for an uploaded picture seems like it's pulled from the wrong part of the icon sheet (or however you want to call it). The screenshot should explain it better:
![screenshot from 2016-10-23 20 44 06](https://cloud.githubusercontent.com/assets/7786285/19630903/94e55e1c-9961-11e6-9477-2fde49cff59e.png)

**Comment by gyllen** [comment]
@nickplesha Seems like there are still some problems with map even after upgrading mapbox-gl

**Comment by nickplesha** [comment]
@pkoby Thanks for reporting, we've updated the map library again and the image sprites should be in order now as I can't reproduce this on retina and non-retina screens, can you confirm if this is still happening for you?

**Comment by pkoby** [comment]
Just tested it. Looks good from here. Thanks.
