### ISSUE TITLE
ability to have a portrait mode for walking

### ISSUE THREAD

**Issue by hughdavenport** [mapillary/mapillary_issues#2321]
### Basic information
- Platform:  `Android`
- Version: `3.00`
### Steps to reproduce behavior
1. Hold phone in portrait mode or have mounted in chest mount or bag mount. 
2. Use mapillary while walking
### Expected behavior

Mapillary should allow portrait mode.
### Actual behavior

Mapillary requires landscape for all modes.
### Additional information

So I have an idea for a bag mount, which would mount to the strap of my backpack, which would require phone to be in portrait mode. I would like to be able to take mapillary sequences with this while walking around.

**Comment by de-vries** [comment]
Go to Settings > Capture, disable 'Pause while tilting'. And voilà, portrait mode is possible.

**Comment by millenbop** [comment]
It has been discussed before, see for instance this one for some discussion:

https://github.com/mapillary/mapillary_issues/issues/1733

**Comment by hughdavenport** [comment]
Ok I'll try the turning off tilt and having phone portrait. The docs suggested that i would have to do offline image manipulation to get it in 4:3 ratio though which is not what i would intend

**Comment by hughdavenport** [comment]
Would this be resolved with the fix in #2327?
