### ISSUE TITLE
Questions: Web uploader for Video? Garmin VIRB XE? Time lapse Video?

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2322]
### Basic information
- Web uploader for Video 
### Questions
1. What is to be expected for Video Upload from Mapillary in near future?
2. Will Mapillary processing of time lapse video be possible in near future?
3. Will Mapillary processing of video be possible in near future without the need of a GPX file? 
### My Mapillary images on bicycle are garbadge

My Mapillary images on bicycle are garbadge: shaken, blurred, out of focus, dark.
Only in full sunlight these images are “acceptable”. Both from my perspective as from Mapillary – estimated – perspective.
### To resolve
1. Use a better mount than Mapillary (free) mount or secure this mount more stable (f.i. by using a strap).
2. Use a smartphone having image stabilization. iPhone 6 did produce better images than Galaxy S5 Neo.
3. Migrate to Action Cam: Garmin Virb XE, having built in GPS.
### Action Cam: Garmin Virb XE, having built in GPS

I have arrived on Step (3) and tested Garmin VIRB XE last weekend.
See: [Mapillary/UserGuide](https://github.com/mapillary/UserGuide/wiki/Equipment)
Test outcome was very ambivalent.

To decide on migrating to Garmin VIRB XE, I would like to know what is to be expected from Mapillary in near future.
### Time lapse photos is not an option (for me).

Time lapse photos have 7 MP resolution, which results in about 2 MB file size per photo.
One day = 5 hours = 18000 photo’s (1 fps) \* 2 MB = 35 GB. No problem!
One weekend = 2 days + 64 GB SD-card > Problem!
Vacation, multiple days: impossible!
### Time lapse video.

Time lapse = 1 fps.
Image = 1080 p. 
Image quality is much better than current Galaxy S5 Neo image quality.
One day = 5 hours = 2 GB is very much OK!
Vacation + 64 GB SD-card: (even) 30 days is OK!

So: Time lapse video seems to be a good solution to my problem of bad photos. Also from resource perspective.
### But now Mapillary has become the bottle-neck.
- Video upload is legacy Application.
- It takes a longue time before upload is on the map.
  Survey today, Mapillary upload early in the evening, OSM mapping using Mapillary in the evening is no option.
- Video max file size = 2 GB. So I have to split Clip(s) into “small” Videos.
- Legacy Application is requiring a GPX file. Which should be not be required since VIRB XE has built in GPS. Will Mapillary processing of video be possible in near future without the need of a GPX file?
- Mapillary does process a video as a sequence of “time lapse images”.
  My last night Video of 800 MB file size video was turned into 247 photos, each about 0,5 MB file size. Which is about 125 MB file size in total. Which leaves me having consumed 800 MB – 125 MB = 675 MB of useless disk space for only 04:25 minutes of video.
  Which is why I would prefer using time lapse Video (1 fps, 1080 p.).
- (( EDIT, NO ISSUE: Video is not visible on the Mapillary map! But it does show in Feed and JOSM! ))
- A time lapse video cannot be uploaded: synchronization between video and GPX track is not possible. One hour GPX should be synchronized with 2 minutes Video. Which, in the legacy Application, seems impossible.
  Will Mapillary processing of time lapse video be possible in near future?

Video/GPS synchronization is NOT correct:

![mapillary upload_time lapse video](https://cloud.githubusercontent.com/assets/20150550/19659124/fa110c4a-9a2a-11e6-96ed-43efa17d9c9f.jpg)

**Comment by ybkuang** [comment]
> Video is not visible on the Mapillary map! But it does show in JOSM!

@AnkEric Do you mean the uploaded videos are visible in JSOM but not on Mapillary map? do you have a link to one of the images?

**Comment by AnkEric** [comment]
This is first photo of Video sequence:
https://d1cuyjsrcm0gby.cloudfront.net/fWSq6eKf26PC1Vw1FdVwzw/thumb-2048.jpg

Or am I unpatient? Might take some time to show? Now I found sequence by Feed and JOSM.

**Comment by gyllen** [comment]
@AnkEric Can we close this ticket?

As a note we are working on making notification more descriptive.

**Comment by AnkEric** [comment]
@gyllen 

> Can we close this ticket?

**Comment by cbeddow** [comment]
@AnkEric 

You're correct on the points about consuming time and resources. 

My one suggestion to minimize all of these issues is to link the VIRB to the Mapillary app on your mobile phone. You'll want to connect to the VIRB via wifi on your mobile phone, then in Mapillary open the camera, tap tap the wifi icon that is below the question mark. The app will recognize the Garmin VIRB as an external camera and ask to link, so confirm this. A preview will refresh on the screen. Now you can point the VIRB where you need to, and meanwhile hit the green button on the Mapillary app to start recording. This will capture photos at intervals, the same as the Mapillary app works with your mobile phone camera. Once you stop taking the sequence, the Mapillary app will ask if you want to transfer these photos. You can then transfer them to your mobile device, and upload via the app. This way you're not uploading video sequences, you have no need to worry about GPX tracks,  not splitting of videos, and much smaller file size due to photos being used instead of videos.

Please let me know if this may address your concerns. For me, I used the Garmin VIRB with video early on and encountered the same issues as you, but found when linking it to the Mapillary app to take photos automatically, everything was much smoother.

**Comment by eneerhut** [comment]
@AnkEric just chiming in here.
Unfortunately no easy solution in the short term for you if you are relying on the Garmin's video time lapse feature.
If you can go without this then time lapse photos is best. You can adjust the resolution accordingly and easy uploading with the web uploader.

If you still need the video then the video uploader you are already familiar with is the easiest tool. The upload limit is now 4 GB and you should be able to extract the GPS as a trace from the Garmin or could record a separate trace using your phone and an app like OSMAnd. This is what I do personally as my GoPro doesn't have GPS.

We will migrate video upload to our current site but it might be a little while before we do this.

Sorry we don't have an easier solution for you at the moment.

**Comment by AnkEric** [comment]
> @cbeddow: My one suggestion to minimize all of these issues is to link the VIRB to the Mapillary app on your mobile phone. 

Interesting option, out of the box thinking, to connect Mapillary to VIRB.

However…

Android Phone and Garmin VIRB XE are connected by WIFI.
But I cannot connect Mapillary to VIRB. I don’t see a “wifi icon that is below the question mark”. 
(Wifi icon with a question mark means that wifi is available and in range, but not connected).
I do want to try this option! Interesting!

What is the extra value by controlling VIRB by Mapillary?
Is “take low resolution pictures” an option in this setup? 
Again: no option to make low resolution pics by VIRB (only 2 MB/pic) is my resource bottleneck (not for one/two day trips, but for multiple day trips it is).
Can Mapillary make low resolution pictures on Garmin VIRB XE?

VIRB has a native option to make Time Lapse Photo’s: 1 photo per ½ - 60 seconds.
IF (!) Garmin VIRB XE would have a “low resolution” option for Time Lapse Photo’s that would resolve ALL (!). 

Also using both VIRB and Phone creates a new resource bottleneck: Power Supply.
For multiple day trips on bicycle (1x photo camera, 1x GPS, 1x VIRB, 2x E-reader and 2x smartphone) this is most critical: 7 items requiring Power! 

> @eneerhut: If you can go without this then time lapse photos is best.

Storage for 2 MB pictures is bottleneck. For multiple day trips even on 64 GB card on VIRB.
>  @eneerhut:  You can adjust the resolution accordingly and easy uploading with the web uploader.

Uploading using web uploader is no issue as long as web uploader doesn’t need my help (manual action) during overnight.
Nice to have:
- web uploader log file.  
If web uploader stops (or I simply forgot and Close browser) I have no clue which photo’s have been uploaded, and which still need to be uploaded.
- select multiple folders for upload.

>  @eneerhut: If you still need the video then the video uploader you are already familiar with is the easiest tool. The upload limit is now 4 GB.

Nice! Thanks! VIRB is creating 2.63 GB Video Clip files, which can now be uploaded without splitting (clipping)!
>  @eneerhut: (Video) you should be able to extract the GPS as a trace from the Garmin

This means: Export a Video by VIRB Edit. Which takes a long, long, very long time!

>  @eneerhut: (Video) record a separate trace using your phone and an app like OSMAnd.

Or GPSMAP 64st! Yes, this is the best option IF (!) a GPS track is required (but it should not be required IF (!) Video includes GPS data).
Still I have to manually Sync video and track. This manual action blocks the option to unattended, batch upload multiple video’s during overnight. One day cycling, 5 hours, means 20 (!) videos.

Yet, I have still another option:
Record a “normal” Video (also nice to have from a personal perspective) and split this Video into images to be uploaded to Mapillary:
[VirtualDub](http://www.virtualdub.org/)
VirtualDub is a video capture/processing utility (…).  It lacks the editing power of a general-purpose editor such as Adobe Premiere, but is streamlined for fast linear operations over video.  It has batch-processing capabilities for processing large numbers of files (…).  VirtualDub is mainly geared toward processing AVI files.
VIRB produces MP4 files. But is should be possible to SaveAs AVI-file.
> @eneerhut: Unfortunately, no easy solution in the short term for you if you are relying on the Garmin's video time lapse feature. We will migrate video upload to our current site but it might be a little while before we do this. Sorry we don't have an easier solution for you at the moment.

Don’t be sorry. Not even Rome was built in one day.
I my opinion we (Mapillary and I) have two good options:

- Garmin will hopefully respect a RFC to create “low resolution images” in Time Lapse Photo mode.  
But Garmin is expected to ignore a RFC by default. Or perhaps just my RFC’s?
- Mapillary will implement upload of multiple (batch upload) video’s, including Time Lapse Video and not requiring a GPX file IF (!) Video contains GPS information.

This “easy solution” should not be implemented “in the short term”: our first more than two days bicycle trip is not expected before April 2017. But it would be appreciated if Mapillary would accept this Request for Change.

**Comment by cbeddow** [comment]
Still pending a product decision on whether or not to support VIRB.
