### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by Akaveeti** [mapillary/mapillary_issues#2323]
Hi,

In recent update version have lot of bugs I faced inAndroid Device.

1) In sequence time , in case I click stop button and click again start button to continue that  app going to hang.

2) Can't possible to delete single image in a  sequence photos.

3) Images is not uploaded, when i click upload button and select upload option . it is showing one popup " cancle and home " . But not uploading images . when i click that cancle or home app going to hang.

4) In settings storage i want to change storage , so i selected SD Card come back and see that storage settings  , but there it is not showing update storage settings.It is showing old storage settings.

5) Sometimes not showing user details in profile.but user is not logout.

6) App going to unfortunately logout. 

7) In logging time when I selected Gmail option , when open one green screen not going logging or not moving to next page or not logging. And in this scenario I click back button when in mobile bottom " time and logging you in " popup overlap in that green screen.

8) Select Login option and click " regular email " option, In this page give one bit space in that name ( email , password )and underline. 

9) After login, I selected Home option in my account , there showing images when i am uploaded . but there showing one latest sequence image box and that below box have showing very old sequence date,time and photos count.every new uploaded below showing one old sequence popup box.

10) Meters, sequence , photos is not updated.

11) Updated sequence is not showing in maps and profile page.

12) After app installation , click on capture option , camera showing black color .

13)After installed I opened capture , In that capture camera showing only black color.after i do crash that manually and I opened that capture. now it is showing camera.and camera showing only half page . not showing fully. 

14) In web portal not possible to upload more than 1200 images.

**Comment by gyllen** [comment]
@Akaveeti Is this in the Android app?

**Comment by Akaveeti** [comment]
Yes , In Android App

**Comment by rsahlin** [comment]
Hi @Akaveeti and thanks for reporting

My name is Richard Sahlin, I am the lead engineer on the Android app.
Could you please let me know what device you are using and what version of Android?
We are looking into your report.

Best regards
/Richard

**Comment by rsahlin** [comment]
Hi again @Akaveeti 

When you try to upload - do you see any kind of message on the screen?
This could be that you are connected to a cell network and settings is set to only upload on wifi.

Best regards
/Richard

**Comment by Akaveeti** [comment]
Hi,

I am using Redmi Note 3.
Version : 5.1.1.
I will try to update on last saturday to still. i will check that setting also. i update every time in wifi only.

**Comment by rsahlin** [comment]
Thanks for your reply @Akaveeti 

Could you please try to trigger an upload and send debug logs by opening the navigation drawer (either pressing the context menu in top left corner - or swiping left)
This will help us investigate the problem.

Best regards
/Richard

**Comment by Akaveeti** [comment]
Okay , sure

**Comment by peterneubauer** [comment]
Ok,
the stats (nr. 10) should be updating now @Akaveeti

**Comment by peterneubauer** [comment]
Closing this for now, most of the issues are fixed now.
