### ISSUE TITLE
Shutter sound enabled even though disabled in settings

### ISSUE THREAD

**Issue by kardotim** [mapillary/mapillary_issues#2324]
* Platform: `Android`
* Version: `6.0` 
* Device: `Huawei Honor 7`

### Steps to reproduce behavior

 1. Go to hamburger menu -> Settings -> Camera -> Disable shutter sound
 2. Go to Capture and take photo, doesn't matter what mode
 3. Hear the shutter sound

### Expected behavior

To not hear a shutter sound when it's disabled in settings.

### Additional information

The device audio is even muted so I think Mapillary is overwriting that in some way. Perhaps that's device related somehow? I haven't been able to reproduce it on a different Android device but please give it a try.

**Comment by echeloni2p** [comment]
Hi!
Well known issue on honor 6/honor 7 already, no real way to fix it.
Some cameras are not being able to mute shutter sound (as requested by some countries law to prohibite upskirt pictures).
echelon

**Comment by kardotim** [comment]
Interesting! I had a hunch it came more from the OS than the app itself. Thanks for sharing the information.
