### ISSUE TITLE
Invalid SSL certificate for API

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2325]
### Basic information
* Platform: `Web`
* Version: `current`
* System/Browser: `Linux / Firefox 48 or Chromium 53`

### Steps to reproduce behavior

 1. Try to visit any API page, for example https://a.mapillary.com/v2/search/im?client_id=CLIENT_ID&max_lat=48.12961&max_lon=-1.7073299999999563&min_lat=48.12421&min_lon=-1.7210000000000036

### Expected behavior
Enjoy the API response in JSON format.

### Actual behavior
SSL certificate error is shown by browser, because the API call is redirected to `mapillary-read-api.mapillary.io` domain, and SSL certificate is valid only for `*.mapillary.com, mapillary.com`.

**Comment by gyllen** [comment]
@PanierAvide This was caused by an error on our server, please confirm that this is now working for you.

**Comment by PanierAvide** [comment]
It works correctly, thanks for solving the issue :-)
