### ISSUE TITLE
Time Travel beetwen photo and panorama wrongly using panorama direction

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#2328]
### Basic information
- Platform:  `Web`
- Version: `...` 
- System/Browser: `Google Chrome`
### Steps to reproduce behavior
1. Open a timetravel beetwen standart photo and 360 photo (https://www.mapillary.com/app/time-travel/trolleway?lat=55.63729856999413&lng=37.673138380009846&z=17&pKey=HN3Hj5XUPXDpnO--5N4nIQ&focus=photo&cKey=gI6q7g3Z1Q588zo6Jvs6LQ)
### Expected behavior

Old and new photos should be overlayed, and facing to same direction.
### Actual behavior

Transition perfoming beetwen standart photo and center of 360 photo, but center of 360 photo may be facing to other direction
### Additional information

... 

![2016-10-27 13-32-02](https://cloud.githubusercontent.com/assets/4630662/19764075/d215f6bc-9c49-11e6-85e2-1a2832d7892b.png)
![2016-10-27 13-32-07](https://cloud.githubusercontent.com/assets/4630662/19764079/d629a55a-9c49-11e6-8c61-9146eaab0352.png)
![2016-10-27 13-32-18](https://cloud.githubusercontent.com/assets/4630662/19764096/e4c27754-9c49-11e6-8048-190e67868d10.png)

**Comment by oscarlorentzon** [comment]
When a panorama is a the background photo in the slider the camera does not rotate to the center of the panorama when sliding anymore. It sticks to the viewing direction of the regular foreground photo.

Example here: https://www.mapillary.com/app/time-travel?lat=44.136356&lng=4.809196&z=17&pKey=bk10X3ULT58FpG2UlY7hRA&focus=photo&cKey=6MSfIDz0O7QJrmwyXCRmAg
