### ISSUE TITLE
Review will only show me a deleted image

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2329]
### Basic information
* Platform: Android, Samsung Galaxy S7 Edge
* Version: 6.0.1

### Steps to reproduce behavior

 1.  Open a sequence with a single image and delete that image.
 2.  Open another sequence and attempt to review individual images.

### Expected behavior

I expect to see the image for which I tapped on the thumbnail.

### Actual behavior

The only image I see is the one I deleted earlier.  The xx/yy count at the bottom is correct, but it won't show me the "right" image.

**Comment by jfburke3** [comment]
I should note that it worked fine *before* I deleted that one image.  It was an image by itself and I didn't think it was necessary.

**Comment by rsahlin** [comment]
Hi @jfburke3 and thanks for reporting.

This has been fixed and will be released with an update very soon.
