### ISSUE TITLE
Extremely slow navigation between photos (only on Chrome)

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2330]
Windows 10
Chrome last version (on Edge works fine)
![slow](https://cloud.githubusercontent.com/assets/8439643/19815449/9b07240e-9d4b-11e6-88a2-e15da144d42a.jpg)

**Comment by gyllen** [comment]
We just made a major performance upgrade on the web. Can you check if its better?

**Comment by eugensim** [comment]
@gyllen Nothing changed. The problem is only on Chrome.

**Comment by oscarlorentzon** [comment]
@eugensim Do you have a link to a specific image where it is slow or is it slow everywhere. Can you elaborate on what you mean by `slow`?

**Comment by eugensim** [comment]
@gyllen @oscarlorentzon here is a video example between Chrome and Edge https://www.youtube.com/watch?v=FhVmVmCcALg&feature=youtu.be

**Comment by oscarlorentzon** [comment]
Thanks @eugensim. It looks very slow on both Chrome and Edge to me.

Is the speed of the MapillaryJS viewer equally slow here?

https://bl.ocks.org/oscarlorentzon/raw/5af00c5c07448233bcb62f5e2124ab39/

**Comment by eugensim** [comment]
@oscarlorentzon no, there is ok.

**Comment by gyllen** [comment]
So this has probably something todo with the fact that we both have the map that use webGL and MapillaryJS using WebGL then, its interesting to me that its only happening in chrome too.

**Comment by oscarlorentzon** [comment]
@eugensim MapillaryJS 2.1 has now been deployed on mapillary.com with a potential fix for the slow navigation. Can you check if the behavior has changed to the better or if it is still the same? Thanks.

**Comment by eugensim** [comment]
@oscarlorentzon it's ok now.

**Comment by oscarlorentzon** [comment]
Great that is works better. Thanks for confirming @eugensim!

Closing this issue then.
