### ISSUE TITLE
Drag-and-drop folder of geo-tagged images doesn't work as expected in Firefox

### ISSUE THREAD

**Issue by govvin** [mapillary/mapillary_issues#2331]
### Basic information
- Platform: `Web`
- Version: `...` 
- System/Browser: `Xubuntu 16.04 / Firefox 49`
### Steps to reproduce behavior
1. Drag-and-drop a folder of geo-tagged images in the Mapillary Uploader
### Expected behavior

Images will be uploaded to mapilllary.
...
### Actual behavior

Instead of proceeding with upload (I also use Chromium, which behaves as expected) it displays a directory listing of the images.
...
### Additional information

... 

![screenshot_2016-10-30_09-53-00](https://cloud.githubusercontent.com/assets/5821688/19833946/e301a036-9e86-11e6-80ef-f42eebb4e0ee.png)
![screenshot_2016-10-30_09-52-31](https://cloud.githubusercontent.com/assets/5821688/19833947/e304a0c4-9e86-11e6-9bb5-2c0277b1c9a6.png)

**Comment by gyllen** [comment]
@govvin Thanks for reporting

**Comment by nickplesha** [comment]
@govvin Thanks for reporting, this happens because Firefox doesn't support drag-and-dropping folders yet. Good news is that it should be available very soon: https://developer.mozilla.org/en-US/Firefox/Releases/50#Files_and_directories so it will start working automatically later this month! 🎉

**Comment by HolgerJeromin** [comment]
For your information: Firefox 50 is released. :-)
