### ISSUE TITLE
Issues with reviewing individual images in Android app (1)

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#2335]
### Basic information
- Platform:  `Android` 
- Version: `3.01` 
- System/Browser: `Samsung S5 6.01`
### Steps to reproduce behavior
1. Open upload "tab"
2. Select sequence
3. Select image in sequence
### Expected behavior

Selected image is displayed
### Actual behavior

Controls are displayed but no image.

**Comment by peterneubauer** [comment]
We are working on this. Is 3.05 better in this respect?

**Comment by rsahlin** [comment]
Please retest with latest (3.06) version.
