### ISSUE TITLE
Issues with reviewing individual images in Android app (2)

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#2336]
### Basic information
- Platform:  `Android` 
- Version: `3.01` 
- System/Browser: `Samsung S5 6.01`
### Steps to reproduce behavior
1. Open upload "tab"
2. Select sequence
3. Select image in sequence (not displayed see prev. issue)
4. Swipe page
### Expected behavior

Previous or next image should be displayed (if images were displayed at all)
### Actual behavior

Page number would indicate that a the image number has been reset to something small.

**Comment by peterneubauer** [comment]
Is this working now?

**Comment by simonpoole** [comment]
Sorry awlful weather here right now, will test asap.

**Comment by rsahlin** [comment]
Closing this issue since not having heard back.
The issue was fixed in 3.04 - please reopen if you still experience the problem.
