### ISSUE TITLE
expanded notification text is not always updated on upload

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2338]
### Basic information
* Platform: `Android` 
* Version: `302` 
* System/Browser: `Fairphone 2`

### Steps to reproduce behavior

 1. Hit upload on a sequence with 80 images
 2. Wait till all are uploaded
 3. Hit upload again on an other sequence

### Expected behavior

Upload finished icon in the "main android title bar" should be replaced with the uploading icon.
Expanded Notification should show the uploading text.

### Actual behavior
In the "android title bar" (not captured by the screenshot) and in the uploading notification the "upload finished icon" was still there. The Expanded notification showed the old info:

![image](https://cloud.githubusercontent.com/assets/2410353/19855675/1e6cef78-9f76-11e6-82e7-e6f9b8a67c81.png)

**Comment by rsahlin** [comment]
This has been fixed in the upcoming beta release 3.08
