### ISSUE TITLE
iOS: review view has misc issues

### ISSUE THREAD

**Issue by saerdnaer** [mapillary/mapillary_issues#234]
The gallery view stutters, the user can see the reusage of the lower tiles as the image get's replaced during he is scrolling up. Maybe increate the preload buffer etc...

When I went to detail view of a image, rotating my device doesn't zoom it up. I also expected some gesturers to work e.g. pinch to zoom or swiping left/right to see the next image.

iPhone 5, iOS 7.1.2, Mapillary 2.1

**Comment by jesolem** [comment]
The gallery and review views have been completely rewritten with version 3.0+. Should be fixed. Re-open otherwise.
