### ISSUE TITLE
Time travel pages shouldn't mention same username twice

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2340]
In a time travel page where both of the pictures were taken by the same user, [such as this one](https://www.mapillary.com/app/time-travel/?focus=photo&pKey=HM0tiMCNUlZ5pnIy51sDUA&cKey=N-CrNGGUrgJlIgcX_ZcnGg), there are several <meta> tags that say the pictures are "by nicolas17 and nicolas17".

If both usernames are the same, it should only be mentioned once; eg. `<meta content="Compare Mapillary photos from Argentina, by nicolas17" name="og:title">`

**Comment by gyllen** [comment]
@nicolas17 I also want to make the generated image a little fancier. Thanks for reporting!
