### ISSUE TITLE
Date of sequence is sometimes 31 Dec 1969

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2341]
Mapillary version info: 3.02, version code: 3.02 running on Google LG Nexus 5X with Android 7.0 patch level October 5, 2016

After the sequence is uploaded it cannot be filtered since first date of filter is jan 2000

Sometimes the cover picture for Dec 31 sequence is missing.

**Comment by rsahlin** [comment]
![dec31](https://cloud.githubusercontent.com/assets/3063192/19920122/1b528d7c-a0d7-11e6-9b70-a3887883e66b.png)

**Comment by rsahlin** [comment]
![31dec-nocover](https://cloud.githubusercontent.com/assets/3063192/19920295/32c77336-a0d8-11e6-9ef0-5d769beea8fa.png)

**Comment by kardotim** [comment]
I had January 1 1970 (epoch) the other day, but went back, and then into the sequence again and the date was corrected.

**Comment by rsahlin** [comment]
Interesting!
Thanks for reporting @kardotim :-)

**Comment by rsahlin** [comment]
This has been fixed in version 3.06
