### ISSUE TITLE
Preview blank if several hundred pictures in sequence

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2342]
Mapillary version info: 3.02, version code: 3.02 running on Google LG Nexus 5X with Android 7.0 patch level October 5, 2016

**Comment by rsahlin** [comment]
![blank-preview](https://cloud.githubusercontent.com/assets/3063192/19920428/e28eab72-a0d8-11e6-9d44-52d4dffdc0f7.png)

**Comment by HolgerJeromin** [comment]
I think this is a priority problem. The Thumbnails are generated for all images of the sequence and after that the current image is rendered. 
The thumbnailing of the sequence should be aborted when clicking one image.

**Comment by kardotim** [comment]
@rsahlin I had the same issue (on Honor 7, Android 6.0), but eventually, the image did load, did that also work for you? It could take up to 20-30 seconds though....

**Comment by rsahlin** [comment]
Hi
I will look into this now and find a solution where the user experience is much faster.

/Richard

**Comment by kardotim** [comment]
This is fixed now, right? @rsahlin :)

**Comment by rsahlin** [comment]
Yes, this was fixed in version 3.04
