### ISSUE TITLE
Alert dialog missing buttons

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2343]
Mapillary version info: 3.02, version code: 3.02 running on Google LG Nexus 5X with Android 7.0 patch level October 5, 2016

See attached image

**Comment by rsahlin** [comment]
![alert-missing-buttons](https://cloud.githubusercontent.com/assets/3063192/19920525/819f94d8-a0d9-11e6-93ed-36cce0e488a5.png)

**Comment by peterneubauer** [comment]
Fixed.
