### ISSUE TITLE
Map box should remain minimized during navigation 

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2344]
I think it's better that the map should be minimized if I clicked **"-"** button once.
https://www.youtube.com/watch?v=CmNbVZ-VhaI&feature=youtu.be

Windows 10
All browsers.

**Comment by gyllen** [comment]
@eugensim Yes this is a bug, thanks for reporting

**Comment by nickplesha** [comment]
@eugensim Thanks for noticing this, it has been fixed.
