### ISSUE TITLE
Better workflow when reviewing before uploading sequence needed (normalize sequence)

### ISSUE THREAD

**Issue by majkaz** [mapillary/mapillary_issues#2345]
I am uploading sequences from web uploader and end every time with additional edits which in part wouldn't be needed if only I could **normalize sequence before posting**.
For some reason, every photo from the BenQ phone gets wrong heading (turned 90 degrees). It is relatively easy to change wrong gps position before uploading, but this one I am leaving to mapillary, I don't see an easy way to do it by myself. 
I think this is the case why sometimes I get wrong direction arrows in the sequence, as well - for example [here](https://www.mapillary.com/app/user/majkaz?lat=48.972659789999966&lng=14.491850720000002&z=17&pKey=Cd6q4MhDj2yorOelS9LRhQ&focus=photo)

Majka

**Comment by gyllen** [comment]
Agree

**Comment by nickplesha** [comment]
@majkaz For now please use the editor for normalizing sequences and we'll be improving the uploader experience with your idea in mind,
