### ISSUE TITLE
use meaningful name for the apk file on the Mapillary Android app versions server

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2346]
The files on ```http://android-releases.mapillary.io/index.html``` are named ```app_release_NNN.apk```, which is a quite self-centric perspective. 

For people installing and testing other apps as well, it would be helpful to provide a self-explanatory name, such as ```Mapillary_android_NNN.apk```.

**Comment by peterneubauer** [comment]
Thanks, good input! Will change this.
