### ISSUE TITLE
Hitbox for minimap arrow is too big

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2347]
### Basic information
* Platform: Web
* System/Browser: Ubuntu, all browsers

### Steps to reproduce behavior

 1. Expect to click on photo point in the top-right corner of the small map.
 2. Click hitbox of the arrow in the corner is square, not triangular, so clicking expands map
 3. Cursor is the same for clicking the arrow as clicking the photo point

### Additional information

I'm not sure if it's even possible to make a triangular hitbox, but the way it is now is confusing. Perhaps make the hitbox square a lot smaller, so it basically just covers the actual arrow, but not the corners of the gray triangle?

**Comment by gyllen** [comment]
@pkoby Thanks for reporting we will see what we can do.

**Comment by nickplesha** [comment]
@pkoby Thanks for noticing this, this has been fixed.
