### ISSUE TITLE
iOS app with GoPro HERO3+

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_issues#2348]
### Basic information
* Platform: `iOS`
* Version: `4.5.4` 
* GoPro: `HERO 3+` 

### Steps to reproduce behavior

 1. Turn on my GoPro's wifi
 2. Open the Mapillary app and press the wifi symbol to the left. 
 3. Choose auto mode
 4. Press the big green start button to beging the capture process
 5. App crash and close, but GoPro was capturing photos

### Expected behavior

 1. No crash

### Actual behavior

 1. Crash and close

**Comment by millenbop** [comment]
I cannot reproduce this, but I've seen your crash log and the crash happens because the app couldn't create a random sequence UUID for some reason (haven't seen this before).

Has it crashed more than once? Has it worked before?

**Comment by kudarisenmon** [comment]
I cannot reproduce after my iOS restarted and it seems to work fine now.
It has worked before 23th, Oct.
then I updated iOS to 10.1.1 and Mapillary app to 4.5.4
thanks

**Comment by millenbop** [comment]
Ok, will close it for now. Please let me know if it happens again and I'll reopen and investigate further.
