### ISSUE TITLE
Can't login on website if size is < 900px

### ISSUE THREAD

**Issue by abienvenu** [mapillary/mapillary_issues#2350]
If the screen resolution if lower than 900px, the login and signup button on the upper right of the website homepage will not appear, and there is no horizontal scroll to go there. In other words, one cannot login at all!

**Comment by knikel** [comment]
@abienvenu: Which device are you using. By resolution do you mean width or height? Thanks!

**Comment by abienvenu** [comment]
I use Firefox on Ubuntu. The bug can be reproduced by resizing the browser window to less than 900px wide. I am talking about width.
