### ISSUE TITLE
Traffic sign detection for Qatar Using Mapillary

### ISSUE THREAD

**Issue by mallelaprasanth** [mapillary/mapillary_issues#2351]
I am new to Mapillary, want to know whether using Mapillary software can detect the traffic signs in any country (we are keen for Qatar region)?
API says that, Traffic sign detection is based on country and it has capability to detect for USA, Europe, Brazil, Australia and Canada. So need a bit clarification for region Qatar, If I take images in Qatar using Mapillary App or by means of someother camera and then upload those images into Mapillary. Then can I be able to get the traffic signs automatically detecting using the software?

Appreciate if I get any help.

Thanks,
Prasanth

**Comment by ybkuang** [comment]
This has been resolved by the recent [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
