### ISSUE TITLE
Single-or last pics in sequence can't be blurred right now

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2352]
### Basic information
* Platform: `iOS` | `Android` | `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Open https://www.mapillary.com/app/index/addismap?lat=49.980111944444445&lng=8.074826944444453&z=17&pKey=0WUGudS5zwVRNGPiNvCRxA&focus=photo&menu=false
 2. Blur
 3. Click "Submit and +"

### Expected behavior

Submit the blur, maybe jump out of the sequence since it's ending

### Actual behavior

No blur submit, exit discard popup
...

### Additional information

... 
<img width="1440" alt="fullscreen_11_7_16__10_01_am" src="https://cloud.githubusercontent.com/assets/11977/20051805/2dbd9968-a4d1-11e6-99d6-24e093518d59.png">

**Comment by HolgerJeromin** [comment]
The GUI says the blur were requested. Blurring is at least locked if you close the dialog.

**Comment by amenk** [comment]
what does that mean?

**Comment by peterneubauer** [comment]
Yes, so the second step - going to the next image - is not working

**Comment by amenk** [comment]
But the blur does not seem to be saved at all - also not locked.

**Comment by nickplesha** [comment]
Thanks for reporting this, submitting blurs on the last image of the sequence should exit out of blur mode after successfully saving blurs. I didn't take into account sequences of just one image when implementing this, though. 😄  This has now been fixed for sequences of all sizes.

**Comment by amenk** [comment]
Nope ... can't submit a blur on https://www.mapillary.com/app/index/addismap?lat=49.981316944444416&lng=8.074502777777752&z=17&focus=photo&pKey=vpuGW_ceZwopur9b36LOUQ&menu=false   - I click submit, but nothing happens, the image is not locked / nor there is a notification that my blur request was submitted.

**Comment by gyllen** [comment]
@amenk It might be that the latest version of the web has not yet been deployed. Can you check now.

**Comment by amenk** [comment]
I don't think so - It already looked like Web 2.0 *SCNR
nope, still not working, even after reload

**Comment by amenk** [comment]
post formdata:

     method:call
     callPath:["blurRequest"]
     arguments:["vpuGW_ceZwopur9b36LOUQ",[{"rect":[0.9266497967993084,0.1305401489962177,0.11362351923230385,0.3064053765001257],"type":"user"}]]
     pathSuffixes:[]
     paths:[]

response:

    {"jsonGraph":{},"paths":[]}

**Comment by gyllen** [comment]
@amenk What browser are you using, I just tried blurring a license plate on that image and it went through (vpuGW_ceZwopur9b36LOUQ)

**Comment by amenk** [comment]
Both, chrome and firefox are not working. Maybe it is because the image is from my account? But it looks like you are also using my account as I see blur requests which are not from me?

**Comment by amenk** [comment]
I can also reproduce on browserstack, `os=Windows&os_version=10&browser=Chrome&browser_version=54.0`

**Comment by gyllen** [comment]
@amenk Actually I did use my account, there is a bug in the notification system right now so it looks like it was you (soon to be fixed).

Is it just the last image in a sequence that you can not blur?

**Comment by amenk** [comment]
Yes. This image is a single image of a 1 image sequence

**Comment by gyllen** [comment]
@amenk Trying to debug, what happens if you try to blur in this image -> https://www.mapillary.com/app/?menu=false&lat=34.10391618669101&lng=-118.3448177576065&z=17&pKey=YE2o3kOX9tnn9E19NSxCWg&focus=photo

**Comment by amenk** [comment]
I don't have any bluring option on this picture at all ...

Different problem from the one at my picture.

**Comment by gyllen** [comment]
<img width="318" alt="screenshot 2016-11-12 18 10 19" src="https://cloud.githubusercontent.com/assets/268859/20243211/538c89b6-a903-11e6-9caf-5fc7796fb747.png">

Are the button that highlighted in green here missing for you?

**Comment by amenk** [comment]
Jep

**Comment by gyllen** [comment]
@amenk Stupid question are you logged in?

**Comment by amenk** [comment]
yes ... we can do teamviewer if you want?

**Comment by gyllen** [comment]
@amenk I will not have time todo that today, but next week will work. In the meantime can you see the blurring button on ANY image?

**Comment by amenk** [comment]
Yes; I do see the blur button on most images. Only not on the one you posted.
On *my* image, I do see the blur button, can use the blur function but when I submit, nothing seems to happen.

**Comment by gyllen** [comment]
@amenk What your Mapillary username?

**Comment by amenk** [comment]
addismap

**Comment by gyllen** [comment]
Looks to me that you managed to submit 13 blurs at least. Can you try todo a blur and see if you get something in your feed after that?

**Comment by amenk** [comment]
Sure, I did bluring on other image. The main problem is that image:

https://www.mapillary.com/app/index/addismap?lat=49.981316944444416&lng=8.074502777777752&z=17&focus=photo&pKey=vpuGW_ceZwopur9b36LOUQ&menu=false

1. Blur my face
2. Click submit
3. nothing in the feed
4. I still can choose edit blurs (expected: "There are pending blur requests")

**Comment by gyllen** [comment]
Yes and I can also see that you have not added a new blur, can you copy your exect curl request from chrome and sen it to me on gyllen@mapillary.com ?
