### ISSUE TITLE
uploads not finishing

### ISSUE THREAD

**Issue by hughdavenport** [mapillary/mapillary_issues#2355]
Android 3.04.

I'm taking sequences during my commute, and now the uploads don't finish overnight. The rate they are going suggests they should, but they must stop at some point then not restart. Means the next day there isn't enough space.

**Comment by hughdavenport** [comment]
Sent some logs

**Comment by hughdavenport** [comment]
Sigh... I suggest you go with option 1. You guys do a great job of pretending to be open...

Delivery to the following recipient failed permanently:

     logs@mapillary.com

Technical details of permanent failure: 
Your email to group logs@mapillary.com was rejected due to spam classification. To address this issue:

* Contact the owner of the group, who can choose to enable message moderation instead of bouncing these emails.
* Set up SPF records for your sending domain if you have not done so already.

Instructions for both steps can be found here: https://support.google.com/a/answer/168383

...

Received-SPF: pass (google.com: domain of hugh@davenport.net.nz designates xxx.xxx.xxx xxx as permitted sender) client-ip=xxx.xxx.xxx.xxx;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of hugh@davenport.net.nz designates xxx.xxx.xxx.xxx as permitted sender) smtp.mailfrom=hugh@davenport.net.nz

**Comment by hughdavenport** [comment]
[mapillary.log.zip](https://github.com/mapillary/mapillary_issues/files/584090/mapillary.log.zip)

**Comment by gyllen** [comment]
@hughdavenport Checking email address and assigning

**Comment by gyllen** [comment]
@peterneubauer Can you check why log sending does not work?

**Comment by voschix** [comment]
I seem to have a similar problem (on two different Android phones): I am trying to upload 70000 pictured in 200 sequences from the phone. I managed to understand the interface and can launch an upload that should upload all photos in all sequences in one go. However that does not work. I noticed, and this applies to both phones, that when the screen goes to sleep, the upload stops. I need to restart it manually. The longest time I can keep the display from going to sleep is 30 minutes - I have not fond a way to disable the sleep function altogether, hence I have to restart the upload every 30 minutes.

**Comment by hughdavenport** [comment]
I wouldn't hold your breath on an official response or a fix... I just uninstalled the app. Their advice for other bugs was for me to make my own truly open source app.

You can get images uploaded manually if you download to a computer and use their python scripts, but it is a bit much work for simple use.

Cheers,

Hugh

**Comment by peterneubauer** [comment]
@hughdavenport thanks for reporting the issue. We are trying to change the spam settings - not that easy with google it seems.

As for the issue - hopefully we can release an alpha with this fixed tomorrow.

**Comment by hughdavenport** [comment]
Has this been fixed? Impressed with your lack of response after "tomorrow"

**Comment by peterneubauer** [comment]
Yes, sorry for not closing it. The fix has been out since Mapillary 3.12 so please test and report here if it's not working. Closing for now.
