### ISSUE TITLE
Connecting accounts doesn't refresh page

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2356]
On https://www.mapillary.com/app/settings/profile
for each of the four accounts we connect,
we must manually refresh the page,
else it looks like nothing happened.

**Comment by gyllen** [comment]
@jidanni Thanks for reporting

**Comment by gyllen** [comment]
@nickplesha Reassigning to you for checking

**Comment by nickplesha** [comment]
This has been fixed, thanks for reporting!
