### ISSUE TITLE
Panoramio final shutdown is November 2017, not 2016

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2357]
On https://www.mapillary.com/alternative-to-panoramio you say

> If you’d like to migrate to Mapillary before the Panoramio shutdown November 4th, 2016...

Well according to http://www.panoramio.com/maps-faq

> . after November 4, 2016, you’ll still have access to your photos and be able to export your data until November 2017.

So please say

> If you’d like to migrate to Mapillary before the Panoramio shutdown November 2017..

**Comment by jidanni** [comment]
However it seems the API might not work anymore,
https://groups.google.com/forum/#!topic/panoramio-questions-support/Ie2hy7hBSls
therefore you need to use e.g., WWW::Mechanize to go through the each page of the user's Panoramio account, downloading each photo, most of which will contain exif data... If they were taken with such a camera and not manually geotagged...

**Comment by jidanni** [comment]
But wait, e.g.,
http://www.panoramio.com/photo/43605707 when downloaded is missing its
title, and exif coordinates. (It was taken with a pre-GPS camera and was
manually geocoded.)

However, according to http://www.panoramio.com/maps-faq

> Tip: Link your Panoramio account with your Google+ account to automatically copy your photos to the Google Album Archive and continue to share your work in Google Maps.

and indeed the same photo in the user's private
https://get.google.com/albumarchive/...
has both still intact!

$ cd ~/Downloads/ && exif 43605707.jpg 台中東勢燥坑向上坡看.jpg | sort | uniq --unique
Altitude Reference  |Sea level
Compression         |JPEG compression
EXIF data contains a thumbnail (6259 bytes).
EXIF tags in '43605707.jpg' ('Intel' byte order):
EXIF tags in '台中東勢燥坑向上坡看.jpg' ('Intel' byte order):
East or West Longitu|E
GPS Tag Version     |2.2.0.0
Image Unique ID     |d4c518bcbbdcc724a46ae36ab9d4f433
Latitude            |24, 10, 43.478
Longitude           |120, 51, 52.243
Maker Note          |1132 bytes undefined data
Maker Note          |1258 bytes undefined data
North or South Latit|N
X-Resolution        |72
Y-Resolution        |72

So it seems one would need to write a WWW::Mechanize script the user
would run that would download each photo from his get.google.com account
and upload it into Mapillary...

Anyway, I have located 1500 out of about 2900 of my Panoramio photos
there on get.google.com ... so its a start...

**Comment by jidanni** [comment]
Hmmm. each album, e.g,.
https://get.google.com/albumarchive/107326194379039522045/album/AF1QipM0TH8llK2C_rDfUcNrk6-atZkWHdDnd55wXqGr
has a Download Album options...

**Comment by gyllen** [comment]
@eneerhut Will know all about this

**Comment by eneerhut** [comment]
@jidanni The wording refers to general Panoramio features and access which have now been shut down. The API as you mentioned is no longer accessible as of the 4th of November.

I'll reword the text accordingly. 
Thanks for looking into WWW::Mechanize as an option. Can we experiment with your account using the links provided and see if we can come up with a workable solution?

**Comment by jidanni** [comment]
Yes you are welcome to experiment. But I suspect the only "intact" photos will probably have to be scraped from the user's https://www.google.com/maps/contrib/ photos tab, which by the way shows many photos which might in fact be 'unlisted'!
https://groups.google.com/forum/#!topic/panoramio-questions-support/hsaV4_p8bSo

**Comment by eneerhut** [comment]
Closing as support for Panoramio is no longer available. Also, mapillary_issues is no longer an active repository.

Let’s continue discussing features in our [forum](https://forum.mapillary.com).
