### ISSUE TITLE
auto mode tapping changes

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2359]
ios app was recently updated to have auto/manual modes. it is great, but there are a few usecases that have become somewhat worse :
* while the auto mode is on, one cannot change the exposure point anymore. this was something i used quite a lot when driving - if there's very bright sky ahead, set the exposure point lower. if approaching a forest, set the exposure point back to the centre. actually, i took quite a lot of photos with incorrect exposure, as i tapped the screen and wondered why is the exposure point not changing...
* while the auto mode is on, it looks like a tap anywhere in the picture area takes a new picture. this is real awesome in general... except when capturing while walking. then, it is much more comfortable to hold the phone so that one or more fingers are in the picture area, and this now frequently results in excess pictures being taken.

how about adding two extra controls in the sidebar ?
* a switch to allow/disallow changing exposure point
* a button to take a manual photo

**Comment by millenbop** [comment]
I see your point. I have to think about this for a moment to not confuse new users. 

There is room top right for a button but sort of confusing to have two capture buttons I think. 

Another way is to have a button for setting the exposure point, i.e. tap "Set exposure" and then tap on the picture. That would require two taps. 

And a third option is to use long-press, but that makes it an even more hidden feature.

(Personally I don't use the app that way, i.e. I only use it for driving and set it on the road only once)

**Comment by richlv** [comment]
long press might not work - it would be constantly triggered while holding the phone when walking.

'set exposure' might be a bit of a problem, too - when driving, i tend to change exposure a few times, if the first attempt does not result in a good outcome (like the sky being so bright i have to set the exposure point lower and lower to get a better lighting).

right now i'd prefer a separate button for manual capture and a switch for 'lock screen/image' - when unlocked, one could set exposure. when locked, one could hold the phone while walking without constantly messing something up.
but the manual capture button should still work, as it is even more useful when walking.

**Comment by millenbop** [comment]
We are currently redoing the camera. You will able to set exposure while capturing and there will be a separate button for taking an extra photo.

**Comment by millenbop** [comment]
This was fixed/released last week, closing.

**Comment by richlv** [comment]
setting exposure while taking pics is now possible, thank you :)
what about taking a pic manually in the automatic mode, how is that possible ?

**Comment by millenbop** [comment]
You use the white button when you have started the capture. I noticed that I forgot to add it to some devices, sorry, so I have fixed it today and submitted an update. So if you don't currently have it, it will be available soon.

**Comment by millenbop** [comment]
![img_6126](https://user-images.githubusercontent.com/12835674/27083992-a40b1ef4-504a-11e7-88b4-f1ddc13ec801.PNG)

**Comment by richlv** [comment]
thanks, the button was missing for me before - got it now after the latest updates :)

**Comment by millenbop** [comment]
Great!
