### ISSUE TITLE
Keep last automatic mode (time vs distance) after switching from manual

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2360]
### Basic information
* Platform:  `Android`
* Version: `3xx` some recent betas :-)
* System/Browser: `Fairphone 2`

### Steps to reproduce behavior

 1. Capture some images with auto mode, set to distance based
 2. Changing to manual mode for sequences by foot
 3. Change again to auto mode

### Expected behavior
I should have auto mode with the last used method: distance based

### Actual behavior
Falls back to time based

**Comment by HolgerJeromin** [comment]
This was bad in the past but the mode (distance vs time)  is not shown and not changeable in the current camera gui, only in the settings. So switching from manual to auto capture sets the unwanted time based capturing.

**Comment by peterneubauer** [comment]
Yes,
The default should be auto distance though.

**Comment by peterneubauer** [comment]
should be working in the latest releases.
