### ISSUE TITLE
uploading automatically on cell data when upload on cell turned off

### ISSUE THREAD

**Issue by hughdavenport** [mapillary/mapillary_issues#2361]
Android 3.04

The upload in background option was turned on which clearly says wifi only. The cell option was turned off. Never actually automatically uploaded on wifi, but always on cell.

I'm actually really disappointed in the amount of bugs coming out of this app, the lack of response on issues raised, the fixes just causing other issues. For a company that pretends to be all about openness I'm amazed that you don't open source the app, i see no reason why it shouldn't. It doesn't even have any business logic in it... If you open it, everyone in the community can help debug, triage, fix all of these issues.

This is the last issue I'm reporting, and the last time I'm using the app, until you do something meaninful to show your commitment to the community (like replying to reports, actually fixing them, or open sourcing an app that has no business logic to hide). Thus this is also the last time I'm contributing to the project sadly.

**Comment by pcopley** [comment]
Is it somewhat telling that neither @gyllen nor @rsahlin felt the need to reply to the valid criticisms raised here?

**Comment by peterneubauer** [comment]
Hi there,
this is indeed a valid bug that we are fixing as we speak (will be out in the next release). As for OSS the Android app, we are tracking that under https://github.com/mapillary/mapillary_issues/issues/1124 and will eventually get there.

**Comment by rsahlin** [comment]
Hi @hughdavenport 

Sorry that you experience problems with the app and feel that we are unresponsive in our replies.
We will have to improve in this area!

I am workin on fixing the upload behavior, this includes a rewrite of the upload logic to a service, adding a number of user interaction elements and resume functionallity.
This is expected to go out to beta developers next week.

Hope that you will be happy with the upcoming releases!

Best regards
/Richard

**Comment by hughdavenport** [comment]
Ah great, the one thats been open for over a year and no comments for the last four months and no reasonable replies when anyone asks on the status... I won't hold my breath, already uninstalled as it has cost me quite a bit in data fees because of this bug, and i don't expect you to fix it properly.

I'm very confused why you have open sourced the windows app but not the android one, as I mentioned before, I can honestly not think of a reason why it isn't. Surely there isn't any business logic in this app that needs protecting.

As for timely responses, i think the fact that people were silently assigned to this ticket and noone actually responded for almost a week shows that you aren't actually making an effort to improve these comms.

**Comment by hughdavenport** [comment]
From reading the other bugs on the open source issue it sounds like you don't actually have any business logic you want to find, but that the code isn't in a clean state and you want to refactor and clean it up first. Instead, heres and idea. Step 1, open source the app as it is now, step 2, file bugs about the cleanup tasks you want done, step 3, watch pull requests come in. Simple! If you really have any enthusiasm for open sourcing then you shouldn't hesitate with that suggestion. I'll check for your reply in a week

**Comment by HolgerJeromin** [comment]
@hughdavenport The windows phone app was [not developed](http://blog.mapillary.com/update/2014/05/15/windows-phone-released.html) by mapillary staff. 
Perhaps the android/iOS app is using some program parts which mapillary is not allowed to release to github.

**Comment by peterneubauer** [comment]
@hughdavenport if you want to build your own Android app now -  all code you need is already working for JOSM - OAuth, upload of normal EXIF images into Mapillary, submitting changesets on them. https://github.com/JOSM/Mapillary/tree/master/src/org/openstreetmap/josm/plugins/mapillary/oauth

**Comment by hughdavenport** [comment]
I notice #1124 is once again lost to the world. I really wish you would either just give up pretending you have an open source stance, or better yet, just do it

**Comment by peterneubauer** [comment]
that is a Github error (500). Will check later to see if they recover.

**Comment by peterneubauer** [comment]
We are trying to release an alpha fixing this tomorrow, so you can test. Thanks!

**Comment by rsahlin** [comment]
This has been fixed and will be released very soon as version 3.08 to the Beta channel.

**Comment by hughdavenport** [comment]
Good to see you followed up with github on unhiding issue #1124. Not.
