### ISSUE TITLE
Website is messed up in midori browser

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2363]
Usually if some website doesn't work in Chrome or Firefox, it will in Midori. But for me mapillary.com is even more messed up in midori right now.

### Basic information
* Platform: `Web`
* System/Browser: `Linux Mint 18 Cinnamon 64bit, Midori Browser`

![mapillary](https://cloud.githubusercontent.com/assets/1220707/20240519/8e555bb0-a91a-11e6-8268-95e9d76ddc3e.png)

**Comment by gyllen** [comment]
@mxa Is it messed up for you in chrome too?

**Comment by mxa** [comment]
Had some issues yesterday in the edit mode in Chrome, checked today and it seems to work now. It's not messed up as it is in midori.

**Comment by gyllen** [comment]
@mxa Ok thanks for reporting, not action on this for now but keeping open.

**Comment by mxa** [comment]
Seems like this is mostly okay now. Minor detail is the backward, play, forward buttons which are overlapping.

![screenshot from 2018-02-04 14-22-49](https://user-images.githubusercontent.com/1220707/35777952-f56ca97c-09b6-11e8-966f-d987e5f1d42d.png)
