### ISSUE TITLE
Web uploader does not check for identical time stamps

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2364]
### Basic information
* Platform: `Web`
* System/Browser: *`Any`*

### Steps to reproduce behavior

1. Go to [sequence `xJsF5RgrG6B0pseKLBKRdQ`](https://www.mapillary.com/app/?focus=map&pKey=Yl6LP_pplucMbsQyw_ItGw)
2. See the mess

Presumably, this is because the time stamp seems to be identical for all photos in the sequence. This sequence seems like it has been uploaded manually via web upload. If the original file names have been preserved on upload they might give a clue to what the correct order may be.

**Comment by gyllen** [comment]
Yes definitly seems like a timestamp problem, would you mind commeting on one of that users images and ask they can delete and reupload?

**Comment by GITNE** [comment]
>Yes definitly seems like a timestamp problem, would you mind commeting on one of that users images and ask they can delete and reupload?

Okay, I am going to do it.

I just wanted this on the issue tracker because this may be a general recurring problem which may need some front- or backend coding if time stamps are identical. Hmm, the web uploader should probably check on that before one can hit the upload button.

**Comment by GITNE** [comment]
Since the immediate problem has been fixed by deleting the sequence `xJsF5RgrG6B0pseKLBKRdQ`, I have renamed this issue to better reflect the cause of the issue and what to fix.

However, I do not know if the owner of that sequence has uploaded it again, that is, same content without any disorder.

**Comment by gyllen** [comment]
@nickplesha Moving to you for investigation (if fixed or now)

**Comment by nickplesha** [comment]
The uploaded image filename still contains the original filename (with some metadata added) and can be used during processing.
