### ISSUE TITLE
upside-down sequences

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2365]
a few sequences with images upside-down. it might be worth checking all images before rotating them.

* https://www.mapillary.com/map/im/gR-LaFurQ--CbWJJQysjZQ
* https://www.mapillary.com/map/im/zDKOEtwKZf_mgGuaWRoPgQ

**Comment by richlv** [comment]
another one, but only a few first images are upside-down :
* https://www.mapillary.com/map/im/m2AwbYI3dMsrs-f6WL-ksw

**Comment by hughdavenport** [comment]
Dup of #2327. May be fixed? Wouldn't hold my breath on an update though

**Comment by AleZena** [comment]
Same here using a Samsung S3
https://www.mapillary.com/map/im/LjHYisKX1MBYKTJzyPLuZg
https://www.mapillary.com/map/im/Mi1M31tj40n2jpTy7S_uJw

**Comment by ybkuang** [comment]
Related to https://github.com/mapillary/mapillary_issues/issues/531..

mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
