### ISSUE TITLE
web uploader has weird 'failed' errors. Confusing and chaotic. 

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2366]
I thought the android app was prone to mysterious upload failures, but it happens with the web uploader as well. 

When uploading a single 147 frames sequence, I got a message box that 126 were uploaded, and 19 failed, with a red button to "retry". When I press this button, one more file uploads with a progress bar "uploading 1/19", and the fail-box comes again. 

Later, and without the progress bar, it seems to continue with uploading some more files, and the upload count goes up. Example below. 

![upload-fail](https://cloud.githubusercontent.com/assets/8266355/20250243/949b7d22-aa0c-11e6-9c05-209dc38e2ed2.png)

Eventually I get a "Publish all" box, with more 'unpublished' pictures than I had uploaded, and an increasing count of uploading pictures above. 
![publish_all1](https://cloud.githubusercontent.com/assets/8266355/20250420/d4384af8-aa0e-11e6-8f39-0c256df267d0.png)
![publish_all2](https://cloud.githubusercontent.com/assets/8266355/20250433/e3e11d9a-aa0e-11e6-989a-98c0f43706ac.png)

What's going on here? Is it uploading everything a second time?

Eventually I get impatient, since i'd like some sleep, and I press the "Publish all", and get a message that 159 files have been published for processing. Still here, it continues uploading, and the counter goes up. 

![publish_all3](https://cloud.githubusercontent.com/assets/8266355/20250438/eb43c63c-aa0e-11e6-8bdf-de371eba02ea.png)

Still my upload-bandwidth is being used, and it counts 168 pictures now. 

Trying to press "Exit uploader", still the upload bandwidth continues. However the feed tells me that finished uploading 147 frames as intended, 10 min ago. Still the upload bandwidth continues. Closing the mapillary browser window, the upload bandwidth vanishes. 

(Browser: Safari 10.0 on MacOS 10.11.6)

**Comment by polarbearing** [comment]
Meanwhile, the feed has changed, telling me that I uploaded 159 pictures and not the real 147, also the emails for uploading and "on the map" talk about 159. 

Thus we definitely have duplicates.

Despite the message that the sequence is on the map, it does not show the trace. I can only click on individual handles in the feed. [Example](https://www.mapillary.com/app/user/polarmap?lat=20&lng=0&z=1.5&pKey=jgYNMqaiWIuLjhnkb93-RA)

Also a sequence I uploaded on Nov 13 is not visible on the website (though it shows up in JOSM).

**Comment by gyllen** [comment]
@polarbearing It looks like it showing up now and that the navigation works. Can you send a key to the images showing up in JOSM but not on the web.

For the webuploader bug Im filing that as the issue.

**Comment by polarbearing** [comment]
The trace form the example is visible on the website meanwhile, indeed. Still the sequence has an image count of 159 of which only 147 can be unique.

Currently, in my [username]'s uploads, each sequence since Oct 9 is shown twice (with the same sequence ID, so no real duplicates).

**Comment by polarbearing** [comment]
Hm, it's even weirder. The trace of the sequence is visible in Seamonkey(Mozilla), but not in Safari.

**Comment by polarbearing** [comment]
Could reproduce the problem today. There was a real network disconnection during the web upload. Consequently there was a failed-count. The "Retry" button is confusing, since it continues automatically but without progress bar. Once all were uploaded, it started again, so I closed the browser window to prevent too many duplicates.

**Comment by nickplesha** [comment]
@polarbearing We've added better disconnection handling in the web app and uploader. If you see a blue banner at the bottom that means that the app has detected the connection is offline. When this happen during uploading, please refresh the page, the state of uploaded images is maintained on the server and you'll be able to resume again when you reconnect.
