### ISSUE TITLE
A sequence has been weirdly splitted and can't be edited

### ISSUE THREAD

**Issue by NicolasDumoulin** [mapillary/mapillary_issues#2367]
Hi,

A sequence was looking good at uploading step, but after it some parts have been splitted.
See for example this picture https://www.mapillary.com/app/?lat=45.745655&lng=3.0850000000000364&z=17&pKey=Cj03we9pZhM567Gn2PPGrg&focus=map
The next one in the sequence is wrongly linked to another part in the sequence, so the sequence is messed up.
Again, the sequence was looking fine at upload step, and I've not edited the photo timestamp. I've just edited some blurs in the sequence.

**Comment by gyllen** [comment]
@NicolasDumoulin *investigating* What platform did you upload the images from?

**Comment by NicolasDumoulin** [comment]
Chromium 53.0.2785.143 running on Ubuntu 16.04 (64-bit)
Thanks

**Comment by gyllen** [comment]
@peterneubauer Would you mind checking the originals of these images, looks like there might be a timestamp issue

**Comment by gyllen** [comment]
Splitting are now a solid feature, closing
