### ISSUE TITLE
EXIF position not read in manual uploader

### ISSUE THREAD

**Issue by PavolG2** [mapillary/mapillary_issues#2369]
### Basic information
* Platform: `Web`
* System/Browser: `Win 7 PRO, Firefox 49.0.2`

### Steps to reproduce behavior

 1. Upload attached picture via the manual uploader

### Expected behavior

Photo uploaded and placed on the correct place :-)

### Actual behavior

N/A lat,lon, so the picture is placed on coordinates 0,0

One of the affected files. Correctly displaying position in all my apps:
![2011-09-25 - 1455](https://cloud.githubusercontent.com/assets/23460115/20277806/66d427ae-aaa2-11e6-8816-f208bae74522.jpg)

### Additional information

...

**Comment by GITNE** [comment]
Thank you for providing the original photo.
After a first quick analysis, the GPS location fields have an invalid seconds component of `0/0` which gives a division by zero error. In this case, the GPS Info IFD is invalid. Hence, some software may be designed to discard the entire field and replace it with a valid one of `0°` (`0/1` `0/1` `0/1`), which seems like a reasonable tolerance strategy. Do you pre-process the files somehow before upload?

**Comment by GITNE** [comment]
Besides, I have also noticed that some of the EXIF time stamp fields show unusual discrepancies:

`Date and Time |2011:10:24 20:42:33`
`Date and Time (Original) |2011:09:25 14:36:54`
`Date and Time (Digitized)|2011:09:25 14:36:54`

Wow, this is almost like a month apart!

**Comment by PavolG2** [comment]
GPS info is added by the Zoner Photo Studio (ZPS) or Geosetter. Especially the second one is probably the most used tool for editing GPS information for Windows platform. So hopefully is writing correct data ;-)
Corrdinates are properly shown in both of them. Also in ACDSee, Adobe Bridge, Google Earth, Panoramio, JOSM editor.

Dump of exif from the correct file
<exif:GPSLongitude>21,14.207220E</exif:GPSLongitude>
         <exif:GPSLatitude>48,42.411980N</exif:GPSLatitude>
         <exif:GPSAltitude>287000/1000</exif:GPSAltitude>
         
Dump from the faulty file
<exif:GPSLongitude>21,13.899180E</exif:GPSLongitude>
         <exif:GPSLatitude>48,43.170952N</exif:GPSLatitude>
         <exif:GPSAltitude>304000/1000</exif:GPSAltitude>
         

I can't see the difference :-/

Maybe only one hint can be, that the faulty one was saved after processing as a TIF and after that converted to JPG.


The time dicrepancies come from the postprocessing. New file was physically created a month ago... Photoshop is not preserving the filedate from the original one.

**Comment by GITNE** [comment]
> I can't see the difference :-/

Well, just compare these:
```xml
<exif:GPSLongitude>21,14.207220E</exif:GPSLongitude>
<exif:GPSLongitude>21,13.899180E</exif:GPSLongitude>
```
You can already observe a slight discrepancy which hints at something is going wrong. Besides, technically you cannot judge by these *computed* values. The GPS Info IFD fields are what matters. And, they are clearly **invalid**. So, some tool in your chain of tools is producing invalid GPS Info IFDs. :worried: Sorry.

> The time dicrepancies come from the postprocessing. New file was physically
> created a month ago... Photoshop is not preserving the filedate from the
> original one.

Okay, then this should explain it.

**Comment by PavolG2** [comment]
Sorry, still cannot see the formatting difference between the correct and non-correct value... 
Can you recommend me, which tool can show me the fraction "raw" values with the wrong 0 value instead of 1? Will try to find the software making the mess.

PS: if all relevant and widely distributed software solutions (e.g Adobe) can handle those files, maybe it's not the worst idea to handle them in mapillary too ;-)

**Comment by GITNE** [comment]
> Can you recommend me, which tool can show me the fraction "raw" values with the wrong 0 value instead of 1? Will try to find the software making the mess.

[`exif`](http://libexif.sourceforge.net)
It is a companion tool of the [`libexif`](http://libexif.sourceforge.net) package, so it is not a standalone tool but a mere tool for testing for developers. Hence, I am not sure if a safe Windows binary may be available somewhere. However, a comparable tool, which is not based on `libexif` may exist for Windows but I am not aware of. Besides that, you can use any hex viewer or editor too.

> PS: if all relevant and widely distributed software solutions (e.g Adobe) can handle those files, maybe it's not the worst idea to handle them in mapillary too ;-)

The thing is, that this issue falls into the realm of fault tolerance and one can hardly blame developers for adopting one specific strategy over another when dealing with invalid input data. Sure, one could argue that the strategy that e.g. Adobe or JOSM developers have chosen may seem a bit more sane in this specific case but they also may have adopted vastly different tolerance strategies in other cases of invalid input data. So, there is no right or wrong when it comes to tolerating invalid input. Anyhow, I think it would have been best if those tools were at least warning users that they are processing invalid data and are presenting *corrected* fault tolerated results to users to work with. This would prevent any future confusion and would also prevent further proliferation of invalid data (or faulty formatted data). In any event, it is a *very* *very* special case, so I would not be surprised if this would not be addressed by Mapillary at all. :wink:

**Comment by GITNE** [comment]
> Can you recommend me, which tool can show me the fraction "raw" values with the wrong 0 value instead of 1?

@PavolG2 You may use the [exiv2](http://www.exiv2.org) tool on Windows to get a precise idea of what is going on with your EXIF meta data. And, although it seems to have not been maintained for over a year now, it really is pretty neat. The author provides a Windows binary too, so you should be ready to go immediately.

Just check this out:
```
> exiv2 -Pvl 66d427ae-aaa2-11e6-8816-f208bae74522.jpg
Image Width 1355
Image Length 900
Compression 1
Photometric Interpretation 2
Manufacturer NIKON CORPORATION
Model NIKON D5000
X-Resolution 1207959552/16777216
Y-Resolution 1207959552/16777216
Planar Configuration 1
Resolution Unit 2
Software Ver.1.00
Date and Time 2011:10:24 20:42:33
YCbCr Positioning 1
Exif IFD Pointer 270
Exposure Time 1/400
FNumber 10/1
Exposure Program 2
ISO Speed Ratings 400
Sensitivity Type 0
Exif Version 48 50 50 49
Date and Time (original) 2011:09:25 14:36:54
Date and Time (digitized) 2011:09:25 14:36:54
Components Configuration 1 2 3 0
Shutter speed 8643856/1000000
Aperture 6643856/1000000
Exposure Bias 0/6
Max Aperture Value 36/10
Subject Distance 4294967295/1
Metering Mode 5
Light Source 0
Flash 0
Focal Length 180/10
Sub-seconds Time Original 50
Sub-seconds Time Digitized 50
Color Space 65535
Pixel X Dimension 1355
Pixel Y Dimension 900
Sensing Method 2
File Source 3
Scene Type 1
Color Filter Array Pattern 2 0 2 0 1 2 0 1
Custom Rendered 0
Exposure Mode 0
White Balance 0
Digital Zoom Ratio 1/1
Focal Length In 35mm Film 27
Scene Capture Type 1
Gain Control 1
Contrast 0
Saturation 0
Sharpness 0
Subject Distance Range 0
Body Serial Number 6607572
Lens Specification 180/10 550/10 35/10 56/10
Lens Model 18.0-55.0 mm f/3.5-5.6
GPS Info IFD Pointer 952
GPS Latitude Reference N
GPS Latitude 48/1 431710/10000 0/0
GPS Longitude Reference E
GPS Longitude 21/1 138992/10000 0/0
GPS Longitude 21,13.899180E
GPS Latitude 48,43.170952N
GPS Altitude 304000/1000
GPS Altitude Reference 0
Exif Version 0221
Exposure Time 1/400
Shutter Speed Value 8643856/1000000
F Number 10/1
Aperture Value 6643856/1000000
Exposure Program 2
Date and Time Original 2011-09-25T14:36:54.50+02:00
Exposure Bias Value 0/6
Maximum Aperture Value 36/10
Subject Distance 4294967295/1
Metering Mode 5
Light Source 0
Focal Length 180/10
Sensing Method 2
File Source 3
Scene Type 1
Focal Length In 35mm Film 27
Custom Rendered 0
Exposure Mode 0
White Balance 0
Scene Capture Type 1
Gain Control 1
Contrast 0
Saturation 0
Sharpness 0
Subject Distance Range 0
Digital Zoom Ratio 1/1
ISOSpeedRatings 400
Flash type="Struct"
Flash/exif:Fired False
Flash/exif:Return 0
Flash/exif:Mode 0
Flash/exif:Function False
Flash/exif:RedEyeMode False
Pixel X Dimension 4288
Pixel Y Dimension 2848
Make NIKON CORPORATION
Model NIKON D5000
Image Width 4288
Image Length 2848
Samples Per Pixel 3
Bits Per Sample 8, 8, 8
Photometric Interpretation 2
X Resolution 240/1
Y Resolution 240/1
Resolution Unit 2
Modify Date 2011-10-20T19:42:23+02:00
Create Date 2011-09-25T14:36:54.50+02:00
Creator Tool Ver.1.00
Rating 0
SerialNumber 6607572
LensInfo 180/10 550/10 35/10 56/10
Lens 18.0-55.0 mm f/3.5-5.6
LensID 154
ImageNumber 11565
ApproximateFocusDistance 4294967295/1
Raw File Name 2011-09-25 - 1455.NEF
Version 6.3
ProcessVersion 5.7
White Balance Custom
Temperature 6750
Tint -6
Exposure 0.00
Shadows 2
Brightness +35
Contrast +33
Saturation +5
Sharpness 25
Luminance Smoothing 0
Color Noise Reduction 25
Chromatic Aberration Red 0
Chromatic Aberration Blue 0
Vignette Amount 0
Shadow Tint 0
Red Hue 0
Red Saturation 0
GreenHue 0
Green Saturation 0
Blue Hue 0
Blue Saturation 0
FillLight 3
Vibrance +20
HighlightRecovery 9
Clarity +30
Defringe 0
HueAdjustmentRed 0
HueAdjustmentOrange 0
HueAdjustmentYellow 0
HueAdjustmentGreen 0
HueAdjustmentAqua 0
HueAdjustmentBlue 0
HueAdjustmentPurple 0
HueAdjustmentMagenta 0
SaturationAdjustmentRed 0
SaturationAdjustmentOrange 0
SaturationAdjustmentYellow 0
SaturationAdjustmentGreen 0
SaturationAdjustmentAqua 0
SaturationAdjustmentBlue 0
SaturationAdjustmentPurple 0
SaturationAdjustmentMagenta 0
LuminanceAdjustmentRed 0
LuminanceAdjustmentOrange 0
LuminanceAdjustmentYellow 0
LuminanceAdjustmentGreen 0
LuminanceAdjustmentAqua 0
LuminanceAdjustmentBlue 0
LuminanceAdjustmentPurple 0
LuminanceAdjustmentMagenta 0
SplitToningShadowHue 0
SplitToningShadowSaturation 0
SplitToningHighlightHue 0
SplitToningHighlightSaturation 0
SplitToningBalance 0
ParametricShadows 0
ParametricDarks 0
ParametricLights 0
ParametricHighlights 0
ParametricShadowSplit 25
ParametricMidtoneSplit 50
ParametricHighlightSplit 75
SharpenRadius +1.0
SharpenDetail 25
SharpenEdgeMasking 0
PostCropVignetteAmount 0
GrainAmount 0
ColorNoiseReductionDetail 50
LensProfileEnable 1
LensManualDistortionAmount 0
PerspectiveVertical 0
PerspectiveHorizontal 0
PerspectiveRotate 0.0
PerspectiveScale 100
ConvertToGrayscale False
Tone Curve Name Medium Contrast
Tone Curve 0, 0, 32, 22, 64, 56, 128, 128, 192, 196, 255, 255
Camera Profile Camera Landscape
CameraProfileDigest 7B753FBEA27F64E58C390B0AD768ED5D
LensProfileSetup LensDefaults
LensProfileName Adobe (Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR)
LensProfileFilename NIKON D90 (Nikon AF-S DX NIKKOR 18-55mm f3.5-5.6G VR) - RAW.lcp
LensProfileDigest 13123C2D50032AEE9CDF93A2E491B73E
LensProfileDistortionScale 100
LensProfileChromaticAberrationScale 100
LensProfileVignettingScale 100
GradientBasedCorrections type="Seq"
GradientBasedCorrections[1] type="Struct"
GradientBasedCorrections[1]/crs:What Correction
GradientBasedCorrections[1]/crs:CorrectionAmount 1.000000
GradientBasedCorrections[1]/crs:CorrectionActive true
GradientBasedCorrections[1]/crs:LocalExposure -0.075000
GradientBasedCorrections[1]/crs:LocalSaturation 0.000000
GradientBasedCorrections[1]/crs:LocalContrast 0.000000
GradientBasedCorrections[1]/crs:LocalClarity 0.300000
GradientBasedCorrections[1]/crs:LocalSharpness 0.000000
GradientBasedCorrections[1]/crs:LocalBrightness 0.000000
GradientBasedCorrections[1]/crs:LocalToningHue 0.000000
GradientBasedCorrections[1]/crs:LocalToningSaturation 0.000000
GradientBasedCorrections[1]/crs:CorrectionMasks type="Seq"
GradientBasedCorrections[1]/crs:CorrectionMasks[1] type="Struct"
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:What Mask/Gradient
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:MaskValue 1.000000
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:ZeroX 0.355544
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:ZeroY 0.515183
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:FullX 0.331232
GradientBasedCorrections[1]/crs:CorrectionMasks[1]/crs:FullY 0.646750
Has Settings True
Has Crop False
AlreadyApplied True
```
or perhaps even in more detail:
```
> exiv2 -Pvlh 66d427ae-aaa2-11e6-8816-f208bae74522.jpg
[…]
66d427ae-aaa2-11e6-8816-f208bae74522.jpg GPS Latitude 48/1 431710/10000 0/0
0000 30 00 00 00 01 00 00 00 5e 96 06 00 10 27 00 00 0.......^....'..
0010 00 00 00 00 00 00 00 00 ........
[…]
66d427ae-aaa2-11e6-8816-f208bae74522.jpg GPS Longitude 21/1 138992/10000 0/0
0000 15 00 00 00 01 00 00 00 f0 1e 02 00 10 27 00 00 .............'..
0010 00 00 00 00 00 00 00 00 ........
```
You can clearly see that the seconds component of `GPSLatitude` and `GPSLongitude` fields is `0/0` which is invalid according to the specification.

I hope this is going to help you weed out the faulty tool from your process. :wink:

**Comment by nickplesha** [comment]
@PavolG2 Hope you've been able to track down the source of the problem. I'll close this issue now.
