### ISSUE TITLE
Data duplicated to wrong location

### ISSUE THREAD

**Issue by freenerd** [mapillary/mapillary_issues#2370]
### Steps to reproduce behavior

1. Visit https://www.mapillary.com/app/?lat=39.22773444082807&lng=-84.21834504190475&z=13.430062331468513
2. Check the pictures from the diagonal line

### Expected behavior

1. No data shown for that geographic area

### Actual behavior

1. Pictures from LA instead. They are correctly geolocated there, but somehow seem to appear double here

### Additional information

![2016-11-16 at 11 42](https://cloud.githubusercontent.com/assets/25713/20344151/dba34d6c-abf1-11e6-95fe-591905e2dca5.png)

**Comment by gyllen** [comment]
@ptpt YOu have any idea why this line has not been removed from the tiles

@freenerd I think somebody created a sequence that has an image in LA and somewhere else

**Comment by ptpt** [comment]
@freenerd thanks for reporting. It was caused by some long sequences and we didn't clean spanning tiles up after cutting them. Now the tiles should be are cleaned up.
