### ISSUE TITLE
"next image" hover icon on map just points forward instead of actual direction

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2371]
### Basic information
* Platform: `Web`
* System/Browser: `chrome`

### Steps to reproduce behavior

 1. looking at https://www.mapillary.com/app/index/gyllen?lat=48.2466449&lng=5.3176617&z=17&pKey=PD9Y7bBFf2lGuNy3XVuBcA&focus=photo
 2. hover over the "next image" button at the top of the screen or any other image in that sequence
 3. look at the dark blue hover icon on the map

### Expected behavior
The "next image" (dark blue) hover icon direction points in the actual direction of the image

### Actual behavior
The "next image" (dark blue) hover icon direction looks forward along the sequnce

### Additional information

![image](https://cloud.githubusercontent.com/assets/1165786/20424367/ca74d698-ad75-11e6-9b6f-a241514e2245.png)

**Comment by gyllen** [comment]
@mprins Thanks for reporting, we are investigating, I think this has something todo with the tiler.

**Comment by ptpt** [comment]
It should be fixed now.

<img width="450" alt="2017-04-04 7 06 09" src="https://cloud.githubusercontent.com/assets/87357/24669203/d4d0b8ae-1969-11e7-94fc-d71b727a437e.png">

**Comment by mprins** [comment]
not sure why the yellow "viewport angle" now points the same direction as the dark-blue; while this image sequence was taken with a -30degree offset along the direction of movement... imo the should both be pointing to -30deg off the sequence line and not 0deg. (this show in edit mode btw)

**Comment by ptpt** [comment]
Thanks for reporting again. This might be an inconsistency issue with our DB systems. We have tracked this issue. Hopefully we will fix it next a few weeks.

**Comment by mprins** [comment]
fixed
