### ISSUE TITLE
API: Add sort parameter for /search/im

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2372]
Hello,
It would be useful to be able to sort image search results, in particular to sort by capture date, in order to retrieve for example only the 10 most recent pictures. As a reference, Flickr has a `sort` parameter which can be used with these values:

> sort (Facultatif)
>    The order in which to sort returned photos. Deafults to date-posted-desc (unless you are doing a radial geo query, in which case the default sorting is by ascending distance from the point specified). The possible values are: date-posted-asc, date-posted-desc, date-taken-asc, date-taken-desc, interestingness-desc, interestingness-asc, and relevance.

Is it something which will be implemented in a near future ?

**Comment by ptpt** [comment]
I think it makes sense to sort by capture time by default. We should do it. WDYT @gyllen.

Thanks for bringing up the Filckr example. We will consider it when we have multiple fields to sort.

**Comment by gyllen** [comment]
@ptpt Yes I think this makes sense for V3, we should have a way to sort

**Comment by PanierAvide** [comment]
And can you implement in V2 a sort making most recent picture returned first by default ? This would be very convenient to avoid multiple calls when the necessary information is just the most recent picture date.

**Comment by gyllen** [comment]
@PanierAvide We will fix for V3 (which will replace V2)

**Comment by PanierAvide** [comment]
Ok, do you have an idea of the release date of the v3 ?

**Comment by gyllen** [comment]
@PanierAvide 2-3 weeks

**Comment by ptpt** [comment]
Sorry for the late response. The API v3 is available now and the corresponding image search API is at https://www.mapillary.com/developer/api-documentation/#search-images

Closing.
