### ISSUE TITLE
hello@mapillary.com does not work

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2373]
I have tried to send an e-mail to hello@mapillary.com from my gmail account, my phone and my computer. None got through. The error message in the latter case was:

This is the mail system at host cicero1.cybercity.dk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<hello@mapilary.com>: host
    d246a9ea698a0c48b9465c54539667.pamx1.hotmail.com[65.54.188.78] said: 550
    Requested action not taken: mailbox unavailable (in reply to RCPT TO
    command)

Reporting-MTA: dns; cicero1.cybercity.dk
X-Postfix-Queue-ID: A3D711089EC
X-Postfix-Sender: rfc822; "REMOVED"@zip.dk
Arrival-Date: Sun, 20 Nov 2016 08:06:11 +0100 (CET)

Final-Recipient: rfc822; hello@mapilary.com
Original-Recipient: rfc822;hello@mapilary.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; d246a9ea698a0c48b9465c54539667.pamx1.hotmail.com
Diagnostic-Code: smtp; 550 Requested action not taken: mailbox unavailable

**Comment by kardotim** [comment]
@simonmikkelsen you spelled mapilary instead of mapillary 😸

**Comment by simonmikkelsen** [comment]
DOH! Thank you @kardotim .
