### ISSUE TITLE
Help for authenticating against Mapillary oauth2

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2374]
(posted here as suggested in https://forum.mapillary.com/t/help-for-authenticating-against-mapillary-oauth2/748)
I am developing an app where I need to have users to authenticate against Mapillary using oauth2. I hope you can help me figure out what I am doing wrong.
My problem is, that when I have redirected the user to Mapillary and the user has accepted, I always gets redirected to ?error=invalid_request&error_description=Wrong%20RedirectUri%20provided
I have tried redirect uris with localhost, 127.0.0.1 and on a real online domain, with the same result. All of them has been exact copies of the call back URI I provided when I generated the app keys.

The way I make the URL in Python is:

client_id = 'Y0NtM3R4Zm52cTBOSUlrTFAwWFFFQTo5ODcxYTgzMTgzNzVhMTNi'
url = 'http://www.mapillary.com/connect?'+urllib.urlencode({'client_id':client_id, 'response_type':'token', 'scope':'user:read', 'state':'return', 'redirect_uri':'http://zip.dk/mapillary/'})
which I use to send a Location header with a 302 temporary moved. This part seems to work fine.

An example of a URI I got from Chromes developer console is:
http://www.mapillary.com/connect?scope=user%3Aread&state=return&redirect_uri=http%3A%2F%2Flocalhost%3A7788%2Ftest.py&response_type=token&client_id=Y0NtM3R4Zm52cTBOSUlrTFAwWFFFQTo5ODcxYTgzMTgzNzVhMTNi

**Comment by katrinhumal** [comment]
@tryl Long time has passed but did you get the help you needed with this?

**Comment by simonmikkelsen** [comment]
@katrinhumal No. I have emailed with several developers, latest Johan. It seems that this requires a lot of debugging time on their part and everyone are very busy. Currently I have 2 issues and only one is blocking me:

I can get past the first step of connecting using http://www.mapillary.com/connect.

I then try to finish the authorizaton, using the Python code:

query_params = parse_qs(environ['QUERY_STRING'])
access_token = query_params['access_token'][0]
payload = {'client_id': client_id, 'client_secret': client_secret, 'redirect_uri':'http://localhost:7788/api', 'grant_type':'authorization_code', 'code':access_token}
data = urllib.urlencode(payload)
h = httplib.HTTPSConnection('a.mapillary.com')
headers = {"Content-type": "application/x-www-form-urlencoded", "Accept": "text/plain"}
h.request('POST', '/v2/oauth/token', data, headers)

that posts the following to https://a.mapillary.com/v2/oauth/token :
code=ey...cut out...Zh&grant_type=authorization_code
This gives the result: {"error":"invalid_request","error_description":"No authorization header passed"}

This is okay if I have made a mistake, but the description says "authorization header" and this call is the one which is supposed to give me an authorization header. There is no example in the api doc and I think I have done it as described.

I also tried this step with the OAuth test client at http://term.ie/oauth/example/client.php and it gave the exact same result.

**The non blocking issues are with connecting:**

I can only use a call back uri with exactly 1 folder in it, e.g. http://localhost:7788/browser
But if I use http://localhost:7788/browser/api
or a longer url I get "Wrong%20RedirectUri%20provided" even though I have made the change in both my code and on Mapillary. This may be an undocumented limitation of your OAuth implementation.

The second non blocking issue is that I can only get authentication to work if I set scope to user:email. If I set it to user:read or
user:email user:read
I get redirected to http://localhost:7788/browser/?error=invalid_scope&error_description=Invalid%20scope%20for%20the%20client
Actually I only needs user:read.

**Comment by katrinhumal** [comment]
Ok, let's assign Johan to this. It's true time is a tight resource but at least it is on the list then!

**Comment by gyllen** [comment]
@nickplesha I know you looked into this sometime ago. Do you have any input at the moment? If not I have to start investigating this matter.

**Comment by nickplesha** [comment]
@simonmikkelsen Sorry to hear you're still having trouble authenticating. Thanks to your bug report we've been able to track down and fix the developer app form so that saving app properties should work correctly now at https://www.mapillary.com/app/settings/developers

To fix your non-blocking issues, go to that URL and check your app details and update the scope and callback URL (you might need to create a new app).

As for `https://a.mapillary.com/v2/oauth/token`, I tested it with my own app and it looks like it indeed requires an `authorization header` which is a bug that @gyllen or @ptpt could look into.

**Comment by gyllen** [comment]
@ptpt Would you be able to look into this issue?

**Comment by simonmikkelsen** [comment]
I can confirm that my non blocking issues are solved (I just created a new app):

- I can now request only user:read
- I can now use a call back uri of arbitrary length/

I can also confirm, as you write, that I still get "No authorization header passed" where it is not expected.

Thank you for your time. When the last issue is fixed, I have a technology preview of an app that I can send into production. The code will be available on GitHub under the MIT License.

**Comment by gyllen** [comment]
@simonmikkelsen So sorry for the delay of this issue, we are now activly looking into solving it

**Comment by gyllen** [comment]
@simonmikkelsen Its seems like you removed that `client_id`, can you create a new app and post the public properties here so I can do proper debug

**Comment by simonmikkelsen** [comment]
Hi @gyllen 
Thanks. I have created a gist with my whole test app at https://gist.github.com/simonmikkelsen/2daa44690b1d92640b8df48aa3cb2d8d
The client id is in line 19 and test redirect uri I have registered at Mapillary is in line 22.
The app runs as a wsgi app. Secret keys are redacted.

I have run it again, and still gets the response
`{"error":"invalid_request","error_description":"No authorization header passed"}`
when I expect to get an authorization token I can use for an authorization header.

**Comment by gyllen** [comment]
Can you try creating a new Application and use this exact structure

https://www.mapillary.com/connect?client_id=NlRpbEg1aVRrbGNmcGhCZGhHSFpGdzo0YTBhYTIwZjk3Mzg5NGJh&scope=user:read+public:upload+public:write+private:read+private:write+private:upload&response_type=token&redirect_uri=http://localhost:3087

You can try above link to and see if that works and then just replace the client_id with your new apps client_id.

**Comment by simonmikkelsen** [comment]
Hi
In my first attempt I used your exact URL with just client_id and redirect_uri replaced. I edited the scope to match the url, which is enable all but user:email and user:write. When I click the Authorize button in Mapillary, I get the message:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

I also created a brand new application in Mapillary and got the exact same result.

I posted a gist with my app for the last attempt in https://gist.github.com/simonmikkelsen/015b8cf7ddfa20e1a3970b9421809719

**Comment by gyllen** [comment]
Thanks for diving deeper into this. But the exact none modified URL works for you?

**Comment by simonmikkelsen** [comment]
I got `{"error":"invalid_request","error_description":"No authorization header passed"}` again.

I have attached the exact file I used as https://gist.github.com/simonmikkelsen/5feb1aac7d622e60a3f7c67b90a2c80b

I used the exact url as you provided, changed the port of my server and put the script in the location corresponding to the redirect_uri. In the step that fails I have to give a client_secret and for good reasons I did not have yours. But I would expect another error message for that problem. Its like the step expects a header to be set which is not set.
So just to clarify: I get just fine past first step and gets an access_token. The failure is in the step where I call a.mapillary.com/v2/oauth/token

Thanks for the late work!

**Comment by gyllen** [comment]
The access token you get in the redirect URL is the access_token you can use for authentication.

Try `https://a.mapillary.com/v3/me?client_id=XXX&token={ACCESS_TOKEN}`

**Comment by gyllen** [comment]
Sorry for not looking into this issue more though. I see that you are trying todo this server side now though. Is there anyway you can make the flow happen on the front-end side?

**Comment by simonmikkelsen** [comment]
What I am trying to do is, to get the users unique Mapillary identifier (and username, which can change) in a way so I can be sure that the user is a Mapillary user. Right now I am basically just using Mapillary as an authentication provider, but with the bonus that everything users can do in my app is related to Mapillary. For that reason it is logical to me that they are tightly coupled to Mapillary.

**Comment by gyllen** [comment]
@simonmikkelsen you should be able todo that by doing

```
1. Steer user to link https://www.mapillary.com/connect?client_id=NlRpbEg1aVRrbGNmcGhCZGhHSFpGdzo0YTBhYTIwZjk3Mzg5NGJh&scope=user:read+public:upload+public:write+private:read+private:write+private:upload&response_type=token&redirect_uri=http://localhost:3087
2. Get the `auth_token` in the response
3. Call https://a.mapillary.com/v3/me?client_id={SAME AS IN LINK ABOVE}&token={RETRIVED ACCESS TOKEN}
```

By the way let me know if you want to get on a Skype call about this. Im happy to get it working for you. Im also availble in the `Mapillary`slack channel on "The Spatial Community"

**Comment by simonmikkelsen** [comment]
Hi

Now I have something that works! Thank you @gyllen !

I did as you suggested, just get https://a.mapillary.com/v3/me

I still had issues: I could not get it to work with a long redirect_uri like http://localhost:7788/browser/api/index4.py  but http://localhost:7788/api did it.
Now I will integrate it into my solution (https://github.com/simonmikkelsen/mapillary-browser) and post the url when ready :-)

If others should be interested, the script can be seen at https://gist.github.com/simonmikkelsen/ed6a4c9c7edd6b03ee47d1c5bfd10b4a
It is located at the url corresponding to the redirect_uri and index.py is made the default file of the api folder.

**Comment by ptpt** [comment]
Awesome. Thanks @gyllen for taking this issue!

**Comment by gyllen** [comment]
@simonmikkelsen Awesome, thanks for your patience, I think what we lack for oauth right now is proper documentation.
