### ISSUE TITLE
website not loading user details or nothing at all

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2377]
There seem to be massive backend problems with the website today.

- login this morning took several minutes, while the screen was pale with spinning dots
- yesterday's uploads were missing, and even more uploaded sequences not processed
- now, while the map loads, the right panel with the user-specific data remains empty with spinning dots. 
- trying to reload the page, now the browser window is completely empty with spinning dots, saying "Mapillary is loading"

Could you please focus on performance and reliability, and less on eye candy and gimmicks?

**Comment by gyllen** [comment]
@polarbearing Yes we have experienced heighten error rates we are currently investigating
