### ISSUE TITLE
Photo sequencing disrupted after web upload

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2378]
### Basic information
* Platform: `Web`
* Version: `latest` 
* System/Browser: `Windows 10 / Chrome Version 54.0.2840.99 m (64-bit)`

### Steps to reproduce behavior

 1. Take photos with Garmin Virb XE facing 90 degrees to the right.
 2. Remove duplicates, split sequences and interpolate using [Mapillary Tools](https://github.com/mapillary/mapillary_tools)
 3. Upload on the [Mapillary Uploader (web)](https://www.mapillary.com/app/uploader)
 4. **Important** Move the location of some images by dragging them to a new location with the mouse.
 5. Begin the upload
 6. Wait for the uploads to appear on the map (may take hours)
 7. Look at photos on the map.

### Expected behavior
I would expect the photos would stay in sequence upon upload.

### Actual behavior
The photos that were moved in step 4 appear in the proper location **spatially**, but not **temporally**:

I moved the five photos in Figure 2 during the uploader phase (step 4 above) because they were slightly too close, due to the vehicle speed changing. I moved the three photos in figure 3 during the uploader phase (step 4 above) because they were not at the proper location along the corner, due to GPS over correction. After upload, these photos appeared in the wrong temporal order.

I hypothesize that the modifications I made during initial upload (step 4 above) caused the temporal shift. This took me a bit to figure out, and the pattern did not occur to me until I remembered that I had edited these photos back during upload (step 4 above), thus my _supposition_ of the issue.

### Additional information

![image](https://cloud.githubusercontent.com/assets/1827881/20643801/c1236b2e-b3ef-11e6-831a-cc2b12cbf6ad.png)
Figure 1

![image](https://cloud.githubusercontent.com/assets/1827881/20643804/cce4d6aa-b3ef-11e6-94bd-73d62edd6e9b.png)
Figure 2

![image](https://cloud.githubusercontent.com/assets/1827881/20643805/d777ad72-b3ef-11e6-923c-d3ab5bb25b12.png)
Figure 3

**Comment by talllguy** [comment]
* Sequence key referenced in this issue is `HroELQl0xLCDsamgxpQGXA`.
* After posting this issue, I decided not to edit the sequence so that the team could review.

**Comment by gyllen** [comment]
@nickplesha We have a solution for this right?

**Comment by nickplesha** [comment]
@talllguy The order of images after upload should now be consistent. The bug was that the time zone difference from UTC was applied to moved images so they were moved `temporally` as well.
Please re-open this issue if you encounter any problems during upload in the web uploader.
