### ISSUE TITLE
Possibility to compare photos by selection

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2380]
Possibility to compare photos manually (by selection) could be very useful feature, because time travel doesn't work every time because of various reasons (inaccurate photo location due to GPS errors or inaccurate GPS syncronization when we use manual upload +/- 30 meters.)

**Comment by angelday** [comment]
@gyllen do our services cover for this use case? (compare between any two arbitrary photos)

**Comment by gyllen** [comment]
@angelday We can do it, its a matter of UX.

**Comment by nickplesha** [comment]
@eugensim To compare any two images use this URL: `https://www.mapillary.com/app/time-travel?pKey=${First image key}&cKey=${Second image key}&focus=photo`. Sorry that there's no UI to create this comparison but it should look exactly like the usual time travel experience.
