### ISSUE TITLE
Resizing existing blur rectangles makes no effect

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2381]
### Basic information
* Platform: Web
* System/Browser: Firefox ESR 45.5.0

When I make blur edits, blur rectangles I add or remove are submitted properly; but resizing existing blur rectangles doesn't work.

Initially I simply saw that the resized rectangle was back to the original size after the edit was approved (yet the two new ones I added were in the correct place). But looking at the network activity, it seems the browser is sending the wrong coordinates, rather than the server not saving them.

### Steps to reproduce behavior

 1. Go to [the blur editor for a photo](https://www.mapillary.com/app/blur?pKey=1e23S3mOyT-OmKKvv6i8pg&focus=photo).
 2. Check Firefox's network debugging tab; this gets retrieved from the API:
```json
"blur": {
 "$type": "atom",
 "value": [
  {
   "type": "license",
   "rect": [0.4755859375, 0.76953125, 0.52685546875, 0.78971354166666663]
  },
  {
   "type": "user",
   "rect": [0.36768994852619069, 0.73541394266303406, 0.37908931982028332, 0.74080983784155341]
  },
  {
   "type": "user",
   "rect": [0.62274684418699788, 0.70748811057297212, 0.62955889061704695, 0.7115745813501585]
  }
 ]
}
```
 3. Resize the blur rectangles in an obvious way (make them 2x bigger or something).
 4. Submit; this is what gets sent to the API
```json
[
 "1e23S3mOyT-OmKKvv6i8pg",
 [
  {
   "type": "license",
   "rect": [0.4755859375, 0.76953125, 0.52685546875, 0.78971354166666663]
  },
  {
   "type": "user",
   "rect": [0.36768994852619069, 0.73541394266303406, 0.37908931982028332, 0.74080983784155341]
  },
  {
   "type": "user",
   "rect": [0.62274684418699788, 0.70748811057297212, 0.62955889061704695, 0.7115745813501585]
  }
 ]
]
```
Those are the exact same numbers, so it's ignoring the resize.
 5. Obviously, if you wait for approval and go to the blur editor again, the rectangles look the same as before.

### Additional information

Didn't test on other browsers yet.

Probably a regression, I'm 90% sure this worked fine before.

**Comment by richlv** [comment]
maybe it's worth having unittests for blur saving (both the fact and the result matching the expectations :) )

**Comment by gyllen** [comment]
@richlv We do, apparently not good enough though ;)

**Comment by nickplesha** [comment]
@nicolas17 Thanks for reporting this and helping us find this issue! We fixed the blur code so the correct dimensions will be used when saving changed blurs.
