### ISSUE TITLE
Photos missing from two sequences

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2382]
According to the API, sequence `96yqM1mOzZeF8E4mAPqy1Q` should have a photo with the key of `tPPf1bodZwRg53NA2c-pIQ` in it but when I try to view this photo, I get an error. I know there has been talk of "ghost images" during processing before but I'm pretty sure this sequence had 54 images when I started uploading it from my phone so there should be a real image in there somewhere.

Similar story with sequence `Z4pRV3ufPy4D5tKzXu9eCg` and photo `ghm48az3MPd8_X3_qwDy6Q`

**Comment by ToeBee** [comment]
Oh and the web viewer just stops working when you try to advance the sequences to the missing photos.

**Comment by ToeBee** [comment]
And I found a 3rd one as well. Sequence `hpSbC3ik3KdwQ6eyMG0vjA` is missing image `c1MSLdZm0_kTFz-4mF6gcA`

**Comment by ToeBee** [comment]
Looking at the original EXIF data on these files, images are definitely being dropped.

While capturing sequence `96yqM1mOzZeF8E4mAPqy1Q` my phone was set to a 1 second capture interval. The image before the missing one ([EogGGvLB6O3kyuYmEQnq0g](https://www.mapillary.com/app/?pKey=EogGGvLB6O3kyuYmEQnq0g&focus=photo)) shows a capture time of `2016_11_25_21_40_12_904` and the image after the missing one ([CqjPKuB5NMeqXnRhUik1Ug](https://www.mapillary.com/app/?pKey=CqjPKuB5NMeqXnRhUik1Ug&focus=photo)) shows a capture time of `2016_11_25_21_40_14_903`. There is a missing second there.

**Comment by peterneubauer** [comment]
These images are now visible, sorry for the hickup - we had the database not quite synced, they were restored in our Xmas-cleaning :)
