### ISSUE TITLE
iOS - image orientation turned 90° anticlockwise

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2383]
### Basic information
* Platform: iPhone 6 iOS 10.0.1
* Version: Mapillary 4.5.6

In this 3 sequences
[https://www.mapillary.com/app/?pKey=G83cyMgtPglFwb28vdWaYg](https://www.mapillary.com/app/?pKey=G83cyMgtPglFwb28vdWaYg)
[https://www.mapillary.com/app/?pKey=R8Cv9_tC5Xdy8_8kN-d3oQ](https://www.mapillary.com/app/?pKey=R8Cv9_tC5Xdy8_8kN-d3oQ)
[https://www.mapillary.com/app/?pKey=OwtnocrcKq7ekSlNCcNXow](https://www.mapillary.com/app/?pKey=OwtnocrcKq7ekSlNCcNXow)
the stored image directions are consistently turned ~90° anticlockwise from the true direction.

The sequences were directly uploaded via wifi. No scripts involved, no data writen to EXIF. Also no sequence edit afterwards.

**Comment by millenbop** [comment]
Thanks for reporting! Will look into asap.

**Comment by millenbop** [comment]
I have looked into it now and cannot see any errors on my end. Tried on both iPhone 5s with iOS 9.3.3 and iPhone 6 with iOS 10.2.

I checked some of your other sequences and they seem to be fine. Did you download an old version of the app or did you edit the direction manually? Or did it work itself out?

**Comment by ramapongithub** [comment]
No, no manual edits in any form.
To check if it happens again i tried to repeat it. Over the week I have  only time after work when it is dark outside. but I did not want to upload dark, blurry images. So I tried the EXIF method, but ran in [Issue 2386](https://github.com/mapillary/mapillary_issues/issues/2386).

**Comment by ramapongithub** [comment]
Tried again, this time with Mapillary  4.5.7. 
But the behavior is the same, turned 90° anticlockwise.
[https://www.mapillary.com/app/?pKey=dBz-tYy-9CfkHzUsTvc_kQ](https://www.mapillary.com/app/?pKey=dBz-tYy-9CfkHzUsTvc_kQ)
[https://www.mapillary.com/app/?pKey=dBz-tYy-9CfkHzUsTvc_kQ](https://www.mapillary.com/app/?pKey=dBz-tYy-9CfkHzUsTvc_kQ)
Next I will update iOS and try again.

**Comment by millenbop** [comment]
I uploaded a potential fix yesterday, I hope it's gonna be out in a day or two.

**Comment by ramapongithub** [comment]
Mapillary 4.5.9 did the trick.
I actually tried two sequences and the image orientation was o.k.
[https://www.mapillary.com/app/user/ramap?lat=49.528795&lng=8.65810399999998&z=17&pKey=mmL3UCe68bm4Hu5dohUshA](https://www.mapillary.com/app/user/ramap?lat=49.528795&lng=8.65810399999998&z=17&pKey=mmL3UCe68bm4Hu5dohUshA)
[https://www.mapillary.com/app/user/ramap?lat=49.532890511776884&lng=8.6570908523654&z=17&pKey=VRYeO-6pU4U4fHaPlk8b8g](https://www.mapillary.com/app/user/ramap?lat=49.532890511776884&lng=8.6570908523654&z=17&pKey=VRYeO-6pU4U4fHaPlk8b8g)

Now I can edit the old sequences.
Thanks for the update!

**Comment by millenbop** [comment]
Yay finally! Thanks for reporting, closing.
