### ISSUE TITLE
[Website] Leaderboard list not displaying information

### ISSUE THREAD

**Issue by ccossio** [mapillary/mapillary_issues#2384]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `Mac/Firefox `

### Steps to reproduce behavior

 1. Click on the Menu button
 2. Click on the leaderboard section.
 3. Type the name of the city or region.
 4. The list does no update

### Expected behavior

It should display the list of the Mapillary users with most photos.

### Actual behavior

The list is not updated with any information and it just loops with out any results being displayed.

### Additional information

The Leaderboard is broken, you cannot display any results from cities, regions or countries.

Just the overall leaders are being displayed

Error Screen
 https://drive.google.com/file/d/0B0QGTEDDVf2VcTdzMWt1bzlCMU0/view?usp=sharing

**Comment by gyllen** [comment]
I think this has todo with our new WOFs

**Comment by peterneubauer** [comment]
Fixed now, closing.
