### ISSUE TITLE
More informative trace display

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2387]
This issue is in regard to both the vector and the raster (#1366) tileset.

Currently, the traces draw lines connecting subsequent photo locations (the dots). I want to put up a request to remove those lines, at least in the higher zoom levels.

The information that photos were take in a certain sequence is irrelevant. Mapillary does a very good job at connecting photos even when they were taken in different sequences. In best case, these lines add visual clutter to the map. In worst case, they are misleading. When there is a big distance between two photos and a line is draw between them, it looks as though there is "some" information there, while there is nothing. It's the individual photos spots that are relevant, not the space between them.

With the visual clutter of the lines removed, I have a second request. Instead of using dots, would it be possible to show arrowheads, triangles, something like that, to show the direction the photo was taken in? This of course also only in the highest zoom levels, where individual photo locations are distinguishable.

**Comment by ptpt** [comment]
Thanks again for the input.

Both requests are easy to implement from my side. For the first request we need some discussion with @jesolem. For the second request, we need discussion with @angelday about the design.

**Comment by pkoby** [comment]
I like this idea. As it is now, I find it's very rare that I click on the next photo too often from the map view. If I want to see the next photo, I use the arrows at the top.

However, I would say that knowing which photos are in a sequence is useful, and shouldn't be lost, but I think if the points would still turn blue when the sequence is selected, there would be no problem.

As a compromise, maybe the lines could be toggled?

**Comment by pbb72** [comment]
Still colouring the currently selected track is a good idea! Also, I think we need to keep the connecting lines in the editor, I see they are vital when sorting through the photos when they are all thrown together in a small location.

**Comment by gyllen** [comment]
@angelday I really like this idea, we could only color the current suquence. Makes sense to me

**Comment by pbb72** [comment]
All positive feedback for a week, then 1,5 years of nothing, and then closed without comment. You guys do project an image of struggling with the whole concept of public issue tracking...

**Comment by angelday** [comment]
@pbb72 There is a reason for everything. We'll be sunsetting the repo and closing these issues or moving them to the forum.

> I want to put up a request to remove those lines, at least in the higher zoom levels. The information that photos were take in a certain sequence is irrelevant. Mapillary does a very good job at connecting photos even when they were taken in different sequences. In best case, these lines add visual clutter to the map. In worst case, they are misleading. When there is a big distance between two photos and a line is draw between them, it looks as though there is "some" information there, while there is nothing. It's the individual photos spots that are relevant, not the space between them.

If you'd like I can have this part opened in the forum, just say so. I cannot promise that we'll implement this, but what I can promise is that we will keep this in mind once we revisit map styling and markers.

> With the visual clutter of the lines removed, I have a second request. Instead of using dots, would it be possible to show arrowheads, triangles, something like that, to show the direction the photo was taken in? This of course also only in the highest zoom levels, where individual photo locations are distinguishable.

This describes https://github.com/mapillary/mapillary_issues/issues/2950

**Comment by pbb72** [comment]
Well, judging by the feedback ("...we need some discussion...", "I like this idea...", "I really like this idea...") I would say that the case should be discussed further...
