### ISSUE TITLE
Download unprocessed original does not work

### ISSUE THREAD

**Issue by Ainali** [mapillary/mapillary_issues#2388]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 7 / Chrome Version 54.0.2840.87 m (64-bit)`

### Steps to reproduce behavior

 1. Go to this image: https://www.mapillary.com/app/?lat=57.630444444444464&lng=18.305283333333335&z=17&focus=photo&pKey=QE6ADEpeQYQfUt1Ph636Rw
 2. Press button ...
 3. Check the link for **Download unprocessed original**

### Expected behavior
The link should be to the image file

### Actual behavior
The link for **Download unprocessed original** is https://www.mapillary.com/

**Comment by gyllen** [comment]
I can not replicate this, can you try again @Ainali

**Comment by Ainali** [comment]
No, I cannot replicate it either anymore. Strange glitch.

**Comment by gyllen** [comment]
Thanks for checking so fast, I think it might have been an API glitch

Please repopen if ti happens again
