### ISSUE TITLE
Direct download link to .apk file not working

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#2389]
At the bottom of mapillary.com there is a link to the .apk file. The link points to http://android-releases.mapillary.io//Mapillary_Android_current.apk which shows an error page. I guess the address should be http://android-releases.mapillary.io/Mapillary_Android_current.apk (only one slash, not two)

**Comment by gyllen** [comment]
@ltog Thanks for reporting

**Comment by peterneubauer** [comment]
Fixed now.
