### ISSUE TITLE
timeline missing

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2390]
### Basic information
* Platform: `iOS` | 
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. starting app
 2. jumps after start direct to featured timeline
 3. choosing own timeline. empty . 

### Expected behavior

should show my activity . 

### Actual behavior

...

### Additional information

...

**Comment by gyllen** [comment]
We are in the middle of upgrading timeline, stay tuned for updates

**Comment by gyllen** [comment]
Fixed
