### ISSUE TITLE
remaining upload time

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2392]
### Basic information
* Platform: `iOS` | 
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. uploading my stuff
 2.
 3.

### Expected behavior

should show speed and remaining time

### Actual behavior

shows speed but in same line trys to show remaining time.
expecting it should do it in second row ,  so that u can see it .-)

### Additional information

...

**Comment by millenbop** [comment]
Hi there!

Thanks for reporting! I'll look into it.

- Anders

**Comment by millenbop** [comment]
Do you still have this bug? Which device are you using? Could you send a screenshot of what it looks like? Thanks!

**Comment by millenbop** [comment]
Are you using German btw? I can see that the translation is pretty long. I'll fix so that the text autoscales, that should solve the problem for all languages. Will be out in the next release.

**Comment by thoschu96** [comment]
Hey Anders


yep.. German language.

Great news .. thx


Cheers

________________________________
Von: Anders Mårtensson <notifications@github.com>
Gesendet: Donnerstag, 6. April 2017 10:15
An: mapillary/mapillary_issues
Cc: Schulz, Thorsten; Author
Betreff: Re: [mapillary/mapillary_issues] remaining upload time (#2392)


Are you using German btw? I can see that the translation is pretty long. I'll fix so that the text autoscales, that should solve the problem for all languages. Will be out in the next release.

-
