### ISSUE TITLE
 App requesting authentication even without logout from my account

### ISSUE THREAD

**Issue by bonix-git** [mapillary/mapillary_issues#2394]
### Basic information
* Platform: `iOS`
* Version: `9.3.5` 
* System: `iPhone 6S Plus`

### Steps to reproduce behavior

 1. Open app mapillary, minimize, open another apps, wait for some time (variable), open mapillary again.
 
 2. Another variation: Open app mapillary, wait for iphone lock the screen. Login on iPhone, try do use the previous open app.

3. Another variation: Sometimes, after minimizing and leaving unused for a longer time, when I select  it from the list of apps already open it again requests authentication.

### Expected behavior

 The App should be open on the last screen used.

### Actual behavior

 The App is requesting my login/password  as if it were a new installation.

 
### Additional information

No previous data is lost. The photos that have not yet uploaded continue to exist.

This problem does not occur on the screen for upload photos.

**Comment by millenbop** [comment]
Thanks for reporting! 

So you're logged in, and after a while it asks you to login again? Has this happened before?

**Comment by bonix-git** [comment]
Hi Andres, This had not happened before. In about a week or two other apps
have also come up with the same behavior. Maybe it's a problem with this
version of iOS. Thank you.



[image: photo]
*Edson Lima Monteiro*
Centro de Tecnologia da Informação de São Paulo
SCTCG-84 / DVT-84
+55 11 3091-6422 <+55+11+3091-6422> | boni@usp.br |
http://cetisp.sti.usp.br/ | Av Prof Luciano Gualberto, travessa 3, n. 71
05508-010

São Paulo - SP - Brasil

**Comment by millenbop** [comment]
You're the first one experiencing this so far. If you have problems with other apps as well it sounds like something else is wrong. Try restarting your phone or upgrading it to 10.x.

**Comment by bonix-git** [comment]
Hi,

Okay. Eventually I'll do this as soon as version 10 stabilizes.

Thanks for the feedback.
