### ISSUE TITLE
Clicking search result closes search window

### ISSUE THREAD

**Issue by kardotim** [mapillary/mapillary_issues#2395]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome on Windows 10`

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/ and search a place (eg Amsterdam)
 2. Hover over the search results, you'll see that they are not being selected
 3. Click on a search result, you'll see that the search box closes and nothing happens.

**Comment by gyllen** [comment]
Thanks for reporting

**Comment by katrinhumal** [comment]
Works now, closing.
