### ISSUE TITLE
Links broken in notification e-mail

### ISSUE THREAD

**Issue by kardotim** [mapillary/mapillary_issues#2396]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome on Windows 10`

### Steps to reproduce behavior

 1. I received a "Your Mapillary photos are now fully processed" e-mail
2: The "View on Mapillary" button just goes to Mapillary.com and not links to the picture that got processed.
 3. In the footer there are three links: Unsubscribe — Manage Your Preferences — Your Profile
 4. The first two footer links are not clickable, the third one goes to https://www.mapillary.com/app/quick-settings?notification_token=FIXME instead of "Your Profile". 
5: It looks like some logo image in the top right hand corner is broken as well.

### Expected behavior
* Working links
* The 'Your Profile' link to go to my profile and not notification settings.
* Notification settings to go to https://www.mapillary.com/app/settings/notifications instead of https://www.mapillary.com/app/quick-settings?notification_token=FIXME

**Comment by gyllen** [comment]
@kardotim These are internal test email, closing this. Please reopen in `elva`, when if problem persists after we announce done state for notifications
