### ISSUE TITLE
Missing Traces On Mapillary Overview

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary_issues#2397]
I have identified 2 routes which I have captured several months ago which are not appearing on the Mapillary overview screen, but which are appearing on OpenStreetMap iD Editor

### Basic information
* Platform: `iOS` 
* Version: `10.11` 

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/map/im/ipbYwGSeSiwP6z1Xj0LSig
 or https://www.mapillary.com/map/im/BD73PRaltbRDPy3fK3HfCg
 2. Look at the Mapillary Map Overview- you will see that there are images here but are not marked with a green line to indicate an image chain.

### Expected behavior
It is expected where there are image chains there will be a green line marked over the Mapillary Overview indicating there is an image chain here.

### Actual behavior
No image chain is visible at https://www.mapillary.com/map/im/ipbYwGSeSiwP6z1Xj0LSig or https://www.mapillary.com/map/im/BD73PRaltbRDPy3fK3HfCg

### Additional information
See Screenshots

![route_1](https://cloud.githubusercontent.com/assets/9841560/20889255/94bef7b4-bb02-11e6-83b4-e32e2c0d693e.JPG)
![route_2](https://cloud.githubusercontent.com/assets/9841560/20889266/9ca6693a-bb02-11e6-8d50-2cf7d88a8107.JPG)

**Comment by ptpt** [comment]
Thanks for reporting this. It's an inconsistency issue with our databases. We've tracked it, and will be back when it gets fixed.

**Comment by ptpt** [comment]
Hi @PaulColinSimpson again this is a data consistency issue. Only part of the sequence is showing https://www.mapillary.com/app/?focus=map&pKey=ipbYwGSeSiwP6z1Xj0LSig&lat=51.53483962274447&lng=-0.025703120425646375&z=12.382548049277785

Tracked internally. Closing.
