### ISSUE TITLE
API search returns images outside min/max lat/lon

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2398]
### Basic information
* Platform: `Web`
* System/Browser: `Linux/Firefox 50`

### Steps to reproduce behavior

 1. Call API to search images in a given bounding box, using `min_lat`, `max_lat`, `min_lon`, `max_lon` parameters. For example `https://a.mapillary.com/v2/search/im?client_id=<CLIENT ID>&max_lat=48.125&max_lon=-1.695&min_lat=48.12&min_lon=-1.7&limit=100&start_time=1465422539357&page=0`

### Expected behavior

The API returns images strictly contained in the given bounding box.

### Actual behavior

Some images outside the box are also returned. For the previous example, we have:
```
{"ca":116.564609050751,"captured_at":1475402428971,"key":"bbNyCC8xui2O2bCJaIuXVQ","lon":-1.70016445,"lat":48.12499619,"location":null,"user":"panieravide"}
```
The longitude is less than -1.7.

```
{"ca":287.894073426723,"captured_at":1478867305245,"key":"QsXmoh_F6bNkn17dxk9ICg","lon":-1.69975573,"lat":48.1250071,"location":null,"user":"panieravide"}
```
The latitude is more than 48.125.

**Comment by gyllen** [comment]
New API is coming out soon, will fix this error keep you eyes open for a notice, closing
