### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by mishari** [mapillary/mapillary_issues#240]
I would like the application to be able to do Geofencing, that is I should be able to define coordinates and a radius. I understand that I can manually delete photos but this will just be a nice and easy way for me to be able to preserve my privacy by not taking photos of areas where I would like to keep private. One application that does this well is MozillaStumbler.

**Comment by jesolem** [comment]
The automatic capture only in designated areas is being released soon and is currently in beta testing. 

Moving the explicit geofencing over to our internal task list. 

Please send an email to support@mapillary.com with a reference to this issue if you want to add more information.
