### ISSUE TITLE
MapillaryUploadService keeps running in background

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#2400]
### Basic information
* Platform: `Android 6.0`
* Version: `3.10` 
* System/Browser: `Motorola Moto G 2`

### Steps to reproduce behavior

 1. Doesn't apply, I guess

### Expected behavior

The service should not respawn nor keep running in background

### Actual behavior

I am seeing a `MapillaryUploadService` (`app.mapillary:uploadservice`) running in my phone, even tough I didn't open Mapillary.
If I stop it (the `PARAR` button) it seems to respawn again after some time (it's already the third time that I am stopping it).

I didn't see this happening with maybe 2 or 3 versions later than the current one (`3.10`)

### Additional information

![](https://cloud.githubusercontent.com/assets/982338/20983228/d1207088-bca2-11e6-86b1-5ef47c9eedfe.png)

**Comment by rsahlin** [comment]
Hi @naoliv and thanks for your report.

Sorry for the late reply, a lot of things going on right now :-)
Re-start of the UploadService can happen for 2 reasons:
- Time based reschedule of failed upload, eg retry after 5 minutes
- Network connected, eg wifi/cell becomes available

Could you please check if you have an upload that has been suspended?
Do this by opening the app and going to the Upload tab - will it display an alert asking you to resume upload?

Best regards
/Richard

**Comment by naoliv** [comment]
There isn't any message asking to resume or upload.
I have a lot of sequences in the phone, but they were already uploaded with the python script.

Some sequences I keep in the phone to review and include data in OSM after, but this never made Mapillary to keep running in background before.

**Comment by rsahlin** [comment]
Ok, thanks - after checking behavior on my phone I can see the same behavior.

Filed an issue:
https://github.com/mapillary/mapillary_issues/issues/2411

A solution is coming and will be out with the 3.12 release, maybe out next week or early next year.

Best regards
/Richard

**Comment by peterneubauer** [comment]
This should now be out.
