### ISSUE TITLE
Searching for "Florida" in the leader board doesn't show the state

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2401]
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 53`

### Steps to reproduce behavior  
 1. Go to the leader boards at https://www.mapillary.com/app/stats
 2. Type `Florida` in the search box

### Expected behavior
"Florida" should be listed as a Region

### Actual behavior
It finds localities and neighborhoods with `Florida` in the name but not the state:
![image](https://cloud.githubusercontent.com/assets/348948/20987253/84b12438-bc91-11e6-851d-33beb033d429.png)

### Additional information
If you just type `Florid` without the last a it does find the state.

**Comment by ToeBee** [comment]
The same thing happens with California.

All other states in the U.S. seem to work. However Puerto Rico shows up as just `PR` in the results list.

**Comment by peterneubauer** [comment]
We are using Mapzens search here, wonder if there is a bug in the shape or otherwise some error @gyllen @knikel ?

**Comment by knikel** [comment]
Perhaps there is some inconsistency between Mapzen's search API and WOF @peterneubauer.

Adding this for future reference: https://mapzen.com/products/search/?query=Florida%2C%20USA&endpoint=place&gid=geonames%3Aregion%3A4155751&selectedLat=28.75054&selectedLng=-82.50010&lng=-82.62062&lat=28.75050&zoom=12

**Comment by knikel** [comment]
I've looked into this issue today and unfortunately, this can't be fixed on our side. We're relying on [`whosonfirst-data`](https://github.com/whosonfirst-data/whosonfirst-data) and if the shape doesn't exist there, we can't display stats for it and it won't be available in the results either. The `Florida, USA` result comes from [`geonames`](http://www.geonames.org) and its shape is not available through `whosonfirst-data`. I understand this can be confusing that one is able to find places throughthe  main search box, but not see stats for them.

**Comment by iandees** [comment]
Thanks to @ToeBee for pointing this out on Slack. I let the Mapzen team know about this and they let me know they are in fact working on fixing this in the Mapzen Search API (by improving the data in Who's On First).

If stuff like this comes up, please don't hesitate to let Mapzen know!

**Comment by ToeBee** [comment]
Yeah, it has gotten worse since I originally opened this issue. I can't find: Washington, Oregon, California, Texas, Minnesota, Ohio, Florida, Virginia and Maryland.
