### ISSUE TITLE
Maps Just Exploded Over Columbus, OH

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#2402]
Well, this one is an interesting bug.    It seems to be mixing sequences.   I didn't see this a couple days ago.  Maybe a bug got introduced to the rendering?

https://www.mapillary.com/app/?lat=39.92383784387275&lng=-81.83169854980409&z=6.749718761072398
![image](https://cloud.githubusercontent.com/assets/11722025/21031012/5455cb34-bd6f-11e6-8189-e4233884a997.png)

**Comment by AllenGraetz** [comment]
oh duh... it's NE of Columbus.  :)

**Comment by pkoby** [comment]
If you click on any of those sequences, you'll see that they're not in any sensible order for the most part, and many of them seem to have a clear focus to each picture (a tree, a building, etc.). If you zoom in, it doesn't look like sequential lines even if you put a bunch of sequences together.

My guess is that this user had a bunch of georeferenced photos taken individually, and uploaded them all at once, so Mapillary took them to be a sequence. I would guess that this user is a Panoramio convert. Another clue is that all the photos are pointed north up.

As far as I'm aware, the database checks for giant distances between photos every few days and cuts up the sequences accordingly. The cluster of craziness should disappear soon.

**Comment by ToeBee** [comment]
A good number of pictures by this user are not appropriate for Mapillary. I just went through a sequence that was a trip to the zoo including zoomed in pictures of animals and people. Another sequence is mostly of puppies. I'm thinking Mapillary might want to reach out to this user and clarify some things.

**Comment by AllenGraetz** [comment]
https://www.mapillary.com/app/?lat=43.82368085501312&lng=-88.48974968846223&z=6.760133969822504&pKey=s8T9ecRR0ZNTBwkssnBsqw

**Comment by AllenGraetz** [comment]
![image](https://cloud.githubusercontent.com/assets/11722025/21057994/ef8f518e-be09-11e6-970e-0fd2e49af9d2.png)

**Comment by AllenGraetz** [comment]
https://www.mapillary.com/app/?lat=41.943790153881224&lng=-83.1828453053089&z=6.760133969822504&pKey=s8T9ecRR0ZNTBwkssnBsqw

**Comment by AllenGraetz** [comment]
![image](https://cloud.githubusercontent.com/assets/11722025/21058015/021dfe86-be0a-11e6-84fc-e506e1140d8c.png)

**Comment by AllenGraetz** [comment]
Toebee, thanks. That makes more sense now.   As one can see above, these are sequences from a user.  When I first saw it, I assumed it was a bug.   But probably not, eh?

**Comment by ToeBee** [comment]
Yeah I think it's just someone that uploaded a bunch of random geotagged travel pictures. I did rather enjoy the vanity plate on the front of the van that reads "Yoder Toter". Based on the name and some other pictures, I'm guessing they are Mennonite. Looks like a good time :)

**Comment by peterneubauer** [comment]
Yeah, these are candidates for splitting. We are working of a better way to correctly handle sequence splits (cuts) and then re-render all tiles so we get rid of the lines.

**Comment by katrinhumal** [comment]
These have been re-rendered now so closing this.
