### ISSUE TITLE
allow switching "original" in the compare mode

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2404]
opening images in the compare mode, one can compare the single original image to any of the "compare it to" images, but not compare any two "other" images - that is, switch the "original" to one of the "compare it to" images.
this would be helpful when one notices that two of the "other" images would make for a better comparison.

**Comment by katrinhumal** [comment]
@richlv Thanks, this is good input! I've taken it to our ideas pool for features and improvements.
