### ISSUE TITLE
Location search does not work with mouse 

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2405]
### Overview
The Search function on the map cannot be operated with mouse clicks. 
It works fine with the navigation keys on the keyboard plus the Retun key.

### Basic information
* Platform: `Web`
* Version: `not applicable` 
* System/Browser: `Windows 10 latest version, Firefox or Chrome or Edge`

### Steps to reproduce behavior

 1. open he mapillary.com site
 2. click "Explore the World"
 3. click the looking glass
 4. type 'Padova' or any other string that produces multiple choice
 5. cllick with with the mouse any of the offered choices

### Expected behavior
the map opens with the clicked location in the center of the window

### Actual behavior
the choice menu disappears, and nothing else happens

### Additional information
If you select the desired location with the up/down keybord keys, and then hit Return everything works as expected.

**Comment by knikel** [comment]
@voschix: The search box should work as expected now.

**Comment by voschix** [comment]
Thanks.
It has been OK for some time now.
Volker
