### ISSUE TITLE
OSM Editor iD does not show corrected positions

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2406]
I corrected positions of some images (a few weeks ago) and they are shown in the OSM editor iD on the original position:

https://www.openstreetmap.org/edit#map=19/51.87634/8.48659

![image](https://cloud.githubusercontent.com/assets/2410353/21243163/e9d8fd7c-c317-11e6-8b1c-e80253beede4.png)

https://www.mapillary.com/app/?lat=51.876170312342055&lng=8.486313783826148&z=18.092393909969125

Related to #2385 which is the same issue for the raster tiles.

**Comment by jesolem** [comment]
Thanks @HolgerJeromin - assigning @peterneubauer to investigate.

**Comment by peterneubauer** [comment]
That's true. The API is right now returning the original positions. I think the corrected ones are in the vector tiles @gyllen ? So when we implement that in iD (which is even great for preformance) we could switch to corrected positions.

**Comment by HolgerJeromin** [comment]
My question is: Why return "known false positions" in the API?

**Comment by gyllen** [comment]
Changesets should now go through when they are approved
