### ISSUE TITLE
Photo labels and location description

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2407]
I would like to use this issue to start a discussion on a feature request regarding photo labels and/or area descriptions. Mapillary is currently lacking any sane means of adding or processing photo labels or a location description. I think that processing and displaying this meta data may be a very useful feature for many users, especially for mapping and managing photos.

By the way, I have observed lately that some Mapillary users, mostly those who migrated from Panoramio started—for lack of better means—*abusing* the comment function to add titles or labels to photos.

The EXIF specification defines basically *four* fields for this purpose; `ImageDescription 0x010E`, `GPSAreaInformation 0x001C`, `DocumentName 0x010D`, and `UserComment 0x9286`. Now, there are certain caveats to each field.
* Because the initial EXIF specification has been designed by short sighted people—to say the least—`ImageDescription` is limited to the ASCII character set only, so it is rather useless for any global web use cases.
* `GPSAreaInformation` seems to be perfect for this use because by specification it is unlimited in length and accepts the ASCII, Shift-JIS, and Unicode (probably UCS-2 or UTF-16, the specification is incomplete here) character sets. It is also easily extendable to support other character sets, if necessary.
* I did not find any specific information on the `DocumentName` field but it is probably limited to ASCII only either, since it comes by id just before `ImageDescription`. Besides, `DocumentName` probably has different semantics than a title, label, or location description.
* `UserComment` seems to fit the profile almost as perfect as `GPSAreaInformation` because by specification its value is unlimited in length and can take ASCII, Shift-JIS, and Unicode strings. However, its semantics are very broad, where it can contain anything from simple tag words, multi-line text to fully fledged XML documents.

Apart from choosing a field for photo titles or labeling, some thought should go into the field's value format for better machine processing too. Since the location description of many photos will pertain to an identifiable street name or highway number (possibly including a milestone value), a locality, postal code, region, province, state, and country a scheme (or format) should be chosen or devised. This scheme does not need to be mandatory but could be advised by Mapillary for machine processing. I think it should be advantageous to resort to an existing standardized scheme.
For photos which can not or do not have a location description that fits a scheme/format (e.g. because they have been shot far from civilization) an alternative geological labeling scheme may be advised or devised.

Here is a short list of possible standardized formats/schemes (for civilized areas):
* Distinguished Names of LDAP/[RFC 4514](https://tools.ietf.org/html/rfc4514), based on X.500
* [OpenStreetMap XML](https://wiki.openstreetmap.org/wiki/OSM_XML) describing only one node with [`name`](https://wiki.openstreetmap.org/wiki/Key:name), [`addr:*`](https://wiki.openstreetmap.org/wiki/Key:addr), or [`ref`](https://wiki.openstreetmap.org/wiki/Key:ref) tags
* *more* *schemes* *exist,* *so* *feel* *free* *to* *post*

**Comment by jesolem** [comment]
Thanks @GITNE - just so that we understand what you mean by a label in this case, can you give us one or two concrete examples?

We are working on tagging/labeling of areas in the images so that you can mark something and add a label/tag. This will then be available in searches on the map. We have comments for images. It looks like you are suggesting a new option. Am I right?

**Comment by GITNE** [comment]
> Thanks @GITNE - just so that we understand what you mean by a label in this case, can you give us one or two concrete examples?

My basic idea or assumption is that users/contributors may want to label a photo with a location description, either in the file—hence the talk about EXIF fields—or once the photos have been uploaded to Mapillary. In technical terms this is similar to adding title meta data to a video, which for example shows up on YouTube after upload in the user's *console*.
Furthermore, the idea is that human readable location description data should be made machine readable too, or in other words, the goal is to enable machine processing of location data beyond coordinates. So, a contributor may use a simple location free title like `Winterspaziergang` (winter walk), which provides no data about the location. But, he/she could also use a human **and** machine readable location description using the distinguished name scheme, e.g. [`CN=Winterspaziergang,STREET=Kirschblütenweg,L=Prenzlauer Berg,ST=Berlin,C=DE`](https://www.mapillary.com/app/?pKey=5ijPLVdUns0nlzXwr7KRrA). Of course, this is an overly simplified example.

Like I have mentioned earlier, this string could go into the photo file (more specifically, one of the EXIF fields I have mentioned above) prior to upload. On the server side, Mapillary is free to store or index this data in any way it may suit a service.

One benefit of doing this would enable auto-adjusting the GPS location data of a photo (after upload) or fixing a photo to a specific area, street, or road (where map data exists) instead of just relying on GPS data. GPS location data is limited in the sense that it basically gives you non-descriptive coordinates like latitude, longitude, and height. They aren't very much human readable (or usable) and also pretty much useless for navigation or finding content to map. Besides, the GPS location data of a photo is sometimes off by dozens of meters.

I am also aware that this scheme can work the other way around. Human and machine readable location description data can also be generated by machines, e.g. from map data and photo coordinates. However, before this human/machine interchange can happen, some sort of format or protocol must be specified to make it work smoothly.

> We are working on tagging/labeling of areas in the images so that you can mark something and add a label/tag. This will then be available in searches on the map. We have comments for images. It looks like you are suggesting a new option. Am I right?

This sounds interesting too, however I think what you are talking about is labeling or tagging image content with image coordinates, like face, license plate, sign, bench, waste basket, car, etc. This may be useful too, however serving or exporting this kind of photos with additional photo content meta data (and value) is going to require a labeling specification, format, or scheme too. AFAIK, this does not exist yet, so Mapillary is free to set a standard. :wink:

**Comment by jesolem** [comment]
Thanks @GITNE , understood.

We are thinking something similar for in-image tagging; free form human description with optional machine class for telling our algorithms what it is. 

Good input and we will return to this issue in a few weeks when we're closer to in-image tagging. Late January or February is my best guess.

**Comment by GITNE** [comment]
@jesolem Thank you for sharing your thoughts and work on tagging photos.

So, it comes down to two categories of tags: Tags that refer to the content (internal) and tags that refer to the location or position (external) of a photo. In other words, instances of internal or content tags are visible in the photo, whereas instances of external tags are non-visible meta data. Both categories of tags are worth while to think about and to design (data structures or protocols) for. Currently, I am interested in external tags describing the geographic location of a photo.

After thinking even more about the `GPSAreaInformation` field, I have realized—although I knew that before—that a description of a geo location is culture and/or administration specific. This is also why the notion that every geo location description could be expressed in one global general address scheme is a naive assumption. Hence, one possible approach to solving this problem might be to have no structure for geo location tags at all. Tagging could just be done as a *set* *of* *words*. No order, no structure, in effect just a simple list. This *scheme* would also work for every language and script.
Let me give you an example. Look at this photo and its location:
[https://www.mapillary.com/app/?focus=photo&pKey=N0Fs38c_BIkrsKNycE-41w](https://www.mapillary.com/app/?focus=photo&pKey=N0Fs38c_BIkrsKNycE-41w)
A set of possible geo location description tags for this photo might look like this:
`"Brandenburger Tor" Brandenburger Tor Berlin Platz Pariser Deutschland "Land Berlin" Europa Erde "Straße des 17. Juni" Straße Strasse des 17 17. siebzehnter Juni "Unter den Linden" Unter den Linden Ebertstraße Ebertstrasse Max-Liebermann-Haus Touristeninformation mittlerer Bogen Tormitte Mitte Tierpark zwischen Säulen "Brandenburg Gate" Brandenburg Gate Earth street 17th seventeenth June tourist information center middle arch between columns`

This set of words has no structure. However, if this set would be processed by a human being he/she should be able to pinpoint the described location quite precisely, this is of course assuming basic skills like literacy and understanding of geography. But, assuming these basic skills is not the point here. The point is that a geographic location can be described in words, or in reference to other locations.

In an area far from civilization, a different example might be: `three 3 days "72 hours" walk west of oasis south Sahara desert Africa Earth`.

These location descriptions could also enable specific kinds of searches and queries, like: “Find all photos in center arch in Berlin” or “Find all photos below a bridge in Malmö” or “Find photos shot from a drain cover”. These are just some more or less *extreme* examples to make a point.

Anyhow, just recently, I have remembered that Mapillary apps already do export some proprietary meta data into photo files, presumably structured in XML. Documenting this for third party applications might be a good start.

**Comment by jesolem** [comment]
Following up here. We have in-image tags for image regions, we have image tags for properties of the image itself. Closing this. 

If there are any remaining feature requests not solved yet, please send an email to support@mapillary.com with the details so we can track it.
