### ISSUE TITLE
Photos count not consistent between web and iOS

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2408]
### Basic information
* Platform: `iOS`
* Version: `4.5.10` 

### Steps to reproduce behavior
 1. Look at the Profile tab in the iOS app, see that I have 8344 photos uploaded
 2. Loot at [my profile](https://www.mapillary.com/app/user/habi) online, see that I have 11.5k photos uploaded

### Expected behavior
Consistent number

### Actual behavior
8344 vs, 11.5k images

![img_1047](https://cloud.githubusercontent.com/assets/1651235/21315622/581d6574-c5fd-11e6-8bf2-4fe83bc63ec7.png)
![clipboard01](https://cloud.githubusercontent.com/assets/1651235/21315623/581f5af0-c5fd-11e6-8586-e9d8fc55746b.png)

**Comment by peterneubauer** [comment]
Is this still the case @habi ?

**Comment by habi** [comment]
Yes.

**Comment by habi** [comment]
I don't know if that's the issue, but I also don't get any emails from Mapillary anymore (on successful uploads, etc.) even tough everything is set to 'On', as seen in the screenshot.
And yes, I've checked the spam folder :)

![screen shot 2017-01-12 at 22 13 10](https://cloud.githubusercontent.com/assets/1651235/21908532/65e81cec-d914-11e6-9c1a-8d2b09c9c2a0.PNG)

**Comment by jesolem** [comment]
I had this issue too for a while but it got fixed for me yesterday without any log in/out.

**Comment by peterneubauer** [comment]
Yup,
the API was still pointing to ELS1. closing, thanks @gyllen for fixing!
