### ISSUE TITLE
parsing error in .apk 3.11

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2410]
the .apk from http://android-releases.mapillary.io/index.html gives a parsing error and doesn't install.

**Comment by peterneubauer** [comment]
Let me check ...

**Comment by peterneubauer** [comment]
Installs just fine for me, I used http://android-releases.mapillary.io/Mapillary_Android_current.apk - what is your error, maybe you have a screenshot?

**Comment by polarbearing** [comment]
Different effect on different devices. 3.11 updated on a BQ Aquaris, marshmellow 6.0.1.

Trying to install on a Nexus S (crespo), CM11 (android 4.4.4) works for 3.08, fails for 3.11:
(no mapillary installed before, trying a new install first, then install 3.08, then trying to update):
```
> adb install Mapillary_Android_3.11.apk
[100%] /data/local/tmp/Mapillary_Android_3.11.apk
Failure [INSTALL_FAILED_OLDER_SDK]
> adb install Mapillary_Android_308.apk 
[100%] /data/local/tmp/Mapillary_Android_308.apk
Success
> adb install -r Mapillary_Android_3.11.apk
[100%] /data/local/tmp/Mapillary_Android_3.11.apk
Failure [INSTALL_FAILED_OLDER_SDK]
```

Copying the apk to the device and installing with the CM file manager gives "Parse error: There was a problem parsing the package".

**Comment by de-vries** [comment]
> "Parse error: There was a problem parsing the package".

this is the exact error I get.

**Comment by peterneubauer** [comment]
This might be a build problem. Is http://android-releases.mapillary.io/Mapillary_Android_3.12.apk working? This might not be a final build, just a test ...

**Comment by de-vries** [comment]
3.12 solved this issue for me

**Comment by peterneubauer** [comment]
Ok, will update the release, Sorry for that!

/peter

**Comment by polarbearing** [comment]
```
> adb install -r Mapillary_Android_3.12.apk
[100%] /data/local/tmp/Mapillary_Android_3.12.apk
Success
```
