### ISSUE TITLE
Android UploadService does not always terminate properly

### ISSUE THREAD

**Issue by rsahlin** [mapillary/mapillary_issues#2411]
### Basic information
* Platform: Android
* Version: 3.11

### Steps to reproduce behavior

 1. 
Trigger network access (toggle wifi on/off)
This will happen frequently to users since network acces, both cell and wifi, will be connected/disconnected.

Check running services - MapillaryUploadService will now be running.
 2.
 3.

### Expected behavior
MapillaryUploadService should not be running since nothing is done.
...

### Actual behavior

...

### Additional information

...

**Comment by rsahlin** [comment]
The service is not terminated when it has nothing to do (only responds to progress or network state)

**Comment by peterneubauer** [comment]
should be solved now in 3.12. Please reopen if not.
