### ISSUE TITLE
"upload failed" 

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#2412]
### Basic information
* Platform: `Android`
* Version: 3,10* System/Browser: `...`

### Steps to reproduce behavior

 1. starting upload
 2. upload startet
 3. after a few hours it stops and says "upload failed" Bla bla. Error disappears after a second and the upload starts again. 

So only a few pics are uploaded in a night instead of a hundreds. 
I changed the Smartphone but it doesn't help. About a week ago, the error appears the first time. 

...

**Comment by wegavision** [comment]
here the error:
Upload failed
Error Java.io.IOExeption:
recvfrom failed: ECONNRESET
(Connection resetby peer) 221 of 1105 photos uploaded

**Comment by wegavision** [comment]
If there is no solution, I will delete the pictures. I dosn't make sense, there are waiting ten thousand pictures and the upload always stops after 50-200.

**Comment by mprins** [comment]
The error message you provide indicates an unstable network connection, you might want to tweak the number of upload threads or try change network.

**Comment by wegavision** [comment]
It worked without any problems for one year. 
Pressing the resume button the uploading starts again. why does the app not resume automatically.

**Comment by katrinhumal** [comment]
@wegavision Sorry for getting to this so late but we've had a couple of updates since your reports - could you try and see if you still have issues? It really should be resuming automatically when connection resumes, so if it doesn't, we need to look into it.

**Comment by katrinhumal** [comment]
If this is still an issue with the latest app version, please email support@mapillary.com
