### ISSUE TITLE
Allow edit of time in filter dialog

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2414]
### Basic information
* Platform:  `Web`

### Steps to reproduce behavior

 1. Add a start time in the web filter dialog. This starts from Today. For example change to august 2015
 2.Try to change to july 2015

### Expected behavior
I want to edit august 2015
...

### Actual behavior
I can only reset and start again in december 2016
...

**Comment by katrinhumal** [comment]
@HolgerJeromin Thanks for this suggestion! I'm taking this to the team for consideration.

**Comment by nickplesha** [comment]
@HolgerJeromin In the date picker modal, you can click on the month name to choose a month from a dropdown and the same for the year. This way you're max 4 clicks away from a chosen month/year.

**Comment by HolgerJeromin** [comment]
I still think that editing should be possible.
Counting clicks is the wrong way if you ask me, but ok. Lets count:

Wanting to change an date (perhaps change by one day) **current approach**:
1. delete old date with the x
2. click into the field
3. click the month
4. select the new month (including remembering the old value)
5. click the year
6. select the new year (including remembering the old value)
7. click the new day (including remembering the old value)

Wanting to change an date (perhaps change by one day) **with edit support**:
1. click into the date
2. select different day (no need to remember the old value)

perhaps you need 
1b. move to a different month with the arrows.
