### ISSUE TITLE
Android app does not handle upload dialog correct 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2415]
### Basic information
* Platform:   `Android` 
* Version: `311` 
* System/Browser: `Fairphone 2 with Android 5.1`

### Steps to reproduce behavior

 1. Take some sequences 
 2. Start uploading one
 3. Leave app or upload tab

### Expected behavior
Going to the upload tab should have updated upload count and if the upload is ready the dialog should be gone. 

### Actual behavior
Often I am see an old count for example  1/5. Even after finished  upload I see 1/5 and am not able to review other sequences. 

Closing the app recovers.

**Comment by mxa** [comment]
confirm this issue in 312

**Comment by ulikoehler** [comment]
I can confirm this on LG G2.

**Comment by katrinhumal** [comment]
@ulikoehler could you please tell me which app version you have?

**Comment by ulikoehler** [comment]
@katrinhumal Sure, its 3.54.
Just so you know, this happens *every* time I'm uploading a sequence. So far there wasn't a single time where the dialog disappeared as expected.

I can provide screenshots, more info etc. if you need it - feel free to ask!

**Comment by HolgerJeromin** [comment]
> So far there wasn't a single time where the dialog disappeared as expected.

Same here. 
Start upload, leave the app. When you come back to the app later the status is not updated from the upload service but still the old status. When the upload service has a change (has uploaded an image) the download dialog is updated. But when there is no change anymore (upload aborted or finished), the dialog is never updated/fixed again.

**Comment by ulikoehler** [comment]
@katrinhumal Would it help if I could provide you with the ADB log of my phone?

**Comment by mxa** [comment]
With every update i expect this issue to be solved, but it is long standing. Currently in 3.54 but this has been like that since many months.

**Comment by katrinhumal** [comment]
Logs would be helpful! Please send by checking the "Save debug logs" option in the Developer section and then submitting them from the hamburger menu.

@peterneubauer will you keep an eye on this, please?

**Comment by ovivoda** [comment]
@katrinhumal Can you ask HolgerJeromin to test this with v3.56 - Beta: http://android-releases.mapillary.io/Mapillary_Android_3.56-BETA.apk

**Comment by ulikoehler** [comment]
@ovivoda I will try testing with the beta later today.

**Comment by ulikoehler** [comment]
@katrinhumal Sorry, I must have missed you message regarding the logs. If the issue still occurs with the beta, I'll send you the logs.

**Comment by HolgerJeromin** [comment]
I have v3.56 installed (playstore beta) and will try to report back when i have more to upload.

**Comment by ulikoehler** [comment]
It seems to me like this issue is fixed in 3.56. I have tested with a one-photo sequence and everything works as expected. I will continue to test with other sequences.

**Comment by ulikoehler** [comment]
I've now tested with a longer sequence and there doesnt seem to be a problem any more (so far, at least). However, I've noticed that when you start the upload and then turn your smartphone off (i.e. display) and on again, it only displays `... ...`: 

http://i.imgur.com/okwNjgV.png

Maybe someone else can confirm that?

**Comment by ovivoda** [comment]
@ulikoehler That is displayed while waiting for a notification from upload. When a new image is uploaded the progress should be updated with correct data. Do you see it as confusing? Maybe we should add "waiting for progress..." ?

**Comment by ulikoehler** [comment]
@ovivoda It's a little bit confusing, but I believe it's not confusing enough for you to waste your time for trivialities like this :-) Now that I know it's not an issue for me.

@HolgerJeromin  What do you think?

**Comment by mxa** [comment]
Confirming what @ulikoehler wrote. Main problem is fixed, but now the progress is shown as in the screenshot in imgur.

**Comment by ovivoda** [comment]
@ulikoehler @mxa Thanks a lot for the feedback. 

Changed the dialog to show "Checking progress from background sync service ..." while the updates are available to the UI thread.

This is already available in http://android-releases.mapillary.io/Mapillary_Android_3.57-SNAPSHOT3.apk

**Comment by HolgerJeromin** [comment]
Even Beta 3.56 from play store is much better. Thanks for your work
