### ISSUE TITLE
Android app "Could not save image"

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_issues#2416]
### Basic information
* Platform: `Android`
* Version: `3.10` 
* System/Browser: `Android 4.2.2`

### Steps to reproduce behavior

 1. Start capture

### Expected behavior
capture images

### Actual behavior
app says "Could not save image",
"ERROR: Exception saving capture - Not a Valid TIFF File" in log file.

### Additional information
My Android phone is FUJITSU ARROWS Z FJL22(au KDDI)

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/672167/mapillary_trace.txt)

**Comment by peterneubauer** [comment]
That's really odd. Is this happening all the time? In this case, it seems that https://github.com/fulcrumapp/sanselan-android/blob/master/src/main/java/org/apache/sanselan/formats/tiff/TiffReader.java#L65 is not being able to read the stream from the camera subsystem as a valid TIFF image with EXIF data.

**Comment by kudarisenmon** [comment]
This is happening all the time on this model. Is this avoidable by app or android setting?

**Comment by peterneubauer** [comment]
Is this still happening with version 3.55?

**Comment by kudarisenmon** [comment]
Version 3.56 works fine! Thank you.
