### ISSUE TITLE
Sequence edit is sometimes not reflected on the map

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2417]
When sequences are edited for position, the new positions of the pictures are not always reflected on the map.

Take for example sequence [sm_wNuq4pBHtH0S8vCIb-w](https://www.mapillary.com/app/?focus=map&pKey=gnwppyyhOoHYhWQc3nO1_Q). I got confirmation that my positioning edit was accepted weeks ago. It is a panorama so the photos should be in a tight circle. And they are actually. But the sequence vector on the map still shows the GPS drifted versions of these photos.

I have seen some sequences where the changes **are** reflected. But I have several examples where they aren't. If you zoom in, you can even see that the orange "current photo" marker on the map is not along the blue "current sequence" feature. Screen shot:

![image](https://cloud.githubusercontent.com/assets/348948/21533834/655e7132-cd24-11e6-9e2a-b2650710fd00.png)

Some other affected sequences:
* [2dDPwDsxuoZJ1CPBKzFX8A](https://www.mapillary.com/app/?focus=map&pKey=lEHVAt7rwNaY6U2Cp13rIQ)
* [yS9u0MGUS2QQ_qn_0I404w](https://www.mapillary.com/app/?focus=map&pKey=llSsUH5NaLNAVBb_BJnrQw)
* [HVHoJx5StjOUgWILJpD9BQ](https://www.mapillary.com/app/?focus=map&pKey=mvl0nD3rK3h-Yp1FYAFbVA) (this one is only a couple of days old, unlike the previous ones)

On the other hand, here is a sequence that was correctly updated on the map after the edit was approved: [jNrUy8mTRhmOvoET33HEZw](https://www.mapillary.com/app/?focus=map&pKey=yaqJyh3dSinlhTrY31M3OQ&lat=37.64306370020847&lng=-103.57271582274379&z=20)

**Comment by ToeBee** [comment]
Another two sequences edited today and the changes are not showing on the map: 
* [GC0KNh5zcEAnae7Gm7NnzA](https://www.mapillary.com/app?pKey=p4o_D4ncfHyQEjlgn5bFdg&focus=map)
* [Ub44T8um9AtX1WWazf8e3Q](https://www.mapillary.com/app/?pKey=cEqCQwme08uGXnbx-G7rJQ&focus=map)

**Comment by peterneubauer** [comment]
Are they showing now?

**Comment by ToeBee** [comment]
Still a problem. Follow my links and look at the sequence, then go into edit mode. You will see the positions are not at all the same in edit mode as they are shown on the map.

**Comment by Thomas8122** [comment]
3 annoying sequences from me

- [the uncorrected positions appears as a green line](https://www.mapillary.com/map/im/gUmFFKrG8Zodg6y1kL3Q0A)

- [Example 2](https://www.mapillary.com/map/im/ED-WZ4-mNP2u_P7uHBKGPw) Every time when i will edit such sequences, i click _Edit current sequences_ and voilà, it is always edited.

- [Example 3](https://www.mapillary.com/map/im/4mpvDVqrQhDUd-FVOsqZ1Q)

**Comment by ToeBee** [comment]
It looks like this is fixed now.
