### ISSUE TITLE
Map view indicates 360 panoramas for normal pictures

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2418]
I uploaded several sequences at a castle yesterday that now show up on the map with the large circle around them and the mouse-over popup has the "360 view" label at the bottom but they were normal pictures taken with the Android Mapillary app. The first one was a panorama sequence but just because I switched the app to manual mode and snapped a bunch of pictures manually while spinning in a circle. Each picture itself is just a single shot from my phone's camera.

The affected sequences are all in this view: https://www.mapillary.com/app/?pKey=1F7Qk3oBJtjGhghPHen4GA&lat=47.79407715238281&lng=18.981190428462128&z=17.202838562588497&focus=map

This might be related to #2261 but that one seems to be sequences where the viewer is actually trying to display pictures as panoramas when they aren't. In this case if you click on the pictures they are displayed correctly as non-panorama images. It's just the map view that is wrong.

**Comment by pkoby** [comment]
It looks like everything in the last couple of days has been doing this, for everyone. I filtered everything from the 29th on and only found 360s. Interestingly, when zoomed way out (and the sequences show as dots), and I turn on the 360 filter, most disappear, but they still show up when zoomed in and viewed as lines.

**Comment by ToeBee** [comment]
Oh, you're right. My uploads from last (taken with a GoPro, uploaded with the script) are showing the same thing.

**Comment by pkoby** [comment]
It seems to be back to normal. Not only are all uploads from yesterday looking right, but I just checked the one you linked, and it's correct now as well.

**Comment by ToeBee** [comment]
Yeah it looks like all the ones in the area I originally linked are fixed. But the ones here are still showing as 360s: https://www.mapillary.com/app/?lat=47.46679722640948&lng=18.97648306845437&z=17.273595621686034

Although only at some zoom levels. Seems like maybe a cache got polluted with bad data and needs to be cleared?

**Comment by peterneubauer** [comment]
That is a bug, we will rerun the Vector tiles for these days, should be ok for the new images. The data is safe

**Comment by peterneubauer** [comment]
Fixed.

**Comment by de-vries** [comment]
[here](https://www.mapillary.com/app/?lat=51.684635197807495&lng=5.3092013431545695&z=17.636180774187103) is a whole patch where all photo's are changed into 360's, even the old ones.

**Comment by ToeBee** [comment]
My last link still leads to mistaken 360 pictures at zoom levels 17+

**Comment by peterneubauer** [comment]
Will rerun that day too. Thanks!

**Comment by ptpt** [comment]
This is an issue in our tiler which wrongly recognized 360 images. We have fixed the issue and rerendered sequences above. Sorry for the inconvenience.

**Comment by ToeBee** [comment]
I hate to be the bearer of bad news but there are at least two more that need rerendering along one of my Hungary traces. The links start at the south edge of the problem tiles.
* https://www.mapillary.com/app/?lat=47.51744904332645&lng=19.03935606534884&z=17&pKey=op5RBHO4rvancrLOuyU54A
* https://www.mapillary.com/app/?lat=47.60646811250001&lng=19.06091167249997&z=17&pKey=X-qhQHEH1JaHSGScnSqZ4w

**Comment by ptpt** [comment]
Should be this tile at the cloud front cache not refreshed. Will ping here when it gets updated. Thanks for reporting.

**Comment by ptpt** [comment]
Hi @ToeBee sequences look right now. Don't hesitate to let me know if you have more issues with your uploads :)

**Comment by ToeBee** [comment]
Someone once said "Caching is easy. Knowing when to invalidate the cache is hard" :)

Things do indeed look good to me now. :+1:

**Comment by peterneubauer** [comment]
👍

**Comment by filipca** [comment]
Spheric only downwards : https://www.mapillary.com/app/?pKey=kXf2IOn9LUBZGP5Dw8PD7A&lat=50.849879259421115&lng=4.345977336861625&z=17&focus=photo&menu=true
Flat pictures that think that they are spheric and showing black.
These are just examples of many more wrong sequences.

**Comment by ptpt** [comment]
Hi @filipca what is the problem with the photos there? They look fine to me:

<img width="1129" alt="2017-01-24 11 20 51" src="https://cloud.githubusercontent.com/assets/87357/22243350/3460255e-e227-11e6-9bc0-71b3904fc7ec.png">

**Comment by filipca** [comment]
I must have made an error.
But this gives a black image.
https://www.mapillary.com/app/?pKey=N8h6UQTiLmUWC_NibAiKSQ&lat=50.857174122405695&lng=4.366701988777095&z=17.000000000000004&focus=map&menu=false

**Comment by ptpt** [comment]
Thanks @filipca for reporting. The black image is a system issue. Investigating and will get it fixed soon.

**Comment by peterneubauer** [comment]
Ok,
the tiling needs to be updated, yes. The black images are because of the same reason, we will fix the backend API to send the correct data to MapillaryJS ASAP.

**Comment by ptpt** [comment]
@filipca Both tiles and the black image are fixed (make sure tiles cache is cleared when you check). Thanks a lot for reporting and sorry for the inconvenience.
