### ISSUE TITLE
Wrong HTTPS for images.mapillary.com

### ISSUE THREAD

**Issue by zbycz** [mapillary/mapillary_issues#2419]
### Basic information
* Platform: `Web Api`
* Version: `*` 
* System/Browser: `several`

### Steps to reproduce behavior

 1. Open https://api.mapillary.com/v1/im/close?lat=50.10058&lon=14.39194&distance=30&limit=1 - OK
 2. Load mentioned image https://images.mapillary.com/khAHIbl6MmqXegXpE79UvQ/thumb-320.jpg - PRIVACY ERROR - page wouldnt load - wrong certificate

### Expected behavior

Domain images.mapillary.com should have valid HTTPS certificate.  Or please provide another way to connect securely. Thanks!

### Test case

https://openstreetmap.cz/node/1601837931

**Comment by martinskans** [comment]
This is probably an old issue that no longer applied (since the api.mapillary.com domain given doesn't even exist anymore), but I've made sure the cert for images.mapillary.com is correctly updated in any case.
