### ISSUE TITLE
optimize reaction of vibration detection

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#242]
If the app detects a vibration it refuses to take a picture. I have the suspicion that the next photo is taken not until the next photo timeout has reached (5s as i am cycling). 
I thinks the next photo should be taken "immediately" after the vibration is gone to prevent holes in the sequence.

**Comment by HolgerJeromin** [comment]
We have distance based capture, so no real problem for my anymore.

**Comment by peterneubauer** [comment]
Yes, we will remove the shake detector, it's too hard to get it right.
