### ISSUE TITLE
Radio Button Doesn't Persist on Changed Basemap

### ISSUE THREAD

**Issue by pkoby** [mapillary/mapillary_issues#2421]
### Basic information
* Platform: `Web`
* System/Browser: `Ubuntu, Chrome/Firefox`

### Steps to reproduce behavior

 1. Change basemap from default (Mapbox Streets) to either other option.
 2. Basemap changes, radio button in layer selector changes back to Mapbox Streets.

### Additional information

If another layer is selected (e.g. OSM), I can still click on the Mapbox Streets button to get that layer back.

![image](https://cloud.githubusercontent.com/assets/7786285/21735045/c00ab46c-d434-11e6-9b1b-abb88257f685.png)

**Comment by nickplesha** [comment]
Thanks for reporting, @pkoby ! This bug has snuck in when we added the map style to the URL for more consistent sharing. We'll have this fixed soon.

**Comment by nickplesha** [comment]
@pkoby This is now fixed! We also have more map style to choose from!
