### ISSUE TITLE
Mapillary watermark & blurs vanish after zoom-in

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2422]
### Basic information
* Platform: `web`
* System/Browser: `any`

### Steps to reproduce behavior
1. Choose any high resolution (> 3MP) photo
2. Zoom into the vicinity of the Mapillary watermark in the lower left corner
3. Optionally, zoom-out again

### Expected behavior
The Mapillary watermark should be displayed or layered on top of the original photo at every zoom level. Ideally, the logo watermark should scale per vector graphics.

### Actual behavior
Watermark vanishes

**Comment by pkoby** [comment]
It looks like the toggle for high-res 360 photos is gone from the "advanced" menu, and maybe this is connected. It looks like when you zoom in, Mapillary now serves the full-res photo, and when it switches to that, it doesn't have a watermark because it's "unprocessed". That's my guess, anyway.

**Comment by GITNE** [comment]
> It also looks like they've figured out tiling the large photos, because if you
> zoom into the top right corner of a really large photo (e.g.
> https://www.mapillary.com/app/?pKey=HvpnvlC46F5LwpM7cVWgMQ&focus=photo), let
> it load, then zoom back out, the watermark is still there.

Yes, I know. This is a great feature and shows progress. :+1:  Now, I have a true incentive to take pictures in the highest resolution supported by my device and upload them to Mapillary, even though it takes considerably more storage space and longer to upload. But, this feature is worth the effort. :smiley:

However, I cannot confirm your observation about the Mapillary watermark still being there after zoom-out. For me, it's still gone after zoom-out, no matter how long I wait.

This bug also affects blurs. Manually applied blurs show up only at *standard* or *initial* *resolution*, even days after the edit. They are gone on zoom-in too. Evidently, this is a serious bug. :worried:

**Comment by gyllen** [comment]
@GITNE Watermark will be gone since the image will be puzzled together by tiles (even when zoomed out). We made a decision to not watermark the tiles so thats all good from our side.

For blurs this is cache in our tiler. We will set the TTL for a tile to a day now so please check if you can see that the blurs are also updated in the tile (worst case it will take 24h to update).

**Comment by GITNE** [comment]
> We made a decision to not watermark the tiles so thats all good from our side.

Doesn't this enable anybody to download the full image data *without* any watermark or attribution?

AFAIK, the *big* *G* company has moved from applying visible watermarks on single tiles to steganography. Can we assume that Mapillary has moved to a similar method of watermarking?

> For blurs this is cache in our tiler. We will set the TTL for a tile to a day now so please check if you can see that the blurs are also updated in the tile (worst case it will take 24h to update).

Yeah, I thought so this may be caused by caching. A 24h cache delay sounds reasonable. :+1:

**Comment by jesolem** [comment]
@GITNE We do not use Steganography even though I think it is cool ;)

The reason as @gyllen explains is that when you zoom in you load lots of small images (like map tiles on a map) that get composed to the image you see and it makes no sense to watermark all of these. You would get lots of watermarks in the view then.

**Comment by GITNE** [comment]
@gyllen The 24h maximum cache delay limit seems to be working and effective.

Since you (Mapillary) do not intend to put a watermark on the zoomed-in or *full* *resolution* tile this issue seems to be fixed and can be closed, unless you want to investigate it further.

**Comment by jesolem** [comment]
@GITNE 👍  - closing
