### ISSUE TITLE
Search for "Dundee" shows place in USA as first result

### ISSUE THREAD

**Issue by boothym** [mapillary/mapillary_issues#2423]
Searching for "Dundee" on the Mapillary website (any browser) shows a place in Nebraska USA and not Scotland as the first result. 

![dundee](https://cloud.githubusercontent.com/assets/16965772/21750416/a0dcd26a-d5aa-11e6-8138-962547fcaeb0.jpg)

Same for "Stirling" and "Inverness" - both showing OSM hamlets as the first result and not the Scottish cities.

**Comment by nickplesha** [comment]
@boothym Thanks for reporting this interesting issue. Our search is powered by Mapzen and we don't have much control on how the search results are sorted. The search algorithm is constantly improving in accuracy and relevancy of search results so I would expect the quality of our search function will improve with it.

**Comment by boothym** [comment]
Thanks for the response. Where is the best place to get this sorted then - is there an active github for Mapzen search or should I email them?

**Comment by nickplesha** [comment]
@boothym https://github.com/pelias/pelias is the project used by Mapzen search.
