### ISSUE TITLE
Mapi-llary Kenobi says:  These are not the images you're looking for *waves hand*

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2425]
(Actually that's not the message I get, but the Star Wars reference was too good to pass up.)

Lately I've been getting "Sorry, we can't find the image you're looking for" on a lot of random images in my sequences.  These are all "old" sequences, too, in that they're a month or more old.

### Basic information
* Platform: Web
* Version: `...` 
* System/Browser: Windows 7.  Firefox and Chrome.

### Steps to reproduce behavior

 1.  Go to the image https://www.mapillary.com/map/im/YzpVFm0NqewCXr_8w0vCvg
 2.  Try to advance to the next image, either with the Play button, or the image advance button.
 3.  When that fails, try to click on the dot representing the next image.

### Expected behavior

I expect it to show me the next image :-)

### Actual behavior

I get the "Sorry, we can't find the image you're looking for" message.

**Comment by peterneubauer** [comment]
I think the naming of that image is invalid @gyllen , https://d1brzeo354iq2l.cloudfront.net/v2/mesh/--49xbCtIcKmxBbYALHRWA is giving errors.

**Comment by gyllen** [comment]
This is API related, we are currently working on throttling our backend so you will not experience this

Closing
