### ISSUE TITLE
Sequences with large gaps popping up all over the Midwestern USA

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2426]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 10 Chrome`

### Steps to reproduce behavior

 1. Navigate map to the Midwest USA
 2. Zoom in

### Expected behavior

Lines wouldn't be going all over the place at small scale

### Actual behavior

There are a lot of wonky tracks that cross many hundreds or even thousands of miles. Seems to be by user `jbthemilker`

### Additional information
![chrome_2017-01-15_17-14-50](https://cloud.githubusercontent.com/assets/1827881/21966682/28e06564-db46-11e6-9c36-fae86bff7b3b.png)

Here's a gif of zooming in

![2017-01-15_17-13-52](https://cloud.githubusercontent.com/assets/1827881/21966673/0810c446-db46-11e6-907c-ada14360b0e0.gif)

**Comment by peterneubauer** [comment]
I'm on it, this is the rendering that is not updated properly after we cut the sequences. Redoing the whole process asap.

**Comment by ToeBee** [comment]
I think probably the same thing as #2402?

**Comment by peterneubauer** [comment]
This is fixed now, and sequences are automatically cut on the server.
