### ISSUE TITLE
Website: while browsing "Uploads", websites refreshes itself and jump to "Feed", every few seconds

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2427]
Web: (Safari 10.0.2)
becomes less usable every time I look :-(
Nobody fixes #2313, and now I can't even count my uploads without being kicked out and thrown back to the feeds :-( 
It refreshes every 60 sec or so with big visual flicker.

**Comment by polarbearing** [comment]
Though the website swaps from the Upload to the Feed section, this does not mean the Uploads would be refreshed. I had to manually reload the page to see new uploads. :-(

**Comment by knikel** [comment]
Hi, a few weeks ago we changed how we handle the feed content -- this shouldn't be an issue anymore (Tested on OS X Sierra 10.12.3 and Safari 10.0.3). While investigating that problem, I found that the elements in the feed would get refreshed with every scroll too. I fixed that as well.
