### ISSUE TITLE
Website: position review while uploading not considered

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2428]
I used the 'review' function during the picture upload via the website, and corrected a systematic bend of my track off a road in about 18 frames, before uploading.

However the track I see now as published shows the uncorrected position. 

[Example](https://www.mapillary.com/map/im/FzMWlJGC2a9LCG-NJqDO4w) from this sequence. 

I see in other recent uploads that my work in correcting them was not honoured. :-(

(Also, it is still not possible to correct the angle during web review, there was another issue open already IIRC)

**Comment by katrinhumal** [comment]
@polarbearing what have you captured the images with? Any chance it was the Mapillary mobile app?

**Comment by polarbearing** [comment]
That was a year ago! Most likely with the Android mapillary app, there is an example in the first post.

**Comment by gyllen** [comment]
@nickplesha Exifs not updating properly?

**Comment by nickplesha** [comment]
@gyllen @polarbearing  I believe there was a bug about a year ago related to editing in uploader, it should work properly now. Let me know if the issue occurs again.
