### ISSUE TITLE
Weird panorama with 360° pictures

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#2429]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `Firefox`

This 360° picture looks wrong.
I don't know if the problem is the viewer or my picture:
https://www.mapillary.com/app/?lat=47.06509277777775&lng=-1.3489538888889003&z=17&focus=photo&pKey=aJbd_DkpRo8_4EU7MxvWaQ

Pannellum is ok:
http://www.stemani.fr/pano_v4mpod_bike_01.html

**Comment by oscarlorentzon** [comment]
@Stefal The originally uploaded image does not seem to have the correct `GPano` metadata in the EXIF (https://developers.google.com/streetview/spherical-metadata) for us to recognize this as a cropped panorama. All the properties in the image in the link must be present in the EXIF.

**Comment by Stefal** [comment]
I understand.
Do you know a simple tool to add these properties ?

**Comment by GITNE** [comment]
@Stefal You can use [Exiv2](http://www.exiv2.org) but it is all manual, no GUI.

**Comment by ybkuang** [comment]
I will close this for now since it is related to the metadata of the images.
