### ISSUE TITLE
crash when pressing buttons while recording sequence

### ISSUE THREAD

**Issue by malenki** [mapillary/mapillary_issues#243]
When the app is recording a sequence and I press any of the hardware buttons (loudness, camera) on the phone repeatedly the app makes some more pictures and then crashes reliably.
So far only tested in walking mode.
Hardware: Sony Xperia Z1 compact, images are stored on a 128GB µSD

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by gyllen** [comment]
@peterneubauer Is this still an issue?

**Comment by peterneubauer** [comment]
Closing, should not be relevant anymore.
