### ISSUE TITLE
A Series of Fotos uopside down in App

### ISSUE THREAD

**Issue by stilicrafter** [mapillary/mapillary_issues#2430]
Hello.
A whole scene of pictures uploaded (Created with Mapillary app ) are upside down.
ID (picuture set : -ahf_-SYK1ivv8YWzJPWMA)
First Foto of set : gvGSm1H_wFVn4sLeQq1cXw
Url : https://d1cuyjsrcm0gby.cloudfront.net/gvGSm1H_wFVn4sLeQq1cXw/thumb-2048.jpg

**Comment by peterneubauer** [comment]
I rotated the pictures, should be online in a couple of hours.
