### ISSUE TITLE
Two sequences stuck at the top of my upload list

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2435]
I have two sequences that are now permanently at the top of my list of uploads even though I have 13 (soon to be 14) sequences that were uploaded later.

In a browser the sequences do not have a date listed under them. In the Android app they have a date of January 2 (which I believe is correct)

The two affected sequences are `PtjcVLAkAf4dmcmn5ekirQ` and `U3Zmc-bneNYskmzRmP31Ww`

Screen shot from a browser:
![image](https://cloud.githubusercontent.com/assets/348948/22430662/96593622-e6d4-11e6-8349-ec8c5cb2aa58.png)

**Comment by peterneubauer** [comment]
From looking, this should now be fixed?
