### ISSUE TITLE
Android app: Constant CreateDate 2002-12-08

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#2438]
### Basic information
* Platform: Android
* Version: 321
* Device: Fairphone 2 (Fairphone Opensource OS version 16.12.0 (this is not the default OS with which Fairphone 2s are sold))

### Steps to reproduce behavior

 1. Capture image sequence
 2. Copy files to PC
 3. Run `exiftool *.jpg | grep "Create Date"`

### Expected behavior

Exiftool should display the date when the image was captured.

### Actual behavior

Exiftool shows

    2002:12:08 12:00:00

as `Create Date` for all pictures. The other EXIF tags seem to be unaffected.

### Additional information

This isn't a new bug. I've seen this already some months ago, but can't remember when exactly.

As a workaround I wrote the script at https://github.com/ltog/mapillary_utils/blob/master/fix_createdate.sh which copies the value from `DateTimeOriginal` into `CreateDate`. The script processes several files in parallel (requires the software GNU parallel to be installed).

**Comment by rsahlin** [comment]
Hello @ltog and thanks for reporting

I'm not sure how to fix this error, we do not explicitly set the EXIF create date tag (EXIF_TAG_CREATE_DATE) it is automatically set by the platform.
This leads me to believe there is a bug in the os of the device.
 Could you please verify the EXIF date using other camera applications?

/Richard

**Comment by ltog** [comment]
This indeed seems to be a generic problem as some random Google results show:

- https://forums.oneplus.net/threads/2002-12-08-exif-date-problem.104599/
- http://www.keypressure.com/blog/2002-12-08/
- http://www.modaco.com/forums/topic/339869-anybody-worked-around-stock-libcameraso-putting-20021208-120000-as-the-exif-date/

I'll report this to the Fairphone people...

**Comment by ltog** [comment]
I created a report at https://forum.fairphone.com/t/bug-report-pictures-have-constant-exif-createdate-2002-12-08/25963 .

**Comment by rsahlin** [comment]
Great @ltog 

I had a look at the code and it's definately doable to create a workaround - however it's preferred that they fix the problem in the platform :-)

Please let me know what they respond.
Closing this issue in the meantime - please re-open if fairphone rejects the issue.

/Richard

**Comment by ltog** [comment]
@rsahlin : May I ask you to do the fix anyway for the following two reasons:

1. I reported the bug but I don't have high hopes that it will be fixed anytime soon. As far as I understood from the Fairphone forum they're quite understaffed.

2. Even if they manage to fix it soon, the problem will persist for other platforms, as the links above suggest. As far as I understood it's actually a Qualcomm problem but I don't know the proper place to report bugs there.

**Comment by rsahlin** [comment]
Hi @ltog 

Ok, I understand. Fair assumptions :-)
Let's reopen the issue and see if we can get it prioritized soon.

/Richard

**Comment by ltog** [comment]
@rsahlin : Cool, thank you!

**Comment by peterneubauer** [comment]
This should be fixed now. Closing.
