### ISSUE TITLE
iOS8 + Mac OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#244]
With the abilities opened for development opened with the expected releases of iOS8 and Mac OS X 10.10 Yosemite, there should be possible to integrate two apps, one iOS8 version of Mapillary that can seamlessly transfer the georeferenced fotos to my Mac OS X 10.10 MacBook, which can upload the images to site.

Also, since I have a limited bandwidth (my ISP is not able to supply a better line) I would like my MacBook to be able to set up the upload with bandwidth restrictions.

**Comment by jesolem** [comment]
I'd still love a desktop Mac app but no time to work on that now. Keeping this as a future reminder.

**Comment by jesolem** [comment]
Desktop uploader is in progress now.

**Comment by nicolas17** [comment]
The title of this issue isn't very descriptive... And I don't think Continuity is of much help to transfer photos from phone to computer anyway.

**Comment by jesolem** [comment]
The desktop uploader got stopped, then started, then stopped again. We're going to get back to this one day. In the meantime, closing this and moving to our internal task list. 

Thanks for your patience guys.
