### ISSUE TITLE
No info icon to see exif etc.

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2441]
The photos waiting to be uploaded have no info icon to see any info about them. Like exif details etc.

**Comment by jidanni** [comment]
An I button in a circle.

**Comment by katrinhumal** [comment]
@jidanni when you click on "Review" after selecting or dragging-dropping your photos, you will be able to click on each point to see more information about that photo (thumbnail and some details):
<img width="1247" alt="screenshot 2017-03-22 13 30 25" src="https://cloud.githubusercontent.com/assets/16334352/24195804/daf3c9f8-0f03-11e7-9242-bef90b170a51.png">

**Comment by katrinhumal** [comment]
@jidanni Closing this for now, please reopen if you need more help.

**Comment by jidanni** [comment]
Thanks. (As a low bandwidth rural user, I don't use Mapillary often.)
