### ISSUE TITLE
I am logged in. Why is my name "username"?

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2443]
![screenshot_20170202-184004](https://cloud.githubusercontent.com/assets/1230959/22548504/4b05adce-e90c-11e6-858f-3c772f115063.jpg)

**Comment by rsahlin** [comment]
Hi @jidanni and thanks for reporting

Does this happen everytime when you open the drawer?
What does it say if you go into the 'Profile' tab?

/Richard

**Comment by peterneubauer** [comment]
This should be working better in the newer versoins of the app, please reopen if it still persists after the next release.
