### ISSUE TITLE
Cannot login to PC to mapillary.com on Windows 7 machine using Chrome 55

### ISSUE THREAD

**Issue by EwenH** [mapillary/mapillary_issues#2444]
Hi,
 I am trying to log-in using Firefox/Chrome/IE but lets stick to Chrome as the preferred method. I have never had an issue logging in and this is the first time on this particular machine.

### Basic information
* Platform: Widows 7 wide screen 
* Version: Current (not legacy) website
* System/Browser: Version 55.0.2883.87 m

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/
 2. Enter Mapillary login details
 3. Click "Sign-in" green button

### Expected behavior

Login - as usual

### Actual behavior

Ajax rotating gif just runs and runs. 

### Additional information

The console log shows
Request URL:https://a.mapillary.com/v2/ua/login?client_id={removed}
Request Method:POST
Status Code:401 Unauthorized

Response is 
{code: "user_not_authenticated", message: "User Not Authenticated"}

There is also another error in the log  ...
XMLHttpRequest cannot load https://a.mapillary.com/v2/ua/login?client_id={removed}. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://www.mapillary.com' is therefore not allowed access.

Other errors are ...

EXCEPTION: SyntaxError: Unexpected token o in JSON at position 1
mini-8bf3efc….js:11 EXCEPTION: SyntaxError: Unexpected token o in JSON at position 1
b.logError @ mini-8bf3efc….js:11
b.logGroup @ mini-8bf3efc….js:11
a.call @ mini-8bf3efc….js:29
(anonymous) @ mini-8bf3efc….js:26
b.object.e @ mini-8bf3efc….js:27
b.__tryOrUnsub @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._finalNext @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b.emit @ mini-8bf3efc….js:27
onError @ mini-8bf3efc….js:26
onHandleError @ mini-8bf3efc….js:26
ZoneDelegate.handleError @ zone-2222385….js:327
Zone.runTask @ zone-2222385….js:259
ZoneTask.invoke @ zone-2222385….js:423
mini-8bf3efc….js:11 STACKTRACE:
b.logError @ mini-8bf3efc….js:11
a.call @ mini-8bf3efc….js:29
(anonymous) @ mini-8bf3efc….js:26
b.object.e @ mini-8bf3efc….js:27
b.__tryOrUnsub @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._finalNext @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b.emit @ mini-8bf3efc….js:27
onError @ mini-8bf3efc….js:26
onHandleError @ mini-8bf3efc….js:26
ZoneDelegate.handleError @ zone-2222385….js:327
Zone.runTask @ zone-2222385….js:259
ZoneTask.invoke @ zone-2222385….js:423
mini-8bf3efc….js:11 SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at b._error (mini-8bf3efc….js:25)
    at b.__tryOrUnsub (mini-8bf3efc….js:35)
    at b.error (mini-8bf3efc….js:35)
    at b._error (mini-8bf3efc….js:35)
    at b.error (mini-8bf3efc….js:35)
    at XMLHttpRequest.n (mini-8bf3efc….js:19)
    at ZoneDelegate.invokeTask (zone-2222385….js:356)
    at Object.onInvokeTask (mini-8bf3efc….js:26)
    at ZoneDelegate.invokeTask (zone-2222385….js:355)
b.logError @ mini-8bf3efc….js:11
a.call @ mini-8bf3efc….js:29
(anonymous) @ mini-8bf3efc….js:26
b.object.e @ mini-8bf3efc….js:27
b.__tryOrUnsub @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b._finalNext @ mini-8bf3efc….js:35
b._next @ mini-8bf3efc….js:35
b.next @ mini-8bf3efc….js:35
b.emit @ mini-8bf3efc….js:27
onError @ mini-8bf3efc….js:26
onHandleError @ mini-8bf3efc….js:26
ZoneDelegate.handleError @ zone-2222385….js:327
Zone.runTask @ zone-2222385….js:259
ZoneTask.invoke @ zone-2222385….js:423
mini-8bf3efc….js:25 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at b._error (mini-8bf3efc….js:25)
    at b.__tryOrUnsub (mini-8bf3efc….js:35)
    at b.error (mini-8bf3efc….js:35)
    at b._error (mini-8bf3efc….js:35)
    at b.error (mini-8bf3efc….js:35)
    at XMLHttpRequest.n (mini-8bf3efc….js:19)
    at ZoneDelegate.invokeTask (zone-2222385….js:356)
    at Object.onInvokeTask (mini-8bf3efc….js:26)
    at ZoneDelegate.invokeTask (zone-2222385….js:355)

**Comment by nickplesha** [comment]
@EwenH Thanks for reporting this and sorry for your login trouble. At that time there was an error with logging in through the login form. Can you try logging in now? It should be possible and at the very least you should get feedback if the attempt was unsuccessful instead of a frozen form with rotating gif.

**Comment by EwenH** [comment]
Thank you Nick - It's working correctly
