### ISSUE TITLE
Manipulating previously uploaded trips - Please move the info box that is centered 

### ISSUE THREAD

**Issue by EwenH** [mapillary/mapillary_issues#2445]
### Basic information
* Platform: Windows 10 on laptop
* Version:  Current Web version
* System/Browser: Chrome 55

### Steps to reproduce behavior

 1. Open the map and zoom into a previously uploaded segment
 2. Edit this segment and start dragging a point to re-align it
 3. Map centres by itself and you can not drop the pin at the position required

### Expected behavior
That during editing, the pages does not auto centre and/or the info box with the lat lng etc, is moved to the top right hand corner so you can complete the move
...

### Actual behavior
The map auto corrects and recentres as soon as you click a pin to move and that you can't drop the pin on the infobox where you had hoped to
...

### Additional information
I think I have found a solution by holding the mouse click down but it is not 100% and certainly not intuitive or easy to use.

**Comment by nickplesha** [comment]
We have turned off the map centering when dragging images so it should now be easier to edit image positions.
