### ISSUE TITLE
Ability to lock direction in iOS app

### ISSUE THREAD

**Issue by nicholas-l** [mapillary/mapillary_issues#2447]
### Basic information
* Platform: `iOS`
* Version: `4.6.4` 

Ability to lock the direction to forward like in the Android App however this seems to be missing in the iOS version.

**Comment by millenbop** [comment]
We are currently redoing the camera UI/UX and it will include new features, like the one above. You will be able to lock to any direction.

**Comment by millenbop** [comment]
This was released last week, closing.
