### ISSUE TITLE
Exits out of camera mode, will not resume pictures

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2450]
### Basic information
* Platform: Android 6.0.1 & 5.0
* Version: Mapillary 3.24 and older

### Steps to reproduce behavior

 1.  Begin taking image sequences
 2.  For unknown reasons, from time to time, Mapillary will exit out of camera mode.  If I go back in, it will either hang for a long time before exiting out again, or it might display the message ERROR_CAMERA_IN_USE.  On a few occasions, I have caught the message "Lost connection to camera" when it exits out of camera mode.
 3.  Very intermittent, but also very very annoying.

### Additional information

Only seems to happen when Camera2 API is enabled.  Have not had it happen (yet) with that disabled.  Toggling Camera2 API off then back on "resolves" the problem, although this is kinda difficult to do while driving.

Happens in both distance-based and time-based sequences.

And yes, I can just leave Camera2 disabled, but my image quality is much poorer when I do that (focus problems, etc.).

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/755459/mapillary_trace.txt)

**Comment by katrinhumal** [comment]
@jfburke3 I suppose this has been resolved in later app versions? Apologies for not getting back on this when it was actual.

**Comment by jfburke3** [comment]
I'll see if I can get it to happen again using a more recent release.  I typically only do a lot of sequences on weekends, and the weather for this coming weekend looks questionable at the moment.

I will add this note, however:
I had a similar--but not identical--problem when using my S7 to take pictures for OpenStreetCam (don't worry, I'm not quitting Mapillary, I just sometimes switch to OSC when I'm in an area that I've already Mapillaryed to death).  The problem in OSC was that it crashed out of camera mode, and when I tried to go back in, it threw an error.  Even more interesting, when I tried to open the phone's native camera app, I got an error (something about server not available, didn't write it down).  So in that case it sounds like an Android background service crashed hard.  I had to reboot the phone to recover.  (Should have tried to use Mapillary before rebooting, didn't think of it at the time.)

I don't know if the OSC problem was the same thing that is happening to Mapillary or not; it might take some enhanced logging to figure that bit out.  I can state, though, that whatever is happening in Mapillary, your app is able to recover if I switch Camera2 API off then on again.  OSC has no similar function, so I can't do anything about it there.

I might want to switch to using my S5 for a while and see if I can reproduce the problem on it.  I do sometimes use both it and the S7 to shoot simultaneous sequences, one forward and one to the side, but I don't use it often enough to know if the problem happens on it, too.

**Comment by katrinhumal** [comment]
@jfburke3 thanks for this feedback! Really interesting to hear. Please keep us posted when you've had the chance to test more.

PS. I'll make sure to get the phrase `Mapillaryed to death` forwarded to our team :joy:

**Comment by jfburke3** [comment]
Happened again today.  I'll send in logs and reference this github #.

**Comment by jfburke3** [comment]
@peterneubauer, this is what I sent in the logs for today, that you e-mailed me about ("interrupted after like 120 frames").

Just some additional comments and observations:
* I was talking on the phone, but that phone call started long before I launched the Mapillary app.
* I was on a heavily-used freeway that isn't in the boondocks, and has pretty good cellular coverage.

After the crash and I verified that I couldn't resume imaging (ERROR_CAMERA_IN_USE error came up each time I went into camera mode), I tried starting the native camera app, DailyRoads Voyager, and OpenStreetCam.  Each one was able to access the camera and take pictures.  After each app, I exited, then went back to Mapillary and into camera mode.  Each time, Mapillary reported ERROR_CAMERA_IN_USE.  So whatever the problem is, it isn't actually killing the camera (or camera API?).  I eventually "fixed" the problem by going into the Mapillary app Settings and fiddling with various  setting configs (e.g., toggling distance mode off/on, changing focus mode, a few others).  I'm not sure which one fixed it because I did several before trying camera mode again, and it worked then.  (If I had to guess, I'd say it was toggling the camera focus setting, since that's the only one that seems to be Camera2 specific.  Recall that previously I was able to fix the issue by toggling Camera2 API off then on again.  If this happens again, then I'm going to start by changing the focus setting and see if that works.)

**Comment by peterneubauer** [comment]
Hi there,
the setting for forcing legacy Camera API if you have Camera2 (Android SDK
> 21) is now under Settings->Developer, you can try that, too and see if it
helps?

**Comment by Eric-FR** [comment]
I just faced the same issue yesterday (for the first time while using Mapillary for 6 months).
Device: Symphony i10
Android: 6.0
Mapillary: 3.117
Force the use of the legacy Camery API : activated.

This was the third sequence of the day with nothing special before. It stopped the acquisition with message "Lost connection to camera".

**Comment by katrinhumal** [comment]
@Eric-FR Could you please try and see if this also happens with the latest version, 3.118?

**Comment by Eric-FR** [comment]
I used v3.119 this week-end. I didn't got this error message but still have strange behaviours on Saturday. During one sequence recording "Unfortunately, Mapillary has stopped". Looking at the screenshot done at this moment, sequence recording was stopped before the crash. During a second sequence, I got a blank screen (full smartphone screen was white). After tens of second, it was back to Mapillary in acquisition mode but with acquisition stopped.

**Comment by voschix** [comment]
I am not sure if I mentioned this before:
On both my Android phones (6 and 7) I have an app by Vodafone ("Vodafone
Station ADSL e Fibra
<https://play.google.com/store/apps/details?id=eu.reply.cordless&feature>")
that does, among other things, detect other Vodafone customers' WiFi and
offers me the possibility to connect to them. When WiFi is active on my
phone and I happen to pass within the reach of one of these WLANs, the app
gets activated and shows a screen offering me to connect to the detected
WLAN. This interrupts picture taking of the Mapillary App. Picture taking
does not restart after stopping the Vodafone app or disabling the WiFi
reception on the phone.  The Mapillary app is the only app on my phone that
I caught  reacting in this way, but I have not checked systematically.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest Android app version
