### ISSUE TITLE
connecting with email address and password does not work

### ISSUE THREAD

**Issue by eppesuig** [mapillary/mapillary_issues#2451]
### Basic information
* Platform: Android, Web
* Version: Android 6.0.1
* System/Browser: firefox 52

### Steps to reproduce behavior

 1. choice to sign in with email address and password
 2. insert your credentials and press "sign in"
 3. the "sign in" button starts circling and keep circling

### Expected behavior

at some point, you should be on the main page

### Actual behavior

I just see the image circling. this happens on both android and web.

**Comment by eppesuig** [comment]
When connecting from Android, a second after pressing the "login" button, a black square with a white text appears in the lower part of the screen. The text is:
connection error: hostname in certificate didn't match: <mapillari-api.mapillary.io>!= <*.mapillary.com> OR <*.mapillary.com> OR  <mapillary.com>

see screenshot
![screenshot_20170207-155632](https://cloud.githubusercontent.com/assets/689923/22696423/3a183e28-ed4e-11e6-946b-e9fc10830d0c.png)

**Comment by EwenH** [comment]
This sounds very similar to the #2444 issue logging into on a Windows 7 machine.

**Comment by eppesuig** [comment]
Hello, I tried again a few days ago and then today. Now I may connect without problems on Android and Web.
