### ISSUE TITLE
Wrong rotation in Android app 325

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2452]
The newest beta version 325 has changed rotation on my fairphone 2 at least in the thumbnail and preview. 
I have not uploaded them till now. 

![rps20170208_092114_653](https://cloud.githubusercontent.com/assets/2410353/22728766/fd8dfcda-eddf-11e6-9d6c-562eda0e9f45.jpg)

**Comment by ArAge67** [comment]
Same here. Photos taken with my Samsung Galaxy S2 are 90 degrees rotated. Not all photos btw, got one sequence with 6 photos and only the first one is rotated the other 5 are ok. Another sequence shows all photos rotated.

**Comment by Jurkis** [comment]
Same on Honor 8.

**Comment by Jurkis** [comment]
Fixed in v.326.

**Comment by ArAge67** [comment]
What about the rotated photos, can I still use/upload them? Do I have to edit them and if yes, how?

**Comment by HolgerJeromin** [comment]
Good question. 
Fixed on my phone with new images, too

**Comment by HolgerJeromin** [comment]
I rotated them from a desktop computer (connected via USB, replaced the files on the phone) with a normal rotation programm (used gwenview on Linux, would recommend FastStone Image Viewer on Windows).
After upload they were shown as expected.

**Comment by ArAge67** [comment]
I rotated multiple photos using Faststone and that did the trick! Thanks for your solution Holger.
