### ISSUE TITLE
On current File Uploader, images in the asset directory are not referenced correctly and appear broken

### ISSUE THREAD

**Issue by EwenH** [mapillary/mapillary_issues#2453]
### Basic information
* Platform: Web
* Version: Windows 10
* System/Browser: `Chrome 55

### Steps to reproduce behavior

 1. Goto https://www.mapillary.com/app/uploader
 2. upload an image 
 3. 

### Expected behavior
The image in the grey box should render but it is broken (on all psuedo pop-up boxes)
...

### Actual behavior
The image is rendered as broken. 
...

### Additional information
The URL is https://assets/images/uploader/big-checkmark.svg which clearly is not looking at the current server.

**Comment by katrinhumal** [comment]
@EwenH apologies for getting to this so late. Could you please check if this is still an issue for you? If yes, would you be able to add some screenshots, please? Will be much appreciated.

**Comment by EwenH** [comment]
This is all good now @katrinhumal with thanks

**Comment by katrinhumal** [comment]
@EwenH that's great, thanks for checking :)
