### ISSUE TITLE
Your Mapillary photos were edited mail contains broken link

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2454]
I received an email that says "Some of your Mapillary photos were edited by [...]" It contains a link that goes to : `https://www.mapillary.com/app/edit/u-BnQa4nK7fw_qBIVPuIqw?feedItem=user-DigP2j1LaU-4GrIu1-o54g-affected_indirect_object-user-udhFs5LvHndu0IdKp8CjzA-approved-changeset-image%3A1486592439980&lat=-18.839736467403327&lng=59.13596675651161&z=3.66738872492115` This brings me to a page that looks like this:
![selectie_152](https://cloud.githubusercontent.com/assets/1449609/22780320/a1f7b656-eebe-11e6-920a-68c5b01fb416.png)

Also: the mail says: " We will review the edits to make sure they follow the Mapillary guidelines." while the changes are already reviewed and approved.

**Comment by knikel** [comment]
This has been fixed, visible soon. Thanks!
