### ISSUE TITLE
Fontsize error messages too big

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2456]
### Basic information
* Platform:  `Android` 
* Version: `4.1.2...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Every error message has a big font so reproducing is easy for instance:
![screenshot_2017-02-11-16-08-25](https://cloud.githubusercontent.com/assets/12451224/22854998/f33ffc9c-f078-11e6-8734-3215511b9829.png)

### Expected behavior

...Smaller fontsize

### Actual behavior

...

### Additional information

...

**Comment by katrinhumal** [comment]
Sorry for not getting to this earlier. The new camera screen has wiped the issue though, so closing now.
