### ISSUE TITLE
Phone tilted problem introduced since version 326

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2457]
### Basic information
* Platform: | `Android` | 
* Version: `4.1.2...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Tried to take photos but can't due to phone tilted message:
 
![screenshot_2017-02-11-16-08-33](https://cloud.githubusercontent.com/assets/12451224/22855094/526cfde0-f07a-11e6-81bb-0352a58b02a8.png)

Look at the odd 359 degrees tilt info. Tilt can't be more than +1 of -1 in this situation. Software should recognize this:

![screenshot_2017-02-11-16-08-27](https://cloud.githubusercontent.com/assets/12451224/22855163/971e254e-f07b-11e6-9d0e-c50d5d7b7fcd.png)

Btw all pausing settings in the capture tab are disabled.

**Comment by HolgerJeromin** [comment]
Same here on Fairphone 2

**Comment by jfburke3** [comment]
I have the same thing on Samsung Galaxy S7 Edge with Android 6.0.1, and Galaxy S5 with Android 5.0.

ALSO, in the lower right, the double-headed arrow keeps jumping back and forth as the red "shutter" icon appears and disappears.

**Comment by kinotus** [comment]
Same tilting error and flickering arrows with Samsung S6 on Android 6.0.1.

**Comment by HolgerJeromin** [comment]
FYI: The changelog of 327 said: fixed tilt problem.

**Comment by ArAge67** [comment]
Today I shot several new traces without any issues so indeed the tilt problem is fixed.

**Comment by katrinhumal** [comment]
Thanks to everyone for reporting and sorry for not getting back to you when it was time. If anyone experiences more tilt problems, please let us know. Closing this for now.
