### ISSUE TITLE
upload not recocnized

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2458]
### Basic information
* Platform: `iOS` 

### Steps to reproduce behavior

 1. uploaded a couple pictures from 10.Feb 2017

### Expected behavior

show beend recocnized from phone and web.

### Actual behavior

not recocnized that it's in the queue or uploaded ...

### Additional information

seems that something went wrong.
would expect to see, that it's uploaded and processing..
so.. u got the upload ?

**Comment by millenbop** [comment]
Investigating! Thanks for reporting!

**Comment by millenbop** [comment]
Thanks for reporting! There was a mismatch between app and server but it has been fixed now. We will re-harvest the photos tomorrow so you should see the uploads soon. No photos should be lost.

**Comment by millenbop** [comment]
Are your uploads available now?

**Comment by thoschu96** [comment]
hey anders,

just checked app and webpage .
all good and nothing seems to be missing.
thanks a lot

cheers
thorsten

Am 14.02.2017 um 15:44 schrieb Anders M?rtensson <notifications@github.com<mailto:notifications@github.com>>:


Are your uploads available now?

-

**Comment by millenbop** [comment]
Thanks!
