### ISSUE TITLE
Typo in upload tab

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2459]
### Basic information
* Platform:  | `Android` | 
* Version: `4.1.2.` 
* System/Browser: `...`

### Steps to reproduce behavior

 1.Upload a few photos and in the upload tab you'll see the typo 'Can' in stead of 'Cancel': 

 
![screenshot_2017-02-11-22-33-56](https://cloud.githubusercontent.com/assets/12451224/22865378/25ce5bb4-f163-11e6-9e0b-c9ab4f68a1d7.png)

**Comment by katrinhumal** [comment]
@ArAge67 Thanks for reporting! I think this should be fixed in newer releases, please let me know if you spot this again.
