### ISSUE TITLE
[web edit] keep image position constant

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#246]
sometimes in one sequence not all images are processed. There we have no street name on top on the right side. 
This is inconvenient as the image is about 1 cm higher than an processed image and the position of the UP and DOWN buttons (inside the image) is moving. 
If you write "<processing street info>" instead of the street name, the image would keep its position and mouse interaction would be easier.

**Comment by jesolem** [comment]
Still an issue?

**Comment by HolgerJeromin** [comment]
the street name is now below the image. So the button position is constant.
