### ISSUE TITLE
Wrong direction/compass on the website

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#2460]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 10 - Firefox/Chrome`

### Steps to reproduce behavior

 1. Go to this link:
https://www.mapillary.com/app/?focus=map&pKey=zpVXwaLy0NbGwmxqw6GTRQ&lat=47.087257512645266&lng=-1.2813127529269082&z=20

The picture points to 80° but the correct direction is about 370°. 
![angle1](https://cloud.githubusercontent.com/assets/8255984/22966810/20931c5e-f364-11e6-8211-34feff5fc0f2.JPG)

You can see the correct angle if you try to edit the sequence:
![angle2](https://cloud.githubusercontent.com/assets/8255984/22966822/2ccb2a16-f364-11e6-88f7-446a58867a34.JPG)

If you follow the sequence, you will see some strange behaviour with the direction jumping from one value to another.

**Comment by katrinhumal** [comment]
@Stefal thanks for reporting! At the time of noticing this, had you submitted any edits to the compass angles? Asking this to figure out if we should suspect the editing process or is it showing wrong for the originally uploaded images.

**Comment by katrinhumal** [comment]
Fixed, closing.
