### ISSUE TITLE
upload/edit GUI

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#2461]
### Basic information
* Platform: `Web`

I think the GUI for the edit and upload parts are not really good, especially the button's position. Look at these screenshots (sorry for the size) and ask a new contributor to find the exit or delete button.
![gui2](https://cloud.githubusercontent.com/assets/8255984/22967432/beb6229e-f366-11e6-98c3-86f15b629670.JPG)
![gui1](https://cloud.githubusercontent.com/assets/8255984/22967433/beb8283c-f366-11e6-97a6-78311e5bd8d7.JPG)

You should not place the buttons at each window's corners, it's not egonomic at all when you have a large screen.

**Comment by katrinhumal** [comment]
Thank you for this feedback @Stefal! We are gathering insights for both the editor and uploader to figure out what we should do to improve them. I will make sure your comments are added to the discussion.

**Comment by katrinhumal** [comment]
This has been tracked internally - you're also welcome to open a thread and discuss this further on our [forum](forum.mapillary.com). Closing here.
