### ISSUE TITLE
Photos taken in landscape position are uploaded rotated

### ISSUE THREAD

**Issue by polkillas** [mapillary/mapillary_issues#2462]
### Basic information
* Platform: `Android 5.1.1` in MIUI 8,2 (6.12.22 | Beta)
* Version: `3.26` 
* System/Browser: in Firefox & Chromium

### Steps to reproduce behavior

 1. Start app
 2. Put phone in landscape position
 3. Start a new sequence
 4. Upload sequence

### Expected behavior
Images should be in the correct landscape position.

### Actual behavior
Images are shown rotated, as in https://www.mapillary.com/app/user/polkillas?lat=40.44085175999999&lng=-3.7109710800000357&z=17&feedItem=user-XJajDbT_uUIjBGoLN4wrYg-activity-user-XJajDbT_uUIjBGoLN4wrYg-publishing_done-image%3A1486916576055&pKey=PDYy28zrounTKj6pnBhl5w&focus=photo
...

### Additional information

... 

Complete log in http://pastebin.com/FMJ4eWuP

**Comment by HolgerJeromin** [comment]
Are you sure you captured them with 326? Probably they are taken with 325 which was fixed in 326 (#2452)

**Comment by polkillas** [comment]
Well, it may be. Actually, I have taken a new sequence with the new version and the issue is not present. I think I fetched the version from the log, but I'm not really sure.

As version 327 fixes this, I'm closing the issue. Thanks!
