### ISSUE TITLE
Make the editor of traffic signs come back with this proposal

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2463]
Hi!
I'm very concerned about traffic signs and I miss the traffic signs editor, the traffic signs game, and all of that stuff.
To help come it back in a nice and renewed way I can afford other vision about traffic signs. 
I have made a proposal in OpenStreetMap that covers all traffic signs, specially destinations traffic signs.
I suggest you that have a look at (https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_traffic_signs_tagging) , and take the useful parts (if any) to make the editor and the game come back.
I hope it will be useful

**Comment by voschix** [comment]
I second this request. I miss the traffic sign editor.

**Comment by ybkuang** [comment]
@yopaseopor @voschix We are looking into the traffic sign editor internally as well. Will keep you updated!

**Comment by ryush00** [comment]
👍

**Comment by ybkuang** [comment]
This has been resolved by the recent [release](https://blog.mapillary.com/update/2017/10/12/human-in-the-loop.html) for human in the loop.
