### ISSUE TITLE
Don't blur real north photos with unknown compass reading photos

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2466]
On https://github.com/mapillary/UserGuide/wiki/Uploading
it says
```
If compass angle information is missing, it will be set to north (you can edit that later).
```
Well, wouldn't it be better to set it to "unknown", "NULL", etc.?
Why confuse real north pictures with unknown azimuth pictures?
Isn't that needlessly throwing away information?

**Comment by Thomas8122** [comment]
Actually unknown compass photos is setting to -1.

**Comment by jidanni** [comment]
Then the documentation is wrong and should be updated.
(Also I hope -1 doesn't mean 359 degrees.)

**Comment by pbb72** [comment]
It's a bit of all. A missing direction is stored as -1 in the database (which is something else than 359) and this value is also returned when using the API to retrieve image information. But graphically on the map, these photos are presented as facing north.

**Comment by jidanni** [comment]
OK I would hope there would be a footnote that says that.

**Comment by katrinhumal** [comment]
Thanks for pointing this out! I've updated our help documentation accordingly (which is now located here: https://help.mapillary.com/hc/en-us/articles/115001663165).
