### ISSUE TITLE
Double notifications for my own blur requests

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2468]
When my own blur requests to my own photos are approved, I get two notifications (in email, mobile push, and displayed on feed). I think one is because they were my requests, and the other is because they were on my photos. There should be only one; I think that was the case before the new notification feed.

![](http://i.imgur.com/13RyPHT.jpg)

**Comment by katrinhumal** [comment]
@nicolas17 this should be fixed now, can you confirm?

**Comment by nicolas17** [comment]
Yes, it's fixed!
