### ISSUE TITLE
Editor feedback

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2469]
Recently I edited a few of my traces using the web editor and I like to share some feedback:

- Everytime you select a photo point on the map the map centers the point position. That's pretty annoying.   Please don't center it or make it user selectable.

- The center box at the bottom isn't user friendly. It covers the map or the shifted point position. Put the center box at the left or right hand side of the map (not on the map).
![image](https://cloud.githubusercontent.com/assets/12451224/23335408/8289b23e-fbb5-11e6-896a-2ec599132e78.png)

- Add an option to turn photos in the right angle. Sometimes photos are upside down for instance.

- Add an option to blur or disable blur.

- Use another color for the current selected photo point. Sometimes is difficult to see which point is selected especially when points are overlapping.

**Comment by katrinhumal** [comment]
@ArAge67 thanks, this is great feedback! I'm taking this to our product team who will definitely consider it.

One comment I can address myself: the blur fixing function has a separate editor (that you access from the same place as this sequence editor) because the types of edits are intrinsically different. We don't currently plan to merge the two editors: one is for what is in the photo (items that need to be blurred or not) and the other for how photos are displayed on the map.

**Comment by kaitu** [comment]
@katrinhumal: I could make use of a better integration of the two editors, though. Actually, viewing what is on the photo can tell a lot about how the photo should be displayed on the map, and adjusted if needed.

A case I encounter often: while I use the blur editor on a 360 photo sequence, I notice that a picture is not oriented correctly. As the 360 viewer of the blur editor retains the current direction of view while navigating to the following/previous picture, it's easy to spot an image which is not aligned with the others, and that means that the direction information associated to the picture is wrong. Currently I refrain from correcting the direction, as swithing back and forth between sequence editor and blur editor would be a chore.

**Comment by katrinhumal** [comment]
Thanks for your input @kaitu! I'm afraid we don't plan to merge the two editors just now. But I will definitely mention your input.
