### ISSUE TITLE
Photo sequence edit is not accessible in Firefox

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#2470]
The button to the Photo sequence edit screen is not visible in Firefox, but in Chrome it works as expected.
Screenshot Firefox: https://s28.postimg.org/n5svh3tbx/mapillary_bug_FF.jpg
Chrome: https://s32.postimg.org/6lcttq845/mapillary_bug1.jpg

### Basic information
* Platform: Windows
* Version: `7` 
* System/Browser: `Firefox 51.0.1 64 bits`

**Comment by katrinhumal** [comment]
@ligfietser sorry for the delay in getting to this! Could you confirm whether you are still experiencing this issue? I tried on my end but all the photos I loaded had editing available as they should.  If possible, please share the link to the photo(s) where this is not working for you.

**Comment by ligfietser** [comment]
@katrinhumal  I see this bug is now solved with Firefox 52.0.1 so this issue can be closed. Thanks!

**Comment by katrinhumal** [comment]
Thanks for checking @ligfietser!
