### ISSUE TITLE
"Distance based capture" becomes disabled when capture mode is or changed to Manual in Capture screen

### ISSUE THREAD

**Issue by Jurkis** [mapillary/mapillary_issues#2473]
### Basic information
* Platform: `Android`
* Version: `Mapillary 3.28` 
* System/Browser: `Android Nougat`

### Steps to reproduce behavior

 1. Open Mapillary v. 2.38 and go to Settings/Capture and enable "Distance based capture" by sliding the button to the right.
 2. Go to Capture screen with Manual capture mode enabled or change to Manual capture mode.
 3. Go back to Settings/Capture.

### Expected behavior

"Distance based capture" remains enabled in Settings/Capture.

### Actual behavior
"Distance based capture" becomes disabled.

### Additional information
Device Honor 8 

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/810456/mapillary_trace.txt)

**Comment by echeloni2p** [comment]
Hi

why would you do distance automatic capture if you explicit choosen manual?
If it is manual, you do it all manual, no need for distance based automatic settings ,-)

echelon

**Comment by Jurkis** [comment]
Sorry, my fault - i missed one step after No 3. When i'm back to Capture screen, i see Auto is enabled (version 3.29 now), but "Distance based capture" is disabled. As a user, i remember, that i enabled "Distance based capture" previously and i expect distant based capture. A little tricky thing from the point of user. Should be good to see not only auto or manual mode but distance based or time based capture information (eg, when Auto is enabled) in Capture screen.

**Comment by katrinhumal** [comment]
@Jurkis Thanks for reporting this and sorry for the late reply. I have been trying it out and looks like this is not happening in the latest app version, 3.33 - would you be able to check whether it works as expected for you as well now?

**Comment by Jurkis** [comment]
Issue still exists for me in v.3.33.

**Comment by jfburke3** [comment]
@echeloni2p To be technical, when you're in manual capture mode, neither distance nor timed capture applies, so there shouldn't be any need to disable distance-capture (which, according to the description, automatically enables timed-capture).  What's worse, though, is that the operator isn't given any warning that this has happened.

**Comment by jfburke3** [comment]
Still happens in 3.45.

**Comment by HolgerJeromin** [comment]
Same as my  #2360

**Comment by HolgerJeromin** [comment]
#2360 was closed, so probably this can be closed, too.

**Comment by katrinhumal** [comment]
Great! Can you confirm that it behaves as you expect now?

**Comment by peterneubauer** [comment]
Thanks, closing.
