### ISSUE TITLE
No picture is taken anymore when touching anywhere on the screen

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2474]
### Basic information
* Platform: `Android` 
* Version: 3.28 
* System/Browser: `...`

### Steps to reproduce behavior

 1. start capturing
 2. touch anywhere on the screen to take a picture
 3.

### Expected behavior
a picture is taken.

### Actual behavior
nothing happens

## Additional information
checked in manual mode. Can't check in automatic mode, as the app crashes immediately.

...

**Comment by katrinhumal** [comment]
@kaitu Apologies, we've fallen a little behind with the bugs here. Can you please check if you still have this problem with 3.33?

**Comment by kaitu** [comment]
The bug with the crashes in automatic mode seems fixed, I don't experience crashes anymore in automatic mode in version 3.33.

Still, no picture is taken when touching anywhere on the screen. The only feedback I get that the screen has been touched is a flashing of the message "Manual capture" or "Automatic capture" under the capture mode setting switch.

**Comment by katrinhumal** [comment]
@kaitu it is not intended that you'd be able to take a photo by touching anywhere on the screen. In automatic mode, you can't control taking photos at all (except of course by choosing the settings of distance or time beforehand), and in manual mode you need to tap the designated button at the right.

**Comment by kaitu** [comment]
Ah, now I understand that you have deliberately dropped this feature. I imagine you had good reasons. Still hope you'll reconsider, I used to find that feature quite practical. Hitting a designated button needs more time and good screen visibility, which are both often a luxury you can't afford.

**Comment by katrinhumal** [comment]
Thanks for clarifying. I've never been a big user of the manual mode myself, so I must admit I didn't even remember this used to be a function - definitely must be a while?!

**Comment by kaitu** [comment]
The tap anywhere on the screen to immediately take a picture used to work both in manual and in automatic mode. I opened this issue as soon as I noticed this feature was missing in the current version. Don't remember exactly when it was introduced, I guess Peter might be able to tell more #693

**Comment by katrinhumal** [comment]
I see! Yes, that seems to have been before I personally ever discovered Mapillary. :) I'm passing on this feedback for sure. Closing the issue for the related crash bug is fixed.
