### ISSUE TITLE
Same image data in two different photos

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2475]
### Basic information
* Platform: `Android`
* Version: `3.28` 
* System/Browser: `Galaxy S7, Android 7`

While reviewing blurs on a sequence I noticed two photos in a sequence have identical image data in them even though the EXIF data is not the same and they are shown at slightly different positions on the map. The two images are:
[QFP1Z_DFztjj8uNP8siJWQ](https://www.mapillary.com/app/?pKey=QFP1Z_DFztjj8uNP8siJWQ&focus=photo)
and 3 steps forward in the sequence: 
[AR62nGDD0Ss_mcW3R7Nqjw](https://www.mapillary.com/app/?pKey=AR62nGDD0Ss_mcW3R7Nqjw&focus=photo)

The EXIF timestamps are 7 seconds apart  and the location and other camera tags (lighting, shutter, etc) are all different. There don't seem to be any pictures stacked on top of each other on the map (which I would expect if a picture got uploaded twice somehow) so it seems to me like the image data from the first image somehow overwrote the image data from the second image. 

I did delete some blurry photos before uploading so the problem could be in the review/delete part of the app or during upload. I suppose it could also be a server-side problem. But since I am signed up for the beta app in the app store, that is my first suspect.

**Comment by katrinhumal** [comment]
@ToeBee This will probably be quite hard to reproduce but perhaps we can still take a look at the particular case. If you have a great Android developer to throw our way then that would considerably speed up the process ;)

**Comment by kaitu** [comment]
possibly related to #273

**Comment by ToeBee** [comment]
I used the app again while walking to SOTM-US this weekend and this happened again.

See this image: 
https://www.mapillary.com/app/?pKey=8Gke2-fdZN5Wvse8SJYhkw&focus=photo  
Then step forward 3 images and you will see the same image in another location: 
https://www.mapillary.com/app/?pKey=ArqB8_k9z6m9bIA99Xlc0Q&focus=photo

They are in different locations but have the same image data.

**Comment by katrinhumal** [comment]
@ToeBee thanks for reporting! Asking @ovivoda to take a look.

**Comment by ToeBee** [comment]
I am beginning to suspect a race condition in the Android app upload code. It happened several times in a single sequence and the duplicated photos are always 3 steps away from each other. I have the app set to use 3 upload threads. Coincidence?

https://www.mapillary.com/app/?pKey=FizBDlP75zy9TniBgH8Szw&focus=photo
3 steps forward:
https://www.mapillary.com/app/?pKey=8NzTABEzAb-SJhNqrhL9Dw&focus=photo

https://www.mapillary.com/app/?pKey=4TCrbYURHZWmp5Nha2yEHw&focus=photo
3 steps forward:
https://www.mapillary.com/app/?pKey=vmAY6O3XZqkI73Jb6GmcSg&focus=photo

https://www.mapillary.com/app/?pKey=k06I9j4NChNjsHyONVoGQA&focus=photo
3 steps forward:
https://www.mapillary.com/app/?pKey=ZFFq4hYJVTD3mLjScwb16w&focus=photo

**Comment by ToeBee** [comment]
Well maybe it **is** just a coincidence. I changed the app to use 4 threads and my last upload still has duplicated photos 3 steps apart:

https://www.mapillary.com/app/?pKey=iic4JWRsKznwq13bDlnbBw&focus=photo
and
https://www.mapillary.com/app/?pKey=L9JNap5dptKhHc037ckmbw&focus=photo

**Comment by ToeBee** [comment]
Another two in a single sequence (uploaded with 3 threads):

https://www.mapillary.com/app/?pKey=0u0qIlVxODzscLk_5xQxmw&focus=photo
and
https://www.mapillary.com/app/?pKey=fx-FRwA001WAJv1ODSF__Q&focus=photo

https://www.mapillary.com/app/?pKey=kM4q72CGMJkvbmWQnRMPYw&focus=photo
and 
https://www.mapillary.com/app/?pKey=UFXMtqbKfuddfEm5ksGWGQ&focus=photo

**Comment by ToeBee** [comment]
Still happening. In fact, almost every sequence I upload using the app is affected. 

I don't see why this would be happening to just me. I'm running the app on a stock Galaxy S7. I suspect it may be happening to others but since most people don't blur review their pictures as much as I do, they don't notice. And even if you do blur review it's hard to spot. Usually I notice because the viewer does a zoom backwards move when it encounters this even though I was moving forward.

It might be worth extracting image data checksums (not including EXIF data because that is different) or something for a few thousand sequences to see how common it might be.

This sequence got hit **hard**:

https://www.mapillary.com/app/?pKey=CHsL8tZQg0gZLmVkz2ifuw&focus=photo
and
https://www.mapillary.com/app/?pKey=5O6FKPgYKe5KM3Z3KUbgtw&focus=photo

https://www.mapillary.com/app/pKey=8SaXgvP9M7d-sRwDU_egIA&focus=photo
and
https://www.mapillary.com/app/?pKey=BIafJeCZkLndYfb1WqU_ag&focus=photo

https://www.mapillary.com/app/?pKey=6xn3yYN5Gq4oNg5Ew64VVA&focus=photo
and
https://www.mapillary.com/app/?pKey=EvYlfQYXwp4nRlpc5naYuA&focus=photo

https://www.mapillary.com/app/?pKey=m-PFhSBL_ftkbw6pX8Zwfg&focus=photo
and
https://www.mapillary.com/app/?pKey=BzOAlaftkA-1HMSe8zFHWg&focus=photo


Another sequence from the same day:

https://www.mapillary.com/app/?pKey=MfskrZLJmqPlpU7vP20spw&focus=photo
and 
https://www.mapillary.com/app/?pKey=EOoh4D02JwdV9dTi46hdwg&focus=photo

https://www.mapillary.com/app/?pKey=PCv7E88zSvG4iaAzuxOeeg&focus=photo
and
https://www.mapillary.com/app/?pKey=dH_2gPElIxKQObqirgMOuA&focus=photo

https://www.mapillary.com/app/?pKey=wv1w029RT21YFtheuVamlg&focus=photo
and
https://www.mapillary.com/app/?pKey=R1z_PJcfoPI2lLN8BZ9dJQ&focus=photo

https://www.mapillary.com/app/?pKey=am5mG6y8x7wtkjIzuLWieA&focus=photo
and
https://www.mapillary.com/app/?pKey=QhpPPr4865H0C0CxmJLUKg&focus=photo

https://www.mapillary.com/app/?pKey=qMiKy-dy5ywFhwcZddqQZg&focus=photo
and
https://www.mapillary.com/app/?pKey=9P1f8Nys2Qr2y8hUi9_3wg&focus=photo

**Comment by nicolas17** [comment]
@ovivoda does the Android app work like the iOS app, merging EXIF data into photos during upload rather than during capture?

**Comment by ToeBee** [comment]
Today I learned something new about this problem. I saw a duplicated picture on my phone before uploading. This means it is a problem in the app and is happening as the pictures are being taken. It is not in the upload process or on the server. I am running the Android app. I also noticed several out of order pictures in the sequence. The timestamp increments as expected on each file name but some were clearly taken 5+ seconds before the timestamp in the file name would indicate. So it seems like this might be some kind of threading problem in the app when it goes to save out the files from the camera. I am saving photos to my external SD card if that makes a difference. I managed to snag the files off of the SD card before uploading. I zipped up the directory on my SD card. I will get a link to the zip file via another channel.

**Comment by katrinhumal** [comment]
@ToeBee thanks, got the email and additional details! @ovivoda heads up, passing those to you.

**Comment by annafock** [comment]
Hi @ToeBee, 
do you still use version 3.28 of the app? We were not able to reproduce this issue on the current version (3.125). Could you please update your update to the latest version and see if the problem remains? If it does, please notify us again and we'll investigate it further.

**Comment by ToeBee** [comment]
When was 3.125 pushed to the Google Play store? I let my phone keep itself up to date so it should generally be running the latest. The last time this problem happened to me was May 10th. I'm pretty sure it happens literally every time I use the app. I see I am running 3.126 right now. I'll try again soon and report back.

**Comment by annafock** [comment]
@ToeBee 3.125 was push on May 10th and version 3.126 on May 15th, so your phones automatic update seems to have been working. Thanks a lot for checking it out another round.

**Comment by ToeBee** [comment]
Update: I just emailed a new sequence with duplications and logs to your support email

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
