### ISSUE TITLE
Cannot login via email on Android 

### ISSUE THREAD

**Issue by Zverik** [mapillary/mapillary_issues#2476]
Entering my login and password, button, then app hangs. When pressing back, displays a json error. Will add a screen later.

### Basic information
* Platform: `Android`
* Version: `3.27` 
* Connection: 3G modem plugged into a TP-Link router

### Steps to reproduce behavior

 1. Press "Sign In"
 2. Press "With E-Mail"
 3. Enter login and password
 4. Press "Sign In"

### Expected behavior

The app is logged in and the profile is displayed

### Actual behavior

A spinner spins indefinitely, nothing happens. When I press "Back", an error message is displayed for a second.

See a screenshot of that message below.

**Comment by peterneubauer** [comment]
Yes thanks. Still not working?

**Comment by Zverik** [comment]
Just logged in with my work's wi-fi. The issue was with a 3G. It definitely had a connection, since I tested it elsewhere. Here is the screenshot:
![screenshot_2017-03-02-17-08-21](https://cloud.githubusercontent.com/assets/766031/23608118/4412f65a-0281-11e7-90d3-c189a4a1a48d.png)

**Comment by jfburke3** [comment]
Now it's not working for me on my Galaxy S5 with the 3.40 beta release, Android 5.0.  (Works fine on my S7.)  I have the same problem described above except I don't get the JSON error message (not yet, anyway).

Background info:  I mainly use my S7 to shoot images, but sometimes I'll switch to the S5, or use both so I can take pics ahead and to the side.  Was going to try that today, except the app wouldn't start (kept crashing).  I eventually uninstalled it and reinstalled it, and that's when I discovered the login problem.

I will note that OpenStreetCam on the same phone had a crash-on-launch problem, too, a few weeks ago, but an uninstall/reinstall fixed it there.

**Comment by jfburke3** [comment]
And I've tried both on WiFi and the cell network.

**Comment by peterneubauer** [comment]
Still not working?

**Comment by jfburke3** [comment]
Unfortunately.  I just installed the new 3.43 beta, and still failing then.  Unlike the earlier version where it would stay on the logon screen with the swirly "please wait" thing, this version seems to be crashing after several seconds of trying.

I don't suppose a special build with login logging would help?  It doesn't seem to be create a log anywhere that I can find.

**Comment by peterneubauer** [comment]
Hi there,
I just tried logging in with OSM, Google and via email / pwd, all worming,
albeit there is a crash between which I will investigate.

Can you log in via email and password on the site?

**Comment by jfburke3** [comment]
Yes, that works fine.

**Comment by jfburke3** [comment]
Still not working on my Galaxy S5 (Android 5.0) :-( even after upgrading to 3.45.

As additional steps, I did this:
Uninstalled the app, searched the phone for anything with "mapillary" in it (didn't find anything), powered off the phone for a few minutes, booted back up, reinstalled the app from the Play store, and tried to log in via e-mail again, which still failed.  I noted that I was connected to my home wifi's 5GHz radio, so I switched to the 2.4GHz radio and tried again, which still failed.  Next, I disabled wifi and let the phone connect to the cell network (4G).  After a minute, I tried to log in via e-mail again, and it failed again.

I'll note that the failure modes are not identical, and there doesn't seem to be a strong correlation between how it fails and how I'm connected.  Sometimes it will give me the Android crash dialog fairly quickly and offer to let me report it (which I have done a few times), sometimes it will sit on the "Trying to log you in ..." message for a looooooooooooonnnnnnnnnnnnnnnnngggggggggggggggg time before I get the Android crash message, and sometimes it sits on that "Trying" box for so long that I eventually give up and use system tools to kill the app.

I do not appear to have any problems on my Galaxy S7 or my old S4.

**Comment by jfburke3** [comment]
@peterneubauer Hey, it works now!  I just installed 3.46-SNAPSHOT on the S5 and tried to log in with it, and...I'm in!

**Comment by peterneubauer** [comment]
Awesome, make sure to update via Play to the latest beta version, 3.47 so
you don't get the snapshot bugs.

Otherwise, happy mapping, more test vesions coming soon!

/peter

**Comment by peterneubauer** [comment]
If this still is an issue, please comment, closing.
