### ISSUE TITLE
Re/view Pictures not working on IOS

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2477]
### Basic information
* Platform: `iOS` 
* Version: `10.2.1` 

### Steps to reproduce behavior

 1. Go to the HomeScreen
 2. Tab on a Sequence you uploaded
 3. Tab on a Picture from the Sequence you uploaded

### Expected behavior

The Splitscreen openes and Shows you the MAP and the Picture

### Actual behavior

The Splitscreen openes, Position for the Picture is staying Black and the MAP is not updating

### Additional information

...

**Comment by geowOSM** [comment]
I remember I experienced this before, but with v4.6.8 It works like a charm and flawlessly.

**Comment by katrinhumal** [comment]
@thoschu96 thanks for reporting! Would you mind checking if you still experience this with the current app version, 4.6.9?

**Comment by thoschu96** [comment]
Hi


yep. still the same with the current Version


Cheers


________________________________
Von: katrinhumal <notifications@github.com>
Gesendet: Dienstag, 21. März 2017 13:39
An: mapillary/mapillary_issues
Cc: Schulz, Thorsten; Mention
Betreff: Re: [mapillary/mapillary_issues] Re/view Pictures not working on IOS (#2477)


@thoschu96<https://github.com/thoschu96> thanks for reporting! Would you mind checking if you still experience this with the current app version, 4.6.9?

-

**Comment by millenbop** [comment]
Could you try deleting the app and installing it again? Make sure you upload any photos you might have before deleting it.

**Comment by thoschu96** [comment]
hey

removing and reinstalling worked well.
better for the future if there was an reset to default button . so u dont have to upload first the pictures u have in the queue.

thx
thorsten

Am 21.03.2017 um 14:37 schrieb Anders M?rtensson <notifications@github.com<mailto:notifications@github.com>>:


Could you try deleting the app and installing it again? Make sure you upload any photos you might have before deleting it.

-

**Comment by katrinhumal** [comment]
@thoschu96 thanks for the feedback and glad it is working for you now!
