### ISSUE TITLE
iOS Enhancement EXIF tags: elevation

### ISSUE THREAD

**Issue by geowOSM** [mapillary/mapillary_issues#2479]
### Basic information
* Platform: `iOS`
* Version: `10.2.1` 
* Mapillary `4.6.8`

Please consider adding GPS-elevation to the EXIF tags of the saved images. Thanks!

**Comment by katrinhumal** [comment]
@geowOSM Thanks for the suggestion, I will take it to the product team. Can you comment briefly why you would want this?

**Comment by geowOSM** [comment]
Sure, living and working well above sea level, I consider elevation an important feature. ;) Crucial in addition to lat/lon and heading data. If a device records gps elevation in the first place, it should be kept and saved. At the moment it is set to '0'.

Thanks!

**Comment by katrinhumal** [comment]
Thank you for specifying @geowOSM - I'll add these comments to give more context to your request.

**Comment by geowOSM** [comment]
Thanks, you all are doing a great job at Mapillary!
