### ISSUE TITLE
webapp : Cancel a blur edit cancel all the other edits

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#248]
If i edit some photos location & direction, then click "edit blurring", but click cancel, it removes all my corrections.

btw : the logo you're using for the photo direction is the exact opposite of what is intuitive :
Look at this 'V', the bottom is where I am, and the top, where I'm looking at. Mapillary use the opposite.

**Comment by de-vries** [comment]
Duplicate of https://github.com/mapillary/mapillary_issues/issues/366 and https://github.com/mapillary/mapillary_issues/issues/756

**Comment by gyllen** [comment]
Fixed with new blur interface in viewer
