### ISSUE TITLE
Being back photo sequence count  (capture screen)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2480]
### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.30/3.31
* System/Browser: SamsungGalaxy Edge S7

On the redesigned capture screen, the count of photos in the current sequence is no longer shown. Please bring it back--it was very useful.

**Comment by katrinhumal** [comment]
@jfburke3 Thanks for the feedback! We do intend to bring it back, stay tuned for next updates.

**Comment by jfburke3** [comment]
It seems to be back in some of the recent releases.  Not sure if that's permanent enough to close this ticket, or if you'd rather wait.

**Comment by katrinhumal** [comment]
It's meant to be permanent so thanks for pointing this out! We're making efforts to get back on top of all the tickets here in mapillary_issues but it will probably take a while until we manage to follow up on everything that is appropriate to close. So your help is much appreciated :)
