### ISSUE TITLE
Change map layer on the web uploader

### ISSUE THREAD

**Issue by ArtificialTruth** [mapillary/mapillary_issues#2482]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome, Windows 10`

### Steps to reproduce behavior

 1. Go to web upload page https://www.mapillary.com/app/uploader
 2. Try to click the map layer icon 
 3. Nothing happens

### Expected behavior
That you can change the map layer like on https://www.mapillary.com/app/user/
..

![image](https://cloud.githubusercontent.com/assets/3297866/23622749/2129c262-02a0-11e7-8db7-f76024fbbb91.png)

**Comment by nickplesha** [comment]
@ArtificialTruth Switching map layer is working in uploader now, thanks for reporting.

**Comment by ArtificialTruth** [comment]
My pleasure!
