### ISSUE TITLE
Clicking on commenter's profile in home won't display user profile

### ISSUE THREAD

**Issue by maxxer** [mapillary/mapillary_issues#2483]
### Basic information
* Platform: `Android`
* Version: `331` 
* System/Browser: `Android7 MIUI`

### Steps to reproduce behavior

 1. Receive a comment notification
 2. Click on the commenter's icon

### Expected behavior

Commenter's profile is shown

### Actual behavior

Placeholder profile is shown

**Comment by katrinhumal** [comment]
@maxxer same for this, well-spotted and we'll make sure to fix.

**Comment by katrinhumal** [comment]
This has been fixed.
