### ISSUE TITLE
Clicking on user name from a comment shows partial profile

### ISSUE THREAD

**Issue by maxxer** [mapillary/mapillary_issues#2484]
### Basic information
* Platform: `Android` 
* Version: `331` 
* System/Browser: `Android7`

### Steps to reproduce behavior

 1. Receive a comment
 2. Click on commenter's username

### Expected behavior

Full user profile is shown

### Actual behavior

The profile is shown but:
1. user avatar is missing
1. user email is not the profile one but self email

**Comment by katrinhumal** [comment]
Good catch @maxxer. This seems to have slipped into the latest versions as well, so we'll make sure to fix.

**Comment by katrinhumal** [comment]
This has been fixed.
