### ISSUE TITLE
Autocapture shooting 5-6 photos per second

### ISSUE THREAD

**Issue by Jurkis** [mapillary/mapillary_issues#2485]
### Basic information
* Platform:  `Android 7.0`
* Version: `3.31` 
* System/Browser: `Honor 8, `

### Steps to reproduce behavior

 1. Enable Distance based autocapture.
 2. Choose Autocapture mode.
 3. Distance autocapture: 5m (or other).
 4. Start shooting.

### Expected behavior

Photo is captured every 5 meters.

### Actual behavior

Photo is captured every 0.2 second or something like this (about 5-6 photos per second) even i don't move. And i get ERROR_INTERRUPTED when stopping shooting.

### Additional information

... 
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/826874/mapillary_trace.txt)

**Comment by maxxer** [comment]
Same behavior, Xiaomi Mi5

**Comment by maxxer** [comment]
Seems fixed in latest 333

**Comment by Jurkis** [comment]
Not for me.

**Comment by symz** [comment]
Try v3.33 - it's fixed for me. Had this problem in v3.32 (LG Swift G, LG G4).

**Comment by Jurkis** [comment]
v3.33 not working as i told before. I'll try to reinstall.

**Comment by katrinhumal** [comment]
@jurkis have you had the chance to try again after reinstall?

**Comment by Jurkis** [comment]
Yes i had. Unfortunately, reinstalling did not resolve the problem.

**Comment by Jurkis** [comment]
I think i found the reason why it's happening. 
The error occurs if "Use Google Mobile Services" is **disabled**.

**Comment by katrinhumal** [comment]
Thanks for testing further @Jurkis - we'll be looking into it.

**Comment by peterneubauer** [comment]
So @Jurkis with enabling, things are working out now?

**Comment by Jurkis** [comment]
Now it work fine (both with  "Use Google Mobile Services" disabled or  "Use Google Mobile Services" inabled.) in version 3.36.
