### ISSUE TITLE
Process and services running in background

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#2486]
### Basic information
* Platform: `Android 6.0`
* Version: `3.32` 
* System: `Motorola Moto G 2`

### Expected behavior
No processes or services running in background.

### Actual behavior
There is one process with 2 services running in background.

### Additional information
It seems that after the last update (version `3.32`), Mapillary keeps running in background, even if I don't run it.

It's possible to see the `Mapillary (app.mappilary)` process together with 2 services (`TelemetryService` and `FusedLocationProviderService`)

![](https://cloud.githubusercontent.com/assets/982338/23752723/4a62561e-04b5-11e7-8a64-11a0259dd8e4.png)

**Comment by peterneubauer** [comment]
So, this is a change back from where the background sync service was not running at all times. This has to do with some of the libraries we use that can't receive IPC intents from services if they run in their own processes. Nothing we can do right now to change it, but maybe later.
