### ISSUE TITLE
"Show my coverage only" button not working 

### ISSUE THREAD

**Issue by ArtificialTruth** [mapillary/mapillary_issues#2491]
### Basic information
* Platform: `Web`
* System/Browser: `Windows 10 64 bit - Chrome`

### Expected behavior
When looking at the map under https://www.mapillary.com/app/user/... ticking the "Show my coverage only" button should show my coverage. 

### Actual behavior
Instead it removes every feature from the map, and shows nothing (except the satellite/map).

### Additional information
Looking here: https://www.mapillary.com/app/?lat=55.723850911753004&lng=12.381823066975016&z=11.768683294846129

The button:

![image](https://cloud.githubusercontent.com/assets/3297866/23835375/67f47014-0766-11e7-94b4-eecb2e6c1e71.png)

**Comment by ptpt** [comment]
Thanks for reporting. At low levels some user's coverage is possible to be missing because of limitation of static vector tiles. Could you show me the link to your profile page so I can check if this is related to https://github.com/mapillary/mapillary_issues/issues/2150

**Comment by ArtificialTruth** [comment]
app/user/mappingproc

**Comment by ptpt** [comment]
Thanks. It seems to be a new issue on our tiles. Investigating...

**Comment by ptpt** [comment]
It should work now. Closing.

**Comment by ArtificialTruth** [comment]
Thank you! :)
