### ISSUE TITLE
Upload failed on Windos Phone app

### ISSUE THREAD

**Issue by ic3d** [mapillary/mapillary_issues#2492]
### Basic information
* Platform: Windows Phone
* Version: 1.2.0.0.
 * System/Browser: Windows Phone 8.1 update 2 on Nokia 640 LTE

### Steps to reproduce behavior

 1. Upload images: select them grom the SD card 
 2. Press "start" to start uploading 
 3. Error (see attachment)

### Expected behavior

Photo uploaded.

### Actual behavior

Upload stopped, no photos uploaded.

### Additional information

None (but you can ask me anything :-) ).
![wp_ss_20170313_0001](https://cloud.githubusercontent.com/assets/6413651/23852623/126b0896-07e9-11e7-9fed-9193a0e5626a.png)

**Comment by katrinhumal** [comment]
@ic3d The Windows app is actually developed by one of our community members ([https://github.com/mapillary/mapillary_windows_phone](https://github.com/mapillary/mapillary_windows_phone)). Unfortunately we don't provide support for it in-house. You could try contacting the author for troubleshooting.

Meanwhile, you could copy the photos to your computer and use our web uploader to upload: https://www.mapillary.com/app/uploader/
