### ISSUE TITLE
Photos added via python scripts not getting added to Finland nor Helsinki leaderboard

### ISSUE THREAD

**Issue by amahon** [mapillary/mapillary_issues#2493]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2539](https://mapillary.zendesk.com/agent/tickets/2539)
**Priority:** N/A
**Group:** Support
**Organization:** N/A
**Assignee:** Mapillary

**Original ticket description:**

<blockquote><div class="zd-comment">

<p dir="auto">I'm not sure if this issue affects anyone else as I didn't find a thread on this in GitHub so I'm approaching via email: I think I've now taken close to 100k pictures in Finland but for some reason my leaderboard stats have lingered around 40k for months now. Also for Helsinki the numbers feel much lower than I'm estimating.</p>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-03-08 at 14:15:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi Eero,</p>

<p dir="auto">Thank you for letting us know! I will take this to our developers and hope to get it fixed quickly. I'll get back to you!</p>

<p dir="auto">Best,
<br>Katrin</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-03-10 at 14:17:*

<blockquote><div class="zd-comment"><p dir="auto"><a href="https://github.com/mapillary/mapillary_elva/issues/1619" rel="nofollow noreferrer" target="_blank">https://github.com/mapillary/mapillary_elva/issues/1619</a></p></div></blockquote>

**Comment by katrinhumal** [comment]
Closing as tracked elsewhere
