### ISSUE TITLE
could you delete some sequences (delete via edit doesn't work)

### ISSUE THREAD

**Issue by amahon** [mapillary/mapillary_issues#2494]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2200](https://mapillary.zendesk.com/agent/tickets/2200)
**Priority:** N/A
**Group:** Support
**Organization:** N/A
**Assignee:** Mapillary

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">Hello, I tried a couple of times to delete some sequences which I uploaded (micmin1972), but they never are removed.</p>

<p dir="auto">Can you remove the following three sequences (because the gps eror is not acceptable for me, and/or because of too many blurry images):</p>

<p dir="auto">8HUvrA85xkXovSn2Wuq21A
<br>OsWBQu51yXRuAFNE_wKwGg
<br>2RyEqdfL2GYltTN6pGiHMg</p>

<p dir="auto">Thanks</p>

<p dir="auto">Michiel</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-09 at 18:17:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi Michiel! When did you delete these sequences? </p>

<p dir="auto">I tried to go and delete them myself right now, but couldn't find them. There's a bit of delay from requesting a deletion and getting the deletions processed. Could you please go back and see if they're gone on your end?</p>

<p dir="auto">It would be great with a quick word back to know if they're deleted!</p>

<p dir="auto">Best,
<br>Madelen</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Michiel Minderhoud on 2017-01-10 at 09:50:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi, I tried to delete them several times in december, and last week. They are still visible today. Note these are sequence id's and not picture id's.</p>

<p dir="auto">Michiel</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-11 at 19:52:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi Michiel! I've just requested these sequences to be deleted. The full deletion should be processed within the next 24 hours (probably much sooner than that).</p>

<p dir="auto">I'd love to get a quick word back that the images look deleted on your end too!</p>

<p dir="auto">Best,
<br>Madelen</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Michiel Minderhoud on 2017-01-16 at 13:26:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi,</p>

<p dir="auto">I see two sequences are disappeared, but still 1 sequence is visible (8HUvrA85xkXovSn2Wuq21A). Example file of the sequence to be deleted:</p>

<p dir="auto"><a href="https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ" rel="nofollow noreferrer" target="_blank">https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ</a></p>

<p dir="auto">And one additional question: in my 'Feed' it is indicated I have 14 edits being processed (and this value is never reducing), this can not be true I think. Btw, the new layout of the Feed is an improvement.</p>

<p dir="auto">Michiel</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-16 at 17:24:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi there! I went in and deleted the last sequence for you. It should be gone within the next couple of hours. </p>

<p dir="auto">We're so happy you like the new feed! We're still tweaking the feed and there might be a couple of bugs/delays in the first version. I'll check in with you on Wednesday to see if you're still experiencing this.</p>

<p dir="auto">Thanks for your patience.
<br>Madelen</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-18 at 20:47:*

<blockquote><div class="zd-comment"><p dir="auto">Hey, did you get this? I'd love to get a quick word back!</p></div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-23 at 18:41:*

<blockquote><div class="zd-comment"><p dir="auto">Hi there! I'm not meaning to spam you but it would be great with a quick word back if this resolved your problem! :)</p></div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Michiel Minderhoud on 2017-01-24 at 09:16:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi, only one issue left: the last sequence is still on the map although the pictures are removed.
<br>So <a href="https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ" rel="nofollow noreferrer" target="_blank">https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ</a> does not show any image anymore, but the sequence is still there. When will it disappear?</p>

<p dir="auto">And I like to point you at two additional bugs in the webinterface in my profile:
<br>- the amount of pending edits in the "Feed" is still at 14 , and never reduces. (The counter increases temporary when I do a new edit, but never goes to zero)</p>

<p dir="auto">Secondly, in the 'upload' tab the upper two sequences always appear on top, and do not chronologicly disappear in the list as it should. So the picture with the windmill is on top since november 2016. I think a correct date is missing?</p>

<p dir="auto">thanks, Michiel</p>
</div></blockquote>

#### Attachments

* [image.png](https://mapillary.zendesk.com/attachments/token/RxFNVBBny4MU2GzNEfmnIg7pE/?name=image.png)
* [image.png](https://mapillary.zendesk.com/attachments/token/XHJhDGGpujTNUv0POGaXlr4Bs/?name=image.png)

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-25 at 19:02:*

<blockquote><div class="zd-comment">
<p dir="auto">Michiel!</p>

<p dir="auto">When I follow this link: <a href="https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ" rel="nofollow noreferrer" target="_blank">https://www.mapillary.com/app/user/micmin1972?lat=51.96860259999997&amp;lng=4.502196369999979&amp;z=17&amp;pKey=YaQkNv2dVy0euYP0o-fmuQ</a> I get this (see attached screenshot).
<br>Can you still see it? </p>

<p dir="auto">I've added both of the bugs you reported and will get back to you if we need to ask some follow-up questions. We've just released this feed and we're still fixing a couple of bugs. Appreciate your feedback a lot. Keep it coming!</p>

<p dir="auto">Madelen</p>
</div></blockquote>

#### Attachments

* [Screen Shot 2017-01-25 at 1.46.01 PM.png](https://mapillary.zendesk.com/attachments/token/LSLipvlypAD0xrZW2APpvQcUT/?name=Screen+Shot+2017-01-25+at+1.46.01+PM.png)

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-25 at 19:03:*

<blockquote><div class="zd-comment"><p dir="auto"><a href="https://github.com/mapillary/mapillary_elva/issues/1362" rel="nofollow noreferrer" target="_blank">https://github.com/mapillary/mapillary_elva/issues/1362</a>
<br><a href="https://github.com/mapillary/mapillary_elva/issues/1361" rel="nofollow noreferrer" target="_blank">https://github.com/mapillary/mapillary_elva/issues/1361</a></p></div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Michiel Minderhoud on 2017-01-25 at 22:14:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi, yes I see the same as you show in the screenshot. But the 'deleted' sequence (that crazy green line covering houses and water due to bad gps) is still visible also on your screenshot. Note: even the thumbnails can be viewed when hoovering over a green dot.</p>

<p dir="auto">Michiel</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-27 at 17:10:*

<blockquote><div class="zd-comment"><p dir="auto">Created an issue about this last thing as well: <a href="https://github.com/mapillary/mapillary_elva/issues/1378" rel="nofollow noreferrer" target="_blank">https://github.com/mapillary/mapillary_elva/issues/1378</a>
<br>K.</p></div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-27 at 20:30:*

<blockquote><div class="zd-comment">
<p dir="auto">Michiel! When it comes to the issue where you still see the traces on Mapillary.com. Could you please empty your cache in your browser and see if they're still there? Thank you for your patience with this!</p>

<p dir="auto">Madelen</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Michiel Minderhoud on 2017-01-29 at 11:38:*

<blockquote><div class="zd-comment"><p dir="auto">Hi! I can still see the traces of the mentioned sequence on Mapillary.com , with empty cache and tested on another computer.</p></div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-01-30 at 16:16:*

<blockquote><div class="zd-comment">
<p dir="auto">Thank you! We will keep on investigating this - thanks for sending me a quick update. </p>

<p dir="auto">Madelen</p>
</div></blockquote>

**Comment by amahon** [comment]
*Comment made from Zendesk by Mapillary on 2017-02-06 at 16:33:*

<blockquote><div class="zd-comment">
<p dir="auto">Hi there! I had an update from our developers that this will be solved within shortly. We need to rerender the maps after making some major updates.  This is all part of making our services better - we really appreciate that you reported this. :)</p>

<p dir="auto">Best,
<br>Madelen</p>
</div></blockquote>

**Comment by madelenarnesdotter** [comment]
@peterneubauer @amahon @gyllen I'm trying to figure out if we can help this guy or not. Can we process this manually?

**Comment by millenbop** [comment]
Umm don't we just have to approve the edits?

**Comment by millenbop** [comment]
![screen shot 2017-03-15 at 15 33 48](https://cloud.githubusercontent.com/assets/12835674/23953435/d283037a-0994-11e7-950c-d14ba467cf57.png)

**Comment by madelenarnesdotter** [comment]
@millenbop if you try to look at the sequences on the map, they are deleted. You get an error message that you can't look at them. But the traces are still there.

**Comment by millenbop** [comment]
Ok! Still we need to start approving edits, we have edits pending since November last year.

**Comment by madelenarnesdotter** [comment]
@millenbop is there any specific reason why we haven't processed these yet? Some bug in the system?

**Comment by millenbop** [comment]
Don't know, sorry. I think Peter used to do it.

**Comment by gyllen** [comment]
@katrinhumal Was locking intentional on this issue?

**Comment by katrinhumal** [comment]
@gyllen yes, this here is an accidental duplicate of the problem tracked in mapillary/mapillary_elva#1378 (it got created while trying out the Zendesk integration).
