### ISSUE TITLE
Upload progress dialog showing even if upload is completed

### ISSUE THREAD

**Issue by maxxer** [mapillary/mapillary_issues#2495]
Basic information
* Platform: `Android`
* Version: `333` 
* System/Browser: `Android7`

### Steps to reproduce behavior

 1. upload a sequence
 2. see *Upload in progress* dialog
 3. leave the phone alone uploading, even closing the app
 4. when upload is finished reopen the app
 5. go to the *Upload* tab and open a second sequence

Result: the *Upload in progress* dialog still shows up. 

![screenshot_2017-03-15-10-28-16-341_app mapillary-1489570261093](https://cloud.githubusercontent.com/assets/240201/23941798/88d916bc-096a-11e7-86f4-b8dfb221de71.jpeg)

**Comment by HolgerJeromin** [comment]
This is the same as my older #2415

**Comment by maxxer** [comment]
oups, sorry for dupe
