### ISSUE TITLE
API v3: user name in feature properties

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#2497]
### Basic information
* Platform: `Web`
* Version: `API v3` 
* System/Browser: `Firefox 50`

### Steps to reproduce behavior

 1. Call image search, for example `https://a.mapillary.com/v3/images?client_id=<CLIENT_ID>&bbox=-1.721,48.12421,-1.70733,48.12961`

### Expected behavior

Have the properties of all pictures, including user name as previous API.

### Actual behavior

The user name is not present, only data about user is its key.

### Additional information

Having the user name directly in image search result is useful, as it avoids making multiple calls to retrieve all user names for a given picture search. Was this information dropped on purpose ? Could it be re-introduced ?

**Comment by ptpt** [comment]
It's added now. https://www.mapillary.com/developer/api-documentation/#the-image-feature

Also a filter `usernames` is added for filtering images by the specified users. See https://www.mapillary.com/developer/api-documentation/#search-images

Thanks for the patience. Closing.
