### ISSUE TITLE
Dragging of folders not working anymore in Web uploader

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2498]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: 'Firefox 52.0`

### Steps to reproduce behavior

 1. Call uploader
 2. Drag a folder containing images on the uploader window
 3.

### Expected behavior
The number of images in the folder is returned

### Actual behavior
message "No photos were found in the selected files" "Try again"

![image1](https://cloud.githubusercontent.com/assets/5104672/24049364/0fa7eed0-0b2c-11e7-81e5-edf1f9f271eb.jpg)

**Comment by katrinhumal** [comment]
@kaitu would you mind trying this again? I don't manage to reproduce your error, it works just as it should for me with Firefox 52.0. So I have a small hope that it was a temporary issue.

**Comment by kaitu** [comment]
I can still reprodude the issue, in Firefox 52.0.1

**Comment by katrinhumal** [comment]
@kaitu ok, needs further investigation. I'm pulling in some help forces :)

**Comment by nickplesha** [comment]
@kaitu Thanks for bringing this to our attention. Firefox just recently added the ability to drag-and-drop folders to a web page but their implementation differs from other browsers so we will need to make some updates to the uploader to use it.

**Comment by kaitu** [comment]
I see it's working as it should now, on Firefox 52.0.2. Closing.
