### ISSUE TITLE
The world is snow white in the in screen map browser or explore feature

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2499]
Sometime Friday the Explore button's map turned "snow white".  I note that the Mapbox icon changed at the bottom of the map in addition to the color change.

* Platform: Android 6.0.1, code: Samsung SM-G550T, retail name: Samsung On5
* Version: 3.3.3

### Steps to reproduce behavior
 1. Use the in screen map explore button.

### Expected behavior
A usable map with contrast.

### Actual behavior
All the roads are white.  The traces/sequences cannot be seen.

### Work around.
I use the Chrome browser on the phone to go to https://www.mapillary.com/app/

### This is the MapBox icon that used to be on the Explore map.
![image](https://cloud.githubusercontent.com/assets/1669057/24072253/8d30c5be-0ba1-11e7-9fa0-1bb3f040553f.png)

### This is the "new" MapBox icon.  I don't know if this matters but I did notice the change.
![image](https://cloud.githubusercontent.com/assets/1669057/24072271/cc18f29c-0ba1-11e7-8267-8280ce2b2a81.png)

I poked at the new icon.  I turned off MapBox' Telemetry setting.

### Snow White!
![image](https://cloud.githubusercontent.com/assets/1669057/24072229/33d520f0-0ba1-11e7-9092-fb33c2f2323a.png)

**Comment by katrinhumal** [comment]
@drkludge Interesting - I'm not able to reproduce! Would you mind checking this again today to rule out that it was a passing hickup?

**Comment by drkludge** [comment]
@katrinhumal I checked again today.  The issue remains.  This issue is on Android 6.0.1.

**Comment by Ainali** [comment]
I have the same issue. 
Platform: Android 7.0, Samsung G935F (S7 Edge)
Version 3.3.3
![screenshot_20170322-000403](https://cloud.githubusercontent.com/assets/5566159/24174981/0f437174-0e94-11e7-8633-a997c903baa7.png)

**Comment by drkludge** [comment]
I've been experimenting with prior versions and the current 3.3.5 release from http://android-releases.mapillary.io/index.html.  The 3.3.5 release has the same problem.  I uninstalled/installed several other releases for the button issue #2481. I finally remembered to try this issue.  Release 3.2.8 does not have the issue.

**Comment by katrinhumal** [comment]
This surely needs further investigating. I only tested with my own phone (Sony Xperia Z1, Android 5.1.1) which was fine.

**Comment by drkludge** [comment]
I upgraded to 3.4.3 yesterday.  The world is no longer snow white.  There is a usable map.

**Comment by katrinhumal** [comment]
Just to wrap this up, this was related to a Mapbox bug, as it turned out.
