### ISSUE TITLE
Images sequences in Melbourne Australia appear to have been removed.

### ISSUE THREAD

**Issue by EwenH** [mapillary/mapillary_issues#2500]
### Basic information
* Platform: `Web`
* Version:  Current Version (not legacy) 
* System/Browser:  FF or Chrome

### Steps to reproduce behavior

 1. navigate to [Melbourne, Australia ](https://www.mapillary.com/app/?lat=-37.82068560820854&lng=144.95841693131615&z=14.009913449732004)
 2. You will notice that all image sequences stop around the Central Business District, however you can view the images by clicking on one earlier in the sequence

### Expected behavior
You can see parts of the Hoddle Grid (the square road sequence above the river) including Lonsdale Street
...

### Actual behavior
All sequences abort prior to entering the city
...

![oops1](https://cloud.githubusercontent.com/assets/4280493/24252153/beb97c78-1030-11e7-8694-174fa0ab9d60.png)

**Comment by HolgerJeromin** [comment]
Works here. So perhaps a temporal hickup of the vector tile serving the green dots

**Comment by katrinhumal** [comment]
@EwenH works here as well, could you please recheck on your end? I suspect (and hope) @HolgerJeromin is right.
