### ISSUE TITLE
Map view on upload screen is centered off the west coast of Africa

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2502]
### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.36-SNAPSHOT
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Go to the Upload function
 2.  Open an image sequence to upload
 3.  Press the little map icon at the lower left

### Expected behavior

Expect a map view that zooms in to where the sequence was taken

### Actual behavior

I see the ocean off the west coast of Africa, which is nowhere near where I take pictures :-)

**Comment by peterneubauer** [comment]
This should be fixed now, the app should go to the last position viewed, or the position of the image.
