### ISSUE TITLE
Missing 'username' in user statistics for Ukraine

### ISSUE THREAD

**Issue by spatialhast** [mapillary/mapillary_issues#2503]
### Basic information
* Platform: `Web`
* Version: `API v2` 
* System/Browser: `Google Chrome Google Chrome `

### Steps to reproduce behavior

 1. Call user stats in Ukraine (85633805), for example https://a.mapillary.com/v2/stats/toplist/85633805/wof?client_id=<CLIENT_ID>&limit=500

### Expected behavior

{"username":"USERNAME", "count":"COUNT"}
![image](https://cloud.githubusercontent.com/assets/3269617/24352231/6d702218-12f1-11e7-81b0-ece640500873.png)

### Actual behavior

missing 'username':
![image](https://cloud.githubusercontent.com/assets/3269617/24352247/837cf7e8-12f1-11e7-9ea9-1c9da9123003.png)
![image](https://cloud.githubusercontent.com/assets/3269617/24352264/8f71d852-12f1-11e7-9cdb-12bd8e0647f2.png)

### Additional information

...

**Comment by ptpt** [comment]
Thanks for reporting. API v2 is deprecated now. We have tracked the issue and will check back when we upgrade it to API v3.

**Comment by ptpt** [comment]
@spatialhast the leaderboard APIs have been added to API v3. The corresponding call in API v3 should be `https://a.mapillary.com/v3/leaderboard/images?iso_countries=UA&client_id=XXX` which responds as follows
```json
[                                           
  {                                         
    "image_count": 757720,                  
    "user_key": "SqUJ_UTe8_LrdnpZ5MeDzg",   
    "username": "tkukovska"                 
  },
  {
    "image_count": 333958,
    "user_key": "Y9YiPRZlQ_wP85S7h1YWFQ",
    "username": "hast"
  },
  {
    "image_count": 246590,
    "user_key": "oCpAlhBsAFW9BTOlWUygYw",
    "username": "algot"
  }
]
```

See http://www.mapillary.com/developer/api-documentation/#leaderboard
