### ISSUE TITLE
Zoomed image tiles sometimes give errors

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2504]
### Basic information
* Platform: `Web`
* System/Browser: `Linux, Firefox ESR 45.8.0`

I'm manually blurring photos in a sequence, and when I zoom, sometimes the high-resolution image tile doesn't load. I have seen error HTTP 504 (timeout) in Firefox's network info, which seems like a temporary issue, but now I'm getting error 500 on this tile:

https://d2qb1440i7l50o.cloudfront.net/H3lrQy_yzScLliBDdxuRhg/1024,1024,1024,1024/1024,1024/0/default.jpg?origin=mapillary.webgl

The response is:
```
Server Side Error: image file is truncated (7 bytes not processed) 

This is likely a permissions problem, though it's
possible that there was a problem with the source file
(/usr/local/share/images/loris/ee/f4d/725/e31/a7c/c0f/02f/400/1bf/8aa/d91/loris_cache.jpg). (500)
```

**Comment by oscarlorentzon** [comment]
Thanks for reporting @nicolas17.

The link returns the file correctly right now and zooming on that image on mapillary.com works correctly.

We had a problem with tiling of some newly uploaded images recently but this one is from February so should not have been affected.

There may be an instability in the image tiling server occasionally. We will try to figure out why.

**Comment by oscarlorentzon** [comment]
No tiling problems reported or experienced recently. Please reopen or create a new issue if a similar problem occurs.
