### ISSUE TITLE
Capture mode text shown when phone is rotated 180 degrees

### ISSUE THREAD

**Issue by Jurkis** [mapillary/mapillary_issues#2506]
### Basic information
* Platform: `Android`
* Version: `3.38` 
* System/Browser: `Honor 8, Android 7`

### Steps to reproduce behavior

 1. Go to Capture mode.
 2. Rotate phone 180 degrees.

### Expected behavior

...

### Actual behavior

Text "Automatic capture" and "Manual capture" are visible under capture mode button, overlaping each other.

### Additional information

... 

![screenshot_20170330-105728](https://cloud.githubusercontent.com/assets/8310079/24494003/6a552520-1539-11e7-8bfb-5e3770b4a7b8.png)

**Comment by katrinhumal** [comment]
@Jurkis Thanks! We'll fix this in the next releases.

**Comment by peterneubauer** [comment]
Yup, that's a bug, will fix when the high-prio ones are fixed. Thanks!

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
