### ISSUE TITLE
Web Viewer - Track Overlay disappears when switching from OpenStreetMap to Mapbox Streets

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2507]
### Basic information
* Platform:  `Web`
* System/Browser: `Windows 10` / Chrome 56.0.2924.87 or Firefox 52

### Steps to reproduce behavior

 1. switch from map layer "Mapbox Streets" to "OpenStreetMap"
 2. switch back to "Mapbox Streets"

### Expected behavior

Map is shown with the green track overlay

### Actual behavior

track overlay disappears

### Additional information

all other switches of map layer seem to be fine

**Comment by katrinhumal** [comment]
@ramapongithub Thanks for reporting! We'll look into this.

**Comment by nickplesha** [comment]
@knikel Do you maybe have some thoughts on why this would happen? When switching from `osm` to `mapbox_streets` it looks like `sprites.json` and `sprites.png` aren't loaded. All other map transitions work OK, including switching to another and back to `mapbox_streets`.

**Comment by knikel** [comment]
We had an issue with relative style paths in some map styles this should be fixed by now.

**Comment by nickplesha** [comment]
@ramapongithub This should be fixed now, thanks for reporting.
