### ISSUE TITLE
Please bring back the Camera2_API toggle setting

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2510]
### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.39

In earlier versions of the Mapillary Android app, there was a setting to allow us to toggle Camera2 API on or off.  This setting was particularly valuable to me (not sure about anyone else!), because it provided a workaround for the problem described in #2450 .  I had that problem happen again today, and only then discovered that the setting was gone.  I ended up having to reboot my phone to recover.

Where this becomes a problem (or, maybe not, if you don't care) is that the "camera crash" (not sure what else to call it) typically happens to me when I'm on road trips.  Also when I'm on road trips, I often spend a lot of time talking on the phone (LONG conversations), because...well, there's not much else to do except drive and look at cows.  While it kinda depends on who I'm talking to, most of the time I'm not going to interrupt the call to reboot my phone just so I can resume shooting sequences.  Having that setting eliminates that as an issue.

**Comment by peterneubauer** [comment]
that toggle is now (3.45+) in Settings->Developer. If eligable, Camera2 is default (you can see it in the offset screen as the camera name, but you can force Legacy in the toggle and the restart the app.

Works?

**Comment by jfburke3** [comment]
I'm...not completely sure that it works like it used to, but I need to do some more testing.
