### ISSUE TITLE
Some buildings do not show on the mapbox layer used on mapillary.com

### ISSUE THREAD

**Issue by Hjart** [mapillary/mapillary_issues#2512]
I have noticed that some buildings do not show up on the Mapbox layer used on the website.

2 examples are https://www.openstreetmap.org/way/164426642 (https://www.mapillary.com/map/im/fqm0oPYpF2KIQ1ycei8HwA) and https://www.openstreetmap.org/way/94180397 (https://www.mapillary.com/map/im/Q3AyzcCi3OKQxBvsHZIe7g).

I didn't yet figure out exactly what triggers it, but both of these buildings are fairly important and I would really like them to show up.

**Comment by katrinhumal** [comment]
@Hjart Buildings are part of the tiles in the background, the styles that Mapillary adds will include mostly markers and stuff and not building shapes. The different map styles have varying levels of details, as chosen by Mapbox. The OSM layer is probably always going to be the most detailed and up-to-date.

**Comment by Hjart** [comment]
I am aware of buildings being part of tiles and that Mapbox are responsible for the appearance of their tiles. I just wasn't sure about how to report this to Mapbox (as I think it's a bug) and thought that maybe you would know.

**Comment by katrinhumal** [comment]
@Hjart I see! Well, I think you can always just contact their support: https://www.mapbox.com/help/reporting-a-problem/#contact.
