### ISSUE TITLE
Image upload speed is not as fast as it used to be.

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2513]
### Basic information
* Platform: `Android 6.0.1, code: Samsung SM-G550T, retail name: Samsung On5`
* Version: `3.2.8 to 3.3.5` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Upload a sequence
 2.
 3.

### Expected behavior

Better upload speeds.

### Actual behavior

Three to four seconds are required for each picture in a sequence.  For example, I had a sequence of 1165 pictures this morning.  I started the upload at 09:22.  The upload finished at 10:34.  My old phone was much faster.

### Additional information

I have two things that changed in my Mapillary configuration. 
1.) My old phone died.  It was replaced with a newer phone.
2.) I used 1.4.7 because that worked best on my old phone.  I am running 3.3.5 on the new phone.
I cannot tell which of these really maters.  What I do know is that
1.) I compared an image from 2005 with a current image.  The images are the same size.
2.) The wireless networks that I used for both phones are the same.
3.) I've tried to change the thread count for the uploads.  The thread count did not help.

My workaround has been to use JOSM for the uploads especially the 9.6K upload over the weekend.  I tried using the phone for a 17K weekend sequence.  The upload did not complete overnight.

**Comment by katrinhumal** [comment]
Hi @drkludge - I think the issue here might be related to the fact that you were using such an old version of the app before. For the time being, only one thread will actually be used for upload and I believe this is what makes the difference in your case. We'll be changing that back later.

**Comment by andrewharvey** [comment]
I've noticed this as well, on the Android app. Upload speed will sit at 0 for a few seconds, then spike to 2MB/s for a second then rest back at 0 for a few seconds. I'd expect the upload to be saturated.

Parallel uploads was set to 2 threads, bumped it up to 4 threads, but I'm not sure if it's making a difference, either that or it only takes affect for the next upload, not the one in progress.

**Comment by katrinhumal** [comment]
@ovivoda do you have any insights into why this may be?

**Comment by drkludge** [comment]
I am on 3.44 now. I took 17,000 pictures on 7/4/2017. It took all night to upload the pictures. I was still on a current 3.x release when I posted this. My point was that the 1.x release is faster than the current 3.x releases including the use of threading. Moreover the picture size has remained constant.

**Comment by andrewharvey** [comment]
For me, I think it's when you have a lot of small images uploading over a high bandwidth uplink which results in long pauses between each image upload. When I tried on a lower bandwidth uplink it seemed to max out the upload constantly.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
