### ISSUE TITLE
Unexpected updates of the app make the app crash

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2516]
### Basic information
* Platform:  `Android` 
* Version: `3.44` 
* System/Browser: `Xperia Z3 compact.`

### Steps to reproduce behavior

 1.Come an update
 2.Update automatically
 3.Crash app when you try to use it

### Expected behavior
Working well the app

### Actual behavior
-Sometimes it works well
-Sometimes it crash my settings so I have to reconfigure it ...when I have started my track, some times I stop at the road, reconfigure the app and start again to drive and to capture it...sometimes I'm tired and I give up if the track was short.
-Sometimes the app crash, with new or old settings, and also it happens when I have started the track. and I gave up.

with this version...the app got stuck when I start to capture a sequence. I have uninstalled it and reinstall it...I have changed all the settings and it doesn't work.

### Additional information
I need some developer setting to avoid such "unexpected" updates when I have a working-well version, because I would prefer an older working version than last crashing app version.

Please fix it as soon as possible because in five days I will drive more than 500 km. so I wish to capture it.

PD: It is sad to said it but... I hate updates.

**Comment by katrinhumal** [comment]
@yopaseopor Thanks for reporting! I am sorry that this update made it worse for you. It would be really helpful if you can send us logs: go to Settings -> Developer and enable 'Save debug logs to file'. Then please try to capture again to trigger the crashing behaviour, and after that send us the logs via the same menu where you have Settings.

On another front: the automatic updates is a behaviour of Google Play. You can tune this in the settings, as instructed here: https://www.howtogeek.com/202297/how-to-disable-automatic-app-updates-in-android/. 

If you want to revert to an older version of the app for your trip, you will find them listed here for direct download: http://android-releases.mapillary.io/index.html

**Comment by yopaseopor** [comment]
I think the think is with API Camera related, because with new version 3.45 and the setting Legacy API Camera enabled it works well. I will send the actual log to logs@mapillary.com

Thnak you for the other important info for me :)

**Comment by katrinhumal** [comment]
@yopaseopor thanks a lot! :)

**Comment by jfburke3** [comment]
I keep automatic updates disabled for this very reason.

**Comment by peterneubauer** [comment]
So,
since 3.45 there have been a  lot of bugs fixed around processing, upload and picture orientation, so I would encourage you to at least update or try 3.50 (you can always downgrade using http://android-releases.mapillary.io/index.html)
