### ISSUE TITLE
Edit approved, but not applied

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#2517]
Hi!

I made some changes to tracks in the hallstatt area and they were approved - I got mails about that.
But the webpage stills shows the unchanged tracks. I did change other tracks in that area in between, those were changed in the view in a nonce, but others are not.
Something hangs.

### Basic information
* Platform: `Web`
* Version: `09.04.2017` 
* System/Browser: `win/linux - Chromium. Firefox,...`

### Steps to reproduce behavior

 1. Edit a track
 2.wait for approval
 3.see if it is changed in weboverview

### Expected behavior
Tracks should show the changed tracks, not the unchanged

### Actual behavior
change approved, but looks like not applied.

### Additional information
User aceini, tracks made on 2nd april 2017, Hallstatt area.
e.g. that track here: https://www.mapillary.com/app/?lat=47.56301887992868&lng=13.650000248973328&z=17&pKey=XEamZVV-rxOnaf68uCM2QQ&focus=photo
or this:
https://www.mapillary.com/app/?lat=47.562613920426145&lng=13.648341794102635&z=17&pKey=oDI-HAMPqGJDdvvftcmRJw&focus=map

**Comment by ToeBee** [comment]
Seems like possibly the same as #2417

**Comment by peterneubauer** [comment]
These edits should now have the correct renderings. I deployed some more fixing code for this - can you test edits and reopen the issue if it persists? The line updates can take a few hours to get into effect, so give it some time to verify after you get the edit approval message.

**Comment by ToeBee** [comment]
I'm pretty sure we don't have the ability to re-open issues after you close them. However this does seem to be fixed. All of my sequences over in #2417 are now showing up correctly on the map.

**Comment by peterneubauer** [comment]
Awesome,
nice!

**Comment by echeloni2p** [comment]
Hi
Not all edits I made are rendered new . e.g. https://www.mapillary.com/app/?lat=47.56285228326723&lng=13.648911640932027&z=17.079845807711507&pKey=WNl3DpAJMvFIml4m0vXb9Q or https://www.mapillary.com/app/?lat=47.07576841242292&lng=15.43814922799902&z=17&pKey=CFUVVb0ZsixeoHhE9cwbjw&focus=photo
will those areas rerendered automatic? Or do I need to edit all of them slightly in one picture to get them rerendered?
