### ISSUE TITLE
Manual capture mode disables distance-based capture

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2518]
### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.44 & 3.45
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Verify that you have distance-based capture enabled in Settings.  I have mine set at 3m if that matters.
 2.  Verify that you are in Automatic capture mode.
 3.  Switch from Automatic capture mode to Manual capture.
 4.  Go back into Settings and note that distance-based capture is now disabled.  Re-enable it.
 5.  Go back into Camera mode.
 6.  Go back into Settings and note that distance-based capture is disabled again.
 7.  In camera mode, switch back to Auto capture.
 8.  Go back into Settings and observe that distance-based capture is still disabled.
 9.  Reenable distance-based capture.  It will remain enabled unless you switch back to Manual capture mode.

### Expected behavior

Switching from Auto to Manual capture should not also change the distance-capture setting.  At the very least, you should still be able to re-enable it.

### Actual behavior

Switching from Auto to Manual capture disables distance-capture.

### Additional information

I can imagine cases where this is intentional, and it that's the reason this is happening, then that's fine.  However, at the very least, a message notifying the operator that distance-capture has been disabled should be displayed.  Even better would be for the app to remember that it had been enabled, and re-enable it when Auto mode is reenabled.  To be technical, when in Manual capture mode, neither distance nor timed capture applies, so it shouldn't be necessary to disable distance-capture, to my way of thinking.

Background:
It took me a little while to figure out this was what had happened.  I was doing a drive through the mountains to relax, and noticed I was passing a POI I wanted to get a good look at.  I switched to Manual mode briefly while doing so, but then switched back to Auto mode, and was disturbed to see that my capture rate was dramatically slower than it had been.  I had to pull over and spend some time fiddling with the app before I found the problem.

**Comment by jfburke3** [comment]
I just noticed #2473 exists for the same problem.  Close this one if you want, and track it with that.

**Comment by katrinhumal** [comment]
@jfburke3 Thanks for reporting! I think it's a good suggestion to track in one place. So closing this, but good to refer to from #2473.
