### ISSUE TITLE
Rotated text appears scrambled

### ISSUE THREAD

**Issue by richardbrinkman** [mapillary/mapillary_issues#2519]
### Basic information
* Platform: `Web`
* Version: `newest?` 
* System/Browser: `Ubuntu 16.04 / Firefox & chromium-browser`

### Steps to reproduce behavior

 1. Browse to https://www.mapillary.com/app/?lat=52.215999491786704&lng=6.878205906769836&z=12.055500320940183&focus=map

### Expected behavior

Rotated street names are readable

### Actual behavior

Some street names are unreadable. Text that is not rotated is readable, but the text that should be rotated is unreadable (see screenshot). If you move your mouse cursor around, the scrambled text changes appearance, but remains unreadable.

### Additional information

The computer is rather old and does not have any fancy new hardware accelerations. I therefore also attached the output of ```glxinfo```.

![screenshot](https://cloud.githubusercontent.com/assets/3140575/24849974/7392471a-1dce-11e7-860a-97024e31a4c9.png)
[glxinfo.txt](https://github.com/mapillary/mapillary_issues/files/909267/glxinfo.txt)

**Comment by nickplesha** [comment]
@richardbrinkman Thanks for reporting this. We can't reproduce this on our machines but it looks like it's a bug with `mapbox-gl` that we use to show map data. Does using any of the other map styles help? (using the layer selector button right above the "zoom in" button)

**Comment by richardbrinkman** [comment]
The weird behaviour only shows on the layer "Mapbox Streets". The layers "Mapbox Satellite", "Openstreetmap" and "ESRI Streets". The latter 3 do appear blurred. Probably because the tile images are stretched.

**Comment by nickplesha** [comment]
@richardbrinkman We've updated the map library recently so can you check if this issue still occurs?

**Comment by richardbrinkman** [comment]
I don't see the weird behaviour any more. It all looks normal now.
Thanks for fixing it.
