### ISSUE TITLE
processing of gps track with pictures missing a few

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#2521]
After doing a few tracks with the new android app version 3.44 I wondered why it always missing a few pictures on start and all others look like they have a position of pictures made later...
Now I´ve seen the behaviour changed: write pictures and a seperate GPX track in legacy folder, and on upload combine them. Thats not error safe, as it looks like it does not match pictures and GPX track fine.

### Basic information
* Platform:  `Android` 
* Version: `3.44` 
* System/Browser: `Android 7.1.1`

### Steps to reproduce behavior

 1. start automatic pictures mode
 2. take some 10-60 pictures
 3.upload

### Expected behavior
Upload all pictures with correct GPS location, maybe write the position at once into the picture as it was before

### Actual behavior
Looks like two threads, the GPS one is lagging 2-5 pictures behind

### Additional information
I´ve seen this in my tracks made on 9th april:
http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUiBFyFlJkN2fUA-2F7zH79E91Fu0C7nB46U1NcTRAUCbwOUHYBigA1MqYh7UIeD-2BrIWo-3D_XWxyqvMaJawcz-2FdEBU4yTSqOdcUyPzyunbGO4aerDu-2FcY5LdiYIvuGSl9NVC9-2FsOaqf9tu4mNt0ftpakHZH4x-2B2i4X2mesT-2BA3sDzxIIfkXKPXn6QSZe6jIBqPEhOXUYTJJiPmljIVDCjrj-2FVq7Kml8eXYJLU5-2B-2FzUVTDc1nj3y0mS3CDFmilgodmogmXbe9JOn2xgXSulPVW2WED8cbzQfsXaH9BVV6pLtj0-2F1HDV2jpyOipWttPKtdfP4-2F7JQD0k-2BbV7DOZOmGDIzZ0-2BboxPMnJEHMX2ebHSoCkdDrznQ-3D
e.g.
or:
http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUgeHrn3-2BtLYtsEJi4tundILHyfqMVfYPKyRQUbh-2BmW1-2B7nGQ-2FxXIrOudHc1JESPrXA-3D_XWxyqvMaJawcz-2FdEBU4yTXZIN82GyLpQ8hr-2BcXb6892hDSL10PxAPXcLiNw8AaVHfJmvNn4wHI5G43Y6TmZBj4c3-2B-2FLEUTmL35BeV2V8K8nJz8RmxaDLuhMrqr8zk5meBeQzSc7F1LwWpSbZP3w0u2SV092tx7yNp3B-2Bw6F51o1XBk4cokRGpvMFT1JHpC4ebIVhp5bfLSlAlQ65h8F2GOOK5J8wowb0X8I9PmidwjIe5dZVkdErcOM0SxqGlQy55TpgO2QUwHWVxUXYvDaj8VqBeLMvvqlutT49wsHkEGY-3D
Or here:
http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUhK3ezzXb7NseRs-2FbIwceacA3AoLoUH0XufaO3F6vfcx9-2FcWBVver2mYuZDpgM0yrU-3D_XWxyqvMaJawcz-2FdEBU4yTWaea0iSBS-2BgP0kQ2-2BxG1clmQ0QYY0qwtdwoUjJf6lCjFG4vul6H8Q7Gd9v-2BDnjrzvThlVJI0uxQZQCHdkQYQYOMj-2FMlkuqkjR0lFFo3CdnU9puPRR6n7qInvgK-2FWqhiYy1QUGgyU8asvb82yeCWL56csnbkQrf-2F0XMjvHRmdUoc8XQcDrMh-2BnjprjMYbb7-2BgWWSj6ZSzj7mZJanLS7gGZCczEhgG-2FVId-2FsiicH-2BxMBnYsbYCJOjKViNXfdrsBFW6Z3s6o7zg26xfF4WM20zt9s-3D

thats why I need to move all pictures of the tracks manually to the right position, also looks like the first pictures (or the last fews) are not uploaded, as no fitting GPX is found. Too bad.

**Comment by katrinhumal** [comment]
Thanks for the details @echeloni2p! @peterneubauer will look into this.

**Comment by peterneubauer** [comment]
Yes, it seems the GPX track is sometimes a bit off, depending on the phone. Probably the best compromise is to both record the track, and write the location as soon as it's known into the EXIF, and then display both in the preview and let the user decide what to choose, maybe default to the image location. WDYT?

**Comment by peterneubauer** [comment]
Also, @echeloni2p are you using the `disable location check` switch? In that case the images might be outside the GPX track since the camera is not stopping, waiting for the GPX logger to start. If this happens even without that switch enabled, it's a bug.

**Comment by echeloni2p** [comment]
yeah, I do use disable_location_check, as in the mountains and city canyons a lot of poisitions are not in the 15m area. Usually I do refine those manually on mapillary wegpage, if that works (see other ticket^^).
The issue with gps notbeing in sync was not a issue until the change in 3.43 (or was is 3.44?)
One or two pictures without GPS location out of a few hundred is fine.
BUT the write GPS location to pictures made 1-10sec later is really a big issue, picture and GPS location must fit.

**Comment by peterneubauer** [comment]
Totally agreed. I'm going to add GPS writing back into the images, and then
we can see both suggestions on the review map, potentially letting the user
choose what location to use, especially later with external images from
cameras with GPS. Also the gpx tracks needs to get better.

**Comment by drkludge** [comment]
@peterneubauer I usually let my phone "run for awhile" before I start taking pictures.  Hence, there are plenty of gps points at the beginning of the capture session.  I am guessing that when I turn the capture session off, you could still let the gps run for a bit.  That way you'd have additional long lat points at the end of the capture session.

**Comment by echeloni2p** [comment]
drkludge thats not the real issue here - I did have the mobile running for 1 hour and made tracks before, it is "just" two threads running out of sync - GPS can be fine, but if the time of the GPS entry and the picture do not match, you have a fine GPS but thats combined with a picture made 10 sec later...
As I´ve written, mapillary did not have had that issue until 3.42, in which gpx track got seperated from picture.

**Comment by peterneubauer** [comment]
Is this still an issue? In that case, I would love to take a look at the sequence if you can get the whole folder (GPX, photos) to me.
