### ISSUE TITLE
mapillary.io serves incorrect SSL/TLS certificate

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2524]
go to https://forum.mapillary.io

notice how a certificate that is only valid for *.mapillary.com and mapillary.com is used

**Comment by domdomegg** [comment]
![image](https://cloud.githubusercontent.com/assets/4953590/24910408/94885a62-1ebf-11e7-8e05-2aaaedddb862.png)

![image](https://cloud.githubusercontent.com/assets/4953590/24910481/d9df34a0-1ebf-11e7-8836-f458ec3c8ed2.png)

![image](https://cloud.githubusercontent.com/assets/4953590/24910452/bf2c1fec-1ebf-11e7-8277-3ce53e855d52.png)

**Comment by gyllen** [comment]
.io is no longer a domain that we use
