### ISSUE TITLE
Error in weekly digest email

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#2525]
Error in email - "Last week's top list in undefined"

![image](https://cloud.githubusercontent.com/assets/4953590/24910303/34d554b2-1ebf-11e7-8713-baf1ce5566cf.png)

### Steps to reproduce behavior

 1. Upload no photos (maybe this is required?)
 2. Get weird email

### Expected behavior

"Last week's top list in [London/England/the UK]"

### Actual behavior

"Last week's top list in undefined"

**Comment by katrinhumal** [comment]
@domdomegg Thanks for notifying, we'll make sure to fix that!

**Comment by katrinhumal** [comment]
Done, the next email should not have this issue.
