### ISSUE TITLE
Erroneous "bad GPS" interferes with picture taking 

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2527]
### Basic information
* Platform:  `Android` 
* Version: `3.45` 
* phone: `Sony Z5 compact` 

### Steps to reproduce behaviour
 1. Check that 'Skip location check' in the Developer settings is not set
 2. Take photos at fixed interval of 3s for a while (with shutter sound on to be able to hear the photos being taken)
 3. After a while the photo frequency will stutter and finally photo taking will cease all together. If you watch the screen, you may see that the green location signal is missing. 
Stopping and starting a new sequence does not unblock the lock.
Exiting the Mapillary App and restarting it normally removes the problem and you are back at point 2 above.
 4. Enabling 'Skip location check' removes the problem

### Notes
From checking the GPS positions of the photos it appears that there are no traces of wrong positions. All photos are always in the correct position.

### Example
[https://www.mapillary.com/app/?lat=45.35441419494427&lng=11.903800316625222&z=16&pKey=HZivxvHQvKGf1m3bWNzBIQ&focus=map&mapStyle=mapbox_streets&username%5B%5D=voschix&dateFrom=2017-04-09&menu=false](https://www.mapillary.com/app/?lat=45.35441419494427&lng=11.903800316625222&z=16&pKey=HZivxvHQvKGf1m3bWNzBIQ&focus=map&mapStyle=mapbox_streets&username%5B%5D=voschix&dateFrom=2017-04-09&menu=false)
shows the traces of two contiguous sequences, the first one (right hand side of the window) shows the stuttering mode ( 'Skip location check' disabled) and the second one (left hand side of the window) with  'Skip location check'  enabled. In between the two sequences I stopped and changed the  'Skip location check' setting.

**Comment by katrinhumal** [comment]
@voschix Thanks for the report! Do I understand correctly that this happens repeatedly, not just once? Do you think you could send us logs of this?

**Comment by voschix** [comment]
Update: the link with GPS problem is most likely a fake. 
Yes the problem happens repeatedly and frequently, and now prevents me from really producing pictures. I changed the picture setting mode to ignore missing GPS signal. I still get the same behaviour plus some pictures that are in the wrong position (see my uploads of 17 April 2017). The app starts, takes pictures for periods from tens of minutes in a row down to small sequences with some ten pictures before picture taking stops. I take pictures every three seconds. When picture taking stops I notice that the app is unresponsive. For example the close button is not visible on the window for a couple of seconds. If I try to restart immediately it often does not work, If I wait a minute or so, it normally restarts without problems. Behaves like a cooling problem. I moved apps out on the SD card - no improvement.
I managed (finally) the find the logs (mapillary_trace.txt) of the Mapillary app on the phone (127MB starting on 11 April 2017). As the file is too big I will send it directly to Katrin Humai via TransferBigFiles
Most likely unrelated: I also have upload problems - will create a separate error report.

**Comment by peterneubauer** [comment]
@voschix can you clear the log and get it to me when this happens again?

**Comment by voschix** [comment]
# Update with Android 363:

I ran some tests today (with "skip location check" disabled) and pictures taken at 3 sec interval on Sony Xperia Z5 compact.

The test confirms that the problem is still present. It also seems to support my initial suspicion that it has to do with GPS. I have to add that it seems that the Z5 (or at least my Z5) has a mediocre GPS reception.

- The app, when started, takes ages (minutes) to start, flagging that it is waiting for GPS, even though the independent app "GPS status and toolbox" shows already good GPS signal with less than 15m error.

- Occasional the app stops with no indication, seemingly in situations with poor satellite view (tree cover, narrow road with high buildings). I then stop the app and wait a minute or so. Touch the red button, but the app does not start, signalling missing GPS signal. Repeat after another minute - same behaviour. If however I immediately go back to the menu by hitting the back triangle, the screen goes black for maybe 5 or 10 seconds, I touch the Capture button, see for a moment the red "location missing" signal, but picture taking starts immediately
- I then repeatedly stopped picture taking touching the square red button, The successive start button operation had no effect and I had to go through the back triangle procedure described above. NOTE: I am certain that in the past I could use the stop-start_again sequence without problems, but am nt sure if that was not with skip-location-check activated.

Hope this helps pinpointing the cause of this annoying problem (particularly when you are taking pictures on the bicycle and you have to stop every time this happens, and dismount the phone to get it working again)

**Comment by peterneubauer** [comment]
With the latest updates, this should be gone. The problem was that the interface reported the fix as reported by the phone with aid of Google service, while the actual capture process was insisting on a pure GPS fix. Now fixed and should be working.
