### ISSUE TITLE
mapillary.com: &deg; not rendered in <title>

### ISSUE THREAD

**Issue by Abbe98** [mapillary/mapillary_issues#2528]
![image](https://cloud.githubusercontent.com/assets/2631719/24998193/977b34f8-2039-11e7-8001-f79492c3c74e.png)

`&deg;` is not rendered in tab-title.

Tested only in Opera(45.0.2552.225). Issue appears on https://www.mapillary.com/360

Using `°` directly seams to do the trick. :-)

**Comment by GITNE** [comment]
> Using `°` directly seams to do the trick. :smiley:

True. Yet, everything works as expected, although I am sure not as intended. :laughing:
Look at the page's source code:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<meta content="app-id=757286802" name="apple-itunes-app">
<title>360&amp;deg; Street-level Photos for Everyone</title>
<!-- […] -->
```
Can you spot the bug?

**Comment by Abbe98** [comment]
I see, the browser or build pipeline converted `&` into `&amp;`.

Interesting that the element inspector did not show the raw code, did not know that it behaved that way.

**Comment by nickplesha** [comment]
Thanks for reporting this! `°` is now visible. :)
