### ISSUE TITLE
Zero timestamp for photos / sequence

### ISSUE THREAD

**Issue by MrYadro** [mapillary/mapillary_issues#2529]
### Basic information
* Platform: `Android` and (or) `Web`
* Version: `3.46` 
* System/Browser: `Firefox`

### Steps to reproduce behavior

 1. Take photos
 2. Upload them

### Expected behavior

Timestamp of photos should way more then 0

### Actual behavior

Timestamp of every photo in sequence is 0

### Additional information

https://www.mapillary.com/map/im/DIivABK6DGjLAAhMMX5-OA
I had problems uploading, It got stuck on processing for ~ 10 minutes.
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/919573/mapillary_trace.txt)

**Comment by quicky2000** [comment]
Hi,

How did you obtained the trace?
Since this morning (just after mapillary ap update) i cannot upload anything... the preprocessing seems to be very slow and upload failed with error 400.
I wonder if this is the same issue than yours

**Comment by MrYadro** [comment]
@quicky2000 you need to enable debugging in Settings -> Developer -> Save debug logs to file, then click Send debug logs in "hamburger" menu

**Comment by quicky2000** [comment]
Thanks for the information.
I tried but my log is quite empty
Mapillary Android logs, user=quicky, version=345(3.45)
Some logs:

**Comment by echeloni2p** [comment]
hii
please try again with 3.48 - after a debug session with peterneubauer, that error should be fixed.

**Comment by peterneubauer** [comment]
Yup,
I'm closing this for now. Thanks @echeloni2p for the help!
