### ISSUE TITLE
Android 3.47 does not detect WiFi to 4g change 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2532]
I left my home with mapillary uploading many images over WiFi. 
After a few hours I got a warning from my provider  that my volume is used too much. 
Android version 3.47 has uploaded 750 MBytes over 4g :-(
Logged by 3G watchdog

**Comment by jfburke3** [comment]
As far as I can tell, on my phone, it suspends upload when I leave wifi coverage.  But, I'll try to test this scenario, if I can get the app to upload anything ( #2530 #2533 ).

**Comment by peterneubauer** [comment]
@HolgerJeromin that is really not ok. Can you reproduce that issue, as we have tested this with going out of range and checking that the app is stopping upload. The app is listening to the Network Monitor API in Android, it would be great to see if that is not triggered on your phone for some reason.

**Comment by HolgerJeromin** [comment]
I will try next time i have images on my phone :-)

**Comment by jfburke3** [comment]
It definitely detected the change on my S7, and suspended uploading until I was reconnected to wifi.

**Comment by peterneubauer** [comment]
Ok, closing this until we have some recreatable error again, we can reproduce here.

**Comment by HolgerJeromin** [comment]
I just rechecked with latest beta app from store. Everything worked as normal. Leaving Wifi stopped uploading in all tests.
