### ISSUE TITLE
Upload fails because of missing date/location

### ISSUE THREAD

**Issue by mikini** [mapillary/mapillary_issues#2533]
### Basic information
* Platform: `Android`
* Version: `Mapillary Android 3.48`
* System/Browser: `Samsung Galaxy SIII (GT-I9305)`

### Steps to reproduce behavior

 1. Capture sequence(s) using Capture tab
 2. Go to Upload tab and start upload

### Expected behavior
Sequences and photos queued for upload should be processed and uploaded. Usually processing time for each photo >1s. When finished sequences and photos are removed from phone.

### Actual behavior
Photos are iterated very quickly, processing time for each <0.1 s. Dialog keeps open showing processing of last photo of last sequence, even after several hours. When cancelling/terminating sequences and photos are still present on phone and not uploaded.

### Additional information

Log indicates that missing date/location in exif is the cause:
```
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_43_138.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_45_122.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_47_168.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_49_164.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_51_188.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_53_170.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_55_189.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.service.MapillaryUploadService  - Sent progress with mapillary_upload 0 files processed.
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_13_57_237.jpg has null date
Sun Apr 16 23:41:51 CEST 2017 : app.mapillary.android.sync.Upload  - No location, skipping /storage/emulated/0/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_16_19_13_42_907/2017_04_16_19_13_43_138.jpg
```
Full log:
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/924664/mapillary_trace.txt)

I have moved the photos to a computer in the hope that mapillary_tools/upload.py would be able to upload them, but they fail verification:

```
$ ~/mapillary_tools/python/upload.py ./Mapillary\ bad\ sequence\ III/ --upload_subfolders
Uploading 0 images with valid mapillary tags (Skipping 850)
Done uploading 0 images.
```

I last saw uploads functional using 3.45-SNAPSHOT but had some trouble with a corrupted image which caused an exception ("Invalid Segment: insufficient data"). I removed all sequences and thought I was safe again but was autoupdated into this exif error which might not be related to the exception. 

Corrupted image exception:
```
Sat Apr 15 05:22:19 CEST 2017 : app.mapillary.android.exif.ExifUtils  - ERROR: parsing image failure: /storage/emulated/0/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_08_08_53_09_301/2017_04_08_08_53_36_765.jpg - Invalid Segment: insufficient data
java.io.IOException: Invalid Segment: insufficient data
	at org.apache.sanselan.common.BinaryFileFunctions.readByteArray(BinaryFileFunctions.java:504)
	at org.apache.sanselan.formats.jpeg.JpegUtils.traverseJFIF(JpegUtils.java:99)
	at org.apache.sanselan.formats.jpeg.JpegImageParser.readSegments(JpegImageParser.java:175)
	at org.apache.sanselan.formats.jpeg.JpegImageParser.readSegments(JpegImageParser.java:272)
	at org.apache.sanselan.formats.jpeg.JpegImageParser.getExifRawData(JpegImageParser.java:378)
	at org.apache.sanselan.formats.jpeg.JpegImageParser.getExifMetadata(JpegImageParser.java:362)
	at org.apache.sanselan.formats.jpeg.JpegImageParser.getMetadata(JpegImageParser.java:312)
	at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:977)
	at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:970)
	at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:945)
	at app.mapillary.android.exif.ExifUtils.getDateCreatedFor(ExifUtils.java:324)
	at app.mapillary.android.exif.ExifUtils$1.subscribe(ExifUtils.java:456)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10179)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
	at io.reactivex.Scheduler$1.run(Scheduler.java:134)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```
Bad image: 
![2017_04_08_08_53_36_765](https://cloud.githubusercontent.com/assets/1330166/25075427/a74765b8-2314-11e7-9668-d7cb39aaff7c.jpg)

**Comment by echeloni2p** [comment]
Hi
App did change the wasay it works, it does process each sequence (combine GPS and picture) and upload afterwards. It should upload fine, at least it does here on 2 mobiles now.

echeloni2p

**Comment by peterneubauer** [comment]
Is this working with the latest (3.47+) releases? The problem was that some Android camera implementations are not writing some EXIF tags properly, so we need to fall back to others to read the capture date.

**Comment by mikini** [comment]
As stated in the above description this was all experienced on 3.48. I noticed that 3.50 is out, will take it for a spin later today. 

Am I able to upload my offloaded sequences by just dropping the sequence dir containing images and gpx back on the phone?
Or could I maybe get some guidance/pointers as to how to fix the upload.py script to be able to upload my backlog of ~10GiB of sequences? (among those some very interesting ones from a tour of [Ringelnatter/Kryle](https://www.openstreetmap.org/way/487532916) WW2 [bunkers near Søndervig](http://www.hvidesande.com/ln-int/hvide-sande/location-local-bunkers)).

**Comment by peterneubauer** [comment]
@mikini yes, if the upload works, the bad sequence should be uploading by putting it back to the phone. Also, we are planning to test and make sure that the upload scripts are taking these GPX/images, can you maybe get me the GPX file and a few images of that bad sequence to test over here?

The bad image seems to be faulty, you probably should delete it from the sequence/phone.

**Comment by mikini** [comment]
Nice, thanks. 

Sure, here is 3 photos and the gpx from one that didn't upload:
[2017_04_14_13_20_28_935.zip](https://github.com/mapillary/mapillary_issues/files/935292/2017_04_14_13_20_28_935.zip)

And the corrupt photo with its gpx:
[2017_04_08_08_53_09_301.zip](https://github.com/mapillary/mapillary_issues/files/935474/2017_04_08_08_53_09_301.zip)

The corrupt one seems to have a valid header but is only 4KiB, it is probably just truncated as I routinely run out of storage ;). It sits alone in the seq dir with the gpx, so I guess the valid photos from that sequence has been uploaded ok and this one left. From the gpx I can see it was captured using "creator="Mapillary Android version 3.45-SNAPSHOT" so it must be a leftover from before the update to 3.48.
In the UI it was present as a sequence with a white thumbnail and no photos inside. I was unable to do anything with it besides deleting the complete sequence by swiping. There were no indication of failure in the UI, that would have been preferable.

```
$ ls -l 2017_04_08_08_53_36_765.jpg 
-rwxr----- 1 miki miki 4096 Apr 11 20:06 2017_04_08_08_53_36_765.jpg
$ file 2017_04_08_08_53_36_765.jpg 
2017_04_08_08_53_36_765.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian]
```

**Comment by mikini** [comment]
No success using 3.50 either. Same quick iteration through sequences, but now an "Upload finished" message instead of hanging at last photo. Still need to press "Cancel" button to continue, though.

Screenshot;
![screenshot_2017-04-19-20-08-47](https://cloud.githubusercontent.com/assets/1330166/25195230/3dd32e2a-253d-11e7-99a7-fba69e0597ed.png)

Looking in the log, I see tons of "has null date" messages. Counting using grep and wc gives 2351 occorences which is ~2 upload attempts of 1180 photos:
```
$ grep "has null date" /run/user/1000/gvfs/mtp:host=%5Busb%3A003%2C046%5D/Phone/mapillary_trace.txt |wc -l
2351
```
Log excerpt:
```
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - trying CreateDate /storage/emulated/0/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_19_09_14_35_753/2017_04_19_09_14_36_240.jpg
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_19_09_14_36_240.jpg has null date
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - trying CreateDate /storage/emulated/0/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_19_09_14_35_753/2017_04_19_09_14_38_257.jpg
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_19_09_14_38_257.jpg has null date
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - trying CreateDate /storage/emulated/0/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_19_09_14_35_753/2017_04_19_09_14_40_163.jpg
Wed Apr 19 20:06:18 CEST 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_19_09_14_40_163.jpg has null date
```
Analyzing metadata using exif and exiv2 tools shows that the date of these pictures is stored in exif tag with id 0x0132 = DateTime (http://www.exiv2.org/tags.html). As exiv2's default "summary" printout (-ps) doesn't print this tag it is probably non-standard somehow.

Exiv2 "vanilla" dump (-pv) of Mapillary photo:
```
$ exiv2 /run/user/1000/gvfs/mtp\:host=%5Busb%3A003%2C046%5D/Phone/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_19_09_14_35_753/2017_04_19_09_14_36_240.jpg -pv
0x8827 Image        ISOSpeedRatings             SShort      1  80
0x0112 Image        Orientation                 Short       1  3
0x0110 Image        Model                       Ascii      10  GT-I9305
0x9207 Image        MeteringMode                Short       1  2
0x0101 Image        ImageLength                 Short       1  2448
0x920a Image        FocalLength                 Rational    1  37/10
0x8822 Image        ExposureProgram             SShort      1  3
0x9209 Image        Flash                       Short       1  0
0x9208 Image        LightSource                 Short       1  0
0x0132 Image        DateTime                    Ascii      20  2017:04:19 09:14:36
0x829a Image        ExposureTime                SRational   1  16/10000
0x829d Image        FNumber                     SRational   1  26/10
0x0100 Image        ImageWidth                  Short       1  3264
0x010f Image        Make                        Ascii       8  SAMSUNG
0x8825 Image        GPSTag                      Long        1  298
0x0001 GPSInfo      GPSLatitudeRef              Ascii       2  N
0x0004 GPSInfo      GPSLongitude                Rational    3  8/1 34/1 37044/1000
0x0003 GPSInfo      GPSLongitudeRef             Ascii       2  E
0x0002 GPSInfo      GPSLatitude                 Rational    3  55/1 28/1 355/1000
0x8769 Image        ExifTag                     Long        1  400
```
Curiously enough, if I compare with a photo saved by the Samsung Camera application, the camera photo has more timestamps than the Mapillary photos. Among them is the 0x9003 = DateTimeOriginal/0x9004 = DateTimeDigitized tags that exiv2 uses in its summary print.

Looking a bit in [the standard, table 17+18, page 86](http://www.cipa.jp/std/documents/e/DC-008-Translation-2016-E.pdf?page=86) it specifies that DateTime is meant for "File change date and time", DateTimeOriginal for "Date and time original image was generated" and DateTimeDigitized for "Date and time image was made digital data".

I'm not familiar with the Android camera API and don't know who generates the exif. I guess you don't do it yourself since you are looking for the correct tag on different devices/APIs. But these three seems to be the only ones defined in exif for the image (GPS date/time tags apart), including additional sub-tags for sub second time resolution and tz offset, so might not be a bad idea to support these. 

"vanilla" dump of Samsung Camera photo:
```
$ exiv2 Samsung\ S3/20170411/20170402_132904.jpg -pv
0x0100 Image        ImageWidth                  Long        1  3264
0x0101 Image        ImageLength                 Long        1  2448
0x010f Image        Make                        Ascii       8  SAMSUNG
0x0110 Image        Model                       Ascii       9  GT-I9305
0x0112 Image        Orientation                 Short       1  1
0x011a Image        XResolution                 Rational    1  72/1
0x011b Image        YResolution                 Rational    1  72/1
0x0128 Image        ResolutionUnit              Short       1  2
0x0131 Image        Software                    Ascii      13  I9305XXUFNL1
0x0132 Image        DateTime                    Ascii      20  2017:04:02 13:29:03
0x0213 Image        YCbCrPositioning            Short       1  1
0x8769 Image        ExifTag                     Long        1  226
0x829a Photo        ExposureTime                Rational    1  1/100
0x829d Photo        FNumber                     Rational    1  26/10
0x8822 Photo        ExposureProgram             Short       1  3
0x8827 Photo        ISOSpeedRatings             Short       1  100
0x9000 Photo        ExifVersion                 Undefined   4  48 50 50 48
0x9003 Photo        DateTimeOriginal            Ascii      20  2017:04:02 13:29:03
0x9004 Photo        DateTimeDigitized           Ascii      20  2017:04:02 13:29:03
0x9101 Photo        ComponentsConfiguration     Undefined   4  1 2 3 0
0x9201 Photo        ShutterSpeedValue           SRational   1  1701/256
0x9202 Photo        ApertureValue               Rational    1  276/100
0x9203 Photo        BrightnessValue             SRational   1  1095/256
0x9204 Photo        ExposureBiasValue           SRational   1  0/10
0x9205 Photo        MaxApertureValue            Rational    1  276/100
0x9207 Photo        MeteringMode                Short       1  2
0x9209 Photo        Flash                       Short       1  0
0x920a Photo        FocalLength                 Rational    1  37/10
0x927c Photo        MakerNote                   Undefined  98  7 0 1 0 7 0 4 0 0 0 48 49 48 48 2 0 4 0 1 0 0 0 0 32 1 0 12 0 4 0 1 0 0 0 0 0 0 0 16 0 5 0 1 0 0 0 90 0 0 0 64 0 4 0 1 0 0 0 0 0 0 0 80 0 4 0 1 0 0 0 1 0 0 0 0 1 3 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0001 MakerNote    Offset                      Long        1  4798
0x0002 MakerNote    ByteOrder                   Ascii       3  II
0x0001 Samsung2     Version                     Undefined   4  48 49 48 48
0x9286 Photo        UserComment                 Undefined 4104  (Binary value suppressed)
0xa000 Photo        FlashpixVersion             Undefined   4  48 49 48 48
0xa001 Photo        ColorSpace                  Short       1  1
0xa002 Photo        PixelXDimension             Long        1  3264
0xa003 Photo        PixelYDimension             Long        1  2448
0xa005 Photo        InteroperabilityTag         Long        1  4896
0x0001 Iop          InteroperabilityIndex       Ascii       4  R98
0x0002 Iop          InteroperabilityVersion     Undefined   4  48 49 48 48
0xa402 Photo        ExposureMode                Short       1  0
0xa403 Photo        WhiteBalance                Short       1  0
0xa406 Photo        SceneCaptureType            Short       1  0
0xa420 Photo        ImageUniqueID               Ascii      33  GDFI02
0x0100 Thumbnail    ImageWidth                  Long        1  160
0x0101 Thumbnail    ImageLength                 Long        1  120
0x0103 Thumbnail    Compression                 Short       1  6
0x0112 Thumbnail    Orientation                 Short       1  1
0x011a Thumbnail    XResolution                 Rational    1  72/1
0x011b Thumbnail    YResolution                 Rational    1  72/1
0x0128 Thumbnail    ResolutionUnit              Short       1  2
0x0201 Thumbnail    JPEGInterchangeFormat       Long        1  5056
0x0202 Thumbnail    JPEGInterchangeFormatLength Long        1  10040
```

**Comment by peterneubauer** [comment]
Yes, this is exactly the problem. Requesting image capture via the vanilla camera APIs results in non-sufficient EXIF metadata with especially date fields missing and not filled in. I strongly suspect that there is more happening after the capture in the camera app.

Can you please try http://android-releases.mapillary.io/Mapillary_Android_3.51-SNAPSHOT1.apk which takes more date failover in the EXIF and let me know if the processing works better, and maybe get us the logs?

**Comment by mikini** [comment]
Using 3.51-SNAPSHOT1 and capturing a quick 3 photo test sequence the upload now do remove the photos from the phone. I can't see them on the site yet, though.  Around 20 minutes has elapsed since upload.

I still have to press "Cancel" in the upload dialog when it says "Upload finished" to dismiss it, which feels odd.

Log attached:
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/952460/mapillary_trace.txt)

**Comment by mikini** [comment]
The previous upIoad eventually came online at https://www.mapillary.com/app/user/mikini?pKey=ZrdVCoTTfKnu6TSteTe3jg

I've been having a lot of random crashes on upload since. Persistently retrying on individual sequences have enabled me to upload most of them in the end. Though, at the moment I have a single sequence left that persistently crashes upload. Here's a log, crash happened at the end, no indication seems to be recorded about cause, except maybe the sequence is already present on server ("Upload with 0 files remaining of 0"); [mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/979667/mapillary_trace.txt)

**Comment by peterneubauer** [comment]
Upload is going to be more table, closing this issue meanwhile
