### ISSUE TITLE
sequence not in proper order

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2535]
The sequence kEt-vktCzxzjxVMWL3hpFg shows images not in the subsequent order.

**Comment by peterneubauer** [comment]
This was a bug on the app level that is fixed. We have an internal issue to reorder these sequences that have images with data Unix 0 (1. Jan 1970), taking the EXIF date instead of the Mapillary tag date as the capture date.

**Comment by peterneubauer** [comment]
This looks fixed, closing.
