### ISSUE TITLE
iOS - not able to stop sequence playing

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2538]
### Basic information
* Platform: `iOS` 10.1.1
* Version: Mapillary App 4.6.13` 

### Steps to reproduce behavior

 1. Go into the sequence screen (the split one with the photo on the top half and the map on the bottom half), either from the map view or from the profil page.
 2. Start playing a sequence with the "Play"-Button (the right pointing triangle)
 3. Exit the sequence screen WITHOUT stopping the playing sequence.
 4. Re-enter the the sequence screen by selecting another sequence from the map or the profile page.

### Actual behavior

When you re-enter the sequence screen the selected sequence is playing automatically. So far, so good. But you can't stop the playing sequence. On top of the screen there is the "Play"-Button shown, not the "Stop"-Button, (the little rectangle one). The sequence playing only stops when reaching the end of the sequence.

### Expected behavior

Either stop playing the sequence automatically when exiting the sequence screen or when re-entering show the "Stop"-Button, as you are in play mode already.

**Comment by millenbop** [comment]
Thanks for reporting, I'll fix as soon as possible!

**Comment by millenbop** [comment]
It has now been fixed, will be out in the next release.
