### ISSUE TITLE
Request Android 360° Photo import and Upload Function.

### ISSUE THREAD

**Issue by kokoye2007** [mapillary/mapillary_issues#2539]
### Basic information
* Platform: `iOS` | `Android` 
* Version: `...` 

### Steps to reproduce behavior

 1. Take 360° Photo and use browser
 2. Import 360° Photo and use browser
 3. Cant connect with 360° cam via app. So take download and transfer. 

### Expected behavior

We want to use 360° photo upload with Mobile application. We cant take with Mapillary App? Ok we want to import 360° photo and want to connect 360° Cam.
Like this:
G00gle Str33t vi3w is can take 360° photo, can import 360° and connect with 360° photo. Easy to use with application and support background upload function.

### Actual behavior

When we can make 360° cam look like Cardboard Cam, 360 cam and g00gle Str33t Vi3w mobile app with 360° photo. We cant upload from application. Also i am using LG360 cam. Download via wifi and using Browser upload. Its not support resume and background process. 

### Additional information

![g00gl3 str33t vi3w](http://i67.tinypic.com/2s62a8x.png)

**Comment by katrinhumal** [comment]
@kokoye2007 thanks for your request! We are already working on the 360 camera support so you will soon be able to link your LG to the Mapillary app to take photos. We do not plan to add an import feature to the mobile app; if you have photos taken outside the Mapillary app then you should use our web uploader (as it sounds like you are doing). Keep an eye on our blog and social media to stay up-to-date - once it is ready, we'll surely announce the Android 360 support there.
