### ISSUE TITLE
the user cannot figure out what to click on to unsubscribe

### ISSUE THREAD

**Issue by jidanni** [mapillary/mapillary_issues#2541]
User wishes to unsubscribe from "Mapillary Weekly Digest".

User clicks the link contained within,

and ends up on the screenshot attached.

In it one does not find the familiar checkboxs seen on other websites
using HTML Forms.

Maybe it is the user's browser (Linux/midori) but anyways, the user cannot
figure out what to click on to unsubscribe.

![f](https://cloud.githubusercontent.com/assets/1230959/25230438/72b88332-2606-11e7-9052-427409c8ac51.jpg)

**Comment by katrinhumal** [comment]
@jidanni thanks for your feedback! These are valuable insights and I'm taking them to our team to figure out how to improve.
