### ISSUE TITLE
Unable to get a GPS lock in latest mapillary versions

### ISSUE THREAD

**Issue by nunogand** [mapillary/mapillary_issues#2543]
Stopped using mapillary app during the winter. When I tried to start using it again, some updates later, the app was unable to get a GPS lock.
All other apps on my phone can get a GPS lock at the same time, just Mapillary can't.

However, eventually I found that version 2.40 of the app still works - after a few seconds I can get GPS lock and start taking pictures.

I'm using Android 4.4.2

**Comment by katrinhumal** [comment]
@nunogand Thanks for reporting! Do you have Google Mobile Services turned on? If not, could you do that and see if it helps get a GPS fix for Mapillary?

**Comment by nunogand** [comment]
I tried with GMS on and off. Only in 2.40 (from the ones I tested) can I get a GPS lock.

**Comment by nunogand** [comment]
My device is a BQ Aquaris E4.5. It's based on MT6582.
I've updated the manufacturer software to Android 5.0 and still fot the same issue.
With CM13 also the same problem: while all other GPS aps can get a fix, latest versions of mapillary can't but 2.40 still works ok.

**Comment by katrinhumal** [comment]
@nunogand Thanks for providing the additional information! @peterneubauer will have a look.

**Comment by peterneubauer** [comment]
@nunogand could you please open the camera, wait for a fix and send the logs?

**Comment by nunogand** [comment]
Installed latest version from Google play. 
With GPS Test I could get a lock in some seconds. Started Mapillary and waited and waited. Made a 15km trip and still no lock. Some time ago I tried taking images with the option "Skip locatin check". All the images taken did not have GPS information. 
I'll send the log but without ever getting a GPS lock.

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/962873/mapillary_trace.txt)

**Comment by ovivoda** [comment]
@nunogand Please check the latest snapshot and let us know if this is still a problem:

http://android-releases.mapillary.io/Mapillary_Android_v3.82-SNAPSHOT1.apk

Thanks!

**Comment by nunogand** [comment]
So far seems to be working well. But next week I'll try it again for more
time.

Nuno

Em 08/08/2017 07:10, "ovivoda" <notifications@github.com> escreveu:

**Comment by ovivoda** [comment]
Thanks Nuno,

We have even more fixes in the latest beta app launched on GooglePlay
3.83-BETA

Ovidiu
