### ISSUE TITLE
Traffic signs filter does not reset after “Reset filters”

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2544]
### Basic information
* Platform: `Web`
* Version: `Any`
* System/Browser: `Linux/Firefox`

### Steps to reproduce behavior
1. Turn on `Traffic signs` filter
2. Click `Reset filters`

### Expected behavior
Traffic signs should stop being filtered or displayed.

### Actual behavior
Traffic signs are still filtered or displayed. Additionally, the address bar URL keeps the `&signs=true` URI parameter. This parameter should either switch to `&signs=false` or be removed from the list of parameters, as it is when turning off the `Traffic signs` filter explicitly.

### Additional information
Turning the `Traffic signs` filter explicitly on or off works always as expected.

**Comment by gyllen** [comment]
Hi @GITNE , thanks for reporting. We are now tracking this bug internally and we will get back to you when its fixed.

@nickplesha Report back here when fixed

**Comment by nickplesha** [comment]
@GITNE Thanks for reporting this. Reset button should work as expected now.
