### ISSUE TITLE
Wrong GPS position on images from GoPro. Photos located on a single straight line.

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2546]
### Basic information
* Platform: `iOS`, GoPro Hero Session 4, my bike and [this connector](https://github.com/habi/OpenSCAD/blob/master/STL/smart_gopro.stl)
* Version: `4.6.13` 

### Steps to reproduce behavior

1. Connect camera, acquire sequence
2. Check while acquiring that the green dots are where I cycle
3. Transfer the images from the camera to the phone
4. Upload

### Expected behavior
See a nicely placed sequence of photos

### Actual behavior
See all photos from two sequences ([MeaXQ5sYY7xqLjInka5BeQ](https://www.mapillary.com/map/im/X5hL5v1oRnQBxUrjA-igVw) and [elGk8MirzCficm1akz7bAQ](https://www.mapillary.com/map/im/awO9MGnvQym8XY94AN8fmA)) along a single line, the first one with a short (correct) detour at the start f the sequence which was actually close to the end of the real sequence.
Both sequences are in the general region of where I took the photos, but I cannot cycle this straight :)

Earlier uploads with exactly the same workflow worked just fine...

**Comment by habi** [comment]
I've tried again today and got the same problem.
This time with sequence [M634IzTqpbQspoFN-w-3WQ](https://www.mapillary.com/map/im/FJ2tquECcjJLI-55X8HkNA) and [jF_jW-C_rYMAbFQxDdIfEQ](https://www.mapillary.com/map/im/J6EgH3v19I13MVMMfrWtdg).
The first one seems to start correctly, but then goes bonkers.
The second one is completely off regarding positions. Also it switches between images from the first and second sequence.

**Comment by habi** [comment]
Here's one of the more recent sequences where everything worked as expected: [rnVSf9enGjZ-enJvc3HaBw](https://www.mapillary.com/map/im/BvW-UBnj8uFUR41Khb7FJw).

(Mapillary-wise that is, I was nearly [run over by a car](https://www.mapillary.com/map/im/6oL-BdugwtBF1JGH-pL45w) shortly after starting the sequence 😱

**Comment by habi** [comment]
BTW: Feel free to delete the 'offending' sequences (or mark them as invisible if possible).
I'm not deleting them for your debugging purposes...

**Comment by millenbop** [comment]
Thanks for reporting! It seems that the time on the camera differs from the phone for some reason. Do you remember if you used the gopro app before capturing? Thinking maybe it messes with the time. We don't officially support the Session just yet, and I don't have access to one, but we will add support.

**Comment by habi** [comment]
> Thanks for reporting! It seems that the time on the camera differs from the phone for some reason. Do you remember if you used the gopro app before capturing?
> 
I did use the GoPro app before Mapillary.
But it seems to me that I have to, otherwise I cannot seem to connect to the camera in the Mapillary app.
> Thinking maybe it messes with the time.
> 
The GoPro app should sync the time of the phone with the camera, at least there's a (turned on) option...
> We don't officially support the Session just yet, and I don't have access to one, but we will add support.
> 
I know you don't support it officially, but it used to work just fine :)

**Comment by habi** [comment]
I've tried again this morning.
- Opened GoPro app, deleted all images in the camera
- Set time and date in GoPro app
- Opened Mapillary app, connected to camera
- Biked to work, while checking that the green dots on the screen are in the correct position (which they are)
- Downloaded images from camera
- Uploaded to Mapillary
- Saw that the [sequence bFFW9g8mud3H74aHdS7ROQ](https://www.mapillary.com/map/im/Um6GpGuydRWZozWZBJiU8g) is wrong

I won't try anymore :)
Unless you instruct me to try something 'special'.

BTW: as seen [here](https://github.com/mapillary/mapillary_issues/issues/1731), the workflow used to work some months ago...

**Comment by millenbop** [comment]
Just wanted to let you know that we'll be moving from the pre-SDK API to the official SDK now, hopefully this will make things work much better. A bonus is that Session and Hero5 and future models will be officially supported too.

**Comment by habi** [comment]
Great! Looking forward to test it.

**Comment by habi** [comment]
I hoped that the newest version (Version: 4.6.15) fixed the problem, but it doesn't.
I've stumbled over a detail that might be important (maybe there's a 'off-by-one'-error somewhere).

This morning I recoded three sequences, a very short and two longer ones.
The first one was 13 images, where I was testing if a 90° angle is picked up.
The second one around 300 images until I had to wait at a red light.
The third one (after a red light) around 100 images.

In the app I only see two sequences.
![img_3374](https://cloud.githubusercontent.com/assets/1651235/26268046/97c4e2f8-3ced-11e7-8c68-ce270f22ba58.PNG)

The 13 first sequence images are spread out over the locations of the second sequence: https://www.mapillary.com/map/im/4Fm14oEB-PA5tKrN5tsH8w
![img_3375](https://cloud.githubusercontent.com/assets/1651235/26268062/b18e34d2-3ced-11e7-8325-e21fd9bc7b21.PNG)

The second sequence images are at the beginning correctly mapped to the second sequence, but keep on going to somewhere very weird (I stopped near 'Universität Bühlplatz', towards the roundabout in the image below): ttps://www.mapillary.com/map/im/oG6D5ZWgrk61-u_q1NsUUg)

![img_3377](https://cloud.githubusercontent.com/assets/1651235/26268095/d7710b52-3ced-11e7-9879-9bd6331fba0e.PNG)
![img_3376](https://cloud.githubusercontent.com/assets/1651235/26268124/fb4f05d8-3ced-11e7-9751-2207a35fb6df.PNG)

**Comment by millenbop** [comment]
No changes for the GoPro in the last update. I plan on submitting it on Friday.

You can see full release notes here: https://docs.google.com/document/d/15eexyVvjIgNvhuNTiuYBxuYWn6dGJduAHXQA311ypU0/edit?pref=2&pli=1#

**Comment by habi** [comment]
Thanks for releasing a new version.
Looking forward to test it ASAP.
I'm marking the 'wrong ' sequences for deletion and will try to record them anew.

**Comment by millenbop** [comment]
Fingers crossed!

**Comment by habi** [comment]
After uploading thousands of images with the `mapillary_tools' I tried again this morning.
The sequence looks fine while recording (analogous to the screenshots in this thread), but on Mapillary, the photos are completely wrong: https://www.mapillary.com/map/im/A2hWQM2BEbwaZ4OJ_owteQ

**Comment by amilopowers** [comment]
Just to let you know: I have the exact same error but I use a GoPro Session 5 and an iPhone 5s.

**Comment by gyllen** [comment]
@habi So just to be clear
```
1. Upload with scripts work
2. Upload from iOS app does not work
```

**Comment by habi** [comment]
> 1. Upload with scripts work
> 2. Upload from iOS app does not work

1. Record GPX and ‘time-lapse’ with GoPro independently, merge and upload with the mapillary_scripts works. No involvement of the Mapillary iOS app at all.
2. Connect camera to iOS app looks like it works (as seen here https://github.com/mapillary/mapillary_issues/issues/2610) but doesn’t work, like reported here.

**Comment by gyllen** [comment]
@habi Ok thanks mos def an iOS issue then

**Comment by amilopowers** [comment]
I've made two more examples. One in a straight line: JfSQ1-E8-_zqWFZ-ScQzsw and one on one point: LmiGsKPx6lCnMAzM16Xmxg

**Comment by gyllen** [comment]
@millenbop Elevate this

**Comment by millenbop** [comment]
Will do!

**Comment by habi** [comment]
I hoped that the newest release fixes this because of the 'tweak of the time/date setting'.
![img_4381](https://user-images.githubusercontent.com/1651235/31556869-02e7cf10-b047-11e7-823f-4ec8707a9cbb.JPG)

But another try with the updated app still yields a straight line at the wrong location (about 25 km from where it would be) when uploaded and a correct location when looking at the phone while recording.
The sequence I recorded is here: [BXwuXt9f6-4s0qGltuL2LA](https://www.mapillary.com/app/user/habi?lat=46.82581140942057&lng=7.209918913566071&z=17&pKey=Fy1_1L3K3VhIE7L7ck0vow)

**Comment by amilopowers** [comment]
Are you guys actively working on this?

**Comment by gyllen** [comment]
@amilopowers Yes

**Comment by habi** [comment]
I was hoping with the newest release (see below) this problem is fixed, but unfortunately it isn't.
![img_5180](https://user-images.githubusercontent.com/1651235/34768586-8aa0a59a-f5fb-11e7-9b85-7459f15c5ba1.jpg)

This morning I
- removed all my image from my GoPro Session 4
- reset the date and time of the camera with the GoPro app
- connected the camera to the Mapillary app
- started and stopped the acquisition of two image sequences while biking to work
- downloaded the images from the camera with the app
- [uploaded to mapillary](https://www.mapillary.com/app/user/habi?pKey=aZU_-cJec7brPAHPFdIo5Q)

The images are all in a straight row, which makes the app completely unusable for me on my phone.
Is there *any* way I can help debugging this?

![img_5177](https://user-images.githubusercontent.com/1651235/34769021-da3bf73e-f5fc-11e7-8504-de8dbbf365ed.PNG)

**Comment by millenbop** [comment]
This should be greatly improved now. Closing, let me know if you have problems still and I'll reopen, thanks.

**Comment by habi** [comment]
Thanks a lot for keeping up with the small and pesky things!
I'll try to check soon and re-open if I run into issues.

**Comment by habi** [comment]
The problem still persists.
I formatted the SD card, updated the Date and time of the camera with the GoPro app on my phone.
Adding the camera to the Mapillary app and recording my commute home.
All the 300+ photos are squashed together to a sequence of approximately 10 m: https://www.mapillary.com/map/im/CH5Zz5wBbQPUZKYP-twlWg

**Comment by amilopowers** [comment]
Same here. Still the same issues.

**Comment by gyllen** [comment]
@millenbop ^^^

**Comment by habi** [comment]
Is there a way I (we) can help to debug you?

I'm happy to go out and record sequences with very specific settings workflows and provide you the images outside of the Mapillary app (and the GPX file if I can export it from the app).
I'd *really* like to make this work, so I could record much more sequences...

**Comment by millenbop** [comment]
![img_8437](https://user-images.githubusercontent.com/12835674/37413756-fdcdc40c-27a7-11e8-9b48-3b5ea85daab6.PNG)

Here's a preview of what I'm working on right now. I hope I can send it out for beta testing soon. Whenever you are using an external camera, you have to set the time offset for the sequence before you upload the images. Basically what you do is a) select an image and b) adjust the slider until the image is in the correct position. Then this offset is used for all the images in that sequence.

So it would be great if you could test it out when it's ready for public testing. Please email me at anders @ mapillary and I'll send an invite to Testflight.

**Comment by habi** [comment]
Great!
Happy to test; email sent.

**Comment by millenbop** [comment]
I haven't received any email yet, also checked spam. Did you email to .com?

**Comment by habi** [comment]
At least I tried, but I’m on mobile for a week (of vacations)...

If it doesn’t arrive, you can send the invite to my address I registered at Mapillary (same user name as here). 

![605df623-956e-42c2-95e3-26a4b38b635d](https://user-images.githubusercontent.com/1651235/37469616-f02fd786-2865-11e8-9a54-356ec9548d5d.jpeg)

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
