### ISSUE TITLE
Report an error link is missing 

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2547]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Visit mainpage from Mapillary
 2. Try to report an error

### Expected behavior

A link to report an error i found

### Actual behavior

On the bottom of the Page there was a link, that is gone...

**Comment by katrinhumal** [comment]
@thoschu96 Thanks for noticing! I will look into this.

**Comment by katrinhumal** [comment]
Submitting issues is available through our Help Center now (email to support@mapillary.com). Closing this.
