### ISSUE TITLE
Reorganize elements in the edit-view

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#255]
The elements in the right pane need more space in the vertical then the map does and enforces scrolling. To prevent that I suggest the following:

Change Lon/Lat from: 
     Latitude: 51.72906805
     Longitude: 10.52255082 
To: Lon/Lat: 51.72906805/10.52255082 

remove the "Hidden: false/true" field (the buttons colour indicates the same information)

Put the "Hide this Image" and "Hide the whole Sequence" buttons in one line.

Change the "Camera was pointing at 0 degrees to the forward direction. " that it works the same way as the "location" filed.

**Comment by knikel** [comment]
The new editor will have completely rebuilt UI. Will close this issue after we roll it out.
