### ISSUE TITLE
Internal server error when giving the API a bbox of size 0

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#2550]
## The error
https://a.mapillary.com/v3/detections?client_id=‹clientID›&bbox=1.0%2C2.0%2C1.0%2C2.0 returns:
```json
{"message":"Internal server error. Please report the issue at https://github.com/mapillary/mapillary_issues/issues"}
```
## Additional info
https://a.mapillary.com/v3/images?client_id=‹clientID›&bbox=1.0%2C2.0%2C1.0%2C2.0 and<br>
https://a.mapillary.com/v3/sequences?client_id=‹clientID›&bbox=1.0%2C2.0%2C1.0%2C2.0 on the other hand return
```json
{"type":"FeatureCollection","features":[]}
```
https://a.mapillary.com/v3/changesets?client_id=‹clientID›&bbox=1.0%2C2.0%2C1.0%2C2.0 even returns a (long) list of results.

## What is the correct behaviour
The API should not error out when giving it a BBOX, which has no size (minlat==maxlat and minlon==maxlon).

**Comment by gyllen** [comment]
@floscher Thanks for reporting, elevated to dev team

**Comment by ptpt** [comment]
@floscher It should be fixed. Thanks!
