### ISSUE TITLE
Corrections not showing

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#2551]
I am noticing that some corrections are not published. Below are two of them.  But its not like before when they got lost, this time the corrected version of the sequence can be seen if going to Edit mode.

https://www.mapillary.com/app/index/andreas.p?lat=59.32241715389111&lng=18.090547075128683&z=17&pKey=WwwplHFBVUdKluFlczpBcA&focus=map

https://www.mapillary.com/app/user/andreas.p?lat=59.29877225141328&lng=17.995904947387004&z=17&focus=map&pKey=vDmxT9o5AJ-Pw-YZFeiYyg

**Comment by katrinhumal** [comment]
@Andblue Thanks for reporting! We've seen this issue before with some edits and are working on it. At other times, however, it just takes a little more time for the map tiles to catch up. Can you please tell me when you made the edits?

**Comment by Andblue** [comment]
Not sure when in time it was, could have been weeks or months ago.

**Comment by katrinhumal** [comment]
@Andblue Oh! In that case, it doesn't matter when exactly since it's clearly too long. I will add your case to the existing examples we have of this, and hopefully, we get it sorted out soon.

**Comment by peterneubauer** [comment]
These sequences should now be corrected on the map, can you please test? We are going to re-send all sequence location changes in order refresh the tiles if needed.
