### ISSUE TITLE
Mapillary not as useful for bicycle mapping

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2552]
### Basic information
* Platform: `Android` 
* Version: `6.0.1` 
* Mapillary: `3.43`

### Steps to reproduce behavior

 1. Use a bicycle mount on the handle bars with Mapillary.
 2. Go riding.
 3. Hit a bump.
4. The application screen flips and stops working. 

### Expected behavior
Hit a bump and the application continues to take pictures.

### Actual behavior
The application stops taking pictures.

For a long time I used Mapillary 1.47 on an older Samsung G3 class phone.  [I could use a rental bike](https://www.mapillary.com/app/?lat=33.451651&lng=-112.0673821&z=17&pKey=B-rnLSgVhSrapKST1b8anw&focus=photo) and take a steady stream of pictures.  I'd try to filter out the upside down pictures but a few would get through.  The application just worked.

[While using Mapillary 3.43 on a bicycle the results are not as positive.](https://www.mapillary.com/app/stats?user=drkludge&lat=33.60288004000904&lng=-112.00263004563112&z=17&pKey=8uPmb_Ai49EQsdquMnNpIw) I hit a bump and have to stop the bike.  Press the super small stop button and then start all over again.  In one case, the app froze or in another I exited Mapillary and started the app again. Moreover, I have shaking and other features turned off that would add to this problem, if turned on. [I tried to fly through this tunnel before GPS lock was lost.](https://www.mapillary.com/app/stats?user=drkludge&lat=33.53359696463852&lng=-112.04152731268692&z=18.245908867964303&pKey=KtcFNn2Qm2dfFI2K6ip_6w)  That way I could get more of the detail inside.  On another time through the tunnel, I leaned back in the seat to see the display. Not only did the app stop taking pictures when I hit a bump well before the tunnel, there were enough additional bumps that the capture screen was spinning.

I've also tried to turn off the auto rotation feature.  As far as I explored, every other part of the Android Mapillary application obeys the auto rotation setting except the capture screen.  For both car capture and bicycle capture, I always put the phone in the mount the same way.  I don't have to think about capture. I put the phone in the mount and go.  The loss of auto rotation would not be an issue.  That's where I feel that the capture screen should obey the auto rotation feature.  I think that this is the source of the problem.  Now I am no longer thinking about riding or enjoying the few, I am thinking about capture.  I am also trying to avoid every bump in the road. Coupled with the tiny stop/start button described in https://github.com/mapillary/mapillary_issues/issues/2481 I find it challenging to use the app while biking.  As I describe, this was not the case in times past.  I think the recent UI changes that left a tiny start/stop button where you cannot see that actual state of capture and this behavior shows that the application has been geared toward walking capture and not bicycle or car 
capture.

**Comment by peterneubauer** [comment]
The rotation of the UX  and shaking detections has been switched off because of the instability in the phone sensors in alter versions. Could you please update to the current 3.54 version and report back?

**Comment by drkludge** [comment]
Thank you for the response.  I will give 3.54 a try later tonight.

**Comment by drkludge** [comment]
@peterneubauer Thank you that is a great improvement.  I was pushing the available light for the images but we have:
- [curb hop warmups](https://www.mapillary.com/app/?lat=33.60137929576457&lng=-112.00448781229005&z=17&pKey=zrQAqUS2v7Ppl7_3hGhagg)
- [looped through a field](https://www.mapillary.com/app/?lat=33.60350298022894&lng=-112.003833491509&z=17&pKey=unewkHw5whuZyx-eopQU-g)
- [over a grass berm](https://www.mapillary.com/app/?lat=33.59775623187977&lng=-111.99293461166315&z=17&pKey=dCIk-uArr4HKjUtdB_EMuw)
