### ISSUE TITLE
User profile not loading

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2553]
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 53 on Linux Mint`

### Steps to reproduce behavior

 1. Go to the Mapillary map (https://www.mapillary.com/app/)
 2. Open your user profile drawer on the right side of the page
 3. User profile opens up blank with the spinning "loading" animation but the user profile information never fills in and just keeps spinning forever.

This doesn't happen every time but lately it seems to be happening to me a lot. Looking at my browser console, I think there might be a client-side timeout on the request to retrieve the user profile and the server isn't returning the information fast enough so the client is timing out and not displaying an error message to the user.

Here are details from the Chrome dev console:
 * The request is to `https://a.mapillary.com/v3/model.json?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&paths=%5B%5B%22userByKey%22%2C%2276YsB_Po7jCH0yAhWKEOFg%22%2C%5B%22about%22%2C%22blur_stats%22%2C%22changeset_stats%22%2C%22created_at%22%2C%22image_stats%22%2C%22nbr_photos%22%2C%22photo_distance%22%5D%5D%5D&method=get`
 * In the network tab the status shows as `(cancelled)` which is why I suspect it is hitting a client-side timeout at which point the request gets cancelled instead of timing out and failing.
 * The Javascirpt console shows this message: `Unable to get response from server, please try again.`

Have I uploaded too many images and it is slowing down my user profile loading? Should I stop uploading? :)

**Comment by ToeBee** [comment]
When I execute the GET request in its own tab, it takes over 15 seconds to complete. I think the user profile pane times out after 5 or 10 seconds.

**Comment by katrinhumal** [comment]
@ToeBee whatever you do, don't stop uploading! :D  Asking @gyllen for advice here.

**Comment by ToeBee** [comment]
I mentioned this issue on IRC and @nicolas17 said he had been seeing it too but thought it was just his internet connection. Then for a while it was working for both of us and the request I posted returned almost instantly when run in a separate tab. Just now it wasn't working but I just had it work once so it seems to be a random hit/miss thing. Maybe one server in a cluster is having problems?

**Comment by voschix** [comment]
I maybe seeing another incarnation of this problem. Since yesterday evening or this morning I am observing very slow connection or no connection to the map and profile parts of the Mapillary site.
I see
![image](https://cloud.githubusercontent.com/assets/11076112/25639082/e447a112-2f8a-11e7-9f12-7bde18d87ad9.png)
spinning forever on my Windows 10 installation with Firefox, with Chrome, and with edge. It should not be a problem of my Internet connection: http://beta.speedtest.net/result/6266025487

**Comment by voschix** [comment]
Map view and profile are consistently not loading on my Windows 10 computer with Firefox, Chrome, and Edge. Surprisingly things are working with Internet Explorer 11 on the same computer

**Comment by GITNE** [comment]
I have been experiencing the same issue for the last few days on Linux/Firefox 47. I have not tested on other platforms, so I thought that it may have been my system only but obviously it is not the case, so this issue must have been probably introduced with the latest web site update. Another side effect is that which ever sequence I choose, the sequence editor does not load completely and then I cannot get out of it either. However, the blur editor works as ever.

**Comment by gyllen** [comment]
Is this still an issue, we have had some big load on the backend lately but scaled it now

**Comment by GITNE** [comment]
The profile pane still does not load for me, regardless if I am logged-in or not. However, the sequence editor loads fully now. I do not see any errors in the browser's network log either. :confused:

**Comment by gyllen** [comment]
@GITNE This might be specific to your profile, elevating this issue

**Comment by ToeBee** [comment]
Mine just timed out a few minutes ago and sometimes still takes several seconds but it is definitely working more reliably now.

**Comment by GITNE** [comment]
> This might be specific to your profile, elevating this issue

@gyllen Or may be a class of profiles because I have been uploading some gigabytes lately too (which are all processed by now but the profile pane still does not work).

I see the following recurring requests in the browser's network log when I open the profile panel: 
[log.txt](https://github.com/mapillary/mapillary_issues/files/973661/log.txt)

If you compare the requested size to the received size it may look like the requests made and responses work correctly but they are not paged properly (due to page download size). Or, the sizes differ simply due to gzip compression, so I do not know.

**Comment by voschix** [comment]
I still see the same behaviour: map page https://www.mapillary.com/app/ does not load. It hangs. Happens on Firefox, Chrome, and edge. Does not happen on Internet Explorer. Looks as if the three browsers that hang report the same four errors on the their web consoles, I am not able to decipher them. I attach the Chrome and Firefox console messages as separate text files. 
[Mapillary-map-not-starting Chrome console.txt](https://github.com/mapillary/mapillary_issues/files/973920/Mapillary-map-not-starting.Chrome.console.txt)
[Mapillary-map-not-starting Firefox console.txt](https://github.com/mapillary/mapillary_issues/files/973921/Mapillary-map-not-starting.Firefox.console.txt)

**Comment by voschix** [comment]
Forgot to say that the Internet Explorer web console does not signal errors.

**Comment by nicolas17** [comment]
It's working for me now, but on first load, the API call to get user info took _much_ longer than it should.

**Comment by GITNE** [comment]
@voschix Your problem seems unrelated to this issue. Have you configured the affected browsers to use a proxy? If so then lack of connection may hint at a problem with the proxy, not the browsers or the website itself.

**Comment by voschix** [comment]
No proxy. Never had one. And I did not change any configuration. The
problem started only a couple of days ago without any intervention on my
side.

**Comment by voschix** [comment]
Everything is back working now. No intervention on my side. Did you do anything on the server side?

**Comment by GITNE** [comment]
Unfortunately, I am still out of luck. :cry:

This is particularly annoying because you do not have easy access to your stats, nor can browse your history feed, nor quickly jump to your sequences in order to edit stuff.

**Comment by ToeBee** [comment]
Yeah, this is still failing for me almost every time on the first request. Usually it works after a couple of tries. I'm guessing after the first request something gets cached and it returns faster on subsequent requests.

**Comment by GITNE** [comment]
> Yeah, this is still failing for me almost every time on the first request. Usually it works after a couple of tries. I'm guessing after the first request something gets cached and it returns faster on subsequent requests.

Works for me now too. It is as @toebee has said, only due to cached data. I have to refresh the page multiple times without discarding the cache and then the profile pane gets loaded. So, it looks like timeouts or paging are the culprit here.

Please, do some tests on slow connections (even though mine should be fast enough), at least from time to time. :wink:
Besides, I have measured that on the first loading of the page the browser pulls like 5 to 6 MB. This is really **a** **lot**, especially for metered connections.

**Comment by gyllen** [comment]
@GITNE I just took a quick look at this and you are right. The problems seems to be that with massive volumes of data as you have (great work), the time to compile stats takes to long.

Once the database warms up for your requests though, thats when it returns.

Investigating.....

**Comment by gyllen** [comment]
@GITNE I boiled it down to actually counting the number of blurs you have done (50k is an impressive number). Im elevating this to our PSQL guy @ptpt to see how we optimize the query.

**Comment by nicolas17** [comment]
That explains why it affects @toebee and me too. Although @gitne still beats both of us :grin:

**Comment by GITNE** [comment]
Eventually, this will happen to every user, hence it may be a good idea to start consolidating older entries, especially blur and sequence edits. The database system is sure able to cope even with millions of records per user but the HTTP server response should definitely be consolidated, at least for profane display purposes. However, a REST API call of fine granularity should still exist.

**Comment by gyllen** [comment]
@GITNE As always you are right, we are actually looking at moving the whole blur database to ELS at the moment. That will make stuff speedy again, in the meantime we will look at the specific psql queries and try to figure out why they are slow (there is probably some indexing to be done)

//cc @ptpt

**Comment by ToeBee** [comment]
I think this got better for a while but seems to be getting worse again over time.

**Comment by GITNE** [comment]
Hmm, I have not seen any improvement. :disappointed: I still have to refresh multiple times to see my feed. If anything, it has probably gotten worse because now the same behavior can be observed even if I am not logged in. :cry: One has to keep in mind that blurs aren’t displayed (although maybe fetched) for logged out users.

**Comment by GITNE** [comment]
I have not seen any improvement. And, it is really a pain to deal with it. I wish this would finally get resolved.:crossed_fingers:

**Comment by gyllen** [comment]
@GITNE Actually @ptpt is looking into this at this minute.

As mentioned before its the big (impressive) numbers of blurs you both have made that is slowing down your profile API call.

**Comment by gyllen** [comment]
@ptpt Whats the latest?

**Comment by nickplesha** [comment]
@ToeBee @GITNE @nicolas17 Sorry about the problems you've been experiencing. We've updated the UI so your profiles should now load as normal. The numbers of pending blur/etc. will load separately (this might take a while but will be much faster when the blur database is upgraded).

**Comment by GITNE** [comment]
@nickplesha Right, I thought so it might actually be a problem with the UI since the backend is capable of handling millions of records per user. I am glad it is finally fixed. :smiley: Thank you!

**Comment by gyllen** [comment]
@nickplesha Yey

Im closing the issue

**Comment by GITNE** [comment]
@nickplesha I am still experiencing `HTTP 504` errors on `https://a.mapillary.com/v3/users/<user key>/stats?client_id=<client id>` requests. You know, the stats which show up in the gray box at the top of the feed. It is exactly the same problem like with feed itself before, if I reload the page multiple times the stats finally show up. Can you check this, please?

**Comment by nickplesha** [comment]
@GITNE I've updated the user profile so it loads separately from the stats (the URL you mention) as @gyllen and @ptpt are still working on speeding up the blur database and it still may return 504 until that's finalized.

**Comment by GITNE** [comment]
@ptpt @nickplesha Hmm, I am still (or again) experiencing this issue almost every time I load the page for the first time, at least regarding stats and uploads. The same happens in the Android app. Does it work for you, @ToeBee?
