### ISSUE TITLE
Blur editor stops registering clicks for new blurs in Chrome/Windows

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2554]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome 57 on Windows 10`

The blur editor sometimes just stops registering clicks when trying to create blur areas. Removing existing blurs still works and the buttons work. I just can't create new blurs. I have only ever seen this in Chrome on Windows. Never in IE or any browser in Linux. My most commonly used combo is Chrome on Linux. It seems to happen randomly. Sometimes it will happen after just a couple uses of the blur editor. Other times I will go maybe 10 times without it happening.

This has been happening for a while. At first I thought it might just be something specific to my system but then I noticed that when Mapillary got into this state, iD on osm.org was also broken so that I couldn't click to select existing features. I mentioned this on Slack last night and Bryan Housel saw it and said they've been hunting down this problem in iD for a while. See the iD issue here: openstreetmap/iD#3805

It seems like this is really a bug in Chrome where it forgets to pass on a mouse event randomly and this completely disrupts things. It is surprising to me that a refresh does not fix the situation. I have to completely restart Chrome, including killing any background processes before I can create new blurs again.

I did find [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=161464) filed against Chromium that seems like it could be related and supposedly there was an attempt to fix it but according to the last comment, the fix may not have worked. So this may just be a matter of waiting for the bug to get fixed in Chrome.

**Comment by katrinhumal** [comment]
It does sound like an external bug, in which case there is not much we can help with. But again, I want to ask advice from tech-wiser people than me, just in case, so... @gyllen, wdyt? :)

**Comment by ToeBee** [comment]
Looking at the Chromium bug I linked, I'm wondering if this really could be the cause though. If you move the mouse while holding down the button, the blur editor will pan the image. So if the browser is sending a zero-pixel move event with every mouse click, it could be activating the pan mode instead of creating a new blur box. So you could maybe filter out zero movement move events or something?

**Comment by gyllen** [comment]
@ToeBee Thanks for reporting this has been elevated to dev team

**Comment by jfburke3** [comment]
I've encountered this too, on Windows 7.

**Comment by nickplesha** [comment]
Thanks for the info! Since it's a bug in Chrome, will close this for now. Please reopen if the linked Chromium issue provides some work-around that we can implement on our end to fix this.
