### ISSUE TITLE
iOS - additional position marker is set when switching from full screen to split screen while playing a sequence

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2556]
### Basic information
* Platform: iOS 10.1.1
* Version: Mapillary App 4.6.14

### Steps to reproduce behavior

 1. Start playing a sequence
 2. Switch to full screen. Rotating the phone or using the full screen button does not matter.
 3. Switch back to split screen

### Actual behavior

When switching back to split screen an additional position marker appears at the actual position of the playing sequence. This position marker stays persistent as the real position marker wanders forward.
You can repeat this several times and dot the sequence with this red position markers. 

### Expected behavior
Only one position marker, the real one, is shown.

**Comment by millenbop** [comment]
Thanks, I'll look into it!

**Comment by millenbop** [comment]
It has been fixed now, fix will be out in the next release.
