### ISSUE TITLE
Wrong meta data in downloaded original

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2557]
Let me put this into an example. This is the meta data I get in a downloaded *original* *image* extracted from a video.

```
0x0112 Image Orientation Short 1 1
0x8825 Image GPSTag Long 1 62
0x0000 GPSInfo GPSVersionID Byte 4 2 2 0 0
0x0006 GPSInfo GPSAltitude Rational 1 0/1000
0x0005 GPSInfo GPSAltitudeRef Byte 1 1
0x0001 GPSInfo GPSLatitudeRef Ascii 2 N
0x0002 GPSInfo GPSLatitude Rational 3 12/1 34/1 1587336352/50000000
0x0003 GPSInfo GPSLongitudeRef Ascii 2 E
0x0004 GPSInfo GPSLongitude Rational 3 12/1 34/1 1870688509/50000000
0x0011 GPSInfo GPSImgDirection Rational 1 298597/1000
0x0010 GPSInfo GPSImgDirectionRef Ascii 2 T
0x010e Image ImageDescription Ascii 602 {"MAPAltitude": 0.0, "MAPLongitude": 12.575485202, "MAPVideoSecure": "<64 digit hex hash code>", "MAPImageWidth": 4096, "MAPLatitude": 12.577059381, "MAPVideoSourceKey": "KQEyqn8SdpJwqRWf9NXaSg", "MAPSettingsEmail": "<user's@email.address>", "MAPPhotoUUID": "15c6c271-4c4d-44da-8521-f1f37ed38053", "MAPSettingsProject": "", "MAPGPSAccuracyMeters": -1, "MAPImageHeight": 3072, "MAPCaptureTime": "2016_11_16_09_31_20_319", "MAPSequenceUUID": "817e21a2-aa48-4a75-966e-126abf347463", "MAPCompassHeading": {"TrueHeading": 298.59793145513913, "AccuracyDegrees": -1}}
0x8769 Image ExifTag Long 1 842
0x9003 Photo DateTimeOriginal Ascii 20 2016:11:16 09:31:20
```

Since this meta data is not really *original* meta data but generated data you would expect it to be correct, if not in values but then at least in semantics.

1. Please note the time stamp. As I have already hinted on multiple occasions `DateTimeOriginal` is time zone agnostic, so simply dumping the UTC time value into this field is plain simple **wrong**. If you can then compute the correct local time for this field otherwise **do** **not** use it. Note that in order to compute the local time given a location and a UTC time stamp you have to compute the jurisdiction which applies to this location first, and then compute the local time from the UTC time stamp and the time zone offset applicable to the given jurisdiction. In any case, preferably use the `GPSDateStamp` and `GPSTimeStamp` fields which are always in UTC. This saves you a lot of headaches.

2. **Do** **not** include any personal user or otherwise sensitive data in the meta data, like a **user's** **e-mail** **address**. Sure, only image owners, that is users who uploaded the photo, can download the so called *original* but they may want to share it with somebody else right away. Today, probably via the internet. So, this means that they most probably will not check the meta data for any sensitive or compromising information before sharing, assuming the file to be in its *original* state, which in most cases probably does not include their e-mail address. So please, stop doing this.

3. Since I do not know the exact semantics of the `MAPVideoSecure` data point, I would probably opt for the value to not get included in the meta data set either, for the exact same reasons as stated above.

4. `GPSAltitudeRef` should preferably be `0` (above sea level), especially if the value of `GPSAltitude` is `0`.

Now, some recommendations. Mapillary should definitely overhaul **all** of its time stamp processing, not just look at single incidents where it may matter or currently causes a problem. Use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) whenever possible (see `MAPCaptureTime`). Do not just copy strings of file names—who's format is dictated by any limitations of any obscure file system—and then reinterpret them.

Compute irreducible rationals. Rationals like `1587336352/50000000` or `0/1000` are legit, however they are more likely to prompt overflow errors in software which does not check for overflow or does not employ overflow exception handling.

**Comment by gyllen** [comment]
@GITNE First off, thanks for taking the time to give us this massive feedback. I do believe that we are actually on the way of addressing most of these issue, but @peterneubauer is more updated than me so I gonna let him answer to that.

**Comment by peterneubauer** [comment]
Hi @GITNE, for the newer Android releases the image information should not contain the mail and username anymore, only the user_key.

For images from videos, we are constructing these from the videos, let me check that code and correct it. For the DateTimeOriginal, to be able to determining the correct timezone we need to actually do a timezone lookup for the location derived from the GPX and the time from GPX, like geonames.

Since there is no way to keep timezone information over all EXIF images (even the ones without GPS data), we decided to whereever we can use UTC as the naming pattern (iOS, Android etc) and use that as the first means of determining the image capture time. Not beautiful but effective, with a fallback to read the different EXIF date fields, see https://github.com/mapillary/mapillary_issues/issues/2561#issuecomment-300440173

You are right in that we should determine the timezone and write the local time into the video EXIF (though there is no convention that mandates local time in EXIF timestamps).

**Comment by GITNE** [comment]
> For images from videos, we are constructing these from the videos, let me check that code and correct it.

Good, so there is hope! :smiley:

> For the DateTimeOriginal, to be able to determining the correct timezone we need to actually do a timezone lookup for the location derived from the GPX and the time from GPX, like geonames.

I believe there is a misunderstanding as to why I have pointed out the `DateTimeOriginal` field. I did not point out the `DateTimeOriginal` field because *I* *want* this field to carry a local time value but because since you already have a GPX track with proper UTC time stamps at your hand when importing a video it would have been a natural choice to go with `GPSDateStamp` and `GPSTimeStamp` in the first place instead of possibly violating the local time assumption for `DateTimeOriginal`. You said it your self, due to the EXIF specification being inconclusive about the time zone of `DateTime`, `DateTimeOriginal`, and `DateTimeDigitized` one is left with nothing else than to assume local time values for or in these fields. My point is, if you cannot–for what ever reason, may it be because it is too complex or too time consuming—to compute the correct local time just use `GPSDateStamp` and `GPSTimeStamp`, especially if you have a GPX track with proper UTC time stamps at hand, or are only processing UTC time stamps internally.

With regards to #2561 I think you may be referring to this statement:
> For our internal images that are taken with the app, the only consistent fix is to save the image filename as UTC timestamp.

Actually, this is not true. An alternative already exists. I have pointed it out on many occasions, and said it even explicitly in #2540. Just write the `GPSDateStamp` and `GPSTimeStamp` fields with UTC if they are missing. Basically, you cannot go wrong with that, even if the user has setup the wrong time zone on their device—because every mobile OS today runs the real time clock in UTC—and you can read the device's real time clock immediately after the photo has been shot. The only thing that *could* go wrong is when the user has setup the wrong time for their time zone initially but usually people get things right when they configure their devices for the first time at their location (time zone). And yes, you **can** get UTC on **every** mobile OS, even if users are taking photos while physically in a different time zone than currently configured (when they did not update their time zone manually).

**Comment by peterneubauer** [comment]
So, I'm going to close this as we have an internal issue to start using GPS timestamp at least as a fallback. This should be then working correctly.
