### ISSUE TITLE
Upside down pictures

### ISSUE THREAD

**Issue by Ilis** [mapillary/mapillary_issues#2558]
Every 3rd—10th picture in a sequence are upside down.

https://www.mapillary.com/app/user/ilis?feedItem=user-X5Qp8Rid0Ll3hjXS8QipAA-activity-user-X5Qp8Rid0Ll3hjXS8QipAA-publishing_done-image%3A1493848036122&pKey=QEKR-BpA13N6VLwT6ffM3g

https://www.mapillary.com/app/user/ilis?feedItem=user-X5Qp8Rid0Ll3hjXS8QipAA-activity-user-X5Qp8Rid0Ll3hjXS8QipAA-publishing_done-image%3A1493848036122&pKey=N2F37VTfIhLIeMJgjgxn2w

I used 3.54 version of Mapillary on Google Nexus 5 phone, mounted on bike handlebar with Mapillary mount.

Moreover, shutter sometimes acts continuously.

Well, roads in my city not smooth, mount has long arm, so phone shakes every second. Maybe G-sensor is a problem?

My proposal is to fix orientation from start to end of sequence recording.

PS. All pictures tilted due to impossible set Mapillary bike mount to direct camera to horizon and 45° to the right or left :) Bike mount designed not good :( My sequences looks like a sort of hell.

**Comment by voschix** [comment]
I was about to report as well an increase in upside-down photos. I am using an unchanged set of equipment (Sony Xperia Z5 compact, same bike , same Mapillary mount, same mix of roads) and since about a week I see a marked increase in 180degree-roated pictures. I get one in about 20 rotated. No pattern as far as I can see.

**Comment by Ilis** [comment]
My log:
[mapillary2017-05-04.log.txt](https://github.com/mapillary/mapillary_issues/files/975528/mapillary2017-05-04.log.txt)

What about continuously acting shutter. I set up distance based capturing 10 or 20 meters, but I have 10 photos on every 10 meters, some of them at the same place. Maybe it is about angle changing based capturing (and no option to disable it).

**Comment by Ilis** [comment]
I made some changes to my bike mount just now :) Rotated bend part 180°, so now I can set up mount vertically and rotate camera 360°
![img_20170504_113101](https://cloud.githubusercontent.com/assets/1223140/25695718/a38602a6-30cd-11e7-8169-2b5cf014485c.jpg)

**Comment by katrinhumal** [comment]
@peterneubauer Here are the examples of the "occasional rotation" I was talking about earlier.

**Comment by peterneubauer** [comment]
That logfile didn't contain anything useful - it was too short. In the Settings->Developer, can you enable tracing? That will write directly into a logfile that is retained over invocations of the app. take some sequence with rotated images, and then send the logs (if trace is enabled, that file will be sent) @Ilis ?

**Comment by peterneubauer** [comment]
fix for this coming out in the next release.
