### ISSUE TITLE
Show blurred fields in the edit-view

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#256]
Sometimes it's difficult to see if an image has blurred parts. To make it easier to see if unblurring is necessary it would be nice to see these red-fields on the blurred parts of an image directly in the edit-section without clicking the unblurring button.

**Comment by jesolem** [comment]
Can we close this after the new viewer release?

**Comment by knikel** [comment]
@bitnapper, @jesolem: yes. This is precisely the behavior we have given you're have the blur mode in the new viewer enabled.
