### ISSUE TITLE
missing track tile after change

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2560]
### Basic information
* Platform: `Web`
* Version: `current` 
* System/Browser: `Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.7 (64-bit)`

### Steps to reproduce behavior

 1. visit https://www.mapillary.com/app/?lat=50.89932297619998&lng=7.035252252499959&z=13&focus=map
 2. there are data tiles missing for sequences and photo locations
 3. 

### Expected behavior

the missing data tiles should be there

### Actual behavior

![bildschirmfoto von 2017-05-04 21 15 45](https://cloud.githubusercontent.com/assets/3539168/25721268/16691780-3110-11e7-8ece-54fa6b9c0afb.png)
![bildschirmfoto von 2017-05-04 21 15 53](https://cloud.githubusercontent.com/assets/3539168/25721273/1b03dc44-3110-11e7-9962-a5cd15a22957.png)
![bildschirmfoto von 2017-05-04 21 16 02](https://cloud.githubusercontent.com/assets/3539168/25721287/222746a0-3110-11e7-8b4a-7105a4dfdb48.png)
![bildschirmfoto von 2017-05-04 21 16 05](https://cloud.githubusercontent.com/assets/3539168/25721291/250278ae-3110-11e7-9058-847e6d23cdba.png)

### Additional information

I requested a location change for some photos yesterday belonging to these data tiles.

Browser console:
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4256/2746.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4256/2745.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4255/2746.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4255/2745.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4255/2745.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/13/4255/2746.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
vendor.946b89ac3e48b870cc2d.bundle.js:1 [object ProgressEvent]
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
a.fire @ vendor.946b89ac3e48b870cc2d.bundle.js:1
e._tileLoaded @ vendor.946b89ac3e48b870cc2d.bundle.js:1
n @ vendor.946b89ac3e48b870cc2d.bundle.js:1
r.receive @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
onInvokeTask @ vendor.946b89ac3e48b870cc2d.bundle.js:1
t.invokeTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
n.runTask @ polyfills.f210a96edd9e7956c6a9.bundle.js:1
invoke @ polyfills.f210a96edd9e7956c6a9.bundle.js:1

**Comment by katrinhumal** [comment]
@jotpe I think this was just a delay in updating, I see the tiles now when exploring this location. Could you check at your end, please?

**Comment by jotpe** [comment]
ok now. But the error message above is strange.

**Comment by katrinhumal** [comment]
@jotpe thanks for confirming! Closing.
