### ISSUE TITLE
Photos shot on GoPro get incorrectly UTC-offset

### ISSUE THREAD

**Issue by bruseker** [mapillary/mapillary_issues#2563]
### Basic information
* Platform: `iOS` 
* Version: `10.3.1` 
* System/Browser: `Mapillary 4.6.14 (220)`
* GoPro firmware: `HD4.01.05.00.00`

I've actually started a whole thread over in the forums before I knew about the issues tracker here.  Rather than repeat myself, I'll just link to that whole discussion.  It seems that the app is trying to take away 6 hours from the time on the photos taken by the GoPro (because I am 6 hours away from UTC), only, it doesn't need to, and that just seems to be messing up the world.

http://forum.mapillary.io/t/so-many-ways-my-first-upload-is-all-wrong/983

latest findings: http://forum.mapillary.io/t/so-many-ways-my-first-upload-is-all-wrong/983/5

**Comment by katrinhumal** [comment]
Thanks! Assigning Anders so he can continue troubleshooting here instead of the forum.

**Comment by millenbop** [comment]
Thanks! I'll look into it!

**Comment by millenbop** [comment]
Just wanted to let you know that we'll be moving from the pre-SDK API to the official SDK now, hopefully this will make things work much better. A bonus is that Hero5 and future models will be officially supported too.

**Comment by millenbop** [comment]
This was released last week. We now always use local time and also the official SDK, so this shouldn't be an issue anymore. Closing.
