### ISSUE TITLE
Upload progress status gives random-seeming amounts of completeness, not in ascending order.

### ISSUE THREAD

**Issue by nbolten** [mapillary/mapillary_issues#2564]
### Basic information
* Platform: `Android`
* Version: `3.55` 
* System/Browser: `Android 6.0.1 on Verizon Samsung Galaxy S5, running TouchWiz on build MMB29M.G900VVRU2DQC2`

### Steps to reproduce behavior

 1. Take a series of image (I took ~110).
 2. Try to upload them.
 3. Watch the progress bar

### Expected behavior

Upload progress is reported as ascending sequence. For example:

    1/110
    2/110
    3/110
    4/110
    (...)

### Actual behavior

I see random-ish completeness numbers. For example:

    1/110
    33/110
    20/110
    90/110
    (...)

### Additional information

The 'upload status' dialog, including a cancel button, remains after the 'upload finished' notification has already been issued, and has an incorrect total number of images. I think that's covered by another reported issue, though.

The time it takes to upload is also pretty inconsistent, and without much feedback provided to the user about what is happening. I uploaded 7 pictures in one series yesterday and it reported processing about 1 picture a minute. I uploaded 110 today and it was all done in a few minutes (less than 10). Ignoring the (probably very good) reasons for the discrepancies, giving the user more information about what's happening during upload would vastly improve the experience of using the app.

**Comment by katrinhumal** [comment]
Hi @nbolten, thanks for the report! Our developers are working on improving the whole upload process so I will make sure they won't miss this issue too. The plan is also, as you just suggested, to make it more evident to the user how the upload is progressing in the sequence list.

**Comment by peterneubauer** [comment]
Can you try http://android-releases.mapillary.io/Mapillary_Android_3.56-SNAPSHOT2.apk and let us know if that works better?

**Comment by nbolten** [comment]
This may not be an easy to reproduce bug. The next sequence I uploaded did this instead:

1. Cycled through 1-23 / 23 images correctly, fairly quickly (1-2 per second).
2. Restarted ascending 1-23 / 23 much more slowly.

There was no change in the dialog indicating that a different process was taking place.

@peterneubauer I'll try it out! It may be hard to judge, though, if it's hard to reproduce.

**Comment by nbolten** [comment]
And after that upload completed, I tried uploading another batch and received the, 'uploading photos finished' dialog, preventing upload of that next batch. I'll try with 3.56.

**Comment by nbolten** [comment]
My experience uploading 85 photos with 3.56: 

- The new upload started without issue, though this may just be due to the app restarting.
- The initial dialog stated, "Uploading 0/85 photos". Should it say "0/85 photos uploaded" or is it indexing from 0?
- The upload sequence incremented by 1 once every ~10 seconds, which seems about right. As the number ascended, the photos were removed from the 'upload view', which did not happen for me in 3.55 (this visual feedback is appreciated). 

I also encountered some other issues. I'll check to see if there are open issues for them, but I'll mention them here as well:

- New users would benefit from an upload time estimate, both before they upload and a 'remaining time' as they upload, so that they can understand their time commitment (1 minute uploading vs. 20 minutes). I recently tried introducing new users to the platform, but spotty WiFi prevented many from completing a capture -> upload cycle, and it was hard to judge whether the upload was working at all.
- I haven't tested it out yet, as I wanted to upload this last sequence without interference, but what is that upload state after selecting 'cancel'? Is it possible to resume, and if so, could the button be renamed to 'pause'? This would benefit new users in the same situation above: pause during a bad connection, resume later.
- My phone went idle around image 18 and turned off the screen. Upon turning it back on soon after, the dialog had disappeared and I was able to scroll around the images-to-upload gallery view, which was no longer darkened. A few seconds later, the upload dialog (with the cancel button) reappeared. I experienced this disappearance of the upload dialog in 3.55 as well, usually when switching app contexts (like going to the Chrome app and then back), and it always initially makes me think that the upload process has ended. I repeated this several times, always with the same result: after 1-11 seconds, the dialog reappears. This is just a guess, but I think the upload dialog regains focus whenever the upload progress info updates, like when the next image has uploaded and the counter increments.

PS: While grabbing that apk, I noticed that mapillary.io domain's cert is for mapillary.com and issues security warnings to browsers attempting to use HTTPS.

**Comment by peterneubauer** [comment]
@ovivoda is looking into this right now, we will also make sure to let the WIFI stay on when turning off the screen to avoid stopping issues, and look over the dialogs etc. out next release.

**Comment by ovivoda** [comment]
This is implemented and will be out in the next release

**Comment by ovivoda** [comment]
This should be fixed in the latest release
