### ISSUE TITLE
Photo upload stats not counting photos taken in country X correctly

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#2567]
### Basic information
* Platform: `Android` + `Web`
* Version: `3.27-3.55` 
* System/Browser: `n/a`

### Steps to reproduce behavior

 1. Upload photos taken in country X -- or at least in Finland
 2. Wait for stats to accumulate & weekly review email to be sent out.
 3. Notice the difference.

### Expected behavior

Number of photos taken in country X and uploaded should be attributed for the country they were taken in.

### Actual behavior

I noticed a weird thing in my latest Weekly Digest email covering regarding the upload stats. The total number of photos I had taken 4/31-5/7 in Finland is suggested to have been 3337 while my total number of photos uploaded was 23988.
 
The oddity is that all the photos I've taken and uploaded this year have been taken in Finland. And certainly more the bit over 3k photos noted to have been taken in Finland have also appeared on the map (in Finland). 

I wonder if this has something to do with the v. 3.3*-3.5* upload problems? At least the order of magnitude of photos that uploaded at first attempt and the number of photos that are noted to have been taken in Finland is the same.

I also wonder if the total counts of photos taken in country X are skewed (=undercounted throughout?) because of this? I would assume so. And if so that would obviously not be good.

Doing a review of the latest Weekly Digests that I hadn't deleted yet it's clear that the discrepencies in the latest digest are not unique:
4/24-30: 11938 / 2813
4/17-23: 15610 / 13109
4/10-16: 43317 / 25967
4/3-9: 21559 / 14945
 
From the above + the latest the discrepency of total photos I have uploaded and photos uploaded "in Finland" is 116412 - 60171 -- that's over 56k photos! Thinking back to my own stats earlier this year it does seem to me that at least the personal numbers in the Leaderboard numbers are showing only photos attributed to Finland. I think I had taken -- or attributed to have been taken -- some 50k+ photos earlier this year. With this my current total (of photos taken in Finland) should be over 160k vs. the 138k that the stats page currently show.

### Additional information 

I've used versions 3.27-3.55 at the same time over this period of time with two phones both of with which I've captured and uploaded with. The other phone has been in auto-update apps the other isn't. The latter was running 3.27 until about a week ago or so. Then 3.5*.

**Comment by GITNE** [comment]
I have observed similar behavior for the last few weeks. This problem goes even further if you try to filter stats for areas below country level, like regions, counties, cities, municipalities, towns etc. In some areas, I am not even listed although I have contributed thousands of photos in that area. Additionally, I am not the only user affected. However, what is strange that usually users who's account creation date predates some unknown date are not affected. Presumably their stats are still counted and updated correctly.

**Comment by GITNE** [comment]
And now, the leader board does not even budge on anything I enter (using Firefox 47), regardless if logged&#x2011;in or not. However, auto-suggest works and lists the correct area.

**Comment by jaakkoh** [comment]
> usually users who's account creation date predates some unknown date are not affected

I doubt this. I registered my account around April 2014 and my account stats are heavily affected.

**Comment by gyllen** [comment]
@peterneubauer Seems like there are a lot of problems with the Finland shape

**Comment by jaakkoh** [comment]
I've also noticed the Finland shape issues. Just haven't been sure if the shape shown represents exactly what the stats count.

See e.g.
[Helsinki area](https://www.mapillary.com/app/stats/85633143?lat=60.17232294926961&lng=24.97178836132062&z=10.363370514484286): You can see rather clearly how there are already areas that have quite dense photo coverage. /Hmm. that link zooms out to national level when I load it, though. Anyways, you can see the above by viewing the areas around Helsinki peninsula. And same is true at least all along the coastline. Most noticeably for nearly all of the Turku Archipelago + all of the Åland area (which  _is_ part of Finland however self-governed and demilitarized).

Altogether I don't see why you couldn't simply take the national boundaries (including the maritime zone) as the boundaries of countries. In fact, I don't see why you would do anything else.

**Comment by peterneubauer** [comment]
This problem should be fixed with better shapes imported, closing for the time being.
