### ISSUE TITLE
Periodic problems with capturing photos

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#2568]
### Basic information
* Platform: `Android`
* Version: `3.55` 
* System/Browser: `Android 6.0.1 on Samsung Galaxy Note 4 (SM-N910C), Build MMB29K.N910CXXU2DQC2`

### Steps to reproduce behavior

 1. Set capture interval to 2 seconds
 2. Start capture
 3. Screen flashes every 2 seconds, but the photo counter remains at 0  

### Expected behavior

Photos should be captured every 2 seconds, and the counter should increment.

### Actual behavior

No photos are captured and the counter does not increment.

### Additional information

Tested at different intervals, with both internal and external Bluetooth GPS.

**Comment by jrcarlsen** [comment]
The problem does not seem to be related to overheating which I suspected earlier.
The problem is periodic, and can't always be reproduced.

I believe this problem may be related to my next bug report which will be about partial images.

**Comment by eneerhut** [comment]
Related to this issue. Some photos are only appearing as partial uploads.
See [here](https://www.mapillary.com/map/im/7JSUy3aY-Fc749lTlnNuHA) for an example.

![image](https://cloud.githubusercontent.com/assets/11349863/26088723/23e3079c-3a3c-11e7-8d6f-ac26551dc39e.png)

**Comment by jrcarlsen** [comment]
From what I can tell, whenever a partial photo (or failed) photo is taken, the counter does not increment. So in the sequence mention by @eneerhut, the counter reported 86 photos, but the uploader reported 202 photos. I haven't checked the numbers, but I assume the sequence has about 116 partial photos.

Debug logs have been submitted.

This bug also exists in version 3.56.

**Comment by peterneubauer** [comment]
I wonder if there is anything fishy with the buffer in the camera APIs. Is this happening all the time or just sporadically for one sequence?

**Comment by jrcarlsen** [comment]
It usually happens after a little while. But stopping captures for 5 mins
doesn't solve it either.

I stopped capturing to let the phone storage catch up, if it was getting
behind. I also tried to keep the phone cool, in case it was a overheating
problem. Neither helped. 2 second interval didn't help either.

This is the same hardware I've used to capture most of my photos.

**Comment by matclab** [comment]
Similar problem here with 3.59. 

Mappilary stop registering photos after a certain time.  Starting a new sequence works for some time, then the counter stop to increment. Sometimes after only 3 shots.

**Comment by jrcarlsen** [comment]
I found that photos was still taken, but they were only partial. Have you noticed partial photos in your sequences?

Also, I replaced my SD Card and haven't had this specific issue since. I have not had time to verify whether the card was broken or if it was a filesystem problem.

**Comment by matclab** [comment]
Neither partial photo here, nor SD card.
Just the counter stopping, and no more photo being taken without apparent
reason.

**Comment by jrcarlsen** [comment]
@ovivoda I have not seen this issue since replacing my SDCard

**Comment by peterneubauer** [comment]
So, we close it until your SDCard stops working again ;)

**Comment by matclab** [comment]
Hello @ovivoda , I finally get the opportunity to try with the lattest Mapilliary (version 3.95) and I get the same problem. In automatic mode, Mapillary starts capturing and suddendly the count of photos being taken stops. 
If i touch the blank button bellow the red square, the count starts again and stops a bit later…
Tell me if and how I can provide more debugging info.

**Comment by matclab** [comment]
@ovivoda I checked the settings, and saw that "Pause on shake" was enabled. Is it expected that mapillary resumes the shots when the phonr stops shaking ? In the meanwhile I've disabled this setting and will try another sequence today or tomorrow.

**Comment by ovivoda** [comment]
@matclab Any improvements?

**Comment by matclab** [comment]
@ovivoda Oups, I've forgotten to report my last try.
Unfortunately not. Same behaviour as reported before.

Please tell me how I can provide you with data relevant to debugging this issue.

**Comment by matclab** [comment]
Last testing at the beginning of June shows the same problem.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
