### ISSUE TITLE
Upload finished -- Cancel

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2569]
### Basic information
* Platform: `Android`
* Version: `3.55` 
* System/Browser: `Samsung Galaxy S7, Android 7.0`

After the upload is finished, I am presented with a dialog box that says "Upload finished" and has as only option "Cancel".

I don't want to cancel my uploads!

![screenshot_20170514-114356](https://cloud.githubusercontent.com/assets/1436366/26032769/aceebb50-389b-11e7-915a-46dc343226ac.png)

**Comment by pbb72** [comment]
Later, when going to upload more photo, I get this message. Whaaaaa?

![2017-05-14 10 42 08](https://cloud.githubusercontent.com/assets/1436366/26033058/0b884be8-38a3-11e7-8d68-673008cd16ea.png)

**Comment by pbb72** [comment]
And now, I can't do anything at all anymore. I'm getting the first (Upload finished -- Cancel) dialog whenever I go into a sequence, and pressing Cancel doesn't do anything. I have to terminate the app to get rid of these dialogs.

**Comment by voschix** [comment]
I had this problem as well.
It appears to have been cured in
http://android-releases.mapillary.io/Mapillary_Android_3.56-SNAPSHOT2.apk

**Comment by HolgerJeromin** [comment]
The whole upload dialog handling was extremely buggy ( #2415) 
I am happy to hear that there is progress.

**Comment by jaakkoh** [comment]
> It appears to have been cured in (...)3.56-SNAPSHOT2.apk

Sounds good. I look forward to seeing this pushed out to the beta channel.

Can I just install this on top of the version I currently have or should I backup the photos on the phone first, then uninstall current, install the SNAPSHOT2 and then copy back the photos?

**Comment by ovivoda** [comment]
@jaakkoh This is pushed to beta channel. Can you confirm that it works for you as well?

Thanks!

**Comment by jaakkoh** [comment]
@ovivoda : It does work also with me (when tested with Huawei P10 and Samsung S5). 
Thanks!

**Comment by pbb72** [comment]
Seems to work fine now in 3.56 :-)
