### ISSUE TITLE
improve blurring parts of an image to the end

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#257]
If one has to blurr parts of an image right to the border of an image it doesn't work when one moves the mousepointer over the edge of the image. It is somewhat difficult to find the right point to click. It could use automatically use the outermost pixel after moving the pointer out of the image.

**Comment by knikel** [comment]
@bitnapper This has been fixed in the recent viewer update. You can also edit blurs in the image view directly.
