### ISSUE TITLE
Version 3.56 "disappeared" all photos taken with 3.55

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2571]
### Basic information
* Platform: Android 6.01
* Version: Mapillary 3.56
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Take lots of sequences with Mapillary version 3.55
 2.  Look on the Uploads tab and see your wonderful sequences
 3.  Upgrade to version 3.56
 4.  Look on the Uploads tab and panic at the missing sequences

### Expected behavior

I should still be able to see my sequences in the app.

### Actual behavior

Heart palpitations, rapid breathing, profuse sweating....

Oh, you meant the *app* behavior.  The sequences don't show up.  Sequences taken *before* version 3.55 (that I haven't finished uploading) do show up on the Upload tab.

### Additional information

The files appear to still exist on disk--I mean, on flash.  I can find them with a file browser, and they're in Android/data/app.mapillary/files/mapillary/CAMERA2_0 on my SD card.

If you want me to upload a trace log, just let me know.  Would help if you can outline exactly how you want me to produce it (e.g., start app, wait X minutes, click Upload tab, wait X minutes, etc.), so I can be sure to get you what you want, unless that much detail isn't important.

**Comment by jfburke3** [comment]
I should note that I tried rebooting my phone and relaunching the app, with the same result.

Going to make a backup copy of the sequences I took this past weekend, just in case......

**Comment by peterneubauer** [comment]
@jfburke3 can you post one of these, maybe just with some images in it (not all) but with the GPS and status.json (if there) present?

**Comment by ovivoda** [comment]
@jfburke3 Can you please check if the files for the sequences that are not visible are still in the same path as the sequences that you can see? I am suspecting a problem with the paths here. Let me know if this confirms or not. Tx!

**Comment by jfburke3** [comment]
@ovivoda  Yes, they're all in that CAMERA2_0 directory. New sequences that I just took are also in that directory. 

@peterneubauer Sure, but I'm not sure if I can do that using my phone. Might have to wait a day or so when I'll be at a real computer.

**Comment by ovivoda** [comment]
@jfburke3 I cannot reproduce this issue here.

**Comment by jfburke3** [comment]
Here are 3 pics, the gpx file, and the json file, from one of the sequences I took that day.  Apologies that it took so long.

[support_files.zip](https://github.com/mapillary/mapillary_issues/files/1030707/support_files.zip)

![2017_05_14_17_15_42_911](https://cloud.githubusercontent.com/assets/11140831/26478836/0ace654a-419d-11e7-9034-a650fc14370a.jpg)
![2017_05_14_17_15_44_842](https://cloud.githubusercontent.com/assets/11140831/26478837/0ad4064e-419d-11e7-8b2c-5dc16fa75b97.jpg)
![2017_05_14_17_15_43_879](https://cloud.githubusercontent.com/assets/11140831/26478838/0aea14fc-419d-11e7-83a9-2508b8fa5822.jpg)

**Comment by peterneubauer** [comment]
Thanks, will look at this ASAP

**Comment by jfburke3** [comment]
This might be fixed....  I installed the 3.60 snapshot from #2562 because I was also having the latest issue described there, and was using it to clean up some of my incompletely uploaded sequences.  In the process of doing that, I realized that some of the sequences I was cleaning up were from  May 14, which is when I took the sequence that the above pics are from.

So I scrolled down through the sequences on my phone and found the specific one from above, which I'm trying to upload now.  I'll post a link to it once the images are published, just so you can see.

Based on what I'm seeing, I think you may have fixed this in 3.59 (because that's the version I had incompletely uploaded sequences from the problem time period).

**Comment by peterneubauer** [comment]
Great,
Let us know how it goes, 3.60 should be MUCH better in uploading.

**Comment by jfburke3** [comment]
I can agree that it appears to be doing a much better job so far.

Only a handful of the sequences in question are showing up as "published" right now, but I was able to find the one that the above pics are from:

https://www.mapillary.com/map/im/xgWuodWGfwom0CGYWiDqYw

**Comment by ovivoda** [comment]
@jfburke3 please try v3.67 or v3.70-BETA from google play and let us know if you're still having issues with it

**Comment by jfburke3** [comment]
I think this is fixed.  I haven't had this problem in the last few releases (including the latest beta).
