### ISSUE TITLE
Version 3.56 seems to have forgotten who I am

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2572]
![screenshot_20170516-002027](https://cloud.githubusercontent.com/assets/11140831/26089721/ec2f36b8-39cd-11e7-9668-fa339aecf4de.png)
### Basic information
* Platform: Android 6.01
* Version: Mapillary 3.56
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Launch Mapillary
 2.  Press the menu spot
 3.  Notice that your info is missing

### Expected behavior

I should see my username and picture

### Actual behavior

My username and picture is missing.  My self-obsession is damaged because my selfie is missing.  I will need therapy now.

### Additional information

The feed does appear to show my account info, just missing from the settings screen.

**Comment by ovivoda** [comment]
New release will have this issue fixed

**Comment by jfburke3** [comment]
Version 3.58 seems to remember me know.  :-)
