### ISSUE TITLE
The Android app doesn't use wifi and cell informations when GMS isn't available?

### ISSUE THREAD

**Issue by aligitor** [mapillary/mapillary_issues#2573]
### Basic information
* Platform: `Android`
* Version: `7.1.2` 
* System/Browser: `LineageOS 14.1`
* Mapillary App version: `3.50`

### Steps to reproduce behavior

 1. Start the Mapillary app
 2. Start capture mode

### Expected behavior

The app finds my location as accurately as other apps do.

### Actual behavior

The app shows "bad fixing", and it rarely finds my accurate position: the button mostly remains red, sometimes yellow, rarely green. If I start other mapping apps / gps trackers their accuracy is much better than Mapillary's.

### Additional information

I don't have Google Play Services or Google Mobile Services on my phone, although I do have alternative location backends like LocalGsmNlpBackend, MozillaNlpBackend, OpenBmapNlpBackend and UnifiedNlp (no GAPPS). In my location settings high accuracy is enabled, it uses wi-fi and cell information too.

It seems that the Mapillary app doesn't use these alternative location providers: there is no Google Mobile Service available on my phone so it uses GPS information only. This problem occurs regardless if I check or uncheck the Mapillary Settings -> Developer -> Use Google Mobile Services option.

**Comment by echeloni2p** [comment]
Hi,
it seems not to use it, but those inforamtion are far too far off. Mapillary needs to be +/- 10m to be accurate. WiFi and Cell information are mostly +/- 100 m.

**Comment by aligitor** [comment]
@echeloni2p I think it also depends where you use it: in a crowded inner city wifi information can add a lot to accuracy, as there are lot of wifi access points around, but GPS signal isn't good in itself because of high builidings.

**Comment by gyllen** [comment]
@peterneubauer You know all about this

**Comment by peterneubauer** [comment]
That is true, we actually can investigate the possibility to use other fused location providers if gms is not available and GPS only is not desirable.

**Comment by aligitor** [comment]
@peterneubauer Is there any news about this? I'd gladly go out with phones, but all of them lacks gms. Why can't the Mapillary app simply use the location information which the OS provides, regardless the source of this location information. Seems an easy issue to me, although I'm not a coder.

Or if there is an older version of the app which could work in my situation, that'd be great too.

Thanks in advance!

**Comment by peterneubauer** [comment]
The bad fix problems should be much better with the latest versions, so I'm closing this, please reopen if you experience this again with the beta releases (join the beta program to get them). Current there is 3.72-BETA
