### ISSUE TITLE
Selecting 'Mapbox Streets' shows 'Basemap: (null)'

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2574]
### Basic information
* Platform: `iOS`
* Version: `4.6.15` 
* System/Browser: `iOS 10.3.1 (14E304)`

### Steps to reproduce behavior

 1. Switch map provider
 2. Select 'Mapbox Streets'

### Expected behavior
Basemap: Mapbox Street

### Actual behavior
Basemap: (null)

**Comment by katrinhumal** [comment]
@habi Thanks for reporting! We actually already caught and fixed this so it should be updated in the app very soon.
