### ISSUE TITLE
Missing Sequence Which Appears On OpenStreetMap iD Editor But Not Mapillary

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary_issues#2575]
### Basic information
* Platform: Web
* System/Browser: Firefox
* Version: 53.0.3

### Steps to reproduce behavior

 1. Go to link in OSM: https://www.openstreetmap.org/edit?editor=id#map=19/51.76670/0.08216
 2. Go to link in Mapillary: https://www.mapillary.com/app/user/essexboy?lat=51.7666641757765&lng=0.08214453360028529&z=18.977023634811154
 3. You will notice that a sequence that was uploded over a year ago is still not visible in Mapillary
 4. Another example includes: OSM Link: https://www.openstreetmap.org/edit?editor=id#map=19/51.63912/0.03379 Mapillary Link: https://www.mapillary.com/app/user/essexboy?lat=51.63917720188795&lng=0.03358920212443195&z=19.187518824086215

### Expected behavior
It is expected that all sequences listed in OSM would be in Mapillary and that you can move along a sequence in OSM
...

### Actual behavior
Actual behaviour is that I can see Mapillary photos in iD Editor but am unable to move along the sequence. The sequence for some reason is not shown in Mapillary.
...

### Additional information

...

**Comment by gyllen** [comment]
@PaulColinSimpson They should be the same, Im trying to find exactly what sequence though, pulled up the areas next to each other and looks equal to me
![screenshot 2017-05-24 17 05 46](https://cloud.githubusercontent.com/assets/268859/26430588/58a1feda-40a3-11e7-89ac-fa22fd329302.png)
![screenshot 2017-05-24 17 05 40](https://cloud.githubusercontent.com/assets/268859/26430591/5e11ca26-40a3-11e7-944f-362d7af0d14a.png)

**Comment by gyllen** [comment]
Closing since no answer
