### ISSUE TITLE
Android app crashes on Samsung Galaxy S8, or freezes the phone.

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#2576]
### Basic information
* Platform: `Android`
* Device: `Samsung Galaxy S8`
* Version: `3.56`

### Steps to reproduce behavior

 1. Capture photos (with pretty much any combination of configuration parameters)
 2. Take a few dozen to about 100-200 photos
 3. The app crashes or totally freezes the phone

### Expected behavior

Smooth capturing for hours.

### Actual behavior

Crash of app or app freezing.

### Additional information

I've tried pretty much all configuration parameters that have impacted the app behaviour before (focus mode, distance/time based mode, distance between photos, Google Play Services on/off, using map-in-camera or not) with no luck.

I have taken 20 sequences all of which with 16-177 photos in each (with the exception of the first sequence that lasted until 460 before the app crashed). The average is only a few dozed photos max.

**Comment by katrinhumal** [comment]
@jaakkoh Thanks! We have 3.58 out in beta now with upload fixes among other improvements - would you like to try that out and let us know?

**Comment by jaakkoh** [comment]
Things are much worse with 3.58. The app freezes or the photo count just stops after a few dozen photos at max. As a new problem half of the photos are half corrupted.

The unfortunate thing is that I'm currently traveling and don't have a device that I can capture with.

I hope you get the capture (and preferably upload) issues resolved by the last week of June as I'll be driving through Europe then. (Likely with an action cam but it'd be nice to capture with a phone too as practice has shown that my action cam uploads lag nearly forever.)

**Comment by katrinhumal** [comment]
@jaakkoh Passing this on to our Android "department"!

PS. For action cam captures, do them anyway if you can - if the upload is cumbersome then we'll find a way to help you with that. Can't miss a drive across Europe! :)

**Comment by jfburke3** [comment]
Just a note that I'm not experiencing any unusual crashy behavior on my Galaxy S7 Edge, Android 6.0.1.

@jaakkoh are you running Android 7.x on your S8?

**Comment by ovivoda** [comment]
@jaakkoh Are you still experiencing this issue with the latest release on GooglePlay?

**Comment by eneerhut** [comment]
@ovivoda no crashes recently on my S8. @jaakkoh good to close for now?
