### ISSUE TITLE
Empty areas on image (write error?)

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#2577]
### Basic information
* Platform: `Android`
* Version: `3.55` 
* System/Browser: `Samsung Galaxy S5 running Android 6.0.1, stock ROM`

### Steps to reproduce behavior

 1. Open Mapillary and record sequence
 2. Settings: Distance based capture, distance autocapture: 5m

### Actual behavior

Shooting a sequence with the phone attached to bicycle, apart from the eventual blurred photos (normal due to asphalt quality / vibrations etc.) eventually I get photos with gray areas. Maybe because the phone couldn't write the photo and the app request another photo write?

### Additional information

I was on bicycle, so it is possible to estimate that going at ~15km/h.

Some pics showing the error. Notice that the gray area varies. Some would have ~20% of area compromised, others would have ~90%:

![2017_05_22_10_37_44_816](https://cloud.githubusercontent.com/assets/397851/26359176/24d7b480-3fab-11e7-9cf5-07109e5f5780.jpg)

![2017_05_22_10_37_05_215](https://cloud.githubusercontent.com/assets/397851/26359199/33fe280e-3fab-11e7-9323-92b366e9a790.jpg)

![2017_05_22_10_37_15_153](https://cloud.githubusercontent.com/assets/397851/26359206/37adf4de-3fab-11e7-85b1-560108f326ce.jpg)

**Comment by nighto** [comment]
Looks like what's shown as gray on Windows Explorer shows as white on browser. Here's a screen capture of what the sequence files looks like on computer. Also notice that the write errors started from a certain point on sequence.

![print mapillary](https://cloud.githubusercontent.com/assets/397851/26359293/75a40e36-3fab-11e7-8683-cbae4a3338c2.png)

**Comment by nighto** [comment]
Interesting to notice as well that the later pictures on the sequence, even though have no visible errors, have no EXIF data:

![print mapillary 2](https://cloud.githubusercontent.com/assets/397851/26359538/1f01c784-3fac-11e7-92da-f32bf6c70e28.png)

**Comment by katrinhumal** [comment]
Hi @nighto - thanks for reporting! We have version 3.58 out in beta now with a lot of fixes. Would you like to give it a try and see how it works for you?

**Comment by nighto** [comment]
Enrolled on beta on Play Store again, will try when it shows the update available.

**Comment by katrinhumal** [comment]
Sounds great! Keep us posted & good luck ;)

**Comment by stev391** [comment]
This might be related to GitHub Issue #2598 as similar symptons, just different default colour for the background in the jpeg.

**Comment by arvdk** [comment]
## Basic information
* Platform: "Android 5.0.1"
* Device: "Samsung Galaxy S4" 
* Mapillary app Version: "3.89" (enrolled for beta)

## Steps to reproduce behavior
Open Mapillary and record sequence
Settings: Time based capture, 1.5s

## Actual behavior
Shooting a sequence with the phone in hand. I sometimes (not always) see the phone having a hard time processing a picture (picture is shown longer than usual, next picture captured is rather quick), but increasing the 1.5s doesn't help. Storage is on external SD. Reïnstalling doesn't help.

## Attachment
* I could make a screenshot but it shows exactly the same as @nighto 's. White in the app, grey in  Windows Explorer. The order of some pics also changed in  Windows Explorer.
* I added the logs, but the logs were not captured with the "save debug logs to file" option switched on. If necessary, I can try to reproduce the error with this option toggled.
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1249658/mapillary.log.txt)

**Comment by nighto** [comment]
Tried yesterday the new beta version (3.89) while walking on foot, and the problem didn't happen again.

**Comment by katrinhumal** [comment]
@arvdk and @nighto thanks for reporting! And sorry for the late reply, I was on holiday and failed to hand this issue off for the time...

@arvdk could you try the latest beta, 3.93? And please turn on the "save debug logs to file" just in case, so if it happens again, you could send us these more detailed logs.

**Comment by arvdk** [comment]
@katrinhumal I'll give it another try. 
One more thing, the issue only occurs at automatic capture mode. I now go manual all the time. But than [this ](https://www.mapillary.com/app/?lat=52.03853216894163&lng=5.554872793966382&z=17&pKey=tE-AGvjA09II5ebJA018fA) happened. I think practically the same issue, except for the fact that GPS data is accurate. (in automatic mode, it won't upload because of missing GPS data) 
This sequence is captured with the updated version 3.93-BETA

**Comment by katrinhumal** [comment]
@arvdk Thanks! I'm handing this over to @ovivoda now. Please send the logs as well if you haven't already - thank you!

**Comment by arvdk** [comment]
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/1278403/mapillary_trace.txt)
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1278404/mapillary.log.txt)
the .log.txt was .log originally, but wouln't upload

**Comment by hlinden** [comment]
I had this issue yesterday as well. 

[Here's an archive of the data directory. (188MB, zipped)](https://owncloud.7183.org/index.php/s/PHi3fwOF4wEIhTK)

...and this is what the log said about the following crash:

`--------- beginning of crash
09-13 18:57:47.446 E/AndroidRuntime(27070): FATAL EXCEPTION: ImageFileSaver
09-13 18:57:47.446 E/AndroidRuntime(27070): Process: app.mapillary, PID: 27070
09-13 18:57:47.446 E/AndroidRuntime(27070): java.lang.OutOfMemoryError: Failed to allocate a 42831 byte allocation with 1376 free bytes and 1376B until OOM
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at org.apache.sanselan.common.BinaryFileFunctions.readByteArray(BinaryFileFunctions.java:496)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at org.apache.sanselan.formats.jpeg.JpegUtils.traverseJFIF(JpegUtils.java:99)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at org.apache.sanselan.formats.jpeg.exifRewrite.ExifRewriter.analyzeJFIF(ExifRewriter.java:229)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at org.apache.sanselan.formats.jpeg.exifRewrite.ExifRewriter.updateExifMetadataLossless(ExifRewriter.java:391)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at org.apache.sanselan.formats.jpeg.exifRewrite.ExifRewriter.updateExifMetadataLossless(ExifRewriter.java:328)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at app.mapillary.android.exif.ExifUtils.updateEXIFLocationTagsForImageUsingSanselan(ExifUtils.java:894)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at app.mapillary.android.camera.legacy.ByteImageFileSaver.run(ByteImageFileSaver.java:49)
09-13 18:57:47.446 E/AndroidRuntime(27070): 	at java.lang.Thread.run(Thread.java:761)`

**Comment by Alessandro-Barbieri** [comment]
I had this issue, I "solved" it changing the photo shooting interval from 1s to 1.5s

**Comment by hlinden** [comment]
I have solved the issue by buying an Transcend Industrial SD-card and by turning off the encryption on the card. However, it would be preferable if the app detected a slow writing speed and just stopped taking pictures until the write buffer was empty again.

**Comment by ovivoda** [comment]
@nighto @Alessandro-Barbieri @hlinden  Can you please try to reproduce the problem again and send me the logs when this happens.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
