### ISSUE TITLE
Request for consideration:  a Mapillary screen saver for Amazon's Fire TV

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2578]
Just an idea that came to mind:  a screensaver for Amazon's Fire TV that pulled random (or semirandom?) sequences from Mapillary to play.  I imagine that it would be more interesting if it selected an entire sequence (with a min/max number of images?  say, >25 and < 200?) to play through.

Not sure what the bandwidth hit on Mapillary's servers would be....might not be practical.

Not an Android developer so I don't know how difficult this is, but figured I'd bring it up.

**Comment by katrinhumal** [comment]
Interesting idea! I'll mention this to the team.

**Comment by jfburke3** [comment]
Just an additional thought on this....  The available sequences should probably be limited to ones that have been manually curated by the Mapillary team (or possibly an approved set of volunteers?) to ensure that only superior-quality sequences are used.  Let's face it, there are some pretty lame sequences out there, including some of mine that I would be horrified to see used as a screen saver.  :-\

**Comment by katrinhumal** [comment]
Closing this, since we unfortunately have no foreseeable plans to implement. You're welcome to take this up on our [forum](forum.mapillary.com) if you want to develop this topic further.
