### ISSUE TITLE
Camera pointing direction doesn't work

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2579]
### Basic information
* Platform: Android 6.0.1
* Version: recent Mapillary 3.5.x (including 3.58)
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Enter camera mode
 2.  Select the direction button.  Select pointing forward.
 3.  Take images!
 4.  Upload said images.
 5.  When published, note that the direction cone points everywhere except forward most of the time.

### Expected behavior

The direction cone should point forward.

### Actual behavior

The direction cone usually points everywhere except forward.

### Additional information

This is *not* the same issue that is described in #2570 

If you have any questions about what sequences are affected, just look at my recent "normalize sequence" requests that I've made to correct the direction.

**Comment by ulikoehler** [comment]
I think this has been fixed in the meantime (I was experiencing the same issue up until ~5 days ago). Now the directions seem to work well, at least for forward-facing cameras and when moving at non-zero speed.

**Comment by ovivoda** [comment]
@ulikoehler tx for the feedback. Was this solved in v3.59?

@jfburke3 please check out latest released version 3.59 on google play and let me know if this issue is still there

**Comment by jfburke3** [comment]
@ovivoda 
I *think* I took this sequence with 3.59.  (Not 100% sure.)  Seems to be 180 degrees off.
https://www.mapillary.com/map/im/yi2mjuW1mSbOzb0y-FtiVQ

Sequences I took yesterday--definitely with 3.59--also don't have the direction embedded correctly.  Not 180 degrees like the other--it seems to vary.  See this sequence, and start playing from here:
https://www.mapillary.com/map/im/jCs_0xzm5orI_t2ajIafwg

**Comment by gappleto97** [comment]
I'm on 3.59, and mine are consistently incorrect with similar issues to those described here. I've had to edit pretty much every sequence I've uploaded, with the sole exception of when I was walking. Even then I had to to reduce direction jitter.

**Comment by gappleto97** [comment]
Also, it never remembers the orientation you set, so we have to manually set it to compass mode

**Comment by ovivoda** [comment]
@jfburke3 @gappleto97 Do you still have this issue on the latest app version from GooglePlay?

**Comment by gappleto97** [comment]
Yes.

**Comment by jfburke3** [comment]
@ovivoda Yes.  Took a lot of sequences yesterday with 3.75-BETA, and the ones I've uploaded so far, still show random directions.

**Comment by ulikoehler** [comment]
I'm using the latest beta (from Google play) and the issue still seems to be the same issue. *Note*: I have not set it to compass mode.

Example sequence: https://www.mapillary.com/app/user/umap?lat=48.15277689953015&lng=11.613950903400394&z=13.812309346476585&pKey=2M_IC49_rFc3qFel1fGnFQ

**Comment by gappleto97** [comment]
For me it all points at 0, not randomly

**Comment by ulikoehler** [comment]
It's not like every image in the affected sequences points at totally random directions. But the images do not point forward, if you set the app to the forward direction. Also it seems to me like its not a constant offset. If you drive constantly in one direction, the cone stays approximately in the same (but wrong) direction. But if you change direction,  the cone goes to another (also incorrect) direction.

See this turn:
https://www.mapillary.com/app/user/umap?lat=48.15272474188697&lng=11.611130911832987&z=15.165210178147971&pKey=2M_IC49_rFc3qFel1fGnFQ

I come from the right. The cone is offset ~100° to the right. Then I turn 90° left. Then then cone points ~90° to the left.

**Comment by peterneubauer** [comment]
@ulikoehler can you try http://android-releases.mapillary.io/Mapillary_Android_3.79-SNAPSHOT1_dedup_gpx.apk ? This one dedupes duplicate GPX trakpoints, which can have a positive effect on the pointing direction of the image.

**Comment by ulikoehler** [comment]
@peterneubauer I'll try it today

**Comment by ulikoehler** [comment]
@peterneubauer It seems to me like using the dedup GPX fix also fixed the issue. At least 2 sequences from yesterday which were uploaded using this version have correct directions. However, they are not visible on the map yet, so I'm not absolutely sure so far.

Example:
https://www.mapillary.com/app/user/umap?lat=47.935824999483884&lng=10.092416831096784&z=17&pKey=tXlA0cLnW9bqP9GHw5Y1eA

**Comment by ulikoehler** [comment]
@peterneubauer It certainly seems like the directions are much better with the GPX dedup version and they seem to be correct for almost all images. There are a couple images in between that are offset, but I think this is no big issue

Example (link goes to an image which is offset):
https://www.mapillary.com/app/user/umap?lat=47.990463178616324&lng=10.177083214675122&z=17&feedItem=user-pyQrwn2chXv57on5L40ZbA-activity-user-pyQrwn2chXv57on5L40ZbA-publishing_done-image%3A1502113393624&pKey=6oLI0Ah8kpzbk9sZtxNnLA

**Comment by ulikoehler** [comment]
@peterneubauer 
After many test sequences with the new beta release on Google Play, I can safely say it worked without any issues so far.

@jfburke3 Could you cross-check this? If it works for you as well, I think we can close this issue.

**Comment by polarbearing** [comment]
I was using 3.117
"Set the camera pointing direction" is set to forward. 
"Use device compass" is off. 
All images have EXIF values for "GPS Img Direction" between 110...130 degrees, which has nothing to do with the driving direction. I could not find another EXIF value about direction. As other apps are reporting correct GPS bearing, the issue must be with mapillary.

**Comment by polarbearing** [comment]
Found another sequence where the directions are stuck to a different narrow angel-range. Again the whole sequence more or less the same wrong angle.

**Comment by polarbearing** [comment]
xref #2622

**Comment by polarbearing** [comment]
Why is the image direction not written to the GPX file?
```
<trkpt lat="XX.41928508" lon="XX.28368317"><pdop>4.5509996</pdop><ele>83.0</ele><time>2018-01-20T13:32:36.384Z</time></trkpt>
```

**Comment by polarbearing** [comment]
Checking sequences with manual capture, in which I had "Use device compass" on, the directions are equally nonsensically. 

Why is the direction not written to the developer's "Show detailed stats"?

**Comment by peterneubauer** [comment]
So, we write the desired direction offset into the GPX file, and calculate the actual direction directly before upload and write it into the EXIF json tag. Until then, the phone direction is recorded in case you want to use it instead of the offset.

In the GPX file, we could write the direction too - I would suggest as reported from the phone, not as calculated from the offset to start with.

**Comment by polarbearing** [comment]
What is the offset calculated from, when the GPS bearing is neither in the EXIF data nor in the GPX file?
The web uploader appears to ignore the GPX file.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest android app version
