### ISSUE TITLE
notifications as result of `@sequence_cut` action contain bogus link to "View on Mapillary"

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2580]
### Basic information
* Platform:  `Web` and `Mail` 
* Version: `N/A` 
* System/Browser: `N/A`

### Steps to reproduce behavior

 1. none, notifications nor sequence cuts are user-controlled

### Expected behavior

The link provided in the notifications (both in the "feed" as well as the link in the mail should go somewhere. I would expect the link to load both new sequences or sequence parts and/or zoom in to the cut location.

### Actual behavior

Opening the link in a browser only loads mapillary with the userprofile in the sidebar; the is no apparent relation bewteen the view shwon and the notification

### Additional information

Links 
  - http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUiMELWwBK9XoCYCr6ACcAcQyk5E5p0DMqH4JlbeSg7mz2gSlca3NdSaoQil8v7C-2BaJQOYW77SM7r8-2BeWTCvCJA-2FGlN3KDWQ7EYfmMgMgIdVr6eX5cBjbWb-2FcAoVuVrVJXvTaAQjYTjzhwnCOjfUUs1L7UEm5PZR18vq5pa4DPz6szdtVvPvwGjOGkb7J3ymSrXMJo8KaHckZUzU5eo2Lyts_50k5pea1VwvjYE957hRsfgD-2FWMDGtGRnNl75i12vLuYEz2nm-2BM78RKNUAmgE24Wr5TOJPOVv1iwHXOQj28RdzvmQ0LIas9MGMMzKttKq4ZhghrAKEJ3eUthciP4sKIbS8OJOlPEiZe72xR8hdA0R131lwYas6xY11nNiBM4PxFyUVnTc2kr3bepLcEWoevha8FN0ztBOHOW5U0B8OkV5lsK7ciox34a7rsw1oc3EZFPpSGIKQ-2Bq5eV25i8OOgjvd0fUsih3K-2FauRLLHMJjpwG8gbrswHgqyMD7xlHgJncLH4iu7VNwj1PC6dwLsNnnJe
  - http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUiMELWwBK9XoCYCr6ACcAcQyk5E5p0DMqH4JlbeSg7mz2gSlca3NdSaoQil8v7C-2BaJQOYW77SM7r8-2BeWTCvCJA-2FGlN3KDWQ7EYfmMgMgIdVr6eX5cBjbWb-2FcAoVuVrVJXvTaAQjYTjzhwnCOjfUUs1L7UEm5PZR18vq5pa4DPz6s1G4d6Tk8D6Z5ZtMBD6-2B9dEN0FxHpS29N9IXkIctkE27_50k5pea1VwvjYE957hRsfgD-2FWMDGtGRnNl75i12vLuZ6krcK-2BeNBOkxqaM8pgyjbWAniCrzhzttg9PMJhKSWcL7Y3CBAtAKWhFc-2FhHG2VInmawCtdKIRk99DemnC-2BB6gvmlCeuiYQYmC067Fwks7-2ByNqRe6zfQhQtnzNWFN02dwWOveEVlBB8LYp15UWjgKGyEqn-2B5IxhofWsV7srEXThC8iGKCnjUrvTR-2FDcAHI0jCOLG2KQjjNVC9SpFVH5ZZKE5x72TLv-2F7Mh-2BpQHZ59mLNAHf16gV76jBHu-2BafSnsMh47D12raO0Z2OXSSXH8XLd

**Comment by voschix** [comment]
I was about to signal the same problem.

**Comment by gyllen** [comment]
@peterneubauer Where are we on this issue?

**Comment by voschix** [comment]
Still there and annoying. 
As these interventions come out of the blue (at least for me), it would be helpful for the user to be able to check the action executed by sequenc-cut.

**Comment by gyllen** [comment]
Sorry for the delay guy, you are right. In general the cutter makes sure that we do not have lines all over the map (somebody flies from Germany to Sweden). So its not doing anything harmful. Having that said though we need to make sure that you can see what actually did happen.

**Comment by peterneubauer** [comment]
So, the sequence_cut bot actually creates changesets that we can render into something that the affected user can examine (sequence before, and a number of smaller sequences after). It's a matter of having a special template for this changeset @gyllen .

**Comment by gyllen** [comment]
@peterneubauer Agreed its in the pipe
