### ISSUE TITLE
UX: Create account button on website even when already logged in

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2581]
### Basic information
* Platform: `Web`
* System/Browser: `any`

This is an user experience nuisance.
The current (and the previous) version of the website shows a button "create account" even when the user is already logged in an obviously has an account already. I'd only show this button, if the user is logged out.

**Comment by gyllen** [comment]
@mxa Is this on the front page?

**Comment by mxa** [comment]
Yes. It is probably intentional, but i find it irritating.

Am 30. Mai 2017 21:53:23 MESZ schrieb Johan Gyllenspetz <notifications@github.com>:
>@mxa Is this on the front page?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mapillary/mapillary_issues/issues/2581#issuecomment-304989237

-- 
Max Neupert

**Comment by gyllen** [comment]
@amahon Thoughts on this?

**Comment by katrinhumal** [comment]
This has been noted down internally to be handled at some point. Since it's not a blocker from using Mapillary, closing the issue here.
