### ISSUE TITLE
Capture sequence can't be stopped in Android v3.58-SNAPSHOT2 

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2582]
### Basic information
* Platform: `Android` 
* Version: `4.1.2` 

### Steps to reproduce behavior

 1. Start capturing in automatic mode
 2. After a few hundred photos press the stop button.
 3. Mapillary doesn't stop capturing

### Expected behavior

Stop capturing

### Actual behavior

When the stop button is pressed Mapillary shows this:

![screenshot_2017-05-27-12-48-10](https://cloud.githubusercontent.com/assets/12451224/26561242/0aa644c0-44bd-11e7-8754-ee5de7ac6b41.png)

The information disappears and Mapillary keeps taking pictures. Everytime you press the stop button the weird gps accuracy information is shown for a few seconds. The only way to stop capturing is to press the back button on my device (Samsung Galaxy S2).

**Comment by jfburke3** [comment]
Just additional data for the developers:  I have not encountered this problem.  Samsung Galaxy S7 Edge, Android 6.0.1.  I took several thousand images this weekend and was able to stop/start them just fine.

**Comment by ovivoda** [comment]
@ArAge67 Can you still reproduce this issue on the latest app version?

**Comment by ArAge67** [comment]
@ovivoda Sorry for the delay. The rear camera of my SGS2 had a huge dust particle so I couldn't use it anymore. Yesterday I fixed it by replacing the rear camera. Today I made several sequences and Mapillary 3.95 didn't have this problem anymore. Thanks!

**Comment by ovivoda** [comment]
@ArAge67 Thanks for the updates. Will close this one for now. If you see this issue again please reopen it and send some logs back.
