### ISSUE TITLE
Random time order in upload tab

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2583]
### Basic information
* Platform: `Android` 
* Version: `4.1.2` 

### Steps to reproduce behavior

 1. Capture a sequence
 2. Browse the upload tab and review your captured photos
 3. Captured photos are not always in time based order

### Expected behavior

Captured images should be in the correct time order.

### Actual behavior

See this screenshot:
![screenshot_2017-05-27-13-28-06](https://cloud.githubusercontent.com/assets/12451224/26561700/b2e4c7c6-44c0-11e7-874d-1afb8ee7f1be.png)

As you can see the photos are in random order. For reviewing this is very annoying. If for instance you want to delete a few 'double' photos, eg waiting for a traffic light, then it's important to have all photos in the correct time sequence otherwise you make mistakes.

This random order happens not only with version Android v3.58-SNAPSHOT2 but also in previous versions.

**Comment by jfburke3** [comment]
I've noticed the same thing.  Android 6.0.1, Samsung Galaxy S7 Edge.

**Comment by ArAge67** [comment]
This is still not fixed in v3.95. I can't use Mapillary if this problem still persists :-(

**Comment by davebrny** [comment]
this is still the case on both my xperia phones, android 6 and android 8. 

i really dont get how there are so many bugs going back years that still havnt being fixed. is there anyone working on these at all or is development for android on hold?

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
