### ISSUE TITLE
Latitude flipped to negative on single picture in sequence

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2585]
### Basic information
* Platform: `Android`
* Version: `3.58` 
* System/Browser: `Samsung Galaxy S 7`

I took a 288 image sequence this weekend using the Mapillary app. A single image in the middle of the sequence got transported into the middle of an ocean. The sequence splitter came through and split the sequence into 3 parts. I assumed the phone glitched and somehow the GPS coordinate got set to 0,0 so I submitted an edit to delete the single image sequence. However later I realized that it was not actually at 0,0 but rather in the southern Pacific ocean. After eyeballing it, it looks like the longitude was actually correct and the latitude just got flipped from positive to negative.

The sequence delete edit already got approved but through the miracle of caching, the image is still showing up on the world map so I was able to get a screenshot and the photo ID: `GiixGBIRECzyzWpZis-hvQ` Not sure if you will be able to do anything with this considering the deletion but @jesolem asked if I could open up an issue when I mentioned it on Slack soo... here it is :)

The photo immediately preceding the one that got flipped is: https://www.mapillary.com/app/?pKey=qUT3IRSioe8Hdd3Csl0wVA and the one after is: https://www.mapillary.com/app/?pKey=q5WBw5A5VXwkMZQPQlLfhA

Screenshot with a line between the (approximate) actual location where I took it and where it shows up on the world map:

![mapillary_latitude_flip](https://cloud.githubusercontent.com/assets/348948/26606077/2771781a-4556-11e7-9361-07327c526b0f.png)

**Comment by katrinhumal** [comment]
@ToeBee have you seen any more of this since?

**Comment by ToeBee** [comment]
I have not... although I don't think I have used the Mapillary app very much since I opened this issue. I do most of my capturing with an action camera.

**Comment by katrinhumal** [comment]
@ToeBee hehe that's nice :) Do you want to do a little test run? It should be fixed now but would be nice to get more evidence for that.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
