### ISSUE TITLE
Website: upload count invisible depending on sat-imagery background

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2586]
When uploading, the current/total count is invisible depending on the contrast to the satellite imagery background. As usual, eye candy intended but lack of functionality. 
![upload_progress](https://cloud.githubusercontent.com/assets/8266355/26608219/b8e19aac-459a-11e7-835a-435734ed708a.png)

**Comment by katrinhumal** [comment]
@polarbearing thanks! I will pass this feedback on for future developments of the uploader.

**Comment by katrinhumal** [comment]
This has been fixed by now.

<img width="420" alt="screenshot 2018-07-09 22 08 33" src="https://user-images.githubusercontent.com/16334352/42470987-d8d4a426-83c4-11e8-94db-af09a5effda9.png">
