### ISSUE TITLE
Picture resolution settings have no effect

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2587]
### Basic information
* Platform: `Android`
* Version: `3.56 snapshot` 
* Phone: 'Sony Xperia Z5 compact'
* System/Browser: `not applicable'

### Steps to reproduce behavior

 1. Produce a series of sequences with different settings of the four possible combinations of the settings of the two toggle switches labelled "Take low resolution pictures" and "Take high resolution pictures", i.e. off-off, on-off, off-on, on-on. Take a fixed number of (nearly) identical photos with each of the four settings
 2. put the microSD card in the computer
 3. check the file sizes of the pictures

### Expected behavior

I expected the pictures in the same series to have (nearly) the same size (in kB), but pictures from different series should have different sizes.

### Actual behavior
All pictures are (nearly) the same size 

### Additional question:
I do not understand why there are two toggle switches for changing the picture resolution (and hence file size).  In particular what does it mean if I take pictures with both the low resolution and the high resolution options set at the same time.

**Comment by katrinhumal** [comment]
@voschix We just released 3.59 with a fix for the resolution settings to work again. Please try and let us know! There is also only one option for low-res setting in that version. @ovivoda has more information on this change.

**Comment by ovivoda** [comment]
@voschix Does this work now?

**Comment by voschix** [comment]
Sorry, I forgot to answer.: I now can get two different sizes of pictures.  And the duplicated setting possibility has been removed. Looks OK now. Thanks

**Comment by ovivoda** [comment]
Thanks @voschix Closing it down now.
