### ISSUE TITLE
Website thinks WebGL isn't enabled in Chrome

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#2588]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: Windows 10 Chrome

### Steps to reproduce behavior

 1. Open Chrome
 2. Go to Mapillary website
 3. Click on Explore places
 4. Be greeted by error message

### Expected behavior
See map like usually

### Actual behavior
Error message appears:
Your browser does not support WebGL or it’s not enabled. To experience Mapillary, you need WebGL. Please enable it and try reloading this page.

### Additional information
I looked into chrome://flags and there WebGL was set as default, I put it to enabled and relaunched and still got error. Enabled experimental WebGL setting and relaunched and error persisted.
... 

![image](https://cloud.githubusercontent.com/assets/4370958/26750119/667f221c-480a-11e7-9455-9c4e3baf844a.png)

**Comment by gyllen** [comment]
@Stalfur Thanks for reporting, elevating

**Comment by nickplesha** [comment]
@Stalfur Thanks for reporting this. Can you please visit https://get.webgl.org/ and https://www.mapbox.com/mapbox-gl-js/example/check-for-support/ and  check what it says? It might help us pinpoint where the issue is occurring.

**Comment by Stalfur** [comment]
This turned out to be a Chrome issue.

I was doing things with OBS and a new version of it didn't work with Chrome, had to disable hardware acceleration. To be able to view WebGL I had to enable hardware acceleration again.

False alarm.
