### ISSUE TITLE
Pause on face-down not working

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2589]
### Basic information
* Platform: `Android`
* Version: `3.59` 
* System/Browser: not applicable
* phone: Sony Xperia Z5 compact

### Steps to reproduce behavior
In Settings > Capture > Pausing,  enable "pause on face-down"

### Expected behavior
Capture stops when the smartphone is pointing to my shoes

### Actual behavior
Shooting continues (in distance-based and in timed capture modes)

### Additional information
This used to work last year with the "old" app

The same applies to pause while tilting

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
