### ISSUE TITLE
Problem on extended drives Android

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#259]
I noticed on my long 13 hour drive out east that when the mapillary folder gets around 4-5 thousand photos, the app starts lagging while taking photos.  When my folder reached 16k photos, the app said it could no longer save to the folder. I'm not sure if the app reads the whole folder, but it cannot handle a lot of photos. The only way around it was to rename the folder by appending a number to it and recreating the folder. If its an android issue would it be possible to create a subfolder for each sequence as this could bypass the issue.

**Comment by peterneubauer** [comment]
So,
is this still an issue with the new app? If yes, there is a new trace file option under developer settings that will make Mapillary to write its own logfile. Feel free to try it and send the logs!

**Comment by james2432** [comment]
i'm not sure, i'd have to drive around until I get to about 4-5 thousand photos again. Will try to organise a trip that will take that many photos and report back

**Comment by james2432** [comment]
The likely hood of it happening has been decreased, as you seem to create a folder per sequence now. I will put 4000-5000 photos in the folder and see what happens to the application and report back
