### ISSUE TITLE
Mapillary Android never relinquishes location

### ISSUE THREAD

**Issue by gappleto97** [mapillary/mapillary_issues#2591]
* Platform: Android
* Version: 7.1
* System/Browser: Android 7.1 (Nexus 6P, LineageOS)

### Steps to reproduce behavior

 1. Go to any tab other than Explore and Capture, OR
 2. Minimize the app in any tab other than Explore and Capture, OR
 3. Exit the app using the back button and confirming exit

### Expected behavior

Mapillary should stop requesting location services

### Actual behavior

You have to manually kill Mapillary for the GPS to turn off

This is a rather large problem, because it means that you cannot upload without having your device plugged in. After playing around a little bit, this appears to be a bug in the Explore menu, but I cannot be sure. In any case, I would *greatly* appreciate it if you made it your *explicit* policy to not request location services when it is not needed.

**Comment by HolgerJeromin** [comment]
You can kill mapillary on upload as the uploading is done on a background service. But yes, this kills my battery.
The app "[GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2)" can show an Icon in the notification bar when an application uses GPS.

**Comment by gappleto97** [comment]
This is still a problem in the latest version. Every time the map shows up, it demands location, and never releases.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
