### ISSUE TITLE
Please consider give us more information about how to register a client ID

### ISSUE THREAD

**Issue by icemagno** [mapillary/mapillary_issues#2592]
Please consider give us more information about how to register a client ID.

I came from here:

https://www.mapillary.com/developer/api-documentation/#client-id

and them here:

https://www.mapillary.com/app/settings/developers

and the "Register an application" form give me a few options I don't know how to fill. After a lot of tests I'm still reciving errors when using the v3 API.

IMPORTANT: I'm developing an application to the Brazilian Navy and have NO website nor callback URL to give since it is a JavaEE application consuming the services behind a military proxy.

The v1 API was nice:

```
public synchronized String getPhotosInBBOX(String minlat, String minlon, String maxlat, String maxlon, String maxresults) throws Exception {
		WebClient wc = new WebClient();
		String url = "http://api.mapillary.com/v1/im/search?min-lat="+minlat+"&max-lat="+maxlat+
				"&min-lon="+minlon+"&max-lon="+maxlon+"&max-results="+maxresults+"&geojson=true";
		
		String result = wc.doGet(url);
       }
```

**Comment by gyllen** [comment]
Hi @icemagno 

We are thinking about how to make this easier to understand. To start with you can just fill in dummie values on those two settings. As long as you are not planning to use any oauth they do not matter.

For using our API `v1` and `v2` are deprecated. What errors are you receiving from the `V3` API?

**Comment by gyllen** [comment]
Adding a client_id box is now redesigned
