### ISSUE TITLE
Blurring/unblurring not possible in top part of picture

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2594]
### Basic information
* Platform: `Web`
* Version: `latest` 
* System/Browser: `Windows10/Firefox`

### Steps to reproduce behaviour

 1. draw a blurring rectangle anywhere in the photo aparto from the top 15% strip
 2. move it in the top strip
 3. try to cancel or move it

### Expected behaviour
A blurring rectangle in the top part of the picture should behave as in any other part of the picture

### Actual behaviour
Blurring activities are blocke in a horizontal strip at the top of the picture

### Additional information
I do not know if this is a new feature or if it has always been like that

...

**Comment by katrinhumal** [comment]
@voschix thanks for reporting! We changed mouse handling in the MJS update last week and this is, unfortunately, causing the problems you have with blurring. Will be working on a fix!

**Comment by nickplesha** [comment]
@voschix This issue is fixed now, blurring should work properly near the top of the image.
