### ISSUE TITLE
Mapillary 3.59 doesn't upload

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_issues#2596]
### Basic information
* Platform: `Android`
* Version: `3.59` 
* System/Browser: `Android 4.2.2` same model as [issue 2416](https://github.com/mapillary/mapillary_issues/issues/2416)

### Steps to reproduce behavior

 1. Start upload

### Expected behavior

Upload images and sequences

### Actual behavior

shows "Upload in Progress" but nothing happens,
written "E/ Exception while preparing file" and "Not a Valid TIFF File" in log file.

### Additional information

See attached log file and captured image.

[Verstion 3.56 worked fine.](https://github.com/mapillary/mapillary_issues/issues/2416)

![2017_06_11_12_03_28_241](https://user-images.githubusercontent.com/2560699/27059557-07cff0ba-5012-11e7-8d6b-2914d219635a.jpg)

[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1069835/mapillary.log.txt)

**Comment by jfburke3** [comment]
Just a comment for the developers that I am not encountering this problem on Samsung Galaxy S7 Edge, Android 6.0.1.

**Comment by kudarisenmon** [comment]
debug log on version 3.61
[Uploading mapillary_trace.txt…]()

**Comment by kudarisenmon** [comment]
debug log on version 3.61
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/1103660/mapillary_trace.txt)

**Comment by kudarisenmon** [comment]
debug log on version 3.64
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1116737/mapillary.log.txt)

**Comment by kudarisenmon** [comment]
debug log on version 3.65
[mapillary-3.65.log.txt](https://github.com/mapillary/mapillary_issues/files/1134131/mapillary-3.65.log.txt)

**Comment by kudarisenmon** [comment]
debug log on version 3.71
[mapillary_trace (1).txt](https://github.com/mapillary/mapillary_issues/files/1167347/mapillary_trace.1.txt)

**Comment by peterneubauer** [comment]
@kudarisenmon do you have a lot of these files? Will test with the one you uploaded. Is that one taken with the Mapillary App?

**Comment by kudarisenmon** [comment]
@peterneubauer 
I have deleted the photos on my SD card.
(I uploaded them by mapillary_tools python script)
I am going to take photos with version 3.72 at this weekend.

**Comment by peterneubauer** [comment]
Ok, was it a lot of photos that didn't upload via the app or just this one?

**Comment by kudarisenmon** [comment]
I take photos with version 3.75-BETA
A lot of photos are not uploaded after app throws exception.
Here is that photo.

https://drive.google.com/file/d/0B9OL2ctJGhoUM3Z0MXpIRW5aMTA/view?usp=sharing

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/1184543/mapillary_trace.txt)

**Comment by peterneubauer** [comment]
@kudarisenmon have youo been taking these images in another timezone? They seem 7h offset to teh GPX track?

**Comment by kudarisenmon** [comment]
@peterneubauer 
I took photos in Japan at around 28th July 14:09. 
The timezone is "Asia/Tokyo (+9:00)".
The first trkpt's timestamp in GPX file is 2017-07-28T05:08:25.358Z and it's added for 9 hours, it'll be 14:08:25.
Is something wrong?

**Comment by peterneubauer** [comment]
No, nothing wrong. However, in order to upload the images, please set your phone timezone back to Japan so the images time gets back to the GPX track and can be matched and uploaded. We are fixing the issue with the images times being in localtime right now.

**Comment by kudarisenmon** [comment]
Version 3.83-BETA works fine.
Thank you.
