### ISSUE TITLE
Black images

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2598]
### Basic information
* Platform: Web
* Version: 
* System/Browser: Windows 7 / Chrome

I came across a recent sequence of mine that is both stationary and completely black.  Not sure what happened, but thought I'd report it in case it's fixable.

Start playing the sequence from here:
https://www.mapillary.com/map/im/gGQClA0yZDvyZ2giFTR_Pg

**Comment by gyllen** [comment]
@jfburke3 Did you use the web uploader or any of our apps to capture these images?

**Comment by jfburke3** [comment]
I used your app to both capture and upload.  I'm not sure which version it was, though.  You can probably figure that out from the dates of the images.

**Comment by gyllen** [comment]
@jfburke3 Was it Android or iOS?

**Comment by jfburke3** [comment]
Sorry, Android 6.0.1, Samsung Galaxy S7 Edge.

I didn't mention all of that at the beginning because I assumed it was a website problem.

**Comment by gyllen** [comment]
@jfburke3 Thanks for info

@ovivoda Can you check this out?

**Comment by jfburke3** [comment]
Just a note that I haven't seen a recurrence of this.

**Comment by stev391** [comment]
I have the same issue.  See sequence: HZYnE4XtI01fRzV5TV1XcQ

Not sure what version that one was, but just returned from a drive and noticed that a sequence that is set to upload contains a mix of good and black images.  Once it is uploaded I will post the sequence number.
Mapillary Version 3.72-BETA
Device: Samsung S7  (SM-G930F), Android 7.0
I just sent the logs via the app, so hopefully they capture the issue.

**Comment by ovivoda** [comment]
@jfburke3 @stev391 Is this still happening with the latest app version as well?

**Comment by ovivoda** [comment]
@stev391 Thanks for the quick reply. 

Do you have any other write problems on that SDCard? Do you also get black images if you capture in the internal phone memory?

**Comment by jfburke3** [comment]
@ovivoda Yes, it's still happening with recent versions. I'll try to provide a link to examples tomorrow. 

I have the app configured to use the SD card. I don't have enough free space on internal memory to use it.

**Comment by gyllen** [comment]
@millenbop @ovivoda ^^^

**Comment by millenbop** [comment]
@jfburke3 my suspicion is that it's a memory card problem, either it's not healthy or it's too slow. Do you have another card you can try? Would it be possible to just do a very short sequence where you save to the internal memory?

Would be helpful to be able to rule out the card.

**Comment by jfburke3** [comment]
@millenbop I have 805 MB of free space on internal storage right now. Pretty much all of that is system/apps. I keep all my data on SD.

My SD card is a Samsung EVO+ 256GB UHS-1 microSDXC U3. (NOT the "Select" line, and it is UHS-1, not UHS-3, which should still be plenty fast.)

I don't have a spare SD card to try.   Another test would be to figure out about when this started happening and try an earlier version of the Mapillary app.

**Comment by jfburke3** [comment]
On the subject of previous app versions, let me note that before @ovivoda joined, there were several releases which had severe GPS lock problems. That was one of the early things he fixed. So, if im going to try an older app version, I'd like it to at least be one that he fixed that problem in.

**Comment by grinapo** [comment]
Thanks for pulling me here. Sharing my opinions.
I have noticed that S7 Camera API2 loves to behave weird. There is an example using OpenPhoto where opening the API resulted a black image, but otherwise it acted like everything's okay; happened once, so far. I have also noticed that using API2 results a significant delay before OpenPhoto is able to display the cam image (around 3-6 seconds sometimes).

Apart from these I haven't got recent problems in _Mapillary_. Even my other referenced issue isn't present nowadays.

**Comment by millenbop** [comment]
@jfburke3 how many photos do you have to take before they end up black? is it easy for you to reproduce the behavior on the external card?

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
