### ISSUE TITLE
stray images and negative image count are confusing

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2599]
Android app 360 from app store

I have no idea what stray photos are. I also have negative count of images to upload.
After upload and no more images i want an empty upload tab.

![rps20170615_224437_242](https://user-images.githubusercontent.com/2410353/27201002-434a4526-521c-11e7-9312-221fed51ba90.jpg)

**Comment by voschix** [comment]
On June 10 I had twice the same problem. Android 359.

**Comment by gappleto97** [comment]
Also having this issue

**Comment by HolgerJeromin** [comment]
Version 361 uploaded some mb and cleaned up the list. Thanks.
