### ISSUE TITLE
add prefs to autostart recording (if autorecord mode, cycling or foot)

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#260]
If my last mode was cycling/car (and not panorama or foot) i want to start recording direct after clicking "take me to the camera".
With this option i am faster back recording after a crash of my camera driver.

**Comment by jesolem** [comment]
Still an issue?

**Comment by HolgerJeromin** [comment]
starting a sequence is not available anymore while driving. Stop and restart sequence requires two clicks but it is intuitive.
