### ISSUE TITLE
erratic behaviour on the main map

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2600]
using the main map on the webpage, the behaviour is quite erratic.
using this in firefox on a laptop, both usb mouse and the trackpad.

zomming in, it sometimes zooms out, either the same amount or a little bit. same with zooming out.
panning, it sometimes "glides" back in the direction i came from.

happens pretty much constantly.

**Comment by voschix** [comment]
Same for me on Windows 10 with Firefox, Chrome, and Edge.

**Comment by eugensim** [comment]
same for me as above.

**Comment by ToeBee** [comment]
I have seen this too. Chrome on windows, Firefox on Linux Mint.

**Comment by ToeBee** [comment]
Screen cap of it in action. I was trying to zoom in on New York. It took 3 tries to successfully zoom in without the page deciding to unzoom me against my wishes. 
![mapillary_yoyo](https://user-images.githubusercontent.com/348948/27302491-e03a41fa-54fc-11e7-9acb-b48726af1080.gif)

**Comment by katrinhumal** [comment]
Thanks for reporting, all! We're aware of the issue and working on a solution. Hope to get this fixed soon.

**Comment by katrinhumal** [comment]
A fix is out for that now so hopefully, no more bouncy map. :)

**Comment by richlv** [comment]
yey, working much better now - thank you a lot :)

**Comment by katrinhumal** [comment]
Thanks go to @nickplesha here! 🏆
