### ISSUE TITLE
Leaderbord "stats not available at this time"

### ISSUE THREAD

**Issue by PRBS35** [mapillary/mapillary_issues#2601]
### Basic information
* Platform: `Web`
* System/Browser: `last version of Chrome, Firefox on Windows`

### Steps to reproduce behavior

 1. Go to "Leaderbord"
 2. Search for your area (country, region, locality, etc.)

Since a few days I always get a "Stats not available at this time".

![screen shot 06-20-17 at 12 59 pm](https://user-images.githubusercontent.com/21849601/27330082-47570d08-55b8-11e7-9a3e-dfc979ebc2f0.JPG)

### Additional information

The Leaderboard is available at a worldwide level ("Users" and "Organizations").

**Comment by gyllen** [comment]
@knikel I fixed some part of this issue yesterday, but we still need to remove this text from areas where the stats are actually working. Can you elevate this issue?

**Comment by knikel** [comment]
This has been fixed. There are few shapes in the system with invalid shapes, so these will display the message. Existing shapes should not display this.
