### ISSUE TITLE
In seqence view image direction does not rotate with map

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2602]
### Basic information
* Platform:  `Android` 
* Version: `3.60` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. On the upload tab open a sequence
 2. Switch on and wait for map to show
 3. Rotate the map

### Expected behavior

Direction of image on map should keep pointing in correct direction wrt. map

### Actual behavior

Direction of image is static wrt. to screen

### Additional information

![screenshot_2017-06-20-22-28-41](https://user-images.githubusercontent.com/1165786/27354489-0f16517e-5608-11e7-917e-37b4cc2dcd4e.png)

![screenshot_2017-06-20-22-28-33](https://user-images.githubusercontent.com/1165786/27354512-1de131b0-5608-11e7-9358-5e035880cc94.png)

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
