### ISSUE TITLE
Mapillary App 4.7.5 crashing after camera is selected

### ISSUE THREAD

**Issue by avataryt** [mapillary/mapillary_issues#2604]
### Basic information
* Platform: `iOS` (iOS 10.3.1/iPhone 6 as well as 10.3.2/iPhone 7)
* Version: `4.7.4` 
* System/Browser: `iPhone 6`

### Steps to reproduce behavior

 1. Starting app
 2. Using the app: everything works fine, besides...
 3. Clicking on the camera button: The camera screen shows up without a camera image (screenshot attached). It does show the overlay graphics and the GPS arrow is blinking once. App will crash in 1 second or less and returns me to my home screen.

### Expected behavior

App should not crash but show the camera/capture screen.

### Actual behavior

App crashes after starting the camera/capture screen, sending me back to my iOS home screen.

### Additional information

Happens on both my phones (iPhone 6, iPhone 7). I tried to activate/deactivate WiFi and airplane mode. Both without any effect.

![5766cd73-702d-4157-97cc-c861cb2eee66](https://user-images.githubusercontent.com/147706/27637736-0aa8377e-5c11-11e7-8c96-94469c18a3f3.JPG)

**Comment by millenbop** [comment]
I found your crash report. For some reason your userUUID is missing and it crashes when it tries to do something with it.

We have had some problems with the backend the past few days. Could you try to logout and login again? That should set the userUUID correctly.

I just tried with email and Facebook and both work to login with.

**Comment by avataryt** [comment]
Thanks for the quick response and help. I logged out, wasn't able to re-login via Facebook (haven't looked further into this), but I was able to re-login with my mailaddress/password combination. This did fix the problem, the app is now working as intended.

**Comment by millenbop** [comment]
Cool, great to hear!

But I should look into the Facebook problem. Can you log in on the web using Facebook?

**Comment by avataryt** [comment]
I was not able to login via Facebook via the web. After logging in via email/password I (re)connected Facebook and verified that Facebook login is now working for me as well via web as via the app.

I can't say with 100% certainty that I had used Facebook login before - so it simply might have been the case that my FB account was not connected. But it does work now. Thanks again for your help, thumbsup!

**Comment by millenbop** [comment]
Ah yes, could be that. We will revamp the login thing, it's on the roadmap. 

Thanks for testing! Much appreciated.
