### ISSUE TITLE
Web uploader not counting right, feedback on uploads is non-sensical

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#2606]
### Basic information
* Platform: `Web`
* System/Browser: `Windows, Chrome`

### Steps to reproduce behavior

 1. Pick 1000 images and do review
 2. Click Plus button
 3. Pick another 1000 images and do review
 4. Uploader now says "upload 1000 images" instead of 2000
 5. Start upload - counter will not count while first batch is being uploaded (I'm presuming - no idea since no feedback)
 6. Periodically get website+app+email notifications about a random number of images having been processed

### Expected behavior
Correct count of images in queue and uploaded
When I upload 1000 images I want to know when that batch has been finished, not get it in 50 notifications where I learn that 25, 5, 8, 232 etc images were processed - that makes no sense especially when I have multiple 1000s of images already uploaded or in queue.

### Actual behavior
Counter doesn't move,
I might have uploaded same batches twice since they didn't count when uploader was counting behind the scenes.

### Additional information
I'm uploading in batches of 1000 and this is the feedback
![image](https://user-images.githubusercontent.com/4370958/27701133-4368505e-5d00-11e7-8fe8-cc710fc9e42b.png)

**Comment by gyllen** [comment]
@nickplesha This counting bug should be easy to fix.

@Stalfur In general we do not recommend you uploading more than 1000 image per upload in the webuploader though. Have you tried out our scripts?

**Comment by nickplesha** [comment]
@Stalfur We've made improvements to the upload so this should be resolved. Let us know if you encounter any issues with uploading again.
