### ISSUE TITLE
Certificate expired on https://legacy.mapillary.com/map/login

### ISSUE THREAD

**Issue by SanderH** [mapillary/mapillary_issues#2607]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome`

### Steps to reproduce behavior

 1. Access https://legacy.mapillary.com/map/login
 2. Browser indicates the page is insecure
 3. View the properties of the certificate and see it was only valid until 2017-06-27

### Expected behavior

Valid certificate

### Actual behavior

Expired certificate

### Additional information

![image](https://user-images.githubusercontent.com/5428967/27747460-803babc2-5dcb-11e7-963f-b01611a4c091.png)

![image](https://user-images.githubusercontent.com/5428967/27747434-61dec286-5dcb-11e7-8798-3b64c5dac66d.png)

**Comment by gyllen** [comment]
@martinskans We need to update cert on legacy too

**Comment by martinskans** [comment]
It doesn't enforce https either so, http://legacy.mapillary.com works.

**Comment by martinskans** [comment]
I have updated the certificate but I think it gets cached somewhere so it still says cert error. I will check in a little while again.

**Comment by martinskans** [comment]
It didn't replace the certificate outwards until I restarted the services for some reason, but now it's fixed.
