### ISSUE TITLE
Not all "place=suburb" are found

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2608]
### Basic information
* Platform:  `Web`
* Version: `...` 
* System/Browser: `any`

### Steps to reproduce behavior

 1. search for location "Voltabarozzo"

### Expected behavior
I expect that the suburb "Voltabarozzo" in Padova , Italy is among the search results

...

### Actual behavior
 the suburb "Voltabarozzo" in Padova , Italy is not among the search results

...

### Additional information
If I try to search for "Au-Haidhausen" (a suburb of Munich, Germany) Mapillary search does find it.
"Au-Haidhausen" has an "is_in" tag; "Voltabarozzo" does not have it.
It seems that Nomatim is missing suburbs without "is_in" tag

**Comment by gyllen** [comment]
@voschix Thanks for reporting, unfortunately there is nothing we can do about this since we are using an external service (Mapzen search) for the search.

I recommend that you file a bug in this project https://mapzen.com/products/search/
