### ISSUE TITLE
Annoying shutter sound

### ISSUE THREAD

**Issue by gmng** [mapillary/mapillary_issues#2609]
Please remove the annoying shutter sound from the android app.
I can't use the android application just because of this terrible sound.

ALL mobile phone has the ability to turn the shutter sound OFF. Why Mappillary force this stupid thing in the app... Please!

**Comment by polarbearing** [comment]
Well there used to be a Camera setting in the app to switch it on/off, which however requires a min android version to work. 
What annoys me extremely is that when I switch it on to get an audible confirmation, it comes with that terrible metal-mechanical-shutter imitation, instead of a decent short nice technical 'beep' or 'bing'

**Comment by voschix** [comment]
@gmng:
You can turn it of in Settings of the app, at least on Android (from version 4.2 onwards)

@Mapillary:
Please do not remove it. It is ok that it is  optional. For me it is essential on the bicycle to know that the picture taking is still working. And please do not change the sound to some other pling or beep or whatever. It's fine that a camera makes a shutter sound.

**Comment by gmng** [comment]
@voschix 
I already switched it to OFF (greyed out the switch in Settings > Camera > Make shutter sound) but the sound is still ON!
Is it a bug?
I have android 6.0 based stock ROM.
I tried to plug in a 3.5mm jack, and also with the volume keys to zero sound but it is just still making this terrible sound.
I do not want them to remove this option but it is not working - at least for me.
It is OK that it is optional, if it worked.

**Comment by voschix** [comment]
@gmng: this looks like a "feature" of your phone-OS-app combination. Do you have any sound problems on other apps on the phone?

**Comment by gmng** [comment]
No, everything working ok afaik.
LETV the manuf. of the phone and OS.

**Comment by polarbearing** [comment]
Well there could be a choice of sounds, or the selection of a sound file. A piercing metal-shutter for you, and a decent bing for me. :-)

**Comment by gmng** [comment]
@polarbearing 
It would be the best solution, and I could select a muted sound.

**Comment by echeloni2p** [comment]
Hi
some mobiles just do NOT allow to mute shutter sounds, e.g. Honor are those. You just cannot mute them with any settings, except a complete new rom.
Thats because of some countries do force the mobiles to make a shutter sound to porevent upskirt pictures.

echelon

**Comment by gmng** [comment]
@echeloni2p 

Ok, thanks for the info. 
I use a chinese stock ROM in Europe.

**Comment by gmng** [comment]
I tried the latest Mappilary android version, and I also installed a new stock ROM (latest for my phone) but the issue is still there. 
That would be a solution to this issue if the user can choose a custom sound file as @polarbearing suggested.

**Comment by echeloni2p** [comment]
Hi!

on some mobiles you would need a modified rom which includes "removed sound", using a stock rom does NOT help. As regulatory forces to create a shutter sound on taking pictures. Even the type of sound is forced. Nothing mapillry can do in this cases.
echelon

**Comment by gmng** [comment]
@echeloni2p 

That's sad. Thanks for the clarification.

**Comment by katrinhumal** [comment]
@gmng which phone model do you have btw?

**Comment by gmng** [comment]
@katrinhumal 
LETV Le 1S X500
v5.9.026 stock ROM
ANDROID 6.0

**Comment by katrinhumal** [comment]
Thanks! @ovivoda can you take a look please?

**Comment by ovivoda** [comment]
@gmng @polarbearing @voschix 

I implemented a workaround for this and I created a new build here. Would be great if you can try it out and let me know if this works for all of you:

http://android-releases.mapillary.io/Mapillary_Android_v3.96-SNAPSHOT1.apk

**Comment by gmng** [comment]
@ovivoda
https://i.imgur.com/BLsk231.jpg

**Comment by polarbearing** [comment]
I can switch sound on and off, however when on it is still the terrible fake-metal-shutter.

**Comment by ovivoda** [comment]
@gmng Thanks for notifying me on this one. Do you get notified about Mapillary being a suspicious app for v3.95 as well?

@polarbearing Thanks changing the default sound is on our research to do list. I do not have a clear date for that though

**Comment by echeloni2p** [comment]
Hey
just to note: with v3.96SNAPSHOT the annoying shutter sound is gone from my honor 7 chinese edt. Somehow you did find the secret entry to remove it^^
thanks.

echelon

**Comment by gmng** [comment]
@ovivoda 
I removed v3.96, installed v3.95 from PLAY. I did not get any notification from AVAST.

**Comment by ovivoda** [comment]
@gmng Thanks! Please try and install v3.95 from here and see if AVAST is complaining:

http://android-releases.mapillary.io/Mapillary_Android_v3.95.apk

I suspect is doing this because is an APK from outside GooglePlay.

**Comment by gmng** [comment]
@ovivoda
Avast gives me a warning if I install any app outside from PLAY. But after I removed v3.95 and downloaded from your domain mapillary.com it did not give me any warning like.
Strange, maybe your domain is white listed since yesterday. 
This is what AVAST shows as risk.
https://i.imgur.com/D7O1gTf.jpg

I will reinstall v3.96 to check it again.

**Comment by gmng** [comment]
I reinstalled v3.96 and  I didn't get any warning from AVAST like two days ago. I do not know what happend. I did not ignored or pressed anything when I first saw the warning, except the back button as cancel.

**Comment by ovivoda** [comment]
Thanks @gmng !

**Comment by gmng** [comment]
@ovivoda 
The shutter sound gone. Thank you!
(tiny bug. Totally different issue. When I capture a sequence lets say with 150 images and then I delete manually the blurry images, lets say 20images, when I upload the sequence it displays "uploading 1 of 150, not 130.  Just a little bug, It doesn't re-count the images after I delete some.) 
Sorry for my poor english, I hope you understand what I wanted to say.
