### ISSUE TITLE
GPS data not transferred to GoPro Hero Session 4 images

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2610]
### Basic information
* Platform: `iOS`
* Version: `4.7.5` 

### Steps to reproduce behavior

 1. Connect the GoPro Hero Session 4 to the Mapillary app
 2. Start biking and record images in two different sessions
 3. Look at the map while recording, everything seems fine
![img_3685](https://user-images.githubusercontent.com/1651235/27819634-6e0b6a14-609b-11e7-9df1-556c21b2a1e1.PNG)
4. Stop biking, stop camera
5. Transfer images

### Expected behavior
Images are correctly geolocated

### Actual behavior
All images are in one sequence ([Fr24yw-DkkSsfSJXyb3HBg](https://www.mapillary.com/app/user/habi?lat=46.939167547924285&lng=7.4175853186873155&z=17&pKey=zNgTTl4m8VNWM5C63I69LQ&focus=photohttps://www.mapillary.com/app/user/habi?lat=46.939167547924285&lng=7.4175853186873155&z=17&pKey=zNgTTl4m8VNWM5C63I69LQ&focus=photo)), which is very close to where I started.
All images are squashed together over a straight line of about 10 m distance, as seen in the screenshot below.
![img_3688](https://user-images.githubusercontent.com/1651235/27819663-8e391994-609b-11e7-90d4-dc44a3884dce.PNG)

### Additional information
The new GoPro connection method does not really work, while the old (theoretically unsupported version) [worked nicely/as expected](https://github.com/mapillary/mapillary_issues/issues/2546#issuecomment-297516227), as said before.
As it is, Mapillary is essentially unusable for me on my bike.

**Comment by habi** [comment]
For kicks I tried again, after formatting the SD card and resetting time and date with the GoPro Capture app.
Same (wrong) result: [SSSsOFVHbfRMqRbW_yMfZA](https://www.mapillary.com/app/user/habi?lat=46.95182519529004&lng=7.429945489104966&z=17&pKey=kLdYdH8TewZPo45Q0NRa6A&focus=map)

**Comment by katrinhumal** [comment]
@habi thanks for reporting this! @millenbop is currently on holiday but he will take a look as soon as he gets back.

**Comment by millenbop** [comment]
Perhaps the SDK will fix this issue in the future. I have reverted the time/date setting to use the old method (i.e. not using the SDK) for now so it should behave as before.

Will be out in the next release.

**Comment by habi** [comment]
Not fixed, see https://github.com/mapillary/mapillary_issues/issues/2546#issuecomment-331806645
