### ISSUE TITLE
'Add Camera UI' cut off on iPhone 5S

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2611]
### Basic information
* Platform: `iOS`, iPhone 5S
* Version: `4.7.5` 

### Steps to reproduce behavior
 1. Add Camera
 2. Try to look at the preview in the 'Add Camera UI', try to refresh preview or go back to the map view.

### Expected behavior
I can see and refresh the preview.

### Actual behavior
Sidebar overlays part of the UI, as shown in the (marked up) screenshot.

![img_3692](https://user-images.githubusercontent.com/1651235/27829257-0a54e5e2-60c1-11e7-8ae1-a1b619a632e1.PNG)

**Comment by katrinhumal** [comment]
@habi and thanks for this one as well - assigning to @millenbop for when he gets back from holiday.

**Comment by habi** [comment]
It seems that this has to do with the rotation of the iPhone.

Here's a screenshot when starting to capture.
![start](https://user-images.githubusercontent.com/1651235/28687024-7cb82122-730d-11e7-9cd3-86fb2809bcb0.JPG)

Here's a screenshot when the phone is rotated to the left (home button to the right).
![home button right](https://user-images.githubusercontent.com/1651235/28687086-a4966fbe-730d-11e7-8867-2038a5f9ad91.JPG)

Here's a screenshot when the phone is afterwards rotated to the other side (home button to the left).
![home left](https://user-images.githubusercontent.com/1651235/28687146-ca00c6be-730d-11e7-8c24-f8ed12573fb9.JPG)

And the last one is when the phone is rotated back to having its home button to the right.
The capture button is now cut off...
![capture button off](https://user-images.githubusercontent.com/1651235/28687172-df9701dc-730d-11e7-8794-fac253c9a333.JPG)

**Comment by millenbop** [comment]
I'm back from vacation now! Thanks for reporting, I'll fix!

**Comment by millenbop** [comment]
It has been fixed now and will be out in the next release.
