### ISSUE TITLE
Serval Video Upload problems 

### ISSUE THREAD

**Issue by dr2okevin** [mapillary/mapillary_issues#2612]
I have serval video upload issuse which prevents me from uploading a lot of fotage.

- Very often uploaded videos are not processed.
- Very often the upload tool warns me about not syncronised gps (but gps is correct)
- Very often I cannot move the map marker in the upload form
- Sometimes videos are uploaded with wrong geo Informationen, sometimes combined with only one picture.

I use a dashcam for my videos. It is a Blackvue DR650GW-2CH. 
The video clips are 1 minute or less long.
Here is some media info from the raw video file.

> Format                         : MPEG-4
Format profile                 : Base Media / Version 2
Codec ID                       : mp42 (mp42/mp42)
File size                      : 46.3 MiB
Duration                       : 1 min 0 s
Overall bit rate mode          : Variable
Overall bit rate               : 6 364 kb/s
Encoded date                   : UTC 2017-06-21 16:49:03
Tagged date                    : UTC 2017-06-21 16:49:03

> Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.2
Format settings, CABAC         : Yes
Format settings, ReFrames      : 1 frame
Format settings, GOP           : M=1, N=30
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 1 min 0 s
Source duration                : 1 min 1 s
Bit rate                       : 6 296 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Frame rate                     : 30.000 FPS
Minimum frame rate             : 28.571 FPS
Maximum frame rate             : 30.303 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.101
Stream size                    : 45.8 MiB (99%)
Source stream size             : 45.8 MiB (99%)
Language                       : English
Encoded date                   : UTC 2017-06-21 16:49:03
Tagged date                    : UTC 2017-06-21 16:49:03
mdhd_Duration                  : 60967

The dashcam safes its position in a gps file. The file contains a unix timestamp and NMEA 0183 data.
**Exampel**
> [1498070941559]$GPVTG,216.93,T,,M,3.693,N,6.840,K,A*37
[1498070941559]$GPGGA,164859.00,5335.67162,N,00955.40497,E,1,10,0.95,26.2,M,45.1,M,,*63
[1498070941559]$GPGSA,A,3,27,10,08,18,16,21,15,30,07,11,,,1.56,0.95,1.24*0A
[1498070941559]$GPGSV,4,1,15,01,03,255,19,07,06,286,23,08,59,292,35,10,63,123,31*71
[1498070941559]$GPGSV,4,2,15,11,16,273,32,13,03,006,07,15,14,038,37,16,26,192,28*76

To upload all this stuff, I concatenate the video files as well als the gps files. I strip the timestamp off the gps file, and convert with the software "gpsbabel" the NMEA data to the gpx format.

The new video file looks like this.
> ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.2
Format settings, CABAC         : Yes
Format settings, ReFrames      : 1 frame
Format settings, GOP           : M=1, N=30
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 29 min 25 s
Bit rate                       : 6 290 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Frame rate                     : 30.000 FPS
Minimum frame rate             : 28.571 FPS
Maximum frame rate             : 31.250 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.101
Stream size                    : 1.29 GiB (99%)

I can see the correct track on the map, and play the video in the Browser, but very often that is the end. Moving the markers let's disappear them, and uploading the initial state (which is almost always correct) gets me to the problems described at the top of this ticket.

It would be nice if you could at least fix the upload and processing problems. It would be even better when ich can batch upload video files, including NMEA data instead of gpx.

Here an example for a sequence where only one image was picket, and placed at the wrong position. https://www.mapillary.com/map/im/2GMKP6GLrbTYkB4Sjr7GHA

Video Upload Screenshots
![grafik](https://user-images.githubusercontent.com/1845792/27879542-4e6c91b0-61c2-11e7-81e9-9fc6345c87b3.png)
![grafik](https://user-images.githubusercontent.com/1845792/27879557-6605dfac-61c2-11e7-9051-b6e8a50c9546.png)
Marker disappears 1 sec before end. 
![grafik](https://user-images.githubusercontent.com/1845792/27879717-cf17f43a-61c2-11e7-9c65-c7765bba7c55.png)

**Comment by gyllen** [comment]
@amahon Assigning this to you as for supporting video upload on regular webpage.

**Comment by Kaldea** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
