### ISSUE TITLE
First image of photo sequence is placed at end of sequence with correct GPS

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2613]
### Basic information
* Platform: `Android` | `Web`
* Version: `3.65` 
* System/Browser: `LG G2`

### Steps to reproduce behavior

 1. Create sequence of 600 images (not sure if it happens with shorter sequences)
 2. Upload via the app
 3. Wait until published
 4. View sequence in web UI

### Expected behavior

The sequence should start at one point, trace your way and then end at some other point.

### Actual behavior

Like expected, but the first image of the sequence is appended to the *end* of the sequence, basically creating a long line on the map. The GPS coords of the image are correct. Only the order of the images is broken.

### Additional information

Example sequence:
https://www.mapillary.com/app/user/umap?lat=48.11033414858534&lng=11.701155090057512&z=14.402101194503556&pKey=Ps69rbJx-wUtLreSHm7amQ

Apparently the `@sequence_cut` bot fixes this issue or deletes it. I'm not sure if that also happens if the end-to-start distance of a sequence is very small. I've had this issue for several days now, but for older sequences it apparently has been fixed.

This has not been introduced with the android app update from a few days ago. I observed it first just before the update in the previous version.

**Comment by voschix** [comment]
Are you sure that the positions are not shifted by one picture? That's what I had at least in one case.

**Comment by ulikoehler** [comment]
@voschix Good idea, but I don't think so, because the last picture is (judging from the optical similarity) clearly in approximately the same location as the last picture (I created these sequences on a bike with 2 seconds capture interval, so there is not a lot of distance between them). If the positions were only shifted, I'd expect pictures to appear at slightly offset locations, not a picture with (apparently) correct GPS coordinates at the wrong end of the sequence.

Still, the locations could be shifted anyway -- as the capturing interval equals to only a few meters - so I probably wouldn't notice the shift too much.

**Comment by ulikoehler** [comment]
Apparently the link from yesterday doesnt work any more. Here's a new sequence which is even stranger as it contains multiple lines across it:
https://www.mapillary.com/app/user/umap?lat=48.10273783811698&lng=11.713979229456214&z=17.872320304711412&pKey=OZ67X0inATbUIjlAQaia-Q

And here's the updated sequence from yesterday. Apparently the App added more images to it. Still, the straight line (basically from start to end):
https://www.mapillary.com/app/user/umap?lat=48.108894093867406&lng=11.702648340663586&z=13.78605579881675&pKey=z4I09n1PImrxlkLnwuC4uw

**Comment by ulikoehler** [comment]
Here's another one:
https://www.mapillary.com/app/user/umap?lat=48.1098222502238&lng=11.718388490345205&z=13.530260546107305&pKey=uTX01He4CAVCgaR3Y_eoHw

I'm still uploading ~100 images from yesterday, so I'm not sure how long the link will work.

**Comment by ulikoehler** [comment]
It seems like it's not *always* the first / last image, I've found a sequence (created 4 days ago, not sure when it was uploaded) which appears to have multiple issues.

https://www.mapillary.com/app/user/umap?lat=48.10521924810496&lng=11.729951583846542&z=13.70473585920739&pKey=8iU7nl58O8Eue2Qvveki9A

Here's a screenshot: http://i.imgur.com/4LGXJPb.png

To some extent all the issues seem to be fixed by `@sequence_cut`, but it seems to just create new sequences for the one or two images that are 'disconnected'.

**Comment by voschix** [comment]
here is another one: 
https://www.mapillary.com/app/?lat=45.372923263234725&lng=11.915300506725771&z=17&pKey=Bt6HtBo34uWiSfxDgxgSqA&focus=map&username%5B%5D=voschix&dateFrom=2017-07-09&dateTo=2017-07-09&menu=false

**Comment by voschix** [comment]
Here are five more in two days:
[https://www.mapillary.com/app/?lat=45.48794436965784&lng=11.62413135622927&z=11.733744568509376&menu=false&mapStyle=mapbox_satellite&username%5B%5D=voschix&dateTo=2017-07-12&dateFrom=2017-07-11](url)
One of them has the misplaced picture in the middle: [https://www.mapillary.com/map/s/ju5S6e-jN2x1JbZDYWCPWg](url)
What's going on? The only thing I noticed during upload, but I am not sure whether it regarded these specific sequences: I uploaded each sequence separately and had many cases of large numbers of stray images left over, for which I then launched again the upload, apparently successfully.

**Comment by ulikoehler** [comment]
This one has not been fixed by @sequence_cut since July 1

https://www.mapillary.com/app/user/umap?lat=48.073994818040774&lng=11.682853592661331&z=11.786498419893697&pKey=xbvD_59VX9oLVe3cbdmgmg

@voschix Regarding stray images, I encountered the same behaviour. Re-starting the upload from the app seems to work, and apparently the server also accepts them (not absolutely sure though).

**Comment by ulikoehler** [comment]
Here's a particularly extreme one with a lot of "detached" photos:
https://www.mapillary.com/app/user/umap?lat=48.09284751114345&lng=11.716117482556456&z=13.472546969532129&pKey=_SQi5WM7MjsDYE9bwyIzTw&focus=map&feedItem=user-pyQrwn2chXv57on5L40ZbA-affected_indirect_object-user-LJi1H04PTQCkgAYlCmFWCA-approved-changeset-image%3A1500896764837

**Comment by ovivoda** [comment]
This issue should be fixed in the latest version of Mappillary Android application
