### ISSUE TITLE
Memory leak in web viewer

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2616]
### Basic information
* Platform: `Web`
* System/Browser: `Chrome 59/Windows 10`

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/
 2. Let browser tab sit for a few hours (over night or while at work)
 3. Come back to a crashed tab 

### Additional information
This has been happening for a while. Last night I decided to leave a Mapillary tab open with the Chrome developer console running to see if I could pin down a reason. I came back to this. Note the warning in the upper right corner.

![screenshot 2017-07-07 19 25 10](https://user-images.githubusercontent.com/348948/27981070-d81b4cdc-634b-11e7-997c-23dd7dc8d9db.png)

According to the Chrome task manager the tab was consuming close to 3 GB of memory. When I tried to take a heap dump, the dev console crashed.

**Comment by ToeBee** [comment]
After a fresh load, the page takes about 170 MB of memory. Over the course of about an hour of just letting it sit there, it crept up to over 1 GB.

**Comment by drkludge** [comment]
I have experienced the same issue. Toby has performed the research. All I
know to do is close Mapillary tabs after I am done. Otherwise I can expect
that a crash is forthcoming.

On Jul 7, 2017 7:33 PM, "Toby Murray" <notifications@github.com> wrote:

After a fresh load, the page takes about 170 MB of memory. Over the course
of about an hour of just letting it sit there, it crept up to over 1 GB.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/2616#issuecomment-313828158>,
or mute the thread

**Comment by gyllen** [comment]
@nickplesha ^^^^

**Comment by jfburke3** [comment]
Just a comment that I've also experienced this, but hadn't done the necessary work to report it, so thanks to @ToeBee for his effort.

The problem also exists in Firefox and MSIE, but Chrome provides better a better tool for monitoring the state of the browser.

**Comment by nickplesha** [comment]
Thanks for reporting this, we'll investigate this issue. @drkludge @jfburke3 are you also running Windows 10?

**Comment by jfburke3** [comment]
I dual boot between Windows 7 and Fedora at home, and have Windows 7 at work, but i have access to a Windows 10 if you need something tested.

**Comment by ulikoehler** [comment]
On Chrome/Linux I've also noticed Mapillary getting slower over time.

Here's a chrome heap profile taken at https://www.mapillary.com/app/ in ~15 minutes:
https://pastebin.com/4mF9NQqU

**Comment by gyllen** [comment]
@nickplesha New information ^^^

**Comment by polarbearing** [comment]
Any action to fix this issue?
Watching the beast in Safari here, the related webkit process for mapillary consuming 1.2 Gigabytes during an upload. Upload stuck now.

**Comment by drkludge** [comment]
Is this related to #2819 and Mapbox’s vector map issue?

**Comment by nickplesha** [comment]
We've been continually making improvements to reduce memory usage in our code. The map component, however, can use up a lot of memory, depending on zoom level and location. Using a different map style (OSM for example) will reduce the memory usage significantly.

**Comment by jfburke3** [comment]
I may have discovered something interesting on this problem.  If I *don't log in* to the Mapillary website (e.g., just explore around and look at images and sequences as a visitor), then I don't seem to encounter the memory leak.  I can let the tab sit open for at least a couple of days with no discernible increase in memory usage.  

@ToeBee would you happen to feel like trying this out, too?  It'd be nice to see a comparable result from someone else who knows what the problem looks like.

**Comment by ToeBee** [comment]
@jfburke3, confirmed. I left an incognito window sitting over night and it is still fine this morning. It looks like it has stayed at around 200 MB of memory usage the whole time. But a normal tab that I left sitting where I am logged in crashed as usual.

**Comment by gyllen** [comment]
@nickplesha This is an interesting discovery, this could have todo something with getting the feed

**Comment by drkludge** [comment]
Relating to @jfburke3 post, I found a connection to the sites cookie use and this issue.  I used some images from wsp-us from the website.  About 24 hours or so later I received a message on twitter to follow wsp-us.  I went and reread the cookie policy. https://www.mapillary.com/cookies

> ...promote trust and safety.

First you are not telling the truth.  I don't see how a cookie is going to promote trust and safety.  In fact it feels more like you just violated that trust.

> With these devices, we collect data such as the identity of the applicable internet service provider, the user's IP address of his or her terminal device, the type of browser software and operating system in use, the date and time of site access, the website address, if any, from which the user linked to the Website, and other similar traffic-related information. We may also aggregate such information with similar data collected from other users and **_disclose such aggregate information to third parties_**.

And there is the connection that I drew--the violation of trust.  There could be a number of ways that twitter got the information except for the the close timing of using a wsp-us image and the email that followed shortly thereafter.   

> You are always free to decline Mapillary cookies via your browser settings, although doing so may interfere with your use of the Service. You may encounter cookies from non-affiliated third parties on certain pages of the service.

I followed the cookie page suggestion and blocked cookies from mapillary.com in my browser.  The memory leak went away.  I found this was a solution by accidentally leaving the Mapillary page up over night.  The browser was still usable the next morning.  Also note it is not true that blocking, "... doing so may interfere with your use of the Service."  The Mapillary.com site works much better now.  Thanks.

**Comment by gyllen** [comment]
@drkludge Thanks for brining this to our attention, we take this things very seriously and we are having an engineer investigating.

**Comment by jfburke3** [comment]
Hmm, the language in the policy doesn't necessarily bother me; it appears to be pretty standard.  And, if you think about it, if Mapillary were to contract with another company to provide some of their services, it might be totally necessary.

**Comment by jfburke3** [comment]
That the cookie might be the issue, though, is very interesting....

**Comment by nickplesha** [comment]
@drkludge Thanks for expressing your concerns. We've updated our privacy policy recently and done a thorough review of everything we do to make sure we are compliant with GDPR, you can read it here: https://www.mapillary.com/privacy. If you check the cookies section you'll see we use only two cookies and we use these two services only for the purpose of analyzing usage of the website and apps to be able improve the user experience and identify areas that users might have trouble with. We don't share your data with Twitter. Using any ad-blocker will prevent all tracking if you wish to do so.

We've also made improvements to improve performance in the web viewer and to eliminate any memory leaks so this issue is hopefully resolved for everyone. Let us know if you encounter problems in the future.
