### ISSUE TITLE
ios: "direction lock when moving fast" threshold is far too low

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2617]
### Basic information
* Platform: `iOS 10.3`
* Version: `4.7.5`

### Steps to reproduce behavior

 1. enable compass mode
 2. start capturing
 3. walk a few steps
 4. "*direction mode*" will switch from compass to GPS
### Actual behavior
iOS-App version 4.7.2 introduced a new feature that will use the GPS direction rather than the compass direction when moving fast. However the definition of moving fast seems to be a bit odd. Even if I'm walking through a park the app will switch to using GPS direction. Since I sometimes swing my phone to the left and to to the right to capture details beside the road this behavior is a bit annoying.

### Expected behavior
- Set the threshold to an higher value like 15-20 kph (seems to be ~ 5kph atm).
- Alternatively (or additional) add a feature to enable/disable the GPS-direction-feature manually.

**Comment by voschix** [comment]
I presume this feature is optional (I do not have access at IOS device). If it were mandatory I would see a problem with all those situations where people take photos by hand and not with a camera on a mount.

**Comment by descilla** [comment]
@voschix 
The release notes says:

> If you are moving fast and you have set your iPhone to use the compass (the default setting), we will ignore the compass value and instead use the GPS to calculate the heading. This reason to do this is because the compass most often is wrong when you are inside a vehicle. If you are in a car and you don’t point the phone forward, please set the offset in the app (i.e. point to the right, to the left etc).

However I've not found a button to disable automatic usage of GPS direction.

**Comment by millenbop** [comment]
Sorry weren't aware of this issue until now. I think the threshold is normal walking speed, i.e. 6 kph. I'll increase this to 15-20!

mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
