### ISSUE TITLE
ios: basemap settings seems to be ignored in capture mode

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2618]
### Basic information
* Platform: `iOS 10.3`
* Version: `4.7.5`

I've set basemap to "OpenStreetMap". This seems to work in all views except in capture mode. The capture mode seems to ignore the configured basemap option and uses the default.

**Comment by katrinhumal** [comment]
Thanks for reporting! @millenbop is on holiday right now but will take a look as soon as he's back.

**Comment by millenbop** [comment]
This has been fixed now, will be out in the next release.
