### ISSUE TITLE
ios: sequences are not displayed in higher zoom levels / when driving slow

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2619]
### Basic information
* Platform: `iOS 10.3`
* Version: `4.7.5`

When I'm zooming in too far the green lines of the (already/old) captured sequences will disappear. Since the zoom level in capture mode is based on how fast I'm moving the sequences are disappearing there too when I'm moving slow.

**Comment by katrinhumal** [comment]
@descilla Likewise here - thanks for notifying and @millenbop will take a look after his holiday.

**Comment by voschix** [comment]
Also on Android 365 in high zoom level. (Haven't tried while moving)

**Comment by katrinhumal** [comment]
@voschix indeed! The lines disappear on Android both in capture and explore mode when zooming in to the last levels. @gyllen what should we suspect here?

**Comment by habi** [comment]
I'm also seeing that, while recording a sequence on the bike (tIjnUvsgF_4G3ZGelB8biQ, this morning).
The firts image is a screenshot of my phone, the second image is a screenshot from approximately the same location from the Mapillary website.

![img_3760](https://user-images.githubusercontent.com/1651235/28316411-12b5c0b4-6bc3-11e7-96b4-5b1b1244b71b.JPG)

![clipboard01](https://user-images.githubusercontent.com/1651235/28316492-5fdfdbcc-6bc3-11e7-8d46-bd6ced75c39e.jpg)

**Comment by millenbop** [comment]
It is a bug with the Mapbox SDK. I have filed a bug for them over a year ago but it still hasn't been fixed (yeah I realise we have old bugs too lol).

What we can do is to limit the zoom level to 14.9 (it breaks at 15). I have done that on iOS but apparently I at least one place.

**Comment by millenbop** [comment]
It has now been limited to zoom level 14.99, will out in the next release.
