### ISSUE TITLE
View of "Connected"-relation is not symmetric

### ISSUE THREAD

**Issue by epsg31468** [mapillary/mapillary_issues#262]
First I thought this is a bug, but while writing the post I noticed that this is only an enhancement:

If a picture a from user A is connected to pictures b_1, ..., b_n  (b_i<>b_j \forall i<>j, n>1) from user B, then on A's userpage the picture a is only connected to one representative chosen of all the images b_i of user B, whereas on B's homepage all images b_i (well, at last a subset with cardinality >1) are connected to image a.

For example, let A=oscarfate
http://www.mapillary.com/profile/oscarfate

and B=SMSM1
http://www.mapillary.com/profile/smsm1 

then SMSM1 shows 27 connections to oscarfate, while the reverse connections are only 8.

I would like to see all connections on all userpages (and naming 8 and 27 the "owning picture count" of the relation).

**Comment by gyllen** [comment]
Closing since connections will be removed and replaced with something better (Images that matches visually from other users)
