### ISSUE TITLE
Very bad traffic signs location detection

### ISSUE THREAD

**Issue by frodrigo** [mapillary/mapillary_issues#2620]
* Detect traffic signs location is far away from photo location: 478m in this case.
* Traffic sign location is rear the photo scene

![](https://user-images.githubusercontent.com/1785486/28036739-73eac844-65b9-11e7-9bc6-a4885792be43.png)

https://www.mapillary.com/app/?lat=48.10194621168628&lng=-1.714222926176319&z=15.139508929944766&focus=map&pKey=D5RxiNqL4dawrGZGe2h5fg&x=0.5054887896925598&y=0.5110139783585042&zoom=0&signs=true&trafficSign%5B%5D=regulatory--maximum-speed-limit-70--g1

https://a.mapillary.com/v3/objects/vvyg52wd83f9iyw133vwdqoeg2?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh
```json
{
  "type": "Feature",
  "properties": {
    "accuracy": 1,
    "altitude": 1.8102772,
    "detections": [
      {
        "detection_key": "9kfqu9shfhppv4kr53dji422ph",
        "image_key": "g5a594tIYifoM6xwZffKHg"
      }
    ],
    "first_seen_at": "2016-02-27T09:02:52.340Z",
    "key": "vvyg52wd83f9iyw133vwdqoeg2",
    "last_seen_at": "2016-02-27T09:02:52.340Z",
    "package": "trafficsign",
    "updated_at": "2017-06-16T10:06:16.618Z",
    "value": "regulatory--yield--g1"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -1.712657017499481,
      48.10627466265029
    ]
  }
}
```

https://a.mapillary.com/v3/images/g5a594tIYifoM6xwZffKHg?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh
```json
{
  "type": "Feature",
  "properties": {
    "ca": 165.18292275023816,
    "camera_make": "Motorola",
    "captured_at": "2016-02-27T09:02:52.340Z",
    "key": "g5a594tIYifoM6xwZffKHg",
    "pano": false,
    "user_key": "9ATMpwjYP8MtUGp1r9qDMg",
    "username": "hamlet"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -1.71628508,
      48.102728
    ]
  }
}
```

**Comment by ulikoehler** [comment]
It seems to me like under certain circumstances the location is not re-calculated when the image orientation has changed.

See e.g. the two stop signs in the center of the image here:

https://www.mapillary.com/app/user/umap?lat=48.1090655408492&lng=11.73979327859945&z=19.672468879605614&pKey=IIKf_TGpJbDuTe_kNUV03g&focus=map&menu=false&mapStyle=mapbox_streets&signs=true

I know for a fact there are no such stop signs there, and as you can see from the corresponding images, the stop sign is next to the street. Possibly the image sequence was originally not oriented correctly and was later normalized.

**Comment by ybkuang** [comment]
@frodrigo @ulikoehler We've looked at the examples you share. The reason is that there are errors in the 3D reconstruction for those areas. Specifically, we notice that the locations of the images after 3D reconstruction are wrong which cause errors when estimating the locations of the signs. We will need to investigate further what lead to the errors in 3D reconstruction.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
