### ISSUE TITLE
Compass not working

### ISSUE THREAD

**Issue by wladich** [mapillary/mapillary_issues#2622]
### Basic information
* Platform: `Android`
* Version: 3.67
* System: Xiaomi 4X 4Gb/64Gb

### Steps to reproduce behavior

 1. In settings enable `distance based capture`, leave `compass based autocapture` at  default value (40)
 2. on `capture` screen tap arrow and enable `Use device compass`
 3. switch to auto capture mode
 4. tap record button
 5. Slowly turn around holding the phone.

### Expected behavior
About 8-10 photos taken

### Actual behavior
One image taken right after tapping record button.

### Steps to reproduce behavior
1. On capture screen switch to manual capture.
2. Tap arrow and enable `Use device compass`
3. Press capture button, turn 90 degrees; repeat 4 times

### Expected behavior
Photos pointing in 4 different directions
a) on map in sequence upload page 
b) in web app after uploading

### Actual behavior

All photos are heading north

### Additional information
I made 4 photos and made screenshot before each photo:
https://www.dropbox.com/s/3y9u4ojavledien/Screenshot_2017-07-14-16-31-47-558_app.mapillary.png?dl=0
https://www.dropbox.com/s/kve7sxvth3u5k51/Screenshot_2017-07-14-16-31-58-973_app.mapillary.png?dl=0
https://www.dropbox.com/s/qub2xc2vuh1m5v6/Screenshot_2017-07-14-16-32-09-766_app.mapillary.png?dl=0
https://www.dropbox.com/s/svpd12zq8s03te2/Screenshot_2017-07-14-16-32-17-842_app.mapillary.png?dl=0
Compass icon on those screenshots is pointing different directions, so compass in my phone is working and app can read its measurements.
Sequence with all 4 photos pointing north:
https://www.mapillary.com/app/user/wladich?lat=55.7973232074836&lng=37.53795395490147&z=17&pKey=yKKxg_dUAxDiBEPVxIjoNA&focus=photo

Developper and camera settings are at default values:
https://www.dropbox.com/s/ltnjnk9l7lw5y4k/Screenshot_2017-07-14-16-32-52-760_app.mapillary.png?dl=0
https://www.dropbox.com/s/b1yop712grwxo29/Screenshot_2017-07-14-16-32-57-255_app.mapillary.png?dl=0
https://www.dropbox.com/s/t0mwci55k9pf8pd/Screenshot_2017-07-14-16-33-32-997_app.mapillary.png?dl=0
https://www.dropbox.com/s/1tt9msqpd7ra0ru/Screenshot_2017-07-14-16-33-37-749_app.mapillary.png?dl=0

**Comment by wladich** [comment]
Also checked in time based capture mode (1 second interval, "use device compass" turned on, auto capture): made several pictures while standing in one place and turning  around -- all photos on upload page are pointing north.

**Comment by peterneubauer** [comment]
@wladich the compass issue should be fixed in recent beta builds, you can join the beta program in the side drawer to get it (soon coming out in general). The compass angle tracking is disabled right now since the compass is not working reliably enough, best to just press manually, we will think about how to make this better.

**Comment by jfburke3** [comment]
@peterneubauer I'm not sure I follow what you mean by "best to just press manually."  Do you mean deselect the "Use device compass" knob and use the directional arrows instead?

**Comment by peterneubauer** [comment]
No, just use device compass, and select manual mode in the switcher above the shutter button (an image is taken only when you press the button). That way you control when to take an image.

**Comment by jfburke3** [comment]
Erm...  That's...kinda not fun when driving a few hundred miles (having to press the button to take a picture).  I'm going to have to pass on testing that, except for maybe a short sequence one day.

**Comment by katrinhumal** [comment]
I think @peterneubauer meant the manual mode for if you're capturing a panorama view around you when standing in one spot. This is of course not feasible for driving, as you point out @jfburke3.

**Comment by peterneubauer** [comment]
While driving, it is highly unlikely that you will get any usable compass info from the phone anyway because of the metal-distortion. Better to set it into fixed-direction offset when driving.

However - the images pointing north when using the device compass in auto mode is a bug, looking into it.

**Comment by Alessandro-Barbieri** [comment]
I think this is a top priority issue but after 5 months nothing is changed ....

**Comment by polarbearing** [comment]
is this related to #2579?

**Comment by ovivoda** [comment]
This issue should be fixed in the latest version of Mappillary Android application
