### ISSUE TITLE
OpenStreetMap basemap on website doesn't use zoom 19 tiles.

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2623]
For quite a few years now, the default tileset for OpenStreetMap (at https://abc.tile.openstreetmap.org/zoom/x/y.png) offers tiles up until zoom level 19.

However, the map on the Mapillary site, when choosing OpenStreetMap as the basemap, doesn't load beyond level 18. The result is a needlessly coarse OSM basemap.

**Comment by katrinhumal** [comment]
@pbb72 thanks for pointing that out. I'll take this to the team to discuss.

**Comment by knikel** [comment]
This has been now fixed, thanks! The tiles should look better now too, since the library we're using defaulted to 512 size, while OSM provides 256 sized tiles. This will be visible after the next deploy.

**Comment by pbb72** [comment]
Perfect, thanks!
