### ISSUE TITLE
allow simultaneous exif tag writing & upload

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2624]
looks like currently the (ios) app allows either upload, or exif tag writing.

when attempting to speed up the uploads by moving images to the computer for an upload when the phone cannot do that, the images need the tags added.

if there are a lot of pictures, adding tags to them takes a very long time, during which time no uploading can happen.

it would be great if both tag adding & upload could be initiated in parallel. that way a bunch of images would be uploaded before transferring images to the computer.

**Comment by katrinhumal** [comment]
@richlv thanks for your request! Taking it to the team for consideration. :)

**Comment by katrinhumal** [comment]
@richlv I learnt that the capture+upload process on iOS will undergo some changes which should solve this problem. So no immediate fix but a solution is in sight! :)

**Comment by richlv** [comment]
thanks a lot for the info. any info on what changes are being worked on ? would that eliminate the double-writing of he images ?

**Comment by katrinhumal** [comment]
@richlv Sorry for ignoring you for so long!! Here's how it's going to work (according to @millenbop who is working on this as we speak):

There are two threads running in parallell:

Thread 1:

for every file
  if EXIF is missing
    add missing EXIF
    add file to upload queue
  else
    add file to upload queue
Thread 2:

for every file in upload queue
  upload
  delete
Processing files is a lot faster than uploading them, and as soon as the first photo is processed, it will start to upload. At the same time as it is being uploaded, the next photo is processed and then added to the upload queue. When the first photo is uploaded, the next photo in the queue is uploaded.

After about 1 third of the total upload time, all the photos have been processed.

**Comment by richlv** [comment]
no worries about the delays at all.
thank you, that seems very reasonable and nice. i hope the ability to add tags without an upload won't go away :)

**Comment by katrinhumal** [comment]
Nope, the plan is to keep that option so that you can retain copies of your images (or just transfer and upload them with some other method).

**Comment by katrinhumal** [comment]
@millenbop ^

**Comment by richlv** [comment]
i was looking for the background processing. that is, if i'm starting to upload a large number of images, after a few hours i'd expect that all of the remaining ones would have the exif tag already.

testcase : have a lot of images, start the upload. after a few hours stop the upload, start adding exif tags - all of the remaining images have the tag added to them (at least judging by the image counter).
