### ISSUE TITLE
difference between coordinates in vector tile vs viewer node?

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2625]
I'm confused by the following:

- using mapbox-gl (0.38.0) and mapillary-js (2.6.0)
- i've loaded a map w mapillary vector tiles and display the mapillary-images source-layer
- the coordinates retrieved from the vector tile geometry after a click of a mapillary-images circle doesn't match the coordinate information retrieved from the viewer when changed to that key

```
features[0].properties.key =  2gUfdmvIQVWu_DpzZ6wv3Q
features[0].geometry.coordinates = (2) [124.96114611625671, 11.170728834452134]
node.key:  2gUfdmvIQVWu_DpzZ6wv3Q
node.latLon:  Object {lon: 124.96114630556268, lat: 11.17072463338343}
node.originalLatLon:  Object {lon: 124.96114805555555, lat: 11.170729722222234}
node.computedLatLon:  Object {lon: 124.96114630556268, lat: 11.17072463338343}
```
```
features[0].properties.key =  3XHbkTgIOlewGOePU2MmnA
features[0].geometry.coordinates =  (2) [125.01285374164581, 11.12494425930474]
node.key:  3XHbkTgIOlewGOePU2MmnA
node.latLon:  Object {lon: 125.01275414202462, lat: 11.12496017166512}
node.originalLatLon:  Object {lon: 125.01285138888886, lat: 11.124943055555548}
node.computedLatLon:  Object {lon: 125.01275414202462, lat: 11.12496017166512}
```

**Comment by cbeddow** [comment]
Elvir in Sarajevo having similar issue, trying to place a "pegman" marker for `you are here`:

`seems that sometimes coordinate of pegman and street view point is not 100% correct since pegman is little (up,down,left,right)`

**Comment by ptpt** [comment]
Two possibilities:

1. Image locations in vector tiles always use the original latlon, which is read from image EXIF or GPS directly, while MJS uses the computed latlon when it is available.
2. The coordinates in vector tiles are not 100% precise, i.e. 100% same as the original latlon. The precision depends on the tile's zoom level, and the location of the tile, and the extent (the number of cells of a tile, which is always 4096. See https://www.mapbox.com/vector-tiles/specification/#encoding-geom). For example the best precision in the a tile at level 14 is `(40075016 / (2^14)) / 4096 = 0.597 meters`, which is around `+/-0.000005` degree. It seems the differences in both cases you provided are falling in this range.

**Comment by ptpt** [comment]
`40075016` is the circumference of the earth. In level 14, you have `2^14` tiles in a row, so each tile has the width `40075016/(2^14)`. A tile has 4096 cells, so you get the precision `(40075016/(2^14)) / 4096`.
