### ISSUE TITLE
ios: don't "reset" center of map view after viewing an image

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2627]
### Basic information
* Platform: `iOS 10.3`
* Version: `4.7.5`

### Steps to reproduce behavior

1. Switch to discover/map-pane (not sure about the name in the English version. In the German version it's named "Entdecken")
2. Swipe a bit around
3. Tap on a sequence to switch to view a specific image
4. Go back to previous pane by tapping to the left top corner (discover/map-pane)

### Actual behavior
When I switch to discover/map-pane the center of the map will be my current position. However every time I select an image and then go back the map view the center (and zoom level) of the map will be set back to my current (GPS) position even if swapped around previously. This seems to be a bit odd.

### Expected behavior

The center of the map should only set to my current (GPS) position when entering the map view initially (tapping the "globe" button at the bottom of the screen).

**Comment by katrinhumal** [comment]
@descilla Thanks for raising this! @millenbop is on holiday until the end of next week but once he's back, he can explain the behaviour and verify how things should really work.

**Comment by millenbop** [comment]
This is fixed now, will be out in the next release.
