### ISSUE TITLE
web: unexpected zoom behavior in "time travel" mode

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2628]
### Basic information
* Platform: `web`
* Browser: `Chrome v59`

### Steps to reproduce behavior

 1. select an image
 2. zoom in
 3. enable "time travel" mode

### Actual behavior
When I use the zoom feature in the image view and then enable time travel mode the image stays zoomed in. However the time travel mode doesn't provide any zoom capabilities. So I can't zoom out or scroll the image. This behavior seems to be a bit odd.

### Expected behavior
There are multiple ways to improve the usability in this scenario. My suggestions:

- Enable zoom capabilities in time travel mode, too.
- Reset the zoom state to default when entering time travel mode.

**Comment by nickplesha** [comment]
@descilla Thanks for reporting this.
@oscarlorentzon Are there any restrictions on zooming in/out in MapillaryJS when slider is active?

**Comment by oscarlorentzon** [comment]
@nickplesha Zoom will be reset to 0 automatically in MJS when activating slider/time travel mode in next release (`2.7.0`).

**Comment by nickplesha** [comment]
This has been fixed by updating to MJS 2.7.0
