### ISSUE TITLE
openstreetmap ("mapnik") basemap layer seems to be diffuse

### ISSUE THREAD

**Issue by descilla** [mapillary/mapillary_issues#2629]
### Basic information
* Platform: `iOS` | `Web`
* System/Browser: `4.7.5 (iOS), Chrome 59 (web)`

### Steps to reproduce behavior

 1. Set basemap layer to *OpenStreetMap*

### Actual behavior
The OpenStreetMap basemap layer seems to be blurry/unsharp. It looks like the (raster) tiles would be upscaled. 

### Expected behavior
Display the OSM tiles as sharp as on openstreetmap.org

### Additional information
It looks like the zoom level definition of OSM and Mapillary (respectively the according framework) are different. I'll give you an example the be a bit more clear:

[This](https://www.mapillary.com/app/?lat=52.01476897858535&lng=7.564154394476958&z=12) is a "random" area on Mapillary. And [this](https://www.openstreetmap.org/#map=12/52.0148/7.5642) is the OSM map with the same settings (same centre of map, same zoom level). As you can see the area displayed on OSM is much larger than the area displayed on Mapillary. [Now](https://www.openstreetmap.org/#map=13/52.0148/7.5642) I zoomed in (one level deeper) on OSM and the OSM map will cover the same area as the Mapillary Website does.

So it looks like Mapillary should use the OSM tiles from one level higher. In the example Mapillary at zoom level 12 should use OSM tiles from zoom level 13. 

I've noticed this behavior at both website and iOS (I can't say anything about the android version in lack of an android phone).

**Comment by gyllen** [comment]
@knikel Please investigate

**Comment by voschix** [comment]
Seems to be the same issue as #2623

**Comment by descilla** [comment]
It looks like OSM tile levels are zero-based numbered while mapillarys zoom index begins at 1.

**Comment by knikel** [comment]
Unfortunately, this is not related to #2623 (fixed). For some reason `mapbox-gl-js` renders different extent of the map at given zoom level compared to Leaflet. Still investigating.

**Comment by knikel** [comment]
It seems like the issue lies between how the tiles are rendered on the `openstreetmap.org` and how `mapbox-gl-js` renders them with the same settings. To my knowledge we're not setting anything specific with regards to the OSM tiles and take them as is with correct `tileSize`. This is the zoom level OSM tiles provide and there is no way to fiddle with that manually in `mapbox-gl-js`. I'm afraid this is one of these *wontfix* issues. Sorry.
