### ISSUE TITLE
web uploader issues

### ISSUE THREAD

**Issue by mxa** [mapillary/mapillary_issues#2630]
The web uploader is doing funky stuff when trying to place some images manually.
1. it completely ignores mouse interaction the first time one of the red dots is dragged.
2. the picture gets placed somewhere else, not where the mouse was released
3. now i somehow got into this (see screenshot) where I can only put the image in one of the corners...

this is with Google Chrome, in Firefox it is even more messed up.

![screenshot from 2017-07-20 12-12-54](https://user-images.githubusercontent.com/1220707/28412558-e715a928-6d44-11e7-8829-eed9a2cc9f91.png)

**Comment by nickplesha** [comment]
@mxa Thanks for reporting this, we' re looking into this issue. Can you share what OS are you using?
There were reports of similar behaviour sometimes happening when browsers interpret drag-and-drop in UI as drag-and-dropping files on top of the tab which causes this.
Also, if you see any error messages in the console when this happens, please add them here.

**Comment by mxa** [comment]
That's on Linux Mint 18.2 cinnamon 64bit.

**Comment by mxa** [comment]
Btw, above happens when you accidentally drag a file (image) into the upload window while uploading.
![screenshot from 2017-08-19 12-07-04](https://user-images.githubusercontent.com/1220707/29485726-03722b74-84d7-11e7-9181-853c4179745f.png)

**Comment by nickplesha** [comment]
@mxa The overlay shouldn't prevent you from editing in the future, if it does appear incorrectly again, just click on it to hide it.

**Comment by mxa** [comment]
@nickplesha the green overlay does prevent you from clicking anywhere except the few pixels that are left out because of the rounded corners. All changes will be lost, the only way out is to close the browser.

**Comment by nickplesha** [comment]
@mxa That's one of the changes we made: the green overlay can be dismissed by clicking on it in addition to dropping new images as before.

**Comment by mxa** [comment]
ah, ok. Thanks.
