### ISSUE TITLE
Comment view multiline is chopped

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2633]
![image](https://user-images.githubusercontent.com/11977/28523528-2cea9798-707d-11e7-973e-48e54a4a0496.png)

**Comment by katrinhumal** [comment]
@peterneubauer should we assign you or @ovivoda to this? :)

**Comment by peterneubauer** [comment]
ovi

**Comment by ovivoda** [comment]
@peterneubauer @katrinhumal This seems to me like a web bug and not an app bug.

**Comment by peterneubauer** [comment]
Yes

**Comment by katrinhumal** [comment]
Woops my bad, I failed to look at the screenshot properly. Let's ask @nickplesha to help then :)

**Comment by nickplesha** [comment]
Comment form has been updated and this should be fixed.
