### ISSUE TITLE
Image uploaded with date 6 months off (correct date in EXIF)

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2634]
I've just noticed that an image sequence take using the Android App on saturday (July 22nd):
https://www.mapillary.com/app/user/umap?lat=48.066333083167194&lng=11.7392856435888&z=12.218355812216307&pKey=_SQi5WM7MjsDYE9bwyIzTw&focus=map
by me has been incorrectly labeled as **January 22nd**. I'm pretty sure my smartphone's time wasn't off by 6 months straight and also the EXIF data suggests that this is an issue with the App (I downloaded the "original unprocessed image" and run exiftool on it):

```
$ exiftool uploaded.jpg | grep 2017
File Modification Date/Time     : 2017:07:24 21:54:26+02:00
File Access Date/Time           : 2017:07:24 21:55:00+02:00
File Inode Change Date/Time     : 2017:07:24 21:54:26+02:00
Image Description               : {"MAPCaptureTime":"2017_01_22_18_21_03_440","MAPVersionString":"3.67","MAPAutoFocusMode":"AUTO","MAPDeviceModel":"LG-D802","MAPCompassHeading":{"MagneticHeading":75.91744995117188,"TrueHeading":75.91744995117188},"MAPAccelerometerVector":{},"MAPSequenceUUID":"d02138aa-70be-44ab-9b5c-96592fc42fea","MAPDeviceMake":"LG Electronics","MAPSettingsUploadHash":"49b6740e0e929f368210e01cc70e27232f4435d2f32f48f8110c05ae1e6b9d0d","MAPLocalTimeZone":"+0200","MAPAutoFocusDistance":0.0,"MAPPhotoUUID":"3684b579-dacc-4a3a-8a66-2cd922b2598b","MAPLongitude":"11.74203372223393","MAPSettingsUserKey":"pyQrwn2chXv57on5L40ZbA","MAPAltitude":"600.0","MAPLatitude":"48.10739890693362","MAPGPSAccuracyMeters":"4.0"}
Date/Time Original              : 2017:07:22 18:14:50
Create Date                     : 2017:07:22 18:14:50
```

As you can see, the `Date/Time Original` as well as the `Create Date` are 100% correct, but `Image Description` clearly contains wrong data, so this is probably caused by an issue in either the app or the server.

In January 2017 I hadn't even heard of Mapillary existing, therefore it's impossible I took the photo at that time :-)

I think internet access was disabled (flight mode) while taking the sequence. But I'm not too sure.

Note that ~2 hours later (NOTE: after I had wifi access for some time!!) I created this sequence:
https://www.mapillary.com/app/user/umap?lat=48.04582919500001&lng=11.67620017180002&z=17&pKey=SZcxEzO5zS44AY_pJVJu8A&focus=map

which has a correct date set.

Here's some other sequences that apparently took place before I even signed up for mapillary:
https://www.mapillary.com/app/user/umap?lat=48.10698637816148&lng=11.74395014730544&z=11.474163006090798&pKey=hNF5Zb1fid54rCZ8w_2AUw&focus=map
https://www.mapillary.com/app/user/umap?lat=48.1075252521739&lng=11.741575472880413&z=17&pKey=dCrt5uo1uFa2LH6IQVhZEQ&focus=map
https://www.mapillary.com/app/user/umap?lat=48.10269336204192&lng=11.671411812041924&z=17&pKey=o-oB_f8Cq-wmCneK0QMRBw&focus=map

For all of them It is possible the smartphone was in flight mode (i.e. mobile internet off) which I often do in order to conserve battery life.

**Comment by peterneubauer** [comment]
Is this happening consistently always even with new sequences @ulikoehler ?

**Comment by ulikoehler** [comment]
@peterneubauer Definitely not. It seems to happen randomly with only a few sequences with no apparent connection between them. For me it happened for four sequences out of more than 100 (estimated) uploaded sequences.

It might be possible that its related to issues with stray images in the app. When the app detects stray images, I will just click on the upload button again. Most of the time the images are uploaded after that. However I'n sure I did that more than four times, so it wouldnt explain the issue properly.

**Comment by ulikoehler** [comment]
Also note that I didnt get a "images published" notification for that sequence.

**Comment by peterneubauer** [comment]
The notification is most probably missing due to a backend bug I did in the notification code. Should be fixed now :)


Can you try http://android-releases.mapillary.io/Mapillary_Android_3.73-SNAPSHOT1.apk and see if you get less stray images, to start with?

**Comment by ulikoehler** [comment]
Thanks, I will try the new snapshot ASAP!

**Comment by ulikoehler** [comment]
I was able to test taking a very short sequence of images (~200 overall) with the 3.73 Snapshot 1 version - it did not produce any stray images. I will continue testing this with longer sequences.

**Comment by dmbreaker** [comment]
Could it be different time zones issue?
I made photos in one timezone and uploading was fine. When moved to another one (with flight mode in the middle) all images became "stray".
Last time I got the issue conditions were similar.

**Comment by ulikoehler** [comment]
@dmbreaker TZ issues could explain max 24h offset but not 6 months.

If you mean secondary issues due to timezone change, thats possible in principle but not for my specific issues. I haven't been in another timezone since Signing up for mapillary. Also i have not changed by smartphone TZ settings.

Still, the issue might be related to flight mode. However, I took pretty much all my sequences in flight mode and only 4 exhibit this issue.

It would be interesting to know what the source for the mapillary timestamp is. Obviously it is not the same source as the source for the EXIF date.

**Comment by peterneubauer** [comment]
The first source for the timestamp for an image is the filename parsed as a timestamp for performance reasons. We now inserted the filename into the EXIF JSON tag, so we afterwards can see what it was. Will be out in the next version so we can debug this.

**Comment by ulikoehler** [comment]
@peterneubauer Thanks, I'll check regularly if there are any new sequences with this issue. If there are new ones, I'll inform you via this thread.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
