### ISSUE TITLE
Images not appearing after upload

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2635]
reference: https://twitter.com/muramototomoya/status/889796502222028800

**Comment by tankaru** [comment]
Hello, my mapillary username is "tankaru".

My uploaded photos were not published, just disappeared.

1. I uploaded about 800 photos via python uploader at around 16 July. They were on "pending" status.
2. At 20 July "pending" status were disappeared. But photos were not published.
3. I uploaded another 70 photos via web uploader at around 22 July.  They were on "pending" status.
4. At 25 July "pending" status were disappeared. But photos were not published.

Attached photo is one example I uploaded on the 3.step.
![20170708_085722_interval01](https://user-images.githubusercontent.com/13701091/28595841-b7a24206-71d0-11e7-812f-7bd5e819c582.jpg)

**Comment by tankaru** [comment]
My disappeared photos are published today.
Is the bug fixed?

**Comment by peterneubauer** [comment]
So, the sequences uploaded by you the 16th are

```
wEx78jJ1SZY2uBInZOWZmw
tqrbdB9HZ_d_k1OONNSKfA
cex6zXgVGJOHRsMAwMPuDg
khL0b1nFgkvprV-3tVAacg
zpOvDUBgyNgt0IVWMrkR2w
B-lqRiVqfWHXt8pOXkuExg
jKPM0iWkW7034yAh8K88fQ
ueFipAD98SZaxWWbHE7bTQ
Aw-8wKRfFt1eYgB2Wqg63w
GjNHEegXMyexbSvVM20HsQ
voPCiPOT2Yu4enIHNpd6BA
zvDx95L0WTxvN6d3nUGf7g
xUIoU-qnlq3oDNE2cg0q-Q
CcG68OarCcE9fSEy8Bkevg
03sd_xFlJNFkdqKBMe-DHA
BJdWW2n2ckp_jsX_zX8zXg
```

you can see them by doing e.g. https://www.mapillary.com/map/s/wEx78jJ1SZY2uBInZOWZmw, and there I'm seeing the first image of that first sequence under https://www.mapillary.com/app/?pKey=QCV6EQrj2wrFq9U4wHAdkA&lat=35.34986666666667&lng=139.56543333333332&z=17 ?

**Comment by tankaru** [comment]
Those sequences are already published before this issue.

The newly published photo is here, for example.
https://www.mapillary.com/app/?pKey=5pK0XWr-QUPfwwMfJ0mlKw

And I'm sorry maybe I'm not getting the point of your comment well,
I just want to know whether "the bug is fixed" or "I should change my upload manner".

**Comment by peterneubauer** [comment]
This bug should be fixed, closing for now.
