### ISSUE TITLE
Android: Explore map during capture offset so not shown in correct location

### ISSUE THREAD

**Issue by stev391** [mapillary/mapillary_issues#2636]
### Basic information
* Platform: `Android`
* Version: `3.72-BETA` 
* System/Browser: `Samsung Galaxy S7 GM-930F`

### Steps to reproduce behavior

 1. Open up Mapillary App,
 2. Goto to capture
 3. tap the map button on the left

### Expected behavior

White dot on screen shown on map in correct position

### Actual behavior

White dot is off to the left of actual position on the map.

### Additional information

Appears to caused by incorrect offset of the map image on the screen.  Map image centred on phone screen, while dot is centred on the map window.  Attached are 3 screenshots, taken at different map zoom levels, but staying in the same physical location (yes I'm aware of the bad GPS fix, happens the same regardless of quality of fix, just lazy and not wanting to go out in the rain).

This makes it hard to navigate when you have to guess where the dot should be...

Actual location is to the right of all dots, but you should see the issue especially contrasting each image.
![screenshot_20170726-132354](https://user-images.githubusercontent.com/30454251/28603172-f2e5d514-7205-11e7-99ac-df1329eff1fb.png)
![screenshot_20170726-132400](https://user-images.githubusercontent.com/30454251/28603171-f2d58d62-7205-11e7-88f1-9f5a12a43677.png)
![screenshot_20170726-132410](https://user-images.githubusercontent.com/30454251/28603173-f33711ea-7205-11e7-97fe-431513cd0fc8.png)

**Comment by ovivoda** [comment]
stev391 Please try the latest beta version and let me know if that works better:

http://android-releases.mapillary.io/Mapillary_Android_v3.93-BETA.apk

**Comment by stev391** [comment]
I'm pleased to advise that changing zoom levels results in the centre of the map staying consistent.  However this has resulted in loosing the dot that shows were you are on the map (except location of launching the app, it just stays there on the same spot on the map, doesn't move with the scrolling of the map).  Also the map is centred on the phone screen not the map portion of the screen.

First start up with location dot shown in correct position relative to the map:
![screenshot_20170902-164921](https://user-images.githubusercontent.com/30454251/29995383-6e6631dc-902b-11e7-8b3a-92996b16f43b.png)

Location dot missing, as it is still at the same location on the map, not where I am at the time of the screen shot. (I'm about where the C415 is on the map near the middle of the screen).
![screenshot_20170902-165032](https://user-images.githubusercontent.com/30454251/29995399-9be57ed8-902b-11e7-8a98-016e9b1448f0.png)

**Comment by ovivoda** [comment]
@stev391 Thanks for getting back on me on this. I'm checking it out and working on fixing it.

**Comment by stev391** [comment]
With 3.95, I get a white dot in the middle of the map portion of the screen, but as noted before the map is centred on phone screen, so there is an offset to my location.  (I didn't try zooming in or out.)

In the screenshot, I'm on the road to the right of the white dot (and it didn't matter if it was a bad fix, good fix or best).
![screenshot_20170910-101700](https://user-images.githubusercontent.com/30454251/30248935-4126ee2e-9674-11e7-87cd-ca77b0d48a6c.png)

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
