### ISSUE TITLE
screen locked while recording with the ios app

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2637]
iphone 6, latest mapillary app version (unable to find the exact version).

take some images. start upload, hit "stop upload" a moment later and switch to the capture mode immediately, start a new sequence. phone locks screen after the normal timeout, stopping the capture.

**Comment by millenbop** [comment]
Thanks for reporting! I'll fix.

**Comment by millenbop** [comment]
This has been fixed now, will be out in the next release.

**Comment by richlv** [comment]
great, thank you :)
