### ISSUE TITLE
ios app - auto-mode button can become inversed

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2640]
open the ios app, switch to the capture mode and hit the start button before the gps signal has been received. the app will go in the capture mode, but will only start capturing when the gps signal will be available. unfortunately, the button shows that there's no active capture.
tapping the button again stops capture, but the button now shows that the capture is active.

**Comment by millenbop** [comment]
Thanks for reporting, I'll look into it!

**Comment by millenbop** [comment]
I have simplified the button behaviour a bit which fixes this issue, will be out in the next release.

**Comment by richlv** [comment]
great, thank you :)
