### ISSUE TITLE
Website "edit tags" feature doesn't have a way to exit

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2641]
### Basic information
* Platform: Web
* Version: 
* System/Browser: Windows 7, Chrome

### Steps to reproduce behavior

 1.  Select an image from a sequence
 2.  Click the 3-dot menu button at the lower right
 3.  Click Edit Tags on this photo
 4.  No options available to do....
 5.  Can't exit because there's no Exit button.

### Expected behavior

An exit button to click

### Actual behavior

Nothing at all to click

**Comment by katrinhumal** [comment]
@jfburke3 Can't accidentally push anything these days without our attentive users noticing! 😉 ❤️ The `Edit tags` button is actually not supposed to be there - yet. But it will be soon, together with lots of stuff to click on. Stay tuned!
Meanwhile, I've notified the dev team of this slip so the button will disappear until it's time for it to make a comeback.
