### ISSUE TITLE
Detections map displays deleted photos

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2643]
The new detections map displays the position and thumbnail of deleted photos.
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Any`
### Steps to reproduce behavior
For example:
1. Go to Any location where photos have been deleted
2. Click `AI detections`
3. Click `Turn on detections`
4. Select to highlight photos with the `Terrain` or `Fence` detection type, or any other type which has been detected in any of the deleted photos
5. Hover the mouse cursor over one of the *deleted* photos
### Expected behavior
Neither the position nor thumbnails of deleted photos should be displayed, nor served by Mapillary.
![0](https://user-images.githubusercontent.com/15823872/28883619-61a4f634-77af-11e7-94f2-069b1ed2e427.gif)

**Comment by gyllen** [comment]
@peterneubauer ^^^

**Comment by peterneubauer** [comment]
Yup, this means we need to remove deleted images from the detections from the backend.

**Comment by gyllen** [comment]
Closing since these are updated over time

@peterneubauer Still make a note
