### ISSUE TITLE
Detections layer visible when in Satellite or OSM map style (base map)

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2644]
Since the introduction of detections, yellow dots appear on green sequence dots when viewing the `Mapbox Satellite` or `OpenStreetMap` base map (map style), even when detections have not been turned on.
### Basic information
* Platform: `Web`
* Version: `Any`
* System/Browser: `Firefox`, possibly others too
### Steps to reproduce behavior
1. Zoom-in to level `10` or greater anywhere on the map
2. Switch to `Mapbox Satellite` or `OpenStreetMap` base map
### Expected behavior
The detections map layer should only be visible when detections are *turned* *on*, regardless of the selected base map. One should only see the base map and the *green* sequences layer.
![yellow dots](https://user-images.githubusercontent.com/15823872/28899806-67efd7f0-77ed-11e7-8a22-1f1c6180619a.png)
#
There is another bug connected to base maps. Once the `OpenStreetMap` layer has been selected, if you try to switch back to the `Mapbox Streets` layer the correct base map does load but the *green* sequences layer disappears (including the falsely displayed *yellow* detections layer). Strangely, this does not apply to the `Mapbox Satellite` base map.
### Steps to reproduce behavior
1. Zoom-in to level `10` or greater anywhere on the map
2. Switch to `OpenStreetMap` base map
3. Switch back to `Mapbox Satellite` base map
### Expected behavior
When viewing the `Mapbox Streets` base map with detections *turned* *off* only the base map and the *green* sequences layer should be visible.

**Comment by gyllen** [comment]
@nickplesha Elevate to internal issue

**Comment by nickplesha** [comment]
@GITNE Thanks for reporting! Should be fixed now.
