### ISSUE TITLE
Android app localization?

### ISSUE THREAD

**Issue by damjang** [mapillary/mapillary_issues#2646]
I read previous issue with localization and find that the "mapillary_localization"  is closed. What is the project of localization for the future? I specially think of android app: pass the translations to Transifex or Crowdin or something similar would be a big add. If nothing of this can be done, maybe also share the resource locale file of mapillary app could be a chance...

**Comment by katrinhumal** [comment]
@damjang Thanks for your question! Localising the Android app is not off our agenda, despite the repo being closed. But I must warn it's also not one of the next items on the list for the near future. In any case, when we get to that, we will set up a system and give anyone interested the chance to help - like we have with iOS localisation today.

**Comment by damjang** [comment]
Ok, thank you for the answer!
