### ISSUE TITLE
time travel does not work - manual upload

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2647]
The sequence was uploaded with the web form: 5gnGytyX5DzJbFNEwRjFrQ
https://www.mapillary.com/app/?lat=52.509840752956364&lng=13.377655618239459&z=18.806149649946747&pKey=GnxTiQMWIsBc3_-YOxUl_w&focus=map&comments=true

This is the nearly the same position, but time travel from night to day does not work.

### Basic information
* Platform: `Web`
* Version: `last?`
* System/Browser: `59.0.3071.109 (Entwickler-Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)`

### Steps to reproduce behavior

 1. Call the url
 2. click on time travel 
### Expected behavior

should slide from night to day.

### Actual behavior

does not, time travel but is deactivated and shows: Time travel
You can compare previous images to the current one, but apparently there is nothing we found in our database for this image.
Still interested? Try this image.

**Comment by thoschu96** [comment]
Hey ,
just checked your link, i see that u took a picture on 16th and 17th, but on the map you see it on different positions. so i guess, the Timetravel only work's when it's on the same "location"..

**Comment by katrinhumal** [comment]
Thanks for raising this. Time Travel will work for images that have more or less the same location and compass angle (_slight_ deviations allowed), have matching points in them (detected by the Structure from Motion (SfM) technology we use for 3D reconstructions - the same thing that creates smooth sliding between overlapping images), and are not in the same sequence. 

In your case, the latter condition makes it impossible to get time travel here; but also, as you navigate between the two images, you see that they do not slide into each other. This is an indication that SfM was not able to detect enough matching points (even though to our human eye it is obvious that it is indeed the same place). So there likely would not be a Time Travel match even if the images were not in the same sequence, unfortunately.

**Comment by katrinhumal** [comment]
Hi! We've recently relaxed the conditions for time travel a bit; while the location and direction still have to match, there no longer need to be matching points between the images using SfM. This means the only problem for this case is now that the images are in the same sequence. So if you're interested, please try to upload them again separately, and see if there will be a time travel option available now.
