### ISSUE TITLE
Green vector tiles not loading due to No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2648]
### Basic information
* Platform: `Web`
* Version: `production`
* System/Browser: `Chrome 59.0.3071.115 (Official Build) (64-bit)`, `Firefox 54.0.1 (32-bit)`

### Steps to reproduce behavior

 1. Open developer console
 2. Navigate to [this area](https://www.mapillary.com/app/user/talllguy?lat=39.28951194693863&lng=-76.57294440667512&z=14.29632512827815&focus=map) of the map
 3. Pan around, look for missing green areas. The entire city is practically covered.
 4. Note the errors in the console.

### Expected behavior

Should be seeing a lot of green

### Actual behavior

Pockets of green dot/line areas do not appear on the map. I've tried disabling cache and using a fresh install of firefox as well.

### Additional information

rename to *.log: [www.mapillary.com-1501860612418.txt](https://github.com/mapillary/mapillary_issues/files/1200867/www.mapillary.com-1501860612418.txt)

![image](https://user-images.githubusercontent.com/1827881/28975479-24f975de-7908-11e7-9ae3-0db8ef665e68.png)

**Comment by katrinhumal** [comment]
@talllguy thanks for reporting! We had a database error and are currently re-rendering all the tiles. I believe your indicated area looks better already. ;)

**Comment by ptpt** [comment]
@talllguy Thanks for reporting. The CORS is enabled for all origins for sure, but sometimes I suspect some glitches happen in the caching side (cloudfront), so for some tiles, CORS headers are not updated or cached and therefore not loaded.

As I checked just now, all tiles showed without any error in Chrome console. Could you try to refresh again?

**Comment by nicolas17** [comment]
Works for me too.
