### ISSUE TITLE
Android - Wifi upload at captive portal

### ISSUE THREAD

**Issue by yuwtze** [mapillary/mapillary_issues#265]
When I am at a location with a hotspot, where I have to accept a Terms & Conditions page before getting access to the internet (coffee shop/retail store, etc), the uploader will begin attempting to  upload as soon as I connect to the wifi, though the uploads will immediately fail.  Once I log in/accept the T&C, uploads work as normal, and the failed uploads are eventually retried, so this is more of an annoyance than anything, but it would be nice if the app could recognize whether there's internet connectivity or not before trying to upload.

**Comment by jesolem** [comment]
This has been fixed, right @peterneubauer ?
