### ISSUE TITLE
Multi-set upload doesn't upload all images

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2650]
Using the web-uploader, it is possible to upload multiple image sets as one:

1. Visit https://www.mapillary.com/app/uploader
2. Drag a set of images onto the browser window.
3. All of the images are being parsed.
4. Click "Review".
5. Drag another set of images onto the browser window.
6. Most (between 50-90%) of the images are being parsed, not all images are there!
7. Repeat 4. and 5. to upload another set of images.
8. Even less images are now being parsed.

I don't see how it's determined which images will be parsed, but it is consistent -- when trying again with the same image sets, the same images are skipped every time. But changing the order, causes other images to be skipped.

**Comment by gyllen** [comment]
@pbb72 I think this is solely based on image name, can you confirm this?

**Comment by pbb72** [comment]
I doubt that very much, since all my sequences have the same image names (00000000.JPG, 00000001.JPG, etc). If conflicting file names would have been the problem, far more images would have been skipped.

**Comment by gyllen** [comment]
@nickplesha Can you take a peak at this?

**Comment by katrinhumal** [comment]
@pbb72 just a heads-up - @nickplesha is on holiday just now but will surely take a look once he's back.

**Comment by nickplesha** [comment]
@pbb72 Can you attach the files you're trying to upload so we can pinpoint what's causing the issue?

**Comment by pbb72** [comment]
Trying to build a test set of images, I think now there is two unrelated issues that I though were the same, and which made me discard the previous comment by @gyllen.

It is correct that photos with the same filename can not be uploaded in one sequence, **if** they are dragged as selections of files into the browser. However, if the **directories** containing the files are dragged into the browser instead (either one by one, or several directories at once) then there is no problem with duplicate file names. (Probably because in this situation the directory name is available to the uploader.)

However, when dragging directories, more than just photo files are send to the uploader. Examples are Thumbs.db, .gpx track files, and various configuration files that ended up in the photo directories. As a result, the upload progress first shows a number of files uploading (which includes non-photo files), and after that shows a **smaller** number of photos ready for publishing.

So, to conclude there is two issues:

- The uploader should allow uploading photos with the same filename.
- The uploader should inform that a number of files were uploaded that were not recognised as photos.

Initially I though some random photos were being dropped, which would be quite serious. But now seeing what really is happening, I think these issues are minor.

**Comment by gyllen** [comment]
@pbb72 @nickplesha 

For the issue about allowing upload with same filename I actually think its a feature not a bug. The idea is

1. User uploads images
2. For somehow the upload crashes
3. User reloads page
4. User add complete folder again
5. Previously uploaded files are ignored

**Comment by pbb72** [comment]
@gyllen The feature you describe is important. However, it should not be done by filename. This should be done by CRC or another check that is less likely to report false positives.

**Comment by gyllen** [comment]
@pbb72 I tend to agree, Im not sure that the browser will be happy by that though. It would need to read a lot of images into memory. I think in general for an upload files are generally named with different names (please correct me if I am wrong)

**Comment by pbb72** [comment]
It depends on the source of the photos. I'm currently using Time & Tide for taking all photos (since it allows to turn the screen off while taking photos), and that app always names the photos 00000000.jpg, 00000001.jpg, etc.

Would checking the date or size be an option?

**Comment by gyllen** [comment]
Since we are parsing the EXIF that would probably work. So as you probably know by now the upload interface is not really perfect. We had a project long time coming on solving that with a Desktop uploader and it finally looks like thats around the corner. I would wait with this feature until the specs are done for the uploader. I will add this as a feature though. Fair enough?

**Comment by pbb72** [comment]
Sounds fine :)
