### ISSUE TITLE
Unable to login or reset password

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2651]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Try to login over the "Sign in" Window
 2. Get errormessage : Wrong email or passord
 3. Try to reset the password over "Forgotten password"
 4. After providing the email and hitting the "Send instructions" the message "Invalid e-mail address" comes up

### Expected behavior

Should be able to Login, as password is not changed
Should be able to reset my password , which is strange

### Actual behavior

Can use the app on a other browser, where i am still logged in and on my IOS an Upload is working.
So Account looks valid for me.

### Additional information

...

**Comment by katrinhumal** [comment]
@thoschu96 thanks for reporting, I can confirm this issue (on Chrome Version 59.0.3071.115 (Official Build) (64-bit)). We'll look into it asap!

**Comment by gyllen** [comment]
Critical issue now resolved

@thoschu96 Thanks for reporting
