### ISSUE TITLE
wrong blurs

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2652]
I always correct the blurs of my sequences. The blur matches were improved some time ago, but after that step there was no noticeable improvement anymore.
I see a lot of false positives... Faces which are not blurred or license plate which are not or one letter is uncovered. Half faces or half license plates are never blurred.

Are corrections part of learning material? It is frustration to correct thousend of photos and to see every time the same time of errors.

I guess the blurring algorithm is independent from the new AI detection. From a end-users point of view I do not understand the bad quality of blurring. Because the new AI detection can recognize people and vehicles very well, this could be a good filter.

**Comment by jotpe** [comment]
This one f.e. has no blur, but I don't know why.
![bildschirmfoto von 2017-08-07 18-37-47](https://user-images.githubusercontent.com/3539168/29036439-b31ecf0a-7b9f-11e7-90fb-80ca6a15d437.png)

**Comment by voschix** [comment]
I also intended o report on this subject, thanks @jotpe for bringing this
up.
I produce more photos than I can check for blurring. The process is not
easy and fast enough.
Also, I would have asked the same question: why do I not see an improvement
in the accuracy of the blurring?
I am less worried about the the false positives, than about the false
negatives. Some are really strange; both faces and number plates close to
the camera often escape the blurring process. So do partial faces and
number plates.

**Comment by ybkuang** [comment]
@jotpe @voschix We are currently working improving the face/license plate detection. The corrections you've have made are essential to improve our algorithm. 

In this new version of the detection algorithm, we're taking into account of context information e.g. locations of the pedestrians/vehicles (same as @jotpe suggested). In this way, we will ensure low false positive and low false negatives. With more training data, we will able to localize the face/license plate better, so we make sure that the full face/license plate will be blurred. In the meantime, we are finding a good balance between localizing all the small faces/license plates against the speed (cost) of the processing. To achieve that, we're making more engineering efforts. 

Again, thanks for the valuable feedback and sorry for the delay on improvement.

**Comment by jotpe** [comment]
I think it can be a good idea for technical freaks, to see blurring statics in the weekly digest, too.

And I believe it would help the motivation of your blur correctors, to tell regularly about your work and status about the blurring algorithm. This allows the user to derive a relationship between his work and the algorithm quality.

**Comment by andrewharvey** [comment]
> And I believe it would help the motivation of your blur correctors, to tell regularly about your work and status about the blurring algorithm. This allows the user to derive a relationship between his work and the algorithm quality.

I agree, before reading this thread it's wasn't clear if manual blurs (both deleting false positives and adding false negatives) were actually fed back as training data.

**Comment by katrinhumal** [comment]
@jotpe and @andrewharvey good point - we mention that manual blur fixes create data for improving the algorithm on our help pages: https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images but will keep it in mind that we could do more explaining and updates around this.

Also, the "edits" that are counted in our weekly digest comprise both change edits (i.e. location, compass angle etc. map-related) and blur edits. But they are covered with one figure.

**Comment by ybkuang** [comment]
This should be improved by the recent [release](https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html) for privacy blurring. Please let us know if the issues persists. 

You can see that the manual blurs help with the improvement of our algorithm.
