### ISSUE TITLE
different levels

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2653]
This to images are connected, but there are on different levels. Is this wanted :

https://www.mapillary.com/app/index/ifjj1ref?pKey=63ppvHLjR4-Pf0r2DawBYg&lat=50.877923&lng=7.118663&z=17&mapStyle=mapbox_streets&focus=photo&menu=false
https://www.mapillary.com/app/index/ifjj1ref?pKey=iAgNfXM0sS3X6HcBSqd-bA&lat=50.877827&lng=7.118763&z=17&mapStyle=mapbox_streets&focus=photo&menu=false
![bildschirmfoto von 2017-08-07 17-36-12](https://user-images.githubusercontent.com/3539168/29033951-010dd520-7b97-11e7-9b61-3042d65e1b16.png)
![bildschirmfoto von 2017-08-07 17-36-17](https://user-images.githubusercontent.com/3539168/29033952-010ec9f8-7b97-11e7-8fb6-a6170cd83982.png)

**Comment by katrinhumal** [comment]
@jotpe Thanks for pointing this out! As for now, we don't have a way to separate between levels on Mapillary. Everything counts as "street level" (this, besides the lack of GPS, is also one of the biggest obstacles between Mapillary and indoor mapping). So right now, I'm afraid there is not much we can do about that...
