### ISSUE TITLE
Sequence stucks at the same coordinate

### ISSUE THREAD

**Issue by raymondde** [mapillary/mapillary_issues#2657]
Another user added a comment to https://www.mapillary.com/app/?pKey=LZIwnsYe902ThqLFvd4e5A&lat=50.913485149999985&lng=7.031052369999998&z=17 

All (?) images of this sequence seems to have the same coordinate. It was recorded was an iPhone 4. I do not know if this is a malfunction of the iPhone or an issue with Mapillary.

To repair the sequence I can offer to upload the GPX track of this track, recorded at the same time with another smartphone.

Or should I request the deleletion of this sequence?

**Comment by ulikoehler** [comment]
That certainly doesnt look right, but is it correct that the sequence was taken in 2015? Maybe it was an issue with an old version of the app?

**Comment by raymondde** [comment]
Yes, 2015 is correct. I cross-checked with my separate recorded GPX tracks.

**Comment by katrinhumal** [comment]
@raymondde Thanks for reporting! If this was taken a long time ago and the current app version doesn't give you trouble, then we just need to fix your existing sequence. Would it work for you if I get you the image originals (I don't suppose you have those still) and you use either our scripts or some program like Geosetter to combine that with the GPS track, then reupload? And we can delete the old, corrupt sequence after that.

**Comment by raymondde** [comment]
@katrinhumal Right, I do not have the original images. As always deleted after uploadiing to Mapillary. Getting these images would be great. Matching the images with my GPX track should work with GeoSetter (already installed on my laptop. Thank you for your help.

**Comment by ulikoehler** [comment]
@raymondde I think @katrinhumal meant they can provide you with the original images. I think using the python script `upload_with_preprocessing.py` would work (maybe the GeoSetter approach will work as well, I haven't worked with it) but I'm not sure how exactly it works internally.

**Comment by raymondde** [comment]
@ulikoehler Yes, that is what I understood from @katrinhumal 's answer. Maybe my reply was misleading. Sorry. Waiting for the original images now..

**Comment by ulikoehler** [comment]
@raymondde Sorry, I must have misunderstood you previously. In case you have no experience with the scripts, I can try to help if you want. Please feel free to ask :-)

**Comment by katrinhumal** [comment]
@raymondde Sounds great, I'll be getting you the images soon - meanwhile, do you want to give me your email address so I can share them with you then? Please send it to support@mapillary.com if you don't want to wave it around here in public. :)

**Comment by raymondde** [comment]
@katrinhumal Email address sent per mail.
