### ISSUE TITLE
wrong name of Location

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2658]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Search for a City over https://www.mapillary.com/app/
 2. Provide "64546"

and

 1. Search for a City over https://www.mapillary.com/app/
 2. Provide "Walldorf"

### Expected behavior

Should list 64546 Moerfelden-Walldorf (and others that are have postalcode 64546)

### Actual behavior

Its showing FKK, Wilds-, Walldorfer Badesee, 64546, Mörfelden-Walldorf, Groß-Gerau, Darmstadt, Hessen, Germany

More Difficult is, when u looking for Walldorf, you see Walldorf, Germany
We have 2 Walldorf's in Germany one is in HESSEN .. 

### Additional information

Can you please adjust it, that it's show 64546, Mörfelden-Walldorf, Hessen, Germany

and

Walldorf (Hessen), Germany

**Comment by katrinhumal** [comment]
@thoschu96 Thanks for bringing this up! We are actually using Mapzen's search so it's not built by us. But @gyllen or @peterneubauer might have more insights into if and what we could do here from our side.

**Comment by gyllen** [comment]
@katrinhumal Unfortunately there is nothing we can do about this because as you stated the search is powered by Mapzen.
