### ISSUE TITLE
Distance and Time based capture not working in Android 3.68 beta

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2659]
Both distance and time capture appear broken in 3.68.  I was parked with distance move enabled and the app was taking pictures as fast as possible. If i disable distance mode and St the time interval to 10 seconds, it still took pictures every half second of one second.

**Comment by jfburke3** [comment]
Or maybe not.  Went into developer settings to enable trace logs and saw skip location check was enabled. Not sure how that happened. Disabled it and things seem normal. 

And version is 3.83 not 3.68.

**Comment by katrinhumal** [comment]
@jfburke3 self-resolving issues, we love those! Thanks for reporting and let's keep an eye on this anyway. It doesn't sound completely right even for the case where location skip is checked, but I think for now this is not a priority to sort out, we still have lots to do to get the standard capture stable first.

**Comment by kaitu** [comment]
I just incurred in the same issue: distance based setting was ignored. It took me a while to figure out that the skip location setting was the culprit, therefore I wouldn't call this exactly a self-resolving issue. Shouldn't be difficult to fix either.

**Comment by katrinhumal** [comment]
Assigning @ovivoda here so he has this on his radar.
