### ISSUE TITLE
ESRI showing wrong map

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2661]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Check Mapping in Roedelsheim (Frankfurt) - Roedelheimer Landstrasse

### Expected behavior

We should see an S-Bend on the ESRI Map Layer, but it's a straight street.

### Actual behavior

...
![image](https://user-images.githubusercontent.com/10342344/29271628-b1ca5ae0-80fc-11e7-9383-b4a02e9ca28b.png)

![image](https://user-images.githubusercontent.com/10342344/29271641-c27ea59e-80fc-11e7-93da-a957aac52f7b.png)

### Additional information

...

**Comment by gyllen** [comment]
@knikel Please look at this and elevate if needed.

**Comment by knikel** [comment]
@thoschu96: It looks to me that these are two different vector styles of the basemap. Do you happen to know which ESRI style is the one you posted a screenshot of? AFAIK we're using the style for ESRI basemap _as is_ without any modifications and it's one of the _simpler_ ones they provide (less details).

**Comment by thoschu96** [comment]
hey @knikel : the first picture is from Mapbox Streets and the Second is from ESRI Streets.
But i can't see , which Version is taken..  i guess, thats need to get checked from internal
My Opinion is, that all BaseMap that can be choosen, showing detailed level with correct Streets.
Or make a Flag, that the Enduser who choose the BaseMap Adjustment, see that it has less details (for speeding up the performance) otherwhise it will be confusing us

**Comment by knikel** [comment]
Some time ago we've updated ESRI sources in the vector tile styles to the latest, these areas look way better now. Check around [here](https://www.mapillary.com/app/?lat=50.14031696966137&lng=8.627344183803189&z=15.174931991850833&mapStyle=esri&focus=map).
