### ISSUE TITLE
Cancelling upload causes all images to be uploaded

### ISSUE THREAD

**Issue by JamesKingdom** [mapillary/mapillary_issues#2662]
### Basic information
* Platform: `Android` 
* Version: `3.61` 

### Steps to reproduce behavior

 1. Start uploading one sequence
 2. Click `Cancel`
 3. Click `Resume`

### Expected behavior

It will resume uploading just that one sequence

### Actual behavior

It uploads every sequence on your phone

**Comment by katrinhumal** [comment]
Hi @JamesKingdom - thanks for reporting! Would it be possible for you to send us some logs of this? Please go to Settings > Developer and check "Save debug logs to file". Then try to reproduce the problem, and send the logs from the left-hand menu.

A second thing you could do is to join the beta programme (from the same menu or from Google Play) and see if that version gives you the same problem.

Assigning our Android developer @ovivoda to this.

**Comment by jfburke3** [comment]
I've encountered the same thing.  This has persisted across several versions.  Not sure exactly when it bega, but it does happen in the current 3.89 release.

**Comment by katrinhumal** [comment]
@jfburke3 would you be able to send some logs of this, by any chance, so @ovivoda can take a look into it?

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
