### ISSUE TITLE
Very slow "upload" tab

### ISSUE THREAD

**Issue by zagor** [mapillary/mapillary_issues#2663]
### Basic information
* Platform: Android
* Version: 3.83
* Phone: Xiaomi Redmi 4X

### Steps to reproduce behavior

 1. Capture many thousands of photos during your holiday
 2. Click "Upload" tab
 3. Wait a very long time

### Expected behavior

Reasonably responsive behaviour even with lots of photos

### Actual behavior

Mapillary is spending so much time enumerating photos that Android thinks it has hung and asks if I want to kill the app. Sometimes multiple times. No visual feedback in the app whatsoever until all photos are counted.

This also causes unattended uploading to fail, since the slowness causes Android to suspend and/or kill the app before uploading can finish.

### Additional information

I have ~35 sequences and ~10000 images left to upload. I have uploaded a half-dozen sequences under manual manual supervision (so I can click "wait" when Android asks if I want to kill Mapillary) but I'm now waiting with the rest in case you want to test changes.

Trace log of just switching to the upload tab:
[mapillary_trace_upload.txt](https://github.com/mapillary/mapillary_issues/files/1224415/mapillary_trace_upload.txt)

**Comment by zagor** [comment]
Issue remains in v3.86.

**Comment by echeloni2p** [comment]
I just had >8k pictures in 60 sequences on my honor 7, no issues so far. It took a few moments, but thats fine, just click on upload and it runs.
Looks like the storage of the redmi 4i is really really slow. Where is the limit for you?
You can e.g. move the sequences one by one to another directory?

echelon

**Comment by zagor** [comment]
Sure it may be a little slow, but not drastically so. I ran "A1 SD Bench" and it shows 150 MB/s read speed and 95 MB/s write speed. That doesn't sound super slow.

**Comment by katrinhumal** [comment]
@zagor could you please try 3.93 which we have out in beta now, and see if it helps anything?

**Comment by zagor** [comment]
Unfortunately, despite my original intention I was unable to keep the images on the device since I needed the storage. 

I found a workaround for uploading: By changing away from the Upload to tab to the Profile tab once upload is started, the app could continue uploading in the background without being interrupted.

I will do a new long capture session soon with the same device and report back my findings.

**Comment by katrinhumal** [comment]
@zagor thanks! Looking forward to hearing back.

**Comment by zagor** [comment]
I now run 3.101 and still see the same problem. I have ~3800 images in 10 sequences, and that is enough to trigger the android kill dialog.

I recorded a short video to illustrate the issue: https://photos.app.goo.gl/x6uzElX6Pd7bYGK72

Video description: The video starts in the profile tab. I scroll up and down breifly to show the application is responding. Then I tap the Upload tab icon and try to scroll again, showing that the UI is frozen. After approximately 10 seconds, the Upload tab is finally drawn and the UI becomes responsive again. But it's too late, the system has flagged the application as unresponsive and throws up the dialog asking if I want to stop it or wait.

![vlcsnap-2017-10-02-19h44m44s184](https://user-images.githubusercontent.com/229360/31091157-58a4b8d2-a7aa-11e7-91d3-3089ab4e6ed7.png)

**Comment by zagor** [comment]
I just got the 3.103 update. It behaves the same way.

**Comment by ovivoda** [comment]
This issue have been fixed in the latest app version
