### ISSUE TITLE
bad resolution

### ISSUE THREAD

**Issue by grinapo** [mapillary/mapillary_issues#2665]
### Basic information
* Platform: `Android` 
* Version: beta
* System/Browser: oneplus1, lineage os latest

### Actual behavior
bad image:
https://www.mapillary.com/app/user/grin?lat=47.52897987643618&lng=21.721103381012654&z=15.499809234371524&pKey=O4IOYU31-O4RvTXr5BzAJQ&focus=photo&feedItem=user-z0MYuvsI0U-carCVexI55Q-activity-user-z0MYuvsI0U-carCVexI55Q-publishing_done-image%3A1502830481976

good image for exactly the same time, same phone, same everything:
https://www.mapillary.com/app/user/grin?lat=47.52834794786071&lng=21.620009965870622&z=17&pKey=8FovjLMMYzt3TPntCrApCA&focus=photo&feedItem=user-z0MYuvsI0U-carCVexI55Q-activity-user-z0MYuvsI0U-carCVexI55Q-publishing_done-image%3A1502830481976

**Comment by HolgerJeromin** [comment]
I have the same since a few weeks every now and than on my Fairphone 2 (android 6, legacy cam api). Some sequences are very ugly and buggy funny colors, too.
The sequence after that has normal quality. 
I do not upload these.

**Comment by echeloni2p** [comment]
Hi

looks like the API of the mobile does some bad things. In these cases: kill mapillary app and restart.
Or use the old style API, not APIv2. I got this with my onePlus3, to. Use old style API (in the settings) prevents mapillary do have bigger issues.
It is a API issue, as the mobile phone companies do not really support the case of doing hundreds of pictures one after another. They simply do not test this and do not bug fix this at all.

echelon

**Comment by HolgerJeromin** [comment]
As i wrote: i do use the legacy cam api....

**Comment by grinapo** [comment]
@echeloni2p also it used to work, and it works randomly, and it's almost impossible to detect it within the app. I have full debug logs around, at least I intend to. :)

**Comment by andrewharvey** [comment]
I'm running into this as well when capturing on Android. It looks like it only has the thumbnail size, seem to be random per sequence.

**Comment by grinapo** [comment]
As a constructive-feeling comment I would - sadly - advise to check the image resolution (or even its general and known jpeg parameters) coming from the API and scream loudly if it differs from what's expected; I mean if you expect imagery sized 4321x1234 you should not happily accept 320x200 sized results. Possibly as a user-switchable safety-debug feature. Surveying a large area in thumbnails is a bit disappointing. 

(And tell me when I can remove the thumbnail-sequences of mine, or if you want to keep them, inform me about it.)

**Comment by katrinhumal** [comment]
@grinapo good points! About those logs you mentioned, would you be able to send us some so that @ovivoda can take a look?

**Comment by grinapo** [comment]
Unfortunately you have to wait till next time, I had some changes on the phone which required a reinstall. A few days since I successfully broke my mapillary-holder, and waiting for the replacement. :-/ Maybe others can enable debug logging and catch a bad one.

**Comment by katrinhumal** [comment]
Competition! Who gets to send logs first ;) I hope the new mount reaches you soon. We send them out at least every week so hopefully the postal services will act fast too.

**Comment by andrewharvey** [comment]
I ran into this issue again loosing a few thousand images :disappointed:. I've just enabled Developer | Save debug logs to file so hopefully next time I can send in the logs. I can't replicate right now (seems random).

**Comment by katrinhumal** [comment]
@andrewharvey 3.103 which is on Google Play now includes a fix for the low-res problem. Please make sure you've updated and I really hope you won't see this issue anymore.

**Comment by andrewharvey** [comment]
Awesome @katrinhumal, I'll try it out.

I had just collected a mapillary_trace.txt of when the issue occurred, but hopefully it won't be needed anymore. I think you can close this issue then, and if we see it again post version 3.103 / 403, we can post back here.

**Comment by katrinhumal** [comment]
Thanks @andrewharvey! Just checking in with @grinapo as well - can you see if the latest version has fixed the problem for you?

**Comment by grinapo** [comment]
@katrinhumal I was not able to reproduce it since then, I have debug on, if you don't hear about me then it's still okay. But I'm not _very_ active nowadays (horrible weather plus lack of travel).

**Comment by katrinhumal** [comment]
@grinapo All right - thanks! I'm closing the issue for now, please reopen if necessary. Hope to not hear about you then! ;)

**Comment by grinapo** [comment]
*sigh* Got blurry with 3.104 again, 
https://www.mapillary.com/app/?lat=47.641129545310946&lng=18.838364344718684&z=17&focus=photo&pKey=VKnqhVQc5tk29jA6pAN23Q
Got plenty of debug logs, where do you want to get them?

**Comment by katrinhumal** [comment]
@grinapo Thanks for the logs, passed them on. Sorry that the problem returned, @ovivoda will take a look.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
