### ISSUE TITLE
Images and sequences from the future

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2666]
The repository accepts images and creates sequences with time stamps in the future.

### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Any`

### Steps to reproduce behavior
 1. For example, goto [`https://a.mapillary.com/v3/images/?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&end_time=2020-12-31`](https://a.mapillary.com/v3/images/?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&end_time=2020-12-31) or [`https://a.mapillary.com/v3/sequences/?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&end_time=2020-12-31`](https://a.mapillary.com/v3/sequences/?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&end_time=2020-12-31)

### Expected behavior
Images with time stamps in the future should not be accepted by the repository or should be discarded. The repository should not create sequences with time stamps in the future either. 

### Actual behavior
Nothing prevents from uploading images (neither by mistake nor on purpose) with time stamps in the future. Both, images and sequences with time stamps in the future exist. However, I do not know how sequences came about to have time stamps in the future.

**Comment by GITNE** [comment]
I have just discovered that many of the sequences *from* the future have been created from video processing. Take these images/sequences for example: [`https://www.mapillary.com/app/time-travel?pKey=IvTn1vmfh9Oe9S-7RzGS_A&focus=photo&cKey=YxzHqsXfPF8sMqXi7qpd7g`](https://www.mapillary.com/app/time-travel?pKey=IvTn1vmfh9Oe9S-7RzGS_A&focus=photo&cKey=YxzHqsXfPF8sMqXi7qpd7g).

**Comment by gyllen** [comment]
@GITNE Thanks for this information

@peterneubauer reassigning

**Comment by peterneubauer** [comment]
So, some of the videos actually have a future date, we are looking into that. Also, there are some images that are on future dates, I will check that out and try to correct it.

**Comment by peterneubauer** [comment]
Future dates are now fixed, closing this for now.
