### ISSUE TITLE
ios app might be losing images

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2667]
mapillary ios app 4.8.2, iphone 6.

took 1100+ images. started the upload. in less than a minute it told me all images were uploaded. although my connection isn't bad, i'm quite sure it is not possible to upload that many images in that short time, this i suspect the images might be lost.

this is a rushed report, i haven't done full testing yet or verified that the images are gone.

**Comment by millenbop** [comment]
Thanks for reporting, I'll look into it!

**Comment by millenbop** [comment]
Ok fixed now. So sorry about this! Uploading update to Apple now.

**Comment by richlv** [comment]
thank you for the quick fix
