### ISSUE TITLE
User Filter and Time Filter gives incomplete result

### ISSUE THREAD

**Issue by arvdk** [mapillary/mapillary_issues#2668]
### Basic information
* Platform: `Web`
* Version: `current` 
* System/Browser: `Tested on chrome & IE11`

### Steps to reproduce behavior
1. Check the west part of the [city center of Gouda](https://www.mapillary.com/app/?lat=52.011212408654984&lng=4.712442244530649&z=15.452896331166848),The Netherlands (most sequences are mine) 
2. Filter by date or by [user = arvdk](https://www.mapillary.com/app/?lat=52.011212408654984&lng=4.712442244530649&z=15.452896331166848&username%5B%5D=arvdk) (me)

### Expected behavior VS Actual behavior
Not all my sequences are shown. Clearly a couple of sequences in west city center of Gouda are mine but doesn't show after filtered. (for example  [sequence key 9GPb3G4_rNSwi8ZEV99MUQ](https://www.mapillary.com/app/?lat=52.01342037363304&lng=4.706312391650272&z=17&pKey=YCburKQlBHqUMz1P0U3i-w&focus=map)  )

### Additional information
* All sequences that don't show are from the same date, if i'm correct)
* Redirected from [mapillary forum](https://forum.mapillary.com/t/filters-dont-work-anymore/381/4)

**Comment by katrinhumal** [comment]
@arvdk Thanks for bringing the report here! Handing this over to the developer team.

**Comment by gyllen** [comment]
@arvdk Thanks for reporting

@ptpt This looks like a bug in tiler to me, there should be no reason why that sequence should not be filtered in since it should have `arvdk`s key. Can you look at this and elevate if necessary.

**Comment by Eric-FR** [comment]
I'm also facing a similar problem. I'm trying to filter my own tracks in Mahajanga city. When I set the Date filter between 2017-01-01 and 2017-07-24, it is displaying several tracks although none of them were recorded in the interval. 
![mapillary_date_selection](https://user-images.githubusercontent.com/32433543/33067676-2ceb5ad0-ceaf-11e7-9d46-1f0e8b47966f.png)

**Comment by Eric-FR** [comment]
On the same place, when filtering between 2017-01-01 and now, some tracks are hidden although recorded and uploaded this year.

**Comment by ptpt** [comment]
@arvdk the filtering is fixed!

@Eric-FR the image is captured at `2017-01-01T00:00:22.893Z` while uploaded at `2017-08-02T03:58:16.575Z`. The time filtering applies on capture time, while the time shown on the bottom of the image is the creation time. We have tracked it internally as a design problem and close here. Thank you for reporting.
