### ISSUE TITLE
Force landscape mode in Android TV Sony Bravia with some setting

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2669]
When I put your app in my new Android TV Sony Bravia I have a problem: app insist in being in portrait mode so Mapillary app is rotated 90 degrees to the left. Is it possible to add some option or setting to "force" landscape mode? If not I have to install other app to do so, but for now Mapillary is the only app does not respect the layout of my Android TV.

**Comment by katrinhumal** [comment]
@yopaseopor Thanks for your question!

@ovivoda do you have some insights?

**Comment by Shinigamae** [comment]
@yopaseopor you can download this apk http://www.mediafire.com/download/48v6ys23vykvs00/Screen.Rotation.Android.TV-7.9.apk, install it on your TV and set the orientation to Landscape only. I have tried and it works like charm!

**Comment by yopaseopor** [comment]
thanks for the solution...but as this is the future (Android TV) or the
present I would like to some day Mapillary thinks about this in a future.
Pics and panoramas are better in a 55'' TV if you cannot go to the place
itselfs ;)

**Comment by katrinhumal** [comment]
Thanks, @yopaseopor - we'll take this into consideration for the future! I'm closing here now since there won't be an instant fix from our side and you now have a workaround.

**Comment by F1F1** [comment]
"Trojan-Spy:Android/Smforw variants silently forward incoming SMS messages on an infected device to a remote server."

File name | Screen.Rotation_.Android_.TV-7_.9_.apk
Other known file names | Screen.Rotation_.Android_.TV_[7_.9]_.apk
MD5 hash | 7173ac30364aac1dfbb26f88e387b08a
SHA256 hash | cc92648ec31363ba31e28729e563561bd1acd631f6c9f8eff45dfd26da1c89db
File size | 583.78 KB
Worker | NVISO_API_KALI_01

https://apkscan.nviso.be/report/show/7173ac30364aac1dfbb26f88e387b08a
