### ISSUE TITLE
Re-login after settings ?

### ISSUE THREAD

**Issue by mr-j0nes** [mapillary/mapillary_issues#2671]
I have noticed when I exit from settings the APP tries to login again.
This is a huge drawback when I have no internet, the APP gets stuck trying to load the login page..

**Comment by katrinhumal** [comment]
@mr-j0nes Thanks for reporting! We have heard this before and if I recall correctly, actually provided a fix. Can you please tell us which app version this happens with?

**Comment by mr-j0nes** [comment]
Thank for the answer. The version I have now is 3.89. I just tried and the problem is still there.
Even after checking the "credits" in the menu it gets logged out and asks for a new login. Weird X(

I use the openstreetmap credentials as login ...

**Comment by ovivoda** [comment]
This issue has been fixed in the latest android app version
