### ISSUE TITLE
Give some ID to every IA recognized item 

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2674]
Now as you have new types of automatic recognition of different things it would be interesting to give every element an unique ID. This would be so useful to solve, for example traffic sign recognition duplicates as the community would mark the meaning of every item and this would never be repeated again, because an item could be watched in more than one pic. Also this would enable the possibility to "attach" meanings in systems like OSM to these "unique" items (for example traffic signs, but also street lights, traffic_lights,recycling containers...)

**Comment by katrinhumal** [comment]
Actually, this is something we're working on. With traffic signs, we already create what we call "map objects" from the image detections. That means that we process the information from several images and figure out that it depicts the same real-life object. So the traffic sign detections (which you can turn on separately in our viewer, or iD, or JOSM) already represent unique objects (with some occasional errors). The rest of the AI detections are still in the phase of just recognising it in the image, and the map giving the location of the image (not the object itself) but we're working onwards to start creating map objects from all other detections as well.

I hope this addresses your proposal @yopaseopor?
