### ISSUE TITLE
Web uploader causes double uploads

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2675]
### Basic information
* Platform: `Web`
* Version: `Any`
* System/Browser: `Firefox`

### Steps to reproduce behavior
1. Choose files to upload
2. Wait for a few files to complete uploading
3. Cancel upload by clicking `Exit Uploader`
4. Return to uploader
5. Click `Delete all`
6. Choose the same files to upload as in step 1
7. Click `Upload`

Note that although the counter does not move and stays at `0 / X` all files are uploaded. After all files have been uploaded the counter (finally) starts counting and all files are uploaded again (while the counter is incremented, beginning from 0). From what I have observed this process may also create duplicate sequences.

### Expected behavior
**All** files should be deleted from the staging area, the list of files on the client cleared, and the counter properly reset to `0` after the `Delete all` button has been clicked.

### Additional information
Possibly, the JavaScript array or list holding the list of files to upload (or already uploaded files) is not recreated or wiped but reused. To prevent this, that is to create a new array set the array variable to `null` before assigning a new array to the variable. It should be safer to create a new array than wiping an existing array.

**Comment by katrinhumal** [comment]
@GITNE thanks for reporting and sorry for the late reply! We'll check up on this. 

Just to check, what you have noticed is that this may result in producing _two identical sequences_, not _one sequence where each image has a duplicate_? (I recently saw this latter case and am trying to figure out if this might be related.)

**Comment by GITNE** [comment]
It's the first of the two. To be more specific, the sequences are identical in content but not in sequence id.

**Comment by gyllen** [comment]
@peterneubauer Reassign to @nickplesha of you think this is a frontend issue

**Comment by ovivoda** [comment]
@nickplesha please check this one and let me know if it make sense to be assigned to you

**Comment by nickplesha** [comment]
Thanks! @GITNE We've since updated the uploader to clear the upload list after exiting. Let us know if you encounter similar errors.
