### ISSUE TITLE
Authentication vulnerable to leaking login credentials

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2676]
### Basic information
* Platform: `iOS`, `Android`, `Web`
* Version: `Any` 
* System/Browser: `Any`

The current authentication scheme via `https://a.mapillary.com/v1/u/login?email=<email>&password=<password>&client_id=<client id>` is vulnerable to leaking credentials to URL history lists (like browser history, proxy logs, or server logs) and cache hash maps (like in browsers and on HTTP(S) proxies).

With regards to caches, it is common for cache implementations to use URLs in canonical and non-canonical forms as hash map keys. Additionally, caches can be shared both locally and on proxies. Especially on proxies, URL cache hash map key may live for a long time, potentially adding to the dangers and probability of getting revealed.

Keep in mind that even friendly HTTP(S) proxies still need to be provided with full (and clear text) URLs by the client in order to either look up internal caches or to request cache misses from the origin. If credentials are transferred in the message body on HTTPS connections then they can be regarded as safe against friendly and malicious proxies (Unless a malicious proxy is successfully spoofing server certificates or TLS connections in general. But, this is a topic of its own).

To prevent these leaks, credentials must be transferred in the message body of HTTPS requests. Transferring credentials in message header fields does not prevent leaking either because HTTP(S) proxies still need to process message headers. To that end, all HTTP(S) requests and responses transferring credentials **should** specify [`Cache-Control: no-cache`](https://tools.ietf.org/html/rfc7234#section-5.2.1.4) and [`Cache-Control: no-store`](https://tools.ietf.org/html/rfc7234#section-5.2.1.5) (or `Cache-Control: no-cache, no-store`) when exchanging credentials. Both servers and clients should honor the semantics of [`no-cache`](https://tools.ietf.org/html/rfc7234#section-5.2.2.2) and [`no-store`](https://tools.ietf.org/html/rfc7234#section-5.2.2.3).

Ideally, credentials and especially passwords should never be sent in clear text, even on encrypted connections. Hence, a challenge scheme might be employed to avoid sending credentials in clear text.

**Comment by katrinhumal** [comment]
Thanks for drawing our attention to this and sorry for the delay! We'll check up on this asap.

**Comment by GITNE** [comment]
Yeah, `https://a.mapillary.com/v2/ua/login?client_id=<client id>` does it the right way, except for the fact that the password is basically only protected by symmetric TLS encryption, instead of being a challenge response token or the like.

**Comment by gyllen** [comment]
@GITNE Thanks for drawing attention to this, `v1` should be shutdown and you should not be able to login with `v1`.

A challenge scheme would be the next thing to implement.

**Comment by gyllen** [comment]
Closing since `v1` is no longer in use

@martinskans FYI
