### ISSUE TITLE
latest ios app version frequently becomes unreponsive

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2677]
ios 9, mapillary 4.8.3.

since the latest upgrade (or two), the app frequently becomes unresponsive. while the pic is update normally, no controls react to tapping. at the same time, whole phone becomes slow - even after force-killing mapillary, phone can be unresponsive for ~5 seconds.

there are times when the app works ok for hours, and times when it hangs every 10 seconds - it hangs, kill it. start it back up, start the capture, hangs in 10 seconds - and so on 5 times in a row.

full phone restart does not resolve the problem.

this does not seem to be related to the map, at least not directly - hangs happen both when not using the map at all (most of the reproduced hangs) and sometimes when switching to the map.

**Comment by katrinhumal** [comment]
@richlv Thanks for reporting and sorry for the late reply. We're up to 4.8.6 now - can you try and report back if you notice similar issues with that?

**Comment by millenbop** [comment]
Thanks for reporting @richlv.

What settings are you using? Are you using distance or time-based capture? Which interval? What phone are you using?

**Comment by richlv** [comment]
distance based, iphone 6.
this has happened also when viewing images/uploading, capture not started at all. the latest freeze happened with 4.8.6.

**Comment by millenbop** [comment]
Thanks! I'll see what I can find.

**Comment by millenbop** [comment]
Are you on Testflight btw? Can send you an older build in that case.

**Comment by talllguy** [comment]
I'm having the same issues on the production version of the app.

The crash/freeze causes the entire phone to come crashing to a halt. Force closing the app renders the iPhone unresponsive for a few seconds. I figured it might have something to do with my iPhone 6s Plus being lower powered than the current models.

**Comment by richlv** [comment]
@millenbop, sorry about the delay. i didn't really know what testflight is, but found it and installed.

an older build would be hard to test still - the bug sometimes does not appear for days, and then it just happens constantly. haven't figured out what makes it come out.

**Comment by millenbop** [comment]
I have experience it as well, but only since I upgraded to iOS 11 beta. I still have the same problem with iOS 11.0. Searching the internet it seems to be a common problem with the latest iOS update.

But I don't know why it would happen on iOS 9 :/

**Comment by millenbop** [comment]
@talllguy which iOS version are you on?

**Comment by talllguy** [comment]
@millenbop I was on iOS 10 but recently upgraded to iOS 11. I have to redownload the app and test there. I deleted it before upgrading.

**Comment by jfburke3** [comment]
I want to make the observation that the Android version has a similar problem; I just haven't had time to report it properly yet.  Maybe this is a good time to do so.

**Comment by millenbop** [comment]
I'll submit a new build today. I have updated all libraries we depend on and also done some optimizations to our app and so far we haven't experienced any slowdowns. It doesn't mean it's fixed but I hope it is! Maybe we have just been lucky.

Let me know when you get a chance to try it out.

**Comment by millenbop** [comment]
The update got out last Saturday, let me know if you think it works better or if it's the same.

**Comment by richlv** [comment]
updated as soon as the new version was available, have used for a few full days since then - no hangs yet. probably need a few weeks of usage more - we can close this issue if nobody has experienced hangs with the latest version.

**Comment by millenbop** [comment]
Ok, closing this one for now. Let me know if anyone experiences it again and I'll reopen. Thanks for reporting in @richlv.
