### ISSUE TITLE
Give some love to the 'mapillary_tools' repo

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2678]
There's a ton of pull requests over at https://github.com/mapillary/mapillary_tools/pulls

Could someone from Mapillary look at them and accept or reject some?

**Comment by katrinhumal** [comment]
Thanks for bringing this up! I'll usher the dev team on this.

**Comment by katrinhumal** [comment]
The mapillary_tools has got a recent [rebuild](https://blog.mapillary.com/update/2018/05/31/updated-upload-tools.html) and also more love in the repo. Closing here.
