### ISSUE TITLE
@sequence_cut not working

### ISSUE THREAD

**Issue by heatshear** [mapillary/mapillary_issues#2679]
### Basic information
* Platform:  `Web`
* Version: `60.0.3112` 
* System/Browser: `Chrome`

### Steps to reproduce behavior

 1. Upload images with a long gap in the sequence
 2. Wait patiently for @sequence_cut to do its thing
 3. Keep waiting

### Expected behavior

@sequence_cut will cut the sequence (used to work fine)

### Actual behavior

Nothing happens - I have a few sequences that never got edited.

### Additional information

I try not to upload these kinds of gaps, but some get away from me. Here's a screenshot of one from 2 weeks ago, at 
Latitude
45.298642264444425
Longitude
-75.73152101583332

![capture](https://user-images.githubusercontent.com/30479453/29626198-fc5313b2-87fb-11e7-818d-5b2c9b401ace.JPG)

**Comment by Alessandro-Barbieri** [comment]
Same, this sequence `ev8rvb6iemkb50gvc6mqrr` is 3 years old and still not split https://www.mapillary.com/map/im/XpjxuH_57DwDwW6rQnUbig

**Comment by heatshear** [comment]
It looks like someone at Mapillary took care of the sequence I identified, but I could flag a ton of others that have the same issue. It would be great if there was a way to flag sequences that need some attention for sequence_cut, because it seems to miss some and never come back for them.

**Comment by katrinhumal** [comment]
@heatshear Thanks for reporting and sorry for the late reply. It happens every now and then that some of these escape cutting, and we could indeed use a better system for discovering these retrospectively.
@gyllen do you have any insights into this?

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal do you re-run the bot on a sequence after an image is deleted/masked?

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Nope, we don't.

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal You should, deleting photos leave holes in the sequences, like the one I linked before.

**Comment by gyllen** [comment]
@Alessandro-Barbieri This is a great point

@peterneubauer @ybkuang Is there anything we can do to sched a sequence for cutting if images are deleted

**Comment by ybkuang** [comment]
@gyllen @Alessandro-Barbieri  it is possible after the upcoming database update

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
