### ISSUE TITLE
Frequent crashes since Android patches (Samsung Galaxy S7 Edge, Android 6.0.1)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2680]
Special note:  Up until now, my phone has been running AT&T baseband version G935AUCS2APC2 (aka "PC2").  All of my previous Github issues were related to that version.  Not sure how the new release I have installed will affect those yet.  It might be a good idea for you to add "Android baseband version" to the information you request from people.

### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.89
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1. Start with an original AT&T model Samsung Galaxy S7 Edge on the original G935AUCS2APC2 baseband version.
 2.  Shoot loooong sequences.  Be happy.
 3.  Update the baseband version to AG1.
 4.  Shoot sequences and watch the app crash.  Be unhappy.

### Expected behavior

Happiness and joy as the app takes many pictures.

### Actual behavior

Misery.  Despair.

### Additional information

My phone was updated from AT&T baseband version PC2 to PG1 over the weekend in a series of several patches.  Not entirely voluntary.  I've been bickering with AT&T for almost a year over the fact that my phone was still on the original release level and none of the published security updates were ever downloadable.  I guess someone finally figured out the problem.  Late last week I started getting notifications that an update was available, but I kept postponing it.  In the middle of the night Saturday/Sunday, the update installed anyway.  Another patch was pending when I woke up, so I went ahead and installed it.  Later I checked for more updates, and another was available, so I installed it, too.  (Better to install them on my schedule than theirs.)  So in the course of about 8 hours, my phone went from patch level PC2 to PG1.  It's still Android 6.0.1, just with different patch levels.

Sunday afternoon I went for a planned drive to get out away from civilization and relax, and shoot some imagery.  Unfortunately, now the Mapillary app keeps crashing out of camera mode incredibly frequently, anywhere from 4 or 5 images into a sequence, up to maybe 110 or 115 images.

This happens with both distance and time capture modes.

I tried uninstalling/reinstalling, but that didn't help.  I changed various settings in the app, which also didn't help.  

The only other thing I could think of was a new "Display size" setting that was introduced in the AG1 patch level, which just has values of "larger" and "smaller" (but I assume affects the DPI of the screen, I need to try to research that).  I'd changed it to smaller after the patch installed, and so I changed it back to larger (which seems to equate to what the original screen appearance was), which required a reboot.  Nada, it still crashes.

Attached is a somewhat lengthy trace log (that I've already e-mailed) that should show at least some of the various settings changes I tried, along with the crashy behavior.  Hopefully it will shed some light on the issue.
[mapillary_trace (1).txt](https://github.com/mapillary/mapillary_issues/files/1255143/mapillary_trace.1.txt)

**Comment by drkludge** [comment]
I am on Platform: Android 6.0.1 also.  My answer to peace and harmony in the universe is as follows:

0. Find version 3.44 of the application and download it to your phone.
1.  Turn off automatic updates for all applications.
2. Update all other applications except Mapillary.  Update daily as the security updates come in.
3. Uninstall your current version of Mapillary.
4. Allow your phone to install from local files or whatever. (I am doing this from memory.)
5. Install the 3.44 version.  I use version 3.53 for bike rides.

- I found a great deal of flakiness after 3.53 on 6.01.  I do not like how this sounds but I would forego all other benefits of the newer Mapillary software for my peace of mind.  I wish I could be more positive than this.
- This also means that I keep a list of my Mapillary configuration changes to apply when I move back and forth between 3.44 and 3.53.  I have had to delete/uninstall 3.53 to reinstall 3.44.
- Like you I am known to go for a drive.  It is not cool when the drive in the open country is fraught with Mapillary issues.

**Comment by jfburke3** [comment]
@drkludge Except I want some of the fixes in the newer releases.....

**Comment by jfburke3** [comment]
Annnnd.... there's another Android patch waiting for me this morning.  I'll probably go ahead and install it today (sorry Mapillarians, I know that complicates troubleshooting the problem).  Maybe it'll actually fix the issue.....

For reference, here's AT&T's release notes on the updates.  You'll need to open the "Previous updates" section:

https://www.att.com/devicehowto/tutorial.html#!/stepbystep/id/stepbystep_KM1135854

**Comment by jfburke3** [comment]
I should note that after a while, I gave up on trying to run Mapillary on the S7, and switched to the S5 (Android 5.0), where it ran fine, except that the camera isn't as good.  I also ran OSC on the S7, and it didn't have any problems.  But....OSC doesn't use the Camera2 API.  I didn't try running Mapillary with Camera2 switched off, so if I get some time, I'll try that and see what happens.

**Comment by jfburke3** [comment]
I installed the pending update and jumped from PG1 to PJ4.

**Comment by jfburke3** [comment]
Same issue after update to PJ4.  It takes a random number of pictures before dropping out of camera mode.  I e-mailed in a fresh log (subject line begins with "Github # 2680").

**Comment by jfburke3** [comment]
The 3.91 apk that @ovivoda sent me seems to fix the problem.  It appeared to work well on both Android 6.0.1 PJ4, as well as Android 7.0 QA6.

**Comment by katrinhumal** [comment]
@jfburke3 thanks for the detailed reports and sorry that the issue here didn't get any attention. Assigning @ovivoda so that you guys can wrap this up and/or give an update of the troubleshooting you may have via other channels.

**Comment by ovivoda** [comment]
@katrinhumal I think we can close this as jfburke3 confirmed it is fixed.

**Comment by katrinhumal** [comment]
Closing then, @jfburke3 please reopen if trouble returns.
