### ISSUE TITLE
Stop sign when traffic lights are flashing or broken

### ISSUE THREAD

**Issue by andrewharvey** [mapillary/mapillary_issues#2681]
For example at https://www.mapillary.com/map/im/XcMyajXjUtlh7pDfQSAgww this appears to be detected as a regular stop sign. But those three black circles mean its different. It means stop when the traffic lights are flashing or broken.

![selection_001](https://user-images.githubusercontent.com/117278/29767429-beca2fa2-8c25-11e7-92a2-827427e803a1.png)

**Comment by jfburke3** [comment]
Where is this?  I've never seen a stop sign like that before.

**Comment by andrewharvey** [comment]
> Where is this? I've never seen a stop sign like that before.

You can see the location in the link, it's common in NSW, Australia.

**Comment by katrinhumal** [comment]
@andrewharvey Thanks - I'll pass this on to our computer vision team! There won't be an instant fix but they can take this into account in the ongoing improvements to the detection system. Closing here.
