### ISSUE TITLE
Street sign recognition miscategorizes seamark signs

### ISSUE THREAD

**Issue by blobgo** [mapillary/mapillary_issues#2682]
Mapiilary does not seem to know different [seamark](https://wiki.openstreetmap.org/wiki/Seamarks/Seamark_Objects) [signs](https://wiki.openstreetmap.org/wiki/Tag:seamark:type=notice) as rendered in iD on OSM.org.

E.g. [here](https://www.openstreetmap.org/edit#map=17/52.40941/13.08744)

**Comment by katrinhumal** [comment]
Hi @blobgo - thanks for bringing this up. Do you have a link to a Mapillary image as well that would be an example of this? I'm afraid our algorithms have not yet been trained to detect these signs. It's possible that it will be added some day.

**Comment by blobgo** [comment]
I already linked to it. E.g. https://www.mapillary.com/map/im/FOiwuZK4rRW0C_9Q337ufg, but see the all images there…

**Comment by katrinhumal** [comment]
@blobgo thanks! I'll pass this on to the computer vision team so that they're aware and can include these in some future version of the detection algorithm. Closing here for now since no instant fix is available.
