### ISSUE TITLE
Vector Tiles with Esri iOS sdk

### ISSUE THREAD

**Issue by AliAdam** [mapillary/mapillary_issues#2686]
Esri ArcGIS API for JS

i tried to add Vector Tiles with Esri iOS SDK  i follow this tutorial https://www.mapillary.com/developer/tiles-documentation/#esri-arcgis-api-for-js
i  use swift   i add it like this
```
let vectorTileLayer = AGSArcGISVectorTiledLayer(url: URL(string:"https://raw.githubusercontent.com/cbeddow/basic_maps/master/esri/mapillary-style.json")!)
self.mapView.map?.operationalLayers.add(vectorTileLayer)
```

but i didn't get any result and no thing added to the map 
 is this vector tiles work only for web or any help how can  i add it with ESRI iOS SDK

**Comment by katrinhumal** [comment]
@AliAdam thanks for your question and sorry for the delayed response! Asking for our dev team for help.

**Comment by gyllen** [comment]
@knikel Can you take a peek at this?

**Comment by knikel** [comment]
@AliAdam: I'm afraid I won't be of much help. The style in the tutorial is correct and after using it you should be able to see Mapillary tiles. Can you confirm that you can load other styles, e.g. with [`ArcGISVectorTiledLayerWithURL`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_arc_g_i_s_vector_tiled_layer.html#a832bf002db72deb5708c3b66ddec0a8a)?

**Comment by AliAdam** [comment]
@knikel  thank you knikel  and sorry for the delayed reply .
 sure i tried this http://basemaps.arcgis.com/b2/arcgis/rest/services/World_Basemap/VectorTileServer/resources/styles/root.json from ESRI and it work fine.

**Comment by knikel** [comment]
`mapillary_issues` is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
