### ISSUE TITLE
No upload of pictures on Samsung A5 / Android 6.0.1

### ISSUE THREAD

**Issue by Ziltoidium** [mapillary/mapillary_issues#2687]
### Basic information
* Platform: Android
* Version: 6.0.1
* System/Browser: `...`

### Steps to reproduce behavior

 1. Upload taken photos with the Mapillary Android app
 2.
 3.

### Expected behavior
should upload pics
...

### Actual behavior
Shows up "upload in progress..."  but nothing happens. 
Sometimes shows "Upload failed Error 0"  or "Java exception"
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/1262400/mapillary_trace.txt)

...

### Additional information
pics are stored on my sd card, not on device. i added the logs as attachment
...

**Comment by jfburke3** [comment]
@Ziltoidium can you add the Baseband Version of your Android build on your phone?  There is a chance that it might be important.  You can get it on the About Device screen.

**Comment by Ziltoidium** [comment]
Baseband A520FXXU2AQF5
Kernel 3.18.14-10911830
Build MMB29K.A520FXXU2AQF5

**Comment by ovivoda** [comment]
@Ziltoidium do you still have the images that caused the problem? Can you please send those to us to investigate more. It seems that those files could not be uploaded for some reason.

**Comment by Ziltoidium** [comment]
sure, i will upload later this evening!

**Comment by Ziltoidium** [comment]
Here are the pictures
https://drive.google.com/drive/folders/0B7Zcm58Uot6baVk0VmtrZFE2a28?usp=sharing

i just saw file size is about 31MB !  Why??
When i usually take pics with the smartphone, these are <10MB.
Maybe a problem with filesize or compression??

**Comment by katrinhumal** [comment]
@Ziltoidium thanks for the images! @ovivoda will take a closer look.

**Comment by Abbe98** [comment]
I have the same issue with my Samsung A5.

**Comment by ArAge67** [comment]
Same here, huge filesizes (30.4 MB) and no upload. Samsung A5 (2017) Android 7.0.

**Comment by jfburke3** [comment]
Just a comment to add some data points for the developers, that I'm not experiencing any problems on Samsung Galaxy S7 on Android 7.0, nor on Samsung Galaxy S5 on Android 6.0.1.

**Comment by kaitu** [comment]
I experienced the same problem with big picture files on Samsung A5, unless I force the use of legacy Cam (Settings -> Developer -> Force the use of legacy Cam).

I had the same issue with the Opencamera app, so I guess that the phone might be at fault rather than mapillary.

**Comment by ovivoda** [comment]
@Abbe98 @kaitu @ArAge67 Please try the latest beta version from GooglePlay and let me know if upload works now for the 30+ MB images.

**Comment by Abbe98** [comment]
@ovivoda it's not possible for me to join the beta program(seams full)...

**Comment by ovivoda** [comment]
@Abbe98 http://android-releases.mapillary.io/Mapillary_Android_v3.112-BETA.apk

**Comment by ArAge67** [comment]
@ovivoda The upload works. Thanks!
