### ISSUE TITLE
Allow disabling most notification in android app

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2688]
### Basic information
* Platform: `Android` 

### Steps to reproduce behavior
 1. Install and setup mapillary on the phone of the partner to have a backup device in case of "emergency" :)
 2. wait a few days to the next "mapillary weekly digest"
 3. The notification is pushed to the partner phone, too

### Expected behavior
On this phone i want only upload <strike>notifications</strike> progress.

### Actual behavior
"mapillary weekly digest" and probably blurs, sequence_cut notification is shown on all registered phones.

**Comment by katrinhumal** [comment]
@HolgerJeromin I think your best solution here is to rely on keeping up-to-date with your upload notifications on your primary phone, even if you uploaded from your partner's. The notifications are related to your account so the settings will apply to all devices the same way. But you can go to the phone settings -> Notifications and find the Mapillary app on the list, then disable all notifications from it.

In addition to that the notifications are account-, not device-driven, we currently also don't offer the granularity to tune on/off just the upload notifications. Those are grouped together with the blur and edit notifications, i.e. everything related to your activity.

**Comment by HolgerJeromin** [comment]
Good point @katrinhumal 
When i wrote "upload notification" i meant the "23 of 42 images" progress bar while (not after) upload.
I am not sure if the progress bar is shown when i disallowed the app to show notifications in the device settings.

**Comment by katrinhumal** [comment]
@HolgerJeromin Aha! I'm fairly sure you'll still see the progress bar even if you turn off app notifications from device settings. Only one way to find out, though! ;)
