### ISSUE TITLE
Big increase in location accuracy messages

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2692]
The latest Mapillary beta has significant location accuracy issues on the latest Android release for my model phone.  Don't know if the issue is caused by Mapillary or changes in Android. If I launch one of my various GPS status apps, it immediately shows that I have a great GPS lock, usually with 5m accuracy or even 3m.

### Basic information
* Platform: Android 7.0, AT&T baseband version QF3
* Version: Mapillary 3.93-BETA
* System/Browser: Samsung Galaxy S7 Edge

**Comment by heatshear** [comment]
I don't know if this is related, but I used a VIRB Elite camera yesterday to capture images. Usually, it works perfectly, but (using my computer to process them), many of them were placed fairly far from the road (say, 50 - 100m). So, I tried dragging them into place before uploading. Only images that I didn't manually move uploaded successfully. A line connected segments of successful images, skipping over anything I tried moving. A real mess. Tried this in both Chrome and Firefox browsers. Same result. I deleted all my images from the staging area. Now I'm going to just upload them and drag them into the proper place after they are published.

**Comment by jfburke3** [comment]
@heatshear I don't know... I'll have to let the developers chime in on that.

Speaking of the developers... they'll want to know that my phone has updated to patch level QG1 now.

**Comment by jfburke3** [comment]
There is a new function in Android 7.0 on Samsung devices (and I assume other brands, too) that is some sort of power saving tripe.  Apparently it affects other applications, and some of those developers aren't particularly fond of it.  I tried adding Mapillary to the Unmonitored Apps list, but that doesn't seem to have had any effect.

For reference, the function I'm referring to is located here:
Settings->Device Maintenance->Battery, then the App Power Monitor section.

**Comment by gyllen** [comment]
@ovivoda FYI

**Comment by jfburke3** [comment]
I seem to have two issues open on the same problem #2719

**Comment by ovivoda** [comment]
@jfburke3 It has more to do with the accuracy of the location. I've build an experimental build here that works better for users complaining about same issue. Please try it out:

http://android-releases.mapillary.io/Mapillary_Android_v3.102-SNAPSHOT1.apk

**Comment by jfburke3** [comment]
I could've sworn that I added comments to this previously.  I have no idea what happened.

I was never able to get that snapshot apk to install.  No matter how I downloaded it, my phone reported it as corrupt.

Are any of those changes included in any of the recent beta releases?

**Comment by ovivoda** [comment]
@jfburke3 Please try v3.112 which is latest Beta app released on GooglePlay

**Comment by jfburke3** [comment]
@ovivoda I did.  I don't think it has improved the problem.  If anything, I think I have worse problems.  See some of the new Github issues I've opened.

Short version:  personally, I don't recommend releasing 3.112 to the public Play store...  :'(

**Comment by jfburke3** [comment]
@ovivoda I've noticed a dramatic drop in this problem with the 3.113- 3.113-SNAPSHOT2 build you cooked up to help with #2729.

And by "dramatic drop" I mean that I'm hard-pressed to be able to cite a specific instance where I saw it occur. I still need to upload sequences and check them out, but... it's looking good so far.

**Comment by ovivoda** [comment]
@jfburke3 Some more fixes regarding sequence list view UI update:

http://android-releases.mapillary.io/Mapillary_Android_v3.113-SNAPSHOT4.apk

**Comment by jfburke3** [comment]
I installed it yesterday and it seemed to perform well in limited testing. It will get a workout on the open highway today, and hopefully I'll be able to spend some time in a forested area this weekend.

**Comment by jfburke3** [comment]
Oh, fyi, the About info says it's SNAPSHOT2, not 4.

**Comment by ovivoda** [comment]
@jfburke3 I have added some more fixes here: 
`http://android-releases.mapillary.io/Mapillary_Android_v3.113-SNAPSHOT5.apk`

**Comment by jfburke3** [comment]
@ovivoda Installed!  Although, I probably won't be able to do much with it until the weather clears up, hopefully by this weekend.....

FYI, it still says SNAPSHOT2 in the version info.

**Comment by jfburke3** [comment]
I've given it a fairly good workout, and I am not seeing the messages any more with the last snapshot builds you provided, and the beta version in the play store works pretty well, too.  I think you can close this one!

**Comment by gyllen** [comment]
@ovivoda ^^^

**Comment by ovivoda** [comment]
Closing this one.

**Comment by jfburke3** [comment]
I just had to add a comment that whatever you did to fix this, has been rock-solid for the past couple of months.  Currently on 3.119.  Fantastic performance.  A very big thank-you for finding the problem @ovivoda .
