### ISSUE TITLE
Stop blurring fences/gates

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2693]
I see that gates/fences get blurred alot and unnecessarily, I suggest to tune better the algorithm.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for your note - we are constantly working on making it better. On the one hand, our long-term members report that they have noticed improvements over time. On the other hand, we know there's still lots of room for further developments, so we're doing our best. Meanwhile, you can help out by fixing the false blurs with our blur editor if you wish: https://help.mapillary.com/hc/en-us/articles/115001663705-Blurring-images
