### ISSUE TITLE
JOSM: object layer fills the recognited object instead of only marking it

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2694]
The detection works in its way.
But the problem is that the detector full-fills the mapillary pic with the result of the detection, avoiding the possibility of view the real detected object. If the object would be wrong recognized you would'nt be able to see it because you only watch the result of the recognition instead of the real object. You can see it in this screen capture. I have marked right and wrong behaviour. With the orange mark will be enough to mark the sign.

<a href="https://imgur.com/lwico7D"><img src="https://i.imgur.com/lwico7D.png" title="source: imgur.com" /></a>

JOSM 12542
Windows 10

**Comment by gyllen** [comment]
@peterneubauer  Should this be moved to JOSM issues?

**Comment by peterneubauer** [comment]
Yes, this should be moved.

**Comment by gyllen** [comment]
@yopaseopor Would you mind filing an issue here -> https://github.com/JOSM/Mapillary/issues and closing this one?

**Comment by yopaseopor** [comment]
Moved to https://github.com/JOSM/Mapillary/issues/64
