### ISSUE TITLE
Photo rotation request

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2698]
Where I can request manual rotation of some sequences and photos?

**Comment by voschix** [comment]
see [#2142](https://github.com/mapillary/mapillary_issues/issues/2142) opened on 31 Jul 2016 by blobgo
see [#2076](https://github.com/mapillary/mapillary_issues/issues/2076) opened on 23 Jul 2016 by voschix 
see [#811](https://github.com/mapillary/mapillary_issues/issues/811) opened on 13 Mar 2015 by rudolfmayer
and earlier requests ....

**Comment by Alessandro-Barbieri** [comment]
@voschix I'm not requesting the feature but asking where I can post a list of sequence in order to have them rotated by the staff. Is github the right place?

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri So far, requesting these has been a bit ad hoc, actually. But I'm thinking it might be best to start collecting these to a spreadsheet for the time being, which our team will then review regularly and fill the requests gathered there. I will come back to you soon and share the document, which then anyone can use for listing their rotated images.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri, @voschix - can we try how it works via this form? https://goo.gl/forms/fk36ogKZmVvM46VM2

The plan is that we pile up requests every week, then we submit all these requests in one go with some dev help. This scales better than us submitting everything one by one.

**Comment by Alessandro-Barbieri** [comment]
Is this working?

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri collecting the responses is working, but we're just about to start handling the first set of rotations requests submitted via this form.

**Comment by Alessandro-Barbieri** [comment]
I have requested two times the rotation of the same sequence (but I want to rotate only once), how is this handled?
I know this because I'm keeping track of the sequences that are waiting rotation and I found a double entry in my file.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri I'm not completely sure how it would be handled if you submit two at the same time (a bot runs over the form responses every once in a while so the edits get created simultaneously) but right now I think I managed to find and delete your double entry. In either case, if this happens please check back about 24 h after submitting and see how it looks. If the sequence has still (or again, or another) wrong orientation, let us know.

**Comment by katrinhumal** [comment]
@nereocystis You're right, sudden shocks confuse the sensors and are most likely the cause of some of your images ending up rotated in otherwise correct sequences. You should send me the image keys (luckily, you can copy these straight from the URL as well, if you think the image options (...) menu takes too long) together with how many degrees clockwise they should be rotated.

**Comment by nereocystis** [comment]
In my sequences, there are a lot of images upside down. I'll try to put together a script to print a list

**Comment by nereocystis** [comment]
I have been looking at my original uploaded files in sequences which have occasional flipped images.

On some sequences, I can look at the exif data for the original files and see Orientation.

In other sequences, the Orientation in exif is missing.

This sequences does not have Orientation:
O5mLROrZMXFfav_mHPbzuw

This sequence does have Orientation
uGU82Y9c7M5DImpbHBQEkw
with some images flipped:

Here's output from my rotation checking python script:
kevin@awabi:~/src/mapillary_tools/python$ ./check_rotated.py uGU82Y9c7M5DImpbHBQEkw kevin@kelphead.org --password xxxx
Result: 279 images in sequence.
First image orientation:  Horizontal (normal)
yfgH5Yqt9LaVsuJ_HKhXbQ  mismatch: current:  Rotated 180  does not match first:  Horizontal (normal)
-QQ71tFl4lXuQNQhEOqN-A  mismatch: current:  Rotated 180  does not match first:  Horizontal (normal)
LOoQaVHjb9IyFd4viK6now  mismatch: current:  Rotated 180  does not match first:  Horizontal (normal)
3  images have different orientation than first image
