### ISSUE TITLE
Blur review interface

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2699]
I want to review blurs an all my photos but a proper way of doing is missing: what I request is a page named like "my blurs" in wich are listed all my photos with blurs that I haven't reviewed.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for the request! Let me check if I have understood you correctly. What you'd like to have is a way to keep track of which images you have already checked for blur fixing, and which are yet to be done?

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal 

> What you'd like to have is a way to keep track of which images you have already checked for blur fixing, and which are yet to be done?

Yes, this will be great

**Comment by katrinhumal** [comment]
Thanks for clarifying! We've heard that from some other people as well so the idea is under consideration. Thanks for your input! I'm adding it to the pool and closing this issue since no immediate fix.
