### ISSUE TITLE
remember "use compass" option

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2700]
### Basic information
* Platform: `Android`
* Version: `3.89`

### Steps to reproduce behavior

 1. turn on "use device compass"
 2. capture a sequence as usual
 3. exit the app
 4. reopen the app

### Expected behavior

the option remembered

### Actual behavior

I have to re-enable the option every time I start the app

**Comment by kaitu** [comment]
#2570

**Comment by katrinhumal** [comment]
Thanks @Alessandro-Barbieri for reporting and @kaitu for linking to the other issue. I'm closing here as a duplicate, and resurfacing the other issue to our team.
