### ISSUE TITLE
Website on firefox for android is too cluttered

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2702]
### Basic information
* Platform: `Android` | `Web`
* System/Browser: `firefox for android`

### Steps to reproduce behavior

 1. Go to mapillary.com/map
 2. Optionalli tap on and image

### Actual behavior

Stuff is overlapped 

### Additional information

See top and bottom right
![screenshot](https://imgur.com/gallery/ozLfF)

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for raising this. As is evident from your experience, the web app has not been optimised for mobile. We suggest using the native app instead, and handling the more advanced actions from your computer. However, I totally see your point related to https://github.com/mapillary/mapillary_issues/issues/2696 - some things you'd just like to do on the fly. I can't promise an instant fix but we'll definitely try to work out some sort of a balanced solution here. I'm closing here and taking your feedback for internal discussion.

P.S. Thanks for sharing lots of feedback recently! It's very helpful in deciding where we should put our limited resources to.
