### ISSUE TITLE
 Android version 3.93 BetaApp bugs

### ISSUE THREAD

**Issue by FilipeGraciosa** [mapillary/mapillary_issues#2703]
I would like to know, if I'm the only one with this 4 problems (driving with automatic capture mode):

**A** - Recurrently the app freezes, stops showing live camera, doesn't respond to touch and stops taking pictures for some minutes, then it returns to work automatically (we lose several kilometers of mapping, due to this bug)

**B** - Several times stops working and shows this message "**The location recording has not yet started**"

**C** - Some times it also stops and shows messages like this "**Starting new sequence, 190.17945354494867m gap detected**"

**D** - Some times when I'm stopped in a red light, the camera keeps on taking pics, even when I'm stopped. Once I counted that it took 10 pics, when I was waiting to move.

PS: I use a Huawei P8

**Comment by voschix** [comment]
I keep seeing (A) frequently on on different versions of the Android App, including 393, on Sony Xperia Z5 compact. It seems to be more frequent when the phone gets hot.
I don't remember to have seen either of (B) and (C). 
No comment on (D) as I normally use time-based picture taking.

**Comment by echeloni2p** [comment]
Hmm, A could be the system being on load doing some jobs until mapillary is able to take new pic. New APIv2 or ald API ? COuld be correlate with temp and CPU of mobile throttles and less power to do the job.
B is strange, but location recording not started, so stop track, close app, remove from memory and start again, solves lots of my issues. Maybe a complete wipe of the mobile and reinstall of system may help to get a defragmented storage. But I did a lot of pictures already (>250k) and no issues with that on itnernal storage. 
Do you use a memory card? This could exlain a and b, as it is slow to write in some circumstances and blocks the picture taking and saving of gps track.
C is basic whole/jumping of GPS position and starting of new track.
D I do see sometimes, too. And I cannot stop with the stop button, only killing the app helps.

echelon

**Comment by katrinhumal** [comment]
Thanks for reporting! @FilipeGraciosa and @echeloni2p, can I ask if you have by any chance the "Skip location check" option turned on in Settings > Developer?

**Comment by FilipeGraciosa** [comment]
I have turned off as it came as default, should I turn it on?

**Comment by katrinhumal** [comment]
@FilipeGraciosa No, it's good that it's off. There are only a handful of cases when you'd need to turn this on, but sometimes people turn it on anyway and we've noticed it can cause problems.

**Comment by damjang** [comment]
@FilipeGraciosa for A and B I think that is the speed of writing to memory (do you have sd card?); for C the same + gps fix problem; for D if you have set the time base capture is ok, if you have set the distance capture this is a bug I already reported (appear on some older and all newer versions) that distance capture method don't work and instead is used time-capture mode - try it changing time-capture interval!

@echeloni2p 
> D I do see sometimes, too. And I cannot stop with the stop button, only killing the app helps.

I have found this bug when gps signal is lost (e.g. in a tunnel) and when gps return Mapillary don't see again the gps and think that no gps fix - I can recover from that state using the back button.

**Comment by ovivoda** [comment]
This issues have been fixed in the latest application versions
