### ISSUE TITLE
Sequence lost ?

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2705]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Checking old mapillary stuff

### Expected behavior

see my coverage of the area
https://www.mapillary.com/app/?lat=54.26374000000001&lng=11.078238999999996&z=17&username%5B%5D=chuck&mapStyle=mapbox_streets&focus=map&pKey=y6ii35oKkA5o9tY7w8GzMg

### Actual behavior

no mapping showed, only short area

### Additional information

can you please check, i thought i captured a bigger area around Year 2014

**Comment by gyllen** [comment]
@thoschu96 Looks like the sequence is on the map now, can you confirm or are you missing a longer drive?

**Comment by thoschu96** [comment]
hi

i miss a longer sequence
it strating at same point but to the other direction

Am 08.09.2017 um 00:52 schrieb Johan Gyllenspetz <notifications@github.com<mailto:notifications@github.com>>:


@thoschu96<https://github.com/thoschu96> Looks like the sequence is on the map now, can you confirm or are you missing a longer drive?

-

**Comment by gyllen** [comment]
@peterneubauer Mysterious sequence ^^

**Comment by peterneubauer** [comment]
We are still having some dirty data after the massive hurricane import, let's get that settled and then see if that sequence is still missing.

**Comment by peterneubauer** [comment]
This should be the other sequence right? Closing for now. https://www.mapillary.com/app/?lat=54.26325&lng=11.078998&z=17&username%5B%5D=chuck&mapStyle=mapbox_streets&focus=map&pKey=cPuHiMaIOPJEz_E4y_AYVQ
