### ISSUE TITLE
App stops taking pictures and screen freezes

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2706]
### Basic information
* Platform:  `Android 7.1` on 'Sony Xperia Z5 compact'
* App Version: `several, up to 393` 

### Steps to reproduce behavior

 1. Start photo taking in time capture mode (I have seen the effect with 2sec, 3sec, or 5 sec and "ignore location" on and off)

### Expected behavior

Picture taking runs until I stop it by pushing the square red button

### Actual behavior
Picture taking stops autonomously after anything from a couple to hundreds of pictures.

### Additional information
When picture taking stops in this way, the screen freezes. The control dot is square, i.e. the app "thinks" it is still running. Sometimes it restarted after several minutes without any external intervention. I normally do not want to wait three or five minutes, and stop and restart the Mapillary App manually. In this way the app starts without delay.

I am aware of, and may have experienced, other ways of the app stopping, as reported in #2449, #2511

...

**Comment by hlinden** [comment]
I am affected by this problem as well. The last 10 to 20 images before this happens are either blank or only have content in the upper areas and a black area at the bottom. 
[mapillary_freeze_crash.log.txt](https://github.com/mapillary/mapillary_issues/files/1291641/mapillary_freeze_crash.log.txt)

I have saved and attached a debug log from one of these instances - username is changed, of course:

**Comment by hlinden** [comment]
I just had trouble again, only this time the app didn't freeze while some pictures still were saved incompletely. Log and screenshot:

[mapillary_incomplete_images.log.txt](https://github.com/mapillary/mapillary_issues/files/1292141/mapillary_incomplete_images.log.txt)

![screenshot_20170911-115404](https://user-images.githubusercontent.com/4718458/30269471-3446042c-96e9-11e7-8e46-381a94aa7dda.png)

**Comment by katrinhumal** [comment]
@ovivoda The last thing seems like https://github.com/mapillary/mapillary_issues/issues/2598 and possibly https://github.com/mapillary/mapillary_issues/issues/2577.

**Comment by jfburke3** [comment]
I've had something similar happen, too.  I can try to provide trace logs if you want, since it seems to happen with a disconcerting regularity.

**Comment by mxa** [comment]
Useful information is: how hot was it on this day around the telephone? See https://forum.mapillary.com/t/device-temperature-battery-level/1205

**Comment by jfburke3** [comment]
I'm aware of the temperature issues. I usually have my air conditioner running and blowing through the defroster vent, which blows the cold air over my phone.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
