### ISSUE TITLE
webuploader misleading messages while retrying upload of failed files

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2707]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `Windows 7 / Firefox 55.0.3`

### Steps to reproduce behavior

 1. open web uploader, upload some files
 2.  repeat until for some reason at the end of the process a windows opens, telling that x files failed to upload
 3. press the "retry x failed" button

### Expected behavior
The uploader tries to upload all of the x failed files. If some files fail again to upload, only at the end of the process a windows opens telling that y files failed to upload (y<=x)

### Actual behavior
After the first file is uploaded, a message instantly appears telling that x-1 files failed to upload, and offering a button to retry x-1 failed.

Without user interaction, the upload continues, showing the same message with a decreasing number of failed files.

Pressing the "retry x-n failed" button during the process results in duplicated uploads (at least the count of the images that is reported as uploaded is larger than it should be. I pressed the button several time after the first successfull upload was reported, and I think that for each time lastly an additional file appeared in the count of uploaded files)

### Additional information
![8](https://user-images.githubusercontent.com/5104672/30211302-b92a21e6-94a0-11e7-871a-6e5555d37094.jpg)
![9](https://user-images.githubusercontent.com/5104672/30211312-c273b988-94a0-11e7-8284-18f200422d32.jpg)
[...]
![11](https://user-images.githubusercontent.com/5104672/30211315-c90c78d4-94a0-11e7-96e6-53f2a43a1c87.jpg)
[...]
![25](https://user-images.githubusercontent.com/5104672/30211322-cf7a0060-94a0-11e7-87f3-30ec20eb811c.jpg)

The submitted sequence consisted of only 328 images. I restarted the upload of failed files several times due to the misleading messages. Don't know for sure how it resulted in 334 images being uploaded.

**Comment by cookry** [comment]
Hi @kaitu I sent you a file request via Dropbox. I'll help here and investigate.

**Comment by kaitu** [comment]
I sent you an image. I don't know why some files failed to upload at first try (probably it's nothing related to mapilllary) nor how to reproduce the issue. Probably some connection glitches.
The point is that I find weird and misleading that a message with a button "Retry xx Failed" appears while the upload process of those remaining xx files is still ongoing.

**Comment by cookry** [comment]
@kaitu can you share a sequence of photos?

**Comment by kaitu** [comment]
The sequence key is: xkbzqNs3dx7usbeisdHDOQ

The sequence actually counts 328 images. My feed says it counts 394 images (I still have 178 pending images, so the number could still rise).

**Comment by katrinhumal** [comment]
@gyllen Could we improve the way UI messages are displayed here?

**Comment by nickplesha** [comment]
@kaitu We've made some improvements to the uploader so this issue should be resolved. Let us know if you encounter any problems with uploading again.
