### ISSUE TITLE
webupload not working

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2708]
### Basic information
* Platform: | `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. uploading pictures via web
 2.
 3.

### Expected behavior

after successfully upload i would expect that the counter of pending photos would rise

### Actual behavior

after upload no new photos shown up to be processed

### Additional information

...

**Comment by katrinhumal** [comment]
Hi @thoschu96 - thanks for reporting. We just have a little lag in the system right now and that's why you don't see your images in your profile (not even in the pending count). Or maybe you do by now. :) In any case, you should see them soon.

**Comment by thoschu96** [comment]
yes
you are right
took a while
hope it get fixed soon
as the error is still there

Am 13.09.2017 um 17:53 schrieb katrinhumal <notifications@github.com<mailto:notifications@github.com>>:


Hi @thoschu96<https://github.com/thoschu96> - thanks for reporting. We just have a little lag in the system right now and that's why you don't see your images in your profile (not even in the pending count). Or maybe you do by now. :) In any case, you should see them soon.

-

**Comment by katrinhumal** [comment]
Thanks for your patience @thoschu96! It will still take some time - namely, we're [importing a huge set of imagery](http://blog.mapillary.com/update/2017/09/14/microsoft-imagery-for-disaster-recovery.html) in the hurricane-affected areas in the US to help with disaster recovery response. That's what's making the queue longer.

**Comment by katrinhumal** [comment]
This should not be an issue anymore.
