### ISSUE TITLE
Disable limit for 'Filter leaderboard for image uploads' in Ukraine (UA)

### ISSUE THREAD

**Issue by spatialhast** [mapillary/mapillary_issues#2709]
### Basic information
* Platform: `Web`
* Version: `API v3` 
* System/Browser: `Google Chrome 60.0.3112.113`

### Steps to reproduce behavior

 1. Call 'Filter leaderboard for image uploads' for Ukraine from 2017-01-01 in browser using URL:
https://a.mapillary.com/v3/leaderboard/images?iso_countries=UA&start_time=2017-01-01&client_id=<CLIENT_ID>

### Expected behavior

I want receive all users list in Ukraine from 2017-01-01 (or 2016-01-01) to current date

### Actual behavior

The response is return only first 20 'users'

### Additional information

https://github.com/mapillary/mapillary_issues/issues/2503

**Comment by echeloni2p** [comment]
Hi!

Ask mapillary for the business plan, they will tell you how much you have to pay and you get unlimited access.

**Comment by spatialhast** [comment]
solved using pagination (https://www.mapillary.com/developer/api-documentation/#pagination):

>  //a.mapillary.com/v3/leaderboard/images?**per_page=1000**&iso_countries=UA&start_time=2015-01-01&client_id=<CLIENT_ID>

thanks @ptpt
