### ISSUE TITLE
Stops taking pictures

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#271]
So I started to take pictures in Ride mode from my car. Nice, but for me there is a huge problem. The Mapillary app just stops taking pictures all the time. The iPhone has a very hard time to get a GPS position, even when the buildings are low or none are there.

The app should keep taking pictures, not stop. There will never be a map filled with nice sequences if the app stops taking pictures 20 times during an hour. A solution would be that the pictures without GPS data aren't shown until the user has placed them.

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by millenbop** [comment]
@jesolem: yes, we stop taking pictures when the GPS is bad (i.e. red).

**Comment by HolgerJeromin** [comment]
Do you mean stop or pause?

**Comment by millenbop** [comment]
sorry, I meant pauses

**Comment by millenbop** [comment]
We have raised the threshold for acceptable GPS precision so it should be much better now. This is also an old discussion, so closing this one.
