### ISSUE TITLE
Disable limit for 'Search sequences'

### ISSUE THREAD

**Issue by spatialhast** [mapillary/mapillary_issues#2710]
### Basic information
* Platform: `Web`
* Version: `API v3` 
* System/Browser: `Google Chrome 60.0.3112.113`

### Steps to reproduce behavior

 1. Call 'Search sequences' for 'Y9YiPRZlQ_wP85S7h1YWFQ' userkeys from 2016-01-01 in browser using URL:
https://a.mapillary.com/v3/sequences?bbox=21.93,43.98,40.43,52.47&userkeys=Y9YiPRZlQ_wP85S7h1YWFQ&start_time=2016-01-01&client_id=<CLIENT_ID>

### Expected behavior

I want receive ALL sequences list from 2016-01-01 to current date

### Actual behavior

The response return only first 200 sequences

**Comment by echeloni2p** [comment]
Ask mapillary for the business plan, they will tell you how much you have to pay and you get unlimited access.

**Comment by spatialhast** [comment]
solved using pagination (https://www.mapillary.com/developer/api-documentation/#pagination), thanks @ptpt
