### ISSUE TITLE
Before we can start...

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2712]
on the website, i've been greeted by the "Before we can start..." popup at least 4 times.
seems to be a bit excessive to ask that every time :)

**Comment by echeloni2p** [comment]
Not for me on chromium

**Comment by richlv** [comment]
forgot to mention browser - firefox 55.0.3

**Comment by katrinhumal** [comment]
@richlv Thanks for reporting! Have you been choosing a reply or skipping?

**Comment by richlv** [comment]
ah, sorry for omitting that much crucial detail :)
i choose an option and hit "submit" each time.

**Comment by katrinhumal** [comment]
Thanks! Well, even if you skip, we shouldn't prompt you every time... unlikely that you'll change your mind about the reply in a day. :) Pulling in @gyllen to check in on this.

**Comment by nickplesha** [comment]
@richlv Thanks for reporting! Sorry for the popups bothering you, should be fixed now. Let me know if it works for you.

**Comment by richlv** [comment]
yay, thank you for the quick fix.
there was some issue with javascript initially, had to force-refresh. now all is good.
