### ISSUE TITLE
Picture from the future

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2715]
### Basic information
* Platform: `Android` | `Web`
* Version: `up-to-date` 
* System/Browser: `not relevant`

### Steps to reproduce behavior
I suppose this to be not reproducible

### Expected behavior
Uploads appear in the profile with a date in the past

### Actual behavior
One of my recent uploads bears a date far in the future

### Additional information
This is a single picture upload that has been inserted automatically (?) by your upload mechanisms some weeks after the bulk of the sequence. 
In addition to having the strange upload date it has not been inserted in the correct position in the main sequence.
Main sequence # p8tl1704tl9odm40bc7zcd
Rogue single-image sequence # llgpv09z1eu8trwi3puhog

![mapillary rogue upload date -1](https://user-images.githubusercontent.com/11076112/30774689-f41da52e-a086-11e7-8949-76a20d88e3af.jpg)
![mapillary rogue upload date -2](https://user-images.githubusercontent.com/11076112/30774692-f9ef3a3a-a086-11e7-8d5f-fdc85133ad40.jpg)

**Comment by gyllen** [comment]
@peterneubauer @ovivoda Seems Android related

**Comment by peterneubauer** [comment]
This is fixed now, the images are correct. https://www.mapillary.com/app/?pKey=yWn3HOBVdCIyZJvhb_NCHg&lat=46.65678500000001&lng=10.19416666666666&z=17
