### ISSUE TITLE
How to get link to photo page?

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary_issues#2716]
@eugenefedoto commented on [Sat Sep 23 2017](https://github.com/mapillary/mapillary-js/issues/263)

https://www.mapillary.com/developer/api-documentation/#retrieve-image-sources

> Attribution should include a clearly visible link to mapillary.com or to the Mapillary photo page directly.

Is there an API to get the link that I'm not noticing?

---

@Abbe98 commented on [Sun Sep 24 2017](https://github.com/mapillary/mapillary-js/issues/263#issuecomment-331727620)

Append the image key to the following URL:
`https://www.mapillary.com/app/?focus=photo&pKey=`

Example:
`https://www.mapillary.com/app/?focus=photo&pKey=wbqWRpw1nbCQh5Hu62zoJA`

**Comment by katrinhumal** [comment]
@eugenefedoto Thanks for your question! And thanks @Abbe98 for the reply. Another way to get the image link is to use the share button at the right-hand side on the Mapillary web when viewing the image. You can copy the URL there with one click.

<img width="1280" alt="screenshot 2017-09-25 13 02 07" src="https://user-images.githubusercontent.com/16334352/30805453-c634c324-a1f1-11e7-937f-503c40a2de2b.png">
