### ISSUE TITLE
Enable sharing of PhotoSpheres from gallery to Mapillary app on Android.

### ISSUE THREAD

**Issue by hlinden** [mapillary/mapillary_issues#2717]
Currently the only way to upload PhotoSphere imagery seems to be:

- take the picture
- go home
- transfer the image to the PC
- upload it using the webinterface

It would be quite a bit easier, if I could just share the picture to the Mapillary app from the gallery.

**Comment by katrinhumal** [comment]
Hi @hlinden - what about if you try moving this image to the Mapillary folder (make sure that it has a geotag)? You can try and see if it then shows up on the upload screen in the Mapillary app (it probably should). You can see which folder is assigned for Mapillary images in Settings > Storage.
