### ISSUE TITLE
regression: new sequence does not start automatically after 601 pictures

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#2718]
### Basic information
* Platform: `Android` 
* Version: `396` 

### Steps to reproduce behavior

 1. set up the app to shoot distance based, eg. 5m, pointing forward
 2. start capture and start driving
 3. wait for capture 601 to occur

### Expected behavior
A new sequence should start automatically after 600 pictures

### Actual behavior
Capture halts at end of sequence/601 pictures. Manual intervention is required to start a new sequence

**Comment by jfburke3** [comment]
I'm pretty sure that it started a new sequence automatically for me, but I'll watch for this.

What phone/model do you have, and Android version?

**Comment by mprins** [comment]
Asus k007, Android 5.0.1 and I have set both battery and storage limits to 0
This worked fine in previous versions, but failed several times last week after I just quit

**Comment by echeloni2p** [comment]
Hi

On my One+ 3T with Android 7.1.1 it did not start a new sequence. On my Huawei Honor 7 with Android 6 it did start a new sequence after 600 pictures.
echelon

**Comment by mprins** [comment]
I may have time over the weekend to give this another try

**Comment by ovivoda** [comment]
@mprins If you have time to try it please install the latest beta app from googlePlay or from here: http://android-releases.mapillary.io/Mapillary_Android_v3.101-BETA.apk 
and send me back the logs if the phone stops capturing after first sequence. Thanks!

**Comment by Eric-FR** [comment]
I'm facing the same issue:
Device : Symphony i10 device.
Android : 6.0
Mapillary: up to date (3.95 now).

I discovered it on September 17th. I still observed it last week-end (September 24th).

When a sequence it having 601 pictures, it is switching to a new sequence but only one picture is recorded in the new sequence. Although in acquisition mode, no capture is done. I have to stop and restart capture. Back home, I observed that the corresponding sequences contained 602 pictures.

Distance based capture : 5 m.
Photo min delay : 1 s.

**Comment by mprins** [comment]
I was able to reproduce this on the way to work, after 601 no more pictures were taken, had to manually stop and start to continue.
logs are in the mail.

**Comment by mprins** [comment]
FIW the sequence numbers are:
- DzcH2tpKGoMp9boo5J8noQ
- rfxOhKDKYy7ZRfKzFx8wEA

**Comment by Eric-FR** [comment]
echelon,

what are your acquisition parameters?

**Comment by echeloni2p** [comment]
Hi

I do use time based capture, 1 sec, high res pictures, ignore location check, animation on shutter, focus mode legacy cam 0 continuous, sequence break 100m, 10% battery limit, no google mobile provider, show detailed stats.
On both devices

echelon

**Comment by Eric-FR** [comment]
I checked today after update to 3.103: the problem is still present.

**Comment by mprins** [comment]
yes, still present in 3.103. I've sent in the logs

**Comment by ovivoda** [comment]
@mprins Thanks for reporting this. Will fix and let you know once I have a new APK

**Comment by mprins** [comment]
Sent some more logs, also occurs with 3.104

**Comment by ovivoda** [comment]
@mprins Thanks for the logs. Will look into it.

**Comment by Eric-FR** [comment]
Bug still present with 3.107 tested yesterday.

**Comment by Eric-FR** [comment]
Bug still present with 3.108. Is there something that I can do to help solving this bug?
Are all contributors concerned or just an unlucky fraction?
I'm planning a long trip next Wednesday with large uncovered parts and this bug will be a serious drawback.

**Comment by ovivoda** [comment]
@mprins @Eric-FR Please try the version here:

http://android-releases.mapillary.io/Mapillary_Android_v3.112-BETA.apk

**Comment by Eric-FR** [comment]
Installed this morning. Issue still not solved.

**Comment by mprins** [comment]
I may have time to do this next wednesday, would be nice if it stopped raining by then and have some daylight.

**Comment by Eric-FR** [comment]
For the test, I used Time based capture : 1s.
I'm not doing trips long enough on a daily basis to check the bug using Distance based capture but I will try as soon as possible.

**Comment by ovivoda** [comment]
@Eric-FR I tested this once again yesterday and I still cannot reproduce. Will you please send me screen-shots of all your settings? Want to have the same setup as you have, even though it is on emulator.

**Comment by Eric-FR** [comment]
![screenshot_20171129-110652](https://user-images.githubusercontent.com/32433543/33398405-21161fb4-d54f-11e7-82be-0a679e188c75.png)
![screenshot_20171129-110708](https://user-images.githubusercontent.com/32433543/33398406-2144f636-d54f-11e7-8812-55cc40c3583e.png)
![screenshot_20171129-110725](https://user-images.githubusercontent.com/32433543/33398407-2186aa68-d54f-11e7-83d9-0c22d32f2106.png)
![screenshot_20171129-110737](https://user-images.githubusercontent.com/32433543/33398409-21b36792-d54f-11e7-8427-63082e060fb8.png)
![screenshot_20171129-110747](https://user-images.githubusercontent.com/32433543/33398411-21da965a-d54f-11e7-9c76-0717059d2198.png)
![screenshot_20171129-110757](https://user-images.githubusercontent.com/32433543/33398412-2224b8ac-d54f-11e7-8e9d-c24052832fc0.png)
![screenshot_20171129-110808](https://user-images.githubusercontent.com/32433543/33398413-224ca682-d54f-11e7-9a8f-e2e158ab3813.png)
![screenshot_20171129-110817](https://user-images.githubusercontent.com/32433543/33398414-2274db48-d54f-11e7-9cff-c9a26e58d252.png)
![screenshot_20171129-110825](https://user-images.githubusercontent.com/32433543/33398415-2296c76c-d54f-11e7-9e5b-cbf85a46a07b.png)

**Comment by mprins** [comment]
Still not fixed in the beta, sent logs and screenshots to logs@

**Comment by HolgerJeromin** [comment]
Worked here with 3.112 today
5 m distance on fairphone 2

**Comment by Eric-FR** [comment]
I made a try today with the new version (3.116), using time based capture. When arriving at 601 pictures in the sequence, after a first message inside Mapillary, I get "Unfortunately, Mapillary has stopped".

**Comment by ovivoda** [comment]
@Eric-FR will check it out and get back to you. I saw the crash here. Trying to figure it out. Still could not reproduce it on my end.

**Comment by Eric-FR** [comment]
New version 3.117: no crash but an error message when arriving at 601 pictures and trying to start the new sequence: _No location, please make sure GPS is available_.

![screenshot_20171221-171206](https://user-images.githubusercontent.com/32433543/34277227-227cfd70-e6a5-11e7-9af8-0be59c940701.png)

**Comment by jfburke3** [comment]
@Eric-FR I get that message frequently at the beginning of a sequence, even ones that I manually start.  However, the message goes away and the app *does* begin shooting images afterwards, so I've never bothered to report it as it doesn't interfere with my ability to use the app.

**Comment by ovivoda** [comment]
@Eric-FR Will work on fixing the message. The capture of a new sequence works?

**Comment by Eric-FR** [comment]
@ovivoda No, the new sequence still not works.
@jfburke3 I will check again if this message is just a coincidence or not, but, for sure, even by waiting, the new sequence is stuck on the first picture, even with correct GPS signal, as on the screen-shot.

**Comment by Eric-FR** [comment]
It's a great pleasure to announce to you that everything is working back again. I performed a static test (time based: 1 s) over 2000 pictures and I got 4 sequences with automatic start of the new sequence when arriving at 601 pictures in the previous one.

**Comment by ovivoda** [comment]
@Eric-FR Thanks for the feedback. So this is still a problem when you drive but works with "ignore location" setting set to ON?

**Comment by Eric-FR** [comment]
I will check latter while driving but "Skip location check" was already disabled.

**Comment by Eric-FR** [comment]
I made several field tests with "distance based" capture 5 s and minimum delay 1 s. I can confirm that switch to new sequences after 600 pictures is running well. 

So, for me, issue is solved.

**Comment by ovivoda** [comment]
@Eric-FR Thanks for the feedback!
@mprins Working good on your side as well?

**Comment by mprins** [comment]
Ran some sequences this weekend, thus are back working
