### ISSUE TITLE
crop photo in web

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2721]
### Basic information
* Platform: `Web`
* System/Browser: `all`

### Expected behavior

It would be super nice to have the ability to crop images from web
eg.: for removing black zones of corrupted photos and car interiors/fingers on the camera

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for the suggestion! I'm taking this to the team to consider for the next version of the web tools. Closing the issue here since there won't be an instant fix.
