### ISSUE TITLE
Image connected to sequence although not part of sequence

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2722]
In order to fix bugs from old uploads (sequences where some images were not in the right order and therefore drawing long green lines over the map), I removed the image causing the issue from the sequence and re-uploaded it (i.e. I downloaded the original unprocessed image and then uploaded it as a new sequence).

For most sequences this appears to have fixed the issue, however for some ones there seems to be a new issue where a

e.g. this one:
https://www.mapillary.com/app/user/umap?lat=48.13148956812475&lng=11.69249616210297&z=20&pKey=ABXqpqMYXWBkgIr7zLP8ng
This image is not connected to the sequence (there are no arrows you can click on. But still, a long green line is drawn from and to this image (as if it were in the sequence it originally belonged to).

One of the images apparently connected to the link above is
https://www.mapillary.com/app/user/umap?lat=48.128316592015295&lng=11.710647143334086&z=19.08155751793806&pKey=BQVxv0_pvHFMtHRuXMASaA
If you click on the "next" (right) arrow at this image, you'll get to aforementioned image which is not in the same sequence.

Therefore, I assume by removing and immediately re-uploading the image, there is some internal error in the mapillary system so the image (original file is identical) is not properly removed from the sequence.

Please note that in any case, this specific issue should be auto-fixed by sequence_cut (the long green line is multiple kilometers long), but this appears not to be the case here.

**Comment by ulikoehler** [comment]
Here's another example:
"Stray" picture:
https://www.mapillary.com/app/user/umap?lat=48.12376006516794&lng=11.703690094975173&z=16.970041410736776&pKey=J1d7SYvllbLoqvCDailAoQ&feedItem=user-pyQrwn2chXv57on5L40ZbA-activity-user-pyQrwn2chXv57on5L40ZbA-publishing_done-image%3A1507179302284

Last regular img in sequence:
https://www.mapillary.com/app/user/umap?lat=48.12203860198292&lng=11.698402549852858&z=17&pKey=jnxi4-gwnsVQyktpH9nVTw&feedItem=user-pyQrwn2chXv57on5L40ZbA-activity-user-pyQrwn2chXv57on5L40ZbA-publishing_done-image%3A1507179302284

**Comment by katrinhumal** [comment]
@ulikoehler Thanks for reporting! We'll investigate.

**Comment by gyllen** [comment]
Closing since image now seems to be removed
