### ISSUE TITLE
Italian motor cycle number plates are frequently missed by pixellation algorithm

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2723]
### Basic information
* Platform:  `Web`
* Version: `current` 
* System/Browser: `NA`

### Steps to reproduce behavior

 1. Take photos of motor cycles with current type of motor cycle number plate in Italy

 2. Upload photos

 3. Check for pixellation

### Expected behavior

The current type of motor cycle number plates are pixellated with high probability

### Actual behavior

The false negative rate (misses) is very high

### Additional information
https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Italy#Motorcycle_plates

**Comment by katrinhumal** [comment]
@voschix Thanks for reporting! Improving this is ongoing work by @ybkuang and team. We'll note this down as one specific area of improvement but you won't see results overnight, I'm afraid. In time, though! Closing the issue here since there's no instant fix.

**Comment by voschix** [comment]
I am not expecting overnight improvement, by all means.
But, if you move things from the GitHub issues they become invisible to the
end user, I suppose. And that end user then may report the same item again
(which I believe has happened with this specific item). It would be nice if
the end user/contributor had a way of checking that an item is already in
your long-term list, thus avoiding double reporting.

**Comment by katrinhumal** [comment]
@voschix That's a good point. We're trying to find some balance between using GH open issues as indicators of the more immediate task at hand (particularly bug reports), and for using them as discussion threads for feature requests where anyone could pitch in.

Ideally, before creating a new issue, one would do a search and check both open and closed issues, and hopefully, find the ones that already exist on the same topic. But I know this doesn't always work out that well in reality.
