### ISSUE TITLE
Upload photos using API V3 and OAuth token

### ISSUE THREAD

**Issue by abanctelchevrel** [mapillary/mapillary_issues#2724]
I'm trying to upload images to Mapillary using an OAuth token but I don't find relevant documentation for this use case.

Among your [OAuth "scopes"](
https://github.com/mapillary/mapillary_apidoc/blob/master/source/includes/_oauth.md) there is a 'public:upload' which make me think that it must be possible, but unfortunately, the [API V3 doc](https://a.mapillary.com/) doesn't mention any way of uploading photos.

This [page](https://gist.github.com/peterneubauer/288633b8ae0358fa53ae) mentions how to upload files from a python script but it relies on the user providing its password, which is not what I wanted.

Do you know if it's possible and if so provide a working example?

Thx!

**Comment by gyllen** [comment]
Closing since this is _not_ yet a documented feature

Using `mapillary_tools` is currently the best bet
