### ISSUE TITLE
Dismiss banner

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2726]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox for android`

### Steps to reproduce behavior

 1. Open website with mobile

### Expected behavior

Can dismiss "open in app" banner

### Actual behavior

"Open in app" banner is very annoying

**Comment by katrinhumal** [comment]
Thanks for pointing this out. The web app is not optimised for mobile, which is why we're quite persistent with the banner. However, I agree that we should probably give you the chance to close that and continue the non-optimised journey if you so wish.

**Comment by gyllen** [comment]
@nickplesha Lets add option to dismiss banner

**Comment by nickplesha** [comment]
@Alessandro-Barbieri This is fixed now, thanks for reporting!
