### ISSUE TITLE
Screen sometimes "stutters" when shooting sequences

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2728]
### Basic information
* Platform: Android 7.0, AT&T build QH1
* Version: Mapillary 3.104 (and several previous releases)
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Begin shooting sequences while driving. 
 2.  Look at the phone screen periodically. 

### Expected behavior

The screen image flows as smoothly as the landscape around me as the app takes pictures.

### Actual behavior

Sometimes the screen image flows smoothly, but much of the time it "stutters" as if briefly freezing the image it just took (I don't know if the image on screen is actually the one being saved, that's just the best way I can describe it).

### Additional information

My impression is that this started about the same time as #2719.  My techie-but-not-a-developer impression is that the app is trying to do too many things in the background while image-taking and other processes are being delayed as a result.

Samsung Galaxy S7 & S7 Edge both support Camera2 API, and i have that enabled in the developer settings. Happens in both distance and timed mode. I've also tried increasing the delay between pics to 0.5s but that didn't help. 

I think the sane thing happens on my Samsung Galaxy S5 (Android 6.0.1, Camera1 API, not Camera2).  I can try to verify that, and can also try on my old Galaxy S4 if you want a comparison. 

I can also shoot a video of the phone screen if you want to see it. 

I also wonder if it could be related to #2706.

**Comment by Eric-FR** [comment]
It may be related to thermal throttling.

I observed this behaviour in August while using a car without air conditioning in warm and sunny places. After tens of minutes, the application became sluggish.  The smartphone was very hot. You have to be carefully when handling it.

Wiko P4200AN
Android 6
Mapillary up-to-date.

**Comment by jfburke3** [comment]
I typically keep my car air conditioner ON, with the front windshield defogger selected, in order to keep cold air flowing over the phone. When I touch it, my phone doesn't usually feel very warm, much less hot.

**Comment by Eric-FR** [comment]
So overheating and thermal throttling may not be issue, just CPU overload in normal conditions.

**Comment by jfburke3** [comment]
@Eric-FR Yes, with the comment that this started somewhat recently (i.e., the app _used to_ show a smoothly flowing image on-screen), so my impression is that the CPU overload you refer to is being caused by Mapillary.  And I'm wondering if the CPU overload is also what's causing the GPS accuracy problems (#2719).

**Comment by jfburke3** [comment]
Subjectively, it seems that 3.107 doesn't suffer from this problem as much.  I drove through the mountains for several hours on Sunday, and the image seemed to flow much more smoothly than before.  Still has an occasional stutter, but not as bad.

**Comment by ovivoda** [comment]
@jfburke3 Can we close this issue? The app works better now?

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
