### ISSUE TITLE
Exiting camera mode take a while

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2729]
### Basic information
* Platform: Android 7.0, AT&T build 
* Version: Mapillary 3.104 (and several previous releases)
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Shoot sequences.
 2.  Stop the sequences.
 3.  Press the phone's back button.

### Expected behavior

The Mapillary app returns to the main screen within a few seconds, like it used to do. 

### Actual behavior

Three app remains on the camera screen, or sometimes a black screen, for a while. 15-30 seconds is not uncommon, and over a minute is somewhat frequent, too. The exact amount of time varies greatly. 

Sometimes it takes so long that Android pops up a message that the app isn't responding and do I want to wait or close Mapillary. 

If you want, I can try to shoot a video of it happening so you can see what I'm talking about. 

### Additional information

My impression is that this started about the same time as #2728 and #2719.  I also wonder if it could be related to #2706.

**Comment by Badooleoo** [comment]
Does it increase the more images you have saved to your device? Is it quick again when there are no images to upload?

I get noticeable slowdown like this once I have more than 10,000 images, by 30,000 images I have to be quite patient.

This happens when loading the Mapillary app, accessing the camera, exiting the camera and exiting the app. It returns to normal as the images decrease. In my case I would guess Mapillary is reading all the directories and files which take longer the more there is.

**Comment by ovivoda** [comment]
@Badooleoo Please try this APK here and let me know if it works better. Try it with a lot of sequences and images:

http://android-releases.mapillary.io/Mapillary_Android_v3.112-BETA.apk

**Comment by jfburke3** [comment]
Sorry, I didn't notice these updates until now....

@badooleoo It's aggravatingly slow with almost zero images.  It's almost unusable when I have only a few thousand pictures.

@ovivoda I noticed that a 3.112 was available on the beta channel and installed it.  If it is what you posted the link to above, then I can't say it has improved anything.  It might even be a little worse.  Maybe.

**Comment by jfburke3** [comment]
This is still present in 3.112.

I will also note that I recently timed one such attempt at >2 minutes, at which point I simply killed the app.

**Comment by ovivoda** [comment]
@jfburke3 I looked a bit more into it and I have a new build here. Please try it and let me know if it works better:

http://android-releases.mapillary.io/Mapillary_Android_v3.113-SNAPSHOT3.apk

**Comment by jfburke3** [comment]
I've only had limited time to test this build, but subjectively it *seems* to be better.  I'll have the opportunity to give it a pretty good run this weekend, after which I can give you a better answer.

**Comment by jfburke3** [comment]
I've given it a fairly good workout, and cannot reproduce the problem with the last snapshot builds you provided, and the beta version in the play store works pretty well, too.  I think you can close this one!

**Comment by ovivoda** [comment]
Thanks @jfburke3 Closing it

**Comment by jfburke3** [comment]
I just had to add a comment that whatever you did to fix this, has been rock-solid for the past couple of months.  Currently on 3.119.  Fantastic performance.  A very big thank-you for finding the problem @ovivoda .
