### ISSUE TITLE
App produces duplicated images in mapillary folder

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#273]
Sometimes I find duplicated images in mapillary folder, both having the same mapillary tags, but only one of them has a file name consistent with the shooting time.

See for example: 

https://dl.dropboxusercontent.com/u/90019879/2014_08_10_12_48_32_875.jpg
https://dl.dropboxusercontent.com/u/90019879/2014_08_10_15_18_32_578.jpg

or

https://dl.dropboxusercontent.com/u/90019879/2014_08_10_11_13_10_462.jpg
https://dl.dropboxusercontent.com/u/90019879/2014_08_10_15_23_10_061.jpg

**Comment by peterneubauer** [comment]
Is this still an issue with the new app versions 1.0+ ? Closing this for now.

**Comment by kaitu** [comment]
Fine. I did only a little testing with the new version, so far the problem hasn't occurred. I'll notify if I spot it again.

**Comment by kaitu** [comment]
Here is another dupe with app version 1.63:

https://dl.dropboxusercontent.com/u/90019879/2015_12_27_13_36_04_952.jpg
https://dl.dropboxusercontent.com/u/90019879/2015_12_27_14_16_04_854.jpg

**Comment by peterneubauer** [comment]
Wow,
These are some hour apart! Are these the originals? Will check the exif...

**Comment by kaitu** [comment]
Yes, originals.
It looks from mapillary_trace.txt that picture 2015_12_27_13_36_04_952.jpg had been shot properly, then it was somehow overwritten with contents of picture 2015_12_27_14_16_04_854.jpg

[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/76643/mapillary_trace.txt)

**Comment by peterneubauer** [comment]
I found a place where potentially images are saved twice (but with the same filename). In the new versions coming out, beginning with the current beta release, that should not happen anymore, please let me know if you upgrade and still encounter this. Closing for now.
