### ISSUE TITLE
No parking detected as no-u-turn

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#2733]
### Basic information
* Platform: `Web`
* Version: `Version 61.0.3163.100 (Official Build) (64-bit)` 
* System/Browser: `Chrome`

I found several cases where if there is a clump of no parking detection, one or 2 signs will be detected as no-u-turn.  See example below

![screen shot 2017-10-10 at 16 53 20](https://user-images.githubusercontent.com/353700/31384209-8b43b9fa-addb-11e7-8083-87ff150d2267.png)

![screen shot 2017-10-10 at 16 50 10](https://user-images.githubusercontent.com/353700/31384162-53ca1bb8-addb-11e7-819c-ff016f2a4a44.png)

https://www.mapillary.com/app/?pKey=ymMf8yn9uxQC_8qXnpY-yg&focus=photo&lat=34.17459138888887&lng=-118.3937680555556&z=17&signs=true&x=0.7277100633701102&y=0.5444554028124847&zoom=2.168831660829741

**Comment by ybkuang** [comment]
This has been resolved by the recent [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html) for traffic sign detection. Please let us know if the issues persists.
