### ISSUE TITLE
Garmin 360 Upload Crashes

### ISSUE THREAD

**Issue by vespax** [mapillary/mapillary_issues#2738]
Latest version of iOS app provides support for Garmin 360 camera.  App detects camera on both iPhone 6 and 6s using iOS 11.  Asks to transfer from Garmin camera, begins upload and then crashes.  

Don't see a work around to upload on website just yet.

### Basic information
* Platform: `iOS` | `Android` | `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1.
 2.
 3.

### Expected behavior

...

### Actual behavior

...

### Additional information

...

**Comment by millenbop** [comment]
Thanks for reporting!

Do you mean it crashes when you are transferring the photos from the camera? Are you using the latest firmware on the camera?

**Comment by vespax** [comment]
Yes, during transfer from camera to Mapillary app.  Using 3.30 in 360 camera.  I believe that is the latest firmware according to Garmin.

**Comment by millenbop** [comment]
Ok thanks! I'll look into it!

**Comment by millenbop** [comment]
I'm having problems reproducing your crashes unfortunately. Do you still have this problem?

**Comment by millenbop** [comment]
No update for a few months, so closing. Will reopen if the problem persists.
