### ISSUE TITLE
When you are sign in button 'Create account' is still there

### ISSUE THREAD

**Issue by kRkk** [mapillary/mapillary_issues#2739]
### Basic information
* Platform: `Web`
* System/Browser: `Ubuntu 17.04 | Firefox 56`

### Steps to reproduce behavior

 1. Go to [mapillary.com](https://www.mapillary.com/)
 1. Log in or Sign in

### Screenshot
![screnshot](https://user-images.githubusercontent.com/16520278/31583638-7e82dc74-b19f-11e7-8c96-527ca925c8ef.png)

**Comment by katrinhumal** [comment]
Thanks for reporting! I think we've just missed that one. Will pass it on to the developers.

**Comment by nicolas17** [comment]
Duplicate of #2581?

**Comment by katrinhumal** [comment]
This has been noted down internally to be handled at some point. Since it's not a blocker from using Mapillary, closing the issue here.
