### ISSUE TITLE
Newly created object tags often disappear a few seconds after creating them

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2743]
When creating an object tag and click the green button to accept the geometry, the green dot appears showing that the tag has been created.

However, for me, the tag disappears a few seconds (sometimes immediately) after creating it.

What seems to happen is:
1. JS backend sends "create obj tag changeset" to backend
2. JS backend periodically updates "current tags in image". As the request from 1 does not always finish immediately (sometimes it doesnt finish at all) this might not contain the newly created tags
3. UI is updated based on the server response from (2) and therefore does not show the tags I created.

Possibly this is dependent on server load but even if that's the case it would be great if you could retry the request in JS if it fails and/or create some logic to show a tag as "pending" (i.e. still being processed on the server.

I've created a screencast video where you can have a look: https://youtu.be/kEek1C_vQ2Q
At the end I also show the Chrome network tab where you can see that a request gets canceled (possibly timeout?). I'm using Chrome  61 on Ubuntu 16.04 x64.

**Comment by ToeBee** [comment]
I see this problem as well. Chrome seems to abort the request to create the tag after a few seconds (or when a new request is initiated?) so it shows in the debug tools as `(cancelled)` however in looking at the dev tools while trying this in IE, I see the sever chewing on the request for 30 seconds before the front end server aborts the request and sends back an HTTP 504 because the back end is taking too long to respond.

A screen shot of IE's request:
![image](https://user-images.githubusercontent.com/348948/31595171-659c482a-b1ff-11e7-917e-29fd7180690a.png)

**Comment by ulikoehler** [comment]
@ToeBee As far as I could see nothing special happened at the point in time the request was canceled (i.e. no other request was started etc) and the request was canceled after 15.00 seconds, so I think Its some hardcoded limit which might be different in IE.

I've seen a similar issue in April or in May when loading large sequences made the reverse proxy 504 due to the API server taking too long to process the data, but the guys fixed it rather quickly so it likely can be fiyed this time as well. Or maybe Its just tens of thousands of people adding millions of tags every minute :-)

Anyway, nice to know Its not just me who is having this issue ;-)

**Comment by gyllen** [comment]
@ulikoehler @ToeBee We had an error during the weekend, this should now have been fixed and actually all the tags you added should be there. closing and sorry for the inconvinience

**Comment by ulikoehler** [comment]
@gyllen The tags still occasionally disappear (though apparently less frequently), with the same issue being shown in the network tab (cancelled requests). However I can confirm that if you wait a few seconds the tags are added 100% reliably (so its mostly just a display error).

**Comment by gyllen** [comment]
@ulikoehler Thanks for reporting that, will give this feedback to backend team

**Comment by ulikoehler** [comment]
@gyllen I've tried again today and I didn't encounter this issue any more. Maybe its dependent on server load but in general I think its safe to assume it's fixed.

**Comment by gyllen** [comment]
@ulikoehler Thanks for trying again, we are keeping an eye on this.
