### ISSUE TITLE
Mapillary ignores the 'Camera points forward' setting

### ISSUE THREAD

**Issue by fgouget** [mapillary/mapillary_issues#2746]
### Basic information
* Platform: Android 7.0
* Version: Mapillary 3.104 or 3.105
* System: Samsung Galaxy S7 (SM-930F)
* 'Force the use of the legacy Camera API = yes' due to bug 1931

### Steps to reproduce behavior

 1. Set the camera pointing direction to forward.
 2. Capture a sequence.
 3. Upload the sequence through the web uploader (or some other way, it probably does not matter).
 4. Click on the sequence on the website and start the editor.

### Expected behavior

The editor shows the pictures pointing in the direction of travel (with an allowance for sharp turns).

### Actual behavior

The editor shows the pictures pointing in at a random angle to the direction of travel:
![image](https://user-images.githubusercontent.com/1897397/31697557-9a9ba362-b3b8-11e7-9810-b0540f083187.png)

### Additional information

I have not yet tried telling Mapillary to use the compass.

**Comment by HolgerJeromin** [comment]
Same or related to #2566

**Comment by jfburke3** [comment]
I just want to make the observation that the last several builds I've used have done very well with the camera direction setting on my phones.  It used to be an issue for me as well, but seems to be pretty reliable now.

**Comment by HolgerJeromin** [comment]
Same here.

**Comment by majkaz** [comment]
Mapillary v. 3.108, Android 5.0.2, legacy api, version code 408.

Mapillary ignores almost all capture settings:

- camera points forward (result as shown by fgouget)
- distance based capture - ignored
- timed capture setting - the time is ignored

The only accepted setting is in the camera pane, the photo min. delay - there comes almost constantly the toast with the "no photo because too fast" message.

**Comment by jfburke3** [comment]
Just a note to say that I can't confirm @majkaz's issues.  The three settings he lists all seem to work for me in the last few releases.  Differences are I'm on Android 7.0, using Camera2 API, so that might be a factor.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
