### ISSUE TITLE
Duplicate image positions

### ISSUE THREAD

**Issue by fgouget** [mapillary/mapillary_issues#2747]
### Basic information
* Platform: Android 7.0
* Version: Mapillary 3.104 or 3.105
* Browser: Samsung Galaxy S7 (SM-930F)

### Steps to reproduce behavior

 1. Set up the phone in a car.
 2. Setup the capture as follows:
    Distance based capture : yes
    Distance autocapture: 5m
    Photo min delay: 0s
    Force the use of legacy Camera API: yes
 3. Drive above 30 km/h.

### Expected behavior

Regularly spaced pictures.

### Actual behavior

The pictures tend to clump in pairs that have the exact same coordinates.
This compounds the picture orientation issue mentioned in bug 2746 (normalizing the sequence results in pictures pointing backwards).

### Additional information

Looking at the LEGACY_CAM_*.gpx files one can notice that Mapillary takes four GPS position samples a few milliseconds apart and then another group of four roughly a second later. For instance:

<trkpt lat="48.7743264" lon="2.2410339"><pdop>4.0</pdop><ele>207.31189075352597</ele><time>2017-10-14T10:12:26.555Z</time></trkpt>
<trkpt lat="48.7743264" lon="2.2410339"><pdop>4.0</pdop><ele>207.31189075352597</ele><time>2017-10-14T10:12:26.556Z</time></trkpt>
<trkpt lat="48.7743264" lon="2.2410339"><pdop>4.0</pdop><ele>207.31189075352597</ele><time>2017-10-14T10:12:26.561Z</time></trkpt>
<trkpt lat="48.7743264" lon="2.2410339"><pdop>4.0</pdop><ele>207.31189075352597</ele><time>2017-10-14T10:12:26.564Z</time></trkpt>

<trkpt lat="48.7744389" lon="2.2408793"><pdop>4.0</pdop><ele>207.45811020482685</ele><time>2017-10-14T10:12:27.585Z</time></trkpt>
<trkpt lat="48.7744389" lon="2.2408793"><pdop>4.0</pdop><ele>207.45811020482685</ele><time>2017-10-14T10:12:27.600Z</time></trkpt>
<trkpt lat="48.7744389" lon="2.2408793"><pdop>4.0</pdop><ele>207.45811020482685</ele><time>2017-10-14T10:12:27.604Z</time></trkpt>
<trkpt lat="48.7744389" lon="2.2408793"><pdop>4.0</pdop><ele>207.45811020482685</ele><time>2017-10-14T10:12:27.633Z</time></trkpt>

However 30km/h is more than 5m/s so the phone attempts to take more than one picture per second, and succeeds, at least some of the time. For instance it took the following pair of photos:

File Name                       : 2017_10_14_12_12_26_659_+0200.jpg
Create Date                     : 2017:10:14 12:12:26.0613
GPS Latitude                    : 48 deg 46' 27.58" N
GPS Longitude                   : 2 deg 14' 27.72" E

File Name                       : 2017_10_14_12_12_27_586_+0200.jpg
Create Date                     : 2017:10:14 12:12:27.0526
GPS Latitude                    : 48 deg 46' 27.58" N
GPS Longitude                   : 2 deg 14' 27.72" E

The 'Create Date' timestamps indicate that both photos were taken between the first and second clumps of GPS positions[1]. As a result the last known GPS position was exactly the same for both pictures.

I find it strange that Mapillary clumps the GPS samples in this way. Maybe it's an attempt to gauge the GPS accuracy. Or maybe Mapillary is just recording the system's GPS notifications so that it's Android that's to blame. Otherwise it seems like it would be much better to record the GPS position at a more even interval.

Barring that, Mapillary should perform some interpolating. This may be hard to perform while recording since the future position is not known at the time the picture is taken. One option would be to delay recording the picture until the next GPS sample is available. Another would be for the app to perform a post-processing step when closing a sequence. Or this could be done on the server if the GPX file got uploaded along with the photos.

In the meantime a workaround is to systematically run the pictures through the geotag_from_gpx.py script since it performs the required interpolation.

[1] I'm ignoring the 0 after the 'Create Date' dot. I'll chalk it up to an incorrect '%04d' instead of the required '%03d' for printing the number of milliseconds. Also the filename probably comes from the time when the picture got saved rather than when it was taken which would explain why it's a bit later than the 'Create Date'.

**Comment by Eric-FR** [comment]
Great analysis!!!
I already observed many time that pictures were not properly spread along tracks. See for instance:
https://www.mapillary.com/map/im/Z_j5YSfYvnXjIBK0LiXSDA
I was suspecting interferences between "distance based capture", "photo min delay" and cpu (over)loading at acquisition time leading to none periodic picture catching. Indeed, your "photo min delay" being set at 0.0s, such interferences are more likely not to exist.

**Comment by davebrny** [comment]
im having the same problem with an xperia xz1 compact and z3 compact.  
the geotag_from_gpx.py only seems to make things slightly better, they are not clumped together anymore but i still have to move quite a few photos.

i bought a garmin glo a few weeks ago which fixes this problem completely on the z3 compact but unfortunately it doesnt work with the mapillary app running on my xz1 compact (android 8) which is the phone that takes the best photos.

it would be great to see a fix for this sometime soon as its real tedious work having to move so many photos, especially on longer sequences

**Comment by ovivoda** [comment]
@fgouget @Eric-FR @davebrny 

Please try and setup `Photo min delay:` to a value higher than `250` miliseconds. That should fix the problem.

**Comment by davebrny** [comment]
that didnt change much unfortunately but im after getting my garmin glo working with the xz1 (by disabling google play services) so all the photos now end up in their correct positions

**Comment by ovivoda** [comment]
@davebrny thanks for the info. So the problem was the interpolation of the images and bad location from gps provider that uses GMS?

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
