### ISSUE TITLE
In the web upload dialog point to the HTTPS version of the legacy site

### ISSUE THREAD

**Issue by Abbe98** [mapillary/mapillary_issues#2748]
![image](https://user-images.githubusercontent.com/2631719/31733926-4f08ed62-b43d-11e7-92c5-e0f57a036776.png)
The second link to legacy.mapillary.com (video upload link) points to `http://legacy.mapillary.com/map/upload/vi` instead of `https://legacy.mapillary.com/map/upload/vi`.

**Comment by gyllen** [comment]
@nickplesha Should be quick fix

**Comment by nickplesha** [comment]
The link has been updated.
