### ISSUE TITLE
Verifier Game served up same image twice

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2750]
I can't be 100% certain but I got an image with a distinctive red object in the lower left corner. I approved the detection but then I am almost certain the same image came back to me again a few clicks later. Presumably you shouldn't be able to double verify your own verifications? I suppose it is also possible that the image got uploaded twice by the user so it is actually two different detections even though it looks identical.

I did approve it the second time as well so hopefully that left a record you can trace.

This is the image:
![2017-10-18 23 54 44](https://user-images.githubusercontent.com/348948/31755008-2c71bd50-b461-11e7-9bc0-51724fc7d04d.png)

**Comment by ToeBee** [comment]
This is another one that I'm pretty sure got served up twice to me while idly verifying some things during SOTM-US.

![2017-10-20 17 52 48](https://user-images.githubusercontent.com/348948/31853564-397c5d5c-b650-11e7-97f4-3969586af2ca.jpg)

**Comment by gyllen** [comment]
@tobias-o Reassigning to you

**Comment by tobias-o** [comment]
@ToeBee I deployed a fix. Please reload the tool and try again.

**Comment by ToeBee** [comment]
I think I have been served up this image 3 times today on the right turn one: [j6vM1YdNXXvoI8hHRer6Fg](https://www.mapillary.com/app/?pKey=j6vM1YdNXXvoI8hHRer6Fg). I'm guessing it is trying to serve up ones that someone else has already validated to get points assigned quicker?

**Comment by ToeBee** [comment]
So that last one might be a false positive. The user took a bunch of pictures at that location while standing still. From the bit of image shown in the verification tool I can not tell if it is actually the same image or not. I got the image key by having bringing chrome dev tools up and then hitting the "back" button in the verifier tool and pulling it out of the image URL. I only did this the last time I saw the image so I can't be sure they were actually the same image key.

**Comment by GITNE** [comment]
I think I have observed the same. However, it is very difficult to prove it unless you track the image keys served. Or, maybe it is just my human imperfection or fuzziness which eludes me? @tobias-o @gyllen Anyway, I have also noticed that it is much more common or probable to happen when you are the first one and/or only one to review a category. It is also more probable to have an image served twice on the first few hundred to review. Try testing on a new category for about 500 images.

**Comment by tobias-o** [comment]
I experienced the same behavior several times, but found that it was different image keys every time. Most of those cases were images taken while moving slow and/or with a high sampling rate. Sometimes the images just looked very similar and were actually far apart.
