### ISSUE TITLE
Allow closing app hint on website

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2758]
When opening the website with opera mobile i get a footer

> For best experience on mobile, use our native app

But blurring is not possible in the app for example. It would be nice if i could get rid of the message and use the pixel space.

**Comment by katrinhumal** [comment]
Thanks for the suggestion! This has been asked for in https://github.com/mapillary/mapillary_issues/issues/2726 as well so I'm closing here in favour of the existing issue.
