### ISSUE TITLE
Closing “Computer vision detections” opens “Search tags” pane

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2760]
### Basic information
* Platform: `Web`
* Version: `Any`
* System/Browser: `Firefox`, possibly others too

### Steps to reproduce behavior
1. Click on `Computer vision detections`
2. Click the `X` symbol to close the pane
3. `Search tags` pane opens

### Expected behavior
Clicking on the `X` symbol of the `Computer vision detections` pane should close it and not open any other pane.

### Actual behavior
Clicking on the `X` symbol of the `Computer vision detections` pane closes it but also opens the `Search tags` pane.

**Comment by katrinhumal** [comment]
Thanks for reporting! We've just provided a fix for this and it will be in effect soon. :)

**Comment by GITNE** [comment]
Works as expected. :smile: Thank you for fixing this issue so quickly! :+1:

**Comment by katrinhumal** [comment]
Thanks to @nickplesha ;)
