### ISSUE TITLE
No more than 99 tags

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2761]
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Firefox`, possibly others too

### Steps to reproduce behavior
1. Go to tag editor
2. Apply 99 + n tags

### Expected behavior
*Intuitively*, the number of tags per image should be unlimited. If a limit is intended then there should be a popup or some kind of message which says that the limit has been reached. Alternatively, you should not be able to add more tags unless you delete one to get below the limit.

### Actual behavior
Any 99 + n*th* tag is silently discarded.

**Comment by gyllen** [comment]
@nickplesha elevate

**Comment by GITNE** [comment]
Seems to be fixed, at least for Firefox on Windows. @nickplesha Did you do anything?

**Comment by nickplesha** [comment]
@GITNE Yes, this should be fixed deployed now! The limit was on only how many tags are shown in the viewer/editor, all tags were saved.
