### ISSUE TITLE
Unable to edit tags because of too many tags

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2762]
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Firefox`, possibly others too

### Steps to reproduce behavior
1. Apply reasonably many tags
2. Exit tag editor
3. Click on `Tags`

### Expected behavior
The `Edit tags` button should always be accessible and the `Tags` pane must not grow beyond the size of the screen. Note that if `mapillary-js` has been embedded in a page it is acceptable for any of its panes to grow over its embed borders but not beyond the screen.

### Actual behavior
The `Edit tags` button becomes inaccessible if the image has been tagged with a certain amount of tags.
![tags](https://user-images.githubusercontent.com/15823872/32002499-fa103116-b99c-11e7-8623-cdf81ed18ee3.png)

**Comment by GITNE** [comment]
Happens on high dpi devices too. :disappointed:
![tags hdpi](https://user-images.githubusercontent.com/15823872/32005110-c52014c4-b9a3-11e7-9238-3afbd830a01c.png "“Tags” pane on high dpi")

**Comment by gyllen** [comment]
@angelday Design feeback

**Comment by angelday** [comment]
`I got 99 tags, but adding one more ain't one`

As a quick fix let's give it a fixed height (based on viewport size?) and make the list scrollable. How about that @nickplesha ?

cc @Stephenduffy

**Comment by nickplesha** [comment]
Thanks for reporting! This has been fixed so list should become scrollable when a lot of tags are in the list.

**Comment by GITNE** [comment]
@nickplesha Works as expected now. Thank you for fixing this so quickly! :+1:
