### ISSUE TITLE
Sequence Cut

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2763]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox`

### Steps to reproduce behavior

 1. Try to make an Sequence cut
 2.
 3.

### Expected behavior

Should find a Button to make an Sequence Cut 

### Actual behavior

Found no way to make an Sequence Cut. Trying to use the Legacy Url, it's only throw an error

### Additional information

...

**Comment by katrinhumal** [comment]
@thoschu96 We don't currently have the option for you to request a sequence cut. Sequence cutting is done by an automatic bot that runs daily and cuts where images are too wide apart. If you think it hasn't been working in specific places, please report and we can take a look and if necessary, manually trigger a rerun of the bot for that area/sequence.

**Comment by thoschu96** [comment]
![image](https://user-images.githubusercontent.com/10342344/32101863-353c3a22-bb1a-11e7-89f8-b5386e70b7a6.png)
Yep. there is a Sequence which is messed up, however ... next to Town : Lungern

**Comment by katrinhumal** [comment]
@thoschu96 Thanks for sharing - we'll manually rerun to fix this.

**Comment by katrinhumal** [comment]
@thoschu96 we went over this again and it should be better now - please check and confirm. :)

**Comment by geowOSM** [comment]
#210 
see https://github.com/mapillary/mapillary_issues/issues/210#issuecomment-343658155

**Comment by katrinhumal** [comment]
Replied in the other thread, closing here.
