### ISSUE TITLE
Feature request : Minimum delay between pictures in sequence auto-navigation

### ISSUE THREAD

**Issue by Eric-FR** [mapillary/mapillary_issues#2764]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

When using the automatic advance option while navigating through a sequence, I find the speed too high, especially when pictures are widely spaced. I would like an option to go slower, for instance setting a minimum delay between two successive pictures.

**Comment by katrinhumal** [comment]
@Eric-FR Thanks for the suggestion! We've heard it a couple of times before that people would like to be able to adjust the speed of the autoplay. I'm adding your feedback to our internally tracked issue and closing here.

**Comment by Eric-FR** [comment]
Thanks for new version with rabbit/turtle option :-). Also, the backward option is interesting.
