### ISSUE TITLE
Feature request : in edit blur mode, stop on next blur

### ISSUE THREAD

**Issue by Eric-FR** [mapillary/mapillary_issues#2765]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

I'm doing a lot of blur corrections on sequences recorded on out-of-town roads. Considering the large number of false positives, I'm looking for a method to easily find false positives. Therefore, I think that, when in edit mod, with auto-advance on, an option to stop on next blur would be useful. So, I would be able to review all intermediate pictures for missing detection and automatically stop on already blurred parts that are mainly false positives.

**Comment by GITNE** [comment]
> I'm looking for a method to easily find false positives.

This is probably going to be best addressed with the verification game, since it is very well suited to quickly find false positives and confirm true positives. @mapillary In this case it might be a good idea to let the users choose a sequence first and then run the verification game on it, instead of randomly serving blur positives. Most users who care for blurs tend to care about their sequences first/more than others’, which is understandable but should also be made good use of. :wink:

**Comment by katrinhumal** [comment]
@Eric-FR I feel I'm not completely following how your workflow goes. If you are playing the sequence (auto-advance) and want it to stop only at the next image that has blurs then how about the "review all intermediate pictures for missing detection" - you would just auto-play past the images where no blurs have been marked by the algorithms. Could you help me understand by explaining a bit more in detail?

**Comment by Eric-FR** [comment]
I start auto-play and I'm ready to stop it if I see:
- people
- vehicle
- false positive
First, I mainly stop for false positives. Second, I usually stop too late and I have to move back to the previous picture(s). Moreover, I stop too late on false positives because they appear suddenly. In opposite, I usually stop before or on the right picture for people and vehicle (driving the same direction at least). 

Typical sequences with not so much people and vehicle that I treated recently:
https://www.mapillary.com/map/im/t0OgAjQqjFaWm12RQWvTww
https://www.mapillary.com/map/im/u4I0WfrQO-dcx_QrGk-uCw

**Comment by kaitu** [comment]
related to #2134

**Comment by katrinhumal** [comment]
Blurring should now work much better since the latest update: https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html

So hopefully, you don't find any sequences anymore where you need to go in and mass blur things. :)
