### ISSUE TITLE
Feature request: Verification: Arrows shortcuts

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#2766]
### Basic information
* Platform: `Web`
* Version: Newest 
* System/Browser: Chrome

### Steps to reproduce behavior

 1. Go to the verification feature.
 2. Select task.
 3. Click a lot - discover that you spend a lot of time moving the mouse.

### Expected behavior
Arrow keys would be a lot faster: ok up, no down, back left, skip right.
A bonus would be vi shortcuts: hjkl :-)

### Actual behavior
Move mouse a lot. Waste time.

**Comment by katrinhumal** [comment]
@simonmikkelsen Glad to say that we are planning on adding keyboard shortcuts to the next version! Closing here since this is already tracked for us internally. :)
