### ISSUE TITLE
Consider removing unfocused/bad photos

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2769]
I see in the verifier game that a lot of mis-interpreted signs come from unfocused/shaken/bad photos.
Consider removing them from the database (what kind of information can you extract from these photos?)

**Comment by voschix** [comment]
I would caution against removing shaken or unfocused photos. They may still
allow to obtain some information like: type of highway, estimated width,
presence of illumination (on night photos), presence o buildings, trees,
bridges, tunnels,...
I admit to be biased as a producer of many such photos, but they
surprisingly often still carry information. Extracting traffic signs is not
the only purpose of Mapillary photos.

**Comment by echeloni2p** [comment]
HI

unsharp/blurred pictures maybe removed in areas with coverage of good pictures. 

echelon

**Comment by katrinhumal** [comment]
Thanks! @voschix is right that even blurry images can contain information so the bulk of the less-than-perfect images are still very useful. Of course, there are some extreme cases when you barely understand what's in the image because it's so blurry - but these are a minority. These can be removed with the editor (https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences). Just a note, that we don't right now have a review system for deletion requests on someone else's images so submitting these will just queue them in the system and they'll be pending on your profile. But deletion of your own images is auto-approved so that works pretty well.  We will not be removing images on Mapillary's behalf though, so this is all community-based.

**Comment by Alessandro-Barbieri** [comment]
@voschix you can just look at the next/previous image and extract data from there. Bad images not only make a bad street-view like experience but also waste resources on the training algorithm (which have to learn how to recognize bad extracts)

**Comment by Alessandro-Barbieri** [comment]
> We will not be removing images on Mapillary's behalf though, so this is all community-based

This is bad: unlike in openstreetmap the community can't run QA tools on the database and then request removal so it's all on your hands providing image quality.

**Comment by katrinhumal** [comment]
I think it might be these logs: https://drive.google.com/file/d/0B19mmCKTPBRYejZTWlo4TnRpbTg/view?ts=59f72da9

**Comment by GITNE** [comment]
> I would say, that removing pictures should be normally done by the authors, unless pictures are clearly offensive or violating the law.

@mapillary I basically agree with @voschix here. Mapillary should give some sort incentive to users to produce quality images, not only quantity for the leaderboard. And, as @voschix has pointed out, algorithms do exist to score image quality. But, I also understand that implementing this is not a top priority right now.

**Comment by katrinhumal** [comment]
Thanks for all your insights! I'll make sure to share with the team.

**Comment by Alessandro-Barbieri** [comment]
An alternative to removal is to hide bad images or to opt-out with a switch in the web view (so will not be visible if the user don't want).

**Comment by drkludge** [comment]
I am not Ansel Adams.  I don't pretend to be.  I am driving most of the time and I don't worry about what the camera is doing.  I am eating my Dog Food while editing OSM right now.  Some of my most useful work may fall into the bad images category but I am getting the information for completing edits in OSM.  I flood an area with pictures and Mapillary magically stitches the pictures together.  Moreover, I don't have to manage the pictures to make my edits.  Mapillary makes me feel like [Tom Sawyer painting a fence.](https://www.youtube.com/watch?v=8xZm2UOam74)  I have had both the Mapbox and Telenav data teams in my area.  They have been able to make edits that I have not been able to get to.  I just didn't get all the trinkets out of the deal!  ;-)
