### ISSUE TITLE
go to original in verifier game

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2771]
It's possible to have a button in the verifier game (or click on the image) for going to the original image.

Will help in requesting unblur/deletion/whatever.

**Comment by voschix** [comment]
No, for protection of privacy.
Access to unblurred photos is only possible for the author of each photo.

**Comment by Alessandro-Barbieri** [comment]
> No, for protection of privacy.
> Access to unblurred photos is only possible for the author of each photo.

Sorry for the confusion, I was referring to the possibility to jump from the extract currently on review to the page with the photo.
I read in a comment that an user is doing manually this with google chrome (extracting the key and then pasting in the link)
I'm not interested in the "true" original.

**Comment by Eric-FR** [comment]
> Access to unblurred photos is only possible for the author of each photo.

Even as author of a photo, I don't know how to access to the unblur version, especially in blur edit mode.

**Comment by voschix** [comment]
@Eric-FR


Even as author of a photo, I don't know how to access to the unblur
> version, especially in blur edit mode.


When you are in blur edit mode
1) click "Exit Editor"
2) In the "Image details" panel click "Download unprocessed original" (only
visible when viewing one of your own photos)

>

**Comment by Eric-FR** [comment]
Ok... but, how to access to the original in blur edit mode? Sometimes, a large part is incorrectly blurred although a small part inside need to be blurred. So I first remove the false positive but, then, the area remains blurred so it is difficult to select the detail to be blurred.

**Comment by katrinhumal** [comment]
@Eric-FR Unfortunately, it takes time for the displayed blur to catch up (due to cache) so this will remain an issue for now in the blur editor. 

@Alessandro-Barbieri Adding a link to the image on Mapillary is another thing that we're considering to add in the next versions of the game. Thanks for adding weight to the suggestion!

**Comment by katrinhumal** [comment]
This has been written down internally as an improvement suggestion for future versions of the verifier. Closing here.
