### ISSUE TITLE
Feature request: Add help information on web app

### ISSUE THREAD

**Issue by ray66** [mapillary/mapillary_issues#2772]
I propose to add a help button to the web interface. The help page should explain the different ways to navigate through the images. In particular, there is missing information on keyboard shortcuts.

**Comment by katrinhumal** [comment]
Hi @ray66 - thanks for pointing this out! I've improved the help page by adding information about the shortcuts: https://help.mapillary.com/hc/en-us/articles/115001662325#navigation. We'll also look into making help more visible.
