### ISSUE TITLE
Blur editor breaks tag editor

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2774]
### Basic information
* Platform: `Web`
* Version: `any` 
* System/Browser: `Firefox`

### Steps to reproduce behavior
1. Go to any image
2. Go to blur editor
3. Exit blur editor
4. Go to tag editor
5. Select any tag
6. Drag a rectangle tag

Notice that the rectangle tag simply vanishes and the tag is discarded. No tags can be added.

### Expected behavior
The tag editor should work as expected independent of any previous user action.

### Actual behavior
The tag editor only works flawlessly if the user did not go to the blur editor.

### Additional information
Of course, reloading the page while in the tag editor restores the tag editor to normal operation.

**Comment by katrinhumal** [comment]
@GITNE thanks for reporting and sorry for the slow response. This should be fixed now, can you please check and confirm at your end?

**Comment by nickplesha** [comment]
While going from blur mode to tag mode should work fine now, it seems going back to blur mode and then to tag editor the second time will reproduce this error again. Sorry, we'll fix the underlying issue completely soon. :)

**Comment by GITNE** [comment]
> While going from blur mode to tag mode should work fine now, it seems going back to blur mode and then to tag editor the second time will reproduce this error again. Sorry, we'll fix the underlying issue completely soon. :)

Confirmed. Seems to work as expected on first attempt now. On second attempt, the reported behavior can still be observed. Thank you for investigating. :smiley:

**Comment by nickplesha** [comment]
This should be fixed now.

**Comment by GITNE** [comment]
@nickplesha Works as expected. Thank you! :smile:
