### ISSUE TITLE
photos shown with compass 0 in sequence editor

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2777]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox`

### Steps to reproduce behavior

 1. edit a sequence

### Expected behavior

Photos shown with the right compass direction in the map and in the `Compass Angle` cell

### Actual behavior

Photos shown with compass angle 0

### Additional information

correct angle shown normally

![screenshot-2017-10-30 mapillary - street-level imagery powered by collaboration and computer vision](https://user-images.githubusercontent.com/10689739/32192040-4cfcfa48-bdb3-11e7-8f6b-f1cd534add41.png)

incorrect angles shown in editor

![screenshot-2017-10-30 mapillary - street-level imagery powered by collaboration and computer vision 1](https://user-images.githubusercontent.com/10689739/32192044-4d347432-bdb3-11e7-9822-a5f38e5d894c.png)

**Comment by GITNE** [comment]
Basically, this is correct. It takes some to reprocess the sequence and update the backend cache. Just wait for about an hour. :wink:

**Comment by Alessandro-Barbieri** [comment]
@GITNE 21 hours later the issue is still there

**Comment by GITNE** [comment]
> @GITNE 21 hours later and the issue is still there

Please, share the sequence key or any image key of the sequence in question, so that @mapillary and others can take a look at it.

**Comment by Alessandro-Barbieri** [comment]
key of sequence: `qJnmLiLpwYmgv6nOdBwgtw`

**Comment by GITNE** [comment]
I observe the same behavior on this sequence. But, I am in Firefox too, so nothing new here.

@Alessandro-Barbieri Did you edit the sequence in the web uploader or the sequence editor afterwards? There might also be an issue with the EXIF data in the images themselves.

**Comment by Alessandro-Barbieri** [comment]
@GITNE I removed some unfocused photo in the area but I don't remember if that sequence had one.

**Comment by gyllen** [comment]
@nickplesha investigate

**Comment by mxa** [comment]
I have set the Android app to use the compass, yet after uploading all images point north. My device definitely has a compass. Is that the same issue? [Sequence](https://www.mapillary.com/map/im/OLEzLN58BkHSSjWl4PY06Q)

**Comment by Alessandro-Barbieri** [comment]
My last sequence have this issue and I can confirm was taken with compass

**Comment by gyllen** [comment]
@peterneubauer Elevating this as an android issue

**Comment by Alessandro-Barbieri** [comment]
Photos with this issue have the `GPSImgDirection` Exif tag equal to 0

**Comment by mxa** [comment]
That means the app failed to squire compass value and there is none, so should we manually change the angle to normalized in direction of travel?

**Comment by peterneubauer** [comment]
@Alessandro-Barbieri do you have a link to the sequence that is pointing north in editing?

**Comment by gyllen** [comment]
@peterneubauer ^^^

**Comment by peterneubauer** [comment]
So,
investigating, the images have all image direction 0 in both EXIF and the JSON tag. This is correct according to the backend processing (since the images in fact point north). This is then an Android issue when using compass @ovivoda .

Normalizing the sequences in the editor should point them to each other eventually. Can you please try that and let us know?

**Comment by ovivoda** [comment]
This issue should be fixed in the latest version of Mappillary Android application
