### ISSUE TITLE
Adding tag while request to add tag running causes new tag to disappear in UI

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#2778]
### Basic information
* Platform: `Web`
* Version: I don't know, accessed 31 Oct 2017 
* System/Browser: `Chrome 63.0.3239.18`

### Steps to reproduce behavior

 1. Go to tag editor
 2. Add some tag
 3. While spinning indicator on tag in sidebar is still spinning, add another tag. For example, find photo with 2 manholes and try to quickly draw both. API is quite slow now so you don't have to do it really quickly.
 4. Two tags with spinning indicator appear
 5. When first (or second?) tag finishes spinning, _second_ tag disappears, both its name from sidebar and bounding box in image, only _first_ remains
 6. After reloading page I see two tags. If, instead of reloading, I navigate to other photo and go back, I still see one tag.

### Expected behavior

After drawing 2 tags, I expect to see both.

### Actual behavior

Second tag disappears.

### Additional information

No errors in console, only ``GET https://www.mapillary.com/this-is-inlined-already.css net::ERR_ABORTED``

**Comment by GITNE** [comment]
I have observed the same issue in Firefox. Sometimes, all other existing tags just disappear (they are not deleted, they just aren’t displayed). This usually happens if you complete drawing a tag before the previous tag request to the server has been completed. On even less occasions, tags are truly dropped. In other words, the tag is not queued for a request nor a request to the server is made. Tip: Try testing on laggy connections, bandwidth is not really an issue here.

**Comment by katrinhumal** [comment]
Thanks for reporting! We've been fixing a number of issues in the tag editor and on my side it looks like this problem has been resolved along the way as well - I am not able to reproduce the issue. When I add tags fast enough to see several of them "processing", they all end up being added to the image as the processing stops. Can you please check and let me know if you still experience the issue?

**Comment by kolen** [comment]
Tried today, it's still reproducible (Chrome 64.0.3282.39).

**Comment by katrinhumal** [comment]
@kolen thanks for re-reporting! I can confirm it's not working completely as it should. As I add several tags in quick succession, not all of them show up. However, when reaching like 6-7 or more tags and starting to remove them, the ones that didn't initially appear start showing up as I delete others. @nickplesha can you please check this out?

**Comment by nickplesha** [comment]
@kolen We've made some improvements to resolve this issue. Let us know if you encounter any errors with tags.
