### ISSUE TITLE
Improvements for detection verification

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#2779]
### Basic information
* Platform: `Web`

### Steps to reproduce

 1. Verify signs via https://mapillary.com/verification/projects

### Suggestions

- [ ] After verifying detections for a while, I noticed, that some of the detections were shown to me multiple times. This is probably not intended and depending on how you count that, it maybe gives me points without another mapper verifying the detection or counts my vote multiple times.

- [ ] I wasn't able to fully complete a challenge, but once I saw a screen saying I completed the challenge and should choose another one. But after a second or so it disappeared and the next detection was displayed. (happened in Firefox for Android)

- [ ] I also noticed that sometimes when I press either :+1: or :-1:, it looks as if I skipped the detection (image turns blue and the fast-forward symbol appears). Don't know if the vote was counted or it really skipped to the next detection. (happened in Firefox 56)

- [x] <s>Sometimes it would help if there was a link to the image containing the detection. E.g. to make an unblur request for the area. I encountered several detections which were completely blurred out and thus not readable. Or sometimes it would be helpful to see the full image to see the context where the detection occured.</s> (see #2771)

- [ ] The share links are broken! They are missing a `/` **and** HTTPS links for the domain `mapillary.com` are broken in general (they are timing out, see #2115). Currently the links are looking like this: https://mapillary.com/verification/pspeed-limit-50-de

**Comment by katrinhumal** [comment]
@floscher Thanks for the feedback! We plan to address the "link to image" in further iterations of the game. For the rest of your items, since they sound like bugs, I'm pulling in developer help here.

**Comment by gyllen** [comment]
@knikel Looks like some bugs to extract from here, elevate

**Comment by floscher** [comment]
As a sidenote: The project "Speed limit 110 km/h in Germany" detects almost no 110 km/h signs. I literally saw more [DKV signs](https://de.wikipedia.org/wiki/DKV_Euro_Service), a wide variety of [TIP trucks](https://www.tipeurope.com/) or 80 km/h signs when verifying that project (**not** combined, each of these sign classes was more present than the actual 110 km/h signs).

I'd guess there were less than 30 correct signs in over 600 signs that I viewed and most of these were stickers on trucks instead of real signs.

**Comment by gyllen** [comment]
@ybkuang Some feedback about 110 signs ^^^

**Comment by yopaseopor** [comment]
Most of signs are bad detected because of blurring them .It would be so useful to include the possibility to unblur it to identify it. But I like so much the verification tool, good job, it was a long-wait-wish made true. Also it would be interesting to "propose" custom detections, marking and element in a pic and starting this kind of quiz.

**Comment by yopaseopor** [comment]
And what about...a section in the app as...Mapillary game!? ;)

**Comment by gyllen** [comment]
@angelday @amahon Some feedback for the game

@yopaseopor Just wait, there will be much more awesome stuff coming up, we are only getting started with the game ;)

**Comment by angelday** [comment]
@Stephenduffy +

**Comment by knikel** [comment]
Thanks a lot for all the feedback everyone!
We're tracking this improvements internally and will be working on the validation app in the coming sprints. I'm closing this issue since `mapillary_issues` is no longer an actively maintained repository.
