### ISSUE TITLE
Disable tag hover while dragging when drawing new tag's bounding rectangle

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#2781]
### Basic information
* Platform: `Web`
* Version: `? (1 Nov 2017)` 
* System/Browser: `Chrome`

### Steps to reproduce behavior

 1. Open tags editor
 2. Find existing tag or create new tag until green dot icon appears
 3. Start creating another tag: press mouse button nearby, and while holding left mouse button, move mouse over green dot of exsiting tag

### Expected behavior

Existing tag does not disturb drawing of bounding rectangle of new tag. There's no reason to highlight existing tags when drawing new tag.

### Actual behavior

Bounding rectangle stops in position before moving over green dot, existing tag is highlighted. It's impossible to make a new tag with one of corners of its bounding rectangle being near center of any existing tag.

### Additional information

![image](https://user-images.githubusercontent.com/24191/32282392-8062dbb6-bf32-11e7-890c-394358988942.png)

**Comment by nickplesha** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
