### ISSUE TITLE
No traffic signs detected in Switzerland

### ISSUE THREAD

**Issue by mhamrle** [mapillary/mapillary_issues#2784]
I recently uploaded few traces from Switzerland and wanted to map speed limit into OSM. But I have not found any detected traffic signs. After small small investigation I have not found any detected traffic signs (found some only from 2015).

**Comment by katrinhumal** [comment]
@mhamrle Thanks for reporting! Depending on how soon after uploading you checked for this, it might have been that the signs were not yet processed. Can you please link to the sequence(s) that you're referring to?

**Comment by voschix** [comment]
It looks as if this is systematic and independent of dates. Traffic sign
recognition on Mapillary tracks fizzles out as soon as you enter
Switzerland. It's not a hard border, but I could not find any traffic signs
further inland than 10km inside Switzerland.

**Comment by mhamrle** [comment]
as mentioned @voschix all traces in switzerland are affected. As an example look at [here](https://www.mapillary.com/app/?lat=46.947553264952205&lng=7.406695140532662&z=17&pKey=ZXv-hHt0bTIeMWxNiwmG-A&focus=photo). The foto is uploaded for more then 3 weeks and traffic sign is not detected.

**Comment by Alessandro-Barbieri** [comment]
Inn primis why traffic sign detection is country sensitive?

**Comment by katrinhumal** [comment]
Thanks for the additional information, everyone! Asking help from @ybkuang.

**Comment by ybkuang** [comment]
@mhamrle @voschix There is some delay on the image processing lately due to update of the scheduler. It will catch up in a few days. Sorry about the delay. 

@Alessandro-Barbieri no strong reason that traffic sign should be country specific. It is a way to us to apply country-specific filtering to the detector given limited amount of training data. In the next iteration of the traffic sign detector, we are considering removing this constraint.

**Comment by GITNE** [comment]
> There is some delay on the image processing lately due to update of the scheduler. It will catch up in a few days.

@ybkuang What about *old* images with false negatives? Is manual traffic sign tagging going to reschedule these for the traffic sign detector?

**Comment by ybkuang** [comment]
@GITNE we will do a complete reprocess on all the images after we re-train the detector with the input from user tags/verifications. Given the cost of processing 200M+ images currently, we would like to ensure the detectors are improved globally before a re-processing.

**Comment by voschix** [comment]
How do you (re-)train the detector if you there is no way for the user to correct the detections? I cannot edit traffic signs in my area - editing is not available. So how can I help improving the detection mechanism?

**Comment by katrinhumal** [comment]
@voschix the first step on the road is our verifier tool: https://help.mapillary.com/hc/en-us/articles/115001964171-Verifier-tool. Right now, only preset tasks are available but our intention is to add the chance to set up a verification task for the traffic sign and area that interest you. And then, we want to also make it possible to edit/add incorrectly detected or missing traffic signs. Then you would be able to help us gather the data needed for retraining the detection algorithm in your area.

**Comment by ybkuang** [comment]
The [update](https://blog.mapillary.com/update/2018/06/15/global-sign.html) has been deployed.
