### ISSUE TITLE
Ricoh Theta V / iOS - no Preview

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2785]
### Basic information
* Platform: iPhone 6, iOS 11.0.1, Mapillary 4.8.10, Ricoh Theta V

### Steps to reproduce behavior

 1. Connect iPhone to Ricoh Theta V via Wifi

### Expected behavior

iPhone should show a preview of the image

### Actual behavior

no preview, only a light blueish/greyish background

**Comment by millenbop** [comment]
Do you mean directly after you have connected the camera, or after you have started the capture?

We don't have a Theta V in the office so can't really test myself (and hence it's not officially supported).

**Comment by ramapongithub** [comment]
Directly after connecting to the camera. I can start capturing, thats no problem. But I can not check the orientation of the camera in the mapillary app. 

[This screenshot](https://www.pic-upload.de/view-34329259/IMG_1661.png.html) is how it looks.
The camera is connected (se the battery and maxImageCounter) but no preview is shown. On the phone there is also this "waiting"-ring-thing, but waiting does not help. I can start taking pictures (when GPS is green,  was inside when making this example), that is not an problem.

**Comment by habi** [comment]
BTW; The shown screenshot is exactly the same as I see here: https://github.com/mapillary/mapillary_issues/issues/2847

**Comment by millenbop** [comment]
Not exactly, it should show a preview image when the capture isn't started.

**Comment by habi** [comment]
Ok, I misunderstood the "work"-flow. Sorry for the noise.

**Comment by millenbop** [comment]
No problem @habi!

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
