### ISSUE TITLE
Ricoh Theta V / iOS - incorrect EXIF

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2786]
### Basic information
* Platform:  iPhone 6, iOS 11.0.1, Mapillary 4.8.10, Ricoh Theta V

### Steps to reproduce behavior

 1. Connect iPhone to Ricoh Theta V via Wifi
 2. Start Sequence with external camera.
 3. Take pictures (while moving).
 4. Download pictures via USB to PC.
 5. Check EXIF-Data

### Expected behavior

Different EXIF-Data in the different pictures

### Actual behavior

All pictures include the same EXIF-Data from the start of the Mapillary app. This means Latitude, Longitude, Time and Elevation.
The same EXIF-Data is in the pictures even when a new sequence was started. Only an restart of the app will update the data, but only for the first picture, next pictures have the same data.

### Additional information

It seems the upload of the GPS-Info via the OSC API does not work. Automatic triggering is working. I now have 2000+ pictures to syncronise with the track from the GPSR.

**Comment by ramapongithub** [comment]
I think I was wrong with the assumption the Mapillary app updated the GPS coordinates on the camera on restart. I used the Theta app in between to change settings and then restarted the Mapillary app. This changed the coordinates on the camera. Only ending and restarting the Mapillary app did not have this effect.

**Comment by millenbop** [comment]
Thanks for reporting. I'm not really following so please help me understand better.

"the Mapillary app updated the GPS coordinates on the camera on restart." 

The Mapillary app doesn't change the GPS coordinates on the camera. It does however write EXIF information into the images when they are transferred to the Mapillary app.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
