### ISSUE TITLE
Ricoh Theta V / iOS - no Download to iPhone

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2787]
### Basic information
* Platform: iPhone 6, iOS 11.0.1, Mapillary 4.8.10, Ricoh Theta V

### Steps to reproduce behavior

 1. Connect iPhone to Ricoh Theta V via Wifi
 2. Go to Upload-Page
 3. Mapillary app detects the Rico Theta and asks, if to download the pictures.
 4. Answer "Yes".

### Expected behavior
Download the pictures to iPhone.

### Actual behavior
The download seems to start, but after around 20 seconds there is a message "Download completed". Afterwards there is no picture on the iPhone. On the camera are 2000+ pictures (checked via USB-connection from PC).

**Comment by millenbop** [comment]
Thanks for reporting!

I'm a bit puzzled. In this thread https://github.com/mapillary/mapillary_issues/issues/2786 you are saying that the EXIF is not correct, which means you have transferred the photos, I'm I correct?

You can only transfer the photos once, this is to avoid duplicates.

**Comment by ramapongithub** [comment]
Okay, thats a bit puzzling. The two Issues are connected.
As I could not download the pictures from the camera to the iPhone there was no way to add the EXIF-Data to the pictures on the phone.
 As next step i downloaded the pictures from the cam to a PC via USB. My assumption was, that the Phone sends the coordinates to the camera (while taking pictures) and then the camera stores them as EXIF in the picture. But that was not the case.
In the end i also downloaded the JSON files from the iPhone via iTunes, extracted the coordinates with the json2GPX.py-script an wrote the coordinates to the pictures with exiftool. Then I uploaded the pictures via script.

Some more technical info: The camera writes an pair of coordinates to the pictures. But this is the last coordinate the camera has received via the WIFI connection.
I assume this is done with the OSC-API by the function camera.setOptions and the Option gpsInfo.
So when i use the ThetaS-app to check the orientation of the camera before using the Mapillary-app the ThetaS-app sends the actual coordinates to the cam. The coordinates are stored there and written to all pictures taken with the Mapillary-app afterwards.
In my opinion the Mapillary-app should send the coordinates via the OSC-API before sending an camera.takePicture command. Then the correct coordinates should be stored in the pictures.

**Comment by millenbop** [comment]
Ah didn't know you could override the GPS on the camera.

We don't do that currently. Basically all we set on the camera is the time/date, the capture mode, and also disable power-off.

This is how the transfer works, in short:

1. Check if there are any json files stored locally in the app for external cameras
2. Look for external cameras
3. Ask if user wants to transfer images
4. Download a list of all files on the camera
5. Check if the file already exists or has been transferred before, this is done using the filename
6. If the file hasn't been downloaded, download it
7. Get the time/date from the image, and find two json files, one before and and one after
8. Interpolate the position using these two json files
9. Write the json data + position to the image in the description tag and save the image locally

So if it doesn't transfer your images, it's either because you have already transferred it (there is a filename match in history.json), or there is a file with the same name.

Could you list the contents of the "/cameras" folder in the app (from iTunes)?

**Comment by ramapongithub** [comment]
The pictures weren't transfered in the first try. As described, everything seemed ok. The camera was found, the app asked if i wanted to do download the pictures from the cam, i answered "yes" and the download started. After around 20 seconds the app reported the download as ready. But no pictures were on the phone. Second and third try ended with the same result.
In iTunes there is an subdirectory below \cameras named \00117890. That is the same number as shown in the app for the camera. In this directory are JSON-files, one for each picture.
I downloaded the JSON-files (after I tried to download via phone, so something may be changed in them) and used them to correlate the pictures to the coordinates and write the EXIF to the pictures.

Attached the content of one of the JSON-files. (MAPSettingsUserKey changed)

`{
  "MAPGpsTime" : "2017_11_04_10_01_15_094",
  "MAPVersionString" : "4.8.10 (260)",
  "MAPLatitude" : 49.526321883359479,
  "MAPCalculatedHeading" : 261.66238403320312,
  "MAPCaptureTime" : "2017_11_04_10_01_15_653",
  "MAPDeviceModel" : "RICOH THETA V",
  "MAPSettingsUserKey" : "XXXXXXXXX",
  "MAPSettingsProject" : "",
  "MAPSettingsTokenValid" : "1",
  "MAPAltitude" : "417.331154",
  "MAPGPSAccuracyMeters" : "5.000000",
  "MAPLocalTimeZone" : "Europe\/Berlin (MEZ) offset 3600",
  "MAPPhotoUUID" : "881E5A2E-05F0-488C-91B2-448BD03297DF",
  "MAPDirection" : 5,
  "MAPLongitude" : 8.7825156468979841,
  "MAPDeviceName" : "00117890",
  "MAPSettingsUploadHash" : "288f0fd971ed56838fe06d71bb7d07b4f263b3e8e0276f75d3b5b2fa17906e51",
  "MAPDeviceMake" : "RICOH",
  "MAPSequenceUUID" : "B51951B6-6E0B-4184-A680-F83DF43D401B",
  "MAPCompassHeading" : {
    "TrueHeading" : 263.05892944335938,
    "MagneticHeading" : 260.66372680664062,
    "AccuracyDegrees" : 25
  }
}`

**Comment by millenbop** [comment]
What does the history.json contain?

**Comment by millenbop** [comment]
And thanks for helping debugging btw :)

**Comment by ramapongithub** [comment]
> What does the history.json contain?

No history.json at all.

Just re-downloaded the complete directory tree via iTunes.
In \camera are 3 subdirectories: \intern, \iPhone and \00117890
\iPhone is empty, \intern contains some json from 2016 (probably downloaded pictures to pc and uploaded them via PC) and in \00117890 are the json-files for the pictures (filename-example: 2017_11_03_18_39_40_794.json). No history.json.

In addition there is an directory \local with two files: featureFeed and userUploads.
And some emty directories from last weekend like 2017_11_20_10_41_00_992. This were pictures taken with the iPhone-camera and uploaded directly from phone.

> And thanks for helping debugging btw :)

If you can working something out with this, I am happy to report ;)
It was a first test for me with this camera, borrowed it from the workplace.
I will try to test it again. Maybe i can recreate the behavior and make a video or something of it.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
