### ISSUE TITLE
web uploader doesn't honour Orientation Exif tag

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2788]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox`

### Steps to reproduce behavior

 1. Take a photo
 2. Change it's Orientation Exif tag with a tool (e.g. exiftool)
 3. Upload with web uploader
4. Click on the marker on the map

### Expected behavior

Photo miniature correctly rotated

### Actual behavior

Photo miniature rotated uncorrectly (very annoying if you have to review the position)

**Comment by gyllen** [comment]
@nickplesha  I can't see why we wouldn't adhere to Orientation tag change

@Alessandro-Barbieri Can you provide us with an example image?

**Comment by Alessandro-Barbieri** [comment]
The image
![tt_img_00016](https://user-images.githubusercontent.com/10689739/32605439-b3c7a782-c551-11e7-860c-8385d88200da.jpg)

what's happening

![screenshot-2017-11-9 mapillary - street-level imagery powered by collaboration and computer vision](https://user-images.githubusercontent.com/10689739/32605435-b07d5eaa-c551-11e7-9d25-2f43b001ab14.png)

**Comment by Alessandro-Barbieri** [comment]
Github too is wrong
On map is correctly shown: lsWlSt4a6bhPLnWblI2-GQ

**Comment by nickplesha** [comment]
@Alessandro-Barbieri I'm seeing the same direction in the EXIF as in the uploader
![exif](https://user-images.githubusercontent.com/3823786/32606926-59caa026-c557-11e7-8de9-152099ab6d00.png)

(the same as this one: https://www.mapillary.com/app/?pKey=lsWlSt4a6bhPLnWblI2-GQ), is this the correct value?

**Comment by Alessandro-Barbieri** [comment]
@nickplesha 
`Orientation` and `GPSImgDirection` are not the same thing

**Comment by nickplesha** [comment]
Aha, was so busy looking a the compass I didn't even notice that the trees are upside-down! 😄 
Unfortunately, we don't apply the `Orientation` tag in the uploader but we're able to rotate images on request (making rotation changes through the website is coming in the future). So, please upload images as they are and let us know so we can rotate them to their correct orientation.

**Comment by Alessandro-Barbieri** [comment]
@nickplesha since I have to re-upload 10k images with this issue (because of bad sync between photo time and gps time), do you prefer that I upload the image without a `Orientation` set and then requesting rotation in the google sheet?

**Comment by nickplesha** [comment]
@Alessandro-Barbieri Yes, please let us handle the rotation and upload the images as they are.

**Comment by Alessandro-Barbieri** [comment]
So a wontfix?

**Comment by nickplesha** [comment]
The option to create rotation edits is coming to the editor in the future to handle this exact situation. The uploader will remain as is for the time being, focused only on getting the images in the system.
