### ISSUE TITLE
approval wrong date

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2789]
After editing compass values online, I got this notification:

> Edit 2
> Position changes: 0
> Compass Angle changes: 682
> Edited by: @baliano
> Approved by: @system
> Requested on: 2017.11.07
> Approved on: 1970.01.01

Same with Edit 1

**Comment by gyllen** [comment]
@peterneubauer Seems like date is way off here

**Comment by Alessandro-Barbieri** [comment]
After some time the date shown is now correct

**Comment by gyllen** [comment]
@Alessandro-Barbieri Ok closing this then, we will not handle this in a foreseeable future
