### ISSUE TITLE
Object Tagging: OK/Cancel-Button is below navigation buttons

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [mapillary/mapillary_issues#2792]
### Basic information
* Platform: `Web`
* Version: as of 2017-11-10
* System/Browser: Firefox 56.0 (64-bit)

### Steps to reproduce behavior

 1. Log in. 
 2. Open an Image that is connected to other images.
 3. Choose the Tag Editor from the right side.
 4. From the left side menu, select a tag.
 5. On the image, select a region. In the bottom-center there is the box with (OK/Cancel) icons. Select the region such that the OK/Cancel-Box lies on a place where a navigation bar is located (i.e. "move foward", "turn left").

### Expected behavior

The OK/Cancel box is on *TOP* of the Navigation box, because I'm currently in that dialog.

### Actual behavior

The OK/Cancel box is below. If I try to hover over it, the Navigation tool gets highlighted (blue shine around it). If I click, the navigation is executed, my tag is lost, and I'm on a different picture. I have no chance to create the tag.

Below screenshot was taken from this example URL:

https://www.mapillary.com/app/tag?lat=47.82519221305705&lng=11.300919055938408&z=19.841258874558076&focus=photo&pKey=xTENy05ckhHJWybZ1QT9cw

![label-z-index](https://user-images.githubusercontent.com/1111039/32659385-ceb4eb18-c61e-11e7-8702-380ca2fc9e08.png)

### Additional information

...

**Comment by katrinhumal** [comment]
@oldschoolBavarianReferenceSystem Thanks for raising this! Would it help you to hide the navigation arrows for the time of creating the tags? You can toggle them on and off by hitting the Shift key (see the tooltip displayed at the bottom of the screen in your screenshot).

**Comment by oldschoolBavarianReferenceSystem** [comment]
@katrinhumal Thanks. Yes that helps! Another solution I found is to pan the image, because the OK/Cancel-Button moves with the image, but the navigation buttons are fixed to the screen.

**Comment by katrinhumal** [comment]
That's great! 👍 Closing then.
