### ISSUE TITLE
Tag for no longer existing objects

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [mapillary/mapillary_issues#2793]
### Basic information
* Platform:  `Web`

### Expected behavior

Reality changes over time. Images on Mapillary stay fixed indefinetely.

 While tagging, I noticed that on one image, there is an object that I can truly tag as `Post Box`. While the tag on the image is infinitely valid, in reality there is no longer a post box and I want to indicate to fellow mappers that reallity changed.

I want a tag or an "adjective" describing a tag further that a specific object or building is no longer there.

Other kind of meta-tags or "adjectives" to tags are possible, like *temporarily*, *closed*.

**Comment by katrinhumal** [comment]
@oldschoolBavarianReferenceSystem Thanks for the request! I believe I understand what you're trying to solve. We are still working out a system for how to make sure the available tag set is useful to our users so while we won't offer an instant fix here, we'll make sure to consider your use case as well. Ideally, if the location has changed, you would capture new imagery there, which then will (or won't) have the up-to-date tags.

**Comment by oldschoolBavarianReferenceSystem** [comment]
@katrinhumal Thanks, I will be patient. And yes, I should go out more often and take new photos :-)
