### ISSUE TITLE
Web: problematic infinity scroll

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2794]
The website has a nice feature, in the profile sidebar an infinity/endless scroll shows the thumbnail list of uploads. Five thumbnails are shown (depending on the screen size) and while you scroll down, more are loaded from the server. This works really nice to scroll back the last 100-or-so uploads.

However, going back further gets really tedious really quick. There are no interface elements, the only way to go back is using the scroll function of the mouse. There is no scroll bar, there is no keyboard access.

Adding to this, apparently list elements that have scrolled out of view are not being destroyed, causing the list to use more and more resources the further you scroll back. Scrolling back more than 2 months on my list causes the whole page to become unresponsive.

Here is my suggestion for a solution: make the list of uploads follow the same filter that is applied to the map. That is, when a date range is set on the map filter, only uploads of sequences within that date range are shown in the thumbnail list.

**Comment by gyllen** [comment]
@angelday UX suggestion ^^^

**Comment by angelday** [comment]
> make the list of uploads follow the same filter that is applied to the map. That is, when a date range is set on the map filter, only uploads of sequences within that date range are shown in the thumbnail list.

Good idea! We need to think about the discoverability though.

**Comment by angelday** [comment]
@pbb72 Thanks for the suggestion, I added to our internal ticketing system – I'll let you know if we're ready to improve the upload sidebar. Meanwhile closing this.

**Comment by pbb72** [comment]
I'm not completely sure I understand the policy for closing issues. I thought these should be closed when the issue was fixed, not when it was accepted?

This way, other users that are struggling with the same problems, won't find this issue because closed issues are not shown or searched by default.

**Comment by Alessandro-Barbieri** [comment]
Yes, very annoying
