### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2796]
* `Letterbox`

Missing pendant to `Mailbox`, might be useful to postal and parcel services.

* `Street Name Sign`

Although in some countries street name signs are qualified as traffic signs, it may be a good idea to have them tagged separately for OCR (similar to `Traffic Sign - Direction`).

**Comment by katrinhumal** [comment]
@GITNE Thanks for pointing these out! We're figuring out the best way to maintain and expand the tag system in the future. That regards handling both completely missing tags as well as synonyms to existing tags.

**Comment by GITNE** [comment]
Right. However, expanding may perhaps not be necessary, if you define synonyms and super set terms in the documentation, for example like `Traffic Sign - Symbol` or `Traffic Sign - OCR`. Or, in case of OCR you could resort to a simple `OCR` tag only but then of course you would loose the traffic sign semantic.
In any event, it may be a good idea to document a list of coded synonyms (e.g. `Static` → {`Barrier`, `Block`, `Bollard`, `Wall`, `Fence`,…}) and natural language synonyms, e.g. `Mailbox` → {Letterbox, Postbox}.

I bring up this because I have been tagging traffic signs but have had to leave out street name signs, which is a pity because street name signs are a natural candidate for OCR. And, because manual tagging is quite costly I am not going to revisit those images. In fact, any manually acquired data is very precious. Hence, it should be paramount to optimize for it.

**Comment by katrinhumal** [comment]
@GITNE great input, thanks! We'll definitely consider these points as we work out the solution.

**Comment by GITNE** [comment]
Please forgive my ignorance but I have just discovered the `Text` tag. Would it make any sense to tag street name signs with the `Text` tag? Or, would it be better to wait for a special tag which includes the *sign* semantic?

**Comment by katrinhumal** [comment]
@GITNE no ignorance to forgive! Good question - I checked with the CV team and this is not the best one for that purpose. We'll look into adding an appropriate tag for this.

**Comment by GITNE** [comment]
> I checked with the CV team and this is not the best one for that purpose.

@katrinhumal Alright, thank you for the clarification. :smiley: So, for the time being I will refrain from tagging with `Text` and tagging street name signs.

**Comment by katrinhumal** [comment]
@GITNE it's here! 🎉  

<img width="226" alt="screenshot 2017-11-29 13 43 13" src="https://user-images.githubusercontent.com/16334352/33375789-5c9ad276-d50b-11e7-950c-861c44b0e6b7.png">
