### ISSUE TITLE
ios app - tagging & upload icons turn into questionmarks

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2797]
### Basic information
* Platform: `iOS`
* Version: `4.8.10`

### Steps to reproduce behaviour

 1. take some photos
 2. start uploading them

### Expected behaviour

tagging & upload icons are either dimmed or disappear

### Actual behaviour

tagging & upload icons in upper left & right turn into inoperable question marks

**Comment by millenbop** [comment]
I'm having problems reproducing it, but I did see it once. I have moved around some code so hopefully that's enough. This code hasn't changed in a long time though.

Let me know if it fixes your problem when the next release is out. Thanks for reporting.

**Comment by richlv** [comment]
i was going to comment on this issue, saying that the problem is still there - and then the app update changelog said "fixed question marks" :)
thank you for the fix (will pay closer attention on the next upload)

**Comment by millenbop** [comment]
Np! But sorry about the late release though!

**Comment by richlv** [comment]
still seeing question mark icons with 4.8.13 - this should probably be reopened.

**Comment by millenbop** [comment]
Yup me too, reopening!

**Comment by millenbop** [comment]
Ah missed to fix it for the state "disabled". Fixed now, will be available in the next release.
