### ISSUE TITLE
show where the exposure point is

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2798]
### Basic information
* Platform: `iOS`
* Version: `4.8.10`

### Steps to reproduce behaviour

 1. start taking photos
 2. tap anywhere in the image

### Expected behaviour

there's a visual indicator where the current exposure point is

### Actual behaviour

the square controls stay in the centre of the screen

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
