### ISSUE TITLE
ID's greater zoom at the new interface

### ISSUE THREAD

**Issue by alexandre-mbm** [mapillary/mapillary_issues#280]
This:

&nbsp;&nbsp;&nbsp;&nbsp;`www.openstreetmap.org/edit#map=`[**`21`**](http://www.openstreetmap.org/edit#map=21/-5.87400/-35.18160)`/-5.87400/-35.18160`

Instead:

&nbsp;&nbsp;&nbsp;&nbsp;`www.openstreetmap.org/edit#map=`[**`16`**](http://www.openstreetmap.org/edit#map=16/-5.87400/-35.18160)`/-5.87400/-35.18160`

[Image of this example](http://www.mapillary.com/map/im/RHeKgL9Gt4PaI9BoVgMFaw)

**Suggestions:** user's config or _n_ links (with a `-+` zoom selector).

**Comment by jesolem** [comment]
What should we fix here?

**Comment by alexandre-mbm** [comment]
This is not a fix but improvements:
1) customize the zoom at ID's URL
2) provide aid to JOSM users

**Comment by jesolem** [comment]
The links to iD and JOSM were updated in the latest viewer release. Zoom default is 14.

We're not doing the variable per user zoom. 
thanks @alexandre-mbm
