### ISSUE TITLE
Large sequence deletion

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2801]
### Steps to reproduce behavior

 1. Mark for deletion a >1k images sequence that you own

### Expected behavior

Sequence deleted after a reasonable time

### Actual behavior

Sequence still waiting for approval after a week or so

### Additional information

Please delete them, no bullshit, I got another user complaining about that bad photos.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for notifying, I've manually approved your edits now.

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal thank you very much

**Comment by katrinhumal** [comment]
No problem at all!
