### ISSUE TITLE
Web: Traffic sign detection - allow marking wrong detection on photos

### ISSUE THREAD

**Issue by majkaz** [mapillary/mapillary_issues#2804]
I have found it was at one time possible to mark wrongly detected signs in the photos. This is not a case any more.

Please, bring it in some way back. I would be happy to have a way to either to delete the recognized sign
or mark the whole photo as having wrong detection on it. Or is there a tag, which would result in the same? Meaning that the wrong traffic sign is sooner or later removed?

The detection fails on almost any big traffic sign (either overhead or beside the road) on trunk/primary roads, and there are even some parts of ads detected as traffic sign. For at least a year, there is no way to 
indicate this.
I am already manually correcting the compass directions in my photos and spending lot of time on the blur editor, I might as well spend the time on the traffic signs.

**Comment by katrinhumal** [comment]
@majkaz Thanks for your request and we really appreciate that you want to help with this! We're working on bringing more tools to the table for you to help correct false detections (and as you correctly note, this was possible before - just this old system didn't scale anymore with the amount of data in our system and the way we process it, which is why it's now taking us time to build new tools). Stay tuned for updates, and I will definitely share your feedback with the team so that they will know how much you (and others) are looking forward to this.

**Comment by majkaz** [comment]
Just a note - the detection seems to be getting more absurd with the time, I cannot remember to have such interesting mismatches before. 

[This](https://www.mapillary.com/app/?menu=false&focus=photo&lat=48.97852059998945&lng=14.493493899979853&z=16.451941083083053&dateFrom=2017-04-01&signs=true&ocr=true&pKey=c9GlrYXR-DLmNirsREX5FQ) is a recent photo, with a better photo quality than most of mine in past. Not sure, where the signs come from, on the marked part, there is nothing nearly similar to the detected signs. This [traffic light](https://www.mapillary.com/app/?menu=false&focus=photo&lat=48.97827459993192&lng=14.492327100029684&z=17&dateFrom=2017-04-01&signs=true&ocr=true&pKey=uEpwYoDAjC9OaZihP2wvuA) detected as a no stopping sign and the brake light of a car detected as one-way street on the same photo are interesting as well - more so that the "computer vision detections" seem to be spot on (traffic light & car).

Are you sure there isn't an AI somewhere in the process trying to get paid by a detected sign?

**Comment by ybkuang** [comment]
@majkaz we are working on improving the detections with more training data.  The false detections will be handled properly with more semantic information from the other detection cars/traffic light etc. 

Unrelated to the detection pipeline itself, there is also a mismatched between the sign template shown the website
![image](https://user-images.githubusercontent.com/5370656/33374636-48afa63c-d507-11e7-8b52-b8328bc51ac1.png)

The no parking sign with red circle is supposed to be represented as 
![image](https://user-images.githubusercontent.com/5370656/33374722-88553d6a-d507-11e7-92c1-93aa8728b24c.png)

Nevertheless, it is a false detection. This will be taken care of in the traffic sign updates.

**Comment by katrinhumal** [comment]
This should be improved with the latest traffic sign update: https://blog.mapillary.com/update/2018/06/15/global-sign.html.
