### ISSUE TITLE
Android 3.108 doesn't release GPS listener

### ISSUE THREAD

**Issue by iandees** [mapillary/mapillary_issues#2805]
### Basic information
* Platform: `Android`
* Version: `3.108` 
* System/Browser: `Google Pixel XL, Android 8.0.0`

### Steps to reproduce behavior

 1. Open Mapillary app
 1. Switch to Capture mode
 1. Begin capturing
 1. Stop capturing
 1. Hit back button to leave Capture mode
 1. Leave the app by pressing home button (or by hitting back button again and exiting the app)

### Expected behavior

App should release GPS listener so that the phone turns off GPS.

### Actual behavior

App does not release GPS listener, phone leaves GPS on. The only way to get the app to release the GPS is to force quit the app by showing the multitasking list and swipe the Mapillary screen to the side.

### Additional information

I notice that the app correctly releases the GPS listener if you don't start capturing after entering Capture mode.

**Comment by ovivoda** [comment]
@katrinhumal Please ask the user to try the v3.112 the beta version from googlePlay or the apk from here: 

http://android-releases.mapillary.io/Mapillary_Android_v3.112-BETA.apk

**Comment by iandees** [comment]
Looks better. Thanks!

**Comment by HolgerJeromin** [comment]
Yeah. Thanks a lot
