### ISSUE TITLE
11 October glitch ?

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2806]
### Basic information
* Platform: `iOS` 
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Uploaded Capturing via IPhone

### Expected behavior

Should be Visible in the next Day (24h)

### Actual behavior

Took from 11-oct until today to get a mail , that this sequence is now online
and on the WebBrowser upload tap, i see multible uploads with only counting 1 picture, but shows
up couple time (3-4) .. maybe a Glitch ...

Still missing couple route, that i captured on 11-oct (13:24 to 14:18 that day) 

### Additional information

![image](https://user-images.githubusercontent.com/10342344/33078731-e16149ec-ced3-11e7-8548-53ce796db8f1.png)

**Comment by thoschu96** [comment]
Seems to be Fixed.. Today i can see the Pictures

**Comment by katrinhumal** [comment]
@thoschu96 thanks - good to close the issue?

PS you can now check up on processing times at status.mapillary.com ;)

**Comment by thoschu96** [comment]
@katrinhumal yes, all seams to be good now
