### ISSUE TITLE
Android-App needs to open mapillary links/intents

### ISSUE THREAD

**Issue by utack** [mapillary/mapillary_issues#2807]
### Basic information
* Platform: Android

### Steps to reproduce behavior

Click a link in the Mapillary newsletter, the browser is the only thing that will open it
Click "share" menu in a browser on the mapillary website. The app is not listed to open it

### Expected behavior

The app opens links/intents from mapillary.com and jumps into browsing mode to the right location

### Actual behavior

The app can not receive mapillary links

**Comment by utack** [comment]
Perfect  
Somehow Osmand already knows how to start mapillary with a photo linked, so the infrastructure must be ready?

**Comment by utack** [comment]
I think you would also need to rework newletter links, they are using some odd "sendgrid" link that the app could never catch.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
