### ISSUE TITLE
Track-order in WEB-UI is not detected correctly

### ISSUE THREAD

**Issue by tbaum** [mapillary/mapillary_issues#281]
![image](https://cloud.githubusercontent.com/assets/91751/3917271/5c501790-2389-11e4-808a-2f9790db3647.png)

sample-files in this [archive](
https://gist.github.com/tbaum/3d6b6893c38a88b82be4/raw/c0296b03f4859275ba35f03d8e42117c054083a8/538B234C-0293999707...0312999688.zip)

**Comment by gyllen** [comment]
This should now be fixed with new manual upload
