### ISSUE TITLE
Links to sequences broken on the forum

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#2810]
See https://forum.mapillary.com/t/links-to-sequences-broken-on-this-forum/1330

### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `Windows 7/Firefox, Chrome, Opera, IE`

### Steps to reproduce behavior

I've posted this URL into the forum message:
https://www.mapillary.com/map/im/ivg5YBQHHBqbBvJROd53RQ

In my browser this URL is redirected to:
https://www.mapillary.com/app/?focus=photo&pKey=ivg5YBQHHBqbBvJROd53RQ&lat=52.17451892281838&lng=5.446230766474969&z=17

This URL is working.

However, the forum software converts the URL to this link:
https://www.mapillary.com/app/?focus=photo&amp%3BpKey=ivg5YBQHHBqbBvJROd53RQ&lat=20&lng=0&z=1.5

It does not show anything but an empty map.
If you remove amp%3B from the link above, it works.

**Comment by gyllen** [comment]
@martinskans Can we do anything about the encoding here on posted links?

**Comment by martinskans** [comment]
It seems to be a known problem within something used by the discourse forum software. They had a long discussion here that didn't seem to end in anything useful:
https://meta.discourse.org/t/onebox-incorrectly-encodes-urls/61542

I need to look into if I can find a useful workaround (maybe disabling the preview box that seems to cause the issue or something).

**Comment by ligfietser** [comment]
Thanks @martinskans for looking into it. Better get rid of that preview box if that does not produce a working link!

**Comment by martinskans** [comment]
It is disabled now!

I replied to the thread you made and it seems to work without the preview box, but just to be sure go ahead and test it yourself. There are cases when something seem fixed but aren't.

Sadly, I can't fix already posted messages easily, but at least new posts will benefit from the fix.

**Comment by gyllen** [comment]
@martinskans Thanks for fix, Im closing this issue
