### ISSUE TITLE
Freezes image-taking (responsive to the Back button and other functions)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2812]
### Basic information
* Platform: Android 7.0, AT&T baseband version QJ2
* Version: Mapillary ver. 3.112
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Begin shooting sequences.
 2.  Watch as the app simply "freezes" image taking after a random number of pictures (sometimes just a dozen, sometimes 1 or 2 hundred)
 3.  Back out of Camera mode (which can take many seconds, I've timed it as long as 2 minutes), go back in, try again.

### Expected behavior

The app should continue to shoot images without lengthy pauses.

### Actual behavior

Image taking simply stops.

### Additional information

I will also note that sometimes, it would appear to have stopped taking images for many seconds, then suddenly I'd see the image count jump by 5, 10, 15, or more.

Other times, I would let it sit for several minutes with no noticeable on-screen change in the app.

Several of the sequences that were affected by this appear to have cut-off images (the top part is there, but the bottom part of the image is black).  I'll get them uploaded starting sometime Tuesday--yes, the bad ones--and then add a comment with the sequence numbers.  If you want a copy of the files from my phone BEFORE uploading, please let me know so I can copy them off.

According to the app, I have 17,104 images in 125 sequences on the S7 right now.

After several frustrating attempts to get the app to take a sequence without freezing, I gave up on the S7 and ran Mapillary on my S5 (which had very few Mapillary images on it when I switched).  It ran fine, and I didn't notice any issues.

The S5 is running Android 6.0.1, and does not have Camera2 API capability, which might (or might not) be a factor here.

**Comment by echeloni2p** [comment]
Hey

yeah, try to use the old camera API, in the settings.
Some companies do not release stable software., esp. camera aoftware tends to break often.
Looks a bit like a samsung bug in APIv2, try APIv1.

echelon

**Comment by jfburke3** [comment]
@echeloni2p I'm not sure it's the API's fault.  My subjective perception is that it works fine until the image count (or maybe the sequence count?) starts to get high.  Either that, or some of the additional processing or threads that are running in the background while images are being taken, are part of the problem (ref. my other Github about GPS accuracy problems #2692 ).

I'll try APIv1 with the high image/sequence count before uploading, though, just to see.

**Comment by echeloni2p** [comment]
Hey

All I can tell: with android 6/7/8 Mapillary works on my android mobiles quite steady and stable with APIv1, on some it does not work in APIv2. [but I do not use samsung at all]
And thats a true sign of a bad API. So try APIv1.
And yeah, not a single mobile producer testing their API for a steady use like mapillary does it, it is all untested and broken. your symptoms (break if a number of pictures are taken) is a classical issue of memory usage error or alike and is mostly broken in the API (which is made by samsung, as they adopted android far to much to their style, not good at all).
So: please try APIv1 and report back to samsung their modified android is broken for taking a lot of pictures in a row.

echelon

**Comment by voschix** [comment]
After a period of relative peace on this front, this problem is now back with a vengeance on my Xperia Z5, Android 7.1.1.  and Mapillary 3.112, Version code 412
I have not seen damaged photos, and it had worked nearly fine for a while.

**Comment by jfburke3** [comment]
@echeloni2p I'm going to run in APIv1 all weekend and see what happens.

@voschix Unfortunately, I do have some damaged photos.  While I don't stop driving and check sequences immediately after it happens in order to verify that "sequence Y" was damaged due to the problem, I definitely have some damaged ones.

**Comment by jfburke3** [comment]
I started the day with Mapillary using APIv1. Before an hour was up, I'd switched back to APIv2, because the performance with v1 was pretty lousy. Build 3.113-SNAPSHOT that @ovivoda cooked up did very well with APIv2--a significant improvement over the last few releases.

**Comment by jfburke3** [comment]
I have to note that I have had the chance to give this build a good workout, and have had several instances of this problem recur.  The build does seem to help other problems, though, that I have noted on their GitHub cases.

**Comment by jfburke3** [comment]
I've emailed in the trace logs.

The subject has this GitHub issue  number in a. 

Note: the Mapillary version is the 3.113-SNAPSHOT 4 apk that  Ovivoda provided in another case. The About info and the log says SNAPSHOT 2.

**Comment by echeloni2p** [comment]
Hey
just use apiv1, depsite the ressource usage. It is nothing mapillary can fix, if the API is broken.
Contact your mobile device producer and ask there for a bugfix. Really. Which is samsung in this case. With a 7s you got more than enough power in the mobile to use APIv1.
Even my cheap honor 7 did 7k pictures with one battery in 2h time.

echelon

**Comment by jfburke3** [comment]
Has it been confirmed that it's an API problem?  Or are you just saying that?

**Comment by echeloni2p** [comment]
Hi
All I can tell: if the APiv2 did not work on my mobiles, using APIv1 did work flawless.
Prooving it to be the APIv2 and telling the manufacturer to bug hunt takes more work than using APIv1.
Esp. as taking more than a few pictures in a row is not a test case any manufacturer has on the list.
Sure, it can be mapillary app, but as long as it works in APIv1, I´ll take the chance of a crappy v2 API and use the old one. No real negative side effects so far in using old API on taking pictures. Maybe a bit more battery usage, but thats fine.

**Comment by davebrny** [comment]
i havnt noticed any lagging once it starts capturing photos, but on my xperia xz1 compact it will freeze for a minute or longer whenever i stop capturing. with my old z3 compact there is no problem at all for some strange reason so maybe its something different between android 6 and 8

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
