### ISSUE TITLE
Mapillary camera interface upside-down when phone rotated to the right

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2813]
### Basic information
Platform: Android 7.0, Androit 6.0.1
Version: Mapillary ver. 3.112 and many previous versions
System/Browser: Samsung Galaxy S7 Edge, Samsung Galaxy S5 Active
### Steps to reproduce behavior

 1.  Mount phone rotated to the right instead of left (that is, so the top of the phone is to your right)
 2.  Launch Mapillary
 3.  Enter Camera mode
 4.  Notice that while the image is right-side up, the Mapillary controls are all upside-down (as if it thinks the phone is rotated to the left)

### Expected behavior

The Mapillary interface should appear normal.

### Actual behavior

The Mapillary interface is presented as if the phone were rotated to the left.

### Additional information

Pressing the open-apps button displays a list of my open apps upside-down, too.  Opening one of them causes the display to revert to rightside-up, until I go back into Mapillary's camera mode again.

I would call this annoying, but not critical.  Would be nice to have fixed one day, but there are more important issues to get resolved, I think.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_

**Comment by ovivoda** [comment]
Same issue as 

https://app.zenhub.com/workspace/o/mapillary/mapillary_elva/issues/4067

@gyllen Should we close one or merge somehow?
