### ISSUE TITLE
Fixed focus at infinity, isn't (SGS 5, Android 6, Camera1 API)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2814]
### Basic information
* Platform: Android 6.0.1
* Version: Mapillary 3.112 (and likely earlier versions)
* System/Browser: Samsung Galaxy S5 -- note Camera2 API is NOT present for this phone

Summary:  The "fixed focus at infinity" setting isn't fixed.  It appears to try to autofocus.

### Steps to reproduce behavior

 1.  On a SGS5, go into Mapillary settings and enable Fixed focus at Infinity.  I don't think the official Android release matters.
 2.  Smear something on the windshield in front of the camera.
 3.  Shoot sequences.
 4.  Notice that they aren't often in focus on the street ahead.  Instead, they appear to be focused on the smear on the windshield.

### Expected behavior

Images should be generally in focus on the roadway.

### Actual behavior

Images appear to be out of focus for the roadway.

### Additional information

I'll post a sequence number of a relevant example once I have it uploaded.

**Comment by jfburke3** [comment]
Special note:  unless there's a super secret squirrel developer feature, Camera2 API is not available for the SGS5.  Samsung appears to have decided not to release that.

**Comment by jfburke3** [comment]
On a scale of 1 (high) to 5 (low), I'd call this a 3.  My two cents worth.

**Comment by jfburke3** [comment]
Example sequence using fixed-focus-at-infinity:

https://www.mapillary.com/map/im/x7sb13fwXuf0k8yJrldi7g

**Comment by Alessandro-Barbieri** [comment]
Confirm the issue with a Samsung Galaxy S5

**Comment by ejegg** [comment]
Confirmed with Galaxy S5 under LineageOS 14.1 (based on Android 7.1.2)

**Comment by ovivoda** [comment]
Please try this APK and let me know if this works better:

http://android-releases.mapillary.io/Mapillary_Android_v3.118-SNAPSHOT3.apk

**Comment by jfburke3** [comment]
I've installed that apk on my S5, but it will be tomorrow before I test it.

**Comment by jfburke3** [comment]
It seems to still have a focus problem.

**Comment by jfburke3** [comment]
This is definitely still a problem.  Currently running Mapillary app version 3.119 from the Play store.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
