### ISSUE TITLE
Webuploader: Images to be uploaded are not visible on Map; Upload impossible!

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2815]
### Basic information
* Platform: Web
* Version:
Mapillary Webuploader
* System/Browser:
Windows 10 v.1709
Google Chrome 62.0.3202.94  (64 bits) / FireFox Quantum 57.0 (64 bits)

### Steps to reproduce behavior

1. Webuploader
2. Browse Files
3. Select sequence for upload
4. Open

### Expected behavior

Images should show on Map by location and direction arrows

### Actual behavior

Images location, direction are NOT visible on Map

### Additional information

Images are being loaded: map is panning and zooming to show Images.
After [Review] Images still not visible on Map.
Images can be uploaded, but images (location and direction) cannot be verified (review) before upload.
Therefore Webupload is NOT OK / VERIFIED / ALLOWED !

Issue occured since November 27, 17:00 PM.
No issue before.

Trying to resolve:
- Ctrl + F5
- different BaseMaps
- different Webbrowsers
- different PC's
- last successful sequence (again)

No success.

![image](https://user-images.githubusercontent.com/20150550/33285867-dd89dda4-d3b3-11e7-924c-ffaf290019b4.png)

/ AnkEric

**Comment by AnkEric** [comment]
ToDay November 28, 07:20 AM same issue...

**Comment by nickplesha** [comment]
@AnkEric Thanks for reporting! You should be able to add images to the uploader now. Editing their position is still not working as we're working on fixing the changes brought on by the latest version of the map library we're using.

**Comment by AnkEric** [comment]
Thanks for this fix!
I guess _"working on fixing the changes brought on by the latest version of the map library we're using"_ means a lot of work?
I have reported some more issues. Possible not relevant, since these might be known issues.
But still: performance is a new issue. Waiting for 30 minutes now to load 1500 Images onto the Map, before Review can start... 661/1500... 
And then, during writing this comment: Finished, unexpectedly! Strange...

**Comment by nickplesha** [comment]
@AnkEric Yes, we're still working on an update for the webuploader to fix the map issues.

Performance while uploading can vary between browsers and depends on many factors. For example, in some browsers, tabs in the background are throttled to save resources and may slow down very noticeably.

Our upload scripts (https://help.mapillary.com/hc/en-us/articles/115001753465-Uploading-with-scripts) are great for large sequences as they don't face the same limitations as the webuploader.

**Comment by nickplesha** [comment]
@AnkEric The bug with the images on the map should be fixed now.

**Comment by AnkEric** [comment]
Thanks!
Speed is back to normal (both showing images on map and upload).
Upload of 1500 images (best practice limit) is OK: 1500 images in 30 minutes.
Also, Memory usage is released during upload: 600 MB > 900 MB > 600 MB > 700 MB. Which is also OK.
CPU is lower than ever before: < 10%. (Used to be up to 30%).
I used to Close Chrome between sequences (to release Memory), but now I succeeded in uploading two sequences in a row. Which is also OK.

One issue:
Images don't show up on the map by Image_Location_Dot and Image_Direction_Arrow.
Review, Deleting Images, Moving Images was one of the reasons for not using Python script.
But I do have a visual check on a sequence being more or less correct (location/timezone, connection to previous sequence, forgotten sequence, duplicate sequence upload etc.).

![image](https://user-images.githubusercontent.com/20150550/33950856-bb90dd84-e02d-11e7-8d35-913ae27aa55f.png)

**Comment by AnkEric** [comment]
In FireFox Quantum 57.0.2 (64 bits) Images are visible on Map (by Location and Direction)...!
Deletions and Move position is possible...!

![image](https://user-images.githubusercontent.com/20150550/33956003-a3f03e4e-e03d-11e7-95e4-a5a11c0c3ac8.png)

**Comment by AnkEric** [comment]
Now (just now?) Google Chrome 63.0.3239.84 (64-bits) is also OK!

Last issue closed! Thanks again...!

![image](https://user-images.githubusercontent.com/20150550/33956381-a33aa9d4-e03e-11e7-8a79-0491ae32d580.png)
