### ISSUE TITLE
Unexpectedly exits out of camera mode while shooting sequences

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2816]
### Basic information

* Platform: Android 6.0.1
* Version: Mapillary 3.112 (and likely earlier versions)
* System/Browser: Samsung Galaxy S5 -- note Camera2 API is NOT present for this phone

While shooting sequences on my S5 this weekend, several times it unexpectedly exited out of camera mode and went back to the home screen.  I was able to go back into camera mode and resume shooting sequences.

I'll try to get a trace log of this and send it in.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
