### ISSUE TITLE
Start Webuploader Upload: [Ctrl]+[F5] required (or not)

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2817]
### Basic information
* Platform: Web
* Version:
Mapillary Webuploader
* System/Browser:
Windows 10 v.1709
Google Chrome 62.0.3202.94  (64 bits)

### Steps to reproduce behavior

1. https://www.mapillary.com/app/
2. Profile...
3. Uploads (tab)...
4. Upload images...

### Expected behavior

Show: [Browse Files] dialog

### Actual behavior

Mapillary is "loading" and keeps "loading".
[Browse Files] dialog does NOT Open.

Press [Ctrl] + [F5] to Refresh and [Browse Files] dialog Opens.

### Additional information

1. https://www.mapillary.com/app/
2. Menu...
3. Upload
Upload starts OK: [Browse Files] dialog will Open!

![image](https://user-images.githubusercontent.com/20150550/33373067-8d920eea-d500-11e7-8a02-7b7cd9631601.png)

![image](https://user-images.githubusercontent.com/20150550/33373074-93d76a7a-d500-11e7-882a-e0569c70c0c4.png)

[Browse Files] dialog does NOT Open. [Ctrl]+[F5] does Open dialog.

![image](https://user-images.githubusercontent.com/20150550/33373087-a298e994-d500-11e7-84dd-64feadbcb460.png)

[Browse Files] dialog Opens. [Ctrl]+[F5] not required.

![image](https://user-images.githubusercontent.com/20150550/33373097-ad23d478-d500-11e7-9fbc-c5c5bfa3fc29.png)

**Comment by gyllen** [comment]
@nickplesha I think this is the same as clicking on setting cog

**Comment by nickplesha** [comment]
Yes, this is fixed now. Thanks for reporting!
