### ISSUE TITLE
Webuploader: Upload second Sequence of Images will not Refresh on Map (not visible)

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2818]
### Basic information
* Platform: Web
* Version:
Mapillary Webuploader
* System/Browser:
Windows 10 v.1709
Google Chrome 62.0.3202.94  (64 bits)

### Steps to reproduce behavior

1. https://www.mapillary.com/app/
Webuploader
2. Upload (images)...
3. Browse Files (dialog)
4. Open...
5. Review
6. Upload
7. Upload is finished
8. Close (dialog)
9. Browse Files (dialog)
4. Open...

### Expected behavior

New sequence of Images to be uploaded should show on Map.

### Actual behavior

However Map is NOT Refreshed.
Review is possible, but: which sequence of Images is Reviewed, to be Uploaded?
New sequence (not shown on Map) or previous sequence (still visible on Map)?

**Comment by katrinhumal** [comment]
@AnkEric We've made some fixes to the web uploader now - could you give it a try and see if the problem still persists?

**Comment by AnkEric** [comment]
Webuploader is OK now.
Even better than before: I can upload multiple sequences subsequently without Closing and Restarting browser and without issues or strange things happening.
Thanks for a good job well done!

**Comment by katrinhumal** [comment]
Thanks for reporting! Glad it works :)
