### ISSUE TITLE
Webuploader: performance issue to Open Images onto Map (before Review)

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2819]
### Basic information
* Platform: Web
* Version:
Mapillary Webuploader
* System/Browser:
Windows 10 v.1709
Google Chrome 62.0.3202.94  (64 bits) / FireFox Quantum 57.0 (64 bits)

### Steps to reproduce behavior

1. Webuploader
2. Browse Files
3. Select sequence for upload
4. Open: 1500 Images

### Expected behavior

1500 Images should show on Map by location and direction arrows within a couple of minutes.

### Actual behavior

First 100 Images will show fast, as normal.
Next 200 Images will show at a rate of 1 Image per Second.
Next 300 Images will show at a rate of 1 Image per 5 Seconds.
Status: 600/1500
Then, unexpectedly, all Images are ready for [Review].
Review: all Images shown on Map.
However: Map is frozen, very hard to Pan or Zoom.
Non-responsive. Webpage is Closed...

Next steps:
- Open 20 Images, is OK.
- Open 50 Images: "0/1491".
"1491"???
I have selected ±50 Images, not 1491!
And again: Non-responsive.

### Additional information

My guess:
I should wait for rework on Webuploader.
Now it is - almost (?) - impossible to Upload 1500 Images in one sequence.

**Comment by AnkEric** [comment]
IF using FireFox Quantum 57.0 (64 bits)
THEN Upload of Images onto the Map is in normal speed. No issue! [Review] for 1500 Images can start after one minute!
However: Images are NOT visible on the Map!! Which is an issue!
I don't prefer to upload not reviewed Images. Also: my current sequences to be uploaded require Deletions.

Still wondering:
Is this MY issue? MY Problem? Has the issue been reproduced by others? Or by @Gyllen?

**Comment by GITNE** [comment]
> Still wondering:
> Is this MY issue? MY Problem? Has the issue been reproduced by others? Or by @gyllen?

I am observing the same issue on Linux with a pre-*Quantum* Firefox browser. After selecting files for upload, and the sequence builds up for review, with every additional image the processing becomes slower and slower. When the counter hits about 400 images the uploader becomes **unusable** and **unresponsive**.

Additionally, WebGL rendering glitches become visible. Some images simply lack the green camera dot. Upload still works but true review and editing becomes impossible. This issue is a **blocker**!

**Comment by AnkEric** [comment]
Thanks @GITNE.
Not my problem anymore. However: I have still 200K Images to be uploaded...

**Comment by GITNE** [comment]
@gyllen After some further testing I have discovered that culprit may be a WebGL rendering issue, a memory leak (or object allocation runaway), or both. If I select 1k or more files and then switch to another tab, the green sequence builds up with usual speed, only limited by network request latency caused by adjusting the map on every next image. But, when I observe Firefox’s `VIRT` and `RES` memory usage in `top` (one instance with Mapillary webpage only) I see about 8GB of virtual and 4GB resident memory. And, Firefox’s resident memory consumption keeps growing. This clearly indicates either a memory leak or an object allocation runaway situation.

**Comment by GITNE** [comment]
If you switch to a raster tile map the web uploader performs reasonably well again. Apparently, Mapbox’s vector map is the true culprit here. :disappointed: And, although the raster map is actually handled as a texture on simple polygons, which still uses WebGL, the drawing complexity is vastly lower than that of the current vector map implementation.

It looks like Firefox users are left with nothing else than switching to raster tile maps as a workaround for now.

**Comment by gyllen** [comment]
@nickplesha See valuable feedback for webuploader ^^^

**Comment by nickplesha** [comment]
Thanks for the detailed info! We're working on some updates for the uploader related to the map that will fix some reported bugs and improve performance.

While using the webuploader the performance and "maximum" number of images depends on the browser as we don't have a great deal of control how they manage memory allocation and their Javascript performance.

For uploading thousands of images without depending on the browser I suggest looking into our upload scripts: https://help.mapillary.com/hc/en-us/articles/115001753465-Uploading-with-scripts

They are command-line tools but can handle any number of images.

**Comment by GITNE** [comment]
> While using the webuploader the performance and "maximum" number of images depends on the browser as we don't have a great deal of control how they manage memory allocation and their Javascript performance.

@nickplesha True, however even a few thousand images should not be a problem for any web browser to handle, and also despite the fact the UI is rendered in WebGL. :wink: But, we understand that you cannot optimize for every browser.

> For uploading thousands of images without depending on the browser I suggest looking into our upload scripts: https://help.mapillary.com/hc/en-us/articles/115001753465-Uploading-with-scripts

@mapillary The problem for me, and probably also other people with these Python scripts is that for example they do not handle proxies. They also pre-process images in a strict fashion, hence they modify the files prior to upload while many people do pre-processing themselves and would actually rather like to just push them to the backend. AFAIK, the scripts do not enable you to just upload transparently to the backend. So, these are some of the reasons why an upload API would be much more helpful in these scenarios. Having an open upload API enables people to adapt their workflow (including uploaders) to Mapillary’s workflow.

**Comment by gyllen** [comment]
@GITNE These are wise words and as we discussed in another issue we should think long and hard about the new upload API. I might run the spec with you before we implement.

**Comment by AnkEric** [comment]
@GITNE, @gyllen,

Issue seems to be resolved. Wepuploader (and ankeric) are back in business...

See: **Webuploader: Images to be uploaded are not visible on Map; Upload impossible! #2815** 
[https://github.com/mapillary/mapillary_issues/issues/2815](url)

**Comment by gyllen** [comment]
@nickplesha We can close this now right?

**Comment by richlv** [comment]
a bit offtopic, but upload_with_authentication.py should allow uploading images w/o any additional processing.

proxies... i think setting the `http_proxy` variable using the standard syntax like `http://proxy:port` should work, but it's been some time since i've needed that.
