### ISSUE TITLE
Webuploader: button "Publish <x> uploaded" visible during Upload in Progress ???

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2820]
### Basic information
* Platform: Web
* Version:
Mapillary Webuploader
* System/Browser:
Windows 10 v.1709
Google Chrome 62.0.3202.94  (64 bits) / FireFox Quantum 57.0 (64 bits)

### Steps to reproduce behavior

1. Webuploader
2. Browse Files
3. Select sequence for upload
4. Open
5. Review
6. Upload Images...

### Expected behavior

Images should be uploaded, counter will be visible.
Once all Images have been uploaded: [Publish] <n> Images

### Actual behavior

A new (?) button is visible: 
- "Publish 7 uploaded"
- "Publish 20 uploaded"
- "Publish 30 uploaded"

![image](https://user-images.githubusercontent.com/20150550/33376419-e3468390-d50d-11e7-825a-4d757b046b95.png)

If (!) I hit "Publish 30 uploaded" next Dialog will be shown:
"33 files have been published for processing".

![image](https://user-images.githubusercontent.com/20150550/33376424-eac371b4-d50d-11e7-888d-5fd4cb89b3eb.png)

And showing progress...
"54 files have been published for processing".

![image](https://user-images.githubusercontent.com/20150550/33376434-f075f91a-d50d-11e7-9fd0-3a6f514c9b5c.png)

What will happen if I hit [X] ???
Will upload be cancelled ???

### Additional information

Assumption: I should not have seen "Publish <x> uploaded" button?
This was a one time only incident???
Didn't see it during next - small - upload.

**Comment by katrinhumal** [comment]
@AnkEric Please re-check for this one as well at your end, now that we've released some fixes to the uploader.

**Comment by AnkEric** [comment]
Webuploader is OK now.
Even better than before: I can upload multiple sequences subsequently without Closing and Restarting browser and without issues or strange things happening.
Thanks for a good job well done!

**Comment by katrinhumal** [comment]
Thanks for testing @AnkEric!
