### ISSUE TITLE
Pending images

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2821]
### Basic information
* Platform: `Web` 
* System/Browser: `Firefox`

I uploaded a sequence (600+ images, don't remember exact count).
600 images published on 2017-11-29 17:33
1 image published on 2017-11-29 17:38
As of now "Pending images: 26"

Why all this randomness? Why not publish all the images once finished?

**Comment by gyllen** [comment]
@Alessandro-Barbieri Its how our stitching algorithms works.

The reason why it takes some time to get your images processed is that we need to do a complete 3D reconstruction of the place where you uploaded images, this is done in tiles and sometimes one tile take longer than another tile.
