### ISSUE TITLE
upside down girl

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2822]
there doesn't seem to be any way to fix or report incorrectly rotated images, dumping things here.

* https://www.mapillary.com/map/im/4qqDHGJUggtQ1vOzpMhX2A - last image only
* https://www.mapillary.com/map/im/3SGTwGH5TOg-xIbHhl7ZNg - whole sequence
* https://www.mapillary.com/map/im/dk4maj3K6G5rmB32vPKGhA - whole sequence

**Comment by Alessandro-Barbieri** [comment]
https://github.com/mapillary/mapillary_issues/issues/2698#issuecomment-328354427

**Comment by jfburke3** [comment]
@richlv In the GitHub  # linked by Alessandro is a Google docs form to submit these in.

**Comment by Alessandro-Barbieri** [comment]
Well, these links doesn't work @richlv. Do you deleted them?

**Comment by richlv** [comment]
@Alessandro-Barbieri, all the links work for me. there is some glitch where sometimes an image is reported as not available for some users - although it works if they try it later.

i submitted the full sequences in that form, leaving this open for the remaining single image

**Comment by katrinhumal** [comment]
Thanks! I took care of the single image as well - correct orientation should be applied to it soon.

**Comment by richlv** [comment]
great, thank you. hopefully a built-in solution for this will be available to save your time.

**Comment by nereocystis** [comment]
I see a lot of rotated images in some of my otherwise correct sequences, particularly when using a bicycle. I suspect that the potholes confuse the camera or mapillary app in some way.

Sending images one at a time is a bit slow.
