### ISSUE TITLE
no visual feedback of capture

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#2823]
ios 11.1.1, mapillary app 4.8.11.

previously, when images were taken, the screen briefly flashed. this is not happening anymore, and that's very inconvenient - it's not clear whether/when images are taken.

screen still flashes in the native photo app. i also restarted the phone, but that did not help.

i seem to recall the screen still flashing after the latest mapillary app update, but do not have detailed records of that.

**Comment by katrinhumal** [comment]
@richlv There should be a setting for this - can you check which state you have for the "Flash the screen when images are captured"?

**Comment by richlv** [comment]
oh, indeed - that was set to off. weird, as i didn't even consciously remember such a setting existing, not to talk about changing it. maybe fatfingering on my part...

thank you for the quick assistance, closing.
