### ISSUE TITLE
Verifier tool improvements

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2825]
Generally speaking, users should be able to define tasks for the verifier tool.

## User defined sequences or areas filtered by a specific sign only or every sign in sequence/area ##
This enables users to work on stuff they care about and most probably also know, so verification is going to be easier and more accurate. One side effect of this strategy would also help and improve the long term motivation of users to keep verifying. While *global* verifications are necessary, they feel like a deep black pit you throw stuff into in the hope that some day something good will come out of it. Well, from a global perspective it works but from an individual perspective it does not return instant rewards which should feed current motivation. It is like if Mapillary would publish user’s photo contributions only once a year. Sure, it would work but you would not be able to keep **many** people interested in the long run.

The backend can still accumulate the results from user defined tasks into *global* tasks or categories.

## Countdown of remaining signs in global task or sequence/area specific task ##
This also helps to improve short and long term motivation. Sometimes, what keeps people going is knowing that they are closing in on their goal or destination.

## Immediate effects on detected objects ##
This is similar to how blurs work. People want to see the effects on what they have accomplished. This would also enable users to actually **use** detected traffic signs to put into OSM. Today, often places with lots of traffic signs and many images are *littered* with traffic sign symbols. This situation does not actually make it easier to map accurate data. Often these places have also false positives sprinkled into them which makes exact mapping (and this is what you actually want) even more complicated and time consuming.

## Keyboard support ##
This would definitely improve ergonomy, hence efficiency on desktops and laptops.

**Comment by katrinhumal** [comment]
Hi @GITNE  - thanks for your great feedback! Your reasoning makes a lot of sense so I really don't have more comments to add besides that we're actually discussing all these things and will implement them in the future as we release updated versions of the tool. :) 

Closing here as your feedback's been taken into account and "fixes" will come in time.

**Comment by GITNE** [comment]
> Closing here as your feedback's been taken into account and "fixes" will come in time.

Great!:grin:I keep my fingers crossed.:crossed_fingers:
