### ISSUE TITLE
map rotates forever

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2827]
### Basic information
* Platform: `Web`
* Version: `up-to-date` 
* System/Browser: `Windows 10`  + `Firefox` or `Chrome` or `edge` 

### Steps to reproduce behavior

 1. browse the Mapillary map in map view
 2. click the compass needle to rotate the view
 3. double click the compass needle to exit from rotating view

### Expected behavior
rotation mode stops

### Actual behavior
rotation mode does not stop.
To exit from rotation mode you need to reload the page

### Additional information
Until a couple of weeks back this worked fine. It's a recent new "feature"

**Comment by katrinhumal** [comment]
@voschix thanks for reporting! We have actually removed the rotation feature for now, which also removes the issue of "map rotates forever".

**Comment by voschix** [comment]
I noticed that the rotation feature has disappeared altogether
:-)
The unstoppable rotation was introduced only recently. It had worked
correctly for a long time.
