### ISSUE TITLE
Reportedly published sequences inaccessible

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2828]
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Linux/Firefox`

I have uploaded two short (58 & 211 images) sequences via the web uploader two days ago. Both sequences have been reported to have been published by email and in the feed. The pending counter shows 0 pending images. Yet, both sequences are neither visible on the map nor accessible. They are not listed in uploads either (`https://a.mapillary.com/v3/sequences`).

Since it is basically impossible to find out the sequence key of any given image key, I am providing here just two image keys of the affected sequences:
* `HPmx5FJpQfYnKHqQnaItDg`
* `JgZPefOohSWsZFIP9jwbxw`

@gyllen It might be a good idea for the `https://a.mapillary.com/v3/images` request to also return the sequence key in every image object. AFAIK, there is no easy way to look up the sequence key of an image key other than to get all the sequences of the owning user, search them for the image key, and then finally get the sequence key. This is absolutely unacceptable, especially if the user has lots and lots of sequences with thousands or even millions of images. Additionally, like in this case, `https://a.mapillary.com/v3/sequences` does not even list any of these images, which makes things even harder.

`https://a.mapillary.com/v3/images` also reports the bearing to be `-1` on both sequences, which is wrong: see also #2826.

**Comment by gyllen** [comment]
@GITNE Yeah sequence key lookup should be in the API. Agree.

@peterneubauer Can you check for inconsistency?

**Comment by GITNE** [comment]
> @GITNE Yeah sequence key lookup should be in the API. Agree.

@gyllen I mean, the sequence key does not *need* to be a member of every image object because this is also a matter of data throughput and data redundancy. On the other hand the same could said of every `user_key` member currently. Anyway, at least a cheap way to lookup the sequence key given an image key should exist.

**Comment by Alessandro-Barbieri** [comment]
Confirm, I can't see sequences uploaded today

**Comment by peterneubauer** [comment]
https://www.mapillary.com/app/?pKey=HPmx5FJpQfYnKHqQnaItDg&focus=photo&lat=54.17074136069118&lng=15.566281601116884&z=17 is now visible ?

**Comment by GITNE** [comment]
Yes, it is on the map and in the feed. Thanks! :tada: What was the cause? :thinking: I just want to know if it was me who perhaps has done something wrong?

**Comment by GITNE** [comment]
:cry: But the `GPSImgDirection` tag has been ignored on these sequences either. `v3/images` still returns `-1` and `v3/sequences` returns `359`.

**Comment by GITNE** [comment]
@peterneubauer Basically, you can close #2828. Though, it would good to know what happened, so that it does not happen again. Just FYI, I have normalized the bearing via the sequence editor on the sequences here but have left it unaltered on the first sequence which exhibited the bearing error in #2826, so that we can verify if the upcoming update has worked as expected.

**Comment by peterneubauer** [comment]
@GITNE we had some inconsistency on dirty sequences in the backend, which we now have monitoring on, so we should see this kind of stuck sequences more cleary in the backend. Thanks for your persistence!!
