### ISSUE TITLE
Annoying popup in time travel mode

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2829]
### Basic information
* Platform: `Web`
* Version: `Any` 
* System/Browser: `Firefox/Linux`

### Steps to reproduce behavior
 1. Select any time travel enabled image
 2. Go to time travel mode

### Expected behavior
No controls should be blocked by other controls and the share popup balloon should also disappear as soon as the user clicks on any other control than the popup.

### Actual behavior
The share popup balloon blocks the media bar and only disappears after releasing the media bar.

### Additional information
Maybe it’s just me but whenever I use time travel the thing that annoys me most is the share popup balloon in your face on the lower right corner which blocks the media bar for transitioning between the two images. Why? Because the media bar is the first thing I want to interact with. And sure, the media bar works as expected but the popup blocks a significant portion of the view and part of the media bar. But, the worst thing is that the share popup ballon only disappears **after releasing** the media bar! :angry: Hence, because of this bad experience I often really hesitate (or think twice) to make use of this actually really fine feature. The share popup might be fine if it would at least not overlay the media bar, hence would be smaller, or maybe in the upper right corner.

**Comment by gyllen** [comment]
@nickplesha Lets remove the popup

**Comment by nickplesha** [comment]
An annoying popup indeed. It's been fixed to behave like the other share popups. Thanks for reporting @GITNE !

**Comment by GITNE** [comment]
@nickplesha Thank you! :tada: This is much better and works as expected. You are the best! :1st_place_medal:
