### ISSUE TITLE
Unfinished uploads stuck on server, if upload scripts crashed

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#2832]
### Basic information
* Platform:  `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Run upload_with_preprocessing.py with many sequences at once 
 2. After upload, script will crash with httplib memory error
![image](https://user-images.githubusercontent.com/4630662/34014076-e67808c6-e12a-11e7-9675-93c1762ba45a.png)
 3. At legacy.mapillary.com i see a HUGE count of unfinished uploads
![image](https://user-images.githubusercontent.com/4630662/34014107-02795ab6-e12b-11e7-9954-f9b0c3039179.png)

### Expected behavior

Unfinished uploads should be published automatically after some hours after upload, and user should be able to publish all unfinished sequence at once, by a button in website, or at least REST method 

### Actual behavior

Unfinished uploads are stuck on server.

**Comment by trolleway** [comment]
Unpublished uploads was published after second run of upload_with_preprocessing.py

**Comment by Alessandro-Barbieri** [comment]
>Unfinished uploads should be published automatically after some hours after upload

Please not this, I want to be able to resume an upload a week later

**Comment by gyllen** [comment]
@Alessandro-Barbieri Yes agree, we need to think about this while we are redesigning the upload API.

**Comment by gyllen** [comment]
Added to feedback box for redesign of upload API
