### ISSUE TITLE
published sequences from LG 360 Cam to mapillary incorrect coordinates

### ISSUE THREAD

**Issue by janislit** [mapillary/mapillary_issues#2833]
published image sequences from LG 360 Cam to mapillary in incorrect coordinates
what can I do ?
https://www.mapillary.com/map/im/MPVxfOXYrs0E7gTqbTubjQ
https://www.mapillary.com/map/im/rUbCaHq8JE0EN0V_rV-pwQ
https://www.mapillary.com/map/im/im6iqX5eCdSAyhTUEOMOPA

### Basic information
Platform: iOS
Iphone 6+ LG 360 Cam

### Additional information
images direct from phone are in correct coordinates
https://www.mapillary.com/map/im/wYUcEOOdr9Z-CwzL9vaEBQ

**Comment by janislit** [comment]
Basic information
    Platform: iOS
    Version: 11.1.2
    System/Browser: mapillary/360 CAM

Steps to reproduce behavior
yesterday I tried again
   Formatted micro SD 
but the result is the same as before (incorrect coordinates)
https://www.mapillary.com/map/im/082Kgdsb-AOpbC2VJdwYSg

in capture you can see mapillary screen on my iphone 6+

its showing blue screen (not what i capturing).

**Comment by millenbop** [comment]
Thanks. Yeah  problem is probably because of daylight saving messing up the timestamps. I'll try to have a fix out later this week or early next year.

**Comment by janislit** [comment]
Now it works, thank you!

**Comment by millenbop** [comment]
Great to hear! Closing.
