### ISSUE TITLE
Wrong units in android app

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2834]
### Basic information
* Platform: `Android`
* Version: `3.108`

### Steps to reproduce behavior

 1. Go to capture mode

### Expected behavior

Use `GiB`

### Actual behavior

Free space is measured in `gb`

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for pointing it out. I'm supposing you mean `GB` not `GiB`? We'll fix the capitalisation.

**Comment by Alessandro-Barbieri** [comment]
@katrinhumal depends, see https://en.wikipedia.org/wiki/Gibibyte for more infos

**Comment by Alessandro-Barbieri** [comment]
@mprins do you have another idea?

**Comment by mprins** [comment]
Really it is irrelevant as the order of magnitude is the same and in the end it's only a few images more or less. the estimate is still accurate whether its giga or gebibytes
