### ISSUE TITLE
upload_with_preprocessing.py:  ('http error', 401, 'Unauthorized', )

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2835]
### Basic information

- Platform: Web
- Version: most recent
- System/Browser: Python 2.7, upload_with_preprocessing.py

### Steps to reproduce behavior

Run [upload_with_preprocessing.py]

### Expected behavior

Since 2017.12.13 **until today 2017.12.19** I have uploaded ±40.000 images by [upload_with_preprocessing.py] successfully.

### Actual behavior

Tonight [2017.12.19 17:30 PM GMT+1] I cannot upload anymore: **'http error', 401, 'Unauthorized',**

```
Traceback (most recent call last):
  File "upload_with_preprocessing.py", line 150, in <module>
    upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)
  ****** cut ******
  File "C:\Python27\lib\urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x00000000058372C8>)

```
### Additional information

Python Script(s) has not been changed.
Environment Setting has not been changed.

Environment:
```
MAPILLARY_EMAIL=******
MAPILLARY_PASSWORD=******
MAPILLARY_PERMISSION_HASH=eyJle******==
MAPILLARY_SIGNATURE_HASH=64Lqm******MQ=
MAPILLARY_USERNAME=ankeric
```

https://www.mapillary.com/app/settings/developers

```
MAPILLARY_PERMISSION_HASH = eyJle******==
MAPILLARY_SIGNATURE_HASH  = 64Lqm******MQ=
```

https://legacy.mapillary.com/map/upload/im

```
MAPILLARY_PERMISSION_HASH = eyJle******==
MAPILLARY_SIGNATURE_HASH  = ktn1E******k=
```
**Legacy** MAPILLARY_SIGNATURE_HASH is _**different**_ from **Developers** MAPILLARY_SIGNATURE_HASH **????**

I was and still am using https://www.mapillary.com/app/settings/developers MAPILLARY_SIGNATURE_HASH:  "= 64Lqm******MQ=".
Which is identical to my Environment Setting....

Webuploader is still ok.

**Comment by AnkEric** [comment]
Issue seems to be in [upload_with_preprocessing.py].

```
        if MAPILLARY_SECRET_HASH is None:
            MAPILLARY_PASSWORD = os.environ['MAPILLARY_PASSWORD']
            MAPILLARY_PERMISSION_HASH = os.environ['MAPILLARY_PERMISSION_HASH']
            MAPILLARY_SIGNATURE_HASH = os.environ['MAPILLARY_SIGNATURE_HASH']
            upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)
```
Work-around:

'## upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)`

Now Script can be used having **--skip_upload** set.
For upload [upload_with_authentication.py] can be used (still ok).

Should I TRY to change my MAPILLARY_PASSWORD **????**

**Comment by AnkEric** [comment]
Simple and Strange: Resolved by Retry....

Now it's OK, as usual... upload is in progress...

```
C:
CD C:\Python27\_Mapillary_Tools\

Python upload_with_preprocessing.py S:\_Mapillary --auto_done
```
**Still very curious: what happened ????**

**Comment by AnkEric** [comment]
**Summarized questions:**

- Why did authentication fail for 4 hours last night?

- Why the difference between **Legacy** MAPILLARY_SIGNATURE_HASH and **Developers** MAPILLARY_SIGNATURE_HASH?

```
https://www.mapillary.com/app/settings/developers

MAPILLARY_PERMISSION_HASH = eyJle******==
MAPILLARY_SIGNATURE_HASH  = 64Lqm******MQ=

https://legacy.mapillary.com/map/upload/im

MAPILLARY_PERMISSION_HASH = eyJle******==
MAPILLARY_SIGNATURE_HASH  = ktn1E******k=
```

- Why does [upload_with_preprocessing_TEST.py] require [MAPILLARY_EMAIL] and [MAPILLARY_PASSWORD]?
Since [upload_with_authentication.py] does not require these parameters.
Please note: I don’t like UserName and Password to be used since Authentication is vulnerable to leaking login credentials.
Moreover: my UserName and Password is stored in my PC Environment Settings as plain text. By Windows design. Not intended for storing privileged information. One of the easiest locations to hack my credentials!

**Comment by katrinhumal** [comment]
@AnkEric thanks for reporting - I'll have to ask @gyllen or @peterneubauer for help here for a possible explanation.

**Comment by peterneubauer** [comment]
This was a backend upgrade failure, things should be working as normal now again right?

**Comment by AnkEric** [comment]
After 22:00 PM last night it was oké. And still is. 

Still curious about my two other questions (on which I stumbled during the hours I was blaming myself).

**Comment by peterneubauer** [comment]
@gyllen ^^^ about auth legacy/developers

**Comment by gyllen** [comment]
@peterneubauer @AnkEric Its the same thing just that the none legacy will authenticate you to upload bigger files.

For the scripts thats something that we need to look over. In general I would like it to work like other scripts.

1. You put in your user/pass (not saved)
2. You get back hashes without having to copy them from the web

**Comment by AnkEric** [comment]
Oke, thanks for your reply.
Good enough for me (correct) > Close...
