### ISSUE TITLE
misspelling in api doc

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2837]
https://www.mapillary.com/developer/api-documentation/#warning

go to `warning--kangaloo-crossing--g1`
should be kangaroo?

**Comment by katrinhumal** [comment]
Correct! We'll fix. Thanks for reporting.

**Comment by jfburke3** [comment]
It's a result of genetic experimentation.  Someone thought that since kangaroos have a large pouch, it might be a good idea to genetically combine them with a loo, so that people would have a place to go when lost in the outback.  :rofl:

**Comment by katrinhumal** [comment]
This has been fixed now.
