### ISSUE TITLE
Web uploader: stuck after a few images

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2839]
Web uploader always stuck after a few images. 

While I initially blamed the memory consumption (#2455), I restarted the browser window and made smaller chunks down to 20 images, again stuck after 1-2 images. 

It still worked earlier today.

**Comment by katrinhumal** [comment]
@polarbearing thanks for reporting! Could you give it another try to see if the issue still persists - we had minor system problems which may have caused this. It works as it should for me right now. If not for you then we'll look into the matter.

**Comment by polarbearing** [comment]
Was trying 20-images chunks yesterday which worked, 40 images failed. 
Today I tried the remaining 223, which got stuck after 58. 

The problem is that I have no method in the workflow to identify on my harddisk, which are the 58 that are uploaded among the 223, so I cannot publish them. My only chance is to delete the already uploaded 58 and try again.

**Comment by polarbearing** [comment]
See #2744 for the resume problem.

**Comment by polarbearing** [comment]
Got another 20-image chungk through this afternoon, now trying the rest is stuck again after image 6.

**Comment by katrinhumal** [comment]
@polarbearing You don't need to figure it out yourself - when you try to add images to the staging area that are already there, the uploader is able to figure this out and will skip adding those for the second time. So you can just add your whole folder again, no need to delete the ones that are already in the staging area.

It's only after you hit the `Publish` button that duplicates unfortunately can't be detected anymore.

**Comment by polarbearing** [comment]
Ok the procedure is not intuitive, but works. Still getting stuck regularly.

**Comment by katrinhumal** [comment]
Good that the duplicate check works. Bad that the upload itself gets stuck. Handing this over to @nickplesha.

**Comment by nickplesha** [comment]
@polarbearing can you please attach an example image (or a chunk of 40 that gets stuck) here so I can try to reproduce this issue?

**Comment by polarbearing** [comment]
As said in #2455, it is certainly not a particular image, since all images did upload eventually. And it was always a different position when it got stuck, not at a particular one. 

So it is more likely an unhandled timeout in the communication between the scripts in the browser and the backend. 

Even a simple 'resume' button would help if it cannot resume automatically.

**Comment by nickplesha** [comment]
@polarbearing I understand, but I can't get this to happen with any images I take with my gear. There are many possible causes for your problem: image size, in-uploader editing, map zoom level etc. If I had your images I could narrow it down to something we can take a look at.

**Comment by polarbearing** [comment]
Hm, those sequences were eventually uploaded and deleted here. Will keep some when the problem reoccurs. 
The images from the device are 3-5 MB each. They were not modified in the browser since #2428 is not fixed. They had valid but incorrect direction values as reported in [#2579-comment](2579#issuecomment-354097330) which I cannot edit in the browser before upload. 
Where would I upload such examples? Attaching in github seems unsuitable for large amounts.

**Comment by polarbearing** [comment]
While it worked for a while, and I got longer sequences around 250 frames uploaded, the stucking now happens again. While earlier this month the already uploaded images were in the "staging", they are now gone and I have to start from scratch. Also any image adjustments need to be done again when I try again.

**Comment by nickplesha** [comment]
@polarbearing We've made some improvements to the uploader so this issue is hopefully resolved. Let us know if you encounter any issues with uploading in the future.
