### ISSUE TITLE
Selected map layer not respected when opening the website

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2840]
In one of the issues discussing the huge memory footprint of the website #2616, one hint by @nickplesha was that the Mapbox style consumes a lot of memory. 
This seems true, using the OpenStreetmap layer uses less memory.

However the layer setting is not considered when the website starts. It starts with Mapbox background. When I click on the layer icon, it shows that the radio button is already on Openstreetmap, however I need to click on it again to actually get this layer. 

Browser: Safari 11.0.2

**Comment by nickplesha** [comment]
@polarbearing This has been resolved.
