### ISSUE TITLE
Sequence_cut has cut an aerial sequence

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2841]
Hi!
As my passion for travel, two days ago I was landing at Barcelona's airport at 9:00 PM. Lights give me a fantastic and plastic images of cities like Igualada ,Terrassa, Sabadell, Cerdanyola, Santa Coloma de Gramenet or Badalona, the Barcelona's port and the airport itself. There were 86 images uploaded.
It was a short and beautiful sequence.

But then @sequence_cut arrived...and cut this images into individual portions. Now the pics are in the place but are also disconnected and have...no meaning (nobody will find it , and also you lost the possibility to play it and see the nightly landing.)
Could be possible to recover that sequence in it's original state and dimension? Like Edit Blurs is possible to enable some option sequence_cut understand that should not cut an specified sequence?
Thanks.

Images from Igualada https://www.mapillary.com/map/im/OiovcVadURPt8NuYUxBJLw
Images from Terrassa https://www.mapillary.com/map/im/371bvS0wV9s3_cGifWnvwg
Images from Sabadell https://www.mapillary.com/map/im/ieR7Hg9LpRBh7_itA2jRsg
Images from Cerdanyola https://www.mapillary.com/map/im/Lgb4CbA__4Ai3fX3VQyY5Q
Images from Santa Coloma https://www.mapillary.com/map/im/9gqSO0F2IMcz5PoOae4OCg
Images from Badalona https://www.mapillary.com/map/im/Op_njk4UXgRI2LVdC1gh4w

**Comment by katrinhumal** [comment]
Hi @yopaseopor - capturing your landing experience is cool indeed and the images look fascinating! The only problem is that unfortunately, this doesn't fit under the roof of "street-level", which is what the Mapillary platform is meant for. And while this doesn't mean that we don't want these images of yours to be on the platform, I'm afraid that we don't have a way for you to connect them back to a sequence as you had wished.

Sequence cut is optimised to assume that we have sequences of street-level images on the platform. One notion here is that we also count and report Mapillary coverage in km, so if very far-apart images were connected in a sequence and counted as km, this would make coverage falsely appear much larger than it actually is, which in turn would interfere with both leaderboards as well as statistics about coverage in general, which is highly of interest to those who use Mapillary for obtaining map data.

**Comment by yopaseopor** [comment]
Well, fortunately I have all the images I have uploaded to Mapillary previosly.
I think it will be possible when you are uploading a sequence, to mark in some way, or some option that specific sequence is a special sequence. That sequence would be not cut and not be counted as stats for km.  of street imagery or leaderboard things. Today we have drones, today we have aerial images, I can be wrong but I think It would be interesting for Mapillary to allow in a effective way these kind of images (plane, train, etc.)

**Comment by katrinhumal** [comment]
Definitely lots of interesting imagery! We never know about the far future, but in the foreseeable one, Mapillary will not be focusing on aerial imagery. Train imagery fits in just fine, though, since it is also on street level. :)
Anyway, thank you for your feedback!

**Comment by Alessandro-Barbieri** [comment]
@yopaseopor this is not the place for aerial images. You can have better luck in openaerialmap
