### ISSUE TITLE
Mapillary app does not allow anymore to store photos on SDCard?

### ISSUE THREAD

**Issue by severinmenard** [mapillary/mapillary_issues#2843]
Android 7.0 on Moto G5 Play
App version 3.117
Since a few days, maybe the last update, Mapillary stores the photos no more on the micro SDcard in the device but in its internal memory and does not allow to browse upper than /storage/emulated/0 (see the screenshot below) and therefore does not allow to get to the SDcard, while this SDcard is detected by all the other apps in the device. Obviously this is a huge limitation for capture photos during long runs. Is there a way to set the storage location back to the micro SDcard?
![screenshot_20180102-115428](https://user-images.githubusercontent.com/1291055/34527036-fa6f20fa-f082-11e7-832c-52e496f1c5b8.png)

**Comment by katrinhumal** [comment]
@severinmenard Thanks for reporting! We're aware of the issue and working on the solution. Hope to get this fixed soon!

**Comment by jfburke3** [comment]
Just a note to say that I am not experiencing this problem on my SGS7 running Android 7.0, with the same Mapillary version.  But then, I had configured the app to use the SD card previously, and haven't tried to change it.

**Comment by katrinhumal** [comment]
@ovivoda maybe useful to know ^

**Comment by drkludge** [comment]
That sounds like the same issue that I had https://github.com/mapillary/mapillary_issues/issues/2515#issuecomment-293068825.  Please try the procedure.

**Comment by ovivoda** [comment]
Please try this APK: http://android-releases.mapillary.io/Mapillary_Android_v3.118-SNAPSHOT1.apk1

and let me know if it works for you. For KitKat and up the application will now use SDCard private folder to save the images if you enable the setting to use the SDCard from Settings->Storage section.

Warning: If you are using this setting and you uninstall the application before uploading the images, the images will be lost.

**Comment by katrinhumal** [comment]
@severinmenard Sorry I forgot to notify here but this has been fixed! Please check if it works for you with the latest app version.
