### ISSUE TITLE
email change

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2845]
I want to change the email associated with my mapillary account but I can't find a way to do so.

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Please send your request to support@mapillary.com and we'll fix it for you. :) (See https://help.mapillary.com/hc/en-us/articles/115002915649 about changing your account details.)

**Comment by Alessandro-Barbieri** [comment]
Why not add something in the site? Only this site doesn't support email change ... (I'm changing my email in dozen of websites)

**Comment by katrinhumal** [comment]
We're definitely thinking about it :) Just with limited resources, we haven't yet run out of other issues/improvements to work on before, which have more impact on the way our community can use Mapillary.
