### ISSUE TITLE
GoPro Session 4 preview not shown

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2847]
### Basic information
* Platform: `iOS`
* Version: `11.2.2` 

### Steps to reproduce behavior

 1. Connect Camera to App
 2. Look at preview, everything looks good
 3. Star biking and then start capture

### Expected behavior
- App still shows preview

### Actual behavior
- App shows only a blue screen

![img_5176](https://user-images.githubusercontent.com/1651235/34770087-227a6582-f600-11e7-954e-cec26df2e909.JPG)

**Comment by habi** [comment]
Images are recorded correctly (minus the GPS coordinates), but that's another issue: https://github.com/mapillary/mapillary_issues/issues/2546#issuecomment-356567833

**Comment by katrinhumal** [comment]
@habi thanks for reporting! Can you say if this has been the case for you all along with this camera, or has it recently started happening (like after an app or camera software update)?

**Comment by habi** [comment]
The app used to work pretty much perfect with my camera in the olden times, as said [here](https://github.com/mapillary/mapillary_issues/issues/2610) and [here](https://github.com/mapillary/mapillary_issues/issues/2546#issuecomment-297516227), but the usefulness with (my) external camera degraded from there...

**Comment by millenbop** [comment]
Hey @habi 

Expected behavior is
1) Connect an external camera
2) App shows a preview photo
3) When capture is started, a blue screen is shown instead

If I understand you correctly, this is how it behaves for you? In that case, it is not a bug.

It has always been this way. The reasons for not showing live video feed is that it would drain the battery faster, and also, it is not available when shooting images in time-lapse mode.

**Comment by habi** [comment]
Ok, that clears things up. Maybe it would be a good idea to have a little pointer to the user, for example when she/he first connects a camera.

**Comment by millenbop** [comment]
Good feedback! I think we planned on writing something in the view ("Preview is not available during capture") but dunno what happened to that... I'll make a note of it and try to incorporate it soon.
