### ISSUE TITLE
Mapillary traces are not shown for base maps except 'Mapbox Streets'

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2849]
### Basic information
* Platform: `iOS`
* Version: `11.2.2` 

### Steps to reproduce behavior

 1. Change base map
 2. Go out and acquire images

### Expected behavior
- Mapillary traces are shown

### Actual behavior
- Traces are not shown for 'Mapbox Satellite', 'OpenStreetMap' and 'ESRI Streets'

![montage](https://user-images.githubusercontent.com/1651235/34830082-14a67cdc-f6e3-11e7-8649-2e4a0cd7151d.png)

The montage shows 'Mapbox Satellite' on the left, 'OpenStreetMap' in the center and 'Mapbox Streets' on the right.

**Comment by katrinhumal** [comment]
@habi Are these freshly uploaded images or all imagery? I.e. you see now green lines anywhere on the map with other base maps besides Mapbox Streets?

**Comment by habi** [comment]
I’ve seen it in the app, and just now found out that it depends on the zoom level: 
![049d1b91-7fed-4cd4-97d4-1e986f1a0458](https://user-images.githubusercontent.com/1651235/34845437-21a78318-f715-11e7-8041-689779431c77.gif)

**Comment by katrinhumal** [comment]
@habi I see! It might be that this has to do with the map tiles not the app. Could you possibly try exploring the same location when you open it not in the Mapillary app but open the browser on your phone and go to mapillary.com/app?

**Comment by habi** [comment]
In the browser I see the traces, except for ‚ESRI street‘, which forces the page to reload, as seen in the screenshots below (all on iPhone SE).

![465ff901-a269-437b-95a2-a015017b0028](https://user-images.githubusercontent.com/1651235/34866098-9f3ea264-f77b-11e7-8a4f-8224b859d860.png)
![294df3db-97cf-4b7f-a1ee-76a2487ce595](https://user-images.githubusercontent.com/1651235/34866099-9f5b2ca4-f77b-11e7-86b2-1c9c0298d500.png)
![f5d4fe91-e5f2-4365-b50e-42d534eae262](https://user-images.githubusercontent.com/1651235/34866100-9f718a12-f77b-11e7-9f7b-09051a1d273f.png)
![8a34f0d9-fdca-4c4e-9a20-466cf7f70527](https://user-images.githubusercontent.com/1651235/34866101-9f892ea6-f77b-11e7-9d9c-cafb55cc6dc3.png)

**Comment by katrinhumal** [comment]
@habi thanks for checking! Handing this over to @millenbop now.

**Comment by millenbop** [comment]
Thanks for reporting! I'll look into it!

**Comment by millenbop** [comment]
Fixed now, closing.

**Comment by habi** [comment]
Great, thanks!
