### ISSUE TITLE
webupload fails with orange-red icons

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2850]
A new way to annoy goodwilling contributors:
Trying to upload a sequence of 17 images, well recognised by the browser. See them uploading (data are transmitted), but then each icon turns orange-red, and at the end I get "17 files failed to upload" with the offer to retry. 
Retrying with the same result. 
No reason is given whatsoever _why_ all images have failed.

Images were taken with Android app 3.117

**Comment by nickplesha** [comment]
@polarbearing Thanks for reporting! Can you attach the images here so we can check the EXIF data?

**Comment by eugensim** [comment]
the same thing happened to me too

**Comment by polarbearing** [comment]
Could upload them to something like an ftp server. Attaching bulk megabytes to github appears inappropriate to me.

**Comment by zayuim** [comment]
Same here, Every image (including images that have already been uploaded successfully in the past) fails.

**Comment by katrinhumal** [comment]
This has been fixed now, please try and let us know if you run into more trouble. :)

**Comment by polarbearing** [comment]
Thanks. So again, the reason were not in the images themselves, which are up now.
