### ISSUE TITLE
"Distance based capture" toggle greys itself out

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2852]
### Basic information
* Platform: `iOS`
* Version: `4.8.12`
* System: `iPhone 7, iOS 11.2`

In the iOS app settings, turning "Distance based capture" off will disable (grey-out) "Distance between captures", and enable "Time between captures" and "Pause capture at low speeds".

If I then turn "Distance based capture" back on, the interface will enable "Distance between captures" and disable "Time between captures", "Pause capture at low speeds"… **and the "Distance based capture" toggle I just tapped!** If I want to turn it off again, I have to close settings and reopen them.

Note that if "Distance based capture" is initially off when you open settings, to reproduce this bug you have to turn it on, then off, then on again (3 taps), and that's when it disables itself.

**Comment by millenbop** [comment]
Ah good catch, thanks for reporting.

**Comment by millenbop** [comment]
Fixed now, closing.
