### ISSUE TITLE
images captured in square ratio, occasionally

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2853]
Android 3.117

While the app normally captures in 4608x3456 (4:3), it recorded a couple of sequences in 3456x3456 (1:1).

I don't see a setting for that, and I don't see a reason. Also it seems to depend on the mood of the app to write to mapillary_trace.txt or not, so for this day there are no entries while the day before and after, there are. Started the app again and it is back on 4:3

What is that? Apparently there was a similar issue #1955 that was closed without resolution.

**Comment by katrinhumal** [comment]
@polarbearing thanks for reporting, this sounds really strange, and even more that it wasn't captured in the logs. Asking @ovivoda to troubleshoot here.

**Comment by polarbearing** [comment]
Is the trace file sometimes overwriting itself? I was now checking another device which I used for manual captures (the above was automatic). I took 10 sequences between 13:56 and 14:32. The 4th sequence at 13:58 has square images. Only the last, 10th, sequence at 14:32 shows up in the log:

```
Sat Jan 20 10:41:17 GMT+01:00 2018 : app.mapillary.android.StorageUtils  - getDefaultImageStoragePath- /storage/emulated/0/Android/data/app.mapillary/files/mapillary
Sat Jan 20 14:32:36 GMT+01:00 2018 : app.mapillary.android.activity.CameraActivity  - onResume()
```

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
