### ISSUE TITLE
Web upload: ignores data capture exif

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2855]
Web uploader ignores data capture for the images that I put manually on the map. And after that the date is set automatically with the date and hour when is made the process, not the real date (july 2017).
![image](https://user-images.githubusercontent.com/8439643/35520145-dde85fc2-051e-11e8-96dd-0960efbd88e5.png)
![image](https://user-images.githubusercontent.com/8439643/35520162-eca8a8b4-051e-11e8-91c1-7d951440a725.png)

Browser: Chrome last version

**Comment by katrinhumal** [comment]
@eugensim Thanks for reporting! What have you captured these images with? Could you please upload a few here for us to take a look?

**Comment by katrinhumal** [comment]
@eugensim I see! Glad that there was a simple explanation and your uploads turned out as they should. Thanks for the feedback. :)
