### ISSUE TITLE
web uploader shows 4 old images, that are on the web already, as to be published

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#2856]
When I call the web uploader via https://www.mapillary.com/app/uploader, it presents me fragments from previous uploads, in the experience so far 4...6 images although the original sequences were larger, as "Publish 4 uploaded" or "Delete all". 

I checked the positions and found that those images are shown on the map. 
Example: https://www.mapillary.com/map/im/sqTv1hIK07vz_dfSnmHtsg

I hope that pressing "Delete all" to delete them from staging would not delete them from the map???

**Comment by katrinhumal** [comment]
@polarbearing Yes, `Delete all` here will delete them only from the staging. Please try that and let me know if this helps.

**Comment by katrinhumal** [comment]
I hope this got resolved. If not, please email us with more details at support@mapillary.com (we're phasing out mapillary_issues).
