### ISSUE TITLE
Upload screen on iOS shows '?' on top

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2857]
### Basic information
* Platform: `iOS`
* Version: `11.2.5` 

### Steps to reproduce behavior

 1. Upload images

### Expected behavior
- Top of screen shows something, probably nice

### Actual behavior
- Top of screen shows two '?', left and right, as seen marked yellow in the screenshot.

![img_6135](https://user-images.githubusercontent.com/1651235/35573578-cb167c30-05d7-11e8-87cc-7922e5096540.JPG)

**Comment by millenbop** [comment]
Thanks! Hm I'm sure I have fixed this already! Anyway, will fix again :)

**Comment by millenbop** [comment]
Ah missed to fix it for the state "disabled". Fixed now, will be available in the next release.
