### ISSUE TITLE
How To: delete multiple images in a sequence

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2859]
### Basic information

* Mapillary website
* Edit current sequence

### Steps to reproduce behavior

We had to stop at the border post South-Africa and Swaziland.
Our guide/driver did advise me: don't touch the action cam. If you ignore it, so will the border guards.
So action cam made 200+ images during a stop.

I was assuming "Python remove_duplicates.py -d 4" (default value) would remove the duplicates.
Which it didn’t. Perhaps due to GPS drift.
Also I forgot to delete these images before upload to Mapillary. I missed 200+ images out of 300.000.

Three options:
- Ignore the missed blurs on faces of border guards. Don’t think this is a good option.
- Blur all 200+ images. Which I did… which took a long time...
- Delete all 200+ images. However, deleting 200+ images will require too much effort. Deleting the complete sequence is fast but not to be preferred. 

### Expected behavior

I would prefer an option to delete multiple images in a sequence, without selecting “Mark whole sequence for deleting”.

**Comment by katrinhumal** [comment]
@AnkEric Thanks for the feedback. We'll definitely take note of this request when thinking about future improvements to the editor. Currently, it sounds like the easiest option in this case might be to delete the whole sequence after all and re-upload only the ones that you want after "weeding out" the unsuitable ones on your computer.

**Comment by AnkEric** [comment]
@katrinhumal 
I will consider this option once I'm finished with South Africa.
200+ Images on the same spot is definitely not oké! Even if they have been blurred.

But also:
I have requested an incorrect sequence for deletion several months ago. It's still not deleted.
Sequence key = lZWLu1157z9WE68OxvYv6Q (Oct 14, 2017)
Pending Edits = 3
I have sent the deletion request again, it's still there.

Off topic:
Deletions sometimes are urgent from a privacy point of view. I would prefer my deletions to be pre-approved (like my blurs are being approved within minutes).

**Comment by katrinhumal** [comment]
@AnkEric Deletion of your own images is auto-approved but with the limit of 1000 images at a time. Sequences longer than that need to be manually approved by admins.

The sequence you indicated was a lengthy one but I've "administrated" it to be deleted now - might take a little time for the map tiles to update but it should be gone soon.

**Comment by AnkEric** [comment]
@katrinhumal 
Thanks for deletion!

FYI: my GPS made a shift in time, backwards and forwards again after a couple of minutes. Strangest issue ever! My Image sequence showed a corner on a straight road and a straight road in the corner of the road... All images for the rest of the day were correctly positioned.
I was annoyed and Mapillary did not delete my errors.
Luckely for me, no one has noticed; -))
