### ISSUE TITLE
Android notifications despite logged out

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#2860]
### Basic information
* Platform: `Android`
* Version: `latest`
* System/Browser: `any Android`

### Steps to reproduce behavior
1. Install app or clear app data and cache
2. Log-in
3. Log-out
4. Perform any action via the web app which causes a notification, like blurs, uploads, deletions etc.

### Expected behavior
Once the user logs out, the app should not pull any Mapillary notifications and not post any Android notifications nor create any network connections to Mapillary.

### Actual behavior
After a user logs out of the app, it still pulls Mapillary notifications of that user and posts them as Android notifications.

**Comment by katrinhumal** [comment]
@GITNE this sounds similar to https://github.com/mapillary/mapillary_issues/issues/2691#issuecomment-357990307 - any chance you have the app installed on external memory?

**Comment by GITNE** [comment]
> @GITNE this sounds similar to #2691 (comment)

No, #2691 is about a bug on how the app handles OSM's OAuth 2.0 protocol implementation. More specifically, it is about where the app stores the access token. I suppose that in order to fix that issue the app would need to store the access token in a file where the app has actually been installed (i.e. an SD card or internal storage) rather than in a `Parcel` object.

This issue is about the fact that the app does not release (or actually does not irretrievably delete) the access token acquired from Mapillary **and** creates network connections to pull notifications although no user has logged-in. Relaunching the app or rebooting the system does not *help* either.

> \- any chance you have the app installed on external memory?

No, running from internal storage.

**Comment by nicolas17** [comment]
Notifications aren't "pulled" by the app doing network connections. The Mapillary server sends them to a Google server which then sends them to your phone.

**Comment by katrinhumal** [comment]
Asking @ovivoda to take a look.

**Comment by GITNE** [comment]
> Notifications aren't "pulled" by the app doing network connections. The Mapillary server sends them to a Google server which then sends them to your phone.

Right, however effectively the app is responsible for that, no matter what dependencies may be involved. It also does not matter if dependencies create network connections on behalf of the app. If no user is logged-in the app should release all notifiers, timers, and other resources and keep quiet.

**Comment by ovivoda** [comment]
@GITNE Will look into this one

**Comment by GITNE** [comment]
@ovivoda Ping? Have you been able to reproduce the issue?

**Comment by ovivoda** [comment]
@GITNE sorry for not getting back to you on this one. You are right I managed to reproduce and I already have a fix in mind for it.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
