### ISSUE TITLE
iOS app recompresses images when adding EXIF

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2861]
### Basic information
* Platform: iOS
* Version: 4.8.13

Background: The iPhone app captures photos with no GPS location or any other EXIF information. The EXIF metadata is stored in separate files. When the photos are uploaded, the app adds the metadata into the photos. There is also a button to only add the EXIF data without uploading, which lets the user copy georeferenced photos to the computer and upload them from there.

The problem is that **this "add EXIF" step re-compresses the JPEG image**, rather than only adding EXIF data and leaving the image data untouched. This inevitably reduces the image quality and adds new compression artifacts (although I admit most artifacts will be unnoticeable after the server downscales them more).

It also makes the processing take longer than it should.  Avoiding re-compression would probably make the "add exif without uploading" feature *much* faster.

### Steps to reproduce behavior
 1. Take some photos!
 2. Copy a photo from the app to a computer via iTunes file sharing (or whatever devs can use to access files from the app container).
 3. Run the "Add EXIF data" processing from the app.
 4. Copy the same photo again via iTunes, to another file.
 5. Compare the two images.

There are several ways to do the comparison. Some GUI image editors may have image comparison features. If there are sharp edges, you may notice the artifacts visually by just  switching between the two photos quickly. Finally, something that worked well for me was GraphicsMagick:
```bash
gm composite orig/2018_02_05_03_09_51_269.jpg exif/2018_02_05_03_09_51_269.jpg -compose difference diff.png
gm convert diff.png -level 0,1,10% diff-enhanced.png
```

I remember someone (Anders?) mentioned that this isn't new to the separate-file EXIF, and back when the app added the EXIF during capture it was probably doing the same double-JPEG-encoding.

This isn't really a high priority to fix, and may need switching to a third-party library to alter the EXIF. But I wanted to finally write it down in an issue.

**Comment by nicolas17** [comment]
Photo taken with iPhone 6:
- [Before adding EXIF](https://user-images.githubusercontent.com/101955/35954409-32148cec-0c68-11e8-9adb-5a7855cf3210.jpg)
- [After adding EXIF](https://user-images.githubusercontent.com/101955/35954461-89965ff4-0c68-11e8-9b24-f329b0fa8d5e.jpg)
- [Pixel-wise difference](https://user-images.githubusercontent.com/101955/35954702-e9ab1ac8-0c69-11e8-83ba-f19961fcf47b.png) (enhanced with `-level 0,1,10% -colorspace Gray`)

On visual comparison it looks as if the compression artifacts (and sensor noise) from the original were slightly sharpened.

**Comment by millenbop** [comment]
Thanks @nicolas17 for the investigation. It is a known issue and like you said it has been like this since the first version of the app. I'll be testing some alternatives this week for EXIF that doesn't use Apple's libraries since I'm doing related EXIF/uploading work anyway. Will keep this thread updated with results.

**Comment by millenbop** [comment]
Just reporting some progress. I went looking for a good lib for exif, but all the ones that I found have licenses we can't use (GPL etc). 

So I decided to take on the challenge myself: 
1) not recompress files when adding exif 
2) add exif without reading the whole file into memory

I'm happy to say that I have a working version now, but I need to do more tests. This also solves #2866

I used the same commands as you to test.

INPUT (no EXIF)
![new](https://user-images.githubusercontent.com/12835674/36311273-1367dcbc-132b-11e8-8854-43cf3f0f1ad5.jpg)

OUTPUT (has EXIF)
![orig](https://user-images.githubusercontent.com/12835674/36311274-13834452-132b-11e8-9edc-02d79e6b0c9a.jpg)

DIFF ENHANCED
![diff-enhanced](https://user-images.githubusercontent.com/12835674/36311265-0bb3d386-132b-11e8-9cc8-49a45efd6ed9.png)

OUTPUT FROM YOUR SCRIPT

total:   3.09 MiB
real:    3.09 MiB (100.00%)
garbage: 0 bytes (0.00%)

**Comment by nicolas17** [comment]
The actual compressed image data is bitwise-identical in both JPEG files, so that's working, and does fix 2866 :)

I see the EXIF'd file doesn't have the usual Mapillary JSON in the description tag, but I assume that's just from testing?

A few days ago I found this (forgot to post it on this ticket earlier, sorry), which supposedly lets you alter metadata using built-in frameworks: https://developer.apple.com/library/content/qa/qa1895/_index.html
But maybe it doesn't let you set all the EXIF tags you need; I didn't look at it in any detail.

**Comment by millenbop** [comment]
This is just from my testing so not all tags are there (yet).

I used that very same article, i.e. the same functions it mentions. Not all of them work though (like merging exif data for instance). They make it look very straightforward but it's not. There is hardly any documentation and I had to do a lot of trial and error. 

There are things missing in the header files as well so you need to sort of reverse engineer some things to figure out which strings to use instead of missing constants.

I hope I get time to properly extract the exif code into reusable libraries since there is hardly any info about this stuff in the Apple docs or on the rest of the internet.

**Comment by richlv** [comment]
heya, any luck on this ? it does not sound simple, but would be a great improvement

**Comment by millenbop** [comment]
I have it ready but it's not out in production yet. I plan to send out betas this week though!

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
