### ISSUE TITLE
OAuth authorization page always mentions "uploader" app

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2863]
The OAuth authorization page at https://www.mapillary.com/connect seems to have hardcoded text saying "The uploader will be able to read your email and write to the database on your behalf".

This appears for any registered OAuth app, even the official JOSM plugin(!). It says "uploader" even if the app is not an uploader, and it says "will be able to read your email and write to the database" even if those aren't the OAuth scopes being requested. For example, JOSM is *not* asking to get access to my email address (`user:email` scope).

I guess that text was added for the desktop uploader app (which I don't remember being ever released 🤔). If the plan was to show something more user-friendly than "the app [name] is requesting the following permissions: [ugly bullet list]", that sounds like a good idea but it should be done only for the uploader app's client_id.

**Comment by katrinhumal** [comment]
@nicolas17 well-spotted! We actually just realised this ourselves as well and will improve the wording to be more accurate and truthful. :)

**Comment by katrinhumal** [comment]
This has gone a bit unattended but I can assure we have this tracked internally so it has not fallen off the table. Closing the issue here.

**Comment by katrinhumal** [comment]
...And we've actually just pushed an update so hopefully, the message is clearer now. :)
