### ISSUE TITLE
incorrect sequence grouping with interrupted `upload_with_authentication.py`?

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2865]
Ran the following on folder with a lot of pictures.
1. `python remove_duplicates.py ~/Desktop/mapillaries/forprocessing/ ~/Desktop/mapillaries/dups`
2. `python sequence_split.py ~/Desktop/mapillaries/forprocessing/ 50 60`
3. `find /Users/danbjoseph/Desktop/mapillaries/forprocessing -mindepth 1 -type d -print0 | xargs -L 1 -0 -P 10 ./upload_with_authentication.py --auto_done`

The upload was interrupted and i had to restart step 3. Some of the resulting sequences on the site have random clumps interspersed among another sequence. If `upload_with_authentication.py` is interrupted/restarted does it start a new sequence with the remaining images? As opposed to using `add_mapillary_tag_from_exif.py` which will assign all the images a sequence id so that no matter if you upload them in multiple chunks, they'll be correctly associated on the server?

![screen shot 2018-02-12 at 12 57 24 pm](https://user-images.githubusercontent.com/4806884/36111635-cf061f90-0ff4-11e8-84d7-62b83a709d37.png)
![screen shot 2018-02-12 at 12 57 52 pm](https://user-images.githubusercontent.com/4806884/36111636-cf08265a-0ff4-11e8-8ba3-0237b826a3de.png)

example sequences in above screenshots:
`7aLfnWJ_CNfqmR65I-yh-w` and `MQA97NfD9RK2K4r4eQDN_w`
(but also happened in other sequences in the same area submitted by user `danbjoseph`)

**Comment by katrinhumal** [comment]
@danbjoseph I'm moving this to the mapillary_tools repo. I know it looks a bit deserted lately but we'll pick it up there!

**Comment by katrinhumal** [comment]
Issue moved to [mapillary/mapillary_tools #220](https://github.com/mapillary/mapillary_tools/issues/220) via [**ZenHub**](https://www.zenhub.com/)
