### ISSUE TITLE
iOS app leaves garbage at the end of JPEG files

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2866]
### Basic information
* Platform: iOS
* Version: 4.8.13

As mentioned in #2861, the iOS app recompresses JPEG files when adding EXIF information, which can lower the quality of the image.

But there is an extra problem. It seems like when the file is recompressed, it's written in-place over the original file, without truncating it. Most of the time (or always), the newly-compressed image will be smaller than the original. But the file will still be of the same size, and it will contain data from the original file at the end.

Suppose the original is 3MB. When the app recompresses it, it shrinks to 2.5MB. The file is still 3MB, with the newly-compressed image taking up the first 2.5MB. The last 500KB will be identical to the last 500KB of the original file, which is now just garbage that any image reader will ignore.

![Image data](https://user-images.githubusercontent.com/101955/36135871-630e843a-106c-11e8-9222-dc48c67e02f6.png)

This is data that takes up space in the phone, takes up space in the server, takes up bandwidth (making the upload take longer), and most importantly doesn't contribute to the image. I wouldn't care if the files were 3MB, but I care if they are 3MB with only 2.5MB of useful data inside...

I wrote a script that parses the JPEG format to find the real file size (by looking for the `FF D9` "End Of Image" marker), and reports how much more data remains from there to the actual end of the files. [You can find it here](https://github.com/nicolas17/mapillary-jpeg-waste). For photos taken by the Mapillary app directly with the iPhone camera (and then processed to add EXIF), there is around 15% of wasted data. For photos taken with a GoPro HERO Session 5 controlled by the iPhone app, I have seen it go as high as 42%.

The main fix here is making the iPhone app truncate the file properly when rewriting it. Perhaps the easiest way is to write the file to a new name and then rename it over the original.

But additionally, the server folks may be interested in fixing this for existing photos. I haven't tried with other GoPro cameras, but assuming they are similar to the Session 5, you could make all your originals from GoPro-iPhone take half the space on S3!

### Steps to reproduce behavior
As in #2861, you can use iTunes to get files before and after they are processed by the app and compare them:
 1. Take some photos.
 2. Copy a photo from the app to a computer via iTunes file sharing.
 3. Run the "Add EXIF data" processing from the app.
 4. Copy the same photo again via iTunes, to another file.
 5. Note that the two files have identical size.
 6. With a hex editor, you will see the original and new file have different data until the new file's byte sequence `FF D9` (End Of Image). After that, both files are identical until the end of the file (which has another FF D9). Another way to see this identical data is `diff -y <(xxd orig.jpg) <(xxd exif.jpg)`.

Alternatively:
 1. Take some photos.
 2. Run the "Add EXIF data" processing from the app.
 3. Copy the whole directory to the computer.
 4. [Get my scripts](https://github.com/nicolas17/mapillary-jpeg-waste) and run `./waste-counter.py dir path/to/dir`. This will report the total file size, and how much of that is actual image data vs leftover garbage.

 ```
$ ./waste-counter.py dir ~/Mapillary/photos/2017_10_10_16_49_24_691/
100%|............................| 181/181 [00:06<00:00, 27.27files/s, waste=43.44 MiB]

total:   264.81 MiB
real:    221.37 MiB (83.59%)
garbage: 43.44 MiB (16.41%)
```

I plan to add more features to the script later, such as truncating files to the correct size.

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
