### ISSUE TITLE
SSL certificate for mapillary.com (not www.mapillary.com) expired on Feb 5th

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2867]
The mapillary.com domain seems to use a separate Let's encrypt certificate:
https://www.ssllabs.com/ssltest/analyze.html?d=mapillary.com&latest

It expired on 5th of february. The "main site" certificate for www.mapillary.com works fine.

**Comment by gyllen** [comment]
@ulikoehler Thanks for reporting

@martinskans ^^^^

**Comment by martinskans** [comment]
It was the root certificate that had failed to refresh automatically and not our ssl cert, so because the root cert had expired it caused our certificate to be marked as invalid. The root cert has been refreshed now.

**Comment by ulikoehler** [comment]
this has been solved already, so I'm closing it. Thanks for fixing, @martinskans .
