### ISSUE TITLE
"Authorization Code" OAuth flow not working

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2868]
While [the OAuth API is not documented](https://github.com/mapillary/mapillary_issues/issues/2862) at the moment, I tried using it anyway according to the old APIv2 documentation.

With implicit grant, going to the /connect page asks if I want to authorize the app, and redirects to the app's URL giving it the access token; all working fine:
```
Browser to:
https://www.mapillary.com/connect?
  client_id=VGhpcyBpcyBhIGZha2UgY2xpZW50IElE&
  scope=user:email&
  response_type=token&
  redirect_uri=https://example.com/auth

Redirects to:
https://example.com/auth?
  token_type=bearer&
  access_token=TokenHere
```

With authorization code grant, going to the /connect page asks to authorize app, and redirects to my URL with the authorization code. But trying to exchange it for an access token using the token endpoint doesn't work:
```
Browser to:
https://www.mapillary.com/connect?
  client_id=VGhpcyBpcyBhIGZha2UgY2xpZW50IElE&
  scope=user:email&
  response_type=code&
  redirect_uri=https://example.com/auth

Redirects to:
https://example.com/auth?
  code=617574686f72697a6174696f6e20636f6465

POST to https://a.mapillary.com/v2/oauth/token with
  grant_type=authorization_code&
  code=617574686f72697a6174696f6e20636f6465&
  redirect_uri=https://example.com/auth&
  client_id=VGhpcyBpcyBhIGZha2UgY2xpZW50IElE

Returns:
{"error":"invalid_request","error_description":"No authorization header passed"}
```

I tried several things, like including the client_secret as a parameter, or passing client_id:client_secret in an Authorization: Basic header (as described in the [OAuth spec](https://tools.ietf.org/html/rfc6749#section-2.3.1)) but none of that works. And I think it used to work...

**Comment by nicolas17** [comment]
I found this problem was mentioned in #2374, but switching to the implicit grant solved the user's needs, so I guess it wasn't investigated further.

**Comment by gyllen** [comment]
@nicolas17 I think your safest bet right now is to use the `implicit` flow. At the moment we are actually looking at replacing our Oauth 2.0 backend.

**Comment by gyllen** [comment]
Closing since `implicit` should be used (for now)
