### ISSUE TITLE
Photo rotated 90°

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2869]
I found this picture that is rotated 90°: https://www.mapillary.com/app/?focus=photo&pKey=qgP6rfLA7IloSTeeYEQxFg

The rest of the photos in the sequence seem to be fine, so I couldn't use the rotation request form (which is for whole sequences).

**Comment by katrinhumal** [comment]
Thanks for reporting @nicolas17 - I listed this for rotation so should be fixed within a few hours.
