### ISSUE TITLE
gopro hero 5/6 video upload

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2871]
# Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `...`

### Steps to reproduce behavior

 1.
 2.
 3.

### Expected behavior

...

### Actual behavior

...

### Additional information

is there a way to upload in one step an gopro video where the gps datas are embedded over the website ?

can‘t do it and still looking how i can extract the gpx datas to do it in two steps as zhe old website is asking for

**Comment by katrinhumal** [comment]
Hi @thoschu96 - today we don't have a way for you to upload the video with embedded gps data, so you need to find a way to split the gpx file or split the video into geotagged images. We might be able to add support for videos with embedded gps info in the future.

**Comment by katrinhumal** [comment]
Uploading videos with embedded GPS data is now possible with the latest release of [mapillary_tools](https://github.com/mapillary/mapillary_tools).
