### ISSUE TITLE
Internal server error when retrieving detections with unauthorized client_id

### ISSUE THREAD

**Issue by nereocystis** [mapillary/mapillary_issues#2872]
### Basic information
* Platform: `Ubuntu`
* Version: `...` 
* System/Browser: `curl`

I tried retrieving detections with a client_id unauthorized to do so.

The first time I tried this request, I received an internal server error, the second time, I received unauthorized request, which is probably correct.

### Steps to reproduce behavior

 1. First request shows server error.

$ curl 'https://a.mapillary.com/v3/images/lxq56ufzLQp95QJeM2dt8w/detections?client_id=a1ZDQjR6X0RDUHN1TmtRVlpZSmlEdzplODBmYTQyNDdkODViN2I4'
{"message":"Internal server error. Please report the issue at https://github.com/mapillary/mapillary_issues/issues"}

2. Second identical request shows correct response.

$ curl 'https://a.mapillary.com/v3/images/lxq56ufzLQp95QJeM2dt8w/detections?client_id=a1ZDQjR6X0RDUHN1TmtRVlpZSmlEdzplODBmYTQyNDdkODViN2I4'
{"message":"Unauthorized"}

### Expected behavior

Should not receive internal server error.

### Actual behavior

See above

**Comment by gyllen** [comment]
@ptpt ^^^

**Comment by ptpt** [comment]
Fixed.
