### ISSUE TITLE
Upside down sequence

### ISSUE THREAD

**Issue by trigpoint** [mapillary/mapillary_issues#2874]
In my area there are several sequences which are upside down, such as https://www.mapillary.com/app/?lat=52.68922206&lng=-2.58849243&z=17.97283578523094&pKey=1ftYBudvfTY82FFHRoE1EQ&focus=photo

They all seem to have been contributed by the same contributor. As they stand they are unusable.

Is there a mechanism by which they can be fixed or should they simply be deleted and reproduced?

Thanks

**Comment by katrinhumal** [comment]
Hi @trigpoint - please report these upside-down sequences via this form: https://goo.gl/forms/o2nCZrC2KKiezQJz1 and we'll make sure to fix them.
