### ISSUE TITLE
Mapillary for ArcGIS Pro

### ISSUE THREAD

**Issue by marsxul** [mapillary/mapillary_issues#2876]
### Basic information
* Platform: ` `Web`  and ArcGIS Pro
* Version: magp-inst-0.2.0 - installed version 0.8.1, ArcGIS Pro 2.0
* System/Browser: `Chrome'

### Steps to reproduce behavior

 1. installed the Mapillary add-in 
 2.  in ArcGIS Pro licensing, I enter my mapillary account
 3.

### Expected behavior
access to the mapillary data and editing data using the imagery
...

### Actual behavior
see screen shot

![image](https://user-images.githubusercontent.com/7337996/37233281-734a58bc-23a7-11e8-88d0-ef41dc05c244.png)

...

### Additional information

...

**Comment by marsxul** [comment]
I was set in the use ArcGIS pro in offline mode.  Once I disabled the offline mode, all the tools began to work.

**Comment by katrinhumal** [comment]
@marsxul Well done noticing this! Glad that it works.
