### ISSUE TITLE
Wrong usernames shown in Time Travel page description

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2877]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

The photo [r1tSm](https://www.mapillary.com/app/?focus=photo&pKey=r1tSmMnbLBBTdUkO10giMw) was taken by user fr@nco. The photo [Z5ufU](https://www.mapillary.com/app/?focus=photo&pKey=Z5ufUrdroGiqLI9DjRsmRw) was taken by user jdieser.

However, a [time travel between those two photos](https://www.mapillary.com/app/time-travel/?focus=photo&pKey=r1tSmMnbLBBTdUkO10giMw&cKey=Z5ufUrdroGiqLI9DjRsmRw&ttKeys%5B%5D=Z5ufUrdroGiqLI9DjRsmRw) shows this in the page metadata:

og:description = "Mapillary is a service where you can compare images over time.
These two images were taken by fr@nc0 at the times 1/28/2018, 12:06:32 PM and 3/1/2018, 9:12:51 PM"
og:title = "Compare Mapillary images from Argentina, by fr@nc0"

This is what it looks like in Telegram:
![Telegram screenshot](https://user-images.githubusercontent.com/101955/37686614-fc8aa62c-2c76-11e8-8be5-27a095a4eea3.png)

### Expected behavior

The description should mention both usernames.

### Actual behavior

The description makes it look like both pictures were taken by the same user.

**Comment by nicolas17** [comment]
By the way, I think this used to work ;)

**Comment by katrinhumal** [comment]
@nicolas17 I also remember this working. @gyllen might something have glitched during all the database work?

**Comment by gyllen** [comment]
@knikel Please escalate

**Comment by knikel** [comment]
`mapillary_issues` is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
