### ISSUE TITLE
notifications bug

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#2879]
### Basic information
* Platform:  `Web`
* System/Browser: `W7/Firefox`

### Steps to reproduce behavior

In my settings at https://www.mapillary.com/app/settings/notifications
 1. App push notifications are set to none
 2. e-mail notifications set to all (default)

### Expected behavior

E-mail notifications are expected

### Actual behavior

No e-mails received anymore

### Additional information

I would like to set update sequences off because it does not make sense to receive an email when a couple of photos are uploaded, some were submitted a few years ago!
I would like to keep notified with the weekly digest or user comments, but it is all or nothing.

**Comment by katrinhumal** [comment]
@ligfietser Thanks for reporting! I can confirm that the same applies to me. @knikel is looking into it.

Also, thanks for the request in the `Additional information`. We don't currently have plans to redo the way notification settings work but if we get there, we'll surely take this feedback into account.

**Comment by knikel** [comment]
`mapillary_issues` is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
