### ISSUE TITLE
Some photos are not visible on the map

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_issues#2881]
Example: https://www.mapillary.com/map/im/4_6fxft0jHXqfUb5OdMlIg

**Comment by katrinhumal** [comment]
@alexandrz This was probably a slight processing lag, I can open the image correctly right now - can you confirm the same?

Great sequence, by the way! 👍

**Comment by alexandrz** [comment]
Yes. Thank you!

**Comment by katrinhumal** [comment]
Great, thanks for checking! :)
