### ISSUE TITLE
Website: please off height measurement

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2886]
I would be so great if we could use Mapillary to make height measurements off photos. This would allow for lots of 3D mapping in OpenStreetMap.

See for reference: https://youtu.be/TkXL6gJ3e-E?t=56s

**Comment by katrinhumal** [comment]
@pbb72 Thanks for the suggestion! Unfortunately, we don't plan to start doing that any time soon. We know there is interest in this but it's not close to our focus areas.
