### ISSUE TITLE
 Mapillary Status 

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2887]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1.  Checking https://status.mapillary.com/
 2.  No data has been indexed for Image processing time for this time period yet.

### Expected behavior

Should see a Graph on that Position

### Actual behavior

Seeing No data has been indexed for Image processing time for this time period yet.

### Additional information

![image](https://user-images.githubusercontent.com/10342344/38348116-419bf39e-38a0-11e8-8291-ca4908fbff61.png)

**Comment by katrinhumal** [comment]
Thanks for reporting, not sure what happened there but it's back on track now. @gyllen knows better but I'm suspecting the gap might somehow be related to us migrating our backend.

**Comment by gyllen** [comment]
@thoschu96 Yes part of a big database upgrade we did (we just moved all data). Its back to normal now. Thanks for reporting.
