### ISSUE TITLE
Personal Feed not UpToDate

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2888]
### Basic information
* Platform:`Web`

### Steps to reproduce behavior

 1. Check your Personal Feed
 2. Seeing the Status how much Pending, Uploades are new etc

### Expected behavior

Currently no new Feed available. Seeing the old, but expecting the new Feed after the 3.April
Which i can see under the Upload Tab

### Actual behavior

No new Update under Feed

### Additional information

...

**Comment by katrinhumal** [comment]
@thoschu96 Thanks for reporting! We've been updating our backend and it's been affecting stats as well, which is why we sent out the weekly digest (feed item and email) later than usually this week. However, you should have it by now - can you confirm?

**Comment by katrinhumal** [comment]
Update - I was wrong in my previous comment. We might not be able to send out the weekly this week due to the database work. Sorry for this but after the update is done, the digest will definitely be back!

**Comment by thoschu96** [comment]
nope
just uploaded domr
and there is a gap in my list
i see them uploaded but nood on my list

Am 05.04.2018 um 16:57 schrieb katrinhumal <notifications@github.com<mailto:notifications@github.com>>:


Update - I was wrong in my previous comment. We might not be able to send out the weekly this week due to the database work. Sorry for this but after the update is done, the digest will definitely be back!

**Comment by katrinhumal** [comment]
@thoschu96 Could you share a link to the uploads that did not have an equivalent feed item?

**Comment by thoschu96** [comment]
Here is the link to the Upload where the Feed item is missing

https://www.mapillary.com/map/im/NOeWbvwGcpJCUP0imweS3w

**Comment by katrinhumal** [comment]
@thoschu96 Thanks! I'm afraid we can't recover the missing feed item. This has also been caused by the backend work, and similar might happen again in the near future until our database upgrade is all done. We're checking up on it as much as we can to avoid it, though. Also, I verified that the sequence is visible on your profile, which is good news. :)
