### ISSUE TITLE
What happened with the Mapillary Stats Website?

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2889]
Open https://www.mapillary.com/app/stats on multiple browsers and platform sources on 4/4/2018 as 23:55.

It looks like there had been some sort of damage.   The number of users I would expect to have over one million photos has been dramatically reduced including my stats.  If I click on my name, then I see the rounded number of 1.6M as I would expect.  On the phone application it says that I have 4,363 sequences.  I thought that it was less than than.  However, sequence cut has been running.  I am not sure if it has something to do with the problem or not. 

Also, it says that there are only two organizations on the org tab.  As I recall the org tab was nearing ten or over ten contributors.

**Comment by katrinhumal** [comment]
@drkludge Thanks for pointing this out. We made some updates to the backend and stats are still catching up. The team is looking into it though so hopefully back to normal soon.

**Comment by madelenarnesdotter** [comment]
@drkludge as you can see the stats are now back! Let us know if you ever experience any other issues!

**Comment by katrinhumal** [comment]
@drkludge you are right. We're sorry for wasting your time and will do our best to communicate known issues better.
