### ISSUE TITLE
Website uploader - Chrome "Something went wrong" when uploading photo 

### ISSUE THREAD

**Issue by houska2** [mapillary/mapillary_issues#2892]
### Basic information
* Platform:  `Web`
* System/Browser: `Debian Jessie, Linux Chrome browser  65.0.3325.181 64bit `

### Steps to reproduce behavior

 1. Login and visit www.mappilary.com/app/uploader/
 2. Choose file ("Browse files") 
 3. Fix location 
 4. Click on "Upload 1 images" 
 5. Wait (bar doesnt move) and after approx 1m browser shows "Aw, Snap!" error

- same problem is in porn mode 

![mapilary1](https://user-images.githubusercontent.com/38128730/38859329-12caa96a-422e-11e8-8100-f02127b0ce35.png)
![mapilary2](https://user-images.githubusercontent.com/38128730/38859330-12e2ad26-422e-11e8-947f-1c82dfa25f0f.png)
![mapilary3](https://user-images.githubusercontent.com/38128730/38859331-12fe8cf8-422e-11e8-9a4e-d95b20df82e6.png)

**Comment by houska2** [comment]
This problem is connected with one specific file. 
I was able to upload other files. 

Problem disappeard when I "convert" the file:
convert $file -quality 100 -rotate 0 rotated-$file

Are you interested to see the  file?

**Comment by katrinhumal** [comment]
@houska2 thanks for reporting and glad to hear you managed to overcome the problem. Feel free to provide the example file - which camera has it been taken with?

**Comment by katrinhumal** [comment]
Hi @houska2 - if this is still a problem, please email us at support@mapillary.com and include the file you're having trouble with. Closing here.
