### ISSUE TITLE
impossible to exit blurring mode

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2893]
### Basic information
* Platform: `Web`
* Version: `latest` 
* System/Browser: `Windows 10  up-to-date/ Firefox latest`
* JOSM with Mapillary plug-in

### Steps to reproduce behaviour

 1. Start editing OSM with JOSM with Mapillary plug-in active
 2. Select a Mapillary photo
 3. In the Mapillary plug-in's "Image info" window click "View in Browser"
 4. Mapillary opens the image in blurring edit mode with the warning text "Manual blurring is currently disabled" superimposed on the image
5. click "Exit Editor"

### Expected behaviour
exit Blurring Editor and return to normal viewing mode

### Actual behaviour
Mapillary web interface remains in blurring editor (with blurring disabled) 

### Additional information
This is annoying when editing OSM with Mapillary photos, as I have to keep open a second Mapillary window to view picture details, like date or author.

**Comment by katrinhumal** [comment]
@voschix thanks for reporting - I suspect that not only that there's a bug in trying to exit the blur mode, but it also sounds weird that viewing the image in browser would make it open in the blur mode instead of normal viewing mode. @gyllen any thoughts?

**Comment by gyllen** [comment]
@nickplesha This should be quick fix ^^

**Comment by voschix** [comment]
Any progress? For me the problem is still there.

**Comment by nickplesha** [comment]
Thanks for reporting @voschix ! This has been fixed.

**Comment by voschix** [comment]
Thanks.
Now there remains a last small bit to fix in the mapillary plugin for JOSM:
it should not open the photos in the blurring editor, but in normal view.

Volker
