### ISSUE TITLE
Angle of direction in drone pictures

### ISSUE THREAD

**Issue by dktue** [mapillary/mapillary_issues#2900]
Could you please consider the direction of the pictures I shoot with my DJI Spark?

I have attached a [sample file](https://user-images.githubusercontent.com/2878623/39244100-f3363566-488f-11e8-8bb0-b8dceafc0ee4.JPG) so you can go through the meta-data.

I checked the file [here](http://exif.regex.info/) and it shows the current angle of direction. 

![sample file](https://user-images.githubusercontent.com/2878623/39244100-f3363566-488f-11e8-8bb0-b8dceafc0ee4.JPG)

**Comment by katrinhumal** [comment]
@dktue thanks for reporting! Do you think it would help you to use the editor's "Normalize" command which makes every image "look towards" the next one in terms of the compass angle?

Read more here: https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences

**Comment by dktue** [comment]
Thanks for your response but I guess this feature would not help with panoramic sequences like this one:

https://www.mapillary.com/app/?lat=48.496944444444466&lng=9.140277777777783&z=17&pKey=FbsQC9yVKsqDPWgSYFlaIw&focus=photo

**Comment by katrinhumal** [comment]
Hm, this doesn't look like a panoramic (360°) image to me? But even for 360 images, you can still set the compass angle that you consider to be the "front" direction of the image.

**Comment by dktue** [comment]
I guess the best way would be to respect the angle provided in the meta-data of the images -- this way I could automatically upload them without worrying.

**Comment by ybkuang** [comment]
@dktue 
- For the compass angle, we use `GPSImgDirection` in the exif (see reference also [here](https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/GPS.html). 
- We assume that the viewing direction of the image is always the center of the image. The same holds for the 360 images.

**Comment by dktue** [comment]
@ybkuang: Would it bei possible to respect other fields as well so users can upload their pictures directly?

**Comment by ybkuang** [comment]
@dktue We also support `GPS GPSTrack`. can you help pointed out which other fields you are referring to? I can see flight/gimbal yaw in the exif

**Comment by dktue** [comment]
The field `Gimbal Yaw Degree` is exactly what I would like to have imported as direction in mapillary. Thanks for helping! :-)

**Comment by dktue** [comment]
Any updated on this? Will you interpret the `Gimbal Yaw Degree`?

**Comment by katrinhumal** [comment]
@ybkuang ^

**Comment by ybkuang** [comment]
@dktue we will take a look into this and when we can plan this into our `mapillary_tools`.  (cc @jernejaMislej  can you add this to our roadmap)

**Comment by jernejaMislej** [comment]
update: i have checked which tags are returned in exifread and that one is not one of them

there are work arounds to insert the value in a tag that is supported, but would have to think well before integrating that in the tools.
if an additional, separate script is enough, i am happy to provide one

**Comment by jernejaMislej** [comment]
@Kaldea cc @katrinhumal can you please help move this to tools issues if it is still relevant, since we are closing this

**Comment by ybkuang** [comment]
Closing this in favor of the issue in mapillary_tools
