### ISSUE TITLE
iOS-App: Crash when opening the settings

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_issues#2901]
The app crashes if opening the settings from:
- camera view (via gear symbol)
- user view (via gear symbol) 
And also in the upload tap. There its shortly showing the note “looking for external camera” and them crashes.

iOS 11.3, iPhone 6, App version 4.8.15

**Comment by millenbop** [comment]
Thanks for reporting!

I uploaded a new version last Friday. Does that version solve your problems?

**Comment by SchmidL** [comment]
Yes, is solved! :D

**Comment by millenbop** [comment]
Awesome! Closing :D
