### ISSUE TITLE
Weird blurring/smoothing Mapillary v. 3.122 Android on Redmi Note 4X

### ISSUE THREAD

**Issue by majkaz** [mapillary/mapillary_issues#2902]
I am getting weird photos taken with Redmi Note 4X (MIUI) using legacy camera settings, but different from #1931
Settings: Distance based capture, pause on shake, pause while tilting
Focus mode: Legacy_cam_0 infinity

The focus mode seems to be ignored, focus mostly at about 2-5 m distance:
In [this](https://drive.google.com/open?id=1t7uMIc6Sfs_8TVTvU0tjKcBLqmKKyvRa) photo, the asphalt is in focus, and there is this blurring on top I cannot explain.

[This photo](https://drive.google.com/open?id=1qAcGiCKYRAcJyggM-BOLtL0BSKbvAL8j) has the blurring problem as well. 

It looks to me like aggressive median smoothing only in parts of the image. The system camera doesn't have this problem, neither has OpenCamera nor Google Camera. The system camera is set to low sharpening, low contrast, should it make some difference.

Using camera2 api brings other problems on this device - it needs a bit hacking to use it and the phone has only partial camera2 api - the white balance doesn't work there. Thus, unless the photos are taken on sunny day, they get color cast over it. The focus problem mostly stays - the photos are often focused at near distance.

Finally, I have seen another problem on this device recently: Taking photos on bicycle gets in every sequence one or more photos upside down. This is true for both camera2 api as well as for legacy cam api.

**Comment by richlv** [comment]
Looks very much like motion blur, on a bicycle/motorcycle you'll need an action camera for proper photos.

See https://forum.mapillary.com/t/weirdly-blurred-original-images/465 .

**Comment by majkaz** [comment]
I still see it as Mapillary issue - the same phone doesn't have this issue using other apps for capturing images.

Something in the Mapillary settings is wrong for the intended usage.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
