### ISSUE TITLE
Cannot change image storage folder

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2903]
### Basic information
* Platform: `Android`
* Version: `3.124` 
* System/Browser: `Huawei Ascend G6-L11 rooted`

### Steps to reproduce behavior

 1. Go to Settings -> Storage -> Picture storage location 
 2. Tap the up arrow and choose a folder
 3. Tap confirm

### Expected behavior

Change the storage directory

### Actual behavior

The directory is unchanged

**Comment by katrinhumal** [comment]
@Alessandro-Barbieri Thanks for reporting, we'll have a look! cc @ovivoda

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
