### ISSUE TITLE
Roadroid stats overreported?

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2904]
I have long be number 1 in Norway, but now I have been overrun by Roadroid (which, as I understand it, is not a single user but all users of the Roadroid app together).

The weird thing is, they have never been close the being number 1, and now they suddenly have almost 4 times as many photos, according to the leaderboard (766k vs my 212k). They have been on number 1 for a few weeks now, with little increase in count. Their monthly increase is only minor (1.7k last month). And if I look at their contributions on the map, my rough estimate (it's very difficult to count photos) is 10k, at most 20k photos in Norway.

Are they contributing to a private project in Mapillary? (In this case, their counts should not be reported in the public leaderboard.) Or is there a Roadroid user that has been standing still, taking 100k's of photos somewhere? Or is there something wrong with the leaderboard statistics?

**Comment by pbb72** [comment]
More interesting, I checked all counties in Norway now, and the highest amount is 8.8k in Nordland. Nothing substantial anywhere else. So where are all those many 100-thousands of photos?

**Comment by katrinhumal** [comment]
@pbb72 That sounds really weird - we'll take a look!

**Comment by gyllen** [comment]
@pbb72 Thanks for reporting, we will take a look.

@peterneubauer Can you check in on this?

**Comment by pbb72** [comment]
Has anything been found out about this? They are currently at 7k photos uploaded this month in Norway, but I can not find any of those. Curiously, there are a few sessions near the Norwegian border, but they are all turning around before going into Norway.

**Comment by peterneubauer** [comment]
So,
I just found a bug regarding the video harvesting, I'm on it and hope to
get the videos visible soon. The have been harvested but are not visible.

**Comment by pbb72** [comment]
Aah, that sounds interesting, looking forward to see all that! 😃

**Comment by peterneubauer** [comment]
So, now, looking at the stats, it seems roadroid is not in there, but there are old photos from north of Norway. correct?

**Comment by pbb72** [comment]
I don't understand what you mean with "there are old photos from north of Norway".

Reported Norway total for Roadroid: 774.5k (me: 252.8k)

Roadroid numbers per county (mine in parentheses):
- Østfold: 0 (0)
- Akershus: 0 (12.4k)
- Oslo: 0 (13.1k)
- Hedmark: 76 (5.6k)
- Oppland: 0 (18.2k)
- Buskerud: 0 (2.4k)
- Vestfold: 0 (0)
- Telemark: 0 (0)
- Aust-Agder: 0 (0)
- Vest-Agder: 0 (0)
- Rogaland: 0 (0)
- Hordaland: 0 (2.9k)
- Sogn og Fjordane: 0 (154)
- Møre og Romsdal: 0 (0)
- Sør-Trøndelag: 252 (155.7k)
- Nord-Trøndelag: 14.1k (25.5k)
- Nordland: 8.8k (8.8k)
- Troms: 0 (6.3k)
- Finnmark: 0 (0)
- Svalbard: 0 (0)

If you sum these, you get a total of 23.2k for Roadroid, and 251.1k for me. That's 97% below the reported total for Roadroid, and 1% below my reported total.

So, where are those missing 751.3k Roadroid photos?

**Comment by peterneubauer** [comment]
Ok, these images seem to be somewhere else. I just checked - image https://www.mapillary.com/app/user/roadroid?lat=62.453802995909086&lng=18.865017048013442&z=5.05102832329827&pkey=gmfk4k821Rx05OTFZeYiAg&menu=false&pKey=gmfk4k821Rx05OTFZeYiAg&username%5B%5D=roadroid is reported to be in Norway by our database, but is in Sweden. @ptpt please take a look at this. Thanks @pbb72 - this looks like a bug.

**Comment by ptpt** [comment]
@pbb72 @peterneubauer our database counts a number of images in Sweden as images in Norway. We have submitted the bug there https://github.com/elastic/elasticsearch/issues/31048.

**Comment by pbb72** [comment]
This seems like a good lead! However, if this is the cause, then major parts of Sweden are being reported as Norway; Roadroid has 3.1 million photos in Sweden, and 750k overreported in Norway. That would mean that around 20% of their photos are misreported. This makes it weird that none of the other Swedish top contributors have large numbers in Norway.

Also, it will mean that these misreported photos are not located in any lower-level subdivision (county), because the total sum of Roadroids images in all of Sweden's counties does add up to their grand total.

One more thing I noticed that may be related. When you look at the leaderboard for Sweden, the map zooms to Sweden. But when you look at the leaderboard for Norway, the map zooms out to include the whole world! Are there any parts of the southern hemisphere that belong to Norway?

Still, any explanation of this bug that I can come up with, breaks down on the fact that it only seems to affect Roadroids numbers...

**Comment by ptpt** [comment]
@pbb72 according to https://github.com/elastic/elasticsearch/issues/31048#issuecomment-394283966 the match is not 100% accurate -- the images closer to the border are more likely be falsely included. So there must be some images are overrepoted in Norway. However 750k overreported seems to be too many. We will check with ELS to see if it's a configuration problem or a ELS bug.

Zooming to Norway shows the whole world is because of Bouvetøya, an island in the southern end.

**Comment by peterneubauer** [comment]
So the error then becomes 2% of the WHOLE shape, not of the different
polygons? Wow that for Island states and spread-out contries.

**Comment by pbb72** [comment]
Thanks, this makes a lot of sense! The node in the ELS bug report is placed over half of Jämtlands län away from Norway, and this would be an error of only 0.5%, and such a large section of Mapdroids photos are placed in Jämtlands län, then I can understand that 25% of their Swedish photos are also reported in Norway.

The other top players in Sweden have most of their photos much further away from Norway, which explains why they never show up in the Norwegian leaderboard.

So I guess the easiest solution is just to remove Bouvet island from Norway? :wink:

Shall I close this issue and open a new one on the precision of Elasticseach that is too course for spread-out countries?

**Comment by peterneubauer** [comment]
Yes please,
that is nothing we can fix right away, but maybe good to keep in mind.

**Comment by pbb72** [comment]
Closing, follow-up issue is #2953
