### ISSUE TITLE
Not created as a Sequence

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2905]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Checking own upload
 2.
 3.

### Expected behavior

Should be a Sequence and not all handled as single Picture

### Actual behavior

https://www.mapillary.com/app/user/chuck?lat=51.90594209997221&lng=1.8601800999999796&z=14.873743986513848&pKey=PYzmfucemQq3KWYCZBdWeg&focus=photo

![grafik](https://user-images.githubusercontent.com/10342344/39687643-b1ddcdb0-51cf-11e8-90ff-83d031510336.png)

### Additional information

Upload from a GoPro as a Sequence, but occure, that i got interpreted as Single Pictures

**Comment by mprins** [comment]
probably distance in between is larger than the sequence cut-off so they are split

**Comment by thoschu96** [comment]
is there an way to get them joined ?

**Comment by katrinhumal** [comment]
@thoschu96 we don't provide a way to join them again. And the automatic cut works on anything that's more than 300 m apart.
