### ISSUE TITLE
Problem with the GPS data in EXIF

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#2906]
I use a Samsung Galaxy S4 I9505. 
Sometimes the GPS data in the picture files are the same as in the picture before. Only the time data is right so I can use the gpx-file after deleting all GPS data in the pitures. But this isn't the right way. 

### Basic information
* Platform: ` | `Android` | ``
* Version: `.5.0.1
* System/Browser: `...`

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
