### ISSUE TITLE
resume android upload does not restrict files

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2908]
Android app 3.125
Upload one sequence
Upload was canceled somehow
Restarting the app asks "resume upload?"
Yes => all sequences on my phone are uploaded!

**Comment by katrinhumal** [comment]
@HolgerJeromin can you try if this happens with the latest app version, 3.126 as well? Also, please turn on the "Save debug logs to file" option in Settings > Developer, and when you manage to reproduce this behaviour, please send us the logs.

**Comment by katrinhumal** [comment]
@HolgerJeromin if this is still an issue, please send us an update to support@mapillary.com - logs would help a lot!
