### ISSUE TITLE
"fixed focus at infinity" mode doesnt appear on my phone

### ISSUE THREAD

**Issue by raditisa** [mapillary/mapillary_issues#2910]
Hi Dev,

i installed the app for my project, and i tried to set my focus mode but the option doesn't appear.

Thank you,
Raditia

### Basic information
* Platform:  `Android`
* Version: `7.0 Nougat

` 
* System/Browser: 

### Steps to reproduce behavior

 1. set the focus mode 
 2. "fixed focus at infinity" mode doesn't appear 

### Expected behavior

"fixed focus at infinity" option appears 
![unnamed](https://user-images.githubusercontent.com/33948550/40092850-abad1da8-58e9-11e8-9e95-6459d03d8660.jpg)

### Actual behavior

"fixed focus at infinity" doesn't appear 
![whatsapp image 2018-05-15 at 21 25 40](https://user-images.githubusercontent.com/33948550/40092855-afd04cb6-58e9-11e8-9743-57aec5f6276b.jpeg)

**Comment by ovivoda** [comment]
@raditisa The screenshots are both from same device and same application version?

**Comment by raditisa** [comment]
i am sorry for the late replay. no, they are from different phone. the first picture is from my friend's phone. and the second one is from xiaomi. maybe the app detect phone's specifications and adjust the focus menu?

**Comment by ovivoda** [comment]
@raditisa Indeed the app reads the focus modes available for that phone model and displays only the ones available.
