### ISSUE TITLE
Allow playback of maps in ios

### ISSUE THREAD

**Issue by hinxx** [mapillary/mapillary_issues#2911]
When map is finished playing one can only frame-step back. Why not have replay?

**Comment by katrinhumal** [comment]
@hinxx Hi and thanks for your request! We don't currently plan to add more playback options to the mobile apps. However, there are options on the Mapillary web (mapillary.com/app) to reverse playback and/or navigate quickly back to the beginning of the sequence. See more information here: https://help.mapillary.com/hc/en-us/articles/115001662325-Mapillary-for-the-Web#navigation

Closing issue as it won't be fixed for now but I'll also pass your feedback to the team so we can consider this in the future.
