### ISSUE TITLE
Keep it more up to date

### ISSUE THREAD

**Issue by hinxx** [mapillary/mapillary_issues#2913]
Very nice feature, featured that is. Keep it more updated if possible.. thanks!

**Comment by danbjoseph** [comment]
what part of mapillary are you asking to be kept more updated?

**Comment by katrinhumal** [comment]
@hinxx Do you mean the featured images list in the iOS app?

**Comment by katrinhumal** [comment]
@hinxx Thanks for clarifying! It's true that we don't update it very often but we do sometimes so it's worth checking out every once in a while. :) We'll take your note into consideration!
