### ISSUE TITLE
Android app Super-crashy today

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2914]
### Basic information
* Platform: Android 7.0
* Version: Mapillary app 3.126, and whatever the previous release was
* System/Browser: Samsung Galaxy S7 Edge

Note 1:  My normal image frequency settings are 3m distance threshold, with 0.3s minimum delay between images.  This is what I've been using successfully for many months.  I believe this is highly relevant information, as  you'll see below.

Note 2:  I have the app configured to write to external SD.  I simply don't have enough free space on internal storage for anything but a single, short sequence.

Note 3:  I e-mailed in several sets of trace logs earlier.  In the body, they all talk about "crashy" or "crashyness".  The last one I sent in is also the largest, and I'm going to open 2 or 3 issues for which that log should be useful.

Note 4:  Today is the first time I used an external Bluetooth GPS receiver (Garmin GLO) with the app.  I have enabled Mock GPS on my phone, and am using the Bluetooth GPS app, as has been noted in many places as necessary, including the Mapillary forum.  I was tired of my image traces on the website map being all over the place.  Don't know if that matters to the issue or not.

Note 5:  For the past few weeks, I've experienced occasional crashes while uploading imagery.  I'll create a separate GitHub issue for this next week, with a trace log, since that's a separate function in the app, and I don't know that it is related to what I'm describing here.

I started out with the previous release version (sorry, don't remember what that was).  Went out for a drive today to find certain specific places, and since a lot of the roads hadn't been explored of course I Mapillaried them.  The app crashed frequently, usually after around 50-150 images had been taken (every couple of miles?).  It was happening so much, that I was considering giving up.  Partway into my drive, I updated the app to 3.126, hoping that would help.  It didn't; the crashes kept coming.

By "crashes" I mean the app exited and I was back on my phone's desktop with the Android popup that the app had crashed, and offering me the choice to restart it or send feedback (I sent feedback once, it also mentions being crashy).  Restarting it worked fine, until the next crash.

When I reached one of the roads I was out to explore, I had to slow down to <15mph due to the roughness of the road.  I noted that I was able to reach almost the very end, with about 450 images taken, before I had any problems again.  The app didn't crash, but it looked like it had stopped taking pictures.

It occurred to me that "speed" might be the factor.  Whether it is my vehicle speed, the speed at which images were being taken, or the speed at which they were being written to the SD card, I'm not sure.  (Remember: I started the day with the previous version, which had worked fine last weekend and before that, but had serious problems *today* for whatever reason.)

I changed my settings to take a picture every 5m, with a 0.5s minimum delay.  That seemed to work for a short while, but I still experienced several crashes.  I increased the frequency to 10m, left the delay at 0.5s.  While I still experienced some crashes, _the frequency of the crashes was greatly reduced, and my sequence lengths regularly rose into the _hundreds!__

I left these settings in place for the rest of the day.  While crashes did happen some more, the frequency was low enough that they were endurable.

I will further note that until today, I hadn't really had too many app-crash problems with my 3m/0.3s settings in place.  I don't know what changed, other than my introduction of the Garmin GLO.

I know that the last trace log I e-mailed in is huge, but as I upload sequences, I should be able to point to specific ones that you can use to find the correct time frame in the log to examine.  If there is something in the log that interests you, please let me know the time stamps, and I'll prioritize uploading sequences close to that.

Please let me know if you have any questions or need more information.

Other issue: 
I will close my mentioning that I've had certain other picture-taking problems that I haven't documented, mainly because they weren't disastrous, and also because getting trace logs for them hasn't been easy (they were rare enough that I either didn't have trace logs enabled because I'd given up, or because the logs that I did have were *so* large that I didn't think you could use them).  The last trace log that I e-mailed in today (about 8MB) should have something for this other issue.  I will open a GitHub ticket on it, and early in the work week will try to prioritize uploading relevant image sequences.  Hopefully the images that I point out will help you find the relevant sections in the large trace log.  Just hang on to it until I get all of the information documented in another case.

**Comment by katrinhumal** [comment]
@ovivoda Can you please take a look at this, together with the logs that have been sent in?

**Comment by echeloni2p** [comment]
Hey

those seems not to be crashes, just android waiting for the SD card to write the data.
Use faster storage/only internal storage to get rid of those.
Or reduce the amount of data written, aka less pictures.

echelon

**Comment by jfburke3** [comment]
When the app exits unexpectedly and you end up back on the phone's desktop with a message on screen that says the app has crashed, it is a crash.

This is the same SD card I've been using for the past few years.  It is only very recently that there have been problems like this.

**Comment by echeloni2p** [comment]
Hey
esp. as the SD card is old, it may break a lot due to age and data writing/deleting, writing again.
CD Cards do fragment a lot and this reduces speed, so mapillary cannot save data as fast as it used to be.
Maybe you try another card?
And my mapillary did tell me more than a dozen time "app seems to be crashed" while it was just trying to access the sd card. I waited a bit longer and it worked on flawless. 

echelon

**Comment by jfburke3** [comment]
If it were a card problem, I would expect to see problems with other apps and items, but I don't.  Specific things that do not appear to have a problem with the SD card are...everything else except the Mapillary app.

I can record UHD video to the card with no issues, and playback presents no problem, either.  Even within the Mapillary app, there are certain functions that should have issues if it were the card, but don't.  Specifically, when the app reaches its hard-coded 600-image-per-sequence limit, it very quickly stops the sequence then starts a new one.  However, if I manually stop a sequence, there is a very long delay before I can start a new one (see issue #2920 that I opened today).  If the card were the issue, then why is the app's hard-coded limit not having the same problem?

If anyone is curious, my SD card is a Samsung EVO+ 256GB UHS-1 microSDXC U3.  (NOT the "Select" line, and it is UHS-1, not UHS-3, which should still be plenty fast.)

**Comment by jfburke3** [comment]
@ovivoda I don't know if this is relevant to this issue or not, but I will note this.

Yesterday when I was driving home from an excursion, late in the day I noticed that the app was stopping sequences after only 30-60 images, then starting new ones.  Unfortunately I was in heavy traffic and couldn't watch the screen well, but I caught a glimpse of message that mentioned something about sequence error, image capture continues, or something like that.  I've seen this before, but it has been pretty rare.  In this instance, I had it happen a dozen times in a row, or more.

Unfortunately, I don't have trace logs on it.

**Comment by echeloni2p** [comment]
Hi

simple: mapillary works different than other apps on the sd card.
A video is a simple stream to save/read, mapillary writes:
a) one file for GPX data, aka: open file, write data, close file, open file, write data, close file
b) each simple image as a single file, aka: open storage, write picture, change FS on sd card, close  storage, and back to start.
Thats why a card getas very fast very fragmented with long time usage of mapillary, each picture is a single file.
The long delays are also associated with storage. One reason is a built in cache (aka take picture, write to cache, move to storage), also the two threads for GPX and picture storage needs to be in sync, this happens after pressing the stop button.
Also the android system tries to generate thumbnails of each picture, you can see this delay on startup of mapillary and/or change into the "upload" folder - the more picturesa re in, the longer it takes for mapillary to respond. I do often have >5k pictures in, it takes ages to restart mapillary, as it tries to check the storage for all pictures and thumbnail them. The slower the SD card, the longer it takes. Thats why internal storage is far better.

To be clear: mapillary may break for a lot of reason, esp. as the syncing of two threads is not a simple task, but it looks a bit like a sd card issue for me.
Does this all happen with internal storage, to?
Ever checked another sd card? Those are really cheap, 50€ per 128GB or around, easy to test.

(also android is not made for mapillary, it is not a usual case the mobile brands do test and work for. taking a zillion of pictures with GPS data and save to a storage over a long time is not the usual user case for them, thats why the APIs are still buggy, some more, some less. Depending on the company, e.g. samsung has modificated a lot, while other do not change much)

echelon

**Comment by jfburke3** [comment]
@echeloni2p I have 805 MB of free space on internal storage right now. Pretty much all of that is system/apps. I keep all my data on SD.

I understand why the SD card is what you suspect.  It was my first suspicion, too. However, I am just not able to reconcile that with how the card behaves with anything else. And again, please note that I  DO NOT see the long delays when the app does its 600-image sequence restart. If it were the SD card, I should see a long delay there, too. 

Another test would be to figure out about when this started happening and try an earlier version of the Mapillary app.  My perception is that problems started around the time that stricter GPS code was implemented in the app. What version was that, and can I download a previous one?

**Comment by jfburke3** [comment]
On the subject of previous app versions, let me note that before @ovivoda  joined, there were several releases which had severe GPS lock problems. That was one of the early things he fixed. So, if im going to try an older app version, I'd like it to at least be one that he fixed that problem in.

**Comment by ovivoda** [comment]
@jfburke3 please try v3.53

**Comment by jfburke3** [comment]
@ovivoda Ok, but not sure what the URL is for old versions. I probably have it, just need to find it. 

In a separate issue you mentioned that 3.127 had been released. I installed it yesterday and did some sequences with 5m for my distance-between-images setting,  and my perception is that it was more stable.  I see that 3.128 is out, so I'll try that one today (will have lots of driving time).  And of course I'll try 3.53 as soon as I can.

**Comment by jfburke3** [comment]
Ah, found the download page.  http://android-releases.mapillary.io/

I'll download 3.53 on my phone and try it as soon as I can.  I want to get as many of my 141 sequences uploaded as I can before I do....

**Comment by jfburke3** [comment]
Welp, my phone was just force-updated to Android 8.0.  :-(  I guess I'll find out if that changes the nature of how the app works soon enough.

**Comment by jfburke3** [comment]
Ok, so I have an update....

The problem as originally described appears to be gone now.

My phone wouldn't let me install 3.53 over 3.128, so I had to uninstall 3.128 first (and I lost 35,000+ images in 175+ sequences because I stupidly didn't make a copy first--this may or may not be important to the problem).

Installed 3.53, which was dreadfully unusable.  When I tried to take sequences, it would crash after 2-15 images.  I'm going to attribute this to incompatibility with Android 8.0, since I'm pretty sure 3.53 was released before Android 8, and probably was never tested against it.

I was able to do some limited testing despite the crashes, and was able to stop & start sequences easily and with no delay.

I reinstalled 3.128 over 3.53, and to my surprise, was able to stop/start sequences easily and with no delay.

So, I'm going to attribute the "fix" as an uninstall/reinstall, since I've pretty much just been installing new versions over old ones for a long time.  If this is what fixed it, then I'll just have to guess that old settings garbage leftover from previous versions was causing problems.

Alternate explanation:  3.128, and other recent versions, simply have a hard time handling/indexing/manipulating a lot of sequences.  I have 49 sequences on my phone right now that I'm uploading; if I can, next weekend I'll try to get my sequence and image count up high again, although that might have to wait for my next trip out of town, and see how the app reacts.  If the problem comes back.....

I will note that not ALL of the problems I've reported have been fixed, just this one.  And, an old one *might* have come back-- @ovivoda , one of the first things you fixed was a pretty bad GPS lock problem, and while I was using 3.128 yesteray after my 3.53 tests, I saw hints that this one might have returned.  After I upload my current sequences, I'm going to uninstall 3.128, reboot, and then reinstall it so that it isn't an "upgrade" from 3.53, in case there's something from 3.53 hanging around that is causing the problem.  Note 1:  while the GPS problem _might_ have been weather related because it there were some storms in the area, I don't think this was the case, because other GPS apps on my phone were reporting decent accuracy numbers.  Note 2:  I've started using an external Bluetooth GPS receiver with the Mock GPS provider settings on my phone enabled.  With detailed stats enabled, *sometimes* the 3.128 app would show Mock GPS Provider at the end of the stats line, and sometimes it wouldn't.  Before I started the tests with 3.53, I think it always showed that (once I started using the external receiver).

**Comment by drkludge** [comment]
Just to confirm, it is not the memory card.  As I point out in 
 issue https://github.com/mapillary/mapillary_issues/issues/2930, the current application is not suitable for a Note 8.  Like @jfburke3  pointed out, my phone was upgraded to Android 8.0.  If it was the memory card then I would have had the same problems with the older app.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
