### ISSUE TITLE
No images to upload

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2915]
### Basic information
* Platform: Android 7.0
* Version: Mapillary 3.126
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Go to the Upload screen.  
 2. Open a single track to upload.  
 3. Upload it.

### Expected behavior

At the end up the upload, the app should return to the list-of-sequences-to-upload, as it has done in the past.

### Actual behavior

Sometimes it does.  Other times I get a blank list with the message "no images to upload."

### Additional information

Exiting completely from the app, then going back in to the Upload screen will show me my remaining sequences.

**Comment by katrinhumal** [comment]
Thanks for reporting! @ovivoda can you take a look please?

**Comment by jfburke3** [comment]
I'm going to mention this here because I *think* it is related:  I've also noticed that the latest app version reports a different number of sequences if I start an "upload all" then later cancel it and exit the app, then go back in and start the "upload all" again.  And by different number of sequences, I don't mean that it is a reasonably smaller number--it seems to be all over the place (smaller, much smaller, larger, etc.).

**Comment by jfburke3** [comment]
I should note that as problems go, this is fairly minor, and exiting/restarting is a perfectly working workaround. I'm mentioning it in case it has some bearing on the other issues I logged. Feel free to close this one if the information provided is all you needed to know.

**Comment by SK53** [comment]
Still seems to be happening on 3.1.28 (Android 5.0.2)

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
