### ISSUE TITLE
Published sequence not on map

### ISSUE THREAD

**Issue by jaku103** [mapillary/mapillary_issues#2916]
### Basic information
* Platform:  `Android`
* Version: `3.126` 

### Expected behavior

Captured and uploaded sequences should appear on map after notification they were ready. 

### Actual behavior

Images, and sequences not on map.

### Additional information

After uploading two sequences that were uploaded during the time that your status page said, "maintenance and data migration in Mapillary backend,"  images have never been fully processed. This happened on May 22nd.

4NlSLvUSq5VV2k6x-1ylmg
fY9VNPk_yT8BmByYuAHzyg

**Comment by katrinhumal** [comment]
Hi @jaku103 - thanks for reporting! I believe this is still an aftermath of the backend maintenance. You should not get notifications before things are fully processed, so we're going to try and fix that in the future. But for the images themselves, can we please wait and see how this proceeds over the weekend? I'm fairly sure things will clear up in a few days.

**Comment by jaku103** [comment]
Thanks for your help, it looks like they are just beginning to show up on the map.

**Comment by katrinhumal** [comment]
@jaku103 great, thanks for confirming! I have the same going on for myself, actually - uploaded some days ago and they're just coming in bit by bit. I'm closing this issue for now, if eventually it seems like something is still missing, feel free to reopen.
