### ISSUE TITLE
iOS rotation issue

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#292]
![image](https://cloud.githubusercontent.com/assets/82719/3985453/b7962cae-2891-11e4-853b-3076503d24d2.jpg)

I managed to get the iPad to display in portrait, even so it was horizontal and the images appeared to be recording with the expected horizontal rotation.

The next time I recorded images, the screen was landscape as expected.

**Comment by jesolem** [comment]
Hi @smsm1 - can we close this?

**Comment by smsm1** [comment]
Yes, I tried to reproduce at the weekend on my iPad and couldn't. Can open again if I come across it in the future.
