### ISSUE TITLE
Manually stopping a sequence then starting a new one has a long hang time (Android)

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2920]
### Basic information
* Platform: Android 7.0
* Version: Mapillary 3.126 (but I think I first started noticing it around the same time you introduced stricter GPS monitoring)
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Start taking a sequence.
 2.  Press stop.
 3.  Wait 20-30 seconds (or more) before the Start button is available.

### Expected behavior

The app should return to user control within a reasonable amount of time, like it used to many versions ago.

### Actual behavior

The app hangs for more than 20 seconds, frequently longer than 30 seconds.

### Additional information

When the app reaches its hardcoded 600 image max-per-sequence and starts a new sequence, it does NOT hang like this.  At most, it only takes 5 or so seconds to start the new sequence.  For this reason, I don't think it can be an Android filesystem issue.

If you want trace logs for this, let me know.  It isn't difficult to reproduce.

**Comment by ovivoda** [comment]
@jfburke3 I could not reproduce this issue on the latest app version v3.128 . Is this still an issue on your end? If so please record the logs and send them over.

**Comment by jfburke3** [comment]
This also seems to have been fixed by what I did when playing with 3.53 (ref my comments on #2914).
