### ISSUE TITLE
Hidden images in sequence with strange sequence number

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2921]
### Basic information
* Platform: `Web`
* Version: `latest` 
* System/Browser: `Windows 10` `Firefox` 

### Steps to reproduce behavior
I don't know how to reproduce the error.

### Note
From the symptoms it may be related to error #1851

### Description
I managed to insert some "hidden" photos in the Mapillary data base that don't show up on the Mapillary map, but there are strong indications that they are only hidden in the the data base with invalid sequence number(s)

### Details
The photos where taken on 20 May 2018 between 16:18 (last visible photo of the previous sequence is [this](https://www.mapillary.com/map/im/6p1A-FSPrGg01xD4TTe4VQ) and 17:45 (first photo of the next visible sequence is [this](https://www.mapillary.com/map/im/im3xBQgY0tJZY4zDMqlHyA).
The photos before and after are visible in the normal way.

They were taken along [this GPX track](https://www.openstreetmap.org/user/voschix/traces/2718436) (recorded with separate GPX device)

The photos were shot and uploaded with the Mapillary App 3.126 on a Sony Z3 compact (model D5803) with Android 6.0.1

With some luck I can click the hidden photos on the Mapillary green-line map as long as they are interspersed with photos from a visible sequence by another user that follows the same road (in this case sequence 17DYaOmodS5cmjfaSbh7sA by user “emicall”).

This is one of the hidden photos:
[https://www.mapillary.com/map/im/i6WLI83NWtaZuUgccnENGw](https://www.mapillary.com/map/im/i6WLI83NWtaZuUgccnENGw)
I noticed that it seems to have an invalid sequence key:
[https://www.mapillary.com/map/s/6d380029-c0f0-4e0f-ad7e-4f1e62d9eeed](https://www.mapillary.com/map/im/i6WLI83NWtaZuUgccnENGw).

This is another one:
[https://www.mapillary.com/map/im/5VJ19DXmPeRLxuZwD07rfA](https://www.mapillary.com/map/im/5VJ19DXmPeRLxuZwD07rfA)
with the same invalid sequence key:
6d380029-c0f0-4e0f-ad7e-4f1e62d9eeed

**Comment by voschix** [comment]
On 30 May 2018 at 16:23, drkludge <notifications@github.com> wrote:

> The photos where taken on 20 May 2018 between 16:18 (last visible photo of
> the previous sequence is this and 17:45 (first photo of the next visible
> sequence is this.
> The photos before and after are visible in the normal way.
>
> Your OSM GPX trace says that there were 14,083 points and I presume a
> matching 14,083 pictures in the trace.
>
No the numbers are not expected to match, the GPX trace and the Mapillary
photos were taken with two independent devices: etrex 20 for the GPX track
and Android app for Mapillary.
The etrex was set to 1 sec and ran continuously. The App was set to one
photo every two seconds, but it stopped several times, and when it worked
it stuttered and produced photos at irregular intervals (that's another
problem I have ...).

> If you have your your notifications set to default, is there any chance
> you received a note that sequence cut edited some of your photos? I feels
> like sequence cut makes a mess of these tracks.
>
I have a large number of successful-publication messages, bot no message
that @sequence_cut helped out.

But; your mentioning of sequence_cut is perhaps a good lead, as all the
hidden images that I managed to click and view had the sequence navigation
(at the top of the images) greyed out, which could indicate that
@sequence_cut has chopped up the sequence(s) in single photos.
Does the strange (longer) sequence key of the hidden images give you any
hint in that direction?

Concerning recovery (I have no backups):
if you could extract all my hidden photos as originals (you have the time
bracket) and send them to me, I could georeference them from the
independent GPX track and upload them manually.

**Comment by voschix** [comment]
The missing photos have just been published as a single sequence 6d380029-c0f0-4e0f-ad7e-4f1e62d9eeed

**Comment by gyllen** [comment]
@voschix Does this mean that all of your images are now visible on Mapillary?

**Comment by voschix** [comment]
I think, yes.
There may small wholes in places, but that is difficult to verify. I
noticed that after a bigger upload often small bits are loaded much later.
This specific case seems to be of the same category, only that it regarded
an entire sequence this time and an entire week delay, and that I detected
some of the missing pictures and noticed the strange sequence numbers.
If you know hat happened I think this specific case should be closed. I
left the decision to close it to you.
Y

**Comment by gyllen** [comment]
@voschix We are doing some restructuring in the processing backend that might cause this error. After the upgrade things will run smoother, so apologies for the strange updates....

@peterneubauer The key looks strange here too ^^^

**Comment by peterneubauer** [comment]
Hi there,
all of the above images are now visible - we had some hickups when restructuring in the backend, and are catching up on that now. The sequence-id is correct - this is beause for new sequences, we switched to full UUIDs (https://stackoverflow.com/questions/45388021/java-util-uuid-randomuuid-tostring-length?rq=1) since there is starting to be quite a lot of data :)
