### ISSUE TITLE
Webuploader: 1000 files failed to upload

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2922]
### Basic information
* Platform: Web
* Version: https://www.mapillary.com/app/uploader
* System: Windows 10, version 1803
* Browser: Google Chrome, Version 67.0.3396.62 (Official Build) (64-bit)

### Steps to reproduce behavior

Upload sequence of 1000 Images

### Expected behavior

Upload sequence of 1000 Images and Publish upload

### Actual behavior

Yesterday:
- 1000 files failed to upload
- Exit Uploader...
- Opening Upload is not possible anymore ("Browse Files" won't show)
- Pending images = 10293 and not changing

Today (after 24 hours):
- Pending images = 10293 and not changing
- Opening Upload is possible, "Browse Files" will show
- Select same files (again)
- 1000 files failed to upload
- Exit Uploader...
- Opening Upload is possible, "Browse Files" will show...
- Selecting a different sequence for upload and uploading 1 image does not resolve:
1 file failed to upload

Update:
- Pending images = 9948 so processing has restarted...
- Retry to upload in a few hours...

### Additional information

![image](https://user-images.githubusercontent.com/20150550/40839437-da16b526-65a2-11e8-8d0f-8b470383ee2e.png)

![image](https://user-images.githubusercontent.com/20150550/40839765-1ab699f6-65a4-11e8-9300-66f2c364b4f9.png)

**Comment by katrinhumal** [comment]
Hi @AnkEric - thanks for reporting, we're working on this and hope to fix it soon. Stay tuned!

**Comment by AnkEric** [comment]
Issue has been resolved!
