### ISSUE TITLE
Status tools for big uploaders?

### ISSUE THREAD

**Issue by bob3bob3** [mapillary/mapillary_issues#2926]
I am part way through uploading about 2 years of drive images. (still using the older tools) At about the 200K point with maybe 800K to go.

I'd like to get an idea of the probable processing time for large runs. I am of course getting a lot of email alerts, but they keep coming days after the upload. I'd like to get an overall idea of where they are up to. "Pending images" doesn't seem to give me real numbers.

One of my concerns are what appear to be missing sequences (gaps) in the map. How do I know if they are really "stuck" or "missing" beyond just waiting?

Web interface, Debian 8 platform.

Tnx

**Comment by cookry** [comment]
@bob3bob3 have you tried our new Command Line Tools? These are tailored to streamline your upload workflow and provide a status on the upload status: https://blog.mapillary.com/update/2018/05/31/updated-upload-tools.html

**Comment by bob3bob3** [comment]
@cookry yes I have. I have to be careful though to put as much as possible into a virtual environment as the process is run from a remote production machine that I only physically visit every 2-3 months to exchange USB drives. (containing run code as well as data) The older tools were strong on that, but the new ones seem to be more sudo oriented.

I am assuming that the pip commands for Piexif and mapillary_tools will run under virtual but have yet to try. README.md is a bit vague on this. I'll try it all soon.

**Comment by cookry** [comment]
@bob3bob3 I am moving this to the mapillary_tools repo where we can better address.

**Comment by cookry** [comment]
Issue moved to [mapillary/mapillary_tools #243](https://github.com/mapillary/mapillary_tools/issues/243) via [**ZenHub**](https://www.zenhub.com/)
