### ISSUE TITLE
[Traffic_signs recognition]: AI says minimum speed when it is advisory speed

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2927]
Hi, 
I don't know where to put this so I put it here, Mapillary people would move to whom is the responsible
You have done well job with traffic signs recognition and their output, also start again to people play to recognise traffic signs.

In Spain (and I think in other countries) you will have a problem:

Your AI recognise a blue rounded traffic sign (Minimum speed in lot of countries, also Spain) while it is blue SQUARED traffic sign (advisory speed in lot of countries, also Spain).

As I tag traafic signs in OSM the translation in tags are

Your AI says
minspeed:backward=50
side=left
traffic_sign:backward=ES:R411
traffic_sign=minspeed

https://es.wikipedia.org/wiki/Anexo:Se%C3%B1ales_de_tr%C3%A1fico_de_reglamentaci%C3%B3n_de_Espa%C3%B1a#/media/File:Se%C3%B1al_r411_velocidad_m%C3%ADnima.svg))

while it REALLY is

maxspeed:advisory=60
side=left
traffic_sign:backward=ES:S7
traffic_sign=maxspeed:advisory

https://es.wikipedia.org/wiki/Anexo:Se%C3%B1ales_de_tr%C3%A1fico_de_indicaci%C3%B3n_de_Espa%C3%B1a#/media/File:Spain_traffic_signal_s7.png

Please make an specific verification project in https://www.mapillary.com/verification/projects
Thanks

**Comment by ybkuang** [comment]
@yopaseopor thanks for the feedback! We will create a verification project for this soon.

**Comment by tobias-o** [comment]
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

We will create a verification project once the new traffic sign recognition has been applied to all images. See here https://blog.mapillary.com/update/2018/06/15/global-sign.html for more details.
