### ISSUE TITLE
[IA recognition] Please make a game app

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#2928]
Now I see your IA start to recognize trademarks, logos, (while it stills with my favorite : traffic_signs). Please make a recognition and verification game app for smartphone. It is addictive.

**Comment by madelenarnesdotter** [comment]
@yopaseopor So happy to hear that you're having fun with our traffic signs (just keep it on a healthy level) :D - I've forwarded your request to the team and we'll hopefully be able to create more verification tasks that you can participate in. We do not have plans on making a standalone app - but I will bring your idea to the team. Thanks for sharing your ideas, keep them coming!
