### ISSUE TITLE
Dex is not supported.  Mapillary presumes that only Wifi will be available.

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2929]
### Basic information
* Platform: `Android`
* Version: `3.44 to current` 

### Steps to reproduce behavior

 1. Plug phone into Dex
 2.  Try to upload images.

### Expected behavior

That I would be able to use Ethernet to update load images.

### Actual behavior

eth0 is not recognized.

### Additional information

![image](https://user-images.githubusercontent.com/1669057/41197079-6fe9167a-6c06-11e8-9213-0f35030cee96.png)

It looks like you don't even need the Samsung Dex Hardware.  [Here's a Youtube video showing an elegant kludge of cables and dongles for the same effect.](https://www.youtube.com/watch?v=s50GWuKphTI)

**Comment by Kaldea** [comment]
Hi!

Thanks for bringing this up. At this time we haven't tested this functionality yet but will keep this in mind for future development. I'm forwarding this suggestion to the devs to look over. 

Thanks again!
