### ISSUE TITLE
Version 3.127 code version 427 is unsuitable for Samsung Note 8.  Reverted to 3.44 code version 3.44.

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2930]
### Basic information
* Platform: `Android` 
* Version: `3.44 and 4.27` 

### Steps to reproduce behavior

 1. I have the Android automatic application upgrade feature on my phone turned off.  I manually upgraded to 4.27.

### Expected behavior

I should be able to finally upgrade and use the latest Mapillary version.

### Actual behavior

Screen is unresponsive with multiple hangs.  Capture failed to continue then would magically startup again.  Reverted back to Mapillary3.44.apk file to correct the problem.

### Additional information

I have two phones that I used for Mapillary captures.  One is for the dash.  It is a Samsung ON5.  The other is a note 8 that I use for side captures. Both phones have automatic upgrades turned off.  Hence, I have been on 3.44 for a long time.  I accidentally upgraded the ON5 to the latest.  I was pleasantly surprised that the application worked well.

This last week I got backed up with 30,000 images.  I could not upload the images overnight.  It took forever to start the upload with 30,000 images in 140 sequences.   I tried 4.27 but found the experience worse yet.  I could not even try to upload a sequence of 140 images without failure.  I would then restart the upload until I finally had all 140 images uploaded.  I then it was onto the next sequence with the same experience.  Moreover, with each failure, I sent--I am guessing Google--feedback.  The image provides the constant message that I experienced.

![image](https://user-images.githubusercontent.com/1669057/41198023-660d5f54-6c23-11e8-855b-e2ba34b03ca0.png)

Capture with 4.27 was abysmal.   I was planning a long drive where I normally capture 5,000 images.  I came home with less than 700 images.

In addition to these items, the whole user experience was sluggish.  I received similar kill messages as shown above asking if I wanted to wait for Mapillary or kill the application when trying to access the Upload tab.

I finally reverted back to 3.44.  Happy days are here again.  Yes there are few things like the Profile Tab failing to update.  However, I have the Samsung ON5 for the feature.  The way I have found to fix the application getting overwhelmed with 30,000 images at this point, is to move the images out of the capture folder.  I can then move back, say, 4,000, images in a number of sequences.  I can then upload those images.  I can upload all the sequences in one go verses nursing along each sequence as I had to do with 4.27.  [I recognize the part of the problem is that I am shooting high quality side view images](https://github.com/mapillary/mapillary_issues/issues/2481#issuecomment-396012005).  I would have 20,000 image still pending to upload.  I'd go back out for another run and be back up to 25,000 images again.  I think I can live with 3.44 and move image folders around until the Samsung Note 8 and I am guessing later Android versions have better support with Mapillary.  Oh!  I was also hoping that I cloud use Dex and Ethernet on the phone to solve the high quality image upload issue.  [There is an issue with the Mapillary application thinking that only wifi is available on the phone.](https://github.com/mapillary/mapillary_issues/issues/2929)

**Comment by echeloni2p** [comment]
HI
3.128 is latest version of mapillary, far far beyond your version. It has a lot of fixed issues and far better track handling, for me it works quite well.
The error you describe seems to be the issue with the Android trying to count all the files in the image gallery of mapillary. It takes ages to load the 30k pictures into mapillary, yeah. try to get rid of them before you do take more pictures ;-)
If it works with <5k pictures, a solution you describe may works. 

echelon

**Comment by drkludge** [comment]
@echeloni2p I believe you missed the point.  I tried recent.  It is super buggy.  The old version is stable.

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_
