### ISSUE TITLE
What does 1.1 M mean on the website?

### ISSUE THREAD

**Issue by drkludge** [mapillary/mapillary_issues#2931]
### Basic information

* Platform: `Web`

### Additional information

Currently there are seven users with 1.1 M images.   What does that mean?  How far apart are each of the users from one another. Moreover, if you click on say, zimmy, all you still see are 1.1 M images. However, you can see that zimmy has 16,430 km mapped.  That's much better.  I don't see why the website has to limited information.  If I look at the profile tab on my phone,  I see all the detail of the number of images that I have captured and the exact number of meters that I have mapped.  I see no problem with putting the same information on the web.  In fact more detail needs to be put on the leader board such as 1.xxx M images.  It is boring staying on 1.1 M forever.  If we look at descilla, there are 968.9 K images.  The rounding on that part of the leader board works. 1.245 M would be much more useful along with the full detail if you click on the user.

**Comment by Kaldea** [comment]
Hi!

Thank for the reaching out! This is an interesting suggestion. I'm passing this over to our marketing team for them to also consider. 

I appreciate you sharing this with us! Have a great day!
