### ISSUE TITLE
Web uploader don't recognize GoPro Fusion GPS Exif data

### ISSUE THREAD

**Issue by ArtificialTruth** [mapillary/mapillary_issues#2932]
### Basic information
* Platform: `Web`

### Steps to reproduce behavior

 1. Upload 360 stiched (from GoPro Fusion Studio) .jpg image to https://www.mapillary.com/app/uploader

### Expected behavior
That Mapillary recognizes the included GPS exif tag in the .jpg photo

### Actual behavior
Can't find location for the pic. In comparison, online tools like http://exif.regex.info/exif.cgi understands and finds the location in the pics.

### Additional information
For some reason, if I open the photo in Paint.net and save it with a new name, Mapillary finds the photo.
Upon further inspection, it seems Paint.net changed the EXIF ```8825	GPS Info``` value from ```144``` to ```184```
It seems there is something wrong with the pointer to the GPS Info IFD in the pictures.
(See page 26/31 in [this pdf](http://www.cipa.jp/std/documents/e/DC-008-Translation-2016-E.pdf) for more information about EXIF tags)
Also, the mapillary scripts are updated to read the data according to this [forum thread](
https://forum.mapillary.com/t/gopro-fusion-rendered-photos-not-loading-locations-using-mapillary-uploader/1541/7).
Example EXIF data for a 360 photo stiched using Fusion Studio (according to [ExifPro](http://www.exifpro.com/) and according to [ExifTool](https://owl.phy.queensu.ca/~phil/exiftool/)):
```
==========ExifPro data==========
File: MULTISHOT_0326_000000.jpg
0132	Date Time	12-06-2018  17:38:36
0131	Software	GoPro Fusion Studio 1.2.1.400
010f	Make	GoPro
0110	Model	GoPro Fusion
8825	GPS Info	144
.0001	GPSLatitudeRef	N
.0002	GPSLatitude	55.0, 44.0, 3350/1000
.0003	GPSLongitudeRef	E
.0004	GPSLongitude	12.0, 21.0, 58870/1000
.0005	GPSAltitudeRef	0
.0006	GPSAltitude	78241/1000
.0007	GPSTimeStamp	08:33:30.00
.001d	GPSDateStamp	2018:06:12
-	GPSLatitude	55° 44' 03.4" N
-	GPSLongitude	12° 21' 58.9" E
-	GPSAltitude	78.2 m

==========ExifTool data==========
- ExifTool Version Number         : 11.01
- File Name                       : MULTISHOT_0326_000000.jpg
- File Size                       : 13 MB
- File Modification Date/Time     : 2018:06:12 17:38:38+02:00
- File Access Date/Time           : 2018:06:13 10:36:25+02:00
- File Creation Date/Time         : 2018:06:13 10:36:25+02:00
- File Permissions                : rw-rw-rw-
- File Type                       : JPEG
- File Type Extension             : jpg
- MIME Type                       : image/jpeg
0 JFIF Version                    : 1.01
2 Resolution Unit                 : inches
3 X Resolution                    : 0
5 Y Resolution                    : 0
- XMP Toolkit                     : Adobe XMP Core 5.1.0-jc003
- Stitching Software              : GoPro Fusion Studio 1.2.1.400
- Use Panorama Viewer             : True
- Projection Type                 : equirectangular
- Cropped Area Image Height Pixels: 2880
- Cropped Area Image Width Pixels : 5760
- Full Pano Height Pixels         : 2880
- Full Pano Width Pixels          : 5760
- Cropped Area Left Pixels        : 0
- Cropped Area Top Pixels         : 0
- Source Photos Count             : 2
- Exif Byte Order                 : Little-endian (Intel, II)
306 Modify Date                     : 2018:06:12 17:38:36
305 Software                        : GoPro Fusion Studio 1.2.1.400
271 Make                            : GoPro
272 Camera Model Name               : GoPro Fusion
1 GPS Latitude Ref                : North
2 GPS Latitude                    : 55 deg 44' 3.35"
3 GPS Longitude Ref               : East
4 GPS Longitude                   : 12 deg 21' 58.87"
5 GPS Altitude Ref                : Above Sea Level
6 GPS Altitude                    : 78.241 m
7 GPS Time Stamp                  : 08:33:30
29 GPS Date Stamp                  : 2018:06:12
- Image Width                     : 5760
- Image Height                    : 2880
- Encoding Process                : Baseline DCT, Huffman coding
- Bits Per Sample                 : 8
- Color Components                : 3
- Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
- GPS Altitude                    : 78.2 m Above Sea Level
- GPS Date/Time                   : 2018:06:12 08:33:30Z
- GPS Latitude                    : 55 deg 44' 3.35" N
- GPS Longitude                   : 12 deg 21' 58.87" E
- GPS Position                    : 55 deg 44' 3.35" N, 12 deg 21' 58.87" E```
- Image Size                      : 5760x2880
- Megapixels                      : 16.6```

**Comment by cookry** [comment]
@ArtificialTruth Currently, we support the GoPro Fusion via our Command Line Tools (CLTs) only. The CLTs will process the GoPro Fusion images and video formats without external GPS. Upgrade to the latest firmware and stitch imagery using GoPro Fusion Studio. 

```
Fusion v01.80 | May 7, 2018
Fusion Studio v 1.2 | May 17, 2018
```

Learn about the tools which where recently updated: https://blog.mapillary.com/update/2018/05/31/updated-upload-tools.html
Or access these tools directly: https://github.com/mapillary/mapillary_tools/

**Comment by cookry** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Comment by cookry** [comment]
Issue moved to [mapillary/mapillary_elva #4671](https://github.com/mapillary/mapillary_elva/issues/4671) via [**ZenHub**](https://www.zenhub.com/)
