### ISSUE TITLE
[Beta] Image location from external camera images cannot be verified. App crashes.

### ISSUE THREAD

**Issue by habi** [mapillary/mapillary_issues#2933]
### Basic information
* Platform: `iOS`
* Version: `Beta 4.9 (286)` (via TestFlight)

### Steps to reproduce behavior

1. Record sequence with external camera
2. Transfer images to app
3. Verify image

### Expected behavior
Location of images can be verified

### Actual behavior
As soon as the verification screen comes up, the app crashes, as can be seen in the screen recording attached to this issue. I see that the images from the camera have *no* location and are set at 0° Latitude and 0° Longitude.

![mapillary](https://user-images.githubusercontent.com/1651235/41399582-fc2b035c-6fba-11e8-9bf3-7746c4cd16c3.gif)

**Comment by millenbop** [comment]
Thanks for testing!

Which camera did you use? If possible, can you attacj the contents of the `mapillary` directory on your phone, minus the images?

**Comment by habi** [comment]
> Which camera did you use? If possible, can you attacj the contents of
> the mapillary directory on your phone, minus the images?

Camera is a GoPro Hero Session 4, same as here: 
https://github.com/mapillary/mapillary_issues/issues/2546

I'm happy to share the `mapillary` directory, how do I get to this on my 
iPhone?

**Comment by millenbop** [comment]
Thanks. You need to connect the phone to your computer and transfer the directory to your computer using iTunes. If you can't, that fine, I'll try to figure out what's wrong anyway!

**Comment by habi** [comment]
> You need to connect the phone to your computer and transfer the directory to your computer using iTunes.
> 
It‘s been a while since I physically connected my phone to the computer, so I forgot ;)
Will do that ASAP and upload the data here.

**Comment by habi** [comment]
Here's the folder (minus all the big images, the thumbnails and the rest remains).
[mapillary.zip](https://github.com/mapillary/mapillary_issues/files/2103649/mapillary.zip)

**Comment by habi** [comment]
Something I just noted. The `time` of the sequences is always the current time (as seen in the movie above) and the screenshot below. Might this have a connection?
Note that the sequences are not all shot in the exact same time...
![img_7060](https://user-images.githubusercontent.com/1651235/41530979-3a5815e0-72f2-11e8-9163-d68987943077.PNG)

**Comment by millenbop** [comment]
Thanks! Probably not related but I'll look into both!

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Comment by habi** [comment]
@millenbop How should we notifiy you of upcoming issues? Are you not doing this in 'the open' anymore? That would be very sad (and in my opinion also bad).
