### ISSUE TITLE
"Couldn't load the feed" after uninstall/reinstall of 3.128

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2934]
### Basic information
* Platform: Android 8.0
* Version: Mapillary app 3.128
* System/Browser: Samsung Galaxy S7 Edge

### Steps to reproduce behavior

 1.  Uninstall Mapillary app.
 2.  Reboot phone.
 3.  Reinstall Mapillary app.  (I did it from the Play store Beta channel.)
 4.  Launch & log in to Mapillary.

### Expected behavior

The Home screen should show my feed.

### Actual behavior

Feed stays blank, Pending Images value is blank.  Message "Couldn't load the feed" shows up near the bottom of the screen after several seconds.

### Additional information

Problem exists whether I'm on WiFi or mobile data.  Prior to uninstall/reinstall (i.e., after just upgrading the app every time a new one was released for the past couple of years), the feed would load.  I'll see about testing this on a Galaxy S5 running Android 6.0 when I have some time.

I'll turn in trace logs and e-mail them in with this issue number in the subject and body.

**Comment by jfburke3** [comment]
Logs sent.

Problem update:  Pending Images now has a value (I'm uploading right now), but still doesn't load the feed.

**Comment by ovivoda** [comment]
@jfburke3 Please delete your Mapillary account from phone settings and then uninstall/reinstall the app. It looks to me like a corrupted AccountManager database issue.

**Comment by jfburke3** [comment]
@ovivoda That did it.  Thanks.  Never thought about that.
