### ISSUE TITLE
Yi cam witchout malillary track

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#2936]
### Steps to reproduce behavior

 1. I use a smartphone and a Yi cam for straight an left view.
 2. Using the mapillary track for the YI you are mixing both sequences in one, so I can not change the view direction of the pictures from the Yi (+270°) in mapillary
 3. using an other track I can not upload
4. Adding the gps files to exif and deleting the track I can upload but then nothig happens, the pictures do not appair in mappilary, wainting now for two days. 

### Expected behavior

...

### Actual behavior

...

### Additional information

...

**Comment by Kaldea** [comment]
Hi! 

We're currently not optimizing for the Yi camera, however, we can take a look to see what's happening. Can you look over the command line tools so you can share an image sample and specific responses from CLTs so we can attempt to debug?

https://blog.mapillary.com/update/2018/05/31/updated-upload-tools.html
https://github.com/mapillary/mapillary_tools/

Thanks!

**Comment by wegavision** [comment]
The problem isn't the YI Cam. i sent you files with exif-data (lat +lan) but they never apear in mapillary.
Now I Have to use the mapillary app only for the track (and there are better tracking apps), so I can send this track with the pictures. This works but it sucks.  Do you need anythong special in the track file? Are there trackings-apps that work with mapillary? And once again the first question, why do you need a track when the gps-data are in the exif files.

**Comment by cookry** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Comment by cookry** [comment]
Issue moved to [mapillary/mapillary_elva #4672](https://github.com/mapillary/mapillary_elva/issues/4672) via [**ZenHub**](https://www.zenhub.com/)
