### ISSUE TITLE
Sequence rotated

### ISSUE THREAD

**Issue by marians** [mapillary/mapillary_issues#2939]
Please rotate the sequence containing https://www.mapillary.com/map/im/cffwg8uSW6JGUsuy8LW2dw

Thanks!

**Comment by Kaldea** [comment]
Hi @marians !

I have submitted this to be flipped for you. I will let you know when it's done. Thanks!

**Comment by Kaldea** [comment]
@marians Thanks for the patience with this, we had a little setback with this particular sequence but it's now corrected. Have a great day!
