### ISSUE TITLE
Set angle on upload

### ISSUE THREAD

**Issue by abitrolly** [mapillary/mapillary_issues#2941]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox 60.0.2`

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/uploader
 2. Upload pictures without GPS tags

### Expected behavior

Some handles or dialog to rotate picture.

### Actual behavior

Can't find anything.

![image](https://user-images.githubusercontent.com/8781107/42119188-9d746080-7c33-11e8-8f11-b11c8c7a70ec.png)

**Comment by madelenarnesdotter** [comment]
Hi @abitrolly Once images have been uploaded to Mapillary you can use the editor to modify the images, [read more here](https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences). We realize that this is not the solution you're looking for in your request, however, it is a way to edit your sequences after publishing them. We are just about to close this repository down and move feature request discussions to the Mapillary Forum, please come join us here! https://forum.mapillary.com/ (This request will be imported to the Forum during the next couple of weeks!)

**Comment by abitrolly** [comment]
Why the dialog itself can not explain it?

    You will be able to edit images after upload.

**Comment by madelenarnesdotter** [comment]
@abitrolly I'm afraid I misunderstood your question, when you wrote "set angle" I thought you wanted to set the offset! Now studying your request one more time made me realize that you might be asking for a way of rotating the images? This is not a feature in the editor but can be done through this form once you've published images: https://docs.google.com/forms/d/e/1FAIpQLSfKTaxX9wDl9gyfmaFR4jm1kqhWrzX1C1xyfypw0tnRBwAcog/viewform

I hope this was helpful, for more feature requests - feel free to post them in our forum!

**Comment by abitrolly** [comment]
I wanted both to rotate and to offset imageset. Are there topic created at forum? Why forum doesn't reuse Mapillary login?

**Comment by madelenarnesdotter** [comment]
For rotating the images, please use [this form](https://docs.google.com/forms/d/e/1FAIpQLSfKTaxX9wDl9gyfmaFR4jm1kqhWrzX1C1xyfypw0tnRBwAcog/viewform) (this is the same one as the one I shared in my previous comment!)

If you want to set offset you do this with the help of the editor:
https://help.mapillary.com/hc/en-us/articles/115001638129-Editing-sequences

You'll have to create a new login for the Mapillary Forum - I hope this is not too much of an inconvenience for you. Drop us an email in support@mapillary.com if you need help or more guidance about anything Mapillary.

**Comment by abitrolly** [comment]
https://forum.mapillary.com/t/edit-offset-for-all-images-in-a-sequence-category/1807
