### ISSUE TITLE
Wrong share button icon in Time travel

### ISSUE THREAD

**Issue by tbertels** [mapillary/mapillary_issues#2942]
### Basic information
* Platform: `Web`
* System/Browser: `Firefox 61`

### Steps to reproduce behavior
Click on [this URL](https://www.mapillary.com/app/time-travel?lat=50.67834503217642&lng=5.667093612465578&z=17&focus=photo&mapStyle=mapbox_streets&pKey=cRVT-1bIG1xt9ZnzpOW-PA&cKey=F3SPF9KzlKVbyjivNPCA9w)

OR 
 1. Click on Time travel button
 2. Click on Compare

### Expected behavior

Correct share button
![shareok](https://user-images.githubusercontent.com/3265870/42123017-0ed6b61c-7c4b-11e8-9e35-e002d3383ca4.png)

### Actual behavior

Current share button (exit logo at the bottom right)):
![share](https://user-images.githubusercontent.com/3265870/42123015-0ba1a524-7c4b-11e8-91ae-4050a3b4e980.png)

### Additional information

...

**Comment by pbb72** [comment]
Apparently, that is the share icon as used by Apple (https://en.wikipedia.org/wiki/Share_icon#Apple). I agree that the icon developed by ShareThis is more recognisable.

**Comment by tbertels** [comment]
Yes, and the ShareThis icon is already used on the [main interface screen](https://www.mapillary.com/app/?lat=50.67834503217642&lng=5.667093612465578&z=17&focus=photo&mapStyle=mapbox_streets&pKey=cRVT-1bIG1xt9ZnzpOW-PA).

**Comment by nickplesha** [comment]
Thanks for noticing and reporting! We'll update the icons to be consistent.
