### ISSUE TITLE
"My coverage" colour hides current sequence colour

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2943]
A new feature on the website colours all my sequences cyan, including the currently selected sequence, making it impossible to distinguish from all my other sequences.

![image](https://user-images.githubusercontent.com/1436366/42134525-b9e8f018-7d3d-11e8-9860-d836d243d9bf.png)

**Comment by angelday** [comment]
This is a serious accessibility problem, thanks for reporting. We've already filed the issue. Will close this now, you'll see this eventually land.
