### ISSUE TITLE
"My coverage" colouring is always turned on

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2944]
Turning off "My coverage" colouring on the website doesn't stick. As soon as I open the sidepanel, it's turned on again.

Steps to reproduce:
1. On the website map, open the right side panel.
2. Switch to the "Uploads" tab.
3. Turn off "My coverage".
4. Close the side panel.
5. Open the side panel again.
6. "My coverage" is coloured again.

**Comment by angelday** [comment]
Yes it's only functioning as long as the sidebar is opened. This is the expected behaviour. We have plans to make working with layers better. For now this won't get fixed.

**Comment by pbb72** [comment]
In this case we have a difference between "intended" and "expected". This behaviour may well be intended, but at least for me it wasn't expected 😁
