### ISSUE TITLE
Cancel and confirm buttons have identical look

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2946]
In the web editor, after performing some edits, a confirmation dialog pops up with a cancel and confirm option. However, both buttons have an identical look, and the cancel ("Exit without submitting") button is actually bigger than the confirm ("Submit") button, making it too easy to press the wrong button.

Note also that Apple systems often have the confirm button on the left and the cancel on the right side, making confusion even more likely.

![image](https://user-images.githubusercontent.com/1436366/42134603-6fe63ece-7d3f-11e8-87e8-d42f569b0dd5.png)

**Comment by angelday** [comment]
This is a bug.

"Exit without submitting" should be a ghost button. I'll file an issue.

**Comment by nickplesha** [comment]
This should now be fixed and deployed, thanks for reporting!

**Comment by pbb72** [comment]
Confirmed, thanks!
