### ISSUE TITLE
"Discard" and "Review" button result in identical next step

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2947]
The sequence editor on the website shows a "Discard" and a "Review" button (after an edit has been performed).

However, these buttons have the exact same functionality, pressing either of them opens a popup window with another pair of "Exit without saving" and "Submit" buttons.

**Comment by gyllen** [comment]
@pbb72 This is intended

**Comment by pbb72** [comment]
Then why not just replace them with one "Continue" button? This is confusing.

**Comment by gyllen** [comment]
@pbb72 Yeah its just what we decided on after user testing, problem was that some people were not comfortable with continue if they did not want to make the changes.
