### ISSUE TITLE
Sequence editor review window serves no purpose for users

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2948]
After performing some editors in the sequence editor on the website, and either confirming or cancelling, one is presented with some review popup window that serves no purpose.

The window gives a long list of sequence id's (which, by design, are always identical), image id's (which have no purpose for common users) and some Lat/Long/CA offset values (with 14!! decimals).

None of this information can be used by a normal user to confirm/review their edits. It's almost as if this is a left-over debug window as it can only be useful for developers.

![image](https://user-images.githubusercontent.com/1436366/42134678-e8404d00-7d40-11e8-8cad-de3c4f88a904.png)

**Comment by gyllen** [comment]
Closing since duplicate

**Comment by pbb72** [comment]
This is one of a set of issues with the web uploader, but I don't believe it is a duplicate? Or did I report this issue before?

**Comment by gyllen** [comment]
@pbb72 Yes my wrong

@angelday Valid design feedback that makes sense, add to improvement box

**Comment by angelday** [comment]
Agree with @pbb72 on this, moving over to the forums for the time being.

**Comment by gyllen** [comment]
@angelday Added to idea box no need to move to forum, closing
