### ISSUE TITLE
Current photo point is not coloured in sequence editor

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2949]
In the web map, the currently "open" photo point is coloured orange, making it easy to see which photo is currently showing.

This functionality is missing in the sequence editor. While it is possible to go from photo to photo just like in the normal interface, it is not indicated which photo is currently shown. Having this would make correcting sequences much easier.

**Comment by angelday** [comment]
> in the sequence editor [...] it is not indicated which photo is currently shown

This is a bug.

The indication should be a white border around the currently selected image. I'll file a ticket.

**Comment by nickplesha** [comment]
Thanks for reporting, we're tracking this issue internally, it has been requested a couple of times already.

**Comment by pbb72** [comment]
> it has been requested a couple of times already

That's why it is nice to track issues publicly, it helps preventing reporting the same issue multiple times :wink: (though many people don't search first, probably me including...)
