### ISSUE TITLE
reverse geocoding to waterway instead of street

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#295]
As an experiment I did a short sequence on a paddling trip (http://www.mapillary.com/map/im/lEzZmMKv9dJwMK6IKPYAiA) as it turns out all the pictures are located towards the nearest major road which is quite some distance away.
Any chance of adding the waterways as a reference in the reverse geocoder?

**Comment by jesolem** [comment]
Geocoding needs a lot of improvements, hope we can get to this over summer where we're also trying out map matching and some other ideas.

**Comment by gyllen** [comment]
No longer geocoding internally in Mapillary. We might want to look for external geocoding solution.
