### ISSUE TITLE
Fix gps position for all images in a sequence 

### ISSUE THREAD

**Issue by abitrolly** [mapillary/mapillary_issues#2951]
### Basic information

* Platform: `Android` | `Web`
* System/Browser: Firefox 61

### Steps to reproduce behavior

 1. Upload sequence with 10 images at one place with incorrect GPS fix (by 20 meters)
 2. Try to fix their GPS coordinates one by one

### Expected behavior

Select all images with mouse and edit GPS correction (delta) for all of them with keyboard.

### Actual behavior

Select each image one by one with mouse. Drag. Works awful (sluggish). All images now at different points.

**Comment by nickplesha** [comment]
mapillary_issues is no longer an active repository.

Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
