### ISSUE TITLE
Broken filter/view on web mapillary.com

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#2952]
Hi!

### Basic information
* Platform:  `Web`
* Version: `03.07.2018` 
* System/Browser: `Win/Linux | Chromium, Firefox`

### Steps to reproduce behavior

 1. open mapillary.com
 2. choose filter: aceini 1st july- 3rd july
 3. see all dots in light blue (not green), not only filtered

### Expected behavior

See green dots and only for the tracks done in timeframe of filter

### Actual behavior

See all available tracks in light blue

### Additional information

For at least a week now

**Comment by nickplesha** [comment]
@echeloni2p Thanks for reporting! We added a new light blue layer with just the user coverage on top. We'll update it so it respects your filters. In the mean time, you can just close your user sidebar and the layer will disappear and you'll be able to see the green Mapillary coverage filtered as usual. Blue layer is only shown when you're viewing your profile. I've added the issue to our internal task list. Sorry for the inconvenience.
