### ISSUE TITLE
Elasticsearch geographic queries are not 100% precise

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2953]
This is a follow-up to issue #2904.

It turns out there is a tiny imprecision in Elasticsearch geographic queries, which increases with the bounds of the area.

Normally for country-sized queries, the error is insignificant. However, Norway includes 2 islands near the South Pole, making the country bounds span a major part of the earth. As a result of the imprecision, Norway queries include a few kilometers into Sweden, which is enough to significantly distort the statistics for Norway. (The top contributor reported for Norway is almost completely made up of misreported photos which are actually in Sweden.)

The corresponding Elasticsearch bug is elastic/elasticsearch#31048

**Comment by pbb72** [comment]
In the case of Norway, Mapillary could minimise this issue by removing Bouvet Island (and Peter I Island?) from the Norway shape.

**Comment by ptpt** [comment]
Exactly @pbb72 we will remove islands that make the geometry span the whole world. Tracked internally. Thanks for reporting.
