### ISSUE TITLE
[Filter your view] by [Date = ...] is not effective if [My coverage = yes] is selected

### ISSUE THREAD

**Issue by AnkEric** [mapillary/mapillary_issues#2954]
### Basic information
* Platform: `Web`
* Version: - 
* System/Browser: Google Chrome

### Steps to reproduce behavior

 1. tab "Uploads"
 2. Select My coverage = yes 
 3. Filter your view
 4. Date = 2018-06-01

### Expected behavior

Not sure but, in previous version, Select [My coverage = yes] did set User = "ankeric" in [Filter your view]?
Now it's empty.

Set [Date = 2018-06-01 - ] should filter sequences by Date.

### Actual behavior

Filter your view is not effective:
- or: all My coverage is visible
- or: Random (?) selection is visible
- only correctly filtered sequences can be selected.

Reset filter and Select [My coverage = no] and [Mapillary public=yes] 
and Set Filter (again) to [Date = 2018-06-01 - ] (and User = ankeric, or not) will show sequences that are not correctly related to Filter. Which Filter is applied is a mystery for me.

Issue can only be resolved (?) by restarting website.

Ehhh... apply Filter will also (sometimes?) produce disabled sequences (where images cannot be selected). Sequence color has been changed.
Sometimes incorrect filtered sequences are visible and disabled?

Filter:
- [My coverage] = yes
- [Mapillary public] = yes
- [User] = ankeric
- [Date] = 2018-06-01- 

will show a random selection in grayed out color. Some sequences (the correct ones) can be selected, incorrect filtered sequences cannot be selected.

### Additional information

![image](https://user-images.githubusercontent.com/20150550/42266704-730fa588-7f77-11e8-851a-d558837c31fe.png)

![image](https://user-images.githubusercontent.com/20150550/42267208-b54183b2-7f78-11e8-8200-5a58b284b794.png)

![image](https://user-images.githubusercontent.com/20150550/42268716-88380afe-7f7c-11e8-93ff-e2d28f386452.png)

**Comment by nickplesha** [comment]
@AnkEric  Thanks for reporting! We added a new light blue layer with just the user coverage on top recently. We'll update it so it respects your filters. In the mean time, you can just close your user sidebar and the layer will disappear and you'll be able to see the green Mapillary coverage filtered as usual. Blue layer is only shown when you're viewing your profile. I've added the issue to our internal task list. Sorry for the inconvenience.
