### ISSUE TITLE
iOS app crashes when opening Profile page

### ISSUE THREAD

**Issue by lenaye** [mapillary/mapillary_issues#2955]
### Basic information
* Platform: `iOS` 
* Version: `4.8.18` 
* System/Browser: `iOS 11.4`

### Steps to reproduce behavior

 1. Open app
 2. Tap on Profile icon
 
### Expected behavior
The app to show Profile page
...

### Actual behavior
Profile page shows for a moment (with empty user) and then promptly crashes.

See video in the link: https://drive.google.com/open?id=1Upw8jPW5kBzXOoc6MQOsSPdskekjms0i

The issue is reproducible every time.

Note: Very first time usage of the app, I can view the profile page.  But after capturing and uploading some images, I went back to Profile to see and updated info of my contribution and the app crashes.

Note:  I'm using 3 devices (iPhone 6, iPhone X and Nokia 8) to capture and upload pics. Not sure if this is causing the issue. My username on mapillary is **laye**.
...

### Additional information
Happenz on both iPhone 6 and iPhone X (both using same version of app running same version of iOS).

**Comment by millenbop** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Comment by millenbop** [comment]
I fixed another bug in this view and perhaps it fixes this issue as well. I haven't received any crash reports in this view so it's just a guess. I can view your profile here without crashes at least. Fix will be out in next release.
