### ISSUE TITLE
Web: Some of my tracks are not showing on the map

### ISSUE THREAD

**Issue by lenaye** [mapillary/mapillary_issues#2956]
### Basic information
* Platform: Web
* System/Browser: `Windows 10, on both Chrome ( 67.0.3396.99) and Opera (53.0)

### Steps to reproduce behavior

 1. Go to my account 
 2. Click on Feed
 3. Click on one of the messages 'Your xxx images have been published.'
 4. On the next page, click on one of the pictures in a sequence (Sequence 2 in this case).

### Expected behavior
The track of the sequence which contained the selected image should be displayed on the map.
...

### Actual behavior
The image is shown and on the map, the orange direction indicator is displayed by the track for that sequence is not shown.
...

### Additional information
Sequence key: 6fW0NrX6SKSesVAd9KRBJg

![tracking not showing](https://user-images.githubusercontent.com/2821167/42271697-d7560c2c-7f7b-11e8-97c1-d05e9232dc13.PNG)

**Comment by madelenarnesdotter** [comment]
Hi @lenaye ! It takes around 24 hours for us to process and reflect everything related to your imagery on Mapillary. I had a look at the sequence, and the track has now shown up! Thanks for reaching out - you can always reach out to support@mapillary.com if you have more questions.
