### ISSUE TITLE
API v3: increasing per_page parameter has no effect on sequences endpoint

### ISSUE THREAD

**Issue by flowrean** [mapillary/mapillary_issues#2957]
### Basic information
* Platform: `Web`
* System/Browser: `macOS 10.13.5/Firefox 61.0`

### Steps to reproduce behavior

 1. Carry out a query for a bbox that contains a sufficient number of sequences and set the `per_page` parameter. For example: https://a.mapillary.com/v3/sequences?bbox=-74.10140991210938,40.60456943720527,-73.75946044921875,40.863679665481676&per_page=500.
 2. Count the results.
 3. See whether there are more results on further pages by inspecting the link header.

### Expected behavior

A first page of results with 500 sequences (in case of the example above). There are 594 total, and 500 is below the maximum of 1000 ([according to the API docs](https://www.mapillary.com/developer/api-documentation/#search-sequences)).

### Actual behavior

Only lower values than the default of 200 work as they should. I cannot get a page to contain more than 200 results.

**Comment by ptpt** [comment]
Fixed. Thank you for reporting.
