### ISSUE TITLE
Android: different notification icons for each state

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#297]
I'd find it useful to have different icons depending on the state of the notification. This would save me from having to open the notification panel each time I want to check.

For example:
* The uploading could have a couple of up/down arrows and possibly even a low resolution progress bar;
* Completed successfully to have a green tick;
* Error with none uploaded successfully to have a red cross; and 
* A partial upload success to have half a tick and half a cross.

**Comment by peterneubauer** [comment]
Have added success icon now. If @knikel can make an error notification icon, I will add that too.
