### ISSUE TITLE
Dim display on request?

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#299]
I took a sequence on a bus ride (front view) today. But the bright display showed everyone behind me that i took photos.
Do we want a stealth mode with a dimmed Display? 
Or do we want not to hide Photo mapping?
The people on the photos itself will not see a difference.

**Comment by jesolem** [comment]
Still relevant, @peterneubauer ?

**Comment by HolgerJeromin** [comment]
Capture interface has changed a lot since than...
