### ISSUE TITLE
Move GPS position and correct angle in one swoop

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#304]
It would be nice to be able to move the pictures GPS position and make automatic angle corrections in one swoop. Currently one has to move the pictures, then wait for the corrections to get approved, and then remember to go back a day or so later and make the angle correction. If done at once the angles will point toward the uncorrected positions.

**Comment by knikel** [comment]
Something for @angelday to think about with regards to the editor

**Comment by angelday** [comment]
In our new changeset editor this is now possible – although not visually. But we have plans for that also, closing.
