### ISSUE TITLE
After saving an edit link back to the image that started the edit

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#306]
I find it really annoying when I save a set of edits, that I can't easily go back to where I was, rather I'm left stranded on the thank you screen. If I've edited a whole stream of images, going back is a complete pain. Could there be a go back to last image edited link, and/or go back to the first image edited link please?

**Comment by knikel** [comment]
Something for @angelday to consider. However the editor will be more integrated with the viewer.

**Comment by angelday** [comment]
With the release of the new changeset editor the original issue with this ticket is answered, closing.
