### ISSUE TITLE
Image orientation often switches, implement rotation on device

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#307]
One of the problems that I have is images becoming portrait or upside down, especially when there's been a bump, or a tight corner it's much more likely to happen. Would it be possible to prevent this from happening, or allowing me to rotate the images rather than having to hide them in the editor?

I've disabled the steady shot, otherwise I end up with virtually no images with the phone attached to my bike. Under bright sunlight this isn't an issue as the shutter speed is fast enough to prevent blurring.

**Comment by gyllen** [comment]
Im gonna close this since rotation are added to apps
