### ISSUE TITLE
editor: allow manual selection of images

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#310]
I have two panoramas taken from a distance of about 30 meters. The two panoramas were merged into one. 8-(

DOqMMJdncpHceEVdQVbWtA is taken from the south position (shows the straight building fassade), OqvN8IN0osCgpWeF2DZ7zA is taken from the north position (shows the round building fassade).
I was able to move a few images, but selecting the map pins from a bunch of about 80 images at the same position is hard.
A thumbnail view of one sequence would help here.

**Comment by jesolem** [comment]
So we can close this?

**Comment by HolgerJeromin** [comment]
closing in favour of #433
