### ISSUE TITLE
Take in account obstructed view when stitching

### ISSUE THREAD

**Issue by sabas** [mapillary/mapillary_issues#315]
I was checking results of the sequences I uploaded and found this behaviour
Take this picture
http://www.mapillary.com/map/im/rFU_Ot0PgDaNYF-HlLtLBw
Zoom out.
Appears the tower in the middle from this photo http://www.mapillary.com/map/im/xn-xvdSoLllP5mgl4dnvkA

**Comment by ybkuang** [comment]
@sabas as you may seen, we have changed our way of displaying the transitions between the images. I will close this issue. Let us know if you have more suggestions.
