### ISSUE TITLE
Add better redirect for hidden images

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#316]
When I link to http://www.mapillary.com/map/im/ezMfFm1ckUnxbfh_gVQAyA from my profile I get a blank map and no info about the image/track. I've got a feeling it was an image that I hid due to the rotation. 

Would it be possible to at least go to another image in the track in that case, or give a message that the image has been hidden?

**Comment by knikel** [comment]
@gyllen we need to add a flag in the `nav` for the image so I can create some meaningful redirects

**Comment by gyllen** [comment]
Should be better now
