### ISSUE TITLE
Picture review / gallery mode show display newest photos first

### ISSUE THREAD

**Issue by zxiiro** [mapillary/mapillary_issues#324]
Occasionally when I am out taking pictures I notice a picture I took isn't of good quality so I would like to delete it. Unfortunately the current review mode makes this process very inconvenient as the oldest photos are shown first and I have to scroll all the way to the bottom to see the latest photos.

I propose that this mode should show the latest photos first so that these quick deletes can be convenient.

**Comment by jesolem** [comment]
@peterneubauer Has this for the next release.
