### ISSUE TITLE
API documentation lacks description of json formats

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#325]
A little more documentation on what the results of an API query contains would be helpful as these are not all obvious, specifically `compass_direction` (which seems not to be the actual compass direction but a string) and `ca` attributes of a GeoJSON feature.

eg. http://api.mapillary.com/v1/im/search?min-lat=55.611&amp;max-lat=55.613&amp;min-lon=12.994&amp;max-lon=12.995&amp;max-results=1&amp;geojson=true
gives:
```json
{features: [{
type: "Feature",
	geometry: {
	type: "Point",
	coordinates: [
		12.993678,
		55.611085
	]},
	properties: {
		location: "Beijerskajen, Malmö",
		marker-color: "#707070",
		marker-size: "medium",
		image: "https://d1cuyjsrcm0gby.cloudfront.net/7RI9XYM19n0qqdU2EulBAQ/thumb-320.jpg",
		key: "7RI9XYM19n0qqdU2EulBAQ",
		compass_direction: "6",
		ca: 286.9018
	}
}],type: "FeatureCollection"}
```

**Comment by mprins** [comment]
looking at the v2 api documentation, eg. https://a.mapillary.com/#get-searchim documentation is much better :+1:

**Comment by knikel** [comment]
Closing this as v1 is deemed deprecated :wink:
