### ISSUE TITLE
Clear all blurs in a single click

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#326]
I regularly find that I need to clear a dozen small blurs on an images and then start again, which is extremely tedious. Can there be a button to clear all the blurring to be able to start again without having to click around 12 times in specific location, especial when they are overlapping?

**Comment by knikel** [comment]
@smsm1, @floscher, @jaakkoh You can clear all blurs in one click not. But that's not everything, you can edit blurs directly in the image view as well ;).
