### ISSUE TITLE
Upload does not work with Chrome

### ISSUE THREAD

**Issue by Chaos99** [mapillary/mapillary_issues#327]
For me, manual upload with Chrome doesn't work.
The upload preview still shows, but on clicking 'upload to server', the button turns pale, the red line on top fills immediately to the max and the text stays at '0 of XX images uploaded'.

Using Version 37.0.2062.120 m on Windows 7, all Plugins (ABP, Ghostery, NoScript) disabled.

Console gives this at button press:
XMLHttpRequest cannot load http://mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com/. The request was redirected to 'https://s3-eu-west-1.amazonaws.com/mapillary.uploads.manual.images/', which is disallowed for cross-origin requests that require preflight.

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by gyllen** [comment]
This should now work
