### ISSUE TITLE
Show accuracy of bluetooth GPS reciever on Android phones

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#336]
Hi,

thank you for adding the accuracy information in camera mode of the Android app.

Because my phone has a bad GPS unit, I use a bluetooth GPS receiver (Holux M-241). I use the app "Blue GPS" to connect it to my phone and enable "fake locations" in Android developer settings. 

Some Android apps (e.g. OSMTracker for Android) show accuracy if I use my Holux receiver. But Mapillary does not. It shows a yellow icon and 0/0/0 m. OSMTracker usually shows 12 m. 

OSMTracker is open-source. Have a look at it. 

Best regards

Michael

**Comment by peterneubauer** [comment]
This is implemented now, please let me know if it is working.
