### ISSUE TITLE
[website] Wrong zoom center point

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#337]
If I zoom in or out in the small map of edit mode, neither the center nor any other explainable (from user point of view) is used as center for the view in the next zoom level.

This happens if you enter edit mode and your first action is zooming inside the small map.

Firefox 32.0.1, Arch Linux 64bit, XFCE, 1366x768 pixel

Workaround: First pan the map. Afterwards zooming behaviour is as usual for Leaflet, OpenLayers & Co.

**Comment by jesolem** [comment]
Is this still an issue? The map layouts have changed a couple of times.

**Comment by knikel** [comment]
This is no longer an issue, as we're not using map offsets for different layouts any more.
