### ISSUE TITLE
New website not useful on notebook displays (height < 768 px)

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#338]
I use an Arch Linux 64bit with XFCE desktop environment. My laptop display is 768 px high. This height is being reduced by the taskbar, the header of Firefox window, Firefox's tab bar and the URL field. I cannot click on the buttons "edit", "info", "comment", "flag" etc. (see screenshot). I do not see the filter fuction.

I cannot scroll outside the map.

My ugly workaround is to zoom out.
![image-view-screen-too-small](https://cloud.githubusercontent.com/assets/3611273/4302257/2dbf0e74-3e58-11e4-9a48-212184400e0e.png)

**Comment by Michael21011** [comment]
@knikel, I have the same issue now. Cannot scroll down to information details. I was checked in Firefox and Chrome.
Could you see this issue again, please?
![2](https://cloud.githubusercontent.com/assets/9266780/6645178/ecc11e84-c9c2-11e4-8713-f8d3c4d0fa53.png)

**Comment by knikel** [comment]
@Michael21011, I'll look into that. Thanks for reporting!

**Comment by pyrog** [comment]
See also #927

**Comment by knikel** [comment]
@Nakaner, @sabas, @Michael21011, @pyrog: We changed the layout this is no longer an issue :smile:
