### ISSUE TITLE
I can't upload images manually anymore

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#340]
Since yesterday I can't upload images taken with my DSLR. Neither via the upload script nor [the "Manual upload"-website](http://www.mapillary.com/map/upload).
The website either stops uploading somewhere between 15% and 98% or says something like "2 of 20 images uploaded (100%)".
The upload script throws either ```HTTP error: HTTP Error 400: Bad Request on DSC00870.JPG``` or ```URL error: <urlopen error [Errno 32] Broken pipe> on DSC00870.JPG``` for each image.

Maybe this has something to do with another issue, that I noticed: The ["Manual upload"-website](http://www.mapillary.com/map/upload) looks like this, when I type the URL in the addressbar and hit enter:
![upload](https://cloud.githubusercontent.com/assets/3904348/4324791/fe3503dc-3f5d-11e4-8c3a-a6b2e70f996d.png)
Clicking "Push to Mapillary" doesn't change this behaviour.

**Comment by domdomegg** [comment]
Can this issue be closed now? I think this is now known to be caused because of the image size limit (10.5MB), try compressing or if not downsampling images.
