### ISSUE TITLE
Not every license plate is being blurred

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#341]
I have noticed that not every license plate in Karlsruhe, Germany, that could be read on photos, is being blurred. License plates near to the cameraman are being blurred but license plates, which are smaller because they are farther, do not get blurred. 

It is not good when I show Mapillary to normal people (in Germany, sorry Blurmary) and they spot dozens of unblurred images. Then the argument "Great new algorithms from computer vision blur almost every face and license plate." does not work anymore.

Just have a look at the photos I uploaded this week.

**Comment by ToeBee** [comment]
From what I have seen, the license plate detection seems to have only been trained on European style license plates. I have seen very few, if any, U.S. license plates blurred in my uploads. Ours have a more square aspect ratio. Taller and not as wide.

**Comment by willemarcel** [comment]
As the Brazilian car plates are gray (they can be red, white or blue, but the majority are gray), I've seen that your algorithm is not detecting properly the plates in gray or white cars. In dark colors cars the algorithm works better.

Examples:
* http://www.mapillary.com/map/im/RR4dcQQkCur0c2cPvE-dHA
* http://www.mapillary.com/map/b/uLYGcY25h-6mRCYUy4qLJQ
* http://www.mapillary.com/map/im/aIp4latqmr6hAnuH40ws4A
* http://www.mapillary.com/map/im/MUCmkm8VACDFCIaaPACM2g
* http://www.mapillary.com/map/im/Al_V4aLqt9MJ9xkx-tYIXg

**Comment by ybkuang** [comment]
@ToeBee @willemarcel The detection will be better in the future as we obtain more training data. We have a small training set to start with so it is not working universally yet.

**Comment by ToeBee** [comment]
Are you using manual blurring/unblurring requests as training data?

**Comment by Matthias84** [comment]
This would be interesting to know, if manual blurring will help to train the detection. Currently it doesn't seem so :-/

I noticed, that there are different categories, that aren't detected:
* slopy/inclined  http://www.mapillary.com/map/im/G5n_eBzE0c6qsEy4-n087w/photo
* partly covered http://www.mapillary.com/map/im/PoHXpyKT-zHBAEOSxMuBnA/photo http://www.mapillary.com/map/im/xJEMTLfTXv2TuHxdyW8QxA/photo
* incomplete (but reconstructable)  http://www.mapillary.com/map/im/f8EGTwoqhJGH5zglclPZeg/photo

**Comment by jesolem** [comment]
@ybkuang Is right now re-training. I'll let him answer.

**Comment by ybkuang** [comment]
The blurring algorithm is much better now with our latest [release](https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html).
