### ISSUE TITLE
Client to pre-process uploads

### ISSUE THREAD

**Issue by sabas** [mapillary/mapillary_issues#342]
Today we were thinking that could be useful a local software to pre-process photos before upload, to compose the walks taken for example without the required exif tags. It could handle:
- position
- rotation / direction
- timestamp
- blurring
- connection between photos

cc @AleZena , @sbiribizio

**Comment by richlv** [comment]
isn't this covered by now (the python scripts) ?

**Comment by peterneubauer** [comment]
Closing this for now, as the python scripts do this.
