### ISSUE TITLE
Handle hidden sequences is a grateful way. Make them accessible for the owner

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#345]
e.g. http://www.mapillary.com/map/e/2C00uOWN0CV8nnSo_pKpKw

**Comment by cimm** [comment]
Related with issue #134, this really bugs me. Every time I open a hidden sequence the whole site hangs.

**Comment by knikel** [comment]
We'll handle this in much more graceful way in the upcoming remake of mapillary.com. Labelling as a feature request.

**Comment by gyllen** [comment]
In future backend we will not handle hidden, but only have delete.
