### ISSUE TITLE
More background map styles

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#347]
I'm thinking specifically about the
- liberally usable MapQuest Open tiles (because they don't render names with local character sets! -- See this area [http://www.mapillary.com/map/im/bbox/40/53/73/120] for illustration of the problem..), some 
- style with elevation contour lines _that show altitude_ (not just hillshading) -- OCM or something else (because both having an idea of the topography & knowing the altitude of the place is very useful), and finally, I'd also include a 
- satellite-only version (because the roads block the imagery quite badly in some places).

**Comment by gyllen** [comment]
This will no longer be available after we switch to vector tiles. However we should put together a whish list of layers.

**Comment by knikel** [comment]
As @gyllen said, we've switched to vector tiles an are using one layer for now
