### ISSUE TITLE
OSM Map notes as an additional layer

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#348]
Add possibility to view OSM Map Notes as a layer (that also pops up the note content when clicked). This would be a nice additional layer option as it could encourage people to go out to document the place where there is a problem but no Mapillary images yet.

**Comment by pbb72** [comment]
Nice suggestion. It should also be possible to add new notes, as you often discover new errors/omissions when looking at Mapillary photos.

**Comment by knikel** [comment]
We'll be relying on sole basemaps in the upcoming version of mapillary.com. Labelling as a feature request.

**Comment by knikel** [comment]
This certainly would be useful for some folks, but we've decided not to add any external layers to maps for the time being other than the few basemaps we currently have.
