### ISSUE TITLE
Notification of "Complaint filed on image" should be re-worded & adjusted

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#351]
upon filing a bunch of requests to split sequences with long badly connecting straight lines and rotating images (on my own photos) I got a same bunch of email notifications with the title "Complaint filed on image".

2 requests:
(i) as with commenting on one's own images: one wouldn't assume to get a notification of any sort
(ii) The wording of the notification should be adjusted - perhaps to describe the request/filing?

**Comment by jesolem** [comment]
Closing this one. We have a major upcoming notifications project. All wording will be adjusted and (i) too.
