### ISSUE TITLE
Let the (Android-)app adjust image-brightness throughout a sequence

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#354]
I've created a sequence yesterday at the border of a forest, so I started outside the forest and walked sometimes in the forest, sometimes outside in direct sunlight. So the lighting conditions changed very much several times.

It seems, that the app adjusts the brightness of the image at the beginning of the sequence and then uses this setting for all consecutive images unless I start a new sequence. That behaviour was quite annoying, because I had to split the sequence several times. Otherwise the images would be so much over-/underexposed, that you could not see anything on them.

Please let the app adjust brightness ideally before each image is taken, or at least several times throughout a sequence.

**Comment by polarbearing** [comment]
My camera is not very good at handling contrast. The typical situation in driving however has 30-50% bright/blue sky in the frame, typically in a V-shape surrounded by rows of houses left/right and the street in the bottom. Thus the averaging exposure setting considers the dominance of the sky and makes the interesting part too dark. 

See the example picture, and its histogram. The information we are interested in sits in the quarter of the values I have adjusted the sliders to. 

Any chance that we can measure exposure in the lower half of the frame? A slider helps only for the walking mode, not while driving where things have to go automatically.

![2015_02_18_16_23_09_example](https://cloud.githubusercontent.com/assets/8266355/6265532/e20e3c8c-b82f-11e4-9da7-ef369f47d50b.jpg)
![hist](https://cloud.githubusercontent.com/assets/8266355/6265687/29cddee6-b831-11e4-84f2-97dec99fa7cc.png)

**Comment by floscher** [comment]
Just wanted to confirm, that this bug is stil present in v1.07.

I made two sequences (124 and 66 images) from which about ten images are acceptable.

The first image is good:
![2015_02_20_15_00_40_736](https://cloud.githubusercontent.com/assets/3904348/6288970/42ea34d2-b91d-11e4-99fa-605a6dff11a4.jpg)

Then overexposure starts:
![2015_02_20_15_08_54_171](https://cloud.githubusercontent.com/assets/3904348/6289058/c8c305b6-b91d-11e4-8744-b79553b2ab36.jpg)

And ~18 images are completely white like this one:
![2015_02_20_15_12_32_771](https://cloud.githubusercontent.com/assets/3904348/6289077/dbcadecc-b91d-11e4-9464-5eb6b1bfc5fc.jpg)

In the current state this makes the app unusable for me.
I'm still on a Nexus 4 with Android 5.0.1 (stock).

**Comment by peterneubauer** [comment]
Any chance you can try with some other phone? The auto adjustment of the
phone camera is working on all the phones I'm testing wtih. Maybe @knikel
can try a Nexus 5 to confirm this?

**Comment by floscher** [comment]
Yes, I'll test it with another phone and report the results here.

**Comment by peterneubauer** [comment]
Any feedback form other phones?

**Comment by rsahlin** [comment]
Please retest with 2.X version
