### ISSUE TITLE
Stats about photo views

### ISSUE THREAD

**Issue by jaakkoh** [mapillary/mapillary_issues#359]
Visiting my Panoramio account first time in years I was positively surprised to see that the 150 or so photos that I've uploaded there had been seen by over 500k people. 

This, together with making note that Mapillary currently doesn't have any visible stats on how the photos I've uploaded have been viewed prompt me suggest that some stats would be nice.

Examples:
* Per photo:
  - Panoramio: http://www.panoramio.com/photo/18131227
  - PicasaWeb: https://picasaweb.google.com/111183738640134561819/Sommar2013#5912818101673020866
  - Flickr: https://www.flickr.com/photos/vasta/15185953077/
* Overview of a user:
  - Panoramio: http://www.panoramio.com/user/739115/stats

Just a thought.

**Comment by jesolem** [comment]
You see this on hover now after a little "eye" icon.
