### ISSUE TITLE
Keyboard shortcuts in the editor

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#360]
I'd like keyboard shortcuts in the editor, as I currently get a very sore hand jumping between moving between images in the sequence, and the action buttons.

I'd also like the option to select multiple images and hide the selected ones.

**Comment by si-the-pie** [comment]
I'd also like to easily move forward and backward in the photo sequence with a keyboard shortcut. There's no obvious help link. A tool tip over the up or down arrow would be a start!

**Comment by knikel** [comment]
Arrow movement will be implemented, since we'll be using mapillary-js in the new editor. Shortcuts are a great idea.

**Comment by knikel** [comment]
Arrow movement is enabled in all the viewers at `mapillary.com`.
