### ISSUE TITLE
http://api.mapillary.com/v1/u/uploadhashes not work in Chrome / Windows 7

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#364]
Starts a Google chrome, Open  http://mapillary.com, login, then open http://api.mapillary.com/v1/u/uploadhashes. There in a message: "You need to sign in or sign up before continuing."

Same page work fine in Firefox

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by floscher** [comment]
Yes, just tried it with Firefox for Android and had still the same problem.

**Comment by gyllen** [comment]
This is obsolete please find your hashes under http://www.mapillary.com/map/upload/im, closing
