### ISSUE TITLE
Blurring an image discards all edits of the sequence

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#366]
I usually blur images of a sequence during editing the sequence (image positions and directions). I start to correct the position of the first image, then of the second image etc. Between correcting the positions I switch into blur mode to add/remove blurrings.

If I leave the blur mode of an image via "Request Blur" -> "Back to Edit" all my edits of this sequence are lost. I do not open a separate tab for blurring an image.

**Comment by knikel** [comment]
@Nakaner You can now blur directly in the viewer where all changes can only be submitted photo by photo. It might sound scary, but it's faster than it used to be. Also, you get a prompt is you have some unpublished blurs.
