### ISSUE TITLE
Layer switcher does not work in Firefox

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#371]
Hi,

the layer switcher does not work in Firefox 32.0.3 (Arch Linux x64, XFCE). If I click on it, nothing happens. If I let the cursor stay on it, the white box  with the three radio buttons appers. When I now move my mouse to click a radio button, the white layer switcher box with the radio buttons (not the layer icon) disappears.

**Comment by knikel** [comment]
This should not be an issue anymore, feel free reopen if it happens again.
