### ISSUE TITLE
Messed up sequences

### ISSUE THREAD

**Issue by Hjart** [mapillary/mapillary_issues#373]
Hi
I'm using a digital camera (Sony Cybershot HX60V) with a built-in gps receiver. It has no compass, but otherwise it's been fine for what I've been doing so far. Only real issue I'm seeing is some messed up sequences. Look at sequence Aq7FvG9S8hZ-30RtT06W6Q for example. I actually did not walk back several 100 meters to take that last picture in the sequence. The EXIF times in my original photos suggests that this particular one actually was taken seconds before/after the 2 neighbouring photos, so I don't understand why the sequence would end up looking as messy as this. Similar stuff has happened to about half of my sequences, so I'll appreciate if you look into this soon.

**Comment by epsg31468** [comment]
Sorry for the delay, I was on chrismas holidays and had a system upgrade.

Here is a screen cast of the wrongly ordered sequence(http://www.mapillary.com/map/im/F5R3ylXJeP7VbLjRQLZA6A):


https://github.com/epsg31468/mapillary_issues/blob/master/screencast/373/screencast2.mov

Comments on the cast (mm:ss):

00:33 In the center, a pole is appearing.
00:37 Moved forward, pole is now in your back. Still OK.
00:39 ERROR: Pole is again in your front, although I was walking forward.
00:50 turning left. No more trees here.
00:54 ERROR: An image from before with the trees in the scene appears.
00:56 Being at the normal street again.

The cyclic sequence seams to be fixed now (http://www.mapillary.com/map/im/3Ip-t1uCC74gI0MAzXP4vQ), but see the screenshot of my comment above: You see the "upward"-arrow, and a click on it brought you back to the first image.

**Comment by epsg31468** [comment]
This bug is still alive:

Start of a new sequence:
http://www.mapillary.com/map/im/G2S4G9bMHDOBO5TfWLXLhw

First sight of trees:

http://www.mapillary.com/map/im/hv9EQWd8bfH1M0MP59SlFA

At the end of the way:

http://www.mapillary.com/map/im/z_eC4x-xxmfaVox8nbOK-w

But if you now hit the forward button, you are again between the trees:

http://www.mapillary.com/map/im/tIXZN8Z1BAYayWNUjzZ8Ww

**Comment by Thomas8122** [comment]
Same here:
http://www.mapillary.com/map/im/qR8i24w_7prJpw4Yz_rKcA

**Comment by peterneubauer** [comment]
Will check it out in Monday.

**Comment by epsg31468** [comment]
Another one:

http://www.mapillary.com/map/im/-dy_C32S-UUg73FIAhBafA

**Comment by pyrog** [comment]
I have one messed up sequence (downloaded from the app or from manual upload?): [-O3JW7CECRLA88QvT6IVjw](http://www.mapillary.com/map/s/-O3JW7CECRLA88QvT6IVjw)

After the [CkbacmLS8hv5uHJilF3DTg](http://www.mapillary.com/map/im/CkbacmLS8hv5uHJilF3DTg) image, the next 6 images are in wrong order.

**Comment by peterneubauer** [comment]
Looks like everything is working now, closing.
