### ISSUE TITLE
Streched pictures with non-standard aspect ratios

### ISSUE THREAD

**Issue by thomersch** [mapillary/mapillary_issues#376]
When uploading cropped images from other sources than the Mapillary app, they get distorted in the web viewer, as in the following sequence: http://www.mapillary.com/map/im/47Wma1QpV4vVeB5DIYb3qA

**Comment by knikel** [comment]
@thomersch With the viewer update, this is no longer an issue. We visually support all aspect ratios of the photos.

**Comment by thomersch** [comment]
👍Great!
