### ISSUE TITLE
App stops recording despite plenty space/battery

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#377]
My app keeps randomly stopping recording while driving. I've taken sequences that are over 400 images with no problems and then sometimes it stops after only a couple of images. This leaves a number of "holes" in my paths and if I don't notice it straight away (issue #208 should solve that) then the hole could become quite large.

Is there an option to add logging for why capture was paused - I'm using Galaxy S4. Possibly some sensor thinks the phone has been turned upside down (which autopauses Mapillary) when its sitting in its phone holder.

**Comment by alexandre-mbm** [comment]
Are not there these options on app for iOS? It is not functional with iPhone 4S.

**Comment by millenbop** [comment]
No the iOS app doesn't have these options, at least not yet.

**Comment by jesolem** [comment]
Hiding the photos until manually placed is not an easy thing to add. 

Restarting when GPS comes back should work already now.

**Comment by alexandre-mbm** [comment]
Same when the signal was better it did not work. To toggle the GPS?

**Comment by Andblue** [comment]
How about an option in the settings to keep taking pictures even if there is no GPS data, and placing them on the map (in a straight line between the pictures that have GPS data).

**Comment by alexandre-mbm** [comment]
> How about an option in the settings to keep taking pictures even if there is no GPS data, and placing them on the map (in a straight line between the pictures that have GPS data).

:+1: 

Seems good.

**Comment by millenbop** [comment]
We have raised the threshold for acceptable GPS precision so it should be much better now. This is also an old discussion, so closing this one.
