### ISSUE TITLE
Show list of sequences in app, allowing to review and delete entire sequences

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#390]
Today I went with my family to an island where I took some Mapillary sequences. One particular sequence I wanted to get "clean" with no people so I started once only to have younger daughter run into picture. So I started a new sequence and this time older daughter ran into the frame!

So I took a 3rd sequence which was good. However it is very hard to go manually through the hundreds of images, finally find the start of the bad sequence and then pick and choose images based on small thumbnails.

I want to be able to view the sequences in app and be able to enter into a sequence and see only the images it contains (not all thousands or hundreds belonging to other ones) as well as be able to delete an entire sequence.

**Comment by jesolem** [comment]
Done for iOS, Android and Windows Phone.
