### ISSUE TITLE
Option: e-mail notification when sequence is ready to be reviewed

### ISSUE THREAD

**Issue by Stalfur** [mapillary/mapillary_issues#391]
Following thousands of uploaded images and the lag it takes in processing it would be nice to get an option to have e-mail notifications sent so you can go and look at that sequence on the website and see if you need to correct anything.

**Comment by korst** [comment]
I've uploaded 195 photo's via the app. 20 minutes later I received over a period of 13 minutes 23 "Your upload is on the map" mails. Maybe you can limit this to 1 mail per upload.

Also, please include a link. If you stay with the "one mail per sequence" approach; a link to the sequence, else to `www.mapillary.com/profile/<username>`

**Comment by gyllen** [comment]
Fixed, mails should now be chunked more nicely
