### ISSUE TITLE
Correct angles to forward direction

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#397]
I use next algorithm:
1. An action camera in my car does photos every 3 second. OSMTracker on smartphone writes track.
2. I use GeoTag to fill coordinates from track into EXIF data of photos.
3. Upload photos to Mapillary server.
4. Wait several hours, open any one photo for editing and press button CORRECT ANGLES in section **Sequence settings**. It turns all photo to the forward direction of my track.
5.Save and Review changes.

Is this algorithm is correct? Could you suggest how to avoid points  4 and 5?

Could somebody review my sequence ([for example](http://www.mapillary.com/map/e/2tptuvQgE57p20d-myltLQ)) and check any wrong behavior or wrong equipment? Because I  am new in this project but I am planning to contribute much.

Thank you in advance.

**Comment by jesolem** [comment]
@peterneubauer Is this still an issue?

**Comment by peterneubauer** [comment]
Closing this since the python tools should work correctly now with offsets.
