### ISSUE TITLE
Better Possibility to Edit Image Angle in Online Editor

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#405]
Hi,

could you please implement a better possibility to edit image angle in
online editor? I would like to have a little line with an arrow at its
end which shows me more exactly in which direction the image was taken.

The small arrows inside the markers are ok, but I would like to have a
hand gear I can pick and use for rotating an image.

Shall I file this request in the issue tracker?

Best regards

Michael

**Comment by travel193** [comment]
Additionally one user requested that ability to change the compass orientation be made more obvious. Currently the number is underlined and in blue however this may not be obvious to some users.

**Comment by knikel** [comment]
Will be fixed in the upcoming version of the editor, closing in favour of #638.
