### ISSUE TITLE
Link to OSM editor on image is not directly to iD

### ISSUE THREAD

**Issue by SK53** [mapillary/mapillary_issues#406]
When I click on the edit in iD image the link is as follows: http://www.openstreetmap.org/edit#map=16/56.9534761407859/24.055552482604977

Not every OSM contributor has iD set as their default editor. I for instance have Potlatch 1 as my default because I need to use it to restore accidentally deleted ways. In practice I use PL2 for day to day edits. Somewhere there are stats about current editor usage on the OSM wiki.

I think the fix is very simple. Just add **?editor=id** after the edit bit in the URL

**Comment by jesolem** [comment]
I think we fixed this with separate links to iD and JOSM. @knikel will check.

**Comment by HolgerJeromin** [comment]
yes. This issue can be closed.

**Comment by knikel** [comment]
:+1:
