### ISSUE TITLE
Cannot install Android app on Motorola Moto E XT1022

### ISSUE THREAD

**Issue by fjanon** [mapillary/mapillary_issues#407]
I cannot install Android app on Motorola Moto E XT1022. The App sotre says that the app is not compatible with my device.

http://www.gsmarena.com/motorola_moto_e_dual_sim-6323.php

Could you please fix that quickly? I need to test it to see if I can integrate Mapillary in my app.

Thanks

**Comment by jesolem** [comment]
Is this still an issue?
