### ISSUE TITLE
Random profile URL's return an actual page with some sequences

### ISSUE THREAD

**Issue by tmdq** [mapillary/mapillary_issues#413]
Example: Try this 
http://www.mapillary.com/profile/asgasf65as6fga

(Expected behaviour: 404 or equivalent page)

(This was tested while being logged in as a user)

**Comment by jesolem** [comment]
@knikel This is fixed now?

**Comment by knikel** [comment]
@jesolem nope, we need a better redirect. Adding as a TODO.

**Comment by knikel** [comment]
Fixed
