### ISSUE TITLE
let add link with OpenStreetMap

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#417]
If you look the way Flickr works, it lets add an OSM id as you me see it here https://www.flickr.com/photos/12353812@N00/14167654343/ and but clicking on crossing here you see we may use it on website
http://lizpoi.3liz.com/orange/index.php/lizpoi/map/?tree_id=3&selected=202&bbox=534575.068739,5486303.902773,535936.603305,5487040.803499&zoom=17

http://readwrite.com/2009/09/28/flickr_now_supports_openstreetmap_tags

http://code.flickr.net/2009/09/28/thats-maybe-a-bit-too-dorky-even-for-us/

**Comment by gyllen** [comment]
I think this would better be accomplished by using our API and getting images from a geo bounding box, http://www.mapillary.com/api

Closing please reopen if I misunderstod.
