### ISSUE TITLE
Mapillary Web UI & Pictures taken in portrait mode

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#424]
Due to shortcomings of my mount, when mapping on my bike, I can only do that in portrait mode.

While the pictures look good in the thumbnail mode on Mapillary.com, in portrait, it seems  the upper & lower edges are cut off, e.g. in
http://www.mapillary.com/map/im/kGik7-1DOcAWd88HFZmQ_w

The image then becomes relatively useless for mapping any road-related aspects.

I don't have a specific layout proposal for this, maybe to not make the pictures extent the current area they are in, just display them smaller?

**Comment by ligfietser** [comment]
I would like to see this improved, too.
This portrait sequence doesn't look very good:
http://www.mapillary.com/map/im/TVKvTpFjqsXs-uPakvFtDQ

**Comment by peterneubauer** [comment]
WDYT - cropping to get the viewer into a decent consistent format?

**Comment by pyrog** [comment]
Cropping the image? :-1:

just recompute the width in the style ?

**Comment by ligfietser** [comment]
Is there any chance that images taken in portrait mode will be solved?
The thumbnail view is ok. Views in full size also.
Example: http://www.mapillary.com/map/im/3ihsdpecqCf6kbWvOxloxA (distorted)
https://d1cuyjsrcm0gby.cloudfront.net/3ihsdpecqCf6kbWvOxloxA/thumb-2048.jpg (ok)

**Comment by knikel** [comment]
@rudolfmayer, @floscher, @pyrog, @ligfietser: We've rolled out a new viewer experience which addresses this issue :smile:

**Comment by floscher** [comment]
Well done @knikel, the new UI looks great. Finally all in one place and no discrimination of aspect ratios anymore :wink: :smile:.
