### ISSUE TITLE
Show individual photo location not part of a sequence

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#427]
The mapillary overlay (blue lines) only show sequence tracks as lines.  Some of my geotagged photos were taken not as a sequence, sometimes just a single photo.  It would good to show them as dots in the mapillary overlay.

**Comment by knikel** [comment]
We do show single photos as dots on the map, e.g. http://www.mapillary.com/map/im/J3v-W2hglcQuNqN9oZ89qA

@maning Maybe the photo you tried to view has not been added to the map yet? If this is still the case, please provide a link and we'll investigate.

**Comment by maning** [comment]
It took a long time to process the photos for this upload I mentioned.  All good now.

**Comment by knikel** [comment]
Awesome, thanks for the info!
