### ISSUE TITLE
Changing coordinates of panoramas

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#433]
If i change the position of one image of an panorama i would like to be asked:

[ ] adjust position of all images in this sequence
[ ] not for this sequence / dont ask for this sequence anymore

**Comment by jesolem** [comment]
Adjust all makes sense. Also "group" panorama location.

**Comment by HolgerJeromin** [comment]
#45 is similar.

**Comment by de-vries** [comment]
so is #83

**Comment by HolgerJeromin** [comment]
Probably solved in new editor.
