### ISSUE TITLE
No instructions on the website or app about manual blur

### ISSUE THREAD

**Issue by elopio** [mapillary/mapillary_issues#437]
I took some photos that were uploaded from the android app to your server. Later I checked them and I saw some of them didn't have the license plates blurred.

There are no indications on the website or on the app telling me that this step could be required, how to do it, or why it's necessary.

**Comment by knikel** [comment]
@travel193 we should add @pyrog's suggestion to the wiki. I'll add link to the wiki/kb to the site somewhere visible.

**Comment by travel193** [comment]
Definitely. I will add it [here](https://github.com/mapillary/UserGuide/wiki/Change-and-Blur-Requests). Always good to have videos as well.
