### ISSUE TITLE
Processing blurring requests delayed?

### ISSUE THREAD

**Issue by osmned** [mapillary/mapillary_issues#438]
I notice the processing of blurring requests is slow. After submitting a request Mapillary shows: 'Your request for blurring has been submitted to the Mapillary team. It will be reviewed within 24h.'

Unfortunately I have pending blurring requests for several days now. If the Mapillary team uses a manual review than I suggest that Mapillary introduces a sort of confidence system: each user who has made more than 10 succesfull blurring requests is authorised to (un)blur images without review.

**Comment by pbb72** [comment]
If this issue is going to be the collection point for problems with the whole approval process (as is suggested in the closing comment in #1012), then the subject of this issue should be changed, as it no longer is only about blurring, but also moves and other actions that require approval.

**Comment by travel193** [comment]
@pbb72 We can use this issue for general queries related to the speed of processing changesets.
Anything more specific can be a separate issue or part of another if already open.
Do you currently have any change sets that haven't been processed?

**Comment by nicolas17** [comment]
Is this still an issue? I haven't seen blur approval take long at all, during the last months, maybe a year.

**Comment by gyllen** [comment]
@eneerhut, @nicolas17 is right this process is working now. (Im closing)
