### ISSUE TITLE
how about fullscreen?

### ISSUE THREAD

**Issue by Ziltoidium** [mapillary/mapillary_issues#440]
hi, i would like to scroll through sequences in fullscreen.  at the moment i only see little pics and a big map on your website.  but i would like to walk through pics and need only a little map sometimes

**Comment by jesolem** [comment]
@Ziltoidium Is the new viewer OK for you? http://blog.mapillary.com/design/2015/05/28/tiles-design.html

**Comment by Ziltoidium** [comment]
@jesolem Yes, absolutely great! Thanks a lot! That´s why i like mapillary, you really interact with the users. Very nice. Greets

**Comment by knikel** [comment]
@Ziltoidium Glad that you like it! We'll port the new layout to standard view too. Closing this now.
