### ISSUE TITLE
time based pics at the iphone app

### ISSUE THREAD

**Issue by Ziltoidium** [mapillary/mapillary_issues#441]
hi,
so far i use "walking" or "riding" modes to take with my iphone.
but i would like to have the possibility to take a pics all 1s or 2s or 5seconds..
when i walk around i like to photograph some details also and cannot always walk and walk and walk..
also i dont want to press the button again and again to make manual photos.
just a setting to make time based photos would be great!
so i can take pics from left to right and so on while walking slow.  thats great for example in cities with many shops

**Comment by jesolem** [comment]
Looking at adding this in the settings. We're also thinking of a 4th mode which would be "automatic walking" with a longer threshold than riding.

**Comment by jesolem** [comment]
Walking automatic is coming in the next version courtesy of @millenbop . Closing.
