### ISSUE TITLE
be able to add pict indoor if not GPS signal

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#443]
I wish to be able to add panorama picts, even there is no GPS signal.

**Comment by pyrog** [comment]
* [OGC® adopts IndoorGML standard for encoding indoor navigation data](http://www.opengeospatial.org/pressroom/pressreleases/2157)
* http://indoorgml.net

**Comment by peterneubauer** [comment]
You can do this via the manual webuploader or the tools with scripts, closing for now.
