### ISSUE TITLE
"Not syncing" notification is present on Android at all times, even when nothing to sync.

### ISSUE THREAD

**Issue by milliams** [mapillary/mapillary_issues#444]
I am running the latest version of the Android app (0.38) with "Upload pictures in background" checked and "Sync when phone is not charging" unchecked.

I have previously taken photo series and have uploaded them with app. At these times, the notification saying something like "Photos to upload but not plugged in" or "Photos uploading 5 of 30" were very useful. However, since then I have not taken any photos but the app is keeping the notification present saying "Not syncing". This is not useful information since I know that I have no photos to upload and so it *shouldn't* be syncing.

I think that if there are no photos in the queue to be uploaded then the notification icon should not be shown at all. Integrated over time, no-photos-to-sync is the most common situation that users will be.

**Comment by jesolem** [comment]
This has been fixed. Closing.
