### ISSUE TITLE
Flag this image : missing problem

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#447]
I would like to report a problem about a picture/sequence geolocalized at the wrong place.
But there is not item to describe this case (or no item "Other").

In this example, the GPS trace is on the wrong lane : [A4 near Dresden](http://www.mapillary.com/map/im/2hz2CAYK2x1IaLQho08Eww)

**Comment by knikel** [comment]
This has been fixed. A text field for submitting a reason has been added.
