### ISSUE TITLE
Snap GPS traces to roads

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#448]
It could be very useful for users to stick manually or automatically there GPS traces to roads, streams, paths… (in practice OSM ways).

So in this example, all the traces could be merged to the center of the highway lanes.
[![a4 dresden](https://cloud.githubusercontent.com/assets/2158081/5091291/2bf2ee00-6f48-11e4-8267-c246dbca635f.png)](http://www.mapillary.com/map/im/VFRE6_-JO01YcCsdEToEWA)

Is it what you explain in #410 ?

**Comment by voschix** [comment]
I don't think that snapping to any road is a good thing to do. I see at least two completely different strong reasons why in Mapillary it would be  bad idea:
(1) if I ride and take photos on an yet unmapped cycleway parallel to a road, the risk is that they get snapped to that road.
(2) when you have several traces of photographs along the same way, how would you be able to pick the trace you want to see the pictures for? You would only be able to click with your mouse an the top-most trace. The present situation of wobbly traces allows you, by zooming in, to select between them.

**Comment by de-vries** [comment]
(1) You can prevent this by making it semi-automatic (automatic with human confirmation)
(2) this problem already exists on roads with lots of coverage. Also, [this](https://xkcd.com/1172/)

**Comment by pyrog** [comment]
1. If the snapping could be (un)activated, just decide to **unused it** in this case :wink: 

1. Use the **Related** button to skip to another trace :smile: 
![related images](https://cloud.githubusercontent.com/assets/2158081/7116617/3072829c-e1f3-11e4-8c78-59d720cf4485.png)

**Comment by eliasp** [comment]
This issue looks pretty much like a duplicate of #224.

**Comment by pyrog** [comment]
@eliasp Your're right :smile: I close this issue

**Comment by richlv** [comment]
related : http://blog.mapillary.com/update/2016/07/14/meili.html
