### ISSUE TITLE
Widget is not translated

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#449]
* Hints and "related" are not translated.
![mapillary widjet](https://cloud.githubusercontent.com/assets/2158081/5102065/97071a46-6fc4-11e4-8d58-0b37302cd1f1.png)
* There is no hint for 
![mapillary widjet icons](https://cloud.githubusercontent.com/assets/2158081/5102127/d16c8206-6fc5-11e4-905f-4f965d5d1da8.png)
* Sub "panels" are not translated (Related, Comment, Informations, Edit)

**Comment by knikel** [comment]
We'll be reworking whole widget and translation scheme. So expect overall better widget and translations.
