### ISSUE TITLE
Better edit interface for panoramas.

### ISSUE THREAD

**Issue by viesturz** [mapillary/mapillary_issues#45]
Currently you get a bunch of pins scattered in a tight spot.

First of all I know that the panorama is taken from a single spot and would like to place all the pins in a single place. Currently there is no good way to do it.

Next when all the images are put in one spot it's impossible to edit them.
There should be a special interface for images taken from the same spot.
Ideally a photosphere like mode where you can drag the images around. Something like what Hugin does.

**Comment by pyrog** [comment]
> Currently you get a bunch of pins scattered in a tight spot.

@viesturz :+1:  It pollute the map.

Also, there is no special marker on the map with the panorama filter:
![panorama filter](https://cloud.githubusercontent.com/assets/2158081/7216155/4c5de52c-e5f5-11e4-8d1b-aafef9d9dc5d.png)

And it pollute also images:
![](https://cloud.githubusercontent.com/assets/2158081/5263754/215d1b6c-7a35-11e4-817d-310564998227.png)

**Comment by jesolem** [comment]
There should be a panorama marker if the filter is turned on. @knikel ?

**Comment by knikel** [comment]
@jesolem The panorama marker is displayed only for processed panoramas, not sequences taken as panoramas.

**Comment by pyrog** [comment]
@knikel Right, but in the first case at https://github.com/mapillary/mapillary_issues/issues/45#issuecomment-94177340, the panorama is stitched.

**Comment by gyllen** [comment]
This is possible in new editor.
