### ISSUE TITLE
Static (?) pages not translated

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#450]
* http://www.mapillary.com/manifesto.html
* http://www.mapillary.com/about.html
* http://blog.mapillary.com
* http://www.mapillary.com/how.html
* http://www.mapillary.com/instructions.html
* http://www.mapillary.com/using.html
* http://www.mapillary.com/jobs.html
* http://www.mapillary.com/legal.html
* http://www.mapillary.com/terms.html
* http://www.mapillary.com/privacy.html
* http://www.mapillary.com/business.html
* http://www.mapillary.com/developer.html
* http://www.mapillary.com/integrations.html
* http://www.mapillary.com/integrate.html
* http://www.mapillary.com/map/latestuploads
* http://www.mapillary.com/osm.html

I see that the string "Mapillary iD Editor" on footer is not translated.

Best regards

**Comment by knikel** [comment]
Translations are on hold, we'll have a better scheme for them. Closing this now as we have it in our backlog.
