### ISSUE TITLE
Manual Uploads brings Firefox down on 500 pics and more

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#454]
Uploading more than a few hundred of pictures taken with a Garmin Virb brings Firefox down. Its complicated and time consuming uploading only 50 pic one at a time so I can't continue it this way. At the moment I have 20GB of pictures in the queue.

The upload_with_authentication script is no alternative because It reports several different error. Is there another way to comfortably upload the images or do I have to delete those 20Gigs?

**Comment by jesolem** [comment]
This has been fixed with new manual upload.
