### ISSUE TITLE
Show blur status in edit mode

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#457]
I'd like to see two things about the blur-status of an image in edit mode (http://mapillary.com/map/e/<image-id>):
* Is there currently a blur request (or more than one) in progress?
* Is this image blurred and if yes where? For some images this is hard to tell, due to blur spots of width 0 or other reasons (e.g. on large monochromatic areas)

Below is a mockup for how http://www.mapillary.com/map/e/mXikyM1qwNGzpXYdrrwR0A could look like in my imagination:
![mapillary-blur-feature](https://cloud.githubusercontent.com/assets/3904348/5158106/38c59716-7332-11e4-89cf-8bd5c1113538.gif)

But a simple "this image has n pending blur requests" and a checkbox showing the current blur spots when checked would also be a good solution.

**Comment by gyllen** [comment]
We will add this in the same way as we did with traffic signs. Closing since other issues open with same.
