### ISSUE TITLE
Make the map coding language dependent

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#462]
http://www.mapillary.com/map/im/1FM9AjPdeAgEhS29pJ0xXQ kann
is very hard for foreigners: שביל ישראל, מועצה אזורית גולן

**Comment by gyllen** [comment]
Mapbox does have an english map. We should make that an option.

**Comment by knikel** [comment]
We'll be using mapbox-gl-js only. They have labels in few languages, reference: https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview whatever is here will work out of the box. Closing.
