### ISSUE TITLE
Map: Zoom is not marker-centered.

### ISSUE THREAD

**Issue by epsg31468** [mapillary/mapillary_issues#464]
When looking at the map where an image is marked(take any example: http://www.mapillary.com/map/im/leX0s8OfoCFNctpD3tVutA), and zooming in (either by clicking on the "+"-icon or by pressing the keyboard-button "+"), the map gets zoomed left to the marker.
If you zoom in further, the marker walks out of the current view rightways.

Expected: Zoom should leave the marker in the current viewport.
Caused by: Zoom works on center of map, but marker is located in the halfway from right-border of map to right-border of image-view-frame, which is located more to the right of the map-center.

**Comment by knikel** [comment]
This has been fixed, we no longer use offsets in the map layouts. Thanks for the feedback!
