### ISSUE TITLE
Fix Uruguay borders

### ISSUE THREAD

**Issue by willemarcel** [mapillary/mapillary_issues#465]
The Uruguay borders need to be fixed, because part of Montevideo and others cities are out of the polygon: http://www.mapillary.com/map/places/uruguay

**Comment by gyllen** [comment]
We will fix that. We are getting better selection algorithms in place at the moment.

**Comment by de-vries** [comment]
duplicate of https://github.com/mapillary/mapillary_issues/issues/739

**Comment by gyllen** [comment]
See answer in #508 tagging this as border in the meantime

**Comment by richlv** [comment]
the latvian border is still messed up, i assume the uruguayan (uff) one is the same ?

**Comment by peterneubauer** [comment]
Uruguay is at https://www.mapillary.com/app/stats/85632511?lat=-32.564052001766&lng=-55.75852824749995&z=6.7764733435440885 and looks better than before to me?
