### ISSUE TITLE
Mapillary server unable to handle pictures taken upside down?

### ISSUE THREAD

**Issue by PeeWeeOSM** [mapillary/mapillary_issues#466]
I've recently bought a Samsung Camera 2 (running Android) and tried to upload some tracks/photos. This seemed to go OK using and the app (all photos uploaded). On the mapillary site the GPX file (blue line)  shows up but unfortunately I can see no images. (search for "rossenberglaan leusden"  and you will see what I mean). All images were taken with the camera hanging upside down from the car windscreen. The Exif info knows this (orientation= bottom right).
I've also uploaded a GPX file with the camera in normal position. This seems to work OK. (see “jan wagenaarlaan leusden” ) 

Another thing I noticed is that once I’ve clicked on the blue line with the errors (rossenberglaan) the photos do not show up but the site seems to get stuck. Even if you click a blue line that is OK after that it will not work. You have to refresh the page before you can get Mapillary to show photos again. 
So my theory is that the mapillary server can not handle pictures taken upside down. If this is the error can this be fixed?

**Comment by peterneubauer** [comment]
This should be working now. Please let me know if not.
