### ISSUE TITLE
Add keyboard shortcuts for next/previous image in web view and editor

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#472]

**Comment by gyllen** [comment]
We should start thinking about keyboard short cuts.

**Comment by richlv** [comment]
slightly offtopic, but a josm plugin might be much more efficient :)
there already are image control keyboard shortcuts, it would be much faster than the web interface...
web interface could be left for basic operations, leaving mass review and other things for the josm plugin.

**Comment by de-vries** [comment]
> a josm plugin might be much more efficient :)

I totally agree, but here is your answer to that: #479

**Comment by richlv** [comment]
well, the gsoc project is there - hopefully mapillary will help them a lot :)
https://www.google-melange.com/gsoc/project/details/google/gsoc2015/nokutu/5676830073815040

**Comment by knikel** [comment]
Shortcuts are part of `mapillary-js`, therfore they are part of the upcoming mapillary.com update.
