### ISSUE TITLE
Scaling preview images does not work

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#473]
Scaling preview images does not work. See screenshot. 
![mapillary-scaling-does-not-work](https://cloud.githubusercontent.com/assets/3611273/5218414/03189bea-764d-11e4-8714-cd9b37e0fbb5.png)

Image is delivered with 1,024px × 768px resolution but it should be scaled down. Once I right-click onto the image to open Firefox's debug console (view HTML code), it is scaled the right way.

Firefox 33.1.1, Arch Linux amd64, XFCE desktop environment, screen resolution 1920x1080 px.

**Comment by knikel** [comment]
This has been fixed some time ago. I've tried most of the browsers to confirm.
