### ISSUE TITLE
Title for all pages is always the same

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#475]
Please, could you change the html page title because it's always "**Mapillary | Crowdsourced Street Photos**" for all users, all places, all pictures…
So it's not obvious to explore the web browser history or tabs :cry:

For profile pages, it could be "**peterneubauer's profile | Mapillary**" :wink:

**Comment by pbb72** [comment]
This is far from done, at least all the photo pages (http://www.mapillary.com/map/im/) and edit pages (http://www.mapillary.com/map/e) still have the standard title.

@knikel, please re-open.

**Comment by knikel** [comment]
@pyrog The title switching works only for current page users are at, not the history.
@pbb72 True, not all the pages behave the same way, we are updating them as we go. Will keep it open until done :+1:

**Comment by knikel** [comment]
Pinging @retro to think about how we can do that in our router in the new mapillary.com.

**Comment by knikel** [comment]
Viewer is viewer, everything else has a label now
