### ISSUE TITLE
Improve naming pictures in the "wild"

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#476]
Few examples : 

* [Jaun](http://www.mapillary.com/map/im/A_5UslHMHlwhcEl-Kg709A) is the name of the village, but the place is **Kaizeregg** (a moutain)
* [Courmayeur](http://www.mapillary.com/map/im/1t1FzA8P4bWmkPl0GEQi6w), the place name could be **Refigio Torino**
* [Unknown](http://www.mapillary.com/map/im/Q2vGyneDu9Rszdm8ibaSSA) could be **Europa Recreation Ground, Gibraltar** (the name of the polygon enclosing the picture)
* [Unknown](http://www.mapillary.com/map/im/G019v9GOVtCTM_LmtvllIA) could be **Island** ??

PS: **Unknown** is not displayed behind the picture itself, but on the [main page](http://www.mapillary.com/map)

**Comment by gyllen** [comment]
This geocoding is as good as the geocoder we use. At the moment there is not much we can do about it. Sorry.
