### ISSUE TITLE
Javascript/Localization Bug in Android Browser – Mapillary unusable!

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#478]
I discovered an important rendering (?) bug which has to do with Javascript/localization with Android Browser (not Chrome!).

On my LG Optimus 2X with Cyanogen Mod 10.1 (equals Android 4.2.2), 386 MB RAM
If I go to mapillary.com, enter any town (e.g. Hanau or Jöhlingen) into Nominatim search field and tap onto one result, the website looks like this:
![mapillary-javascript-bug](https://cloud.githubusercontent.com/assets/3611273/5231873/806bc000-7741-11e4-82c1-091cd241d5e5.png)
The following screenshots show the website scroll by scroll.
![screenshot_2014-11-28-14-06-39](https://cloud.githubusercontent.com/assets/3611273/5231902/0dc52c2a-7742-11e4-8a21-0d8dbf273e9d.png)

ca. 0.8 screenheight scrolled down:
![screenshot_2014-11-28-14-07-25](https://cloud.githubusercontent.com/assets/3611273/5231903/20b334f8-7742-11e4-84d6-a2e2a95d5e37.png)

ca. 0.8 screenheight scrolled down:
![screenshot_2014-11-28-14-07-35](https://cloud.githubusercontent.com/assets/3611273/5231905/2401586a-7742-11e4-8d83-049ac5da243c.png)

ca. 0.8 screenheight scrolled down:
![screenshot_2014-11-28-14-07-40](https://cloud.githubusercontent.com/assets/3611273/5231906/28346012-7742-11e4-9ffd-7f0c27a91d88.png)

ca. 0.8 screenheight scrolled down:
![screenshot_2014-11-28-14-08-20](https://cloud.githubusercontent.com/assets/3611273/5231907/31e32526-7742-11e4-9e0a-ef2b85013257.png)

This issue only occurs with Android Browser (I am not using Chrome!). If I use Firefox for Android (latest version from F-Droid), it looks like this (i.e. ok):
![screenshot_2014-11-28-14-09-36](https://cloud.githubusercontent.com/assets/3611273/5231914/58dfd340-7742-11e4-9a43-ea09fb29528c.png)
![screenshot_2014-11-28-14-09-46](https://cloud.githubusercontent.com/assets/3611273/5231915/61e5f56e-7742-11e4-825e-837ef5e56d80.png)

I hope that you still have a nice weekend. :-)

**Comment by knikel** [comment]
Thanks @pyrog for testing this. Is this still an issue for you @Nakaner? I still haven't gotten around getting an older device like LG Optimus 2X.

**Comment by knikel** [comment]
We won't support Android Browser soon. We're relying on WebGL a lot. Closing.
