### ISSUE TITLE
Make a JOSM plug-in

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#479]
Many of the top contributors from my country are also very active OSM-mappers and most of them are JOSM users. I really appreciate that you are making it easy to use mapillary photos for OSM-mapping, but IMHO ID isn't the most usable editor and a JOSM plug-in for mapillary photos would be a much better idea. 
JOSM might be a bit intimidating for beginning mappers, but a lot of your top contributors are using it. It might be a nice idea to give them access to the photos via their favorite editor.

**Comment by gyllen** [comment]
And finally that day have arrived :) -> http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html
