### ISSUE TITLE
Improve internationalization (i18n)

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#482]
Could you, please, follow theses guidelines ?
* [Sentence splitting](http://status.net/wiki/I18n_guidelines#Sentence_splitting)
* [Parameter order](http://status.net/wiki/I18n_guidelines#Parameter_order)
* Put all the punctuation in text to be translated<br /> (There is extra spaces and double coma in http://www.mapillary.com/map/upload)
* Use locale to display date, time and numbers<br/>
  **5,194,016 photos 160,842,928 meters** is localized as **5&nbsp;194&nbsp;016 photos 160&nbsp;842&nbsp;928 mètres**<br/>
(and some peoples uses miles :wink: )

If you could, take care of : 

* [Plurals](http://status.net/wiki/I18n_guidelines#Plurals)
* Images containing text
  * http://www.mapillary.com/img/business.png
  * http://www.mapillary.com/img/store-img/app-store.png …

See also http://github.com/edx/edx-platform/wiki/i18n-Coding-Guidelines

Example in Mapillary that is difficult to translate because the sentence is splitted : 

 * Map an area that cannot be reached with street view cars, like the lovely **Venice Beach canals**, or the unmapped **Venice Fishing Pier**.

Should be translated in french like this : 

  * Cartographiez une zone qui n'est pas accessible par les voitures street view, comme ces charmants **canaux de Venice Beach**, ou cette **jetée de Venice** non cartographiée.

**Comment by knikel** [comment]
Closing this, translations will be reworked completely.
