### ISSUE TITLE
Website must better reflect API-Errors (during blurring  request)

### ISSUE THREAD

**Issue by epsg31468** [mapillary/mapillary_issues#484]
If an API call returns with HTTP status other than 200, the front-end website must raise an error.

**Background:** I made a blurr request on the website, after hitting the final submit button, the website responded with the positive message "Thank you. Your request for blurring has been submitted to the Mapillary team. It will be reviewed within 24h.", despite that the underlying API call ( https://api.mapillary.com/v1/b/request?key=IMG_KEY) responded with a HTTP 400 status and submitting the blurr actually failed.

BTW logging out and in again fixed the problem with blurring.

Related issue: https://github.com/mapillary/mapillary_issues/issues/438

**Comment by gyllen** [comment]
Yes this is fixed
