### ISSUE TITLE
Show that images are already edited/flagged

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#489]
It could be useful to see that others users as already flagged an image (to avoid to send another useless request).

The icon could be a… flag :laughing:  or the flag/edit buttons could have another color ?

In this [example](http://www.mapillary.com/map/im/4DjzCkYBftJ2aItpQjg8Ew) I already edit blurring ![mapillary blur already requested](https://cloud.githubusercontent.com/assets/2158081/5259873/adb43fba-7a07-11e4-9d12-8dd8d21394ba.png)

**Comment by knikel** [comment]
Adding as a feature request for the new mapillary.com

**Comment by angelday** [comment]
This is partly done for blurs and we will bring flagging image back, closing. @pyrog let me know if you want to reopen it.
