### ISSUE TITLE
Windows phone app taking weird photos

### ISSUE THREAD

**Issue by 23cpo** [mapillary/mapillary_issues#491]
I've uploaded a sequence four days ago and it wasn't processed yet: http://www.mapillary.com/map/im/HV_oaHkPr45XNwnurPqaJQ 
There were also different images merged into one image. I've used the Windows Phone App to capture those pictures.
The sequence I've captured and uploaded yesterday via my Android phone got processed immediately

**Comment by gyllen** [comment]
This has to come from the camera. Have you seen this again. Closing but reopen if its still a problem.
