### ISSUE TITLE
Add tutorial/tips/blog to explain how to make good panoramas and traces

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#492]
Need advice to use Mapillary App to make Panoramas.

My first test : http://www.mapillary.com/map/im/nV4aDq15FGF1hjqxsXedSQ

* Made panoramas at each letters
* walk from A to D

![mapillary - my first track and panoramas](https://cloud.githubusercontent.com/assets/2158081/5263584/0dcb082c-7a33-11e4-87a3-0ce627ca11c8.png)

I expected to have : 
* one linear sequence from A to D
* Nice panoramas at each letters (see [Viewing panoramas and Stitching panoramas](http://blog.mapillary.com/update/2014/09/10/support-for-pano.html) on the blog)
* A "nice" purple button "Panorama" like in this example![panorama button](http://blog.mapillary.com/img/2014-09-09-pano-dynamic.png)

What I get : 
* 6 sequences
* A trace on pano positions (see #45)
* Not obvious navigation on some positions (I expected only move front and behind arrows)
![mapillary - strange navigation](https://cloud.githubusercontent.com/assets/2158081/5263755/2192caf0-7a35-11e4-88bd-606de366e821.png) ![mapillary - obvious navigation](https://cloud.githubusercontent.com/assets/2158081/5263754/215d1b6c-7a35-11e4-817d-310564998227.png)
* Access to Panoramas is not obvious (should to zoom out to see it)
![mapillary - pano here not obvious](https://cloud.githubusercontent.com/assets/2158081/5263903/7cb0989e-7a36-11e4-8c5a-5cf162552b9e.png) 
![mapillary - obvious pano after zoom out](https://cloud.githubusercontent.com/assets/2158081/5263911/904b3ddc-7a36-11e4-9f26-4a04105c02fa.png)

**Comment by pyrog** [comment]
Mapilary team have worked on stitching images :smile: See #804 and also #45

![](https://cloud.githubusercontent.com/assets/2158081/7216193/f5c95168-e5f6-11e4-8868-78d2bab40050.png)

**Comment by pyrog** [comment]
See also #967

**Comment by jesolem** [comment]
We're continuously adding tips and guides to the User Guide wiki and anyone is welcome to contribute. Closing this.
