### ISSUE TITLE
[Blur editor] Red blur rectangles are drawn in wrong location for non-4:3-images

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#494]
I tried to blur something in the lowest part of an image, but the blur-editor didn't allow me to draw a blur-rectangle there. Maybe this is related to the aspect-ratio of the image being 3:2 (my digital camera isn't capable to shoot in 4:3).

It seems that the blur-editor doesn't allow me to draw a rectangle that extends into the lowest 10% of the image. Additionally, when I click and drag anywhere else, the rectangle starts a bit above my cursor. So probably there is something wrong with the calculation of the rectangles position from the position of the mouse cursor.

Probably related to #389 (blurring with non-standard aspect-ratio).

**Comment by gyllen** [comment]
Is this still an issue?

**Comment by floscher** [comment]
@gyllen yes, it is. Try to blur the lower 10% (more exactly the lower 11.1333%) in the following image, and you'll see:
http://www.mapillary.com/map/b/a9o-5ph7u6StYfSMjQktxA

The problem is, that the blur editor site forces the width of an image to 800px, but doesn't care about the height of the image. But when it comes to the calculation of the blur-coordinates, I guess you assume, that the image is displayed with a width of 800px and the height of exactly 600px, which is a false assumption, if the image doesn't have an aspect ratio of 4:3.

This is essentially the same issue as #157, #232, #389, #424 (partly), #553, #787, #1014, #1063. These are all about the offset of the blur-rectangles when blurring images with non-4:3 aspect ratio.

Here is an animation, which tries to explain, why the blur-rectangles have an offset for images with aspect ratios other than 4:3 (click on the image to view in full resolution):
![non-standard_aspect-ratio](https://cloud.githubusercontent.com/assets/3904348/8396781/2c4deb72-1db5-11e5-9c2e-75dbc4618b05.gif)

The green lines mark the coordinate system, which the blur editor uses for registering mouseclicks. As you can see, this is larger than the image itself for a 3:2 image (in this example the image is 2048x1365px). This is then transformed to fit the image (in this case shrinked vertically). That produces an offset of the actual blur rectangles. And because clicks outside of the image are not registered by the blur editor, you therefore can't blur the lowest part of images with an aspect ratio greater than 4:3.

**Comment by gyllen** [comment]
Thanks for the link, you are right this is a bug with the ratio of the image. Assigning to frontend team.

**Comment by floscher** [comment]
I'd suggest that you close all but one issue from the folowing, as these are really describing the same thing, and several people from your team are assigned to at least one of them ;-):
#157 (assigned to gyllen)
#232 (assigned to ybkuang)
#389 (assigned to paulinus)
#494 (this isue here, assigned to knikel)
#787 (assigned to knikel)
#1063 (assigned to knikel)

As a sidenote:
* For images with aspect ratios >4:3 (3:2, 16:9, …) the red rectangles in the blur editor __and__ the final blurred part of the image have an offset to the position where you clicked the image.
Example: http://www.mapillary.com/map/b/a9o-5ph7u6StYfSMjQktxA
* For images with aspect ratios <4:3 (3:4, 6:5, any portrait image, …) the red rectangles are drawn __without__ offset, but the part of the image that is finally blurred still has an offset.
Example: https://www.mapillary.com/map/b/w1KSUIjUYnMS6a9RnpDRIg (note the already blurred spot)

If you need more information or if I can help you in any way with fixing this issue, just leave me a comment.

**Comment by knikel** [comment]
This has been fixed, there is a full visual support for non 4:3 photos. Thanks for reporting. Enjoy!
