### ISSUE TITLE
Other filters are… not filters

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#498]
**Other filters** don't filters traces (show only them with some criteria) but show/hide markers.
![mapillary other filters](https://cloud.githubusercontent.com/assets/2158081/5331385/b9614a94-7e29-11e4-9b8f-54e7377069a6.png)

Suggestions : 
* Rename it **Markers** or
* Really filter images that are panoramas or that have some comments.
* Add others options : 
  * **Flagged images**
  * **Webcams**
  * **Day / Night**

**Comment by knikel** [comment]
@pyrog Very good points, in the new view (http://blog.mapillary.com/design/2015/05/28/tiles-design.html) we refer the these as objects and filters have a separate category, the same convention will be used in the normal view when we port the layouts. The general rule of thumb is: _if it gets added to the map_ it's an object, _if it gets removed from the map_ it's a filter. Works for you?
