### ISSUE TITLE
Angle of  4,294,967,201°

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#505]
Sometimes newly uploaded (with the python script) images have an angle around  4,294,967,201°. Using the + button a few times and it overruns and gets back to 0°. So its not a big drama but a bit confusing some times. Would be nice if this field were a text field instead of having + and - buttons.

Example: http://www.mapillary.com/map/e/LMt0B5H3-7stboFnbZVzHA

**Comment by lordsutch** [comment]
Oops, I just reported this again as #535. Please ignore the duplicate.

**Comment by ybkuang** [comment]
@bitnapper @wimh @lordsutch Thanks for reporting this and the comments on the hex parsing! We have fixed this and it should parse correctly for new sequences from now on. If you have links to the old sequences that you want to be reprocessed, just send them here and we put those onto reprocessing list.

**Comment by HolgerJeromin** [comment]
It should be easy to query your database for angles >360 degrees... Or do i miss something?

**Comment by ybkuang** [comment]
Yes. That is doable. Right now it is a bit expensive now though for 6M images. We are working on better indexing of the database.  Once that is done, it will be easy to do.

**Comment by lordsutch** [comment]
I manually fixed the orientations on the uploads I made with the wrong orientations already using the edit path tool on the website.

**Comment by gyllen** [comment]
@ybkuang Can we close this?

**Comment by ybkuang** [comment]
Closing this now. Leave a comment if there are still old images with odd orientations.
