### ISSUE TITLE
what about sky direction?

### ISSUE THREAD

**Issue by Ziltoidium** [mapillary/mapillary_issues#506]
on my iPhone with the mapillary app i can see the direction the photo was taken (North, South etc..).
But how about pictures without this direction info?  For example i like to take fotos with a good DSLR and later sync it with my garmin.
Then i will know where it was taken, but not in which direction.   Is there any chance you will find it out later?  Maybe because it was a track in one long direction, that i took on a bike or so..  or in my car at a railroad.  
Did not find any action cam so far that offers direction information.  Even the Garmin Virb Elite offers only the location, nothing more.
Sometimes is nice to use something better than my iphone, but then important information is missing, or not?

**Comment by ybkuang** [comment]
I will close this now since the issue has been resolved in the discussions. Thanks!
