### ISSUE TITLE
Russia is missing in www.mapillary.com/map/places page

### ISSUE THREAD

**Issue by trolleway** [mapillary/mapillary_issues#508]
![image](https://cloud.githubusercontent.com/assets/4630662/5489330/31c68280-86d9-11e4-8389-d654c241a237.png)

**Comment by peterneubauer** [comment]
We are on it, we just imported new shapes and will adjust the places pages accordingly. Thanks!

**Comment by geomapper69** [comment]
Georgia (country) is also missing.  If I try to select it via URL:
http://www.mapillary.com/map/places/georgia
I get Georgia (US state).

**Comment by freeExec** [comment]
I understand that Russia is big, but maybe there is a place for it.

**Comment by alexandrz** [comment]
Imho it would be better to split Russia, USA, China, India and other big countries by states and regions.

**Comment by eugensim** [comment]
still missing

**Comment by gyllen** [comment]
Correct we are working on better shapes. At the moment we are working on on how to use OSM borders on mapillary. We just need to figure out the license first.

**Comment by richlv** [comment]
both georgia and russia seem to be available now - anything to be done for this issue ?

**Comment by peterneubauer** [comment]
Yes,
we reimported the shapes, now with <10000 vertices for search, and <5000 vertices for display. Things should be much more accurate now, the old values where 2000 vertices or both.

**Comment by peterneubauer** [comment]
Russia is now here: https://www.mapillary.com/app/stats/85632685?lat=63.66522761673309&lng=9.500126907369122e-9&z=1.809768264151432, closing.
