### ISSUE TITLE
Iphone Icloud backup

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#510]
It would appear that when my iphone automatically backs-up to icloud, if there is data in the mapillary folder, it will back this up too.
I do not know this is happening for sure, but I am getting warnings that my Icloud storage is full, when I did not get these messages before using Mapillary app.
Is it possible in IOS to flag that folder as a "do not backup"  ?

**Comment by millenbop** [comment]
What's the most common scenario? That users want them to be backed up or not? It should be easy to add, just wondering if we should do it or not. 

(best solution is to upload the photos to Mapillary servers and not keep them on your phone)

**Comment by jesolem** [comment]
@millenbop Set it to default off. I think this is what most people want.

**Comment by millenbop** [comment]
Implemented this now on a per folder basis. Will be available in next app version.
