### ISSUE TITLE
https://upload.mapillary.com/ certificate error

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#512]
Hi,

I tried to use 
python upload.py
to upload pictures that I copied from my iphone.
Python gives error: [SSL: CERTIFICATE_VERIFY_FAILED]

If I try to open https://upload.mapillary.com/ in IE, I get:

There is a problem with this website’s security certificate.
 
The security certificate presented by this website was issued for a different website's address.

Security certificate problems may indicate an attempt to fool you or intercept any data you send to the server.

**Comment by SanderH** [comment]
upload_with_authentication.py has a similar problem, giving either this error:
* CertificateError: hostname 'mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com' doesn't match either of 's3-eu-west-1.amazonaws.com', '*.s3-eu-west-1.amazonaws.com'

or this one:
* URL error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> on VIRB0548.JPGURL error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> on VIRB0547.JPG

**Comment by wimh** [comment]
Looks like the problem is related to the S3 bucketname (mapillary.uploads.manual.images) which contains dots. 

from: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

> When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. 

I am using an older version of python, so I can't verify it myself, but changing this line in upload_with_authentication.py:

    MAPILLARY_UPLOAD_URL = "https://mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com"

into:

    MAPILLARY_UPLOAD_URL = "https://s3-eu-west-1.amazonaws.com/mapillary.uploads.manual.images"

Should fix the issue too. For me the upload still seems to work.

see also http://shlomoswidler.com/2009/08/amazon-s3-gotcha-using-virtual-host.html

**Comment by geomapper69** [comment]
Was this tested in python 2.7.9 ?
Everything works ok with the change in URL in 2.7.8.
I also changed the URL in the upload.py script:
upload.mapillary.com  >  d22zcsn13kp53w.cloudfront.net
All OK in 2.7.8.

Updated to 2.7.9.
Everything fails:
URL error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> on IMG_0536.JPG

**Comment by geomapper69** [comment]
I found a work around that allows me to continue with 2.7.9.
http://legacy.python.org/dev/peps/pep-0476/
Opting out
It is also possible though highly discouraged to globally disable verification by monkeypatching the ssl module:


import ssl

ssl._create_default_https_context = ssl._create_unverified_context

**Comment by paulinus** [comment]
@geomapper69 i'm currently testing with
```MAPILLARY_UPLOAD_URL = "https://d22zcsn13kp53w.cloudfront.net/"```
and it works fine here with python 2.7.9, without such fix.

Could you test the lastest version? (only this changed though)

**Comment by geomapper69** [comment]
Tested with latest version (todays) - upload.py
Same errors.
Maybe an issue with certificates on my PC, I will investigate tomorrow.

**Comment by geomapper69** [comment]
![cwindowssystem32cmd exe 14012015 213446](https://cloud.githubusercontent.com/assets/10060476/5743875/884dbdd2-9c35-11e4-8315-608215654b49.jpg)

**Comment by geomapper69** [comment]
Manually updated my system root certificates from:

http://catalog.update.microsoft.com/v7/site/Search.aspx?q=root%20certificate%20update

Seems to have fixed it.  Will test some more and feedback.

**Comment by riblit** [comment]
I have the same problem with upload.py on Win 7. I tried the certificate update. Didn't help

**Comment by geomapper69** [comment]
I'm testing with Win 7 Home Premium 64bit, all ok so far.

**Comment by wimh** [comment]
@riblit did you also change

    MAPILLARY_UPLOAD_URL = "https://d22zcsn13kp53w.cloudfront.net/"

**Comment by riblit** [comment]
@wimh  my upload.py script already has that URL

MAPILLARY_UPLOAD_URL = "https://d22zcsn13kp53w.cloudfront.net/"

**Comment by geomapper69** [comment]
Unless there are any updates, I am happy to close this issue.

**Comment by peterneubauer** [comment]
Do it!

**Comment by lhost** [comment]
HOWTO validate OpenSSL certificate in any python version:
http://blog.hostname.sk/2015/02/27/nagstamon-python-openssl-certificate-validation/
