### ISSUE TITLE
App-Settings should be accessible while in Camera Mode

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#514]
If you want to change a setting, let's say the interval of pictures taken, you can't do that in the camera mode; this means you have to go one step back, thus breaking any sequence you were currently recording, and also stopping recording for the time it takes to change the settings.

It would therefore be much preferred if settings editing could be done also while in recording mode, accessible the same way (at least in Android) by pressing the menu button.

**Comment by peterneubauer** [comment]
This is implemented in 1.0, see side drawer.
