### ISSUE TITLE
Merging of sequences in Web UI

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#515]
Sometimes a sequence is broken unintentionally - e.g. by someone calling or some other application taking the foreground, which happens especially in walking method when manually triggering taking pictures. Or simply by accidentally clicking the "new sequence" button..

For such cases, it might be useful to allow in the mapillary web interface to merge sequences together.

**Comment by lucadelu** [comment]
This could be useful also for Android app.

**Comment by Jibec** [comment]
should also be automaticaly proposed after having corrected position of pictures and having find connections. I have many sequences created because of "gps gaps" that are uncorrects.

**Comment by pyrog** [comment]
> Or simply by accidentally clicking the "new sequence" button..

:+1:

See [0g9tlKeJ5uj7E8eCuuZ-6w
![merge sequence](https://cloud.githubusercontent.com/assets/2158081/7901439/320d5ac8-0787-11e5-9445-ccbd8e522b99.png)
](http://www.mapillary.com/map/s/0g9tlKeJ5uj7E8eCuuZ-6w)

**Comment by voschix** [comment]
What's the status of this? I am keenly waiting for it to become available.

**Comment by gyllen** [comment]
We are still working on it @voschix , we are in the processes of figuring out how to handle change sets.

**Comment by rudolfmayer** [comment]
So, not much progress on this yet..
What about providing a python small script as part of the mapillary tools as a first option? I anyway copy my pictures from off the card to a HDD for checking image quality before uploading. On that occasion, I also group sequences that are broken into one folder.

If you'd provide a script that takes a folder, finds all files (non-recursive or recursive, as the user wants it), that takes the sequence tags from the chronologically first image found and applies it to all other images (but only if needed, to avoid re-writing images that already have that tag), that would help tremendously already. Any chance for this to happen?

Instead of taking the sequence identifier from the first image, one could also think of taking the identifier most frequently occurring, i.e. the one that the majority of images already has.

**Comment by gyllen** [comment]
@rudolfmayer I wonder if this is a function that would be better in the apps so you can merge directly before upload. What do you think @peterneubauer

**Comment by rudolfmayer** [comment]
I think it might be _also_ useful in the app, but I can see more benefits in an offline (out of the app/on the computer processing) - especially as I already have many sequences on my HDD that would need merging...

**Comment by voschix** [comment]
I think it would be nice to able to do it at choice on the computer or on
the smartphone
I personally would put the priority of implementation on the computer.

**Comment by gyllen** [comment]
@peterneubauer Maybe pilot this in the Android app? WDYT?

**Comment by rudolfmayer** [comment]
Any news on this? I really think that the (Python) script would be the first step to do, it should be rather short, and doesn't require advanced issues like merging of already uploaded sequence IDs, changesets, etc..
Also, for multiple uses, this would be much easier to do than in the app..

**Comment by gyllen** [comment]
@peterneubauer ^^

**Comment by peterneubauer** [comment]
Changesets for moving images between sequences are now implemented. We need to test them, but in principle after that we can start exposing it even through the APIs for external editors.

**Comment by utack** [comment]
Does this work now. Automatically by the sequence bot, or manually triggered somehow?

**Comment by gyllen** [comment]
@utack It should work no, however we do not allow users to create these changesets (so no manual, merging or splitting).

**Comment by peterneubauer** [comment]
closing this, as I don't think we will expose a UX for manually editing several sequences right now.
