### ISSUE TITLE
Clicking "Edit Blurring" before edit page loaded takes you to the home page

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#516]
The loading of http://www.mapillary.com/map/e/ofda66cAXYXsfYTPypE4Tw took around 20 seconds to load the image and map, during this time clicking the "Edit Blurring" button causes it to got to the home page. Could the buttons be disabled during this loading time?

**Comment by knikel** [comment]
Fixed, thanks for the feedback!
