### ISSUE TITLE
After zooming in on a photo, need option to zoom to 100%

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#517]
After zooming into a photo to get some details, I'd like a button on the top left to where the navigation controls are to zoom me to 100% so that I can move to the next image in the sequence quickly.

**Comment by knikel** [comment]
![zoom](https://cloud.githubusercontent.com/assets/1574656/6484394/d67e2c82-c27b-11e4-868b-9599b4c07bf4.png)

We have added a third button, which resets zoom to 100%, it appears only when zoomed in/out. Thanks for the feedback!
