### ISSUE TITLE
When zooming in, load higher res images if available

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#518]
It would be cool if higher resolution images if available were to dynamically load when zooming in on a photo so that e.g. details of a shop front can be made clearer while mapping for OSM. Some of the photos I've taken with my Garmin VIRB are much higher quality than shown. There is a workaround of using the download image link in a new tab, however it would be much easier if it was available within the main interface.

**Comment by jesolem** [comment]
We have zoom to full res for panoramas today. The intention is to get this for regular photos too.

@gyllen @oscarlorentzon for scoping out and implementing.

**Comment by oscarlorentzon** [comment]
@smsm1 We now load and show the full resolution when zooming in for every photo on mapillary.com.
