### ISSUE TITLE
render individual photos on the map differently

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#522]
Suggestion for improvement:
Render single uploaded images (such as traffic signs, remarkable buildings etc) with a different colour and a bigger dot. Example http://www.mapillary.com/map/im/ImoS-qGhNdLP3Tsvpw9E8A

**Comment by gyllen** [comment]
I like the idea, but at the moment I do not think that would be doable. Marking as enhancement and closing.
