### ISSUE TITLE
EXIF Field missing:Orientation 

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#523]
Hey

when i try to upload some Sphere Pictures, i getting this.
It would be helpfull, when i seleceted a Picture for uploading, that i can enter the missing data
into the website, to get the uploaded ..
or pleae provide us a Windows Programm to insert the Required data..

thx
thorsten

**Comment by alexandre-mbm** [comment]
Orientation **!=** GPSImgDirection **?**

Does Mapillary require which of them?

**Comment by jesolem** [comment]
This is fixed in the new version of the web uploader.
