### ISSUE TITLE
Issues with (manually) uploading >100 images

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#524]
I have many issues with uploading hundreds of images, sometimes 200 is the limit, sometimes 100. If I upload more, often less than 100% comes through the server. For example I select 200 images, Mapillary sees only 150 that can be uploaded. 

Another issue that maybe causes the straight lines between the first and last point, is that my browser (Firefox, Windows 9) puts the last selected image first, see attachment
![bug](https://cloud.githubusercontent.com/assets/9638726/5580550/838de2e4-904c-11e4-81cb-449741f66b4d.jpg)

Workaround: selecting the images from last to first solves this issue.

**Comment by gyllen** [comment]
This should be fixed with new manual upload, please reopen if this is not the case
