### ISSUE TITLE
When uploading images manually, add option to append to existing sequence

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#525]
It would be great if I could append images to existing sequences when uploading manually (via website or script).
Then I could upload the first part of a sequence on one day and the next part on another day (maybe solution for #524). And sequences with upload-errors could be submitted and the missing images could be added later (this would probably require to insert the images in existing sequences instead of simply appending them).

The upload-form on the website could offer a dropdown or similar to select the existing sequence (maybe ordered by distance from images to upload) and the script could offer a commandline-parameter which takes the sequence-ID.

**Comment by gyllen** [comment]
This is now possible on the new webupload

**Comment by floscher** [comment]
I can't find an option to do that.
I just tried to insert an image into sequence [CN-LYFksUvFk2Q2VpeavYA](https://www.mapillary.com/map/s/CN-LYFksUvFk2Q2VpeavYA), but couldn't find anything that would allow me to do son.

**Comment by gyllen** [comment]
You can append new images after you uploaded a first batch. But not since you finialized the sequence and push it to our servers.

**Comment by floscher** [comment]
OK, thank you for the clarification.
