### ISSUE TITLE
App fails to upload specific set of images >10.5MiB

### ISSUE THREAD

**Issue by bong0** [mapillary/mapillary_issues#527]
I have this issue since months now that some specific images cannot be uploaded. After a long time the app cancels the upload and reports it's got a 400 or so... There are several issued pointed out in the log.

I cannot upload the images to github since they are slightly bigger than 10MB so here's a zip: http://docs.juliankessel.de/mapillary_failedqueue.zip

Redacted log:

    --------- beginning of /dev/log/system
    01-01 15:12:48.567 W/ViewRootImpl( 2757): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=166.21594, y[0]=690.144, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=75546233, downTime=75546224, deviceId=6, source=0x1002 }
    01-01 15:15:51.967 E/ActivityThread( 2757): Performing stop of activity that is not resumed: {app.mapillary/app.mapillary.android.activity.WelcomeActivity}
    01-01 15:15:51.967 E/ActivityThread( 2757): java.lang.RuntimeException: Performing stop of activity that is not resumed: {app.mapillary/app.mapillary.android.activity.WelcomeActivity}
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3237)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3324)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.app.ActivityThread.access(ActivityThread.java:144)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.app.ActivityThread.handleMessage(ActivityThread.java:1273)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.os.Handler.dispatchMessage(Handler.java:102)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.os.Looper.loop(Looper.java:212)
    01-01 15:15:51.967 E/ActivityThread( 2757): at android.app.ActivityThread.main(ActivityThread.java:5137)
    01-01 15:15:51.967 E/ActivityThread( 2757): at java.lang.reflect.Method.invokeNative(Native Method)
    01-01 15:15:51.967 E/ActivityThread( 2757): at java.lang.reflect.Method.invoke(Method.java:515)
    01-01 15:15:51.967 E/ActivityThread( 2757): at com.android.internal.os.ZygoteInit.run(ZygoteInit.java:902)
    01-01 15:15:51.967 E/ActivityThread( 2757): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
    01-01 15:15:51.967 E/ActivityThread( 2757): at dalvik.system.NativeStart.main(Native Method)
    --------- beginning of /dev/log/main
    01-01 15:41:58.217 D/app.mapillary.android.service.UploadService( 2757): upload AWS 2015_01_01_14_29_47_678.jpg: HTTP/1.1 204 No Content
    01-01 15:41:58.267 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:41:58.297 D/app.mapillary.android.service.UploadService( 2757): Uploading photo /storage/sdcard1/Android/data/app.mapillary/files/mapillary/2015_01_01_14_29_53_138.jpg
    01-01 15:42:07.827 D/app.mapillary.android.service.UploadService( 2757): upload AWS 2015_01_01_14_29_53_138.jpg: HTTP/1.1 204 No Content
    01-01 15:42:07.847 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:42:07.847 D/app.mapillary.android.service.UploadService( 2757): Uploading photo /storage/sdcard1/Android/data/app.mapillary/files/mapillary/2015_01_01_14_30_00_480.jpg
    01-01 15:42:17.157 D/app.mapillary.android.service.UploadService( 2757): upload AWS 2015_01_01_14_30_00_480.jpg: HTTP/1.1 204 No Content
    01-01 15:42:17.187 D/app.mapillary.android.service.UploadService( 2757): Done, errors Upload failure (400)
    01-01 15:42:17.197 D/app.mapillary.android.service.MapillaryUploadSyncAdapter( 2757): onPerformSync for account[user@host], done.
    01-01 15:53:57.957 D/app.mapillary.android.activity.WelcomeActivity( 2757): Android version: 19
    01-01 15:53:57.957 D/app.mapillary.android.activity.WelcomeActivity( 2757): Mapillary version: 0.38
    01-01 15:53:57.957 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:53:57.957 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:53:58.267 I/Adreno-EGL( 2757): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: RGURRAM_AU_LINUX_ANDROID_LNX.LA.3.5.2.2_RB1.04.04.04.087.030+PATCH[ES]_msm8974_LNX.LA.3.5.2.2_RB1__release_ENGG ()
    01-01 15:53:58.267 I/Adreno-EGL( 2757): OpenGL ES Shader Compiler Version: E031.24.00.15
    01-01 15:53:58.267 I/Adreno-EGL( 2757): Build Date: 08/12/14 Tue
    01-01 15:53:58.267 I/Adreno-EGL( 2757): Local Branch: 
    01-01 15:53:58.267 I/Adreno-EGL( 2757): Remote Branch: quic/LNX.LA.3.5.2.2_rb1
    01-01 15:53:58.267 I/Adreno-EGL( 2757): Local Patches: 8b00bd16f3c1d9d35a2fa902df5e679888d2b2e3 Fixes an llvm crash with mini dEQP apk
    01-01 15:53:58.267 I/Adreno-EGL( 2757):                  38bad22e162dead4e008444520a0144c78a347bd Fixes a potential dEQP crash.
    01-01 15:53:58.267 I/Adreno-EGL( 2757):                  ce345e1c45c2ae2d1fb2cb125c8d2574f1af5f95 Rev
    01-01 15:53:58.377 I/Timeline( 2757): Timeline: Activity_idle id: android.os.BinderProxy@44322818 time:78016065
    01-01 15:54:00.057 I/Timeline( 2757): Timeline: Activity_launch_request id:app.mapillary time:78017742
    01-01 15:54:00.157 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:00.167 D/app.mapillary.android.activity.DeleteImagesActivity( 2757): files: 15
    01-01 15:54:00.537 I/Timeline( 2757): Timeline: Activity_idle id: android.os.BinderProxy@44346730 time:78018224
    01-01 15:54:05.357 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:05.367 D/app.mapillary.android.activity.DeleteImagesActivity( 2757): files: 15
    01-01 15:54:05.547 I/Timeline( 2757): Timeline: Activity_idle id: android.os.BinderProxy@44346730 time:78023234
    01-01 15:54:06.307 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:06.307 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:06.337 I/Timeline( 2757): Timeline: Activity_idle id: android.os.BinderProxy@44322818 time:78024028
    01-01 15:54:09.657 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:54:09.807 D/app.mapillary.android.service.MapillaryUploadSyncAdapter( 2757): onPerformSync for account[user@host], manualSync true
    01-01 15:54:09.807 D/app.mapillary.android.service.MapillaryUploadSyncAdapter( 2757): Sync over Cell: false
    01-01 15:54:09.807 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:54:09.807 D/app.mapillary.android.service.UploadService( 2757): UploadService()
    01-01 15:54:09.807 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:09.807 D/app.mapillary.android.service.UploadService( 2757): startUpload
    01-01 15:54:09.807 D/app.mapillary.android.activity.StorageUtils( 2757): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
    01-01 15:54:09.817 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:54:09.817 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:54:09.837 D/app.mapillary.android.service.UploadService( 2757): Uploading photo /storage/sdcard1/Android/data/app.mapillary/files/mapillary/2014_10_14_09_33_00_143.jpg
    01-01 15:54:24.057 D/app.mapillary.android.service.UploadService( 2757): upload AWS 2014_10_14_09_33_00_143.jpg: HTTP/1.1 400 Bad Request
    01-01 15:54:24.057 D/app.mapillary.android.activity.Utils( 2757): WiFi: true, Ethernet: false
    01-01 15:54:24.077 D/app.mapillary.android.service.UploadService( 2757): Uploading photo /storage/sdcard1/Android/data/app.mapillary/files/mapillary/2014_10_14_09_33_06_216.jpg
    01-01 15:54:24.077 W/SingleClientConnManager( 2757): Invalid use of SingleClientConnManager: connection still allocated.
    01-01 15:54:24.077 W/SingleClientConnManager( 2757): Make sure to release the connection before allocating another one.
    01-01 15:54:50.877 D/app.mapillary.android.activity.WelcomeActivity( 2757): Appending log to /storage/emulated/0/mapillary.log

**Comment by floscher** [comment]
Mapillary has an upload limit of 10.5 MiB (see [#340 (comment)](https://github.com/mapillary/mapillary_issues/issues/340#issuecomment-57039304)).

**Comment by bong0** [comment]
@floscher thanks for pointing that out. Then the app needs to be anjusted to handle this

**Comment by peterneubauer** [comment]
@gyllen do you think there is a limitation on the object size on S3 causing this?

**Comment by gyllen** [comment]
Yes thats what it is. Can we check this in the app @peterneubauer ?

**Comment by peterneubauer** [comment]
Is this still an issue with the newer Play versions of the app?

**Comment by peterneubauer** [comment]
Closing for now.
