### ISSUE TITLE
Manual upload does not work

### ISSUE THREAD

**Issue by abienvenu** [mapillary/mapillary_issues#530]
I try to upload four small images with Firefox 31.0 on Win7 :
- I go to https://www.mapillary.com/map/upload
- I click "Choose files" and select my files
- The minimap appears with my four images correctly geo-located
- I click "Upload to server"
- The greys out and its text changes to "Uploading to server"
- Nothing more happens

When I click the upload button, the firebug console logs four exceptions :

```
Blocage du chargement du contenu mixte actif (mixed active content) « http://mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com/ »[En savoir plus] lib-78ec9c9d.js:366
Exception { message: "", result: 2153644038, name: "", filename: "https://dga406zepc8gy.cloudfront.net/javascripts/lib-78ec9c9d.js", lineNumber: 366, columnNumber: 0, inner: null, data: null } lib-78ec9c9d.js:380

Exception { message: "", result: 2153644038, name: "", filename: "https://dga406zepc8gy.cloudfront.net/javascripts/lib-78ec9c9d.js", lineNumber: 366, columnNumber: 0, inner: null, data: null } lib-78ec9c9d.js:380

Exception { message: "", result: 2153644038, name: "", filename: "https://dga406zepc8gy.cloudfront.net/javascripts/lib-78ec9c9d.js", lineNumber: 366, columnNumber: 0, inner: null, data: null } lib-78ec9c9d.js:380

Exception { message: "", result: 2153644038, name: "", filename: "https://dga406zepc8gy.cloudfront.net/javascripts/lib-78ec9c9d.js", lineNumber: 366, columnNumber: 0, inner: null, data: null } lib-78ec9c9d.js:380
```

I tried with Chrome, same behaviour.

**Comment by peterneubauer** [comment]
Is it working on IE?

**Comment by abienvenu** [comment]
No, with IE I do not even get the minimap.

**Comment by gyllen** [comment]
Can you try not using https (http://www.mapillary.com/map/upload)

**Comment by abienvenu** [comment]
Right, manual upload works perfectly well with http ! I have to enter my login/password on the http site (even if I am logged in the https site), but it works.

**Comment by Peatsmoke** [comment]
Yesterday and today I've tried to upload several photo's over http and https.
The uploading process says the uploads are succesfull but the photo's don't show up in my activity (http://www.mapillary.com/profile/peatsmoke/activity).

**Comment by Czmartin** [comment]
the same with me, can not upload via https, http works fine

**Comment by Peatsmoke** [comment]
It could be a browser problem. Chrome blocks https because of a unsafe
script. Allowing the script solves it.
Op 4 feb. 2015 21:22 schreef "Czmartin" <notifications@github.com>:

**Comment by gyllen** [comment]
Thanks for reporting. This will be taken care of in next release of manual upload.

**Comment by knikel** [comment]
This is very likely an issue with exif parsing library on IE

**Comment by knikel** [comment]
Won't be an issue in the new uploader. Will close when we roll it out.
