### ISSUE TITLE
Change Request - Automatic orientation issue flag

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#531]
My Iphone5 has an issue of sometimes changing the orientation of the photos mid sequence.
I guess the reason it is doing this is the way the Iphone works out which way is "down".  I think it simply senses with its accelerometers where the greatest force is coming from and assumes that is gravity and sets that to down.
The issue is when you are taking pictures while moving, it feels the forces of you moving side to side or up and down (if you are jogging, etc.) and it gets the orientation wrong.
As part of the post processing of the images, is it possible to look at the orientation statistics for the whole sequence of images.  When I do this (in Picasa), for a sequence of 503 images I get: 472 "180 deg rotated", 22 "270 deg rotated", 6 "normal", and 3 "90 deg rotated.  It is clear the correct orientation for the whole sequence should be "180 deg rotated".  All the other orientations should be flagged as suspect and need to be manually checked.

I have looked at other users photo sequences and the problem seems to be quite common and the database is becoming degraded by including these mis-orientated images.

**Comment by jesolem** [comment]
@geomapper69 We have been wanting to do this for some time. Post processing would solve a lot of these issues. On our list. Thanks for reporting.

**Comment by korst** [comment]
In the sequence of [this photo] (http://www.mapillary.com/map/im/ZBOtA6juJc03qzxKv4P2Gg) are lots of rotated photo's. (I flagged most of them) I'm pretty sure the rotated photo's indicate the bumpiest parts of the ride. (all pics were taken in standard orientation)

**Comment by ybkuang** [comment]
We've implemented a rotation classification algorithm in our backend. It is a feature request to connect the results with a change request for user approval.

mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!

**Comment by ybkuang** [comment]
Related to https://github.com/mapillary/mapillary_issues/issues/531

mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
