### ISSUE TITLE
Missing objects

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#532]
Hey,

i see under my activity 
a 3day ago entry with a small thumbnail and a link to unsafe:%38ksxfdcmpx3xk29svxqbqg:kvgL7kS_ZizqtTudkaENjQ

what is that ?

Second issue..

i upload a walking map and can see it, when i click on it

it's six day's ago

http://www.mapillary.com/#/map/im/EDx9hoqDN5iclDvqShBDmg

Cheers
Thorsten

**Comment by gyllen** [comment]
Seems to be working now. Closing reopen if this is still an issue.
