### ISSUE TITLE
Request to unblur specific sequence.

### ISSUE THREAD

**Issue by maning** [mapillary/mapillary_issues#533]
This sequence is entirely of street art.  

http://www.mapillary.com/map/im/WxpNQRy9-loni1l2R82YRQ

Can you unblur everything?

**Comment by ybkuang** [comment]
@maning  You can request unblur changesets using the editor. Unfortunately, the editor only supports unblur request per image.

**Comment by maning** [comment]
I see, I'll do this manually then (~100 images).

**Comment by ybkuang** [comment]
Cool! Good to recover the faces in the street art! ;) We will work on better UI/processing for batch unblur requests in the future.
