### ISSUE TITLE
Upload from website : exif error

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#534]
Hello,

I had to edit the exif data of a set of pictures, but after these modifications, i couldn't send them (exif error).
I found that the upload manager refuse the picture if GPSProcessingMethod is empty. If I set it to "0", I can send the picture.

**Comment by ybkuang** [comment]
@Stefal what did you use to edit the exif? There is an issue with JOSM edit which the exif parser we use fails to parse the exif. See also https://github.com/mapillary/mapillary_issues/issues/423 and https://github.com/mapillary/mapillary_issues/issues/205.

**Comment by Stefal** [comment]
Yes, I have used Josm to geolocalize the pictures with a gpx file.

before :
---- File ----
FileName                        : IMG_20141225_113752_original.jpg
---- EXIF ----
ISO                             : 160
Model                           : XT1052
MeteringMode                    : Average
FocalLength                     : 4.5 mm
SubjectDistance                 : 1.97 m
Flash                           : Auto, Did not fire
ModifyDate                      : 2014:12:25 11:37:52
ImageWidth                      : 4320
Orientation                     : Unknown (0)
WhiteBalance                    : Auto
ImageHeight                     : 2432
ExposureProgram                 : Manual
LightSource                     : D65
ExposureTime                    : 1/500
FNumber                         : 2.4
Make                            : Motorola
GPSLatitudeRef                  : North

GPSLongitude                    : 0°31.0432
GPSLongitudeRef                 : East
GPSDateStamp                    : 2014:12:25
GPSAltitudeRef                  : Above Sea Level

GPSAltitude                     : 165 m
GPSTimeStamp                    : 10:38:08
GPSImgDirection                 : 208.98
GPSProcessingMethod             : 0
GPSImgDirectionRef              : Magnetic North
GPSLatitude                     : 47°8.7862
OtherImageStart                 : 579
OtherImageLength                : 16785

After :
---- File ----
FileName                        : IMG_20141225_113752.jpg
---- EXIF ----
ISO                             : 160
Model                           : XT1052
MeteringMode                    : Average
FocalLength                     : 4.5 mm
SubjectDistance                 : 1.97 m
Flash                           : Auto, Did not fire
ModifyDate                      : 2014:12:25 11:37:52
ImageWidth                      : 4320
Orientation                     : Unknown (0)
WhiteBalance                    : Auto
ImageHeight                     : 2432
ExposureProgram                 : Manual
LightSource                     : D65
ExposureTime                    : 1/500
FNumber                         : 2.4
Make                            : Motorola
GPSLatitudeRef                  : North
GPSLongitudeRef                 : West
GPSLongitude                    : 0°31.0486

GPSDateStamp                    : 2014:12:25
GPSAltitudeRef                  : Above Sea Level
GPSAltitude                     : 166 m

GPSTimeStamp                    : 10:38:09
GPSImgDirection                 : 208.98
GPSProcessingMethod             : 
GPSImgDirectionRef              : True North
GPSLatitude                     : 47°8.7765
OtherImageStart                 : 20
OtherImageLength                : 16785
GPSSpeedRef                     : km/h
GPSSpeed                        : 70.11844385
GPSVersionID                    : 2.3.0.0

If I set the GPSProcessingMethod to "0", I can upload it.
I don't know if mapillary should ignore this tag, or if this is a real mistake of Josm.

**Comment by ybkuang** [comment]
@Stefal Good catch on the GPSProcessingMethod field! The problem is that after the JOSM edit, the exif parser (a javascript lib we use for the webuploader) fails to recognize/read the exif completely. This could be due to the missing value of GPSProcessingMethod. So there could be a problem with the exif parser we used too since exiftool can parse this correctly.

**Comment by Stefal** [comment]
Yes, the exif parser seems very sensitive.

**Comment by knikel** [comment]
Should be solved in the new uploader (web/desktop), will close when we roll it out.
