### ISSUE TITLE
images sent 2 days ago are not online

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#538]
Hi !
I sent about 1000 images 2 or 3 days ago with the website, but none of them are online.
Is there a problem on the website ?

**Comment by gyllen** [comment]
Hi,

Are your images still not online? What is you username?

**Comment by Stefal** [comment]
Hi,

Not online.
My username is stephanep :
http://www.mapillary.com/#/profile/stephanep

**Comment by gyllen** [comment]
How did you upload your images. Through app or manual upload?

**Comment by Stefal** [comment]
As I said in my first message : with the website (manual upload)

**Comment by gyllen** [comment]
Ah sorry for misunderstanding. So do you still have these images? Can you provide us with one of them? I will need one to debug to see what could have gone wrong.

**Comment by Stefal** [comment]
Yes, I still have all the images.

![img_20141225_123120](https://cloud.githubusercontent.com/assets/8255984/5723245/dfe20704-9b42-11e4-8c66-a45798012007.jpg)

**Comment by alexandre-mbm** [comment]
My test images also are not shown.

Trace:
![5](https://cloud.githubusercontent.com/assets/957501/5759713/4a2c5c9c-9cae-11e4-9dd0-8fe7463b79ce.png)

Example:
![tt_img_00001](https://cloud.githubusercontent.com/assets/957501/5759719/5b670d36-9cae-11e4-8381-184ece3d6e44.jpg)

**Comment by alexandre-mbm** [comment]
My test images were uploaded here:
http://www.openstreetmap.org/#map=19/-5.87779/-35.17869

Them do not appear and may have affected at this zoom level the rendering of a next sequence that already existed.

**Comment by Stefal** [comment]
alexandre-mbm your problem is different as the manual upload returns "uploaded : false", when it said "true" for me.

**Comment by alexandre-mbm** [comment]
@Stefal, no. My screenshot was captured before of the upload.

**Comment by Stefal** [comment]
Ah ! Sorry !

**Comment by alexandre-mbm** [comment]
@gyllen 

Image 1
![manual-upload-activity-wrong](https://cloud.githubusercontent.com/assets/957501/5938437/e6fc219e-a6d9-11e4-8ece-a2f79b3b79a3.png)

Image 2
![manual-upload-uploads-wrong](https://cloud.githubusercontent.com/assets/957501/5938439/ed4126a8-a6d9-11e4-9176-0c751a60ae93.png)

**Comment by geomapper69** [comment]
The area that you circled in image 4 (Rua Praia de Camboinhas, Natal) is now uploaded and available, can this issue now be closed?

**Comment by geomapper69** [comment]
http://mapillary.com/map/im/h_il1sjQIJFfPvJicW38hw

**Comment by alexandre-mbm** [comment]
Why did it take so long? After days them are still "processing"...

**Comment by gyllen** [comment]
@alexandre-mbm Might be a hickup in the pipeline. We have done some reruns lately. uploads are always safe. Sometimes it takes time for them to run through pipeline though. Closing this, thanks for helping out debugging and reporting.

**Comment by alexandre-mbm** [comment]
For record: then the Tina Time-lapse's result can be used directly without any treatment! :+1:

**Comment by gyllen** [comment]
@alexandre-mbm Nice!

**Comment by Stefal** [comment]
Why is this issue closed ? My images are still not online.
I tried to send another sent 2 days ago, and the problem is still here.
Uploading 700 images : ok
Activity in my profile : none since a long time
Processing : none
![img_20150131_144630](https://cloud.githubusercontent.com/assets/8255984/6022817/e2c7b21a-abbf-11e4-85f0-1ceb20d75904.jpg)
![capture mapillary 2015-02-01](https://cloud.githubusercontent.com/assets/8255984/6022824/f6d03ef8-abbf-11e4-9f2c-b54c05a28560.PNG)

**Comment by alexandre-mbm** [comment]
And I even will do a second test when I have time.
