### ISSUE TITLE
Blur request : 400 Bad Request

### ISSUE THREAD

**Issue by ybkuang** [mapillary/mapillary_issues#539]
Can't submit blur request
http://www.mapillary.com/map/b/1aE70M7Sja0J0UHG4B_MBw

**Comment by gyllen** [comment]
Correct behaviour since there already are a pending blur on that image

**Comment by floscher** [comment]
This should not fail silently, as a user who is not looking at the console won't get any feedback.

I got this today again with http://www.mapillary.com/map/b/gkgGrn9QX6r84RWoAjJSMQ

**Comment by knikel** [comment]
This has been fixed, users gets notified when they try to blur image with already requested blur.
