### ISSUE TITLE
2 recent manual uploads have paths but won't display

### ISSUE THREAD

**Issue by lordsutch** [mapillary/mapillary_issues#540]
I manually uploaded two sets of images (as "lordsutch") over the weekend; they show up on the map as traces, but clicking anywhere on them or going directly to them from my Uploads page just shows a spinner and never shows any images on the path.

http://www.mapillary.com/#/map/im/BFw77UIBTnEp8MHwWLpZTw
http://www.mapillary.com/#/map/im/NoRgzyxpE6mubG8e7Rx1kg

**Comment by alexandre-mbm** [comment]
Today it seems okay.

**Comment by lordsutch** [comment]
Yep, appears to be fixed now. Thanks!
