### ISSUE TITLE
Lastest iphone update left orphan images

### ISSUE THREAD

**Issue by riblit** [mapillary/mapillary_issues#541]
My iPhone  6 Mapillary updated itself between taking a bunch (around 1300) of images and initiating an upload. The new version can't see the images and tells me there is nothing to upload, however I can see then when I check the app with itunes.

**Comment by jesolem** [comment]
Ah. I know why, sorry about that. 

The new app organizes photos in subfolders, one for each sequence, so you can easily upload/delete a sequence. The photos are still there as you say, it is just that the upload view only lists the folders. 

Easiest fix: copy the orphaned jpegs from iTunes to your computer, put them in a folder (any name will do), put that folder back through iTunes. Then your photos will appear and you can upload from the app.

Alternatively you can copy over and then run the upload scripts from https://github.com/mapillary/mapillary_tools/tree/master/python

Don't worry about organizing them in sequences, everything is in EXIF and they will be correctly sorted after upload.

**Comment by riblit** [comment]
I'll try the iTunes way tomorrow. I tried the Python  script earlier this evening, it throws an ssl error.

I noticed a lot of EXIF metadata missing from the images. Data taken, date digitised, gps time stamp are some from memory.  This means the images can't be uploaded manually.

Recent events in the new app. The text is incorrect. Should be "You have (xx) images ready" not you has (xx) images ready.

**Comment by ybkuang** [comment]
@riblit  We are working on fixing ssl error issue for the python script upload.py.

- The web uploader does not support images taken from the app. The EXIF metadata are stored in the TIFF tag, so things are good for those images.

-  Thanks for pointing the typo out. We will fix that soon.

**Comment by riblit** [comment]
I copied the photo in a folder back via iTunes and the app found them.  1615 images on the way now. Multiple sequences in the same folder.

**Comment by jesolem** [comment]
@riblit Great. No problem with multiple sequences in the same upload. The images will be correctly sorted, they have a sequence id in EXIF.
