### ISSUE TITLE
IOS update - Image capture riding - phone goes into standby and stops capture

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#543]
New IOS update appears to not keep the phone awake while taking pictures automatically (riding).
Old version would quite happily take pictures for one hour or more without intervention.  New version appears to need you to keep touching the screen to keep it alive.

**Comment by jesolem** [comment]
It should be the same behavior in the new version. Can you try to quit the app (double tap, swipe up) or restart the phone.

I have seen this once but then the camera had other problems too and needed to be restarted. 

thanks for reporting!

**Comment by geomapper69** [comment]
I quit all the open apps, and I shutdown and restarted the phone.
Tested this morning, now its working fine.
Thanks.
