### ISSUE TITLE
iOS App: iPhone 6 Icons are a bit off

### ISSUE THREAD

**Issue by ubahnverleih** [mapillary/mapillary_issues#545]
On the iPhone 6 is the close and the GPS indicator icon are a bit off in the camera view
![img_0715](https://cloud.githubusercontent.com/assets/371280/5765476/1bb6a768-9cfa-11e4-913a-713efbc99863.PNG)

**Comment by jesolem** [comment]
@ubahnverleih Thanks.

A fix is already in the 3.1 update that will go out soon. App Store approval was slow after the holidays.
