### ISSUE TITLE
Automatically detect & tag street signs (or "interesting" objects in general)

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#546]
I am using mapillary quite a bit to improve OSM, but one thing I am specifically interested in is setting the speed limit on roads correctly.

Especially in areas such as Australia or the US where you have many roads w/o any relevant speed information this affects routing precision a lot.
The roads there are often however very long, so it would be very interesting to not have to go through all my images sequentially, but get the key frames detected automatically.

This would involve
- Having tags (e.g. as discussed in issue #144) & a way to filter images by tags
- Detection of at least the basic street signs, a good start would be signs with red circles. It would be great if there was as a second implementation stage a specific differentiation between e.g. speed, overtaking, turning - but just recognising them would be a great first step!

**Comment by ybkuang** [comment]
@rudolfmayer Great suggestion. We are already working on traffic sign detection on our backend and will release some of the results in the near future. Stay tuned. 
p.s. thanks for all your great contributions!

**Comment by korst** [comment]
@rudolfmayer have you ever tried the ScoutSigns plugin (josm)? it displays photos of speed limit signs in josm. more info: http://sdkblog.skobbler.com/scoutsign-osm/ 
speaking of scoutsigns, do you at Mapillary plan on any collaboration with them?

**Comment by ybkuang** [comment]
@korst Yes. We are working with ScoutSigns on integration.

**Comment by korst** [comment]
neat, looking forward to being able to use this data!

**Comment by rudolfmayer** [comment]
I guess this is mostly solved - once you add detection of road signs in Australia as well :-)

**Comment by ybkuang** [comment]
@rudolfmayer Yes. It is in our roadmap to improve detection accuracy and extending traffic signs to more continents. Do you have a good source of traffic sign templates in Australia? I can find examples here http://en.wikipedia.org/wiki/User:Cassowary/road_signs_in_Australia. But I think that is far from completely. If you happen to have some good references, let us know ;)

**Comment by rudolfmayer** [comment]
This seems to be a good source:
http://www.roadsignsaustralia.com.au/ourproducts/TrafficSigns.aspx

Not sure whether there is any copyright issue with using the images from there, though... However, you could use it as a check-list to see how complete your collection of signs is.

Queensland goverment has a nice site: https://www.qld.gov.au/transport/safety/signs/types/index.html

**Comment by domdomegg** [comment]
Is this done now with the Traffic Sign recognition?

**Comment by domdomegg** [comment]
Also see http://sdkblog.skobbler.com/the-new-scoutsigns-powered-with-mapillary/

**Comment by gerhardneuhold** [comment]
We are currently processing all our images with our [updated traffic sign pipeline]( https://blog.mapillary.com/update/2018/06/15/global-sign.html).

If you have further feedback, let's continue discussing features in our new [forum](https://forum.mapillary.com/)!
