### ISSUE TITLE
Reverse geocoding has wrong city

### ISSUE THREAD

**Issue by ghost** [mapillary/mapillary_issues#547]
I've noticed a lot of my uploaded photos have an incorrect guess as to the city. I've tried correcting some but have had the corrections denied.  Are you using OSM LGA  boundaries?

**Comment by riblit** [comment]
Here is an interesting example of incorrect geocoding on the Western motorway at Strathfield.

Westbound lane  Western Motorway, Sydney
http://www.mapillary.com/map/im/pCypToXCPk_NMPtWlGHhFw

Same place in Eastbound lane  Western Motorway, Parramatta
http://www.mapillary.com/map/im/r-ytKv1S8XllxqwlQqH8Fg

Both incorrect.

**Comment by jesolem** [comment]
Thanks. We are using Nominatim and it is not great. We're looking for better alternatives, let us know if you have suggestions. 

@riblit What do you mean that the edits were denied?

**Comment by riblit** [comment]
@jesolem GeoSetter, one of the programs I use here, uses geonames,org for reverse geocoding
When I look through my Activity
3 days ago
riblit got 1 change sets declined

3 days ago
riblit got 1 change sets declined

4 days ago
 riblit requested 1 change sets

5 days ago
 riblit requested 1 change sets

6 days ago
riblit got 11 change sets declined


The only changes I have requested have been to correct the location city or suburb.

**Comment by ybkuang** [comment]
@riblit We might have declined these changesets by mistakes (since our admin UI didn't handle the location changesets correctly). Really sorry about this! 

Is it OK that you resubmit the changesets? Thanks for taking the time improving the data!

**Comment by riblit** [comment]
@ybkuang I just submitted 6 changes of city/suburb name from Parramatta to Arndell Park

**Comment by ybkuang** [comment]
@riblit Awesome! We will approve those as soon as possible.

**Comment by riblit** [comment]
@ybkuang I've been looking at the OSM data. The shopping centre area wasn't named so I have added the name Arndell Park Shopping Centre to it.  There are some other photos within the shopping centre area that I didn't rename. It will be interesting to see if your software picks them up.

**Comment by ybkuang** [comment]
@riblit very cool with adding the address data. As you suggested, it is a great idea that if an image has unknown location,  our backend should query for neighboring images for addresses. We are not doing that now, but will investigate in our todos. Thanks again!

**Comment by riblit** [comment]
I'm trying out some ideas to get an idea of how your backend behaves with different data in OSM so today I drove down a road just outside the Arndell Park administrative boundary and a few roads within the boundary.  I also drove along roads  in the suburb of  Bungarribee. Last time I uploaded photos from there they were marked as in Parramatta.

Before I uploaded them I added the administrative boundary for Bungarribee to OSM so hopefully the backend will pick up the correct suburb.

**Comment by geomapper69** [comment]
@riblit I was looking at the original problem with the Western Motorway.  You said both image addresses are incorrect, what address did you expect to be shown?  I was thinking both should be "Western Motorway, Sydney".
Using http://open.mapquestapi.com/nominatim/
and using the image lat, long data, I see the first image is getting its address reference from:
http://www.openstreetmap.org/way/166417895
road: Western Motorway
suburb: North Strathfield
city: Sydney
state: New South Wales
postcode: 2137
country: Australia
country_code: au
place_id: 109724809

the second
http://www.openstreetmap.org/way/166417897
road: Western Motorway
suburb: North Strathfield
city: Parramatta
state: New South Wales
postcode: 2150
country: Australia
country_code: au
place_id: 109724876

**Comment by riblit** [comment]
@geomapper69  I would expect to see North Strathfield for both.

A postal address would be (if a building adjoined the motorway)
Western Motorway
North Strathfield
NSW 2137


The postcode in the second one is  Parramatta

You appear to be in Europe. Our city, suburb breakup is probably a bit different to yours.
Wikipedia has a good overview http://en.wikipedia.org/wiki/Sydney#Government

We have Local Government Areas (LGA), each with its own council and, depending on its size, an LGA can be a city or a Municipality.  Either way they both have suburbs.

North Strathfield is a suburb of the city of Canada Bay. http://en.wikipedia.org/wiki/City_of_Canada_Bay

**Comment by riblit** [comment]
@ybkuang, @geomapper69, thanks for the nominatim link. I've used it to check some of the photos I uploaded last night. My findings are that the suburb field is the correct one to use for Australia. The city field is a wild guess.

**Comment by geomapper69** [comment]
One other thing I noticed is that the admin boundary coverage for this area (Sydney) is poor in OSM compared to other areas, using:
http://www.itoworld.com/map/2
another useful check is:
http://global.mapit.mysociety.org/

It is possible to "force" OSM to reference the object (way) by using the tag:
is_in:city=Sydney
is_in:suburb=North Strathfield
However, this is not recommended as the correct fix is a good definition of the boundaries.

I think a simple fix would be to continue using nominatim, but give more details on address, eg:
http://mapillary.com/map/im/ty4rEyLxgca7219oQ5rTkw
"near to:  5, St.-Jakob-Straße, Zentrum, Jena-Zentrum, Jena, Thuringia, 07743, Germany".

One question is:
Does Mapillary check the location one time and never check again, or is the location checked every time the picture is viewed?

**Comment by riblit** [comment]
@geomapper69 I checked http://www.itoworld.com/map/2 and agree with you regarding the admin boundaries. More will appear as we have permission to use the ABS data. 

I did notice that some boundaries I added are not shown and some admin level 10 boundaries are shown as without admin_level tag.

I have the same question re Mapillary and location checking. @ybkuang  should be able to answer that one.

**Comment by ybkuang** [comment]
We have decided to disabled reverse geocoding. One will need to use other tools to solve this.
