### ISSUE TITLE
Fractional values of GPSImgDirection being misinterpreted

### ISSUE THREAD

**Issue by lordsutch** [mapillary/mapillary_issues#548]
When interpolating GPS locations using Exiftool's -Geotag option, the GPSImgDirection values tagged are fractional rather than integers. While exiftool and exiv2 on the command line seem to read these values correctly, when imported into Mapillary the angles get distorted (apparently adding 90 degrees or so). The preview on the web uploader, on the other hand, seems to show the correct angles.

Here's an example of an uploaded sequence showing this problem:

http://www.mapillary.com/map/im/Jn6h2QnKToRh_uiEJPkjoA

**Comment by ybkuang** [comment]
@lordsutch There was a bug in the backend which has been fixed. We re-processed your sequence. The compass angles look good now. Let us know if there are other sequences having the same problem. Thanks!

**Comment by ybkuang** [comment]
@lordsutch Closing this for now. If you have more sequences with wrong angles, you can reopen and report here.
