### ISSUE TITLE
Street signs being blurred reduces usefullness.

### ISSUE THREAD

**Issue by riblit** [mapillary/mapillary_issues#552]
I have noticed that street navigation signs are being randomly blurred when uploaded. This is a nuisance if the photos are being used to check and name roads in OSM.

This link is a good example as it also shows the incorrect geolocation address issue.  Leicester Avenue is in Strathfield, not Sydney.

http://www.mapillary.com/map/im/7dNM-9ghVRk_w8VC7hZ1pQ

**Comment by jesolem** [comment]
@riblit They are not "randomly" blurred. It is the license plate detector that is overly enthusiastic. We are working on tuning it, for now you have to unblur in the editor if you want to read an incorrectly blurred sign.  

(let's take the geotagging in your other issue)

**Comment by riblit** [comment]
@jesolem  I'll give that a run. I just requested two unblurrings.
