### ISSUE TITLE
Unable to select blur spots when orientation is poatrait

### ISSUE THREAD

**Issue by higa4** [mapillary/mapillary_issues#553]
Cannot select blur spots on the photos taken by portrait-orientation as bellow.
https://www.mapillary.com/map/b/w1KSUIjUYnMS6a9RnpDRIg
https://www.mapillary.com/map/b/Mj7MZ1-h4Pw_wuHYwk8m7g

**Comment by floscher** [comment]
Same as #157 and #232.
Subset of #424.

Other issues with images with non-standard aspect ratio:
* #376 and #424 about images with non-standard aspect ratio in the viewer, which get stretched.
* #232, #389 and #494 cover the offset of blur rectangles those images have.

**Comment by pyrog** [comment]
I could draw blur boxes but I can't click on the **Request blurring** button.
(It disappear when I draw a box)
[![orientation portrait](https://cloud.githubusercontent.com/assets/2158081/7261537/c9ea34b2-e872-11e4-881a-e76455dd2c4d.png)
dZcXckjQR5sl6zEVf4ZmYA](http://www.mapillary.com/map/b/dZcXckjQR5sl6zEVf4ZmYA)

**PS:** In the case the aspect ratio seem correct, but the picture should be rotated

**Comment by knikel** [comment]
@higa4 This has been fixed. You can also now blur photos directly as you browse them. Thanks for the feedback!
