### ISSUE TITLE
Knowledge Sharing - IOS 3.0 and python uploads

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#554]
'All,
'To share my steps for Iphone to upload via PC python script:
'
'
'1. I use iMazing to transfer from iphone to PC.  ITunes is ok for a copy, but I was unable to find an easy way to delete the images from the phone afterwards.  IBrowse is a free alternative but is slower.
'
'
'2. Move jpgs out of sub directories into a single directory with Python script:

'import shutil 
'import os 
'# techmyway.wordpress.com/2012/01/03/python-os-and-shutil-module-usage
'#  copy all the files in the subfolders to main folder 
'# The current working directory 
'dest_dir = os.getcwd() 
'# The generator that walks over the folder tree 
'walker = os.walk(dest_dir) 
'# the first walk would be the same main directory 
'# which if processed, is 
'# redundant 
'# and raises shutil.Error 
'# as the file already exists 
'rem_dirs = walker.next()[1] 
'for data in walker: 
' for files in data[2]: 
'  try: 
'   shutil.move(data[0] + os.sep + files, dest_dir) 
'  except shutil.Error: 
'# still to be on the safe side 
'   continue 
'# clearing the directories 
'# from whom we have just removed the files 
'for dirs in rem_dirs: 
' shutil.rmtree(dest_dir + os.sep + dirs)

'3. Fix orientation issues (with a bat file) with exiftool.exe, I usually take pictures "upside down" (with volume buttons facing up), for normal orientation replace 3 with 1.
'cd c:\python27
'exiftool -n -overwrite_original -IFD0:Orientation=3 C:\Python27\Mapillary_iphone_raw1\
'pause

'4. QC pictures with your favourite picture viewer, I use Picasa but many others exist.  Ensure you do not have the viewer open until step 3 is complete.  Otherwise the pictures may be read with errors in orientation.  Make whatever adjustments are required in the viewer.

'5. Upload with latest python script (upload.py).  I have made a few modifications that make it more friendly and verbose:
'a.  Decrease threads from 4 to 1 to make it more bandwidth friendly with other household users.  Added a one second pause between uploads for same reason.
'b.  Added datetime stamp to every "uploading" and "success" printed message.  This allows me to judge roughly how long each file is taking to upload and estimate how long the full upload will take.

'I am sure other users have similar hints and tips that they may wish to share.

**Comment by geomapper69** [comment]
Update:

For item 1.
I found it is actually easy to delete the files after copy in ITunes.  You need to use the delete key.  The only menu options are "Add File..." and  "Save to....", but the keyboard delete key is active.

**Comment by mprins** [comment]
@geomapper69 you might use the wiki for this kind of thing.

https://github.com/mapillary/mapillary_issues/wiki
