### ISSUE TITLE
Settings to reduce quality of a phonecam to take pictures for Mapillary

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#560]
I explain it

I started with Mapillary with a Samsung Galaxy SCL, with no SD, with a bad phonecamera , small size of every picture I was be able to make 30 minutes of Mapillary track.
Then I had a Samsung Galaxy Core, with a SD, and a cam of 8/12Megapíxels so I was be able to take one hour or something more like that. Every picture was about 2MB.
And now Santa Claus gave me a Xperia Z3 Compact, with a cam of 20 MB pixels and a SD of 32GB.Little problem, every picture take about 6 MB so I can take pictures about one hour or less (less time than tracks done with Samsung Galaxy Core)
My question is:
-Is any way to reduce a little the Megapixels of the phonecam to take pictures smaller so I can do more tracks than nowadays? Example a setting to make pictures of 5Mpx;8Mpx,12Mpx, 20Mpx...

**Comment by geomapper69** [comment]
I think all phones default to maximum resolution when any app accesses the camera.  To try to reduce the resolution real-time may be too intensive.
One thing I thought about was at the end of a sequence you can maybe add an option to "compress" the database.  This could be done while not taking pictures.

**Comment by jesolem** [comment]
We are thinking of adding a setting to request lower resolution photos. This can be done through the camera APIs.

**Comment by yopaseopor** [comment]
Good new setting but I like to configure this low resolution more than 1024px option,also option in pixels and option in megapixels

**Comment by peterneubauer** [comment]
closing this, please let us know if this is still relevant.
