### ISSUE TITLE
edit geo data before upload doesn't work

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#561]
Because GPS sometimes gives pretty shitty results I've tried to edit the gps tags before upload. 

* I've made some pics with the mapillary app.
* I've used [GottenGeography] (https://github.com/robru/gottengeography) to edit the geo data. 
* Then I uploaded the pics with the mapillary app. (manual upload gave errors)
* The photos appeared on mapillary with the old/unedited geo tags.

Sequences in question: [[1]]
(http://www.mapillary.com/map/im/JmJ-HYUoHVedB_cQRXeYyg) [[2]] (http://www.mapillary.com/map/im/1nqyfSTxPPGmvIuttWLTew)

**Comment by geomapper69** [comment]
If you still have the original, you can compare the Exif data with exiftool.exe (with the -k option).
There is a lot of data stored in the image description field which Mapillary uses.

**Comment by kaitu** [comment]
If you upload with the mapillary app, the (unedited) image description field will be read, not the geo tags.

I think that you could generate e fresh image description field from the edited geo tags using the add_mapillary_tag_from_exif.py script, but you have first to group the images in a separate folder for each sequence. It would be nice to have a modified version of the script which reads the sequence id from the original description field and writes it in the new version of the description field. That way, the sequence grouping would be automatically retained.

To use manual upload and read the geo tags, you first need to erase the image description field. For example, with exiftool command:
exiftool -ImageDescription=

**Comment by alexandre-mbm** [comment]
Do anyone can share here `exiftool.exe  -k` valid results? I will study the mapillary_tools. I want to use the georeferenced photos generated by Tina Time-lapse app. Probably this will be the most practical way to use a smartphone with Android 2.3

**Comment by atpl-pilot** [comment]
Try geosetter, that solves your problem. Geosetter ist great and the right tool. www.geosetter.de

**Comment by alexandre-mbm** [comment]
@atpl-pilot, thank very much. It probably will resolve my issue. It have a Open Street Map layer, in addition to an usability very interesting. I will go to try GeoSetter in the coming days and return here if I find problems with manual uploads and it.

But GottenGeography is very important due to it be for Linux also. And Python, and open source!

**Comment by polarbearing** [comment]
As geosetter, which appears to be Windows only, was last touched in 2011, how could it correct the Mapillary-specific Exif-tags? (Unless it strips everything it does not know)

**Comment by geomapper69** [comment]
If you correct the regular lat, long data in the exif tags, then run:
python upload_each_folder_as_sequence.py
This will call the sub-script add_mapillary_tag_from_exif.py and the Mapillary tags will be reset to match the new exif lat, long.
New files should then be uploaded with:
python upload.py
Google's Picasa 3 also allows you to move the location of photos.

**Comment by alexandre-mbm** [comment]
Note that the new files should be uploaded with `python upload.py` because the command `python upload_each_folder_as_sequence.py` not imply an upload.

@geomapper69:
> Google's Picasa 3 also allows you to move the location of photos.

And the direction?

**Comment by geomapper69** [comment]
python upload_each_folder_as_sequence.py script can upload as well if you activate the upload.py (the last line of the present version of the code).
Picasa 3 does not allow the editing of direction, only lat and long.

**Comment by kaitu** [comment]
To edit image direction you could also use the PhotoAdjust plugin of the java OSM editor JOSM:

http://wiki.openstreetmap.org/wiki/JOSM/Plugins/PhotoAdjust

If you do, after you've completed your editing, remember to to make the changes permanent by right clicking on the image layer and selecting the "Write coordinates to image header" function  (along with coordinates, it will write directions as well).

**Comment by de-vries** [comment]
I've made some progress on this subject. Here is how I'm able to edit before upload:

First I change the geodata with the PhotoAdjust plugin of JOSM. (thanx @kaitu ) The great advantage of using JOSM is that you can set your own backgrounds.
The manual upload refuses any pics that are taken with the mapillary app. (from what I understood, to prevent double uploads) So I have to remove the EXIF description tag. I'm not that in to command line tools and scripts, so I use [Phatch](http://photobatch.stani.be/) for that. 

**Here are some suggestions to make it easier to edit the geodata before upload:**
- If The EXIF-coords differ from the coords written in the EXIF-description, use the first. This way you also get a lot more information than in the method I described above. not only do get the original gps data, you also know that the coords are manually edited. 
- Implement a check for doubles, so you can drop the restriction on manually uploading photo's taken with the app. If you add a ID to the EXIF-description, this sould be fairly easy.

**Comment by de-vries** [comment]
closing this because low relevance and the edit options that the new uploader offers
