### ISSUE TITLE
geotag_from_gpx.py - documentation

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#562]
Add requirement to install pyexiv2.
It is fairly obvious since it gives error if you do not, but it should be in the instructions.

**Comment by paulinus** [comment]
On which instructions would you expect it?
There is a mention of it in the docstring of the file
  https://github.com/mapillary/mapillary_tools/blob/master/python/geotag_from_gpx.py
but it might not be visible enough.

**Comment by geomapper69** [comment]
Sorry, my mistake.
I got as far as Requires gpxpy and did not read on.
