### ISSUE TITLE
Add option to re reverse-geocode photos

### ISSUE THREAD

**Issue by riblit** [mapillary/mapillary_issues#563]
An option to re-geocode existing photos to pick up changes in OSM data would be useful.
An example is when there are photos in an unnamed street and Mapillary incorrectly adds the name of a nearby street.  When the street is named in OSM it would be nice to be able to check a "re-geocode" checkbox to flag the photos in that street rather than manually edit and submit each one for approval.

As an example. This one http://www.mapillary.com/map/im/K7vVouCHt0-rCHJlQUWAZA is named as in Ron Mace Drive, Blacktown  It is really in Fleurs Street, Minchinbury.

At the time it was uploaded, Fleurs Street was not named. I have since named Fleurs Street and nominatim reflects the change.

road: Fleurs Street
suburb: Eastern Creek
city: Blacktown
state: New South Wales
postcode: 2766
country: Australia
country_code: au

Also, Mapillary  is using the city field. In Australia the suburb field is the more accurate one.

**Comment by knikel** [comment]
We're not using place names in the upcoming update of mapillary.com
