### ISSUE TITLE
geotag_from_gpx.py fails if there is negative altitude in gpx file

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#564]
Error is invalid value for EXIF type.
Removing negative values from gpx file using text editor find  <ele>-  replace with  <ele>  fixed the error.
The negative values in gpx were correct, some of Baku, Azerbaijan is below sea level (Caspian Sea is lower than the rest of the world oceans)

![untitled](https://cloud.githubusercontent.com/assets/10060476/5928002/a36db620-a690-11e4-8ec9-e3a889eedc9c.png)

**Comment by geomapper69** [comment]
A small modification to line 183 should fix it:
exiv_elevation = make_fraction(int(elevation*10),10)
exiv_elevation = make_fraction(abs(int(elevation*10)),10)

I will test.

**Comment by jesolem** [comment]
Fixed by PR in tools.
