### ISSUE TITLE
Flag signs

### ISSUE THREAD

**Issue by sabas** [mapillary/mapillary_issues#565]
http://www.mapillary.com/map/im/fYY3NW6O5jMec-htbibH6w
This sign is correctly recognised but it's not a real sign (it's a sticker on the truck). It's possible to flag it as an error?

**Comment by ybkuang** [comment]
@sabas, we will work on the next version of the editor so that users can contribute/flag signs.

**Comment by sabas** [comment]
Thanks :+1:

**Comment by gyllen** [comment]
@sabas We have "sneak" released this feature. See if you can find out how it works. Feedback welcome!

**Comment by floscher** [comment]
Same as #573 and #568.

**Comment by sabas** [comment]
@gyllen cool, I tested the deletion and the new sign feature. I noticed that the interface is tied to the image instead of the image container, so when you zoom in, the buttons disappear..
