### ISSUE TITLE
Update iD integration to API v2

### ISSUE THREAD

**Issue by jesolem** [mapillary/mapillary_issues#566]

**Comment by elopio** [comment]
Is this the reason why I no longer see the mapillary layer when editing from the osm website?

**Comment by gyllen** [comment]
How lonf have you had this error? It should be working.

**Comment by elopio** [comment]
On 2015-03-14 10:59, Johan Gyllenspetz wrote:
>
> How lonf have you had this error? It should be working.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mapillary/mapillary_issues/issues/566#issuecomment-80584856>.
>
Nevermind, I've found it now on the map data section.
Either it was moved, or I drank too much. Sorry for the noise.

**Comment by peterneubauer** [comment]
So, closing then ;)

**Comment by elopio** [comment]
On 2015-03-16 09:37, Peter Neubauer wrote:
>
> So, closing then ;)
>

Well, I have no idea what this issue was originally about, it has no 
description. So my comment was not a confirmation that the bug is fixed, 
it was a reply to my own dumb question.
