### ISSUE TITLE
Add possibility to correct the traffic sign 

### ISSUE THREAD

**Issue by eMerzh** [mapillary/mapillary_issues#568]
sometimes the recognition of the signs somewhat fails ..like here
http://www.mapillary.com/map/im/49lyaxVAXy0q-LpZOxt4zQ

30 and 20 instead of 90 and 70....

it should be possible to mark those signs  as incorrect and suggest another value
(i'm even thinking of an app that could event ask to confirm the value ...  so an api would be great :p )

**Comment by ybkuang** [comment]
We are working on a feedback system. Stay tuned!

**Comment by gyllen** [comment]
@floscher @eMerzh We are "sneak" releasing this feature. See if you can find out how it works. At this point we want a lot of feedback :)

**Comment by floscher** [comment]
First of all: It's great to see this feature arriving. It's placed exactly where I'd have searched for it.

But there are a few things that I think should be changed/added:
* The feature is only turned on when previously the traffic sign filter was on and can't be turned off. An on/off-button in edit-mode would probably be better (with default on).
* I don't see the plus sign to add signs for every image (e.g. http://www.mapillary.com/map/e/MZVJTbv4Pjz2urAXYG-qcA doesn't have one)
* I can't change a sign that is already marked as a sign (e.g. can't change the 30 km/h sign to a 90 km/h one)
* I can't move a rectangle, even if I just edited it and (accidentally) hit save
* I can't delete a traffic sign mark where no traffic sign exists
* I'd like to see blur spots integrated into this feature, that would ease marking blur spots very much (like @peterneubauer mentioned in #457 and @pyrog requested in #500)

I appreciate that this is just a sneak peek and probably some of these features are already in the works. All in all I like this tool even in this early stage and am looking forward to see how it evolves.

**Comment by gyllen** [comment]
@floscher Thanks for the feedback

Some answers

1. I built it primarily to be used in the none edit view. You should see edits here http://www.mapillary.com/map/im/MZVJTbv4Pjz2urAXYG-qcA. Note that no edit is availble outside us/eu though.
2. See 1. :)
3. We have that feature (you can press the sign in the left corner). I made it more visible now though. Check it out.
4. We really don't want people to move rectangles. Better remove it and create a new one. Thats a quirk for us to get the feedback right for training. Hope that does not bother to much.
5. See 3.
6. Working on it :), want to get this right first. Then we apply same system to blur.

Keep the feedback coming people.

**Comment by floscher** [comment]
@gyllen I can't edit anything on http://www.mapillary.com/map/im/MZVJTbv4Pjz2urAXYG-qcA, only in edit mode:

![traffic_sign_edit](https://cloud.githubusercontent.com/assets/3904348/6067591/01730202-ad76-11e4-88c6-fb91b68aeb06.png)
That's how it looks for me. I'm on Firefox 35.0.1 (Ubuntu 14.10).

**Comment by gyllen** [comment]
@floscher Can you try login/logout

Also I have deployed new changes. A shift + reload might be needed.

![screenshot 2015-02-05 11 37 44](https://cloud.githubusercontent.com/assets/268859/6067721/751c8b2e-ad2b-11e4-940e-463ffdd67279.png)

**Comment by gyllen** [comment]
@floscher Also not that you can zoom in image while editing

**Comment by gyllen** [comment]
@floscher Do you have time to logon here for more feedback http://www.hipchat.com/g48gQJmpc

**Comment by pyrog** [comment]
@gyllen It's work (tested on Mac OS X with Firefox and Safari), thanks :smile: 

The display is not very clear with all theses icons (especially the litter bins):

![traffic signs editings](https://cloud.githubusercontent.com/assets/2158081/6075893/bcb5b400-addb-11e4-9541-22ad4c89d81f.png)

I suggest:
* to move the delete icons side by side the traffic sign icons.
* center them with the rectangle of the traffic sign.
* to display at any zoom levels the icons on bottom left of the picture (don't zoom)
* Does the share icons is it really useful when editing traffic signs (or blurring) ?

![traffic signs editings](https://cloud.githubusercontent.com/assets/2158081/6076102/b78fd584-adde-11e4-8231-87b9fb02f727.png)

**Comment by pyrog** [comment]
Without zoom, the icons overlapped each others:
![traffic signs without zoom](https://cloud.githubusercontent.com/assets/2158081/6076218/7b684864-ade0-11e4-905e-ae1e1caf7dc3.png)

Could you display only the red squares over the traffic signs without any icons?
(because it easy to check the recognition in moving the mouse cursor hover the icons on the bottom left).
![traffic signs without icons](https://cloud.githubusercontent.com/assets/2158081/6076290/d0d249d4-ade1-11e4-9478-66a64294c8c6.png)

**Comment by pyrog** [comment]
In the **Select traffic sign** popup, could you also display the selected part of the picture ?

![select traffic sign with picture](https://cloud.githubusercontent.com/assets/2158081/6076427/91135624-ade3-11e4-9833-38801eab473f.png)

**Comment by korst** [comment]
My main conclusion of testing this feature is:  the bigger the image is, the better. So either:
- make the image bigger or adjustable (https://github.com/mapillary/mapillary_issues/issues/600),
- improve the usability of the zoom function, or
- make some kind of magnifying glass function.

**Comment by gyllen** [comment]
@korst @floscher @eMerzh Try this out http://www.mapillary.com/map/games/traffic

**Comment by korst** [comment]
@gyllen, First impression; looks great! good that you added the 'other sign' option.

Issue: The control buttons (bottom left) move out of view when zooming. quite a work-flow-breaker... This issue is also present at main/map view

**Comment by korst** [comment]
@gyllen, **I've been testing 'the game' for over an hour now and here are my findings:**
*some of the items below may also apply to traffic sign related stuff elsewhere on mapillary.*

### Issues:
**It's very easy to cheat  this game** 
• Click 'Change sign'
• Change nothing
• Save your changes
• a new version will be made with your name on it, if approved you'll get the points, not the one whom you 'stole' the edit from.
If people start doing this, it will clutter your DB.
Solution: check if actual change is made

**Gets stuck on spinner** After pressing save or approve, it fails to load new image. The stats in the right sidebar do get updated thou. If this happens, you'll have to F5 yourself out of that situation
(it may be just server issues, as the whole site isn't to reactive ATM, I'll report back on it if issue stays.)

**Hovering over unsaved signs doesn't make their red box transparant** like it does to saved signs. Now the only way to look under the red box is to move it.

The **No truck sign** (EU) doesn't have a diagonal bar in some countries. This is a little confusing. 


### Tweaks:
• Add option to focus on your own country.
• Add option to edit/flag incorrect blurs.
• Add a little map with the location of the photo. This is not an important feature and the page is already quite full as it is, so maybe only show it when hovering the location link.
• Add a link to the FAQ: https://titanpad.com/iAg0BrJnaM use the word beta to get away with the current state :) `<a href="https://titanpad.com/iAg0BrJnaM">FAQ (beta)</a>`

**Comment by korst** [comment]
another issue:
Sometimes I get to assess my own edits. There is no approve button though. So When it happens only thing to do is press skip image or refresh the page.

**Comment by gyllen** [comment]
Thanks for the feedback @korst, will wait a couple of days for more feedback and then do another round of bug fixes. The locking should be fixed pretty soon though. Leaving this issue open for more feedback.

**Comment by pyrog** [comment]
> Issue: The control buttons (bottom left) move out of view when zooming. quite a work-flow-breaker... :+1: 

* Traffic sign icons are relatively small, so they are hard to be read

* It's difficult to edit trafic signs when multiples images are superposed
![superposed images](https://cloud.githubusercontent.com/assets/2158081/6177280/96aadd2e-b305-11e4-8983-08afedae6c4c.png)

**Comment by gyllen** [comment]
@pyrog For the last image. Is there any need for you to zoom out like that. Or is the image like that per default?

**Comment by eMerzh** [comment]
Like korst i got a lot of "stuck on spinner" ... often (but not only) with images still processing message.
Couple of suggestion : 
- Make it mobile friendly
- Make it Offline friendly (i know this one is hard)
- Add possibility to export data?
- Add more signs to the sign list

**Comment by jBeata** [comment]
First of all congratulation for this app.
As a suggestion it would be nice if I could move the already detected road sign on the image. There are situations where the detected sign it is not positioned right.
Another suggestion is related to the action buttons: when I zoom in these buttons are not visible anymore, and I need to move the image until they becomes again visible. It would be helpful if these buttons remains visible even if the image is zoomed in.

**Comment by PolyglotOpenstreetmap** [comment]
What I would like to see, is an extra button on the images, which
duplicates the current one having the same size, probably defaulting to
unknown.

It would avoid all the zooming in and out.

Another thing I'd like, is a zoomed in image when hovering over a bbox, but
that's another issue.

Polyglot

2015-02-18 20:36 GMT+01:00 jBeata <notifications@github.com>:

**Comment by pyrog** [comment]
@gyllen
> For the last image. Is there any need for you to zoom out like that.

No, just to show that there are several images at the same place :smile: 

>Or is the image like that per default?

No.

But because the "action" buttons are hide when zoom in, we should zoom out and then see multiple images. That's a bit disappointed :wink: 

And In practice, traffic signs coordinates are only related to one of theses images.

@jBeata
> Another suggestion is related to the action buttons:  It would be helpful if these buttons remains visible even if the image is zoomed in.

:100:

**Comment by Peatsmoke** [comment]
Could I help by sending a collection of dutch traffic-signs in SVG-format?
So if, please let me know where I can send or drop it. ;)

**Comment by gyllen** [comment]
@Peatsmoke File an issue here https://github.com/mapillary/traffico/issues or a pullrequest if you know how to do it.

**Comment by Peatsmoke** [comment]
@gyllen Sorry... Have tried to understand it or to find a how to... I have no idea how to start or how to do this. This is a total new area for me. :/

**Comment by floscher** [comment]
@Peatsmoke What @gyllen meant was to create a new issue (like this here) over in the repository [mapillary/traffico](//github.com/mapillary/traffico) with the green button at the top of the page he linked.
I've done that for you by creating mapillary/traffico#29.

**Comment by gyllen** [comment]
@floscher Thanks for fixing that. @Peatsmoke Sorry for beeing unclear

**Comment by Peatsmoke** [comment]
So... My evaluation for now:
*Making a game wasn't probably the best idea. It seems to me, some people cheating by adding wrong signs, to collect points. Because the evaluation should help "the computer" to recognise signs, this behaviour could give problems in the future;
*Cheap supermarket logo's (Aldi/ Lidl) are giving a lot of false positives;
*By evaluating (own) sequences, the photo's are much to small!!!!;
*I got a lot of false positives by trees;
*Missing a whole lot of signs (I know it takes a lot of time to add those);
*It seems to me the more we evaluate the recognation is getting better.

Cheers!

**Comment by sabas** [comment]
What about the "limitations" (for example: on a left turn sign "PSV only") or other "textual" signs which could be useful for turn restrictions?

**Comment by scandidavian** [comment]
I'm logged in and have reviewed a number of photos in the EU, but yet I receive no points. I've tried Safari and Chrome on Mac OS X Yosemite.

**Comment by gyllen** [comment]
@scandidavian Thanks for reporting, we were selecting to few users in our server (more people has been playing than we expected :)). Its fixed now.

**Comment by Michael21011** [comment]
I was entered to game after some days pause. I see new interface but now I can not change signs on photos. I can add new sign and all works fine, but if I want change sign for wrong one it doesn't react on my click. So, only left top button is not working for me. Windows Server 2008 64 bit , Firefox 31.0

**Comment by knikel** [comment]
@Michael21011 Would you mind checking the game now? The sign edit button should work as expected now. You might need to shift-refresh the page.

**Comment by Michael21011** [comment]
I was entered to game after some days pause. I see new interface but now I can not change signs on photos. I can add new sign and all works fine, but if I want change sign for wrong one it doesn't react on my click. So, only left top button is not working for me. Windows Server 2008 64 bit , Firefox 31.0

Update: I found that I can change sign by pressing big image of sign under photo.

**Comment by Michael21011** [comment]
@knikel, it works now. Thank you!

**Comment by PolyglotOpenstreetmap** [comment]
Could the zoom buttons be repeated outside the picture on the bottom? 

It would also be nice to have hotkeys. Certainly for confirming that the detection was fine.

Ability to scroll with the mouse wheel would be great, but I guess that's hard to implement in the browser.

Of course it should only be possible to validate/save when completely zoomed out.

Jo

**Comment by Michael21011** [comment]
Could you add Country name to under photos? Now there is only Street name and City. Sometime it is interesting to know where the photo was taken.

**Comment by pyrog** [comment]
> Could you add Country name to under photos?
:+1:

**Comment by mbirth** [comment]
I just tried "The Game" for the first time. Despite that the mouse wheel doesn't work for zooming, a bigger annoyance to me was that the initial box (when adding a new sign) is HUGE and when zoomed in fills the whole screen.

The box should have the same size on the screen no matter how deep you are zoomed in.

Also with one photo I was zoomed in to the side where there was a traffic sign and clicking the "+" button didn't seem to do anything. After zooming out I found out that the new box was created outside my zoomed viewport. So maybe you can make new boxes always appear in the centre of the screen.

**Comment by gyllen** [comment]
@mbirth Thanks for your report, this thread is getting out of hand with to many comments. I think most of it is fixed. I gonna go ahead and close this one. @mbirth would you mind open a new ticket with the request you just added.
