### ISSUE TITLE
Traffic signal warning sign detected instead of a bump warning

### ISSUE THREAD

**Issue by stefanb** [mapillary/mapillary_issues#573]
Instead of a european "bump warning" traffic sign mapillary detects "traffic signal ahead warning" sign.

See:
https://www.mapillary.com/map/im/8x7Ea_VQyxpjby85HjLLMQ

**Comment by ybkuang** [comment]
@stefanb Thank you for pointing this out. We will re-train the detection algorithms in the next iteration and also will add a feedback system to tag/remove false signs.

**Comment by floscher** [comment]
Duplicate of #568.

**Comment by gyllen** [comment]
@stefanb We are "snesk" releasing feature. Feedback should now be possible. Try it out and give us feedback.
