### ISSUE TITLE
No manual upload

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#574]
Hi,

Since several days I have a strange behaviour when I upload files manual. It's not the same issue as #530. 
I go to https://www.mapillary.com/map/upload or http://www.mapillary.com/map/upload 
I click "Choose files" and select the files
The minimap appears with my images
I click "Upload to server"
The greys out and its text changes to "Uploading to server"
Pins turn green
At the end I click "Push to Mapillary"
The screen refreshes and I can start to upload more
The files never appear on the map or in my activity-index.

I'm using Chrome 42.0.2288.6 on Win 8.1.

**Comment by ybkuang** [comment]
Sorry about this. Can you try uploading a few images and see what the browser console says after you press the "push to Mapillary" button?

**Comment by gyllen** [comment]
Can you also send us an example image. It might be that your images are beeing rejected

**Comment by Peatsmoke** [comment]
Hi Johan,

I'm at my work,  as soon I'm @home,  I'll send you a example.  Rejecting
would be strange, 'cause I've uploaded more than 82.000 images without
being rejected.

Grtz Marco
Op 1 feb. 2015 07:40 schreef "Johan Gyllenspetz" <notifications@github.com>:

**Comment by Peatsmoke** [comment]
Sems to be solved: pictures are visible on the map... ????

**Comment by gyllen** [comment]
Very wiered case though. How long did it take before the images showed up. Did they show up in your profile before they showed up on the map?

**Comment by Peatsmoke** [comment]
They didn't show up at all. That's the weird... It took almost three days
before they showed up in my activity and on the map. It looked that they
got stuck somewhere or somehow.

2015-02-01 18:42 GMT+01:00 Johan Gyllenspetz <notifications@github.com>:
