### ISSUE TITLE
add_mapillary_tag_from_exif.py -  missing enviroment variable

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#575]
MAPILLARY_UPLOAD_TOKEN is missing.

I do not see it when I check the data at:
http://api.mapillary.com/v1/u/uploadhashes

is it the same as permission_hash or signature_hash or is it something different ?

**Comment by geomapper69** [comment]
I found that script upload_each_folder_as_sequence.py is the one that is defining the environment variable MAPILLARY_UPLOAD_TOKEN.
This is a script that I have not previously used, so the variable is not defined in my system.
I am trying to run upload_each_folder_as_sequence.py, but am currently getting an invalid response from https://api.mapillary.com/v1/u/login.  Gives response 401:Unauthorized.
I will continue to work on it.

**Comment by geomapper69** [comment]
When I try in my browser:
https://api.mapillary.com/v1/u/login?password=********&email=geomapper69
I get:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.

![untitled2](https://cloud.githubusercontent.com/assets/10060476/6103266/ab2cb2a6-b05b-11e4-8843-eb13ece773a8.png)

**Comment by gyllen** [comment]
@geomapper69 Its because the call is a POST not a GET. You should access your parameters from here though http://api.mapillary.com/v1/u/uploadhashes

**Comment by geomapper69** [comment]
@gyllen    OK, but that only gives me permission_hash or signature_hash, I need MAPILLARY_UPLOAD_TOKEN.
I found it is created by script upload_each_folder_as_sequence.py, but this script fails.  I have tried logging in & out of Mapillary on the browser and it makes no difference. 
![cwindowssystem32cmd exe 10022015 215200](https://cloud.githubusercontent.com/assets/10060476/6132924/b6a6d278-b16f-11e4-8db7-f5d483e527c3.png)

**Comment by geomapper69** [comment]
@gyllen I think I have found the problem.
upload_each_folder_as_sequence.py asks for the environment variable MAPILLARY_USERNAME, but it should be asking for MAPILLARY_EMAIL for the correct logon parameters.
I will adjust and test.

**Comment by geomapper69** [comment]
@gyllen , @peterneubauer  The scripts are now completing without errors, however there still seems to be a mismatch in the EXIF headers MAPSettingsEmail is being assigned the username, and MAPSettingsUsername is not being defined.
I am not sure this will be an issue or not when they are uploaded, I just tried a test upload to see if it needs the extra tag info or not.

**Comment by gyllen** [comment]
@jesolem Can you have a look at this?

**Comment by peterneubauer** [comment]
well, really, the environment variable is USER_EMAIL, which also is in the MapSettings. Let's change the USERNAME env variable name to reflect that.

**Comment by geomapper69** [comment]
Still testing to try to get the output add_mapillary_tag_from_exif jpgs to go to Mapillary via upload.py.
I have renamed the files %Y_%m_%d_%H_%M_%S_000.jpg, and the exif tags look ok, but still the uploads are not being processed (no confirmation emails received).
I compared the exif tags between a native IOS Mapillary jpg and the add_mapillary_tag_from_exif (python) jpgs and find:

Tags in IOS but not in python:
MAPAccelerometerVector:
MAPAltitude:
MAPAtanAngle:
MAPCameraMode:
MAPLocalTimeZone:
MAPDeviceName:
MAPGPSAccuracyMeters:
MAPSequenceCaptureUsed:
MAPSettingsProject:
MAPSettingsTokenValid:
MAPShowCameraTutorial:
MAPVersionString:

Tags in Python but not in IOS:
MAPOrientation:

I can try to modify the python script to include values for the missing tags, if this is the problem?

**Comment by geomapper69** [comment]
Just received email to show that latest test worked.

**Comment by jesolem** [comment]
Just checking in on this issue. Is it still relevant?

**Comment by geomapper69** [comment]
since setting all 3 of the environment variables (username, email & password), its been fine.
It can be closed.
