### ISSUE TITLE
Consider moved locations when doing sequence angle correct

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#576]
I edited a sequence. I moved photo's and corrected angles (in that order). Here is the change set: http://www.mapillary.com/map/cs/jCmZEK0XSVdyLhI-HP-vSg

To correct angles I used the button that makes all images in this sequence so that they are pointing in the direction of the next image in the sequence.

I expected that in this operation the new locations of the images would be used. Instead the old locations were used and, now that the change set is applied, the images are not pointing in the direction of the next image.

**Comment by jesolem** [comment]
This needs to be fixed. Adding to the list for next editor work.

**Comment by pbb72** [comment]
The title if this issue needs to be changed, it's not very clear.

**Comment by de-vries** [comment]
this works in the new editor
