### ISSUE TITLE
Different modes for car and bicycles

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#577]
I would like to have a different mode for car and bicycle, where the latter would have a much lower requirement on "having to move faster" to take images; sometimes on a bike you want to on purpose go slower to capture something without too much vibration, but then, the app denies you that wish because you go to slow...

This is partially related to the issues described in #247, and solving that *might* issues make this one obsolete.

**Comment by jesolem** [comment]
We're thinking of doing 2 automatic modes: "Riding" and "Walking (auto)" where the latter does not have the speed requirement and possibly a longer delay (4s instead of 2s?). Would that work?

Relying on x meters could be an option but only when the GPS accuracy is better than ~x meters. Would give unexpected results otherwise...

**Comment by peterneubauer** [comment]
Also, I will add a setting in Android to disable the auto-pausing on low velocities, should be exactly what you want. I can't lower the default velocity more, since the GPS accuracy will otherwise interfere and give false movements.

**Comment by peterneubauer** [comment]
Implemented. Will be out in the next release.

**Comment by rudolfmayer** [comment]
Wow, that is a fast response time :-)

I understand the limitations with the GPS, makes sense indeed. Removing the auto-pause on low velocities might do the trick - but isn't that then the same as the walking mode?

**Comment by peterneubauer** [comment]
Yes, but still it's good for the backend to know you where biking. I was playing around with Google activity recognition - not working great.

**Comment by peterneubauer** [comment]
Riding and auto-waling implemented on Android.
