### ISSUE TITLE
Web-UI: Sequence navigation buttons disappear when zoomed in

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#580]
When zooming into an image, the buttons to navigate backwards/forwards in a sequence disappear, which means I always have to zoom out again before I can go to the previous/next image. Ideally, the buttons should stay visible..

(If removing the button in zoomed mode is actually *intentionally*, sp that they don't hide details in the image, this should be an explicit feature to show/hide buttons, as also the +/- buttons could cover interesting things)

**Comment by korst** [comment]
this was also mentioned is this issue: https://github.com/mapillary/mapillary_issues/issues/356

**Comment by jesolem** [comment]
Duplicate to #356 , closing
