### ISSUE TITLE
angle ajusting inconvenience

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#582]
When adjusting the angle of a single image, using the +/- buttons there is a little inconvenience.

normally in the edit view all markers on the map are stacked in the order of the sequence and the marker of the selected image (the green one) is on top. But if the surrounding markers are red/edited and I press the + or - button its no longer on top of the stack and turns red again. (it still renders on top of the blue markers, but it jumps back in sequence order with the red ones.

**Comment by knikel** [comment]
Closing in favour #199, will be solved by the editor update.
