### ISSUE TITLE
Going trough browser history does all kind of weird things

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#584]
When I use the forward/backward buttons in my browser (FF35) all kind of weird an unpredictable things happen.

For example:
- After browsing trough a few sequences I start pressing the back button. nothing happens, except that the url in the address bar changes.
- I browse trough a sequence, move to another sequence, go 3 steps forward and start pressing the back button. after the 5th click I go back to the first sequence.
- Sometimes (while going back in browser history) I hit a page that redirects me and thus removes some of the browser history.

Two things that should change imho:
- Mapillary should make way less records in the browser history. (go figure out what event are worthy of putting in browser history)
- When pressing back, I should go back to something.

**Comment by gyllen** [comment]
I think its not an issue of putting less in the browser history. We want every page to be accessible by the link. Its more a matter of getting the back button to work for images.

**Comment by pbb72** [comment]
I'm no expert on this, but I believe displaying a unique link for every photo does not necessarily mean you have to step through all of them while pressing the back button. I think I've seen web apps that update the URL for every action you take (with "#" hash marks), but pressing back takes you to the previous full page, not just one action back.

Though that still keeps the question open if you want to backstep through all photos, or not. I personally would prefer not, instead being taken all the way back to the last full page load.

**Comment by knikel** [comment]
@pbb72 @de-vries:
@paulinus deployed an awesome fix for that recently, the behaviour is a bit more sane now. You're basically ‘locked’ to whatever you do in the /map/im view as a one entry in browser history now. Pressing back button will move you back to the major view (different than /map/im URL) you visited previously.

**Comment by pbb72** [comment]
Seems to work great now, thanks! :+1:

**Comment by de-vries** [comment]
That's much better. There is only a minor issue now when you go trough an edit page. 

to analyse this:

>If you start at  photo "1" > click `edit` > click `cancel edit`
>your browser history looks like:
>- photo "1" 
>- photo "1" 

>If you start at  photo "1" > click `edit` > click `edit blur` > click `request blur` > click `go back to edit` > click `cancel edit` 
>your browser history looks like:
>- photo "1" 
>- edit photo
>- edit blur
>- photo "1" 
>
>If you do the same but click `go back to browsing` after the blurring you'll get the same browser history.

At first this looked a bit strange to me, but after writing this it's quite clear that clicking `cancel edit` doesn't trigger a new event in the browser history while it would make a lot more sense if it did.

**Comment by knikel** [comment]
@de-vries: I’ll investigate that, should be a quick fix. Thanks!

**Comment by de-vries** [comment]
I've just tested this to see if still relevant in the new viewer.

The behaviour now is that when you press "cancel edit" there is made a entry in the browser history, but that entry doesn't link to the edit page, but to the photo.

**Comment by knikel** [comment]
This won't be an issue in the upcoming update. We have an awesome router that persists the map changes to the route, etc. Will close when we roll it out.
