### ISSUE TITLE
link button to iD and JOSM has an offset

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [mapillary/mapillary_issues#586]
When using the link button to iD or JOSM on the info page of a picture, the position one 'lands' at in the editors is a bit off. In iD it ends up under the menu bar on the right and in JOSM it's also more to the right.

In iD it's also a bit annoying that the Mapillary layer is not switched on by default. People who don't now iD, risk never figuring out that it's possible to see Mapillary pictures with it.

Jo

**Comment by gyllen** [comment]
Looking into this. Enabling Mapillary per default in iD might be hard. Thats not really up to us.

**Comment by PolyglotOpenstreetmap** [comment]
Created an issue for it on the iD side:
https://github.com/openstreetmap/iD/issues/2524

Jo

**Comment by gyllen** [comment]
Closing
