### ISSUE TITLE
Map in Edit screen zooms to wrong point

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#590]
1. Open a photo in Mapillary. 
2. Click the Edit button to go to the Edit screen. 
3. Zoom in to the map by clicking the "+" button or scrolling the mouse wheel.

Problem: the map zooms in too far to the left (west), a few 100m outside the original map view.

The problem can by solved by dragging the map view once, or by resizing the browser window width to below 1280 pixels (triggering responsive design mode).

**Comment by pbb72** [comment]
It's say this is a *bug*, not an *enhancement* request.

**Comment by knikel** [comment]
This issue been fixed now, thanks for spotting it @pbb72!

**Comment by pbb72** [comment]
Thanks, works very well! I don't know if #914 is technically the same problem, that also doesn't zoom to the right location.

**Comment by knikel** [comment]
@pbb72 :+1:! #914 is a similar one, but I haven't gotten to that issue yet :)
