### ISSUE TITLE
Don't switch images when hovering over pins

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#591]
In the Edit screen, the active image is switched simply by hovering over the pin for another image in the map view.

This is very annoying, for example when moving the mouse to click on the zoom buttons. I also causes a lot of trouble when moving pins, where the move operation is aborted or canceled while dragging the pin across another pin.

The active image should only be switched when clicking on another pin.

**Comment by korst** [comment]
I also found this annoying, but after getting used to it, it became a useful feature to me. Maybe an on/off switch? (checkbox "select on hover" next to map)

> It also causes a lot of trouble when moving pins, where the move operation is aborted or canceled while dragging the pin across another pin.

agreed, this should be fixed.

It's also annoying when zooming. When zooming-out the markers get closer to the cursor an you risk touching them. When zooming-in you have to keep distance and risk the makers getting out of view.

**Comment by mprins** [comment]
for sequences where i just  want to check for blurring this would add up to thousends of clicks extra

**Comment by korst** [comment]
> for sequences where i just want to check for blurring this would add up to thousends of clicks extra

this could be solved by issue https://github.com/mapillary/mapillary_issues/issues/472

**Comment by knikel** [comment]
This won't be an issue with updated editor. Will close when we roll it out.

**Comment by gyllen** [comment]
Fixed in new editor.
