### ISSUE TITLE
improve panorama sequences

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#592]
Due to imprecise gps every photo taken in panorama mode has different coords and the sequence gets spread out [like this one] (http://www.mapillary.com/map/im/tm7SGDSLuPNxgGPWajgfQQ).

A solution could be to take the average of all gps coords in the sequence and apply it to all the photo's.

**Comment by gyllen** [comment]
Im not sure this is worth it.

**Comment by pyrog** [comment]
Theses images seem to be stitch by Mapillary and the GPS are not averaged:
![panorama mode](https://cloud.githubusercontent.com/assets/2158081/7216127/05b8d02e-e5f4-11e4-9a74-37e3c0aca2e8.png)

http://www.mapillary.com/map/im/TS9JnSDu-L8H_H4qyvuJfw

See also #804

**Comment by de-vries** [comment]
duplicate of #83
