### ISSUE TITLE
Stitch begin and end of panorama sequences together

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#593]
Stitch begin and end of panorama sequences together, so you get an endless sequence.

**Comment by jesolem** [comment]
Good idea.

@ybkuang I think we are doing the matches already between first-last but we could connect the prev/next too if there is enough overlap. Let's see.

**Comment by ybkuang** [comment]
Yes. We are stitching the first and the last now. Could be that it doesn't have enough overlap or misses the matches? @korst do you have a link to a sequence?

**Comment by korst** [comment]
@ http://www.mapillary.com/map/im/2ZybfwNeukMP7yrsxriwYw there is no down arrow. you could use the little circles tho.

@ http://www.mapillary.com/map/im/mZ0BqCdfi3xEi7PlSxz0bw when pressing the down button, you jump to another panorama, but you could have continued rotating.

Approaching the [end] (http://www.mapillary.com/map/im/um2uLX-aRToytvmaaJMpmw) of that sequence and pressing up, the same happens. press up again and you jump to jet another sequence. (press down two times and you are heading in another direction than were you cam from :/ )

[Here] (http://www.mapillary.com/map/im/afy16MfTF_tPGct9cUt7ug) is another sequence where you can't use the arrows to rotate trough the end of the sequence (both directions), but you can use the little circles,

**Comment by jesolem** [comment]
> Here is another sequence where you can't use the arrows to rotate trough the end of the sequence (both directions), but you can use the little circles,

This is what I meant too. If you can go with circles you should be able to go with prev/next arrows.

**Comment by korst** [comment]
> This is what I meant too. If you can go with circles you should be able to go with prev/next arrows.

I would like to add to that that pics in the same sequence should be prioritized over others.

**Comment by ybkuang** [comment]
@korst Agree! We need to improve the navigation in the viewer. It is in our to-do list.

**Comment by de-vries** [comment]
the way panoramas are handled now makes this issue irrelevant.
