### ISSUE TITLE
install on Huawei Y530-U00 not supported

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [mapillary/mapillary_issues#597]
I tried to install Mapillary on Huawei Y530-U00, 4.3, kernel 3.4.0

but it claims it's not supported.

**Comment by peterneubauer** [comment]
is https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk working? (prerelease, don't kill me if it doesn't work)

**Comment by PolyglotOpenstreetmap** [comment]
Hi Peter,
It installed fine, but behaved somewhat oddly. Do you think it makes sense to install it on my 'production' phone and test it further like that?
Jo

**Comment by peterneubauer** [comment]
Updated prerelease, can you check out https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk again?

**Comment by HolgerJeromin** [comment]
i have 0.39 installed on my desire hd with custom 4.0.4 Rom.
installing this prerelease does not work:
clicking install, ok for permission, wait about 10 seconds, " application was not installed".
must i uninstall the old Version? I miss the message i remember from installing new osmand apk: this is an update, all setting will survive.

**Comment by PolyglotOpenstreetmap** [comment]
Hi Peter,

Is there a more recent version? The one from 2pm yesterday still crashes quite often

**Comment by peterneubauer** [comment]
Yes, can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk now?

**Comment by PolyglotOpenstreetmap** [comment]
After taking 1 picture. I get Error:take picture failed when trying to take
the  next one. I love the new way to review the pictures and flicking  away
the bad ones.

**Comment by peterneubauer** [comment]
Got the log?

**Comment by peterneubauer** [comment]
Seems something is strange with your camera. Can you try restarting your
phone?

**Comment by peterneubauer** [comment]
Thanks for all the help @PolyglotOpenstreetmap , closing this finally!
