### ISSUE TITLE
We need a dos and don'ts list for trafic sign tagging

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#599]
There are a lot of situations were it's hard to say what the best course of action is. A lot of them come from the immaturity of this feature, but others will always be there. This feature definitely needs documentation on how to (not) use it. Here are some examples of situations were its unclear how to handle:

- Should I tag [this sign] (http://www.mapillary.com/map/im/pEbTb-BG1LsV33M0wxit9w)? (it's from a Dutch cycle route network) And other uncommon/non-international signs?
- What to do if the sign is not available?
- [This sign] (http://www.mapillary.com/map/im/DwZ4sipeD6-r13HVE2MMcQ) is almost tagged right, but the exact sign is not available. remove it or let it be?
- Should I tag [additional panels] (http://www.mapillary.com/map/im/NURMSv_TP0Wi3ffvwqE0DA)?
- Can I tag [direction panels] (http://www.mapillary.com/map/im/BBTabHxrAwnzoDCvmSykPg)? those contain essential information for osm lane tagging.

**Comment by Nakaner** [comment]
I think that this is not the right forum/location to discuss OSM tagging. Use an [OSM mainling list](https://lists.openstreetmap.org/listinfo), international) or OSM Forum instead.

korst wrote:
> Can I tag direction panels? those contain essential information for osm lane tagging.

See [this OSM way](https://www.openstreetmap.org/way/324350860/history#map=18/50.11664/8.53654) (it is a very detailed tagged way, usually you only use destination:lanes and destination:ref), a discussion about [OSM Lane Visualizer](http://forum.openstreetmap.org/viewtopic.php?id=29866)

**Comment by korst** [comment]
@Nakaner, I'm not sure how you understood my question but I'm not trying to discuss OSM tagging.

> See this OSM way 
yea, something like that, but i need the information from the direction panels to do that.

**Comment by gyllen** [comment]
Created titanpad for easy collaboration around this subject. Agree that we need a FAQ, please join https://titanpad.com/iAg0BrJnaM

**Comment by korst** [comment]
@gyllen I've added an answer to https://titanpad.com/iAg0BrJnaM 
You'd better check that I didn't say something stupid

**Comment by gyllen** [comment]
@korst Thanks! Good answer. Im gonna compile this and add to the FAQ button in the game.

**Comment by de-vries** [comment]
@gyllen I've added some Q&A's again. 
Also, if you want to keep this titanpad usable, maybe clean it out a bit.

**Comment by gyllen** [comment]
Updated FAQ in game

**Comment by de-vries** [comment]
@gyllen nice work! But the link in the 6th question seems broken.
