### ISSUE TITLE
Android App v0.39 crashes continously on LG Optimus P990

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#601]
The current Android app (downloaded today via direct apk link) crashes after the first, second or third image taken. I use an external GPS receiver (Holux M-241) via bluetooth (I use BlueGPS to connect phone and receiver).

To reproduce:

1. Turn on GPS receiver (bluetooth is on) and wait for fix (I did it [here](http://www.mapillary.com/map/im/I13VOCL1g3ifUZCdG4qjrQ)).
2. After fix wait two minutes extra (because a fix does not meant that the accuracy is good enough).
3. Start BlueGPS at the phone and connect it to the receiver.
4. Start Mapillary app and go to camera.
5. Change to walking mode.
6. Take the first picture (manually, i.e. press shutter button).
7. Take the second and third image. The app crashes after the third image.
8. You are now at the Mapillary start screen. If you tip at the camera icon, the app cannot open the camera (blocked by system).
9. Wait a moment, until camera can be accessed again.
10. Enter camera mode. The app will crash again after the first, second or third image.

Rebooting the phone does not help. Changing to car/bicycle mode and back does not help. I will try car mode later today when I use my car.

I had app crashes after the third image on September 30, 2014 but rebooting was a workaround. At that time, one reboot was enough and the app worked well afterwards.

How can I enable logging? Do I have to enable development mode? (If yes, please add to the description of this checkbox that it also enables logging.)

**Comment by Nakaner** [comment]
System information: 

* app version: 0.39
* images are stored at external SD card (which is accessible)
* LG-P990
* Cyanogenmod version: 10.1-20140216-NIGHTLY-p990 (latest version, phone is out of support)
* Android 4.2.2
* 342 MB RAM
* ARMv7 (v7l)
* rooted

**Comment by peterneubauer** [comment]
@Nakaner any chance you can uninstall the app and try installing https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk (not finished the layout) and let me know if that one works better?

**Comment by Nakaner** [comment]
The crashes also occures in the dev version you provided.

I have searched on my SD card and found an apk (called 0.39, too) which I downloaded on September 26, 2014. This version does not have the bug.

You will get feedback about the dev version via email.

**Comment by mprins** [comment]
@Nakaner sometimes purging the dalvik cache helps

**Comment by peterneubauer** [comment]
@Nakaner could you send a log from the 1.0 dev version so I can see if there is anything in there to fix?

**Comment by Nakaner** [comment]
@mprins Purging dalvik cache help and helped not.
I tested several versions of Mapillary app today. Deleting dalvik cache helped if it was the version from September and yesterday. It did not help for 1.0 dev version.

I tried to uninstall one version, deleted dalvik cache and installed another version. This helped if I installed v0.39. I was unable to get 1.0dev to work. Purging dalvik cache did not help there.

@peterneubauer I cannot find a "send logs" button in 1.0 dev version? Where is it located?

**Comment by peterneubauer** [comment]
@Nakaner have added the log sending to the main drawer again, try https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk

**Comment by peterneubauer** [comment]
The app is updated, same url, feel free to re-test.

**Comment by Nakaner** [comment]
The crashing bug is fixed now in v1.0 dev. You can close the issue, if you do not want to backport it to v0.39. I will continue to use v1.0. :-)
