### ISSUE TITLE
Provide Download of Old Stable Android App

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#602]
Could you please provide (next to the existing apk link at your website) a link the old stable version? I have updated my version (I do not use Google services) today without making an app backup (using Titanium Backup) before. A few minutes ago I wanted to go out and take a ~ 100 images. [Because the app crashes continously](https://github.com/mapillary/mapillary_issues/issues/601), I would like to use the old version instead.

**Comment by korst** [comment]
related: I find it inconvenient that the .apk link doesn't contain the version number. As another one who doesn't use Google services that leaves me with no quick way to find out what's the newest version.

**Comment by gyllen** [comment]
@korst I like the idea, @peterneubauer can we add version number to apk link?

**Comment by peterneubauer** [comment]
The link is https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_038.apk

**Comment by de-vries** [comment]
Thanx, I'm satisfied.
