### ISSUE TITLE
Traffic signs recognition

### ISSUE THREAD

**Issue by ohrie** [mapillary/mapillary_issues#603]
![unbenannt](https://cloud.githubusercontent.com/assets/6567206/6088604/7945e438-ae58-11e4-8ad5-4de6a2e66dae.png)
There are some problems with the recognition of traffic signs. Blurry Lights were detected as some signs. Example: http://www.mapillary.com/map/im/6t3PzWbt72ryDD_DE0XeXQ (need to activate traffic signs)

**Comment by korst** [comment]
click on the trash icon next to each 'traffic sign' to delete it, then click the save icon.

**Comment by ohrie** [comment]
I know, but i shouldn't be recognized by the algoritihm.

**Comment by korst** [comment]
If I understood correctly, they use this feedback to train the algoritihm.

**Comment by gyllen** [comment]
Yes we do, we will use your feedback to improve our detection algorithm. Thanks for helping out!
