### ISSUE TITLE
Can't save signs in chromium

### ISSUE THREAD

**Issue by korst** [mapillary/mapillary_issues#604]
After adding or editing a traffic sign in Chromium (Version 40.0.2214.94 Ubuntu 14.04 (64-bit)) I can't save the changes. If I click the save icon a spinning icon appears and that's all.

Problem is not present in Firefox.

**Comment by gyllen** [comment]
Can you try login/logout?

**Comment by korst** [comment]
yea that worked, apologies for not thinking of that myself.
