### ISSUE TITLE
Can't set sign type in editi mode

### ISSUE THREAD

**Issue by korst** [mapillary/mapillary_issues#605]
When in edit mode you can't set the type of traffic sign

**Comment by gyllen** [comment]
Press the animated version of the sign.

**Comment by korst** [comment]
I'm not sure which one you mean, but I pressed both the sign rendered on the photo and the one in the bottom left corner. didn't work. also when I press the '+ sign' I don't get the dialog box that let me choose the traffic sign. 

In the map view all this thing *do* work.

**Comment by gyllen** [comment]
Ah got it. So its in the edit mode. Makes sense. Im not sure we are going to support this feature in edit mode yet. What do you think? I it needed?

**Comment by korst** [comment]
It's needed. And for this reason: my main conclusion from testing this feature is that the photo needs to be as big as possible to adequately tag signs. Also you don't need the map if you are, for example, looking to improve the sign data of a given sequence. I'd much rather use this feature from the edit mode.

I think it makes sense to put all edity-thingies on one page. From both the viewpoints of people who want to edit and those who just want to look at/explore the data.

I think it has been mentioned before, but I would like to see the edit blurring feature merged into this. (now it takes to many clicks and page refreshes)

**Comment by gyllen** [comment]
Disabled editing in edit mode. Edit mode will step by step be incorporated in to ordinary view. To speedup editing and make things more robust.
