### ISSUE TITLE
Traffic signs turn of after editing blurs

### ISSUE THREAD

**Issue by korst** [mapillary/mapillary_issues#606]
how to reproduce:
- turn traffic signs on
- go to edit screen
- click 'edit blurring'
- edit blurring
- click 'request blurring'
- click 'back to edit/browsing'
- traffic signs are turned off

This shouldn't happen. Also there should be a way to trigger the traffic signs from the edit page. (see issue https://github.com/mapillary/mapillary_issues/issues/594)

**Comment by gyllen** [comment]
Removed edit traffic signs from edit mode. Edit mode will step by step be incorporated into ordinary viewer to speed up edits.

**Comment by korst** [comment]
The issue isn't solved. When you edit some blurring and then come back to the map view, the traffic signs are turned off.

**Comment by gyllen** [comment]
@korst Issue will be solved when blur gets incorporated into image view. Its on list of upcoming improvements. Sorry for beeing unlcear about that.
