### ISSUE TITLE
Google Sphere

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#608]
Not an issue, but I would like to know more about Google Sphere uploads.

- Some Mapillary links to good examples?

- Does Mapillary in some way crop the pictures?

- Will Mapillary be able to do its magic on Google Sphere pictures?

- Google Sphere pictures should be great for the 3D reconstructions, Are/will they?

**Comment by ybkuang** [comment]
@Andblue 

> Some Mapillary links to good...?
Here is one panorama from @kaitu http://www.mapillary.com/map/im/9KkA1VG_fQSWZVcn8z-H4A
You can choose the panorama filter at the bottom left corner to see panorama images (not all of them are Google Sphere though)

> Does Mapillary in some way crop the pictures?
We don't crop Google Sphere uploads.

> Will Mapillary be able to do its magic on Google Sphere pictures?
The Google Sphere photos will go through same processing pipeline (e.g. face detection, traffic sign detection) as normal uploads. On the other hand, our process pipeline has not taken into account the distortion in Sphere photos. Therefore, some of the processing (detections) might fail. We will enhance the processing in the future. 

> Google Sphere pictures should be great for the 3D reconstructions, Are/will they?
In general, a Sphere will contain more information of the scene which will facilitate the 3D reconstruction. Similar to detections, special treatment is needed for 3D reconstruction for Sphere photos. Our current focus to build a robust reconstruction pipeline for normal photos and later integrate also the rich Sphere photos.

**Comment by Andblue** [comment]
I have been toying with the idea of buying a 360cam from Giroptic, which snaps 360x300 degree pictures (i.e. almost a globe). A bit pricey and I still would need to find a good mount solution for the car. And I haven't found any feedback from people who actually used the final product.

**Comment by ybkuang** [comment]
We ordered two 360cams for testing. Still waiting for delivery though ...

**Comment by Andblue** [comment]
Aha, that explains the lack of user feedback on the internet regarding the 360cam.
