### ISSUE TITLE
Add "Uploads Pending" count to profile page

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#609]
While debugging other items, I discovered that when I went into the Manual Uploads page, I had a lot of pending uploads there needing to be pushed to server.
I pushed these and then found more, then push, then found more.
I am normally uploading with python upload_with_authentication.py and sometimes my internet connection fails and I need to restart the upload.
I am guessing that these are the orphaned pictures in the sequences that never got a "DONE" sent with the correct sequence ID.
I found I can check https://api.mapillary.com/v1/u/uploadspending to check for this in the future, but a counter on your profile home page would also help to draw your attention to the problem.

**Comment by gyllen** [comment]
I problem here might also be that you are pushing duplicates. We are making a unique hash for every image so we are able to detect duplicates, we are also about to implement it. Would an email saying that we did not upload your image since its a duplicate be sufficient?

**Comment by geomapper69** [comment]
yes, that would be enough.
I will also add a note in the documentation in the python upload script.

**Comment by gyllen** [comment]
Thanks for feedback. This is under implementation.

**Comment by dymo** [comment]
Does that mean i have a lot of pending uploads from all the times I had to restart upload_with_authentication.py because of connection problems?

Can/should I do something to delete them? There is no reason to keep gigabytes of my duplicated images.

**Comment by geomapper69** [comment]
@dymo Did you try to look at  https://api.mapillary.com/v1/u/uploadspending ? (you may need to log out then log into Mapillary to make it work).  It gives you a list of pending files (if any).
You can then go to http://www.mapillary.com/map/upload and either delete them (clear all images), or complete the upload (push to Mapillary).
You may need to refresh the page many times after deleting or completing, if you have many failed sessions, since each sequence is displayed separately.

**Comment by dymo** [comment]
uploadspending give me a long list, but when i go to the manual upload page, it says "1 of 1 images uploaded (100%)" and shows a zoomed out map without any pins.

When i look at the network requests in developer tools (Chrome 40), i see that the call to uploadspending does return a list of 215 images and no errors in the console.

I did try logout / login + refresh several times.

@gyllen it would be nice to have a simpler way to delete all these pending sequences or even better auto delete after x hours/days of inactivity.

**Comment by gyllen** [comment]
@dymo I agree. Will fix that. Also it would be nice if images where viewable in editor on site. Main reason for them not beeing that now is since manual upload from site rename files in such a way that web page can read lon,lat from filename.

**Comment by gyllen** [comment]
@geomapper69 @dymo You should now be able to see pending stuff on webpage. Check it out and reopen if you are missing something.
