### ISSUE TITLE
Incorrect order in a sequence

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_issues#610]
http://www.mapillary.com/map/im/ht5HNseY2TUQr2ToZHIVVw

**Comment by floscher** [comment]
http://www.mapillary.com/map/e/6GrR4TAYgRLQP5w2lwtcWQ (from the same sequence) looks strange. Is this an issue with the camera or with mapillary?

**Comment by gyllen** [comment]
We are aware of this. Its a backend problem. Reordering sequences at the moment. @peterneubauer please close when done.

**Comment by peterneubauer** [comment]
@floscher that image is probably a phone problem.

**Comment by peterneubauer** [comment]
The faulty image has a data_captured of 0, @gyllen you probably need to fix that first. http://www.mapillary.com/map/iminfo/ht5HNseY2TUQr2ToZHIVVw

**Comment by ybkuang** [comment]
@peterneubauer @gyllen I did a rerun for that image just now.
