### ISSUE TITLE
Uploading using Google Drive or Dropbox

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_issues#611]
My phone memory is limited and the Internet connection is really bad. I would like to backup photos to my laptop and upload them later. Now I can do it using Android File Transfer and the python script, but I don't want to run the script manually and check it's progress. What would be more convenient for me is to give you full access to some dropbox or google drive directory and just put new photos in it.

**Comment by gyllen** [comment]
Yes I like that idea. Im thinking that you can just dump images taken from the app into a mapillary folder on your dropbox account and then we just harvest the images from there. Keeping this here as an enhancement. With current work load it might take some time before we get around to it though.

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
