### ISSUE TITLE
Assume default Orientation when tag is missing

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#613]
The manual uploader refuses images which do not have the Orientation tag set. Instead, it should assume the default setting (1 - Horizontal) when the tag is missing.

(It seems that exporting from Lightroom removes the Orientation tag.)

**Comment by gyllen** [comment]
@ybkuang You are the EXIF master, is this something we can do?

**Comment by ybkuang** [comment]
@pbb72 The original idea of having this requirement is to ensure the data quality of the images. But you are right, we will consider removing the orientation tag requirement in the near future! Thanks!

**Comment by stevage** [comment]
I just ran into this issue. For some reason, Picasa seems to not include (and strip it off) this tag when you crop and export an image. Well, I think - it's a bit hard to be sure without a better EXIF viewer. But I tried to upload 20-30 photos and a quarter of them were rejected.

**Comment by stevage** [comment]
Here's how I worked around the problem for myself with a Bash script:

```
#!/bin/bash
if [[ -z "$@" ]]; then
  echo Usage: set_orientation.sh [file1.JPG] [file2.JPG] ...
  exit
fi
for f in $@; do
  if [[ -z `exiftool -Orientation "$f"` ]]; then
     exiftool -n -Orientation=1 $f
  fi
done
```

After a bit of research, I do think the current behaviour is wrong. There is no requirement that any image have an Orientation EXIF tag, and no reason to think that any image without such a tag is incorrectly oriented. Indeed, it seems that Picasa applies the required rotation, then strips the tag, when it saves an image (whether through export or just saving changes.)

**Comment by pbb72** [comment]
Adding a missing Orientation tag can be done in one command in ExifTool:

    exiftool -Orientation#=1 -if "not $Orientation#" <DIR>

**Comment by jesolem** [comment]
The requirement on Orientation tag is now removed in the new manual upload. Defaults to 1 if missing.

Thanks for good suggestions and your patience ;)
