### ISSUE TITLE
Traffic sign feedback: add a popup when there are unsaved changes

### ISSUE THREAD

**Issue by ybkuang** [mapillary/mapillary_issues#614]

**Comment by ireun** [comment]
Would love to see that, or an auto-save while going to the next photo..

**Comment by de-vries** [comment]
In map view you should disable the drag to go to next pic feature when editing signs. or at least give a warning.
I lost edits by mis-clicking when trying to drag makings because of this.

**Comment by gyllen** [comment]
This sounds like a good idea to me, what do you think @knikel?

**Comment by knikel** [comment]
@ybkuang, @ireun, @de-vries Added to the viewer! Thanks for the feedback!
