### ISSUE TITLE
Some signs are missing in Detected Traffic Signs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#615]
See http://www.mapillary.com/profile/chuck/ors
![detected traffic signs](https://cloud.githubusercontent.com/assets/2158081/6127985/4bb8013c-b131-11e4-9cf6-4166e51d1f0c.png)
* type-information_disable_persons
* type-prohibitory_no_pedestiran_or_cycles (typo :wink)

http://www.mapillary.com/profile/allen/ors
* type-warning_winding_road
* type-warning_skewed_railroad_crossing

**Comment by gyllen** [comment]
Add missing signs to traffico

**Comment by knikel** [comment]
This has been fixed now.
