### ISSUE TITLE
Wrong window title for Explore Interesting Areas

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#616]
![wrong window title](https://cloud.githubusercontent.com/assets/2158081/6128546/0cbaff06-b137-11e4-990f-42d7a7a23523.png)

I visit previously a user's profile : http://www.mapillary.com/profile/rudolfmayer/ors
And after the explore page: http://www.mapillary.com/map/explore

**Comment by knikel** [comment]
Fixed, thanks!.

**Comment by pyrog** [comment]
Thanks :smile: 
Could you please, also append the name of the country?

http://www.mapillary.com/map/explore/sweden
* `EN` Mapillary | Explore Sweden
* `FR` Mapillary | Explorez la Suède
