### ISSUE TITLE
Directional map pin is lost when editing compass angle on a single photo

### ISSUE THREAD

**Issue by glw** [mapillary/mapillary_issues#619]
The behavior im getting when editing is more specifically: after a bulk edit of compass angles, I individually inspect images and angles, if I find one out off in its angle I edit the compass angle for that individual image as usual. What I have found is when markers are close enough together that they overlap, and I then click a +/- button to change the angle the marker (pin) gets pushed behind the surrounding marks so that you can no longer see the directional (^) marker adjusting. Which drags out the editing process.

**Comment by knikel** [comment]
Will be fixed with the upcoming update of the editor.
