### ISSUE TITLE
install not possible with desire hd custom rom 4.0.4

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#622]
as #597 was closed:
I have 0.39 installed on my desire hd with custom 4.0.4 Rom.
Installing the prerelease https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk does not work:
clicking install, ok for permission, wait about 10 seconds, " application was not installed".
must i uninstall the old Version? I miss the message i remember from installing new osmand apk: this is an update, all setting will survive.

**Comment by peterneubauer** [comment]
What Rom?

**Comment by HolgerJeromin** [comment]
viperdhd from feb 2013 iirc

**Comment by peterneubauer** [comment]
Mmh, any chance to install the Android SDK, and check out `adb logcat` on your device while you are installing? There might be warnings/errors revealing the culprit.

http://developer.android.com/sdk/index.html

http://developer.android.com/tools/help/logcat.html

/peter

**Comment by HolgerJeromin** [comment]
I installed a Logcat app. this was the right idea.

Uninstalled mapillary and reinstall worked!

Close this issue if you like.

build.board: spade
build.bootloader: 0.85.2425
build.brand: htc_europe
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: ace
build.display: ViperDHD
build.fingerprint: htc_europe/villec2/villec2:4.0.4/IMM76D/116779.100:user/release-keys
build.hardware: spade
build.host: ABM018
build.id: ViperDHD
build.manufacturer: HTC
build.model: HTC Desire HD
build.product: htc_ace
build.radio: 12.56.60.25U_26.10.04.03_M
build.serial: HT0CGRX12139
build.tags: release-keys
build.time: 1348140783000
build.type: user
build.user: unknown
version.codename: REL
version.incremental: 110954.1
version.release: 4.0.4
version.sdk_int: 15

02-14 14:03:12.928 I/InstallAppProgress(16187): Finished installing app.mapillary.android
02-14 14:03:18.513 D/PackageManager(22843): Failed to generate PackageInfo, PackageSettings is null! pkg:app.mapillary.android, flag:8192
02-14 14:03:20.095 W/PackageManager(22843): Package app.mapillary.android desires unavailable shared library com.sonymobile.camera.addon.api; ignoring!
02-14 14:03:20.095 W/PackageManager(22843): Can't install because provider name com.mapillary.provider.pictureupload (in package app.mapillary.android) is already used by app.mapillary
02-14 14:03:20.095 W/PackageManager(22843): Package couldn't be installed in /data/app/app.mapillary.android-1.apk

**Comment by peterneubauer** [comment]
Ahh - you need to uninstall the existing app in order for the new one to install. I think it will not be required if they both are later from Google Play though.

**Comment by HolgerJeromin** [comment]
the old install was the apk from the homepage because of #179

**Comment by peterneubauer** [comment]
Ok,
if you uninstall the one you have, and take the new one from https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk, are things starting to work? Be aware that settings and data will be lost using this method, so you need to log in again.

**Comment by peterneubauer** [comment]
Is https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk working for you @HolgerJeromin ?

**Comment by HolgerJeromin** [comment]
Installation worked flawless. Installer said it will keep all settings. 
have to reenter password tomorrow with desktop Computer access (old version was not logged in either).

**Comment by peterneubauer** [comment]
Awesome, closing this. Thanks!

**Comment by HolgerJeromin** [comment]
FYI, app works. 
Tested settings and camera view. 
Not tested: real photos :-)
