### ISSUE TITLE
Manual web upload contaminated (1/1 image in the queue)

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#623]
I have a big issue with the manual web upload interface.
Each time as I open this menu I see that I have 1 of 1 image in the cue, it is always the same one that I have uploaded once with a script as test (Peewee's orange velomobile, located at http://www.mapillary.com/map/im/bbox/52.12365298437356/52.123985630152355/5.411497503519058/5.412852019071579). I cannot clean or delete this image by clearing the cache, I see it on different computers. Every time I click on this menu this image is uploaded somehow, even if I dont  press 'push to mapillary'. Clearing does not help. I just uploaded a new sequence and this picture is send again with them, even though it is >100km away. Result: a big straight line.
Can you guys clean up my manual upload queue?

**Comment by gyllen** [comment]
Will fix. thx for reporting.

**Comment by gyllen** [comment]
Hi,

I can not find any uploads for you anymore. Can you check if image is still there? Also can you hide the 100km away image ;)

Gonna work in a little update where you can see all different uploads on page.

**Comment by ligfietser** [comment]
It is my last upload, www.mapillary.com/map/im/2XbUsWBQrB4rjHt6O3Qzog
Hiding will not solve this bug, this ghost  photo is keep coming back as soon as I use the manual upload from the site!  Thanks for your help, really appreciated.

**Comment by gyllen** [comment]
Is it still there?

**Comment by ligfietser** [comment]
My manual uploads are empty now, thanks!

**Comment by gyllen** [comment]
Cool closing issue then. We will work more on manual upload in the near future.

**Comment by ligfietser** [comment]
My manual uploads with the python script failed again, so I pressed no. Now I see 17 images in the cache on the manual uploads of the website again, so this bug still isn't solved. Can you clear my manual uploads history again? I can't seem to remove this myself.

**Comment by jesolem** [comment]
In the reworked editor we should have a link to clear this history.

(@gyllen aborting the scripts with answering "no" at the end means there is a folder with photos but no DONE file)

**Comment by gyllen** [comment]
@ligfietser You should be able to remove these images yourself. Sorry for very late answer. Im closing this issue again, please reopen if you have further questions.
