### ISSUE TITLE
[Traffic sign feedback] Duplicated signs.

### ISSUE THREAD

**Issue by ireun** [mapillary/mapillary_issues#624]
Hello,

I think there should be a way, to tell the algorithm that one sign on one photo is that same sgin on another photo. That way, one the map there would not be a duplicates. Just one sign in a place of a photo, where this sign is the biggest one.

**Comment by gyllen** [comment]
Hi,

This will be the next step of Mapillary. Once we combine the traffic sign data we get now with this information http://blog.mapillary.com/update/2014/12/15/sfm-preview.html , we will be able to give an exact position of the sign. So hold out its coming up :)
