### ISSUE TITLE
Missing NL traffic_signs get blurred

### ISSUE THREAD

**Issue by PeeWeeOSM** [mapillary/mapillary_issues#625]
Peter Neubauer asked me to open an issue. I added a comment on this photo.
http://www.mapillary.com/map/im/R1qar-TZgvfsfq1aN6a83w

I think more traffic_signs from this source could be used for Mapillary. Not 100% sure though because I am no legal expert.

It would be much appreciated if the G12a and G13 would be added for detecion (and not blurred)

**Comment by mprins** [comment]
all dutch road signs are in the public domain as they are part of dutch law which has no copyright and is, by definition, in, of and by the public.

I've proposed some symbols in various PR's already.

**Comment by gyllen** [comment]
Awesome @mprins, Im gonna close ticket, please open tickets at https://github.com/mapillary/traffico for sign requests.
