### ISSUE TITLE
Manual Upload connects new sequence randomly to any other sequence

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#626]
Images uploaded via the manual upload get connected to older sequences. I couldn't figure out how it chooses the old sequence to connect to, it seems rather randomly.

Example: http://www.mapillary.com/map/im/kDDnHtw3zFQuHfXV2idhXw

**Comment by gyllen** [comment]
We will review this when we make next version of manual upload.

**Comment by gyllen** [comment]
With better explanation (which we have in the new manual upload) this issue should now be fixed
