### ISSUE TITLE
Reviewing images before upload is painfully slow

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#628]
Using HTC One M8 Android 5.0.1

When I review images, I can only open one at a time. I can not swipe left or right to move to the next images

In addition, everytime I return to the gallery to select the next image, I am returned to the very beginning of the gallery which results in a lot of wasted time scrolling up and down trying to find the next image to review

**Comment by pbb72** [comment]
I agree it's a problem that you're put back at the top whenever you return from image review.

But being able to browse images while reviewing depends on what application you have choosen to open the images with. The first time I reviewed an image from Mapillary, I choose to use the ES File Explorer image browser. This application allows me to swipe between images, and even delete the ones I don't like. So, I only return back to Mapillary after all the images have been reviewed.

**Comment by DaCor1** [comment]
I'll try that

**Comment by DaCor1** [comment]
No joy, images wont open in that app, just an ongoing loading gif

**Comment by pbb72** [comment]
Are you trying with ES File Explorer? Are you able to open and browse the images outside of Mapillary? They are stored in /storage/extSdCard/mapillary/ on my phone.

**Comment by peterneubauer** [comment]
Can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk and let me know about review? Upload all existing pics before, you need to uninstall the existing app before. Will come out next week on Play I hope :)

**Comment by DaCor1** [comment]
Ah, I'm in Lesotho for another week and have about 7k photos to upload but
no bandwidth so I will not be able to do a review unfortunately

**Comment by peterneubauer** [comment]
Ok,
no problem, keep it up!

/peter

**Comment by PeterMead** [comment]
I tried the prerelease apk and the review crashes, as does the upload.

**Comment by peterneubauer** [comment]
@PeterMead any chance you can send me the log form the main drawer?

**Comment by PeterMead** [comment]
@peterneubauer I tried the "Send debug logs" but the file was empty.

**Comment by peterneubauer** [comment]
Working now, releasing soon.
