### ISSUE TITLE
Show pending changes

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#631]
It's been a few times that I have been going through my own uploads, and see problems that I am pretty sure about I edited several days ago.

There are many possible reasons for this:
- I may be remembering wrong, maybe I didn't submit any changes at all.
- Or maybe I made the changes less than a day ago.
- There may be a delay in the processing of changes.
- Maybe someone else did a conflicting change, discarding my change requests.
- There could have been an error sending the change requests.
- Maybe my change requests were denied.

Without additional information, it is impossible to know what is going on, and then it's hard to decide what to do. Wait longer? Submit all changes again?

The editor should show what change requests have been submitted, immediately after making a change.

**Comment by pbb72** [comment]
As a temporary solution, you could send out an email for every received change request. Then we can use our mailbox for an overview of pending changes.

**Comment by gyllen** [comment]
Done!

**Comment by pbb72** [comment]
Sorry, I don't see anywhere that pending changes are shown. Where could I find this?

**Comment by pbb72** [comment]
Ah, I see now I got an email for a blur request. But I haven't gotten anything for any of the move or hide requests.

**Comment by pbb72** [comment]
Also, the email notification is not really the best solution, since it requires me to go through all of the email notifications to find out if I previously requested a change for a specific photo.

Plus, it will not tell me if someone else has already made a change request for a photo.

The best solution really is to show pending changes on the edit page of the photo itself.

**Comment by gyllen** [comment]
@pbb72 Thanks for the feedback. We are working on a dashboard where you would be able to get an overview of everything. In the meantime we will server you mails. The change set mails are on the way.
