### ISSUE TITLE
improve 'add new sign'

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#633]
When manually adding a new traffic sign;

- The default type (that's chosen when you just close the 'Select Traffic Signs' pop-up) should be other, not the jumping deer/first in the list.
- The red box can be smaller. Almost always it's to big.
- The size and place of the red box should be relative to the size of the frame it's rendered in, not to the image. in other words: when zoomed in the red box should be smaller. if you zoom a lot the red box can become bigger than the frame. When I zoom it's always to tag a small/distant sign anyway.
- ~~The title of the 'Select Traffic Signs' pop-up should be: 'Select Traffic Sign' (singular)~~ done

**Comment by gyllen** [comment]
Valid points. Will implement in new version.

**Comment by ireun** [comment]
Also, these buttons to add / save signs could be sticked to the frame. So you wouldn't have to zoom out, to add another.

**Comment by gyllen** [comment]
Yes. They will not follow zoom in next version.

**Comment by pyrog** [comment]
> The size and place of the red box should be relative to the size of the frame it's rendered in, not to the image

:+1:

**Comment by mbirth** [comment]
I just tried "The Game" for the first time. Despite that the mouse wheel doesn't work for zooming, a bigger annoyance to me was that the initial box (when adding a new sign) is HUGE and when zoomed in fills the whole screen.

The box should have the same size on the screen no matter how deep you are zoomed in.

Also with one photo I was zoomed in to the side where there was a traffic sign and clicking the "+" button didn't seem to do anything. After zooming out I found out that the new box was created outside my zoomed viewport. So maybe you can make new boxes always appear in the centre of the screen.

(From #568)

**Comment by knikel** [comment]
@de-vries, @mbirth, @ireun, @pyrog: We've addressed these concerns in the new viewer, adding traffic signs should be faster now. The game has to catch up though, so I'll leave this issue open.
