### ISSUE TITLE
Undo blurs that overlap traffic signs

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#635]
A lot of (mostly text containing) signs are blurred. I tagged a lot of them. I think that all blurs overlapping with traffic signs should be removed, or at least reviewed.

**Comment by ybkuang** [comment]
@de-vries Good idea! We will definitely take this into account in improving the detector pipeline.

**Comment by pyrog** [comment]
> A lot of signs are blurred

I founded also a lot of them.
:+1: with @de-vries suggestion

**Comment by ybkuang** [comment]
With the new [release](https://blog.mapillary.com/update/2018/04/19/accurate-privacy-blurring-at-scale.html), the blurring has been improved. I will close this now. If you find more issues, let's continue discussing in the forum.
