### ISSUE TITLE
Feature request: Edit functionality like "traffic sign game"

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#636]
Why not a edit functionality like in the traffic sign game with bigger photo's? 
Just a screen to edit al at once: traffic signs, blurring and maybe something like adjusting brightnes and contrast in the photo's. Now I've te switch between different functions.
Al in one place with surely bigger photo's would be a great comfort for some diehards (like me) ;).

**Comment by gyllen** [comment]
Like the idea, will think about what we can do.

**Comment by knikel** [comment]
@angelday, something to think about.
