### ISSUE TITLE
improve "Adjust the compass angles"

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#638]
As its alt-text says, the action linked to the "correct angles" button is: 
"Adjust the compass angles of all images in this sequence so that they are pointing in the direction of the next image in the sequence".

I think you can make this more accurate when you don't take the direction to the next image as the new compass angle, but the average of the direction to the next image and the direction from the previous image.

![selectie_040](https://cloud.githubusercontent.com/assets/1449609/6209349/4fc1905c-b5c5-11e4-80b1-60bec7136f08.png)
orange arrow: current behavior
purple arrow: proposed behavior

**Comment by gyllen** [comment]
Will be smarter in version 2 of editor

**Comment by knikel** [comment]
@angelday something to think about.

**Comment by angelday** [comment]
With the new editor, this is actually now possible to correct and get visual feedback. We even have plans to further improve the experience. @de-vries let me know if it doesn't address your question, in the mean time, I'm closing this.

**Comment by de-vries** [comment]
My issue wasn't with the GUI around this function, but with the way the new angles are calculated. 
It's not a huge issue, but in sharp turns it can make the calculated angle much more accurate.

**Comment by angelday** [comment]
pinging @gyllen regarding calculations

**Comment by gyllen** [comment]
@ybkuang Your the smart one ;), would this be better for us? It sounds like it to me.

**Comment by pbb72** [comment]
If you decide for this change, could you update interpolate_direction.py to do the same? :smile:

**Comment by gyllen** [comment]
Agree @ybkuang your in charge of that too ;)

**Comment by ybkuang** [comment]
Thanks for the suggestion @de-vries. Let's continue the discussions in the forum. 

mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
