### ISSUE TITLE
EU sign collection just broke

### ISSUE THREAD

**Issue by korst** [mapillary/mapillary_issues#640]
![selectie_041](https://cloud.githubusercontent.com/assets/1449609/6210167/3575a2e4-b5cd-11e4-89e3-2bd2fe04c39f.png)

happened in the last hour or so

**Comment by knikel** [comment]
@korst What browser do you use? Seems that transformations do not work in the browser you use.

**Comment by mprins** [comment]
I'm seeing this as well in google chrome version 40.0.2214.111 (64-bit)

**Comment by mprins** [comment]
turned out to be a caching issue in my case

**Comment by korst** [comment]
FF 35.0.1, Ubuntu14.04 (64bit)

CSS transformations were working before

**Comment by mprins** [comment]
@korst I generally open the dev tools (F12) go to network view and check the disable cache, then force reload and close the dev tools again.

or you can click-hold the reload button until a menu pops up and choose the reload you want

**Comment by knikel** [comment]
It was an issue with unnecessary characters in the style attribute. Deploying in a second. Will close the issue when deployed. Thanks!

**Comment by korst** [comment]
@mprins thanx, but didn't work either.

@knikel I'll stop lokking for clear chase options then. (didn't know there are so much!)

**Comment by knikel** [comment]
All good in FF too. Thanks!
