### ISSUE TITLE
Issues with sequence angle correct when angles go over 359 deg

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#641]
I am having problems with the sequence angle correct feature.

Take the following two images from the same sequence:
* http://www.mapillary.com/map/e/RcTjtznJDXvZd1FStJKg9g, facing 315deg
* http://www.mapillary.com/map/e/XJE_BGEHXrBS7IhdXjzQ0g, facing 330deg

All images were taken out of a left side window while driving, so they should point at 270 degrees relative to the driving direction. In the case of the example images, they should be pointing at around 90 degrees (driving south)

So I do a sequence correction to 270 degrees. The first image now gets 95deg, which is correct, but the second gets 449deg! Technically correct, this corresponds to 89deg, but the editor is now showing the image pointing straight north because the angle is bigger than 359deg.

Originally I had bigger problems, where almost all images were assigned an angle value of 359 after the sequence corretion, but I can not reproduce this bug anymore.

**Comment by knikel** [comment]
Closing in favour of #345. Will be fixed soon.

**Comment by knikel** [comment]
Will be fixed with the upcoming editor update.
