### ISSUE TITLE
There is no app for Ubuntu phone

### ISSUE THREAD

**Issue by elopio** [mapillary/mapillary_issues#642]
It would be great to have a mapillary app for the Ubuntu phone. The first phones are being sold now, and while it won't have as many users as android, probably many will be open street mappers and interested about open data.

The camera app [1] is already attaching gps and orientation exif information into the photos. It is gplv3, so you can either embed it or copy most of the things from there.

[1] http://bazaar.launchpad.net/~phablet-team/camera-app/trunk/files

**Comment by peterneubauer** [comment]
closing this, without a contributor stepping up we are not going to have the means to do this.
