### ISSUE TITLE
Roadsigns : favorise country distribution

### ISSUE THREAD

**Issue by Jibec** [mapillary/mapillary_issues#643]
Hello,

When correcting images with http://www.mapillary.com/map/games/traffic I notice I often correct images from Germany, that is the best mapped country in openstreetmap ... And with really good road sign density.

Can we favorise a little country with few mapillary/osm contributors ?

OSM stats : http://osmstats.neis-one.org/?item=countries

**Comment by gyllen** [comment]
Yes, you are right I like the idea. Adding to feedback for revamp of feedback tool.

**Comment by gyllen** [comment]
Applied better geographic distrubtion
