### ISSUE TITLE
App view distorted since yesterday

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#644]
Since yesterday the app (android 0.39), still takes 3:4 pictures, but stretches the camera view out over the whole screen so the view gets distorted a bit. The photo's turn out OK though.

Here is a screen shot:
![screenshot_2015-02-17-09-17-50](https://cloud.githubusercontent.com/assets/1449609/6225181/24daf302-b687-11e4-9dd4-6bf70287cd7f.png)

**Comment by peterneubauer** [comment]
Yeah, I think this is just an issue with the preview size. Sorry about that. There is a new app out, that still has this issue, it is scheduled for the release after the next.

**Comment by polarbearing** [comment]
While the live image still seems to be stretched in 1.13, it seems that the live view shows less of the frame than the actual shot. 

While I always adjust the camera to look over vehicle parts often I see the tip of the bonnet in the shots.

**Comment by peterneubauer** [comment]
Mmh, this one is next up on features. Annoying that there is no generic way to show the exact preview for all devices.

**Comment by polarbearing** [comment]
Why are we so interested in the 4:3 ratio anyway? If we are interested in traffic signs we should keep the widest format the device provides?

**Comment by jesolem** [comment]
4:3 is mainly because we want it to look good when combined with other images and in all viewers. Nothing more than that. 

For example: 
zoom out here to see dynamic stitch https://www.mapillary.com/map/im/o8-hgcxqYECoAbeS9n4agg
or the complete static stitch https://www.mapillary.com/map/im/76BLNBHyFLKij-kTTW12yw

**Comment by peterneubauer** [comment]
Fixed in the next release.
