### ISSUE TITLE
I want a better capture indicator [app]

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#646]
Lately I missed a lot of photo's cause the the app wasn't capturing (while I thought it was). IMO the visual indicators aren't good enough for three reasons:
- I optimize the direction of the phone for taking pictures, not watching the screen.
- Sunny whether is perfect for taking pics, but terrible for watching the screen.
- I also have to watch the road.

I know about the shutter sound option, but I want it to be notable, not annoying.

My suggestion is that you use the LED-light on the phone to indicate capturing. (*Doesn't every phone have one? Mine does. Its used for charging status and to show new messages.*)
Advantages are that the led is equally visible from all directions and also works when you implement the much requested "turn screen off during capturing" feature.

**Comment by mprins** [comment]
> Doesn't every phone have one?

No, not every phone has a status led en tablets in general don't have one at all

**Comment by polarbearing** [comment]
> I know about the shutter sound option, but I want it to be notable, not annoying.

+1
The built-in sound in my device is terrible and annoying. A custom sound, like a light knocking or a low-frequencey "thummm" would be good for audible feedback.

**Comment by peterneubauer** [comment]
possibly through http://stackoverflow.com/questions/2724871/how-to-bring-up-list-of-available-notification-sounds-on-android

**Comment by peterneubauer** [comment]
Now there is even an image counter in the status at the bottom of the screen to keep you informed, together with the shutter animation that should give you some indication?

**Comment by de-vries** [comment]
I haven't had a chance to try this in full sunlight yet, but it looks better. (the app looks overall much better since pre 1.0) 
I think the white flash will help. The counter looks good too, (depending on the [background] (https://github.com/mapillary/mapillary_issues/issues/681)) but may be even bigger IMO.

**Comment by peterneubauer** [comment]
Closing this for now.

**Comment by de-vries** [comment]
While still not perfect, it is much better now and any further suggestion to improve it will mostly just be a personal preference.
For example: I like I like the color you added to the start/pause button, but I don't see why you had to remove the start/pause icons. ;)
