### ISSUE TITLE
New sequence and stop capturing buttons are to close together [app]

### ISSUE THREAD

**Issue by korst** [mapillary/mapillary_issues#647]
Yesterday I missed out on a 200 photo sequence because when I wanted to start a new sequence I accidentally turned off capturing. (I didn't notice because issue https://github.com/mapillary/mapillary_issues/issues/646)

**Comment by korst** [comment]
In the new app (1.0) they're even closer together

**Comment by peterneubauer** [comment]
I have added some padding in the next version, let me know if it is enough, and submit a screenshot with the desired padding so I can adjust :)
