### ISSUE TITLE
wrong angle correction by sequence_basic_bot

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#648]
Hi !

I noticed that the sequence_basic bot cuts some sequence (it's ok) but change the angle of some images to a wrong direction.
For example :
http://www.mapillary.com/map/cs/1J1I7jfoCdnaGENMnAP12w

The correct angle is about 50°

**Comment by ybkuang** [comment]
@Stefal do you remembered if you have applied bulk edit of the image angles for that sequence? That will help us pinpoint the bug. Thanks

**Comment by Stefal** [comment]
Wow, it was a long time ago.
If I'm right, I didn't apply a bulk edit as it was some pictures I took manually with my smartphone in hand to remember me some hamlet's names.
But it's possible that I did a manual angle modification : 
http://www.mapillary.com/map/cs/V5rXeZuK5Za4Oe1uFnYjXA

**Comment by ybkuang** [comment]
@Stefal The sequence bot does not correct the angles anymore. Please report back if the issue remains.
