### ISSUE TITLE
Loopy sequences

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#650]
I have several sequences where the displayed path of the sequence on the map makes a loop back to earlier in the sequence. Sometimes it is near the beginning of the sequence but not always. If I download the GPX, there is no loop and if I'm following the image sequence in the browser, there is no "next picture" button when I get to the end so it seems like this is only a problem on the map display.

Links to pictures where the looping is a problem:
http://www.mapillary.com/map/im/ADhFFnXc2_bHpeP7iD7e7Q
http://www.mapillary.com/map/im/fs6GEh4pvW0TnpaGFlqcwQ
http://www.mapillary.com/map/im/3vQFMwIo6sRq-xKzVeLjeA (this one is in the middle of a sequence)

**Comment by jesolem** [comment]
I just saw this too on a sequence. Assigning to @knikel

**Comment by ToeBee** [comment]
Just had another one:
http://www.mapillary.com/map/im/VVK9ZDc56wQ5CWAlmInxqA

**Comment by gyllen** [comment]
I think this is a manual upload issue. @ToeBee Are you using manual upload?

**Comment by ToeBee** [comment]
Yes I am using the manual upload. These are pictures I captured with my GoPro and geotagged with the gpx2exif tools.

**Comment by ToeBee** [comment]
Looks like the second one in the first post and the additional one I posted have been fixed but the others are still loopy.

**Comment by gyllen** [comment]
@ToeBee Yes I manually fixed some. Just wanted to confirm this is in manual upload only.

**Comment by dymo** [comment]
Looks like my problem in #581 maybe it is not date related?

**Comment by ToeBee** [comment]
And two more today:
http://www.mapillary.com/map/im/MmTG0A4h1p__NWixwtlHiQ
http://www.mapillary.com/map/im/EMMdeGYs0kKjZRkFni7Ngw

**Comment by ToeBee** [comment]
Another today:
http://www.mapillary.com/map/im/h-uNkOGyG74wV7bJJDbQYQ

**Comment by ToeBee** [comment]
Most of the ones I have mentioned above are fixed. Are they being fixed because I mentioned them here or is there something automatic that is fixing these? The sequences I uploaded last night seem to have spawned three loops:
http://www.mapillary.com/map/im/wi3canUYBel6FXSyHH-YvQ
http://www.mapillary.com/map/im/7Q1vLNCelsYDzZ2Xf-lHYQ
http://www.mapillary.com/map/im/Tgjk8DejWVS0HR9SSPIrFQ

**Comment by gyllen** [comment]
We have an automatic job that is called the unlooper. While we are trying to figure out whats casuing this. Its some kind of race in our importing script (for manual upload).

**Comment by ToeBee** [comment]
Ah ok. I'll just wait for the unlooper to catch my uploads then. Although... this unlooper does not seem to have caught the last sequence I mentioned in my first post on this issue. You can see the loopiness here:
http://www.mapillary.com/map/im/bbox/39.30919876019212/39.42359679353423/-97.1685791015625/-96.90439224243164

**Comment by gyllen** [comment]
Seems unlooped now?

**Comment by ToeBee** [comment]
I think at low zoom levels there is some weirdness happening with the tile rendering of the blue line that makes it look ok but I'm still seeing a link between these two images when zoomed in.
http://www.mapillary.com/map/im/74B6nWsgjuMlV-7Gqpdbeg (last image of the sequence) http://www.mapillary.com/map/im/3vQFMwIo6sRq-xKzVeLjeA (somewhere in the middle)

**Comment by gyllen** [comment]
Most loops should be fixed by now
