### ISSUE TITLE
Show hidden photos in edit mode

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#652]
The edit window should show hidden images, so that it is possible to un-hide them again.

**Comment by gyllen** [comment]
It "should" do that.

**Comment by pbb72** [comment]
Hmm, I was going to get a link to an example, but now it shows all image icons in the original (non-corrected) location, even though the connecting line shows the corrected locations...
https://www.mapillary.com/map/e/XgnMUJJ6wtuL3L2lBIf_RQ: ![old-pins](https://cloud.githubusercontent.com/assets/1436366/6256462/afd24bc2-b7b8-11e4-843a-9060c223c59e.png)

**Comment by pbb72** [comment]
Here is the example I was looking for!
![clipboard image2](https://cloud.githubusercontent.com/assets/1436366/6313669/dc65326a-b9b8-11e4-9364-4262cc7eedcf.jpg)

After https://www.mapillary.com/map/e/PAedSJRBquuNNm4LRr0DwA there comes a lot of bad photos I hid, and not they are completely unavailable in edit mode.

**Comment by gyllen** [comment]
We are abandoning the hidden concept and will move to delete instead. Reason nobody has ever asked to unhide an image and this is more space saving.

**Comment by pbb72** [comment]
Seems to me the reason that nobody ever asked to unhide an image, is that it has been impossible to do exactly that.

Not being able to hide and unhide pictures will make people less inclined to remove (their own or other peoples) bad photos, and thus lower the overall quality. If space is an issue, I would recommend keeping deleted photos for a limited time, so that someone else can protest the deletion.

This of course requires a system where people can actually see what photos have been removed!

**Comment by gyllen** [comment]
@pbb72 Yes removal will go through same changeset systems as edit today. And the author of the image will probably be asked before removal

**Comment by HolgerJeromin** [comment]
Only hiding images had always had a smell in my view. 
"OK, you don't want that image on the map. Good, but we only hide it, for us it is still usable for what ever we want." So +1 for deletion.
