### ISSUE TITLE
The app (Android v1.0) crashes when clicking "Profile"

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#654]
First of all, you did a great job with the redesign. But I encountered the following bug:

On first startup it didn't show my username although I was logged in in the previous version and my feed was empty. It crashed as soon as I clicked on "Profile".

Starting with the second startup, my username is shown and the feed is populated. But the profile section is still broken.

**Comment by Peatsmoke** [comment]
I had the same behaviour in Android 4.4.2 and seded the crashreports.

**Comment by peterneubauer** [comment]
I just pushed an update to Play store, v 1.0/versionCode 103. Does that upgrade and for you?

**Comment by floscher** [comment]
The problem already disappeared without updating. After rebooting the phone it was gone.

**Comment by peterneubauer** [comment]
Yay!
