### ISSUE TITLE
Show photo and map side by side on the changeset screen

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#655]
On the changeset screen, the photo is currently shown underneath the map, flushed to the left. It ought to be like on all other screens, where the photo is shown side by side with the map.
![clipboard image](https://cloud.githubusercontent.com/assets/1436366/6263085/66dedc24-b811-11e4-8203-08470290fbc0.jpg)

**Comment by knikel** [comment]
This should be fixed by now. Thanks for reporting!
