### ISSUE TITLE
Android app upgrade should not remove home screen icon

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#656]
This morning, Mapillary seemed disappeared from my phone. Where it's icon used to be, was now an empty spot. Going into the apps drawer, I didn't initially find the application either. 

It turned out the icon had changed drastically (for the better, though) making it hard to find again. However, the upgrade should not have removed the home screen icon. Apps are upgraded often, but we should not have to drag them back to the home screen every time.

**Comment by peterneubauer** [comment]
Should not happen anymore now. Not sure why it did that.
