### ISSUE TITLE
Android menu items too small for outdoor, in traffic use

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#658]
The new menu in the Android app looks very nice. However, for use outside it is horrible.

The labels are too small to read outside and to touch while moving, and the gray icons are simply invisible.

For usage outside, in traffic, you need big high-contrast icons such as the previous version of the Android app had.

**Comment by knikel** [comment]
@pbb72 all valid points. We're addressing this in the coming release with as slightly bigger icons (will be matched with native camera app on Nexus/L) and larger text size, the drawer will be also black for higher contrast. Bear in mind that labels are also clickable.

![larger-drawer-styles](https://cloud.githubusercontent.com/assets/1574656/6326649/2d284632-bb54-11e4-8a54-a0e4908f0c0e.png)

What worries me though, are the gray icons you're seeing, they should either be green (single-shot mode) or blue (auto-shot mode), as we're not using anything other than applying colour to a shape. Ideas @peterneubauer?

**Comment by peterneubauer** [comment]
This is part of v1.15 coming out soon.

**Comment by pbb72** [comment]
I wasn't talking about the items in the camera menu, but in the main menu. They are tiny, thin, gray icons on a white background.
![2015-02-25 15 47 43](https://cloud.githubusercontent.com/assets/1436366/6374000/58ff53a2-bd0e-11e4-9837-aa20364c56e5.png)
