### ISSUE TITLE
Android app too little contrast in some screen captions

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#659]
The captions for the review and settings screen use black text on a dark gray background. Even indoors and at maximum brightness, this is close to impossible to read.

**Comment by peterneubauer** [comment]
What colors are you suggesting?

**Comment by pbb72** [comment]
The captions on the other screens (Feed, Projects, Profile) are good. These are white or light gray on dark gray. It's only the Review and Settings screens that use black on dark gray.

**Comment by pbb72** [comment]
The "Back" arrows on the Review and Settings screens are still black on dark gray, and thus almost invisible.

**Comment by pbb72** [comment]
Confirmed! :+1:
