### ISSUE TITLE
"Poor Location Accuracy" on iPhone 3GS iOS6

### ISSUE THREAD

**Issue by fjanon** [mapillary/mapillary_issues#66]
I can't use Mapillary on my iPhone 3GS iOS 6.1.6 (the latest iOS version for the 3GS), it always says "Poor Location Accuracy" although the Maps application runs just fine with the GPS.

**Comment by gyllen** [comment]
@fjanon Sorry for getting back to this late. But has this issue been resolved in Mapillary iOs app 2.0

**Comment by gyllen** [comment]
Please reopen if not
