### ISSUE TITLE
Android app gives insufficient feedback when pressing the Upload button

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#662]
I have the app set to manual uploading, because I want to be able to review the photos before that.

In the old app, there was a clear feedback when starting the upload. You opened a menu where you could start the upload, and the menu closed as soon as the upload was started.

In the new app, there is a onscreen button (actually, it's not clear if this is a button or just an icon), that gives no feedback at all when pressed. You have to notice the icon in the Android notification area to see uploads have started.

**Comment by peterneubauer** [comment]
Hej @knikel could we make a button with pressed state there maybe? I will add a toast to pop up and tell about the status bar.

**Comment by knikel** [comment]
@peterneubauer check `ic_upload` and `ic_upload_active`. Would that work?
