### ISSUE TITLE
Android app menu button often invisible in camera screen

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#663]
The camera screen has a tiny grey menu button. This is completely invisible when something dark is on camera in that part of the screen, but even with some white background there the button is difficult to notice.

Also, the button is too small to use while moving.

**Comment by peterneubauer** [comment]
You can just swipe in the menu from the left side, no need to hit the button.

**Comment by peterneubauer** [comment]
Have enlarged and padded the camera buttons, should be better now. We will see over the icons though.
