### ISSUE TITLE
Android app camera mode icon should be clickable

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#665]
The mode icon in the camera screen (which show the current mode: Walking manual, Walking auto shot, Riding, Panorama) should be clickable to change the mode.

In combination with the almost invisible menu button, it took me a long time to figure out how to change the mode.

(Also: Riding you do on a horse or a bicycle. In a car you drive. Maybe you could call it riding if you were sitting on top of the car roof?)

**Comment by floscher** [comment]
> In combination with the almost invisible menu button, it took me a long time to figure out how to change the mode.

Me too! Maybe you could show the menu on the first time a user opens the camera. Even showing it every time I open the camera would not annoy me (but probably others).

**Comment by floscher** [comment]
In addition, the menu should go away when I switched the mode (e.g. like in the default Android camera app).

**Comment by pbb72** [comment]
Actually, there really is no need for the menu. The menu only has entries for changing the mode, usage of compass, and a shortcut to settings. A mode and compass icon are already available on the camera screen. Make these clickable, add a settings button, and the whole menu can be removed.
