### ISSUE TITLE
Android app confuses between manual and auto shot

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#666]
Is this a bug or am I simply not understanding?

When the camera is in "Walking, manual" mode, I am offered a big green button and a "End" button.

When the camera is in "Walking, auto shot" mode, I am only offered a big blue button.

I have been trying to get autoshot to work, but after an hours walk, I was very confused not understanding it's operation, and it has only recorded 27 photos. While I now notice that the manual mode End button tells me it ends a sequence.

Could it be that what is called the manual mode is actually the autoshot mode? Also, the identical icons don't make the situation any better.

**Comment by pbb72** [comment]
OK, I can now confirm that the two are not mixed up, but it is still very confusing that the manual mode has a "stop sequence" button, while the autoshot mode doesn't have that.

**Comment by peterneubauer** [comment]
Yeah, we will see over the icons. Thanks!
