### ISSUE TITLE
Failure to load next picture in sign tagging

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#670]
Probably about 10-20% of the time when I click save or validate in the road sign tagging game I never get another image. It just sits there with the spinning "loading" circle of dots. According to my browser's dev tools, there is no pending HTTP request so it doesn't seem to be network problem. Maybe the server is responding with an unexpected message that the javascript can't handle? I don't see any errors in the console either.

I am using Chromium 39.

**Comment by pyrog** [comment]
> I don't see any errors in the console either.

:+1:

**Comment by gyllen** [comment]
@peterneubauer Please close when graphserver has caught up

**Comment by gyllen** [comment]
This should now be fixed. Please reopen if you find errors.

**Comment by de-vries** [comment]
still getting spinners... but less though.

**Comment by pyrog** [comment]
> still getting spinners

:+1:  but also found issue #696

**Comment by ToeBee** [comment]
Yeah, I'm still getting this too.

**Comment by peterneubauer** [comment]
Will take a look on Monday.

**Comment by ToeBee** [comment]
Tonight I have run into a similar but slightly different problem: After I click the save or approve button, sometimes *nothing* happens. No spinner, no next picture. It registers the click and changes the tagging controls but then nothing else happens.

**Comment by pyrog** [comment]
Today, spinner on picture with:
* Message: *"This image hasn’t finished processing yet! It will look better soon, promise."* 
* Console log:
```
XMLHttpRequest cannot load https://a.mapillary.com/v2/search/im/or/random?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&package=trafficsign_eu_1.0. Origin http://www.mapillary.com is not allowed by Access-Control-Allow-Origin.
```

**Comment by pyrog** [comment]
Another one without any message or error log

**Comment by peterneubauer** [comment]
That one @gyllen should take a look at.
