### ISSUE TITLE
Traffic sign feedback game. Got the same image twice.

### ISSUE THREAD

**Issue by PeterMead** [mapillary/mapillary_issues#673]
The image I got was http://www.mapillary.com/map/im/LUhbxAgqXeRfGJH3XPYirg for which I was the previous editor.

That would mean I'd be approving my own change if it wasn't for the fact that the approve button was missing.

**Comment by pyrog** [comment]
:+1:

**Comment by gyllen** [comment]
Yeah you can not approve your own images. However the algorithm should not give you images you edited.

**Comment by ToeBee** [comment]
I also just got an image I previously tagged as evidenced by me being listed as the previous editor of the picture. The picture ID is WQCbhneJtlo2akYX9kv7sw.
![mapillary_same_picture](https://cloud.githubusercontent.com/assets/348948/6433996/a0862a42-c043-11e4-9de1-4db301229527.png)

**Comment by gyllen** [comment]
This should now be fixed

**Comment by de-vries** [comment]
Just got another one. I've cleared my chase after you closed this issue.

**Comment by ToeBee** [comment]
I just got my own image again as well. Image ID: CDIz3dyA28C1pI23_nXLRw

**Comment by ToeBee** [comment]
And again with image F8uWdGJUE9SlXRUyRIEwPQ

**Comment by ToeBee** [comment]
I just came across an image where the same user has two consecutive versions of sign tagging. Not sure how this happened since for me when I get the same one twice the save/verify controls are hidden. Image:
http://www.mapillary.com/map/im/E62kEzeHmQ1z73VtKWBU8A

**Comment by floscher** [comment]
Maybe the user corrected something in the second edit (added more signs, removed a wrong tagged sign). AFAIK you could even just add a sign, remove it again and then click save.

**Comment by smsm1** [comment]
As mentioned in #840 I'm still getting this issue, even in a browser that I've not used the game in before. I'm using Safari 8.0.4  on a Mac.

**Comment by pyrog** [comment]
@gyllen Could you reopen this issue ?
I got it on http://www.mapillary.com/map/im/jYol9v-3dP9DMFH6Ld3VkA
