### ISSUE TITLE
Getting "toebee blurred some of your photos" email on my own blur requests

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#676]
I'm getting this email after some (but not all) blur changes. It is clearly intended to be sent to users when someone else edits one of their pictures. I just had a batch of 63 blur change requests accepted an hour ago at which time I got the "We’re just letting you know that the 63 blur edits you requested were approved." email. Those blur requests were for random pictures from several different users. I'm not sure if this email is talking about one of the images in that batch or if it is a separate thing. 

![2015-02-19 22 47 56](https://cloud.githubusercontent.com/assets/348948/6277775/3ecf281a-b857-11e4-9e55-635362aa67d8.png)

**Comment by gyllen** [comment]
Thanks for reporting this.

@peterneubauer Seems like aggregation in for user on mine blur is not correct

**Comment by ToeBee** [comment]
Haven't you completely rewritten the notification system since this issue was opened? Either way, it's not happening now so I'll go ahead and close this issue.
