### ISSUE TITLE
wrong country in activity list

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#677]
just saw this:
![selectie_045](https://cloud.githubusercontent.com/assets/1449609/6278878/042a1f46-b89b-11e4-941e-db8aa454f5c5.png)

All photo's I made today in the Netherlands, not Belgium. [This is one of the photo's.](http://www.mapillary.com/map/im/srlr1dWR8YSUw4FxUHH-DQ?z=10)

I only ever made photo's in the Netherlands, so if you can find any that are tagged different, they're wrong.

**Comment by gyllen** [comment]
We must be using to simple shapefiles. Are these images in anyway close to the border?

**Comment by korst** [comment]
> Are these images in anyway close to the border?
about 5km

**Comment by gyllen** [comment]
@korst Yes thats it then. We are currently looking at this.

**Comment by mprins** [comment]
this will always be kind of problematic, you know there are areas like Baarle Hertog / Baarle Nassau... 
http://www.mapillary.com/map/im/bbox/51.374673661013496/51.4738989064778/4.729442596435547/5.059032440185547

**Comment by de-vries** [comment]
@mprins You have a strange way of motivating people ;)

@gyllen Additional info: according to the statistics pages of [the Netherlands] (http://www.mapillary.com/map/places/netherlands) and [Belgium] (http://www.mapillary.com/map/places/belgium) all my photo's are made in the Netherlands. Also the street names associated with these photo's are the correct (dutch) street names.

**Comment by mprins** [comment]
:blush:

**Comment by gyllen** [comment]
@de-vries Yes we are using two different borders. We are on the verge for a merge :) for those two.

@mprins I challenge you to get some pictures in there ;)

**Comment by mprins** [comment]
@gyllen It's a bit out of my way, but if I get in the area I'll do a :camera: drive-by

**Comment by gyllen** [comment]
Adding the borders tag to this issue. We are working in a solution to this see #508

**Comment by gyllen** [comment]
Hows this looking now?

**Comment by de-vries** [comment]
This specific issue isn't reproducible in the new mapillary. There are however still some issues with borders though. See for example [this guys](https://www.mapillary.com/app/stats/85633111?user=eosfoto) stats, he has 526830 uploaded photos, but in [the Netherlands](https://www.mapillary.com/app/stats/85633337) he has 409746 photos and in [Germany](https://www.mapillary.com/app/stats/85633111) he has 360339 photos, combined that's way more than 526830.

**Comment by gyllen** [comment]
I think that is unfortunately an overlapping border issue, Im not sure we can do so much about it unless we get better shapes.

**Comment by peterneubauer** [comment]
We reimported the country shapes with higher accuracy. Is this issue better now?

**Comment by peterneubauer** [comment]
closing this, as the new importedd shapes should fix the issue.
