### ISSUE TITLE
 samsung galaxy note upload montage of photos as one

### ISSUE THREAD

**Issue by rbracket** [mapillary/mapillary_issues#678]
Friends, 

well,  this upload is strange.  

the new interface mostly impresses...but this should not happen.

http://mapillary.com/map/im/95_LX7gJX2XNC2l4IvrEww
!
[screenshot_2015-02-19-17-57-51](https://cloud.githubusercontent.com/assets/688646/6280331/2e1bcc86-b860-11e4-8fcf-aca6ec8008b0.png)

**Comment by gyllen** [comment]
Wow amazing art :), but not so good for upload

**Comment by peterneubauer** [comment]
Wow. Have never seen anything like that. Can you please send or attach the log?

**Comment by rbracket** [comment]
Hi,

I sent a log, about the time I posted the new issue.

I will attempt another upload today.

best,
Katie

**Comment by rbracket** [comment]
well... here is the log... next time I'll make sure to get the log into the
github issue from step 1...

**Comment by peterneubauer** [comment]
Yeah, did this happen again?

**Comment by rbracket** [comment]
I  updated Mapillary late Friday.   On Monday, at the latest, I'll check
again.  The second set of log files were from a 'buggy'  version of
Mapillary.  so, yes it happened again...but not to worry.

**Comment by peterneubauer** [comment]
Closing this for now. Reopen if it occurs again.

**Comment by rbracket** [comment]
It continues,   as of Monday and Saturday.   Yesterday I deleted bad photos before uploading.  I also wondered if my method, comcast.net ISP, and leaving the network on during fieldwork.   

l have also send logs. ..I will do a short sequence today

**Comment by rbracket** [comment]
this photo is from a walk this AM.  I disabled wifi before opening
mapillary.

Exif of 2015_02_24_10_15_17_334.jpg

File
dirname
/storage/emulated/0/Android/data/app.mapillary/files/mapillary/b8d40986-ea86-46f7-9623-e368e1c834ad___Mapillary
filename 2015_02_24_10_15_17_334.jpg
filesize 1,450 kb
timestamp Tue Feb 24 10:15:18 PST 2015

Exif (Android OS Exif Interface)
DateTime
ExposureTime
Flash null (off)
FNumber
FocalLength
GPSAltitude
GPSAltitudeRef
GPSDateStamp
GPSLatitude
GPSLatitudeRef
GPSLongitude
GPSLongitudeRef
GPSProcessingMethod
GPSTimeStamp
ImageLength 1200
ImageWidth 1600
ISOSpeedRatings
Make
Model
Orientation 0 (UNDEFINED)
WhiteBalance null (auto)

Exif IFD0
Date/Time 2015:02:24 10:15:18
Image Description
{"MAPDeviceMake":"SAMSUNG","MAPCameraMode":1,"MAPCaptureTime":"2015_02_24_10_15_17_334","MAPSettingsEmail":"
ksurey@gmail.com
","MAPLocalTimeZone":"-0800","MAPVersionString":"1.15","MAPCompassHeading":{"MAPCompassDirectionMode":0,"TrueHeading":163.43764209747314,"MagneticHeading":147.8138427734375},"MAPDeviceModel":"GT-N5110","MAPCameraRotation":"0","MAPPhotoUUID":"0dbfe157-ce85-437e-b8e8-b41df130466a","MAPLatitude":"45.474736408344434","MAPLightSensor":"6229.8","MAPGPSAccuracyMeters":"6.0","MAPSequenceUUID":"b8d40986-ea86-46f7-9623-e368e1c834ad","MAPAltitude":"84.10162846429573","MAPSequenceCaptureUsed":"1","MAPSettingsUploadHash":"3495009549d9a762c3e9f4bc4f9aeb5d3dd8dce7dfca8e7c0f6bb2e341704bc4","MAPSettingsProject":"","MAPAccelerometerVector":{"z":0.044058360159397125,"y":0.216875359416008,"x":9.621748924255371},"MAPLongitude":"-122.72193136654789"}
Make SAMSUNG
Model GT-N5110
Orientation Top, left side (Horizontal / normal)
Resolution Unit Inch
Software N5110UEU2CNE2
Unknown tag (0x0100) 1600
Unknown tag (0x0101) 1200
X Resolution 72 dots per inch
Y Resolution 72 dots per inch
YCbCr Positioning Center of pixel array

Exif SubIFD
Color Space sRGB
Date/Time Digitized 2015:02:24 10:15:18
Date/Time Original 2015:02:24 10:15:18
Exif Image Height 1200 pixels
Exif Image Width 1600 pixels
Exif Version 2.20
Exposure Mode Auto exposure
Exposure Program Aperture priority
Exposure Time 1/2237 sec
F-Number F2.7
Flash Flash did not fire, auto
FlashPix Version 1.00
Focal Length 3.43 mm
ISO Speed Ratings 50
Max Aperture Value F2.7
Metering Mode Center weighted average
Scene Capture Type Standard
Unique Image ID
Unknown tag (0x0112) 1
User Comment User comments
White Balance Mode Auto white balance

Exif Thumbnail
Resolution Unit Inch
Thumbnail Compression JPEG (old-style)
Thumbnail Image Height 312 pixels
Thumbnail Image Width 416 pixels
Thumbnail Length 27854 bytes
Thumbnail Offset 8 bytes
X Resolution 72 dots per inch
Y Resolution 72 dots per inch

GPS
GPS Img Direction 147.81 degrees
GPS Latitude 45.0° 28.0' 29.051070038913167"
GPS Latitude Ref N
GPS Longitude -122.0° 43.0' 18.95291956688652"
GPS Longitude Ref W

Jpeg
Component 1 Y component: Quantization table 0, Sampling factors 1 horiz/2
vert
Component 2 Cb component: Quantization table 1, Sampling factors 1 horiz/1
vert
Component 3 Cr component: Quantization table 1, Sampling factors 1 horiz/1
vert
Compression Type Baseline
Data Precision 8 bits
Image Height 1200 pixels
Image Width 1600 pixels
Number of Components 3

**Comment by peterneubauer** [comment]
So,

According to the logs, there is something seriously wrong with Samsung devices:

```
02-20 10:26:27.426 W/dalvikvm( 3992): No implementation found for native Ldalvik/system/VMRuntime;.pauseGc:(Ljava/lang/String;)I
02-20 10:26:27.431 E/ActivityThread( 3992): Pause GC
02-20 10:26:27.431 E/ActivityThread( 3992): java.lang.reflect.InvocationTargetException
02-20 10:26:27.431 E/ActivityThread( 3992): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread.pauseGC(ActivityThread.java:5410)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2277)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread.access$900(ActivityThread.java:169)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.os.Looper.loop(Looper.java:146)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at android.app.ActivityThread.main(ActivityThread.java:5487)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
02-20 10:26:27.431 E/ActivityThread( 3992): 	at dalvik.system.NativeStart.main(Native Method)
02-20 10:26:27.431 E/ActivityThread( 3992): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: dalvik.system.VMRuntime.pauseGc:(Ljava/lang/String;)I
02-20 10:26:27.431 E/ActivityThread( 3992): 	at dalvik.system.VMRuntime.pauseGc(Native Method)
02-20 10:26:27.431 E/ActivityThread( 3992): 	... 15 more
```

also, this seems to be a known bug, see http://developer.samsung.com/forum/board/thread/view.do?boardName=SDK&messageId=266242

So, I suggest upgrading to the latest Android version from Samsung which _might_ fix the issue, and I did some sync adaptions in the later Mapillary versions (1.13+) that _might_ solve this issue. Not much else to do it seems :(

**Comment by rbracket** [comment]
Okedoke.

Both Mapillary and the Samsung device report having the latest versions as
of today for Mapillary and as of Feb 20 for the Android version.  I did
remove and reinstall Mapillary since my last upload.

However,  I will wait until I have time to learn a bit more about this
Samsung device.  I have it set to automatically update.   seems to be at
androd 4.4.2 with a kernel from  May 2014.

thanks,
Katie

**Comment by peterneubauer** [comment]
Really sorry for that, but it seems that there is a problem with the
Garbage Collector interface on that device, causing any hard-working app to
crash - not only Mapillary when in Camera mode.
