### ISSUE TITLE
App crashes at photo upload on Android (Samsung Galaxy Pocket)

### ISSUE THREAD

**Issue by nicolasrpmaia** [mapillary/mapillary_issues#679]
I'm having dificulties on Android 2.3.6, Samsung Galaxy Pocket. The app crashes while trying to automatically upload the photos. Trying to manually upload the photos also crashes the app.

These problems began with the introduction of the 1.0 app release (feb 2015).

**Comment by peterneubauer** [comment]
@nicolasrpmaia can you please upgrade to 1.07? Also, Android 2.3.6 is not supported, did you install it from the direct link? That one is updated to point to 1.07 too now, https://dl.dropboxusercontent.com/u/5925006/mapillary/mapillary_android-release.apk

**Comment by nicolasrpmaia** [comment]
Hi @peterneubauer, thanks for promptly replying! Upon closer inspection, I discovered I actually had and still have Android version 4.0.4, sorry about that.

Installing the app from the link you gave also did nothing to solve the issue. The only difference now is that when the app crashes, it doesn't offer me the option to report it to Mapillary.

**Comment by nicolasrpmaia** [comment]
Update: the app unexpectedly started uploading photos to the Mapillary website again, apparently out of nowhere.

**Comment by peterneubauer** [comment]
So, if you update to the latest Play release (v 1.14) and have that issue again, can you attach the log here or send it by mail from the main drawer menu?

**Comment by peterneubauer** [comment]
Any luck @nicolasrpmaia ?

**Comment by nicolasrpmaia** [comment]
If I have the issue again in the future with future releases I'll be sure to attach the log here.

Thanks for the support!
