### ISSUE TITLE
Better feedback on deleting pictures

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#680]
I have a sequence of 10 photos, and I go in to review them. I see one of the photos is not OK, so I press the delete icon. The photo stays on screen, but the counter in the header says the total is now 9 photos. I go back to the thumbnails view, and I still see 10 thumbnails, even though the header says 9 photos. The photo that I wanted to delete, can still be opened, but I cannot open the last photo in the sequence anymore. I go back to the review screen, and then into the thumbnail screen again, and now the thumbnails are updated, showing only 9 thumbnails and the one I wanted to delete is gone.

This problem has caused me to delete several photos unintentionally, because it seems like tapping the delete icon doesn't do anything.

With larger amounts of photos this problem can also cause the application to crash. I had a longer sequence (enough to make the thumbnail view scrollable), and I deleted 3 or more photos (enough to make the number of lines of thumbnails less). Going back into the thumbnail view, I scrolled to the bottom, which was now at different positions depending on if you look at the number of photos left or the not updated number of thumbnails. Coming at the bottom, the application immediately crashed.

**Comment by pbb72** [comment]
I still had problems today removing some photos, especially from longer sequences. Pressing the delete button while a photo is open does nothing visually (same photo still on screen), I have to go back into the thumbnail screen to see the photo is actually deleted.

This may cause me to accidentally delete several photos, because there is no feedback that the delete button has been pressed. So I may think my press was not registered, and press delete again.

**Comment by pbb72** [comment]
It's not only a lack of feedback. Part of the problem is also that the image is not always immediately deleted when you press the trash icon. I've seen cases where it seems to take up to a minute before the image is gone.

**Comment by pbb72** [comment]
Actually it's not a matter of time before the image is gone, but I have to browse back at least 2 images, and then when I go forward again the image is gone. So it seems there is some kind of cache where the deleted image is not removed.

**Comment by nighto** [comment]
Seems to be related with #1130. Still happening on the current version of Android app.

**Comment by peterneubauer** [comment]
This should not be relevant anymore, closing for now.
