### ISSUE TITLE
Android app should not use single-color icons on top of photos/camera

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#681]
All icons that are used on top of photos or the camera live view, should have either a contrasting icon background, or a halo, or a shadow.

This is because the image underneath the icon can be the same color as the icon, making the icon invisible. This is worst with dark grey icons because dark areas are very common in images, but it also happens with white icons when there is an overexposed area.

**Comment by knikel** [comment]
This will be addressed in the next release through thin outlines for the large camera buttons. Small (status) icons are placed in squares for now.

**Comment by pbb72** [comment]
Personally I don't really like the gradient background, would be better with a solid (half-transparent) gray background.

But the main problematic icon, the menu icon, still doesn't have a background to make it stand out on dark areas.
