### ISSUE TITLE
Android app bug? Two times new sequence autostart stops camera recording

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#682]
It's not completely clear to me if this is a bug, and how it is triggered, but I will try to describe my problem.

Initially, I had changed the "New sequence min distance" setting to 0. My intention was to disable this feature (since anything "automatic" is often the cause of problems) but I later realized that setting it to 0 *should* mean every single image is automatically a new sequence. However, what really happened is that the app always only took a single photo whenever I started recording. Even though there was no indication on the screen that no more photos were being taken. I had to pause and start a new sequence for 1 new photo to be taken.

Later, I increased the distance to 50 meters. While walking in an area with bad GPS reception, I saw a message that a new sequence was started, probably because there hadn't been sufficient GPS reception for 50 meters, this is OK. But only one single photo was taken in the new sequence, and after that I got another message that a new sequence was started. After this second message, no more photos were being taken at all until I manually started a new sequence.

**Comment by peterneubauer** [comment]
This is a bug. Fixed in the next release, new sequence will be started automatically and continued.
