### ISSUE TITLE
Move the shutter button a bit towards the centre

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#685]
When manually aiming the camera, I find that having a clear view of the border of the image is more important than having an unobstructed wiev of the central part. I would therefore suggest to move the big shutter button a little bit towards the centre, to leave enough space to discern the subject on the right side.

**Comment by jesolem** [comment]
+1

It is on the side that has window mount for me so easy inspection of the image edge is important. A few pixels should be enough.

**Comment by peterneubauer** [comment]
Done, out in the next release.
