### ISSUE TITLE
Android app upload doesn't start

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#686]
I've got 260 photos in my queue from todays walk, but nothing happens when I press the upload button. No upload is starting.

I have also restarted my phone, but still nothing is getting uploaded. This has been functioning yesterday.

My phone is a Samsung Galaxy S3 with Android 4.3

**Comment by polarbearing** [comment]
Which version do you use? I had the same problem with 1.06, and it worked again in 1.07

**Comment by peterneubauer** [comment]
Yeah, if it doesn't work with 1.07, please send a debug log.

**Comment by pbb72** [comment]
The logs are in the mail! :)

**Comment by pbb72** [comment]
It should be version 1.07 I'm using.

**Comment by nicolasrpmaia** [comment]
This sounds identical to the bug reported by me in #679. They should be merged if possible.

**Comment by peterneubauer** [comment]
So, does this work? (v109, see settings) https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk

**Comment by nicolasrpmaia** [comment]
Unfortunately installing v109 didn't solve the issue for me.

**Comment by pbb72** [comment]
For me, 1.09 solved the problem, my photos are uploading now :-)

**Comment by peterneubauer** [comment]
Yay! Thank for the help!
