### ISSUE TITLE
Android: display tilt angle and make tilt range configurable.

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#688]
I'd like to be able to read the tilt angle overlayed in camera mode (I like, for example,  the way Opencamera does it, turning the reading to green colour when within the -1° +1° range).

In walking autoshoot mode, I'd also like to make the "pause while tilting" option much more selective: could you make the allowed angle range configurable? And also apply the same tolerance range around the vertical, so that it doesn't prevent shooting in portrait mode.

**Comment by peterneubauer** [comment]
Yay, more settings! The preventing to shoot portrait mode is intentional though, as portrait images cause all kinds of problems in matching, viewing and bluring, we are not fond of doing special cases everywhere for them right now.

**Comment by peterneubauer** [comment]
Good suggestions, will try to get it in!

**Comment by peterneubauer** [comment]
How do you like this one? https://dl.dropboxusercontent.com/u/5925006/mapillary/android_prerelease/app-release.apk

**Comment by kaitu** [comment]
Thanks for fast action! The new setting looks good, just what I wanted. I can't field test it right now. I suspect that for use under bright sunlight I'll like a more prominent feedback when the phone is correctly aligned, and that in an environment lacking any horizontal or vertical reference I'll like to be clearly told in which direction it's tilted. I'll get back after some field testing.

**Comment by kaitu** [comment]
After a little outdoor testing I reckon the "tilted" red icon is visible enough. 
I experimented a bit with the max til values in static operation (walking).
Setting the max tilt to 0 degrees, in manual mode it's very hard to keep the phone level enough for all the time needed to press the shutter, conversely in auto mode and with a little persistance is possible to trigger a very levelled shot.
Setting the max tilt to 1 degrees, it's easy enough to keep the phone steadily within tilt range, but it's not always obvious which way the phone should be turned if you like to further improve levelness.

It would be awesome if the following different five states could be read on the display:

- tilt out of range, you must rotate clockwise
- tilt within range (you can take a picture), but rotate clockwise to improve levelness
- level is as good as you can get holding the phone by hand (less than 1°) or within automatic straightining range (I think Yubin said this is planned for the near future?): take picture now!
- tilt within range (you can take a picture), but rotate anticlockwise to improve levelness
- tilt out of range, you must rotate anticlockwise

**Comment by kaitu** [comment]
Forget my last request, I just found that all I asked is already available in developer settings.

**Comment by polarbearing** [comment]
In the new trace log (thanks for that) I found dozens of 'tilting' / 'not tilting' per second. Not sure if that was before or after the decision to take the shot (they were taken regularly) but I have seen the red icon a lot on the screen while driving. 

Where does the tilt information come from, from the acceleration sensors?

Could the 'tilting' / 'not tilting' in the log be specified numerically for better evaluation?

**Comment by peterneubauer** [comment]
Added tilt angle to the debug.

**Comment by polarbearing** [comment]
Here is an example, what I observe in the dev-info is that the tilt oscillates between 0 and 1 degree.

Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting
Thu Feb 26 08:46:15 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting

**Comment by peterneubauer** [comment]
check out https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk for tilt output

**Comment by polarbearing** [comment]
Did you fix something else? In the quick home shaking, the tilt evaluation is now around the 20 deg threshold:

Fri Feb 27 10:29:13 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting 34
Fri Feb 27 10:29:13 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting 15
Fri Feb 27 10:29:13 CET 2015 : app.mapillary.android.activity.CameraActivity  - tilting 27
Fri Feb 27 10:29:13 CET 2015 : app.mapillary.android.activity.CameraActivity  - not tilting 17

Will see how it behaves while driving later.

**Comment by peterneubauer** [comment]
Yeah,
That's the default, you can change it on settings.
