### ISSUE TITLE
Panorama breaks sign tagging

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#690]
While doing some sign tagging in the US I keep getting served up this panorama shot in Los Angeles but it has no sign tagging controls in it so I can't do anything with it except for skip. The image ID is uYGMwKS6Hql4HnBEJcpuyg

![image](https://cloud.githubusercontent.com/assets/348948/6309383/98755a4a-b912-11e4-9764-70e78b893e19.png)

Also, there is a headless man in this image. So that's amusing.

**Comment by gyllen** [comment]
Skipped showing panoramas since tagging not possible there at the moment.

Failed to find head for man, still closing issue though ;) @ToeBee
