### ISSUE TITLE
Panorama on map

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#691]
New panorama pictures are no longer placed on the map in one nice "dot". They are now spread out in  a messy sequence.

Example: http://www.mapillary.com/map/im/1DMf9D4Z9q7lyTGP5ldk6g

I am using the iOS app.

**Comment by jesolem** [comment]
@Andblue We have considered placing sequences taken in panorama mode to get their position assigned to e.g. the average lat,lon but we have not done that yet. We show the raw positions reported in EXIF. 

I think what happened this time is that you had poor GPS accuracy (yellow marker) on this particular sequence. Or?

(beautiful pano btw)

**Comment by Andblue** [comment]
@jesolem Aha, I thought that they used to be grouped, but now I actually found one of my old ones that isn't. But most of them are a "dot" and the ones I did recently aren't. Looks like I drew conclusions based on to few data points, I do tend to do that.

I mostly get the yellow marker. I don't know why I keep buying iPhones, nice UI, but every single iPhone has hade terrible network, wifi and GPS.

**Comment by jesolem** [comment]
Ok, I'm going to close this one. Grouping pano shots to the same location is on our list.
