### ISSUE TITLE
No action icon in sign tagging

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#696]
![no action icon](https://cloud.githubusercontent.com/assets/2158081/6313649/167117ae-b9b8-11e4-9c87-4c5ca67eeed9.png)

https://d1cuyjsrcm0gby.cloudfront.net/E1bDQtpz8JG4Mrm-hObQ1w/thumb-1024.jpg

**Comment by gyllen** [comment]
@peterneubauer GS needs faster response

**Comment by pyrog** [comment]
Another one:
![no action icon - 2](https://cloud.githubusercontent.com/assets/2158081/6316029/890d2caa-ba15-11e4-8f4d-da0f366c47b1.png)

In the HTML source code, there is a loop with a lot of thumb-views of the picture and the console display the following message:
```log
[Error] Failed to load resource: La connexion réseau a été perdue.
```

**Comment by gyllen** [comment]
Is this still an issue @pyrog ?

**Comment by pyrog** [comment]
@gyllen The issue seem to be solved :smile: 
No issue (*spinner* or *missing action icon*) on 60 pictures

**Comment by gyllen** [comment]
Awesome! Nice work by the way :)

**Comment by pyrog** [comment]
Sorry, this issue is still there: on a 360° image

https://d1cuyjsrcm0gby.cloudfront.net/GhOda1QnYDi0XOI4PUPk-Q/thumb-2048.jpg
![no action icon again](https://cloud.githubusercontent.com/assets/2158081/6416963/7d1e4926-beaa-11e4-95fb-204db6659bb6.png)

**Comment by de-vries** [comment]
@pyrog thit alsso metioned here: https://github.com/mapillary/mapillary_issues/issues/690

**Comment by pyrog** [comment]
**Note:** this [previous image](http://www.mapillary.com/map/im/GhOda1QnYDi0XOI4PUPk-Q) appear a lot. Could you "remove" panorama images of the game?
