### ISSUE TITLE
phone rotating bug in app

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#698]
When reviewing a single image, the app kind of fails when I rotate my phone. I get a "mapillary has stopped" message and then I'm back at the sequence or review page.

**Comment by peterneubauer** [comment]
Mmh,
can't recreate it. Can you check with the new 1.13 and send me the logs if that happens?

**Comment by de-vries** [comment]
nope, it's gone in 1.13.

**Comment by peterneubauer** [comment]
Great! Closing.
