### ISSUE TITLE
Updated user manual available?

### ISSUE THREAD

**Issue by JanVanBekkum** [mapillary/mapillary_issues#699]
I don't understand the uploading process in Android version 1.08.
Questions:
* What do the different statuses in Feed mean? You had ... images ready, you added ... images to sequence.... I expect 3 main statuses: not released for upload, released for upload and uploaded. How can I see in what status each sequence is?
* I recorded 4 sequences this morning. One was uploaded by Mapillary, I don't see anything happening with the other sequences

**Comment by gyllen** [comment]
Yeah we do need to look over these confusing messages.

**Comment by sandrauddback** [comment]
@JanVanBekkum Just wanted to follow up on this as we're just about to start a project where we will review our feed items. We'll use your feedback when working on this project. Thanks!
