### ISSUE TITLE
App crashes when tap Profile on menu

### ISSUE THREAD

**Issue by marloncabrera** [mapillary/mapillary_issues#701]
Mapillary Version name: 1.08 Version code: 108

Cellular is Nexus 4 android version 5.0.1

**Comment by peterneubauer** [comment]
Is this still happening with the new version 1.13 on Play?

**Comment by peterneubauer** [comment]
should be fixed in v1.13.

**Comment by marloncabrera** [comment]
Ok, it is working on version 1.13.

Thank you.
