### ISSUE TITLE
Android: App frequently crashes

### ISSUE THREAD

**Issue by kaktinjanka** [mapillary/mapillary_issues#702]
App frequently crashes even then I am not using it. 
HTC Desire S (saga), Android 4.0.4
Additionally debug log file created is empty.

**Comment by kaktinjanka** [comment]
Looks like it is image upload module/app part, because app crashes every time when I push image upload button.

**Comment by polarbearing** [comment]
@kaktinjanka could you provide the developers with a version number you are using, current one is 1.13 from play store. Log file is created retrospectively when you touch "Send debug log" as mapillary.log on your sd card.

**Comment by kaktinjanka** [comment]
Yesterday updated app to version 1.13, but problem remains. 
Then I touch "Send debug log" app creates  mapillary.log file on SD card but file is empty.

**Comment by peterneubauer** [comment]
@kaktinjanka can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk again? I think the bug might be fixed.

**Comment by kaktinjanka** [comment]
Hello! Tried app from dropbox link and looks like my issue is gone.Later updated from Play store, will report result tomorrow.

**Comment by peterneubauer** [comment]
Nice! Closing for now.
