### ISSUE TITLE
camera-mode notification popups don't go away

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#704]
In version 1.13 of the Android app, the popup notifications that appear while in camera mode never go away unless certain events happen. For example, when I stop driving (e.g., at a stop sign or traffic light), I expect the "too slow" message. However, it never goes away when I resume forward motion, even when I'm cruising along at 45mph.

Other messages also do not go away. The "new sequence started" message also stays on-screen, unless I stop the sequence or it is replaced by another message (such as the "too slow" one).  I've also had ”processing " stay on screen for several minutes.

Picture taking continues to occur; I can see the camera window freeze a frame behind the message.

It is probably important to know that the messages appear to begin fading, only to be redrawn immediately. I'm going to guess a flag isn't being cleared?

Samsung Galaxy S4, stock Android 4.2.2, rooted.

Very very distracting, especially when driving.

**Comment by jfburke3** [comment]
Should probably specify that this is in driving mode, not walking mode.

**Comment by peterneubauer** [comment]
Yup, looks like a bug in the way animations are drawn when they can't finish because of the next one coming. Will look into it, thanks!

**Comment by polarbearing** [comment]
Had these issues massively in the version on Feb 18, and to a much lesser extent yesterday with 1.09. Will continue testing with 1.13.

**Comment by bacza** [comment]
I confirm that too, with v1.08.
I noticed "Phone is tilting" message not going away until some other message appears.
Furthermore, I saw red "phone shaking" icon at the bottom also not going away.

**Comment by peterneubauer** [comment]
Can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk and report back, maybe send a log? I'm doing 
````
anim_fade_in_out.setAnimationListener(new Animation.AnimationListener() {
                    @Override
                    public void onAnimationStart(Animation animation) {
                        camera_status_splash.setVisibility(View.VISIBLE);
                    }

                    @Override
                    public void onAnimationEnd(Animation animation) {
                        camera_status_splash.setVisibility(View.GONE);
                    }

                    @Override
                    public void onAnimationRepeat(Animation animation) {

                    }
                });
````

And can't recreate the error over here.

**Comment by peterneubauer** [comment]
I think I have something that works, see http://stackoverflow.com/questions/5474923/onanimationend-is-not-getting-called-onanimationstart-works-fine/13881013#13881013

please try the above link and report back.

**Comment by bacza** [comment]
Hi, the second update of v1.14 solved the problem for me. (seems like you removed that nice fade-out effect completely?)

**Comment by peterneubauer** [comment]
Nice! I will put it back now together with the fix. Thanks for testing!

**Comment by peterneubauer** [comment]
Check the link again, fade-out animation should be there again, and bug gone. Will be in the next release.

**Comment by jfburke3** [comment]
Yep, that did it for me, too (without the nice fadeout).  I'll wait for the fix to be pushed to Goofball Play, thoug, since I can live without the fadeout.

**Comment by polarbearing** [comment]
Did not happen anymore in today's version (though I only took few sequences due to bad weather).

**Comment by peterneubauer** [comment]
Nice!

**Comment by polarbearing** [comment]
>> bad weather

> Nice!

No, not nice. Raindrops on window. Wipers in the shot. Long exposure - motion blur. Do you have a fix for that? ;-) (Still got the features I wanted to map)

**Comment by bacza** [comment]
Well.. the bug is still there but now it's different :)
The effect of pop ups not going away is fixed now but there are cases when some of the pop ups disappear too quickly :)
I mean, when the car is stopped, "Too slow" message is displayed and nicely faded out after a while - that's correct. Next "Too slow" message displays and fades out correctly too. But then some other subsequent message appears and disappears INSTANTLY. And another one too. Then some next fades out ok. But another one doesn't. and so on..
That happens unpredictably - some messages fade out nicely and some other don't - they disappear immediately. Some of them disappear so quickly that they are hard to notice.
I guess that has something to do with the workaround you linked - the solution with the postDelayed()?
If yes, it seems like those postDelayed() Runnable()s somehow interfere each other disturbing subsequent messages.. (?)
But that's only the blind guess..

**Comment by peterneubauer** [comment]
Yeah,
In order to do it totally tight one would need a messaging queue, but that
IMHO is too much interfering with the Android internals. Maybe we can try
to push less messages instead...
