### ISSUE TITLE
Sequence size is limited to 30 photos in new android App

### ISSUE THREAD

**Issue by alexandrz** [mapillary/mapillary_issues#705]
I captured several long sequences (taking low resolution photos), but only 30 photos per sequence were visible in review activity and uploaded to mapillary.

Example:

http://www.mapillary.com/map/im/W-OvlDFqE0gvlxlkXke7Jw
http://www.mapillary.com/map/im/rQKfybSKd6Jg3kje_0UEZQ

Mapillary 1.0
Nexus 5
Android 5.0.1

**Comment by peterneubauer** [comment]
Fixed on v1.13,please update from Play
