### ISSUE TITLE
Do not record images when no sdcard is mounted / android

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#706]
When no sdcard is mounted (e.g. USB connected to PC), the app records images to /data/data/app.mapillary/files/mapillary, according to the info in the Developer settings. 

Those files are only visible for review in the same situation, once the sdcard is back the files in the regular folder are shown. 

It would be better if the app refuses to take pictures instead of squeezing them into the application storage. 

(For some reason the Astro file manager does not even show me the content of /data but that might be a permission problem, the device is not rooted)

(test pictures captured in 1.09, location shown in 1.13)

**Comment by peterneubauer** [comment]
Well, for a lot of models without external memory this is the only position. Also, you can increase the threshold to stop taking pictures when your card is not mounted , having that effect.

**Comment by HolgerJeromin** [comment]
But mapillary should look (and upload/delete) for images in 
/data/data/app.mapillary/files/mapillary
even if it is using another path right now.
