### ISSUE TITLE
Please provide repository with numbered version of apk files

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#707]
While things have improved with version numbers shown in the settings, it is still a hassle to guess if the latest version is on play store or behind the dropbox link on the website or the prerelease link.

Could you provide a repository:
- where apk files have version numbers in the file name
- where older files are visible for regression testing
- which gets a new version uploaded automatically during the build process

A version that is stable enough could then be pushed to play store manually.

**Comment by peterneubauer** [comment]
The pattern is https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_114.apk, current:

https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk

**Comment by knikel** [comment]
@polarbearing You can find few recent builds here: https://www.dropbox.com/sh/8rgd29wgn87hiam/AAB0AARtwlL8U3cMRpVeRXuja?dl=0

The same link will land in the footer in the next deploy, the current version will be kept in sync with Play Store, right @peterneubauer?

**Comment by peterneubauer** [comment]
Yes,
it will actually be the latest development builds, so it even might be
fresher than Play store :)

**Comment by knikel** [comment]
Cool, closing then.

**Comment by polarbearing** [comment]
Thanks that helps a lot. Just a little confusion - I installed the 'app-release_current.apk' saying it was uploaded 12 h ago while 'app-release_114.apk' was 22 h ago, still the current tells me 1.14 in app info. However they differ in file size an md5 hash. Thus current is not just a symlink to 114 ?

**Comment by peterneubauer** [comment]
It's not a symlink. I will put is in a proper place once I release it.
Essentially, the current is _bleeding_edge_build_ :)

**Comment by HolgerJeromin** [comment]
It would be nice it these links (and all other interesting ones) will not be remembered by the nerds who reads all issues, but to explain them in the README.md of this repository.
