### ISSUE TITLE
sequence out of order

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#709]
Go to http://mapillary.com/map/im/ntWwB2JIxA0scL60BhPlpA and step forward through the next two images. Note how the location jumps around.

Not sure if this is a website problem or how the 1.13 Android app is coding the metadata.

So far this is the only time I've seen this, but will update if I see it again.

**Comment by dymo** [comment]
I have the same problem here: http://www.mapillary.com/map/im/ga5I6PqB0oHR3f-OU9WGzw
but it was manually uploaded from my GoPro, so i don't think it is related to the Android app.

**Comment by kaktinjanka** [comment]
I also had this problem on track (http://mapillary.com/map/im/wLi5iHvMS3k1TP7JMcSmJg), but now it seems ok. It is not related to the new  Android app because I have took and uploaded images with "old" app.

**Comment by de-vries** [comment]
I also had this problem on track: http://www.mapillary.com/map/im/Nx7P8UyeOTzu2KctN4VtSA

But for unknown reasons it solved itself

**Comment by jfburke3** [comment]
So my track has also fixed itself.  Makes me wonder if there is still some backend processing going on, even though the picture(s) aren't tagged with the 'still being processed' message, or maybe some database indexing has fallen behind and the problem goes away when it catches up?  If that's the case, then I guess it isn't really an issue.

**Comment by gyllen** [comment]
Yes this has been fixed on the backend side now. Thanks for reporting this.

**Comment by peterneubauer** [comment]
http://www.mapillary.com/map/im/ntWwB2JIxA0scL60BhPlpA is still to investigate.

**Comment by peterneubauer** [comment]
This should not be an issue anymore with the new viewer. Closing.
