### ISSUE TITLE
black warning screens - android app

### ISSUE THREAD

**Issue by glw** [mapillary/mapillary_issues#711]
Great job on the new app, I'm really enjoying it. 

Is it possible to make the black boxes that pop up when in camera mode, transparent?

**Comment by peterneubauer** [comment]
The flashes are designed to be visible even while driving etc, which is why they are a bit bigger than normal. Making them transparent or just the normal Android Toast size would make them unusable for people on bikes or in cars. WDYT?

**Comment by glw** [comment]
I see what you mean. It is certainly useful to have large text for those uses. As for transparency (the point may be moot now that issue #712 is fixed), my personal opinion would be that a slight transparency (e.g. 0.8) would not take too much away from a positive user experience. And allows you to multi-task by; seeing the notification and, at the same time (quickly - so that eyes are on the road/path) check to make sure your camera is still correctly positioned.

**Comment by glw** [comment]
I used the app after the update this morning. the Notification boxes are not an issue.  Thanks!
