### ISSUE TITLE
"Too slow." black box remains after motion resumes

### ISSUE THREAD

**Issue by glw** [mapillary/mapillary_issues#712]
As the title suggests, on occasion (which occasions I have not nailed down yet), the black warning box, "Too slow." Will remain present on screen after motion has resumed. This is for a nexus 5, android: lollipop.

**Comment by jfburke3** [comment]
Happened to me too.  Peter has already made a test build that fixes this problem.  Read here:

https://github.com/mapillary/mapillary_issues/issues/704

**Comment by peterneubauer** [comment]
You guys are really on top of things!! Closing this and releasing in 1h.

**Comment by glw** [comment]
Thanks guys!
