### ISSUE TITLE
You requested * leads to frontpage [app]

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#713]
"You requested n blurs" and "You requested n change sets" in the feed in the app leads to the frontpage. In the case of the change sets it helps to strip the part after change set ID from the url.

**Comment by gyllen** [comment]
I assume this is in the Android app?

**Comment by de-vries** [comment]
Yes android, and still present in 1.28

**Comment by gyllen** [comment]
@peterneubauer We need to correct these links whenever possible

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
