### ISSUE TITLE
Sequence folders should be timestamps and not UUIDs

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#714]
Sequences are currently sorted into folders with cryptic UUID numbers as filename. They don't sort chronologically. 

For people who want to review their folders on the big screen of the PC, or keeping a personal copy of the full resolution, it would be good if the folder name were a timestamp, such as the image names, e.g. 2015_02_23_12_55_15_514.

They are better human readable, thus easier to find, and sort chronologically. 

They are still unique on the device. Global uniqueness is preserved since the sequence UUID is in the EXIF data.

**Comment by gyllen** [comment]
Is this on android?

**Comment by polarbearing** [comment]
Yes android.

**Comment by jesolem** [comment]
Adding for iOS too

**Comment by pbb72** [comment]
Don't the folders themselves have a timestamp already?

**Comment by polarbearing** [comment]
They have, on Android, since the other Peter kindly fixed the cryptic UUID ;-)

**Comment by jesolem** [comment]
Fixed for iOS too. Will go out with next approved version.
