### ISSUE TITLE
Web navigation not intuitive

### ISSUE THREAD

**Issue by mishari** [mapillary/mapillary_issues#715]
Supposing I want to go to Bangkok. (While logged in) I go to mapillary.com I see a map, so I look for a search bar, I don't see any. There should probably be an easier way to get to where I want without having to scroll a map across the world, which currently seems to be my only option.

**Comment by gyllen** [comment]
Hi, there is a search bar in the right hand corner on the front page. There is also a search bar in the left corner when you are viewing an image as this one http://www.mapillary.com/map/im/mj5RWtg6x-dAoWVN4dVzLw . It reads Destination... and have a green search button next to it.

This is interesting though. It means that we need to place these search bars better. Where were you looking for the search bar?

**Comment by mishari** [comment]
Oh, I wonder why it wasn't showing up, perhaps it was a temporary glitch or some assets were not loading. Thanks!

**Comment by mishari** [comment]
The issue occured again, I have attached a screenshot.
![mapillary___crowdsourced_street_photos_and_brouter_web_client](https://cloud.githubusercontent.com/assets/503018/6734055/812d2fa8-ce88-11e4-9097-1625877e823b.png)

**Comment by ybkuang** [comment]
Hi, can you try opening your browsers terminal and run localStorage.clear()?

**Comment by mishari** [comment]
I get an "undefined"

On 19/3/15 22:43, Yubin Kuang wrote:
> Hi, can you try opening your browsers terminal and run localStorage.clear()?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/715#issuecomment-83639224>.
> 

-- 
Best regards
Mishari Muqbil
Twitter: @mishari Skype: misharim Phone: +66 81 8240629
EE32 64BD 7D1F 5946

**Comment by ybkuang** [comment]
Did you manage to get back the normal page after that?

**Comment by knikel** [comment]
@mishari if you refresh the browser it should log you out. It seems that you entered a blank project.

**Comment by mishari** [comment]
Hit reload, it's working now, thank you.

On 19/3/15 22:47, Yubin Kuang wrote:
> Did you manage to get back the normal page after that?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/715#issuecomment-83640238>.
> 

-- 
Best regards
Mishari Muqbil
Twitter: @mishari Skype: misharim Phone: +66 81 8240629
EE32 64BD 7D1F 5946
