### ISSUE TITLE
Need help with upload outside of app

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#718]
I spent several hours yesterday trying to uploading about 10.5k images from the trip to Lesotho, but in the end I gave up. Every time I got help and figured out a step in the process (I am not super technical) and ran the script again, I got a new error. I am currently trying to figure out an SSL error which I've gotten several pointers on but none work.

I tried uploading using the web uploader but it wont recognise the exif data even though the exif data is present and correct on each image (checked with geosetter)

I am honestly totally frustrated with the whole process. As far as I can see, the upload script and the documentation surrounding it are very much aimed at people who understand python and scripting languages i.e. not the majority of people. 

- Is there some better documentation that I am missing somewhere that can take me through this process at an idiots level?
- Is there an alternative way to get these images uploaded other than the scripts or web uploader?
- Should I just burn these to DVD discs and post them to you?

I don't recall exactly what it was, but I remember something years ago from a separate project where I could download and install a program that would manage image uploads in a controlled manner. Is there anything like that planned for Mapillary?

**Comment by ybkuang** [comment]
Hi @DaCor1, sorry about that. Can you send a sample image to yubin@mapillary.com so we can take a look? Also, did you edit the exif with some other tools before you try manual upload? Thanks!

**Comment by DaCor1** [comment]
Hi Yubin,

I've emailed one of the images from my phone to you.

Dave

**Comment by ybkuang** [comment]
Hi Dave, Thanks. We will take a look!

**Comment by peterneubauer** [comment]
Done, your images are up, and they are AWESOME!
