### ISSUE TITLE
Login flow 

### ISSUE THREAD

**Issue by mmatteocato** [mapillary/mapillary_issues#720]
Hi!
I've a problem: i'm registered with a wrong email (.co instead .com). I can take a picture with mapillary and do the login but I can't modify the email. Please help me and fix the login flow with a link to confirm the email.
thanks

**Comment by gyllen** [comment]
Will fix. We are going to add possibility to email soon. Can you in the meantime just mail me at gyllen@mapillary.com with wanted email and I will fix it for you. Sorry for the trouble.
