### ISSUE TITLE
Single capture mode while riding

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#723]
There used to be in earlier versions the option to manually trigger taking a single picture while in the waling auto mode (it seems this is not there anymore in the latest version?)

I thought that this would actually be very useful for riding as well - often you might stop at a crossing, and especially clear pictures of intersections would provide excellent value for mapping. Thus, to be able to trigger a shot while you are e.g. waiting for the lights to turn green would be very useful.

**Comment by de-vries** [comment]
In walking auto mode you can, if activated via settings, take a shot with the volume keys.

When I go out I'll try this in riding mode, cause now it says "to slow"

**Comment by kaitu** [comment]
It would make more sense to ignore the "Pause on stop" setting for pictures taken in manual mode.
Considering that the phone mount might interfere with accessibility of the volume keys, a button for single pictures would still be handy.

**Comment by peterneubauer** [comment]
Closing this for now, I think switching to waling-single shot mode for these pictures is legit for now, otherwise things become very fuzzy as of when to take pictures and when not. Thanks for the thinking though, feel free to come with further suggestions!

**Comment by rudolfmayer** [comment]
I don't think that switching to walking mode is a viable alternative, as that implies

- pressing many more buttons (stop the sequence, switch mode, take the shot, and switch back to driving mode). You won't always have that much time at a red light / stop sign / etc...

- breaks the sequence and leaves you with three sequences instead - the one before, the single still shot, and the one afterwards, when it should really be one sequence.

I don't think there is anything fuzzy in my original proposal - I don't want any automation, just an option to manually trigger a shot, when the app otherwise normally tells me to "start moving faster to take pictures", because I am currently stopped...

**Comment by peterneubauer** [comment]
mmh, we could put a preference into place that puts let's you manually
trigger a shot if possible tapping anywhere on the surface?

**Comment by rudolfmayer** [comment]
Could work for me (though it might not be the most intuitive :-))

**Comment by rudolfmayer** [comment]
One semi-automatic solution for this would be: once we noticed that we stopped, take one more picture; this would ensure that we have at least one picture at the place we actually stopped at, whether it is the "clear view" to the intersection we wanted is a different story, but it is better than nothing.. still, manually capturing would be preferable.
