### ISSUE TITLE
Some signs are difficult to distinguished in Select Traffic Signs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#726]
* Same icon for `type-prohibitory_no_traffic_both_ways` and `type-prohibitory_vehicle_weight_limit`
* `type-prohibitory_vehicle_height_limit` have the **Nt** text

The **Nt** text should added to the `type-prohibitory_vehicle_weight_limit` sign? :wink:

![traffic signs](https://cloud.githubusercontent.com/assets/2158081/6358858/f077ae5a-bc6e-11e4-83ae-03cc4d9b6594.png)

**Comment by knikel** [comment]
![placeholders-units](https://cloud.githubusercontent.com/assets/1574656/6409658/18430bba-be67-11e4-99f9-9aa2cc91ff23.png)

@pyrog This has been fixed for the EU batch of signs - Nt, Nm (number of tonnes, number of meters). Thanks for catching this! I will think however of a better solution to handle these signs, as Nt and Nm are still quite cryptic.
