### ISSUE TITLE
Allow click-drag to draw the red box [traffic signs game]

### ISSUE THREAD

**Issue by waldyrious** [mapillary/mapillary_issues#727]
...rather than having the box placed arbitrarily and then having to invariably move & resize it. By click-dragging, we can improve the experience of adding new signs down to a single action rather than 3 or more.

And in the mean time, please place the resize button at the bottom right, which provides a more natural sizing UX (see for instance the resize handle in the comment box below).

**Comment by knikel** [comment]
@waldyrious Thanks for the feedback, we've implemented that flow in the new viewer!

**Comment by waldyrious** [comment]
Woohoo! :smile:
