### ISSUE TITLE
Allow zooming out all the way [traffic signs game]

### ISSUE THREAD

**Issue by waldyrious** [mapillary/mapillary_issues#729]
...rather than clicking many times in the minus sign icon

**Comment by de-vries** [comment]
or zoom by mouse wheel...

**Comment by waldyrious** [comment]
That too, yes, but it might not be enough since we can zoom to less than the original size. Perhaps the zoom level could "snap" around the default to make it easier to hit the correct size. But even if that was implemented, I still think a dedicated button would make sense.

**Comment by floscher** [comment]
…and show the current zoom factor to make it easier to tell, if the view is zoomed in.

**Comment by gyllen** [comment]
Added

**Comment by waldyrious** [comment]
yay :) :+1:
