### ISSUE TITLE
Sequence cut (in web interface) not doing anything?

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#732]
I've several times tried to cut a sequence, following image http://www.mapillary.com/map/e/PAedSJRBquuNNm4LRr0DwA.

The settings are a bit unclear, I don't want to cut it at every gap > x meters, I just want to cut it *there*.

Anyway, I've tried many times, with x set to 0, 1, 50 or 300 meters, and every time my request is accepted, but nothing happens.

Maybe I am not understanding the cut feature?

This might be a duplicate of #398 and/or #501, I don't know because there's no description in those issues.

**Comment by ybkuang** [comment]
It will take a while for us to approve the changeset (usually within 24 hours). Sorry for the confusion.

**Comment by pbb72** [comment]
I've send several requests, more that one week ago. I've never seen any result. So either I am not understanding how it should function, or it is not functioning at all.

**Comment by pbb72** [comment]
Could you please re-open this issue? The requested sequence cuts are still not gone through. Either the feature is not working at all, or it's not working as expected.

**Comment by pbb72** [comment]
I can also add that, after requesting a sequence cut, I never receive an email notification that a change set has been requested. So it seems to me that this feature simply doesn't work.

**Comment by pbb72** [comment]
Any change of reopening this bug, or indicating that it is a duplicate of another issue? Or do I need to file a new issue to get this looked at?

**Comment by ybkuang** [comment]
Can you provide a link to the sequence that you requested the cut?

**Comment by pbb72** [comment]
One of the examples was included in the original post: http://www.mapillary.com/map/e/PAedSJRBquuNNm4LRr0DwA

For another one I also wrote down the cut ID: NiPV6T0UkGywYBhcgVpVeg, the photo where I requested the cut is http://www.mapillary.com/map/e/fSL2Tl0Fnu7aXzc9Vmgj0Q

**Comment by pbb72** [comment]
Any updates on this? Am I doing things wrong, is this simply not working?

**Comment by ybkuang** [comment]
@pbb72 , we are still looking at it. It could be something in our backend. Will report back!

**Comment by pbb72** [comment]
How is the development on the sequence cut feature going? As long as this feature doesn't work at all (as seems to be the case now) maybe it should be removed from the editor, to avoid confusing people.

**Comment by HolgerJeromin** [comment]
I think you and mapillary are right. 
The users want to cut the sequence at one exact point (aka after "this" image). This does not seem to be possible right now. Only cutting the whole sequence at all places more than x meters. 
As our sequences are rarely have such distances, no cutting gets approved.

I thought i requested a cut, but my changeset only got the rotation approved:
http://www.mapillary.com/map/cs/gwiFRMwmOYXL21fh_oF77Q
The cut was requested at image http://www.mapillary.com/map/e/6CugZvShGvL8vSsynM3n0g to get rid of the crossing of the buildings.

**Comment by pbb72** [comment]
One place where I want to cut (http://www.mapillary.com/map/e/PAedSJRBquuNNm4LRr0DwA) there is a distance of 1.2 km (1200m) between points, so the distance can't be the problem. I've requested a cut several times, but it's never been accepted.

But I agree, I want to be able to cut at points that I choose, not be dependent on a minimum distance.

**Comment by simonmikkelsen** [comment]
I have also had this issue for a while and looked into it:

In newest Chrome on Linux Mint Debian Edition I open
http://www.mapillary.com/map/e/CeTkBCBDQBQiBT2lIJ4RzQ
I press the edit button.
I press the "Request sequence cut" button. This fires an OPTIONS and
POST request to basicprocessing, the latter with skey
x3HzyYlDiW5qnXHBUkPcIg as payload and status 200.
I press the "Save and Review Changes" button. Nothing happens on the
network.
I press the Send Changes button. This fires an OPTIONS and POST request
to create, but the POST fails with status 400. The payload is {"set":"[[]]"}

The latter looks pretty dodgy to me, as 400 is an error code. It may be worth investigating unless a new editing process is very close. I can imagine a lot of areas being polluted by rouge sequence lines.

**Comment by travel193** [comment]
Thanks Simon!

**Comment by pbb72** [comment]
As there is no option anymore now for sequence cutting, I guess I'll just close this...
