### ISSUE TITLE
Editor: changing sequence angles can be done in two steps

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#734]
Currently, after entering a number for changing the camera angle for the whole sequence, you first have to press the checkmark to confirm the number, and then press the "Correct angles" button.

These last two steps should be combined into one, there is no reason for splitting this up in two steps.

**Comment by pbb72** [comment]
Correction, it can be done in even less steps. Why do we have to click the number to be able to edit it, when it could be an open textbox. Write in a number and click the "Correct" button.

You could leave the default value empty, to prevent changing all the directions by an accidental click on the button. That is not done today.

**Comment by Nakaner** [comment]
I agree. It should be visible as a text input field by default.

**Comment by pbb72** [comment]
Not sure, this might be a duplicate of #405

**Comment by gyllen** [comment]
Fixed in new editor. Open new issue if you experience something similar there.
