### ISSUE TITLE
Better organize files inside mapillary dir

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#735]
I was trying to download some pics from my phone from a specific day. But there is one problem: there are only dirs with hashes in mapillary (and thus I can't identify which one belongs to which day).

Could we have an option to split/organize files in day? (or date; and possibly sequence inside day)

**Comment by jesolem** [comment]
I think #714 will solve your problem. Fixed in Android, will be added to iOS too.

**Comment by naoliv** [comment]
Right. Didn't find #714 while searching :-)

**Comment by jesolem** [comment]
;) closing
