### ISSUE TITLE
low-diskspace threshold should be configurable in absolute MB, or less than 2%

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#737]
2% is the lowest I can set it, still means 260 MB on my device, thus I missed some good sequences in perfect light on my way home. 

I'd be happy to leave 10-20MB free for log files if I am on the way to the next wifi waterhole.

(Android)

**Comment by peterneubauer** [comment]
I can lower the limit to zero, and you change it at your own risk?

**Comment by HolgerJeromin** [comment]
+ 1 for counting in mb. much better for big sd cards

**Comment by peterneubauer** [comment]
There is now detailed statistics showing remaining disk in GB, and I downed the the settings to 0% for your convenience.
