### ISSUE TITLE
Android: device dependent aspect ratio?

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#738]
I thought that the app was set to always shoot in 4/3, but I just realized that on a Samsung k-zoom it shoots in 16/9 (example: http://www.mapillary.com/map/im/zH6aKlHum3dHdPGzRYVdGg).

**Comment by peterneubauer** [comment]
When that happens, van you please send a log to check?

**Comment by kaitu** [comment]
Sent. 
By the way, it would be great if you could also have a look at the not working continuous focus on this phone.

**Comment by peterneubauer** [comment]
can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk and report back? Have inserted more debug around the choosing of aspect ratio.

**Comment by kaitu** [comment]
Thanks, the problem is fixed in this version. It correctly chooses the largest available 4/3 resolution.

**Comment by peterneubauer** [comment]
Awesome
Thanks for testing!
