### ISSUE TITLE
92% of my photos are not counted towards country stats because of bad border shape

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#739]
I was wondering why I show up with so few photos (454) for the top Norway stats. But then I noticed the shape for Norway draws it's border straight through Trondheim, making 92% of my photos fall outside!

Technically, you should actually be using the maritime border (off-coast) instead of the land/water edge.

Anyway, could you pretty-please let Trondheim fall completely inside Norway? :-)

(By the way, a similar problem applies to the region borders. Trondheim now falls in between two Norwegian regions.)

![clipboard image](https://cloud.githubusercontent.com/assets/1436366/6392535/d03f2c0e-bdc1-11e4-87a8-c9f509e4334f.png)

**Comment by gyllen** [comment]
We are working on getting better borders for countries. You are not alone on experience this problem. At the moment we are using http://naturalearthdata.com/. Would be happy if anybody could tip us for a better source.

**Comment by pbb72** [comment]
I guess OpenStreetMap is out of the question? ;-) http://www.openstreetmap.org/relation/1059668

**Comment by gyllen** [comment]
If we can keep stuff in separate database I think it will work. I would like to have all cuts of Countries, States, Regions and municipalities in an easy bundle though. Would prefer not to extract from data myself.

**Comment by PolyglotOpenstreetmap** [comment]
Wouldn't it be possible to use Overpass to fetch specific admin_levels?

Jo

**Comment by gyllen** [comment]
We are not experts on extracting OSM data here. @peterneubauer Do you have any experience with that?

**Comment by kaitu** [comment]
OSM boundaries can be also be exported in various formats from this service:
https://osm.wno-edv-service.de/boundaries/

**Comment by jfburke3** [comment]
Is there some way you can make use of the shape files Geofabrik has for download?

http://download.geofabrik.de

(I note in passing that some areas of the U.S. and individual states also appear to have boundary issues on your maps.)

**Comment by pbb72** [comment]
Which data from Natural Earth are you using? None of the three detail levels I downloaded goes through Trondheim:

![clipboard image 2](https://cloud.githubusercontent.com/assets/1436366/6425856/f1af2dc0-bf3e-11e4-8b51-561bc90ab584.jpg)

**Comment by de-vries** [comment]
@gyllen As said you can extract the osm data via [overpass](http://overpass-turbo.eu/). I don't understand how to make a query there, so what I always do is:
- go to [taginfo.openstreetmap.org](http://taginfo.openstreetmap.org/tags/admin_level=2) and find the tag you want. 
- On that page you'll find a [link to the right overpass-turbo query](http://overpass-turbo.eu/?key=admin_level&value=2&template=key-value). 
- @ overpass-turbo you'll find all kind of export options.

**Comment by de-vries** [comment]
this issue is related to https://github.com/mapillary/mapillary_issues/issues/677

**Comment by pbb72** [comment]
Yeah, #739, #677 and #465 are clearly all the same issue.

**Comment by volucris** [comment]
I am experiencing the same issue, and (childish though that may be of me) the toplist would have been a great motivation to go out and map more, had it not disregarded my area.

By the looks of @pbb72 's post, Natural Earth also provides better shapes than those used now, perhaps these can be taken into use until a better source (including marine territories) is found?

**Comment by gyllen** [comment]
@pbb72 @volucris How are this looking on the new site. I know all shapes are not perfect yet but they should be better. We are using "whos on first".

**Comment by pbb72** [comment]
Sorry, my bad for not reporting back! The stats have been great, I think at least for the last year.
