### ISSUE TITLE
Previous photo on "Detect Traffic Signs"

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#740]
Some time I am pressing wrong button on "Detect Traffic Signs game" page. For example, I want to add a new sign but I am pressing "Save" instead of it. 
It would be great to have a possibility to return back to previous edited photos.
Or just separate "Save" button from other buttons by big space.

**Comment by PolyglotOpenstreetmap** [comment]
Already happened to me as well. Maybe a scrolling list might help.

**Comment by pyrog** [comment]
>  I want to add a new sign but I am pressing "Save" instead of it. 

:+1: It happened a "lot" to me

**Comment by gyllen** [comment]
We separated the buttons undo function is not in the works.
