### ISSUE TITLE
No preset for yield sign

### ISSUE THREAD

**Issue by 1ec5** [mapillary/mapillary_issues#742]
In the “Help Us Detect Traffic Signs (us)” tool, yield signs aren’t recognized and there’s no preset for them. They’re pretty recognizable and should be tagged [`highway=give_way`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way).

**Comment by polarbearing** [comment]
What do you mean by preset? I just played the game and there are both, regular yield and stop sign. I also just approved a few images having a yield sign.

**Comment by 1ec5** [comment]
This is the U.S. version of the game, not the EU version. But it looks like @ToeBee already filed mapillary/traffico#21 in the right place.
