### ISSUE TITLE
No presets for U.S. speed limit signs

### ISSUE THREAD

**Issue by 1ec5** [mapillary/mapillary_issues#743]
Unlike the EU version, the “Help Us Detect Traffic Signs (us)” tool has no preset for speed limit signs. The following presets should be offered: 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, and 80 mph in the U.S.; and 30, 40, 45, 50, 55, 60, 80, 90, 100, 110, and 120 km/h in Canada (since this version also includes Canadian photos).

**Comment by gyllen** [comment]
@1ec5 Can you file this issue here instead https://github.com/mapillary/traffico/issues (prefferably a pull request though :))

**Comment by 1ec5** [comment]
OK, filed as mapillary/traffico#38.
