### ISSUE TITLE
Make the speed of the play button configurable

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [mapillary/mapillary_issues#744]
Hi,

Would it be possible to make the speed of the play button configurable?

Jo

**Comment by gyllen** [comment]
I like this idea. Maybe we could just make use of this icons http://fontawesome.io/icon/fast-forward/ we should also be able to go backwards me think.

**Comment by jfburke3** [comment]
+1  -- I was going to suggest the same thing.  I had visualized a speed-control slider to adjust playback speed, but not sure how hard that would be to code.

**Comment by knikel** [comment]
We'll be using [mapillary-js](https://github.com/mapillary/mapillary-js) as the main viewer for the new mapillary.com. This could be something that mapillary-js supports and has in the API.

**Comment by oscarlorentzon** [comment]
[MapillaryJS 2.10.0](https://github.com/mapillary/mapillary-js/releases/tag/v2.10.0) supports configurable play speed. Try it in the [examples section](https://github.com/mapillary/mapillary-js#examples). [mapillary.com](https://www.mapillary.com) will be updated in the coming days.
