### ISSUE TITLE
Stuck in "Railroads" project

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#749]
Through a link in the OpenStreetMap wiki it seems I ended up in the "Railroads" project.

But now I seem to be stuck there, I can not see any of the normal sequences or photos anymore. The top bar of the website also changed color to green.

How do I get back to the main project?

**Comment by jesolem** [comment]
@pbb72 Weird bug here. Railroads is a test project of ours. 

Do you see a "project" link in the top navbar? If so clicking in "Mapillary Public" will take you back to the public data (and the regular black nav bar).

![image](https://cloud.githubusercontent.com/assets/136751/6413209/62d44e3e-be8d-11e4-8182-1d5dabb80414.png)

**Comment by jesolem** [comment]
BTW, where was the link from?

**Comment by knikel** [comment]
@pbb72 Logging out and cleaning local storage/cache in the browser settings will work. If you don't want to lose other websites localStorage data, open the console while on mapillary.com and type `localStorage.clear()`, hit enter and refresh the page. Sorry for the trouble!

**Comment by pbb72** [comment]
Thanks @knikel, that command helped me out. All is OK now.

The link I was talking about is the "Take surveys of construction sites" link on http://wiki.openstreetmap.org/wiki/Mapillary

No "Project" link in the top navbar:
![clipboard image 2](https://cloud.githubusercontent.com/assets/1436366/6415305/818ecfc8-be9e-11e4-845d-e6b03f2237cc.png)
