### ISSUE TITLE
Blur was accepted, but not all blur spots are blurred

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#750]
Some time ago (minimum several months), I requested blurring for http://www.mapillary.com/map/im/OSmB9nk75f0i2178_oejTw.
Today I viewed it again and noticed, that not all red rectangles that appear on http://www.mapillary.com/map/b/OSmB9nk75f0i2178_oejTw are blurred.

**Comment by gyllen** [comment]
Thanks for reporting this, if you find more please post here.

**Comment by gyllen** [comment]
Issue fixed, please report if you see again, closing.
