### ISSUE TITLE
Duplicated and superposed traffic signs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#751]
Today, I saw 3 images with traffic signs detected twice:

![traffic signs detected twice](https://cloud.githubusercontent.com/assets/2158081/6417789/39ab62ae-beb0-11e4-88ed-1dc9f1ae9eaf.png)
https://d1cuyjsrcm0gby.cloudfront.net/YwpCUyhNuY7gNdvjspGPCg/thumb-1024.jpg

**Comment by Peatsmoke** [comment]
I have seen this too, for more than once over the last two days.

**Comment by ybkuang** [comment]
Thanks for reporting this! 

We are removing overlapping detections, so ideally this should not happen. We will look into it.

**Comment by pyrog** [comment]
http://www.mapillary.com/map/im/e5rYaBaA6BHUJluyRkBisw
![duplicated traffic signs](https://cloud.githubusercontent.com/assets/2158081/6427156/709f49ec-bf78-11e4-8cca-8ed01ee9a1bf.png)

**Comment by ybkuang** [comment]
This should be resolved by the latest [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html). Please let us know if the issue persists.
