### ISSUE TITLE
Error 400 in upload

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#752]
(Android)
Normal uploads end with "upload status: 204" which is a bit funny since as a http code it means No Response, status 200 OK would be more logical, but well...

02-27 21:09:31.167 D/app.mapillary.android.sync.UploadService$SendFileTask[1]( 2008): upload status: 204

In uploading larger sets of sequences with several hundred images, I occasionally (in 3 out of 4 cases so far) get a "upload status: 400" and the file is still in the review folders on the android. A new upload request had always uploaded the remaining file. 

Fri Feb 27 18:50:50 CET 2015 : app.mapillary.android.sync.UploadService$SendFileTask[1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1]  - Uploading photo /storage/sdcard0/mapillary/2015_02_26_11_32_44_206/2015_02_26_11_39_29_120.jpg to http://mapillary.uploads.images.s3.amazonaws.com/
Fri Feb 27 18:50:50 CET 2015 : app.mapillary.android.sync.UploadService  - sleeping.0/169 of 428

and a while later
Fri Feb 27 18:53:11 CET 2015 : app.mapillary.android.sync.UploadService$SendFileTask[1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1][1]  - upload status: 400

* If that is simply a hickup of that cloud server, could the app simply try again?

* When I later upload the remaining file again, is it automatically inserted in its sequence since it has the sequence UUID embedded?

**Comment by eliasp** [comment]
Same here. I have a sequence where all but the first 2 images where uploaded.
Other new sequences are uploaded just fine, but those 2 images will always end up with `Error: Upload failure (400)`.

The same happened before with 2 other sequences where I just ended up deleting the remaining pictures.

Log of latest attempt:
```
03-01 23:39:00.419 D/app.mapillary.android.activity.StorageUtils(20879): getDefaultImageStoragePath- /storage/emulated/0/Android/data/app.mapillary/files/mapillary
03-01 23:39:00.479 I/Timeline(20879): Timeline: Activity_idle id: android.os.BinderProxy@42a5aac0 time:648202232
03-01 23:39:05.209 D/app.mapillary.android.activity.MainActivity(20879): Appending log to /storage/emulated/0/mapillary.log
03-01 23:39:05.839 I/Timeline(20879): Timeline: Activity_idle id: android.os.BinderProxy@42f29500 time:648207592
03-01 23:39:06.889 I/Timeline(20879): Timeline: Activity_launch_request id:com.android.bluetooth time:648208644
03-01 23:39:08.469 D/app.mapillary.android.activity.StorageUtils(20879): getDefaultImageStoragePath- /storage/emulated/0/Android/data/app.mapillary/files/mapillary
03-01 23:39:08.539 I/Timeline(20879): Timeline: Activity_idle id: android.os.BinderProxy@42a5aac0 time:648210299
03-01 23:39:23.009 D/app.mapillary.android.activity.Utils(20879): WiFi: true, Ethernet: false
03-01 23:39:23.009 D/app.mapillary.android.sync.NetworkMonitor(20879): We have Wifi or Ethernet Connection.
03-01 23:39:23.029 D/app.mapillary.android.sync.ImageUploadSynchService(30844): initializing
03-01 23:39:23.039 D/app.mapillary.android.sync.MapillaryUploadSyncAdapter(30844): onPerformSync for account[mail@eliasprobst.eu], manualSync true
03-01 23:39:23.039 D/app.mapillary.android.sync.MapillaryUploadSyncAdapter(30844): Cell sync pref: false
03-01 23:39:23.039 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.049 D/app.mapillary.android.sync.UploadService(30844): startUpload
03-01 23:39:23.049 D/app.mapillary.android.service.StorageUtils(30844): getDefaultImageStoragePath- /storage/emulated/0/Android/data/app.mapillary/files/mapillary
03-01 23:39:23.059 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.069 D/app.mapillary.android.sync.UploadService$SendFileTask(30844): Cell sync pref: false
03-01 23:39:23.069 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.069 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.069 D/app.mapillary.android.sync.UploadService$SendFileTask[1](30844): Uploading photo /storage/emulated/0/Android/data/app.mapillary/files/mapillary/2015_02_28_15_13_53_077___Mapillary/2015_02_28_15_16_36_758.jpg to http://mapillary.uploads.images.s3.amazonaws.com/
03-01 23:39:23.079 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:23.089 D/app.mapillary.android.sync.UploadService$SendFileTask(30844): Cell sync pref: false
03-01 23:39:23.089 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.089 D/app.mapillary.android.activity.Utils(30844): WiFi: true, Ethernet: false
03-01 23:39:23.099 D/app.mapillary.android.sync.UploadService$SendFileTask[2](30844): Uploading photo /storage/emulated/0/Android/data/app.mapillary/files/mapillary/2015_02_28_15_13_53_077___Mapillary/2015_02_28_15_16_33_287.jpg to http://mapillary.uploads.images.s3.amazonaws.com/
03-01 23:39:24.079 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:25.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:26.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:27.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:28.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:28.419 D/app.mapillary.android.activity.MainActivity(20879): Appending log to /storage/emulated/0/mapillary.log
03-01 23:39:28.899 I/Timeline(20879): Timeline: Activity_idle id: android.os.BinderProxy@43133800 time:648230658
03-01 23:39:29.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:29.779 I/Timeline(20879): Timeline: Activity_launch_request id:com.android.bluetooth time:648231539
03-01 23:39:30.089 D/app.mapillary.android.sync.UploadService(30844): sleeping.0/0 of 2
03-01 23:39:30.549 D/app.mapillary.android.sync.UploadService$SendFileTask[2](30844): upload status: 400
03-01 23:39:30.999 D/app.mapillary.android.sync.UploadService$SendFileTask[1](30844): upload status: 400
03-01 23:39:30.999 D/app.mapillary.android.sync.UploadService(30844): Done, errors Upload failure (400)
03-01 23:39:31.089 D/app.mapillary.android.sync.MapillaryUploadSyncAdapter(30844): onPerformSync for account[mail@eliasprobst.eu], done.
03-01 23:39:31.169 D/app.mapillary.android.activity.StorageUtils(20879): getDefaultImageStoragePath- /storage/emulated/0/Android/data/app.mapillary/files/mapillary
03-01 23:39:31.219 I/Timeline(20879): Timeline: Activity_idle id: android.os.BinderProxy@42a5aac0 time:648232973
```

**Comment by peterneubauer** [comment]
Any chance you can send me one of these images, so i can try to upload it from my phone and debug?

**Comment by eliasp** [comment]
Uploaded them to my box as I'm not sure whether GitHub will do any changes (resizing, EXIF, …) when uploading them here:

* [2015_02_28_15_16_33_287.jpg](http://eliasprobst.eu/~elias/stuff/mapillary-752/2015_02_28_15_16_33_287.jpg)
* [2015_02_28_15_16_36_758.jpg](http://eliasprobst.eu/~elias/stuff/mapillary-752/2015_02_28_15_16_36_758.jpg)

**Comment by peterneubauer** [comment]
Cool.
The images are over 10.5 MB which is the current upload limit. @gyllen we need raise that. What phone is this @eliasp ?

**Comment by peterneubauer** [comment]
Also, @eliasp if this is an SLR, could you try to compress the image a bit, since it seems 10.8 MB for a picture of 4208x3120 looks quite much? You then can upload it with the current S3 settings.

**Comment by polarbearing** [comment]
I wonder if the returned upload failure could be more specific than just Error 400, to analyse the reason? In my case the leftovers always uploaded in the second attempt, and they were much smaller than 10MB. 

@eliasp - the log reveals your mail address, you might edit that to keep it private.

**Comment by eliasp** [comment]
The phone is a OnePlus One. 

On March 2, 2015 8:36:23 AM CET, Peter Neubauer <notifications@github.com> wrote:
>Cool.
>The images are over 10.5 MB which is the current upload limit. @gyllen
>we need raise that. What phone is this @eliasp ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mapillary/mapillary_issues/issues/752#issuecomment-76669247

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eliasp** [comment]
Activated now "take low resolution pictures" in the settings. Let's see how usable the resulting pictures are and whether I'll run into the 400 again. 


On March 2, 2015 8:39:29 AM CET, Peter Neubauer <notifications@github.com> wrote:
>Also, @eliasp if this is an SLR, could you try to compress the image a
>bit, since it seems 10.8 MB for a picture of 4208x3120 looks quite
>much? You then can upload it with the current S3 settings.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mapillary/mapillary_issues/issues/752#issuecomment-76669508

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peterneubauer** [comment]
Is this working now?

**Comment by polarbearing** [comment]
If you mean me, my last upload went through, but not enough to be statistically safe to say fine, wait a few days.

**Comment by polarbearing** [comment]
Ok last night was fine as well. There were 1375 files uploaded with purely status '204' since March-05. 
From Feb-27 - Mar- 04 there were 2136 files with '204' and 4 with '400'.
This coincides with the status log lines being tidied from the accumulated thread numbers (old: [3][3][3][3][3][3][3][3][3], new: [1]).
I notice that I had switched the number of parallel threads to 2, using the new setting, will test with 4 from now.

**Comment by peterneubauer** [comment]
Very good to hear,
Thanks for the thorough investigation @polarbearing!

**Comment by vincentdephily** [comment]
Sorry for reusing a closed issue, but it seems to match regular errors 400 I get. Retrying yields consitent failure. The pics are often bigger than 10mb, as this is a phone with a 20mp sensor. The logs just say status 400, and i've tried with different number of upload threads.

**Comment by vincentdephily** [comment]
The remaining problem has been resolved some time last week AFAICS. The app uploaded my backlog of > 10mb photos, and hasn't built a new backlog yet. Thanks.

**Comment by peterneubauer** [comment]
Mmh,
Even the new v1.39 is still stuck?

**Comment by vincentdephily** [comment]
As I said, my backlog of about 150 photos got unstuck some time last week and no more stuck images since, so all is well, thanks. Before that, my workaround was to use an app that reduced the image file size, but it was very cumbersome.

I was on 1.36 until now, I'll see if 1.39 is any different.

**Comment by peterneubauer** [comment]
Coolio, thanks!
