### ISSUE TITLE
Select all images with blur in editor

### ISSUE THREAD

**Issue by Montfrooij** [mapillary/mapillary_issues#753]
I'd like to be able to get a list with pictures of all blurs that were applied (I'm thinking about the website editor)
I'm noticing many 'false' blurs, but since they can appear anywhere in a sequence, I have to walk through the sequences one by one to correct this. 
A list with all pictures that have a blur (and the possibility to edit them) would save a lot of time. 
(and mean I would actually check them all)
Peter

**Comment by richlv** [comment]
i'd like to see a button/control "jump to next image with blur" :)

**Comment by richlv** [comment]
also very similar to #357

**Comment by knikel** [comment]
Closing in favor of #357
