### ISSUE TITLE
Upload fewer images in parallel on Android

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#754]
My Android images are about 4 MByte. At home i have the incredible upload speed of 40 kbytes/s. So one image needs 15 minutes to upload, if i did the calculation right.
The progress bar starts with 4 of x Photos so i think you transfer 4 in parallel.
The chances to have an abort in one hour are very high. Do you use resume?

I would like to reduce the parallel uploads to two connections (or automagic if we have a fast network).

**Comment by peterneubauer** [comment]
That sounds like a setting to add maybe?

**Comment by HolgerJeromin** [comment]
I am not sure if 4x parallel is a good idea with any connection speed. Because we have large files and not very much small files. So I think the app will fill the uplink even with only one connection.

**Comment by polarbearing** [comment]
See also #752 about retrying broken uploads.
