### ISSUE TITLE
Android App Dev option: GPS accuracy change

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#755]
Please have a dev setting in Android APP of mapillary to set the needed accuracy of GPS signal to 20, 25 or 30 meter instead of 15 meter.
In cities with small streets it is nearly impossible to get a GPS fix with <15 meter failure rate.
I need to replace the images in webbrowser afterwards, even with 15m fixation.
With this you can get more pictures from within these areas.

aceini

**Comment by peterneubauer** [comment]
Well, you can enable the stats to see the full accuracy, and disable the location check to take pictures with lower accuracy than 15m.that covers this pretty much?

**Comment by kaitu** [comment]
I reckon that pictures taken with lower accuracy will otherwise just be disregarded on your side, while echeloni2p meant to realign them in webbrowser. Maybe you could implement a filter showing images taken with lower accuracy and show them normally after they have been manually approved or repositioned?

**Comment by polarbearing** [comment]
Android's "accuracy" value is snake oil anyway, as it is based on HDOP only. You can have a systematic ionospheric error of 30 m while the device assumes, based on good constellation, a 5 m "accuracy"; or a signal reflected on a building projects you 200m away for a few seconds.

**Comment by echeloni2p** [comment]
Whatever, if I take pictures with no location check, it is shown "pictures will be discarded" - what sense is in taking this pictures?
I want those pictures on the map and relocate them afterwards with my browser to let them be in the right place. 
So: howto make pictures with 30m accuracy and get them into mapillary map?
(and yeah, the error shown is somewhat time based, but in some areas you will not get towards the needed 15m for the app and the app will not take any pictures in default mode)
aceini

**Comment by peterneubauer** [comment]
Well,
the pictures without GPS will be discarded, but might be good for e.g.
indoor testing and then deletion on the phone. The bad-fix ones are right
now not discarded on the servers, but might not be shown or discarded in
the future to guarantee some minimum of data quality, so we don't want to
promise anything there :)
