### ISSUE TITLE
make map to move pictures of a track bigger

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#757]
Please make the map view in which users can move pictures of a track around bigger, or: resizeable.
It is a pain in the *** to fiddle around with such a small windows and in a useable zoom to move pictures around, I see soemtimes too few and need to scroll around to much.
Or if a lot of pictures are clogged on a small area, it jumps too much from picture to picture without being able to easy move picture around.

**Comment by knikel** [comment]
Will be much better experience after we update the editor.
