### ISSUE TITLE
icons of pictures in edit mode went gone, no notification of changeset

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#758]
While editing a 400 picture track, the markers of the single images in edit view (the map) went gone and only the track was visible. (I do not remember if I still saw the changed images below the map).
I could not click any picture anymore and move any of them around. One note: I guess server was still processing that track for road signs and registration.
I click on save changes and I got no email about that changeset being accepted, even in my profile I did not see any notification of the changes I sent to the server. It was like I did not sent anything at all.

After some time I got a message about changeset applied.

**Comment by gyllen** [comment]
We are working on a dashboard where change sets will be more visible.

**Comment by gyllen** [comment]
This will be incorporated in the new feed. Also backend is completly rewritten. Closing this. Add new ticket if you find any issues with new editor.
