### ISSUE TITLE
"Sync when not charging" ignored

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#759]
I have "Sync when not charging" not checked. I wait it means nothing will upload until I will swich charger into phone.
Instead I see app photos was uploaded when I enter home (wifi start be accessible).

Seems setting "Sync when not charging" ignored or something like that.

**Comment by peterneubauer** [comment]
Can you please send the log when this is happening?

**Comment by iav** [comment]
Where to send?

**Comment by peterneubauer** [comment]
Thanks. If you request manually to sync, the battery setting is overridden, is that what you were doign? Will add better wording around it.

**Comment by iav** [comment]
No, I not press sync button

**Comment by de-vries** [comment]
@peterneubauer the wording is better now, but I have two issues:
1. The line is so long that, even in horizontal mode, it gets cut. Better allow it to split over more lines.
![screenshot_2015-03-02-11-04-29](https://cloud.githubusercontent.com/assets/1449609/6438717/196c2f50-c0cc-11e4-804d-4fddbb6bff83.png)
2. The double negative is a bit confusing. Better would be: "~~Don't sync automatically~~ Block automatic sync When phone is ~~not charging~~ on batery. [...]" (or remove just one of the negatives)

**Comment by peterneubauer** [comment]
Is this still an issue with the newest build from https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk ?

**Comment by iav** [comment]
Will try on week, thank you.

**Comment by iav** [comment]
Today i Run this 
> Is this still an issue with the newest build from https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk

It seem work as it should on first look.
And now I think - maybe - it work previously too - but it incorrectly shows status in notification area: too rare updates. At least not change status when power cord swiched off, and stiill show "uploading".

**Comment by iav** [comment]
Today I got 500 photos, and like to keep it inside phone ungtil go home.  But all them was uploaded via wifi and drain near all battery while I was guest. "upload on battery" was not set - I checked it.

Did "am I on carger?" checked periodicaly and often (about 1 time in 5 sec), starting upload of every photo, or once on batch start?

I drive to my friends with smartphone powered by car charger, abd it can connect to my friends home wifi untill I disconnect charger. It's a reason why it can start uploading.
But then it should stop upload after power disconnection - at least, I hope so.
I will send logfile via email.

**Comment by voschix** [comment]
I confirm that the problem of the upload starting automatically when on battery with "upload on battery" is not checked, is present in Android version 1.39.

**Comment by peterneubauer** [comment]
Ok, looking into it now ...

**Comment by peterneubauer** [comment]
out now in the alpha.
