### ISSUE TITLE
Bug: Traffic-sign count on map.

### ISSUE THREAD

**Issue by Peatsmoke** [mapillary/mapillary_issues#761]
While tagging signs, I found this strange behaviour. 
![gh001](https://cloud.githubusercontent.com/assets/10783093/6430280/0f405002-c003-11e4-99a7-ac79556ccc25.jpg)

When zooming in to this point I see several photos. This one is definitely not in Straelen but somewhere in Belgium, looking at license plates, traffic signs and lights:
![gh002](https://cloud.githubusercontent.com/assets/10783093/6430300/18fe27ee-c004-11e4-844c-3fc42224b496.jpg)

**Comment by floscher** [comment]
This is a problem with sequence http://mapillary.com/s/DiZwBKuoi3GvX7u8vG8q2Q that has set its coordinates to 51.380445° N 6.231432° E for every single image.

It was taken on the A67 in the Netherlands, starting near Eindhoven (between exit 32a and 34) and heading east.

Probably this has nothing to do with traffic sign editing, but rather is either an issue with uploading or wrong EXIF-tags.

**Comment by floscher** [comment]
There is also another sequence with the very same coordinates and by the same user: http://mapillary.com/map/s/YHznDQMLrKBTEHvr-d0ojg

But this sequence consists only of completely black images with different aspect ratios:
![oyks9cwfb3vfjo-aqaf2zw](https://cloud.githubusercontent.com/assets/3904348/6431473/25233672-c031-11e4-80ac-3b55619c2dfe.jpg)
http://mapillary.com/map/im/oYKs9cWFb3vfJO-AqAF2zw
![mwoe2savsrwr2yvubnepcq](https://cloud.githubusercontent.com/assets/3904348/6431477/3ad82c52-c031-11e4-8e5c-310cf8afa075.jpg)
http://mapillary.com/map/im/Mwoe2SAvsRWR2yVUbNEpCQ

**Comment by gyllen** [comment]
Hmm we should probably remove these sequences.

**Comment by gyllen** [comment]
This is part of old web interface so closing.

**Comment by floscher** [comment]
Could you delete the sequence http://mapillary.com/map/s/YHznDQMLrKBTEHvr-d0ojg ? It still consists only of black images of different aspect ratios.
The other sequence can be corrected more easily, because it's only misplaced.
