### ISSUE TITLE
Sequence split request should make clear if it should be split before or behind current picture

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#762]
Website: When I request a sequence split, the request is an edit of image A. It is not clear if image A should be the last image in the earlier sequence or the first image of the later sequence.

**Comment by floscher** [comment]
AFAIK currently every request is reviewed by a human, who probably will be able to decide quite reliably where to split.

But it wouldn't hurt, if the flagging message would be changed to either "The sequence should be split after this image" or "The sequence should be split before this image", as splitting after the last and before the first image would make no sense.

What I'd rather like to see is, that the creator/uploader of images gets the same abilities to react on a flagged image (i.e. to rotate flagged images and split sequences).

**Comment by pbb72** [comment]
Has anybody ever been able to use the sequence split feature? It's never worked for me, I don't even get a confirmation email after requesting a split.

**Comment by floscher** [comment]
I never used it myself, because I had no need to yet. I would've rather needed a "glue"-tool for merging two sequences.

As the request from @polarbearing has been fulfilled, this can probably be closed.

**Comment by HolgerJeromin** [comment]
I think the splitting is done on every places where the distance is greater than 300 meters. No way to select. 
But I am unsure. :-)

**Comment by floscher** [comment]
@HolgerJeromin You can also request a split when clicking on the flag icon below an image on the Mapillary site. That's what this issue is about. There is no problem left to solve, this issue is finished and can be closed.

**Comment by gyllen** [comment]
Sequence splitting is now done automatically
