### ISSUE TITLE
App should record full GPX trace

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#763]
Feature request: Android (and other mobile devices):
As a courtesy to OSM mappers, with a switch in the dev settings, the app should record a GPX trace of the drive all the time it is running and has GPS signal, independent of triggering a picture or not. 

The output should be one gpx file per running session of the app, potentially with new `trkseg` per sequence cut.  The `trkpt` should contain `time, lat, lon, ele, speed, course, hdop, sat` and fixtype if available.

**Comment by ybkuang** [comment]
Good suggestion! There are several things that need to done in our backend for handle this properly. We will definitely consider this in the future versions.

**Comment by peterneubauer** [comment]
If you need that, please run any decent GPX tracker in the background.
