### ISSUE TITLE
app incorrectly creates new segments

### ISSUE THREAD

**Issue by zdila** [mapillary/mapillary_issues#765]
App incorrectly creates new segments "because of 300m gap", but thre is no such gap. See for example this: https://www.mapillary.com/map/im/1HK5CVRDoYAaoCKrlbIutg

Is there a way to join these segments?

**Comment by gyllen** [comment]
Wow nice sequence! At the moment you can not merge sequences from webpage. We will see over app functionallity. Luckily enough the images are close enough that if you press forward (or use the playbutton) image will still be connected.

**Comment by polarbearing** [comment]
@zdila you would need to check the log what caused that 300 m assumption. A possible reason is a spurious GPS error, e.g. a temporary signal reflection, that projected you far away for a moment.

The app could implement a filter against unplausible jumps.

**Comment by zdila** [comment]
@polarbearing, where can I find the log? Is it stored on the SD card?

**Comment by peterneubauer** [comment]
The mapillary.log file will be created when you do "send debug logs" in the root of your sdcard as "mapillary.log"

**Comment by zdila** [comment]
There is no "send debug logs" in Settings or in Settings/Developer.

**Comment by polarbearing** [comment]
what app version are you using?

**Comment by zdila** [comment]
Sorry, I've found it below "settings" menu item :-). Unfortunately there are only log messages from just couple of minutes ago.

Version: 1.16 / 116

**Comment by polarbearing** [comment]
As I understand "send debug log" retrospectively grabs a number of log lines from the system log, thus your situation might have been expired. "Write trace log" is a file the app continuously writes by itself, thus proactively.

**Comment by zdila** [comment]
I've turned on "write trace log" and will see next time I record the track.

**Comment by peterneubauer** [comment]
Thanks so much @polarbearing for jumping in here - yeah, try to enable
trace and send it next time things happen.

**Comment by zdila** [comment]
The problem occured again for example here http://www.mapillary.com/map/im/JsQr2HSXoMXOSNA5Cr-mpQ. Thet time I had `Developer / Write trace logs` turned on so you can analyze it. I have not found that file on my sdcard, probably because it has been deleted after upload. Do you have it now on your server os should I try to check it before uploading?

**Comment by peterneubauer** [comment]
Martin,
yes, the tracefile should be at the location pointed out in that setting,
normally as /sdcard/mappilary.trace I believe. Would be great if you can
send it, the normal "send logs" menu item should pick it up.

/peter

**Comment by zdila** [comment]
`Send logs` will send me a mail with the only text "Some logs". But I was able to tgz it from my sdcard and upload it to [Google Drive file](https://drive.google.com/file/d/0B6M72P2gzYmwbEFuczZ5TW9nbEE/view?usp=sharing).

**Comment by peterneubauer** [comment]
Thanks a lot! It seems your GPS was not in its best shape on these sequences, considering how off they are from the street. Have inserted more debugging, and displaying the actual detected gap. Other than that, form the data the gap cutting seems correct to me, looking at the logs.

https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk for the new version.

If this happens a lot, maybe we need to increase the max gap setting further.

**Comment by zdila** [comment]
[Here](http://www.mapillary.com/map/im/3A849YSVPtefVk9YcYQG2w) it looks that GPS is nicely on the road. Despite of that there is a gap. Maybe there is some filtered-out point which farther than 300m, the point that caused the gap (can you see it in the logs I've sent?).

If yes, there could be another solution. If we have 3 points A, B and C and the distance between A and B is more than 300m, but distance between A and C is less than 300m, then point B could be excluded and no gap would be created. Or maybe even for points D, E, F, G, H: if D - E > 300m but D - H < 300m then filter out E, F, G.

I will send you more debug logs propably next week created with apk you've attached.

**Comment by peterneubauer** [comment]
Coolio, to detect the gap I'm using Androids  http://developer.android.com/reference/android/location/Location.html#distanceTo(android.location.Location) which gives me > 300m on these images (you can see it in the log, too). Let's see how it works out in your next trial.

**Comment by zdila** [comment]
[Here](https://drive.google.com/file/d/0B6M72P2gzYmwcjFHNmhraEdTaXc/view?usp=sharing) you can download the trace log. Please check my records from yesterday, eg. [this segment](http://www.mapillary.com/map/im/dhsxT71QFk8EHiHGC6wHjQ) and all adjanced, in both directions. New segments are still created very often but the message now displays gaps longer than 1500m. Note that when using my phone for turn-by-turn GPS navigation, it works normally without any jumps outside the road. Same is for Locus Pro application where I record my tracks (record every second and if point is at least one meter from the previous one) - the recorded track lies nicely on the road without any wacky points.

**Comment by peterneubauer** [comment]
Ok,
it seems the stock formula is calulating too big gaps. I have now implemented http://stackoverflow.com/questions/27928/how-do-i-calculate-distance-between-two-latitude-longitude-points, and increased the max gap value setting to  1500m. Can you test https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk again (v1.21)

**Comment by zdila** [comment]
Thanks, installed. I will check it, but probably earliest at weekend :-)

**Comment by zdila** [comment]
With v1.21 it created nicely only single segment - http://www.mapillary.com/map/im/We_S_d8Hy_5i938GzlaR1A

**Comment by peterneubauer** [comment]
That's nice, feel free to close the issue if it is working correctly!

**Comment by zdila** [comment]
I'll test once more during a weekend. It will be a longer trip. If it is ok then I'll close it. Thanks :-)

**Comment by zdila** [comment]
No problems after [last](https://www.mapillary.com/map/im/IAzPh918Xh_xInU5rDJEmg) [recordings](https://www.mapillary.com/map/im/7rT0gu-dFE-3d10TYgqllA). Thanks!
