### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#766]
My browser shows a warning that the website is only partially encrypted, when called via https. 
Reason might be a hardcoded fav-icon:
`<link href='http://www.mapillary.com/favicon.ico' rel='icon' type='image/ico'>`

The login page should always redirect itself to the SSL version:
`http://www.mapillary.com/map/login` accepts login without SSL

**Comment by gyllen** [comment]
We will see over the missing https assets. Login page is no problem, data will always be sent of SSL. Our API server do not accept plain traffic.

**Comment by HolgerJeromin** [comment]
you could use http://www.paulirish.com/2010/the-protocol-relative-url/ for the favicon (and other stuff).

**Comment by knikel** [comment]
Fixed through #1871
