### ISSUE TITLE
Other people's sequences on my profile page

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#767]
At least twice now I've pulled up my profile page and thought to myself "hmm these don't look like my pictures." This time I got a screenshot. As you can see, this is my profile page but the sequence the mouse is hovering over was uploaded by someone else. All sequences in the first three rows are other people's pictures. After that it seems to be all mine.

![mapillary_wrong_profile](https://cloud.githubusercontent.com/assets/348948/6457952/3d279322-c143-11e4-93ac-21b34a842bac.png)

**Comment by kayD** [comment]
I can confirm this, happened 1 or 2 days ago. It went away after some refreshing though (it refreshed automatically after some seconds). Pressing F5 did not reproduce the problem. (Did not bother to do thorough tests then.)

**Comment by ToeBee** [comment]
Just happened again. Again, the first 3 rows of images were from another user. A refresh fixes it.

**Comment by gyllen** [comment]
Thanks for reporting.

**Comment by gyllen** [comment]
Should be fixed now

**Comment by ToeBee** [comment]
I don't have sufficient permissions to reopen this issue but it happened to me again just now. The first 3 rows are not my sequences.

![screenshot - 06282015 - 04 40 51 pm](https://cloud.githubusercontent.com/assets/348948/8398466/b9ead202-1db4-11e5-8ae6-f96bd6572776.png)

**Comment by gyllen** [comment]
@ToeBee How did you get to the profile page, did you press a link or did you go directly there (trying to debug here)

**Comment by ToeBee** [comment]
I don't remember with complete certainty but I think in this case I was in the middle of uploading a sequence and opened up a new tab, went to mapillary.com and then clicked on the profile link from the user nav menu. I don't have my profile page bookmarked and my profile isn't my browser's first suggestion when I type mapillary in the URL bar so I'm pretty sure I got to it through a link of some kind on your site, not a direct load.
