### ISSUE TITLE
Android app shows blinking "Processing" message, taking no more photos

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#768]
I've come across this situation a few times now. After taking one or two photos in a sequence, the camera in the Mapillary app shows a message "Processing" on the screen, coming up every few seconds. This lasts at least several minutes.

No more photos are being taken. It does not help to stop the sequence and start a new one, the "Processing" message comes up straight away. I need to exit the camera module, and then enter it again to make more photos.

**Comment by pbb72** [comment]
I've send the log files in an email. It seems like this often happens after I hold up the phone to check the sequence counter.

According to the log files, a photo is being taken, but the pictureCallback is never logged.

**Comment by pbb72** [comment]
Again several instances today. It's starting to become irritating, to walk a long street and then see only 1 or 2 photos have been taken! :-1:

**Comment by gyllen** [comment]
Which app? Andriod or iOs?

**Comment by pbb72** [comment]
Title says it all ;-) Android it is

**Comment by peterneubauer** [comment]
Can you try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk, putting a bit more debugging around this.

**Comment by pbb72** [comment]
I've installed that version, and did my best to trigger the bug. I managed 7 times in half an hour :)

**Comment by peterneubauer** [comment]
Ok,
I added a new camera setting "process pictures in the background". https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk

If you uncheck, the processing will happen in the main thread, much like the old approach pre-1.0. Does that work better for you?

**Comment by HolgerJeromin** [comment]
Please do not make this the default again :-)
My old phone (desire hd) had a lot of camera freezes (had to restart phone) in the pre-1.0 release, due to some lags of the OS. I was only able to capture with 4s delay. 
With the new app the phone sometimes freezes for a few seconds (also playing podcast is not responding) and the next picture is skipped with the "processing not ready" message. But i am able to capture with 2 sec delay on this old hardware!

**Comment by pbb72** [comment]
I still managed to get the phone stuck on "Processing" twice this morning, with background processing turned OFF.

**Comment by peterneubauer** [comment]
Try out https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk, I have switched to another way of checking processing, as I suspect a concurrency issue here.

**Comment by pbb72** [comment]
Works good so far, no Processing problems at all this morning! I will be doing more tests in the next few days.

**Comment by HolgerJeromin** [comment]
then peter has to decide if the option of background processing will survive.

**Comment by peterneubauer** [comment]
So,
if there is no problem now with the default of background processing, I
will remove foreground processing again since it leads to a more sluggish
UX.

**Comment by pbb72** [comment]
Please note that todays problem-free walk was with background processing turned OFF. I can do another test later today or tomorrow with background processing turned ON again.

**Comment by peterneubauer** [comment]
Yes,
please do!

**Comment by pbb72** [comment]
I had one "Processing" instance this morning, with background processing set ON. By coincidence it was at the end of a street where I stopped the sequence myself, so I am not sure if the processing in this instance would have prevented further photos or not.

I will be doing more testing with background processing and reporting back :-)

**Comment by peterneubauer** [comment]
Ok, let me know. The "processing" is now triggered by the number of active worker tasks, so this might actually be legit. Happy to hear that things might be working out now - that thing has been pestering us for a long time now :)

**Comment by polarbearing** [comment]
Was driving today with yesterday's version and did indeed notice no processing delays, shooting was quite regularly. Had a couple of white-screen crashes, will have a look into the log and mail it.

**Comment by peterneubauer** [comment]
Thanks!

**Comment by pbb72** [comment]
Two days without any processing messages. We have a winner! :-D

It works great for me now, so I am closing this issue.

**Comment by peterneubauer** [comment]
Awesome, releasing today.
