### ISSUE TITLE
Android app should set counter to "0" as soon as starting a new sequence

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#769]
Take this situation:

I was walking through a street, taking photos. At the end of the street, the on-screen counter was on 10. I turned around to take photos in the other direction, started a new sequence, and at the end of the street the counter was at 10. "Wow, that is very consistent," I thought. I went into a much shorter side street, started a new sequence, and at the end of this street the counter was also at 10. "This is getting suspicious..."

In the end I found out that ONLY in the first street had photos been taken. The counter only showed "10" because it had never been reset after the first street. Currently the counter only changes after a photo has been taken. If no photos are being taken because of whatever problem (bad GPS reception, blur, tilted phone, app too busy, etc) then the screen keeps on displaying the last result. This is not good.

Instead, the counter should be reset to "0" as soon as I start a new sequence. (Even before any photos are taken.)

**Comment by peterneubauer** [comment]
Should be changed in the latest build, https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk

**Comment by pbb72** [comment]
Yes, very nice! :-)
