### ISSUE TITLE
Webbrowser doesn't show previous photo/map when going back

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#771]
While following a sequence of photos on the website, and when clicking a new position on the map, the current URL is updated.

This is very nice, it allows to easily link to specific photos and map locations, by simply copying the URL.

However, when pressing the "Back" button in the webbrowser, even though the previous URL is displayed, the screen does not update. It does not display the previous photo or the previous map position. I tested this on Internet Explorer 11, Firefox 36 and Chrome 40.

And additional problem with every photo changing the URL, is that it gets very hard to go back to the previous webpage. It's not uncommon to browse through 100+ photos, and it gets very difficult to go back so many steps in a mobile webbrowser. On Firefox and Chrome it's even impossible go to more than 50 pages back. (You have to use the History manager to go further back.)

**Comment by de-vries** [comment]
Duplicate of https://github.com/mapillary/mapillary_issues/issues/584

**Comment by pbb72** [comment]
Correct, this is a duplicate.
