### ISSUE TITLE
Allow interaction before photo is fully loaded

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#772]
When opening a new photo in the web interface, a low-quality version is loaded initially. This is very good, and gives a quick response.

However, it is impossible to do any further interaction with the webpage until the high quality version is fully loaded, which often takes between 2 and 10 seconds. Especially when there is also transition effects (morphing between photos) this can take a long time. During this time, it's impossible to quickly go to the next/previous photo, or click another location on the map. The navigation arrows are not even shown until the final image is loaded.

Please make interaction possible even before the photo is fully loaded.

**Comment by knikel** [comment]
We're using mapillary-js in the upcoming version of mapillary.com, this is not an issue anymore. Will close after we roll it out.
