### ISSUE TITLE
Can't go forward even if there is just a small gap

### ISSUE THREAD

**Issue by zdila** [mapillary/mapillary_issues#773]
At http://www.mapillary.com/map/im/EOPMrXg2D4DEpmahOoZ1VA, it is not possible to go forward even there is only small gap to the next sequence (created because of #765).

**Comment by Nakaner** [comment]
Mapillary misses a "sequence connector" feature at the moment. The should be the possibility in web editor to enter useful connections between two nearby sequences. 

Example: It should be possible to enter a jump connection between [this image](http://www.mapillary.com/map/im/NtXFcBg4Kz4UOpi8Z16VXg) and [this image](http://www.mapillary.com/map/im/7eC5TovXQv7FHXyPomncRA). Users often create more useful connections than programs (e.g. [if a tunnel and a overground road cross each other](http://www.mapillary.com/map/im/wUVSX_ept51VaKTQQxr1Ew)).

**Comment by nicolasrpmaia** [comment]
I often interrupt my sequences when walking around because of people getting in the way of the shot. Not only is it distracting for the final picture, but also a cause for concern for the person being photographed. Unfortunately, this also means I will have gaps between my sequences, and Mapillary can't deal with it yet.

IMO they should be automatically connected until a user flags it as a mistake.

**Comment by jesolem** [comment]
@nicolasrpmaia That's why we have the point down to pause feature in the apps. So that you can run automated capture but just point the phone down whenever there are people or other reasons to pause. No new sequence is created.

**Comment by pbb72** [comment]
In addition you can delete photos before uploading, or hide them after uploading.

But I agree with the original request anyway, it should be possible to continue where there is a small gap. What if you stop your sequence at some street corner, and another person creates a new sequence starting there? Those sequences should be linkable.

**Comment by jesolem** [comment]
@pbb72 Agree that it would be nice to be able to merge. 

The sequence continuation is there in the viewer, if you hit forward after a sequence ends it will continue on the next logical continuation. No need to hard link them in that case.

**Comment by filipca** [comment]
I have the impression that the continuations (connections) are not made before the first time the track is shown in the map.  Which is OK for me.  But it is confusing for those who do not know that.

**Comment by filipca** [comment]
I have found out that the end arrow and the begin arrow of the next track have to be in the same direction in order for the tracks to connect.  How could I have known that ? RTFM ?
Sorry for the many bad tracks.

**Comment by gyllen** [comment]
This will be solved in new viewer
