### ISSUE TITLE
App should take first picture in automatic modes even when speed=0

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#775]
Shooting only when speed > 0 prevents taking duplicates of the same frame. However that reason is not valid for the first picture. 

For practical reasons, when I start a new sequence waiting at a traffic light, the first picture can be taken already.

This also solves #769 for automatic shooting.

**Comment by jesolem** [comment]
Actually, this is the expected behavior. We wanted it this way ;)

**Comment by HolgerJeromin** [comment]
Can you explain the reasons? 
This way you loose the first meters of every sequence, till the device is at speed.

**Comment by peterneubauer** [comment]
Thinking about it, it seems reasonable to take one picture, then wait for the automatic to kick in. Reopening.

**Comment by HolgerJeromin** [comment]
Thanks. Did you forgot to reopen? :-)

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
