### ISSUE TITLE
Add a constant angle offset in web editor

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#776]
There are a lot of sequences in Mapillary which have wrong angle (assigned by compass) and are not taken in direction of travel. This applies usually for sequences from trains and busses (± 90° if taken throug side windows or 180° if taken to the back door). 

At the moment the web editor only allows to correct image angles so that they are 0° in direction of travel. If I want to correct all image angles of a sequence [like this one](http://www.mapillary.com/map/im/ia0rnmdlsXpZWblFiFJ_Hg), I have to correct each image manually (i.e. I won't do it). Please add a text field where I can enter a fix offset for the whole sequence. [This example](http://www.mapillary.com/map/im/ia0rnmdlsXpZWblFiFJ_Hg) would get an offset of 270° (from mathematical direction of rotation).

Sometimes a split of a sequence is necessary if one sequences has several parts with different rotation offsets to direction of movement.

**Comment by de-vries** [comment]
there already is a option fot that. Click on the "0":
![selectie_047](https://cloud.githubusercontent.com/assets/1449609/6483486/15610f3c-c272-11e4-946d-f28ec78f3a71.png)
set the number of degrees:
![selectie_048](https://cloud.githubusercontent.com/assets/1449609/6483521/4dbf60ea-c272-11e4-9994-64fc6f0d67f9.png)
Click approve, click correct angles

**Comment by pbb72** [comment]
This feature is not easy to discover, and it's not intuitive that you have to click the number to show the edit box. See also #734

**Comment by Nakaner** [comment]
Thank you @de-vries.

@pbb72 I agree. It should be visible as a text input field by default.

**Comment by knikel** [comment]
@angelday something to think about

**Comment by angelday** [comment]
The new changeset editor allows you to offset all photos in a sequence with a number (1), also normalize the sequence (eg. point all marker to the next, 2), and last, but not least, change individual markers to an arbitrary angle (3). This should address @Nakaner 's original issue, I'm closing, let me know if you have other concerns.

**Comment by pbb72** [comment]
@angelday, just a quick note that your point 3 only works for the initially selected photo. (See #2170.)
