### ISSUE TITLE
The app makes a lot of empty folders

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#778]
Just took a walk and this is the result:
![selectie_049](https://cloud.githubusercontent.com/assets/1449609/6487901/34dcbbf0-c294-11e4-85af-500bee041674.png)

I've seen this before. All empty folders get deleted when I upload.

**Comment by de-vries** [comment]
It's probably best to build in a check and remove them as it will always stay possible to manually create empty folders (by pressing repeatedly on new sequence)

**Comment by peterneubauer** [comment]
I'm doing that in the review activity fro the sequences, but added the cleaning now even upon leaving the camera. try https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk and report back!

**Comment by de-vries** [comment]
just made 1000 photo's, 11 sequences and no empty folders

**Comment by peterneubauer** [comment]
Then let's one it ☺
