### ISSUE TITLE
Sign for Traffic Light

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#779]
Well, traffic signs are a fantastic idea so...what about traffic lights? (not the traffic_sign of traffic light : the traffic_light itself) .It can be like an icon. What do you think?

**Comment by ybkuang** [comment]
Hi, @yopaseopor. Traffic light detection is on our list! Need some time to get to it though;)

**Comment by gerhardneuhold** [comment]
Thanks for your feedback @yopaseopor. We enabled detection of traffic lights in our semantic segmentation pipeline. 

Have a look here:
https://www.mapillary.com/app/?lat=48.093341051760035&lng=16.31415000000004&z=17&pKey=R9JddAQXwMnooeK_2Tqk_g&focus=photo&detections=true
