### ISSUE TITLE
Shutter sound should use headset when available

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#783]
The shutter sound is an important feedback that pictures are being taken, but it can also be a problem. Imagine me walking behind someone else's children while my phone is making camera shutter sounds every few seconds, or past a building with guards outside, or some kids doing less legal stuff. It could get me in all kinds of trouble.

So I plugged my headset in my phone, to have the shutter sound only to myself. But to my surprise the shutter sound keeps coming from the phone speakers!

The shutter sound should really be coming through the headset when that is plugged in. This is related to #671 and #463.

**Comment by peterneubauer** [comment]
This might be a device-specific or android bug, not sure Mapillary can do anything about it?

http://forums.androidcentral.com/samsung-galaxy-note-2/232158-headphones-notification-sound-still-coming-through-speakers.html

**Comment by mike1s** [comment]
It is possible to replase shutter sound by someone else, notification sound for example, if you got root.

http://4pda.ru/forum/index.php?showtopic=225904 ,sorry

**Comment by mike1s** [comment]
in English: http://forum.xda-developers.com/showthread.php?t=1349161
shutter sound filename Camera_click.ogg

**Comment by peterneubauer** [comment]
Well,
I think that's a bit over the top for the broad range of users. Not going
to do it, sorry.

**Comment by mike1s** [comment]
In worst case, several layers of the electricial insulation tape sticked on to ring speaker can significantly lower the sound.

**Comment by HolgerJeromin** [comment]
Setting the phone to silent mode is probable easier than hiding in tape :-)

**Comment by pbb72** [comment]
Yes, it may well be a "feature", since the standard camera app is also ignoring the headset for the shutter sound.

Of course, for silencing the shutter in Mapillary I don't nee tape or the phone settings. I can just uncheck "Make shutter sound" in the Mapillary settings. But all of these solutions go against my main problem, that I do need some sort of notification when a photo is being taken.

But would it be possible to let Mapillary use a notification sound instead of a shutter sound? (That would make this issue a duplicate of #463, I guess.) An optional short vibration would also be fantastic.

**Comment by mike1s** [comment]
Do not laugh at my advice! On some phones, as i know, the anti- pantsu :) protection is much stronger even against manipulations with these system files.

Vibration feedback +1. But should be kept in mind, that vibromotor affects on magnetometer.
