### ISSUE TITLE
Wrong "Improve this map" link to openstreetmap.org

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#784]
How to reproduce the problem:
1. Open map to explore, for example http://www.mapillary.com/map/im/CWhdWD-g3I-Nx1fB0DHvng
2. Switch layer to OSM via button in right top corner.
3.Check link in right bottom corner "Improve this map"
It has format http://www.openstreetmap.org/#lxbarth.i6fgdd0o/48.352696895599365/54.29126363317301/16
But openstreetmap doesn't support coordinates like this.
It should be like: http://www.openstreetmap.org/#map=16/54.2913/48.3527

**Comment by simonpoole** [comment]
I beleive that it is a mistake in any case. particularly given the audience of mapillary, to refer to a Mapbox internal page for such things, particularly considering that there is a perfectly good OSM page to link to that will take coordinates etc.: http://www.openstreetmap.org/fixthemap (I'm naturally slightly biased wrt to this issue).

**Comment by knikel** [comment]
The link is corrected as suggested by @Michael21011. Thanks for the feedback!
