### ISSUE TITLE
Progress counter in traffic sign game stuck at 0%

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#785]
In the past days the number of confirmed images in the European traffic sign game grew to over 1% (ATM 57762/5709454=1,01169%).

However the counter in the game still shows 0%. Are you maybe forgetting to multiply by 100 after dividing the two numbers :wink:? I would also recommend to show more (2 or 3) decimal places to encourage the players by showing the progress in more detail.

**Comment by gyllen** [comment]
Fixed

**Comment by floscher** [comment]
Thank you.

Could you please also add something like
```css
.traffic-game__stats__progress {
  background: #eff1f3;
}
```
to the CSS?

That would make the unfilled part of the progress bar visible.
