### ISSUE TITLE
Aspect ratio wrong

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#786]
Looking at http://www.mapillary.com/map/im/LU1uVkkC4ZvTT6A3WTL4rA the aspect ratio seems to be clearly wrong (FF 36.0.1).

**Comment by floscher** [comment]
Same as #553 and subset of #424.

In #424 I proposed a solution for this, the response was quite positive, but nothing changed since then:
![suggestion](https://cloud.githubusercontent.com/assets/3904348/4968906/a9136fd6-684f-11e4-9f85-0467dbec5497.png)

**Comment by gyllen** [comment]
Its not that simple unfortunately, if it was we would have deployed it by now, our new viewer (which we are working on now) will handle this though.

I tinkering with idea of disabling portrait photos though. For us its better with 2 landscape stacked on each other.

Sorry for the ugly aspect ratio, but please know we are working on it.

**Comment by floscher** [comment]
@gyllen thanks for the info, great to hear that there is a solution in the works

**Comment by simonpoole** [comment]
@gylen this is a completly normal non pano, non portrait picture generated with 08:15 mobile phone which had no issues at all with previous versions of the UI. If it isn't clear, in capitals: NEW PROBLEM!

**Comment by floscher** [comment]
@simonpoole your photo (https://d1cuyjsrcm0gby.cloudfront.net/LU1uVkkC4ZvTT6A3WTL4rA/thumb-1024.jpg) is widescreen (16:9), as is the image from #376 (https://d1cuyjsrcm0gby.cloudfront.net/47Wma1QpV4vVeB5DIYb3qA/thumb-1024.jpg).

Both widescreen and portrait images have the same problem, that they are stretched to fit the 4:3 viewer. That is the problem you describe, isn't it? Both #376 and #424 deal with it, #376 more with widescreen, #424 more with portrait images.

My image above uses a portrait image simply because I reused it from #424, it could've also been a widescreen image.

Note: In the first comment of this issue I first linked to #553. That was a typo, which I corrected to #376 while writing my previous comment on this issue.

**Comment by gyllen** [comment]
Np @floscher, all aspect ratios will be handling accordingly in new viewer.

**Comment by floscher** [comment]
@gyllen I am talking about the current viewer.

My last comment is an answer to @simonpoole and tries to explain, why the problem he described here is __currently__ affecting widescreen __and__ portrait images, therefore it is __not__ a new problem.

Sorry, if that wasn't clear enough.

**Comment by gyllen** [comment]
@floscher @simonpoole Bad response from my side actually deleted old one. @floscher is right this is not a problem with the images. Its the viewer that show them wrong.

However the app should not chose 16:9 solutions to upload. @peterneubauer are you aware of this?

**Comment by floscher** [comment]
That problem (app uploading 16/9 images) in turn is the same as #738 :wink:.

**Comment by simonpoole** [comment]
Given that this is fairly obviously a change of behaviour of the app, the relevant device info: Samsung Galaxy S5, Android 5.0 (lolipop). new app version.

**Comment by peterneubauer** [comment]
Can you send me a log when that happens so a can check the different
reported possible ratios?

**Comment by simonpoole** [comment]
@peterneubauer I've just sent the current log from the app. Note that since there is no way to review the log, I don't know if there is relevant info in it at this point in time. If not I'll send immediately after a sequence later today.

**Comment by peterneubauer** [comment]
In this one, there is a lot of processing of files going on. I'm not sure while the processing of images (really just the EXIF-writing and saving of the aquired image form the camera callback) is taking so much time, there is another issue about it.

Regarding the aspect ration - from the logs it seems there is no standard 4/3 size on your camera, so we choose the one with the biggest resolution.

Can you check the new build from https://dl.dropboxusercontent.com/u/5925006/mapillary/releases/app-release_current.apk, where I'm logging all sizes to see what we could do to choose a better one?

**Comment by peterneubauer** [comment]
This should be working now, closing it, part of the next release.
