### ISSUE TITLE
Blurring box drawn in wrong location

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#787]
In edit mode trying to blur the number plate in http://www.mapillary.com/map/im/LU1uVkkC4ZvTT6A3WTL4rA drawing a box around the number plate results in a box offset a couple of cm up. May be related to the previously reported issue with the aspect ratio.

**Comment by floscher** [comment]
Same as #553, #494, #389, #232 and #157.

**Comment by simonpoole** [comment]
@floscher note: orientation of the device was -not- portrait mode and previously blurring worked

**Comment by floscher** [comment]
The issue is caused by all non-standard (i.e. not 4:3) aspect ratios.

**Comment by floscher** [comment]
As a temporary solution the mapillary team could add the following CSS to the blur editor:
```css
img.b__canvas__image {
  width:800px;
  height:600px;
}
```

This would stretch the images, but the red rectangles would then appear exactly at the tip of your mouse for portrait,  widescreen and panorama images as well as for browser windows narrower than 800px.

**Comment by pyrog** [comment]
![request blurring](https://cloud.githubusercontent.com/assets/2158081/6917959/d92c7bda-d7a9-11e4-9252-2842dfde7dd5.png)
Find this one http://www.mapillary.com/map/b/9iVhaxdNN1t8y4rrYL-T-w
* The aspect ratio is correct for blurring but coordinates of the box are wrong
* In the traffic sign game, the aspect ratio is wrong but the signs are drawn at the good place

**Comment by ToeBee** [comment]
This is becoming an issue for me with video uploads. Since video is typically not 4:5, I can't blur any of my recent uploads. (just tried on this one: http://www.mapillary.com/map/im/523TaQYvA4kguwcPJCnfJA)

**Comment by pyrog** [comment]
Same problem with **panorama**
[![](https://d1cuyjsrcm0gby.cloudfront.net/iNh6o4CAVWSsrVxZJc9CKg/thumb-320.jpg)
iNh6o4CAVWSsrVxZJc9CKg](http://www.mapillary.com/map/b/iNh6o4CAVWSsrVxZJc9CKg)

**Comment by knikel** [comment]
@simonpoole, @ToeBee: Non 4:3 photo support has been addressed with the new viewer release. You can also blur directly in the viewer.
