### ISSUE TITLE
Re: Deleting Uploaded Images

### ISSUE THREAD

**Issue by dud1** [mapillary/mapillary_issues#789]
Is there any way to get images that have been uploaded deleted?  It is the first time I have used the Android App and it seems I have uploaded some images automatically rather than going through and reviewing them.  Most of them are of poor quality due to lighting conditions.

Thanks
Dudley

**Comment by filipca** [comment]
Yes, there is the little pencil icon under the image.  - hide this image - save and review changes - send change request.  
After a while you will learn to live with bad images.

Settings - Upload pictures in background.  
This seems checked by default.

**Comment by gyllen** [comment]
Thanks for answering this @filipca
