### ISSUE TITLE
Last 4-5 pictures are corrupted

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#791]
I think it's an app bug because this is happening to me after the last update of the app.Last 4-5 pictures of every track are corrupted, they are splitted, wrong, they are not loading in a good way, so I have to delete them.

**Comment by peterneubauer** [comment]
Is that with the Android app? Can you please send the log when that happens, got a link to a corrupted photo on the Web?

**Comment by yopaseopor** [comment]
Yes , it is with Android App. At http://www.mapillary.com/map/im/7VHmRgTpljen8A14hg2AKQ it seems like that. I don't have log about that time but I'll promise you some of that, I will do some test to log it because it is not the first time it happens that.

**Comment by metatraveller** [comment]
Some of my uploads are corrupted in a similar fashion, but I use Windows phone. Perhaps it is a server side issue? http://mapillary.com/map/im/4vylJFBSiF1ZYITHGP-r6g

**Comment by peterneubauer** [comment]
The best thing to verify that end be if you can make sure none of the
uploaded images is corrupt, e. G. Review before upload, and then spotting
them being corrupt I on the site.

**Comment by yopaseopor** [comment]
In my situation is not. Always I do a copy of the pictures I upload and they are corrupted then, before try to upload it (I syncro manually, with the option in review option)

**Comment by metatraveller** [comment]
In this particular series, I did save the photos on the phone before uploading and none of them were corrupted.

**Comment by yopaseopor** [comment]
Now I sent to Mapillary some logs with some app freezes.Data was not corrupt but at the end of the track, when I push the button, app is not working well
