### ISSUE TITLE
Why can't this photo be uploaded?

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#792]
Attached is a properly geotagged photo. Latitude, longtitude, stimestamp and orientation are specified. The uploader does not give any error message when selecting the image. But after choosing the file, it just says "0 of 0 images uploaded", with no images available, no map shown. Clicking "Upload to server" just makes that button gray and does nothing more.

Other images upload just fine. Something must be wrong with this photo, but I don't know what.

![77518826](https://cloud.githubusercontent.com/assets/1436366/6547784/965b77b2-c5e2-11e4-97dd-46ee1de2de0b.jpg)

**Comment by ybkuang** [comment]
Seems that the exif-parser don't recognize the date format of the image.
2012-07-27T14:35:39Z instead of 2012-07-27 14:35:39.

We will look for a fix.

**Comment by pbb72** [comment]
Wow, are dates stored as strings in EXIF? You learn something new every day :)

**Comment by ybkuang** [comment]
It should be working now.

**Comment by filipca** [comment]
I hope it understands also a millisecond.

**Comment by pbb72** [comment]
Upload work well now, thanks!
