### ISSUE TITLE
Manual upload: "Could not find valid EXIF Data" on file with valid EXIF

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#793]
I get "Could not find valid EXIF data" error message on http://www.mapillary.com/map/upload for this image:
https://www.dropbox.com/s/6u29b8epl06ife4/SAM_5986.JPG?dl=0

![image](https://cloud.githubusercontent.com/assets/24191/6560286/1108b620-c69a-11e4-91eb-22aa6a8322d7.png)

Exiftool shows that it contains EXIF:
https://gist.github.com/kolen/498636efd8a5fc749060

If this error means "image is missing some EXIF tag", error message should be more informative. This message says that there's no EXIF at all.

**Comment by gyllen** [comment]
Is this still an error? If so @ybkuang can you check image?

**Comment by kolen** [comment]
Tried again on this image (and whole sequence), it works now.

**Comment by jesolem** [comment]
Closing this then.
