### ISSUE TITLE
Manual upload - failed images issue

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#795]
FF 36.0.1

Currently roughly 10% of selected images will fail to upload, which in itself is naturally not good, however: the % uploaded display seems to ignore the failed uploads and will in some cases reach 100% even though a large number of images have failed. In this situation the "Push to server" button is disabled leading to no obvious way for the user to rectify the situation. Refreshing the browser window will break this deadlock, however at the expense of loosing the references to the failed images. 

The only way around this is to note the failed images manually before refreshing and adding them back afterwards, this typically multiple times (because the 10% failure rate applies to retries too).

While obviously the 10% failure rate is too high in any case, at least a button/whatever should be provided to retry the failed images.

**Comment by gyllen** [comment]
Hi @simonpoole thanks for reporting this. We are just at the moment rewriting the whole manual upload backend+frontend, hopefully things will be much clearer in the weeks to follow.

**Comment by gyllen** [comment]
As a work around for now. If you reload page and select all of the images that you uploaded before, the client will detect already uploaded images and ignore them for a second upload.

**Comment by SK53** [comment]
@gyllen I've been using this workaround for a while, but it gets tedious with a large number of issues. Otherwise I can just confirm @simonpoole's experience, but I already resize & reduce quality of images to get a cleaner uploading experience. I think the manual upload needs better progress feedback than the current % indicator: perhaps as a minimum show figures for current upload as well as for total number of images in the sequence being generated.

**Comment by richlv** [comment]
theoretically, the manual upload scripts could help. unfortunately, they suffer from an inability to retry in some cases (see issue #23), and there does not seem to be any way to continue an upload that fails with the scripts

**Comment by gyllen** [comment]
@SK53 @richlv @simonpoole Did new manual uploader solve any of these issues for you?

**Comment by richlv** [comment]
heya - i'm using upload_with_authentication.py, and git log does not seem to show any changes regarding retries to it. did i miss something ?

**Comment by simonpoole** [comment]
@gyllen I haven't manually uploaded for a while so my memory needs some jogging. iirc the behaviour, while not perfect, was substantially better. Unluckily I don't have a long sequence available right now the I could upload to test again, however I'll try and generate one in the next couple of days (the weather forecast is very good, so it should happen).

**Comment by gyllen** [comment]
@richlv If a script fails you can kill uploaded images from the web uploader.

**Comment by gyllen** [comment]
@simonpoole Excellent, let me know any feedback.

**Comment by richlv** [comment]
oh, sorry - i got a bit mixed up with all the issues. the script problems are tracked elsewhere :)

**Comment by gyllen** [comment]
@richlv np, thanks for taking the time to report

**Comment by gyllen** [comment]
closing
