### ISSUE TITLE
Manual upload - selecting a larger number of files crashes the browser

### ISSUE THREAD

**Issue by simonpoole** [mapillary/mapillary_issues#796]
FF 36.0.1

Selecting a larger number of images to upload will imediately crash the browser, something below 500 images seems to work 1500 definitely crashes.

**Comment by gyllen** [comment]
@simonpoole Yeah thats correct, its really a browser problem since the browser tries to hold 1500 images in memory. Really the only solution I think is to select images in batches.

**Comment by Stefal** [comment]
I think we really need a desktop app to send the pictures with : 
- speed limit
- sending resume

I still have a lot of pictures to send, but the web manual upload is a nightmare for me.

**Comment by gyllen** [comment]
@Stefal @simonpoole Have you guys tried the new uploader we have improved it a lot. I still like the idea of a native uploader though. I can see a couple of solutions

1. Add Dropbox/Megaupload integration
2. Add functionality to JOSM
3. Create standalone application

**Comment by simonpoole** [comment]
@gyllen it is a lot better now (this is on a current FF version), however from an UI pov I still think that simply sitting there and displaying 99.xx% and a spinner is not particularly good way to indicate that it has tried to upload all images but some have failed.
