### ISSUE TITLE
Enable mouse wheel as zoom control in blur edition mode

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#797]
Currently blur edition always goes in small window, no zoom allowed. 
Need zoom to view is text still readable where it should not be, and more accurate blur edition if should.

**Comment by knikel** [comment]
We'll be using mapillary-js for editing, you can check out how tagging (which is underlaying implementation of blurring) will work for example with panorama photos [here](http://blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html). Closing as this is already part of the stack we use for the upcoming mapillary.com
