### ISSUE TITLE
"Correct angles" works only for part of the sequence

### ISSUE THREAD

**Issue by abienvenu** [mapillary/mapillary_issues#798]
I use frequently the "Correct angles" feature to indicate that my photos are pointing forward (0°). Sometimes (maybe once out of ten), the correction happens only for the beginning of the sequence. Even if I wait for several days, or retry to request the change later, it will still fail at the same point.

Example : http://www.mapillary.com/map/im/TD6CM4-RAnQMbsQkQTF6IA
This image angle and the following have not been corrected, while the previous ones are ok.

Any idea about what is going wrong ?

**Comment by pbb72** [comment]
This could be related to #641, although I see your photos get an angle "-1", while mine get angles >360 (like 400). But the effect seems to be the same, the arrow is pointing north.

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by abienvenu** [comment]
I will give it a try...

**Comment by pbb72** [comment]
Yes, this still seems to be an issue.

A few days ago I rotated the whole sequence http://www.mapillary.com/map/s/L6oJfYQmZdYhqUBLDh5DSA to 0 degrees, but http://www.mapillary.com/map/e/8f_91ZoWNOJKbDjmZA5bNQ, http://www.mapillary.com/map/e/SXGVJBhG1vEJVCc8NSP3yw, and everything from http://www.mapillary.com/map/e/E2_qDYiLnGlxGGYv1sZrMQ onward is still on "-1".

This can also clearly be seen on the change set overview: http://www.mapillary.com/map/cs/V32BFBfF-xAIJljjFCgXTw

Please re-open the issue.

**Comment by gyllen** [comment]
Fixed in new editor (and new changeset backend)
