### ISSUE TITLE
Create a FAQ for users (and the rest)

### ISSUE THREAD

**Issue by CharlesNepote** [mapillary/mapillary_issues#799]
I'm quite sure that people are asking themselves many common questions about Mappillary and the ways to use it. Some examples:
* Can I take photos from a train?
* Can I take photos from a bus? Do I need to ask?
* Is it also interesting to take photos from the back of my car?
* Are there equipments to take photos by walk? by bike? by car?
* Is it also interesting to take one just a single picture instead of a set?
...

**Comment by jesolem** [comment]
We're looking at this. Probably a wiki solution as a user guide with details on everything. Including FAQ.

**Comment by mprins** [comment]
why not? https://github.com/mapillary/mapillary_issues/wiki

**Comment by jesolem** [comment]
@mprins That's what I'm thinking but maybe in a separate repo so that it is not "issues" ;) We also had suggestions for other platforms. Stay tuned.

**Comment by jesolem** [comment]
Closing. 
We have both FAQ on the Help page and a forum now.
