### ISSUE TITLE
App review order is wrong

### ISSUE THREAD

**Issue by nomoregrapes** [mapillary/mapillary_issues#800]
When reviewing photos on the (Android) app, the sequences appear to be ordered by "last modified" which is fine until you start deleting some photos in a sequence, they then seem to be out of order and it's difficult to know which ones you have checked. It would be better to order the sequence by "photo taken date/time" which could be the first of last photo on the sequence (it shouldn't make a difference as sequences don't overlap). I consider this a bug.

A feature enhancement would be great to allow the option to tick a sequence as "reviewed" so that can start uploading while you review other sequences. Or it could be used if you really want one sequence to upload without having to wait for others to upload first.

**Comment by filipca** [comment]
Are you aware of Settings - Review and Upload - Show/Upload newest features ?

I agree with you.

**Comment by nomoregrapes** [comment]
I was not aware of that, I just looked and it was ticked. I have unticked it in the hope that will show oldest first. However I think this confirms my issue is a bug with the App using a modified date rather than a taken/created date.

**Comment by peterneubauer** [comment]
Agreed on the ordering. Thing is, if we start ordering according to EXIF tag, the processing for sequences of 1000s of images will take considerable time. Another option would be to sort by filename?

**Comment by nomoregrapes** [comment]
You don't need to take the time of all photos in the sequence, just the
first photo & save it as the sequence time. Does that save processing?

On 10 March 2015 at 14:05, Peter Neubauer <notifications@github.com> wrote:

> Agreed on the ordering. Thing is, if we start ordering according to EXIF
> tag, the processing for sequences of 1000s of images will take considerable
> time. Another option would be to sort by filename?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/800#issuecomment-78059123>
> .
>



-- 
Gregory Marler
No More Grapes
07939 689 691
info@nomoregrapes.com
http://www.nomoregrapes.com

**Comment by HolgerJeromin** [comment]
the file time should be a source to sort.

**Comment by vincentdephily** [comment]
The sequence folders are named by timestamp of the sequence start on the SD card, that ought to be correct to sort.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest version of Mappillary Android application

**Comment by HolgerJeromin** [comment]
Yes it is. Thanks!
