### ISSUE TITLE
Resize photos to hide a car dashboard.

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#801]
I took a lot photos in car by action camera with wide angle objective.
I would like to crop all images to remove dashboard from photos and keep in frame only street, not my car parts.
As I know there is not such functionality in editor that is why I am planing to use python for it.

Could you list the allowable sizes or aspect ratio, which can be uploaded on Mapillary site?

**Comment by jesolem** [comment]
I really want to add cropping to the editor but I think that will take some time for us to build. 

If you are cropping yourself, please take the largest 4:3 aspect ratio. Make sure to preserve exif (Preview on Mac famously clears exif).

**Comment by Michael21011** [comment]
@jesolem, thank you for answer!
Unfortunately, the windshield is more like a 16:9 than 4:3
If it will give a wider area,  can I use it (16:9)? Will Mapillary show them correctly  without distortion?

**Comment by jesolem** [comment]
Currently our viewer scales to 4:3. That could be fixed one day ;)

Submit in the format you think gives the best data, keeping in mind that for some time the viewer will squeeze the photos on mapillary.com.

**Comment by gyllen** [comment]
Closing since answered
