### ISSUE TITLE
New roadsign initial size size

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#802]
New roadsign initial size size and placement now counts from image, zoom and viewport position ignored.

It should be placen on center of viewport and have same size, based on a viewport size or screen "real world" size.

**Comment by knikel** [comment]
@iav Thanks for the feedback. From now on we don't initially add a traffic sign to the canvas, but rather you start drawing it in the place where you want. So this is no longer na issue. Bear in mind that this is happening in the new updated viewer. The game will catch up to that same behavior soon.
