### ISSUE TITLE
Ideas for accepting photos with bad/no GPS reception

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#803]
I mostly do city mapping, and it's clear there are some (narrow) streets where it is very hard or even impossible to get a proper GPS signal.

To map these, I would have to manually take photos, geotag them on my computer, and then do a manual upload on the website. This is a shame, because the Mapillary website actually has one of the easiest tools for properly geotagging photos.

So I would like to give some suggestions for solutions where badly geotagged photos could be accepted anyway:

1. Upload these photos, but hide them by default. This requires bug #652 to be fixed. Then the uploader can later choose to properly position these photos. If they don't, then there is no change to the current situation; badly positioned photos won't show up for the public. (I'm not sure if the GPS precision is stored in the EXIF information by default, elsewise maybe the Mapillary app has to store that information somewhere else.)

2. Use the last (or next) know good GPS position. This would cause a stack of photos on the same identical location when the GPS signal is lost. I've noticed my phone (Samsung Galaxy S3) already does this itself in some situation, especially at the beginning of sequences where I sometimes find the first 3-4 photos at the exact same position. Optionally, the uploader could hide subsequent images with identical GPS positions, allowing the editor to properly position them afterwards like in the first suggestion.

3. Spread out photos with bad GPS information in between the last and next known good positions, based on their time stamps. The app might even want to continue looking for a GPS reception after the last photo has been taken, if the last one did not have a good reception.

The quality of these "guessed" locations could be improved, for example by only doing this for short distances, or by using the OSM road information for enhanced positioning. (For example in tunnels that aren't straight.)

**Comment by kayD** [comment]
Somewhat related to #213

**Comment by filipca** [comment]
Have a look at how much my tracks in Brussels have improved since I wear a Garmin Glo double GPS receiver under my hat.  That is since 9 march 2015.

**Comment by filipca** [comment]
Thanks to #213 I now know that we can correct the locations of the photos in M..
So I might start doing that for Brussels.

**Comment by pbb72** [comment]
I see now that much of this is already discussed in #81

**Comment by jesolem** [comment]
Keeping #81 , closing this.
