### ISSUE TITLE
Y U NO Panorama?

### ISSUE THREAD

**Issue by kayD** [mapillary/mapillary_issues#804]
I enjoy panorama shooting a lot. (My first spherical panorama is from July 2001 digitized from negatives :triumph: )

However, most of my mapillary panoramas - although shot in panorama mode - are not stitched:
* https://www.mapillary.com/map/im/xkEWwV3yhM8UA3WZCW-glQ
* https://www.mapillary.com/map/im/mVSXI3juybDmffphG_iNbg
* https://www.mapillary.com/map/im/rI58qfaUX6LrLCUuX5gf4A

There is enough overlap, sufficient exposure similarity, so ლ(ಠ益ಠლ) why are they not stitched?

**Comment by ybkuang** [comment]
Hi @kayD. Right now, if you press the '-' button on the top-right corner, you can see a stitched version of the images for your sequences. 

We are currently working on a new version of the viewer so that panorama will be presented in a proper way.

**Comment by kayD** [comment]
Hi,

Sorry I don't get it. Klicking '-' in the rightmost top certainly unzooms the map, klicking on '-' in the image view area one, I get these results (tested in 4 browsers):

![yuno-all](https://cloud.githubusercontent.com/assets/316554/6617120/90a6e3ee-c8b5-11e4-9c52-cd57dc2df641.png)

TL: Vivaldi, TR: Chrome, BL: Firefox 33, BR: Opera 12

In all of them I don't see a stitched image, but nicely perspectively arranged individual images.

**Comment by ybkuang** [comment]
@kayD Sorry for confusion. You are right. The images are current not stitched into a single image. One of our goals is to enhance the viewer so that you can get similar experience as a single panorama.

**Comment by kayD** [comment]
I thought the very goal was that the images would be stitched. And one of my panoramas _has_ been stitched properly:
http://www.mapillary.com/map/im/Gvq_cX66mqv4egoSrpflgQ
(Please note the "Panorama" button below the image.)
So how come THIS panorama has been stitched, and the afforementioned ones have not? What is the difference?

**Comment by gyllen** [comment]
@kayD The nicely stitched one was an experiment which we probably will bring back. Right now we are not looking at it actively though. We are spending all our resources on getting this http://blog.mapillary.com/update/2014/12/15/sfm-preview.html up and running for the whole planet.

**Comment by kayD** [comment]
Hello Yubin and Johan. Great! As probably the whole world, cannot wait for this :smile: 
However, the panoramas have IMHO their own right of existence, as they are semantically not a set of pictures, but one (only shot using multiple exposures due to limitation of optics). As this they show a scene at one point in time, one wheather condition, etc. So they should be available in a stitched form. It is quite a different (not better or worse) experience than the SFM project.
Thanks for the explanation and I know that there's always too little development time available.

**Comment by kaitu** [comment]
Thanks @kayD for linking a properly stitched panorama (it looks great) and @gyllen for explaining why I had so far searched for the "Panorama" button in vain.
The stitchet panorama looks great, I hope you'll find resources to bring back the feature. Maybe, should the computational power be the problem, insteat of a precomputation you could offer it on demand for single shots?

**Comment by pyrog** [comment]
This one have the panorama button. Great job :smile: 
http://www.mapillary.com/map/im/TS9JnSDu-L8H_H4qyvuJfw

**Comment by jesolem** [comment]
Hi everyone
Is there anything remaining to be fixed here or can we close this issue?

**Comment by pyrog** [comment]
> can we close this issue?

Unfortunately no.
We will waiting the stitched panorama feature will be "soon" in production :smile:

**Comment by gyllen** [comment]
@paulinus Would we be able to achive this effect in new gl viewer without stitching the images?

**Comment by nighto** [comment]
Now that the panorama function is live (as per blog.mapillary.com/update/2014/09/10/support-for-pano.html), the images get updated automatically, or should the user upload them again?

**Comment by paulinus** [comment]
With the current SfM pipeline, we support standard images, and panoramic images created by the camera itself.

Currently, we have do not generate panoramic images out of standard images taken in panorama mode. We instead display the original images and transitions between them. We can improve the navigation between these images, but we don't plan to generate the stitched panorama at the moment.
