### ISSUE TITLE
Filter everything but user sequences on the user profile

### ISSUE THREAD

**Issue by SK53** [mapillary/mapillary_issues#805]
I find the recent activity view rather fun, but it would also be nice to be able to pick out newly added sequences on maps. My suggestion is to make new sequences a different colour (perhaps a paler blue) and then progressively age them to the standard colour. In the first instance this could perhaps just be done on the sequences new this week.

**Comment by rudolfmayer** [comment]
In addition to colour coding, one enhancement would be to allow filtering by image date, with some presets like "last week", "last month", and maybe one more detailed filter where you can specify exact date ranges.

**Comment by HolgerJeromin** [comment]
you know the filtering (look at the button on the left bottom) on the main map?

**Comment by rudolfmayer** [comment]
Obviously I didn't :-) so you can trash my comment....

**Comment by SK53** [comment]
@jesolem wonder why this was closed so smartly, it's merely an enhancement suggestion & it is **NOT** the same as filtering by date (as per @rudolfmayer). The idea is that by showing newly added sequences on the map view there well be more user engagement, more return visits (is there new stuff in my area, new stuff I can use in OpenStreetMap etc). AFAIK this is not covered by any other Issue.

**Comment by rudolfmayer** [comment]
I agree, this should not be closed, it is different from filtering

**Comment by jesolem** [comment]
My bad. Just read the last comments and thought problem solved.

**Comment by jesolem** [comment]
You can see your own contributions, filter by user and time. Is there still something needed?

**Comment by rudolfmayer** [comment]
I think the initial idea by @SK53 was to make the lines of different colour, to visually differentiate new and older traces.
I like that idea, and think filtering is complementary, but not replacing it.

**Comment by jesolem** [comment]
@rudolfmayer @SK53 Did you see this demo http://blog.mapillary.com/update/2015/08/04/tangram.html ?

Here lines are colored based time. We could do a version with a gradient. Would that work? Just trying to get your feedback before we consider playing with the styling. ping @knikel

**Comment by rudolfmayer** [comment]
I think this would be great with a gradient!

**Comment by knikel** [comment]
We'll have it in the profile views in the upcoming update of mapillary.com. Will close this when we roll it out. @angelday is deciding the colours of the highlighted sequence as we speak 😉

**Comment by angelday** [comment]
It is out, closing.
