### ISSUE TITLE
More detailed lists on traffic signs

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#806]
The traffic sign recognition is great, but I'd like to correct some of the recognised signs. Specifically, the recognition found many signs for my user (http://www.mapillary.com/profile/rudolfmayer/ors) where it claims they are from the US - but I never mapped there...
So, what would be handy to correct (at least some of them) is if I could click on a certain type of sign, and then see a list with links where they actually are located, so I could easily find and edit them.

(Btw, it would be great if you could use such information from corrected signs to improve your recognition algorithms :-))

**Comment by gyllen** [comment]
@rudolfmayer us is a bit misleading its just the type of detector, the signs detected is actually from your Australian trip ;), we already do use GPS do only process some parts of the worls
