### ISSUE TITLE
Possibility to choise direction in android application

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#812]
Is it possible to add a setting to Mapillary android application with angle of direction? Now there is only "forward". 
I dream to install 4 smartphones into car to film forward, backward, left and right directions at the same time.
Also to view addresses of houses (to improve openstreetmap) 45 degree will useful.

What do you think?

**Comment by kaitu** [comment]
This is related to #115

**Comment by peterneubauer** [comment]
Can do in the App, mostly a matter of UX. How to choose the locking angle in a good manner, and should we reset to 0 if starting over in order to avoid wrong tilts by mistake? /cc @knikel

**Comment by Michael21011** [comment]
@peterneubauer, I think in quick panel you should save current two base option ("Using phone compass" and "Compass locked forward") to avoid errors for most people.
And in settings under CAMERA section you could add new row ("Lock direction with custom angle"), this row will open a dialog with an input for value.
If custom angle is selected then  we will see label "Compas locked {0} andle" in quick settings on button and you could replace color of icon in icon bar to orange instead of white.

I think reset to 0 after starting a new sequence is inappropriate, because phone lost gps signal during session and start new sequence automatically. But it could be useful to see warning when user enters to shooting mode from main activity of application.

Also it will useful to have possibility to change the angle for a sequence in "Review" before uploading photos to server.

**Comment by polarbearing** [comment]
I did some sequences with 30 or 45 deg side turn, and this makes the images more meaningful, and exposure more stable, since you have less sky in the frame. Just asking for changesets is cumbersome, thus the option in this issue, to correct angles before download, is much needed.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
