### ISSUE TITLE
Web ui unusable on a screens with low height

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#813]
Web-developers, please, buy on ebay any netbook with 768 pixels on heigh screen, or just set a virtual machine with same screen size. Then set up windows and firefox or chrome browser - but not enter into "full screen mode", and don't remove from screen systemm ui - taskbar, window titles etc. Just don't do any "geek-style UI customizations".

And try to do something but "just browsing". Try to inspect signs, to edit blurs, to view proto info or related photos.

Repeat all above having fonts in browser increased to +2 from default.

Just try, please.

**Comment by filipca** [comment]
A couple of printscreens can tell a thousand words.

**Comment by iav** [comment]
![2015-03-17 02_06_16-greenshot](https://cloud.githubusercontent.com/assets/325961/6679357/299d245e-cc4f-11e4-9b6a-6c66b0c5f905.png)
1. How to login? Where "Login" button? We need to scroll, scroll down.
![2015-03-17 02_06_46-greenshot](https://cloud.githubusercontent.com/assets/325961/6679370/6cf3741a-cc4f-11e4-9400-6df9f4320a2f.png)
Got it. Now press login, and nothing. Where login form? nowhere.
Maybe, try to  scroll back up - it's easy to think, because previously we scroll down - just reverse it:
![2015-03-17 02_07_07-greenshot](https://cloud.githubusercontent.com/assets/325961/6679399/c4da205c-cc4f-11e4-953b-4b63e68da91b.png)
Got it! It was easy, right? And so interesting, much better than just see login, clik, enter password, and be autenticated, sure.
![2015-03-17 02_08_03-greenshot](https://cloud.githubusercontent.com/assets/325961/6679432/34a70ad0-cc50-11e4-9d05-3764cb027ab8.png)
But where we are, what is it?
Looks like there are some ower left border, but how to go there? no scroll°bars, no drag...
Hm.
No  way?
O! Remember, some times ago we clock 3 horisontel bars? Try to press it again... 
![2015-03-17 02_08_21-greenshot](https://cloud.githubusercontent.com/assets/325961/6679447/78cff082-cc50-11e4-87d8-79637dc7f86c.png)
Victory, definitely! It was not so easy, but now we are there!
![2015-03-17 02_09_08-greenshot](https://cloud.githubusercontent.com/assets/325961/6679467/9a5807c6-cc50-11e4-9f4d-d28a596f7a6e.png)
Now it's time to browse my neighborhood.
What to do peoble who no interested in Germany, Sweden, Brazil, United States, Italy, Poland - I still don't know, really. I can pan to my yard, but can't select tracks or photos there.

It's no joke or irony - I realy nave no clue how to go to track or sign edit mode not from my uploads inside my profile.
Ok, I go to browse from my profile
![2015-03-17 02_14_46-greenshot](https://cloud.githubusercontent.com/assets/325961/6679518/260b64c0-cc51-11e4-9fa1-5b27c2941fb5.png)
Yes, i understand - my netbook have not large screen. But you can see how tiny % of my tiny screen used for photo? 
Want to see related photos, or info? forget.
Want to run sequence? Edit, or smth? 
Forget!  There no place for it.
Scrollbars? What are yuu talking about.
Better look to this nice black bar on top! To that white bar with search field, so need on every edition, much more usable that any edit controls, and can't be placed somewhere not concurent for space with content...
![2015-03-17 03_02_37-greenshot](https://cloud.githubusercontent.com/assets/325961/6679595/7da4359e-cc52-11e4-9b9f-1eef37bfc5a4.png)
![2015-03-17 02_17_22-greenshot](https://cloud.githubusercontent.com/assets/325961/6679596/8274606c-cc52-11e4-9fe0-b94822c59276.png)
ttry to enter some sign... How to exit from selection without choosing? How to choose "none of that"? 
Maybe, there should be some more signs? 
scrollbars? Scrollbars are for old farts, anybody knows. Use some free space upper and on left and righ? No, just let him use chromebook-17"-retina!

no macbook retina - mapillary don't need losers.
Yes, I understand.
Sorry for disturbance.

**Comment by jesolem** [comment]
@iav Although I understand your frustration that our service is not giving you a great experience on your hardware, I don't understand your tone. Why the aggressive language?

A little perspective: we are a team of 6 building a service that you get to use for free. We are doing this on a shoestring budget and we're all working many more hours than considered healthy. Our front-end web person who is brilliant by any standard is working part time while he's finishing his thesis. 

Think about this next time you consider filing a bug with "humorous" insults. We don't appreciate it.
