### ISSUE TITLE
Need pausing on pitch angle to

### ISSUE THREAD

**Issue by mike1s** [mapillary/mapillary_issues#814]
While hands- free shooting, it is easy not to catch inclination in this direction. Thus, a lot of interesting objects are goes out from field of view, and it is totaly impassible to imagine environment using such photos.

//I speak English very bad. Please, try to read my mind

**Comment by peterneubauer** [comment]
@mike1s is this in the Android app? You can disable the Pausing on pointing down in the Settings of the app.

**Comment by mike1s** [comment]
Yes, Android. Pausing on pointing down works well, thanks. But I talking about opposite case, not to disable pausing, but to enable with highest requirement to horisontality of the optical axis to the horizon, because of uselessness of these photos, that are not coveres at least horizon. Pausing on pointing down now enables blocking from about 45deg from horison. With phone's vFOVs about 40deg, there will be only asphalt on picture. It is easy to accidentally tilt phone in this direction, for example, when phone is hanged to rucksac's strap and I get up to upright position on bike, or if I holding the phone in hand on belt- level, not looking at display. Whith such feature, I could notice absence of shutter sound and correct phone's orientation, and not to overview all images in order to delete useless ones.

I proposes feature like already existing "max tilt", but about pitch angle, in adition to existing roll angle.

**Comment by kaitu** [comment]
I didn't dare to ask for yet another setting. But when I think of all the picture I accidentally shoot at my own feet, I like the idea of experimenting with a configurable max pitch angle setting.

**Comment by mike1s** [comment]
Even in Apple- like approach, the setting in menu may not be, but blocking function should be, for the purpose of data quality without handwork. But it'l be better, if there will be such regulator, 10...30deg from horizon, i think so.

**Comment by jesolem** [comment]
There is pause on pointing down, you can manually turn it off, is there anything @peterneubauer needs to do here? (spring cleaning issues)

**Comment by peterneubauer** [comment]
closing this. Please let us know if this is still relevant @mike1s
