### ISSUE TITLE
Notification email issues 

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#816]
This is a series of general issues with the various notification emails

**The "Uploads in your country" email**
1. Don't send me notification of my own uploads. I know I've uploaded. 
2. If other people upload in a watched country or region, tell me who they are with links to their profile pages and/or the sequences. 

**Mentioned in a comment email**

The "Comment back" link sends me to the mapillary site but the page does not load making it impossible to comment back directly

**Comment by gyllen** [comment]
@sandrauddback How can we approve this email with better info?

**Comment by rudolfmayer** [comment]
I agree with notifications on your own uploads, that should be stopped.

I think what would be good to have
- Tell how many (and link to the first N) sequences, and show them, like you do for the images now (this could even replace the images, as there are probably anyhow too many that can be displayed!
- Tell the list of users involved, as suggested by @DaCor1

**Comment by sandrauddback** [comment]
Closing this as we do not anymore send these notifications.
