### ISSUE TITLE
Android app v1.20 crashing randomly

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#817]
The newest version of the app has some nice features however it is very unstable. Some examples:

1. Started the app after installing and modified some settings (pause delay to 1 second, tilt angle to 30 degrees, focus to infinity). Switched to photo mode and started a new sequence. Every 2 second got an error on the screen instead of photo being taken
2. Put all settings back to normal, taking photos fine then app crashes for no obvious reason

I've sent logs hoping it might help with the random crashes

This is with a HTC One M8

**Comment by peterneubauer** [comment]
@DaCor1 is this still and issue with the latest versions? Otherwise, I would close it.

**Comment by DaCor1** [comment]
Go ahead and close. It's been a long time since this has happened.

It only occurred on one particular phone, so it's most likely specific to
that device
