### ISSUE TITLE
Sequence review, make it easier to do

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#818]
Sometimes when I go to review sequences either by myself or others, its impossible to know where to start and how to tell whats been reviewed. 

Is it possible, on the profile pages, to give an option to review sequences as a simple list and include some option to flag whether or not the sequence has been reviewed in full. 

As sequences build up and you start getting overlapping sequences its getting more and more difficult to see whats reviewed and whats not.

**Comment by filipca** [comment]
Don't forget that M wants to do important things by combining the pictures.

**Comment by DaCor1** [comment]
Which makes the review process all that more important

I dont mind doing the reviewing, its just I don't know where to start and
how to prevent myself going over the same images multiple times

**Comment by voschix** [comment]
I support this proposal. I have many smallish sequences, and I would like to see in particular two features:
a) a flag that tells me that Mapillary has finished all its automatic business (I have sequences sitting there where even after eight days there is still the odd photo not finished)
b) I would like to be able to tag a sequence as inspected by myself

**Comment by rudolfmayer** [comment]
I would also like to have this feature, with
c.) being able to filter sequences depending on the status

**Comment by de-vries** [comment]
similar discussion in #211

**Comment by knikel** [comment]
@angelday good feedback to consider

**Comment by angelday** [comment]
We are currently finishing up / piloting the changeset editor approve functionality within Mapillary. This will exactly do this:

- allows to look through all changesets in a feed-like format
- allows to navigate on the map, see your favorite areas and make approvals in-line

@DaCor1 it will answer your original question, in the mean time I'll leave this ticket open until we release it to the general public.

**Comment by angelday** [comment]
This has been released, closing.
