### ISSUE TITLE
Enable volume button to take photo when stopped driving

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#819]
When driving, I can pull up in front of something, it would be good to be able to take a snapshot once the car has stopped moving. the volume keys, when driving, only seem to work when in motion

Also, a slightly separate issue, if you press the volume keys as the app is about to take a photo, the app will crash

**Comment by filipca** [comment]
Quite right and you are not the first to ask it.
I have an example of it :
http://www.mapillary.com/map/im/0RNT9N_EjraRTzFUQrq1FQ
I had to push my bike up the hill, but now no one can see it.

**Comment by iav** [comment]
Trying to press volume button when stop on a good view - but got "too slow" banner.
Pressing volume button means "I know there will be a good shot".

**Comment by jesolem** [comment]
Android or iOS?

**Comment by DaCor1** [comment]
I'm on Android

**Comment by peterneubauer** [comment]
This should be working.
