### ISSUE TITLE
Manual Input if exif data is missing

### ISSUE THREAD

**Issue by fuddl** [mapillary/mapillary_issues#82]
The website does not accept manually uploaded pictures if they don't have all the necessary exif data:

![exif missing](https://cloud.githubusercontent.com/assets/842548/2708220/b9e6cadc-c4a9-11e3-9a28-b56c425b6bf5.png)

Maybe I should be able to manually enter this information into a form (e.g: pick the location on a map)

I'd provide a lot of old pictures this way..

**Comment by gyllen** [comment]
This should be included in manual upload version 2

**Comment by gyllen** [comment]
Fixed in new editor
