### ISSUE TITLE
Add the OpenCycleMap layer

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#820]
Would it be possible for you to add the OpenCycleMap style as an option, as I'm often looking for images along cycle routes?

@gravitystorm is the owner of the cycle map style and hosting.

**Comment by voschix** [comment]
I second this proposal.

**Comment by HolgerJeromin** [comment]
Quite similar to #347
Opencyclemap has a quite easy tile usage policy. 

The new manual upload preview map has only mapbox and no osm default style. Perhaps there are more small maps on your site which has only mapbox maps. The osm default style renders for example beaches which could be helpful for positioning.

**Comment by knikel** [comment]
We'll be relying on basemaps from Mapbox. Labelling as a feature request for further consideration

**Comment by knikel** [comment]
We've decided not to add any external layers to maps for the time being.
