### ISSUE TITLE
App stops when coming in reach of open WiFi

### ISSUE THREAD

**Issue by sanderd17** [mapillary/mapillary_issues#821]
Our town library has a WiFi network that's open, but requires separate login on a local webpage to connect to the internet.

So when I drive past the library, my phone sees the network, connects to the WiFi network, and shows that login webpage. This probably causes a context switch in Android, and stops the recording sequence.

I had it "crash" a few times when I drove near the library, until I realised that the library could be the actual cause of the problem.

I think it would be great if Mapillary could keep recording even when it's pushed to the background.

**Comment by filipca** [comment]
I had that problem with Fon.  I found a setting for it.

**Comment by jesolem** [comment]
I think there was a fix for "capture portals" that solved this. You still have the problem?

**Comment by sanderd17** [comment]
I haven't been riding in the city lately (and when I did, I disabled WiFi), so it's possible that this has been fixed.

**Comment by peterneubauer** [comment]
Let us know if you encounter this again!

**Comment by peterneubauer** [comment]
Closing this for now, happy to reopen if the bug reappears.
