### ISSUE TITLE
Android app crashes due to incoming calls 

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#822]
Using android version 1.20 on HTC one M8

**Comment by peterneubauer** [comment]
Any chance send a log on this? I can call you to trigger it :)

**Comment by DaCor1** [comment]
Lol, no problem, I can get someone to call me. Will send the logs asap

Any chance send a log on this? I can call you to trigger it :)

—
Reply to this email directly or view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/822#issuecomment-82201270>
.

**Comment by DaCor1** [comment]
Sent logs with 1 crash from an incoming call. It should also show another
incoming call with no crash

**Comment by peterneubauer** [comment]
Just tested it with the latest code and couldn't trigger crash, just stopping of the active sequence, which is expected. Test again with the latest alphas and reopen if it happens again, preferrably with log.
