### ISSUE TITLE
Re: Manual Upload Methods

### ISSUE THREAD

**Issue by dud1** [mapillary/mapillary_issues#823]
Is there a recommended approach to this as it seems to be very slow compared to sending images via the phone app?  i.e. when sending 200 images are you better sending 10 lots of 20 images or even 20 lots of 10 images or does it make now difference.

Would I be better trying to use the python tool to upload images and avoid the browser?  i.e. is it any faster?

Many thanks for any advice in advance.

Dudley

**Comment by gyllen** [comment]
@dud1 If you are on wireless I would say sending images from your phone is a fast as uploading from your computer. However if you are a bit more on the techy side you might want to tryout our upload script https://github.com/mapillary/mapillary_tools

**Comment by dud1** [comment]
Thanks for the comment.  Not long after my posting the manual upload was upgraded.  It is now much improved (more robust and faster) so it would seem that the browser may not have been the problem.   

Dudley
