### ISSUE TITLE
Connections tab on user profile has user names under the wrong image

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#824]
On http://www.mapillary.com/profile/smsm1/connections the usernames under each image, are swapped. Clicking the image reveals the correct username.

![mapillary___smsm1_s_profile](https://cloud.githubusercontent.com/assets/82719/6678493/4b783d6e-cc33-11e4-99c3-ddaea5d538aa.png)

**Comment by peterneubauer** [comment]
This is a processing bug, fixed for future data, will be corrected soon for existing data. Thanks for reporting!
