### ISSUE TITLE
"My Uploads" page doesn't show any useful information

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#825]
I have a lot of trouble navigating between sets of uploads on the "My Uploads" page because it just shows thumbnails with no context.

Suggestions:

* Show the date for each sequence
* Make clear which way it's sorted - oldest first or newest? I always forget and fumble around
* Show a reverse geocoded location, like a suburb or street name, maybe for the start and end points.
* Show something clearer than the eyeball symbol with the number next to it. I still have no idea what this means - I intuitively think it's the number of photos in the sequence but it can't be that.
* The grey GPX box is very unintuitive - it seems to imply that there is an associated GPX file with the images (like I uploaded a GPX file and images and Mapillary combined them) but that's nonsense. I imagine it's just providing a link to download a generated GPX file, but this UI isn't great - a hover-only link with a download icon would be much more understandable.

**Comment by ToeBee** [comment]
I believe a reverse geocoded location is shown on hover, if a reverse geocode is successful. I see something like "14th Street, Ogden" on sequences that start in a city. For ones that start out in the country there is nothing though.

The eye symbol is a view counter. I'm not sure if it counts how many times the sequence has been viewed or if each image view within the sequence counts. But either way, I agree it isn't exactly intuitive. The main reason I know this is because of this tweet: https://twitter.com/mapillary/status/563113907645341696

**Comment by stevage** [comment]
Thanks. Weirdly, none of the imagery I uploaded before yesterday has a reverse geocode (and they're almost all in the city), yet a few since then do. http://www.mapillary.com/profile/stevage

For me, the view counter is much less valuable than some of the other things I mentioned.

**Comment by richlv** [comment]
* amount of images would be useful, too (maybe even more useful  than view count :) )

**Comment by de-vries** [comment]
Also, leave out the user name. All sequences on `mapillary.com/profile/<user_name>/uploads` are uploaded by `<user_name>`, so no need to mention that on every sequence.

**Comment by HolgerJeromin** [comment]
A small break, new row or horizontal line after each new week would probably useful, too.

**Comment by knikel** [comment]
@angelday great feedback on profile page

**Comment by angelday** [comment]
@stevage since we released the new profile pages (this is yours: https://www.mapillary.com/app/user/stevage ), this has gotten an overhaul and I think it answers your concerns. I'm closing this, let me know if you have more concerns.
