### ISSUE TITLE
Website not usable after clicking on a "private" sequence

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#826]
I cannot open any sequence by clicking on its blue line after clicking on a "private" sequence ([example](http://www.mapillary.com/map/im/jgRruq2H1IJROOJLddKk4A)) and getting the [error message](https://cloud.githubusercontent.com/assets/3611273/6685055/f2d249e8-cc96-11e4-8ee2-83d705add257.png).

This bug occurs both in Firefox and Chromium.

**Comment by gyllen** [comment]
Can you get out of it?

**Comment by Nakaner** [comment]
If I click at the Mapillary icon and afterwards on "Explore Germany", I can see the map as usual.

**Comment by gyllen** [comment]
@Nakaner Open your browsers terminal and run localStorage.clear() , sorry for this you should not be able to switch to a blank project

**Comment by Nakaner** [comment]
It does not work. I get `undefined`

**Comment by knikel** [comment]
@Nakaner I think what @gyllen meant is that in case you have been stuck in a blank project (and your toolbar turned green) this command would log you out to and fix this erroneous situation, but as you said after clicking on the logo/going to other view you can see map as usual.

I'm looking into this situation, as you were supposed to see a modal that this sequence have been hidden/not in your projects - given you're logged in.

**Comment by knikel** [comment]
@Nakaner I am looking into this and have a question, when this happened to you did you see a modal stating that this sequence might be hidden/deleted/private?

**Comment by Nakaner** [comment]
The bug still exists. If I open mapillary.com, log myself in, go to the map and click on a private sequence, nothing happens (i.e. no image appears). If I click at a public sequences, nothing happens, too. If I click at a public sequence before I have ever clicked at a private one, the image(s) of the public sequence appear.

**Comment by knikel** [comment]
Closing in favour of #345. Will be fixed soon.
