### ISSUE TITLE
Website empty after opening a private sequence

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#827]
If I am logged in and open a private sequence, I get an almost empty (no map, no images) website. 

![mapillary-empty](https://cloud.githubusercontent.com/assets/3611273/6685064/03eb1494-cc97-11e4-89c8-ce2cd2f3d25d.png)

**Comment by knikel** [comment]
This has been fixed now. People will be redirected out of hidden, deleted or 'not in their project' sequences.
