### ISSUE TITLE
Preachy browser update message

### ISSUE THREAD

**Issue by systemed** [mapillary/mapillary_issues#828]
"This website would like to remind you: Your browser (Chrome 38) is out of date. Update your browser for more security, comfort and the best experience on this site."

Chrome 38 was released in October, only five months ago. Showing this preachy bright yellow warning is really not a great welcome to Mapillary.

**Comment by knikel** [comment]
Thanks @systemed for mentioning that, the message you're seeing comes from browser-update.org and by default it gets displayed for Chrome browsers which are 3 or more releases behind the current version (41). After dismissing it, you won't see the message again. It will be fixed to respect more that 3 Chrome releases behind. Thanks.
