### ISSUE TITLE
Manual upload stuck at 99%

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#829]
I keep getting this kind of thing:

![screenshot 2015-03-18 11 17 33](https://cloud.githubusercontent.com/assets/678344/6700314/8eaa7e5c-cd60-11e4-9396-1bcb5cf68a30.png)

When it gets to the last few images, the "Upload to server" button becomes re-enabled (as in the screenshot), and the "push to Mapillary" button never appears.

I'm guessing it's something to do with an aborted upload I did earlier: I started uploading a few images, then realised the GPS coords weren't quite right so I aborted it. I haven't been able to upload those images since.

Weirdly it still seems to be doing something and actually dips below 99% sometimes:

![screenshot 2015-03-18 11 20 24](https://cloud.githubusercontent.com/assets/678344/6700342/cdde4cde-cd60-11e4-9870-0fa8706ecf89.png)

**Comment by gyllen** [comment]
We will deploy new upload site in a couple of days. We are at the moment working hard to get it out. In the meantime, just reload page and you should be fine.

Pro tip if one image is missing you can select all of the old ones. Uploaded images will not be uploaded again.

**Comment by stevage** [comment]
Oh, reloading the page worked. Thanks!
