### ISSUE TITLE
merge points on one coordinate

### ISSUE THREAD

**Issue by fuddl** [mapillary/mapillary_issues#83]
Its a huge pain to correct a photoset thats been shot from ony single point:
![solution rquired](https://cloud.githubusercontent.com/assets/842548/2717855/d41badee-c546-11e3-87b7-5d2f7f5ae6bb.png)

Maybe there should be a way to define a set of pictures to be taken from the same position. Currently its a pain in the edit interface

**Comment by pyrog** [comment]
@fuddl :+1:

**Comment by gyllen** [comment]
Easier in new editor.
