### ISSUE TITLE
Angle change not applied on all images

### ISSUE THREAD

**Issue by PanierAvide** [mapillary/mapillary_issues#832]
Hello,
I tried 3 times to make an angle change (make angles follow the forward direction) on this sequence :
http://www.mapillary.com/map/im/lG73omwNLlzjVBEpEt4vAQ
And the angles are changed only in the first part of the sequence, and the rest of the images keeps the default angle.
Thank you in advance.

**Comment by abienvenu** [comment]
Same as [#798](https://github.com/mapillary/mapillary_issues/issues/798).

**Comment by jesolem** [comment]
Let's track this in #798 - closing.
