### ISSUE TITLE
Cannot turn off shutter sound

### ISSUE THREAD

**Issue by trigpoint** [mapillary/mapillary_issues#834]
I am running android version 1.25. The shutter sound is always on and very annoying.
The checkbox to turn it off has no effect.

**Comment by smsm1** [comment]
Which version of Android are you using and which phone are you using? May help in terminating the issue.

**Comment by kaitu** [comment]
For what is worth, I'm experiencing the same issue as trigpoint an a Samsung SM-C115 running Android 4.4.2. The problem has always been there, even with previous versions of the app.

**Comment by trigpoint** [comment]
Am running on jolla, Sailfish 1.1.2.16.

Is the shutter sound really necessary, surely it was a limitation of mechanical cameras. No camera maker actually designed it in.

**Comment by trigpoint** [comment]
Am told it is android 4.1.2

**Comment by smsm1** [comment]
In some countries it is a legal requirement and cannot be turned off, after some people taking photos inappropriately. 

It is designed in, so that people can tell a photo has been taken, as the expectation is that there is a sound when there is a photo taken, as per the older mechanical cameras.

**Comment by trigpoint** [comment]
Thanks, although it can easily be overcome by turning the volume down, or plugging in a 3.5mm jack cable. But it is really annoying every 2 seconds when you are driving.

**Comment by smsm1** [comment]
I agree, it's one of the reasons I moved from a Drift action camera to a Garmin Virb Elite.

**Comment by jesolem** [comment]
@peterneubauer is there something to do here or should we accept as is?

**Comment by peterneubauer** [comment]
I think calling the api to turn off sound is all we can do. If the vendor dies choose not to honor that call, turning down the system volume outside the app us the only option. Closing this.
