### ISSUE TITLE
"still processing" count not correct

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#835]
On my Profile page, the  number of photos given as "still procesung" is often completely wrong, mostly much too low.
Windows 8.1

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by dymo** [comment]
I (dymo12) have not uploaded anything for a few months, but have 4 images still processing.

**Comment by voschix** [comment]
The "still processing" queue disappeared suddenly a couple of days back and the "still processing" numbers look much more reasonable  now. I would say that the problem has disappeared, even if I have not checked everything.

**Comment by gyllen** [comment]
@voschix We managed to flush some troublesome images through the system. Closing issue....
