### ISSUE TITLE
Should "showMap=false" actually work when embedding?

### ISSUE THREAD

**Issue by msankala** [mapillary/mapillary_issues#837]
Try as I might, I can't hide the map window when embedding an iframe. I've also tried using iframe-url directly in browser window and changed "false" to "no" without avail.
I've tried both Chrome and Firefox, both browsers show map and image.

**Comment by knikel** [comment]
@msankala There was a parsing bug on our end, it has been fixed now. The showMap defaults to true if no argument is passed, `&showMap=false` works as expected, e.g.
```
<iframe width="500px" height="400px" src="http://www.mapillary.com/jsapi?image=UjZ0KtvAZllXmN2SRfGOIQ&showMap=false"></iframe>
```
