### ISSUE TITLE
Easily edit blurring from the traffic signs game

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#838]
It would be really useful if I could get straight to the edit blurring and edit image pages from the traffic signs game: http://www.mapillary.com/map/games/traffic I'm coming across many images that need edits to the blurring, or removed for what ever reason. Being able to quickly get there would speed up the process compared to using the link under the image, and then editing the image from there.

**Comment by pyrog** [comment]
:+1: 

> using the link under the image, and then editing the image from there.

:bulb:  I use this link and replace `im` by `b` in the url

See also #885

**Comment by knikel** [comment]
We're more likely to implement a blur game rather than mixing two. We'll track this one internally.
