### ISSUE TITLE
Adding a traffic sign starts drawing

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#839]
I find the current method of adding traffic signs annoying, especially when in the upper to right hand side of the image due to the location of the resize handle. I'd prefer a method whereby I click the + and then start dragging over the part of the image I want to add the sign to. This would make it much faster and easier.

**Comment by de-vries** [comment]
:+1: I vote for this

**Comment by knikel** [comment]
@smsm1, @de-vries We've added this as a standard behavior. Thanks for the feedback!
