### ISSUE TITLE
Traffic sign game to prefer certain countries

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#841]
I would much prefer to verify traffic signs in countries that I know, rather than random places where I'm not so aware of the signage. Could select based on where I've mapped previously.

**Comment by davidak** [comment]
:+1:

**Comment by pyrog** [comment]
see also #882

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
