### ISSUE TITLE
"gpx" checkbox not shown as marked in opera

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#847]
opera 12.16, linux.
in the upload tab of the profile, there's a gpx checkbox in the upper right corner. clicking it does show "gpx" on all the uploads, but the checkbox itself stays unmarked

**Comment by mprins** [comment]
You might just want to update your browser, the stable release for linux is at 28 atm...

http://blogs.opera.com/desktop/2015/03/opera-28-stable-update/

**Comment by richlv** [comment]
a bit of an offtopic, but latest opera version on linux is not really... that nice :)
of course, if this issue is too complicated, it is not that critical

**Comment by jesolem** [comment]
Closing this one.
@richlv Hope you understand, hard for us to keep everything 100% for old versions.
