### ISSUE TITLE
"Request blurring" button not working

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#848]
The "Request blurring" button on http://www.mapillary.com/map/b/sV96W4N6YEN3YSrKV7aUAQ does not work after removing the blurring for the street sign. This happens with Chrome Mac latest version and Safari. Other images have worked fine.

**Comment by knikel** [comment]
@smsm1 Maybe there has been a blur request already pending for that image, but hasn't been approved yet. When such thing happens the user gets proper feedback now. If something similar happens please reopen this issue.

**Comment by de-vries** [comment]
> When such thing happens the user gets proper feedback now.

good work! but there is a typo in "prolbem":
![selectie_051](https://cloud.githubusercontent.com/assets/1449609/6972626/4d34ebe8-d985-11e4-9838-4010fbcfa51a.png)

**Comment by jesolem** [comment]
@de-vries Correct. Also in "sever" ;)

I fixed. Will go out with next deploy.
