### ISSUE TITLE
Upload does not proceed - no mesage

### ISSUE THREAD

**Issue by flohoff** [mapillary/mapillary_issues#85]
Android client - I have 363 Images from last track. I am on WLAN and press "Upload now". Nothing happens. I get no message. The amount of images does not decrease nothing. 

I tried restarting the client/phone. Used a different WLAN etc.

I am clueless where the problem is. 

There always might be problems on server side or something - I'd expect some kind of message if and what went wrong.

**Comment by nighto** [comment]
Just hit this bug. Took some pictures until I had like less then 300MB space free, and the upload didn't work. I had to free up some space (easiest way: deleting Whatsapp media folder :P) and when I had like 600MB space free, it started immediately. This on a Moto X, with 16GB of memory (11.8GB available to user) and no SD card. 

Perhaps it'd be interesting to have on the interface a warning - only shown if you drag the minimum free space all the way down - that you might have upload problems if you have very low free space available.

**Comment by peterneubauer** [comment]
Is this working now? With the new app version, uploads should be much smoother. closing for now.

**Comment by trolleway** [comment]
Issue still continue at Asus Nexus 7, Android 6.
When Android show low memory warning, upload not starting. Mapillary app is just updated from market.
After clean of memory, upload begin automatically.

**Comment by utack** [comment]
The exact same issue still persists
Please re-open this bug

**Comment by utack** [comment]
Thanks  
Do you need any logs or details on my setup to get an idea what is happening?

**Comment by peterneubauer** [comment]
Yes @utack, a log or even better, you enable trace in the settings of the app, and send us the logs? Thanks!
