### ISSUE TITLE
typos in blur confirmation requests

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#850]
"We’re just letting you know that the 3 blur requests you entered has been registred."
"We’re just letting you know that the 1 blur requests you entered has been registred."

proper plural handling seems to be missing. even taking that into account, this sentence is always wrong ("requests.. has"). there's also a simpler typo :)

* "1 requests"
* "3 requests has"
* "registred"

**Comment by knikel** [comment]
@richlv, fixed. Will be visible soon. Thanks a lot for the feedback!
