### ISSUE TITLE
Need a way to upload not all sequences

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#851]
Currently in android app on review section I can press upload button - and upload all data. I can't uload sequences one by one, by reviewing.
Will be useful to queue upload sequences one by one - with upload button inside sequence, or as option opened on long press on a sequence.

**Comment by HolgerJeromin** [comment]
yes. Would love that. 
Or a way to mark a sequence (move to a special folder?) via preview on the laptop.
/mnt/sdcard/mapillary/new/2015-03-xxx...
/mnt/sdcard/mapillary/reviewed/2015-03-xxx...

would be very easy.

**Comment by jesolem** [comment]
@iav Agree. This is how it works on iOS. We'll take a look at adding in upcoming Android version.

**Comment by vincentdephily** [comment]
Duplicate of #964 ?

**Comment by iav** [comment]
yes.

**Comment by HolgerJeromin** [comment]
this is implemented in the meantime
