### ISSUE TITLE
Image preview goes black in Android app

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#853]
Perhaps already reported, but after I review maybe 50 photos in the app, new photos stop loading, and the screen remains completely black. It makes reviewing pretty impossible.

**Comment by HolgerJeromin** [comment]
According to my observation the active viewed image has no priority over the thumbnailing the whole sequence in the background. If i wait till the full sequence is thumb-nailed i get an image again.
Annoying, yes.

**Comment by stevage** [comment]
OIC - so as I'm stepping forward, I eventually catch up to where the thumbnailing is up to.

Hmm. When I have a lot of photos, it's not really viable to wait until they all get thumbnailed.

**Comment by peterneubauer** [comment]
True,
thumbnailing on the fly is kinda hard with these amounts of photos, we are using the Picasso library, but still with only limited success for caching ...

**Comment by HolgerJeromin** [comment]
Isn't is possible to change the priority of the thumbnailing? So the active viewed fullscreen image should get rendered now and the rest is thumbnailed with lower priority?

**Comment by peterneubauer** [comment]
is this still the case?
