### ISSUE TITLE
Add indication whether the photo has been processed yet

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#854]
Impossible too add roadsigns on some photos without a reason.
Example: on photo https://www.mapillary.com/map/im/yuOFNjPMRX5RxoQS55eNWQ in roadsign mode I see + button - but pressing to it just does nothing.

**Comment by ybkuang** [comment]
@iav Thanks for reporting this!

This is because that the detection algorithm has not been run for those images. We will fix that soon.

**Comment by ToeBee** [comment]
Aha. This explains what I've been seeing for over a week now. It would be good to indicate this somehow. Like disable the sign buttons and have a mouseover tooltip that says something about the detection step not being run yet.

**Comment by ybkuang** [comment]
We have now change the validation interface in this [release](https://blog.mapillary.com/update/2017/10/12/human-in-the-loop.html), which resolves this issue.
