### ISSUE TITLE
Home page cover photo location link broken

### ISSUE THREAD

**Issue by travel193** [mapillary/mapillary_issues#855]
The link for the location of the cover image does not appear when moused over on Windows 8 Chrome in full screen. I noticed a resizing of the browser to half-screen causes the link to work again. 
![cover page location link](https://cloud.githubusercontent.com/assets/11349863/6814370/50096000-d27e-11e4-8974-230b2ecf594e.JPG)

**Comment by knikel** [comment]
This has been fixed.
