### ISSUE TITLE
Allow option to show larger image in the website when viewing a sequence

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#856]
Currently, when using the website to review a sequence, the images are quite small and the map is huge. It would be more beneficial to reverse this, given the whole purpose is to collect images. 

It would make for more effective reviewing, allow for more efficient data extraction from images (for OSM) and make sequences far more interesting to viewers

**Comment by filipca** [comment]
I am sure they know this.  But I

**Comment by jesolem** [comment]
@DaCor1 Yes, @knikel is looking at options for switching to large images on the site. 

@filipca Not sure I understand your comment. How would you like to improve the user experience?

**Comment by DaCor1** [comment]
Excellent, I look forward to seeing it.

Btw, the change to the blurring process is a nice improvement

**Comment by knikel** [comment]
@DaCor1 We've rolled out a new view recently (http://blog.mapillary.com/design/2015/05/28/tiles-design.html) I think it solves your use case? :)

**Comment by DaCor1** [comment]
It does indeed, love the new changes
