### ISSUE TITLE
Many images with strange appearance after upload from Windows Phone app

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary_issues#857]
I recently uploaded a number of sequences using the Windows Phone app on Windows Phone 8.1. Many of the images got a very strange appearance after processing. The number of images with strange appearance seems related to the number of stream errors that occurred and were shown in the app during upload. When uploading the sequences with most of the strangely looking images, a lot of errors occurred and the app had to be restarted multiple times. All uploads were done with a stable connection. I have gathered a list of most of the strange images (ordered by sequence):

http://www.mapillary.com/map/im/UPEDBKUDR64osV8O95jTEA
http://www.mapillary.com/map/im/bWGYteuLMvejSW6VDFXe-Q
http://www.mapillary.com/map/im/WS6GWNN_IMWSD1zneL5NVg
http://www.mapillary.com/map/im/goUxE94dTBVAlaCfr8p9Fg
http://www.mapillary.com/map/im/_vZsbPNK3XGXcpuC-ncPUg
http://www.mapillary.com/map/im/vDjU6ri0CQBaLJitBsn_4Q
http://www.mapillary.com/map/im/U2bOmGP8LtdVp176ZSa40g
http://www.mapillary.com/map/im/2u4Jd7bg9reUpMX2L-SGWw
http://www.mapillary.com/map/im/7qtDf_cynZvSeNUcLh94Fw
http://www.mapillary.com/map/im/xx3ogjBN6koHbAeuw9ldig
http://www.mapillary.com/map/im/GNXICNbyYA8KAh2Nzx0-Mw
http://www.mapillary.com/map/im/eoMIBTVuXWaSU4AoixUA-Q

http://www.mapillary.com/map/im/ruuE66VX_0lKqEA_pZEW1g

http://www.mapillary.com/map/im/h9ahFp-PtPlm5ZCsEQSosg
http://www.mapillary.com/map/im/nmvYpMLS8fVQ0lX_onZ7MA
http://www.mapillary.com/map/im/ZzAFjuRBXN9XzQgokaOYsw
http://www.mapillary.com/map/im/gtwZgdHMrktYJGVr_1_Zeg

There were similar problems with sequences taken some months ago: 

http://www.mapillary.com/map/im/y5LRTByCcMJaIYyUVKP0FQ
http://www.mapillary.com/map/im/DckMP7K-oroqc1l4QIIXkg
http://www.mapillary.com/map/im/v95KKQxRwdVxUjbmVTqfFQ
http://www.mapillary.com/map/im/38PPp44-ELaZlJqKuUmYVA
http://www.mapillary.com/map/im/ET6pquKNfZLlcVmFbxlCuQ
http://www.mapillary.com/map/im/FB9H-J9m0tASwjU2pMuErQ

http://www.mapillary.com/map/im/rtlF3ED0HhDZS2FEci3Bhg
http://www.mapillary.com/map/im/WjWJ3LTcaecjFhe0YRPsFA
http://www.mapillary.com/map/im/Fml9ZUva76I35R53ku0q6g
http://www.mapillary.com/map/im/umVlemH4prczpfv4JgDuxg

http://www.mapillary.com/map/im/pFbinIBAezFhFDWkhiBFjQ
http://www.mapillary.com/map/im/Iv4wi_YMdUrpXG9f5SGBAQ
http://www.mapillary.com/map/im/Ad4K_-sRG2-CG-rrz_CUmg

http://www.mapillary.com/map/im/KNRJI0clEI2XNQY8pPS1xA
http://www.mapillary.com/map/im/m2CsRp2dsyKECNrVeEItVA
http://www.mapillary.com/map/im/bcS54uiuEmwhU2i2SXdNjw
http://www.mapillary.com/map/im/ta0iOrrl-DHJRqIsnxynGg

http://www.mapillary.com/map/im/wuZAhoCO2rAsbzN1QgeY3A
http://www.mapillary.com/map/im/Yu1Kfep_pQ6Gyn-Y1BSQwA
http://www.mapillary.com/map/im/Q1qeuc9tMAoq4Tda2by39w
http://www.mapillary.com/map/im/gXYAunwvqNmRhXmkwER2MA

http://www.mapillary.com/map/im/puSC9ikOVq-bltSlar8TAw

http://www.mapillary.com/map/im/2frHdDwG_ZITf0xv0_A9dg
http://www.mapillary.com/map/im/SMCg71t-B8h5ta9OBS6izQ
http://www.mapillary.com/map/im/0zMb4S9bAxST1vYs8ZEJgg

http://www.mapillary.com/map/im/lF1ygR3OPx11VoFH2II0Mg

http://www.mapillary.com/map/im/DoCRy3dar916th2GBziaSQ

http://www.mapillary.com/map/im/wtCG8VG2te6cezH4_SqUmw
http://www.mapillary.com/map/im/V2ZetH9oY17ZkpNrWKEigA
http://www.mapillary.com/map/im/f25rKoLORWQzUsfEyM9fMA

**Comment by jesolem** [comment]
Hey @oscarlorentzon , we missed this one sorry, assigning to @ybkuang to investigate.

**Comment by ybkuang** [comment]
@oscarlorentzon I just checked that the originals of those images have the same strange appearance. So I suspect the images got corrupted either during capture/uploading. I have actually seen similar behavior for other users with Windows app. I wonder if it is related to the app.

**Comment by oscarlorentzon** [comment]
Before uploading all of my sequences I checked the thumbnails in the app camera roll and everything looked OK. Although you can not see the original images in the app it would be strange if the thumbnails have correct colors and the originals do not. This seems to imply that the upload is the source of the problem.

**Comment by ybkuang** [comment]
Windows phone app is no longer maintained. @oscarlorentzon Let's revisit in the future ; ) Good old days
