### ISSUE TITLE
Images missing after upload from Windows Phone app	

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary_issues#858]
For some uploaded sequences there seems to be a lot of missing images after upload. The images appeared in the Windows Phone app camera roll (Windows Phone 8.1). A lot of stream errors occurred during upload. The following panoramas were taken with approximately 30-40 images. There are a number of large gaps appearing when playing the sequences:

http://www.mapillary.com/map/im/J5rdPsp-a-amKjDs48q_EA
http://www.mapillary.com/map/im/PDSA6TlbcA9NQNHQDjWEPg
http://www.mapillary.com/map/im/zJWMFcS-yKR_WVvdzBIXkg

Don’t know if this is significant or even related but for the following two sequences the number of photos appearing in the camera roll was not the same as the actual number stated in the upload statistics on the homepage.

For sequence:

http://www.mapillary.com/map/im/x5sAXtYr2LtQ30D3k7rozg

there were 490 images in the camera roll but the statistics says that only 456 were uploaded.

For sequence 

http://www.mapillary.com/map/im/5be8a1dhkuxGpF83k8Udqg

there were 1168 images in the camera roll but the statistics says that only 1145 were uploaded. It is not obvious by looking at the sequences that images actually have disappeared as in the example above. There were not many errors occuring in the app during the upload of the two sequences.

**Comment by gyllen** [comment]
Does the upload error correlate with the number of stream errors?

**Comment by oscarlorentzon** [comment]
Yeah, there were a lot of stream errors when uploading the three sequences mentioned at the beginnning. They were uploaded some months ago. When starting an upload in the app the images were uploaded in series. After recieving the first error the images were instead uploaded in parallel, two at a time. When more erros occured the number of images uploaded in parallel increased. When restarting the app the upload was done in series again.

The two sequences mentioned last were uploaded in the last week and the stream errors did not occur as frequently and the app was restarted manually as soon as I noticed that an initial stream error had occured. Since it is not obvious that there are missing images in the last two sequences, the number of stream errors certainly seems correlated with the upload error.

**Comment by gyllen** [comment]
Did you upload images today? Just checking since I have been seeing some strange images in our upload folders.

**Comment by oscarlorentzon** [comment]
Do not know if the "Reply to this email directly"-function worked properly but I did not upload images on that particular day.

**Comment by jesolem** [comment]
@oscarlorentzon Is this still an issue?

**Comment by oscarlorentzon** [comment]
I have not uploaded anything for a while but the last couple of times I uploaded sequences the behaviour seemed more stable than what I reported in the first part of the issue above.

I will take som notes next time I upload and report back.

Has there been any changes in the app to address uploading issues in the latest release?
