### ISSUE TITLE
Panorama sequence broken in two after upload from Windows Phone app

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary_issues#859]
A single panorama sequence taken and uploaded with the Windows Phone app on Windows Phone 8.1 have been broken up in two sequences after upload with a strange appearance for a lot of the images:

http://www.mapillary.com/map/im/ET6pquKNfZLlcVmFbxlCuQ
http://www.mapillary.com/map/im/2LIfiAvmMdUIAvoBrdptDw

**Comment by ybkuang** [comment]
The originals of the images were corrupted. I assume something went wrong during the upload from the app.  Same issue as in #857.
