### ISSUE TITLE
Image disappeared from PhotoSphere-sequence

### ISSUE THREAD

**Issue by floscher** [mapillary/mapillary_issues#860]
Today one photo disappeared from my latest sequence (http://www.mapillary.com/map/s/CN-LYFksUvFk2Q2VpeavYA), which consisted of 9 PhotoSpheres recorded with the stock Android camera app and uploaded with the manual upload page.
It was visible yesterday, I even issued a blur request for the image that disappeared, because it was blurred by mistake. The blur request was approved today at 16:34 CET, later I got the message that "the image is hidden or part of a private sequence", but in the meantime I get the "Image not found" message.

The link to the image in question is http://www.mapillary.com/map/im/cINRW2OIVnOgGMvbMYdtKw

**Comment by jesolem** [comment]
This is strange. We should take a look.

**Comment by peterneubauer** [comment]
Mmh,
I can't find any image 'cINRW2OIVnOgGMvbMYdtKw' anywhere in our data. Even for the raw thumbnail, https://d1cuyjsrcm0gby.cloudfront.net/cINRW2OIVnOgGMvbMYdtKw/thumb-2048.jpg gives nothing. Are you sure?

**Comment by floscher** [comment]
This is the link from the unblur confirmation mail. I was able to click on it once and view the image (at that time it still was still blurred), it was also displayed in-mail (https://d1cuyjsrcm0gby.cloudfront.net/cINRW2OIVnOgGMvbMYdtKw/thumb-320.jpg). If you want it for investigation, I can redirect the blur confirmation mail. 
A few days ago I also sent you the original image by mail.

Two things came to my mind, that may be connected to the disappearance of the image:
* I've edited the timestamp (subtracted some minutes) of this particular image before uploading to bring the images in order. I walked this way in one direction and took the pictures, but this one was made on my way back. I wanted to make it look as if it was also made before walking back.
* for some time (several hours after upload) the line connecting the images on the map was drawn in wrong order, IIRC the first two images or so were displayed after the last one of the other images

**Comment by floscher** [comment]
Ping

**Comment by gyllen** [comment]
Hi @floscher we have not had time to look into this yet. In the mean while have you seen any other images not showing up. I suspect though as you say that this has something todo with the timestamp. Thanks for having patience with us and we hope that us beeing slow on replying here does not keep you from uploading :)

**Comment by floscher** [comment]
Thanks for your fast response. I just wanted to bring it to your attention again, as some time has passed and maybe something has changed. I can totally understand, that you have more important things to do.

No, I've not seen any other images disappear since then. Would it easily be possible that you re-insert the image in the sequence, so that at least the sequence is complete again?

**Comment by peterneubauer** [comment]
Closing this, as I don't think the image is in our system.
