### ISSUE TITLE
Detect Traffic Sign Game: 503 Service Unavailable

### ISSUE THREAD

**Issue by davidak** [mapillary/mapillary_issues#861]
http://www.mapillary.com/map/games/traffic

yesterday i don't get any image. today, every POST request where i changed signs get a 503...

(accept works)

**Comment by ChrissW-R1** [comment]
I'll get this issue every time I add a traffic sign. Verifying ist ok.

**Comment by ChrissW-R1** [comment]
+1
Same issue. No changes could saved.

**Comment by de-vries** [comment]
The confirmed counter is stuck at 86855 since yesterday, looks like no one is able to save changes.

**Comment by peterneubauer** [comment]
Should be working now again? We upgraded Elasticsearch to 1.4.4, and there are some settings disabled by default that we had to re-enable. Sorry for the inconvenience.
