### ISSUE TITLE
Detect Traffic Sign Game: Signs disapear when image is loaded

### ISSUE THREAD

**Issue by davidak** [mapillary/mapillary_issues#862]
http://www.mapillary.com/map/im/EqowbIZ1HfIgr7ENajrtww
http://www.mapillary.com/map/im/tiMgyu3jFb1xyt8yrcOVEg
http://www.mapillary.com/map/im/BPhUaqeOjvQI6ItTNDwMpQ

![bildschirmfoto 2015-03-26 um 20 59 31](https://cloud.githubusercontent.com/assets/91113/6855841/f7ff0a84-d3fb-11e4-846f-f44d812f751d.png)

also, when i add a sign, it is not visible or nothing happens after clicking the `+`. i can click `undo`

**Comment by knikel** [comment]
@davidak I've deployed few improvements to the traffic sign game, would you mind checking if this is still an issue in your case?

**Comment by davidak** [comment]
i don't had the problem again. thank you!
