### ISSUE TITLE
Capturing unreasonble stops and need to re-enter to continue

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#863]
Android app stops captiring time to tome without visible reason, instead it writes kind of error on every capture try.
To continue I need to exit from foto mode with back button, then again enter photo mode.
I sent you some logs already via "send log" function of application.

But sometimes it just stops capturing - red circle turns blue, and I have to look to it and touch to restart capturing. It can be dangerous when used in car on road, and it means I have to check if capturing continues as it should time to time.

**Comment by eliasp** [comment]
Seeing the same here too.
Currently mapping a lot (~2000-3000 uploaded pictures per day) and when mapping by car, it often just stops for no real reason, but also when:
- somebody calls while capturing (even when ignoring the call)
- driving through a tunnel/GPS signal interruption for a moment

I also had it crash quite a few times while capturing in car mode (sent reports through play store with comment "crashed while capturing in car mode").

As the way I have it mounted in the car (clipped to the sun shield) doesn't allow me to see the display, I often check to verify whether it's still running when waiting at traffic lights or so, but that's rather annoying.

I'll try to gather some helpful debug logs during the next days and will attach them once I have something usable.

My device is a OnePlus One, running Android 4.4/CM11 (official ROM).

**Comment by peterneubauer** [comment]
Alias,
will check the Play crash, yes, please send a log next time you get a
crash, too.

**Comment by eliasp** [comment]
@peterneubauer Just sent a mail with complete logs to `hello@mapillary.com` - subject `Mapillary Android Logs - GitHub Issue #863`.

I wanted to capture images during a ~30 min car ride, but ended up with 37 or so pictures taken.

A message, which is repeated quite often and looks rather suspicious:
```
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): java.lang.RuntimeException: takePicture failed
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at android.hardware.Camera.native_takePicture(Native Method)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at android.hardware.Camera.takePicture(Camera.java:1312)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at android.hardware.Camera.takePicture(Camera.java:1257)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at app.mapillary.android.activity.CameraActivity.takeShot(CameraActivity.java:668)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at app.mapillary.android.activity.CameraActivity.access$300(CameraActivity.java:40)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at app.mapillary.android.activity.CameraActivity$17.run(CameraActivity.java:1121)
04-19 16:59:43.649 E/app.mapillary.android.activity.CameraActivity(18094): 	at java.lang.Thread.run(Thread.java:841)
04-19 16:59:43.649 D/app.mapillary.android.activity.CameraActivity(18094): flashing: Error: takePicture failed
04-19 16:59:43.669 D/app.mapillary.camera.Animation.app.mapillary.android.activity.CameraActivity$16@47bc3908(18094): onAnimationStart: Error: takePicture failed
```

Another one:
```
04-19 17:00:15.409 I/Choreographer(18094): Skipped 68 frames!  The application may be doing too much work on its main thread.
```

**Comment by eliasp** [comment]
Since the latest updates 2-3 weeks ago, capturing is now rock solid. Didn't have a single issue anymore since then.
From my POV, this issue can be closed then.

**Comment by iav** [comment]
Not captured last week, but earlyer have issues. No mapillary app updates seen after last fails on my phone (galaxy S4). Maybe, it fixed for your device.
But not mine.
Please, hold this issue opened at least until monday - I will try to capture a lot this weekend.

**Comment by peterneubauer** [comment]
Ok, try and report back!

**Comment by iav** [comment]
It did it again.
Rarely than before, but 45- times for 2 days.
I send you logfile with internal send log function just after last hang, letter from shtripok.

**Comment by iav** [comment]
there is trace log, look to 31.05.2015  https://www.dropbox.com/s/anm1vcj9trmqotk/mapillary_trace.txt?dl=0

**Comment by naoliv** [comment]
Today I saw this problem, much more than I would like (basically it failed all the trip):

    06-04 14:28:27.699 D/app.mapillary.android.activity.CameraActivity(23707): requesting takePicture
    06-04 14:28:27.721 W/System.err(23707): 	at app.mapillary.android.activity.CameraActivity.takeShot(CameraActivity.java:680)
    06-04 14:28:27.721 W/System.err(23707): 	at app.mapillary.android.activity.CameraActivity.access$300(CameraActivity.java:40)
    06-04 14:28:27.722 W/System.err(23707): 	at app.mapillary.android.activity.CameraActivity$17.run(CameraActivity.java:1133)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): java.lang.RuntimeException: takePicture failed
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at android.hardware.Camera.native_takePicture(Native Method)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at android.hardware.Camera.takePicture(Camera.java:1436)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at android.hardware.Camera.takePicture(Camera.java:1381)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at app.mapillary.android.activity.CameraActivity.takeShot(CameraActivity.java:680)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at app.mapillary.android.activity.CameraActivity.access$300(CameraActivity.java:40)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at app.mapillary.android.activity.CameraActivity$17.run(CameraActivity.java:1133)
    06-04 14:28:27.723 E/app.mapillary.android.activity.CameraActivity(23707): 	at java.lang.Thread.run(Thread.java:818)
    06-04 14:28:27.723 D/app.mapillary.android.activity.CameraActivity(23707): flashing: Error: takePicture failed
    06-04 14:28:27.769 D/SFPerfTracer(  280):        layers: (4:10) (FocusedStackFrame (0xb824e4f8): 0:25583)* (DimLayer (0xb82239a8): 0:10882)* (DimLayer (0xb828daa8): 0:6799)* (StatusBar (0xb82bc6c0): 0:331129) (com.android.systemui.ImageWallpaper (0xb82c1870): 0:9080)* (NavigationBar (0xb82cdad8): 0:175) (app.mapillary/app.mapillary.android.activity.CameraActivity (0xb82dcc28): 12:4020) (SurfaceView (0xb82bd950): 37:5774

Also, there seems to be some kind of memory leakage with mapillary. It trashs the phone (other apps get killed).

I can send the full logcat (monster file) or only the lines with `mapillary` if you want.

**Comment by naoliv** [comment]
There are also some
   06-04 14:18:13.113 E/app.mapillary.android.activity.FeedFragment$FetchFeedTask(23707): doInBackground connection exception

**Comment by peterneubauer** [comment]
@naoliv yeah, this sucks. Is the camera exception occuring all the time or after a number of pics? The feed exception is no problem.

**Comment by naoliv** [comment]
I couldn't notice a pattern here. First I thought it could be some problem when driving in some poorly maintained highway parts (some kind of problem when detecting that the phone was shaking), but then it started to happen also in the good highway parts.
What I could observe was that it started to happen more frequently each time, 
regardless of the number of shots taken.
Taking a look at the developer section of the phone, in process statistics, I could see that the memory status was critical (that is why I said I guess there is some kind of memory issue here, since I was running only mapillary at this point).
But I am afraid I can't tell you for sure what could be causing this nor when it exactly happens :-/

**Comment by iav** [comment]
@peterneubauer maybe enable some extra logging into special build? I'd use it and report logs.
Today I upload 18 segments, but it should be 3 or 4 - other are crash-cuts.

**Comment by naoliv** [comment]
Could it be some concurrence between the main thread and the image processing thread?

**Comment by peterneubauer** [comment]
I don't think so. I can add you to the alpha tester Play group If you send me you preferred mail and you can test the latest pre-release versions @naoliv

**Comment by naoliv** [comment]
Sure. naoliv@gmail.com

**Comment by peterneubauer** [comment]
I am suspecting that the camera implementation of that phone is not tested against long picture taking and might leak memory, have seen it on some phones @naoliv

**Comment by naoliv** [comment]
Do you need some detailed log from phone?

**Comment by peterneubauer** [comment]
Yes please,
send me the logs

/peter

**Comment by mbirth** [comment]
I also have crashes on my Nexus 5 (Android 5.1.1). I can't trace it to a specific amount of photos. Sometimes it's after 10, other times after 150 photos. It's only the camera mode which crashes and I end up in the main Mapillary app from where I can start camera mode again.

Could you add me to the alpha tester group, too, please? \<GitHub-Username\>@gmail.com .

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
