### ISSUE TITLE
Issue with GPS on Samsung Note 3 Neo

### ISSUE THREAD

**Issue by Michael21011** [mapillary/mapillary_issues#865]
I have an issue with Mapillary Android application on Samsung Galaxy Note 3 Neo (SM-N7505)

It cannot receive a strong GPS signal. The icon on status bar switches between red and yellow colors and very rare it is green.
But it uses 15 from 22 visible satellites.

Other navigation programs work fine without interruption of signal.

I took some screenshot of Mapillary with different color of GPS icon and also screenshot of "GPS Test".
 https://drive.google.com/folderview?id=0B24PzizqbR_yRzhYaDdCTlZRWDA&usp=sharing

Also there are two log files in folder.

Please ask me if any additional information is required to solve this issue.

Thanks in advance!

**Comment by filipca** [comment]
Thanks for the investigative work.  I did not really have a look at it because I am not an expert.  I should be watching the Galileo launch now.  Mapillary is a bit more severe than other programs.  It turns yellow with a DOP of ? m and stops with a DOP of ? m.
We all have these problems, certainly in the city.
Maybe postprocessing with RTK could help (not with your smartphone).
I alleviated the problem with a Garmin Glo.

**Comment by peterneubauer** [comment]
Mmh, there is one image where the GPS is red but the accuracy is 8m. I can't donwload the trace or log, maybe you can switch settings in Drive, @Michael21011 ?

**Comment by Michael21011** [comment]
@peterneubauer , do you see this icon now?
![23](https://cloud.githubusercontent.com/assets/9266780/6937566/cc4cbe8c-d864-11e4-9a0d-45f74ffb1e11.png)
I created another shared folder on other hosting if previous doesn't work.
https://yadi.sk/d/sZ5wP4Qrffewi

Thank you for attention to my problem!

**Comment by peterneubauer** [comment]
@Michael21011 this seems to be version 1.16 - Can you upgrade to the latest version (I think 1.23)? Also, feel free to join the preview programme, seehttps://github.com/mapillary/UserGuide/blob/master/README.md

**Comment by Michael21011** [comment]
Now I have got a version 1.24 and behaviour is the same. I am afraid a GPS
chip in my phone cannot achieve minimal accuracy.

**Comment by rsahlin** [comment]
Please retest with latest 2.x release
