### ISSUE TITLE
Mixpanel resources not loading because of CORS error

### ISSUE THREAD

**Issue by joakimfors** [mapillary/mapillary_issues#866]
Running Chrome 41.0.2272.101 on OS X 10.10.2

`XMLHttpRequest cannot load http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJ2aXNpdGVkIiwicHJvcGVydGl…iAiZGM3ZDA5ZjA4MTI1Njc1ZjNlNDRkZGYxMmZmMWU2M2UifX0%3D&ip=1&_=1427536794443. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access.`

**Comment by iav** [comment]
Possible, it's related:

https://a.mapillary.com/v2/im/O3H7-p4myX_JbeOs_hvTNQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh Failed to load resource: the server responded with a status of 503 (Service Unavailable)

O3H7-p4myX_JbeOs_hvTNQ:1 XMLHttpRequest cannot load https://a.mapillary.com/v2/im/O3H7-p4myX_JbeOs_hvTNQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access. The response had HTTP status code 503.
angular-sanitize.min.js.map:1 GET https://d1dk9tvuiy3v51.cloudfront.net/javascripts/angular-sanitize.min.js.map 404 (Not Found)

**Comment by knikel** [comment]
Fixed.
