### ISSUE TITLE
Can not view picture when the filter panel is open

### ISSUE THREAD

**Issue by joakimfors** [mapillary/mapillary_issues#867]
When the filter panel is expanded it is not possible to see the selected/active picture. The picture panel expand control is active and changing state but the viewer panel stays minimized.

U-A: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by knikel** [comment]
@joakimfors This has been a correct behaviour as we wanted to have the viewer toggled when interacting with filters (not everyone has a large display). However, I've fixed that, so you can toggle whenever you want and I separated the manual toggle behaviour to another button. 
![manual-toggle](https://cloud.githubusercontent.com/assets/1574656/7002167/aa2efce4-dc46-11e4-92d3-b3e346dc5055.png)

As long as the `M` button is green, the toggle won't take effect, this would still work for people who want to keep the minimized stated even when they close the filters tab.

Thanks for the feedback @joakimfors!
