### ISSUE TITLE
Separate edit links from metadata

### ISSUE THREAD

**Issue by joakimfors** [mapillary/mapillary_issues#868]
It would perhaps be good to separat the JOSM/iD edit links from the picture metadata in the viewer to reduce confusion. Put them under a sub header or add something like "Edit map data in …".

**Comment by jesolem** [comment]
Makes sense. I'd still want them in the info panel but adding a header like the "Information" one to separate out the editing links is good. 

Maybe call the header "Edit OSM" and then simple "JOSM" and "iD".

**Comment by joakimfors** [comment]
Yeah, leave them in the info panel but under a sub heading.

**Comment by knikel** [comment]
Done, thanks!
