### ISSUE TITLE
TypeError: t.className is undefined

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#871]
Very often, after having moved a lot of photo pins in the edit interface, I am no longer able to move any more pins.

At the moment, this happened after moving 73 photos. However, it seems to me that this is not related to the number of photos that have been moved, because other times it happens after different amounts of edited photos.

It seems to me this is a JavaScript error. It seems to happen after "loosing" a photo because of dragging it over another photo (see also issue #591). It does not always happen when dragging one photo pin over another, but it seems that always _when_ it happens, it happens when dragging one pin over another.

After this has happened, whenever I try to move a photo pin, the console logs an error message "TypeError: t.className is undefined" in lib-0990e76d.js:7:11663. I am currently using Firefox 36, but I have also had this error on Chrome 41.

All other JS functionality seems to work fine, such as panning/zooming the map, switching photos by hovering or using the navigation arrows, hiding images, opening the blur interface, etc.

**Comment by knikel** [comment]
@pbb72 I was able to reproduce this only when hovering on image markers in very close proximity in sequences with loads of photos with very little time between each event. I've implemented couple of fixes that address this issue through that lens. I did my best to test it thoroughly, however if this persists I will reopen this one and try different angles.

**Comment by pbb72** [comment]
Hmmm, "image markers in very close proximity in sequences with loads of photos with very little time between each event". Sounds familiar, yeap that's me! ;-)

http://www.mapillary.com/map/e/S5WeYePVcxO3bKV3AzMLMg

http://www.mapillary.com/map/e/ggGtowVH5sncAMBI93XBlQ

**Comment by knikel** [comment]
@pbb72 I did not mean it as a bad thing of course. Awesome use case to test performance against, keep it up :smile: :+1:!

**Comment by pbb72** [comment]
I didn't take it as negative at all. I love to push your system to the limits! :-)
