### ISSUE TITLE
Manual uploads sometimes don't happen

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#872]
I've had a few instances recently where I've selected a bunch of photos (500 or so), waited till they appear orange on the map, click "Upload to server", go to bed...and the next day, still nothing has uploaded. I'm not sure what more information I can add.

**Comment by AllenGraetz** [comment]
I've encountered the same problem.  

The good news is they've rolled out a new manual uploads screen.  I've done a bunch of uploads today  and not had that issue.

**Comment by jesolem** [comment]
@stevage Do you still have this issue with the updated upload view we released March 31?

**Comment by stevage** [comment]
Only done one upload since then, which worked great. Let's consider it closed and I'll reopen if I hit it again.
