### ISSUE TITLE
"still processing" number blatantly wrong

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#873]
The "still processing" figure on my Profile page seems normally blatantly wrong. It has been constantly set to "1" now for a while, Seems not to change during uploads and seems not to reflect the number of pictures still being processed (with the text "this image hasn't finished processing ..." under the photo - at this very moment I have more than 2000 photos in that state).

**Comment by voschix** [comment]
Maybe this is a side effect of another problem: I have found that I have exactly one photo that behaves strangely: http://www.mapillary.com/map/im/B1FxEgIrjonuukDMSgYDKw
It cannot be visualized, shows the "this picture has not yet ..." message, and also blocks the sequence in he sense that you cannot click forward (or backward) along the sequence "through" this photo.  It seems not to exist.

**Comment by gyllen** [comment]
We are working on fixing these broken images.

**Comment by skorasaurus** [comment]
Does this need to be closed? I clicked on the link in @voschix 's 2nd post and the image displays as intended and I am able to continue the sequence when I click the play button.

**Comment by jesolem** [comment]
I think this is one is safe to close now.
