### ISSUE TITLE
Bad classification for some traffic signs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#877]
![type-danger_intersection](https://cloud.githubusercontent.com/assets/2158081/6903669/35e4b3da-d71c-11e4-9364-b4ec8f9390f3.png)

* type-danger_intersection
* type-priority_next_intersection_left
* type-priority_next_intersection_right

The last two are of type danger.
See **Junction with a minor side road** in [Comparison of European road signs](http://en.wikipedia.org/wiki/Comparison_of_European_road_signs) on wikipedia.

They should be named **type-danger_intersection_minor_left** / **type-danger_intersection_minor_right** to be properly sorted and displayed next the first one ?

Also, the sign **Crossroads** is missing :wink: 
![Crossroads](http://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/EE_traffic_sign-132.png/60px-EE_traffic_sign-132.png)

**Comment by knikel** [comment]
These are internal labels we're using, we'll have a better mapping for these in the future.

**Comment by knikel** [comment]
We have an updated naming convention, in the near feature we’ll be updating the classification naming conventions too; you can find source of truth for everything related to Mapillary‘s traffic signs: https://github.com/mapillary/mapillary_sprite_source this is also the place where that will happen. Thanks for the feedback!
