### ISSUE TITLE
Speed limits traffic signs are sorted lexicographically

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#878]
See comment of @floscher https://github.com/mapillary/mapillary_issues/issues/596#issuecomment-73387828

Please, could you just "rename" them to give the correct order ?

* type-prohibitory_speed_limit_10 -> type-prohibitory_speed_limit_010
* type-prohibitory_speed_limit_20 -> type-prohibitory_speed_limit_020
* …
* type-prohibitory_speed_limit_90 -> type-prohibitory_speed_limit_090
* type-prohibitory_speed_limit_100
* type-prohibitory_speed_limit_110
* type-prohibitory_speed_limit_120

**Comment by smsm1** [comment]
+1 to sorting these numerically, it would make it much easier to select them correctly.

**Comment by knikel** [comment]
This has been fixed, thanks for the feedback @pyrog and @smsm1!
