### ISSUE TITLE
Traffic sign: type-danger_hump is missing

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#879]
Could you add [traffico](http://traffico.io/examples.html)  **danger_hump** sign please ?

PS: It is called **Road bump** in http://en.wikipedia.org/wiki/Comparison_of_European_road_signs#Warning
![](http://upload.wikimedia.org/wikipedia/commons/thumb/4/44/EE_traffic_sign-154.png/60px-EE_traffic_sign-154.png)

**Comment by mprins** [comment]
this was added in 2df713daccfa623e245a5dde127fe1637bc52315  and is already available

**Comment by iav** [comment]
Still not see in roadsign chooser. Should I?

**Comment by pyrog** [comment]
@knikel Don't see this sign in Mapillary :smile:

**Comment by knikel** [comment]
Has been added to traffico, and visible on mapillary when we release new __object recognition__ packages that contain this sign.
