### ISSUE TITLE
Images are still missing after >6h since upload

### ISSUE THREAD

**Issue by zibik** [mapillary/mapillary_issues#880]
Hi
I uploaded some photos and after 6 hours these pictures are not available on Mapillary. Example: http://www.mapillary.com/map/im/A343PHcWDuRsgW3WmI0FMA
Is that normal? 
Sorry for my ticket, but it is very important to me. I need this sequence just now.
Cheers

**Comment by maning** [comment]
I get the same error for photos I uploaded ~12 hours ago.
https://www.mapillary.com/map/im/BZh5YKEv_M3SVdlGto04Qg
https://www.mapillary.com/map/im/9yHt4uVklB3PawhMYIHfmw

**Comment by gyllen** [comment]
We are really sorry about this guys. We had a major server upgrade this weekend and our servers are still catching up. Good news though, expect really low latency on new uploads!

**Comment by gyllen** [comment]
Image should be up now
