### ISSUE TITLE
Traffic signs are country dependent in Europe

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#882]
Some traffic signs are very different from one european country to others.
See http://en.wikipedia.org/wiki/Comparison_of_European_road_signs#Warning

* Bus stop ![France](http://upload.wikimedia.org/wikipedia/commons/thumb/7/79/France_road_sign_C6.svg/60px-France_road_sign_C6.svg.png) ![Germany](http://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Zeichen_224.svg/60px-Zeichen_224.svg.png)
* Pharmacy ![Austria](http://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Apotheke_Oesterreich_Logo.svg/60px-Apotheke_Oesterreich_Logo.svg.png) ![Hungary](http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Hungary_road_sign_I-040.svg/60px-Hungary_road_sign_I-040.svg.png)
* Motorway ![France](http://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Autoroute_F.svg/60px-Autoroute_F.svg.png) ![Switzerland](http://upload.wikimedia.org/wikipedia/commons/thumb/1/15/CH-Hinweissignal-Autobahn.svg/60px-CH-Hinweissignal-Autobahn.svg.png)
* …

**Irish** traffic signs are very different than the rest of european signs. They are very similar to US signs.
![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/18/W043_-_Roundabout_Ahead_-_Warning_Sign_Ireland.png/60px-W043_-_Roundabout_Ahead_-_Warning_Sign_Ireland.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Ireland_road_sign_W_001.svg/60px-Ireland_road_sign_W_001.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Ireland_road_sign_WK_073.svg/60px-Ireland_road_sign_WK_073.svg.png) …
And the optical recognition usually fail: it find the **Priority road** sign ![](http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/France_road_sign_AB6.svg/60px-France_road_sign_AB6.svg.png)
For examples, see:
* http://www.mapillary.com/map/im/g08tAmfXvZBVq_olNjH8Tw
* http://www.mapillary.com/map/im/cITxq-PPFi4i9Ra-VCphTg

**Comment by smsm1** [comment]
Agree having something that was more country dependant would be helpful for the list of signs, as I've seen for example a lot of bus stop signs however only on reading this issue find out that the circle with a H means a bus stop.

**Comment by mprins** [comment]
ideally the sign picker dialog would be (enhanced to be) country specific based on the location of the image.
This would probably give some rate of error near the country borders though... Ireland, being an island may get away with that, not sure what the signs in Northern Ireland are like?

**Comment by smsm1** [comment]
In Northern Ireland the signs follow the UK conventions more closely.

**Comment by pyrog** [comment]
Currently, how to "tag" irish traffic signs?
![irish traffic signs](https://cloud.githubusercontent.com/assets/2158081/7301466/1bf7733e-e9e3-11e4-8f70-ae44b9daa8fd.png)

Some players use the equivalent european sign for danger. They're right for the meaning of the sign, but I think it's a bad idea because the purpose of this game is to help the vision algorithm to be more efficient.

@peterneubauer What is your position in this case ?

**Comment by peterneubauer** [comment]
Well yes. The signs suggested should follow the actual signs used in the country. @knikel any chance we can make it so?

**Comment by knikel** [comment]
@pyrog @peterneubauer this is definitely the end goal in terms of traffic sign representations, and something we will eventually do. I’m going to revisit Traffico soon with focus on wider spectrum of traffic signs covered.

**Comment by knikel** [comment]
We started to work on traffico with regards to handling different signs across countries. Currently we detect them as one EU package on mapillary.com. We're rolling out new packages whenever we can. So, in short we're working on it, will take some time until fully in place :wink:.
