### ISSUE TITLE
Consider adding `end of prohibition` and `destinations` to OR packages

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#883]
I know it's difficult to add all the traffic signs in the vocabulary of traffico, but for the players and the pictures I think there are four kinds of traffic sign it is important Mapillary doesn't miss it:

-End of prohibition: (there's no one) (finish of forbidden overtaking or speed limit)
-Destinations: I know it's so complicated and different between countries so why traffico doesn't have a generic destination type?
-Kilometers,arrow curves,etc. :there's a lot of traffic signs with the names, and the kilometer you are in,or the curve and the direction you have to drive in like > or >>>.At first sight they seemed accessory but they are so important to give you important information about the road by you are driving
-Electronic panels: when you are in a motorway or near a city there are some electronic panels that changes the traffic sign inside in, so I think it will be a great idea to make one generic electronic panel sign.

Greetings from Austria (holidays)
yopaseopor

**Comment by pyrog** [comment]
> End of prohibition

:+1: 
![](http://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/France_road_sign_AB7.svg/60px-France_road_sign_AB7.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/France_road_sign_B31.svg/60px-France_road_sign_B31.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/4/47/France_road_sign_B33_%2850%29.svg/60px-France_road_sign_B33_%2850%29.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/France_road_sign_B34.svg/60px-France_road_sign_B34.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/France_road_sign_B34a.svg/60px-France_road_sign_B34a.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/France_road_sign_B35.svg/60px-France_road_sign_B35.svg.png)

![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/France_road_sign_B53.svg/60px-France_road_sign_B53.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/France_road_sign_B55.svg/60px-France_road_sign_B55.svg.png)

![](http://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/France_road_sign_C4b_%2850%29.svg/60px-France_road_sign_C4b_%2850%29.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/15/France_road_sign_C108.svg/60px-France_road_sign_C108.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/France_road_sign_C112.svg/60px-France_road_sign_C112.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/France_road_sign_C114.svg/60px-France_road_sign_C114.svg.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/C116_1.png/60px-C116_1.png) ![](http://upload.wikimedia.org/wikipedia/commons/thumb/8/86/France_road_sign_C208.svg/60px-France_road_sign_C208.svg.png)

See [Panneaux de fin d’interdiction](http://fr.wikipedia.org/wiki/Panneau_de_signalisation_routière_de_prescription_en_France#Panneaux_de_fin_d.E2.80.99interdiction) and [Panneau de signalisation routière d'indication en France](http://fr.wikipedia.org/wiki/Panneau_de_signalisation_routière_d%27indication_en_France) for France
and [Comparison of European road signs](http://en.wikipedia.org/wiki/Comparison_of_European_road_signs) for Europe

**Comment by yopaseopor** [comment]
Also http://es.wikipedia.org/wiki/Anexo:Se%C3%B1ales_de_Tr%C3%A1fico_de_Reglamentaci%C3%B3n_de_Espa%C3%B1a

**Comment by ybkuang** [comment]
Most of these signs are added in the latest [release](https://blog.mapillary.com/update/2018/06/15/global-sign.html). You can file more requests in the future and we need to find a better way to group such request together.
