### ISSUE TITLE
Traffic sign game: Add blurring/unblurring to the game

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#885]
As a traffic sign could it be possible to add/delete blurring to the game? (There are so many car plates and faces to blur and there are so many traffic signs to unblur)

**Comment by pyrog** [comment]
Or is it possible to use the same interface to blur/unblur ?
With the `B` shortcut to blur/unblur and the `T` to add/remove traffic signs ?

**Comment by iav** [comment]
I see a new "blur" button in "browsing mode". But currently it opens link like "http://map/b/dW0NDxHCXa7wrwd7d5AVIw" - without site.

**Comment by de-vries** [comment]
> I see a new "blur" button in "browsing mode". But currently it opens link like "http://map/b/dW0NDxHCXa7wrwd7d5AVIw" - without site.

the edit button has the same problem.

**Comment by jesolem** [comment]
The broken URL has been fixed. Can we close this now?

**Comment by de-vries** [comment]
> The broken URL has been fixed. Can we close this now?

well, the issue started about something else. So at least you have to add a blur button (like the one in the map-view) to the traffic sign recognition game before you can close it.

Also I think this is a duplicate issue, but in this case I'd rather see it as much requested feature. ;)

**Comment by iav** [comment]
Generally better will be one big window with easy and fast, no-page-reload swiching between roadsign and bur edition.

**Comment by de-vries** [comment]
agreed, but that takes a lot more coding and in the mean time a link to the blur page would be nice.

**Comment by knikel** [comment]
We're very likely to have a blurring game after we build a new version of the traffic sign game. Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
