### ISSUE TITLE
100 photo limit on upload is not enough

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#888]
First, the new manual uploader is much better. Hooray!

But 100 photos at a time isn't enough. When you take one photo every two seconds, that's only 3 minutes of footage. I'd really like to be able to upload 1000 photos at a time, so I can do it overnight. Doing batches of 100 is too frustrating and tedious.

Is there some command line way, perhaps?

**Comment by knikel** [comment]
Hey @stevage,
you can adjust the limit cap at the very first 'screen' of the uploader by pressing manual upload settings. The change will be confirmed by a brief flash of a green tick mark. Hope that helps?

![upload-limit](https://cloud.githubusercontent.com/assets/1574656/6965489/23e51bba-d952-11e4-8c0b-1b71503297d6.png)

**Comment by stevage** [comment]
Oh, I didn't see that (probably because it was still uploading). Weird, but works, thanks.
