### ISSUE TITLE
Example image in traffic game faq is not found

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#889]
The FAQ of http://www.mapillary.com/map/games/traffic points to http://www.mapillary.com/map/im/BBTabHxrAwnzoDCvmSykP which apparently doesn't exist.

**Comment by de-vries** [comment]
Here is the correct link: http://www.mapillary.com/map/im/BBTabHxrAwnzoDCvmSykPg
But here is a better example: http://www.mapillary.com/map/im/5A3DlkG4yTnVvKE3XrjDHQ

**Comment by knikel** [comment]
Thanks @vincentdephily for catching that! Fixed with a URL suggested by @de-vries.
