### ISSUE TITLE
Can't see fresh images

### ISSUE THREAD

**Issue by stevage** [mapillary/mapillary_issues#890]
I just had an email notification that a sequence has been "added to the map". Clicking on any of the links eventually (long pause) shows the message "This image doesn’t exist, has been hidden or is part of a private project."

Eg: http://www.mapillary.com/map/im/h5AqiVkmSBOp-8vrgfp1mA

Looks like maybe the email is going out slightly too early.

**Comment by gyllen** [comment]
Works now?

**Comment by stevage** [comment]
That one does, yes. Maybe a temporary glitch - I also couldn't see images on any of my previously uploaded sequences.

**Comment by gyllen** [comment]
Yeah we had a temporray server glitch, need to show better error message.
