### ISSUE TITLE
Wrond tool button distance scaling in roadsign editor

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#892]
Look to distance from red roadsign selection area to operation buttons - resize., delete, sign choose, and moving.
![image](https://cloud.githubusercontent.com/assets/325961/6988347/157259be-da59-11e4-944c-72edd560f1c1.png)

When we "go deeply" we scale up image - and distance from selection area to tool buttons (marked with red arrows) scaled as image. But it shoildn't.
![image](https://cloud.githubusercontent.com/assets/325961/6988306/b232dfe0-da58-11e4-8fcc-a3d64f013453.png)

**Comment by de-vries** [comment]
duplicate of #730

**Comment by pyrog** [comment]
See #909 #910

**Comment by knikel** [comment]
This won't be an issue after we update the editor

**Comment by knikel** [comment]
This is part of `legacy.mapillary.com`, closing this since we want to deprecate that part of mapillary.com. We'll have similar functionality in the future.
