### ISSUE TITLE
Can't rearange wrong Path

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#895]
Hey. i try to correct to path of
http://www.mapillary.com/map/e/akhpldZQSwQddZd34524pA
(my latest upload that is now on the map.)
But i do not see the Flags to re-arange them on the map.
Whats wrong ?

**Comment by jesolem** [comment]
Works now. Can we close this or do you still have problems?

![image](https://cloud.githubusercontent.com/assets/136751/7055968/51ce4b46-de48-11e4-900c-77a456d075a0.png)

**Comment by gyllen** [comment]
Closing since no interaction
