### ISSUE TITLE
"highway=cycleway" gets ignored in reverse geocoding

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#896]
In reverse geocoding names of cycleways are not conciddered. For example: [this photo](http://www.mapillary.com/map/im/knlnmbz4IjvOJcksqa71IA) has the name of a nearby street, while the cycleway it's clearly on also has a name. If you go one photo forward in that sequence you get the name of another nearby street. 

I couldn't find a single example of a photo geocoded to a cycleway, thus my conclusion: "highway=cycleway" gets ignored in reverse geocoding.

**Comment by jesolem** [comment]
We're going to look at geocoding properly but it will take a while to fix.

**Comment by polarbearing** [comment]
Geocoding needs some care anyway, in particular in walking mode. I had uploaded pictures when walking across a meadow, or from some interesting places in the forest, and find them geocoded to the next major road which is several hundred meters away.

**Comment by gyllen** [comment]
No longer geocoding in backend.
