### ISSUE TITLE
Edit/blur links got to an invalid url

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#898]
On http://www.mapillary.com/map/im/ITEXzkU-tVbSVwyuULaOjQ the edit link goes to http://map/e/ITEXzkU-tVbSVwyuULaOjQ and the blur link goes to http://map/b/ITEXzkU-tVbSVwyuULaOjQ

**Comment by pbb72** [comment]
The bug simply a slash too many at the start of the URL: "//map/e/xxx" should have been "/map/e/xxx"

**Comment by pbb72** [comment]
For users, the work-around is to change "/im/" in the URL into "/e/" to get the edit link, or "/b/" for the blur link.

**Comment by knikel** [comment]
Fixed, sorry about this guys!
