### ISSUE TITLE
Recent activity on user profile is 1 day out.

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#900]
I'm finding the recent activity is often 1 day out. For example is say I uploaded 0 on April 4th, and 2695 on April 3rd. Yet, I uploaded 2695 on the 4th and 617 on the 3rd (which is thinks I uploaded on the 2nd.

**Comment by jesolem** [comment]
Could be a time zone issue? @gyllen ?

**Comment by de-vries** [comment]
duplicate of #634

**Comment by gyllen** [comment]
I thinks its a web client issues.

**Comment by knikel** [comment]
Closing in favour of #1632

**Comment by knikel** [comment]
This widget needs a complete rework. Won't be part of the upcoming mapillary.com update, but we'll add it after the initial release in a better form. Closing.
