### ISSUE TITLE
Error while taking pictures

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#903]
While I was driving my brother saw that Mapillary started to give a message with something saying that there was an error while taking the picture. Since I was driving I wasn't able to play with it to see exactly what was happening but I could see that Mapillary was trying to take the pic (I could see the screen flashing) and right after it gave the message with the error.
This repeated for every 2 seconds.

Storage space and everything else was OK and the only solution was to exit the app and start it again.

Since Mapillary (the main core) was apparently working, could this be an issue with the picture processing thread? (somehow it crashed and the main loop kept working)

I wasn't able to save the log (was driving + had to restart the app)

**Comment by iav** [comment]
Have the same on Galaxy S4. It can be device-dependent. Please, tell yuiur device model.

**Comment by naoliv** [comment]
Mine is a Motorola Moto G 2, running Android 5.0.2

**Comment by naoliv** [comment]
What I saw today: was driving, received a call, didn't answer it (the phone was at the support), saw that Mapillary stoped to capture, clicked the button but it gave the same error like before.
Maybe this problem is reproducible after receiving a call?

**Comment by peterneubauer** [comment]
Will try the calling situation, I think there is another bug related to incoming calls.

**Comment by Stalfur** [comment]
Galaxy S4, same issue, not related to receiving calls. Plenty storage space.

Restarting app usually works, had to restart twice one time.

**Comment by rsahlin** [comment]
Please retest with latest 2.X release
