### ISSUE TITLE
Sometimes keeps taking pics while the car is stopped

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#905]
Sometimes I see mapillary taking pics even if I am stopped. I have sequences with 10 photos (20+ seconds stopped, then) where mapillary kept working.
Is this caused by a possible low precision GPS reception or maybe some issue with mapillary or phone sensors?

**Comment by jesolem** [comment]
If the GPS accuracy is poor the distance/speed computation will be off and the device thinks it is moving.
