### ISSUE TITLE
Can't approve trafic signs in map-view

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#907]
Saving edits and approving in the game does work as supposed.only when I click approve in map-view the button gets a spinner and nothing happens.
It's like this for like 2 days

**Comment by ToeBee** [comment]
This might be related to #854 but I'm pretty sure I've seen it happen on pictures that I know have been run through the detection system because I uploaded them several weeks ago and I've already flagged road signs in them.

**Comment by de-vries** [comment]
@ToeBee I don't think #854 is related, it also happens on half year old photo's and saving changes isn't affected.

**Comment by knikel** [comment]
@de-vries @ToeBee The main reason why such situation might have happened is that the region where the photo is taken hasn't been processed yet on our side, as you have already mentioned.
We run the detection manually every time. This will change over time when we do the detection automatically and will speed up the process.

For now I've added feedback when this is the case  in form of a warning.

@ToeBee @de-vries When this happens again on an photo that has signs could you please post a link in #854 so we can investigate further?

**Comment by de-vries** [comment]
@knikel I'm afraid I didn't explain it clear enough.  I'm still able to make changes and safe them. So the behavior is quite different from #854. 
But pressing the approve button (without adding, removing or changing anything) doesn't have any effect (except for the spinner on the button) on any (processed) photo. It doesn't matter if there are signs in them or not.

for example: if I try to approve the sign on [this almost one year old photo](http://www.mapillary.com/map/im/bxO4eUnO0ihyTRaWz-8YrA) nothing happens.

**Comment by de-vries** [comment]
wait a minute. behavior changed a little....

**Comment by de-vries** [comment]
Here is what's changed:

- press the approve button
- get the spinner on the button
- go to another photo
- wait a little and the spinner disappears
- go back to first photo

behavior before: 
- there was a approve button

behavior now:
- there is a approved icon

So when I press the approve button I still get the spinner on the button that doesn't go away and I don't get any confirmation that my feedback is received or saved.

**Comment by knikel** [comment]
@de-vries awesome, thanks a lot for your time and feedback! So the remaining thing to fix is the direct feedback that the image has been approved already without the need to jump between photos. Working on that now.

**Comment by de-vries** [comment]
something (probably) related:
when I jump to another photo I always get an add-sign-button and a approve button.

After 3 seconds that changes in what it should be. eg:
the add-sign-button and the approved icon, or the "It is not possible to approve or add traffic sign on this photo yet." warning.

This is a bit slow if you ask me.

**Comment by knikel** [comment]
Editing traffic signs should be a bit more fluid now. Thanks again @de-vries!

**Comment by de-vries** [comment]
nice! confirmation on saving or approving is much faster now. The slowness I described in my previous comment didn't change much, but I like that it says fetching to indicate something is going on. Also +1 for the "Approved" and "Already edited" texts.

some minor issues with it:
- When hovered the "Approved" and "Already edited" texts are unreadable. Wrong text color.
- The "Fetching" text only shows up in the last 0.5 second of the 2.5 second wait.
- If you click the approve button in the first second it's visible it goes trough the following phases:
 - approve icon
 - click
 - spinner icon
 - "Approved"
 - "Fetching" 
 - "Approved"

A possible solution to make this smoother would be to preload the traffic sign data of next (and previous) photo in the sequence.

**Comment by de-vries** [comment]
solve first point in list by adding
```
.pure-button[disabled]:hover {
    color: #242528!important; }
```
to the css

**Comment by knikel** [comment]
@de-vries Awesome! So, I've rolled out couple of more fixes, the approved button is more legible and has no hover state, as you suggested. You should not see confirm button flashing anymore.

In regards to preloading, I haven't done that, but we're tracking it internally and will work on that soon. I totally understand that shaving off 2-3 seconds, times _N_ will have a huge impact for power users like you!

I'm closing this issue now. Thanks a lot!

**Comment by de-vries** [comment]
nice work! feels much more solid now.
