### ISSUE TITLE
Traffic signs editing: drawing is not cleaned at high zoom levels

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#910]
![drawing is not cleaned](https://cloud.githubusercontent.com/assets/2158081/7089963/01272970-dfa0-11e4-8955-5dcfae3f34eb.png)

See also #909

Safari Version 8.0.4 (10600.4.10.7)
Mac OS X 10.10.2

**Comment by pyrog** [comment]
Ok with Chrome Version 41.0.2272.118 (64-bit)

**Comment by knikel** [comment]
These visuals artifacts should be cleaned up now as soon as you start interacting with the controls. Thanks for catching it @pyrog!

**Comment by pyrog** [comment]
Nice, thanks :smile:
