### ISSUE TITLE
Adroid App Camera Rotation

### ISSUE THREAD

**Issue by holgersoft** [mapillary/mapillary_issues#911]
I can rotate my phone to the left to get landscape mode.  But if I rotate it to the right in camera mode the UI is kind of upside-down.  The symbols and the menu are right (the symbols are at the upper left corner), but the Android status bar and the detailed status (tilt, direction, GPS) are upside-down.  Can you improve that please?

My phone is a Samsung Galaxy S4 mini, Android 4.4.2, Mapillary 1.20.

**Comment by peterneubauer** [comment]
Yup, not sure about the notification bar but the GPS status should be fixed. This is not really a rotation but more a convenience for left handed mapping.

**Comment by HolgerJeromin** [comment]
BTW the debug output doesn't rotate nicely to both sides.
