### ISSUE TITLE
Video upload issue

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#912]
Hey there,

i am using an SONY HDR-AS30V, it can record MP4 files with included GPS values.
But i have Problems to upload them..

i am still stuck at the point "Video time period is outside the GPX period. Please move the marker on the map to the current image position."

I have the MP4 file selected as video.. used GPSBAbel to convert the GPS-Log file into a GPX File.. but still.. i can't get the UPLOAD Button

When i match the Video to the GPS File is still had a diff.

Video time: 04/09/2015, 9:45:20:709
GPS start time: 04/09/2015, 9:45:20:20

Any ideas ? Any Suggestions ?

Cheers
Thorsten

**Comment by pyrog** [comment]
Could you add a sample of yours files?

10 first positions for example of:
* Sony log file (in NMEA format)
* Converted file (in GPX format)

**Suggestion**: Does Mapillary could detect GPS file format and convert it automatically (NMEA, GPX, KMZ)

**Comment by briskyd** [comment]
I am having the same problem with a Gamin Virb . Upload button wont appear, I did get one video (a time lapse 2fr/sec) to Sync and upload though.  Can I provide anything that would help?

**Comment by paulinus** [comment]
@thoschu96 the error seems to be due to the GPS track finishing before the end of the video. It might be the camera stops the GPS track just an instant before stoping the video. It would be very helpful if you could share a small sample video that we could inspect. 

We might need to replace the error by a warning, and allow uploading videos that do not have GPS positions for all of their duration.

**Comment by ToeBee** [comment]
If this really is just a matter of the video being slightly longer than the GPS trace, see #894.

**Comment by thoschu96** [comment]
the original log (cutted down)
@Sonygps/ver5.0/wgs-84/20150409074519.000/
@Sonygpsoption/0/20150409074519.000/20150409074520.000/
$GPGGA,074520.000,5000.7295,N,835.7961,E,1,0,,,M,,M,,*7D
$GPRMC,074520.000,A,5000.7295,N,835.7961,E,27.17,,090415,,,A*45
$GPGGA,074521.000,5000.7261,N,835.8067,E,1,0,,,M,,M,,*77
$GPRMC,074521.000,A,5000.7261,N,835.8067,E,27.15,,090415,,,A*4D
$GPGGA,074522.000,5000.7230,N,835.8172,E,1,0,,,M,,M,,*75
$GPRMC,074522.000,A,5000.7230,N,835.8172,E,26.82,,090415,,,A*40
$GPGGA,074523.000,5000.7197,N,835.8279,E,1,0,,,M,,M,,*72
$GPRMC,074523.000,A,5000.7197,N,835.8279,E,27.03,,090415,,,A*4F
$GPGGA,074524.000,5000.7165,N,835.8387,E,1,0,,,M,,M,,*78
$GPRMC,074524.000,A,5000.7165,N,835.8387,E,27.03,,090415,,,A*45

**Comment by thoschu96** [comment]
and the GPX file (also cutted down)
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPSBabel - http://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/1/0">
  <time>2015-04-12T08:59:32.702Z</time>
  <bounds minlat="50.011335000" minlon="8.596601667" maxlat="50.107585000" maxlon="8.670985000"/>
  <trk>
    <trkseg>
      <trkpt lat="50.012158333" lon="8.596601667">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:20Z</time>
        <course>0.000000</course>
        <speed>13.977455</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.012101667" lon="8.596778333">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:21Z</time>
        <course>0.000000</course>
        <speed>13.967167</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.012050000" lon="8.596953333">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:22Z</time>
        <course>0.000000</course>
        <speed>13.797400</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.011995000" lon="8.597131667">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:23Z</time>
        <course>0.000000</course>
        <speed>13.905434</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.011941667" lon="8.597311667">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:24Z</time>
        <course>0.000000</course>
        <speed>13.905434</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>

**Comment by thoschu96** [comment]
just checked the VideoFile and the GPX File.. i dont't see a time difference. both is 00:16:57 long

**Comment by pyrog** [comment]
Your gpx file seem to be in a wrong format :cry: 

Here is your NMEA file converted with [online GPS Babel](http://www.gpsvisualizer.com/gpsbabel/)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPSBabel - http://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/1/0">
  <time>2015-04-15T19:17:12.332Z</time>
  <bounds minlat="50.011941667" minlon="8.596601667" maxlat="50.012158333" maxlon="8.597311667"/>
  <trk>
    <trkseg>
      <trkpt lat="50.012158333" lon="8.596601667">
        <ele>0.000000</ele>
        <time>2015-04-09T07:45:20Z</time>
        <course>0.000000</course>
        <speed>13.977455</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.012101667" lon="8.596778333">
        <ele>7.452000</ele>
        <time>2015-04-09T07:45:21Z</time>
        <course>0.000000</course>
        <speed>13.967167</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.012050000" lon="8.596953333">
        <ele>7.452100</ele>
        <time>2015-04-09T07:45:22Z</time>
        <course>0.000000</course>
        <speed>13.797400</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.011995000" lon="8.597131667">
        <ele>7.452200</ele>
        <time>2015-04-09T07:45:23Z</time>
        <course>0.000000</course>
        <speed>13.905434</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
      <trkpt lat="50.011941667" lon="8.597311667">
        <ele>7.452300</ele>
        <time>2015-04-09T07:45:24Z</time>
        <course>0.000000</course>
        <speed>13.905434</speed>
        <geoidheight>0.0</geoidheight>
        <fix>2d</fix>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```

**Comment by orofarne** [comment]
Same problem with Garmin Virb. Nothing helps.

**Comment by pyrog** [comment]
@thoschu96  and @orofarne 
> I am still stuck at the point "Video time period is outside the GPX period. Please move the marker on the map to the current image position."
> I have the MP4 file selected as video.. used GPSBAbel to convert the GPS-Log file into a GPX File.. but still.. i can't get the UPLOAD Button

I made a test with .mp4 and .gpx test files:
The *Upload to server* button appear when I move the blue marker.
![upload video](https://cloud.githubusercontent.com/assets/2158081/7355867/f34dbc82-ed24-11e4-9848-1fd25ef75d12.png)

**Comment by paulinus** [comment]
We've just updated the video upload page so that it no longer require the video to be fully contained in the GPX. You still need to make sure that the video is in sync with the GPX track by moving the blue marker to a proper place. If video starts or finishes outside the GPX range, you will get a warning but it will let you upload anyway.
