### ISSUE TITLE
Related images: display informations about theses images

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#913]
When the mouse cursor is over a related image, could you display the **date** and the **author** of the image ?

Currently, we should to click on it to display theses informations (and it's a bit long because the web page seem to be reloaded).

Thanks :smile:

**Comment by jesolem** [comment]
What image view is this? We show location, user, views in most places.

**Comment by pyrog** [comment]
Map view:
[rX3guAZJPgzJg10h3JHt6A
![related image](https://cloud.githubusercontent.com/assets/2158081/7807671/b3cb1ecc-038d-11e5-855b-3f2a75145002.png)
](http://www.mapillary.com/map/im/rX3guAZJPgzJg10h3JHt6A)

**Comment by knikel** [comment]
We've removed this feature as it doesn't make sense to have it, given we have OpenSfM working in the new viewer. You can easily navigate to these photo through the viewer.
