### ISSUE TITLE
Main map zooms to wrong point

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#914]
This issue is related to #590, but is slightly different.

When locating a photo on the map, Mapillary places the pinpoint at around 75% of the screen width to the right. However, zooming in and out of the map happens from the midpoint. As a result, zooming in once places the pointer on the outer right edge of the screen, and zooming in twice, places it outside the screen.

Instead, the screen should be zoomed in and out around the map pointer, keeping that always visible on the map.

**Comment by knikel** [comment]
We removed all the map offset vs. layout magic. This is no longer an issue in the new viewer.
