### ISSUE TITLE
Strange format for GPX files in Firefox

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#915]
I have strange issue with the download of GPX files from Mapillary when I use Firefox (37.0.1) on a Windows 8.1 computer. Let's take an example:
https://api.mapillary.com/v1/s/gpx/RwgwfnN6N6nHWTUXMKttBQ.gpx
Opens fine in Internet Explorer and Google Chrome, but in Firefox I get this strange text, which does not look like GPX. See this file:
![strange gpx file](https://cloud.githubusercontent.com/assets/11076112/7126004/230a020e-e236-11e4-8add-8ad3a50d9672.jpg)

**Comment by pbb72** [comment]
That exact same link works fine in my Firefox 37.0.1 on Windows 8.1. It looks to me like the response was handled as HTML instead of as XML. Are you consistently getting this? Then you may have a plugin that changes how XML files are handled in Firefox.

**Comment by voschix** [comment]
Thanks, yes, the Firefox Extension "Skype Click to Call" is he culprit.
