### ISSUE TITLE
Edit view: Add higher resolution (> 19) OSM layer

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#916]
When working with photos taken while walking in the city, the default OSM layer does not provide enough detail for the big pointers that Mapillary uses. Very often, my maps (in edit mode) end up as a big heap of pointers completely covering the map.

It would be cool if we could use a OSM layer that has higher resolution, for example the Humanitarian OSM one which goes to level 20.

**Comment by jesolem** [comment]
Let's revisit this after the next update of the map tiles. We're switching things out a bit.

**Comment by knikel** [comment]
We have max zoom 20 for the OSM layer

**Comment by pbb72** [comment]
Thanks! Though not of much use now, since the editor itself is non-functional at the moment, and I assume the new website will also have a new editor :-)

**Comment by knikel** [comment]
Yes, complete overhaul.
