### ISSUE TITLE
Change request confirmation email needs to have a link to the changed set(s)

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#918]
Currently, the email confirmation one receives after submitting a change request just says "We’re just letting you know that the X change set requests you entered has been registered."

It's impossible to keep track of which changes these apply to, especially since it can take several days before the changes are performed. Preferably, the email would contain a link to a specific page for the change set (such as one gets after the change has been performed), but if this is not possible, a link to the modified sequence(s) would already be very helpful.

**Comment by jesolem** [comment]
+1

**Comment by gyllen** [comment]
Noted, Im afraid there might be a problem with showin a changeset before its approved. But I will investigate.

**Comment by pbb72** [comment]
As I said, if a link to the changeset is impossible, a link to the modified sequence or images would also help.

**Comment by pbb72** [comment]
Thanks for linking to changesets!
