### ISSUE TITLE
in the uploadhashes message, mention that relogging could help

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#920]
even when a user is logged in, opening http://api.mapillary.com/v1/u/uploadhashes may fail with :
"You need to sign in or sign up before continuing."

apparently, that can be fixed by logging out and then in again. suggestion - mention that in the message. something like "If you already are logged in, try logging out and back in"

it's a common issue and has been already reported as #364 and #513

**Comment by domdomegg** [comment]
Hashes are now located at:
https://www.mapillary.com/map/upload/im

**Comment by knikel** [comment]
This will be added in the the uploader for the mapillary.com

**Comment by knikel** [comment]
Upload hashes are available at [`mapillary.com/app/settings/developers`](https://www.mapillary.com/app/settings/developers) and are always visible (well, as long as you're logged in).
