### ISSUE TITLE
Make it easier to delete sequences and photos

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#922]
I have 5356 photos in 108 sequences in my phone, all of them already uploaded via mapillary_tools.
Since Android ≥ 4.4 doesn't allow me to delete them using another program, it seems that I need to use Mapillary itself for this.
But there isn't any option to select all sequences and delete them. I need to enter on each sequence, select one photo, select ALL and only then delete.
It would be good to have a better way to completely delete all the sequences and images.

**Comment by peterneubauer** [comment]
You can in the sequences view swipe a sequence card to the side to delete it?

**Comment by naoliv** [comment]
Indeed, I didn't know this.
But couldn't we still have an option to select and delete all?

**Comment by naoliv** [comment]
I almost deleted a sequence with 1588 photos today, since I started to swipe it unconsciously.
Could we also have some kind of warning to avoid this?

I see two things now:
* have some warning or confirmation while swiping a sequence
* have a quick way (in the menu) to choose "Delete all sequences"

**Comment by peterneubauer** [comment]
we can add a "delete all" button, but it clutters the UX, and nowawdays automatic upload is disabled by default, and you can select what to upload. Also, the swipe has an UNDO option. Closing this for now.
