### ISSUE TITLE
Current image pin is no longer green

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#923]
In the edit interface on the website, the map pin  that belongs to the currently shown image, used to be green.

This is no longer the case now (I've tried several times, editing different sequences, in different browsers). The current pin is just blue or red, depending on if it's been modified or not. This makes it very difficult to determine exactly which pin corresponds to the current photo.

Also, it seems as if the procedure for switching photos has changed, as I now sometimes need to click the pin before the photo loads, instead of just hovering over the pin. However, this does not seem to be the case all the time, so maybe it's just a delay in the loading.

**Comment by pyrog** [comment]
> The current pin is just blue or red, depending on if it's been modified or not

The image with it key in the URL is always green, even if we click on another one 
http://www.mapillary.com/map/e/CbbBbwPy-EfISLdP4HDhAg

> This makes it very difficult to determine exactly which pin corresponds to the current photo.

:+1: 

> Also, it seems as if the procedure for switching photos has changed, as I now sometimes need to click the pin before the photo loads, instead of just hovering over the pin.

Not today

>  so maybe it's just a delay in the loading.

The delay is a bit "long"

Tested on **Chrome**, **Firefox** and **Safari**

**Comment by pyrog** [comment]
In the map view, the pin of the current image is visible (always green) :smile:

**Comment by pbb72** [comment]
What you are saying is not completely true, pyrog.

Look at the following images, where the URL changes, but the same pin stays green. This did not used to be the case. Previously, when you selected another image (in EDIT move, I am NOT talking about the viewer!), then the corresponding pin would automatically turn green. This is not the case anymore.

![clipboard image 6](https://cloud.githubusercontent.com/assets/1436366/7216757/5f28a3d0-e60a-11e4-8a5e-d20ed82efa19.jpg)
![clipboard image 7](https://cloud.githubusercontent.com/assets/1436366/7216758/655dc60e-e60a-11e4-9c2d-3ea229aea10d.jpg)
![clipboard image 8](https://cloud.githubusercontent.com/assets/1436366/7216759/68f2bd38-e60a-11e4-8b85-47d46a5fd4b2.jpg)

**Comment by pyrog** [comment]
> What you are saying is not completely true, pyrog.

It was incomplete :wink: Sorry, I wasn't clear. :smile:

The image with it key in the URL is always green **[when you load it or refresh it]**…

[![edit 1](https://cloud.githubusercontent.com/assets/2158081/7216877/115597f8-e60f-11e4-873e-d49ed6611de2.png)
CbbBbwPy-EfISLdP4HDhAg
](http://www.mapillary.com/map/e/CbbBbwPy-EfISLdP4HDhAg)
[![edit 2](https://cloud.githubusercontent.com/assets/2158081/7216878/14628d0c-e60f-11e4-98e4-c41631275654.png)
mLhA5dWvL2sW9pXyMKms-Q](http://www.mapillary.com/map/e/mLhA5dWvL2sW9pXyMKms-Q)
[![edit 3](https://cloud.githubusercontent.com/assets/2158081/7216879/16ff2c8c-e60f-11e4-823e-61befac35a80.png)
aXo4rILXljKLbySjKSW8qw](http://www.mapillary.com/map/e/aXo4rILXljKLbySjKSW8qw)

**Comment by pbb72** [comment]
But, can you **confirm** or **deny** that previously, it was always the currently displayed image that had a green pin?

**Comment by pyrog** [comment]
I **confirm** you're comments :smile: 

Markers are **not refreshed** when we click on the direction arrows or when we click or move the mouse cursor over another marker

**Comment by pbb72** [comment]
:+1: Do you also know when this changed, and if it was with a purpose?

**Comment by pyrog** [comment]
> Do you also know when this changed

no

> and if it was with a purpose?

Seem to be a bug :cry:

**Comment by pbb72** [comment]
I agree :smiley:

**Comment by jesolem** [comment]
Awesome thread here guys ;)

This has been like this in the editor for a long time (forever?). Adding as an enhancement to editor for next editor update.

**Comment by pyrog** [comment]
> forever?

Sure?? My memory is not perfect too :wink:

**Comment by pbb72** [comment]
Forever? Are you sure you are understanding my bug report? I am 99 % certain that until a few days ago, the current image was always displayed with a green pin in the editor!

**Comment by knikel** [comment]
@pbb72 It might be me debouncing extra events in #871, will look into that. Thanks for reporting it!

**Comment by pbb72** [comment]
Thanks, it looks like this bug has finally been fixed! Both hovering over a pin and moving back and forth using the arrow icons, updates the green pin.
