### ISSUE TITLE
Editing traffic signs on Chrome is "icy"

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#924]
When I add a new traffic sign, the box *"follow"* the mouse cursor with a delay when I move or resize the box.
Like if the box is *"sliding"*.

This "bug" seem to be more visible when the image is zoomed in.

**Chrome** version 42.0.2311.90 (64-bit) on **Mac OS X** version 10.10.3 (14D131)

**Comment by iav** [comment]
I see this effect only for 2-3 days, only with Chrome browser v.42.0.2311.90 m.
I not see it with Mozilla browsers.

**Comment by knikel** [comment]
This shouldn't be an issue anymore
