### ISSUE TITLE
Tell the game player that he must be logged in to play

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#925]
Anonymous users can't play.

* The message **"Already edited"** is always displayed so user can't validated any pictures.
* User **You** is displayed at the bottom of the leaderboard with **0 points**

![log in to play game](https://cloud.githubusercontent.com/assets/2158081/7220356/965e0d6c-e6c4-11e4-8f96-2c981e87ef7d.png)

* The **plus button** is still enabled but it add a traffic sign box without any handle to move or resize it.
* When adding some "ghost" signs, it's possible to press the save button but the spinner run infinitely.

![gost traffic sign](https://cloud.githubusercontent.com/assets/2158081/7220403/d13070fa-e6c5-11e4-8060-cb6466388e42.png)

**Comment by jesolem** [comment]
We should do this.

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
