### ISSUE TITLE
Service unavailable is blocking whole profile page

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#926]
Currently, requests to https://a.mapillary.com/v2/search/s/ul?... are returning 503 Service Unavailable.

This blocks the whole profile page, even though 90% of all information has been downloaded fine. Manually unhiding the &lt;div ng-show="mode == 'activity'"&gt; element brings up the hidden profile content.

One resource that is failing to load, should not block the rest of the page.

**Comment by iav** [comment]
Got error 503 trying to save roadsign update from browsing mode

there chrome browser error console
Failed to load resource: the server responded with a status of 404 (Not Found)
content_script.js:36 The suggested author is: Mapillary AB, Sweden
userData.jsp?dlsource=tnkeepi&userid=NTBCNTBC&ver=2015.5.20.10.11:340 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
register_server_layer.html?version=2015.5.20.10.11:12 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
mapapp-62f7a832.js:16639 Object
mapapp-62f7a832.js:16639 Object
mapapp-62f7a832.js:16639 Object
https://a.mapillary.com/v2/im/ByRoC-xbjdqZDQYsUALcDQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh Failed to load resource: the server responded with a status of 503 (Service Unavailable)
ByRoC-xbjdqZDQYsUALcDQ:1 XMLHttpRequest cannot load https://a.mapillary.com/v2/im/ByRoC-xbjdqZDQYsUALcDQ/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mapillary.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by gyllen** [comment]
Closing this since its originally opened for profiles. These requests should now be fast.

**Comment by pbb72** [comment]
Wow, the page is so fast now! This looks great :-)
