### ISSUE TITLE
Can't read information panel on computer

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#927]
When the window is full screen ("**paysage**" orientation), the bottom of the information panel is hidden by the *filter* button:
![paysage](https://cloud.githubusercontent.com/assets/2158081/7220503/b4422a7a-e6c9-11e4-82f8-a79e564164a5.png)

:bulb: **Suggestion**:
* Could you display the Information panel below the reduced image?
![reduced image](https://cloud.githubusercontent.com/assets/2158081/7220533/5006cd48-e6cb-11e4-8ec7-e2607335d994.png)
* Could you also display **EXIF information** of the **original** picture ?
(camera, brand, focal length, aperture, zoom…)

PS: It's possible to read all the information text when resizing the window in "**portrait**" orientation
![portrait](https://cloud.githubusercontent.com/assets/2158081/7220508/f195a384-e6c9-11e4-8ee9-1bb5bb0e7a0f.png)

**Comment by knikel** [comment]
The layout has changed, this is no longer an issue. Thanks for the feedback @pyrog!
