### ISSUE TITLE
Page titles on Firefox are not descriptive

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#932]
Since stepping back through the browser history is problematic in Mapillary (pages are not reloaded among other things, see also #584), we should have descriptive page titles so that we can pinpoint the page that we want to jump back to. (For example the profile page, or a specific photo page.)

Besides that, it's a common best-practice to give pages descriptive titles.

Right now, all pages are titled "Mapillary | Crowdsourced Street Photos". I recommend keeping this title only for the front page. Photo pages could be called "Mapillary | [Street Name]" (where [Street Name] is the text that is also displayed below the photo). Edit and blur pages could be labeled "Mapillary | Edit [Street Name]" and "Mapillary | Blur [Street Name]". Simple map views could be "Mapillary | Map". A profile page "Mapillary | [User Name]", etcetera.

**Comment by pyrog** [comment]
Job have been done for previous pages, see #475 :wink: 

But need to be done for new (and future) pages :smile: 
* http://www.mapillary.com/map/games/traffic **Mapillary | Traffic signs game**

Have already a title, but the term "manual" is it really useful?
* http://www.mapillary.com/map/upload/im **Mapillary | Upload Photos**
* http://www.mapillary.com/map/upload/vi **Mapillary | Upload Videos**

**Comment by pbb72** [comment]
What do you consider "previous" pages? I see photo pages from October 2014 that also have the standard "Mapillary | Crowdsourced Street Photos" title.

This does look like a duplicate of #475, but that issue should not have been closed, because it's clearly not fixed.

@pyrog, are you aware that I am talking about the regular photo pages (http://www.mapillary.com/map/im/) and the edit pages (http://www.mapillary.com/map/e/)?

**Comment by knikel** [comment]
@pbb72 We do give names to locations/pages dynamically while you're on the current page (I think that is what @pyrog meant), however we do not persist it in the browser history - these titles are dynamic. Putting this as a TODO.

**Comment by pbb72** [comment]
@knikel, maybe you consider "page title" to be something else then I do, but map and edit pages do not have any other page titles than "Mapillary | Crowdsourced Street Photos". I'm not talking about the browser history, I am looking at the top of my browser window, at the page tabs. The page title that is displayed in the page tab, is "Mapillary | Crowdsourced Street Photos".

I am *not* talking about the bold caption underneath the photo (technically an <h5> tag).

**Comment by knikel** [comment]
@pbb72 Therefore we’re on the same page in that case.

We do display that when browsing the map, I’ll make sure it’s shown in the editor too.
![titles](https://cloud.githubusercontent.com/assets/1574656/7479701/a4ed15ac-f363-11e4-8c00-1988f593c0b8.png)

Would you mind checking this link @pbb72  http://www.mapillary.com/map/im/fZAQqA2YJH_bd2w2B6cQsw ? If you can’t see what I see, this is a bug :)

We fall back to “Mapillary | Crowdsourced …” when there is no location though.

**Comment by pbb72** [comment]
Ha, interesting! This indeed works in Chrome and Internet Explorer 11, but not in Firefox (my browser of choice)... (Unless I have an extension installed that blocks this behavior.)

**Comment by knikel** [comment]
@pbb72 ok, so we got a bit closer, I will investigate this behaviour on FF, thanks a lot for you time!

**Comment by pbb72** [comment]
OK, just restarted Firefox in safe mode, and no page titles. So it's not a extension that is causing this.

**Comment by knikel** [comment]
Closing in favor of #475
