### ISSUE TITLE
Timeout blocks editing interface

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#935]
While editing photos on the edit pages, I'm currently getting regular timeouts (around once every 20 photos) on the URL https://a.mapillary.com/v1/g/(ID1)?client_id=(ID2)&depth=1&maxDirection=1&seqDepth=1 (I guess this is the API URL?)

The result of this is a throbber displayed on the photo, and nothing else happening. I can not switch to other photos anymore. The only thing I can do I save the changes that have been done so far.

A timeout should be reported on the client side, and should not block the possibility to go to another photo.

**Comment by pbb72** [comment]
Comparable to #926

**Comment by jesolem** [comment]
Hey @pbb72 Is this still an issue or was this something temporary?

**Comment by pbb72** [comment]
I'm still having regular problems with the interface "hanging up", probably waiting indefinitely for elements to load. Sometimes it seems to help to restart the browser (Chrome) though.

Hard to pinpoint the problem though, because having the network monitor open clearly makes the browser slower, and many problems are gone when I reload the page for monitoring.

**Comment by pbb72** [comment]
Currently, none if the changeset pages work because of 503 Service Unavailable errors after 30s on https://api.mapillary.com/v1/cs/(some-id-code)

**Comment by ybkuang** [comment]
@pbb72 We are currently upgrading our databases. So the editor is currently affected. Sorry for the inconvenience.

**Comment by pbb72** [comment]
OK, you need a system to display this kind of information on the web pages :-)

**Comment by pbb72** [comment]
Ah, and now there is a message bar! Very good, it wasn't visible until now :-)

**Comment by ybkuang** [comment]
;) we are working on a proper status page for this too.

**Comment by knikel** [comment]
We've added notifications for all requests in the editor. We've got some status pages on the. We'll release them when they'll be more useful to end users and get some nicer visual treatment :wink:
