### ISSUE TITLE
Android: Compass keeps switching to locked forward option on  train

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#936]
Whilst on a fast intercity train with the camera/phone pointed outside the window, I've been noticing the option for the compass direction switching to the lock forward option, which means that it's invalid. An option to lock left or lock right would be more appropriate.

**Comment by smsm1** [comment]
I'm using riding mode.

**Comment by kaitu** [comment]
This is related to #812

**Comment by peterneubauer** [comment]
In riding mode, the compass should be locked, since it is highly likely that the camera is stable wrt to the driving direction, and the risk for metal problems with the built in compass is bigger
We probably should add an option to adjust the camera direction though.

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by smsm1** [comment]
I haven't used the Android app recently so don't know if there has been a fix to allow you to set the direction that the camera is pointing.
