### ISSUE TITLE
Possibly corrupt sequence

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#937]
My last sequence [this](http://www.mapillary.com/map/im/EV5q5YGj2ylPWRdFlX_slg), seems to be corrupted. It was uploaded using `upload_with_authentication.py`, but for some reason the completion of the sequence hung on completion. I entered on manual upload on the site, and found the sequence there, and pushed publication. I am not able to access any photos of the sequence.

**Comment by Skippern** [comment]
From `upload_with_authentication.py`:
```
Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.
Finalize upload? [y/n]: y
Upload a DONE file to tell the backend that the sequence is all uploaded and ready to submit.
Traceback (most recent call last):
  File "upload_with_authentication.py", line 173, in <module>
    upload_done_file(params)
  File "upload_with_authentication.py", line 45, in upload_done_file
    open("DONE", 'a').close()
IOError: [Errno 28] No space left on device: 'DONE'
```

**Comment by Skippern** [comment]
and:
```
Finalizing upload will submit all successful uploads and ignore all failed.
If all files were marked as successful, everything is fine, just press 'y'.
Finalize upload? [y/n]: y
Upload a DONE file to tell the backend that the sequence is all uploaded and ready to submit.
Uploading: DONE
Success: DONE
Traceback (most recent call last):
  File "upload_with_authentication.py", line 173, in <module>
    upload_done_file(params)
  File "upload_with_authentication.py", line 49, in upload_done_file
    os.remove("DONE")
OSError: [Errno 2] No such file or directory: 'DONE'
```

**Comment by Skippern** [comment]
I see now it seems to affect all my newer sequences, including the latest done with the online video uploader, there are currently 10 inaccessible sequences on [my profile](http://www.mapillary.com/profile/skippern).

**Comment by peterneubauer** [comment]
@Skippern the latest of your sequences seems to work. Which ones are failing? Also, is your hard drive getting full so the script can't move files?

**Comment by Skippern** [comment]
There was several that was not working, from the one I linked and newer, but they seemed to work about 1 or 2 days after they was published. I haven’t seen the same in the last I published. I am out travelling so I am not able to do any in depth tests at the moment

Aun Johnsen

**Comment by Skippern** [comment]
Trying to minimize the problem with lack of discspace (managing with transferring from my Garmin VIRB in batches), but main problem is unstable internet connection.
Aun Johnsen

**Comment by peterneubauer** [comment]
I think things are working now with the new viewer rollout. Closing, feel free to reopen @Skippern if things are not ok.
