### ISSUE TITLE
inversed contributor name on picture connection

### ISSUE THREAD

**Issue by Jibec** [mapillary/mapillary_issues#938]
Hi,

Search  on http://www.mapillary.com/profile/jibec/connections for this :
Week 2015-10
 - User cquest
 - - Mar 8, 2015 

we can see that the two first connections have corrects contributors, but the third is inversed. It's easy to tell because of the part of the car that is different ;)

Thanks for your help

**Comment by jesolem** [comment]
We had this a while ago but fixed. Maybe something remaining, we'll take a look.

**Comment by gyllen** [comment]
This feature will be removed for something better (we will start showing only really good matches to other users images instead). Closing this ticket
