### ISSUE TITLE
Statistics : "still processing" count is not correct

### ISSUE THREAD

**Issue by Jibec** [mapillary/mapillary_issues#939]
Hi,

My profile says :  "38640 uploaded images" and "2 still processing".
If you got to my last sequence, there is at least 40 still processing : http://www.mapillary.com/#/map/s/vEBNJuRnRpC8i_Kgt2p_DA

Two possibilities :
1. there is two "still processing" meaning : upload processing and post-upload processing
2. the count is not correct

Btw : why don't you make an opensource library to spread the post-process on contributors PC ? Output (position, modifications, connections, ...) should be on CC also.

Thanks for your help

**Comment by Skippern** [comment]
I have a constant "1 still processing" on my profile, and when uploading a new sequence it seems to say "[number of images in sequence + 1] still processing" - is this a ghost hanging in the system, cache issue, database issue?

**Comment by gyllen** [comment]
We are working on these images. Currently we have 3600 images that has failed to process out of 22 million so we are getting the errors one by one.

**Comment by Skippern** [comment]
Also seems that sequences uploaded by python script, but approved via the web app doesn't appear in "processing", and it can take time for the counter for "uploaded images" to be updated. Currently my profile shows 60102 images uploaded and 14 in processing, while it was just updated with a sequence of ~400 images, either processing count should have been 400 larger, or the total should have been 60500+

I have more images in the pipeline, so if you monitor my account from there you will probably see constant uploading for some time....

**Comment by gyllen** [comment]
@Skippern After manual upload it might take some time for the images to show up, did the images show up eventually for you?

**Comment by gyllen** [comment]
Closing since no answer
