### ISSUE TITLE
Better UI for watching images on http://www.mapillary.com/

### ISSUE THREAD

**Issue by Jibec** [mapillary/mapillary_issues#940]
Hi, when you want to show a place to someone : 
with a big screen : you have a tiny zone for the picture and a huge zone for the map
with a cellphone screen : you have a huge zone for the picture and you can't access the map because of the size of the screen

one example : http://www.mapillary.com/map/im/5OXXGY_FxvQeY_97xo8q5w

can't we have an "navigation view" for having full screen images and a little map on movable frame ?
If the screen is too little, the map should be on the bottom.

Upgrades could be to merge pictures to make a patchwork when possible.

thanks for your great work

**Comment by jesolem** [comment]
Thanks for the feedback. We're working on this right now. Stay tuned!

**Comment by domdomegg** [comment]
This can be closed now as this is done with the 2 tabs in the map v2 @Jibec @knikel

**Comment by Jibec** [comment]
thanks for great work!
