### ISSUE TITLE
add warning when you leave the manual upload page and a upload is pending

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#942]
If this is  technically to difficult just add a waring to the page: "leave this tab (and your browser) open till the upload is finished"

**Comment by jesolem** [comment]
Makes sense.

**Comment by knikel** [comment]
@angelday, @retro: We should have that in the uploader, right?

**Comment by angelday** [comment]
This is addressed in the new uploader ( https://www.mapillary.com/app/uploader ), closing. @de-vries let me know if this doesn't answer your question.
