### ISSUE TITLE
Uploaded images count is off

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#944]
The uploaded images count on [my profile](https://www.mapillary.com/profile/de%20vries) is lower than on [places/the netherlands](https://www.mapillary.com/map/places/netherlands) which shouldn't be possible. (Not all the time tho, since [places/the netherlands](https://www.mapillary.com/map/places/netherlands) gets updated less frequent) The numbers differ by about 450.

I think, but am not sure, that the issue started when I did a upload (I think it was a manual one) a few weeks ago. I was then under the impression that the photo's (about 450) were not added to the uploaded images count on my profile page.

**Comment by de-vries** [comment]
yesterday I uploaded 4 sequences (366 photos) and they are not added to the  uploaded images count on my profile page. The are also not visible on the Recent Activity applet. [places/the netherlands](https://www.mapillary.com/map/places/netherlands) isn't updated yet so I cant tell if the photo's are counted there.

**Comment by de-vries** [comment]
user [peewee32](http://www.mapillary.com/profile/peewee32) also has more photo's on places/the netherlands than his profile page.

**Comment by de-vries** [comment]
>yesterday I uploaded 4 sequences (366 photos) and they are not added to the uploaded images count on my profile page. They are also not visible on the Recent Activity applet.

update: they are visible on the Recent Activity applet from the moment #1002 was fixed, but now my image count is only half of what it used to be. And from a quick look at other profile pages it looks like everyone is affected.

**Comment by jesolem** [comment]
@de-vries we're having a glitch today, affecting all stats and they are roughly halved on the site @peterneubauer is on it.

**Comment by de-vries** [comment]
@jesolem, so that leaves, for this issue, only the ~450 missing photos an those from the users mentioned in my third comment. Maybe a glitch that went unnoticed?

**Comment by jesolem** [comment]
@de-vries Stats should work now (soon). Can you see the 450 photos on the map? If not then we need to investigate, they are somewhere.

**Comment by de-vries** [comment]
@jesolem, I don't know which photos it are. When I noticed the difference between the numbers on the stats page and my profile I remembered having the impression of photos not getting counted weeks before, but I wasn't even sure at the time. It might even be that the number on the stats page is to high, instead of the number on my profile to low. (sorry for the vagueness) 

The only hint I can give you is that the exact difference between the numbers is 428. You could look for an upload of that number. It might be multiple sequences, so if it was a manual upload that probably means multiple uploads. (again, sorry for the vagueness)

**Comment by jesolem** [comment]
@de-vries OK, assigning to master detective @gyllen

**Comment by de-vries** [comment]
@gyllen, I've got a new hint for you and it might be a useful one this time ;)

The difference between the current uploaded images count on my profile (22757) and on places/the netherlands (23216) is now 459. So it increased by 31 since last time I checked. I didn't upload anything in the last 10 days, so I'm confident those numbers are not influenced by still processing images.

[**Here**](http://www.mapillary.com/map/im/_EXl-pIlTuCfvfoSCVkmdw) I've uploaded a sequence of 31 that by all logic must be the reason for  the increase of difference. 

good luck finding the cause of this.

**Comment by gyllen** [comment]
This is a border and shape issue see answer in #508 adding borders label

**Comment by peterneubauer** [comment]
We improved the shapes now. Is this better now?

**Comment by peterneubauer** [comment]
Closing this if no one objects.
