### ISSUE TITLE
Mapillary stopped

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#947]
today the android app stopped twice. I got a message saying "Mapillay is gestopt". Which is dutch for "Mapillary stopped" or "Mapillary has been stopped". can be both.

It happened after taking [this](http://www.mapillary.com/map/im/V9UcmKQN9YxlMyHYSCzK4A) and [this](http://www.mapillary.com/map/im/TUKjW7OYxZVunI0ZWmPrwA) photo. I'll send a log by email.

**Comment by peterneubauer** [comment]
@de-vries did this happen during the camera was on or while you were reviewing sequences? I'm seeing a NullPointerException in the review activity, which is fixed in the latest dev version (can get it to you if you want)

**Comment by de-vries** [comment]
During the camera. It happened today 3 times (took 1000+ photo's), i'm not sure if I can recall on what moment. do you want the logs?

About the dev version, if you want it tested get it to me, I always like latest stuff.

**Comment by peterneubauer** [comment]
Yeah,
send the logs. It seems on some models the camera is throwing exceptions
after a number of images - I'm imagining the low level drivers not being
tested hard enough for our use case :/

**Comment by de-vries** [comment]
I finally found time to send the logs. I had the bug again a few times today. details are in the mail.

**Comment by de-vries** [comment]
I just send you a mail with my log, since it happened 5 more times yesterday

**Comment by peterneubauer** [comment]
@de-vries , can you join https://plus.google.com/communities/104427435312937590517 so you can test pre-releases and check out improvements?

**Comment by de-vries** [comment]
@peterneubauer I'd be honoured

**Comment by de-vries** [comment]
I didn't had this bug for a long time now, but that's probably just because I now have a action cam and don't use the app for long sequences any more. closing this because the symptoms were vague at best.

**Comment by peterneubauer** [comment]
Thanks for going the extra mile @de-vries!
