### ISSUE TITLE
Bug in sequence frequence on android

### ISSUE THREAD

**Issue by oddityoverseer13** [mapillary/mapillary_issues#948]
While messing with settings in the android Mapillary app this morning, I increased the sequence frequency to two seconds. Then I realized that'd be too slow for my bike ride, so I tried dropping it back down to 1 second. The slider dropped down, but the actual number didn't. I'm 90% sure this is a bug.

**Comment by peterneubauer** [comment]
True, sounds like a bug. will investigate.

**Comment by jrcarlsen** [comment]
In app/src/main/res/xml/preferences.xml the option pref_key_sequence_delay is configured for a range of 2-10 seconds. I am new to the code so I am not 100% this is the correct place to fix this.

**Comment by jrcarlsen** [comment]
A pull request for this bug has been submitted.

**Comment by jrcarlsen** [comment]
Peter, is there any chance you can fix this one soon? I have to go around much slower and often stop completely to catch all the street signs for OSM use.This weekend I'll be going around a lot, and I'll be able to cover a much bigger area for you guys if this is fixed.

**Comment by peterneubauer** [comment]
@jrcarlsen thanks for the PR, merged and released as alpha, join the program and test! https://github.com/mapillary/UserGuide
