### ISSUE TITLE
How can I delete a sequence?

### ISSUE THREAD

**Issue by chrismcnally** [mapillary/mapillary_issues#949]
I use the android app and the web app,  I've been away from Mapillary for a month and it seems a lot has changed, and I cannot figure out how to delete photos and sequences after they are uploaded.  I'm pretty lost actually. Is there any documentation on how to edit? I need to delete a sequence and re-upload but I cannot find a way in the web app or the Android app.

**Comment by de-vries** [comment]
click the edit button under the photo, then on the edit-page you'll find a 'Hide the whole Sequence' button.

**Comment by chrismcnally** [comment]
I don't have an edit button. Using the android app I choose Feed, select a
set and I see my photos, which I can navigate, but no edit button. I've
done exactly what you said with the old app.

**Comment by jesolem** [comment]
The app loads a web view that was configured to be easier to use from touch screen devices (you can interact with gestures on both the map and photo). This change happened about 2 months ago and I think this is what you're seeing here.

Open the page in another browser or from the website and you can edit.

**Comment by jesolem** [comment]
Anything we need to do here or can this be closed?

**Comment by chrismcnally** [comment]
It can be closed. Thanks.
