### ISSUE TITLE
Feature request: pass filter and view parameters in URLs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#950]
Could you store the filter state in URLs of map view, edit view… ?
(Panorama ON/OFF, Traffic signs ON/OFF, Season=winter, show comment panel, information panel, filter panel, small view… play sequence…)

It will be useful to make links in github…

Thanks :smile:

**Comment by pyrog** [comment]
In the traffic sign game, I click on the link to see the current image on the map but I don't see the traffic signs.
I should:
 1. Open the filter panel,
 1. Click on traffic sign and
 1. Close the filter panel.

It take time and it's boring.

Could you:
* Set the traffic sign filter to on with the URL    
or
* Add a shortcut to set quickly this filter (see #594)   
or
* Use a cookie to remember my settings?

**Comment by pyrog** [comment]
> It will be useful to make links in github…
See #977 comment

**Comment by jesolem** [comment]
Good suggestion.

**Comment by rudolfmayer** [comment]
I'd also like to have this feature - ideally this would always be in the URL so you can simply copy/paste it.

A less ideal alternative would be to request a permanent link that would have this information set (such as e.g. the share map link in Google Maps, could be also with a short URL, but I think that this is less important)

**Comment by knikel** [comment]
That's coming in the upcoming update of mapillary.com

**Comment by knikel** [comment]
@nickplesha has been hard at work when it comes to this feature! We've released configurable embeds with whatever you see in the viewer + filters, read more here: http://blog.mapillary.com/update/2016/11/30/embed-mapillary.html
