### ISSUE TITLE
Two problems with Sony Xperia Z3

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#951]
I have encountered two problems with the Xperia Z3 and the Mapillary app:

1) when using the magnetic power cable the pictures are recorded upside down. It only happens with the magnetic power cable when it is used as power supply. It's not the magnet itself that causes the problem.

2) (similar to issue #222) In order to use the Mapillary car mount and the magnetic power cable I have to insert the phone in such a way that the phone's camera button is permanently pressed. In case of a strong  shake this seems to cause the same problem as described in in #222. Looking at the produced picture sequence, after the last good picture there are two unreadable .jpg files of 6 M each.

**Comment by peterneubauer** [comment]
That's the first time I hear that. Do you have one of these pictures to check? We are listening to the orientation sensors - can you check if you get the same kind of upside down pics with the normal camera?

**Comment by voschix** [comment]
Luckily enough, the upside-down pictures were mainly a false alarm. 
The pictures, when loaded normally with the app, are correctly inserted in the database.
What happens is the following:
My phone is mounted upside down in the car in a Mapillary mount.
Without the magnetic power cable, the Mapillary camera screen looks like this
![screenshot_2015-04-27-18-24-18](https://cloud.githubusercontent.com/assets/11076112/7352814/fd1f633e-ed0e-11e4-8ed7-e0728b2cd2cd.jpg)
When I connect the magnetic power cable only on the phone side, nothing changes.
When I connect the magnetic power cable also at the other end, i.e. to a powered USB port then I get this screen:
![screenshot_2015-04-27-18-25-18](https://cloud.githubusercontent.com/assets/11076112/7352861/4d2ade44-ed0f-11e4-861f-e440df81fb0f.png)
And when I use Windows Explorer to look into the memory of the USB-connected phone it looks like this:
![clipboard01](https://cloud.githubusercontent.com/assets/11076112/7352880/85d2cb80-ed0f-11e4-9e21-0c6c1b4f51cf.jpg)
*But*, when I check the "Orientation" in the EXIF data of the pictures, they are correctly marked "Rotate 180°"
What remains strange is the effect of the *powered* magnetic power cable, rotating the display and the picture orientation. It does not happen when the phone is powered with a normal mini-USB cable.

Sorry to have caused a mainly false alarm.

**Comment by peterneubauer** [comment]
Mmh,
this sounds to me as if the phone is assuming the phone to be in a holder since in the cradle, the connectivity programs are starting. With the magneting cable, the direction is confused and gives wrong orientation to the apps. What about a normal camera picture - is the same happening there?

**Comment by voschix** [comment]
You are possibly right that the presence of the magnetic power supply could
be interpreted as the camera being in a cradle with the cable at the bottom
of the camera.

Sorry I forgot this:
pictures with the normal camera app do not have the problem. It seems to be
specific to the Mapillary app.

Volker

**Comment by peterneubauer** [comment]
How about another camera app? I'm strongly suspecting that the built in camera app might be using some internal APIs that are not exposed to other apps. Closing this for now.
