### ISSUE TITLE
In traffic sign game Ireland apears in EU section, instead of US one

### ISSUE THREAD

**Issue by XANua** [mapillary/mapillary_issues#952]
http://www.mapillary.com/map/im/gohcqDmmjobIByVjclPK_Q

http://en.wikipedia.org/wiki/Comparison_of_MUTCD-Influenced_Traffic_Signs

**Comment by pyrog** [comment]
See also #882

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
