### ISSUE TITLE
Default position of traffic sign area in traffic sign game

### ISSUE THREAD

**Issue by XANua** [mapillary/mapillary_issues#953]
Default area for new traffic sign apears in the middle of the photo, in a fixed size, regardless to current zoom and portion of image visible. It's lowers usability of a tool, especially when that area appears outside of current portion of image.

**Comment by de-vries** [comment]
mentioned in #633

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
