### ISSUE TITLE
first use many problems

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#954]
Can't upload pictures, even those I made with your app. Error: "Fehlerhafte Dateien (diese werden nicht hochgeladen) "
Problems with the app:
- Cann't switch off the sound, the setting doesn't work

- Made about 500 pictures in different sequences but the app still says. "Your feed is empty".  I moved the app to the SD-card, before it works.

-The colors of the pictures aren't very good, is there an automatic white balance?

**Comment by jesolem** [comment]
Thanks for reporting. What app/phone is this? iOS/Android/WP

(the feed get's populated after the photos have been processed by the backend, so if upload does not work you will not get anything in the feed.)

**Comment by wegavision** [comment]
It's a Huawei Smartphone with Android 4.2
Now there are 59 of 500 pictures uploaded the others are lost. One personal picture is also uploaded, how can I delete this?

**Comment by jesolem** [comment]
Assigning to our Android person @peterneubauer to investigate.

You can hide any photo if you click the "edit" button under the photo on the website.

**Comment by peterneubauer** [comment]
@wegavision are you sure the photos are lost? Under Preferences-> Developer you should see the location of the images on your device, can you check with a file explorer app that the folder is really empty? Also, what is your Mapillary username?

**Comment by peterneubauer** [comment]
@wegavision feel free to send a log when you encounter problems again.

**Comment by wegavision** [comment]
I had to delete them, because I want to make new photos and didn't found a way, storing them on the SD-card. Even moving mapillary to the sd-card, the storage-folder will not move to the card. The entry in the settings doesn't work. 

Today I made new pictures, some of them are good others not.
This hasn't a good white-ballance
http://www.mapillary.com/map/im/iDIsgdobKlCoaZWlHUbQUA
this is ok
http://www.mapillary.com/map/im/YnAZDkimOY5Xp_-8t0Hqow
Does the app use the settings of the system-app for the camera? I never had these problems with the colors before. Or does anyone knwo a batch converter for the white balance?

I still can not turn off the sound of the camera. I see there is an open bug, so I am not the first who reported this.

**Comment by peterneubauer** [comment]
@wegavision you feed should not be empty anymore since you now uploaded images? http://www.mapillary.com/profile/wegavision/activity

Also, we are letting the camera decide how to expose the images - it's on auto exposure so there is very little influence from the Mapillary app. The white balance is on auto and might be influenced by tinted front screens in the ar of course etc.

For the sound, the API for that was introduced first in 4.2, and it depends on the vendor to implement it. It might be that your phone is not supporting the setting (yet).

**Comment by peterneubauer** [comment]
For the location of the images folder - can't you press the folder location and choose another one? You need to make sure that the app can write into that folder though since Android is picky with file permissions for apps on external media.

**Comment by wegavision** [comment]
I can chance the location in the setting to storage/sdcard1. This should be my micro-sd. But the photos will still go to storage/sdcard0.

**Comment by peterneubauer** [comment]
That is strange.

Can you change the location, then take some shots and send the log?

**Comment by wegavision** [comment]
How can I get the log? I find only the way: bluetooth, Sms and gmail. My computer hasn't bluetooth, I have no phone card in the smartphone and no gmail account.

**Comment by peterneubauer** [comment]
The "Send logs" should be in the main menu of the mapillary app.

**Comment by pbb72** [comment]
From my experience, it seems like Mapillary sometimes "falls back" to saving photos on the internal storage (sdcard0) even though your preference is storing on the SD-card. Maybe the card was not fast enough at that moment, or some other temporary issue. After that, the images seem to have disappeared when you restart the app. Using a file manager to move the Mapillary folder from the internal storage to the SD-card, allows you to see these disappeared photos again, and upload them.

In the beginning you mention you can't upload images made with the app. Are you referring to the manual upload feature on the website? In that case it's true, images made with the app cannot be uploaded through the website. I'm not sure why, but you can't. The easiest is to put them back on your SD-card and upload them with the app, or there is a Python script available for download that can be used to upload these images from the computer.

If you don't have email configured on you phone, I think you can find the log file in the root of the internal storage (sdcard0) as "mapillary.log", but I am not certain about that.

**Comment by wegavision** [comment]
Now I use the app for two weeks and on this smartphone (Huawei) I can change all yes to no and nothing happens. It uploads the pictures when it finds Wifi, it makes sound etc.
Perhaps I found an other smartphone, but mapillary needs android 4.1 so I can't use my old THC desire.

**Comment by peterneubauer** [comment]
@pbb72 @wegavision yes, if there is no suitable external storage found, Mapillary will use the internal storage. An improvement has been suggested - looking for pictures on all mounted devices, I'll see how much complexity that adds.

@wegavision what did you change to "all yes"?

**Comment by wegavision** [comment]
I only noticed that the sound is on whatever there is on/off, the app uploads pictures whatever it is dissable on battery or not and so on. Sometimes it paused on stop but somestimes not etc.Therefor  I am the only with this bug, I think it is the smartphone. And the pictures aren't very pretty so I will buy an other. (But with my lumia 920 there are other bugs...)

**Comment by peterneubauer** [comment]
@wegavision the battery settings are only preventing you from taking new pictures as having the camera preview and the sensors on is draining the phones battery a lot. How did it go with the new phone?

**Comment by peterneubauer** [comment]
So, how are the new 1.60+ releases? Is this still prominent?

**Comment by rsahlin** [comment]
Please retest with latest 2.X release
