### ISSUE TITLE
Missing Photo - Upload iOS 8.3

### ISSUE THREAD

**Issue by canadarunner** [mapillary/mapillary_issues#957]
I've uploaded several sequences of photos (some approx 3 days ago, others 1 day).
I uploaded them from my iPhone 6, iOS 8.3, newsest version

**Comment by jesolem** [comment]
Are you still missing them? If so, what is your Mapillary username?

**Comment by canadarunner** [comment]
Hi Jan, yes I still miss them, my username ist canadarunner

**Comment by gyllen** [comment]
Doing some investigations, How many image were there and do you have roughly a time when you uploaded them. Also do you have the time when you captured them. Sorry for the inconvenience.

**Comment by gyllen** [comment]
There are several photo from the 19th of april on your profile. Was it in connection to these that you uploaded the new ones?

**Comment by canadarunner** [comment]
From the 19th i miss only some at the end of the last sequence. But I miss a whole track from the 24th…
No there was no connection between these two uploads

**Comment by gyllen** [comment]
How many photos do you think it is. Is it in the thousands or the hundreds?

**Comment by canadarunner** [comment]
The missing photos from the 24th are around 700 photos.

**Comment by gyllen** [comment]
And upload was from the iOS app? Also the upload did happen on the 24th, what time exactly, do you know that?

**Comment by canadarunner** [comment]
Yes, from the iOS app. It should take the whole afternoon, so approx. from 11-15 (GMT+1)

**Comment by gyllen** [comment]
What date were the images captured? Going through all uploads and one key is the actual capture time.

**Comment by gyllen** [comment]
I found your images, they failed in our pipeline. Investigating why.

**Comment by gyllen** [comment]
We have located the images and now also the problem. We switched your emails a couple of weeks ago and at the moment we are using emails as a tag in the images (as a part of a verification process). The switched email confused our servers. So can you for safety make sure that you login/logout of the app.

We have your images and will manually enter them into our system. Please allow a couple of days for this to go through. Thanks for reporting this and sorry for the inconvenience.

**Comment by canadarunner** [comment]
OK, thank you very much!! I was sure that I logged me in with the new email, but, Yes, I wil!
Thank you very much!

**Comment by canadarunner** [comment]
Hi Johan, are the images already imported in the system?

**Comment by gyllen** [comment]
Hi @canadarunner not yet. Its on our list, we had a super busy week though. I make sure that I will personally import them the following week. Sorry for the delay.

**Comment by canadarunner** [comment]
Thanks, no problem! Only want to check the status ;-) 
Have a nice sunday!

**Comment by canadarunner** [comment]
Hy Johann

I've got another problem and I'm not sure if it's due to your manual import.
When I'd like to approve traffic sign in other sequences I got this message:

(Normally I do this on my Notebook, but on the Phone it looks the same)

**Comment by gyllen** [comment]
@canadarunner A bump here, please know we have not forgotten about your images. If you read this months newsletter you will see that we have been quite busy though ;)

**Comment by canadarunner** [comment]
Hy Johann
I don't want to pressure you, but I first want to clean up my images until I upload the new ones! And during the time, they filled up my phone…
Would be cool if you can add the images!

**Comment by canadarunner** [comment]
Hy Johann

Are my images up?

**Comment by gyllen** [comment]
Hi @canadarunner sorry for the delay. I have not forgotten about you. Will see if I can squeeze in the fix for your images today. In the meanwhile there should be no problem uploading your new images :)

**Comment by gyllen** [comment]
Hey, I found and added some of your old photos. Sorry for the delay :(

**Comment by canadarunner** [comment]
Thanks!! Cool :)

**Comment by gyllen** [comment]
@canadarunner Can you see the images on your profile?

**Comment by canadarunner** [comment]
I checked it already, But I was only able to find the images from the 25th April. But there should also be some from the 24th April!

**Comment by gyllen** [comment]
Aha, I might have just got your images from the 25th then. Do you know how many there are from the 24th?

**Comment by canadarunner** [comment]
I would roughly estimate about 700.
