### ISSUE TITLE
Wrong sequence-key link in picture information

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#958]
In the picture "Information" the Sequence Key link is wrong. The URL is a non-existing sequence key, that contains the image-key  number instead of the sequence-key number - see attached screenshot
![wrong sequence key link](https://cloud.githubusercontent.com/assets/11076112/7336712/a16db0f8-ec0b-11e4-92e5-121bda1f0297.jpg)
.

**Comment by jesolem** [comment]
We'll investigate. Looks odd.

**Comment by knikel** [comment]
This has been fixed
