### ISSUE TITLE
Image in blur editor is too smal

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#960]
The maximum downloadable resolution of a photo is 2048x1536 pixels. At this size, many more details are visible than in the blur editor, where photos are scaled to 800x600 pixels.

The blur editor needs to show all details, and preferably maybe even a blow-up (2x or 4x) view, so that we can be certain we don't miss any details that need to be blurred out.

**Comment by jesolem** [comment]
Now you can edit on the large image in the new viewer. Closing. Thanks @pbb72 !

**Comment by pbb72** [comment]
Am I missing something, @jesolem? In the current viewer on a full-HD screen, the image is still scaled down to about 50% of the full resolution. I've been looking for zoom buttons like we used to have on the old viewer, but I don't see them either.

Again, preferably I would even like a 2x or 4x zoomed-in view to check for any missed details.

**Comment by jesolem** [comment]
Ah. I get it now. @knikel is working on a zoom tool for the new viewer. 

re-open and assigning

**Comment by pbb72** [comment]
Super! :-)

**Comment by oscarlorentzon** [comment]
Zooming in regular photos is tracked here: mapillary/mapillary-js#112

Higher res than 2048 is tracked here: mapillary/mapillary-js#92

**Comment by pbb72** [comment]
@oscarlorentzon can you explain what a "perspective image" and a "tiled panorama" is?

**Comment by oscarlorentzon** [comment]
A perspective image is just a regular, flat image that you take with the phone, i.e. not a panorama. 

The tiled panorama issue applies to regular photos as well. It just means that we can make smaller tiles from a high resolution photo and download only the parts of the photo that we need when we zoom in. Then we can see the part of the photo that we are looking at in high resolution while keeping the rest of the photo at the lower resolution. Then we do not need to load the complete (and potentially very large) high resolution photo immediately.

**Comment by pbb72** [comment]
Very cool, this would result in a kind of loupe function where you only enlarge a part of the photo?

**Comment by oscarlorentzon** [comment]
Yes, you could describe it like that. Enlarging the part of the photo that we are interested in based on where we zoom.

**Comment by oscarlorentzon** [comment]
With the pan/tilt/zoom functionality for all photos I consider this issue to be resolved.

**Comment by oscarlorentzon** [comment]
Full resolution image tiling has been deployed so you can now see all the original pixels when zooming in while editing.
