### ISSUE TITLE
Map view in edit window is too small

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#961]
All editing in the edit window centers around the map view. Either the editing is done in the map view (moving pins), or the results of edits is displayed in the map view (changing compass angle, hiding images).

Yet, the map view is tiny. It's a bit under 400x400 pixels big. Even the image/sequence settings have a bigger area at ca. 400x530 pixels. The photo, that is only needed as reference on this screen, is over 800x600 big.

Please make the map as big as possible in this screen. Can it not be the same as on the viewer screen, with a full-screen map?

**Comment by knikel** [comment]
@pbb72: Does the new sequence editor solve this issue for you?

**Comment by pbb72** [comment]
Yes thank you, very good now! I like being able to switch between big photo and big map.

**Comment by gyllen** [comment]
@pbb72 @knikel Im always happy when we manage to close really old issues like this 🎉
