### ISSUE TITLE
sequence pictures not showing up

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#963]
I shot some small sequences last week, but they are not showing up in the map.
However:
  - they are visible on my profile page
  - the track is showing on the regular map (but not the pics)
  - thumbnails are showing in the related pictures (eg. http://www.mapillary.com/map/im/sVy6hp9Fwp9hVQIo0Q3k9Q has two related pics from http://www.mapillary.com/map/im/9E91tMwqHbC2vcgKigBKdg)
  - pics show up in my activity feed as having been added to the map

sequences:

  - http://www.mapillary.com/map/im/jNJKRxkDXKSsDR_kz9asTw
  - http://www.mapillary.com/map/im/9E91tMwqHbC2vcgKigBKdg
  - http://www.mapillary.com/map/im/_GAiWUtk_L18tvBwbi2_nw
  - http://www.mapillary.com/map/im/_0MDfIdFh5h_Q9VJpysKrQ

**Comment by peterneubauer** [comment]
I resent the sequences of that day to the server. They should be ok now?

**Comment by mprins** [comment]
yep; they show up and I can edit.
