### ISSUE TITLE
Allow to upload selected sequences only

### ISSUE THREAD

**Issue by rudolfmayer** [mapillary/mapillary_issues#964]
When having multiple sequences, and not being able to review all of them at once, it would be great if one could select a specific sequence to be uploaded (and not processing any of the other sequences)

I guess the easiest implementation would be for the user to disable "upload picture in background", and then at the sequence review screen have an option to upload this specific sequence.

A more user-friendly nicer option would not require me to turn off background uploading. However, one should also not need to mark each sequence as uploadable, so one option could then be to blacklist which sequences are not yet to be uploaded., and all the others would get uploaded in the background automatically.

**Comment by jesolem** [comment]
We have this for iOS and could do the same on Android. Would have to be with background uploading disabled though. 

-> @peterneubauer

**Comment by peterneubauer** [comment]
Yup,
I think that sounds like a good addition. Will look into it at for the next release.

**Comment by vincentdephily** [comment]
That's something that I really missin the app too. But I'd like review to have granularity at the indivdual photo level :

* Photos can have 3 states: accepted, rejected, or unreviewed (currently the "accept" button is a no-op that just display the next image).
* By default, opening a sequence displays only unreviewed photos, but it should be possible to view/change the state of already-reviewed photos.
* Provide a "mark all other photos as reviewed" button for each sequence.
* When all photos in a sequence are either accepted or rejected, the sequence as a whole is reviewed and uploadable.
* The "background upload" setting gains and additional "only reviewed sequences" value.

Hopefully this strikes a good balance between carefree and nitpicky uploaders, and isn't too much work to implement ?

**Comment by peterneubauer** [comment]
Mmh,
This is a bigger change since we need to hold review state over restarts.
Nevertheless a good suggestion!

**Comment by HolgerJeromin** [comment]
moving the sequence folders in special subfolders (unreviewed, reviewed, upload) would be easy and allows sorting via desktop computer if connected via usb cable. I do most reviews on my big screen.

**Comment by vincentdephily** [comment]
Folders sound like a good simple solution.

I'm not sure what the difference between "reviewed" and "upload" be in your example ? It seems to me that anything that has been reviewed can be uploaded. The 3 categories I has in mind were unreviewed, accepted, rejected.

**Comment by HolgerJeromin** [comment]
The difference between "reviewed" and "upload" can be used to have a priority in uploads. Think about 8000 "boring" photos and in between is a interesting sequence which i want to upload with priority. 
I could review all and push only one sequence in the upload batch.
But this is probably not needed and i bit too much. You are right.
Personal i would delete every "rejected" images.

**Comment by vincentdephily** [comment]
Never felt the need for "upload ASAP" usecase myself, but it's understandable. However, you've probably marked a good chunk of those 8000 boring photos as accepted already (otherwise they wouldn't be in the upload queue), so what you want is a "put this photo on top of the upload queue" function ? Sounds quite different from the current topic, maybe you should create a separate issue for it ?

Concerning the "delete VS mark-as-rejected", it's just to prevent acidental deletes (happened to me more than once) and because sometimes the threshold for deletion change halfway through the review because I see that 80% of my images have the same imperfection, so I decide to ignore it.

I admit it's not the most important distinction (unreviewed vs accepted is), and maybe some users would prefer to free up disk space ASAP instead. Your call.

**Comment by HolgerJeromin** [comment]
I also have the "80% of my images have the same imperfection" thing often. Thats why i prefer reviewing on desktop, where it is easier to get an overview of the status of a sequence.

**Comment by rudolfmayer** [comment]
I guess the discussion is indeed a bit digressing... So, maybe opening a new issue would indeed be good if you want to continue discussion

**Comment by peterneubauer** [comment]
upload selected sequences is out in the latest alpha.
