### ISSUE TITLE
Navigation arrow don't work

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#965]
Up navigation arrow isn't responsive (no network request triggered, no error in console)
[AxQRL_C083RnqLO4XDwm5w
![navigation arrow is not responsive](https://cloud.githubusercontent.com/assets/2158081/7373998/0b33f55e-edd0-11e4-981b-2f5eab897e02.png)](http://www.mapillary.com/map/im/AxQRL_C083RnqLO4XDwm5w)

Here [WmEge8uFkkoiE4eCl5p-BA](http://www.mapillary.com/map/im/WmEge8uFkkoiE4eCl5p-BA), both arrows are unresponsive.
(This seem to be the case for all images in **all sequences**)

**Comment by ybkuang** [comment]
@pyrog Can you check again? It should be fixed now.

**Comment by pyrog** [comment]
Fine, Thank you :smile:
