### ISSUE TITLE
Editing traffic signs in the game view is difficult

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#966]
The picture width is near 100% of the window, so I can't see buttons below it.
![game view full width](https://cloud.githubusercontent.com/assets/2158081/7374707/24d48b64-edd4-11e4-861c-e6b74cbccd52.png)

I should:
 1. Scroll down the page,
 1. Click on the plus icon,
 1. Scroll up,   
then
 1. Resize and move the new traffic sign.

Steps 1 and 3 take time and are boring :wink: 

Tip: resizing the window avoid this problem, 
![game view resized](https://cloud.githubusercontent.com/assets/2158081/7374718/32097aba-edd4-11e4-94f6-5eab00e15b45.png)

but if I go to the map view the map is not visible
![map view resized](https://cloud.githubusercontent.com/assets/2158081/7374734/49f83d00-edd4-11e4-9dbe-21a24b8247fc.png)

(so I should resize again the window to it's original width)
![map view full width](https://cloud.githubusercontent.com/assets/2158081/7374740/50f477ae-edd4-11e4-9d80-9ac99216e833.png)

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
