### ISSUE TITLE
Add tutorial or tips to produce better pictures

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#967]
Could you give advices to contributors to produce good pictures?

For exemple:
* To **avoid reflections on the windshield**, move the camera to the bottom of the windshield, closer the dashboard   
[![](https://d1cuyjsrcm0gby.cloudfront.net/Ik4h5ig7zL-w2dQ4Odko9A/thumb-320.jpg)](http://www.mapillary.com/map/im/Ik4h5ig7zL-w2dQ4Odko9A)
[![](https://d1cuyjsrcm0gby.cloudfront.net/TNXwqvHuHek4Y63YSOPzFQ/thumb-320.jpg)](http://www.mapillary.com/map/im/TNXwqvHuHek4Y63YSOPzFQ)

* To **avoid blurred pictures**, set your camera in manual focus (set to infinity)

**Comment by travel193** [comment]
Hi Pyrog,
That's definitely a good idea. We are working on getting a wiki up and running now to include all knowledge on things Mapillary and foremost is capturing great sequences. I'll post it the info here once it has been compiled.

**Comment by eugensim** [comment]
It must be said that the most beautiful sequences are made by manual upload - using the camera with continuous shooting mode (burst mode) then geotagged with Geosetter by syncronized them by a gps file (.gpx)

**Comment by pyrog** [comment]
* To **avoid blurred pictures** in walking mode, disable the automatic mode, then walk, stop, take a picture and so on…

[![](https://d1cuyjsrcm0gby.cloudfront.net/Tazyt7CaNX69NV_iiAD4Lg/thumb-320.jpg)](http://www.mapillary.com/map/im/Tazyt7CaNX69NV_iiAD4Lg)

**Comment by domdomegg** [comment]
* To avoid blurred pictures when still, try leaning the camera on a still, flat surface, eg. A railing, side of a wall or tree stump
* If you have a slow internet connection, try using lossless or almost lossless compressors that do not remove EXIF data, eg. ImageOptim (Mac).
* To avoid reflections on the windshield avoid white objects near the dashboard, as they easily reflect light into the camera - look out for parking tickets!

Of course these are in addition to the other tips, so merge the reflections one :)

I use a Mac for Mapillary, so if someone could recommend an equivalent for ImageOptim on Windows that would be appreciated. Will take a few useful screenshots for importing from Android or iPhone and changing settings in ImageOptim.

**Comment by domdomegg** [comment]
To avoid your photos getting denied by the server, compress them so that they are <8.5 MB

**Comment by domdomegg** [comment]
Wrote an entire section to put on the end of http://www.mapillary.com/instructions.html and/or http://www.mapillary.com/instructions.html

```html
<h3 id="transfer-photos-ios">Transfer photos from iPhone/iPod/iPad</h3>
<ol>
	<li>If you haven't already, <a href="http://www.apple.com/itunes/download/">download and install</a> iTunes.</li>
	<li>Open iTunes</li>
	<li>Connect your iDevice to iTunes (via USB preferably, as it gives faster transfer speeds)
	<li>In the top left, in the toolbar click the device icon, then in the left column select 'Apps'<br><img src="iphone_import_1.png" alt="iTunes iPhone sync panel" /></li>
	<li>Scroll down to find a 'File Sharing section'. Select Mapillary on the left, and select the folders you wish to copy.<br><img src="iphone_import_2.png" alt="iTunes iPhone file sharing with Mapillary" /></li>
	<li>Press 'Save to...', and select a suitable location for the folders to be stored. The progress will be shown in the top activity bar of iTunes</li>
	<li>Once it has finished copying, you can then eject your device and disconnect it from your computer</li>
</ol>

<h3 id="transfer-photos-android">Transfer photos from Android</h3>
<ol>
	<li>Mac only: <a href="https://www.android.com/intl/en/filetransfer/">Download Android File Transfer</a></li>
	<li>Connect your Android device to your computer. You will probably need a microUSB cable, many come detachable from your charger or are given to you as an accessory</li>
	<li>Your device will mount, as a disk on Windows or will open the Android File Transfer app on Mac</li>
	<li>Navigate to your SD Card (or internal storage if you don't have one), then the 'mapillary' folder. Inside this will be date-stamped folders of all your photos<br><img src="android_import_1.png" alt="Android File Transfer showing the Mapillary storage folder"></li>
	<li>Copy these to your computer. Mac only: In Android File Transfer you must drag and drop them to the save location</li>
	<li>Once it has finished copying you can disconnect it from your computer</li>
</ol>

<h3 id="install-imageoptim">Install and setup ImageOptim (Mac only)</h3>
<ol>
	<li><a href="https://imageoptim.com/ImageOptim.tbz2">Download ImageOptim</a></li>
	<li>Extract the .bz2 file with a unarchiver of choice, my preference is <a href="http://unarchiver.c3.cx/unarchiver">The Unarchiver</a></li>
	<li>Move ImageOptim.app to where you want to keep it. Recommended is /Applications/</li>
	<li>Open the app, then open ImageOptim>Preferences (Shortcut ⌘Q)</li>
	<li>In the 'General' tab, enable all the compressors on the left. If it is extremely slow, you may wish to disable some, however the photos will be compressed less.<br><img src="imageoptim_settings_1.png" alt="ImageOptim general settings page" /></li>
	<li><strong>Untick 'Strip PNG metadata' and 'Strip JPEG metadata'. Without this metadata you will not be able to upload them to Mapillary!</strong></li>
	<li>(optional - recommended) Switch to the tap 'JPEGOptim'. Here decrease the quality to 90%. I have found that this radically decreases file size with no visible decrease in quality.<br><img src="imageoptim_settings_2.png" alt="ImageOptim JPEGOptim settings page" /></li>
</ol>

<h3>Compress photos with ImageOptim (Mac only)</h3>
<ol>
	<li>Make sure you have <a href="#install-imageoptim">installed and setup</a> ImageOptim correctly for Mapillary</li>
	<li>Open ImageOptim</li>
	<li>Drag and drop your photos or folders with photos into ImageOptim, or use the '+' button and choose files<br><img src="imageoptim_1.png" alt="ImageOptim starting screen" /></li>
	<li>The images will start to compress imediately, although it may take some time</li>
	<li>When a green tick appears that photo has finished processing. You may remove photos from the list by clicking on them and pressing backspace in ImageOptim<br><img src="imageoptim_2.png" alt="ImageOptim with a photo complete" /></li>
	<li>(optional - not recommended) You may further compress images by pressing the 'Again' button, which will do a 2nd pass on the images, although this often does not save too much data, and it is faster just to upload them</li>
</ol>

<h3>Uploading photos taken with the Mapillary app</h3>
<ol>
	<li>Windows only: <a href="https://www.python.org/downloads/windows/">Install the lastest Python 2. You'll probably want the 'Windows x86 MSI Installer', and have a look at a few guides to get properly set up</a></li>
	<li>Download <a href="https://raw.githubusercontent.com/mapillary/mapillary_tools/master/python/upload.py">upload.py</a>
	<li>Open Command prompt (Windows) or Terminal (Mac)</li>
	<li>Enter the command: <code>cd {path to the script}</code></li>
	<li>Enter the command: <code>python upload.py {path to your photos}</code></li>
	<li>Wait for all your photos to upload, and then you're done!</li>
</ol>
```

**Comment by jesolem** [comment]
@travel193 take this and add to the User Guide. Close when done.

**Comment by travel193** [comment]
Hi @domdomegg ,
Thanks for all the information. Great information.
I am adding it into the wiki now. Do you have the original screen grabs for the write up?

**Comment by domdomegg** [comment]
Here:
https://drive.google.com/file/d/0B1eQ5phy9ZasSVY5RlhiRm1rYnM/view

**Comment by travel193** [comment]
Hi @domdomegg ,
Thanks heaps for those. Great write up.
You can now view it on our wiki [here](https://github.com/mapillary/UserGuide/wiki/Transferring-Files).

Cheers

**Comment by travel193** [comment]
@pyrog 
We will add capturing instructions and tips [here](https://github.com/mapillary/UserGuide/wiki/Capturing). I'll add new tips whenever I see them. Feel free to contribute also.
