### ISSUE TITLE
Attach the images to the ways of Openstreetmap

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#97]
Like Mapillary maps the world within Openstreetmap why not could exist the possibility that the system would "attach" the images of various changesets to a concrete "highway" (in Openstreetmap the codes for all the ways,streets,cicleways,railways,etc. are named with the key "highway") of Openstreetmap if both exists.Also to the concrete direction: forward,backward...

**Comment by ybkuang** [comment]
mapillary_issues is no longer an active repository.
Let’s continue discussing features in our forum! We will import this issue as topic to the Mapillary Forum in the coming weeks. We’ll notify here once it’s been done. See you there!
