### ISSUE TITLE
Uploading single images is not possible

### ISSUE THREAD

**Issue by bitnapper** [mapillary/mapillary_issues#971]
While mapping for OSM I take a lot of pictures I'd like to share. But uploading them with the web uploader merges them randomly into other sequences. Also uploading on picture at a time causes this problem.
Generally it would be nice to be able to upload plenty images which do not get merged into a sequence but be used as single images.

**Comment by jesolem** [comment]
Uploading one at a time should not group them. 

-> @knikel

**Comment by domdomegg** [comment]
> it would be nice to be able to upload plenty images which do not get merged into a sequence but be used as single images

:+1:

**Comment by knikel** [comment]
@angelday something to consider for the uploader

**Comment by angelday** [comment]
@gyllen thoughts?

**Comment by gyllen** [comment]
I say this is a case for desktop uploader.

**Comment by mschwendener** [comment]
As I understand it, this _is_ the desktop uploader: "uploading them with the web uploader merges them randomly"

**Comment by gyllen** [comment]
@mschwendener Yes a problem right now is that `one upload in the manual uploader` == `one sequence`. So single images will be connected by a line no matter how far away they are from each other in the order of capture date.

I think this is something we need to look into for the manual uploader.

**Comment by mschwendener** [comment]
move to _bug_ instead of _feature_?

**Comment by gyllen** [comment]
Well it works as intended so in our label scope considered a new feature not a bug :)

But yes it needs to bed fixed. Thanks for giving all of this feedback.

**Comment by nickplesha** [comment]
This should now be resolved.
