### ISSUE TITLE
Download a sequence

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#972]
It would be very good if we have an option to download an entire sequence by pressing a button. Please add that option to save a sequence like an album photo in the PC. Thanks.

**Comment by jesolem** [comment]
Good idea. Adding it to the list for future updates.

**Comment by yopaseopor** [comment]
But first it would interesting to be able to remake a sequence cutting or joining o make a selection. P.e. I don't want to download my 400 kms trip, i just only want to download last km.

**Comment by gyllen** [comment]
Downloads of whole sequence are now possible through mailing support@mapillary.com
