### ISSUE TITLE
Signup link accessible when user is logged in

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#975]
Hello there,

as a logged user, you can reach the [signup form](http://mapillary.com/map/signup):

![signup form logged](http://i.imgur.com/H1mfprtl.png)

The link is visible on the Mapillary Blog, on the right side panel, the button "Join the expedition".

**Comment by jesolem** [comment]
I don't think this is a problem. A logged in user would not sign up again by mistake and might want to help someone create an account. Closing.
