### ISSUE TITLE
[Android] Cannot login.

### ISSUE THREAD

**Issue by ireun** [mapillary/mapillary_issues#976]
Hello

Today I've downloaded Mapillary App from Google Play, i've tried to login, I'v typed in email and password, and than.. Nothing, there is no "login" button, "OK" on the keyboard as well does nothing.

Can i get an older .apk where loging in was working? I'm using Samsung S5, Android 5.0

**Comment by pyrog** [comment]
I had the same problem: cannot **login** but also, cannot **sign in**

**Comment by ireun** [comment]
I've downloaded .apk directly from mapillary site and... It works, not sure why but try it! ;)

**Comment by jesolem** [comment]
The button should be in the top right. Maybe a change for 5.0 that needs fixing. @peterneubauer will check.

**Comment by ireun** [comment]
I know, in the .apk downloaded from mapillary site it was there, but I've not noticed it in the version from GP.

**Comment by arno974** [comment]
Same issue on my S5.
I can log in to theweb site but not using the android app.
Same issue with the Mapillary App on the store or the apk.

**Comment by perbac** [comment]
Same issue on my Fairphone
 I can log in to the webpage but not using the Android app.
 /Per

**Comment by ireun** [comment]
@arno974 try an older .apk ;)

**Comment by peterneubauer** [comment]
Mmh,
this seems to be a problem in our API call, I'm on it.

**Comment by perbac** [comment]
Is it possible to say anything about timeschedule for the fix of this bug? 
Now I have tested both on my Fairphone and a Samsung and the result is the same.

**Comment by peterneubauer** [comment]
Have you tried the new v1.24 on Play? I tested login, should work.

**Comment by perbac** [comment]
Unfortunately yes.
When trying to login there sometimes is a blink of a text saying something about Java. Could that be an issue?

**Comment by peterneubauer** [comment]
Is that on all your phones or just the Fariphone?

**Comment by perbac** [comment]
Just tested on the Fairphone so far.

**Comment by perbac** [comment]
Now I have tested on one Samsung S2 and one Samsung S4. It did not work on neither of them. On the S4 there was a blink saying something like "...page is full..".

**Comment by peterneubauer** [comment]
I'm using this version on my phone (Sony Xperia) and got feedback from
others being able to run without problems. Would like to test a fair
phone...

**Comment by perbac** [comment]
Believe you are not in my neighborhood? I´m in Nyköping, Sweden.

**Comment by peterneubauer** [comment]
Mmh you can log in via Web?

**Comment by perbac** [comment]
Yes, that works and on the Samsung S4 I now get a message saying "..error 504..".

**Comment by peterneubauer** [comment]
Got a Screenshot?

**Comment by de-vries** [comment]
>I can log in to the webpage but not using the Android app.

I can confirm this behavior for the fairphone. totally nothing happens when I give my email address and password.
(now I feel stupid for testing this, as I now cannot use the app anymore :( )

**Comment by perbac** [comment]
Sorry no screenshot. With the next test there was no errormessage on any of the phones.

**Comment by peterneubauer** [comment]
I can recreate it here, on it...

**Comment by de-vries** [comment]
also tied 1.16, same problem

**Comment by peterneubauer** [comment]
I suspect a backend bug. We investigate in 1h.

**Comment by ireun** [comment]
Same here, on S5. Login in button now shows up, but nothing happens after clicking it.

**Comment by peterneubauer** [comment]
Yup,
this is a backend failure. Going to notify here when it's up again.

**Comment by peterneubauer** [comment]
Things are operational again. can you please try?

**Comment by perbac** [comment]
Yes!! 
After work it will be a tour on some interesting roads.
Thanks!

**Comment by de-vries** [comment]
nope

**Comment by peterneubauer** [comment]
Good good.
