### ISSUE TITLE
Traffic sign game down

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#978]
There is a "blank" page without image and leaderboard.

Some ressources are missing (see javascript console):
* [Error] XMLHttpRequest cannot load https://a.mapillary.com/v2/search/im/or/random?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&package=trafficsign_eu_1.0. Origin http://www.mapillary.com is not allowed by Access-Control-Allow-Origin. (traffic, line 0)
* [Error] XMLHttpRequest cannot load https://a.mapillary.com/v2/stats/im/or?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh&package=trafficsign_eu_1.0. Origin http://www.mapillary.com is not allowed by Access-Control-Allow-Origin. (traffic, line 0)
* [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)

**Comment by pyrog** [comment]
Tested few minutes after, the image pane and the leaderboard appeared.
But there is a spinner and some javascript errors

**Comment by ireun** [comment]
I think so, image processing now takes.. longer than it usually took. Also https://www.mapillary.com/map/feed takes ages to load.

**Comment by jesolem** [comment]
We have been a bit overloaded these last few days due to lots of uploads and upgrades we're making. It should improve in a few days. 

We should look at the JS errors.
