### ISSUE TITLE
I can see comments in the activity list, but I can't see who it is from or which image was commented on.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#979]
In the activity list on the website I can see the following:

a day ago  Thailand
[username] got 1 comment on image
[comment]

I can't see which image was commented on, or who made the comment.

This also seems to be true for the Android application.

**Comment by AllenGraetz** [comment]
I've had that problem via chrome on the desktop, too.  

If we had a conversations / comments section, that would make for an easy work around.

**Comment by gyllen** [comment]
Yes this is a known issuse. I think at the moment you have to click the country name to see the image. @knikel the UX is not very clear here.

**Comment by knikel** [comment]
Closing this, since the feed will have totally different form soon.
