### ISSUE TITLE
[idea] Implement priority regions for photo processing

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#983]
Make the first step in processing uploaded photo's a check for if the photo's are in a certain (variable) area, country or BBox. And if they are prioritize processing them above everything else. You can use this to help HOTOSM projects like Nepal and future humanitarian projects, but also for promotional reasons, like when you are throwing a mapping-party or something.

**Comment by filipca** [comment]
I vote for this.

**Comment by gyllen** [comment]
Our end goal is to make processing fast for all places. It should never take longer than 15 m from upload to map. Closing since faster processing is on the way
