### ISSUE TITLE
Limit access to user activy

### ISSUE THREAD

**Issue by Jibec** [mapillary/mapillary_issues#986]
hi,

I'm found of Mapillary, but I don't want to have everyone knowing where I was and what pictures I've done.
I'd like to have the ability to hide tabs "uploads", "activity" and "connection" to other people than myself.

I know that my username will still be available on each picture, but it will make it harder for people to know my journeys.

Is that feasible ?

**Comment by de-vries** [comment]
You should also do something about the gpx downloads. It's quite easy to download all gpx files from someones user page and load them in some gpx-viewer.

It took me two minutes to make this image:
![selectie_054](https://cloud.githubusercontent.com/assets/1449609/7489712/08afb998-f3da-11e4-9e02-9240df91a446.png)
Now you guess which Mapillary team members travel pattern you're looking at ;)  

I don't see any (honorable) use for the option to download all gpx files from a single user. Imo it would be better to offer a option to download all gpx in a certain area.

**Comment by jesolem** [comment]
@Jibec Good suggestion. You mean like a setting for the profile page that hides the listings there and just shows your profile information? I like that. 

Assigning to @knikel to work something out in the upcoming remake of the profile page. 

@de-vries I'm honored ;) Point taken.

**Comment by de-vries** [comment]
Also: there is the limitation that you can only download gpx files when logged-in, but that's no real limitation since the links are only hidden and still source code.

**Comment by Jibec** [comment]
@jesolem yes, it's what I thought. It's just to limit eventual "stalking" (maybe the word is too hard) not to fight secret services ;)

**Comment by shlublu** [comment]
I couldn't agree more with this request. This is also a concern that prevents me from contributing as much as I would like to.

**Comment by jesolem** [comment]
We're on it.

**Comment by jesolem** [comment]
Let's do this then:

1) add a toggle in Settings for `Hide activity on my profile view`.

2) If toggle is set, we show `@username has hidden the activity summary`. (or similar)

Should hide the upload feed and the toggle for map filter (in today's design). 
![profile-hide](https://cloud.githubusercontent.com/assets/136751/17167962/14293dbe-53e0-11e6-9388-d4462ab28014.png)

**Comment by gyllen** [comment]
The way our system is now setup this is not possible. To achieve anonymity you can chose to upload through an Organization.
