### ISSUE TITLE
[idea] (private) Videos in processing counter

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#987]
After submitting a lot of videos (and I still have more videos to submit), I notice that it takes quite some time before they have been processed and sequences appear on the **upload** tab. It would be nice for my own control to have a counter of what videos are still being processed, and maybe when overing the mouse over the number, or a different tab, see the file names of the videos in process queue. This information I think is only interesting for each user, i.e. I would like to see my video process queue, but have no interest of knowing about other users queue.

As it is now I have no real idea how many videos are still in queue to be processed. I see that there are several videos I have uploaded that are still not processed, and currently there is no way of telling what is still in the queue. With the long process time it is therefor difficult to estimate if submitting a video actually was successful.

After now waiting a few days without more videos appearing I start fearing that some of the videos I have submitted have dropped into void. Since I had to delete the vids for disc-space I risk that these are gone forever...

**Comment by gyllen** [comment]
@Skippern Im sure the videos are not lost. @knikel we have this data in the API any way we can show it on the web?

**Comment by Skippern** [comment]
@gyllen I would think that at least those videos where I got a "complete" status when uploading are with you in some way.

**Comment by gyllen** [comment]
@Skippern Yes I just checked, you have alot of none parsed videos. Just triggered a manual video processing in the system. Expect things to start showing up soon.

**Comment by Skippern** [comment]
Thanks @gyllen

I have another 25GB pre-processed (trimmed) ready to upload, but won't be able to send anything in that direction for the next 2 months due to bandwidth restrictions. I am currently looking for ways to convert them into geo-referenced image sequences, as I might be able to pass that over time, but haven't found any usable solutions yet.

Hope to see my sequences show up soon

**Comment by Skippern** [comment]
![24hrs](https://cloud.githubusercontent.com/assets/802652/7506148/8b0d0956-f432-11e4-9de6-ce95c1f0778c.png)
24hrs later, I am shocked. It's like a blocked pipeline just getting flow again.
