### ISSUE TITLE
How much data for 3D

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#988]
I am wondering how much/many data/pictures Mapillary needs for the different 3D and positioning possbilities mentioned in the November blog post. I assume 1 picture doesn't work at all, but to make any kind of use, is it 10 or 1000 pictures of a building/place?

Also, will the system learn to use pictures of a building taken from very different distances, lets say 30 and 1000 meters?

http://blog.mapillary.com/update/2014/11/14/opensfm.html

**Comment by ybkuang** [comment]
@Andblue The approach we are using requires at least 2 images of the same object (e.g. a  building) from different view points (a baseline between the two images is also needed). On the other hand, the more images we have, the more details we will potentially be able to compute in the 3D reconstruction. 

For images taken from different distances, the system will try to match the visually similar parts presenting in them and utilize that for reconstruction.

**Comment by Andblue** [comment]
Follow up question:

Will the system also learn to position pictures on the map? Making sequences in the city with a regular mobile phone is difficult, the GPS precision is low. If there is a sequence in each direction, will that help to position further sequences?

**Comment by ybkuang** [comment]
@Andblue Yes. Once we have the reconstruction, we can try to position the images better on the map given the rough GPS prior recorded on the phones. That is actually one of the goals we would like to achieve with 3D reconstruction.
