### ISSUE TITLE
[Android] - version 1.23 - camera crash all the time

### ISSUE THREAD

**Issue by Neogeografen** [mapillary/mapillary_issues#989]
The new version 1.23 (from May 4th) crash when turning on camera - camera is on for 2-3 seconds - then app stops. Have tried to uninstalled and then install app

 Version 1.2.0 did never crash in camera mode.

Anyway to downgrade to 1.2.0?

Using Andriod 4.2.2

NB - bug report via app has been sent

**Comment by peterneubauer** [comment]
Yes, 
that's a bug, I'm right now pushing an update - it occurs for Android < SDK version 18. Sorry for that, fix coming.

**Comment by peterneubauer** [comment]
try out https://www.dropbox.com/s/7lyd1y4lb6vkg02/app-release_124.apk?dl=0 and report back.

**Comment by peterneubauer** [comment]
Also, version pushed to Play, check in a couple of hours.

**Comment by Neogeografen** [comment]
I have now downloaded 1.24 from Play and it's working fine again - Thanks for fixing so fast.

**Comment by peterneubauer** [comment]
Awesome, sorry for the inconvenience!
