### ISSUE TITLE
Photo set displayed on front page to small

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#990]
The set of photos displayed on front page is to small. I quite often see the same photo as before, which shouldn't happen if - and contradicts that - you have nearly 15.000.000 photos to chose from. 

Since it's probably to much to ask for a beauty detecting algorithm, the next best thing to do is crowd coursing it. Please give us more options assess photos.

**Comment by jesolem** [comment]
The photos on the front page are from "starred" sequences. Right now we do the starring but will open that up or find a more open solution later on. We will add something.

**Comment by de-vries** [comment]
>  find a more open solution

Is #992 something?

**Comment by jesolem** [comment]
closing this

And yes, I'm a fan of #hashtags as in #992
