### ISSUE TITLE
Change sets partially accepted

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#991]
The whole process of change sets that need to be accepted is very obscure. Sometimes it only takes 2 hours for a change set to be approved, other times it takes several days. There is no indication on the website if a sequence is part of a change set that is awaiting approval. The email confirmation that a change set has been received does not include any information about the change set, or a link to the changed sequences. It looks also like I'm not getting confirmation emails for every change set, even though they may later be approved.

But now I see a new problem: partially accepted change sets. In specific, it involves the change set http://www.mapillary.com/map/cs/To6J6IH7U_WyBxLtsMla-w. I've been reorganizing my photos, but I see that for example the changes in the sequence part between http://www.mapillary.com/map/im/NxBP33ZVeQHQGom4Rznl3A and http://www.mapillary.com/map/im/NuL3Qv9-i9X9b8I_vsMF0w have not come through. (Some) other changes in the same sequence did go through.

Because of the obscurity of the whole process, it's impossible for me to see what the reason for this is:
- Maybe some of the edits were simply not approved. (Why would that be?)
- Maybe bugs in the process mean that some of the change requests were not processed/uploaded, even though they showed up on the map while editing.
- Maybe the edits conflict with another edit I or someone else did before or after that.
- Maybe approval happens in batches that can include parts of changesets.

**Comment by pbb72** [comment]
Another example: in change set http://www.mapillary.com/map/cs/wn7UfD4MCZw142z5H86SlQ, originally I had also moved the sequence part from http://www.mapillary.com/map/im/sdWk1ZRhl7tZ2VffX4ESyQ to http://www.mapillary.com/map/im/9_-v9O7DiEQoeNTMBdQXEw.  The rest of the change set has been accepted, but not these.

**Comment by HolgerJeromin** [comment]
In the following changesets i requested changing angles (at -45 degree relative to the movement) for all images. Only a few were accepted:
http://www.mapillary.com/map/cs/Vc4HNQB3bM9K909YHnHZbg
http://www.mapillary.com/map/cs/t8vDgMmHuPX7DwJkznFHkg
http://www.mapillary.com/map/cs/n_TzFttGPQJHZ2JUlAXSSw
http://www.mapillary.com/map/cs/M5bdb3p51fJiOMcEDfa8hA

**Comment by HolgerJeromin** [comment]
perhaps not all images were processed. But they were visible in the editor, so this should work :)

**Comment by de-vries** [comment]
bump:

http://www.mapillary.com/map/cs/aXPu7_qoAzxMXdXHDo3Dzw
http://www.mapillary.com/map/cs/LkeTXKprEwE93QnqtEU9ZA
http://www.mapillary.com/map/cs/n_a8PZHKM7ZZVGMl-KVO1w

**Comment by gyllen** [comment]
Fixed in new editor (and new changeset backend)
