### ISSUE TITLE
[Idea] Add possibility for #custom tags

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#992]
It would be useful is there was a possibility to add custom tags to photos and sequences. 

Because custom tags:
- would make for the most flexible feedback system.
- would be a good source for filters.
- can be used for assessing photo quality. eg: #blurry or #overexposed.
- can be used for marking beautiful photos. eg: #best_of_Mapillary.
- can be used to mark photos taken during some event. eg: #festival_whatever.
- give the option to get really creative. eg: #walking the dog
- can be used to indicate the weather.
- can be used to mark photos as not representative. eg: #roadworks 
- can be used for marking photos that are useful in some osm project. eg: #HOTOSM_Nepal
- can be used to mark photos taken by drones. eg: #airial. (see #352)

Tagging could be done as hash-tags in the comments, or maybe in a separate field. However it's done, it would be nice if the following features were possible: to display them without showing all the comments and getting suggestions when typing them.

**Comment by jesolem** [comment]
Yup, #hashtags is high on my list too. It's on our future feature list.

**Comment by jrcarlsen** [comment]
I would appreciate the tags as well, I use the photos for mapping on OSM - and it would be useful for me for different purposes.

Lets say we have a long road in Thailand, and we are trying to figure out how much of this road have a specific reference number, by adding tags like this "#th:highway:ref:1317" on all photos with a sign saying "1317", we could later quickly find all these signs and come to a conclusion.

Same goes for village signs. By tagging all the sign that go into a village, we should later be able to figure where the actual village is.

This tags could also be used in OSM for source tags, e.g.:
source=http://www.mapillary.com/map/tag/th:highway:ref:1317

The format of the tag is just an example, there might be much better ways of doing this tagging.

**Comment by jesolem** [comment]
We added support for tagging in MapillaryJS and will soon get that viewer onto mapillary.com, then hook up tagging for all.

**Comment by jesolem** [comment]
Closing as we now shipped tagging both for image and object in images.
