### ISSUE TITLE
un-blur recognised signs

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#993]
I would like to see recognised signs un-blurred, currently there are a number of signs which are blurred. Recognising, correcting, and even using the sign data for anything is complicated when the sign surface (text/pictogram) are blurred. I see this mainly in US signs with text in them, but also in some with pictogram. I don't know if this also applies to EU signs as I haven't done much editing/contributions with those.

**Comment by de-vries** [comment]
duplicate of #635

**Comment by domdomegg** [comment]
Bumping this to be closed. As de-vries said, it is a duplicate
