### ISSUE TITLE
(NaN% uploaded)

### ISSUE THREAD

**Issue by Fod90** [mapillary/mapillary_issues#994]
During batch upload using browser, progress status changes to "(NaN% uploaded)".

![image](https://cloud.githubusercontent.com/assets/12325592/7536189/f878c924-f58d-11e4-9571-ec3536822a2a.png)

Does this mean 100% - or is upload still in progress?

Browser version is "Google Chrome 42.0.2311.135"

[Update 2015-05-08 13:32 UTC]:
It seems that if 
![image](https://cloud.githubusercontent.com/assets/12325592/7537232/6d6dfa16-f597-11e4-8dd1-ee0e82e3a70c.png)
is pressed when "(NaN% uploaded)" is shown, not all (sometimes even no) pictures in the queue have been uploaded.

-- 
Jakob

**Comment by AllenGraetz** [comment]
I have gotten this when my wifi connection goes down.  I'm assuming the client-side javascript is trying to grab some data from the server, can't get to it and instead of returning an error message like "connection has been lost" it still tries to do the percentage calculation, has a null and thus displays the NaN%.

**Comment by Fod90** [comment]
The issue is persistent; apart from very small series, I have not been able to upload an entire series yet without encountering the "(NaN% uploaded)" status somewhere along the upload.

My series are quite large (>1GB), and and have tried uploading from different locations (mostly private connections with modest 1 - 5 Mb/s upload bandwidth).

**Comment by Fod90** [comment]
@AllenGraetz: I also think that the "(NaN% uploaded)" status is a symptom of "lost connection". I am on wired internet, so WiFi is not a possible issue here.

Currently, I suspect the client-side upload script to have stability issues - for example, if an upload stalls, this will result in status "(NaN% uploaded)" rather than a restart/resume of the upload.

**Comment by pyrog** [comment]
Got this when my laptop goes in sleep mode.

```
[Error] Failed to load resource: La connexion réseau a été perdue. (mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com, line 0)
[Error] Failed to load resource: Aucun serveur ayant le nom d’hôte précisé n’a pas pu être trouvé. (mapillary.uploads.manual.images.s3-eu-west-1.amazonaws.com, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
```

**Comment by knikel** [comment]
Uploader is getting a serious update in the upcoming release of mapillary.com. Will close this issue when rolled out.
