### ISSUE TITLE
Firefox rendering problem if image has not been processed yet

### ISSUE THREAD

**Issue by Nakaner** [mapillary/mapillary_issues#996]
If an image has not been processed yet (i.e. labelled with "This image hasn’t finished processing yet! It will look better soon, promise.") the first letter of the contributor's nickname is not visible on small notebook displays.

My display is 1366x768 px, Firefox 37.0.2, Arch Linux, XFCE. The Firefox windows (see attached screenshot is 738 px high).

The problem does not occur if I view the page at fullscreen mode (F11 key).

The problem does not occur if the image processing has been finished.
![akaner](https://cloud.githubusercontent.com/assets/3611273/7551547/9745cec2-f68c-11e4-9d86-58ad6afe1c1c.png)

**Comment by knikel** [comment]
We've changed the layout a lot, not an issue anymore :+1:
