### ISSUE TITLE
Microsoft Phone App sucks, sorry

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#997]
The pictures of my cheap chinese phone were too bad, so I get a lumia 920. The windows app is different, will there be an update in near future? Primarily "pause on stop" is missing!

**Comment by wegavision** [comment]
I made some experience with the Lumia and mapillary but the pictures are too bad. I do not know why. 
Here an example, the first picture with the microsoft cam and the other with the app (standing).
![parade1](https://cloud.githubusercontent.com/assets/12095741/7555850/81337a44-f759-11e4-897b-2a168e91e38f.jpg)
![parade2](https://cloud.githubusercontent.com/assets/12095741/7555848/710ca690-f759-11e4-9525-3334f73f637d.jpg)

**Comment by pbb72** [comment]
Looks to me like the Mapillary photo (the bottom one) is out of focus. Shutter time, ISO setting, etc is all roughly the same. The Android Mapillary app has a focus setting, does the Microsoft one also have that?

**Comment by wegavision** [comment]
I seems to be a Lumia problem, infinity focus is blurry:
http://forums.windowscentral.com/nokia-lumia-1020/281366-why-infinity-focus-blurry.html
This should be fixed with the last firmware, but it isn't.

**Comment by jesolem** [comment]
Is the issue still there for version 1.1 (released a week ago)?

If so, since we now open sourced the WP app, you can file issues directly at https://github.com/mapillary/mapillary_windows_phone/
