### ISSUE TITLE
Traffic sign game : can't play game !

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#999]
![spinner on saving](https://cloud.githubusercontent.com/assets/2158081/7553094/5edfc462-f6e0-11e4-857f-88960931a2ee.png)

On page load:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

On saving changes:
`[Error] XMLHttpRequest cannot load https://a.mapillary.com/v2/im/PPCDfcoJ1UzaSyuKV0lx1w/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. Origin http://www.mapillary.com is not allowed by Access-Control-Allow-Origin. (PPCDfcoJ1UzaSyuKV0lx1w, line 0)`

See also #998

**Comment by ireun** [comment]
Safe thing happens whil trying to edit traffic signs on the map view.

**Comment by domdomegg** [comment]
Same. Strangely fine when approving, just hangs on editing.

**Comment by pyrog** [comment]
Try to add a traffic sign there : [o4NvNe7RZZoMShjxzSsbFg](http://www.mapillary.com/map/im/o4NvNe7RZZoMShjxzSsbFg)

Got theses errors in javascript console:

```
[Error] XMLHttpRequest cannot load https://a.mapillary.com/v1/pa/search?limit=1000&max-lat=37&max-lon=-5&min-lat=36&min-lon=-6&page=0. Origin http://www.mapillary.com is not allowed by Access-
Control-Allow-Origin. (o4NvNe7RZZoMShjxzSsbFg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
[Error] XMLHttpRequest cannot load https://a.mapillary.com/v2/im/o4NvNe7RZZoMShjxzSsbFg/or/version?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh. Origin http://www.mapillary.com is not allowed by Access-Control-Allow-Origin. (o4NvNe7RZZoMShjxzSsbFg, line 0)
```

**Comment by ybkuang** [comment]
We have been working on scaling up our database/processing recently. There are glitches when writing to database. We are working on it. Sorry for this.

**Comment by gyllen** [comment]
fixed

**Comment by pyrog** [comment]
Thank you very much :smile:
